@class AWEModalTransitionDelegate, ACCMusicVolumeViewModel, ACCPanelViewController, ACCImageAlbumAudioPlayer, NSString, ACCMusicPickerViewController, ACCMusicPickerViewModel;
@protocol ACCMusicRecommendListRepositoryProtocol, DVECoreDraftServiceProtocol, DVEEditingContextProtocol, DVETrackEventProtocol, DVECoreActionServiceProtocol, DVEPlayerServiceProtocol, DVECoreAudioProtocol, ACCStudioPerfUtilServiceProtocol, ACCAdvanceEditViewModelProtocol, ACCAdvanceEditPageService, ACCEditMusicServiceProtocol, ACCAdvanceActionDispatchProtocol, ACCMusicModelProtocol, DVERootViewControllerProtocol, ACCEditTransitionServiceProtocol, DVEEditingRuntimeProtocol, ACCAELiveDraftViewModelProtocol, DVEMulitpleTrackViewServiceProtocol;

@interface ACCAEMusicSelectComponent : ACCAdvanceEditComponent <ACCMusicListBizHandler, ACCMusicPickerViewControllerPresenter, ACCMusicPickerViewControllerDelegate, ACCPanelViewDelegate>

@property (weak, nonatomic) id<ACCAdvanceEditViewModelProtocol> viewModel;
@property (weak, nonatomic) id<ACCAELiveDraftViewModelProtocol> liveDraftViewModel;
@property (weak, nonatomic) id<ACCAdvanceActionDispatchProtocol> actionDispatch;
@property (weak, nonatomic) id<DVERootViewControllerProtocol> root;
@property (weak, nonatomic) id<DVEEditingRuntimeProtocol> mediaContext;
@property (weak, nonatomic) id<DVEPlayerServiceProtocol> playerService;
@property (weak, nonatomic) id<DVECoreAudioProtocol> audioEditor;
@property (weak, nonatomic) id<DVECoreActionServiceProtocol> actionService;
@property (weak, nonatomic) id<ACCEditTransitionServiceProtocol> transitionService;
@property (retain, nonatomic) AWEModalTransitionDelegate *transitionDelegateForAlbum;
@property (weak, nonatomic) id<DVEMulitpleTrackViewServiceProtocol> multipleTrackViewService;
@property (weak, nonatomic) id<DVETrackEventProtocol> trackManager;
@property (weak, nonatomic) id<DVECoreDraftServiceProtocol> draftService;
@property (weak, nonatomic) id<ACCAdvanceEditPageService> pageService;
@property (weak, nonatomic) id<ACCStudioPerfUtilServiceProtocol> perfService;
@property (weak, nonatomic) id<DVEEditingContextProtocol> editingContext;
@property (weak, nonatomic) id<ACCEditMusicServiceProtocol> musicService;
@property (nonatomic) double showMusicPanelTime;
@property (retain, nonatomic) ACCMusicPickerViewModel *musicPickerViewModel;
@property (retain, nonatomic) ACCMusicPickerViewController *musicPickerController;
@property (retain, nonatomic) id<ACCMusicRecommendListRepositoryProtocol> recommendListRepository;
@property (retain, nonatomic) ACCMusicVolumeViewModel *volumeViewModel;
@property (retain, nonatomic) ACCPanelViewController *panelViewController;
@property (retain, nonatomic) ACCImageAlbumAudioPlayer *audioPlayer;
@property (nonatomic) BOOL shouldPlaceTheSelectedMusicFirst;
@property (nonatomic) BOOL openMusicForReplace;
@property (retain, nonatomic) id<ACCMusicModelProtocol> selectedMusic;
@property (retain, nonatomic) id<ACCMusicModelProtocol> deletedMusic;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)componentWillAppear;
- (void)componentWillDisappear;
- (void)panelViewController:(id)a0 willShowPanelView:(id)a1;
- (void)panelViewController:(id)a0 willDismissPanelView:(id)a1;
- (void)musicListSelectMusicPlayable:(id)a0 withUrl:(id)a1;
- (void)musicListSelectMusicDownloaded:(id)a0 withUrl:(id)a1;
- (id)publishModel;
- (void)componentDidMount;
- (void)setupObserver;
- (BOOL)musicListShouldEnableClipForMusic:(id)a0;
- (BOOL)musicListShouldEnableTriggerApplyForMusic:(id)a0;
- (void)musicListDeselectMusic:(id)a0;
- (BOOL)playerTypeIsAudioPlayer;
- (void)musicListClipMusic:(id)a0;
- (void)musicListTriggerApplyMusic:(id)a0;
- (BOOL)enablePreloadNearbyMusicResource;
- (id)nearbyMusicResourcePreloadStrategy;
- (void)syncDataOnWillTransitionIn;
- (void)syncDataOnSaveWithPublishModel:(id)a0;
- (void)syncDataForLiveDraftWithPublishModel:(id)a0;
- (void)componentFirstFrameDidRender;
- (void)trackEventAddAudio;
- (void)trackDuration:(double)a0 event:(id)a1;
- (id)dataSyncer;
- (void)setupAudioPlayer;
- (void)preloadMusicPanelRecommendListIfNeeded;
- (void)syncDataWithPublishModel:(id)a0 forLiveDraft:(BOOL)a1;
- (id)musicWithId:(id)a0 jsonString:(id)a1 relativePath:(id)a2;
- (void)trackEventReplaceAudioWithSlot:(id)a0;
- (void)dismissMusicPicker;
- (void)doApplyMusic:(id)a0 clippedRange:(struct _HTSAudioRange { double x0; double x1; })a1 isReplace:(BOOL)a2;
- (void)doTrackAddAudioEventWithMusic:(id)a0 resultCode:(unsigned long long)a1 error:(id)a2;
- (void)showMusicSearch;
- (BOOL)musicListShouldPlaceTheSelectedMusicFirst;
- (id)viewControllerPresentMusicPicker:(id)a0;
- (id)panelViewControllerPresentMusicPicker:(id)a0;
- (void)picker:(id)a0 didFinishPickingMusic:(id)a1;
- (void)pickerShowMusicSearch:(id)a0;
- (void).cxx_destruct;
- (void)showMusicPicker;

@end
