@class NSDictionary, ACCEditBeautyEffectCompareButton, ACCBeautifulEffectPanelComponentRepositoryWorker, ACCEditBeautyEffectVCContext, UILabel, ACCEditBeautyVideoControlBar, NSString, ACCEditBeautyEffectContentItemViewController, ACCBeautifulEffectPanelComponentAlertWorker, NSArray, NSMutableDictionary, ACCEditBeautyEffectPanelView, ACCEffectCommandActionManager, ACCEditBeautyEffectDownloadService, ACCBeautifulEffectPanelComponentResetWorker, UIView, ACCEditBeautyEffectSlider, ACCEditBeautyEffectCompontentViewModel, ACCEditBeautyEffectNavigationController, ACCSecondaryPageInnerTransitionManager, ACCEditBeautyPlayerSliderProgressView, ACCBeautifulEffectActionModel;
@protocol AEKMegaEditor;

@interface ACCBeautifulEffectPanelComponent : ACCSecondaryPageComponent <ACCEditBeautyEffectSliderDelegate, ACCEditBeautyEffectVCContextDelegation, ACCEditBeautyEffectVCContextSubscriberProtocol, ACCEditBeautyVideoControlBarDelegate, ACCEditBeautyPlayerSliderProgressViewListener, ACCEditPreviewMessageProtocol>

@property (retain, nonatomic) ACCSecondaryPageInnerTransitionManager *transitionManager;
@property (retain, nonatomic) UIView *containerView;
@property (retain, nonatomic) UIView *sliderContainerView;
@property (retain, nonatomic) UIView *playControlContainerView;
@property (retain, nonatomic) ACCEditBeautyEffectCompareButton *compareButton;
@property (retain, nonatomic) ACCEditBeautyEffectPanelView *panelView;
@property (retain, nonatomic) ACCEditBeautyEffectContentItemViewController *itemVC;
@property (retain, nonatomic) ACCEditBeautyEffectNavigationController *navController;
@property (retain, nonatomic) ACCEditBeautyEffectSlider *slider;
@property (retain, nonatomic) ACCEditBeautyVideoControlBar *videoControlBar;
@property (retain, nonatomic) UILabel *playerSliderCurrentProgressLabel;
@property (retain, nonatomic) UILabel *playerSliderProgressSplinelineLabel;
@property (retain, nonatomic) UILabel *playerSliderTotalProgressLabel;
@property (retain, nonatomic) ACCEditBeautyPlayerSliderProgressView *playerSliderProgressView;
@property (retain, nonatomic) ACCEditBeautyEffectCompontentViewModel *viewModel;
@property (retain, nonatomic) ACCEditBeautyEffectDownloadService *beautyEffectDownloadService;
@property (retain, nonatomic) ACCEditBeautyEffectVCContext *effectContext;
@property (retain, nonatomic) ACCEffectCommandActionManager *commandActionService;
@property (retain, nonatomic) ACCBeautifulEffectActionModel *needUpdateBeautifulEffectNormalActionModel;
@property (retain, nonatomic) ACCBeautifulEffectPanelComponentAlertWorker *alertWorker;
@property (retain, nonatomic) ACCBeautifulEffectPanelComponentResetWorker *resetWorker;
@property (retain, nonatomic) ACCBeautifulEffectPanelComponentRepositoryWorker *repositoryWorker;
@property (retain, nonatomic) id<AEKMegaEditor> megaEditor;
@property (copy, nonatomic) NSString *styleNodeId;
@property (copy, nonatomic) NSString *repositoryUUID;
@property (retain, nonatomic) NSDictionary *styleExtraCellModelsNodeIdInfo;
@property (retain, nonatomic) NSMutableDictionary *preSliderValueInfo;
@property (retain, nonatomic) NSMutableDictionary *styleSliderValueInfo;
@property (retain, nonatomic) NSMutableDictionary *resourceInfo;
@property (retain, nonatomic) NSArray *faceAreas;
@property (nonatomic) BOOL isNeedRetryDetectFaceStatus;
@property (nonatomic) BOOL isNeedShowHasNoFaceToastStatus;
@property (nonatomic) BOOL indicatorViewHiddenStatus;
@property (nonatomic) BOOL isFirstUpdateVideoControlStatus;
@property (nonatomic) BOOL isCurrentVideoPlayingStatus;
@property (nonatomic) BOOL isShowUnDetectToastStatus;
@property (nonatomic) BOOL isDisableDoBeautyActionShowToastStatus;
@property (nonatomic) BOOL isPreviewRecoveryBoundsStatus;
@property (nonatomic) BOOL isPreviewUpdateBoundsStatus;
@property (nonatomic) BOOL isDismissBeautyEidtPageStatus;
@property (nonatomic) BOOL isCurrentUpdateSliderStatus;
@property (nonatomic) double lastPlayTimeValue;
@property (nonatomic) long long beautifyStyleConfirmToastShowToastType;
@property (nonatomic) double sliderStartTime;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (double)panelHeight;
- (void)componentDidAppear;
- (void)playerCurrentPlayTimeChanged:(double)a0;
- (void)loadComponentView;
- (void)componentDidMount;
- (void)playStatusChanged:(long long)a0;
- (void)hideToast;
- (void)bindObserve;
- (double)sliderHeight;
- (void)bindServices:(id)a0;
- (void)showAlertWithTitle:(id)a0 content:(id)a1 actionButtonTitle:(id)a2 cancelButtonTitle:(id)a3 actionBlock:(id /* block */)a4 cancelBlock:(id /* block */)a5;
- (void)showToastAndStore:(id)a0;
- (void)saveDraftIfNeeded;
- (id)p_generateBaseParamsDictWithPublishModel:(id)a0;
- (double)subViewHeight;
- (id)subViewInHierarchy;
- (unsigned long long)secondaryPageComponentType;
- (void)detectFace;
- (void)disableDoBeautyAction;
- (void)retryDetectFaceIfNeeded;
- (void)videoControlDidPause;
- (void)resetDisappearUI;
- (void)prepareRepositoryInfoIfNeeded;
- (void)prepareEffectIfNeeded;
- (void)prepareMegaEditor;
- (void)prepareResetItemApplyStatus;
- (void)prepareEffectFromDraft;
- (void)prepareLastEffect;
- (void)hideSlider;
- (void)resumeEffectDraft;
- (id)lastActionModelsWithKey:(id)a0;
- (void)prepareLastEffectIfNeededWithActionModel:(id)a0;
- (void)updateStyleMoreItemApplyStatus:(id)a0;
- (void)enableDoBeautyAction;
- (void)configPanelViewIfNeeded;
- (void)hasNotDetectFace;
- (void)hasDetectFaceWithFaceAreas:(id)a0;
- (void)bindObserveDelegateOrSubscriber;
- (void)bindObserveNavAction;
- (void)bindObserveFuncationAction;
- (void)trackCancelToastClickParamsWithType:(id)a0 isCancelStatus:(BOOL)a1;
- (void)trackExitBeautifyPanelParamsWithExitCancelStatus:(BOOL)a0;
- (void)didSelectResetConfirmActionWithUseCacheEffectStatus:(BOOL)a0;
- (void)didClickSaveConfirmActionStatus;
- (void)dissmissAction;
- (BOOL)isChangeStatus;
- (void)trackCancelOrResetToastShowParamsWithType:(id)a0;
- (void)didSelectOffNodeResetNormalEffectActionWithTitle:(id)a0 content:(id)a1;
- (BOOL)hasOnlyOriginStyleStatus;
- (void)didSelectOffNodeResetStyleEffectActionWithTitle:(id)a0 content:(id)a1;
- (void)didSelectOffNodeResetStyleEffectAction;
- (void)didSelectStyleEffectHasOtherStyleItemActionWithNodeId:(id)a0 styleExtraCellModelsNodeIdInfo:(id)a1 completeHandler:(id /* block */)a2;
- (BOOL)hasOriginStyleStatus;
- (id)beautyEditorWithMegaData:(id)a0;
- (float)convertRealValue:(float)a0;
- (BOOL)didSelectStyleEffectItemSelfStatusWithNodeId:(id)a0;
- (void)didSelectStyleEffectItemOtherActionWithNodeId:(id)a0 styleExtraCellModelsNodeIdInfo:(id)a1 completeHandler:(id /* block */)a2;
- (id)applyAllNodeId;
- (void)didSelectStyleEffectItemActionWithNodeId:(id)a0 styleExtraCellModelsNodeIdInfo:(id)a1 completeHandler:(id /* block */)a2;
- (void)showAlertDialogWithTitle:(id)a0 content:(id)a1 confirmCompleteHandler:(id /* block */)a2 cancelCompleteHandlder:(id /* block */)a3;
- (id)applyAllActionModels;
- (void)resetApplyEffectValueAndStatusWithExcludeNodeId:(id)a0 isNeedResetStyleNodeToDefaultRealValueStatus:(BOOL)a1;
- (void)megaRemoveAllEffects;
- (long long)effectCurrentValueWithItemModel:(id)a0;
- (id)trackParamsAppendLastNodeEditInfoWithParams:(id)a0;
- (id)trackParamsEditBeautifulInfoWithParams:(id)a0;
- (id)applyAllNodeIdDiffStyleNode;
- (id)styleExtraNodeIds;
- (id)diffStyleExtraNodeIds:(id)a0 targetNodeIds:(id)a1;
- (id)diffNodesValueInfoWithNodeIds:(id)a0;
- (void)didSelectResetLastEffectIfNeeded;
- (void)applyDiffEffectWithNodeIds:(id)a0 valueInfo:(id)a1;
- (void)resetApplyStyleEffect;
- (void)resetApplyEffectValueAndStatus;
- (void)syncRefreshAlgoAndCurrentFrame:(id)a0;
- (void)resetRender;
- (void)applyCacheEffectIfNeededWithStatus:(BOOL)a0;
- (void)resetStyleMoreItemApplyStatus;
- (void)resetStyleNodePropertyStatus;
- (void)resetApplyEffectValueAndStatusWithExcludeNodeId:(id)a0;
- (long long)effectDefaultValueWithItemModel:(id)a0;
- (void)didSelectLeafWithOffNodeItemModel:(id)a0;
- (void)didSelectLeafWithNormalItemModel:(id)a0;
- (void)didSelectLeaftTrackActionWithItemModel:(id)a0;
- (void)megaRemoveEffectWithNodeId:(id)a0;
- (long long)effectCurrentValueWithModel:(id)a0;
- (void)compareActionForOriginEffect;
- (void)compareActionForBeautyEffect;
- (id)appendStyleNodeWithModels:(id)a0;
- (void)applyEffectWithActionModel:(id)a0 megaEditor:(id)a1;
- (void)megaRemoveNotValidEffect;
- (void)updateCompareButtonUserInteractionEnabledStatus;
- (BOOL)hasMoreTagStatusWithActionModel:(id)a0;
- (id)resourceWithActionModel:(id)a0;
- (id)tagWithActionModel:(id)a0;
- (id)beautifyItemModelWithActionModel:(id)a0;
- (id)tagInfoWithActionModel:(id)a0;
- (float)vailedRealValue:(float)a0 realMinValue:(float)a1 realMaxValue:(float)a2;
- (id)statusModellWithActionModel:(id)a0;
- (long long)effectDefaultValueWithModel:(id)a0;
- (float)realValue:(float)a0;
- (void)showStyleSliderDefaultValueForStatusModel:(id)a0 nodeId:(id)a1;
- (void)showNormalSliderDefaultValueForStatusModel:(id)a0 nodeId:(id)a1;
- (void)showSliderCommandConfigStatus;
- (void)compareAction:(id)a0;
- (void)sliderWithNormalEffectValueDidChange:(long long)a0 realValue:(long long)a1 model:(id)a2;
- (void)sliderWithStyleEffectValueDidChange:(long long)a0 realValue:(long long)a1 model:(id)a2 isRemoveMegaStatus:(BOOL)a3;
- (void)didFinishSlidingTrackWithModel:(id)a0 value:(long long)a1;
- (void)videoControlBarDidPause:(id)a0;
- (void)videoControlBarDidPlay:(id)a0;
- (id)formatTimeToContent:(long long)a0;
- (double)sliderAndPanelTopOffset;
- (void)setUpPanelView;
- (void)setUpVideoControl;
- (struct CGSize { double x0; double x1; })compareEffectButtonSize;
- (void)clickTapMediaVideoAction;
- (id)trackParamsAppendNodeInfoWithParams:(id)a0;
- (BOOL)isEqualToLastNodeIdsAndCurrentApplyNodeIds;
- (id)trackParamsAppendLastNodeInfoWithParams:(id)a0;
- (void)accEditBeautyDidStartSlidingByEffectSlider:(id)a0;
- (void)accEditBeautyEffectSlider:(id)a0 valueDidChange:(long long)a1 realValue:(long long)a2;
- (void)accEditBeautyEffectSlider:(id)a0 didFinishSlidingWithValue:(long long)a1 realValue:(long long)a2;
- (void)accEditBeautyEffectSlider:(id)a0 isSliding:(BOOL)a1;
- (void)showSliderForNode:(id)a0;
- (void)ckBeautyVCContext:(id)a0 didSelectCollection:(id)a1;
- (void)ckBeautyVCContext:(id)a0 didSelectLeafItem:(id)a1;
- (void)dragPlayTimeBegin:(double)a0;
- (void)dragPlayTimeChanged:(double)a0;
- (void)dragPlayTimeEnd:(double)a0;
- (BOOL)hasSelectItemIsNotOffNodeStatus:(id)a0;
- (void)showLoadingToast:(id)a0;
- (void)hideLoadingToast;
- (BOOL)isDictionariesEqual:(id)a0 and:(id)a1;
- (void)showToast:(id)a0;
- (void).cxx_destruct;
- (void)request;
- (id)dataManager;
- (void)prepare;
- (void)dealloc;
- (void)render;

@end
