@class DVEVCContext, AWEVideoIntelligentChapterManager, AWEEditChapterAwemeResourcesHandler, UILabel, ACCChapterTimeLineController, NSString, AWEVideoIntelligentChapterConfig, ACCChapterControlBarViewController, DUXAlertDialog, NSArray, ACCChapterInputController, ACCChapterCenterLineView, AWEIntelligentChapterProgressViewController, DVEVCContextServiceContainer, AWEVideoPublishChapterDetailModel, UIButton, ACCChapterViewModel, UIImpactFeedbackGenerator, DUXContentSheet, UIView, ACCChapterOverviewViewController, DVETrackPanelContext, NLEInterface_OC, ACCChapterPreviewViewController, ACCChapterMediaTimelineActionView, NSDate, DVEModuleManager, ACCChapterLoadingResourceView;
@protocol ACCChapterViewControllerDelegate, DVECoreAudioProtocol, DVENLEEditorProtocol, DVECoreCanvasProtocol, IESServiceProvider, DVEVCContextExternalInjectProtocol, ACCEditServiceProtocol;

@interface ACCChapterViewController : UIViewController <ACCChapterOverviewMediaTimelineViewDelegate, ACCChapterVideoTrackPreviewTransitionDelegate, UIGestureRecognizerDelegate, ACCChapterVideoToolBarDelegate, DVEPreviewZoomTransitionOuterContextProvider, ACCChapterInputControllerDelegate, UIViewControllerTransitioningDelegate, AWEMediaSmallAnimationProtocol, ACCEditTransitionViewControllerProtocol>

@property (weak, nonatomic) id<DVENLEEditorProtocol> nleEditor;
@property (weak, nonatomic) NLEInterface_OC *nle;
@property (weak, nonatomic) id<DVECoreCanvasProtocol> canvasEditor;
@property (weak, nonatomic) id<DVECoreAudioProtocol> audioEditor;
@property (weak, nonatomic) id<ACCEditServiceProtocol> editService;
@property (retain, nonatomic) UIImpactFeedbackGenerator *feedbackGenerator;
@property (retain, nonatomic) UIButton *cancelBtn;
@property (retain, nonatomic) UIButton *saveBtn;
@property (retain, nonatomic) UILabel *chapterTitleLabel;
@property (retain, nonatomic) DVEVCContext *vcContext;
@property (retain, nonatomic) DVETrackPanelContext *trackPanelContext;
@property (retain, nonatomic) ACCChapterCenterLineView *playHead;
@property (retain, nonatomic) ACCChapterInputController *inputController;
@property (retain, nonatomic) ACCChapterMediaTimelineActionView *overviewActionView;
@property (retain, nonatomic) ACCChapterMediaTimelineActionView *intelligentChapterActionView;
@property (retain, nonatomic) ACCChapterMediaTimelineActionView *chapterEditActionView;
@property (retain, nonatomic) ACCChapterMediaTimelineActionView *chapterDeleteActionView;
@property (retain, nonatomic) ACCChapterPreviewViewController *previewController;
@property (retain, nonatomic) ACCChapterControlBarViewController *controlBarController;
@property (retain, nonatomic) ACCChapterTimeLineController *timelineController;
@property (retain, nonatomic) ACCChapterViewModel *nleChapterViewModel;
@property (retain, nonatomic) ACCChapterOverviewViewController *overViewViewController;
@property (retain, nonatomic) AWEIntelligentChapterProgressViewController *progressViewController;
@property (retain, nonatomic) id<IESServiceProvider> serviceProvider;
@property (retain, nonatomic) DVEVCContextServiceContainer *serviceContainer;
@property (retain, nonatomic) DVEModuleManager *moduleManager;
@property (retain, nonatomic) AWEVideoPublishChapterDetailModel *lastFoundModel;
@property (retain, nonatomic) NSArray *enterChapterDetails;
@property (retain, nonatomic) NSDate *enterDate;
@property (nonatomic) BOOL hadSeekToFirstWhenEnter;
@property (nonatomic) BOOL hasChangedChapter;
@property (nonatomic, getter=isLoading) BOOL loading;
@property (nonatomic, getter=isViewHasAppeared) BOOL viewHasAppeared;
@property (retain, nonatomic) AWEVideoIntelligentChapterManager *chapterManager;
@property (retain, nonatomic) DUXContentSheet *remindSheet;
@property (nonatomic) BOOL isIntelligentChapter;
@property (retain, nonatomic) DUXAlertDialog *dialog;
@property (nonatomic) BOOL isIntelligentChapterFailed;
@property (nonatomic) BOOL isIntelligentActionViewShow;
@property (retain, nonatomic) AWEVideoIntelligentChapterConfig *aiChapterConfig;
@property (nonatomic) double startFlowTime;
@property (retain, nonatomic) AWEEditChapterAwemeResourcesHandler *awemeResourceHandler;
@property (retain, nonatomic) id<DVEVCContextExternalInjectProtocol> injectService;
@property (retain, nonatomic) ACCChapterLoadingResourceView *loadingResourceView;
@property (nonatomic) unsigned long long enterChapterRecommendType;
@property (retain, nonatomic) UIView *reeditSaveLoadingView;
@property (weak, nonatomic) id<ACCChapterViewControllerDelegate> delegate;
@property (nonatomic) BOOL isFromEditPage;
@property (retain, nonatomic) NSString *enterFrom;
@property (nonatomic) BOOL isReedit;
@property (retain, nonatomic) id<ACCEditServiceProtocol> reeditService;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)needUseChapterPoint;

- (id)zoomTransitionEndView;
- (id)zoomTransitionStartView;
- (BOOL)isUserPreuploadEnabled;
- (id)trackView;
- (BOOL)isLandscapeVideo;
- (id)initWithInputData:(id)a0;
- (id)mediaSmallMediaContainer;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })mediaSmallMediaContainerFrame;
- (id)mediaSmallBottomView;
- (id)displayTopViews;
- (void)willTransitionIn:(id /* block */)a0;
- (id)videoPublishChapterViewModel;
- (id)topButtons;
- (id)trackViews;
- (id)animateViewsWithAlpha;
- (id)smallPreview;
- (void)releaseResouce;
- (void)p_handleChangedSlotTimeRange:(id)a0;
- (void)didClickSaveBtn:(id)a0;
- (void)didClickCancelBtn:(id)a0;
- (void)timelineWillBeginDragging:(id)a0;
- (void)didSelectTransition:(id)a0;
- (void)didTapMediaTimeline;
- (id)initWithNLEModel:(id)a0 injectService:(id)a1 viewModel:(id)a2 editService:(id)a3;
- (id)zoomTransitionEndContainerView;
- (void)willBeginTranstion;
- (void)addChapterWithContent:(id)a0 timestamp:(long long)a1;
- (void)chapterInputViewReachMax;
- (void)timeline:(id)a0 didChangeTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)timelineDidEndDecelerating:(id)a0;
- (void)timelineDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (BOOL)useIntelligentChapter;
- (BOOL)isAsynIntelligentChapterEnable;
- (void)overViewTimeline:(id)a0 didChangeTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)initServiceInject:(id)a0;
- (void)setupVideoIntelligentChapter;
- (void)handleIntelligentChapterActionViewClick;
- (void)trackEventShowIntelligentChapterLoadingIsAsyn:(BOOL)a0;
- (void)p_showRemindSheetVcIfNeeded;
- (void)fetchAwemeResource;
- (void)initBINDObserve;
- (void)tryLocateChapterPoint:(BOOL)a0 shouldAttach:(BOOL)a1;
- (BOOL)useChapterProgressBar;
- (void)addChapterTimeLineChapterWithTimestamp:(long long)a0;
- (void)trackEventOverviewActionClickedIsIntelligent:(BOOL)a0;
- (void)trackEventIntelligentChapterFailedType:(id)a0;
- (void)trackEventChapterProgressButtonClicked:(BOOL)a0;
- (void)trackEventChapterToastShowWithType:(id)a0;
- (void)updateReeditCover;
- (void)removeLoadingResourceView;
- (void)updateReeditDataAndUI;
- (void)showLoadingResourceView;
- (void)trackEventIntelligentChapterShow;
- (BOOL)isEnableUseIntelligentChapter;
- (void)trackEventEditActionClicked;
- (void)trackEventIntelligentChapterClicked;
- (void)startVideoIntelligentChapterWithStatus:(long long)a0;
- (id)chapterRemindImagePath;
- (id)chapterRemindImageUrl;
- (void)remindSheetVcAddAction:(id)a0;
- (void)p_showReeditSaveLoadingView;
- (void)p_hiddenReeditSaveLoadingView;
- (void)trackEventCancelButtonClicked;
- (void)trackEventSaveButtonClickedIsOverview:(BOOL)a0;
- (void)p_didSave;
- (void)trackEventClickIntelligentChapterLoading:(BOOL)a0 actionType:(id)a1;
- (id)getPublishModelParamsWithParams:(id)a0;
- (void)clearButtonDidClicked;
- (void)showChapterProgressBarIsSelected:(BOOL)a0;
- (void)trackEventClearAllChapterClicked;
- (BOOL)needChapterRemindOpt;
- (void)reeditChapterWithItemID:(id)a0 chapterList:(id)a1 extra:(id)a2 chapterType:(long long)a3 chapterBarColor:(id)a4 completion:(id /* block */)a5;
- (void)adjustFrameIntelligentChapterIfNeeded;
- (void)p_overviewViewControllerShowIsIntelligent:(BOOL)a0;
- (id)addChapterText;
- (void)p_closeOverViewViewController;
- (void)handleOverviewActionViewClick;
- (void)handleChapterEditActionViewClick;
- (void)handleChapterDeleteActionViewClick;
- (void)setupIntelligentChapterIfNeeded;
- (void)p_showOverViewViewController;
- (void)trackEventRenameChapterClicked;
- (void)trackEventDeleteChapterClicked;
- (void).cxx_destruct;
- (long long)preferredStatusBarStyle;
- (id)animationControllerForDismissedController:(id)a0;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (id)bottomView;
- (void)setupUI;

@end
