@class ACCBarItem, AWEAIGCProcessResultModel, AWEDynamicTemplateApplyPopover, ACCEditorGenericEffectPanelViewModel, ACCEditorOneClickFilmingViewModel, NSNumber, UIButton, UIView, ACCEditorOneClickFilmingViewController, AWEBigToSmallModalDelegate, NSString, ACCToastWithCancelView, ACCVideoEditClipTask, ACCPicTemplateLoadingView, NSArray, ACCEditorOneClickFilmingButtonView, AWEBinding, AWEVideoUniformEffectViewController, UIImageView;
@protocol ACCGenericTemplateApplierService, ACCEditPreviewProtocol, ACCEditMusicServiceProtocol, ACCAIGCSaveDraftServiceProtocol, ACCVideoEditFlowControlService, ACCAIGCUnifyLoadingContentViewProtocol, ACCAIUnifyLoadingServiceProtocol, ACCEditElementBindService, ACCEditClipV1ServiceProtocol, ACCEditOneClickFilmDownLoadService, ACCEditCutMusicServiceProtocol, ACCEditorOneClickFilmListFetchService, ACCEditTransitionServiceProtocol, ACCRepoEditorOneClickFilmingData, ACCEditSpecialEffectServiceProtocol, ACCAdvanceEditServiceProtocol, ACCCTRServiceProtocol, ACCOneClickFilmPanelTrackerService, ACCEditOneClickFilmTrackService, ACCEditOneClickFilmApplyServiceProtocol, ACCStickerServiceProtocol, ACCVideoEditBottomControlService, ACCEditorOneClickFilmService, ACCEditViewContainer, ACCSequenceEditServiceProtocol, ACCVideoEditChallengeBindService, ACCAIGCUnifyLoadingViewProtocol, ACCEditServiceProtocol, ACCStudioAIMemoriesService, AWEStudioEditMusicFeaturePublicAPI, ACCSequencePlayControlServiceProtocol;

@interface ACCEditorOneClickFilmComponent : ACCFeatureComponent <ACCEditorOneClickFilmingSubscriber, ACCEditPreviewMessageProtocol, ACCEditMusicServiceSubscriberProtocol, ACCBarItemContainerViewSubscriber, ACCPanelViewDelegate, ACCEditSessionLifeCircleEvent, ACCEditorOneClickFilmingExitServiceProtocol, ACCSequenceEditServicePlayerSubscriber, ACCSequenceMediaContentViewProvider, ACCEditSpecialEffectServiceSubscriber, ACCEditorOneClickFilmingApplyDiffService, ACCAIGCUnifyLoadingViewDelegate, AWEVideoUniformEffectViewControllerDelegate, ACCEditorOneClickFilmingSideSlipPanelServiceProtocol, ACCEditBeatsServiceSubscriber, ACCGenericTemplateApplierSubscriber, ACCStudioAIMemoriesServiceSubscriberProtocol, ACCEditOneClickFilmApplySubscriberProtocol, ACCExtractEventSubscriber, ACCFrameExtractSubscriber>

@property (retain, nonatomic) ACCEditorOneClickFilmingButtonView *oneClickFilmingButtonView;
@property (retain, nonatomic) ACCBarItem *oneClickFilmItem;
@property (retain, nonatomic) UIButton *oneClickFilmItemButton;
@property (retain, nonatomic) UIImageView *iconView;
@property (retain, nonatomic) ACCEditorOneClickFilmingViewController *oneClickFilmVC;
@property (retain, nonatomic) ACCEditorOneClickFilmingViewModel *viewModel;
@property (weak, nonatomic) id<ACCEditServiceProtocol> editService;
@property (weak, nonatomic) id<ACCEditViewContainer> viewContainer;
@property (weak, nonatomic) id<ACCEditorOneClickFilmService> oneClickFilmService;
@property (weak, nonatomic) id<ACCEditOneClickFilmApplyServiceProtocol> applyService;
@property (weak, nonatomic) id<ACCGenericTemplateApplierService> applierService;
@property (weak, nonatomic) id<ACCEditOneClickFilmTrackService> trackService;
@property (weak, nonatomic) id<ACCEditMusicServiceProtocol> musicService;
@property (retain, nonatomic) AWEBigToSmallModalDelegate *vcTransitioningDelegate;
@property (weak, nonatomic) id<ACCSequenceEditServiceProtocol> sequenceEditService;
@property (weak, nonatomic) id<ACCAdvanceEditServiceProtocol> advanceEditService;
@property (weak, nonatomic) id<ACCEditorOneClickFilmListFetchService> oneClickFilmFetchListService;
@property (weak, nonatomic) id<ACCEditOneClickFilmDownLoadService> oneClickFilmDownloadService;
@property (weak, nonatomic) id<ACCSequencePlayControlServiceProtocol> sequencePlayControl;
@property (weak, nonatomic) id<ACCEditElementBindService> editElementBindService;
@property (weak, nonatomic) id<ACCStickerServiceProtocol> stickerService;
@property (weak, nonatomic) id<ACCEditCutMusicServiceProtocol> cutMusicService;
@property (weak, nonatomic) id<AWEStudioEditMusicFeaturePublicAPI> musicFeatureAPI;
@property (retain, nonatomic) AWEBinding *didChangedUinTemplateSignal;
@property (retain, nonatomic) AWEBinding *willChangedWorkspaceSignal;
@property (retain, nonatomic) AWEBinding *didChangedWorkspaceSignal;
@property (retain, nonatomic) AWEBinding *exitWithCancelSignal;
@property (weak, nonatomic) id<ACCEditSpecialEffectServiceProtocol> specialEffectService;
@property (weak, nonatomic) id<ACCAIUnifyLoadingServiceProtocol> aigcUnifyLoadingService;
@property (weak, nonatomic) id<ACCEditClipV1ServiceProtocol> clipService;
@property (nonatomic) BOOL hasPresentOneClickFilmVC;
@property (readonly, nonatomic) BOOL isMultiProjects;
@property (retain, nonatomic) id<ACCEditTransitionServiceProtocol> transitionService;
@property (retain, nonatomic) id<ACCRepoEditorOneClickFilmingData> repoOneClickFilmData;
@property (nonatomic) BOOL hasChangeMaterials;
@property (nonatomic) BOOL isCombineOneProject;
@property (nonatomic) BOOL needUpdateSidebar;
@property (retain, nonatomic) id<ACCVideoEditBottomControlService> bottomControlService;
@property (weak, nonatomic) id<ACCCTRServiceProtocol> ctrService;
@property (weak, nonatomic) id<ACCVideoEditChallengeBindService> editChallengeBindService;
@property (nonatomic) BOOL hasPrefetched;
@property (nonatomic) BOOL isFirstRenderReady;
@property (copy, nonatomic) NSArray *features;
@property (copy, nonatomic) NSArray *recommendFeatureTypes;
@property (retain, nonatomic) ACCPicTemplateLoadingView *templateLoadingView;
@property (retain, nonatomic) UIView<ACCAIGCUnifyLoadingViewProtocol> *templateUnifyLoadingView;
@property (retain, nonatomic) UIView<ACCAIGCUnifyLoadingContentViewProtocol> *loadingContentView;
@property (retain, nonatomic) AWEAIGCProcessResultModel *unifyResult;
@property (nonatomic) double msgToEffectStart;
@property (retain, nonatomic) AWEVideoUniformEffectViewController *uniformEffectVC;
@property (nonatomic) BOOL isMainPanelTransfering;
@property (weak, nonatomic) id<ACCEditPreviewProtocol> previewService;
@property (retain, nonatomic) ACCEditorGenericEffectPanelViewModel *panelViewModel;
@property (retain, nonatomic) id<ACCOneClickFilmPanelTrackerService> panelTrakcerService;
@property (weak, nonatomic) id<ACCVideoEditFlowControlService> flowService;
@property (weak, nonatomic) id<ACCStudioAIMemoriesService> aiMemoriesService;
@property (nonatomic) BOOL isAppearUnifyLoadingView;
@property (nonatomic) BOOL hasHandleBottomEntranceViewWhenFirstRender;
@property (retain, nonatomic) id<ACCAIGCSaveDraftServiceProtocol> aigcSaveDraftImpl;
@property (nonatomic) BOOL isShowBottomPreviewBeforeOneClickFilmingClicked;
@property (nonatomic) BOOL openVCDidAppearFlag;
@property (nonatomic) BOOL openVCFirstRenderFlag;
@property (retain, nonatomic) AWEDynamicTemplateApplyPopover *dynamicTemplateApplyPopover;
@property (retain, nonatomic) NSString *autoApplyTemplateId;
@property (nonatomic) BOOL hasMusicBeatsDynamicTemplate;
@property (weak, nonatomic) ACCVideoEditClipTask *clipTask;
@property (retain, nonatomic) ACCToastWithCancelView *clipCancelToast;
@property (copy, nonatomic) NSArray *editTemplateList;
@property (retain, nonatomic) NSNumber *enableDynamicTemplateValue;
@property (retain, nonatomic) NSNumber *musicBeatsTemplateApplyingTipStyle;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)mediaContainerView;
- (void)componentWillAppear;
- (void)componentDidAppear;
- (void)componentWillDisappear;
- (id)pieceInstanceViewAtIndex:(unsigned long long)a0;
- (void)transferAsync:(id)a0;
- (void)transferAsyncTaskAndDismissLoading:(id)a0;
- (void)transferAsyncTaskAndDismissLoadingInIM:(id)a0;
- (void)cancelTaskAndDismissLoadingWithClickType:(id)a0;
- (void)retryTaskAndDismissLoading:(id)a0;
- (void)cancelTaskWithCancelType:(id)a0;
- (BOOL)isDraftAndIsSavedFromButton;
- (void)clickGainAIAssetButtonWithType:(long long)a0;
- (void)sequenceEditService:(id)a0 didTransferToIndex:(long long)a1 editMode:(unsigned long long)a2 isAutoTransfer:(BOOL)a3;
- (void)sequenceEditService:(id)a0 changedWithAddedIndexSet:(id)a1 deletedIndexSet:(id)a2;
- (void)sequenceEditServiceSwipeUpGesture:(id)a0;
- (BOOL)musicService:(id)a0 shouldForbidPauseWhenDisappear:(id)a1;
- (void)extractFrameDidFinished:(id)a0;
- (void)extractUploadDidFinished:(id)a0;
- (void)extractFeatureDidFinished:(id)a0;
- (void)templateApplierDidRemoveWithTemplateId:(id)a0 changeInfo:(id)a1;
- (void)templateApplierWillApplyWithTemplateModel:(id)a0;
- (void)templateApplierDidApplySeekWithTemplateModel:(id)a0;
- (void)sensorialRenderWithEditService:(id)a0;
- (void)firstRenderWithEditService:(id)a0;
- (void)barItemContainer:(id)a0 didClickMoreButton:(BOOL)a1;
- (void)panelViewController:(id)a0 willShowPanelView:(id)a1;
- (void)updatePanGestureEnabled:(BOOL)a0;
- (void)extractPrepareMaterialModels:(id)a0;
- (void)loadComponentView;
- (void)componentDidMount;
- (void)componentDidUnmount;
- (unsigned long long)preferredLoadPhase;
- (id)serviceBindingArray;
- (id)rootVC;
- (void)setupObserver;
- (void)closeButtonDidClick;
- (void)toggleLoadingViewState:(BOOL)a0;
- (BOOL)previewService:(id)a0 shouldForbidPauseWhenDisappear:(id)a1;
- (void)bindServices:(id)a0;
- (id)preferredFallbackWaitTimeTip;
- (void)addBarItemToToolBar;
- (void)resetSequenceMediaContainerView;
- (void)didUpdateProgressForLatestTemplate:(unsigned long long)a0 templateModel:(id)a1;
- (void)specialEffectService:(id)a0 willChangeShowState:(unsigned long long)a1;
- (void)specialEffectService:(id)a0 didChangeShowState:(unsigned long long)a1;
- (void)exitEditorWhenCancel;
- (void)exitEditorWhenCancelBeforeAnimation;
- (void)exitEditorWhenFinish;
- (void)exitEditorWhenFinishBeforeAnimation;
- (void)willExitBigPanelWhenCancel;
- (void)didExitBigPanelWhenCancel;
- (void)willExitBigPanelWhenSave;
- (void)didExitBigPanelWhenSave;
- (void)dismissVCWithAnimate:(BOOL)a0 completion:(id /* block */)a1;
- (id)p_getCurrentTemplateModel;
- (void)enterSegmentEditPage;
- (void)showOneClickFilmingSideSlipViewIfNeeded;
- (void)hideOneClickFilmingSideSlipViewIfNeeded;
- (void)insertIfNeededAndApplyModel:(id)a0;
- (void)insertIfNeededWithModel:(id)a0 apply:(BOOL)a1 forbidPlay:(BOOL)a2;
- (void)insertIfNeededWithModel:(id)a0 apply:(BOOL)a1;
- (void)refreshOneClickPanel;
- (void)changeSparkBackground;
- (BOOL)shouldDisableComponent;
- (void)initOneClickFilmScene;
- (BOOL)isEnableDynamicTemplate;
- (void)tryReloadOneClickFilmComponent;
- (void)prefetchOneClickFilmListAndFirstTemplateIfNeeded;
- (void)setupSoftBringInTemplate;
- (BOOL)enableOneClickFilmFullLoading;
- (id)buildUnifyLoadingConfigWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (id)requestTimesForVideoDuration:(double)a0;
- (void)requestAlgorithmsWithFeatureConfig:(id)a0;
- (BOOL)shouldReApplyTemplate;
- (void)cleanMusicBeatsTempalteBindMusic;
- (void)updateLoadingViewShowImage;
- (void)reRefreshSidebarIfNeed;
- (void)trackBottomEntranceViewShowIfNeeded;
- (void)autoOpenOneClickFilmViewController;
- (void)clearMusicBeatsDynamicTemplateAutoApplyContext:(id)a0;
- (void)configOneClickFilmingButton;
- (void)resetOneClickFilmingButtonViewTitleAndIcon;
- (void)dismissPlayControlIfNeeded;
- (void)showClipCancelToast;
- (void)setupObserverRelatedMusic;
- (void)setupObserverRelatedTemplate;
- (BOOL)isMusicBeatsTemplateApplyPopoverStyle;
- (void)updateEntranceEnableStatus;
- (BOOL)shouldRemoveEntranceForAdvanceEdit;
- (void)setupGestureObserverIfNeeded;
- (void)updateLoadingViewShowImageWithLora;
- (void)updateLoadingViewShowImageWithImageCache;
- (void)doInFirstRender;
- (void)showMusicBeatsDynamicTemplateApplyTips;
- (void)createClipVideoWith:(id)a0;
- (void)fetchBeatsMusic:(id /* block */)a0;
- (void)resumeDraftApplyingTemplate;
- (BOOL)shouldFetchDataForAIMemoriesScene;
- (BOOL)shouldFetchDataForAICreationScene;
- (void)trackForAlbumAutoFilmEditFirstFrame;
- (BOOL)enableSetCover;
- (void)preDownLoadTemplate:(id)a0;
- (void)trackForAlbumAutoFilmPanelAutoShowFirstTime;
- (void)trackToolsAlbumAutoFilmPerformanceSuccess;
- (void)oneClickFilmingButtonDidClickWithSource:(unsigned long long)a0 completion:(id /* block */)a1;
- (void)prefetchOneClickFilmBigPanelDataIfNeeded;
- (BOOL)shouldShowOneClickFilmingButtonViewOnBottomPreview;
- (void)updateEditPlayControlStatus:(BOOL)a0 didSave:(BOOL)a1;
- (void)updateBottomViewStatusWhenExitOneClickFilmPanel;
- (void)removeOneClickFilmingButtonView;
- (long long)getTemplateSettingTimeConsuming;
- (void)updateUnifyLoadingViewConfig;
- (void)cancelTaskAndDismissLoading;
- (void)p_saveStickerIfNeeded;
- (void)dismissOneClickFilmingWithCompletion;
- (void)dismissOneClickFilm;
- (BOOL)shouldEnableEntranceWithSideslip;
- (id)entranceTitle;
- (void)didClickDynamicTemplateCancelApplyBtn;
- (void)updateOneClickFilmButtonViewConfig:(BOOL)a0;
- (id)createBarItemTitleHintView;
- (BOOL)couldEnableOneClickFilming;
- (void)didClickBarItem;
- (void)removeBarItemHintView;
- (void)resetOneClickFilmFetchListData;
- (void)openGenericEffectPanelPageWithEnterMethod:(id)a0;
- (BOOL)canResponserTextStickerInputWithTapGes;
- (void)slipEffectViewWillShow;
- (void)openBigSideslipPropPanel;
- (void)panelWillHidden;
- (void)panelDidHidden;
- (BOOL)disableAutoChangeClipState;
- (void)hasReceivedAIMemoriesTaskID:(id)a0;
- (void).cxx_destruct;
- (void)cancelSyncTask:(id)a0;

@end
