@class ACCGenericTemplateMusicBeatsTaskManager, NSMutableArray, CKGenericTemplateModel, AWEGenericTemplateApplier, NSString, AWEGenericTemplateAIGCTaskManager, ACCGenericTemplateTextParamManager, AWEVideoPublishViewModel, NPGenericTemplateService_OC, NSArray, AWEBinding, ACCGenericTemplatePreprocessTaskManager, ACCGenericTemplateTTSTaskManager, NSNumber;
@protocol ACCGenericTemplateApplierService, ACCSequenceEditServiceProtocol, IESServiceProvider, ACCVideoEditChallengeBindService, ACCEditServiceProtocol;

@interface ACCEditorOneClickFilmService : NSObject <NPGenericTemplateRecommendConfigDelegate, AWEAIGCTemplateAiProcessResultDelegate, ACCEditorOneClickFilmService>

@property (weak, nonatomic) id<IESServiceProvider> serviceProvider;
@property (weak, nonatomic) AWEVideoPublishViewModel *repository;
@property (retain, nonatomic) NPGenericTemplateService_OC *service;
@property (retain, nonatomic) NSMutableArray *recommendServices;
@property (copy, nonatomic) NSArray *materials;
@property (nonatomic) BOOL isFirstRenderReady;
@property (nonatomic) BOOL isMaterialsInferring;
@property (nonatomic) BOOL isShowingOneClickFilmPanel;
@property (copy, nonatomic) NSArray *projectUUIDList;
@property (retain, nonatomic) NSMutableArray *completionBlockArray;
@property (weak, nonatomic) id<ACCEditServiceProtocol> editService;
@property (weak, nonatomic) id<ACCGenericTemplateApplierService> templateApplierService;
@property (weak, nonatomic) id<ACCVideoEditChallengeBindService> editChallengeBindService;
@property (weak, nonatomic) id<ACCSequenceEditServiceProtocol> sequenceEditService;
@property (copy, nonatomic) NSArray *recommendFeatureTypes;
@property (nonatomic) BOOL recommendIlaRealTimeFeatureExtractionEnabled;
@property (copy, nonatomic) NSString *recommendScene;
@property (nonatomic) BOOL hasEnterSegmentEditPage;
@property (nonatomic) BOOL hasEditSegmentMaterial;
@property (retain, nonatomic) AWEGenericTemplateAIGCTaskManager *templateAIGCTaskManager;
@property (retain, nonatomic) AWEBinding *updateLoadingViewTypeSignal;
@property (retain, nonatomic) AWEBinding *updateUnifyLoadingResultSignal;
@property (retain, nonatomic) AWEBinding *transferAIGCTemplateTaskAsyncSignal;
@property (retain, nonatomic) AWEBinding *cancelAIGCTemplateTaskAsyncSignal;
@property (retain, nonatomic) AWEBinding *retryAIGCTemplateTaskAsyncSignal;
@property (retain, nonatomic) AWEBinding *filterImageOnlyTemplateSignal;
@property (retain, nonatomic) AWEBinding *updateLoadingViewAIAssetInsufficientSignal;
@property (retain, nonatomic) AWEBinding *updateLoadingViewShowOrHideSignal;
@property (retain, nonatomic) ACCGenericTemplatePreprocessTaskManager *preprocessTaskManager;
@property (retain, nonatomic) ACCGenericTemplateTTSTaskManager *ttsTaskManager;
@property (retain, nonatomic) ACCGenericTemplateTextParamManager *textParamTaskManager;
@property (retain, nonatomic) ACCGenericTemplateMusicBeatsTaskManager *musicBeatsTaskManager;
@property (copy, nonatomic) CKGenericTemplateModel *applyingTemplateModel;
@property (nonatomic) long long applyingCount;
@property (retain, nonatomic) AWEGenericTemplateApplier *templateApplier;
@property (retain, nonatomic) NSNumber *updateMusicBeatsTaskId;
@property (nonatomic) BOOL hasFilterImageOnlyTemplate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL lastTemplateHasStickers;
@property (nonatomic) BOOL isCloudFeatureReady;

+ (id)featureConfigWithOneClickFilmingScene:(unsigned long long)a0;
+ (BOOL)c3FeatureEnabled;
+ (id)featureConfigWithOneClickFilmingScene:(unsigned long long)a0 recommendFeatureTypes:(id)a1 ilaRealTimeFeatureExtractionEnabled:(BOOL)a2 isDraftOrBackup:(BOOL)a3;

- (BOOL)isTemplateReady:(id)a0;
- (BOOL)shouldPreprocessMaterials;
- (void)preprocessMaterialsIfNeeded;
- (void)updateIsFirstRenderReady:(BOOL)a0;
- (void)updateFeatures:(id)a0;
- (BOOL)hasAIGCCacheWithTemplateID:(id)a0;
- (void)updateUnifyLoadingShowOrHide:(BOOL)a0;
- (void)updateLoadingViewSubtitleWith:(long long)a0 type:(long long)a1;
- (id)featureConfig;
- (id)businessScene;
- (void)bindService;
- (void)updatePanelState:(BOOL)a0;
- (id)generateMaterials;
- (void)markHasEnterSegmentEditStatus:(BOOL)a0;
- (void)markHasEditSegmentMaterialStatus:(BOOL)a0;
- (BOOL)shouldDisableEditorOneClickFilmFeature;
- (void)prepareMaterial:(id /* block */)a0;
- (BOOL)isValidMaterials:(id)a0;
- (void)updateMusicBeatsWithTemplate:(id)a0 completion:(id /* block */)a1;
- (void)cancelMusicBeatsUpdateTaskIfNeed;
- (void)applyUniTemplate:(id)a0 extraInfo:(id)a1 completion:(id /* block */)a2 seekCompletion:(id /* block */)a3;
- (void)removeUniTemplateWithId:(id)a0 isPureRemoveScene:(BOOL)a1 completion:(id /* block */)a2;
- (id)initWithServiceProvider:(id)a0 repository:(id)a1;
- (id)fetchCurrentApplyTemplateModel:(id)a0;
- (void)updateUnifyLoadingWithViewType:(long long)a0 errMsg:(id)a1;
- (void)updateUnifyLoadingWithWithAIGCProcessResultModel:(id)a0 querySceneType:(long long)a1;
- (void)didAIGCRequestSuccessWithRequestInfo:(id)a0;
- (id)bimAlgorithmModelList;
- (void)syncAIGCInfoFromRepoToService;
- (void)addRecommendService:(id)a0;
- (void)trackProcessILAResultWithMaterials:(id)a0;
- (void)removeRecommendService:(id)a0;
- (void)p_extractFeatureWithService:(id)a0 materials:(id)a1 completion:(id /* block */)a2;
- (void)handleWillApplyTemplate:(id)a0;
- (void)handleDidApplyTemplate:(id)a0 targetModel:(id)a1 changeInfo:(id)a2 error:(id)a3 completion:(id /* block */)a4;
- (void)handleTemplateRenderedWithTrackData:(id)a0;
- (void)handleTemplateApplyTrackInfo:(id)a0;
- (id)p_fetchCurrentApplyTemplateModel;
- (void)trackCustomInfoTaskDuration:(id)a0;
- (void)trackTTSTaskDuration:(id)a0;
- (BOOL)supportFunctionForStage:(unsigned long long)a0;
- (unsigned long long)frameExtractionStrategy;
- (struct CGSize { double x0; double x1; })videoFrameSizeForVideo:(id)a0 forStage:(unsigned long long)a1;
- (id)requestTimesForVideo:(id)a0 forStage:(unsigned long long)a1;
- (BOOL)enableAccurateFrameExtractionForVEFeature;
- (void).cxx_destruct;

@end
