@class NSMutableDictionary, ACCImageAlbumData, ACCImageAlbumAudioPlayer, ACCImageAlbumSessionPlayerViewModel, ACCImageAlbumExportManager;

@interface ACCImageAlbumModernEditorSession : NSObject <ACCImageAlbumEditorSessionProtocol> {
    ACCImageAlbumData *_albumData;
    id /* block */ onFirstImageEditorRendered;
    id /* block */ onCustomerContentViewRecovered;
    id /* block */ onCurrentImageEditorChanged;
    id /* block */ onPlayerDraggingStatusChangedHandler;
    id /* block */ willScrollToIndexHandler;
    id /* block */ onPreviewModeChanged;
    id /* block */ onWillReloadData;
    struct CGSize { double width; double height; } _containerSize;
}

@property (nonatomic) BOOL didFirstRenderedCallbacked;
@property (retain, nonatomic) ACCImageAlbumAudioPlayer *audioPlayer;
@property (retain, nonatomic) NSMutableDictionary *stickerUniqueIdStcikerIdMapping;
@property (retain, nonatomic) ACCImageAlbumExportManager *exportManager;
@property (retain, nonatomic) ACCImageAlbumExportManager *captureManager;
@property (retain, nonatomic) ACCImageAlbumSessionPlayerViewModel *playerViewModel;
@property (nonatomic) struct CGPoint { double x; double y; } centerOffset;
@property (nonatomic) BOOL filterImageLayer;
@property (nonatomic) BOOL mainImageLayerEnableMove;

- (void)scrollToIndex:(long long)a0;
- (double)currentPlayTime;
- (void)removeTimeObserver;
- (void)setScrollEnable:(BOOL)a0;
- (double)bgmVolume;
- (void)setVolumeForAudio:(double)a0;
- (id)capturePreviewUIImage;
- (BOOL)isPreviewMode;
- (void)releasePlayer;
- (void)setIsPreviewMode:(BOOL)a0;
- (void)updateInfoStickerTemplateParam:(int)a0 json:(id)a1;
- (id)nativeGetInfoStickerTemplateParam:(int)a0;
- (void)pauseMusic;
- (void)setAudioClipRange:(id)a0;
- (void)replayMusic;
- (void)getProcessedPreviewImageAtIndex:(long long)a0 preferredSize:(struct CGSize { double x0; double x1; })a1 compeletion:(id /* block */)a2;
- (void)getSourcePreviewImageAtIndex:(long long)a0 preferredSize:(struct CGSize { double x0; double x1; })a1 compeletion:(id /* block */)a2;
- (void)beginImageAlbumPreviewTaskExportItemRetainAndReuse;
- (void)endImageAlbumPreviewTaskExportItemRetainAndReuse;
- (void)resetWithContainerView:(id)a0;
- (void)continuePlayMusic;
- (void)replaceMusic:(id)a0;
- (id)currentImageItemModel;
- (void)exportImagesWithProgress:(id /* block */)a0 onSucceed:(id /* block */)a1 onFaild:(id /* block */)a2;
- (void)reloadCurrentPlayerItem;
- (void)reloadPlayerItemAtIndex:(long long)a0;
- (void)setAutoPlayInterval:(double)a0;
- (void)setDisableTransitionAnimation:(BOOL)a0;
- (double)progressBottomInsert;
- (id)playerGestureView;
- (void)updatePageProgressViewShowStatus:(BOOL)a0;
- (void)updateInteractionContainerAlpha:(double)a0;
- (void)setOnCurrentImageEditorChanged:(id /* block */)a0;
- (void)setOnCustomerContentViewRecovered:(id /* block */)a0;
- (void)setOnPreviewModeChanged:(id /* block */)a0;
- (void)setWillScrollToIndexHandler:(id /* block */)a0;
- (void)setOnPlayerDraggingStatusChangedHandler:(id /* block */)a0;
- (void)setOnWillReloadData:(id /* block */)a0;
- (id)customerContentViewAtIndex:(long long)a0;
- (id)imageItemAtIndex:(long long)a0;
- (void)exportImagesWithProgress:(id /* block */)a0 onSucceed:(id /* block */)a1 onFaild:(id /* block */)a2 needUniqueId:(BOOL)a3;
- (struct CGSize { double x0; double x1; })imageLayerSizeAtIndex:(long long)a0 needClip:(BOOL)a1;
- (struct CGSize { double x0; double x1; })imageOriginalSizeAtIndex:(long long)a0;
- (long long)totalImageItemCount;
- (void)updatePageProgressAnimationEnable:(BOOL)a0;
- (void)startAutoPlay;
- (void)stopAutoPlay;
- (void)updateComposerFilterWithFilterId:(id)a0 filePath:(id)a1 intensity:(float)a2;
- (void)batchUpdateComposerFilterWithFilterId:(id)a0 filePath:(id)a1 intensity:(float)a2;
- (void)setupLensHDRModelWithFilePath:(id)a0;
- (void)setHDREnable:(BOOL)a0;
- (void)beginCurrentImageEditorBatchUpdate;
- (void)endCurrentImageEditorBatchUpdate;
- (long long)uniqueIdForStickerId:(long long)a0;
- (void)setPlayerCenterOffset:(struct CGPoint { double x0; double x1; })a0;
- (void)setOnFirstImageEditorRendered:(id /* block */)a0;
- (void)updateAlbumData:(id)a0;
- (id)initWithImageAlbumData:(id)a0 containerSize:(struct CGSize { double x0; double x1; })a1;
- (void)removeInfoStickerWithUniqueId:(long long)a0;
- (long long)addInfoStickerWithPath:(id)a0 effectInfo:(id)a1 userInfo:(id)a2 imageIndex:(long long)a3;
- (id)nativeGetTextStickerParam:(int)a0;
- (void)updateTextStickerTextParams:(long long)a0 textParams:(id)a1;
- (void)updateInfoStickerWithUniqueId:(long long)a0 updateTypes:(unsigned long long)a1 props:(id)a2;
- (id)stickerWithUniqueId:(long long)a0;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })getInfoStickerBoundingBoxWithUniqueId:(long long)a0;
- (void)removeInfoStickerWithUniqueId:(long long)a0 traverseAllEditorIfNeed:(BOOL)a1;
- (long long)addTextSticker:(id)a0 withUserInfo:(id)a1 imageIndex:(long long)a2;
- (BOOL)applyTemplateFile:(id)a0 diffJson:(id)a1 imageIndex:(long long)a2;
- (id)getNeedDownloadedResourceForImageIndex:(long long)a0;
- (id)exportTemplateInfoOnlyImageForImageIndex:(long long)a0;
- (id)getNleWrapperAtImageIndex:(long long)a0;
- (id)getNleImageAlbumEditorAtImageIndex:(long long)a0;
- (void)updateOriginImageInfoForTemplateIndex:(long long)a0;
- (BOOL)userAddedLayerFlag:(id)a0 AtImageIndex:(long long)a1;
- (void)updateTemplateInfoAfterDownloadIfSuccess:(BOOL)a0 downloadTemplateCache:(id)a1 callBack:(id /* block */)a2 data:(id)a3 forImageIndex:(long long)a4;
- (void)p_logInfoWithLogMsg:(id)a0;
- (void)setupAudioPlayerIfNeed;
- (id)geometryModelWithLayer:(id)a0 fromNLEImageWrapper:(id)a1 mediaSize:(struct CGSize { double x0; double x1; })a2;
- (void)p_saveImage:(id)a0 toFile:(id)a1;
- (BOOL)isCoverToolsExperienceOpt1;
- (void)p_logErrorWithLogMsg:(id)a0;
- (void)p_setupPlayerDataSource;
- (id)albumData;
- (id /* block */)onCustomerContentViewRecovered;
- (id /* block */)onPreviewModeChanged;
- (id /* block */)onCurrentImageEditorChanged;
- (id /* block */)onWillReloadData;
- (void)p_updateStickerIdMappingWithUniqueId:(long long)a0 stickerId:(long long)a1;
- (id /* block */)onFirstImageEditorRendered;
- (id /* block */)willScrollToIndexHandler;
- (id /* block */)onPlayerDraggingStatusChangedHandler;
- (long long)p_getVEStickerIdWithUniqueId:(long long)a0;
- (void)p_getPreviewImageAtIndex:(long long)a0 preferredSize:(struct CGSize { double x0; double x1; })a1 usingOriginalImage:(BOOL)a2 compeletion:(id /* block */)a3;
- (void)p_logInfoWithLogMsg:(id)a0 isError:(BOOL)a1;
- (void)saveImageAlbumTemplateStickersWithImageEditor:(id)a0 ImageItem:(id)a1;
- (int)setRedrawCallback:(id /* block */)a0 data:(id)a1 forImageIndex:(long long)a2;
- (void)reloadData;
- (long long)currentIndex;
- (void).cxx_destruct;
- (struct CGSize { double x0; double x1; })containerSize;
- (void)setPreviewSize:(struct CGSize { double x0; double x1; })a0;
- (void)addPeriodicTimeObserverForInterval:(double)a0 queue:(id)a1 usingBlock:(id /* block */)a2;
- (void)setBottomOffset:(double)a0;

@end
