@class NSMutableDictionary, NSDictionary, AVAsset, IESMMCanvasConfig, IESMMTranscoderParam, NLEInterface_OC, NSString, IESMMImageMovieInfo, IESVideoAddEdgeData, NSMutableSet, NSArray, NLEModel_OC, HTSVideoData;

@interface ACCNLEEditVideoData : NSObject <NLERenderHook, ACCEditVideoDataProtocol>

@property (retain, nonatomic) NLEModel_OC *nleModel;
@property (retain, nonatomic) NSMutableSet *updateTypes;
@property (nonatomic) BOOL forbidUpdateNLEModel;
@property (retain, nonatomic) NLEInterface_OC *nle;
@property (copy, nonatomic) NSDictionary *stickerChangeMap;
@property (nonatomic) BOOL isTempVideoData;
@property (copy, nonatomic) NSString *mattingAudioPath;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) HTSVideoData *videoData;
@property (nonatomic) BOOL willSeekToRealFrame;
@property (copy, nonatomic) NSString *identifier;
@property (nonatomic) BOOL disableMetadataInfo;
@property (readonly, nonatomic) double totalVideoDuration;
@property (readonly, nonatomic) double currentTotalDuration;
@property (readonly, nonatomic) double totalDurationWithTimeMachine;
@property (nonatomic) BOOL isFastImport;
@property (nonatomic) BOOL isRecordFromCamera;
@property (nonatomic) BOOL isMicMuted;
@property (copy, nonatomic) NSDictionary *movieInputFillType;
@property (nonatomic) double maxTrackDuration;
@property (copy, nonatomic) NSDictionary *dataInfo;
@property (nonatomic) struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; } importTransform;
@property (copy, nonatomic) NSDictionary *metaRecordInfo;
@property (readonly, nonatomic) BOOL isHDR;
@property (readonly, nonatomic) double totalVideoDurationAddTimeMachine;
@property (retain, nonatomic) IESMMTranscoderParam *transParam;
@property (nonatomic) BOOL useAVAssetReader;
@property (copy, nonatomic) NSDictionary *videoCurves;
@property (retain, nonatomic) AVAsset *videoHeader;
@property (copy, nonatomic) NSArray *videoAssets;
@property (copy, nonatomic) NSArray *subTrackVideoAssets;
@property (nonatomic) int previewFrameRate;
@property (copy, nonatomic) NSDictionary *videoTimeScaleInfo;
@property (copy, nonatomic) NSArray *audioAssets;
@property (copy, nonatomic) NSArray *bgAudioAssets;
@property (nonatomic) double totalBGAudioDuration;
@property (nonatomic) BOOL isDetectMode;
@property (readonly, nonatomic) BOOL hasRecordAudio;
@property (copy, nonatomic) NSDictionary *audioSoundFilterInfo;
@property (copy, nonatomic) NSDictionary *videoSoundFilterInfo;
@property (readonly, nonatomic) BOOL videoAssetsAllHaveAudioTrack;
@property (readonly, nonatomic) BOOL videoAssetsAllMuted;
@property (retain, nonatomic) NSString *musicID;
@property (copy, nonatomic) NSDictionary *assetRotationsInfo;
@property (copy, nonatomic) NSDictionary *assetTransformInfo;
@property (retain, nonatomic) AVAsset *endingWaterMarkAudio;
@property (copy, nonatomic) NSDictionary *volumnInfo;
@property (copy, nonatomic) NSDictionary *bingoVideoKeys;
@property (copy, nonatomic) NSArray *pcmDataPaths;
@property (copy, nonatomic) NSDictionary *videoTimeClipInfo;
@property (copy, nonatomic) NSDictionary *audioTimeClipInfo;
@property (nonatomic) long long studio_videoClipResolveType;
@property (nonatomic) BOOL notSupportCrossplat;
@property (nonatomic) BOOL crossplatCompile;
@property (nonatomic) BOOL crossplatInput;
@property (nonatomic) BOOL crossplatMultiTrack;
@property (nonatomic) BOOL enableVideoAnimation;
@property (copy, nonatomic) NSDictionary *canvasInfo;
@property (retain, nonatomic) NSMutableDictionary *textureVerticesMap;
@property (copy, nonatomic) NSDictionary *canvasConfigsMap;
@property (readonly, copy, nonatomic) NSDictionary *templateConfigsMap;
@property (retain, nonatomic) IESMMCanvasConfig *preferCanvasConfig;
@property (nonatomic) BOOL forbidChangeCanvasSize;
@property (nonatomic) struct CGSize { double x0; double x1; } canvasSize;
@property (nonatomic) struct CGSize { double x0; double x1; } normalizeSize;
@property (nonatomic) long long contentSource;
@property (copy, nonatomic) NSDictionary *movieAnimationType;
@property (copy, nonatomic) id /* block */ effectFilterPathBlock;
@property (nonatomic) long long effect_timeMachineType;
@property (retain, nonatomic) AVAsset *effect_reverseAsset;
@property (readonly, copy, nonatomic) NSArray *effect_timeRange;
@property (copy, nonatomic) NSArray *effect_operationTimeRange;
@property (nonatomic) double effect_timeMachineBeginTime;
@property (nonatomic) double effect_newTimeMachineDuration;
@property (readonly, nonatomic) double effect_videoDuration;
@property (readonly, copy, nonatomic) NSDictionary *effect_dictionary;
@property (copy, nonatomic) NSDictionary *extraInfo;
@property (retain, nonatomic) NSString *extraMetaInfo;
@property (copy, nonatomic) NSDictionary *accelerateInfo;
@property (readonly, copy, nonatomic) NSString *getAudioDataMD5;
@property (readonly, copy, nonatomic) NSString *getReverseVideoDataMD5;
@property (copy, nonatomic) NSDictionary *photoAssetsInfo;
@property (copy, nonatomic) NSDictionary *photoAssetsImageInfo;
@property (copy, nonatomic) NSArray *photoMovieAssets;
@property (readonly, nonatomic) BOOL isNewImageMovie;
@property (retain, nonatomic) IESMMImageMovieInfo *imageMovieInfo;
@property (copy, nonatomic) NSArray *infoStickers;
@property (retain, nonatomic) IESVideoAddEdgeData *infoStickerAddEdgeData;
@property (copy, nonatomic) NSString *draftFolder;
@property (readonly, copy, nonatomic) NSString *cacheDirPath;
@property (retain) NSMutableDictionary *urlDict;

- (void)setSticker:(long long)a0 offsetX:(double)a1 offsetY:(double)a2;
- (void)setEffectTimeRangeFollowMainTrack;
- (void)updateMovieInputFillTypeWithType:(id)a0 asset:(id)a1;
- (void)updateVideoCurvesWithCurveSource:(id)a0 asset:(id)a1;
- (void)updateVideoTimeScaleInfoWithScale:(id)a0 asset:(id)a1;
- (void)updateSoundFilterInfoWithFilters:(id)a0 asset:(id)a1;
- (void)removeSoundFilterWithFilter:(id)a0 asset:(id)a1;
- (void)updateVideoSoundFilterInfoWithFilters:(id)a0 asset:(id)a1;
- (void)removeVideoSoundFilterWithFilter:(id)a0 asset:(id)a1;
- (void)updateAssetRotationsInfoWithRotateType:(id)a0 asset:(id)a1;
- (void)updateAssetTransformInfoWithTransformInfo:(id)a0 asset:(id)a1;
- (void)updateVolumeInfoWithVolumes:(id)a0 asset:(id)a1;
- (double)videoRateForAsset:(id)a0;
- (void)setVolumeForAudio:(float)a0;
- (void)setVolumeForVideo:(float)a0;
- (id)volumeForAsset:(id)a0;
- (struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })audioTimeClipRangeForAsset:(id)a0;
- (void)addAudioWithAsset:(id)a0;
- (void)addAudioWithAssets:(id)a0;
- (void)removeAudioWithAssets:(id)a0;
- (void)removeAudioAsset:(id)a0;
- (void)removeAllAudioAsset;
- (void)acc_addAudioAssetDict:(id)a0 fromVideoData:(id)a1;
- (id)addVideoWithAsset:(id)a0;
- (id)addSubTrackWithAsset:(id)a0;
- (void)moveVideoAssetFromIndex:(long long)a0 toIndex:(long long)a1;
- (void)acc_addVideoAssetDict:(id)a0 fromVideoData:(id)a1;
- (void)acc_replaceVideoAssetAtIndex:(long long)a0 withAsset:(id)a1 fromVideoData:(id)a2;
- (void)acc_replaceVideoAssetsInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a0 withAssets:(id)a1 fromVideoData:(id)a2;
- (id)acc_videoAssetAtIndex:(unsigned long long)a0;
- (void)removeAllVideoAsset;
- (void)removeVideoAsset:(id)a0;
- (void)removeVideoAssetForAllTrack:(id)a0;
- (void)setMetaData:(id)a0 recordInfo:(long long)a1 MD5:(id)a2 needStore:(BOOL)a3;
- (struct { long long x0; int x1; unsigned int x2; long long x3; })getVideoDuration:(id)a0;
- (void)updateVideoTimeClipInfoWithClipRange:(id)a0 asset:(id)a1;
- (struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })videoTimeClipRangeForAsset:(id)a0;
- (void)configVideoTimeClipInfo:(id)a0;
- (void)configVideoTimeClipInfoWithClipRange:(id)a0 asset:(id)a1;
- (void)addAudioTimeClipInfos:(id)a0;
- (void)updateAudioTimeClipInfoWithClipRange:(id)a0 asset:(id)a1;
- (void)removeAudioTimeClipInfoWithAsset:(id)a0;
- (void)setMetaData:(id)a0 recordInfo:(long long)a1;
- (void)updateCanvasInfoWithCanvasSource:(id)a0 asset:(id)a1;
- (id)canvasConfigWithAsset:(id)a0;
- (void)updateTemplateConfigsMap:(id)a0 withDraftID:(id)a1;
- (void)updateTemplateConfigsMap:(id)a0 withDraftFolder:(id)a1;
- (void)updateCanvasConfigsMapWithConfig:(id)a0 asset:(id)a1;
- (void)updateCanvasConfigsMapWithConfigAndCommit:(id)a0 asset:(id)a1;
- (void)updateMovieAnimationTypeWithFilter:(id)a0 asset:(id)a1;
- (void)removeAllPitchAudioFilters;
- (void)clearAllEffectAndTimeMachine;
- (void)clearReverseAsset;
- (void)effect_cleanOperation;
- (void)effect_reCalculateEffectiveTimeRange;
- (double)effect_currentTimeMachineDurationWithType:(long long)a0;
- (void)updatePhotoAssetInfoWithURL:(id)a0 asset:(id)a1;
- (void)updatePhotoAssetsImageInfoWithImage:(id)a0 asset:(id)a1;
- (void)setImageMovieInfoWithUIImages:(id)a0 imageShowDuration:(id)a1;
- (void)awe_muteOriginalAudio;
- (void)awe_setMutedWithAsset:(id)a0;
- (void)muteMicrophone:(BOOL)a0;
- (void)acc_convertCanvasSizeFromSize:(struct CGSize { double x0; double x1; })a0 toSize:(struct CGSize { double x0; double x1; })a1;
- (void)acc_getRestoreVideoDurationWithSegmentCompletion:(id /* block */)a0;
- (id)acc_safeAudioTimeClipInfo:(id)a0;
- (double)acc_totalVideoDuration;
- (BOOL)acc_audioAssetEqualTo:(id)a0;
- (BOOL)acc_videoAssetEqualTo:(id)a0;
- (void)updateCacheDirPath:(id)a0;
- (id)videoDataUUID;
- (id)audioClipRangeOfAsset:(id)a0;
- (void)beginEdit;
- (id)nleWillBeginRender:(id)a0;
- (BOOL)moveResourceToDraftFolder:(id)a0;
- (void)monitorDuplicateResourceWithPath:(id)a0 andParams:(id)a1;
- (void)syncDataBeforeSaveDraft;
- (id)initWithNLEModel:(id)a0 nle:(id)a1;
- (id)initWithNLEModel:(id)a0 nle:(id)a1 forbidUpdateNLEModel:(BOOL)a2;
- (void)updateOldDraftDataToNLE;
- (id)p_syncNLE;
- (void)_setupNLEStatus;
- (void)syncTextTemplate;
- (void)p_syncVE;
- (void)generateAssetVideos:(id)a0 slot:(id)a1 nle:(id)a2;
- (long long)htsTimeMachineTypeFromNLETimeEffectType:(unsigned long long)a0;
- (unsigned long long)nleTimeEffectTypeFromHtsTimeMachineType:(long long)a0;
- (void)nleDidEndRender:(id)a0;
- (void)refreshNLEStatus;
- (void)pushUpdateType:(long long)a0;
- (BOOL)audioTrackCannotHandleWithAudioAsset:(id)a0;
- (id)addPictureWithURL:(id)a0 duration:(double)a1;
- (void)updateCanvasConfigsMapWithConfig:(id)a0 trackSlot:(id)a1;
- (void)acc_fixAudioClipRange;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)prepareWithCompletion:(id /* block */)a0;

@end
