@class ACCRecordGestureActionHandler, UITapGestureRecognizer, NSString, UIPinchGestureRecognizer, UIPanGestureRecognizer, AWEStudioRecorderFeatureGestureConfig, NSMutableSet, ACCRecordTapGestureRecognizer, ACCEffectGestureActionHandler;
@protocol ACCRecordSwitchModeService, ACCRecordPropService, ACCCameraSwapService, ACCRecorderViewContainer, ACCRecordGestureService, ACCRecordSystemLivePhotoService, ACCRecordTemplateVideoPreviewService, ACCRecordARService, AWEStudioRawTypePropServiceProtocol, ACCDuetSessionSwtichService, ACCFilterService, ACCCameraService;

@interface ACCRecordGestureComponent : ACCFeatureComponent <UIGestureRecognizerDelegate>

@property (retain, nonatomic) AWEStudioRecorderFeatureGestureConfig *featureConfig;
@property (retain, nonatomic) NSMutableSet *sdkGesturesSet;
@property (retain, nonatomic) UITapGestureRecognizer *cameraTapGesture;
@property (retain, nonatomic) ACCRecordTapGestureRecognizer *doubleTapSwitchCamera;
@property (retain, nonatomic) UIPinchGestureRecognizer *recordPinchGesture;
@property (retain, nonatomic) UIPanGestureRecognizer *exposureCompensationPanGesture;
@property (retain, nonatomic) UIPanGestureRecognizer *sdkDuetLayoutPanGesture;
@property (retain, nonatomic) id<ACCRecorderViewContainer> viewContainer;
@property (retain, nonatomic) ACCRecordGestureActionHandler *cameraActionHandler;
@property (retain, nonatomic) ACCEffectGestureActionHandler *sdkActionHandler;
@property (nonatomic) BOOL hasAddGesture;
@property (nonatomic) BOOL sdkGestureHasDisabled;
@property (nonatomic) BOOL hasAddDuetLayoutGesture;
@property (nonatomic) BOOL manuallyDisableSDKGestures;
@property (retain, nonatomic) id<ACCRecordARService> arService;
@property (retain, nonatomic) id<ACCCameraService> cameraService;
@property (weak, nonatomic) id<ACCCameraSwapService> cameraSwapService;
@property (retain, nonatomic) id<ACCFilterService> filterService;
@property (retain, nonatomic) id<ACCRecordPropService> propService;
@property (retain, nonatomic) id<ACCRecordGestureService> gestureService;
@property (retain, nonatomic) id<ACCRecordSwitchModeService> switchModeService;
@property (retain, nonatomic) id<AWEStudioRawTypePropServiceProtocol> rawTypePropService;
@property (nonatomic) BOOL disableDoubleTapGesture;
@property (nonatomic) BOOL disablePinchZoomGesture;
@property (retain, nonatomic) id<ACCDuetSessionSwtichService> duetSessionSwtichService;
@property (retain, nonatomic) id<ACCRecordSystemLivePhotoService> systemLivePhotoService;
@property (retain, nonatomic) id<ACCRecordTemplateVideoPreviewService> templateVideoPreviewService;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)componentDidMount;
- (unsigned long long)preferredLoadPhase;
- (id)serviceBinding;
- (void)addGestures;
- (void)addLongPressGesture;
- (void)addPinchGestureForZoom;
- (void)handlePinchGestureForZoom:(id)a0;
- (void)p_bindViewModels;
- (void)p_readExistData;
- (void)handleCameraDoubleTapGesture:(id)a0;
- (void)handleCameraLongPressGesture:(id)a0;
- (void)_setupActionHandler;
- (id)filterCameraPreviewDeliveryTouches:(id)a0;
- (void)updateGestureStateForSticker:(id)a0;
- (void)manuallyDisableSDKGesturesIfNeeded;
- (void)manuallyEnableSDKGesturesIfNeeded;
- (void)addSingleTapGesture;
- (void)addDoubleTapGesture;
- (void)addGesturesForSDK;
- (void)disableSDKGesturesAndDisableTapFocus:(BOOL)a0;
- (void)addPinchGestureForZoomWithView:(id)a0;
- (void)addSingleTapGestureWithView:(id)a0;
- (void)handleCameraTapGesture:(id)a0;
- (void)addDoubleTapGestureWithView:(id)a0;
- (void)addLongPressGestureWithView:(id)a0;
- (void)addPanGestureWithView:(id)a0;
- (void)handleExposureCompensationPanGesture:(id)a0;
- (void)addSDKPanGestureRecognizer;
- (void)addSDKPinchGestureRecognizer;
- (void)addSDKRotationGestureRecognizer;
- (void)addSDKTapGestureRecognizer;
- (void)addSDKLongPressGestureRecognizer;
- (void)handleSDKPanGesture:(id)a0;
- (void)handleDuetSDKPanGesture:(id)a0;
- (void)handleSDKPinchGesture:(id)a0;
- (void)handleSDKRotationGesture:(id)a0;
- (void)handleSDKTapGesture:(id)a0;
- (void)handleSDKLongPressGesture:(id)a0;
- (void)p_handleSDKPanGesture:(id)a0;
- (void)addSDKDuetLayoutPanGestureRecognizer;
- (void)disableNormalRecordGestures;
- (void)disablePinchZoomGesture:(BOOL)a0;
- (void)disableDoubleTapGesture:(BOOL)a0;
- (void)duetLayoutDidApplyDuetEffect:(BOOL)a0;
- (id)p_currentEffectIdentifier;
- (void)addPanGesture;
- (void).cxx_destruct;
- (BOOL)gestureRecognizer:(id)a0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)a1;
- (BOOL)gestureRecognizer:(id)a0 shouldReceiveTouch:(id)a1;
- (BOOL)gestureRecognizer:(id)a0 shouldRequireFailureOfGestureRecognizer:(id)a1;

@end
