@class UIView, NSString, AWETextImageTagModel, AWEStoryTextImageModel, ACCVideoDataClipRangeStorageModel, UIImageView, ACCTextStickerTextView, UITextView, NSMutableArray, ACCTextStickerInputController;
@protocol ACCTextStickerViewDelegate, ACCStickerContainerProtocol, ACCStickerProtocol;

@interface ACCTextStickerView : UIView <UIGestureRecognizerDelegate, ACCTextStickerInputControllerDelegate, ACCTextViewDelegate, ACCStickerEditContentProtocol>

@property (nonatomic) double minCenterCanBeMoved;
@property (retain, nonatomic) ACCTextStickerTextView *textView;
@property (retain, nonatomic) AWEStoryTextImageModel *textModel;
@property (copy, nonatomic) NSString *originContentBeforeEdit;
@property (retain, nonatomic) AWETextImageTagModel *originTagBeforeEdit;
@property (weak, nonatomic) ACCTextStickerInputController *inputControllerInjected;
@property (retain, nonatomic) ACCTextStickerInputController *inputController;
@property (nonatomic) double currentScale;
@property (readonly, nonatomic) BOOL enableTextStickerSocialBind;
@property (readonly, nonatomic) unsigned long long viewOptions;
@property (nonatomic) BOOL isAuto;
@property (nonatomic) long long autoCount;
@property (nonatomic) double autoDate;
@property (nonatomic) BOOL fromClickEdit;
@property (nonatomic) struct CGPoint { double x; double y; } editCenter;
@property (retain, nonatomic) UIImageView *imgTagView;
@property (nonatomic) BOOL enableEdit;
@property (weak, nonatomic) id<ACCTextStickerViewDelegate> delegate;
@property (nonatomic) double defaultFontSize;
@property (retain, nonatomic) UITextView *toEditTextView;
@property (retain, nonatomic) NSString *textStickerId;
@property (retain, nonatomic) NSMutableArray *recommendTitleId;
@property (retain, nonatomic) NSMutableArray *recommendTypeId;
@property (retain, nonatomic) ACCVideoDataClipRangeStorageModel *timeEditingRange;
@property (copy, nonatomic) id /* block */ textChangedBlock;
@property (copy, nonatomic) id /* block */ searchKeyworkChangedBlock;
@property (copy, nonatomic) id /* block */ willChangeTextInRangeBlock;
@property (copy, nonatomic) id /* block */ didChangeTextInRangeBlock;
@property (copy, nonatomic) id /* block */ didTouchTextStickerView;
@property (nonatomic) struct CGPoint { double x; double y; } editCenterOffset;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } editingConstraintFrame;
@property (nonatomic) BOOL forceEnableEdit;
@property (nonatomic) unsigned long long fromXiangSuType;
@property (copy, nonatomic) NSString *creationId;
@property (nonatomic) BOOL needPlaceHolder;
@property (nonatomic) BOOL disableDelete;
@property (copy, nonatomic) id /* block */ textTemplateModelChangeBlock;
@property (nonatomic) BOOL deselectWhenNotDisplay;
@property (weak, nonatomic) UIView<ACCStickerProtocol> *wrapperView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, getter=isTransparent) BOOL transparent;
@property (nonatomic) long long stickerId;
@property (copy, nonatomic) id /* block */ triggerDragDeleteCallback;
@property (copy, nonatomic) id /* block */ coordinateDidChange;
@property (weak, nonatomic) id<ACCStickerContainerProtocol> stickerContainer;

- (void)textStickerInputController:(id)a0 didUpdateSearchStatus:(BOOL)a1 Keyword:(id)a2 searchType:(unsigned long long)a3;
- (void)textStickerInputController:(id)a0 onExtraInfoDidChanged:(id)a1;
- (void)textStickerInputController:(id)a0 textView:(id)a1 onReplaceText:(id)a2 withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a3;
- (void)updateDisplay;
- (void)contentDidUpdateToScale:(double)a0;
- (void)updateWithCurrentPlayerTime:(double)a0;
- (id)copyForContext:(id)a0;
- (void)updateWithInstance:(id)a0 context:(id)a1;
- (id)validText;
- (struct CGSize { double x0; double x1; })textContentSize;
- (void)panAction:(id)a0;
- (void)updateFontScale:(double)a0;
- (id)initWithTextInfo:(id)a0 options:(unsigned long long)a1 delegate:(id)a2;
- (void)createImageTagIfNeeded;
- (BOOL)isTemplateSticker;
- (void)updateEditingFramesForUseRefactorWithScale:(BOOL)a0;
- (void)updateEditingFrames;
- (void)scaleIfNeeded;
- (void)removeImageTagIfNeeded;
- (void)updateImageTagModel;
- (void)handleTextViewContentChanged;
- (double)adjustedFontSize:(double)a0 scale:(double)a1;
- (void)updateTipsDisplayWith:(id)a0;
- (void)resetTextViewAlignment;
- (id)initWithTextInfo:(id)a0 options:(unsigned long long)a1;
- (void)resetContentSnapIfNeed;
- (void)restoreToSuperView:(id)a0 animationDuration:(double)a1 animationBlock:(id /* block */)a2 completion:(id /* block */)a3;
- (id)bubbleHelper;
- (double)bubbleAutoDismissDate;
- (long long)bubbleAutoDismissCount;
- (void)updateBubbleAutoDismissCount:(long long)a0;
- (void)updateBubbleAutoDismissDate;
- (void)revertStickerViewTextModelwith:(id)a0;
- (void)startTemplateStickerEdit;
- (long long)imageTagTypeWithContent:(id)a0;
- (void)injectSocialInputController:(id)a0;
- (void)showTextViewCursor;
- (void)hideTextViewCursor;
- (void)updateInputControllerTextView:(id)a0;
- (void)transportToEditWithSuperView:(id)a0 animation:(id /* block */)a1 animationDuration:(double)a2 completion:(id /* block */)a3;
- (void)transportToEditWithNewSuperView:(id)a0 Animation:(id /* block */)a1 animationDuration:(double)a2 completion:(id /* block */)a3;
- (void)transportToNormalWithOriginalSuperView:(id)a0 Animation:(id /* block */)a1 animationDuration:(double)a2 completion:(id /* block */)a3;
- (void)updateBubbleStatusAfterEdit;
- (void)showBubbleAutomaticallyIfNeededWithX:(long long)a0 y:(long long)a1 expireInterval:(double)a2;
- (void)updateTipOffsetForEditPage;
- (void)hideTipOffsetForEditPage;
- (id)copy;
- (void).cxx_destruct;
- (BOOL)isFirstResponder;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)textViewDidChange:(id)a0;
- (void)textViewDidChangeSelection:(id)a0;
- (BOOL)textView:(id)a0 shouldChangeTextInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1 replacementText:(id)a2;
- (id)stickerView;
- (void)updateFrame;

@end
