@class AWEVideoPublishViewModel, AWETextTopBar, ACCTextReadEffectSelectPanelModel, ACCTextStickerSnap, ACCTextStickerEditInputHandler, AWETextStickerStylePreferenceModel, ACCTemplateTextStickerBorderViewList, NSString, ACCAnimatedButton, UIControl, ACCTextStickerEditWrapedToobarContainer, ACCTextStickerView, UITextView, NSMutableDictionary, ACCTextTypeFaceViewController, ACCTextStyleViewController, UIView, AWEEditGradientView, AWEModernTextToolBar, ACCSocialStickerEditToolbar, AWETextTemplateController;
@protocol ACCTextReadEffectSelectViewProtocol, ACCTextStickerEditorSliderProtocol, ACCTextStickerEditViewDelegate, ACCTextReaderTrackerProtocol;

@interface ACCTextStickerEditView : AWEStudioExcludeSelfView <ACCTextStickerEditWrapedToobarContainerDelegate, AWETextTemplateControllerDelegate, ACCTextStickerEditorSliderDelegate, ACCTextStickerEditViewProtocol>

@property (nonatomic) unsigned long long viewOptions;
@property (retain, nonatomic) ACCTextStickerView *editingStickerView;
@property (retain, nonatomic) ACCTextStickerSnap *stickerBeforeEditSnap;
@property (retain, nonatomic) ACCTextStickerSnap *stickerTextImageModeSnap;
@property (weak, nonatomic) UIView *orignalSuperView;
@property (retain, nonatomic) UIControl<ACCTextStickerEditorSliderProtocol> *fontSizeSlider;
@property (nonatomic) double trackParamFontSize;
@property (retain, nonatomic) ACCAnimatedButton *saveButton;
@property (retain, nonatomic) ACCAnimatedButton *cancelButton;
@property (retain, nonatomic) UIView *lowerMaskView;
@property (retain, nonatomic) AWEEditGradientView *upperMaskView;
@property (retain, nonatomic) ACCSocialStickerEditToolbar *socialToolbar;
@property (retain, nonatomic) AWEModernTextToolBar *modernTextToolBar;
@property (retain, nonatomic) AWETextTopBar *topTextToolBar;
@property (retain, nonatomic) ACCTextStickerEditWrapedToobarContainer *toolbarContainer;
@property (nonatomic) double panelHeight;
@property (nonatomic) double keyboardHeight;
@property (nonatomic) BOOL fromTextMode;
@property (nonatomic) unsigned long long lastInputMode;
@property (retain, nonatomic) AWETextTemplateController *textTemplateController;
@property (retain, nonatomic) UIView *textTemplateBorderView;
@property (retain, nonatomic) ACCTemplateTextStickerBorderViewList *textTemplateBorderViewList;
@property (retain, nonatomic) UIView *multiLinesTextTemplateMaskView;
@property (retain, nonatomic) AWEEditGradientView *textTemplateTopMaskView;
@property (retain, nonatomic) UITextView *fakeTextInputView;
@property (retain, nonatomic) ACCTextStickerEditInputHandler *inputHelper;
@property (nonatomic) long long totalStickerMentionCountExcludeSelfWhenEditing;
@property (nonatomic) long long totalStickerHashtagCountExcludeSelfWhenEditing;
@property (nonatomic) BOOL hasShowedTemplateDisableActionToast;
@property (nonatomic) BOOL editingStyle;
@property (nonatomic) BOOL needEditInSecondaryVC;
@property (nonatomic) BOOL stickerStopEditProcessing;
@property (nonatomic) BOOL stickerStartEditProcessing;
@property (nonatomic) BOOL forbidExitEditVC;
@property (nonatomic) BOOL isTextTemplateUsed;
@property (nonatomic) BOOL isTextScaleChanged;
@property (nonatomic) BOOL isTextStyleChanged;
@property (nonatomic) BOOL isTextFontChanged;
@property (retain, nonatomic) NSMutableDictionary *stopEditTrackParams;
@property (nonatomic) BOOL hasTrackedForInputText;
@property (retain, nonatomic) UIView<ACCTextReadEffectSelectViewProtocol> *soundEffectsSelectionView;
@property (copy, nonatomic) NSString *currentCompeleteText;
@property (nonatomic) BOOL isUseSug;
@property (nonatomic) BOOL isAIImageTextEditing;
@property (nonatomic) BOOL isKeyboardShowing;
@property (readonly, weak, nonatomic) id<ACCTextStickerEditViewDelegate> delegate;
@property (nonatomic) BOOL isWillShowing;
@property (nonatomic) long long maxWordCount;
@property (nonatomic) unsigned long long editMode;
@property (weak, nonatomic) AWEVideoPublishViewModel *publishViewModel;
@property (copy, nonatomic) id /* block */ didSelectedColorBlock;
@property (copy, nonatomic) id /* block */ didSelectedFontBlock;
@property (copy, nonatomic) id /* block */ didChangeStyleBlock;
@property (copy, nonatomic) id /* block */ didChangeAlignmentBlock;
@property (copy, nonatomic) id /* block */ keyboardDidShowBlock;
@property (copy, nonatomic) id /* block */ didSelectTTSAudio;
@property (copy, nonatomic) id /* block */ didTapFinishCallback;
@property (copy, nonatomic) id /* block */ didTapCancelCallback;
@property (copy, nonatomic) id /* block */ textTemplateSetupCallback;
@property (copy, nonatomic) id /* block */ onEditFinishedBlock;
@property (copy, nonatomic) id /* block */ finishEditAnimationBlock;
@property (copy, nonatomic) id /* block */ startEditBlock;
@property (copy, nonatomic) id /* block */ startSelectingTTSAudioBlock;
@property (copy, nonatomic) id /* block */ updateTextReaderModelBlock;
@property (copy, nonatomic) id /* block */ getTextReaderModelBlock;
@property (copy, nonatomic) id /* block */ shouldDisableTextReaderEntrance;
@property (copy, nonatomic) id /* block */ stickerTotalHashtagBindCountProvider;
@property (copy, nonatomic) id /* block */ stickerTotalMentionBindCountProvider;
@property (copy, nonatomic) id /* block */ triggeredSocialEntraceBlock;
@property (copy, nonatomic) id /* block */ didSelectedToolbarColorItemBlock;
@property (copy, nonatomic) id /* block */ exitTextStickerEditView;
@property (copy, nonatomic) id /* block */ clearEmptyTextSticker;
@property (copy, nonatomic) id /* block */ startEditStickerView;
@property (copy, nonatomic) id /* block */ updateTextTemplateTextBlock;
@property (copy, nonatomic) id /* block */ updateTextTemplateFontBlock;
@property (copy, nonatomic) id /* block */ updateTextTemplateColorBlock;
@property (copy, nonatomic) id /* block */ updateTextTemplateAlignmentBlock;
@property (copy, nonatomic) id /* block */ updateTextTemplateTextStyleBlock;
@property (copy, nonatomic) id /* block */ cleanTextReadData;
@property (copy, nonatomic) id /* block */ addNewTextStickerWithInitialText;
@property (copy, nonatomic) id /* block */ willShowTTSPanelBlock;
@property (copy, nonatomic) id /* block */ willDismissTTSPanelBlock;
@property (copy, nonatomic) id /* block */ hasBindedTemplateSpeakNameBlock;
@property (copy, nonatomic) id /* block */ speedRateBlock;
@property (retain, nonatomic) AWETextStickerStylePreferenceModel *stylePreferenceModel;
@property (retain, nonatomic) ACCTextReadEffectSelectPanelModel *ttsPanelModel;
@property (weak, nonatomic) id<ACCTextReaderTrackerProtocol> tracker;
@property (nonatomic) BOOL hasFlashMobProperty;
@property (nonatomic) BOOL inTextStickerSecondaryVC;
@property (nonatomic) BOOL editingStickerTransfering;
@property (retain, nonatomic) ACCTextTypeFaceViewController *textTypeFaceController;
@property (retain, nonatomic) ACCTextStyleViewController *textStyleController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createTemplatePickerConfig;

- (void)setFakeTextViewFirstResponder;
- (id)textModel;
- (void)beginEdit;
- (void)confirmBtnClicked;
- (id)trackCommonParams;
- (void)p_setup;
- (void)p_showToastWithText:(id)a0;
- (id)aiMemoriesCommonParams;
- (void)updateSocialBarShow:(BOOL)a0;
- (BOOL)optimizeNewTextStickerToolsPreview;
- (void)updateFontSizeSlider;
- (void)fontSizeSliderValueDidChanged:(id)a0;
- (void)stickerPickerControllerDidFinishLoadCategories:(id)a0;
- (void)stickerPickerController:(id)a0 didSelectSticker:(id)a1 extraParams:(id)a2 indexPath:(id)a3 categoryIdentifier:(id)a4;
- (void)stickerPickerController:(id)a0 didDeselectSticker:(id)a1;
- (void)trackDidDeselectSticker:(id)a0 cancelMethod:(id)a1;
- (void)sliderInteractionDidBegin:(id)a0;
- (void)sliderInteractionDidEnd:(id)a0;
- (void)startEditStickerView:(id)a0;
- (void)didClickedTextMaskView;
- (void)didClickedSaveButton:(id)a0;
- (void)finishEdit;
- (void)handleKeyboardChangeFrameNoti:(id)a0;
- (void)removeTextTemplateBorderView;
- (void)showTextTemplateBorderView;
- (void)updateTextTemplateBorderViewsWithSizeDic:(id)a0 positionDic:(id)a1 hidden:(BOOL)a2 scale:(double)a3;
- (void)updateEditViewWithMaxWordCount:(long long)a0;
- (void)presetTextViewDidChange:(id)a0;
- (BOOL)presetTextView:(id)a0 shouldChangeTextInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1 replacementText:(id)a2;
- (id)initWithOptions:(unsigned long long)a0 fromTextMode:(BOOL)a1 publishViewModel:(id)a2 delegate:(id)a3;
- (unsigned long long)textStickerEditStyle;
- (id)lowerMaskViewColor;
- (BOOL)isCurrentDragActive;
- (void)stopEditFromSaveButton:(BOOL)a0;
- (void)updateStopEditTrackerParamsWithAction:(id)a0;
- (void)didClickedCancelButton:(id)a0;
- (void)updateTopTextToolBarWithShow:(BOOL)a0;
- (void)setupLowerMask;
- (BOOL)isSupportTextTemplateSticker;
- (void)setupSaveButton;
- (BOOL)isUseTextTemplateStickerUIAndData;
- (void)setupUpperMask;
- (void)setupTopTextToolBar;
- (void)setupCustomTextInputBlock;
- (void)setupFakeTextInputView;
- (void)setupFontSizeSlider;
- (void)p_onSelectedFont:(id)a0 atIndexPath:(id)a1;
- (void)p_onSelectedColor:(id)a0 atIndexPath:(id)a1;
- (void)didClickToolbarTextStyleButtonWithStyle:(unsigned long long)a0;
- (void)didClickToolbarAlignmentButtonWithType:(long long)a0;
- (void)p_registerAllToolbarHandlers;
- (BOOL)p_isTextTemplateTab;
- (BOOL)p_textTemplateIsMultiLines;
- (BOOL)isStickerUsedTextTemplate:(id)a0;
- (void)p_registerToolbarItemConfigProvider:(id /* block */)a0 clickHandler:(id /* block */)a1 forItemIdentity:(id)a2;
- (void)didClickToolbarAlignmentButton;
- (void)didClickToolbarTextStyleButton;
- (BOOL)p_isTextReaderEnableForCurrentText;
- (BOOL)p_isTextReaderEffectiveForCurrentText;
- (void)didClickToolbarTextReaderButton;
- (void)layoutFontSizeSlider:(double)a0;
- (void)handleTextDidChangeNotification:(id)a0;
- (void)handleTextBeginEditNotification:(id)a0;
- (void)updateTextConstraintFrame;
- (void)showSocialBarWithKeyboardNotification:(id)a0;
- (void)updateToolBarTextReaderIcon;
- (void)stopEditFromSaveButton:(BOOL)a0 animated:(BOOL)a1;
- (void)removeMultiLinesTextTemplateMaskView;
- (void)resetEditPanelController;
- (void)transportToNormalStatus:(BOOL)a0 animationBlock:(id /* block */)a1 completion:(id /* block */)a2;
- (void)cacheCurrentSelectInfo;
- (void)updateTemplateTextStickerStatusForSave;
- (void)recordTextStickerTrackInfo;
- (void)resetCurrentEditingContext;
- (id)prepareTextModelInitialInfo:(id)a0;
- (void)updateModernTextBarWithTextModel:(id)a0;
- (void)updateTextTemplateControllerWith:(id)a0 usedTextTemplate:(BOOL)a1;
- (void)updatetextTypeFacePanelWith:(id)a0;
- (void)startEditStickerView:(id)a0 inputMode:(unsigned long long)a1;
- (void)snapTextStickerViewIfNeeded:(id)a0;
- (void)updateTextStickerEditPanelWith:(id)a0;
- (void)bindInputAccessoryViewWithToolBarType:(unsigned long long)a0;
- (void)p_bindInputAccessoryView:(unsigned long long)a0;
- (void)transportToEditStatus:(id)a0;
- (void)convertEditViewIfNeedWithCompletion:(id /* block */)a0;
- (void)p_resetTextToobarColorViewShowStatus;
- (void)p_associationSocialBindIfEnableWithInputMode:(unsigned long long)a0;
- (void)p_associationTextReaderIfEnableWithInputMode:(unsigned long long)a0;
- (void)fontSizeSliderStartEdit;
- (BOOL)p_shouldFetchTemplateTextRead:(id)a0;
- (void)fetchSoundEffectAndFindEffect:(id)a0 completion:(id /* block */)a1;
- (BOOL)newTextStickerBugFix;
- (void)setupTextStickerWithTemplateStatus;
- (id)getToolContentView:(long long)a0;
- (BOOL)supportTextStickerSocialBind;
- (void)updateSearchKeyworkBarStatus:(BOOL)a0 keywork:(id)a1 searchType:(unsigned long long)a2;
- (void)trackForInputTextIfNeeded;
- (void)refreshSocialBarFrame;
- (void)templateTextStickerBorderViewsEditBlockWith:(long long)a0;
- (void)showMultiLinesTextTemplateMaskView;
- (void)trackTemplateInputEvent:(id)a0;
- (void)templateTextChangeTo:(id)a0 textRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1;
- (void)trackTemplateDeselectWithTemplate:(id)a0 method:(id)a1;
- (void)templateText:(id)a0 selectedRangeChangeTo:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1;
- (id)modernTextBarConfig;
- (void)setModernTextToolBarSwitchBlock;
- (void)handleDeSelectTemplateSwitch;
- (void)revertTextTemplateIfNeeded;
- (void)trackTemplateSwitcherTabChangedWithType:(unsigned long long)a0;
- (void)initialTextTemplateStatusWithStickerView:(id)a0;
- (void)updateTextTemplateAlignment:(long long)a0;
- (BOOL)p_displayTextTemplateStyleValue;
- (void)trackTemplateInputEvent:(id)a0 extraParams:(id)a1;
- (void)trackTextEditNumToast;
- (id)initWithOptions:(unsigned long long)a0 publishViewModel:(id)a1 delegate:(id)a2;
- (id)initWithOptions:(unsigned long long)a0 fromTextMode:(BOOL)a1 publishViewModel:(id)a2;
- (void)pauseCurrentEditingSticker:(id /* block */)a0;
- (void)stopEditWithOutAnimation:(BOOL)a0;
- (void)switchEditingStickerToKeyboardInputMode;
- (void)updateTextTemplateBorderViewsForNewWithSizeDic:(id)a0 positionDic:(id)a1 hidden:(BOOL)a2;
- (void)updateTextTemplateBorderViewWithCenter:(struct CGPoint { double x0; double x1; })a0 hidden:(BOOL)a1 scale:(double)a2;
- (void)updateTextTemplateBorderViewForNewWithCenter:(struct CGPoint { double x0; double x1; })a0 size:(struct CGSize { double x0; double x1; })a1 hidden:(BOOL)a2;
- (void)updateMultiLinesTextTemplateMaskViewWithCenter:(struct CGPoint { double x0; double x1; })a0 hidden:(BOOL)a1 scale:(double)a2;
- (void)updateMultiLinesTextTemplateMaskViewForNewWithCenter:(struct CGPoint { double x0; double x1; })a0 size:(struct CGSize { double x0; double x1; })a1 hidden:(BOOL)a2;
- (void)reloadToolBarContainer;
- (void)toggleTextReadingToolHidden:(BOOL)a0;
- (void)updateTextStickerEditPanel:(long long)a0 textContent:(id)a1;
- (void)trackChangeStickerContentStyleWitnEvent:(id)a0;
- (void)keyboardDidHide:(id)a0;
- (void).cxx_destruct;
- (BOOL)resignFirstResponder;
- (void)keyboardWillShow:(id)a0;
- (void)keyboardWillHide:(id)a0;
- (void)dealloc;
- (void)keyboardDidShow:(id)a0;
- (void)setContentText:(id)a0;
- (void)setupCancelButton;
- (void)addObservers;
- (void)removeObservers;

@end
