@class NSString, NSMutableDictionary;
@protocol IESVideoPlayerProtocol;

@interface AFDPureModePagePlaybackController : AWEBaseController <AWENowPlayingInfoPlayerProtocol, AWEBGPlayUserSettingsChangedMessage, AFDPureModePageControllerProtocol>

@property (retain, nonatomic) NSMutableDictionary *nowPlayingInfo;
@property (nonatomic) BOOL hasSetUPControlCenter;
@property (nonatomic) BOOL hasAddNotification;
@property (nonatomic) long long startAwemeIndex;
@property (nonatomic) double startStayTime;
@property (nonatomic) BOOL isEnterBackgroundFromPiP;
@property (nonatomic) long long currentAwemeIndex;
@property (retain, nonatomic) id<IESVideoPlayerProtocol> playerController;
@property (nonatomic) BOOL pausedByNotLoop;
@property (nonatomic) BOOL isPlaying;
@property (nonatomic) BOOL isPausedInBackground;
@property (nonatomic) BOOL needResumeWhenAudioRecover;
@property (nonatomic) BOOL isLoopedWhenPause;
@property (nonatomic) BOOL isAlbumFinished;
@property (nonatomic) double albumLastPlayTime;
@property (nonatomic) BOOL disableReportBGPlayStart;
@property (nonatomic) BOOL shouldReportBGPlayEnd;
@property (nonatomic) double bgPlayStartTime;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)playForRemoteControl;
- (void)pauseForRemoteControl;
- (void)seekToTimeForRemoteControl:(double)a0;
- (void)playPrevForRemoteControl;
- (void)playNextForRemoteControl;
- (BOOL)canPlayForRemoteControl;
- (BOOL)canPauseForRemoteControl;
- (BOOL)canPlayPrevForRemoteControl;
- (BOOL)canPlayNextForRemoteControl;
- (BOOL)canSeekForRemoteControl;
- (BOOL)canAutoPlayNextAweme:(long long)a0;
- (void)videoWillLoopTimes:(long long)a0;
- (void)player:(id)a0 updatePlayTime:(double)a1 canPlayTime:(double)a2 totalTime:(double)a3;
- (void)player:(id)a0 didChangePlaybackToAction:(long long)a1;
- (void)addNotifications;
- (void)handleAppWillResignActiveNotification:(id)a0;
- (void)updateNowPlayingInfoPlayback;
- (void)handleAudioSessionInterruptionNotification:(id)a0;
- (id)liveModuleService;
- (void)trackStayTime;
- (void)handleAppWillTerminateNotification:(id)a0;
- (BOOL)enableBGPlaySettings;
- (BOOL)supportPinchSwitch;
- (void)backgroundPlayDidChangedUserSettingsToType:(long long)a0;
- (void)handleAppProtectedDataWillBecomeUnavailableNotification:(id)a0;
- (void)handleAppDidBecomeActiveNotification:(id)a0;
- (void)trackBGPlayStartIfNeeded;
- (void)trackBGPlayEndWithExitMethod:(long long)a0;
- (long long)getSkipIndexOffset:(BOOL)a0;
- (void)resetControlCenter;
- (void)setUpControlCenter;
- (BOOL)shouldUpdateNowPlayingInfo;
- (BOOL)canPlaybackLoop;
- (void)updateNowPlayingInfoProgress:(double)a0;
- (BOOL)shouldShowPlayNextRemoteControl;
- (void)handleAppDidEnterBackgroundNotification:(id)a0;
- (BOOL)enableFollowSwitch;
- (void)removeSkipCommandTarget;
- (BOOL)fixBGPlayPlayTime;
- (void)updatePlayerControllerLogExtra:(id)a0;
- (void)addSkipCommandTarget;
- (long long)handleSkipForward:(id)a0;
- (long long)handleSkipBackward:(id)a0;
- (void)skipByInterval:(double)a0;
- (void)invalidatePlayStrategy;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })artworkRectForImage:(id)a0;
- (id)cropImage:(id)a0 withRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)updateNowPlayingInfoWithPlaybackTime:(double)a0 isPlaying:(BOOL)a1;
- (BOOL)shouldPlayCurrentAwemeInBackground;
- (void)viewDidAppear;
- (void)becomeActive;
- (double)videoDuration;
- (void)willResignActive;
- (void).cxx_destruct;
- (void)setData:(id)a0;
- (void)updateNowPlayingInfo;
- (void)dealloc;
- (void)removeNotifications;
- (long long)skipInterval;
- (void)updateProgress:(double)a0;
- (void)viewDidDisappear;

@end
