@class AWEAwemeModel, NSString, UIView, AWEGradientView, NSDictionary, UIViewController, AFDSlidesView, NSNumber;
@protocol AWEPlayInteractionPaginatedProgressControllerProtocol, AWEPlayInteractionViewControllerNewProtocol, AWEPlayVideoDelegate, AWEAwemeBizPlayVideoProtocol, AWEAwemePlayInteractionUpdateDelegate, AWEAwemePlayInteractionCommerceDelegate, AWEAwemePlayInteractionPlayDelegate, AWEPlayInteractionViewControllerProtocol, AWEPlayVideoViewControllerContainerProtocol, AWEAwemeDisplayViewController, IESVideoPlayerDelegate, AWEAwemePlayVideoTrackProtocol, AWEAwemePlayVideoViewControllerProtocol, IESVideoPlayerProtocol, AWEPlayVideoViewControllerDelegate, AWEAwemePlayInteractionPanelDelegate;

@interface AFDRichAwemeViewController : UIViewController <AFDSlidesViewActionDelegate, AFDRichAwemeFullPageOuterContextProvider, AFDRichAwemeViewControllerProtocol>

@property (retain, nonatomic) UIViewController<AWEAwemePlayVideoViewControllerProtocol, AWEAwemeDisplayViewController, AWEAwemeBizPlayVideoProtocol, AWEAwemePlayVideoTrackProtocol> *videoController;
@property (retain, nonatomic) AWEGradientView *topGradientView;
@property (retain, nonatomic) AWEGradientView *bottomGradientView;
@property (retain, nonatomic) UIView *gradientBackgroundView;
@property (retain, nonatomic) id<AWEPlayInteractionPaginatedProgressControllerProtocol> paginatedProgressController;
@property (nonatomic) BOOL isPlayingBeforeEnterFullPage;
@property (nonatomic) long long lastPlayerState;
@property (weak, nonatomic) id<AWEPlayVideoViewControllerContainerProtocol, AWEPlayVideoDelegate, AWEPlayVideoViewControllerDelegate> playerDelegate;
@property (nonatomic) struct EngineAudioWrapper { } *audioWrapper;
@property (nonatomic) struct EngineVideoWrapper { } *videoWrapper;
@property (weak, nonatomic) id<AWEPlayVideoViewControllerContainerProtocol> container;
@property (nonatomic) BOOL isInFullPageTransition;
@property (nonatomic) BOOL isSliderZooming;
@property (retain, nonatomic) AFDSlidesView *imageSliderView;
@property (retain, nonatomic) AWEAwemeModel *model;
@property (nonatomic) BOOL shouldPrepareForDisplay;
@property (nonatomic) BOOL isInStoryContainer;
@property (retain, nonatomic) NSNumber *clickEnter;
@property (retain, nonatomic) NSNumber *slideType;
@property (retain, nonatomic) NSNumber *detailSlide;
@property (nonatomic) BOOL hasReportClickEnter;
@property (copy, nonatomic) NSString *referString;
@property (copy, nonatomic) NSString *enterFrom;
@property (copy, nonatomic) NSDictionary *context;
@property (copy, nonatomic) NSDictionary *logExtraDict;
@property (copy, nonatomic) NSString *cityInfoString;
@property (copy, nonatomic) NSString *adEventName;
@property (copy, nonatomic) NSString *originEntryEnterMethod;
@property (nonatomic) double defaultSeekToTime;
@property (copy, nonatomic) NSString *reactId;
@property (copy, nonatomic) NSString *ruleId;
@property (weak, nonatomic) id<AWEAwemePlayInteractionPlayDelegate, AWEAwemePlayInteractionPanelDelegate, AWEAwemePlayInteractionCommerceDelegate, AWEAwemePlayInteractionUpdateDelegate, AWEPlayInteractionViewControllerProtocol> interactionDelegate;
@property (weak, nonatomic) id<AWEPlayInteractionViewControllerNewProtocol> interactionNewDelegate;
@property (nonatomic) BOOL shouldAdaptFullScreenThree;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) id<IESVideoPlayerProtocol> playerController;
@property (weak, nonatomic) id<IESVideoPlayerDelegate> videoPlayerDelegate;
@property (nonatomic) long long playState;
@property (readonly, nonatomic) long long loopTimes;
@property (readonly, nonatomic) double currentPlaybackTime;
@property (readonly, nonatomic) double totalPlayTime;
@property (readonly, nonatomic) double playStartTimestamp;
@property (readonly, nonatomic) NSNumber *videoDuration;
@property (nonatomic) long long coverContentMode;
@property (nonatomic) BOOL shouldAdaptFullScreen;
@property (nonatomic) BOOL useNormalCover;
@property (nonatomic) BOOL isScrolledAutomatically;
@property (nonatomic) BOOL isFullScreen;
@property (readonly, copy, nonatomic) id /* block */ playVideo;
@property (nonatomic) BOOL pauseBySingleClick;
@property (nonatomic) BOOL forceUsePlayerVideoPlayEndTracker;
@property (readonly, nonatomic) UIView *contentView;

- (void)pauseWithAnimation;
- (void)playWithAnimation;
- (BOOL)holdStop;
- (void)buildInteractionControllerIfNeeded:(id)a0;
- (BOOL)edgePan:(id)a0;
- (BOOL)shouldResponseToPinchGesture:(id)a0;
- (void)updatePlayerIfNeeded;
- (BOOL)shouldResponseToTapPoint:(struct CGPoint { double x0; double x1; })a0;
- (void)handleTapPoint:(struct CGPoint { double x0; double x1; })a0;
- (id)repostModel;
- (id)repostFromModel;
- (id)getPlayModeWithAutoPlayMode;
- (id)playerExtraTrackInfo;
- (id)internalLogExtraDict;
- (void)updateDefaultSeekToTime:(double)a0;
- (void)updatePlayerBackgroundViewIfNeededWhenLandscape:(BOOL)a0 fromHomepageHot:(BOOL)a1;
- (void)removePlayerBackgroundViewIfNeeded;
- (id)getPlayerBackgroundView;
- (void)paginatedProgressViewDidClickNextPage;
- (void)paginatedProgressViewDidClickPreviousPage;
- (void)updateAudioPlayWithPlayVideoVC:(id)a0;
- (void)sliderDidBeginZooming;
- (void)sliderDidEndZooming;
- (void)sliderWillBeingDragging;
- (void)sliderDidEndDragging;
- (void)sliderDidEndScrolling;
- (void)progressDidUpdateWithIndex:(long long)a0 progress:(double)a1 duration:(double)a2 animated:(BOOL)a3;
- (void)sliderWillStartNextLoop;
- (void)onThemeChanged;
- (void)resetRefreshFlag;
- (void)updateWithImageSliderView:(id)a0;
- (void)setupAndPlayTimer;
- (void)resetProgressOfCurrentImage;
- (void)showImageSlidesViewGradientLayer;
- (void)hideImageSlidesViewGradientLayer;
- (BOOL)shouldResponseToGesture;
- (id)pauseIcon;
- (void)addNotifications;
- (void)postVideoNotificationForAutoPlay;
- (BOOL)isConsistentPlayModeOn;
- (void)onShoppingAnchorFullModeChange:(id)a0;
- (void)initVideoController;
- (void)initSlidesView;
- (void)updateProgressDuringTransition;
- (id)richAwemeViewController;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })targetImageSliderFrameConvertedToView:(id)a0;
- (void)fullPageTransitionWillBegin;
- (void)fullPageTransitionDidEnd;
- (void)fullPageSinkingTransitionWillBegin;
- (void)fullPageSinkingTransitionDidFinish;
- (void)fullPageSinkingTransitionDidCancel;
- (void)updateActiveSliderAtPresent;
- (void)initVideoDeletedView;
- (unsigned long long)slidesViewPlayMode;
- (BOOL)needAutoPlayDuringSinkTransition;
- (void)paginatedProgressViewDidSelectedItemAtIndex:(long long)a0;
- (void)paginatedProgressViewDidSelectAlbumPreviewItemAtIndex:(long long)a0;
- (void)checkPauseIconSuperview;
- (void)updatePaginatedControllerWithInteractionController:(id)a0;
- (void)willEnterFullPage;
- (void)prepareForDisplay;
- (void).cxx_destruct;
- (BOOL)play;
- (BOOL)pause;
- (BOOL)stop;
- (id)methodSignatureForSelector:(SEL)a0;
- (id)transitionContext;
- (void)viewWillAppear:(BOOL)a0;
- (void)reset;
- (BOOL)respondsToSelector:(SEL)a0;
- (void)viewDidLoad;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)forwardInvocation:(id)a0;
- (BOOL)accessibilityScroll:(long long)a0;
- (void)setupUI;
- (void)handlePinchGesture:(id)a0;

@end
