@class UIView, NSString, AFDRadarNearbyItemModel, AFDButton, UIImageView, AFDRadarActivityModel, AWEUIListCellActionButton, YYLabel, AWERadarUserModel, AFDRadarNeighbourhoodGroupModel, UILabel;

@interface AFDRadarNearbyItemListTableViewCell : UITableViewCell <AWEUserMessage>

@property (retain, nonatomic) AFDButton *baseView;
@property (retain, nonatomic) UIImageView *avatarImageView;
@property (retain, nonatomic) UIImageView *rightArrowImageView;
@property (retain, nonatomic) YYLabel *nameLabel;
@property (retain, nonatomic) UIView *emptyNameLabelView;
@property (retain, nonatomic) UILabel *noticeLabel;
@property (retain, nonatomic) AWEUIListCellActionButton *actionButton;
@property (retain, nonatomic) AWERadarUserModel *model;
@property (retain, nonatomic) AFDRadarActivityModel *activity;
@property (retain, nonatomic) AFDRadarNearbyItemModel *itemModel;
@property (retain, nonatomic) AFDRadarNeighbourhoodGroupModel *groupModel;
@property (nonatomic) BOOL isAnimationHighlighted;
@property (nonatomic) long long followButtonState;
@property (nonatomic) long long friendsState;
@property (nonatomic) long long lastFollowStatus;
@property (nonatomic) BOOL lastIsFromPrivateAccount;
@property (copy, nonatomic) NSString *enterFrom;
@property (copy, nonatomic) NSString *referString;
@property (nonatomic) BOOL isFromRootVC;
@property (nonatomic) BOOL needShowAuthView;
@property (nonatomic) BOOL isSpringFestivalActive;
@property (copy, nonatomic) id /* block */ didClickGroupEntrance;
@property (copy, nonatomic) id /* block */ didClickFollowBlock;
@property (copy, nonatomic) id /* block */ didReceiveFollowResponseBlock;
@property (copy, nonatomic) id /* block */ authLocationBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (double)sugguestHeight;
+ (id)reuseIdentifier;

- (void)didFinishFollowUser:(id)a0 status:(long long)a1 error:(id)a2;
- (void)didFinishUnFollowUser:(id)a0 status:(long long)a1 error:(id)a2;
- (void)didFinishSetRemarkWithUser:(id)a0;
- (id)attributedStringForString:(id)a0 color:(id)a1;
- (void)refreshFollowBtnUI;
- (void)p_refreshUI;
- (void)setBGViewBackgroundColor:(id)a0;
- (void)setActionButtonIsAttentionState:(BOOL)a0;
- (void)dataSourceTogether:(id)a0;
- (void)p_setBaseViewShowStatus:(unsigned long long)a0;
- (void)animationHighlighted;
- (void)p_refreshFollowBtnUI;
- (void)p_refreshGroupBtnUI;
- (void)p_drawListCorner;
- (void)p_refreshUserName;
- (void)displayFollowAnimation;
- (void)p_animationNormal;
- (BOOL)enableLightInteraction;
- (id)lightInteractTitle;
- (void)clearActionBtnImage;
- (void)configFollowBtnWithState:(long long)a0 title:(id)a1;
- (id)lightInteractIcon;
- (void)updateActionButtonImage:(id)a0;
- (id)p_noticeLabelText;
- (void)startLightInteraction;
- (void)p_requestFollow;
- (void)p_transferToGroupChatConversation;
- (void)p_fakeFollowCommit;
- (void)p_fakeFollowRollBack;
- (void)p_clickCard;
- (void)p_transferToOthersHomepage:(id)a0;
- (void)trackClickGroupEntrance;
- (void)p_transferToCommandVC:(long long)a0;
- (id)p_getConversationId;
- (void)trackEnterPersonalHomepageWith:(id)a0;
- (void)p_refreshUserCell;
- (void)configurateWithNearbyItem:(id)a0 activity:(id)a1;
- (void)p_resumeUI;
- (void)p_setupUserCell;
- (void)p_setupGroupCell;
- (void)p_setupEntranceCell;
- (void)p_setupUserSelfCell;
- (void)p_setupUnauthNearbyCell;
- (void)p_setupEmptyCell;
- (void)clickCard;
- (void)p_followBtnClicked:(id)a0;
- (void)p_refreshCellByUserSelf;
- (long long)p_getFakeFollowStatus;
- (void)p_fakeFollow:(long long)a0 flag:(BOOL)a1;
- (unsigned long long)p_inWhichTopVC;
- (void)updatePaddingForRootVC;
- (void)refreshCellWithPosition:(long long)a0;
- (void)refreshCellWithModel:(id)a0;
- (void)p_setupUI;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)a0 reuseIdentifier:(id)a1;
- (void)dealloc;
- (BOOL)isCurrentUser;
- (void)p_addObservers;

@end
