@class NSTimer, AWEAwemeModel, NSString, NSMutableDictionary, UIImageView, NSObject, NSMutableArray, HMDThreadSafeDictionary, NSNumber;
@protocol OS_dispatch_queue;

@interface AWEAwemeFeedPreCacheV2Manager : NSObject <AWEUserMessage, AWEPrecacheProtocol>

@property (retain, nonatomic) NSMutableDictionary *cacheList;
@property (retain, nonatomic) NSTimer *feedCachePrefetchTimer;
@property (nonatomic) long long newHistoryCount;
@property (nonatomic) BOOL hasCacheSuccess;
@property (nonatomic) double cacheSuccessTimestamp;
@property (nonatomic) double launchTimestamp;
@property (retain, nonatomic) AWEAwemeModel *currentSessionUsedModel;
@property (copy, nonatomic) NSString *currentSessionUsedModelDepName;
@property (nonatomic) BOOL hasReadLocalCache;
@property (nonatomic) BOOL hasReadUnDownloadVideoModel;
@property (retain, nonatomic) NSMutableDictionary *consumedAwemeIds;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *storageQueue;
@property (retain, nonatomic) NSMutableArray *readLocalCacheCompletions;
@property (nonatomic) BOOL appDidBecomeActive;
@property (nonatomic) BOOL appIsActive;
@property (retain, nonatomic) NSMutableArray *shouldClearAndTrackerDuplicatedModels;
@property (retain, nonatomic) NSMutableArray *shouldClearAndWithoutTrackerDuplicatedModels;
@property (retain, nonatomic) NSMutableArray *feedRequestModels;
@property (nonatomic) long long feedCacheSource;
@property (nonatomic) BOOL multiStageLocalCacheEmpty;
@property (nonatomic) BOOL videoHasPreloaded;
@property (nonatomic) long long cacheInvalidType;
@property (nonatomic) BOOL feedRequestModelsHasExpired;
@property (retain, nonatomic) NSNumber *readCacheListTime;
@property (retain, nonatomic) NSNumber *readRequestModelsTime;
@property (retain, nonatomic) HMDThreadSafeDictionary *cacheListInfoDict;
@property (retain, nonatomic) NSMutableArray *validCacheListInfoArray;
@property (retain, nonatomic) NSMutableDictionary *depNameMaxSizeDict;
@property (retain, nonatomic) NSMutableDictionary *depNameExpireTimeDict;
@property (retain, nonatomic) NSNumber *readCacheListTimeV2;
@property (retain, nonatomic) UIImageView *tempImageView;
@property (nonatomic) double lastEnterBackgroundTime;
@property (nonatomic) BOOL retryReadCache;
@property (retain, nonatomic) NSMutableDictionary *expiredInfoWithAwemeId;
@property (nonatomic) BOOL hasValidCacheForCurrentLaunch;
@property (retain, nonatomic) NSMutableArray *historyAwemeIds;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (Class)aAWESearchModuleServiceDOUYINSSAdaperClass;
+ (id)sharedInstance;

- (void)didFinishLoginWithUid:(id)a0;
- (void)didFinishLogoutWithUid:(id)a0;
- (void)getFeedCacheFromFileWithCompletion:(id /* block */)a0;
- (void)clearDuplicatedFeedPreCacheModels:(id)a0;
- (BOOL)isPrecacheUndownloadedAwemeModel:(id)a0;
- (void)saveFeedRequestModels:(id)a0;
- (BOOL)hasValidModelForCurrentLaunch;
- (id)getCloudContentEvalParams;
- (void)setForyouFeedDataController:(id)a0;
- (id)feedCacheFromDepName;
- (id)aAWESearchModuleServiceDOUYINSSAdaper;
- (void)onAppFeedReady;
- (void)videoDownloadFinished:(id)a0;
- (void)timerRepeatFetchFeedCache;
- (void)enableAutoTrimForURLString:(id)a0 URLKey:(id)a1;
- (void)disableAutoTrimForURLString:(id)a0 URLKey:(id)a1;
- (void)readLocalCompletionBlock:(id /* block */)a0;
- (void)fetchCacheIfNeeded;
- (BOOL)hasPreCache;
- (BOOL)p_canGetCacheModelForCurrentLaunchType;
- (void)initAllDataSource;
- (void)applicationDidDidBecomeActive;
- (void)p_createTimerIfNeeded;
- (void)p_initNewCacheListInfo;
- (void)postReadCacheFinishedSignal;
- (BOOL)p_canUseUndownloadVideo;
- (id)p_readLocalCacheInfo;
- (void)p_initDepNameConfigInfo;
- (id)p_getValidCacheListInfoArray;
- (id)p_getDepNameFromCacheInfo:(id)a0;
- (void)p_getCacheModelsForDepName:(id)a0 completion:(id /* block */)a1;
- (long long)p_isValidCacheInfo:(id)a0 timeoutHour:(long long)a1;
- (id)getCurrentSessionUsedModelWithTracker:(BOOL)a0;
- (void)clearDuplicatedFeedPreCacheModels:(id)a0 needTracker:(BOOL)a1;
- (void)p_trackPullOutCacheVideo:(BOOL)a0 respFrom:(id)a1;
- (void)p_loadImageCoverForModelIfNeeded:(id)a0;
- (id)useCurrentLaunchModelInOrder:(BOOL)a0;
- (id)p_depName;
- (id)p_getAwemeIDFromCacheInfo:(id)a0;
- (id)p_getCurrentSessionModelFromNewCache;
- (long long)isValidCache:(id)a0 timeoutHour:(long long)a1;
- (void)storageToFileWithFeedPreCacheList:(id)a0 completion:(id /* block */)a1;
- (id)getCurrentSessionUsedModelInOrder:(BOOL)a0;
- (void)p_loadImageCoverForModel:(id)a0;
- (void)p_clearDuplicatedCacheModels:(id)a0 needTracker:(BOOL)a1;
- (void)p_updateUnconsumedVideoWithModel:(id)a0;
- (void)p_saveData;
- (BOOL)p_forceFetchCacheEnable;
- (BOOL)p_isForceFetchCache;
- (void)p_forceFetchCacheIfNeeded:(BOOL)a0;
- (void)p_saveUnconsumedVideo;
- (void)__getFeedCacheFromFileWithCompletion:(id /* block */)a0;
- (double)getExpireTimeStampWithValidCache:(id)a0 timeoutHour:(long long)a1;
- (void)__storageToFileWithFeedPreCacheList:(id)a0 completion:(id /* block */)a1;
- (BOOL)p_hasEnoughCachedModelForNextLaunch;
- (id)processCacheListByCloudInfo:(id)a0;
- (void)processFeedPreCacheModels:(id)a0 sourceProvider:(id)a1;
- (id)getCurrentSessionUsedModel;
- (BOOL)findValidModelInExpiredInfo:(id)a0 withCurrentTime:(double)a1;
- (void)p_saveCacheInfo:(id)a0 awemeModels:(id)a1;
- (void)removeCacheForURLString:(id)a0 URLKey:(id)a1;
- (void)p_saveFeedRequestModels:(id)a0;
- (BOOL)p_canSaveAwemeModel:(id)a0;
- (id)cacheModelsDict;
- (void)p_clearPreCacheData;
- (void)p_saveUnconsumedVideoAfterAssessment;
- (void)p_logCacheList;
- (id)p_buildDesc:(id)a0;
- (id)p_buildCacheItemInfo:(id)a0 depName:(id)a1;
- (void)p_updateCacheListInfo:(id)a0 infoDict:(id)a1;
- (void)p_writeCacheListInfo:(id)a0;
- (void)p_writeCacheModelsForDepName:(id)a0 models:(id)a1 completion:(id /* block */)a2;
- (id)p_getCacheInfoDictForModel:(id)a0;
- (void)p_removeCacheInfoDict:(id)a0;
- (void)p_removeCacheInfo:(id)a0 awemeModel:(id)a1;
- (id)p_cacheModelKeyForDepName:(id)a0;
- (id)useCurrentLaunchModel;
- (void)videoStartPlay:(id)a0;
- (void).cxx_destruct;
- (void)applicationDidEnterBackground;
- (id)init;
- (void)applicationWillResignActive;

@end
