@class UICollectionView, AWEAIVideoClipFavoriteMusicViewModel, AWEAIVideoClipFooterView, NSDictionary, NSObject, AWEVideoRangeSlider, NSMutableArray, ACCAnimatedButton, UIView, NSString, AWEAIVideoClipRetryPanelView, AWEModalTransitionDelegate, AWEVideoPublishViewModel, NSArray, HTSVideoSpeedControl, AWESegmentedClipFooterPassThroughView, AWEAIVideoClipMusicPanelView, AWEAIVideoSegmentsView;
@protocol ACCChallengeModelProtocol, ACCMusicModelProtocol, AWEAIVideoClipFooterViewControllerDelegate;

@interface AWEAIVideoClipFooterViewController : UIViewController <AWEAIVideoClipFavoriteMusicViewModelDelegate, AWEVideoClipFooterView>

@property (nonatomic) unsigned long long currentPanelType;
@property (retain, nonatomic) AWEAIVideoClipRetryPanelView *loadingPanelView;
@property (retain, nonatomic) AWEAIVideoClipMusicPanelView *musicPanelView;
@property (retain, nonatomic) AWEAIVideoSegmentsView *videoSegmentsPanelView;
@property (retain, nonatomic) AWEAIVideoClipFooterView *videoClipPanelView;
@property (retain, nonatomic) AWEModalTransitionDelegate *transDelegate;
@property (retain, nonatomic) NSArray *assetModelArray;
@property (retain, nonatomic) NSMutableArray *musicList;
@property (retain, nonatomic) AWEVideoPublishViewModel *publishModel;
@property (retain, nonatomic) AWEAIVideoClipFavoriteMusicViewModel *favoriteMusicViewModel;
@property (nonatomic) BOOL favoriteMusicEnabled;
@property (nonatomic) BOOL favoriteMusicNeedUpdate;
@property (retain, nonatomic) NSDictionary *referExtra;
@property (retain, nonatomic) id<ACCMusicModelProtocol> selectedMusic;
@property (nonatomic) double startLocation;
@property (nonatomic) BOOL useSuggestClipRange;
@property (weak, nonatomic) NSObject<AWEAIVideoClipFooterViewControllerDelegate> *delegate;
@property (nonatomic) BOOL enableVideoSegementsEdit;
@property (copy, nonatomic) NSString *createID;
@property (retain, nonatomic) id<ACCChallengeModelProtocol> challenge;
@property (copy, nonatomic) NSArray *proBindMusicIDArray;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } normalItemSize;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } coverItemSize;
@property (readonly, nonatomic) AWEVideoRangeSlider *videoRangeSlider;
@property (readonly, nonatomic) HTSVideoSpeedControl *speedControl;
@property (readonly, nonatomic) UICollectionView *framesCollectionView;
@property (readonly, nonatomic) UICollectionView *videosCollectionView;
@property (readonly, nonatomic) UIView *cursorView;
@property (readonly, nonatomic) AWESegmentedClipFooterPassThroughView *framesCollectionLeftMaskView;
@property (readonly, nonatomic) AWESegmentedClipFooterPassThroughView *framesCollectionRightMaskView;
@property (readonly, nonatomic) ACCAnimatedButton *rotateButton;
@property (readonly, nonatomic) ACCAnimatedButton *deleteButton;
@property (readonly, nonatomic) ACCAnimatedButton *speedControlButton;
@property (readonly, nonatomic) ACCAnimatedButton *aniCloseButton;
@property (readonly, nonatomic) ACCAnimatedButton *aniOkButton;
@property (nonatomic) unsigned long long currentVideoIndex;

- (id)addExtraParams:(id)a0;
- (double)currentPanelHeight;
- (void)handleFavoriteStatusChangedNotification:(id)a0;
- (void)p_retryAction;
- (void)moreDataDidLoad;
- (id)initWithSourceAssetModelArray:(id)a0 referExtra:(id)a1;
- (void)p_showSelectMusicViewController;
- (void)fetchFavoriteMusicList;
- (void)p_showPanel:(unsigned long long)a0;
- (void)updateMusicItemList:(id)a0 andUseMusic:(id)a1;
- (void)updateFavoriteMusicListLoading:(BOOL)a0;
- (void)segmentedClipsEndAnimationWithCompletion:(id /* block */)a0;
- (double)p_panelHeightForPanelType:(unsigned long long)a0;
- (void)p_handleSelectMusic:(id)a0 error:(id)a1;
- (id)p_recommendMusic;
- (void)p_musicPanelConfirmAction:(id)a0;
- (void)p_rotateAction:(id)a0;
- (void)p_videoSegmentsFinishButtonAction;
- (void)updateMusicList:(id)a0 error:(id)a1;
- (void)p_transitionFrom:(unsigned long long)a0 to:(unsigned long long)a1;
- (id)p_panelViewOfType:(unsigned long long)a0;
- (BOOL)shouldContinueProceedure;
- (void)segmentedClipsStartAnimationWithCell:(id)a0;
- (BOOL)isInSingleSegmentEditing;
- (BOOL)isInVideoSegmentsEditing;
- (void)footerViewWillAppear;
- (void)footerViewDidAppear;
- (void)footerViewWillDisappear;
- (void)footerViewDidDisappear;
- (void)undoMusicSelection;
- (void)didFinishDeleteAssetModelAtIndex:(long long)a0;
- (id)initWithSourceAssetModelArray:(id)a0 publishModel:(id)a1;
- (void).cxx_destruct;
- (id)containerView;
- (void)viewDidLoad;
- (void)dealloc;

@end
