@class NSObject, NSMutableDictionary, NSString, NSMutableSet, AWEDCFeedPageContext, NSIndexPath, NSMutableArray;
@protocol OS_dispatch_queue, AWEDCFeedListViewControllerProtocol;

@interface AWEDCFeedTrackerService : NSObject <AWEDCFeedTrackerServiceProtocol>

@property (nonatomic) double enterTimeStamp;
@property (nonatomic) double enterTimeForExitDualScene;
@property (nonatomic) BOOL isViewControllerShowing;
@property (retain, nonatomic) NSMutableSet *hasShownItemID;
@property (retain, nonatomic) NSMutableSet *needToTrackForShown;
@property (retain, nonatomic) NSMutableDictionary *rankCache;
@property (retain, nonatomic) NSIndexPath *nextIndexPathForRankCache;
@property (nonatomic) BOOL hasTrackedFMP;
@property (retain, nonatomic) NSIndexPath *needToTrackForFMP;
@property (nonatomic) double refreshBallShowTime;
@property (nonatomic) double refreshBallShowTimeForMonitor;
@property (retain, nonatomic) NSMutableArray *switchPreviewClientShowArray;
@property (retain, nonatomic) NSMutableDictionary *hasRealShownCellDic;
@property (retain, nonatomic) NSMutableDictionary *hasInvisibleCellDic;
@property (retain, nonatomic) NSMutableDictionary *incompleteShownCellDic;
@property (retain, nonatomic) NSMutableSet *hasTrackCellSet;
@property (retain, nonatomic) NSMutableDictionary *totalDurationDic;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *trackerQueue;
@property (nonatomic) BOOL enableTrackerQueue;
@property (weak, nonatomic) id<AWEDCFeedListViewControllerProtocol> container;
@property (weak, nonatomic) AWEDCFeedPageContext *context;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)enterFrom;
- (void)trackEvent:(id)a0 withParams:(id)a1;
- (id)trackerConfig;
- (void)trackAuthorInfoDidClickWithAwemeModel:(id)a0;
- (void)trackItemCoverTimeConsume:(double)a0 withModel:(id)a1 isRequestTime:(BOOL)a2;
- (void)trackItemCoverStatus:(unsigned long long)a0 withModel:(id)a1;
- (void)trackLiveWindowDurationV2WithMethod:(id)a0 actionType:(id)a1 roomID:(id)a2 model:(id)a3 duration:(long long)a4;
- (void)trackTitleShowWithIndexPath:(id)a0 withParams:(id)a1;
- (void)trackTitleOfItemDidClickedWithIndexPath:(id)a0 withParams:(id)a1;
- (long long)rankWithItemID:(id)a0;
- (void)trackDislikeWithType:(id)a0 awemeModel:(id)a1;
- (void)markRefreshBallShowing;
- (void)markRefreshBallShowingForMonitor;
- (void)trackAbnormalityWithAction:(id)a0 subCase:(id)a1;
- (void)trackHistoryFindCellDidClicked;
- (void)trackClientShowByDelayIfNeededWithExtra:(id)a0;
- (void)clearSwitchPreviewClientShowArray;
- (void)invalidateRankCache;
- (double)get2ColorBallShowTimeStampForMonitor;
- (void)resetRefreshBallShowingForMonitor;
- (void)trackDataRequestTimeConsume:(double)a0 withModel:(id)a1 requestMethod:(id)a2;
- (void)trackRefreshBallShowDurationWithRequestMethod:(id)a0;
- (void)trackRefreshWithCardsCount:(long long)a0 useUnConsumeVideo:(BOOL)a1;
- (void)trackClientShowV2;
- (void)trackClientRealShowDuration;
- (void)trackAllClientRealShowDuration;
- (void)clearHasTrackCellSet;
- (void)trackClientShowV2WithFilter:(BOOL)a0;
- (void)trackClientIncompleteShowWithType:(id)a0;
- (void)trackHistoryFindCellShow;
- (void)recordHistoryModelItemID:(id)a0;
- (void)trackCommonEvent:(id)a0 model:(id)a1 params:(id)a2;
- (void)markViewControllerShowing:(BOOL)a0;
- (void)trackNeedToTrackForShownItem;
- (void)trackNeedToTrackForFMP;
- (void)trackItemDidShownIfNeededWithIndexPath:(id)a0;
- (void)addIndexPathsToNeedToTrackForShown:(id)a0;
- (void)resetHasShown;
- (void)trackExitWithModel:(id)a0;
- (void)refreshTimeStampForExitDualScene;
- (void)trackSlideWithParams:(id)a0;
- (void)trackFMPWithIndexPath:(id)a0;
- (void)trackItemDidClickedWithIndexPath:(id)a0;
- (void)trackEnterWithModel:(id)a0;
- (void)trackItemDidClickedWithIndexPath:(id)a0 withParams:(id)a1;
- (void)trackItemDidClickCloseWithIndexPath:(id)a0 withParams:(id)a1;
- (void)trackSpecialCardDislikeClickWithAwemeModel:(id)a0 withParams:(id)a1;
- (void)trackSpecialCardControlWithAwemeModel:(id)a0 withParams:(id)a1;
- (long long)calculateClientRankWithModel:(id)a0 indexPath:(id)a1;
- (void)trackItemDidShownWithAwemeModel:(id)a0 indexPath:(id)a1;
- (void)trackLiveShowIfNeededWithAwemeModel:(id)a0 indexPath:(id)a1;
- (BOOL)fixClientShowTracker;
- (id)getCardCommonTrackParamsWithAwemeModel:(id)a0 indexPath:(id)a1;
- (BOOL)shouldDelayTrackClientShow;
- (void)trackShowWithParams:(id)a0 aweme:(id)a1;
- (void)trackClientShowV2WithAweme:(id)a0 showType:(id)a1 visiblePercent:(double)a2;
- (void)handleRealShowDurationDicIsVisible:(BOOL)a0 forAwemeModel:(id)a1;
- (void)trackInvisibleCellShowDuration;
- (void)trackClientStayTimeWithAweme:(id)a0 duration:(double)a1;
- (double)firstEnterSwitchPreviewTimeStamp;
- (long long)rankWithAwemeModel:(id)a0 indexPath:(id)a1;
- (void)trackEvent:(id)a0 withParams:(id)a1 enableCommonParams:(BOOL)a2;
- (void).cxx_destruct;
- (id)init;

@end
