@class NSDictionary, AWETrendDetailResponse, NSIndexPath, AWEDetailTrendDescriptionModel, AWEAwemeModel, NSString, AWETrendDetailMusicListModel, AWEDetailAwemeListDataController, AWEDetailTrendHeadTitleModel, NSMutableDictionary, NSArray, AWEDetailHeaderInfoModel, AWERequestVidFeatureModel, AWEDetailNaviBarModel, AWEDetailShimmerModel, AWEDetailDiffableMultiModelObject, AWEDetailTrendHeaderMaterialModel, AWECodeGenTrendsActivityResourceInfoModel, AWETrendInfoModel, AWEDetailTrendCommonTrackParams, AWETrendCheckTrackModel;
@protocol AWEDetailTrendMonitorService;

@interface AWEDetailTrendViewModel : NSObject <AWEDetailViewModelProtocol>

@property (retain, nonatomic) AWEDetailNaviBarModel *naviBarObject;
@property (retain, nonatomic) AWEDetailShimmerModel *shimmerViewObject;
@property (retain, nonatomic) AWEDetailHeaderInfoModel *headerInfoObject;
@property (retain, nonatomic) AWEDetailTrendHeaderMaterialModel *trendMaterialObject;
@property (retain, nonatomic) AWEDetailTrendHeadTitleModel *trendTitleObject;
@property (retain, nonatomic) AWEDetailTrendDescriptionModel *trendDescriptionObject;
@property (retain, nonatomic) AWETrendDetailMusicListModel *trendMusicListObject;
@property (retain, nonatomic) AWEDetailDiffableMultiModelObject *awemeListObject;
@property (retain, nonatomic) AWEDetailAwemeListDataController *awemeListDataController;
@property (retain, nonatomic) AWEAwemeModel *awemeModel;
@property (retain, nonatomic) AWETrendInfoModel *trendInfoModel;
@property (retain, nonatomic) AWEDetailTrendCommonTrackParams *commonTrackParams;
@property (copy, nonatomic) NSString *shootSameSchema;
@property (copy, nonatomic) NSString *oneClickFilmSchema;
@property (copy, nonatomic) NSArray *materialFollowShootButtonModels;
@property (retain, nonatomic) NSDictionary *cacheParams;
@property (retain, nonatomic) NSDictionary *enterTrackParams;
@property (retain, nonatomic) AWETrendDetailResponse *detailResponse;
@property (nonatomic) long long detailInfoFetchState;
@property (nonatomic) long long awemeListFetchState;
@property (nonatomic) long long awemeListInitFetchStatus;
@property (nonatomic) long long trendsDetailEnterFrom;
@property (nonatomic) BOOL hasFetchedAwemeList;
@property (nonatomic) long long truelyTrendsCount;
@property (nonatomic) long long awemeListFetchNumbers;
@property (retain, nonatomic) id<AWEDetailTrendMonitorService> monitor;
@property (readonly, nonatomic) AWETrendCheckTrackModel *trendRequestTrackModel;
@property (nonatomic) long long collectState;
@property (copy, nonatomic) NSString *buttonText;
@property (readonly, copy, nonatomic) NSString *gameId;
@property (readonly, copy, nonatomic) NSString *mapId;
@property (retain, nonatomic) AWERequestVidFeatureModel *featureModel;
@property (nonatomic) BOOL disableTrendsActivitySetting;
@property (copy, nonatomic) NSArray *trendsActivityResourceInfos;
@property (retain, nonatomic) AWECodeGenTrendsActivityResourceInfoModel *trendsActivityResourceInfoModel;
@property (copy, nonatomic) id /* block */ detailViewModelFetchDetailInfoActionBlock;
@property (copy, nonatomic) NSString *shootEnterMethod;
@property (copy, nonatomic) NSString *videoPlayEnterFrom;
@property (copy, nonatomic) NSString *videoPlayEnterMethod;
@property (copy, nonatomic) NSString *clickVideoMethod;
@property (retain, nonatomic) NSMutableDictionary *paramDict;
@property (readonly, copy, nonatomic) NSArray *sectionControllerModelObjectArray;
@property (retain, nonatomic) NSIndexPath *awemeListSectionSelectedIndexPath;
@property (nonatomic) BOOL awemeListUpdated;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)preloadTrendsDetailInfoWithConfigParams:(id)a0 awemeModel:(id)a1 enableCombineNetworkRequest:(BOOL)a2 enableMemoryCache:(BOOL)a3 cacheExpireTime:(double)a4;
+ (id)preloadFirstPageTrendsAwemeInfoWithConfigParams:(id)a0 awemeModel:(id)a1 enableCombineNetworkRequest:(BOOL)a2 enableMemoryCache:(BOOL)a3 cacheExpireTime:(double)a4;
+ (void)clearNetworkRequestCacheForKey:(id)a0;
+ (id)trendsPageRequestParamDictWithTrendInfoModel:(id)a0 awemeModel:(id)a1 configParams:(id)a2;
+ (id)getMapIdWithTrendInfoModel:(id)a0;
+ (id)makeTrendModelFromAwemeModel:(id)a0;
+ (void)setGameMaterialGameInfoWithResponse:(id)a0;
+ (id)trendsPageRequestParamDictWithTrendInfoModel:(id)a0 awemeModel:(id)a1 configParams:(id)a2 trendsDetailEnterFrom:(long long)a3;
+ (id)makeTrendTrackModelFromAwemeModel:(id)a0;
+ (id)lastGroupOriginMaterialsListJSONStringEncodedWithTrendInfoModel:(id)a0 awemeModel:(id)a1;
+ (id)trendTitleFromAweme:(id)a0;

- (void)configViewModelWithParamDict:(id)a0;
- (void)fetchDetailInfo;
- (void)fetchAwemeList;
- (BOOL)isFetchingInitialAwemeList;
- (BOOL)hasLora;
- (void)setupSkeletonMode;
- (void)trackAIFollowShootShow;
- (BOOL)entryFrequencyEnabledWithTrendsActivityResourceInfo:(id)a0;
- (void)entryFrequencyReloadWithTrendsActivityResourceInfo:(id)a0;
- (BOOL)shouldShowTrendsEntry;
- (void)trackShowTrendsEntry;
- (void)configViewModelWithAweme:(id)a0 trackDict:(id)a1;
- (id)currentTrendModel;
- (void)resetEntryFrequencyValueWithTrendsActivityResourceInfo:(id)a0;
- (void)trackClickTrendsEntry;
- (void)resetEntryShowInfo;
- (id)userCountStringWithCount:(long long)a0;
- (id)requestParamDict;
- (id)awemeListRequestParamDict;
- (BOOL)hasEllegalTrendId;
- (BOOL)hasMaterialsForPreload;
- (void)trackTrendsDetailNetworkRequestDidFinishWithExtraParam:(id)a0;
- (void)p_decomposeDetailResponse:(id)a0 requestIsFromCache:(BOOL)a1;
- (void)preloadShootResourceIfNeed;
- (void)schemaDataVerifyWithRequestParams:(id)a0 responseModel:(id)a1;
- (BOOL)needRequestFlashMobIdForTrendDetail;
- (void)trackTrendsAwemeNetworkRequstDidFinishWithExtraParams:(id)a0;
- (BOOL)entryFrequencyEnabled;
- (BOOL)canShowTrendsEntry;
- (id)trendDetailEntryFrequencyV2Config;
- (void)p_createMusicListObjectWithResponse:(id)a0 requestIsFromCache:(BOOL)a1;
- (void)p_createTrendsActivityResourceInfoWithResponse:(id)a0;
- (id)diversionInfoWithAweme:(id)a0;
- (void).cxx_destruct;

@end
