@class AWEDemaciaLoadingAndVolumeView, NSMutableDictionary, NSDictionary, UITapGestureRecognizer, AWEDemaciaPlayerControlView, UIView, AWEDemaciaPlayerVideoModel, NSString, AWEDemaciaVideoBSModel, NSTimer, AWEDemaciaPlayerInitModel, NSNumber, CADisplayLink, UIImageView;
@protocol AWEDemaciaPlayerViewDelegate, IESCommonVideoPlayerProtocol;

@interface AWEDemaciaPlayerView : UIView <AWEStudioDemaciaPlayerViewProtocol, AWEDemaciaPlayerControlViewDelegate, AWEDemaciaPlayerView>

@property (readonly, nonatomic) long long acc_currentPlayState;
@property (retain, nonatomic) NSString *enterFrom;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) id<IESCommonVideoPlayerProtocol> playerController;
@property (retain, nonatomic) UIView *loadingView;
@property (retain, nonatomic) AWEDemaciaLoadingAndVolumeView *volumeLoadingView;
@property (retain, nonatomic) UIImageView *coverImageView;
@property (retain, nonatomic) CADisplayLink *displayLink;
@property (nonatomic) double playTime;
@property (nonatomic) double originHeight;
@property (nonatomic) double originWidth;
@property (retain, nonatomic) AWEDemaciaVideoBSModel *bsModel;
@property (retain, nonatomic) AWEDemaciaPlayerVideoModel *videoModel;
@property (retain, nonatomic) AWEDemaciaPlayerInitModel *infoModel;
@property (copy, nonatomic) NSDictionary *paramDic;
@property (nonatomic) long long currentPlayState;
@property (nonatomic) long long trategyType;
@property (retain, nonatomic) NSTimer *quietModeTimer;
@property (nonatomic) BOOL slidingSeekTime;
@property (nonatomic) BOOL slidingSeekTimeSucceed;
@property (nonatomic) double eachPlayTime;
@property (nonatomic) double stallStartTimestamp;
@property (nonatomic) unsigned long long stallCount;
@property (nonatomic) double stallTotalDuration;
@property (nonatomic) BOOL firstFramePlay;
@property (nonatomic) BOOL finishedLog;
@property (retain, nonatomic) NSMutableDictionary *trackContext;
@property (nonatomic) BOOL isResourceRecallEnabled;
@property (weak, nonatomic) id<AWEDemaciaPlayerViewDelegate> delegate;
@property (retain, nonatomic) UITapGestureRecognizer *tap;
@property (nonatomic) double fullScreenWidth;
@property (nonatomic) double fullScreenHeight;
@property (nonatomic) BOOL isQuiet;
@property (nonatomic) BOOL notPlayWhenAppear;
@property (retain, nonatomic) AWEDemaciaPlayerControlView *controlView;
@property (nonatomic) BOOL usingForLongVideoNewStyle;
@property (nonatomic) BOOL isTTPlayer;
@property (nonatomic) BOOL isQuietModedisabled;
@property (retain, nonatomic) NSNumber *realStartPlayTime;
@property (retain, nonatomic) NSNumber *realEndPlayTime;
@property (nonatomic) BOOL notStop;
@property (retain, nonatomic) NSString *enterFrom;
@property (nonatomic) BOOL needsRespondingToVideoResourceRecall;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)updatePlayerIfNeeded;
- (void)resetDisplayLink;
- (void)setStartPlayTime:(double)a0;
- (void)updateCoverImage;
- (BOOL)alertIfNotValid;
- (long long)scaleModeForVideo;
- (void)onVolumeChangeNotification:(id)a0;
- (void)refreshDemaciaVideoModel:(id)a0 paramDic:(id)a1;
- (void)demaciaPlayerSliderTouchBegan:(id)a0;
- (void)demaciaPlayerSliderValueChanged:(id)a0;
- (void)demaciaPlayerSliderTouchEnded:(id)a0;
- (void)demaciaPlayerFullScreenButtonClicked:(long long)a0;
- (void)demaciaPlayButtonClicked:(BOOL)a0;
- (void)demaciaPlayerBackButtonClicked;
- (void)demaciaPlayerReplayButtonClicked;
- (void)demaciaPlayerHideFullScreenBtn:(BOOL)a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 initModel:(id)a1;
- (id)acc_initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 initModel:(id)a1;
- (void)acc_refreshDemaciaVideoModel:(id)a0 paramDic:(id)a1;
- (void)realPlay;
- (void)addVideoLoadingView;
- (void)addControlView;
- (void)screenTap:(id)a0;
- (void)addIESVideoPlayer;
- (void)addVolumeLoadingView;
- (void)stopAllPlayerNotice:(id)a0;
- (BOOL)_isResourceRecalledForRecallMessage:(id)a0;
- (void)initCommonTrack;
- (void)resetToBeginTime;
- (void)enterQuietMode:(BOOL)a0;
- (double)videoStartPlayTime;
- (id)_isCurrentVideoH265;
- (id)monitorSeekStateKey;
- (void)addPeriodicTimeObserver;
- (void)registerWillLoopBlock;
- (void)registerVideoDownloadBlock;
- (void)registerNoVideoDownloadBlock;
- (void)registerPlaybackFailedBlock;
- (void)registerStallStateChangeBlock;
- (void)registerDidReadyForDisplayBlock;
- (void)registerPlaybackStateChangeBlock;
- (void)registerSingleUrlPlaybackFailedBlock;
- (long long)contentModeForDefaultVideoCover;
- (id)longAndShortVideoModel;
- (id)playURIString;
- (void)checkVideoSize:(struct CGSize { double x0; double x1; })a0 fromPlayer:(BOOL)a1;
- (id)monitorFirstFrameKey;
- (id)monitorFirstFrameLogKey;
- (id)monitorpPlayErrorKey;
- (void)playResumeDisplayLink;
- (id)__qualityType;
- (void)commitMonitor;
- (id)monitorpPlayBlockKey;
- (void)doActionIfNotValid;
- (void)doActionIfNotValidWithText:(id)a0;
- (void)setControlViewMode:(long long)a0;
- (void)setControlRotateMode:(long long)a0;
- (void)rotateAnimation:(long long)a0 complete:(id /* block */)a1;
- (void).cxx_destruct;
- (BOOL)play;
- (BOOL)pause;
- (id)loginUser;
- (BOOL)stop;
- (void)setHidden:(BOOL)a0;
- (void)replay;
- (void)reset;
- (void)layoutSubviews;
- (void)dealloc;
- (void)setAlpha:(double)a0;
- (void)stopDisplayLink;
- (void)seekToTime:(double)a0 completion:(id /* block */)a1;

@end
