@class NSString, AWEDeliveryEntryChatInfoModel, NSArray, AWEDeliveryChatTopInfoModel, NSDictionary, NSObject, NSDateFormatter, NSMutableOrderedSet, AWEDeliveryChatDetailMessageCacheManager;
@protocol AWEECOMIMPaasMessagesInConversationDataSourceBridgeProtocol, AWEECOMIMPaasConversationBridgeProtocol, AWEECOMIMPaasUserInfoModelProtocol, OS_dispatch_queue;

@interface AWEDeliveryChatDetailVCBiz : NSObject <AWEDeliveryMsgModelDataSource>

@property (copy) NSArray *cellModelArr;
@property (retain, nonatomic) NSMutableOrderedSet *originMessagesSet;
@property (retain, nonatomic) NSArray *originSortedMessageArr;
@property (retain, nonatomic) id<AWEECOMIMPaasConversationBridgeProtocol> curConversation;
@property (retain, nonatomic) id<AWEECOMIMPaasUserInfoModelProtocol> currentLoginUser;
@property (retain, nonatomic) id<AWEECOMIMPaasMessagesInConversationDataSourceBridgeProtocol> messageDataSource;
@property (copy) NSDictionary *messageID2CellModelMap;
@property (nonatomic) BOOL hasBeenAddedHistorySeparateMessage;
@property (retain, nonatomic) NSDateFormatter *dateFormatter;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *messageDataQueue;
@property (copy, nonatomic) NSArray *photoURLArr;
@property (nonatomic) BOOL isFetchingHistoryMsg;
@property (nonatomic) long long lastMaxClearUnreadMsgTime;
@property (copy, nonatomic) NSString *lastRiderId;
@property (copy, nonatomic) NSString *lastDeliveryState;
@property (readonly, nonatomic) BOOL hasMoreMessage;
@property (copy, nonatomic) id /* block */ messagesUpdateBlock;
@property (copy, nonatomic) id /* block */ messageInsertBlock;
@property (copy, nonatomic) id /* block */ conversationUpdateBlock;
@property (copy, nonatomic) id /* block */ unreadCountUpdateBlock;
@property (copy, nonatomic) id /* block */ targerUserReadIndexBlock;
@property (copy, nonatomic) id /* block */ firstLoadOriginMessagesBlock;
@property (retain, nonatomic) AWEDeliveryEntryChatInfoModel *entryModel;
@property (copy, nonatomic) NSDictionary *requestCommonParams;
@property (copy, nonatomic) NSString *pageName;
@property (copy, nonatomic) NSString *serviceType;
@property (retain, nonatomic) AWEDeliveryChatTopInfoModel *chatTopInfoModel;
@property (retain, nonatomic) AWEDeliveryChatDetailMessageCacheManager *messageCacheManeger;
@property (readonly, copy, nonatomic) NSString *deliverStatus;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)sendTextMessage:(id)a0;
- (id)pageCommonTrackParams;
- (id)generateRequestParamsWithParams:(id)a0;
- (void)fetchRiderChatInfoWithCompletion:(id /* block */)a0;
- (BOOL)checkRiskControlledChangedWithPigeonMessage:(id)a0;
- (void)dealRecalledMessageWithMessage:(id)a0;
- (void)dealStatusChangedMessage:(id)a0;
- (void)insertOrUpdateMessages:(id)a0 isSendByMe:(BOOL)a1 finishBlock:(id /* block */)a2;
- (void)clearUnreadCount;
- (void)__asyncMessageDataQueue:(id /* block */)a0;
- (void)showPhotoViewer:(unsigned long long)a0;
- (void)checkIsAllPhotoImageFullURLAndShowPhotoPickerCompletion:(id /* block */)a0;
- (id)sendMsgParamsDictWithNeedSenderRole:(BOOL)a0;
- (void)resendImageMessage:(id)a0;
- (void)resendVideoMessage:(id)a0;
- (void)resendMessage:(id)a0;
- (void)sendImageMessage:(id)a0 groupImages:(id)a1;
- (void)sendVideoMessage:(id)a0;
- (void)uploadImageAndSendImageMessageWithImgFilePath:(id)a0 imageMessage:(id)a1;
- (void)uploadVideoAndSendVideoMessageWithFilePath:(id)a0 videoMessage:(id)a1;
- (void)recallMessageWithModel:(id)a0;
- (id)shouldNotAggregationArr;
- (void)insertOrUpdateMessagesAndGenerateMsgModelsWithMessages:(id)a0 isSendByMe:(BOOL)a1 finishBlock:(id /* block */)a2;
- (void)generateDisplayableMessageModelList:(BOOL)a0 hasInsertMessage:(BOOL)a1 hasUpdateMessage:(BOOL)a2 finishBlock:(id /* block */)a3;
- (id)cellModelArrWithMessages:(id)a0 lastCellModel:(id)a1;
- (BOOL)shouldAddTimeMessageWithMessageModel:(id)a0 lastMessageModel:(id)a1;
- (id)timeStringFromCursor:(double)a0;
- (BOOL)shouldAggregationMessagesBetLastMsgModel:(id)a0 curMessageModel:(id)a1;
- (BOOL)isNotInTowMinutesBetweenLastMsgModel:(id)a0 curMessageModel:(id)a1;
- (BOOL)isRecalledBySharkMessage:(id)a0;
- (BOOL)isInTowMinutesBetweenLastMsgModel:(id)a0 curMessageModel:(id)a1;
- (double)timeIntervalBetweenLastMessage:(id)a0 curMessage:(id)a1;
- (id)commonTrackParamsDict;
- (BOOL)checkRiderHasChanged;
- (BOOL)checkDeliveryStateChanged;
- (void)bindCurrentLoginUser:(id)a0;
- (void)bindCurrentConversation:(id)a0;
- (void)fetchHistoryMessagesWithCompletion:(id /* block */)a0;
- (void)showPhotoPreviewer:(id)a0;
- (void)sendEmotionMessageWithEmotionDict:(id)a0;
- (void)sendMediaMessages:(id)a0;
- (BOOL)checkCanSendUserEnterFromGoodsOrOrder:(id)a0 goodID:(id)a1;
- (BOOL)hasCellModel:(id)a0;
- (id)trackMsgStringFromMessage:(id)a0;
- (void)trackPageViewEventName:(id)a0 eventParams:(id)a1;
- (void)tracePageShow;
- (void)traceTopBannerClick;
- (void)traceInputBoxPhoneClick;
- (void).cxx_destruct;
- (id)init;

@end
