@class AWEEcomSearchCoinTaskView, AWEEcomSearchTabManager, AWEEcomSearchStateStore, AWESearchExtraParamsUtility, AWESlidingTabbarView, AWEEcomSearchViewModel, AWEEcomSearchMerchandiseTabGuideManager, AWEEcomSearchResultConfig, AWEEcomSearchProfile, NSString, AWEEcomSearchBackgroundView, AWESlidingViewController, AWEEcomAISearchEntranceManager, AWEEcomSearchTabGuideManager, AWEEcomSearchBar;
@protocol AWEEcomSearchResultViewControllerDelegate;

@interface AWEEcomSearchBaseResultViewController : UIViewController <AWESlidingViewControllerDelegate, AWESearchActionListenerProtocol, AWEEcomSearchTabManagerDelegate, AWEEcomSearchChildVCConstructorVisitor, AWEEcomAISearchEntranceManagerDelegate, AWEEcomSearchResultViewControllerProtocol>

@property (retain, nonatomic) AWEEcomSearchTabManager *tabManager;
@property (retain, nonatomic) AWESlidingTabbarView *tabView;
@property (retain, nonatomic) AWESlidingViewController *slidingViewController;
@property (retain, nonatomic) AWEEcomSearchBackgroundView *backgroundView;
@property (nonatomic) long long searchTheme;
@property (nonatomic) BOOL backgroundViewHidden;
@property (nonatomic) BOOL pageDidAppear;
@property (nonatomic) double tabViewYTotalOffset;
@property (nonatomic) long long ECSearchTabScrollCase;
@property (copy, nonatomic) NSString *showImprId;
@property (copy, nonatomic) NSString *originTabList;
@property (retain, nonatomic) AWEEcomSearchTabGuideManager *tabGuideManager;
@property (retain, nonatomic) AWEEcomSearchMerchandiseTabGuideManager *merchandiseTabGuideManager;
@property (retain, nonatomic) AWESearchExtraParamsUtility *searchExtraParams;
@property (copy, nonatomic) id /* block */ getMoreButtonCenterBlock;
@property (retain, nonatomic) AWEEcomAISearchEntranceManager *aiSearchEntranceManager;
@property (weak, nonatomic) AWEEcomSearchBar *searchBar;
@property (copy, nonatomic) NSString *preSearchKeyword;
@property (copy, nonatomic) NSString *presearchID;
@property (copy, nonatomic) NSString *searchKeyword;
@property (retain, nonatomic) AWEEcomSearchViewModel *searchViewModel;
@property (retain, nonatomic) AWEEcomSearchStateStore *searchStateStore;
@property (retain, nonatomic) AWEEcomSearchResultConfig *resultConfig;
@property (weak, nonatomic) AWEEcomSearchProfile *profile;
@property (weak, nonatomic) id<AWEEcomSearchResultViewControllerDelegate> delegate;
@property (copy, nonatomic) NSString *keyword;
@property (copy, nonatomic) NSString *searchChannel;
@property (copy, nonatomic) NSString *refer;
@property (copy, nonatomic) NSString *previousPage;
@property (copy, nonatomic) NSString *gid;
@property (copy, nonatomic) NSString *enterGroupID;
@property (copy, nonatomic) NSString *authorId;
@property (copy, nonatomic) NSString *searchEntranceStyle;
@property (copy, nonatomic) NSString *isSearchButton;
@property (nonatomic) long long searchQueryInputTime;
@property (copy, nonatomic) NSString *searchPassThroughParams;
@property (copy, nonatomic) NSString *enterFromSecond;
@property (copy, nonatomic) NSString *preRequestRootTag;
@property (nonatomic) BOOL isFromECommerce;
@property (nonatomic) BOOL isFirstSearch;
@property (copy, nonatomic) id /* block */ didExecuteSearchBlock;
@property (copy, nonatomic) id /* block */ sugSessionIDBlock;
@property (copy, nonatomic) id /* block */ searchBackgroundStateChangedBlock;
@property (copy, nonatomic) id /* block */ ecomSearchEducationPopupCloseBlock;
@property (copy, nonatomic) NSString *ecomDynamicOriginTabList;
@property (copy, nonatomic) NSString *dynamicTabLogid;
@property (copy, nonatomic) NSString *currentTabSwitchMethod;
@property (copy, nonatomic) NSString *ecomTargetTab;
@property (nonatomic) BOOL lockEcomTargetTab;
@property (retain, nonatomic) AWEEcomSearchCoinTaskView *coinTaskView;
@property (copy, nonatomic) id /* block */ ecomSearchBarTypeChangeBlock;
@property (copy, nonatomic) id /* block */ ecomSearchMiddlePageThemeBlock;
@property (nonatomic) long long capsuleIndex;
@property (copy, nonatomic) id /* block */ dismissSearchResultVCWhenJumpToNewPageBlock;
@property (copy, nonatomic) NSString *preRequestTrueRootTag;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (long long)numberOfControllers:(id)a0;
- (id)slidingViewController:(id)a0 viewControllerAtIndex:(long long)a1;
- (void)slidingViewController:(id)a0 didSelectIndex:(long long)a1 transitionType:(long long)a2;
- (void)slidingViewController:(id)a0 didFinishTransitionFromPreviousIndex:(long long)a1 currentIndex:(long long)a2 transitionType:(long long)a3;
- (void)slidingViewControllerDidScroll:(id)a0;
- (unsigned long long)tabType;
- (void)configUI;
- (void)setupBind;
- (id)getEnterFrom;
- (void)searchWithKeyword:(id)a0 tabType:(unsigned long long)a1 enterMethod:(id)a2 extraLogParams:(id)a3 onlyShowSug:(BOOL)a4 completion:(id /* block */)a5;
- (void)searchMiddleViewControlleWillShow;
- (BOOL)isShowingMiddleView;
- (void)onFetchDataCompletion;
- (void)setSlidingViewControllerClipsToBounds:(BOOL)a0;
- (void)tabViewYOffset:(double)a0;
- (void)tabViewYOffsetReset;
- (void)updateSearchBackground:(id)a0 hidden:(BOOL)a1 theme:(long long)a2;
- (void)updateSearchDynamicBackground:(id)a0 hidden:(BOOL)a1 theme:(unsigned long long)a2;
- (void)setEcomSearchGetMoreButtonCenterBlock:(id /* block */)a0;
- (id /* block */)ecomSearchGetMoreButtonCenterBlock;
- (void)searchWithKeywordThenSwitch:(id)a0 tabType:(unsigned long long)a1 enterMethod:(id)a2 extraLogParams:(id)a3 onlyShowSug:(BOOL)a4 force:(BOOL)a5 completion:(id /* block */)a6;
- (void)didSelectFilterViewAISearchEntranceWithParams:(id)a0 host:(id)a1;
- (void)componentCellDidSelectTabWithTabType:(id)a0;
- (id)getEnterFromSecond;
- (id)getEcomSceneId;
- (void)searchForKey:(id)a0 force:(BOOL)a1 paramsModel:(id)a2 completion:(id /* block */)a3;
- (void)setupEcomResultPageTask;
- (void)didReceiveTradeBoardContext:(id)a0;
- (void)searchForKeyThenSwitch:(id)a0 force:(BOOL)a1 paramsModel:(id)a2 completion:(id /* block */)a3;
- (void)configTabBarWithTheme:(unsigned long long)a0;
- (void)switchToTabAtIndex:(long long)a0;
- (void)trackEcomTabSwitchWithPreviousTabIndex:(long long)a0 currentTabIndex:(long long)a1 switchType:(id)a2;
- (void)dynamicEcommerceTabs:(id)a0;
- (void)recordLogPassback:(id)a0 tabType:(unsigned long long)a1 ofChild:(id)a2;
- (void)updateTabbarHidden:(BOOL)a0;
- (void)trackEcomSearchTabShow;
- (void)destoryEcomResultPageTask:(id)a0 taskResponse:(id)a1;
- (void)viewControllerBeginRefreshData:(id)a0;
- (void)viewControllerEndRefreshData:(id)a0 searchData:(id)a1;
- (void)searchTabsDidUpdateWithSelectedIndex:(long long)a0;
- (void)forceSwitchToTabAtIndex:(long long)a0;
- (void)constructorVisit:(id)a0;
- (BOOL)needInterceptReturnEventWithParams:(id)a0;
- (id)activeResultViewController;
- (id)currentSelectedChildVC;
- (void)fetchDynamicTabs:(id)a0;
- (void)guideManagerRegisterByteSync:(id)a0;
- (void).cxx_destruct;
- (id)methodSignatureForSelector:(SEL)a0;
- (void)updateBackgroundView;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)forwardInvocation:(id)a0;

@end
