@class AWEUserRecommendBigCardDataSource, AFDFrequencyRuleGroup, NSString, AWEFamiliarFeedRecommendStrategy, AFDFrequencyCountRule, AFDFrequencyExitRule;

@interface AWEFeedRecommendManager : NSObject <AWEUserMessage, AWEFeedRecommendManagerProtocol, AWEFeedFetchInsertCardManagerProtocol>

@property (nonatomic) BOOL hasFetchedData;
@property (retain, nonatomic) AWEUserRecommendBigCardDataSource *hotFeedDataSource;
@property (retain, nonatomic) AWEUserRecommendBigCardDataSource *familiarFeedMateDataSource;
@property (retain, nonatomic) AWEUserRecommendBigCardDataSource *familiarFeedMultiMateDataSource;
@property (retain, nonatomic) AWEUserRecommendBigCardDataSource *familiarFeedObdDataSource;
@property (retain, nonatomic) AWEFamiliarFeedRecommendStrategy *familiarFeedRecommendStrategy;
@property (retain, nonatomic) AFDFrequencyRuleGroup *feedRuleGroup;
@property (retain, nonatomic) AFDFrequencyCountRule *feedShowCountRule;
@property (retain, nonatomic) AFDFrequencyCountRule *allShowCountRule;
@property (retain, nonatomic) AFDFrequencyExitRule *dislikeExitRule;
@property (nonatomic) BOOL hasNextAvailableFeedCardModel;
@property (nonatomic) long long insertFetch;
@property (nonatomic) long long insertIndex;
@property (nonatomic) BOOL hasInsert;
@property (nonatomic) BOOL hasShownRecPopup;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)sharedInstance;

- (void)didFinishLogoutWithUid:(id)a0;
- (BOOL)canHandleLeftSlideGesture:(id)a0 model:(id)a1;
- (id)leftSlideViewController:(id)a0;
- (void)leftSlideViewControllerDidEnter:(id)a0;
- (id)panelViewControllerForModel:(id)a0;
- (id)feedRecommendCellViewController:(long long)a0;
- (void)refreshInsertPosition;
- (void)willDisplayCardModel:(id)a0 slideType:(long long)a1;
- (void)didEndDisplayingCardModel:(id)a0 slideType:(long long)a1;
- (BOOL)canFetchCard;
- (void)didFetchCardModel:(id)a0 success:(BOOL)a1;
- (BOOL)canInsertCardToList:(id)a0 fetchCount:(long long)a1;
- (void)configureCardModel:(id)a0;
- (void)didInsertCardModel:(id)a0 success:(BOOL)a1 fetchCount:(long long)a2;
- (id)userFromModel:(id)a0;
- (id)profilePageRouterParamsStringForMateCard:(id)a0;
- (void)trackFollowCardFinish:(id)a0 eventType:(id)a1;
- (BOOL)handleCardModelFromFeed:(id)a0;
- (void)appendUserModel:(id)a0 postList:(id)a1 isFromHotFeed:(BOOL)a2;
- (void)didInsertHotFeedRecommendCardModel:(id)a0;
- (void)showRecommendExplanationModalViewOnModel:(id)a0;
- (id)appendParametersForUserProfileURL:(id)a0 model:(id)a1;
- (void)trackFollowCard:(id)a0 eventType:(id)a1;
- (id)mateCardTrackParamsWithAweme:(id)a0;
- (BOOL)enableInsertFamiliarFeedCard;
- (void)fetchRecommendCardOfFamiliarFeedWithSuccessCompletion:(id /* block */)a0;
- (id)insertUserCardForFamiliarFeedWithContext:(id)a0;
- (void)resetImpressionStatus:(id)a0;
- (void)p_onPersonalRecommendChanged:(id)a0;
- (void)longPressDislikeModel:(id)a0;
- (void)setTrackLongPressParamsWithParams:(id)a0 model:(id)a1;
- (void)postExitPrivacySettingNotification;
- (void)postEnterPrivacySettingNotification;
- (void)reportRateFromScene:(long long)a0;
- (void)resetInsert;
- (void)obdShowOnFamiliarFeed:(id)a0;
- (id)randomMusicURL;
- (BOOL)enableRecommendCardInFeed;
- (BOOL)shouldInsertRecommendCardInFeedIgnoreDelay:(BOOL)a0;
- (id)familiarFeedRecommendItemID;
- (id)randomMusicURLList;
- (id)defaultMusicPlayUrl;
- (BOOL)checkCanInsertInThisFetchWithAwemeList:(id)a0 fetchCount:(long long)a1 ignoreDelay:(BOOL)a2;
- (id)p_viewModelForAweme:(id)a0;
- (void)configureFeedRecommendCardModel:(id)a0 dataSource:(id)a1;
- (void)delayInsertionToNextFetch;
- (long long)dayIntervalOfShow;
- (long long)hotFeedMaxShowCount;
- (long long)allMaxShowCount;
- (long long)recommendCardShowTimesOneDay;
- (void)fetchFamiliarRecommendUserDataWithType:(long long)a0 isAutoTrigger:(BOOL)a1 completion:(id /* block */)a2;
- (id)newBackgroundImageUrl;
- (id)insertRecommendCardWithType:(long long)a0 index:(long long)a1 canShowSlideUpHint:(BOOL)a2;
- (id)recommendUserCardAweme;
- (void)changeInsertFetchAndIndexIsRefresh:(BOOL)a0;
- (void)changeFetchForMultiInsert;
- (long long)insertIndexInHotFeed;
- (BOOL)checkCanInsertInThisFetchWithAwemeList:(id)a0 fetchCount:(long long)a1;
- (long long)familiarFeedRecommendCardShowTimesOneDay;
- (long long)hotFeedRecommendCardShowTimesOneDay;
- (void)impressBigCardWithModel:(id)a0;
- (void)updateRecommendCardCloseDate;
- (id)feedUserRecommendViewController;
- (void)trackSwitchBottomTabDismissIfNeeded:(id)a0;
- (id)keyWithUserID:(id)a0;
- (BOOL)shouldInsertRecommendCardInFeed;
- (void)markCardHasShown;
- (id)recommendExplanationUrl;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end
