@class AWEFeedStickerBubbleHelper, AWEImageAlbumImageModel, AWESearchStickerModel, ACCStickerContainerView, AWEFeedSearchTagStickerDisplayHandler, NSDictionary, UITapGestureRecognizer, AWEFeedStickerContainerView, NSMutableArray, UIView, NSString, ACCFeedStickerConfig, AWEAwemeModel, NSArray;
@protocol AWEVideoInteractiveDelegate, AWEVideoInteractiveDataSource, AWEVideoInteractiveMaskDelegate, AWEPlayInteractionViewControllerProtocol;

@interface AWEFeedStickerDisplayManager : NSObject <AWEFeedStickerDisplayDelegate, AWEFeedStickerBubbleHelperDelegate, UIGestureRecognizerDelegate, AWEVideoInteractiveProtocol>

@property (retain, nonatomic) AWEAwemeModel *model;
@property (retain, nonatomic) AWEImageAlbumImageModel *itemModel;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } targetContainerRect;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } targetPlayerFrame;
@property (nonatomic) BOOL lastStickerCount;
@property (weak, nonatomic) UIView *outerContainer;
@property (retain, nonatomic) AWEFeedStickerContainerView *containerView;
@property (retain, nonatomic) ACCStickerContainerView *stickerContainer;
@property (retain, nonatomic) AWEFeedStickerBubbleHelper *bubbleHelper;
@property (copy, nonatomic) NSArray *handlers;
@property (retain, nonatomic) AWEFeedSearchTagStickerDisplayHandler *vtagDefaultDataHandler;
@property (nonatomic) BOOL tapPointInside;
@property (retain, nonatomic) UIView *interactionContainer;
@property (retain, nonatomic) NSMutableArray *stickerFrameArray;
@property (retain, nonatomic) UITapGestureRecognizer *singleGesture;
@property (copy, nonatomic) NSString *lastAwemeId;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } searchStickerFrame;
@property (retain, nonatomic) ACCFeedStickerConfig *feedStickerConfig;
@property (weak, nonatomic) id<AWEPlayInteractionViewControllerProtocol> InteractionDelegate;
@property (nonatomic) double searchPauseTagPausedTime;
@property (nonatomic) BOOL isMaskControllerContainer;
@property (nonatomic) BOOL isMaskControllerInRichContentContainer;
@property (weak, nonatomic) id<AWEVideoInteractiveMaskDelegate> maskControllerDelegate;
@property (weak, nonatomic) id<AWEVideoInteractiveDelegate> delegate;
@property (weak, nonatomic) id<AWEVideoInteractiveDataSource> dataSource;
@property (nonatomic) BOOL shouldIgnorePauseTagDisplay;
@property (retain, nonatomic) AWESearchStickerModel *defaultStickerModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, weak, nonatomic) UIView *container;
@property (nonatomic) BOOL isGlobalStickerContainer;
@property (nonatomic) BOOL isPureMode;
@property (nonatomic) BOOL pauseTagDataFromRequest;
@property (copy, nonatomic) NSDictionary *videoInfoDict;
@property (copy, nonatomic) NSString *referString;
@property (copy, nonatomic) NSDictionary *logExtraDict;
@property (copy, nonatomic) NSDictionary *trackContext;
@property (weak, nonatomic) UIView *bubbleContainer;
@property (readonly, nonatomic) BOOL bubbling;
@property (nonatomic) BOOL showWithVideoPausing;
@property (nonatomic) BOOL disableUpdateContainer;
@property (nonatomic) BOOL interactionDisabled;

+ (BOOL)hasQuickFlashSticker:(id)a0;
+ (void)joinQuickFlashWithAwemeModel:(id)a0 enterFrom:(id)a1 logExtraDict:(id)a2;
+ (void)processAlbumImagesData:(id)a0;
+ (Class)aAWESearchModuleServiceDOUYINSSAdaperClass;
+ (BOOL)checkSearchTagIsCoupon:(id)a0;
+ (BOOL)enableAISearchNewFrameWorkScanCircle;
+ (BOOL)imageAlbumStickerOptimizeWithAd:(id)a0;
+ (id)firstMatchQuickFlashSticker:(id)a0;
+ (BOOL)hasGlobalStickers:(id)a0;
+ (struct CGSize { double x0; double x1; })globalStickerSize:(id)a0 itemModel:(id)a1;
+ (BOOL)isImageFormat:(id)a0;

- (void)dealloc;
- (void)setPureMode:(BOOL)a0;
- (BOOL)stickersDidTap:(struct CGPoint { double x0; double x1; })a0;
- (BOOL)tryToHandleTapVideoShareStickerInPoint:(struct CGPoint { double x0; double x1; })a0;
- (void)handleEventWithParams:(id)a0;
- (long long)numOfStickers;
- (BOOL)isShowingStickersViewController;
- (void)updateStickerState;
- (void)dismissAllSearchTag;
- (BOOL)isStickersAreaTapped;
- (id)hunterContainerForLynxSticker;
- (void)updateShareAwemeStickerContent:(id)a0;
- (id)allStickerViews;
- (void)recordCurrentSearchPauseTagPausedTime;
- (void)dismissStickers;
- (void)playerIsPaused;
- (void)playerIsResumed;
- (void)videoDelegateDidChangedWithInteractionDelegate:(id)a0;
- (void)updateModernInteractiveContainer:(id)a0;
- (BOOL)isShowingStickers;
- (void)configWithAwemeModel:(id)a0 withIndex:(long long)a1;
- (void)configWithStickerConfig:(id)a0;
- (void)trackShowIfNeeded;
- (void)configWithAwemeModel:(id)a0;
- (BOOL)stickersDidLongPress:(struct CGPoint { double x0; double x1; })a0;
- (double)currentPlayerTime;
- (BOOL)isOverlap;
- (id)aAWESearchModuleServiceDOUYINSSAdaper;
- (void)removeAllStickers;
- (void)videoPlay;
- (void)videoPause;
- (BOOL)getSearchVisionTagOptimizeClientV3Enable;
- (BOOL)isFastCommentElementAppear;
- (id)interactionBottomContainerView;
- (id)interactionLeftContainerView;
- (id)interactionRightContainerView;
- (id)targetHandlerForTapAtPoint:(struct CGPoint { double x0; double x1; })a0;
- (BOOL)haveSearchDefaultTag;
- (void)createSearchHandlers;
- (id)searchTagCouponFilterWithHandlers:(id)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })adjustStickerFrame:(id)a0;
- (BOOL)checkSearchDefaultTagShouldHidden;
- (id)getBTM:(id)a0;
- (void)configAllHandlersDataWithArray:(id)a0;
- (id)createCommonSearchTrackParams;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })tryAdjustStickerPauseFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)pageJumped;
- (void)bubbleStatusChanged:(BOOL)a0;
- (BOOL)searchPauseTagDataFromRequest;
- (double)searchTagPausedTimestamp;
- (void)resetSearchTagPausedTimestamp;
- (void)trackBusinessShow;
- (void)setupDisplayManager:(id)a0;
- (void)doubleClicked:(id)a0;
- (BOOL)isTapInCenter:(id)a0;
- (id)getVideoHandlers;
- (void)configAllHandlersData;
- (id)searchTagFrameFilterWithHandlers:(id)a0 tagStatus:(id)a1;
- (id)searchTagDuplicateFilterWithHandlers:(id)a0 tagStatus:(id)a1;
- (id)searchTagCountFilterWithHandlers:(id)a0 tagStatus:(id)a1;
- (id)createSearchDefaultHandlerWithNewhandlers:(id)a0 defaultStickerModel:(id)a1 playTime:(id)a2 tagStatus:(id)a3;
- (void)trackShowSearchIconFailWithContent:(id)a0 failReason:(id)a1;
- (BOOL)getSearchVisionTagAvoidLeftRightBorderEnable;
- (BOOL)p_configStickerEnabled:(id)a0;
- (void)configHandlers;
- (void)displayStickers;
- (BOOL)p_enableGlobalStickers:(id)a0;
- (void)showPlayerFrame;
- (id)interactionContainerView;
- (void)prepareForDisplay;
- (void)longPress:(id)a0;
- (void)dismiss;
- (void).cxx_destruct;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (void)viewWillAppear;
- (id)initWithContainer:(id)a0;
- (void)reset;
- (BOOL)pointInside:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (BOOL)blockAction;
- (BOOL)isVideoPlaying;
- (void)tapAction:(id)a0;
- (void)viewWillDisappear;

@end
