@class _TtC16AWELiveSwiftImpl26AWEFeedLiveTabParamsCenter, NSDictionary, AWEFeedLiveTabRevisitFoldView, AWEFeedLiveTabRevisitControlView, NSMutableArray, UIView, NSString, AWEFeedLiveMultiTabPreviewStreamViewController, NSTimer, AWEFeedLiveTabRevisitEventView, AWEFeedLiveTabComponentLoader, FeedFollowUpVisitData, AWEFeedLiveTabTopSelectionView;
@protocol AWEFeedLiveTabRevisitDataCenterService, IESLiveDI, AWEXTabBaseChannelControllerProtocol, AWEFeedLiveTabMultiTabDataCenterService;

@interface AWEFeedLiveTabViewController : UIViewController <AWELiveTabTransitionOutterContextProvider, AWEFeedLiveTabComponentLoaderProtocol, AWEFeedLiveTabViewControllerService, AWEFeedLiveTabRevisitFoldViewDelegate, AWEFeedLiveTabRevisitEventViewDelegate, AWEUserMessage, AWEHPContentVCChannelConfigProtocol, AWEHPLeftSlideToUserProtocol, AWELiveVideoFeedUpdateMessage, AWEFeedLiveTabSelectionAction, IESLivePipActions, AWEFeedTabItemViewControllerProtocol, AWEFeedLiveTabViewControllerProtocol>

@property (retain, nonatomic) NSMutableArray *componentOrderArray;
@property (retain, nonatomic) NSMutableArray *componentMetaArray;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) id<IESLiveDI> liveTabDI;
@property (retain, nonatomic) NSDictionary *landingParams;
@property (nonatomic) BOOL isLiveTabEnterOtherPage;
@property (nonatomic) BOOL isTabDisappear;
@property (retain, nonatomic) NSTimer *followUpTimer;
@property (retain, nonatomic) NSTimer *animationTimer;
@property (nonatomic) long long pageViewState;
@property (nonatomic) long long loadType;
@property (retain, nonatomic) _TtC16AWELiveSwiftImpl26AWEFeedLiveTabParamsCenter *paramsCenter;
@property (retain, nonatomic) FeedFollowUpVisitData *visitData;
@property (retain, nonatomic) AWEFeedLiveTabComponentLoader *componentHolder;
@property (retain, nonatomic) id<AWEFeedLiveTabMultiTabDataCenterService> multiTabDataCenter;
@property (retain, nonatomic) id<AWEFeedLiveTabRevisitDataCenterService> revisitDataCenter;
@property (retain, nonatomic) UIView *portalContainerView;
@property (retain, nonatomic) AWEFeedLiveMultiTabPreviewStreamViewController *multiTabPreViewVC;
@property (retain, nonatomic) UIView *multiTabBackgroundView;
@property (retain, nonatomic) AWEFeedLiveTabRevisitControlView *controlView;
@property (retain, nonatomic) AWEFeedLiveTabRevisitFoldView *foldView;
@property (retain, nonatomic) AWEFeedLiveTabRevisitEventView *eventView;
@property (retain, nonatomic) AWEFeedLiveTabTopSelectionView *tabSelectionView;
@property (retain, nonatomic) UIView *loadingContainer;
@property (nonatomic) BOOL hasLazyLoadRevisit;
@property (nonatomic) BOOL didReceiveFirstFrame;
@property (weak, nonatomic) id<AWEXTabBaseChannelControllerProtocol> channelController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) long long type;
@property (readonly, copy, nonatomic) NSString *referString;

- (id)aweui_emptyPageConfigForState:(unsigned long long)a0;
- (void)aweui_emptyPagePrimaryButtonTapped:(id)a0;
- (void)didFinishLoginWithUid:(id)a0;
- (void)didFinishLogoutWithUid:(id)a0;
- (void)pauseWithAnimation;
- (void)transition_didStartTransitionWithContext:(id)a0;
- (BOOL)btm_autoManaged;
- (id)btm_pageIdentifier;
- (id)currentAweme;
- (void)animatedRefreshWithCompletion:(id /* block */)a0;
- (BOOL)currentTabIsTop;
- (void)onAwemeDeleted:(id)a0 isDislike:(BOOL)a1;
- (void)onAwemeDeleted:(id)a0 isLiveFinish:(BOOL)a1 isDislike:(BOOL)a2;
- (double)getPlayTimeStamp;
- (void)loadMoreFeed;
- (id)transition_destinatedViewControllerForSlideDirection:(unsigned long long)a0 gestureRecognizer:(id)a1;
- (unsigned long long)transition_destinatedType;
- (void)setChannelConfig:(id)a0;
- (void)showGuideIfNeed;
- (void)handleConnectionChanged:(id)a0;
- (void)willFromPipToRoomWithShowType:(unsigned long long)a0;
- (id)guideContent;
- (void)setLoadingViewShowByOuterBiz:(BOOL)a0;
- (void)changeToIndex:(long long)a0;
- (void)feedHasSlideToModel:(id)a0;
- (void)p_showLoadingView;
- (void)onCatchViewTouched;
- (void)onCatchViewPanned;
- (id)getHandleLeftSlideToUserTableVC;
- (BOOL)canShowLeftSlideToUserGuide;
- (void)initFetch;
- (void)showLoadingView:(BOOL)a0;
- (void)stopGuideAnimation;
- (void)feedLiveTabDidEnter:(id)a0;
- (void)feedLiveTabDidLeave:(id)a0;
- (long long)currentPageViewState;
- (void)sendLiveTabRequestWithPullType:(long long)a0 params:(id)a1 completion:(id /* block */)a2;
- (void)sendLiveTabRequestWithPullType:(long long)a0 params:(id)a1 revisitCompletion:(id /* block */)a2 tabCompletion:(id /* block */)a3 completion:(id /* block */)a4;
- (void)sendLiveTabMultiDataRequestWithPullType:(long long)a0 params:(id)a1 completion:(id /* block */)a2;
- (void)sendLiveTabRevisitDataRequestWithPullType:(long long)a0 params:(id)a1 completion:(id /* block */)a2;
- (void)handlePreloadLiveTabDataRequest;
- (void)updateControlViewIfNeedWithParams:(id)a0 completion:(id /* block */)a1;
- (void)loadMoreFeedWithTabId:(long long)a0;
- (void)deleteComponentWithTagStr:(id)a0 completion:(id /* block */)a1;
- (void)insertComponentWithTagStr:(id)a0 componentData:(id)a1 atIndex:(unsigned long long)a2 completion:(id /* block */)a3;
- (void)renderTabSelectionView:(id)a0;
- (void)liveTabDidStartFirstFrameWithTabId:(long long)a0;
- (void)renderPortalView;
- (BOOL)canRefreshWithNetError;
- (void)feedLiveTabDidEnterBackground;
- (void)feedLiveTabDidEnterForeground;
- (void)bindService;
- (double)containerSafeTopPadding;
- (double)containerSafeBottomPadding;
- (long long)landingTabID;
- (id)landingTabName;
- (id)p_addRequestParams;
- (void)requestLocalComponentsCompleteWithData:(id)a0 blockTypes:(id)a1 error:(id)a2;
- (void)onRevisitEventViewTouched;
- (id)initWithEnterFrom:(id)a0 params:(id)a1 loadType:(long long)a2;
- (void)p_sendLiveTabRequestWithPullType:(long long)a0 params:(id)a1 revisitCompletion:(id /* block */)a2 tabCompletion:(id /* block */)a3 completion:(id /* block */)a4;
- (void)requestLiveTabInfoWithPullType:(long long)a0 params:(id)a1 completion:(id /* block */)a2;
- (void)requestRevisitInfoWithPullType:(long long)a0 params:(id)a1 completion:(id /* block */)a2;
- (void)handleLiveTabRequestResultTabSuccess:(BOOL)a0 revisitSuccess:(BOOL)a1 pullType:(long long)a2;
- (void)layoutMultiTab;
- (void)clearDuplicateInfos:(id)a0 pullType:(long long)a1;
- (void)handleMultiTabRequestData:(id)a0 pullType:(long long)a1;
- (BOOL)matchWatchLayerWithLiveTabData:(id)a0;
- (void)lazyLayoutRevisit;
- (void)handleRevisitRequestData:(id)a0 pullType:(long long)a1;
- (void)layoutRevisit;
- (void)handleComponentWithLiveTabData:(id)a0 blockTypes:(id)a1;
- (void)updateLandingParamsFrom:(id)a0;
- (void)setupManager:(id)a0;
- (void)setupComponentHolder;
- (void)deleteInnerItemNotification:(id)a0;
- (void)deleteOuterItemNotification:(id)a0;
- (void)skipToNextRoomNotification:(id)a0;
- (id)redDotExtraModel;
- (void)p_refreshVisitIfNeed:(BOOL)a0;
- (void)requestShowFollowupIfNeed;
- (void)p_invalidTimer;
- (void)p_playGuideIfNeedWithDuration:(double)a0 type:(long long)a1;
- (void)loadMultiTab;
- (void)loadRevisit;
- (void)setMultiTabPreViewVCCornerRadius;
- (double)portalViewHeight;
- (void)loadControlView;
- (void)revisitShowChanged:(BOOL)a0 type:(long long)a1;
- (void)clearMultiTabPreViewVCCornerRadius;
- (void)p_dismissLoadingView;
- (BOOL)canUsePreloadLiveTabData;
- (void)p_cleanRequestParams;
- (void)lazyInitFetchRevisit;
- (id)getFollowUpReqVisitType;
- (void)trackerFollowupShow:(int)a0;
- (void)clickCloseRevisit;
- (void)clickOpenRevisitEvent:(BOOL)a0 visitType:(int)a1;
- (void)trackerFollowupClick:(int)a0 showingFollowup:(BOOL)a1;
- (void)p_openRevisitView;
- (void)p_closeRevisitView;
- (void)lazyLoadRevisit;
- (void)p_openRevisitViewAnimation;
- (void)p_showTopSelectionView:(BOOL)a0;
- (void)p_closeRevisitViewWithDuration:(double)a0;
- (BOOL)enableImmediatelyPlayGuideWithType:(long long)a0;
- (id)landingGuideSource;
- (id)appearGuideSource;
- (void)p_showRevisitViewWithAnimation;
- (void)p_closeRevisitViewImmediately;
- (id)feedTableViewController:(long long)a0;
- (BOOL)canRefresh;
- (void).cxx_destruct;
- (void)setScrollEnabled:(BOOL)a0;
- (void)play;
- (void)pause;
- (void)reload;
- (void)stop;
- (void)addObserver;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })a0 withTransitionCoordinator:(id)a1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (id)eventName;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;

@end
