@class UIViewController, NSString, AWESocialRelationObserver, NSDate, NSNumber, AFDAmbassador;
@protocol AWEFeedTableViewControllerFriendsAmbassadarProtocol, AWEAwemeDetailTableViewControllerProtocol, AWEFeedTrackControllerProtocol;

@interface AWEFeedFriendsController : AWEBaseController <AWEFeedTrackControllerListenerProtocol, AWEFeedControllerProtocol, AFDAwemePermissionMessage, AWEUserMessage>

@property (weak, nonatomic) id<AWEFeedTrackControllerProtocol> feedTrackController;
@property (retain, nonatomic) AWESocialRelationObserver *mateObserver;
@property (retain, nonatomic) NSNumber *lastIndex;
@property (retain, nonatomic) NSDate *story25CurrentStartTime;
@property (nonatomic) double story25AccumulatedDuration;
@property (nonatomic) BOOL story25IsRunning;
@property (retain, nonatomic) AFDAmbassador<AWEFeedTableViewControllerFriendsAmbassadarProtocol> *friendsAmbassador;
@property (retain, nonatomic) NSNumber *lastImpressionOrder;
@property (nonatomic) BOOL isFriendsQuicklySlideMaskGuide;
@property (retain, nonatomic) UIViewController<AWEAwemeDetailTableViewControllerProtocol> *detailViewController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (Class)aAWELiteUGSocialModuleAdapterClass;

- (void)didFinishLogoutWithUid:(id)a0;
- (void)didFinishUnFollowUser:(id)a0 status:(long long)a1 error:(id)a2;
- (void)didFinishBlockUser:(id)a0 status:(long long)a1;
- (void)didFinishUnBlockUser:(id)a0 status:(long long)a1;
- (void)didFinishHidePostFromHer:(id)a0 status:(long long)a1;
- (void)didFinishUnHidePostFromHer:(id)a0 status:(long long)a1;
- (void)didFinishTapTAIsFriendWithUser:(id)a0 isFriend:(BOOL)a1;
- (void)didFinishRemoveFansWithUser:(id)a0;
- (id)currentAweme;
- (void)didChangePrivateRelationWithUser:(id)a0 relationType:(long long)a1 relationValue:(long long)a2;
- (void)didChangeAwemePrivacyType:(id)a0 privacyPermissionType:(long long)a1 extra:(id)a2 syncHandle:(id /* block */)a3;
- (void)insertVideosToFamiliarFeedWithAweme:(id)a0;
- (void)initialFetchCompletion:(id)a0 error:(id)a1;
- (void)loadMoreCompletion:(id)a0 error:(id)a1 isFooterRefreshing:(BOOL)a2;
- (void)refreshCompletion:(id)a0 error:(id)a1 needAnimation:(BOOL)a2;
- (void)beginRefresh;
- (void)onDataSourceReload;
- (void)configureCellBrforeSetParentVC:(id)a0 withModel:(id)a1 atIndexPath:(id)a2;
- (void)configureCellAfterSetParentVC:(id)a0 withModel:(id)a1 atIndexPath:(id)a2;
- (void)insertAwemeWithUploadSuccess:(id)a0;
- (void)insertVideosToFeedFromHotLaunchWithAwemeIDs:(id)a0 extraInfo:(id)a1;
- (void)insertVideosToFeedFromHotLaunchWithAwemeIDs:(id)a0 extraInfo:(id)a1 completion:(id /* block */)a2;
- (void)viewDidLoadBeforeTableviewSetup;
- (void)viewDidLoadAfterTableviewSetup;
- (void)tableView:(id)a0 didEndDisplayingCellBeforeReset:(id)a1 forRowAtIndexPath:(id)a2;
- (void)scrollViewDidScrollEndWithActive;
- (void)deleteRecommendAwemeIfNeeded;
- (void)addNotifications;
- (void)showAllUIElementForCell:(id)a0;
- (id)paramsForTrackEventType:(unsigned long long)a0 initialContextParams:(id)a1;
- (void)didTrackEventWithTrackEventType:(unsigned long long)a0 initialContextParams:(id)a1 allTrackParams:(id)a2;
- (void)onCommentAddNotification:(id)a0;
- (id)paramsForEnterPersonalDetail;
- (id)aAWELiteUGSocialModuleAdapter;
- (void)__removeMaskIfCurrentCellHasFeedTableViewCellMaskView;
- (void)removeMaskIfCurrentCellHasFeedTableViewCellMaskView;
- (id)awe_createTipsLabel;
- (void)momentDidPublishNotification:(id)a0;
- (void)p_toFeedTab;
- (id)getBackToFeedMaskViewWithCell:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 isFriendsQuicklySlideMaskGuide:(BOOL)a1;
- (void)familiarDetailViewControllerDeleteAwemeWithUserID:(id)a0;
- (void)trackClickReturnGuide;
- (void)transferToInferiorQualityDetailViewController:(id)a0;
- (void)setFriendsAmbassador;
- (void)configureInteractionTypeWithCell:(id)a0 model:(id)a1;
- (id)friendsAmbassadarDelegate;
- (void)updateImprOrderOfAweme:(id)a0;
- (void)removeAwemesWithUserIDsIfNeedForHot:(id)a0;
- (void)removeAwemesByRecommendToFriendWithUserID:(id)a0 reason:(id)a1;
- (BOOL)p_isTargetAweme:(id)a0 withJudgeBlock:(id /* block */)a1;
- (void)deletePersonalRecommendAwemeIfNeeded;
- (void)removeMomentPublishFailed:(id)a0;
- (void)p_handleMateDislikeNotification:(id)a0;
- (void)observeMateSate;
- (void)updateMateState:(id)a0;
- (void)didTrackEnterPersonalDetailWithAllTrackParams:(id)a0;
- (void)willEnterForeground;
- (void).cxx_destruct;
- (void)play;
- (void)didEnterBackground;
- (void)scrollViewWillEndDragging:(id)a0 withVelocity:(struct CGPoint { double x0; double x1; })a1 targetContentOffset:(inout struct CGPoint { double x0; double x1; } *)a2;
- (void)tableView:(id)a0 willDisplayCell:(id)a1 forRowAtIndexPath:(id)a2;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)tableView:(id)a0 didEndDisplayingCell:(id)a1 forRowAtIndexPath:(id)a2;
- (void)viewWillDisappear:(BOOL)a0;

@end
