@class AWEFeedTableViewControllerResumeConfig, AWEConcernRedDotController, AWEAwemeModel, NSString, UIViewController;
@protocol AWEHPChannelControllerConfigProtocol, AWEFeedTabItemViewControllerProtocol;

@interface AWEFeedFollowChannelController : NSObject <AWEConcernYellowDotBusinessControllerDelegate, AWEInnerNotificationMessage, AWEUGDesktopChannelGuideMessage, AWEMessageReachChannelCommunicator, AWEUGSceneDesktopChannelGuideEvadeProtocol, AWEHPChannelControllerProtocol>

@property (nonatomic) BOOL isBubbleDemote;
@property (nonatomic) BOOL isBubbleDidFinished;
@property (retain, nonatomic) UIViewController<AWEFeedTabItemViewControllerProtocol> *contentVC;
@property (retain, nonatomic) UIViewController<AWEFeedTabItemViewControllerProtocol> *guestVC;
@property (retain, nonatomic) AWEConcernRedDotController *redDotController;
@property (nonatomic) double lastBubbleShowTime;
@property (nonatomic) long long lastBubbleMode;
@property (copy, nonatomic) AWEAwemeModel *enterAwemeModel;
@property (retain, nonatomic) AWEFeedTableViewControllerResumeConfig *resumeConfig;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<AWEHPChannelControllerConfigProtocol> config;

+ (Class)aAWEFeedModuleServiceDOUYINHTSAdaperClass;

- (BOOL)shouldDesktopChannelGuideEvadeWithScene:(id)a0 enterFrom:(id)a1;
- (void)channelTopTabDidSelect;
- (void)showDesktopChannelGuide:(id)a0 config:(id)a1 guideType:(id)a2;
- (BOOL)channelRefreshWithModel:(id)a0 completion:(id /* block */)a1;
- (void)channelEnterWithModel:(id)a0;
- (void)channelLeaveWithModel:(id)a0;
- (void)channelTopTabContainerDidAppear;
- (void)channelTopTabDidUnSelect;
- (void)innerNotificationWillDisplay:(id)a0;
- (void)innerNotificationDidDisplay:(id)a0;
- (void)refreshIfYellowDotIsShowing;
- (void)hiddenYellowDot:(id /* block */)a0;
- (id)aAWEFeedModuleServiceDOUYINHTSAdaper;
- (id)liveAvatarsBubbleContentConfigWith:(id)a0;
- (void)showPointYellowDotWithComponentID:(id)a0 completion:(id /* block */)a1;
- (void)showTextYellowDotWithComponentID:(id)a0 text:(id)a1 completion:(id /* block */)a2;
- (void)showNumberYellowDotWithComponentID:(id)a0 count:(unsigned long long)a1 completion:(id /* block */)a2;
- (void)showFollowBubbleWithConfig:(id)a0;
- (void)hideFollowBubbleWithConfig:(id)a0;
- (BOOL)currentFollowFeedAwemeIsAntiAddict;
- (id)getCustomTrackParamsWithTrackInfo:(id)a0;
- (void)followTabAwemePlayBegin:(id)a0;
- (void)followTabGeneralAwemePlayEnd:(id)a0;
- (void)followTabAlbumAwemePlayEnd:(id)a0;
- (BOOL)isGuestFollowPage;
- (void)generateGuestVCIfNeeded;
- (void)generateContentVCIfNeeded;
- (void)setupChannelConfigIfNeed;
- (BOOL)isHTSFollowPage;
- (void)updateTopBottomBarThemeStyle;
- (BOOL)isOldFollowPage;
- (BOOL)awe_isSkylightOpen;
- (id)getContentVC;
- (BOOL)mr_isSkylightOpen;
- (id)singleAvatarBubbleContentConfigWith:(id)a0;
- (double)channelBubbleShowingDurationWithConfig:(id)a0;
- (id)getNetworkQualityParams;
- (void)updateEnterTrackerInfoWithRealEnterFrom:(id)a0;
- (void)updateEnterTrackerInfoWithEnterFrom:(id)a0 transitionType:(long long)a1;
- (void)trackYellowDot;
- (void)trackEnterHomepageFollowWithModel:(id)a0;
- (void)followTabPinTopViewShow;
- (BOOL)canShowLeftSlideGuide;
- (BOOL)channelTopTabShouldRepeatedClickTab;
- (void)channelTopTabItemTapGestureRecognizerShouldReceiveTouchWithParams:(id)a0;
- (void)channelDidLoadWithType:(unsigned long long)a0;
- (void)channelDidReload;
- (void)channelLandingTabWithModel:(id)a0;
- (void)channelTrackRefreshWithModel:(id)a0;
- (void)channelShowTopBar;
- (BOOL)slidingScrollViewShouldScrollWithPanGestureRecognizer:(id)a0;
- (double)interactionRightContainerHeight;
- (double)nextInteractionRightContainerHeight;
- (BOOL)canShowFeedPendantWithChannelIDs:(id)a0;
- (void)channelWillEnterForeground;
- (void)channelDidEnterBackground;
- (BOOL)channelReleaseContentViewController:(id)a0;
- (id)channelGetCommunicationObject:(id)a0 byProtocol:(id)a1;
- (void)channel:(id)a0 startPreload:(unsigned long long)a1 completion:(id /* block */)a2;
- (id)getContentViewController;
- (id)doubleAvatarsBubbleContentConfigWith:(id)a0;
- (void).cxx_destruct;
- (id)position;
- (id)initWithConfig:(id)a0;
- (void)dealloc;
- (id)sceneType;
- (id)tabID;

@end
