@class UIPanGestureRecognizer, AWEGrouponLifeSwipeUpGuideView, UIViewController, NSMutableArray, UIButton, UIView, UIScrollView, NSString, AWEGrouponHalfScreenDismissAnimationController, AWEGrouponHalfScreenContainerModel, AWEGrouponHalfScreenAnimation, CAShapeLayer, NSArray, AWEGrouponHalfScreenShowAnimationController;

@interface AWEGrouponHalfScreenContainerViewController : UIViewController <BDXPoolContainerDelegate, UIGestureRecognizerDelegate, BDXContainerLifecycleProtocol, AWEGrouponHalfScreenShowAnimationProvider, AWEGrouponHalfScreenDismissAnimationProvider, AWEGrouponFeedEventMessage, AWEGrouponHalfScreenContainerProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) AWEGrouponHalfScreenContainerModel *containerModel;
@property (retain, nonatomic) UIView *containerView;
@property (retain, nonatomic) CAShapeLayer *containerShapeLayer;
@property (retain, nonatomic) UIViewController *currentContentVC;
@property (retain, nonatomic) UIButton *maskViewButton;
@property (retain, nonatomic) UIPanGestureRecognizer *panGesture;
@property (nonatomic) struct CGPoint { double x; double y; } containerViewPanStartPoint;
@property (nonatomic) BOOL isMaxStatusWhenPanStart;
@property (nonatomic) BOOL isRedirectContent;
@property (retain, nonatomic) id containerContent;
@property (retain, nonatomic) UIScrollView *contentScrollView;
@property (retain, nonatomic) UIView *contentView;
@property (retain, nonatomic) NSMutableArray *subscribeList;
@property (retain, nonatomic) AWEGrouponHalfScreenShowAnimationController *showController;
@property (retain, nonatomic) AWEGrouponHalfScreenDismissAnimationController *dismissController;
@property (retain, nonatomic) AWEGrouponHalfScreenAnimation *currentShowAnimation;
@property (retain, nonatomic) AWEGrouponHalfScreenAnimation *currentDismissAnimation;
@property (retain, nonatomic) AWEGrouponHalfScreenAnimation *currentTargetAnimation;
@property (nonatomic) long long originHeightPercent;
@property (nonatomic) long long maxHeightPercent;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } angleTargetRect;
@property (nonatomic) double paddingTop;
@property (nonatomic) double containerShowedTimeStamp;
@property (nonatomic) BOOL showCompleted;
@property (retain, nonatomic) UIButton *highLightBtn;
@property (nonatomic) BOOL needFrezedContainerHeight;
@property (retain, nonatomic) AWEGrouponLifeSwipeUpGuideView *swipeUpGuideView;
@property (nonatomic) BOOL didScrollTopTabInGroupon;
@property (copy, nonatomic) NSString *arrowColor;
@property (retain, nonatomic) NSArray *viewInjectorList;
@property (nonatomic) unsigned long long containerViewStyle;
@property (copy, nonatomic) id /* block */ dismissCompletion;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) unsigned long long containerViewState;

- (void)containerDidFirstScreen:(id)a0;
- (void)container:(id)a0 onSetupLynxInfo:(id)a1 bulletInfo:(id)a2;
- (void)container:(id)a0 onUpdateLynxInfo:(id)a1 bulletInfo:(id)a2;
- (void)xpoolContainerDidFinishLoad:(id)a0;
- (void)xpoolContainer:(id)a0 didLoadFailedWithError:(id)a1;
- (void)xpoolContainerDidFirstScreen:(id)a0;
- (void)nearbylifeC2PageFetchFinish:(id)a0 resource:(id)a1 refreshContext:(id)a2 isRefresh:(BOOL)a3;
- (void)hiddenHalfScreenHighLight;
- (void)updateHalfScreenAngleTargetRect:(id)a0 dialogProps:(id)a1;
- (void)updateHalfScreenCloseAnimationTargetView:(id)a0;
- (void)addDitoFMPDoneNotificationIfNeeded:(id)a0;
- (void)recordUserHasScroollTab;
- (void)setupContainerContent:(id)a0;
- (void)maskViewButtonClicked:(id)a0;
- (id)initWithContent:(id)a0 containerModel:(id)a1;
- (void)showContentViewWithCompletion:(id /* block */)a0;
- (void)handleFullScreenPanGesture:(id)a0;
- (void)handlePanGestureStateBegan:(id)a0;
- (void)handlePanGestureStateChanged:(id)a0;
- (void)handlePanGestureStateEnded:(id)a0;
- (double)containerViewLimitTopY;
- (void)publishJSBEvent:(id)a0 params:(id)a1;
- (double)containerViewLimitBottomY;
- (void)dismissHalfScreenWithCloseType:(id)a0;
- (void)trackNearbyHalfScreenInteractionMonitorWithParams:(id)a0;
- (void)changeContainerViewPositionWithNewHeight:(double)a0;
- (void)updateContainerViewState:(unsigned long long)a0;
- (BOOL)shouldDisableHalfScreenHorizontalScrollWhileHalfStateOf:(id)a0;
- (id)findScrollViewInContent;
- (id)findScrollViewInContentOfBDXViewController:(id)a0;
- (id)findScrollViewInContentOfUIViewController:(id)a0;
- (id)__findScrollViewWithParentView:(id)a0;
- (void)registerRedirectJSEvent;
- (void)registerContentPopJSEvent;
- (void)registerHeightChangeJSEvent;
- (void)registerChangeArrowColorJSEvent;
- (void)registerCloseHalfScreenContianerJSEvent;
- (void)trackNearbyHalfScreenJSBMonitorWithParam:(id)a0;
- (void)redirectContentWithSchema:(id)a0;
- (void)halfScreenChangeStatusWithType:(unsigned long long)a0;
- (void)updateHalfScreenArrowColor:(id)a0;
- (void)dismissHalfScreenWithCloseType:(id)a0 showExtraAnimation:(BOOL)a1;
- (void)registerHalfScreenJSEvent;
- (void)reportHalfScreenCloseAnimationExposeIfNeeded;
- (id)showAnimationOfType:(unsigned long long)a0;
- (id)dismissAnimationOfType:(unsigned long long)a0;
- (id)endingAnimationOfType:(unsigned long long)a0;
- (unsigned long long)showAnimationType;
- (unsigned long long)dismissAnimationTypeWithShowExtraAnimation:(BOOL)a0;
- (void)trackNearbyHalfScreenWillClose:(id)a0;
- (void)trackNearbyHalfScreenCloseAnimationDone:(id)a0 animations:(id)a1;
- (void)trackNearbyHalfScreenBecomeFull:(id)a0;
- (void)updateContainerViewStateHalf;
- (void)updateContainerViewStateFull;
- (void)updateContainerViewStateMaxPercent;
- (void)sendHalfScreenInjectedViewEvent:(SEL)a0 funcBlock:(id /* block */)a1;
- (void)postHalfScreenStateChange:(id)a0 params:(id)a1;
- (void)hideSwipeView;
- (BOOL)canShowSwipeUpView;
- (void)setSheetLayout;
- (void)setRichArrowAlertLayout;
- (void)setNomalArrowAlertLayout;
- (void)setupContentOfViewController:(id)a0;
- (void)setupContentOfView:(id)a0;
- (void)transparentAngleTargetRect;
- (void)recordSwipUpViewShow;
- (id)swipeUpShowStorageKey:(id)a0 type:(long long)a1;
- (void)updateAngleTargetRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)updateHalfScreenHeightAndAngleTargetRect;
- (void)highLightButtonClicked:(id)a0;
- (void).cxx_destruct;
- (BOOL)gestureRecognizer:(id)a0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)a1;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (BOOL)gestureRecognizer:(id)a0 shouldBeRequiredToFailByGestureRecognizer:(id)a1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)setupUI;
- (void)handlePanGesture:(id)a0;
- (void)setupLayout;

@end
