@class AWEHomePageContextTabNode, NSString, NSArray, NSMutableDictionary, AWEHPChannelReloadTypeDetail, NSObject, NSDictionary, AWEFeedChannelObject;
@protocol AWEHPXTabUIDelegate, AWEHPCommonTabUIDelegate, AWEHPChannelControllerConfigProtocol, AWEHPTabBarUIDelegate, AWEHPChannelManagerDelegate, AWEHPChannelControllerProtocol, AWEHPTopTabUIDelegate, AWEHPChannelFactoryProtocol, AWEHPRootChanennlManagerDelegate;

@interface AWEHPChannelBaseManager : NSObject <AWEHPChannelBubbleAbilityImpl, AWEHPChannelEditAbilityImpl, AWEHPChannelPageAbilityImpl, AWEHPChannelTabItemAbilityImpl, AWEHPChannelTopBarAbilityImpl, AWEHPChannelControllerProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) id<AWEHPChannelFactoryProtocol> factory;
@property (retain, nonatomic) AWEHomePageContextTabNode *tabNode;
@property (retain, nonatomic) NSArray *nonResumeTabModels;
@property (retain, nonatomic) AWEHPChannelReloadTypeDetail *nonResumeReloadType;
@property (retain, nonatomic) NSMutableDictionary *nonResumeChannelMap;
@property (nonatomic) BOOL isLoaded;
@property (weak, nonatomic) NSObject<AWEHPChannelControllerProtocol> *channelController;
@property (weak, nonatomic) AWEFeedChannelObject *selfChannel;
@property (readonly, nonatomic) AWEHPChannelBaseManager *parentManager;
@property (readonly, nonatomic) AWEFeedChannelObject *selectedChannel;
@property (readonly, nonatomic) NSArray *availableTabIDList;
@property (readonly, nonatomic) NSArray *currentTabIDList;
@property (readonly, nonatomic) NSArray *currentChannels;
@property (readonly, nonatomic) NSDictionary *currentChannelMap;
@property (readonly, nonatomic) NSArray *allChannels;
@property (readonly, nonatomic) NSDictionary *allChannelMap;
@property (weak, nonatomic) NSObject<AWEHPTabBarUIDelegate> *tabBarUIDelegate;
@property (weak, nonatomic) NSObject<AWEHPTopTabUIDelegate> *topTabUIDelegate;
@property (weak, nonatomic) NSObject<AWEHPXTabUIDelegate> *xTabUIDelegate;
@property (weak, nonatomic) NSObject<AWEHPCommonTabUIDelegate> *commonTabUIDelegate;
@property (weak, nonatomic) NSObject<AWEHPRootChanennlManagerDelegate> *rootManagerDelegate;
@property (weak, nonatomic) NSObject<AWEHPChannelManagerDelegate> *managerDelegate;
@property (weak, nonatomic) id<AWEHPChannelControllerConfigProtocol> config;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)channelTopTabDidSelect;
- (BOOL)channelRefreshWithModel:(id)a0 completion:(id /* block */)a1;
- (void)channelTopTabContainerDidAppear;
- (void)channelTopTabContainerDidDisappear;
- (void)channelTopTabDidUnSelect;
- (void)enumerateAllChannelsUsingBlock:(id /* block */)a0;
- (id)getPrePluginControllers;
- (id)getPostPluginControllers;
- (BOOL)awe_isSkylightOpen;
- (BOOL)canShowLeftSlideGuide;
- (void)channelTabBarDidSelect;
- (void)channelTabBarDidUnSelect;
- (BOOL)channelTabBarShouldRepeatedClickTab;
- (BOOL)channelTabBarShouldDoubleClickTab;
- (BOOL)channelTabBarShouldLongPressTab;
- (void)channelTabBarDidSingleTap;
- (void)channelTabBarDidDoubleTap;
- (void)channelTabBarDidLongPress;
- (BOOL)channelShouldForbidTabBarDoubleTap;
- (BOOL)channelTopTabShouldRepeatedClickTab;
- (BOOL)channelTopTabShouldInterceptCommonBubble;
- (BOOL)channelTopTabShouldInterceptCaptionBubble;
- (void)channelTopTabItemTapGestureRecognizerShouldReceiveTouchWithParams:(id)a0;
- (void)channelTopTabItemTapGestureRecognizerStateChangedWithParams:(id)a0;
- (void)topTabScrollDidReachStableEnd;
- (BOOL)channelTopTabItemShouldForbidDoubleTap;
- (void)channelTopTabWillBeginDragging;
- (void)channelTopTabDidScroll;
- (void)channelTopTabDidEndDraggingWithWillDecelerate:(BOOL)a0;
- (void)channelTopTabWillBeginDecelerating;
- (void)channelTopTabDidEndDecelerating;
- (void)channelTopTabDidEndScroll;
- (void)channelDidLoadWithType:(unsigned long long)a0;
- (BOOL)channelAllowReloadWithConfig:(id)a0;
- (void)channelWillReloadWithConfig:(id)a0;
- (void)channelDidReload;
- (BOOL)channelIsAvailableWithError:(id *)a0;
- (void)channelDidUnloadWithType:(unsigned long long)a0;
- (void)channelViewDidLoad;
- (void)channelViewDidUnload;
- (void)channelViewWillAppear;
- (void)channelViewDidAppear;
- (void)channelViewWillDisappear;
- (void)channelViewDidDisappear;
- (void)channelWillEnterWithType:(long long)a0;
- (BOOL)disableOnetimePullRefreshOptWithChannel:(id)a0;
- (BOOL)showTopTabRefreshAnimationWithModel:(id)a0;
- (BOOL)showBottomTabRefreshAnimationWithModel:(id)a0;
- (void)channelHideTopBarWithTransform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })a0 alpha:(double)a1;
- (void)channelShowTopBar;
- (void)channelRefreshGestureRecognizerBegin:(id)a0;
- (void)channelRefreshGestureRecognizerEnd:(id)a0;
- (void)channelRefreshGestureRecognizerStateChanged:(id)a0;
- (unsigned long long)channelRefreshGestureRecognizerDirection:(id)a0;
- (unsigned long long)canLeftSlideToUserPageWithReason:(id *)a0;
- (double)currentCellLeftSlideInteractiveGuideHeight;
- (double)nextCellLeftSlideInteractiveGuideHeight;
- (BOOL)channelDisableFullscreenPopTransition;
- (BOOL)canShowFeedPendantWithChannelIDs:(id)a0;
- (void)channelAppWillResignActive;
- (void)channelDidBecomeActive;
- (void)channelWillEnterForeground;
- (void)channelDidEnterBackground;
- (id)channelGetContentInfo;
- (BOOL)channelShouldHandleTransition_destinatedViewControllerForSlideDirection:(unsigned long long)a0 gestureRecognizer:(id)a1;
- (id)channelTransition_destinatedViewControllerForSlideDirection:(unsigned long long)a0 gestureRecognizer:(id)a1;
- (id)getContentViewController;
- (double)tabSegmentShowPercentWithChannelId:(id)a0;
- (struct CGPoint { double x0; double x1; })bottomCenterOfTabSegmentWithChannelId:(id)a0;
- (void)callTabBarDidUnSelect;
- (void)callTabBarDidSelect;
- (id)getChannelWithIndex:(long long)a0;
- (id)callChannelGetContentInfo;
- (id)getSubChannelUsingRecursiveWithChannelID:(id)a0;
- (id)getRootChannelUsingRecursiveWithChannelID:(id)a0;
- (void)willSetupChannel:(id)a0;
- (void)didSetupChannel:(id)a0;
- (void)updateTopBarSegmentItemWithChannel:(id)a0;
- (BOOL)callCanLandingUsingRecursiveWithConfig:(id)a0;
- (id)getFeedHomePageContextWithChannel:(id)a0;
- (void)didSwitchSelectedChannelFromChannel:(id)a0 toChannel:(id)a1 config:(id)a2;
- (void)channel:(id)a0 updateBottomTabItem:(id)a1;
- (void)channel:(id)a0 updateBottomBarFillBackground:(BOOL)a1;
- (void)channel:(id)a0 updateBottomBarThemeStyle:(unsigned long long)a1;
- (void)channel:(id)a0 updateBottomTabLeftElementButtonViewModels:(id)a1;
- (void)channel:(id)a0 updateBottomTabRightElementButtonViewModels:(id)a1;
- (void)channel:(id)a0 updateBottomTabCompactBGColorFill:(BOOL)a1;
- (void)channel:(id)a0 updateBottomTabCustomCoverViewWithModel:(id)a1;
- (void)channel:(id)a0 updateTopBarThemeStyle:(unsigned long long)a1;
- (void)channel:(id)a0 updateTopBarBadgeSceneStyle:(unsigned long long)a1;
- (void)channel:(id)a0 updateTopTabBrightness:(id)a1;
- (void)callTopTabDidUnSelectWithChannel:(id)a0;
- (void)callTopTabDidSelectWithChannel:(id)a0;
- (void)didUpdateCurrentChannels:(id)a0;
- (void)updateTopTabOrder:(long long)a0 withChannel:(id)a1;
- (void)updateTopTabOrderAlignMainTab:(long long)a0 topRecommendTabOrder:(long long)a1 withChannel:(id)a2;
- (BOOL)getIsLanding;
- (void)callEnterUsingRecursiveWithChannel:(id)a0 model:(id)a1;
- (void)callLeaveUsingRecursiveWithChannel:(id)a0 model:(id)a1;
- (void)enumerateCurrentChannelsUsingBlock:(id /* block */)a0;
- (BOOL)callSaveEditTopTabWithAllChannelIDList:(id)a0 currentChannelList:(id)a1 reloadType:(id)a2 completion:(id /* block */)a3;
- (id)getHomePageContext;
- (void)dismissSelectedChannelPinTopComponentIfNeeded;
- (id)getTopBarStageWithChannel:(id)a0;
- (void)callAllChannelDidLoadWithReloadType:(unsigned long long)a0;
- (void)callTrackEntranceShowWithChannel:(id)a0 model:(id)a1;
- (void)callTopTabContainerDidAppear;
- (void)callTopTabContainerDidDisappear;
- (id)getCommunicationObjectWithChannel:(id)a0 byProtocol:(id)a1;
- (id)getSelectedChannelUsingRecursive;
- (BOOL)callTopTabShouldInterceptCommonBubble;
- (BOOL)callTopTabShouldInterceptCaptionBubble;
- (id)getChannelWithChannelID:(id)a0;
- (BOOL)callCanShowLeftSlideGuide;
- (id)getContentViewControllerWithChannel:(id)a0;
- (BOOL)callVerticalPanGestureRecognizerShouldBegin:(id)a0 reason:(id *)a1;
- (BOOL)callChannelShouldHandleTransition_destinatedViewControllerForSlideDirection:(unsigned long long)a0 gestureRecognizer:(id)a1;
- (id)callChannelTransition_destinatedViewControllerForSlideDirection:(unsigned long long)a0 gestureRecognizer:(id)a1;
- (void)callSelectedChannelDidEndRefreshWithModel:(id)a0;
- (void)callSelectedChannelWillBeginRefreshWithModel:(id)a0;
- (void)callTrackRefreshUsingRecursiveWithModel:(id)a0;
- (id)getSelectedChannelUsingRecursiveWithChannel:(id)a0;
- (void)awe_callTopSegmentControlHidden:(BOOL)a0;
- (id)getReferStringUsingRecursiveWithChannel:(id)a0;
- (BOOL)callTopTabShouldRepeatedClickTab;
- (BOOL)updateSelectedChannelWithIndex:(long long)a0 configBlock:(id /* block */)a1;
- (void)callAppWillResignActive;
- (void)callAppDidBecomeActive;
- (void)callAppWillEnterForeground;
- (void)callAppDidEnterBackground;
- (void)callChannel:(id)a0 startPreloadWithType:(unsigned long long)a1;
- (void)callScrollViewDidFinishSliding;
- (void)callScrollViewDidScrollToIndex:(long long)a0;
- (unsigned long long)getDotSceneStyleWithChannel:(id)a0;
- (id)getChannelInAllChannelsWithChannelID:(id)a0;
- (BOOL)callLandingUsingRecursiveWithConfig:(id)a0;
- (id)getReferStringUsingRecursiveForSelectedChannel;
- (void)callBeginLandingUsingRecursiveWithTabID:(id)a0 model:(id)a1;
- (void)callEndLandingUsingRecursiveWithTabID:(id)a0 model:(id)a1;
- (id)getPageViewControllerWithChannel:(id)a0;
- (void)callChannelTopTabItemTapGestureRecognizerShouldReceiveTouchWithChannel:(id)a0 params:(id)a1;
- (void)callChannelTopTabItemTapGestureRecognizerStateChangedWithChannel:(id)a0 params:(id)a1;
- (BOOL)shouldPresentLightThemeInTopBarWithChannel:(id)a0;
- (BOOL)callSlidingScrollViewShouldScrollWithChannel:(id)a0 panGestureRecognizer:(id)a1 reason:(id *)a2;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })tabSegmentViewRectWithChannel:(id)a0;
- (unsigned long long)callRefreshGestureRecognizerDirection:(id)a0;
- (void)callRefreshGestureRecognizerStateChanged:(id)a0;
- (void)callRefreshGestureRecognizerBegin:(id)a0;
- (void)callRefreshGestureRecognizerEnd:(id)a0;
- (BOOL)callTabBarShouldLongPressTab;
- (BOOL)callTabBarShouldRepeatedClickTab;
- (BOOL)callTabBarShouldDoubleClickTab;
- (id)callSelectedChannelReferString;
- (void)callSelectedChannelPlay;
- (void)callSelectedChannelStop;
- (void)callSelectedChannelPause;
- (void)callSelectedChannelReload;
- (void)callSelectedChannelAnimatedRefreshWithCompletion:(id /* block */)a0;
- (void)callSelectedChannelCancelRefresh;
- (BOOL)callSelectedChannelCurrentTabIsTop;
- (BOOL)callSelectedChannelCanRefresh;
- (void)callSelectedChannelSetScrollEnabled:(BOOL)a0;
- (void)callSelectedChannelPauseWithAnimation;
- (void)callSelectedChannelSeekPlayTimeWithItemID:(id)a0;
- (void)callSelectedChannelOnAwemeMarkDislikeCanWithdraw:(id)a0;
- (void)callSelectedChannelOnAwemeDeleted:(id)a0 isDislike:(BOOL)a1;
- (void)callSelectedChannelOnAwemeDeleted:(id)a0 isLiveFinish:(BOOL)a1 isDislike:(BOOL)a2;
- (id)callSelectedChannelCurrentAwemeID;
- (id)callSelectedChannelCurrentAweme;
- (void)callSelectedChannelSetRefreshMethod:(id)a0;
- (void)callSelectedChannelSetAccessoriesHidden:(BOOL)a0;
- (void)p_appWillResignActiveWithChannel:(id)a0;
- (void)enumerateChannels:(id)a0 usingBlock:(id /* block */)a1;
- (void)callTrackContentVCStayTimeWithChannel:(id)a0 model:(id)a1;
- (void)p_appDidBecomeActiveWithChannel:(id)a0;
- (void)p_appWillEnterForegroundWithChannel:(id)a0;
- (void)p_appDidEnterBackgroundWithChannel:(id)a0;
- (void)callBadgeDidShowWithChannel:(id)a0 badgeContext:(id)a1;
- (void)callBadgeDidDowngradeWithChannel:(id)a0 badgeContext:(id)a1;
- (void)callBadgeDidHideWithChannel:(id)a0 badgeContext:(id)a1;
- (void)callChannelDidChangeDotSceneStyleWithChannel:(id)a0 dotSceneStyle:(unsigned long long)a1;
- (void)p_channel:(id)a0 tabBarShowBubbleWithTask:(id)a1;
- (id)p_getBizTrackParamsWithChannel:(id)a0 trackInfo:(id)a1 bizTrackParamsBlock:(id /* block */)a2;
- (id)p_getBizTrackParamsWithChannel:(id)a0 trackInfo:(id)a1 bizTrackParamsBlock:(id /* block */)a2;
- (void)p_cancelBottomTabItemBubbleWithChannel:(id)a0 task:(id)a1;
- (id)callGetCustomTrackParamsWithChannel:(id)a0 trackInfo:(id)a1;
- (void)channel:(id)a0 showBottomTabItemBubbleWithModel:(id)a1 showCallback:(id /* block */)a2 clickCallback:(id /* block */)a3 dismissCallback:(id /* block */)a4;
- (void)cancelBottomTabItemBubbleWithChannel:(id)a0 isContainerHide:(BOOL)a1;
- (void)callBubbleShowWithChannel:(id)a0 result:(id)a1 model:(id)a2;
- (void)callBubbleDismissWithChannel:(id)a0 type:(long long)a1 model:(id)a2;
- (id)p_channelGetContentInfoWithChannel:(id)a0;
- (id)callChannelGetContentInfoWithChannel:(id)a0;
- (void)p_channel:(id)a0 showPinTopComponentWithModel:(id)a1 configModel:(id)a2 showResult:(id /* block */)a3 pinTopCompletion:(id /* block */)a4;
- (void)p_channel:(id)a0 generatePinTopTaskWithModel:(id)a1 completion:(id /* block */)a2;
- (void)channel:(id)a0 generatePinTopTaskWithModel:(id)a1 completion:(id /* block */)a2;
- (long long)p_canShowPinTopChannel:(id)a0;
- (void)p_channel:(id)a0 invokePinTopWithComponentTask:(id)a1;
- (void)callTopTabPinTopWithChannel:(id)a0 pinTopCallContext:(id)a1 completion:(id /* block */)a2;
- (long long)p_getChannelPinTopIndexWithChannels:(id)a0;
- (long long)p_checkTopTabStableWithAllChannelIDList:(id)a0 currentChannelList:(id)a1;
- (void)updateChannelsWithAllChannelIDList:(id)a0 currentChannelList:(id)a1 selectedChannelID:(id)a2;
- (id)p_generateCurrentChannelItemModelList;
- (id)p_getChannelListAfterPinTopWithTargetChannel:(id)a0 channelList:(id)a1;
- (void)channel:(id)a0 showPinTopComponentWithModel:(id)a1 showResult:(id /* block */)a2 pinTopCompletion:(id /* block */)a3;
- (void)channel:(id)a0 showCommonPinTopComponentWithShowResult:(id /* block */)a1 pinTopCompletion:(id /* block */)a2 source:(id)a3;
- (void)channel:(id)a0 canShowPinTopComponentWithShowResult:(id /* block */)a1;
- (long long)canShowPinTopComponentWithChannelID:(id)a0;
- (void)p_callBeginLandingUsingRecursive;
- (void)p_callEndLandingUsingRecursive;
- (long long)p_canLandingUsingRecursiveWithConfig:(id)a0;
- (id)getChannelByNonResumeModelIfNeedWithChannelID:(id)a0;
- (BOOL)p_canLandingWithChannel:(id)a0 config:(id)a1 needCheckIndex:(BOOL)a2;
- (id)p_generateEnterModelWithLeaveChannel:(id)a0 enterChannel:(id)a1 config:(id)a2;
- (void)callEnterWithChannel:(id)a0 model:(id)a1;
- (id)p_generateLeaveModelWithLeaveChannel:(id)a0 enterChannel:(id)a1 config:(id)a2;
- (BOOL)updateSelectedChannelWithChannel:(id)a0 configBlock:(id /* block */)a1;
- (void)p_landingWithChannel:(id)a0 config:(id)a1;
- (void)callChannelDidLoadWithChannel:(id)a0 reloadType:(unsigned long long)a1;
- (BOOL)callChannelAllowReloadWithChannel:(id)a0 config:(id)a1;
- (void)callChannelWillReloadWithChannel:(id)a0 config:(id)a1;
- (void)callChannelDidReloadWithChannel:(id)a0;
- (BOOL)callChannelIsAvailableWithChannel:(id)a0;
- (void)callChannelDidUnloadWithChannel:(id)a0 reloadType:(unsigned long long)a1;
- (void)updateChannelTopBarMaskWithChannel:(id)a0;
- (BOOL)removeChannelWithChannelID:(id)a0;
- (BOOL)isNumberEqual:(id)a0 numberTwo:(id)a1;
- (void)callChannel:(id)a0 didUpdateSkylight:(id)a1;
- (BOOL)isScrollViewSlidingWithChannel:(id)a0;
- (BOOL)isLandingInProgressWithChannel:(id)a0;
- (void)callViewDidReleaseNotRecursiveWithChannel:(id)a0;
- (void)p_triggerBottomChannelContentViewControllerLoadFinish:(id)a0;
- (void)channel:(id)a0 updateReferString:(id)a1;
- (void)removeChannel:(id)a0;
- (void)channel:(id)a0 updateViewControllerSkylight:(id)a1;
- (void)channel:(id)a0 updateTopBarMaskStatus:(long long)a1;
- (id)getLifeCycleInfoModelWithChannel:(id)a0;
- (id)getContentViewControllerByBusinessWithChannel:(id)a0;
- (void)tryReleaseContentViewControllerWithChannel:(id)a0 withParams:(id)a1 withCompletion:(id /* block */)a2;
- (void)channel:(id)a0 triggerContentViewControllerLoadFinish:(id)a1;
- (void)p_channel:(id)a0 startPreload:(unsigned long long)a1;
- (void)callChannelDidLoadPageViewController:(id)a0;
- (BOOL)p_showTopTabRefreshAnimationWithModel:(id)a0 channel:(id)a1;
- (BOOL)p_showBottomTabRefreshAnimationWithModel:(id)a0 channel:(id)a1;
- (void)callHideTopBarWithChannel:(id)a0 transform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })a1 alpha:(double)a2;
- (void)callShowTopBarWithChannel:(id)a0;
- (BOOL)p_canShowLeftSlideGuideWithChannel:(id)a0;
- (BOOL)p_channelDisableFullscreenPopTransition:(id)a0;
- (BOOL)p_slidingScrollViewShouldScrollWithChannel:(id)a0 controller:(id)a1 panGestureRecognizer:(id)a2 reason:(id *)a3;
- (double)awe_callInteractionRightContainerHeightWithChannel:(id)a0;
- (double)awe_callNextInteractionRightContainerHeightWithChannel:(id)a0;
- (void)callScrollViewDidFinishSlidingWithChannel:(id)a0;
- (double)awe_callInteractionRightContainerHeight;
- (double)awe_callNextInteractionRightContainerHeight;
- (BOOL)callTabBarShouldRepeatedClickTabWithChannel:(id)a0;
- (BOOL)callTabBarShouldDoubleClickTabWithChannel:(id)a0;
- (BOOL)callTabBarShouldLongPressTabWithChannel:(id)a0;
- (void)callTabBarDidSingleClickWithChannel:(id)a0;
- (void)callTabBarDidDoubleClickWithChannel:(id)a0;
- (void)callTabBarDidLongPressWithChannel:(id)a0;
- (BOOL)p_callShouldForbidTabBarDoubleTapWithChannel:(id)a0;
- (void)p_callTabBarDidSelect;
- (void)p_callTabBarDidSelectedWithChannel:(id)a0;
- (void)p_callTabBarDidUnSelect;
- (void)p_callTabBarDidUnSelectedWithChannel:(id)a0;
- (void)channelStartScaleAnimation:(id)a0;
- (void)channel:(id)a0 showBottomTabItemActionPopoverWithActions:(id)a1 preferDarkTheme:(BOOL)a2 showCallback:(id /* block */)a3;
- (void)channel:(id)a0 showBottomTabItemImage:(id)a1 withAnimateType:(long long)a2 withCompletion:(id /* block */)a3;
- (void)channel:(id)a0 cancelBottomTabItemImageWithCompletion:(id /* block */)a1;
- (void)p_callWillEnterWithChannel:(id)a0 type:(long long)a1;
- (void)consumeComponentWhenEnterIfNeed:(id)a0 model:(id)a1;
- (void)p_leaveWithChannel:(id)a0 model:(id)a1;
- (void)p_trackRefreshWithChannel:(id)a0 model:(id)a1;
- (void)callWillEnterWithChannel:(id)a0 type:(long long)a1;
- (void)p_callTopSegmentControlHidden:(BOOL)a0 withChannel:(id)a1;
- (void)channel:(id)a0 topBarUpdateEntranceWithModel:(id)a1 completion:(id /* block */)a2;
- (void)p_channel:(id)a0 topTabShowBadgeWithTask:(id)a1;
- (void)channel:(id)a0 topBarShowBadgeWithModel:(id)a1 preCheckCallBack:(id /* block */)a2 showCallBack:(id /* block */)a3 hideCallBack:(id /* block */)a4 downgradeCallBack:(id /* block */)a5;
- (BOOL)p_channel:(id)a0 shouldBlockEmptyIDWithModel:(id)a1 isBadgeType:(BOOL)a2;
- (void)p_channel:(id)a0 topTabShowBubbleWithTask:(id)a1;
- (void)channel:(id)a0 topBarShowBubbleWithModel:(id)a1 preCheckCallBack:(id /* block */)a2 showCallback:(id /* block */)a3 clickCallback:(id /* block */)a4 dismissCallback:(id /* block */)a5;
- (void)p_channel:(id)a0 topBarCancelBubbleWithTask:(id)a1 completion:(id /* block */)a2 isContainerHide:(BOOL)a3;
- (BOOL)isCurrentChannelWithChannel:(id)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })topBarContainerFrameChannel:(id)a0;
- (struct CGPoint { double x0; double x1; })channel:(id)a0 topCenterPointOfWindowWithChannelId:(id)a1;
- (void)channel:(id)a0 topBarShowBadgeWithModel:(id)a1 showCallBack:(id /* block */)a2 hideCallBack:(id /* block */)a3 downgradeCallBack:(id /* block */)a4;
- (void)channel:(id)a0 topBarHideBadgeWithCompletion:(id /* block */)a1 isBeforeChannelUnload:(BOOL)a2;
- (void)channel:(id)a0 topBarShowBubbleWithModel:(id)a1 showCallback:(id /* block */)a2 clickCallback:(id /* block */)a3 dismissCallback:(id /* block */)a4;
- (void)channel:(id)a0 topBarCancelBubbleWithCompletion:(id /* block */)a1 isContainerHide:(BOOL)a2;
- (void)channel:(id)a0 topBarChangeAlphaWith:(double)a1;
- (void)channel:(id)a0 scrollToTabSegmentWithChannelId:(id)a1 animated:(BOOL)a2;
- (BOOL)callChannelTopTabItemShouldForbidDoubleTapWithChannel:(id)a0;
- (void)p_channelTopTabWillBeginDraggingWithChannel:(id)a0;
- (void)p_channelTopTabDidScrollWithChannel:(id)a0;
- (void)p_channelTopTabDidEndDraggingWithWillDecelerate:(BOOL)a0 channel:(id)a1;
- (void)p_channelTopTabWillBeginDeceleratingWithChannel:(id)a0;
- (void)p_channelTopTabDidEndDeceleratingWithChannel:(id)a0;
- (void)p_channelTopTabDidEndScrollWithChannel:(id)a0;
- (void)p_callTopTabContainerDidAppear;
- (void)p_callTopTabContainerDidAppearWithChannel:(id)a0;
- (void)p_callTopTabContainerDidDisappear;
- (void)p_callTopTabContainerDidDisAppearWithChannel:(id)a0;
- (BOOL)p_callTopTabShouldRepeatedClickTab;
- (BOOL)p_callTopTabShouldRepeatedClickTabWithChannel:(id)a0;
- (void)p_callTopTabDidSelectedWithChannel:(id)a0;
- (void)p_callTopTabDidSelectUsingRecursive;
- (void)p_callTopTabDidUnSelectWithChannel:(id)a0;
- (void)p_callTopTabDidUnSelectUsingRecursive;
- (BOOL)p_callTopTabShouldInterceptCommonBubble;
- (BOOL)p_callTopTabShouldInterceptCommonBubbleWithChannel:(id)a0;
- (BOOL)p_callTopTabShouldInterceptCaptionBubble;
- (BOOL)p_callTopTabShouldInterceptCaptionBubbleWithChannel:(id)a0;
- (void)p_topTabScrollDidReachStableEnd:(id)a0;
- (BOOL)p_callChannelShouldHandleTransition_destinatedViewControllerForSlideDirection:(unsigned long long)a0 gestureRecognizer:(id)a1 withChannel:(id)a2;
- (id)p_callChannelTransition_destinatedViewControllerForSlideDirection:(unsigned long long)a0 gestureRecognizer:(id)a1 withChannel:(id)a2;
- (BOOL)p_callVerticalPanGestureRecognizerShouldBegin:(id)a0 withChannel:(id)a1 reason:(id *)a2;
- (void)setupChannelGreyMode:(id)a0;
- (void)p_resetChannelLcInfoModel:(id)a0;
- (void)callViewDidLoadNotRecursiveWithChannel:(id)a0;
- (void)callViewDidResumeNotRecursiveWithChannel:(id)a0;
- (void)callViewWillAppearNotRecursiveWithChannel:(id)a0;
- (void)callViewDidAppearNotRecursiveWithChannel:(id)a0;
- (void)callViewWillDisappearNotRecursiveWithChannel:(id)a0;
- (void)callViewDidDisappearNotRecursiveWithChannel:(id)a0;
- (void)p_callXTabDidSelectedWithChannel:(id)a0;
- (void)p_callXTabDidSelectUsingRecursive;
- (void)p_callXTabDidUnSelectWithChannel:(id)a0;
- (void)p_callXTabDidUnSelectUsingRecursive;
- (void)callXTabDidSelectWithChannel:(id)a0;
- (void)callXTabDidUnSelectWithChannel:(id)a0;
- (id)getSubEditTabNodes;
- (id)getCommunicationObjectWithLifeCycle:(id)a0 byChannel:(id)a1 byProtocol:(id)a2;
- (void)didSystemThemeChanged;
- (void)p_reloadChannelWithChannelModels:(id)a0 currentChannelIDList:(id)a1 reloadType:(id)a2 selectedChannelID:(id)a3;
- (id)p_getChannelByNonResumeModelIfNeedWithChannelID:(id)a0;
- (id)p_generateChannelWithModel:(id)a0 reloadType:(id)a1 index:(long long)a2 prepareReloadChannel:(id)a3;
- (void)p_updateAllChannels:(id)a0;
- (void)p_updateCurrentChannelsWithChannelIDList:(id)a0 selectedChannelID:(id)a1;
- (id)getChannelIDStringWithChannels:(id)a0;
- (void)p_updateCurrentChannels:(id)a0;
- (id)getDefaultChannelWithConfig:(id)a0;
- (void)p_switchSelectedChannel:(id)a0 config:(id)a1;
- (id)p_recursiveSearchNode:(id)a0 forChannelID:(id)a1;
- (id)p_getSelectedChannelUsingRecursiveWithChannel:(id)a0;
- (void)p_reloadCurrentChannelsGreyModeNeedUpdateGreyStatus:(BOOL)a0;
- (id)p_createPageViewControllerWithChannel:(id)a0;
- (void)enumerateSubSelectedChannelWithChannel:(id)a0 usingBlock:(id /* block */)a1;
- (BOOL)enumerateParentManagerWithChannel:(id)a0 usingBlock:(id /* block */)a1;
- (id)getTabNode;
- (void)willUpdateCurrentChannels:(id)a0;
- (void)willUpdateAllChannels:(id)a0;
- (void)didUpdateAllChannels:(id)a0;
- (id)p_deleteInvalidCurrentIDList:(id)a0;
- (void)p_removeAllResourceIfNeedWithChannel:(id)a0;
- (BOOL)updateSelectedChannelWithChannelID:(id)a0 configBlock:(id /* block */)a1;
- (long long)p_prepareReloadChannel:(id)a0 chanenlModel:(id)a1 reloadType:(id)a2 index:(long long)a3;
- (id)p_createChannelWithModel:(id)a0 controllerClass:(Class)a1 reloadType:(id)a2 index:(long long)a3;
- (id)getCommonStageWithChannel:(id)a0;
- (id)getBottomBarStageWithChannel:(id)a0;
- (id)getXTabStageWithChannel:(id)a0;
- (void)p_setupControllerWithChannel:(id)a0;
- (void)p_appendPrivatedLifeCycleControllers:(id)a0 toArray:(id)a1;
- (void)p_setupPrivatedPluginControllers:(id)a0 channel:(id)a1;
- (void)willSwitchSelectedChannelFromChannel:(id)a0 toChannel:(id)a1 config:(id)a2;
- (void)updateChannelModels:(id)a0 reloadType:(id)a1;
- (void)updateCurrentChannelsWithChannelIDList:(id)a0 selectedChannelID:(id)a1;
- (long long)getChannelIndexWithChannelID:(id)a0;
- (void)reloadCurrentChannelsGreyMode;
- (void)reloadChannelWithChannelModels:(id)a0 currentChannelIDList:(id)a1 reloadType:(id)a2 selectedChannelID:(id)a3;
- (void).cxx_destruct;
- (id)initWithConfig:(id)a0;
- (void)dealloc;

@end
