@class NSTimer, NSString, AWEIMChatModel, UIImage, AWEUserModel, NSMutableDictionary, AWEIMShopConversationSubscriptionRequestModel, UIViewController, AWEIMMessageConversation, AWEIMUser, AWEIMConversationContext;
@protocol AWEIMConversationFeatureConfigProtocol, IESIMGroupAvatarCropViewControllerProtocol;

@interface AWEIMNewChatDetailContext : NSObject <AWEUserMessage>

@property (retain, nonatomic) NSTimer *fetchFriendActiveTimer;
@property (retain, nonatomic) AWEIMChatModel *chatModel;
@property (retain, nonatomic) AWEIMMessageConversation *conversation;
@property (retain, nonatomic) AWEIMConversationContext *conversationContext;
@property (nonatomic) BOOL refresh;
@property (retain, nonatomic) AWEIMUser *user;
@property (copy, nonatomic) NSString *userId;
@property (copy, nonatomic) NSString *secUserID;
@property (nonatomic) unsigned long long cfAddStatus;
@property (nonatomic) BOOL isStranger;
@property (nonatomic) BOOL hideExitCell;
@property (nonatomic) BOOL needAccessibilityScrollToTop;
@property (nonatomic) long long onlineCount;
@property (nonatomic) long long taIsFriendSwitchStatus;
@property (copy, nonatomic) NSString *fansGroupOnlineStatus;
@property (copy, nonatomic) NSString *schema;
@property (nonatomic) long long currentUserRole;
@property (readonly, weak, nonatomic) UIViewController *viewController;
@property (nonatomic) BOOL shownInHalfScreen;
@property (nonatomic) unsigned long long pageUIStandard;
@property (nonatomic) unsigned long long completeActionType;
@property (nonatomic) BOOL isPigeon;
@property (nonatomic) unsigned long long groupAvatarSource;
@property (weak, nonatomic) UIViewController<IESIMGroupAvatarCropViewControllerProtocol> *cropVC;
@property (retain, nonatomic) NSMutableDictionary *activeUserMapper;
@property (nonatomic) BOOL shouldNotTransferToSetting;
@property (nonatomic) BOOL needRefreshViewLayout;
@property (nonatomic) BOOL isDissolveDuxBoxShowed;
@property (nonatomic) BOOL isInChatMoreSettingScene;
@property (nonatomic) BOOL shouldQuit;
@property (retain, nonatomic) AWEUserModel *fullDetailUser;
@property (copy, nonatomic) NSString *enterFrom;
@property (nonatomic) BOOL replaceEnterFrom;
@property (copy, nonatomic) NSString *imageSourceForTracking;
@property (nonatomic) long long aweim_naviBarType;
@property (nonatomic) BOOL hideSectionTwo;
@property (copy, nonatomic) NSString *liveAutoSyncDescription;
@property (copy, nonatomic) NSString *workAutoSyncDescription;
@property (nonatomic) BOOL shouldUseWebcastProfile;
@property (retain, nonatomic) id<AWEIMConversationFeatureConfigProtocol> conversationFeatureConfig;
@property (retain, nonatomic) UIImage *imageUploading;
@property (nonatomic) long long tabberFirstLLandingIndex;
@property (retain, nonatomic) AWEIMShopConversationSubscriptionRequestModel *shopPushRequestModel;
@property (nonatomic) BOOL isFromEditGroupInfoNotice;
@property (nonatomic) BOOL didShowPanelFromEditGroupInfoNotice;
@property (nonatomic) BOOL isFromEditGroupNameGuideCard;
@property (nonatomic) BOOL isChangeGroupAvatarNeedPreview;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)enabledV2Profile;
+ (BOOL)isSupportLeftSlideEnter;
+ (BOOL)enabledChatType:(id)a0;
+ (BOOL)enableGroupOwnerMsgWithConversation:(id)a0;
+ (BOOL)enabledSupportLongPressAndChangeUI;
+ (id)commonTrackEnterFromWithInMoreSettings:(BOOL)a0;
+ (id)commonTackerParamsWithConversation:(id)a0 inMoreSettings:(BOOL)a1;
+ (BOOL)chatDetailV2EnabledChatType:(id)a0;
+ (BOOL)shouldLandingAtGroupOwnerMessage;
+ (BOOL)isGroupDetailLandingToVideo;
+ (BOOL)groupMemberWithChatBtn;
+ (BOOL)enabledGestureEnterPersonal;
+ (BOOL)chatDetailV2EnabledSplitVideoAweme;
+ (BOOL)enabledChangeFollowStatus;
+ (BOOL)enabledNameClick;

- (void)didFinishBlockUser:(id)a0 status:(long long)a1;
- (void)didFinishUnBlockUser:(id)a0 status:(long long)a1;
- (id)conversationDataManager;
- (void)fetchActiveStatus;
- (void)fetchActiveStatusInit;
- (void)__fetchFansGroupOnlineStatusIfNeed;
- (void)p_refreshActiveUserInfos:(id)a0;
- (void)updateChatModel;
- (void)updateContextParticipantData;
- (void)updateUserStatusWithCompleteBlock:(id /* block */)a0;
- (void)loopFetchActiveStatus;
- (void).cxx_destruct;
- (void)setViewController:(id)a0;
- (void)dealloc;
- (id)initWithConversation:(id)a0;

@end
