@class UIView, NSString, AWEImageTemplateEditViewModel, UIImageView, NSDictionary, UIButton, UICollectionView, UILabel, NSIndexPath;
@protocol ACCDUXLoadingInstance, ACCLoadingViewProtocol, AWEImageTemplateListViewDelegate;

@interface AWEImageTemplateListView : UIView <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>

@property (retain, nonatomic) UIView *currentView;
@property (retain, nonatomic) UIView *topIndicator;
@property (retain, nonatomic) UIView *normalView;
@property (retain, nonatomic) UICollectionView *tabCollectionView;
@property (retain, nonatomic) UICollectionView *imageTemplateCollectionView;
@property (retain, nonatomic) UIButton *clearImageTemplateApplyBtn;
@property (retain, nonatomic) UILabel *authorHintLabel;
@property (retain, nonatomic) UILabel *authorNameLabel;
@property (retain, nonatomic) UIImageView *avatarImageView;
@property (retain, nonatomic) UIButton *complianceNoticeButton;
@property (retain, nonatomic) UIButton *complianceActionButton;
@property (retain, nonatomic) UIView *authorInfoView;
@property (retain, nonatomic) UIImageView *providerIcon;
@property (retain, nonatomic) UIView *templateAuthoInfoView;
@property (retain, nonatomic) UIImageView *tproviderIcon;
@property (retain, nonatomic) NSDictionary *headerImageForCopyrightAlertView;
@property (retain, nonatomic) UIView<ACCDUXLoadingInstance> *progressLoadingView;
@property (retain, nonatomic) NSDictionary *imageTemplateSettings;
@property (retain, nonatomic) NSIndexPath *currentSelectedTabIndexPath;
@property (nonatomic) long long currentTemplatePlatform;
@property (retain, nonatomic) UIView *loadingView;
@property (retain, nonatomic) UIView<ACCLoadingViewProtocol> *loadingIndicator;
@property (retain, nonatomic) UIView *networkErrorView;
@property (nonatomic) BOOL tabIsFixed;
@property (nonatomic) BOOL isAutoLandingTabHasBeenTracked;
@property (retain, nonatomic) NSDictionary *showModelHastracked;
@property (nonatomic) BOOL hasFirstRenderedTemplateReport;
@property (weak, nonatomic) id<AWEImageTemplateListViewDelegate> delegate;
@property (weak, nonatomic) AWEImageTemplateEditViewModel *viewModel;
@property (nonatomic) long long loadStatus;
@property (nonatomic) BOOL selectInvertEnabled;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)viewForLoadStatus:(long long)a0;
- (void)templateSelectSetup;
- (void)reloadTemplateList;
- (void)applyTemplateSuccess;
- (void)reselectTemplateModel;
- (void)selectTemplateCollectionCellInIndexPath:(id)a0 unselectInIndexPath:(id)a1;
- (void)applyTemplateFailed;
- (void)clearTemplateChooseStatus;
- (BOOL)shouldShowTopIndicator;
- (double)templateImageCollectionViewHeight;
- (BOOL)isTemplateInfoInTemplateList;
- (void)networkErrorButtonClicked:(id)a0;
- (void)p_scrollToIndexPath:(id)a0;
- (void)p_trackVisibleTemplateCell;
- (void)p_trackApplyTemplateEndWithIfSuccess:(BOOL)a0;
- (void)loadingViewDismiss;
- (void)p_showComplianceNotificationAndAuthorInfoAndClearBtnStatusWith:(id)a0;
- (void)templateApplyTemplateSuccessForIndexPath:(id)a0;
- (void)selectTemplateAtIndexPath:(id)a0;
- (void)loadingViewShowWithCancelBlock:(id /* block */)a0;
- (void)p_selectTemplateAtIndexPath:(id)a0 unselectIndexPath:(id)a1 defaultTabIndexPath:(id)a2;
- (void)p_authorInfoShouldHidden:(BOOL)a0;
- (void)p_complianceNoticeBtnShouldHidden:(BOOL)a0;
- (void)clearTemplateInfo;
- (void)p_selectTabAtIndexPath:(id)a0 animated:(BOOL)a1;
- (void)templateImageCollectionView:(id)a0 didSelectItemAtIndexPath:(id)a1;
- (long long)templateImageCollectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (id)templateImageCollectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (struct CGSize { double x0; double x1; })templateImageCollectionView:(id)a0 layout:(id)a1 referenceSizeForHeaderInSection:(long long)a2;
- (struct CGSize { double x0; double x1; })templateImageCollectionView:(id)a0 layout:(id)a1 sizeForItemAtIndexPath:(id)a2;
- (void)p_updateTabSelection:(id)a0;
- (void)p_viewStopScrolling:(id)a0;
- (void)templateImageDoSelectForIndexPath:(id)a0;
- (void)selectTemplateWithLoadingAtIndexPath:(id)a0;
- (id)visibleTemplateCellIndexPaths;
- (void)p_trackTempalateWhenShowsWithIndexPath:(id)a0;
- (BOOL)isTemplateInMultiParts;
- (id)p_sortIndexPathForVisibleItems:(id)a0;
- (void)p_updateAuthorInfoWithTemplateInfoModel:(id)a0 shouldHideAuthorInfo:(BOOL)a1;
- (void)p_updateComplianceBtnInfoWithTemplateInfoModel:(id)a0;
- (void)p_fetchUserAvatarByUserID:(id)a0 completion:(id /* block */)a1;
- (void)scrollToShowTemplate:(id)a0;
- (id)p_getSettingsInfoForPlatform:(long long)a0 actorInfoDic:(id)a1;
- (Class)templateTabItemClass;
- (id)clearStickerImage;
- (id)clearStickerSelectedImage;
- (void)clearImageTemplateApplyBtnClicked:(id)a0;
- (id)templateImageCollectionView;
- (void)complianceNoticeButtonClicked:(id)a0;
- (double)templateTabViewHeight;
- (void)showComplianceNotificationAndAuthorInfoAndClearBtnStatusWith:(id)a0;
- (void)reloadData;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 referenceSizeForHeaderInSection:(long long)a2;
- (id)collectionView:(id)a0 viewForSupplementaryElementOfKind:(id)a1 atIndexPath:(id)a2;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 sizeForItemAtIndexPath:(id)a2;
- (id)collectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (long long)collectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (void)collectionView:(id)a0 didSelectItemAtIndexPath:(id)a1;
- (long long)numberOfSectionsInCollectionView:(id)a0;
- (void)scrollViewDidScroll:(id)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)scrollViewDidEndScrollingAnimation:(id)a0;
- (void)setupUI;
- (void)showLoadingView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 viewModel:(id)a1;

@end
