@class NSArray, NSOrderedSet, NSString, NSObject;
@protocol OS_dispatch_semaphore;

@interface AWEIMShareRecommendDataManager : NSObject <AWEUserMessage>

@property (copy, nonatomic) NSArray *recommendSortedInfos;
@property (nonatomic) double lastSyncTimeStamp;
@property (copy, nonatomic) NSArray *sortedIntimateGroupInfos;
@property (nonatomic) long long limitCount;
@property (retain, nonatomic) NSObject<OS_dispatch_semaphore> *lock;
@property (nonatomic) struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } mutex;
@property (copy, nonatomic) NSOrderedSet *disrecommendUidList;
@property (copy, nonatomic) NSOrderedSet *sharePanelDisrecommendUidList;
@property (copy, nonatomic) NSOrderedSet *disrecommendConversationIdList;
@property (retain, nonatomic) NSObject<OS_dispatch_semaphore> *disrecommendLock;
@property (nonatomic) struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } disrecommendMutex;
@property (nonatomic) double lastSyncDisrecommendTimeStamp;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)sharedInstance;

- (void)didFinishLogoutWithUid:(id)a0;
- (long long)disrecommendCount;
- (void)trackShareFriendShow:(id)a0 logPB:(id)a1 groupID:(id)a2 authorID:(id)a3 enterMethod:(id)a4 extraParams:(id)a5;
- (void)trackSharePanelPerformanceWithParams:(id)a0;
- (void)addDisrecommendWithShareModel:(id)a0 success:(id /* block */)a1 failure:(id /* block */)a2;
- (void)removeDisrecommendWithShareModel:(id)a0 success:(id /* block */)a1 failure:(id /* block */)a2;
- (id)transformToShareModelsOptimize:(id)a0;
- (id)getIntimateGroupShareModelList;
- (id)getRecommendShareModelList;
- (id)getLatestChatWithCount:(unsigned long long)a0;
- (id)fansGroupShield:(id)a0;
- (BOOL)shouldRefreshDisrecommendUidList;
- (void)updateDisrecommendUidList:(id)a0 isForSharePanel:(BOOL)a1;
- (BOOL)enableDisrecommendList;
- (void)addDisrecommendWithGroupShortId:(long long)a0 conversationId:(id)a1 success:(id /* block */)a2 failure:(id /* block */)a3;
- (void)addDisrecommendWithUid:(id)a0 secUid:(id)a1 success:(id /* block */)a2 failure:(id /* block */)a3;
- (void)updateSortedInfoWithJSONArray:(id)a0 uid:(id)a1;
- (void)updateSortedIntimateGroupInfoWithJSONArray:(id)a0 uid:(id)a1;
- (void)storeSortedInfoModels:(id)a0 uid:(id)a1;
- (void)storeSortedIntimateGroupInfoModels:(id)a0 uid:(id)a1;
- (void)updateDisrecommendUidList:(id)a0 isForSharePanel:(BOOL)a1 uid:(id)a2;
- (void)storeDisrecommendUidList:(id)a0 isForSharePanel:(BOOL)a1 uid:(id)a2;
- (void)storeDisrecommendConversationIdList:(id)a0 uid:(id)a1;
- (void)removeDisrecommendWithGroupShortId:(long long)a0 conversationId:(id)a1 success:(id /* block */)a2 failure:(id /* block */)a3;
- (void)removeDisrecommendWithUid:(id)a0 secUid:(id)a1 success:(id /* block */)a2 failure:(id /* block */)a3;
- (void)p_addLocalDisrecommendWithUid:(id)a0 isForSharePanel:(BOOL)a1;
- (void)p_removeLocalDisrecommendWithUid:(id)a0 isForSharePanel:(BOOL)a1;
- (void)p_postDisrecommendSecUid:(id)a0 success:(id /* block */)a1 failure:(id /* block */)a2;
- (void)p_deletDisrecommendSecUid:(id)a0 success:(id /* block */)a1 failure:(id /* block */)a2;
- (void)storeDisrecommendUidList:(id)a0 isForSharePanel:(BOOL)a1;
- (void)p_addLocalDisrecommendWithConversationId:(id)a0;
- (void)p_removeLocalDisrecommendWithConversationId:(id)a0;
- (void)p_postDisrecommendGroupShortId:(long long)a0 success:(id /* block */)a1 failure:(id /* block */)a2;
- (void)p_deletDisrecommendGroupShortId:(long long)a0 success:(id /* block */)a1 failure:(id /* block */)a2;
- (void)storeDisrecommendConversationIdList:(id)a0;
- (id)sortedRecommendShareListWithRecents:(id)a0 limitCount:(long long)a1 filterNotFriendUser:(BOOL)a2 shouldFilterMsgBox:(BOOL)a3;
- (id)sortedRecommendShareListWithRecents:(id)a0 limitCount:(long long)a1 filterNotFriendUser:(BOOL)a2 shouldFilterMsgBox:(BOOL)a3 shieldFansGroup:(BOOL)a4;
- (id)sortedRecommendShareListWithRecents:(id)a0 limitCount:(long long)a1 filterNotFriendUser:(BOOL)a2 filterGroupChat:(BOOL)a3 shouldFilterMsgBox:(BOOL)a4 shieldFansGroup:(BOOL)a5;
- (id)filterInFoldBoxShareModel:(id)a0;
- (id)sortedRecommendList:(id)a0 withRecents:(id)a1 filterNotFriendUser:(BOOL)a2 filterGroupChat:(BOOL)a3 shieldFansGroup:(BOOL)a4;
- (id)transformSingleToShareModelOptimize:(id)a0;
- (id)transformChatToShareModelOptimize:(id)a0;
- (id)getStoredSortedInfoModels;
- (id)getStoredSortedIntimateGroupInfoModels;
- (id)getStoredDisrecommendUidList;
- (id)getSharePanelStoredDisrecommendUidList;
- (id)getStoredDisrecommendConversationIdList;
- (void)cleanSortedInfoModels;
- (void)cleanSortedIntimateGroupInfoModels;
- (void)cleanDisrecommendUidList;
- (void)cleanDisrecommendConversationIdList;
- (void)p_addDisrecommendKey:(id)a0 value:(id)a1 success:(id /* block */)a2 failure:(id /* block */)a3;
- (void)p_removeDisrecommendKey:(id)a0 value:(id)a1 success:(id /* block */)a2 failure:(id /* block */)a3;
- (id)p_paramsWithSecUid:(id)a0 groupShortId:(long long)a1 extraDict:(id)a2;
- (void)p_postAddDisrecommendWithParams:(id)a0 completion:(id /* block */)a1;
- (void)p_postRemoveDisrecommendWithParams:(id)a0 completion:(id /* block */)a1;
- (BOOL)__enableShareChat:(id)a0 needFilterFansGroup:(BOOL)a1;
- (BOOL)enableRecommendSort;
- (void)p_safeCallDidDisrecommendListChangeOnMainThread;
- (id)sortedRecommendShareListWithRecents:(id)a0 limitCount:(long long)a1 filterNotFriendUser:(BOOL)a2;
- (id)transformSingleToShareModel:(id)a0;
- (void)p_addDisrecommendSecUid:(id)a0 groupShortId:(long long)a1 extraDict:(id)a2 completion:(id /* block */)a3;
- (void)p_deleteDisrecommendSecUid:(id)a0 groupShortId:(long long)a1 extraDict:(id)a2 completion:(id /* block */)a3;
- (id)sortedRecommendList:(id)a0 withRecents:(id)a1 filterNotFriendUser:(BOOL)a2 shieldFansGroup:(BOOL)a3;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end
