@class AWELongVideoDataController, NSString, AWELandscapeReolutionReminder, NSTimer, UIView, AWELandscapeReminder;
@protocol AWELongVideoLVWidgetContainerProtocol;

@interface AWELandscapeReminderController : AWELandscapeInteractionBaseController <HunterContainerLifeCycleProtocol, AWELandscapeReolutionReminderDelegate, AWELandscapeReminderControllerProtocol>

@property (retain, nonatomic) AWELandscapeReminder *reminder;
@property (retain, nonatomic) AWELandscapeReolutionReminder *manualGerasTypeReminder;
@property (nonatomic) unsigned long long reminderType;
@property (retain, nonatomic) AWELongVideoDataController *longVideoDataController;
@property (nonatomic) BOOL isSlidering;
@property (nonatomic) BOOL hasEnterQuietState;
@property (nonatomic) BOOL hasCancelNextMixVideoPlay;
@property (nonatomic) BOOL isQuiet;
@property (nonatomic, getter=isShowingLVWidget) BOOL showLVWidget;
@property (nonatomic) BOOL feShowLVWidget;
@property (nonatomic) BOOL hasTrackAppointmentShow;
@property (copy, nonatomic) id /* block */ skipOpeningEndingGuideBlock;
@property (copy, nonatomic) id /* block */ skipOpeningEndingTipsBlock;
@property (retain, nonatomic) NSTimer *dismissTimer;
@property (nonatomic) double bottomOffset;
@property (retain, nonatomic) UIView<AWELongVideoLVWidgetContainerProtocol> *lVWidgetContainer;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)container:(id)a0 didChangeIntrinsicContentSize:(struct CGSize { double x0; double x1; })a1;
- (void)player:(id)a0 didChangePlaybackStateWithAction:(long long)a1;
- (void)player:(id)a0 updatePlayTime:(double)a1 canPlayTime:(double)a2 totalTime:(double)a3;
- (void)bindEvent;
- (void)registerEvent;
- (void)updateControllerWithAnimationOffset:(double)a0 positon:(long long)a1;
- (void)willExitLandscape;
- (void)willEnterSplitScreen:(BOOL)a0 movePoint:(struct CGPoint { double x0; double x1; })a1 scale:(double)a2;
- (BOOL)supportMixAutoPlayInRecommend;
- (BOOL)enableAutoPlayNext;
- (BOOL)canAutoPlayNext;
- (void)resetWidgetEnv;
- (void)startWithAppointment;
- (void)trackAppointmentShowIfNeeded;
- (void)resetDismissTimer:(BOOL)a0;
- (void)dismissReminderWithAnimated:(BOOL)a0;
- (void)refreshRemindTime:(id)a0 actionButtonText:(id)a1 tapBlock:(id /* block */)a2;
- (void)dismissReminder;
- (void)refreshRemindTime:(id)a0;
- (void)showRemindTimeLabel;
- (double)lastPlayTimeInterval;
- (BOOL)optimizeDismissReminder;
- (BOOL)canShowMixVideoReminder:(BOOL)a0 playerController:(id)a1;
- (void)trackMixAutoPlayReminederShow;
- (void)refreshRemindTime:(id)a0 tapBlock:(id /* block */)a1;
- (BOOL)canShowReminder:(BOOL)a0 playerController:(id)a1;
- (void)createHunterIfNeeded;
- (void)updateLVWidgetLayout:(BOOL)a0;
- (void)showLVWidgetWithData:(id)a0 show:(BOOL)a1;
- (void)didReceivePlayerAction:(id)a0 extraParams:(id)a1;
- (void)showHistoryRecordReminder;
- (void)showAutoPlayReminder:(BOOL)a0;
- (void)showSpeedReminder:(double)a0;
- (void)showResolutionReminder:(id)a0;
- (void)refreshRemindTime:(id)a0 actionButtonText:(id)a1;
- (void)showSkipHeadReminder;
- (void)showSkipTailReminder;
- (void)showSkipHeadTailReminder:(BOOL)a0;
- (void)showSkipHeadTailGuideReminder;
- (void)showTimingCloseChangedTip;
- (void)preloadLVWidgetWithData:(id)a0;
- (void)trackSkipReminderClick;
- (void)trackSkipReminderShow;
- (id)timingCloseReminderText;
- (void)didDismissResolutionReminder;
- (void)changeToManualGearsType:(unsigned long long)a0;
- (void)showManualGearsTypeReminderWithState:(long long)a0 manualGearsType:(unsigned long long)a1;
- (id)longVideoPaymentCommonParams;
- (void)updateState:(long long)a0;
- (void).cxx_destruct;
- (void)setData:(id)a0;
- (void)reset;
- (double)totalDuration;
- (void)viewDidLoad;
- (void)dealloc;
- (void)setupUI;
- (id)nextEpisode;

@end
