@class NSTimer, AWEMusicPlayDuration, AWEMusicPlayerModel, AWEMusicPlayerQueue, RxMultipleDelegate, NSMutableDictionary, NSString, AWEAudioEngine, NSMutableArray, NSDictionary, AWEMusicExtraInfoManager;
@protocol LunaPlayerPluginService, AWEMusicServiceDelegate;

@interface AWEMusicService : HTSService <AWEAudioEngineDelegate, AWEMusicPlayerQueueDelegate, AWEAudioFocusProtocol, AWENowPlayingInfoPlayerProtocol, MusicService>

@property (retain, nonatomic) RxMultipleDelegate<AWEMusicServiceDelegate> *multipleDelegate;
@property (retain, nonatomic) AWEAudioEngine *player;
@property (retain, nonatomic) NSTimer *timer;
@property (retain, nonatomic) AWEMusicPlayerQueue *currentQueue;
@property (nonatomic) long long playStatus;
@property (nonatomic) double seekToPlayTime;
@property (nonatomic) BOOL isPlayingInterrupted;
@property (copy, nonatomic) id /* block */ workItem;
@property (retain, nonatomic) AWEMusicPlayerModel *playingModel;
@property (retain, nonatomic) AWEMusicPlayerModel *willPlayingModel;
@property (nonatomic) BOOL didEnterBackground;
@property (retain, nonatomic) AWEMusicExtraInfoManager *extraInfoManager;
@property (nonatomic) BOOL isPendingPlay;
@property (nonatomic) BOOL isPlayingInner;
@property (nonatomic) BOOL isSeeking;
@property (nonatomic) double innerSeekToTime;
@property (nonatomic) BOOL isFirstPlay;
@property (retain, nonatomic) NSMutableArray *attachKeyArray;
@property (retain, nonatomic) AWEMusicPlayDuration *playDuration;
@property (retain, nonatomic) id<LunaPlayerPluginService> playPlugin;
@property (nonatomic) BOOL isRepeated;
@property (retain, nonatomic) NSMutableDictionary *nowPlayingInfo;
@property (retain, nonatomic) id playCommandTarget;
@property (retain, nonatomic) id pauseCommandTarget;
@property (retain, nonatomic) id previousCommandTarget;
@property (retain, nonatomic) id nextCommandTarget;
@property (retain, nonatomic) id seekCommandTarget;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) long long scaleMode;
@property (nonatomic) BOOL resumePlayWhenInterruptionEnd;
@property (nonatomic) BOOL fadeInOutEnable;
@property (nonatomic) long long preloadMusicCount;
@property (nonatomic) BOOL canBackgroundPlay;
@property (retain, nonatomic) NSDictionary *bizFlags;
@property (retain, nonatomic) NSDictionary *trackParams;
@property (nonatomic) BOOL canStartFromChorus;
@property (nonatomic) BOOL blockPlaying;

+ (id)service;

- (void)playForRemoteControl;
- (void)pauseForRemoteControl;
- (void)seekToTimeForRemoteControl:(double)a0;
- (void)playPrevForRemoteControl;
- (void)playNextForRemoteControl;
- (BOOL)canPlayForRemoteControl;
- (BOOL)canPauseForRemoteControl;
- (BOOL)canPlayPrevForRemoteControl;
- (BOOL)canPlayNextForRemoteControl;
- (BOOL)canSeekForRemoteControl;
- (long long)playBitrate;
- (void)pauseWithType:(long long)a0;
- (void)stopWithType:(long long)a0;
- (void)seekToTime:(double)a0 completion:(id /* block */)a1 renderComplete:(id /* block */)a2;
- (void)setStartTimeWithPrepareToPlay:(double)a0;
- (void)setDelayPrepreToPlayToStartTimeSet:(BOOL)a0;
- (BOOL)isLoadStatePlayable;
- (double)actualDuration;
- (double)actualPlaybackTime;
- (void)setQueue:(id)a0 method:(long long)a1;
- (void)feedQueue:(id)a0;
- (id)currentPlayModel;
- (BOOL)updateCurrentModel:(id)a0;
- (BOOL)updateCurrentModel:(id)a0 method:(long long)a1;
- (BOOL)updateCurrentModelWithoutPlay:(id)a0;
- (BOOL)updateCurrentModelWithoutPlay:(id)a0 method:(long long)a1;
- (void)resetRemotePlayInfo;
- (void)setMusicModels:(id)a0 current:(id)a1 queueId:(id)a2 method:(long long)a3;
- (void)playFinishToNext;
- (void)goPrevWithNotification;
- (void)goNextWithNotification;
- (BOOL)canGoPrev;
- (BOOL)canGoNext;
- (long long)getCacheSizeByModel:(id)a0;
- (void)attachObject:(id)a0 forKey:(id)a1;
- (id)getAttachedObjectForKey:(id)a0;
- (void)updateTrackParams:(id)a0;
- (void)manualAuidoOver;
- (void)removeRemoteControlCommand;
- (void)setMusicModels:(id)a0 current:(id)a1 queueId:(id)a2;
- (void)appendMusicModels:(id)a0;
- (void)audioEnginePlaybackTimeChanged:(id)a0;
- (void)audioEngine:(id)a0 didFinishedWithError:(id)a1;
- (void)audioEngineUserStopped:(id)a0;
- (void)audioEngine:(id)a0 didChangeStallState:(long long)a1 actionType:(long long)a2 reason:(unsigned long long)a3;
- (void)audioEngine:(id)a0 playbackStateChanged:(long long)a1;
- (void)audioEngineReadyToPlay:(id)a0;
- (void)audioEnginePrepared:(id)a0;
- (void)audioEngineReadyToDisPlay:(id)a0;
- (id)audioEngineApiForFetcher:(id)a0;
- (BOOL)audioIsPlaying;
- (void)audioPause;
- (void)audioRemoveRemoteControlCommand;
- (void)receiveNotes:(id)a0;
- (void)onAudioPlay:(id)a0;
- (void)onAudioOver:(id)a0 duration:(double)a1;
- (void)queueDidUpdatePlayList:(id)a0;
- (void)queue:(id)a0 didChangeLoopModeFromLoopMode:(unsigned long long)a1;
- (void)goPrev;
- (void)goNext;
- (void)resignPlayingPlayer;
- (BOOL)goNextIsManual:(BOOL)a0 isFinished:(BOOL)a1 animation:(BOOL)a2;
- (void)playIsFirst:(BOOL)a0;
- (void)p_setAudioSessionActive;
- (void)becomePlayingPlayer;
- (void)realPlay:(BOOL)a0;
- (void)p_preparePlayerModel:(id)a0 completion:(id /* block */)a1;
- (void)mCheck:(id)a0;
- (void)setAuthentication:(id)a0;
- (void)resetNowPlayingInfo;
- (void)updateNowPlayingInfoPlayback;
- (BOOL)p_updateCurrentModel:(id)a0;
- (void)playCurrent;
- (BOOL)p_updateCurrentModelWithoutPlay:(id)a0;
- (void)setCurrentToPlay;
- (void)p_playNextIsManual:(BOOL)a0 isFinished:(BOOL)a1;
- (void)setCurrentToPlayReadyBlock:(id /* block */)a0;
- (void)playStatusChanged:(long long)a0;
- (void)onTimer:(id)a0;
- (void)pauseTimerIfNeeded;
- (BOOL)p_isPlayerInitialized;
- (BOOL)enableTimerOpt;
- (void)resumeTimerIfNeeded;
- (void)preloadNextMusicItems;
- (void)updatePreviousAndNextCommandStatus;
- (void)reloadNowPlayingInfoPlayback;
- (void)playWithNotification;
- (void)pauseWithNotification;
- (id)nextPlayQueue;
- (id)historyPlayQueue;
- (void)setQueue:(id)a0;
- (void).cxx_destruct;
- (void)play;
- (void)pause;
- (void)setStartTime:(double)a0;
- (void)clear;
- (long long)playbackState;
- (void)addObserver:(id)a0;
- (BOOL)isPlaying;
- (id)init;
- (void)stop;
- (double)duration;
- (void)removeObjectForKey:(id)a0;
- (void)seekToTime:(double)a0;
- (id)playerView;
- (void)removeObserver:(id)a0;
- (void)dealloc;
- (double)playbackTime;
- (void)setupTimer;
- (id)queue;
- (BOOL)looping;
- (void)prepareToPlay;
- (double)durationWatched;
- (double)playableDuration;
- (void)setIsLooping:(BOOL)a0;
- (void)setupNotifications;
- (void)seekToTime:(double)a0 completion:(id /* block */)a1;

@end
