@class DUXLoadingParticleView, UILabel, AWEMateOnboardingEmptyViewController, DUXContentSheet, AWEMateOnboardingCloseFriendSectionFooterView, AFDFamiliarFriendsDataProvider, NSMutableArray, UIView, AWEMateOnboardingSectionHeaderView, DUXButton, UIScrollView, AWENavigationBar, NSString, UIStackView, NSMutableSet, AWEMateOnboardingNavigationBarTitleView, NSArray, LOTAnimationView, AFDFadingEdgeTableView, DUXVacantView;

@interface AWEMateOnboardingViewController : UIViewController <DUXSheetDelegate, UITableViewDelegate, UITableViewDataSource, AWEMateOnboardingViewControllerProtocol>

@property (nonatomic) unsigned long long step;
@property (copy, nonatomic) id /* block */ canShowStepTwoBlock;
@property (retain, nonatomic) NSMutableArray *userList;
@property (retain, nonatomic) UIScrollView *stepOneScrollView;
@property (retain, nonatomic) LOTAnimationView *lightLottieView;
@property (retain, nonatomic) LOTAnimationView *darkLottieView;
@property (retain, nonatomic) UIStackView *stepOneTitleStackView;
@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UILabel *subtitleLabel;
@property (retain, nonatomic) DUXButton *actionButton;
@property (retain, nonatomic) AWENavigationBar *navigationBar;
@property (retain, nonatomic) AWEMateOnboardingNavigationBarTitleView *navigationBarTitleView;
@property (retain, nonatomic) UILabel *sheetModeTitleLabel;
@property (retain, nonatomic) AFDFadingEdgeTableView *tableView;
@property (retain, nonatomic) AWEMateOnboardingSectionHeaderView *closeFriendHeaderView;
@property (retain, nonatomic) AWEMateOnboardingSectionHeaderView *recommendUserHeaderView;
@property (retain, nonatomic) AWEMateOnboardingCloseFriendSectionFooterView *closeFriendFooterView;
@property (retain, nonatomic) UIView *bottomMaskView;
@property (retain, nonatomic) UIView *footerLabelContainerView;
@property (retain, nonatomic) UILabel *footerLabel;
@property (nonatomic) BOOL isSheetMode;
@property (weak, nonatomic) DUXContentSheet *sheet;
@property (retain, nonatomic) UIView *sheetBackgroundMaskView;
@property (nonatomic) BOOL sheetHasFinishedStepOne;
@property (nonatomic) BOOL sheetHasFinishedStepTwo;
@property (nonatomic) BOOL waitingRequestComplete;
@property (nonatomic) BOOL userRecommendRequestOnAir;
@property (retain, nonatomic) NSMutableSet *selectedUserId;
@property (retain, nonatomic) NSMutableSet *showedUserId;
@property (retain, nonatomic) AFDFamiliarFriendsDataProvider *familiarFriendsDataProvider;
@property (retain, nonatomic) NSArray *closeFriendList;
@property (nonatomic) long long closeFriendSectionCurrentCount;
@property (nonatomic) BOOL viewHasAppeared;
@property (retain, nonatomic) DUXVacantView *errorView;
@property (retain, nonatomic) DUXLoadingParticleView *loadingView;
@property (retain, nonatomic) AWEMateOnboardingEmptyViewController *emptyViewController;
@property (retain, nonatomic) NSString *enterFrom;
@property (retain, nonatomic) NSString *enterMethod;
@property (retain, nonatomic) NSString *fromPage;
@property (copy, nonatomic) id /* block */ completeBlock;
@property (nonatomic) BOOL isMomentFeed;
@property (nonatomic) BOOL isFamiliarFeedFullScreen;
@property (nonatomic) unsigned long long onboardingType;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (BOOL)configWithRouterParamDict:(id)a0;
- (BOOL)sheetWillStayAfterClickMaskArea;
- (void)sheetWillDismiss:(id)a0;
- (void)sheetDidDismiss:(id)a0;
- (void)sheet:(id)a0 didChangeFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1 withUserInteraction:(BOOL)a2;
- (void)awe_themeReload;
- (void)initView;
- (void)onActionButtonTapped;
- (void)showInSheetModeWithStartAtStep:(unsigned long long)a0 canShowStepTwoBlock:(id /* block */)a1;
- (void)showStepOneSheet;
- (void)makeRecommendDataRequest;
- (void)endLoadingWithSuccess:(BOOL)a0 isEmpty:(BOOL)a1;
- (void)doStepTwoAction;
- (void)trackObdPageWithAction:(id)a0;
- (void)initCommonView;
- (void)initStepOneView;
- (void)initStepTwoView;
- (void)updateStepOneScrollViewLayoutInFullScreenMode;
- (id)getConfigTextForKey:(id)a0 defaultValue:(id)a1;
- (void)refreshLottieView;
- (void)addSkipButtonToNavigationBarIfNeeded;
- (BOOL)shouldShowCloseFriend;
- (void)fetchCloseFriendList;
- (void)trackObdApplicationClick;
- (void)doMateApplyAction;
- (void)doCloseAction;
- (void)showStepTwoSheetFromStepOne;
- (void)moveToStepTwoWithAnimated:(BOOL)a0;
- (void)trackObdSelectWithUserId:(id)a0 selected:(BOOL)a1;
- (void)trackOBDSelectAll:(BOOL)a0;
- (void)trackAddFriendWithUserModel:(id)a0;
- (void)trackFriendCardWithEventType:(id)a0 userModel:(id)a1;
- (BOOL)isCloseFriendSection:(long long)a0;
- (void)doExpandAction;
- (void)reloadData;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (id)tableView:(id)a0 viewForHeaderInSection:(long long)a1;
- (id)backgroundColor;
- (void)tableView:(id)a0 didSelectRowAtIndexPath:(id)a1;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (id)init;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (long long)numberOfSectionsInTableView:(id)a0;
- (void)commonInit;
- (void)tableView:(id)a0 willDisplayCell:(id)a1 forRowAtIndexPath:(id)a2;
- (double)tableView:(id)a0 heightForRowAtIndexPath:(id)a1;
- (void)viewWillAppear:(BOOL)a0;
- (double)tableView:(id)a0 heightForHeaderInSection:(long long)a1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (double)tableView:(id)a0 heightForFooterInSection:(long long)a1;
- (id)tableView:(id)a0 viewForFooterInSection:(long long)a1;
- (void)closeButtonTapped:(id)a0;
- (void)skipButtonTapped:(id)a0;
- (void)doSelectAllAction;

@end
