@class NSDictionary, UITapGestureRecognizer, AWEDemaciaLoadingAndVolumeView, UILabel, NSMutableArray, TTVideoEngineModel, NSString, UIImage, MPVolumeView, NSTimer, NSMutableDictionary, AWENoxusPlayerBrightnessView, AWENoxusPlayerVolumeView, AWENoxusPlayerInitModel, UIView, UIPanGestureRecognizer, LOTAnimationView, CADisplayLink, AWENoxusGradientView, UIImageView, NSDate, AWEDemaciaVideoBSModel, AWENoxusLongVideoDetailResponseModel, AWENoxusPlayerControlView;
@protocol AWENoxusPlayerViewDelegate, IESCommonVideoPlayerProtocol;

@interface AWENoxusPlayerView : UIView <AWENoxusPlayerControlViewDelegate, AWEDemaciaPlayerAirPlayManagerDelegate, AWENoxusPlayerProgressSliderDelegate, UIGestureRecognizerDelegate, AWENoxusPlayerView>

@property (retain, nonatomic) id<IESCommonVideoPlayerProtocol> playerController;
@property (retain, nonatomic) AWEDemaciaLoadingAndVolumeView *volumeLoadingView;
@property (retain, nonatomic) UIView *loadingView;
@property (retain, nonatomic) UIImageView *loadingImageView;
@property (retain, nonatomic) UIImageView *loadingLogoImageView;
@property (retain, nonatomic) UIImageView *videoCoverImageView;
@property (retain, nonatomic) LOTAnimationView *lottieView;
@property (retain, nonatomic) UILabel *loadingLabel;
@property (retain, nonatomic) NSTimer *loadingNetTimer;
@property (retain, nonatomic) UILabel *forbiddenPlayLabel;
@property (retain, nonatomic) UILabel *continueTipLabel;
@property (nonatomic) double continueTipStamp;
@property (retain, nonatomic) UILabel *nextEpisodeTipLabel;
@property (retain, nonatomic) AWENoxusGradientView *nextEpisodeTipBackView;
@property (retain, nonatomic) UILabel *stallNetLabel;
@property (retain, nonatomic) UILabel *stallTipLabel;
@property (retain, nonatomic) UIView *stallTipBackView;
@property (retain, nonatomic) NSDate *stallFirstDate;
@property (retain, nonatomic) AWENoxusPlayerVolumeView *volumeView;
@property (retain, nonatomic) AWENoxusPlayerBrightnessView *brightnessView;
@property (retain, nonatomic) MPVolumeView *systemVolumeView;
@property (retain, nonatomic) CADisplayLink *displayLink;
@property (nonatomic) double playTime;
@property (nonatomic) double originHeight;
@property (nonatomic) double originWidth;
@property (nonatomic) double verticalBottomOffset;
@property (retain, nonatomic) AWEDemaciaVideoBSModel *bsModel;
@property (retain, nonatomic) AWENoxusLongVideoDetailResponseModel *videoModel;
@property (retain, nonatomic) AWENoxusLongVideoDetailResponseModel *lastPlayableVideoModel;
@property (retain, nonatomic) AWENoxusPlayerInitModel *infoModel;
@property (retain, nonatomic) TTVideoEngineModel *engineModel;
@property (retain, nonatomic) UIImage *engineBigImage;
@property (copy, nonatomic) NSDictionary *paramDic;
@property (nonatomic) long long currentPlayState;
@property (nonatomic) long long trategyType;
@property (retain, nonatomic) NSTimer *quietModeTimer;
@property (nonatomic) BOOL tapSliderSeeking;
@property (nonatomic) BOOL settingModeChanging;
@property (nonatomic) double eachPlayTime;
@property (nonatomic) double stallStartTimestamp;
@property (nonatomic) unsigned long long stallCount;
@property (nonatomic) double stallTotalDuration;
@property (nonatomic) BOOL firstFramePlay;
@property (nonatomic) BOOL finishedLog;
@property (nonatomic) double firstPlayStartTime;
@property (retain, nonatomic) NSMutableDictionary *trackContext;
@property (nonatomic) unsigned long long panDirection;
@property (nonatomic) BOOL panStateChanged;
@property (nonatomic) unsigned long long panTouchArea;
@property (nonatomic) double startVolume;
@property (nonatomic) double startBrightness;
@property (nonatomic) double startPanProgress;
@property (retain, nonatomic) NSMutableArray *nextEpisodeTipArray;
@property (nonatomic) long long playbackAction;
@property (nonatomic) BOOL skipNextVideoPlayTrack;
@property (weak, nonatomic) id<AWENoxusPlayerViewDelegate> delegate;
@property (retain, nonatomic) AWENoxusPlayerControlView *controlView;
@property (retain, nonatomic) UITapGestureRecognizer *tap;
@property (retain, nonatomic) UIPanGestureRecognizer *panGesture;
@property (retain, nonatomic) UIImageView *watermarkImageView;
@property (nonatomic) double fullScreenMax;
@property (nonatomic) double fullScreenMin;
@property (nonatomic) BOOL isQuiet;
@property (nonatomic) BOOL notPlayWhenAppear;
@property (nonatomic) BOOL slidingSeekTime;
@property (nonatomic) BOOL slidingSeekTimeSucceed;
@property (nonatomic) unsigned long long resolutionType;
@property (nonatomic) BOOL isTTPlayer;
@property (nonatomic) BOOL notStop;
@property (nonatomic) BOOL forbiddenPlay;
@property (nonatomic) BOOL isApplicationInactive;
@property (nonatomic) BOOL airPlayPickerShow;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)updatePlayerIfNeeded;
- (void)resetDisplayLink;
- (void)onNetworkChanged:(id)a0;
- (void)setStartPlayTime:(double)a0;
- (void)updateCoverImage;
- (long long)scaleModeForVideo;
- (void)trackPlayTimeIfNeeded;
- (BOOL)hasWatermark;
- (void)onVolumeChangeNotification:(id)a0;
- (void)didStopPlayingVideoOnExternalDisplayWithCurrentTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (void)didConnectToAirPlayDeviceWithName:(id)a0;
- (struct { long long x0; int x1; unsigned int x2; long long x3; })currentTimeForPlayingVideoOnExternalDisplay;
- (void)updateAirPlayProgressWithCurrentTime:(double)a0 totalTime:(double)a1;
- (void)didStartPlayingVideoOnExternalDisplay;
- (void)updateAirPlayPlayerStatus:(unsigned long long)a0;
- (void)willStartPlayingVideoOnExternalDisplay;
- (void)getCurrentPlayURLWithCompletionBlock:(id /* block */)a0;
- (void)noxusProgressSlider:(id)a0 tapPointPercent:(double)a1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 initModel:(id)a1;
- (void)realPlay;
- (void)addVideoLoadingView;
- (void)addControlView;
- (void)screenTap:(id)a0;
- (void)addIESVideoPlayer;
- (void)addVolumeLoadingView;
- (void)initCommonTrack;
- (void)resetToBeginTime;
- (void)enterQuietMode:(BOOL)a0;
- (id)_isCurrentVideoH265;
- (id)monitorSeekStateKey;
- (void)addPeriodicTimeObserver;
- (void)registerVideoDownloadBlock;
- (void)registerNoVideoDownloadBlock;
- (void)registerPlaybackFailedBlock;
- (void)registerStallStateChangeBlock;
- (long long)contentModeForDefaultVideoCover;
- (id)playURIString;
- (id)monitorFirstFrameKey;
- (id)monitorFirstFrameLogKey;
- (id)monitorpPlayErrorKey;
- (void)playResumeDisplayLink;
- (id)__qualityType;
- (void)commitMonitor;
- (id)monitorpPlayBlockKey;
- (void)rotateAnimation:(long long)a0 complete:(id /* block */)a1;
- (void)noxusPlayerRotateAimModeIn;
- (void)noxusPlayerSliderTouchBegan:(id)a0;
- (void)noxusPlayerSliderTouchEnded:(id)a0;
- (void)noxusPlayerSliderValueChanged:(id)a0;
- (void)noxusSettingTypeListSelectModel:(id)a0;
- (void)noxusSettingTypeDismiss:(BOOL)a0;
- (void)noxusPlayButtonClicked:(BOOL)a0;
- (void)noxusPlayerNextButtonClicked;
- (void)noxusPlayerPanelButtonClicked;
- (void)noxusPlayerPixelButtonClicked;
- (void)noxusPlayerSpeedButtonClicked;
- (void)noxusPlayerFullScreenButtonClicked:(long long)a0;
- (void)noxusPlayerBackButtonClicked:(long long)a0;
- (void)noxusPlayerTVButtonClicked;
- (void)noxusPlayerChangeDeviceButtonClicked;
- (void)noxusPlayerExitAirPlayButtonClicked;
- (void)setVerticalModeBottomOffset:(double)a0;
- (void)addWatermarkImageView;
- (void)addOtherView;
- (void)addVolumeView;
- (void)addBrigtnessView;
- (void)brightnessDidChangeWithNotification:(id)a0;
- (void)trackPlayTimeIfNeededWithIsMira:(BOOL)a0;
- (void)updateLoadingViewLayout;
- (void)createAndSetPlayerDashInfo;
- (void)updateWatermarkImage;
- (void)updateWatermarkLayout;
- (void)handleRestrictLabelContent:(id)a0;
- (void)wrappedPlayerSeekToTime:(double)a0 completion:(id /* block */)a1;
- (double)videoTotalTime;
- (void)setLoadingViewHidden:(BOOL)a0 videoCoverHidden:(BOOL)a1;
- (void)enterQuietMode:(BOOL)a0 timerStart:(BOOL)a1 complete:(id /* block */)a2;
- (void)resetQuietModeTimer:(BOOL)a0;
- (void)determineGestureDirectionWithTranslation:(struct CGPoint { double x0; double x1; })a0;
- (void)determineActionWithTranslation:(struct CGPoint { double x0; double x1; })a0 touchAtRight:(BOOL)a1;
- (void)endPanPlayerProgress;
- (unsigned long long)gestureDirectionInTranslation:(struct CGPoint { double x0; double x1; })a0;
- (void)changePlayerProgress:(struct CGPoint { double x0; double x1; })a0;
- (void)changeVolume:(struct CGPoint { double x0; double x1; })a0;
- (void)changeBrightness:(struct CGPoint { double x0; double x1; })a0;
- (void)showVolumeView:(double)a0 byTouch:(BOOL)a1;
- (void)showBrightnessView:(double)a0;
- (void)beginPanPlayerProgress;
- (void)registerDidFetchVideoModelBlock;
- (void)registerPlayerDidReadyForDisplayBlock;
- (void)registerUrlPlaybackFailedBlock;
- (void)registerDidChangePlaybackState;
- (void)registerWillLoopPlayingBlock;
- (void)upResolutionTipFromNetWork;
- (id)netSpeedString;
- (void)startNetSpeedTimer;
- (void)stopNetSpeedTimer;
- (long long)currentVideoActionState;
- (void)enterQuietMode:(BOOL)a0 timerStart:(BOOL)a1;
- (void)trackPlayTimeIfNeededFromFullbtn:(BOOL)a0;
- (void)progressChangedByTapOrTouch:(double)a0;
- (void)setStallViewHidden:(BOOL)a0;
- (void)downResolutionTipFromNetWork;
- (void)trackPlayTimeIfNeededWithIsMira:(BOOL)a0 fromFullbtn:(BOOL)a1;
- (void)noxusPlayerReplayButtonClicked;
- (void)noxusPlayerTrialBuyBarDidClickBuyButton;
- (void)noxusPlayerPayMaskViewDidClickBuyButton;
- (void)showNextEpisodeTip:(id)a0;
- (unsigned long long)gestureDirectionInVelocity:(struct CGPoint { double x0; double x1; })a0;
- (void)resetPanDirection;
- (void)noxusPlayerPayMaskViewDidShow;
- (void)refreshVideoModel:(id)a0 paramDic:(id)a1;
- (void).cxx_destruct;
- (BOOL)play;
- (BOOL)pause;
- (BOOL)stop;
- (void)setHidden:(BOOL)a0;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)replay;
- (void)pan:(id)a0;
- (void)reset;
- (void)layoutSubviews;
- (void)dealloc;
- (void)setAlpha:(double)a0;
- (void)stopDisplayLink;
- (void)prepareToPlay;
- (long long)actionState;
- (void)seekToTime:(double)a0 completion:(id /* block */)a1;

@end
