@class NSString, NSArray, NSMutableDictionary, AWENearbyPageContext, NSMutableSet, AWENearbyGrouponTabModel, UICollectionView, UICollectionViewCell;
@protocol AWENearbyC2ContainerFeedCellProtocol, AWENearbyGrouponTabFeedDelegate;

@interface AWENearbyGrouponTabPageFeedViewModel : AWEBaseViewModel <AWENearbyC2FeedControllerPlayProtocol, AWENearbyContainerEventMessage, AWENearbyC2FeedCellDelegate>

@property (retain, nonatomic) AWENearbyPageContext *pageContext;
@property (nonatomic) BOOL isLiveWindowsWillShow;
@property (nonatomic) BOOL isLifeWindowsShowing;
@property (nonatomic) long long normalRefreshCount;
@property (nonatomic) BOOL isHalfScreenShowing;
@property (nonatomic) BOOL isHalfScreenShowingStayPlay;
@property (nonatomic) BOOL hasEnteredInnerPage;
@property (copy, nonatomic) NSString *currentRecAfterClickAwemeID;
@property (retain, nonatomic) NSMutableSet *p1aidPoiIds;
@property (retain, nonatomic) NSMutableSet *p1aidProductIds;
@property (retain, nonatomic) NSArray *dataList;
@property (nonatomic) long long lastAutoPlayType;
@property (retain, nonatomic) UICollectionViewCell<AWENearbyC2ContainerFeedCellProtocol> *playingCell;
@property (retain, nonatomic) AWENearbyGrouponTabModel *tabModel;
@property (nonatomic) long long tabRank;
@property (retain, nonatomic) NSMutableDictionary *cellHeightCache;
@property (weak, nonatomic) id<AWENearbyGrouponTabFeedDelegate> delegate;
@property (weak, nonatomic) UICollectionView *collectionView;
@property (nonatomic) BOOL needInvalidateLayout;
@property (nonatomic) long long tabID;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL isFirstFetched;

- (void)trackEvent:(id)a0 params:(id)a1;
- (id)referString;
- (BOOL)enableAutoPlay;
- (void)trackEvent:(id)a0 params:(id)a1 btmInfo:(id)a2;
- (id)initWithPageContext:(id)a0;
- (BOOL)lifeTabHasSmallLiveWindowWithPageType:(long long)a0;
- (void)playEnd:(id)a0;
- (void)willExitInnerPage:(id)a0;
- (void)willEnterInnerPage:(id)a0;
- (void)cellHeightChangeWithAweme:(id)a0 height:(double)a1;
- (void)cellUpdatePlayTime:(double)a0 totalTime:(double)a1 awemeModel:(id)a2;
- (void)cellUpdateLivePlayTime:(double)a0 awemeModel:(id)a1;
- (void)cellLynxResetActionType;
- (id)getGrouponTabModel;
- (long long)getGrouponTabRank;
- (void)nearbyContainerWillAppear;
- (void)nearbyContainerDidAppearWithPageType:(long long)a0;
- (void)nearbyContainerDidDisappear;
- (void)nearbyContainerEnterBackground;
- (void)containerscrollViewDidEndScroll:(id)a0;
- (void)nearbyHalfScreenContainerWillShowWithModel:(id)a0;
- (void)nearbyHalfScreenContainerWillDismissWithModel:(id)a0;
- (BOOL)shouldStopAutoPlay;
- (void)requestRecommendDataAfterClickWithParams:(id)a0 completion:(id /* block */)a1;
- (void)cancelRecommendDataRequest;
- (void)shouldShowSmallScreenWithRoomID:(id)a0 customSchema:(id)a1 scene:(long long)a2 showComplete:(id /* block */)a3;
- (void)shouldShowSmallScreenWithRoomID:(id)a0 customSchema:(id)a1 scene:(long long)a2 smallLiveWindowTopPercent:(float)a3 showComplete:(id /* block */)a4;
- (void)startAutoPlayType:(long long)a0 source:(long long)a1;
- (void)restartAutoPlay;
- (void)pauseAutoPlay;
- (void)autoPlayNextCellFromSource:(id)a0;
- (id)feedSectionLayout;
- (void)updateTabModel:(id)a0 tabRank:(long long)a1;
- (void)updateDataList:(id)a0;
- (void)getDeleteLiveRoomAwemesWithRoomID:(id)a0 completion:(id /* block */)a1;
- (void)addEventTrackerHooker;
- (void)requestRecommendDataIfNeed:(id)a0;
- (id)isSchemaInsertLiveUnderTake;
- (void)showLiveSmallWindow:(id)a0 scene:(long long)a1 withRoomID:(id)a2 showComplete:(id /* block */)a3;
- (void)setTapActionOnLiveSmallWindow:(id)a0 scene:(long long)a1 schema:(id)a2;
- (void)setHiddenCompletionOnLiveSmallWindow:(id)a0;
- (void)trackLiveSmallWindowShow;
- (void)trackLiveSmallWindowClick;
- (void)_autoPlayType:(long long)a0 source:(long long)a1;
- (id)__nextPlayCell;
- (void)playNextCell:(id)a0 source:(id)a1;
- (BOOL)inSchemaAutoPlayUnderTake;
- (void)requestRecommendDataForMode:(id)a0 inCell:(id)a1;
- (id)__nextPlayCellList;
- (void)resumeAutoPlay;
- (long long)__autoPlayAffectTime;
- (void).cxx_destruct;
- (id)autoPlayConfig;

@end
