@class NSTimer, AWEUserWorkCellViewModelPool, NSHashTable, DUXAlertDialog, NSString, NSMutableSet, UICollectionView, UIPanGestureRecognizer, NSIndexPath;
@protocol AWEProfileBatchChooseWorkDelegate, AWEProfileBatchChooseWorkDataSource;

@interface AWEProfileBatchChooseWorkViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, AWEProfileCollectionViewDelegateWaterfallLayout, UIGestureRecognizerDelegate>

@property (retain, nonatomic) UICollectionView *collectionView;
@property (retain, nonatomic) NSHashTable *animatedCoverCells;
@property (retain, nonatomic) NSMutableSet *selectedAwemeIDSet;
@property (nonatomic) BOOL isDefaultSelectAll;
@property (nonatomic) BOOL isViewOnAppear;
@property (nonatomic) struct CGPoint { double x; double y; } targetContentOffset;
@property (retain, nonatomic) NSIndexPath *targetScrollToIndexPath;
@property (nonatomic) BOOL isOnLoadingMore;
@property (retain, nonatomic) AWEUserWorkCellViewModelPool *viewModelPool;
@property (retain, nonatomic) UIPanGestureRecognizer *panGesture;
@property (retain, nonatomic) NSIndexPath *lastEffectiveIndexPath;
@property (retain, nonatomic) NSIndexPath *lastIndexPath;
@property (retain, nonatomic) NSIndexPath *initialIndexPath;
@property (nonatomic) BOOL isSelectionMode;
@property (nonatomic) double autoScrollSpeed;
@property (nonatomic) double scrollEdgeThreshold;
@property (retain, nonatomic) NSTimer *autoScrollTimer;
@property (nonatomic) BOOL hasShownDialog;
@property (retain, nonatomic) DUXAlertDialog *reachedMaxDialog;
@property (nonatomic) long long layoutStyle;
@property (nonatomic) BOOL hasMultiSelectionTracked;
@property (copy, nonatomic) NSString *referString;
@property (nonatomic) BOOL isManageMode;
@property (nonatomic) long long maxChosenCount;
@property (retain, nonatomic) NSString *enterScene;
@property (weak, nonatomic) id<AWEProfileBatchChooseWorkDelegate> delegate;
@property (weak, nonatomic) id<AWEProfileBatchChooseWorkDataSource> dataSource;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (Class)aAWEPadUserPageAdapterClass;

- (void)addGesture;
- (void)p_loadMoreData;
- (id)aAWEPadUserPageAdapter;
- (void)p_endRefreshingWithMore:(BOOL)a0 list:(id)a1 error:(id)a2;
- (double)p_footerInset;
- (void)stopAutoScroll;
- (void)updateContentOffset:(struct CGPoint { double x0; double x1; })a0 animated:(BOOL)a1;
- (id)createNormalLayout;
- (id)createWaterfallLayout;
- (id)createSingleColumnLayout;
- (long long)computeLayoutStyle;
- (id)initWithIsDefaultSelectAll:(BOOL)a0;
- (void)p_cleanSelectedSet;
- (void)shouldUpdateGuideToastWithShouldRecount:(BOOL)a0 shouldNeverShow:(BOOL)a1;
- (id)generateSelectedIndexSet;
- (BOOL)isValidHorizontalSwipe:(struct CGPoint { double x0; double x1; })a0 velocity:(struct CGPoint { double x0; double x1; })a1;
- (BOOL)handleGestureBegan:(id)a0;
- (void)handleAutoScrollForLocation:(struct CGPoint { double x0; double x1; })a0;
- (void)handleGestureEnded;
- (void)trackMultiSelectionIfNeeded;
- (BOOL)getWhetherCellIsSelectedWithIndexPath:(id)a0;
- (void)showReachedMaxAlertDialog:(BOOL)a0;
- (BOOL)updateSelectionInRange:(long long)a0 endIndex:(long long)a1 targetValue:(BOOL)a2 excludeInitial:(BOOL)a3;
- (BOOL)p_handleCellGestureChooseCollectionView:(id)a0 atIndex:(long long)a1 oldValue:(BOOL)a2 targetValue:(BOOL)a3;
- (void)startAutoScrollDown;
- (void)startAutoScrollUp;
- (void)autoScrollDown;
- (void)autoScrollUp;
- (void)updateSelectionDuringScroll;
- (void)p_handleCellChooseButtonClickCollectionView:(id)a0 atIndexPath:(id)a1;
- (void)p_updateSelectedIndexSetWithList:(id)a0;
- (void)decideWhetherChangeFromMax;
- (void)deleteSelectedItemsWithNetworkCompletion:(id /* block */)a0 collectionViewCompletion:(id /* block */)a1;
- (void)configSelectedItem:(id)a0 isSelected:(BOOL)a1;
- (void)clearSelectedItems;
- (void)configTargetScrollToItemID:(id)a0;
- (void)reloadData;
- (void).cxx_destruct;
- (BOOL)gestureRecognizer:(id)a0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)a1;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 sizeForItemAtIndexPath:(id)a2;
- (id)collectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (long long)collectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (void)collectionView:(id)a0 didSelectItemAtIndexPath:(id)a1;
- (long long)numberOfSectionsInCollectionView:(id)a0;
- (void)handleGestureChanged:(id)a0;
- (id)createLayout;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(BOOL)a0;
- (void)setupUI;
- (void)handlePanGesture:(id)a0;
- (id)dataController;

@end
