@class AWEPushSettingSectionedActionSheetView, NSString, AWEPushSettingActivityModel, NSArray, AWEHalfScreenBaseViewController, NSDictionary, AWEPushSettingActionSheet, AWEPushSettingReceiveWhoseNotificationView, AWEPushSettingsInnerPushBanner, NSNumber, AWENotificationSettingModel;
@protocol AWESettingBaseViewModelDelegate, AWEPushSettingViewModelDelegate;

@interface AWEPushSettingViewModel : AWESettingBaseViewModel <AFDSettingSearchDelegate, AWEPushSettingViewModelProtocol> {
    NSArray *_sectionDataArray;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<AWESettingBaseViewModelDelegate, AWEPushSettingViewModelDelegate> controllerDelegate;
@property (nonatomic) BOOL systemSettingGuideShow;
@property (nonatomic) BOOL systemSettingGuideShowWithView;
@property (copy, nonatomic) NSDictionary *trackerInfo;
@property (weak, nonatomic) AWEPushSettingActionSheet *multiSwitchSheet;
@property (weak, nonatomic) AWEPushSettingSectionedActionSheetView *multiSwitchWithSectionsSheet;
@property (weak, nonatomic) AWEHalfScreenBaseViewController *actionSheetVC;
@property (nonatomic) BOOL shouldShowAnchoPushItem;
@property (retain, nonatomic) NSNumber *systemPushEnabledValueUsedForApplicationActiveReload;
@property (nonatomic) BOOL localCallPushValue;
@property (nonatomic) BOOL hasShownPushGuideView;
@property (nonatomic) BOOL isToastShowing;
@property (nonatomic) BOOL didTrackEnterSetting;
@property (nonatomic) BOOL invokeByDS25Push;
@property (nonatomic) BOOL hasReportClick;
@property (copy, nonatomic) id /* block */ invokeAfterDidGrantedPush;
@property (nonatomic) BOOL isGuideShowing;
@property (retain, nonatomic) AWENotificationSettingModel *settingModel;
@property (copy, nonatomic) NSString *enterFrom;
@property (copy, nonatomic) NSDictionary *containerParamDict;
@property (retain, nonatomic) AWEPushSettingReceiveWhoseNotificationView *receiveWhoseNotificationView;
@property (nonatomic) BOOL useCardUIStyle;
@property (nonatomic) BOOL inner;
@property (nonatomic) BOOL pushEnable;
@property (copy, nonatomic) id /* block */ reloadGroupBlock;
@property (nonatomic) BOOL disableDefaultHighlightCell;
@property (retain, nonatomic) AWEPushSettingActivityModel *activityModel;
@property (retain, nonatomic) AWEPushSettingsInnerPushBanner *innerPushBanner;

+ (BOOL)useNewStyle;
+ (Class)aAWEPadBizUIAdapterClass;
+ (Class)aAWESearchModuleServiceDOUYINSSAdaperClass;
+ (id)settingSearchRegisterDic;
+ (unsigned long long)itemStatusWithSettingItem:(id)a0;
+ (Class)aAWEUserCenterIgnoreCommonAdapterClass;
+ (Class)aAWEUserCenterModuleServiceDOUYINHTSAdapterClass;
+ (Class)aAWEPushSettingsAdapterClass;
+ (BOOL)__shouldShowFriendsOnlineRemindSwitchWithEnableFriendActive:(BOOL)a0;
+ (BOOL)enableShootPushSwitch;
+ (BOOL)enablePushMutliAccount;
+ (id)pushSettingsPageURL:(long long)a0;
+ (BOOL)newPushSettingsItem:(id)a0;
+ (BOOL)newPushFilterItem:(id)a0;
+ (BOOL)useAdpaterRegisterCustomSettingItems;
+ (id)settingSearchRegisterDic_pushDirectMessage;
+ (id)settingSearchRegisterDic_pushVideoNotice;
+ (id)settingSearchRegisterDic_pushLiveNotice;
+ (id)settingSearchRegisterDic_pushLiveActivityNotice;
+ (id)settingSearchRegisterDic_pushOtherNotice;

- (id)aAWEPadBizUIAdapter;
- (void)handleApplicationDidBecomeActiveNotification;
- (void)presentHalfScreenVC:(id)a0 withView:(id)a1;
- (void)p_adaptiveLowVersionSystemWithVC:(id)a0 withView:(id)a1;
- (id)aAWESearchModuleServiceDOUYINSSAdaper;
- (void)updatePushStatus;
- (id)generateSettingItemModelWithType:(long long)a0;
- (id)getPushStatus:(id)a0;
- (id /* block */)switchChangedBlockWithFieldType:(id)a0;
- (id)switchItemModelWithTitle:(id)a0 needIcon:(BOOL)a1 isSwitchOn:(BOOL)a2 isEnable:(BOOL)a3 hasLineView:(BOOL)a4 switchChangeBlock:(id /* block */)a5;
- (void)__uploadPushSettingWithType:(id)a0 subTypeField:(id)a1 toValue:(id)a2 reloadWhenFailed:(BOOL)a3;
- (void)resetPushStatus:(id)a0 pushType:(id)a1;
- (void)__statNotificationSettingValueAfterChangeWithField:(id)a0 subFieldType:(id)a1 toValue:(id)a2;
- (void)updatePushStatusWithCompleted:(id /* block */)a0;
- (void)reloadForAnchorPushItemUpdateIfNeeded;
- (BOOL)needShowUrgeReply;
- (BOOL)shouldIgnoreNotice;
- (id)aAWEUserCenterIgnoreCommonAdapter;
- (id)__liveActivityNotificationSettingItemModel;
- (id)pushTypeToProperty;
- (id)liveActivityDetailText;
- (id)aAWEUserCenterModuleServiceDOUYINHTSAdapter;
- (id)aAWEPushSettingsAdapter;
- (void)liveSettingUpdatedNotification;
- (void)handleApplicationResignActive;
- (void)__receiveWhoseNotificationChanged:(unsigned long long)a0;
- (id)newProductSectionDataArray;
- (void)updateAnchorPushSettingWithCompleted:(id /* block */)a0;
- (void)updateAnchorBellPushVideoSetting;
- (void)refreshWhenBellPushPermissionChange:(id)a0;
- (void)__trackEnterNotificationSetting;
- (void)__showPushGuideView;
- (id)actualWhenToPushConsiderSystemNotification;
- (id)selectItemModelWithTitle:(id)a0 settingIndexValue:(long long)a1 isSelected:(BOOL)a2;
- (id /* block */)confirmAlwaysReceivePush;
- (BOOL)__isSystemPushOn;
- (id)newSubtitleSelectItemModelWithTitle:(id)a0 subtitle:(id)a1 settingIndexValue:(long long)a2 isSelected:(BOOL)a3;
- (id)whenToPushSelectItemsOnVC:(id)a0;
- (void)__uploadPushSettingWithType:(id)a0 toValue:(id)a1;
- (void)__uploadPushSettingWithType:(id)a0 subTypeField:(id)a1 toValue:(id)a2;
- (id)__trackSystemNotificationSettingParamsGuideEvent:(id)a0 extraParams:(id)a1;
- (void)__trackSystemNotificationSettingGuideEvent:(id)a0 extraParams:(id)a1;
- (void)__settingScrollToUserRangeAndFlashHighlightAnimation;
- (id /* block */)confirmReceiveFollowBlock;
- (id /* block */)confirmReceiveFriendBlock;
- (id /* block */)confirmNotReceiveBlock;
- (BOOL)__hasTaskToFinish;
- (id)__fetchWhoseReceiveLabelWithValue:(unsigned long long)a0;
- (id)newStyleSectionDataArray;
- (id)__receiveWhoseNotificationSettingItemModel;
- (id)__whenToPushDisclosureText;
- (id /* block */)whenToPushItemTappedBlock;
- (id)__detailTextWithUerRange:(id)a0 forHeader:(BOOL)a1;
- (id)__userRangeActionItemsWithCurrentRangeValue:(id)a0;
- (id)singleSelectItemModelWithTitle:(id)a0 detail:(id)a1 IconURL:(id)a2 isEnable:(BOOL)a3 fieldType:(id)a4 selectItems:(id)a5;
- (id)__simplifyVideoNotificationSettingItemModel;
- (id)__simplifyLiveNotificationSettingItemModel;
- (id)newUpdateLiveNotificationSettingItemModel;
- (id)newUpdateVideoNotificationSettingItemModel;
- (id)__simplifyOtherNotificationSettingItemModel;
- (id)__friendDotText;
- (id)newStyleSettingModelForSubVCWithTitle:(id)a0 iconName:(id)a1 type:(long long)a2;
- (id)receiveWhoseNotificationItemDisclosureTextWithType:(unsigned long long)a0;
- (id)receiveWhoseNotificationItemTitleTextWithType:(unsigned long long)a0;
- (id)cardUICallPushDetailText;
- (id)livePushDetailText;
- (id)newUpdatePushDetailText:(unsigned long long)a0;
- (id)__simplifyLivePushDetailText;
- (id)newVideoPushDetailTextWithModel;
- (id /* block */)newVideoPushChangedBlockWithFieldType:(id)a0;
- (id)__simplifyNewVideoPushDetailTextWithModel;
- (id)otherPushDetailTextWithModel;
- (id)multiSwitchesItemModelWithTitle:(id)a0 detail:(id)a1 identifier:(id)a2 iconURL:(id)a3 isEnable:(BOOL)a4 switchItems:(id)a5;
- (BOOL)isHitIMChatMoveToFriend;
- (id)__concatLabelStringWithType:(id)a0 userRangeValue:(id)a1;
- (void)updateAnchorPushSetting;
- (id)switchItemModelWithTitle:(id)a0 needIcon:(BOOL)a1 isSwitchOn:(BOOL)a2 isEnable:(BOOL)a3 isDisableWithTitleAndSwtich:(BOOL)a4 hasLineView:(BOOL)a5 switchChangeBlock:(id /* block */)a6;
- (id)multiSwitchesItemModelWithTitle:(id)a0 detail:(id)a1 identifier:(id)a2 iconURL:(id)a3 isEnable:(BOOL)a4 sections:(id)a5;
- (id)confirmWhenTapDisableCellOnVC:(id)a0;
- (id)__fetchWhenToPushLabelWithValue:(int)a0;
- (void)switchUrgeEnterpriseCommitChangeBlock:(BOOL)a0;
- (id)__actionSheetTitleTextWithUserRangeValue:(id)a0;
- (id)callPushDetailText;
- (id)multiAccountPushDetailText;
- (id)__liveNotificationSettingItemModel;
- (id)__videoNotificationSettingItemModel;
- (id)__otherNotificationSettingItemModel;
- (void)__showTemporaryNotReceiveSelectSheet;
- (id)sectionDataArray;
- (void)setSectionDataArray:(id)a0;
- (void)viewDidAppear;
- (void)reloadData;
- (void).cxx_destruct;
- (id)init;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)dealloc;

@end
