@class AWEAwemeModel, DUXPopover, UIImageView, AWEPlayInteractionMusicElementViewModel, UIView, AWEPlayInteractionMusicListenFeedGuideViewModel, NSString;
@protocol AWEPlayInteractionMusicViewProtocol, AFDMuteAwemeCancelViewProtocol;

@interface AWEPlayInteractionMusicElement : AWEPlayInteractionRightElement <AFDMuteAwemeMessage, AWEUserMessage, UIGestureRecognizerDelegate, DUXPopoverDelegate, AWERightElementMusicLayout, AWEElementSelfFilterProtocol, AWEPlayInteractionMusicElementProtocol>

@property (retain, nonatomic) UIView<AWEPlayInteractionMusicViewProtocol> *musicView;
@property (retain, nonatomic) AWEPlayInteractionMusicListenFeedGuideViewModel *listenFeedGuideViewModel;
@property (retain, nonatomic) UIImageView *followCameraImageView;
@property (nonatomic) BOOL hasShowfollowCamera;
@property (retain, nonatomic) UIView<AFDMuteAwemeCancelViewProtocol> *cancelMuteView;
@property (retain, nonatomic) AWEPlayInteractionMusicElementViewModel *viewModel;
@property (weak, nonatomic) UIView *previewableView;
@property (nonatomic) BOOL shouldShowCancelMuteAnimation;
@property (nonatomic) BOOL cancelMuteViewClicked;
@property (nonatomic) BOOL canEnterDetail;
@property (retain, nonatomic) DUXPopover *replaceMusicPopover;
@property (nonatomic) unsigned long long replaceMusicPopoverState;
@property (nonatomic) BOOL replaceMusicPopoverAutoDismiss;
@property (nonatomic) BOOL needMaskCover;
@property (nonatomic) long long lastListenFeedCover;
@property (nonatomic) BOOL lastMusicEnterTrendFeedCover;
@property (nonatomic) BOOL lastMusicNoEnterTrendAndMusicDetailFeedCover;
@property (nonatomic) BOOL lastMusicNoEnterSingleSongMusicDetailFeedCover;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) AWEAwemeModel *model;

+ (Class)aAWEPadModuleAdapterClass;
+ (id)activateInfoWithContext:(id)a0;
+ (Class)aAWEMainModuleServiceDOUYINHTSAdaperClass;
+ (BOOL)enableStory25MusicElementWithModel:(id)a0 context:(id)a1;
+ (Class)aAWEPlayInteractionMusicElementDOUYINLiteSocialAdapterClass;
+ (BOOL)shouldActivateWithData:(id)a0 context:(id)a1;

- (void)popoverDidDisappear:(id)a0;
- (void)initializeElement;
- (void)viewController_willDisplay;
- (void)viewController_didEndDisplaying;
- (void)viewController_viewWillAppear;
- (void)viewController_viewDidAppear;
- (void)viewController_viewWillDisappear;
- (void)viewController_viewDidDisappear;
- (void)muteAwemeCanceled;
- (id)aAWEPadModuleAdapter;
- (void)playMusicAnimations;
- (void)stopMusicAnimations;
- (void)videoPlayerWillTrackPlayTime;
- (void)onMusicButtonClicked:(id)a0;
- (void)viewDidChangeBreakPoint;
- (id)activateInfoWithData:(id)a0;
- (void)layoutElementView;
- (void)prepareForActivate;
- (void)pauseMusicAnimations;
- (void)resumeMusicAnimations;
- (id)aAWEMainModuleServiceDOUYINHTSAdaper;
- (void)accessibilityElementAutomaticFocus;
- (void)didtappedCancelMuteView;
- (void)addBottomButtonPriorityDebugLongPressIfNeeded;
- (BOOL)isFollowShootAnchor;
- (void)setupPadElementSizeWithConfig:(struct { double x0; double x1; double x2; double x3; double x4; double x5; double x6; double x7; double x8; double x9; double x10; double x11; })a0;
- (void)playMusicAnimationsAfterFeedReadyDelay;
- (void)doPlayMusicAnimations;
- (void)performPause;
- (BOOL)bizDowngradeMusicAnimations;
- (void)updateMusicButton;
- (void)showFollowCameraImageView;
- (void)previewingViewControllerForView;
- (void)playCancelMuteAnimation:(id)a0;
- (id)aAWEPlayInteractionMusicElementDOUYINLiteSocialAdapter;
- (void)dismissReplaceMusicPopoverIfNeeded;
- (void)executeIfMusicAnimationOptEnable:(id /* block */)a0;
- (void)p_hideMusicElementForTeenChannel;
- (void)playCancelMuteAnimationIfNeeded;
- (void)accessibilityElementAutomaticFocusNotification:(id)a0;
- (void)checkMusicElementIfNeedShow:(id)a0;
- (void)changeMusicCoverToListen:(id)a0;
- (void)updateMusicButtonImage;
- (void)hideMusicView:(BOOL)a0;
- (void)trackCancelMuteViewEvent:(id)a0 eventType:(id)a1;
- (void)p_cancelMuteAwemeWithMusicAnimationPlay:(BOOL)a0;
- (void)updateMusicViewModel;
- (void)rebuildMusicView;
- (void)resetFollowCameraImageView;
- (BOOL)isCanEnterTrendDetailStatus;
- (void)onLineLogicUpdateMusicButtonImage:(id)a0;
- (BOOL)musicCoverUnavailable;
- (void)trackMusicButtonImageFetchStatusWithModel:(id)a0 url:(id)a1 error:(id)a2;
- (BOOL)showCancelMuteAwemeTipsIfNeeded;
- (BOOL)shouldShowReplaceAudioPopover;
- (void)hideLeftElements:(BOOL)a0 animate:(BOOL)a1;
- (void)showReplaceMusicPopoverIfNeeded;
- (void)trackMusicCycleShowEvent;
- (BOOL)canPlayMusicAnimations;
- (BOOL)musicTrackAlertIfNotValid;
- (void)onMusicButtonTouchDown:(id)a0;
- (BOOL)shouldShowListenFeedCover;
- (void)onListenFeedButtonClicked:(id)a0;
- (BOOL)isPlayInteractionSingleSongOptStatus;
- (id)musicViewEnterTrendDetailOrEnterMusicDetail;
- (BOOL)isCanEnterMusicDetailStatus;
- (id)shootStyleMusicView;
- (void)followCameraImageViewClick:(id)a0;
- (void)trackMusicCoverFlipShow;
- (BOOL)canEnterTrendDetailWithoutMusic;
- (void)updateHotSplashMusicButtonImageIfNeededWithImageView:(id)a0 image:(id)a1;
- (void)p_showOtherAllElement;
- (void)updateLayout;
- (void).cxx_destruct;
- (void)pause;
- (BOOL)gestureRecognizer:(id)a0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)a1;
- (id)defaultContentImage;
- (void)reset;
- (void)resume;
- (BOOL)gestureRecognizer:(id)a0 shouldBeRequiredToFailByGestureRecognizer:(id)a1;
- (void)viewDidLoad;
- (void)dealloc;

@end
