@class UIColor, NSString, UIView, NSMutableArray, AWERLTransition;

@interface AWERLVirtualView : NSObject <AWERLVirtualViewOverride>

@property (weak, nonatomic) UIView *renderedView;
@property (copy, nonatomic) NSString *reuseIdentifier;
@property (retain, nonatomic) NSMutableArray *privateSubviews;
@property (nonatomic) BOOL rl_newAdded;
@property (nonatomic) BOOL rl_layoutCacheValid;
@property (retain, nonatomic) AWERLTransition *insertTransition;
@property (retain, nonatomic) AWERLTransition *deleteTransition;
@property (nonatomic, getter=isUserInteractionEnabled) BOOL userInteractionEnabled;
@property (retain, nonatomic) UIColor *backgroundColor;
@property (nonatomic) double cornerRadius;
@property (nonatomic) BOOL clipsToBounds;
@property (copy, nonatomic) id /* block */ singleTapBlock;
@property (nonatomic) BOOL hidden;
@property (nonatomic) double borderWidth;
@property (nonatomic) struct CGColor { } *borderColor;
@property (nonatomic) BOOL masksToBounds;
@property (nonatomic) long long contentMode;
@property (nonatomic) double alpha;
@property (nonatomic) struct CGColor { } *shadowColor;
@property (nonatomic) float shadowOpacity;
@property (nonatomic) struct CGSize { double width; double height; } shadowOffset;
@property (nonatomic) double shadowRadius;
@property (nonatomic) BOOL isAccessibilityElement;
@property (copy, nonatomic) NSString *accessibilityLabel;
@property (copy, nonatomic) NSString *accessibilityIdentifier;
@property (nonatomic) unsigned long long accessibilityTraits;
@property (nonatomic) struct CGSize { double width; double height; } size;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } frame;
@property (nonatomic) struct CGSize { double x0; double x1; } layoutSize;
@property (nonatomic) struct CGPoint { double x0; double x1; } layoutPosition;
@property (nonatomic) long long layoutStyle;
@property (nonatomic) struct UIEdgeInsets { double top; double left; double bottom; double right; } absoluteLayoutStyle;
@property (nonatomic) struct CGSize { double width; double height; } rl_cachedConstraintSize;
@property (nonatomic) struct CGSize { double width; double height; } rl_cachedMeasureSize;
@property (nonatomic) BOOL rl_hitLayoutCacheValid;
@property (copy, nonatomic) NSString *debugName;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)registerAutoSyncAttributeKeyPathPairs:(id)a0;
+ (id)autoSyncAttributeKeyPathPairs;
+ (void)unregisterAutoSyncAttributeKeyPath:(id)a0;

- (void)debugBuildDescriptions:(id)a0;
- (id)reuseIdentifier:(id)a0;
- (id)userInteractionEnabled:(BOOL)a0;
- (void)changeSubviews:(id)a0;
- (void)updateFrameForRenderedView:(id)a0;
- (id)singleTapBlock:(id /* block */)a0;
- (id)layoutStyle:(long long)a0;
- (id)absoluteLayoutStyle:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a0;
- (struct CGSize { double x0; double x1; })layoutThatFits:(struct CGSize { double x0; double x1; })a0;
- (id)createViewToRender;
- (void)updateAttributesForRenderedView:(id)a0;
- (id)borderColor:(struct CGColor { } *)a0;
- (id)borderWidth:(double)a0;
- (id)masksToBounds:(BOOL)a0;
- (id)cornerRadius:(double)a0;
- (BOOL)canRenderView;
- (id)mountWithContext:(id)a0;
- (void)debugBuildLayoutDescriptions:(id)a0;
- (void)debugHierarchyVirtualViewDescriptions;
- (void)debugHierarchyLayoutDescription;
- (void)unmount;
- (id)fetchViewToRender;
- (void)onAnimationCompletion;
- (id)clipsToBounds:(BOOL)a0;
- (id)contentMode:(long long)a0;
- (id)alpha:(double)a0;
- (id)shadowColor:(struct CGColor { } *)a0;
- (id)shadowOpacity:(float)a0;
- (id)shadowOffset:(struct CGSize { double x0; double x1; })a0;
- (id)shadowRadius:(double)a0;
- (id)transition:(id)a0;
- (void)__updateMountedView:(id)a0 context:(id)a1;
- (void).cxx_destruct;
- (id)valueForUndefinedKey:(id)a0;
- (id)initWithSize:(struct CGSize { double x0; double x1; })a0;
- (id)init;
- (void)addTransition:(id)a0;
- (void)addSubview:(id)a0;
- (id)backgroundColor:(id)a0;
- (id)subviews;
- (id)isAccessibilityElement:(BOOL)a0;
- (id)accessibilityLabel:(id)a0;
- (id)accessibilityTraits:(unsigned long long)a0;
- (id)size:(struct CGSize { double x0; double x1; })a0;
- (id)hidden:(BOOL)a0;

@end
