@class AWEPhotoPickerController, UIView, CAKModalTransitionDelegate, NSString, NSMutableDictionary, AWEStudioPropVideoProcessorUtil, CAKAlbumViewController, AWEARTextInputViewController, IESEffectModel, NSMutableSet;
@protocol ACCLoadingViewProtocol, ACCSideslipPropService, ACCSelectAlbumAssetsProtocol, AWEStickerViewLayoutManagerProtocol;

@interface AWEStickerApplyEditableEffectHandler : AWEStickerApplyBaseHandler <ACCRecordUploadButtonHandlerProtocol, ACCRecordFlowServiceSubscriber, ACCRecordPropServiceSubscriber, AWEPhotoPickerControllerDelegate, ACCSelectAlbumAssetsDelegate>

@property (weak, nonatomic) id<ACCSideslipPropService> sideslipPropService;
@property (retain, nonatomic) AWEPhotoPickerController *photoPickerController;
@property (retain, nonatomic) AWEARTextInputViewController *textInputController;
@property (retain, nonatomic) CAKModalTransitionDelegate *transitionDelegate;
@property (retain, nonatomic) CAKAlbumViewController *albumViewController;
@property (retain, nonatomic) id<ACCSelectAlbumAssetsProtocol> albumViewControllerBuilder;
@property (weak, nonatomic) id<AWEStickerViewLayoutManagerProtocol> currentLayoutManager;
@property (retain, nonatomic) UIView<ACCLoadingViewProtocol> *loadingView;
@property (retain, nonatomic) AWEStudioPropVideoProcessorUtil *videoProcessor;
@property (retain, nonatomic) IESEffectModel *currentSticker;
@property (nonatomic) BOOL hasExportedBeforePanelDismiss;
@property (nonatomic) BOOL hasChangedText;
@property (retain, nonatomic) NSMutableSet *templatePropIdSet;
@property (retain, nonatomic) NSMutableDictionary *templateCustomIdDict;
@property (nonatomic) BOOL hasStartUpdateMutiPics;
@property (copy, nonatomic) id /* block */ exportBlock;
@property (nonatomic) BOOL hasEndShootingBeforeApplyImages;
@property (nonatomic) BOOL isPhotoAuthNotDeterminedWhenResignActive;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)flowServiceStateDidChanged:(unsigned long long)a0 preState:(unsigned long long)a1;
- (void)flowServiceWillBeginTakePicture;
- (void)flowServiceWillAddPictureToVideo:(id)a0;
- (void)flowServiceDidAddPictureToVideo:(id)a0;
- (void)flowServiceWillAddFragment:(id)a0;
- (void)flowServiceDidRemoveFragment:(id)a0;
- (void)flowServiceDidRemoveAllSegment;
- (void)flowServiceDidTakePicture:(id)a0 error:(id)a1;
- (void)flowServiceDidCompleteRecord;
- (void)propServiceWillDismissPanel:(id)a0;
- (void)propServiceDidShowPanel:(id)a0;
- (id)publishModel;
- (void)handleClickUploadButton;
- (BOOL)albumViewControllerShouldSelectAsset:(id)a0;
- (void)albumViewControllerDidSelectAssets:(id)a0;
- (void)albumViewControllerDidSelectOneAsset:(id)a0;
- (void)p_hiddenLoading;
- (void)camera:(id)a0 didTakeAction:(long long)a1 error:(id)a2 data:(id)a3;
- (void)camera:(id)a0 didRecvMessage:(id)a1;
- (void)didSelectNewSticker:(id)a0 oldSticker:(id)a1;
- (void)camera:(id)a0 didApplySticker:(id)a1 success:(BOOL)a2;
- (void)camera:(id)a0 willApplySticker:(id)a1;
- (BOOL)couldHandleClickUploadButton;
- (void)photoPickerController:(id)a0 didSelectAsset:(id)a1 atIndex:(long long)a2;
- (void)photoPickerControllerDidSelectPlusButton:(id)a0;
- (void)photoPickerControllerDidSelcetTextPlusButton:(id)a0;
- (void)photoPickerController:(id)a0 didClickMultiSelectionFinishButton:(id)a1;
- (void)handlerDidBecomeActive;
- (void)didChangeLayoutManager:(id)a0;
- (void)p_resetWithSticker:(id)a0;
- (BOOL)shouldChooseVideoAssets;
- (void)p_handleAIEffect:(id)a0;
- (void)p_configAndShowTextInputController:(BOOL)a0;
- (void)p_removePhotoSelectViewsFromLayoutManager:(id)a0 animated:(BOOL)a1;
- (void)p_showPhotoSelectViewsOnLayoutManager:(id)a0 animated:(BOOL)a1;
- (void)resetEditablePropInfo;
- (void)p_resetPhotoPickerController;
- (void)preloadPropAnnotations:(id)a0;
- (BOOL)shouldShowPhotoPicker;
- (void)p_showPhotoPickerControllerIfNeeded;
- (id)p_packageName;
- (id)p_iconName;
- (BOOL)p_shouldCreateCustomizedProp:(id)a0;
- (void)p_saveCustomPropFrameSamplingImagesIfNeeded;
- (void)p_updateDiyPropType:(id)a0;
- (void)p_setCustomPropInfoWithPictureToVideo:(id)a0 videoFragment:(id)a1;
- (void)applySelectedMultiAssets:(id)a0 needNotify:(BOOL)a1;
- (void)exportCustomPropWithPackagePath:(id)a0 iconPath:(id)a1 completion:(id /* block */)a2;
- (void)p_execShootingEndExportIfNeeded;
- (void)removeDraftURSWithFragments:(id)a0;
- (void)p_trackForSelectPhotoAssets:(BOOL)a0;
- (void)p_trackForFinishUploadAssets:(BOOL)a0 isSingleAsset:(BOOL)a1;
- (void)p_trackForExportCustomPackage:(id)a0 success:(BOOL)a1 error:(id)a2;
- (id)p_addBorderForCustomPropIcon:(id)a0;
- (void)openAlbumViewControllerIfPossible;
- (void)showAlbumViewController;
- (void)p_showPhotoPickerControllerWithImageDetector:(id)a0;
- (void)createPhotoVCWithAssetType:(unsigned long long)a0;
- (BOOL)p_shouldFilterWithScene:(unsigned long long)a0;
- (void)trackPropTrayShow;
- (id)generateSingleSelectVideoAlbumInputData;
- (id)generateMultiSelectAlbumInputData;
- (id)generateSingleSelectAlbumInputData;
- (void)p_trackForClickAlbumPlusButton;
- (void)handleSelectedAsset:(id)a0 selectedFromAlbum:(BOOL)a1;
- (void)selectVideoAsset:(id)a0;
- (void)p_imageArrayApplyHandler:(id)a0 needNotify:(BOOL)a1;
- (struct CGSize { double x0; double x1; })customPropAssetMaximumExportSize;
- (id)cropImageIfNeeded:(id)a0;
- (void)p_imageApplyHandler:(id)a0 photoSource:(id)a1 previewOnly:(BOOL)a2;
- (void)p_updateDiyInfoAfterUpdatingPhotoSelection;
- (void)p_showLoadingWithScene:(long long)a0;
- (void)selectSingleVideoAsset:(id)a0 atIndex:(long long)a1;
- (void)multiAssetSelectionWithAsset:(id)a0 atIndex:(long long)a1;
- (void)singleAssetSelectionWithAsset:(id)a0 atIndex:(long long)a1;
- (void)trackPropTrayClick;
- (void)p_imagePreviewIfNeed:(id)a0;
- (void)p_doesKeyboardShow:(BOOL)a0;
- (void)p_trackForFinishEditText:(BOOL)a0;
- (void)p_trackForEnterEditText:(BOOL)a0;
- (void)clearAIGCEffectConfigIfNeeded;
- (void)openVideoClipViewControllerWithAsset:(id)a0 fromAlbum:(BOOL)a1;
- (void)handleApplyVideoPathSuccessAsset:(id)a0 videoPath:(id)a1;
- (id)p_editablePropCommonTrackDict;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (void)p_applicationWillResignActive:(id)a0;
- (void)p_applicationDidBecomeActive:(id)a0;

@end
