@class AWEAwemeModel, NSString, AWEScreenCastAwemeImpl, NSArray, BDSCProgressInfo, BDSCAirPlayObserver, AWEScreenCastControlViewConfig, NSDictionary, NSMutableArray, AWEScreenCastObserver, AWEScreenCastJSBridgeImpl;
@protocol AWEScreenCastShortConfigService, AWEScreenCastFloatingViewService, AWEScreenCastPendantService;

@interface AWEScreenCastModuleService : HTSService <AWEScreenCastModuleService, AWESCSearchMutuallyExclusiveTaskDelegate>

@property (copy, nonatomic) NSString *sceneID;
@property (retain, nonatomic) AWEScreenCastControlViewConfig *awemeControlViewConfig;
@property (retain, nonatomic) AWEScreenCastAwemeImpl *awemeImpl;
@property (retain, nonatomic) AWEScreenCastJSBridgeImpl *jsbridgeImp;
@property (nonatomic) BOOL allowBusinessPlayer;
@property (retain, nonatomic) NSDictionary *playInfo;
@property (retain, nonatomic) id<AWEScreenCastFloatingViewService> floatingViewService;
@property (retain, nonatomic) id<AWEScreenCastShortConfigService> shortConfigService;
@property (retain, nonatomic) id<AWEScreenCastPendantService> pendantService;
@property (retain, nonatomic) NSMutableArray *searchTasks;
@property (retain, nonatomic) AWEScreenCastObserver *screenCastObserver;
@property (retain, nonatomic) BDSCAirPlayObserver *airPlayObserver;
@property (retain, nonatomic) AWEAwemeModel *lvFocusModeAlbum;
@property (copy, nonatomic) NSArray *lvFocusModeEpisodeCache;
@property (retain, nonatomic) AWEAwemeModel *fromModel;
@property (nonatomic) BOOL isInCastInnerFeed;
@property (readonly, nonatomic) BDSCProgressInfo *curProgressInfo;
@property (readonly, nonatomic) unsigned long long playStatus;
@property (readonly, nonatomic) AWEScreenCastControlViewConfig *currentBizConfig;
@property (readonly, nonatomic) unsigned long long castStatus;
@property (readonly, nonatomic) BOOL isVideoCasting;
@property (readonly, nonatomic) BOOL isLongVideoFocusMode;
@property (nonatomic) BOOL needShowSearchViewAfterForceUpdateToPortrait;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (BOOL)screenCastAdapterInitialized;
- (BOOL)isScreenCasting;
- (BOOL)isSearchViewShowing;
- (void)showCastSearchDevicesView;
- (void)showCastSearchDevicesViewWithDelay;
- (void)closeSearchDeviceViewController;
- (BOOL)longVideoSupportCast:(BOOL)a0;
- (BOOL)canScreenCastWithScene:(unsigned long long)a0;
- (id)shortVideoCastConfig:(BOOL)a0;
- (BOOL)longVideoCastInShortFeedEnable;
- (BOOL)longVideoCastInLandscapeFeedEnable;
- (BOOL)shortVideoCastEnableWithReferString:(id)a0;
- (BOOL)landscapeNewEnableWithReferString:(id)a0;
- (BOOL)feedCastEnableWithReferString:(id)a0;
- (BOOL)searchViewUnification;
- (BOOL)useNewControlViewUI;
- (BOOL)newPendantEnabled;
- (BOOL)castStateFeedbackEnabled;
- (id)byteScreenCastContext;
- (id)currentConnectedDeviceName;
- (id)controlViewConfig;
- (void)updateDayMode:(BOOL)a0;
- (void)showCastControlViewWithConfig:(id)a0;
- (void)updateControlViewWithConfig:(id)a0;
- (id)createCastControlViewWithConfig:(id)a0;
- (void)startupScreenCastIfNeed;
- (void)closeScreenCast;
- (void)closeScreenCast:(BOOL)a0 disconnect:(BOOL)a1;
- (void)closeScreenCastOnlyRemoveCastControlView;
- (BOOL)isCastViewShowing;
- (BOOL)isCastControlViewShowing;
- (void)seekToProgress:(double)a0;
- (BOOL)isInLVScreenCasting;
- (BOOL)isInShortScreenCasting;
- (void)preSearch;
- (void)stopPreSearchIfNeeded;
- (BOOL)isEnableAirPlayMirrorForPlaylet;
- (BOOL)isAirPlayMirroring;
- (void)removeAllScreenCastInnerFeed;
- (void)activeListenerWith:(id)a0;
- (void)invokeWithArgs:(id)a0;
- (id)invokeWithAction:(id)a0 uuid:(id)a1 params:(id)a2;
- (void)openFeedBackPage;
- (BOOL)needEnterCastPageForModel:(id)a0;
- (BOOL)needForbidWithModel:(id)a0;
- (id)castForbiddenToastWithModel:(id)a0;
- (BOOL)isLongVideoWithModel:(id)a0;
- (id)videoIDWithModel:(id)a0;
- (id)longVideoHeadTailTimeWithModel:(id)a0;
- (id)curSceneString;
- (void)startScreenCastWithVideoModel:(id)a0 progressInfo:(id)a1;
- (void)startScreenCastWithVideoModel:(id)a0 progressInfo:(id)a1 completed:(id /* block */)a2;
- (void)updateCastPlayVideoList:(id)a0;
- (void)longVideoFocusModeUpdatePlayVideoList:(id)a0;
- (void)appendCastPlayVideoList:(id)a0;
- (BOOL)checkCanCastVideoInFeedWith:(id)a0 landscape:(BOOL)a1;
- (BOOL)checkLandscapeCanCastWith:(id)a0;
- (void)preSetupViewModelConfig:(id)a0 forVideoInfo:(id)a1;
- (BOOL)canContinuePlay;
- (id)bizSettingConfig;
- (void)updateScreenScreenBottomDistance:(id)a0;
- (BOOL)enableLongVideoFocusMode;
- (void)quitLongVideoFocusMode;
- (void)recordLongVideoFocusMode:(id)a0;
- (id)currentFocusModeRecordAlbum;
- (id)currentFocusModeEpisodeList;
- (id)currentScreenCastModel;
- (BOOL)isLongVideoLastEpisode:(id)a0;
- (void)tryFetchLongVideoAlbumEpisodeList:(id)a0 needUpdateList:(BOOL)a1;
- (void)updateLongVideoFocusEpisodesCache:(id)a0;
- (id)getVideoListDescription:(id)a0;
- (void)trackScreenCastButtonShowed:(id)a0 awemeModel:(id)a1 extraParams:(id)a2;
- (void)trackScreenCastButtonClicked:(id)a0 awemeModel:(id)a1 extraParams:(id)a2;
- (void)trackFloatingViewShowed:(id)a0 awemeModel:(id)a1 extraParams:(id)a2;
- (void)trackFloatingViewClicked:(id)a0 awemeModel:(id)a1 extraParams:(id)a2;
- (void)trackScreenCastButtonActionForbidden:(id)a0 extraParams:(id)a1;
- (void)trackControlPageReturnClickedWithExtraParams:(id)a0;
- (void)trackScreenCastContentServiceWithPath:(id)a0 duration:(double)a1 error:(id)a2 extraParams:(id)a3;
- (void)trackScreenCastContentServiceWithExtraParams:(id)a0;
- (void)trackScreenCastInnerFeedClosedWithExtraParams:(id)a0;
- (void)sendEvent:(id)a0 extraParams:(id)a1;
- (id)commonEventParamsWithAwemeModel:(id)a0;
- (void)addSearchTask:(id)a0;
- (void)performBonjourBlock:(id /* block */)a0;
- (void)enterScreenCastInnerListWithAwemeModelList:(id)a0 enterFrom:(id)a1 fromModel:(id)a2 preNode:(id)a3 params:(id)a4;
- (void)requestWithParams:(id)a0 pullType:(long long)a1 completion:(id /* block */)a2;
- (unsigned long long)currentCastIndex;
- (id)screenCastFeedVideoList;
- (BOOL)needEnterSearchProcess;
- (void)tryCastModel:(id)a0;
- (BOOL)innerFeedNeedLoadMoreData;
- (BOOL)screenCastInnerFeedEnabled;
- (BOOL)screenCastLandscapeUsePortraitListEnable;
- (long long)innerFeedCastNextLimitCount;
- (BOOL)innerFeedSupportLoadMoreForAllScene;
- (BOOL)screenCastSearchLoadMoreEnable;
- (void)updateCastCloseReason:(id)a0;
- (BOOL)innerFeedPlayOptimize;
- (void)configContentServiceWithParams:(id)a0;
- (BOOL)isCompilationWithReferString:(id)a0;
- (BOOL)isYummeWithReferString:(id)a0;
- (BOOL)isHomepageWithReferString:(id)a0;
- (BOOL)checkIsValid:(id)a0;
- (id)commonEventParams;
- (BOOL)canStopOtherTask:(id)a0;
- (void)willChangeState:(unsigned long long)a0 task:(id)a1;
- (void)wakeUpObserver;
- (BOOL)shortVideoCastConfigSupportPortrait:(BOOL)a0 referString:(id)a1;
- (BOOL)needEnterFocusModeWithModel:(id)a0;
- (void)quitLongVideoFocusModeIfNeeded:(id)a0;
- (BOOL)supportCastWithAwemeType:(long long)a0;
- (id)extraParamsWithSceneID:(id)a0;
- (void)trackScreenCastEnterInnerFeedWithExtraParams:(id)a0;
- (BOOL)mediumLandscapeCastEnable:(BOOL)a0;
- (void).cxx_destruct;
- (void)play;
- (void)pause;
- (BOOL)isPlaying;
- (id)init;
- (void)updateSceneID:(id)a0;

@end
