@class AWEStudioIdleTimerHandler, NSString, NSDictionary, ACCEditorTrackerTool, NSObject;
@protocol ACCComponentManager, AWECommerceOpenShareProtocol;

@interface AWEStudioVideoEditViewController : ACCViewController <AWEMediaBigAnimationProtocol, ACCEditTransitionContainerViewControllerProtocol, ACCEditSessionLifeCircleEvent, AWEStudioVideoEditViewControllerProtocol, AWEStudioTransitionEditorContextProvider, AWEEditPageProtocol>

@property (retain, nonatomic) ACCEditorTrackerTool *editorTrackerTool;
@property (nonatomic) BOOL hasExecutedFirstResetPlayer;
@property (nonatomic) BOOL hasReportFirstFrameDuration;
@property (nonatomic) BOOL hasReportSensorialPlayFrameDuration;
@property (nonatomic) long long tryPlayCount;
@property (retain, nonatomic) AWEStudioIdleTimerHandler *idleTimerHandler;
@property (nonatomic) BOOL hasAddedVolumeChangeObserver;
@property (nonatomic) BOOL isFirstTimeOfTappingVolumeButton;
@property (nonatomic) BOOL draftInited;
@property (retain, nonatomic) NSDictionary *firstRenderTrackParams;
@property (nonatomic) unsigned long long recordBindOptimizeType;
@property (nonatomic) long long needSaveDraftFlag;
@property (retain, nonatomic) NSObject<AWECommerceOpenShareProtocol> *commerceOpenShareHelper;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) id inputData;
@property (readonly, nonatomic) id<ACCComponentManager> componentManager;

- (id)awesst_enterFrom;
- (void)sensorialRenderWithEditService:(id)a0;
- (void)firstRenderWithEditService:(id)a0;
- (void)coverRemoveVisibleWithEditService:(id)a0;
- (void)failedToPlayWithEditService:(id)a0;
- (void)setCoverImage:(id)a0;
- (void)buildEditSession;
- (id)beforeTransitionSnapshotView;
- (id)publishModel;
- (id)draftService;
- (id)initWithBusinessConfiguration:(id)a0;
- (id)editService;
- (id)sequenceEditService;
- (id)musicFeatureAPI;
- (BOOL)enableFirstRenderOptimize;
- (id)stickerService;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })mediaBigMediaFrame;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })mediaBigPlayerFrame;
- (id)mediaBigMediaSnap;
- (id)mediaBigButtonsContainerSnap;
- (id)mediaBigButtonsContainer;
- (long long)mediaBigMediaContentMode;
- (id)mediaBigMediaSnapToAdvanceEdit:(BOOL)a0;
- (double)mediaBigMediaContainerCornerRadius;
- (void)transitionMediaSnapWithCompletion:(id /* block */)a0;
- (void)popSelf;
- (id)handleTargetViewControllerInputData;
- (void)prepareForLoadComponent;
- (void)beforeLoadLazyComponent;
- (id)creatComponentManager;
- (id)perfService;
- (id)pageEditService;
- (id)pageSequenceEditService;
- (void)saveDraftIfNeed;
- (id)p_reactedBGMAsset;
- (id)transitionMediaSnap;
- (id)transitionSnapContentViewWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 playerFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)controllerTaskFinished;
- (void)configWithInputData:(id)a0;
- (id)beforeTransitionMediaSnapshotView;
- (void)configComponentManager;
- (void)registerViewService;
- (void)trackEnterAudioReplacePage;
- (void)addVolumeChangeObserver;
- (long long)anchorListRequestItemType;
- (id)anchorParamsFromPublishModel:(id)a0;
- (void)trackMoreButtonClick:(BOOL)a0;
- (void)p_playWhenEnterFromUpload;
- (void)p_continuePlayWhenBack;
- (void)fetchHDCountWithCompletion:(id /* block */)a0;
- (void)removeVolumeChangeObserver;
- (BOOL)p_isOpenNewPageInEditorAndBack;
- (id)stickerContainerSnapService;
- (void)handleEditFirstRenderCallBack;
- (void)handleFastLoadComponentOfPhase;
- (void)handleEditSensorialPlayFrameCallBack;
- (BOOL)shouldForceInfini;
- (void)p_resetPlayer;
- (void)setupSlidesVoiceVolume;
- (void)setupMuteVoiceIfNeeded;
- (void)trackEditorFirstFrame;
- (void)trackEditorSensorialPlayFrame;
- (void)trackVisibleFirstFrame;
- (id)editPlayerMonitorService;
- (void)doExternalTask;
- (BOOL)shouldHandleNonInfini;
- (void)handleNonInfiniIfNeeded;
- (void)pollTrackImportQuality:(BOOL)a0;
- (void)volumeClicked:(id)a0;
- (void)trackFirstTimeOfTappingVolumeButton;
- (void)close;
- (void).cxx_destruct;
- (id /* block */)cancelBlock;
- (BOOL)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)loadView;
- (void)viewWillDisappear:(BOOL)a0;
- (id)sourceModel;

@end
