@class UIFont, NSString, UIImage, NSURL, NSAttributedString, NSIndexPath, UITableViewCell, NSArray, NSNumber, UIColor;
@protocol AWEUserSettingBigFontAdapterProtocol;

@interface AWESettingItemModel : NSObject

@property (retain, nonatomic) NSString *identifier;
@property (copy, nonatomic) NSString *cellControllerID;
@property (nonatomic) long long type;
@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSAttributedString *attributedTitle;
@property (copy, nonatomic) NSString *titleHighLightedPart;
@property (retain, nonatomic) UIColor *titleColor;
@property (copy, nonatomic) NSString *subTitle;
@property (copy, nonatomic) NSString *fancySubtitle;
@property (copy, nonatomic) NSString *detail;
@property (copy, nonatomic) NSAttributedString *attributedDetail;
@property (copy, nonatomic) NSString *rightButtonTitle;
@property (retain, nonatomic) UIColor *rightButtonBgColor;
@property (retain, nonatomic) UIColor *rightButtonLineColor;
@property (retain, nonatomic) UIColor *rightButtonTextColor;
@property (nonatomic) BOOL isForbidChangeColor;
@property (nonatomic) BOOL isCellLoading;
@property (copy, nonatomic) NSString *loadingImageName;
@property (copy, nonatomic) NSString *loadingPlaceholderText;
@property (copy, nonatomic) id /* block */ rightButtonAction;
@property (copy, nonatomic) id /* block */ detailButtonAction;
@property (retain, nonatomic) UIColor *detailColor;
@property (retain, nonatomic) UIFont *detailFont;
@property (nonatomic) BOOL ignoreTitleTranslate;
@property (nonatomic) BOOL ignoreDetailTranslate;
@property (nonatomic) BOOL isFriendsGeckoImage;
@property (retain, nonatomic) UIImage *specificIconImage;
@property (copy, nonatomic) NSString *iconImageName;
@property (copy, nonatomic) NSString *svgIconImageName;
@property (retain, nonatomic) NSURL *iconImageNameUrl;
@property (retain, nonatomic) NSString *iconSearchBundleName;
@property (nonatomic) long long cellType;
@property (nonatomic) BOOL isSwitchOn;
@property (nonatomic) BOOL isEnable;
@property (nonatomic) BOOL isDataException;
@property (nonatomic) BOOL isDisableWithTitleAndSwtich;
@property (copy, nonatomic) NSString *disbleToast;
@property (nonatomic) BOOL isDisableExceptSwitch;
@property (nonatomic) BOOL isSelect;
@property (nonatomic) BOOL showDotView;
@property (nonatomic) long long dotType;
@property (nonatomic) BOOL useStandardDotColor;
@property (nonatomic) BOOL forceDotUseRedColor;
@property (nonatomic) BOOL useStandardArrowImage;
@property (nonatomic) long long redDotType;
@property (nonatomic) long long colorStyle;
@property (nonatomic) double cellHeight;
@property (retain, nonatomic) NSNumber *customTopMargin;
@property (retain, nonatomic) NSNumber *customBottomMargin;
@property (nonatomic) BOOL highlightDetail;
@property (nonatomic) BOOL enableDetailCenterFit;
@property (copy, nonatomic) id /* block */ cellTappedBlock;
@property (copy, nonatomic) id /* block */ cellConfirmBlock;
@property (copy, nonatomic) id /* block */ switchChangedBlock;
@property (copy, nonatomic) id /* block */ cellRefreshBlock;
@property (copy, nonatomic) id /* block */ cellReloadBlock;
@property (retain, nonatomic) NSString *rightPicName;
@property (nonatomic) struct CGSize { double width; double height; } rightPicSize;
@property (copy, nonatomic) id /* block */ rightPicTappedBlock;
@property (copy, nonatomic) id /* block */ refreshSubtitleBlock;
@property (nonatomic) BOOL hasLineView;
@property (nonatomic) long long uploadIndex;
@property (retain, nonatomic) NSNumber *rightCustomViewForceVisibility;
@property (retain, nonatomic) NSNumber *customRightMargin;
@property (nonatomic) BOOL rightPicColorChanged;
@property (retain, nonatomic) id<AWEUserSettingBigFontAdapterProtocol> fontAdapter;
@property (retain, nonatomic) NSIndexPath *indexPath;
@property (nonatomic) BOOL userInteractionEnabled;
@property (nonatomic) long long subtitleLeftIndentation;
@property (nonatomic) BOOL shouldJumpUpdateHeight;
@property (retain, nonatomic) NSString *textFieldContent;
@property (retain, nonatomic) NSString *textFieldPlaceholder;
@property (retain, nonatomic) UIImage *textFieldRightImage;
@property (nonatomic) long long textFieldRightViewMode;
@property (copy, nonatomic) id /* block */ textFieldEditingChangedBlock;
@property (copy, nonatomic) id /* block */ textFieldEndEditingBlock;
@property (copy, nonatomic) id /* block */ textFieldBeginEditingBlock;
@property (copy, nonatomic) id /* block */ textFieldShouldReturnBlock;
@property (weak, nonatomic) UITableViewCell *cell;
@property (retain, nonatomic) id value;
@property (copy, nonatomic) NSString *cellControllerClass;
@property (copy, nonatomic) NSString *traceEnterFrom;
@property (copy, nonatomic) NSArray *rightTitleList;
@property (nonatomic) long long rightTitleListSelectedIndex;
@property (copy, nonatomic) id /* block */ rightTitleListSelectedBlock;
@property (copy, nonatomic) NSString *businessID;

- (void)dealloc;
- (void)refreshCell;
- (void).cxx_destruct;
- (id)initWithIdentifier:(id)a0;
- (id)init;

@end
