@class NSTimer, ACCToolBarItemsModel, NSArray, ACCToolBarItemView, UIView, UIImageView, NSString, AWEToolBarViewModel, CAGradientLayer, ACCToolBarCommonViewLayout, AWEToolBarScrollStackView;

@interface AWEToolBarView : UIView <UIScrollViewDelegate>

@property (nonatomic) BOOL folded;
@property (nonatomic) BOOL shouldHideMoreButton;
@property (nonatomic) BOOL labelShowing;
@property (retain, nonatomic) NSTimer *timer;
@property (retain, nonatomic) ACCToolBarCommonViewLayout *layout;
@property (retain, nonatomic) NSArray *itemsArray;
@property (retain, nonatomic) ACCToolBarItemsModel *model;
@property (retain, nonatomic) AWEToolBarViewModel *viewModel;
@property (weak, nonatomic) CAGradientLayer *maskLayer;
@property (nonatomic) unsigned long long fadeMaskState;
@property (retain, nonatomic) AWEToolBarScrollStackView *scrollStackView;
@property (retain, nonatomic) ACCToolBarItemView *moreButtonView;
@property (retain, nonatomic) UIImageView *shadowView;
@property (retain, nonatomic) UIView *fadeView;
@property (readonly, copy, nonatomic) NSArray *viewsArray;
@property (nonatomic) BOOL alwaysShowLabel;
@property (copy, nonatomic) id /* block */ clickItemBlock;
@property (copy, nonatomic) id /* block */ clickMoreBlock;
@property (copy, nonatomic) id /* block */ scrollExpandBlock;
@property (copy, nonatomic) id /* block */ didLayoutUIBlock;
@property (copy, nonatomic) id /* block */ didStackViewScroll;
@property (nonatomic) BOOL isEdit;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)viewWithBarItemID:(void *)a0;
- (void)showAllLabel;
- (void)p_layoutUI;
- (unsigned long long)barItemDirection;
- (void)updateItem:(id)a0 animated:(BOOL)a1;
- (void)updateItemViewHiddenOpt:(id)a0 layoutUI:(BOOL)a1;
- (void)updateAllItemViews:(BOOL)a0;
- (void)layoutUIWithAnimated:(BOOL)a0;
- (void)updateFoldState:(BOOL)a0 shouldHideMoreButton:(BOOL)a1 animated:(BOOL)a2;
- (id)viewIndexWithBarItemID:(void *)a0;
- (void)resetFoldState;
- (void)updateAllBarItemsRotate:(double)a0 animated:(BOOL)a1;
- (void)hideAllLabelWithAnimation:(BOOL)a0;
- (BOOL)shouldShowDivisionView;
- (id)initWithViewLayout:(id)a0 itemsData:(id)a1 model:(id)a2 isEdit:(BOOL)a3;
- (void)updateFadeViewWithState:(unsigned long long)a0;
- (void)layoutMoreButtonView;
- (unsigned long long)p_numberOfItemsFolded;
- (unsigned long long)numberOfAllItems;
- (void)hideAllLabelAfterSeconds:(double)a0;
- (void)onMoreButtonClicked;
- (void)scrollToExpand;
- (BOOL)p_shouldShowMoreButton;
- (unsigned long long)p_numberOfItemsToShow;
- (long long)numberOfItemsFoldedWithFirstFrameBefore;
- (void)p_checkAndShowBubble;
- (BOOL)itemBarShouldShow:(id)a0;
- (void)layoutShadowView;
- (void)layoutScrollStackView;
- (id)p_itemViewsToShow;
- (void)triggerItemBarShowBlockWithViews:(id)a0;
- (void)layoutUIWithFolded:(BOOL)a0 animated:(BOOL)a1;
- (double)calculateScrollStackViewFrameHeight;
- (void)updateItemViewHiddenOpt:(id)a0 animated:(BOOL)a1;
- (void)updateItemViewHiddenOpt:(id)a0 layoutUI:(BOOL)a1 animated:(BOOL)a2;
- (void)p_layoutUIAnimated;
- (void)p_updateAllBarItemsRotate:(double)a0;
- (void)foldStatusUpdate;
- (void)triggerItemBarShowBlockForClickMoreIfNeed;
- (id)indexesOfItemsToshow;
- (BOOL)p_viewInsideScrollFrame:(id)a0;
- (id)p_barItemWithItemId:(void *)a0;
- (void)clickedBarItemType:(unsigned long long)a0;
- (void).cxx_destruct;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)scrollViewDidScroll:(id)a0;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)setupUI;

@end
