@class AWEUGFeedPendantActivityTaskManager, NSString, NSTimer, AWEUGPendantActivityModel, UIView, AWEUGFeedPendantEvadeControlService, AWEUGPendantExpandFoldTask;
@protocol AWEUGPendantUIProtocol, AWEUGPendantResourceManagerProtocol, AWEFeedPendantLinkMonitorProtocol;

@interface AWEUGPendantActivityController : NSObject <AWEBasicModeMessage, AWEUGPendantActivityControllerProtocol, AWEUGPendantTaskStatusProtocol>

@property (retain, nonatomic) UIView<AWEUGPendantUIProtocol> *pendant;
@property (retain, nonatomic) AWEUGPendantActivityModel *dataModel;
@property (retain, nonatomic) AWEUGFeedPendantEvadeControlService *evadeControlService;
@property (nonatomic) BOOL userClosed;
@property (nonatomic) BOOL playFailed;
@property (nonatomic) BOOL isResourceComplete;
@property (weak, nonatomic) id<AWEUGPendantResourceManagerProtocol> resourceDelegate;
@property (nonatomic) BOOL needCheckReportAgain;
@property (nonatomic) BOOL didTrackShow;
@property (nonatomic) BOOL hasAddToken;
@property (nonatomic) long long topTabType;
@property (nonatomic) double lastTimestamp;
@property (nonatomic) BOOL duringCountdown;
@property (nonatomic) unsigned long long capsuleState;
@property (copy, nonatomic) NSString *lastLottieName;
@property (weak, nonatomic) AWEUGPendantExpandFoldTask *expandFoldTask;
@property (retain, nonatomic) AWEUGFeedPendantActivityTaskManager *activityTaskManager;
@property (retain, nonatomic) NSTimer *timer;
@property (retain, nonatomic) id<AWEFeedPendantLinkMonitorProtocol> linkMonitor;
@property (nonatomic) BOOL disableResponseToClick;
@property (nonatomic) BOOL disableResponseToClose;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) UIView<AWEUGPendantUIProtocol> *pendantView;
@property (readonly, nonatomic) AWEUGPendantActivityModel *activityModel;

- (id)trackParams;
- (void)basicModeDidChange:(BOOL)a0;
- (void)trackShowEvent;
- (void)feedContainerDidAppear;
- (void)showPendant;
- (void)hidePendant;
- (void)setupNotification;
- (id)currentReferString;
- (void)feedContainerViewControllerDidSwitchTab:(id)a0;
- (void)trackLogWithKey:(id)a0 message:(id)a1;
- (void)updateCapsuleState:(unsigned long long)a0;
- (void)updateUIWithKey:(id)a0 string:(id)a1 complete:(id /* block */)a2;
- (BOOL)hasTaskInProcess;
- (void)trackFeedPendanTimingTaskManagerLogWithMessage:(id)a0;
- (void)updateCurrentProgress:(double)a0 animated:(BOOL)a1;
- (void)triggerWatchVideoTaskIfNeeded;
- (void)pauseWatchVideoTask;
- (id)getFeedPendantLinkMonitorParams;
- (void)updateCapsuleWithText:(id)a0 activityTaskType:(long long)a1 andTimestamp:(double)a2;
- (void)performTaskCompleteLottieWithType:(unsigned long long)a0 completed:(id /* block */)a1;
- (void)showFirstTimingTaskBubbleIfNeeded;
- (void)showFirstTimingTaskPauseReasonBubbleIfNeeded;
- (void)trackFeedPendantResourceManagerLogWithMessage:(id)a0;
- (id)currentFeedContainerViewController;
- (long long)currentFeedType;
- (BOOL)checkIfCanShowPendant;
- (BOOL)fixTaskStopTiming;
- (void)pendantResourceDownloadNotify:(id)a0;
- (void)feedContainerDidDisappear;
- (void)pendantDraggingEndedNotify:(id)a0;
- (void)setupPendantResource;
- (void)checkPendantModelIfCertify:(id)a0;
- (void)setupPendantConfigModel;
- (void)setupPendantDrag;
- (void)setupPendantView;
- (void)setupEvadeControlService;
- (void)setupNotClickLimit;
- (void)checkFrequentLimitID;
- (id)frequentLimitID;
- (void)monitorMainResourceLoadStatus;
- (void)monitorAlphaVideoMainResourceLoadStatus;
- (void)updatePNGFoldContentUIFrame:(id)a0;
- (void)monitorTaskCompleteResourceLoadStatus;
- (void)pendantPlayFailed;
- (void)pendantContentClick;
- (void)pendantPlaySuccessfully;
- (void)pendantCloseClick;
- (void)recordGaiaCapsuleTextDebugInfo:(BOOL)a0 activityType:(long long)a1 description:(id)a2;
- (void)logEvadeControlType:(id)a0;
- (void)trackShowEventNew;
- (void)trackMaterialShowEvent;
- (void)addTokenToSlardarIfNeeded;
- (BOOL)checkIfInExemptPeriod;
- (void)showEnterLottieIfNeededCompleted:(id /* block */)a0;
- (void)addExpandFoldTask;
- (void)savePendantState;
- (void)configPendant;
- (void)handleWatchVideoTask;
- (void)setupTaskManager;
- (id)getFeedPendantLinkMonitorTargetParams;
- (void)monitorFeedPendantStageChangeEventWithCurrentParams:(id)a0 targetParams:(id)a1;
- (BOOL)shouldUpdatePendantWithModel:(id)a0;
- (BOOL)isSameCaptionWithNew:(id)a0 old:(id)a1;
- (void)trackFeedPendantActivityControllerLogWithMessage:(id)a0;
- (void)recordFrequencyControlDebugInfo:(BOOL)a0 description:(id)a1 currentTime:(double)a2 targetTime:(double)a3;
- (void)trackFeedPendantBeFrequencyLimited:(unsigned long long)a0 controlledZ:(long long)a1 controlledY:(long long)a2 controlledN:(long long)a3;
- (void)updatePendantStore;
- (void)pendantContentClickWithMonitor;
- (void)monitorService:(id)a0 status:(unsigned long long)a1 level:(unsigned long long)a2 error:(id)a3 extraInfo:(id)a4;
- (void)recordCloseAction;
- (void)showSideBarCaptionIfNeeded;
- (BOOL)isSameStringWithNew:(id)a0 old:(id)a1;
- (void)updatePendantResource;
- (void)trackFoldDragEvent;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frameOfPendantViewPNG;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frameOfPendantView;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frameOfExpandPendantCloseWithPendantFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frameOfFoldPendantCloseWithPendantFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (double)heightToStatusBar;
- (id)getCurrentAwemeModelItemID;
- (BOOL)homepageDecorationEnterFromFix;
- (void)recordPushCapsuleTextDebugInfo:(BOOL)a0 description:(id)a1;
- (void)monitorResourceLoadWithStatus:(unsigned long long)a0 withExtraParams:(id)a1;
- (void)showFirstCountdownBubbleIfNeeded;
- (void)setupWithConfigModel:(id)a0 resourceDelegate:(id)a1;
- (void)updataActivityMessageWith:(id)a0;
- (void)willBeCleared;
- (unsigned long long)getCurrentCapsuleStatus;
- (unsigned long long)getCurrentActivityType;
- (void)didScrollCountDown:(long long)a0 task:(id)a1;
- (void)handleCountdownTask;
- (void)willEnterForeground;
- (void).cxx_destruct;
- (void)didEnterBackground;
- (id)init;
- (void)dealloc;

@end
