@class UIView, NSString, UIImage, NSAttributedString, NSArray, UITextView, UIImageView, UITapGestureRecognizer, UIWindow, UILabel;

@interface AWEUIAlertView : UIView <IESIMAlertViewProtocol, AWEMRGlobalAlertTrackProtocol, AWEUIAlertViewLocationProtocol, ACCUIAlertViewProtocol, UIGestureRecognizerDelegate>

@property (nonatomic) double customCornerRadius;
@property (nonatomic) BOOL shouldShowIconImage;
@property (retain, nonatomic) UIImage *iconImage;
@property (nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } iconImageEdgeInsets;
@property (readonly, nonatomic) UIImageView *iconImageView;
@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSAttributedString *attributedTitle;
@property (readonly, nonatomic) UILabel *attributedLabel;
@property (copy, nonatomic) NSString *message;
@property (copy, nonatomic) NSAttributedString *attributedMessage;
@property (nonatomic) BOOL messageShouldAlignLeft;
@property (readonly, nonatomic) UITextView *descriptionTextView;
@property (copy, nonatomic) NSString *text;
@property (copy, nonatomic) NSAttributedString *attributedText;
@property (copy, nonatomic) id /* block */ handleBlock;
@property (copy, nonatomic) id /* block */ dismissBlock;
@property (nonatomic) BOOL dismissWhenTappedInBlankArea;
@property (readonly, nonatomic) NSArray *actions;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) UIImage *headerImage;
@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSAttributedString *attributedTitle;
@property (copy, nonatomic) NSString *message;
@property (copy, nonatomic) NSAttributedString *attributedMessage;
@property (nonatomic) double customCornerRadius;
@property (readonly, nonatomic) UITextView *descriptionTextView;
@property (nonatomic) BOOL dismissWhenTappedInBlankArea;
@property (nonatomic) BOOL isButtonAlignedVertically;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) long long style;
@property (nonatomic) double containerWidth;
@property (nonatomic) double containerMaxHeight;
@property (nonatomic) double textViewHorizatalInset;
@property (copy, nonatomic) NSArray *actions;
@property (retain, nonatomic) UIView *animationView;
@property (retain, nonatomic) UIView *backgroundView;
@property (retain, nonatomic) UIImageView *headerImageView;
@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UIImageView *iconImageView;
@property (retain, nonatomic) UITextView *descriptionTextView;
@property (retain, nonatomic) UILabel *attributedLabel;
@property (retain, nonatomic) UITapGestureRecognizer *tapGes;
@property (retain, nonatomic) UITapGestureRecognizer *tapToDismissGes;
@property (copy, nonatomic) NSArray *buttons;
@property (copy, nonatomic) NSArray *buttonTitles;
@property (weak, nonatomic) UIWindow *windowToShowAlert;
@property (readonly, nonatomic) BOOL useModernStyle;
@property (weak, nonatomic) UIView *viewToShowAlert;
@property (nonatomic) BOOL dismissWhenTappedInBlankArea;
@property (copy, nonatomic) id /* block */ dismissBlock;
@property (copy, nonatomic) id /* block */ dismissBlockWithoutCallCancelAction;
@property (copy, nonatomic) id /* block */ configUIBlock;
@property (nonatomic) BOOL useHtmlRender;
@property (nonatomic) double maxContentHeight;
@property (nonatomic) double customCornerRadius;
@property (retain, nonatomic) UIImage *headerImage;
@property (nonatomic) struct UIEdgeInsets { double top; double left; double bottom; double right; } headerImageEdgeInsets;
@property (nonatomic) long long closeButtonStyle;
@property (nonatomic) BOOL shouldShowIconImage;
@property (retain, nonatomic) UIImage *iconImage;
@property (nonatomic) struct UIEdgeInsets { double top; double left; double bottom; double right; } iconImageEdgeInsets;
@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSAttributedString *attributedTitle;
@property (copy, nonatomic) NSString *message;
@property (copy, nonatomic) NSAttributedString *attributedMessage;
@property (nonatomic) BOOL messageShouldAlignLeft;
@property (copy, nonatomic) NSString *text;
@property (copy, nonatomic) NSAttributedString *attributedText;
@property (copy, nonatomic) id /* block */ handleBlock;
@property (nonatomic) BOOL isButtonAlignedVertically;
@property (nonatomic) BOOL disableLocalizations;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)presentAwemeGuideAlertWithTitle:(id)a0 description:(id)a1 actionButtonTitle:(id)a2 cancelButtonTitle:(id)a3 actionBlock:(id /* block */)a4 cancelBlock:(id /* block */)a5;
+ (void)showAlertWithTitle:(id)a0 description:(id)a1 image:(id)a2 actionButtonTitle:(id)a3 cancelButtonTitle:(id)a4 actionBlock:(id /* block */)a5 cancelBlock:(id /* block */)a6 UIConfigBlock:(id /* block */)a7;
+ (void)showAlertWithTitle:(id)a0 description:(id)a1 image:(id)a2 actionButtonTitle:(id)a3 cancelButtonTitle:(id)a4 actionBlock:(id /* block */)a5 cancelBlock:(id /* block */)a6;
+ (BOOL)isSomeAlertShowing;
+ (id)alertViewWithStyle:(long long)a0;
+ (void)awe_showLocationRequestAlertWithResultBlock:(id /* block */)a0 cancelBlock:(id /* block */)a1 descriptionContent:(id)a2;
+ (void)awe_showLocationRequestAlertWithResultBlock:(id /* block */)a0 cancelBlock:(id /* block */)a1;
+ (void)messageReach_alertTrackerLoad;
+ (void)awe_showNearbyLocationRequestAlertWithResultBlock:(id /* block */)a0 cancelBlock:(id /* block */)a1;

- (id)messageReach_title;
- (void)messageReach_didAttachTracker;
- (void)loadSubviews;
- (void)dismissSelfDefineAlert;
- (id)initWithModernStyle:(BOOL)a0;
- (void)didTapAlertView:(id)a0;
- (void)p__showSelfDefineAlertWithAnimation;
- (void)loadSubviewsForModernStyle;
- (void)loadSubviewsForClassicStyle;
- (void)onAttributedLabelClicked:(id)a0;
- (void)onCloseButtonClicked:(id)a0;
- (id)adjustedActionsForActions:(id)a0 recommendedActionIndex:(long long *)a1;
- (void)findCancelActionAndExecute;
- (void)p__dismissSelfDefineAlertWithAnimation;
- (void)resetUIBeforeShowingForModernStyle;
- (void)resetUIBeforeShowingForClassicStyle;
- (id)initForShareTrendingHeaderImage:(id)a0;
- (void)addViewOverHeaderImageView:(id)a0;
- (void)setMr_didRegisterActionListener:(id)a0;
- (void)messageReach_show;
- (void)messageReach_p__dismissSelfDefineAlertWithAnimation;
- (id)mr_didRegisterActionListener;
- (void)messageReach_tapHandler;
- (void)messageReach_registerActionsListener;
- (void).cxx_destruct;
- (void)addAction:(id)a0;
- (id)init;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (void)show;
- (void)dismiss:(BOOL)a0;

@end
