@class NSString, UIImage, BDPUserItem, BDPUniqueID, UIImageView, NSDictionary, NSLayoutConstraint, UILabel;

@interface BDPFollowUserCard : UIView <BDPAppRouteChangeMessage>

@property (nonatomic) BOOL usingFirstClickResult;
@property (copy, nonatomic) NSString *enterFrom;
@property (copy, nonatomic) NSString *avatarUrl;
@property (copy, nonatomic) NSString *verifiedImageName;
@property (retain, nonatomic) UILabel *followLabel;
@property (retain, nonatomic) UILabel *nickNameLabel;
@property (retain, nonatomic) UILabel *descriptionLabel;
@property (retain, nonatomic) UIImage *avatarImage;
@property (retain, nonatomic) UIImage *verifiedImage;
@property (retain, nonatomic) UIImageView *closeCardView;
@property (retain, nonatomic) UIImageView *littleIconView;
@property (retain, nonatomic) UIImageView *avatarView;
@property (copy, nonatomic) NSDictionary *trackerEventDict;
@property (retain, nonatomic) BDPUniqueID *uniqueID;
@property (retain, nonatomic) NSLayoutConstraint *avatarTopConstraint;
@property (retain, nonatomic) NSLayoutConstraint *avatarLeftConstraint;
@property (retain, nonatomic) NSLayoutConstraint *followButtonRightConstraint;
@property (nonatomic) BOOL hiddenAsCommand;
@property (nonatomic) BOOL isFixed;
@property (nonatomic) BOOL isLivePreview;
@property (nonatomic) BOOL initallyFollowing;
@property (retain, nonatomic) BDPUserItem *userItem;
@property (nonatomic) double x;
@property (nonatomic) double y;
@property (nonatomic) double width;
@property (nonatomic) double height;
@property (nonatomic) double padding;
@property (nonatomic) long long pageID;
@property (copy, nonatomic) NSString *componentId;
@property (copy, nonatomic) NSString *userId;
@property (copy, nonatomic) NSString *secUserId;
@property (copy, nonatomic) NSString *awemeId;
@property (copy, nonatomic) NSString *nickName;
@property (copy, nonatomic) NSString *unfollowReason;
@property (copy, nonatomic) NSString *followStateString;
@property (nonatomic) long long followState;
@property (copy, nonatomic) NSString *expand;
@property (copy, nonatomic) id /* block */ BDPFollowCardCloseCallBack;
@property (copy, nonatomic) id /* block */ BDPFollowCardUpdateCallBack;
@property (copy, nonatomic) id /* block */ BDPFollowCardInsertCallBack;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)setUpDescriptionLabel;
- (void)getAvatarImageWithCompletion:(id /* block */)a0;
- (void)onAppRouteChangePageWithPageID:(long long)a0 pageURL:(id)a1 uniqueID:(id)a2;
- (void)setUpElements;
- (void)setUpFollowCardBase;
- (void)setUpAvatarImageView;
- (void)setUpFollowLabel;
- (void)setUpNicknameLabel;
- (void)setUpCloseCardView;
- (void)setLittleView;
- (void)updateFollowLabel;
- (void)getUserInfosIfNeededWithCompletion:(id /* block */)a0;
- (void)setUpShadow;
- (id)getGestureToOpenPersonalPage;
- (void)onTapNicknameOpenUserProfile:(id)a0;
- (void)onTapFollowUser:(id)a0;
- (void)onTapClose:(id)a0;
- (void)onTapAvatarOpenUserProfile:(id)a0;
- (void)followCardTrackerEventWithclickType:(id)a0 resultType:(id)a1;
- (void)onTapOpenUserProfileProcessFromAvatar:(BOOL)a0;
- (void)livePreviewTrackerWithClickType:(id)a0;
- (void)executeAfterFollowExpand:(id)a0 uniqueID:(id)a1 aweID:(id)a2 error:(id)a3;
- (id)getCommonParmsWithClick:(BOOL)a0 clickType:(id)a1;
- (id)initWithUserInfo:(id)a0 uniqueID:(id)a1;
- (void)updateFollowCardWithUserInfo:(id)a0;
- (void)followCardEventWithDestroy:(BOOL)a0 uniqueId:(id)a1;
- (void).cxx_destruct;
- (void)dealloc;

@end
