@class UIView, BDPAddShortcutGuideTimer, BDPOrientationGuideView, BDPOnlineTimeReporter, BDPVConsole, NSString, NSDictionary, BDPWKKryptonView, BDPStarkPage, BDPFloatingViewController_HG, BDPTimingEvent;
@protocol BDPToolBarViewProtocol, BDPLoadingViewProtocol;

@interface BDPStarkController : BDPBusinessXScreenViewController <BDPWarmBootMessage, BDPOnlineTimeReporterDelegate, BDPBootLifeCycleMessage, BDPAppInterfaceOrientationChangeMessage, BDPGamePrebootManagerMessage, BDPNativeGameBaseControllerProtocol> {
    BOOL _isGameFirstFrameDidDraw;
    BOOL _hasEnteredBg;
}

@property (retain, nonatomic) BDPStarkPage *starkPage;
@property (nonatomic) BOOL isPaused;
@property (nonatomic) BOOL didPostLaunchReady;
@property (weak, nonatomic) UIView<BDPToolBarViewProtocol> *toolBarView;
@property (retain, nonatomic) BDPOrientationGuideView *orientationGuideView;
@property (retain, nonatomic) BDPFloatingViewController_HG *floatingVC;
@property (retain, nonatomic) BDPAddShortcutGuideTimer *addShortcutGuideTimer;
@property (retain, nonatomic) UIView<BDPLoadingViewProtocol> *loadingView;
@property (nonatomic) BOOL disableOrientationFix;
@property (nonatomic) BOOL newOrientationDisable;
@property (retain, nonatomic) NSDictionary *enterPerformanceDict;
@property (retain, nonatomic) BDPWKKryptonView *kryptonView;
@property (retain, nonatomic) BDPVConsole *vConsole;
@property (retain, nonatomic) BDPTimingEvent *gameForegroundStayTiming;
@property (retain, nonatomic) BDPTimingEvent *gameBackgroundStayTiming;
@property (nonatomic) BOOL enableMetal;
@property (nonatomic) BOOL isAuthenticating;
@property (retain, nonatomic) BDPOnlineTimeReporter *timeReporter;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) double lastTapTime;
@property (nonatomic) BOOL isCompositeVideo;

+ (void)bootstrapLaunch;

- (void)onAppEnterBackground;
- (void)setupLoadingView;
- (void)applicationEnterBackGroundWithUniqueID:(id)a0;
- (void)applicationEnterForeGroundWithUniqueID:(id)a0;
- (void)applicationSCFirstFrameDidShow:(id)a0;
- (void)applicationWarmBootDoneWithUniqueID:(id)a0;
- (void)applicationWorkBeforeCloseWithUniqueID:(id)a0;
- (BOOL)isFeedGame;
- (void)cleanWarmCacheWithUniqueID:(id)a0;
- (void)interfaceOrientationChange:(id)a0 targetOrientation:(long long)a1 uniqueID:(id)a2;
- (void)startExceptionMonitor;
- (void)onAppEnterForeground;
- (BOOL)XScreenWindowShouldShowCustomButton:(id)a0;
- (BOOL)XScreenWindowShouldShowLeftCustomButton:(id)a0;
- (BOOL)canBeActive;
- (id)getOnAppEnterForegroundParams;
- (void)forceStopRunning;
- (unsigned long long)popGestureSwipeBackMode;
- (void)setupFloatingViewIfNeeded;
- (BOOL)XScreenWindow:(id)a0 recognizer:(id)a1 shouldReceiveTouch:(id)a2;
- (void)stopExceptionMonitor;
- (id)getCurrentGameView;
- (void)setupGameView;
- (id)paramForMemoryKill;
- (void)feedGameStatusChange:(unsigned long long)a0 uniqueID:(id)a1;
- (void)setGamePause:(BOOL)a0;
- (void)addRootNaviGestureDelegate;
- (void)removeRootNaviGestureDelegate;
- (void)onOrientationChange;
- (void)_showOrientationGuideViewWithOrientation:(long long)a0;
- (void)_hideOrientationGuideView;
- (void)onViewLongPressed:(id)a0;
- (void)windowBecomeKey:(id)a0;
- (void)startOnlineReportWithDelay:(long long)a0;
- (void)setGameViewPause:(BOOL)a0;
- (BOOL)shouldUseLandscape:(id)a0;
- (void)_showOrientationGuideViewIfNeed;
- (void)startOnlineReportInFeedGame;
- (void)pauseByOnlineTimeReporter;
- (void)resumeByOnlineTimeReporter;
- (void)closeByOnlineTimeReporter;
- (BOOL)useHighPerformancePlus;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })calculateKryptonViewRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (BOOL)enableNativeVConsole;
- (void)onBDPGameExit:(id)a0;
- (void)addKryptonView;
- (void)setGameActive:(BOOL)a0;
- (void)startOnlineReportIfNeed;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (BOOL)gestureRecognizer:(id)a0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)a1;
- (long long)preferredInterfaceOrientationForPresentation;
- (BOOL)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (BOOL)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(BOOL)a0;
- (BOOL)navigationBarHidden;
- (void)_showLoadingView;
- (id)initWithUniqueID:(id)a0;
- (void)hideLoadingView;

@end
