@class NSString, NSMutableDictionary, UIView;
@protocol LynxKeyListener;

@interface BDXLynxInput : LynxUI <UITextFieldDelegate, LynxFontFaceObserver>

@property (retain, nonatomic) NSMutableDictionary *placeholderAttributes;
@property (retain, nonatomic) NSString *placeHolderValue;
@property (nonatomic) BOOL autoHideKeyboard;
@property (nonatomic) BOOL smartScroll;
@property (readonly, nonatomic) BOOL firstScreenLayoutDidFinished;
@property (readonly, nonatomic) BOOL shouldFocusAfterLayout;
@property (nonatomic) long long maxLength;
@property (nonatomic) BOOL readonly;
@property (nonatomic) BOOL mIsChangeFromLynx;
@property (retain, nonatomic) NSString *mFilterPattern;
@property (retain, nonatomic) NSString *mAdjustMode;
@property (nonatomic) BOOL mAutoFit;
@property (nonatomic) double mBottomInset;
@property (nonatomic) double mKeyboardHeight;
@property (nonatomic) long long mInputType;
@property (retain, nonatomic) id<LynxKeyListener> mKeyListener;
@property (nonatomic) double mLetterSpacing;
@property (nonatomic) double mFontSize;
@property (nonatomic) double mFontWeight;
@property (nonatomic) double mPlaceholderFontSize;
@property (nonatomic) double mPlaceholderFontWeight;
@property (nonatomic) BOOL mPlaceholderUseCustomFontSize;
@property (nonatomic) BOOL mPlaceholderUseCustomFontWeight;
@property (readonly, nonatomic) double textHeight;
@property (readonly, nonatomic) BOOL mCompatNumberType;
@property (readonly, nonatomic) BOOL mSendComposingInputEvent;
@property (readonly, nonatomic) NSString *mFontFamilyName;
@property (readonly, nonatomic) NSString *mPlaceholderFontFamilyName;
@property (readonly, nonatomic) BOOL mPlaceholderUseCustomFontFamily;
@property (readonly, nonatomic) BOOL fontStyleChanged;
@property (readonly, nonatomic) BOOL placeholderFontStyleChanged;
@property (readonly, nonatomic) long long sourceLength;
@property (retain, nonatomic) UIView *mInputAccessoryView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)__lynx_ui_method_config__5361;
+ (id)__lynx_ui_method_config__5432;
+ (id)__lynx_prop_config__5613;
+ (id)__lynx_prop_config__6004;
+ (id)__lynx_ui_method_config__6195;
+ (id)__lynx_ui_method_config__6486;
+ (id)__lynx_prop_config__6967;
+ (id)__lynx_prop_config__7428;
+ (id)__lynx_prop_config__7509;
+ (id)__lynx_prop_config__76610;
+ (id)__lynx_prop_config__78111;
+ (id)__lynx_prop_config__78912;
+ (id)__lynx_prop_config__79713;
+ (id)__lynx_prop_config__80514;
+ (id)__lynx_prop_config__81315;
+ (id)__lynx_prop_config__83116;
+ (id)__lynx_prop_config__84517;
+ (id)__lynx_prop_config__85918;
+ (id)__lynx_prop_config__87319;
+ (id)__lynx_prop_config__88820;
+ (id)__lynx_prop_config__90321;
+ (id)__lynx_prop_config__93622;
+ (id)__lynx_prop_config__100623;
+ (id)__lynx_prop_config__102224;
+ (id)__lynx_prop_config__103025;
+ (id)__lynx_prop_config__103826;
+ (id)__lynx_prop_config__104627;
+ (id)__lynx_prop_config__105428;
+ (id)__lynx_prop_config__106229;
+ (id)__lynx_prop_config__107030;
+ (id)__lynx_ui_method_config__109131;
+ (id)__lynx_prop_config__111332;
+ (id)__lynx_prop_config__112233;
+ (id)__lynx_ui_method_config__113634;
+ (id)__lynx_ui_method_config__114335;
+ (id)__lynx_ui_method_config__121736;
+ (id)__lynx_ui_method_config__122537;
+ (id)__lynx_ui_method_config__123738;
+ (id)__lynx_prop_config__125039;
+ (id)__lynx_prop_config__126340;
+ (id)__lynx_prop_config__127641;
+ (id)__lynx_prop_config__129742;

- (void)layoutDidFinished;
- (void)updateFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 withPadding:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a1 border:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a2 margin:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a3 withLayoutAnimation:(BOOL)a4;
- (void)propsDidUpdate;
- (void)onListCellDisappear:(id)a0 exist:(BOOL)a1 withList:(id)a2;
- (void)setFontSize:(double)a0 requestReset:(BOOL)a1;
- (void)updateFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 withPadding:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a1 border:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a2 withLayoutAnimation:(BOOL)a3;
- (void)onListCellPrepareForReuse:(id)a0 withList:(id)a1;
- (void)onListCellAppear:(id)a0 withList:(id)a1;
- (void)setLynxDirection:(unsigned long long)a0 requestReset:(BOOL)a1;
- (void)setCaretColor:(id)a0 requestReset:(BOOL)a1;
- (void)setFontWeight:(unsigned long long)a0 requestReset:(BOOL)a1;
- (void)emitEvent:(id)a0 detail:(id)a1;
- (void)onWillShowKeyboard:(id)a0;
- (void)onWillHideKeyboard:(id)a0;
- (void)addText:(id)a0 withResult:(id /* block */)a1;
- (void)onFontFaceLoad;
- (void)setColor:(id)a0 requestReset:(BOOL)a1;
- (void)setLetterSpacing:(double)a0 requestReset:(BOOL)a1;
- (void)setFontFamily:(id)a0 requestReset:(BOOL)a1;
- (void)setTextAlign:(unsigned long long)a0 requestReset:(BOOL)a1;
- (void)setFont;
- (void)setPlaceholderFont;
- (void)onWillShowKeyboardChanged:(BOOL)a0 notification:(id)a1;
- (void)updateScrollView:(id)a0 showKeyboard:(BOOL)a1 diff:(double)a2 bottomInset:(double)a3 userInfo:(id)a4;
- (void)setValue:(id)a0 index:(id)a1 callback:(id /* block */)a2;
- (double)convertFontWeightToUIFontWeight:(unsigned long long)a0;
- (void)setInputTextDirection;
- (void)syncPlaceHolderDirection;
- (void)applyCompatNumberType;
- (void)setInputFilter:(id)a0 withResult:(id /* block */)a1;
- (void)setValue:(id)a0 withResult:(id /* block */)a1;
- (void)setTextValue:(id)a0 requestReset:(BOOL)a1;
- (void)setShowSoftInputOnFocus:(BOOL)a0 requestReset:(BOOL)a1;
- (void)sendDelEvent:(id)a0 withResult:(id /* block */)a1;
- (void)setType:(id)a0 requestReset:(BOOL)a1;
- (void)setPassword:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolder:(id)a0 requestReset:(BOOL)a1;
- (void)setDisabled:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setMaxLen:(int)a0 requestReset:(BOOL)a1;
- (void)setReadOnly:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolderColor:(id)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolderFamily:(id)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolderFont:(id)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolderWeight:(id)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolderStyle:(id)a0 requestReset:(BOOL)a1;
- (void)setFocus:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setAutoHideKeyboard:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setSmartScroll:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setAdjustMode:(id)a0 requestReset:(BOOL)a1;
- (void)setAutoFit:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setBottomInset:(id)a0 requestReset:(BOOL)a1;
- (void)setConfirmType:(id)a0 requestReset:(BOOL)a1;
- (void)resetSelectionMenu:(id)a0 withResult:(id /* block */)a1;
- (void)select:(id)a0 withResult:(id /* block */)a1;
- (void)setSelectionRange:(id)a0 withResult:(id /* block */)a1;
- (void)focus:(id)a0 withResult:(id /* block */)a1;
- (void)blur:(id)a0 withResult:(id /* block */)a1;
- (void)getSelection:(id)a0 withResult:(id /* block */)a1;
- (void)setEnableAutoCorrect:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setEnableSpellCheck:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setCompatNumberType:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setSendComposingInputEvent:(BOOL)a0 requestReset:(BOOL)a1;
- (void).cxx_destruct;
- (BOOL)textFieldShouldEndEditing:(id)a0;
- (BOOL)textFieldShouldReturn:(id)a0;
- (id)init;
- (void)textFieldDidEndEditing:(id)a0;
- (BOOL)textFieldShouldBeginEditing:(id)a0;
- (void)textFieldDidBeginEditing:(id)a0;
- (BOOL)textField:(id)a0 shouldChangeCharactersInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1 replacementString:(id)a2;
- (void)dealloc;
- (void)delete:(id)a0;
- (void)textFieldDidChange:(id)a0;
- (void)insertChild:(id)a0 atIndex:(long long)a1;
- (id)createView;
- (void)frameDidChange;

@end
