@class NSString, NSDictionary, UIView;
@protocol BDXLynxInputEmojiFormater;

@interface BDXLynxTextArea : LynxUI <UITextViewDelegate, LynxFontFaceObserver> {
    BOOL _firstScreenLayoutDidFinished;
    BOOL _shouldFocusAfterLayout;
}

@property (nonatomic) BOOL smartScroll;
@property (nonatomic) long long maxLength;
@property (nonatomic) BOOL readonly;
@property (readonly, nonatomic) BOOL multiline;
@property (readonly, nonatomic) double textHeight;
@property (retain, nonatomic) NSString *adjustMode;
@property (nonatomic) BOOL mIsChangeFromLynx;
@property (retain, nonatomic) NSString *mFilterPattern;
@property (retain, nonatomic) NSString *mAdjustMode;
@property (nonatomic) BOOL mAutoFit;
@property (nonatomic) double mBottomInset;
@property (nonatomic) double mKeyboardHeight;
@property (nonatomic) BOOL autoHeightInputNeedSmartScroll;
@property (copy, nonatomic) NSDictionary *currentUserInfo;
@property (nonatomic) double mLetterSpacing;
@property (nonatomic) double mFontSize;
@property (nonatomic) double mFontWeight;
@property (readonly, nonatomic) BOOL mEnterShouldConfirm;
@property (readonly, nonatomic) double mWidth;
@property (readonly, nonatomic) double mHeight;
@property (retain, nonatomic) id<BDXLynxInputEmojiFormater> richTextFormater;
@property (readonly, nonatomic) BOOL mSendComposingInputEvent;
@property (readonly, nonatomic) NSString *mFontFamilyName;
@property (readonly, nonatomic) BOOL fontStyleChanged;
@property (readonly, nonatomic) BOOL placeholderFontStyleChanged;
@property (retain, nonatomic) UIView *mInputAccessoryView;
@property (readonly, nonatomic) long long maxLines;
@property (readonly, nonatomic) long long sourceLength;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)lynxLazyLoad;
+ (id)__lynx_ui_method_config__4331;
+ (id)__lynx_prop_config__4642;
+ (id)__lynx_prop_config__4803;
+ (id)__lynx_prop_config__4994;
+ (id)__lynx_prop_config__5085;
+ (id)__lynx_prop_config__5166;
+ (id)__lynx_prop_config__5247;
+ (id)__lynx_prop_config__5328;
+ (id)__lynx_prop_config__5409;
+ (id)__lynx_prop_config__54810;
+ (id)__lynx_prop_config__56211;
+ (id)__lynx_prop_config__57612;
+ (id)__lynx_prop_config__59113;
+ (id)__lynx_prop_config__60414;
+ (id)__lynx_prop_config__61915;
+ (id)__lynx_prop_config__65416;
+ (id)__lynx_prop_config__67117;
+ (id)__lynx_prop_config__74318;
+ (id)__lynx_prop_config__75919;
+ (id)__lynx_ui_method_config__76720;
+ (id)__lynx_prop_config__78521;
+ (id)__lynx_ui_method_config__80422;
+ (id)__lynx_ui_method_config__82823;
+ (id)__lynx_ui_method_config__87524;
+ (id)__lynx_prop_config__89725;
+ (id)__lynx_prop_config__90526;
+ (id)__lynx_prop_config__91327;
+ (id)__lynx_prop_config__92128;
+ (id)__lynx_prop_config__92929;
+ (id)__lynx_prop_config__95030;
+ (id)__lynx_prop_config__97131;
+ (id)__lynx_prop_config__99932;
+ (id)__lynx_ui_method_config__101233;
+ (id)__lynx_ui_method_config__101934;
+ (id)__lynx_ui_method_config__104635;
+ (id)__lynx_ui_method_config__105436;
+ (id)__lynx_ui_method_config__106637;
+ (id)__lynx_prop_config__107938;
+ (id)__lynx_prop_config__109239;
+ (id)__lynx_prop_config__110540;
+ (id)__lynx_prop_config__111341;
+ (id)__lynx_prop_config__113542;

- (void)layoutDidFinished;
- (void)propsDidUpdate;
- (void)setFontSize:(double)a0 requestReset:(BOOL)a1;
- (BOOL)updateLayerMaskOnFrameChanged;
- (void)setLynxDirection:(unsigned long long)a0 requestReset:(BOOL)a1;
- (void)setCaretColor:(id)a0 requestReset:(BOOL)a1;
- (void)setFontWeight:(unsigned long long)a0 requestReset:(BOOL)a1;
- (void)emitEvent:(id)a0 detail:(id)a1;
- (void)onWillShowKeyboard:(id)a0;
- (void)onWillHideKeyboard:(id)a0;
- (void)applyAutoHeight;
- (void)addText:(id)a0 withResult:(id /* block */)a1;
- (void)setRichType:(id)a0 requestReset:(BOOL)a1;
- (void)onFontFaceLoad;
- (void)setColor:(id)a0 requestReset:(BOOL)a1;
- (void)setLetterSpacing:(double)a0 requestReset:(BOOL)a1;
- (void)setFontFamily:(id)a0 requestReset:(BOOL)a1;
- (void)setTextAlign:(unsigned long long)a0 requestReset:(BOOL)a1;
- (void)setFont;
- (void)updateScrollView:(id)a0 showKeyboard:(BOOL)a1 diff:(double)a2 bottomInset:(double)a3 userInfo:(id)a4;
- (void)setValue:(id)a0 index:(id)a1 callback:(id /* block */)a2;
- (double)convertFontWeightToUIFontWeight:(unsigned long long)a0;
- (void)setInputTextDirection;
- (void)setInputFilter:(id)a0 withResult:(id /* block */)a1;
- (void)setValue:(id)a0 withResult:(id /* block */)a1;
- (void)setShowSoftInputOnFocus:(BOOL)a0 requestReset:(BOOL)a1;
- (void)sendDelEvent:(id)a0 withResult:(id /* block */)a1;
- (void)setType:(id)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolder:(id)a0 requestReset:(BOOL)a1;
- (void)setDisabled:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setMaxLen:(int)a0 requestReset:(BOOL)a1;
- (void)setReadOnly:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolderColor:(id)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolderFont:(id)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolderWeight:(id)a0 requestReset:(BOOL)a1;
- (void)setPlaceHolderStyle:(id)a0 requestReset:(BOOL)a1;
- (void)setFocus:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setSmartScroll:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setAdjustMode:(id)a0 requestReset:(BOOL)a1;
- (void)setAutoFit:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setBottomInset:(id)a0 requestReset:(BOOL)a1;
- (void)setConfirmType:(id)a0 requestReset:(BOOL)a1;
- (void)resetSelectionMenu:(id)a0 withResult:(id /* block */)a1;
- (void)select:(id)a0 withResult:(id /* block */)a1;
- (void)setSelectionRange:(id)a0 withResult:(id /* block */)a1;
- (void)focus:(id)a0 withResult:(id /* block */)a1;
- (void)blur:(id)a0 withResult:(id /* block */)a1;
- (void)getSelection:(id)a0 withResult:(id /* block */)a1;
- (void)setEnableAutoCorrect:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setEnableSpellCheck:(BOOL)a0 requestReset:(BOOL)a1;
- (void)setSendComposingInputEvent:(BOOL)a0 requestReset:(BOOL)a1;
- (void)onWillShowKeyboardChanged:(BOOL)a0 userInfo:(id)a1;
- (void)textViewLineEvent:(id)a0;
- (id)getContentWithLimitedLines:(id)a0 lines:(long long)a1 source:(id)a2 dest:(id)a3 dStart:(long long)a4 dEnd:(long long)a5 index:(long long *)a6 constraints:(struct CGSize { double x0; double x1; })a7;
- (void)setValue:(id)a0 requestReset:(BOOL)a1;
- (void)setMaxLines:(int)a0 requestReset:(BOOL)a1;
- (void)setPlaceholderFontFamily:(id)a0 requestReset:(BOOL)a1;
- (void)setConfirmEnter:(BOOL)a0 requestReset:(BOOL)a1;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (void)scrollRectToVisible:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)textViewDidBeginEditing:(id)a0;
- (BOOL)textViewShouldBeginEditing:(id)a0;
- (void)textViewDidEndEditing:(id)a0;
- (void)textViewDidChange:(id)a0;
- (BOOL)textView:(id)a0 shouldChangeTextInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1 replacementText:(id)a2;
- (void)insertChild:(id)a0 atIndex:(long long)a1;
- (id)createView;
- (void)frameDidChange;

@end
