@class UIScreenEdgePanGestureRecognizer, NSString, UIView, BDXContext, NSURL, BDXProtocolMethodMatcher, BDXSchemaParam, NSMutableArray, _TtC6AnnieX19AnnieXPageViewModel, NSNumber;
@protocol AnnieXContainerBaseProtocol, BDXLoadingViewProtocol, BDXPageDelegate, BDXNavigationBarProtocol, BDXKitViewProtocol, BDXPoolContainerDelegate, BDXPageSchemaParamProtocol, BDXContainerLifecycleProtocol, AnnieXUIServiceProtocol;

@interface BDXViewController : UIViewController <BDXBridgeSetContainerProtocol, AWEUGMatryoshkaDollPushViewControllerCheckProtocol, UIGestureRecognizerDelegate, BDXBridgeCloseProtocol, BDXBridgeReloadProtocol, BDXBridgeSetSideslipMethod, BDXPageContainerProtocol, BDXPoolContainerProtocol, BDXContainerLifecycleProtocol, BDXTopLevelProtocol> {
    NSNumber *_topLevelEnable;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL showingKeyboard;
@property (nonatomic) double topOffset;
@property (nonatomic) long long originStatusBarStyle;
@property (nonatomic) BOOL originNavigationBarHidden;
@property (nonatomic) BOOL originNavigationBarIsHidden;
@property (nonatomic) BOOL shouldResetNavigationBar;
@property (nonatomic) BOOL statusBarHiddenStatus;
@property (nonatomic) BOOL hasExecuteDidAppearedOnce;
@property (nonatomic) BOOL isAppearing;
@property (retain, nonatomic) UIView<AnnieXContainerBaseProtocol> *viewContainer;
@property (retain, nonatomic) UIView *pageView;
@property (retain, nonatomic) NSMutableArray *containerReadyBlockList;
@property (nonatomic) BOOL preControllerPopGestureRecongnizerEnabled;
@property (retain, nonatomic) BDXProtocolMethodMatcher *containerProtocolMatcher;
@property (retain, nonatomic) BDXProtocolMethodMatcher *poolProtocolMatcher;
@property (retain, nonatomic) UIScreenEdgePanGestureRecognizer *blockBackGesture;
@property (retain, nonatomic) UIScreenEdgePanGestureRecognizer *webBackGesture;
@property (retain, nonatomic) UIView *loadFailedView;
@property (retain, nonatomic) UIView<BDXLoadingViewProtocol> *loadingView;
@property (nonatomic) BOOL isDestorying;
@property (retain, nonatomic) _TtC6AnnieX19AnnieXPageViewModel *viewModel;
@property (retain, nonatomic) NSNumber *enableAnnieXSL;
@property (nonatomic) BOOL layoutDuetoTransition;
@property (nonatomic) BOOL isContainerReady;
@property (retain, nonatomic) BDXSchemaParam<BDXPageSchemaParamProtocol> *config;
@property (nonatomic) unsigned long long appearanceState;
@property (retain, nonatomic) UIView<BDXNavigationBarProtocol> *navigationBar;
@property (retain, nonatomic) UIView *statusBar;
@property (nonatomic) long long statusBarStyle;
@property (nonatomic) BOOL shouldFullScreen;
@property (nonatomic) BOOL hideStatusBar;
@property (retain, nonatomic) id<AnnieXUIServiceProtocol> uiService;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL popupIsPresenting;
@property (nonatomic) BOOL popupIsDismissing;
@property (weak, nonatomic) id<BDXPageDelegate> pageDelegate;
@property (readonly, nonatomic) long long viewType;
@property (retain, nonatomic) BDXContext *context;
@property (nonatomic) BOOL hybridInBackground;
@property (nonatomic) BOOL pageVisiable;
@property (nonatomic) BOOL disableNativeClose;
@property (weak, nonatomic) id<BDXContainerLifecycleProtocol> containerLifecycleDelegate;
@property (nonatomic) BOOL didMount;
@property (readonly, copy, nonatomic) NSString *sessionID;
@property (readonly, nonatomic) NSURL *originURL;
@property (readonly, nonatomic) struct CGSize { double width; double height; } preferredLayoutSize;
@property (readonly, copy, nonatomic) NSString *containerID;
@property (readonly, nonatomic) UIView<BDXKitViewProtocol> *kitView;
@property (readonly, copy, nonatomic) NSString *engineType;
@property (nonatomic) long long loadStatus;
@property (nonatomic) BOOL hybridAppeared;
@property (weak, nonatomic) id<BDXPoolContainerDelegate> poolContainerDelegate;

+ (void)_aweLazyRegisterStaticLoad_TaskAdapter;

- (void)container:(id)a0 didFinishLoadWithURL:(id)a1;
- (void)container:(id)a0 didLoadFailedWithUrl:(id)a1 error:(id)a2;
- (BOOL)container:(id)a0 shouldStartLoadWithRequest:(id)a1 navigationType:(id)a2;
- (void)containerDidStartLoading:(id)a0;
- (void)container:(id)a0 didStartLoadingSuccessWithUrl:(id)a1;
- (void)container:(id)a0 didFetchedResource:(id)a1 error:(id)a2;
- (void)containerDidFirstScreen:(id)a0;
- (void)container:(id)a0 updateTitle:(id)a1;
- (void)containerDidNavigatedStateChanged:(id)a0;
- (void)container:(id)a0 onKeyBoardChange:(id)a1 eventType:(unsigned long long)a2;
- (void)dismissWithAnimated:(BOOL)a0 completion:(id /* block */)a1;
- (BOOL)transition_enableCustomActionForSlideDirection:(unsigned long long)a0 gestureRecognizer:(id)a1;
- (void)transition_performCustomActionForSlideDirection:(unsigned long long)a0 gestureRecognizer:(id)a1;
- (void)setBdxpool_status:(unsigned long long)a0;
- (void)setStatusBarBackgroundColor:(id)a0;
- (void)refreshCurrentPage;
- (void)registerXBridgeMethod:(id)a0;
- (id)schemaParams;
- (void)updateStatusBarStatus:(long long)a0;
- (BOOL)close:(id)a0 completion:(id /* block */)a1;
- (void)handleViewDidAppear;
- (void)handleBecomeActive;
- (void)handleResignActive;
- (id)viewControllerOfContainer;
- (id)getViewContainer;
- (void)removeKitView;
- (void)resetKitView;
- (void)handleViewDidAppearOnlyPage;
- (void)handleViewDidDisappearOnlyPage;
- (id)engineView;
- (id)cardModel;
- (void)loadWithURL:(id)a0 context:(id)a1;
- (id)findViewWithName:(id)a0;
- (void)dismissLoadingView;
- (id)initWithRequestURL:(id)a0 config:(id)a1 context:(id)a2;
- (BOOL)shouldPageInternalBack;
- (void)disableSwipInteractivePopeGesture:(BOOL)a0;
- (id)hmdPageExtension;
- (void)setTopLevelEnable:(id)a0;
- (id)topLevelEnable;
- (void)bdx_closeWithAnimated:(BOOL)a0 completion:(id /* block */)a1;
- (BOOL)disableSwipe;
- (id)slAnnieXMonitor;
- (void)bdx_setDisableNativeClose:(BOOL)a0;
- (void)bdx_updateTitle:(id)a0;
- (void)bdx_updateTitleColor:(id)a0;
- (void)bdx_updateNavgationBarBackgroundColor:(id)a0;
- (void)bdx_updateStatusBarBackgroundColor:(id)a0;
- (void)bdx_updateStatusBarMode:(long long)a0;
- (void)bdx_updateStatusBarHide:(BOOL)a0;
- (void)bdx_setAllBounces:(BOOL)a0;
- (void)bdx_setDisableBackPress:(BOOL)a0;
- (void)bdx_setDisableSwipe:(BOOL)a0;
- (void)bdx_setupFullScreen:(BOOL)a0;
- (BOOL)bdx_shouldUseCustomClose;
- (void)bdx_jsbReloadView;
- (void)disableFullScreenPop:(BOOL)a0;
- (struct CGSize { double x0; double x1; })ipadContainerSize;
- (void)setupIpadConfig;
- (void)__addLoadingViewIfNeeded;
- (BOOL)__isCachedViewAlreadLoad;
- (void)handleErrorViewReload:(id)a0;
- (void)handleXBridgeHideLoadingMethod;
- (id)lifeCycleTracker;
- (void)__onBanReuse:(id)a0;
- (void)layoutPadContainer;
- (void)__close:(BOOL)a0 completion:(id /* block */)a1;
- (BOOL)isWebView;
- (id)curUserAgent;
- (id)p_getContainerLifecycleDelegate;
- (BOOL)p_useSLAnnieX;
- (id)__defaultConatinerBackgroundColor;
- (void)p_initialAnnieXNavigationbar;
- (void)__setupLoadingBackgroundColor;
- (void)setupViewContainerBgColor;
- (void)p_setupAddKeyboardObserver;
- (void)appThemeDidChange:(id)a0;
- (void)__layoutViewContainer;
- (BOOL)p_shouldUseAnnieXCard;
- (void)enableSystemScreenEdgePanGesture:(BOOL)a0;
- (void)__setupBlockBackGesture;
- (void)__updateStatusBarStatus;
- (BOOL)_hasPopUpViewController;
- (void)__resetLeftPanPop;
- (void)__resetNavigationBarStyle;
- (BOOL)_viewControllerIsClosing;
- (BOOL)__statusBarExist;
- (void)sendBecomeActiveEvent;
- (void)blockBackAction:(id)a0;
- (void)__updateStatusBarStatusWithMode:(long long)a0;
- (double)calOffset;
- (void)addLoadFailedView:(id)a0 errorType:(long long)a1;
- (void)__setupBackgroundColor;
- (void)__updateNavBarButtons;
- (void)updateContainerViewLayout;
- (id)getContainerLightDarkBgColor;
- (double)getViewContainerLeftRightMargin;
- (BOOL)useAnnieXNavigationBar;
- (void)depracted_updateRightButtonType:(long long)a0;
- (BOOL)isEqualToViewController:(id)a0;
- (BOOL)removeOldBeforePushNew;
- (void)aweug_ViewDidAppear:(BOOL)a0;
- (void)aweug_ViewDidDisappear:(BOOL)a0;
- (void)aweug_ReloadWithContext:(id)a0;
- (id)sceneForUrlString:(id)a0;
- (void)loadURL:(id)a0;
- (void).cxx_destruct;
- (void)viewSafeAreaInsetsDidChange;
- (id)childViewControllerForStatusBarStyle;
- (void)viewDidLayoutSubviews;
- (void)reload;
- (BOOL)close:(id)a0;
- (BOOL)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (BOOL)shouldAutorotate;
- (void)goBack;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillAppear:(BOOL)a0;
- (void)scrollViewDidScroll:(id)a0;
- (BOOL)respondsToSelector:(SEL)a0;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })a0 withTransitionCoordinator:(id)a1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (id)forwardingTargetForSelector:(SEL)a0;
- (void)dealloc;
- (double)topMargin;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)reloadWithContext:(id)a0;
- (void)updateTitle:(id)a0;
- (void)handleViewDidDisappear;

@end
