@class NSString, NSDictionary, NSPredicate, NSArray, NSNumber, CAKAlbumListTabConfig;

@interface CAKAlbumListViewConfig : NSObject

@property (nonatomic) BOOL enableSearch;
@property (retain, nonatomic) NSPredicate *searchFilterPredicate;
@property (retain, nonatomic) NSDictionary *searchCommandTrackInfo;
@property (retain, nonatomic) CAKAlbumListTabConfig *mixedAssetsTabConfig;
@property (retain, nonatomic) CAKAlbumListTabConfig *photoAssetsTabConfig;
@property (retain, nonatomic) CAKAlbumListTabConfig *videoAssetsTabConfig;
@property (retain, nonatomic) CAKAlbumListTabConfig *livePhotoAssetsTabConfig;
@property (nonatomic) BOOL enableRecommend;
@property (retain, nonatomic) CAKAlbumListTabConfig *recommendAssetsTabConfig;
@property (retain, nonatomic) NSString *recommendTabTitle;
@property (retain, nonatomic) NSString *recommendText;
@property (retain, nonatomic) NSArray *recommendKeyWords;
@property (nonatomic) long long recommendType;
@property (nonatomic) long long recommendEnterFrom;
@property (nonatomic) BOOL enableCustomCellAlwaysAction;
@property (nonatomic) BOOL enableTabView;
@property (copy, nonatomic) NSNumber *adjustTabSelectionLineWidthWithTitle;
@property (nonatomic) BOOL enableScaleIconAdjust;
@property (nonatomic) BOOL enableAssetsRepeatedSelect;
@property (nonatomic) BOOL addAssetInOrder;
@property (nonatomic) BOOL enableMixedUpload;
@property (nonatomic) long long assetsSortStyle;
@property (nonatomic) BOOL enableiOS14AlbumAuthorizationGuide;
@property (nonatomic) BOOL shouldShowiOS14GoSettingStrip;
@property (nonatomic) BOOL enableAlbumAuthorizationDenyAccessGuide;
@property (nonatomic) BOOL reverseData;
@property (nonatomic) double horizontalInset;
@property (nonatomic) long long columnNumber;
@property (nonatomic) unsigned long long assetsSelectedIconStyle;
@property (nonatomic) BOOL scrollToBottom;
@property (nonatomic) BOOL searchListdateAscending;
@property (nonatomic) BOOL disablePreviewPresentOptimize;
@property (nonatomic) unsigned long long selectionLimitType;
@property (nonatomic) BOOL withoutCountLimitation;
@property (nonatomic) long long maxAssetsSelectionCount;
@property (nonatomic) long long minAssetsSelectionCount;
@property (nonatomic) long long maxVideoAssetsSelectionCount;
@property (nonatomic) long long minVideoAssetsSelectionCount;
@property (nonatomic) long long maxPhotoAssetsSelectionCount;
@property (nonatomic) long long minPhotoAssetsSelectionCount;
@property (nonatomic) double videoSelectableMinSeconds;
@property (nonatomic) double videoSelectableMaxSeconds;
@property (nonatomic) struct CGSize { double width; double height; } aspectRatio;
@property (nonatomic) NSString *defaultTabIdentifier;
@property (copy, nonatomic) NSArray *initialSelectedAssetModelArray;
@property (nonatomic) BOOL enableDisplayFavoriteSymbol;
@property (nonatomic) BOOL enableSyncInitialSelectedAssets;
@property (nonatomic) BOOL enableHorizontalAssetBlackEdge;
@property (nonatomic) BOOL shouldDismissPreviewPageWhenNext;
@property (nonatomic) BOOL previewNextNeverDisabled;
@property (nonatomic) long long colorTheme;
@property (nonatomic) BOOL enableMultithreadOpt;
@property (nonatomic) BOOL enableBatchUpdateOpt;
@property (nonatomic) struct CGAffineTransform { double a; double b; double c; double d; double tx; double ty; } selectedTransformScale;
@property (nonatomic) BOOL shouldSwapPreviewAndSelect;
@property (nonatomic) BOOL enableShowPreviewCheckMarkButton;
@property (nonatomic) BOOL enableSearchPageShowPreviewCheckMarkButton;
@property (nonatomic) BOOL enablePrviewDidSelectItemStatus;
@property (nonatomic) BOOL enableVideoPreviewPlayControl;
@property (nonatomic) BOOL canCleanVideoPreviewFullScreen;
@property (copy, nonatomic) NSDictionary *previewPageCommonParams;
@property (nonatomic) struct CGSize { double width; double height; } selectionLineSize;
@property (nonatomic) double selectionLineBottomOffset;
@property (nonatomic) double selectionLineCornerRadius;
@property (nonatomic) BOOL enableSelectedPreload;
@property (nonatomic) BOOL enableSafeBottom;
@property (nonatomic) BOOL disableScrollAssetToVisiable;
@property (copy, nonatomic) id /* block */ configControllerTracker;
@property (copy, nonatomic) id /* block */ configCellStartTracker;
@property (copy, nonatomic) id /* block */ configCellEndTracker;
@property (nonatomic) unsigned long long assetsOrder;

- (void).cxx_destruct;
- (id)init;

@end
