@class UIView, NSString, XPlayScreenOn, CGCloudPlayerInfo, XPlayQualityStatsModel, CGCloudPlayerStatsModel, CGPerformanceMonitor, CGDataChannel, CGObject, UIViewController, CGExtensionManager, CGXCloudPlayerControllerNativeWrapper;
@protocol CGRTCSEIMessageDelegate, XPlayStreamingParametersControllerProtocol, XPlayRenderProtocol, CGRTCRoom, XPlayCloudPlayerDelegate, XPlayAudioCapture, CGNetworkMonitor, XPlayDelayMonitor, XPlaySettingsBool, CGLoadTimeMonitor, XPlayScreenRecordProtocol, XPlayAudioPuller, CGCloudPermission, XPlayKeyboardProtocol, CGMessageSDK, CGCloudPlayerDelegate, CGItem, XPlayCloudMessageProtocol;

@interface CGCloudPlayer : NSObject <CGRTCRoomDelegate, CGLoadTimeMonitorDelegate, XPlayCloudPlayerProtocol, CGCloudPlayer> {
    id<XPlayRenderProtocol> render;
    id<XPlayAudioPuller> audioPuller;
    id<XPlayAudioCapture> audioCapture;
    CGObject<CGRTCSEIMessageDelegate, XPlayDelayMonitor> *delayDetectMonitor;
    id<XPlayStreamingParametersControllerProtocol> resolution;
}

@property (weak, nonatomic) id<CGItem> item;
@property (retain, nonatomic) CGCloudPlayerInfo *info;
@property (retain, nonatomic) id<CGRTCRoom> room;
@property (retain, nonatomic) CGDataChannel *dataChannel;
@property (retain, nonatomic) UIView *view;
@property (retain, nonatomic) UIViewController *controller;
@property (nonatomic) BOOL didPlay;
@property (nonatomic) BOOL isPlaying;
@property (nonatomic) BOOL didLoadSuccess;
@property (retain, nonatomic) XPlayScreenOn *screenOn;
@property (retain, nonatomic) CGExtensionManager *extensionManager;
@property (retain, nonatomic) CGCloudPlayerStatsModel *playerStats;
@property (nonatomic) unsigned long long status;
@property (nonatomic) BOOL needResumeWhenBecomeActive;
@property (nonatomic) BOOL isMute;
@property (retain, nonatomic) id<XPlaySettingsBool> disableUpdateStatusToPauseBeforeBegin;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<XPlayCloudPlayerDelegate> delegate;
@property (readonly, nonatomic) id<XPlayAudioCapture> audioCapture;
@property (readonly, nonatomic) id<XPlayAudioPuller> audioPuller;
@property (readonly, nonatomic) id<XPlayRenderProtocol> render;
@property (readonly, nonatomic) id<XPlayStreamingParametersControllerProtocol> resolution;
@property (readonly, nonatomic) id<XPlayDelayMonitor> delayDetectMonitor;
@property (readonly, copy, nonatomic) NSString *name;
@property (readonly, nonatomic) CGXCloudPlayerControllerNativeWrapper *cloudPlayerControllerNativeWrapper;
@property (readonly, nonatomic) XPlayQualityStatsModel *qualityStats;
@property (readonly, nonatomic) BOOL isMain;
@property (retain, nonatomic) id<CGMessageSDK> messageSDK;
@property (retain, nonatomic) id<CGCloudPermission> cloudPermission;
@property (retain, nonatomic) CGPerformanceMonitor *performaceMonitor;
@property (retain, nonatomic) id<CGNetworkMonitor> networkDetect;
@property (retain, nonatomic) id<CGLoadTimeMonitor> loadTimeMonitor;
@property (retain, nonatomic) id<XPlayKeyboardProtocol> keyboard;
@property (retain, nonatomic) id<XPlayCloudMessageProtocol> customMessage;
@property (retain, nonatomic) id<XPlayCloudMessageProtocol> matchedCustomMessage;
@property (retain, nonatomic) id<XPlayScreenRecordProtocol> screenRecorder;
@property (weak, nonatomic) id<CGCloudPlayerDelegate> cloudPlayerDelegate;

- (void)setAudioCapture:(id)a0;
- (void)setupCellularEnhancement:(id)a0 completion:(id /* block */)a1;
- (id)initWithDeprecatedEngine:(id)a0 item:(id)a1 cloudPlayerInfo:(id)a2;
- (void)stopVideoStreamAndQuitRoomFrom:(id)a0;
- (void)stopGame;
- (void)loadTimeoutWithType:(long long)a0;
- (void)setDelayDetectMonitor:(id)a0;
- (void)setAudioPuller:(id)a0;
- (void)onRemoteVideoSizeChanged:(id)a0 uid:(id)a1;
- (void)onRemoteVideoStateChanged:(long long)a0 withVideoStateReason:(long long)a1 uid:(id)a2;
- (void)onUserJoinedWithUid:(id)a0;
- (void)onUserLeave:(long long)a0 uid:(id)a1;
- (void)onRemoteStreamStats:(id)a0;
- (void)onRoomStats:(id)a0;
- (void)onEngineErrorWithCode:(long long)a0 room:(id)a1;
- (void)onFirstRemoteVideoFrameDecoded:(id)a0 uid:(id)a1 room:(id)a2;
- (void)onFirstRemoteVideoFrameRendered:(id)a0 uid:(id)a1 room:(id)a2;
- (void)onUserPublishStreamVideo:(BOOL)a0 uid:(id)a1 room:(id)a2;
- (void)onUserPublishStreamAudio:(BOOL)a0 uid:(id)a1 room:(id)a2;
- (void)onRoomStateChanged:(long long)a0 uid:(id)a1 reason:(long long)a2 originalErrorCode:(long long)a3;
- (void)onAudioFrame:(id)a0;
- (void)forceOffline:(id)a0;
- (void)forceOfflineBinary:(id)a0;
- (void)statusWillUpdate:(unsigned long long)a0 info:(id)a1;
- (void)pauseAtBeginIfNeeded;
- (void)sendExitRoomCommand;
- (void)rtcError:(long long)a0;
- (void)remoteLeaveRoom:(long long)a0 uid:(id)a1;
- (id)formatByteRTCAudioFrame:(id)a0;
- (void)internalAudioPullerEnabled:(BOOL)a0;
- (int)switchRemoteSimulcastStreamTypeWithIndex:(int)a0;
- (void)disableGestureRecognizer:(BOOL)a0;
- (void)setRTCRuntimeParameters:(id)a0;
- (void)onVideoFrame:(id)a0;
- (void)setResolution:(id)a0;
- (void).cxx_destruct;
- (void)play;
- (void)pause;
- (void)stop;
- (void)_applicationDidBecomeActive:(id)a0;
- (void)startAudioCapture;
- (void)setVolume:(int)a0;
- (void)preload;
- (void)_applicationWillResignActive:(id)a0;
- (void)resume;
- (void)dealloc;
- (void)focus;
- (void)stopAudioCapture;
- (void)_applicationWillTerminate;
- (void)setMute:(BOOL)a0;
- (void)loadSuccess;
- (void)setRender:(id)a0;

@end
