@class CSJWKWebViewClient, NSURL, NSDate, NSDictionary, BUWebViewProgressView, CSJCustomNavigationBarView, NSMutableArray, CSJWebViewBottomBar, UIView, CSJASlotContext, NSString, CSJAdSlot, UIViewController, BUTimer, NSError, CSJDislikeContext;
@protocol CSJAd;

@interface CSJWebViewControllerViewModel : NSObject <WKScriptMessageHandler, UIViewControllerTransitioningDelegate, WKUIDelegate, CSJCustomNavigationBarDelegate, BUWebViewDelegate>

@property (nonatomic) BOOL isLuban;
@property (copy, nonatomic) NSDictionary *luban_json;
@property (copy, nonatomic) id /* block */ loadLubanJsonFail;
@property (retain, nonatomic) NSMutableArray *luban_product_ids;
@property (retain, nonatomic) NSDate *startdate;
@property (nonatomic) long long currentStatus;
@property (nonatomic) long long backgroundStatus;
@property (nonatomic) long long js_max_scroll_percent;
@property (nonatomic) BOOL isTrackLoad_Finish;
@property (nonatomic) BOOL isTrackLoad_result;
@property (nonatomic) BOOL isFirstLoad_start;
@property (retain, nonatomic) NSError *loadFailError;
@property (nonatomic) BOOL isLoadingAndClose;
@property (retain, nonatomic) CSJDislikeContext *dislikeContext;
@property (copy, nonatomic) NSString *stashCid;
@property (copy, nonatomic) NSString *stashLogExtra;
@property (nonatomic) BOOL isBackground;
@property (nonatomic) BOOL isAppear;
@property (nonatomic) long long heartBeatOverTime;
@property (copy, nonatomic) id /* block */ heartBeatCallback;
@property (retain, nonatomic) BUTimer *heartBeatTimer;
@property (nonatomic) BOOL observingHeartBeat;
@property (retain, nonatomic) UIView *csj_maskView;
@property (nonatomic) BOOL enableBrowseTimer;
@property (retain, nonatomic) BUTimer *browseTimer;
@property (nonatomic) long long browseTime;
@property (nonatomic) BOOL needRecoverFullLinkTimer;
@property (nonatomic) struct CGSize { double width; double height; } size;
@property (retain, nonatomic) CSJCustomNavigationBarView *customNavigationView;
@property (retain, nonatomic) CSJWebViewBottomBar *bottomBar;
@property (nonatomic) BOOL isNavBarHidden;
@property (retain, nonatomic) BUWebViewProgressView *progressView;
@property (nonatomic) BOOL hasEnterBackground;
@property (nonatomic) BOOL needReportClick;
@property (retain, nonatomic) CSJWKWebViewClient *webView;
@property (readonly, nonatomic) id<CSJAd> adInfo;
@property (retain, nonatomic) CSJAdSlot *adSlot;
@property (copy, nonatomic) NSString *webTitle;
@property (nonatomic) BOOL isHiddenProgress;
@property (copy, nonatomic) id /* block */ CloseBlock;
@property (retain, nonatomic) NSURL *requestURL;
@property (nonatomic, getter=isSupportAlert) BOOL supportAlert;
@property (nonatomic) BOOL hasTerminateTrack;
@property (retain, nonatomic) NSDictionary *relatedMaterialMeta;
@property (copy, nonatomic) NSString *createExtraString;
@property (copy, nonatomic) id /* block */ hasLoadLubanListPage;
@property (nonatomic) unsigned long long landingPageType;
@property (nonatomic) BOOL isFromClick;
@property (nonatomic) unsigned long long pageType;
@property (weak, nonatomic) CSJASlotContext *context;
@property (copy, nonatomic) id /* block */ downloadDidCloseStoreController;
@property (copy) NSDictionary *session_params;
@property (weak, nonatomic) UIView *view;
@property (weak, nonatomic) UIViewController *parentVC;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)handleViewDidAppear:(BOOL)a0;
- (void)handleViewDidDisappear:(BOOL)a0;
- (id)fetchHookConsoleLog;
- (void)registerJSBridge3;
- (id)buJSB3_adInfoWithViewModel:(id)a0;
- (id)buJSB3_getMaterialMetaWithViewModel:(id)a0;
- (id)trackTag;
- (id)initWithRequestURL:(id)a0 adinfo:(id)a1 size:(struct CGSize { double x0; double x1; })a2 isNavBarHidden:(BOOL)a3 landingPageType:(unsigned long long)a4 isFromClick:(BOOL)a5;
- (BOOL)enableBrowseForReward;
- (id)initWithRequestURL:(id)a0 adinfo:(id)a1 size:(struct CGSize { double x0; double x1; })a2 isNavBarHidden:(BOOL)a3;
- (BOOL)isOverseaLPNewStyle;
- (BOOL)useLandingPageNewStyle;
- (void)addAccessibilityIdentifier;
- (void)handleViewWillAppear:(BOOL)a0;
- (void)handleViewWillLayoutSubviews;
- (void)appDidEnterBackgroundNotification:(id)a0;
- (id)getTrackTag;
- (void)appWillEnterForegroundNotification:(id)a0;
- (void)trackLoading;
- (void)jsCallNative_commonConvertWithParams:(id)a0;
- (void)openInternalStoreWithMaterial:(id)a0;
- (void)goClose:(id)a0;
- (BOOL)isRealPlayablePage;
- (void)customNavigationBarDidClickCloseButton:(id)a0;
- (void)customNavigationBarDidClickDislikeButton:(id)a0;
- (void)handleTapWithInfo:(id)a0;
- (id)buJSB3_commonConvertWithViewModel:(id)a0;
- (void)sendTrackDataWithParameters:(id)a0;
- (id)jsCallNative_getTeMaiAds;
- (void)jsCallNative_send_temai_product_idsWithParams:(id)a0;
- (id)buJSB3_getTeMaiAdsWithViewModel:(id)a0;
- (id)buJSB3_send_temai_product_idsWithViewModel:(id)a0;
- (id)buJSB3_getNetworkDataWithViewModel:(id)a0;
- (double)getRewardInterval;
- (void)onRewardTimerOut;
- (id)_renderDict;
- (id)durationFromStartDate;
- (void)setFinishdate:(id)a0;
- (id)showdate;
- (id)durationFromFinishShowDate;
- (void)setShowdate:(id)a0;
- (void)setEnterForegrounddate:(id)a0;
- (id)finishdate;
- (id)enterForegrounddate;
- (id)durationFromFinishDate;
- (id)durationFromEnterForegroundDate;
- (void)configLubanInfoWithURL:(id)a0;
- (void)preloadWebViewAndData;
- (void)buildRelatedMaterialMeta;
- (void)trackOpenWithTag:(id)a0;
- (id)jsCallNative_adInfo;
- (void)jsCallNative_sendLogWithParams:(id)a0;
- (id)jsCallNative_getMaterialMeta;
- (id)jsCallNative_getNativeSiteCustomData;
- (void)jsCallNative_close;
- (void)jsCallNative_openAdLandPageLinksWithParams:(id)a0;
- (id)jsCallNative_download_app_adWithParams:(id)a0;
- (id)jsCallNative_click_button;
- (void)receiveH5HeartBeat:(id)a0;
- (id)pbu_urlWithString:(id)a0;
- (void)openWebViewNewPageWithUrl:(id)a0;
- (void)goClose;
- (void)startNewHeartBeatTime;
- (void)trackCloseWith:(long long)a0 tag:(id)a1;
- (void)stopHeartBeatTime;
- (void)stopBrowseTimer;
- (void)creatNavigationItems;
- (void)createBottomBar;
- (void)_onPanGR:(id)a0;
- (void)hiddenCloseButton;
- (void)registerJSBridgePlugin;
- (void)registerLubanJSBridgePlugin;
- (void)preloadLubanData;
- (void)onRewardTimerUpdate:(long long)a0;
- (void)buildCustormNavigationViewFrame;
- (void)buildBottomBarFrame;
- (void)buildWebviewFrame;
- (void)trackShow;
- (void)startBrowseTimer;
- (void)registShowConsole;
- (void)addScriptMessageHandleForName:(id)a0;
- (double)webview_y;
- (BOOL)getOfflineSwitch;
- (void)registerUserAgent;
- (void)_onGoBackButton;
- (void)_onGoForwardButton;
- (void)_onReloadButton;
- (void)_onSafariButton;
- (BOOL)handleScrollPercentWith:(id)a0;
- (BOOL)handleTaptWith:(id)a0;
- (BOOL)bu_shouldStartLoadWithRequestWithURL:(id)a0;
- (BOOL)p_handleAppStoreRequest:(id)a0;
- (void)trackLoadStartWith:(long long)a0 tag:(id)a1;
- (void)registJS_ScrollPercent;
- (void)trackLoadFinishWithTag:(id)a0;
- (void)registJSPerformance;
- (void)trackLoadFailWithError:(id)a0 tag:(id)a1;
- (id)origUA;
- (id)sdkUA;
- (void)onBrowseTimerUpdate;
- (void)onHeartBeatTimerOut;
- (void)trackStayWithTag:(id)a0;
- (void)trackEnterForeground;
- (void)dislikeButtonTapped:(id)a0;
- (void)goback:(id)a0;
- (id)webClickTrack;
- (void)customNavigationBarDidClickBackButton:(id)a0;
- (id)initWithRequestURL:(id)a0 adinfo:(id)a1 size:(struct CGSize { double x0; double x1; })a2 isNavBarHidden:(BOOL)a3 landingPageType:(unsigned long long)a4;
- (id)buJSB3_getATTStatusWithViewModel:(id)a0;
- (id)buJSB3_click_buttonWithViewModel:(id)a0;
- (id)buJSB3_sendLogWithViewModel:(id)a0;
- (id)buJSB3_openAdLandPageLinksWithViewModel:(id)a0;
- (id)buJSB3_getNativeSiteCustomDataWithViewModel:(id)a0;
- (id)buJSB3_closeWithViewModel:(id)a0;
- (id)buJSB3_adInfoStashWithViewModel:(id)a0;
- (id)buJSB3_download_app_adWithViewModel:(id)a0;
- (id)buJSB3_heart_beatWithViewModel:(id)a0;
- (void)bu_loadRequest:(id)a0;
- (void)handleViewWillDisappear:(BOOL)a0;
- (void)handleDidReceiveMemoryWarning;
- (void)registJS_Tap;
- (void)observeHeartBeatWithOverTime:(long long)a0 callback:(id /* block */)a1;
- (void)cancelObserveHeartBeat;
- (void)responseViewFirstClick:(struct BUWebViewClickStruct { struct CGPoint { double x0; double x1; } x0; id x1; })a0;
- (void)responseViewClick:(struct BUWebViewClickStruct { struct CGPoint { double x0; double x1; } x0; id x1; })a0;
- (void)responseViewDidScroll:(struct BUWebViewClickStruct { struct CGPoint { double x0; double x1; } x0; id x1; })a0 offset:(struct CGPoint { double x0; double x1; })a1;
- (void)webViewWebContentProcessDidTerminate:(id)a0;
- (void).cxx_destruct;
- (id)animationControllerForPresentedController:(id)a0 presentingController:(id)a1 sourceController:(id)a2;
- (void)handleError:(id)a0;
- (id)animationControllerForDismissedController:(id)a0;
- (id)webView:(id)a0 createWebViewWithConfiguration:(id)a1 forNavigationAction:(id)a2 windowFeatures:(id)a3;
- (void)scrollViewDidScroll:(id)a0;
- (void)webView:(id)a0 runJavaScriptAlertPanelWithMessage:(id)a1 initiatedByFrame:(id)a2 completionHandler:(id /* block */)a3;
- (void)webView:(id)a0 runJavaScriptConfirmPanelWithMessage:(id)a1 initiatedByFrame:(id)a2 completionHandler:(id /* block */)a3;
- (void)observeValueForKeyPath:(id)a0 ofObject:(id)a1 change:(id)a2 context:(void *)a3;
- (void)dealloc;
- (BOOL)shouldTrack;
- (void)webView:(id)a0 didFailLoadWithError:(id)a1;
- (BOOL)webView:(id)a0 shouldStartLoadWithRequest:(id)a1 navigationType:(long long)a2;
- (void)webViewDidStartLoad:(id)a0;
- (void)webViewDidFinishLoad:(id)a0;
- (BOOL)useCache;
- (double)_bottomBarHeight;
- (void)userContentController:(id)a0 didReceiveScriptMessage:(id)a1;
- (void)showCloseButton;
- (void)handleViewDidLoad;
- (void)createWebView;

@end
