@class NSData, NSString, NSURL, EAGCDAsyncReadPacket, EAGCDAsyncSocketPreBuffer, NSObject, NSMutableArray, EAGCDAsyncWritePacket;
@protocol GCDAsyncSocketDelegate, OS_dispatch_queue, OS_dispatch_source;

@interface EAccountGCDAsyncSocket : NSObject {
    unsigned int flags;
    unsigned short config;
    id<GCDAsyncSocketDelegate> delegate;
    NSObject<OS_dispatch_queue> *delegateQueue;
    int socket4FD;
    int socket6FD;
    int socketUN;
    NSURL *socketUrl;
    int stateIndex;
    NSData *connectInterface4;
    NSData *connectInterface6;
    NSData *connectInterfaceUN;
    NSObject<OS_dispatch_queue> *socketQueue;
    NSObject<OS_dispatch_source> *accept4Source;
    NSObject<OS_dispatch_source> *accept6Source;
    NSObject<OS_dispatch_source> *acceptUNSource;
    NSObject<OS_dispatch_source> *connectTimer;
    NSObject<OS_dispatch_source> *readSource;
    NSObject<OS_dispatch_source> *writeSource;
    NSObject<OS_dispatch_source> *readTimer;
    NSObject<OS_dispatch_source> *writeTimer;
    NSMutableArray *readQueue;
    NSMutableArray *writeQueue;
    EAGCDAsyncReadPacket *currentRead;
    EAGCDAsyncWritePacket *currentWrite;
    unsigned long long socketFDBytesAvailable;
    EAGCDAsyncSocketPreBuffer *preBuffer;
    struct { long long version; void *info; void /* function */ *retain; void /* function */ *release; void /* function */ *copyDescription; } streamContext;
    struct __CFReadStream { } *readStream;
    struct __CFWriteStream { } *writeStream;
    struct SSLContext { } *sslContext;
    EAGCDAsyncSocketPreBuffer *sslPreBuffer;
    unsigned long long sslWriteCachedLength;
    int sslErrCode;
    int lastSSLHandshakeError;
    double alternateAddressDelay;
    void *IsOnSocketQueueOrTargetQueueKey;
}

@property (weak) id<GCDAsyncSocketDelegate> delegate;
@property (retain) NSObject<OS_dispatch_queue> *delegateQueue;
@property (getter=isIPv4Enabled) BOOL IPv4Enabled;
@property (getter=isIPv6Enabled) BOOL IPv6Enabled;
@property (getter=isIPv4PreferredOverIPv6) BOOL IPv4PreferredOverIPv6;
@property (readonly) BOOL isDisconnected;
@property (readonly) BOOL isConnected;
@property (readonly) NSString *connectedHost;
@property (readonly) unsigned short connectedPort;
@property (readonly) BOOL isIPv4;
@property (readonly) BOOL isIPv6;
@property (readonly) BOOL isSecure;

+ (void)ignore:(id)a0;
+ (void)cfstreamThread;
+ (void)scheduleCFStreams:(id)a0;
+ (void)unscheduleCFStreams:(id)a0;
+ (id)gaiError:(int)a0;
+ (void)startCFStreamThreadIfNeeded;
+ (void)stopCFStreamThreadIfNeeded;
+ (id)lookupHost:(id)a0 port:(unsigned short)a1 error:(id *)a2;
+ (id)hostFromSockaddr4:(const struct sockaddr_in { unsigned char x0; unsigned char x1; unsigned short x2; struct in_addr { unsigned int x0; } x3; char x4[8]; } *)a0;
+ (id)hostFromSockaddr6:(const struct sockaddr_in6 { unsigned char x0; unsigned char x1; unsigned short x2; unsigned int x3; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x4; unsigned int x5; } *)a0;
+ (unsigned short)portFromSockaddr4:(const struct sockaddr_in { unsigned char x0; unsigned char x1; unsigned short x2; struct in_addr { unsigned int x0; } x3; char x4[8]; } *)a0;
+ (unsigned short)portFromSockaddr6:(const struct sockaddr_in6 { unsigned char x0; unsigned char x1; unsigned short x2; unsigned int x3; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x4; unsigned int x5; } *)a0;
+ (unsigned short)portFromAddress:(id)a0;
+ (BOOL)isIPv4Address:(id)a0;
+ (BOOL)isIPv6Address:(id)a0;
+ (BOOL)getHost:(id *)a0 port:(unsigned short *)a1 fromAddress:(id)a2;
+ (BOOL)getHost:(id *)a0 port:(unsigned short *)a1 family:(char *)a2 fromAddress:(id)a3;

- (BOOL)bindSocket:(int)a0 toInterface:(id)a1 error:(id *)a2;
- (void)closeSocket:(int)a0;
- (void)closeUnusedSocket:(int)a0;
- (int)createSocket:(int)a0 connectInterface:(id)a1 errPtr:(id *)a2;
- (void)connectSocket:(int)a0 address:(id)a1 stateIndex:(int)a2;
- (double)alternateAddressDelay;
- (void)setAlternateAddressDelay:(double)a0;
- (void)closeWithError:(id)a0;
- (void).cxx_destruct;
- (void)disconnect;
- (id)initWithDelegate:(id)a0 delegateQueue:(id)a1;
- (void)dealloc;
- (int)socketFD;
- (id)initWithDelegate:(id)a0 delegateQueue:(id)a1 socketQueue:(id)a2;
- (void)setDelegate:(id)a0 synchronously:(BOOL)a1;
- (void)setDelegateQueue:(id)a0 synchronously:(BOOL)a1;
- (void)setDelegate:(id)a0 delegateQueue:(id)a1 synchronously:(BOOL)a2;
- (void)setDelegate:(id)a0 delegateQueue:(id)a1;
- (BOOL)preConnectWithInterface:(id)a0 error:(id *)a1;
- (BOOL)connectToHost:(id)a0 onPort:(unsigned short)a1 error:(id *)a2;
- (BOOL)connectToHost:(id)a0 onPort:(unsigned short)a1 withTimeout:(double)a2 error:(id *)a3;
- (BOOL)connectToHost:(id)a0 onPort:(unsigned short)a1 viaInterface:(id)a2 withTimeout:(double)a3 error:(id *)a4;
- (void)lookup:(int)a0 didSucceedWithAddress4:(id)a1 address6:(id)a2;
- (void)lookup:(int)a0 didFail:(id)a1;
- (BOOL)connectWithAddress4:(id)a0 address6:(id)a1 error:(id *)a2;
- (void)didConnect:(int)a0;
- (void)didNotConnect:(int)a0 error:(id)a1;
- (void)startConnectTimeout:(double)a0;
- (void)endConnectTimeout;
- (void)doConnectTimeout;
- (id)badConfigError:(id)a0;
- (id)badParamError:(id)a0;
- (id)errnoErrorWithReason:(id)a0;
- (id)errnoError;
- (id)sslError:(int)a0;
- (id)connectTimeoutError;
- (id)readMaxedOutError;
- (id)readTimeoutError;
- (id)writeTimeoutError;
- (id)connectionClosedError;
- (id)otherError:(id)a0;
- (id)connectedHost4;
- (id)connectedHost6;
- (unsigned short)connectedPort4;
- (unsigned short)connectedPort6;
- (id)connectedHostFromSocket4:(int)a0;
- (id)connectedHostFromSocket6:(int)a0;
- (unsigned short)connectedPortFromSocket4:(int)a0;
- (unsigned short)connectedPortFromSocket6:(int)a0;
- (void)getInterfaceAddress4:(id *)a0 address6:(id *)a1 fromDescription:(id)a2 port:(unsigned short)a3;
- (void)setupReadAndWriteSourcesForNewlyConnectedSocket:(int)a0;
- (BOOL)usingCFStreamForTLS;
- (BOOL)usingSecureTransportForTLS;
- (void)suspendReadSource;
- (void)resumeReadSource;
- (void)suspendWriteSource;
- (void)resumeWriteSource;
- (void)readDataToLength:(unsigned long long)a0 withTimeout:(double)a1 tag:(long long)a2;
- (void)readDataToLength:(unsigned long long)a0 withTimeout:(double)a1 buffer:(id)a2 bufferOffset:(unsigned long long)a3 tag:(long long)a4;
- (void)readDataToData:(id)a0 withTimeout:(double)a1 tag:(long long)a2;
- (void)readDataToData:(id)a0 withTimeout:(double)a1 buffer:(id)a2 bufferOffset:(unsigned long long)a3 maxLength:(unsigned long long)a4 tag:(long long)a5;
- (void)maybeDequeueRead;
- (void)flushSSLBuffers;
- (void)doReadData;
- (void)doReadEOF;
- (void)completeCurrentRead;
- (void)endCurrentRead;
- (void)setupReadTimerWithTimeout:(double)a0;
- (void)doReadTimeout;
- (void)doReadTimeoutWithExtension:(double)a0;
- (void)writeData:(id)a0 withTimeout:(double)a1 tag:(long long)a2;
- (void)maybeDequeueWrite;
- (void)doWriteData;
- (void)completeCurrentWrite;
- (void)endCurrentWrite;
- (void)setupWriteTimerWithTimeout:(double)a0;
- (void)doWriteTimeout;
- (void)doWriteTimeoutWithExtension:(double)a0;
- (void)startTLS:(id)a0;
- (void)maybeStartTLS;
- (int)sslReadWithBuffer:(void *)a0 length:(unsigned long long *)a1;
- (int)sslWriteWithBuffer:(const void *)a0 length:(unsigned long long *)a1;
- (void)ssl_startTLS;
- (void)ssl_continueSSLHandshake;
- (void)ssl_shouldTrustPeer:(BOOL)a0 stateIndex:(int)a1;
- (void)cf_finishSSLHandshake;
- (void)cf_abortSSLHandshake:(id)a0;
- (void)cf_startTLS;
- (BOOL)createReadAndWriteStream;
- (BOOL)registerForStreamCallbacksIncludingReadWrite:(BOOL)a0;
- (BOOL)addStreamsToRunLoop;
- (void)removeStreamsFromRunLoop;
- (BOOL)openStreams;
- (int)socket4FD;
- (int)socket6FD;
- (struct __CFReadStream { } *)readStream;
- (struct __CFWriteStream { } *)writeStream;
- (struct SSLContext { } *)sslContext;

@end
