@class GPBInt64ObjectDictionary, HTSLiveOfficialChannelInfo, HTSLiveClientComponent, HTSLiveAvatarLiveInfo, HTSLiveActivityRoomSkinInfo, IESLiveCircleInfo, HTSLiveGameCPData, NSMutableDictionary, HTSLiveRoomRevenueData, HTSLiveEcomData, HTSLiveToolBarData, HTSLiveOfficialChannelExtraInfo, GPBStringInt64Dictionary, HTSLivePackMetaInfo, HTSLiveRoomActivityTag, HTSLiveBonus, HTSLiveActivityData, HTSLiveCornerMarkReach, HTSLiveHotRoomInfo, HTSLiveAudioBGData, HTSLiveLabelInfo, HTSLivePublicScreenBottomInfo, HTSLiveLifeGrouponInfo, HTSLiveRoomViewStats, HTSLiveUnionLiveInfo, GPBInt64Array, HTSLiveEpisodeExtraInfo, HTSLiveStreamUrl, HTSLiveIndustryServiceInfo, HTSLiveRoomPlatformComponentsData, HTSLiveRoomGameData, IESLiveEnterPreviewHandler, HTSLiveBorderInfo, IESLivePreloadRequestControl, HTSLiveDesireInfo, HTSLiveGamePlayData, HTSLiveCommentWallPosition, NSDate, HTSLiveShareResource, HTSLiveVSCameraInfo, HTSLiveRoomUserAttr, HTSLiveRoomAnchorData, HTSLiveAnnouncementInfo, HTSLiveBeautifyInfo, HTSLiveLinkMic, HTSLiveOpenContentData, HTSLiveUser, HTSLiveMemberMessage, HTSLiveLikeDisplayConfig, HTSLiveShortTouchAuth, HTSLiveRoomReplayInfo, HTSLiveTVStation, OfficialRoomInfo, HTSLiveRoomAuthStatus, NSString, HTSLiveVipData, NSError, HTSLiveRelevantRecommendation, HTSLiveRoomSpecificSceneTypeInfo, HTSLiveLinkerUsers, HTSLivePaidLiveData, IOSClientComponent, HTSLiveCommentWallInfo, HTSLiveLinkerDetail, NSMutableArray, NSNumber, HTSLivePreviewExposeData, HTSLiveCastScreenData, HTSLiveEnterPublicAreaAnimation, ConnectPage, HTSLiveRoomExtra, HTSLiveRoomFeedData, ListCategoryResponse_CategoryNode, HTSLiveRoomChannelData, HTSLiveFeedbackCard, HTSLiveMatchInfo, GPBEnumArray, HTSLiveVerticalTypeInfo, HTSLiveRoomBasisData, HTSLiveQuizExtra, HTSLiveCommentaryRoomInfo, HTSLiveAnchorTabLabel, HTSLiveActivityLiveRecommendConfig, HTSLiveRoomIMInfo, NSDictionary, HTSLiveRoomCart, NSArray, HTSLiveRoomReqUserData, HTSLiveLiveStatusInfo, HTSLiveEasterEggData, HTSLiveRoomOthersData, HTSLivePicoInfo, HTSLiveRoomHealthScoreInfo, HTSLiveAppearance, HTSLiveRoomShortTouchAreaConfig, HTSEventContext, HTSLiveWelfareProjectInfo, RoomPublicScreenInfo, HTSLiveEpisode, HTSLiveRoomUserInfoModel, HTSLiveVSPremiereToast, HTSLiveRoomInteractData, HTSLiveBurstInfo, HTSLiveMatchChatConfig, HTSLiveMatchRoomData, HTSLiveRoomStats, HTSLiveCommentBox, HTSLiveGameExtra, HTSLiveImage, IESLiveChannelInviteModel, HTSLiveInteractOpenExtra;
@protocol IESLiveDIContext;

@interface HTSLiveRoom : IESLivePBBaseMessage <IESLiveGPBMessageInstaller, IESLiveRoomVendorProtocol, IESLiveRoomSocialProtocol, IESLiveRoomShowProtocol, IESLiveRoomService, IESliveEnterRoomData, IESLiveRoomFoundationProtocol, HTSLiveModelTrackProtocol, IESLiveRoomCommunityProtocol, IGListDiffable, AWEShareLiveRoomModelProtocol>

@property (copy, nonatomic) id /* block */ preloadStreamCompletion;
@property (copy, nonatomic) id /* block */ enterCompletion;
@property (nonatomic) BOOL loadVCAfterSchemaPreview;
@property (retain, nonatomic) NSError *enterApiError;
@property (retain, nonatomic) IESLivePreloadRequestControl *preloadRequestControl;
@property (readonly, nonatomic) IESLiveEnterPreviewHandler *enterPreviewHandler;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSString *currentMainCameraMatchID;
@property (retain, nonatomic) GPBInt64Array *currentMainCameraEventIds;
@property (readonly, nonatomic) BOOL isUnionLiveRoom;
@property (readonly, copy, nonatomic) NSString *cameraTypeTrackStr;
@property (nonatomic) BOOL vsHasAppointmentTag;
@property (nonatomic) BOOL vsIsInnerFromDrawer;
@property (readonly, nonatomic) NSNumber *currentGroupID;
@property (nonatomic) long long degradeLevel;
@property (nonatomic) BOOL enableSeek;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSMutableArray *tabsItemsWithDeleteHiddenTabs;
@property (readonly, nonatomic) BOOL isTemplateVerticalStream;
@property (readonly, nonatomic) BOOL isVSOrMediaMixRoom;
@property (readonly, nonatomic) HTSLiveEpisodeExtraInfo *vsComponentExtraInfo;
@property (retain, nonatomic) RoomPublicScreenInfo *publicScreenPlatformInfo;
@property (retain, nonatomic) HTSLiveVSCameraInfo *roomSubCamera;
@property (readonly, nonatomic) HTSLiveVSCameraInfo *currentCamera;
@property (retain, nonatomic) NSArray *allCameraInfosArray;
@property (readonly, nonatomic) NSString *currentCameraID;
@property (readonly, nonatomic) NSNumber *currentGroupID;
@property (readonly, nonatomic) NSNumber *currentContentID;
@property (readonly, nonatomic) int currentCameraType;
@property (retain, nonatomic) NSNumber *currentMainCameraContentID;
@property (readonly, copy, nonatomic) NSString *cameraTypeTrackStr;
@property (readonly, nonatomic) BOOL hasMultiCameraData;
@property (nonatomic) BOOL hasPaidCameraData;
@property (readonly, nonatomic) BOOL isMainCamera;
@property (copy, nonatomic) NSString *cameraFromFeedIDStr;
@property (retain, nonatomic) NSNumber *vsType;
@property (retain, nonatomic) HTSLiveEpisode *episode;
@property (readonly, nonatomic) NSNumber *vsRoomType;
@property (readonly, nonatomic) BOOL isVSRoom;
@property (readonly, nonatomic) BOOL isVSRoom_Live;
@property (readonly, nonatomic) BOOL isVSRoom_FirstPlay;
@property (readonly, nonatomic) BOOL isVSStreamVertical;
@property (copy, nonatomic) NSString *sharePlatform;
@property (readonly, nonatomic) BOOL isVSRoomSports;
@property (retain, nonatomic) NSNumber *roomID;
@property (retain, nonatomic) NSNumber *currentGameID;
@property (nonatomic) BOOL isGameEntranceShow;
@property (retain, nonatomic) NSString *cityName;
@property (nonatomic) int feedLabelType;
@property (nonatomic) int mainFeedLabelType;
@property (retain, nonatomic) id audioModel;
@property (retain, nonatomic) NSString *userCityName;
@property (nonatomic) long long ntpDiffTime;
@property (nonatomic) BOOL isRemotePlay;
@property (retain, nonatomic) NSNumber *enterTimestamp;
@property (copy, nonatomic) NSString *enterSessionID;
@property (retain, nonatomic) NSString *logID;
@property (readonly, nonatomic) NSString *ownerUserID;
@property (nonatomic) BOOL isLandscape;
@property (retain, nonatomic) HTSLiveRoomUserInfoModel *userInfoModel;
@property (nonatomic) BOOL isGaming;
@property (copy, nonatomic) NSString *gameName;
@property (nonatomic) BOOL isLandscapeEnter;
@property (nonatomic) BOOL filterEffectivelyUsed;
@property (nonatomic) BOOL faceStickerEffectivelyUsed;
@property (nonatomic) BOOL beautyEffectivelyUsed;
@property (retain, nonatomic) ListCategoryResponse_CategoryNode *selectedCategory;
@property (nonatomic) BOOL mirrored;
@property (nonatomic) long long liveDuration;
@property (retain, nonatomic) NSString *isOtherChannel;
@property (nonatomic) BOOL canGoBack;
@property (nonatomic) BOOL disableBackTip;
@property (nonatomic) BOOL pushWithBack;
@property (nonatomic) BOOL goLiveSquare;
@property (nonatomic) BOOL alreadyClosedWhenEnter;
@property (retain, nonatomic) NSNumber *portalID;
@property (retain, nonatomic) NSString *originatingRoomID;
@property (retain, nonatomic) NSString *originatingAuthorID;
@property (copy, nonatomic) NSString *searchResultId;
@property (retain, nonatomic) HTSLiveMemberMessage *selfMemberMsg;
@property (retain, nonatomic) NSNumber *fanticket;
@property (retain, nonatomic) NSNumber *triggerStayDuration;
@property (retain, nonatomic) NSNumber *linkUserID;
@property (retain, nonatomic) NSNumber *linkAnchorID;
@property (retain, nonatomic) NSNumber *preferTagId;
@property (nonatomic) long long roomEnterPosition;
@property (retain, nonatomic) ConnectPage *enterRoomConectPage;
@property (nonatomic) BOOL isRead;
@property (nonatomic) BOOL isFromCity;
@property (nonatomic) BOOL isUnionCustom;
@property (retain, nonatomic) NSNumber *customUserID;
@property (retain, nonatomic) IESLiveChannelInviteModel *channelInviteModel;
@property (nonatomic) BOOL isEnterVSSportRoomBySchema;
@property (copy, nonatomic) NSString *schemaDefaultResolutionKey;
@property (retain, nonatomic) NSNumber *pullType;
@property (retain, nonatomic) NSNumber *fromPullRefresh;
@property (retain, nonatomic) NSNumber *feedLocalTime;
@property (retain, nonatomic) NSNumber *fromRefreshRedistribute;
@property (retain, nonatomic) NSString *uniqueID;
@property (nonatomic) BOOL isFinished;
@property (nonatomic) BOOL isAnchor;
@property (nonatomic) long long audienceLoadState;
@property (readonly, nonatomic) HTSEventContext *trackContext;
@property (readonly, nonatomic) long long liveTime;
@property (nonatomic) BOOL disableUseComponentTemplate;
@property (nonatomic) BOOL isCommerceWhenEnter;
@property (copy, nonatomic) NSDictionary *anchorABMap;
@property (nonatomic) BOOL isEnablePipMode;
@property (copy, nonatomic) NSDictionary *anchorShareFilterUsers;
@property (readonly, nonatomic) HTSLiveRoom *roomModel;
@property (readonly, nonatomic) IESLiveEnterPreviewHandler *enterPreviewHandler;
@property (retain, nonatomic) id<IESLiveDIContext> attachingDIContext;
@property (readonly, nonatomic) NSNumber *roomID;
@property (readonly, nonatomic) BOOL hasEntered;
@property (readonly, nonatomic) BOOL hasComplete;
@property (readonly, nonatomic) BOOL useDefaultLoadingImage;
@property (readonly, nonatomic) BOOL needSendPreLoadingDuration;
@property (readonly, nonatomic) id audioModel;
@property (nonatomic) int feedLabelType;
@property (nonatomic) int mainFeedLabelType;
@property (retain, nonatomic) NSString *cityName;
@property (retain, nonatomic) NSNumber *currentGameID;
@property (copy, nonatomic) NSString *enterFromAdType;
@property (nonatomic) BOOL isAd;
@property (copy, nonatomic) NSDictionary *rawAdParams;
@property (readonly, nonatomic) long long ntpDiffTime;
@property (retain, nonatomic) NSNumber *fromSourceUserID;
@property (retain, nonatomic) NSNumber *fromSourceUserStatus;
@property (nonatomic) BOOL isFromAggregateColumnClick;
@property (readonly, nonatomic) BOOL isVSOrMediaMixRoom;
@property (nonatomic) int landscapeCommentStyle;
@property (retain, nonatomic) RoomPublicScreenInfo *publicScreenPlatformInfo;
@property (retain, nonatomic) NSNumber *isFirstPullRefresh;
@property (nonatomic) BOOL isGameEntranceShow;
@property (readonly, nonatomic) NSNumber *vsRoomType;
@property (readonly, nonatomic) BOOL isVSRoom;
@property (readonly, nonatomic) BOOL isVSRoom_Live;
@property (readonly, nonatomic) BOOL isVSRoom_FirstPlay;
@property (retain, nonatomic) NSNumber *multitabSelectTabid;
@property (readonly, nonatomic) BOOL isVSStreamVertical;
@property (copy, nonatomic) NSString *sharePlatform;
@property (retain, nonatomic) HTSLiveVSCameraInfo *roomSubCamera;
@property (readonly, nonatomic) BOOL hasMultiCameraData;
@property (readonly, nonatomic) BOOL isMainCamera;
@property (readonly, nonatomic) NSString *currentCameraID;
@property (readonly, nonatomic) HTSLiveVSCameraInfo *currentCamera;
@property (retain, nonatomic) NSArray *allCameraInfosArray;
@property (readonly, nonatomic) NSNumber *currentContentID;
@property (readonly, copy, nonatomic) NSString *cameraTypeTrackStr;
@property (copy, nonatomic) NSString *cameraFromFeedIDStr;
@property (nonatomic) BOOL hasPaidCameraData;
@property (readonly, nonatomic) HTSLiveEpisodeExtraInfo *vsComponentExtraInfo;
@property (nonatomic) BOOL isTemplateVerticalStream;
@property (copy, nonatomic) NSString *liveRecommendInfo;
@property (copy, nonatomic) NSDictionary *couponApiParams;
@property (nonatomic) BOOL isFromAD;
@property (nonatomic) BOOL isAutoEnterFromAD;
@property (nonatomic) BOOL enterByHybridAD;
@property (copy, nonatomic) NSDictionary *hybridAdParams;
@property (copy, nonatomic) NSString *adStr;
@property (retain, nonatomic) NSDictionary *itemLogpb;
@property (retain, nonatomic) NSString *liveSource;
@property (copy, nonatomic) NSString *requestId;
@property (copy, nonatomic) NSString *logpb;
@property (retain, nonatomic) NSNumber *currentMainCameraContentID;
@property (retain, nonatomic) HTSLiveImage *horizontalBackground;
@property (nonatomic) BOOL hasHorizontalBackground;
@property (retain, nonatomic) HTSLiveVSPremiereToast *premiereToast;
@property (nonatomic) BOOL hasPremiereToast;
@property (retain, nonatomic) HTSLiveEnterPublicAreaAnimation *enterPublicAreaAnimation;
@property (nonatomic) BOOL hasEnterPublicAreaAnimation;
@property double hotDuration;
@property (retain) NSDate *lastHotTime;
@property (readonly, nonatomic) long long id_p;
@property (readonly, nonatomic) NSString *idStr;
@property (readonly, nonatomic) long long createTime;
@property (readonly, nonatomic) long long finishTime;
@property (readonly, nonatomic) HTSLiveRoomAnchorData *anchorData;
@property (readonly, nonatomic) long long roomLayout;
@property (readonly, nonatomic) long long lastPingTime;
@property (readonly, nonatomic) long long layout;
@property (readonly, nonatomic) long long liveRoomMode;
@property (readonly, nonatomic) long long streamId;
@property (readonly, nonatomic) NSString *streamIdStr;
@property (readonly, nonatomic) HTSLiveStreamUrl *streamURL;
@property (readonly, nonatomic) BOOL hasStreamURL;
@property (nonatomic) long long status;
@property (readonly, nonatomic) long long streamProvider;
@property (readonly, nonatomic) long long groupSource;
@property (readonly, nonatomic) long long groupId;
@property (readonly, nonatomic) long long liveId;
@property (readonly, nonatomic) long long osType;
@property (readonly, nonatomic) long long clientVersion;
@property (readonly, nonatomic) long long appId;
@property (copy, nonatomic) NSString *title;
@property (nonatomic) BOOL liveTypeNormal;
@property (nonatomic) BOOL liveTypeLinkmic;
@property (nonatomic) BOOL liveTypeAudio;
@property (nonatomic) BOOL liveTypeThirdParty;
@property (nonatomic) BOOL liveTypeScreenshot;
@property (nonatomic) BOOL liveTypeSandbox;
@property (nonatomic) BOOL liveTypeOfficial;
@property (nonatomic) int visibilityRange;
@property (retain, nonatomic) HTSLiveUser *owner;
@property (retain, nonatomic) HTSLiveLiveStatusInfo *liveStatusInfo;
@property (retain, nonatomic) HTSLiveRoomSpecificSceneTypeInfo *sceneTypeInfo;
@property (copy, nonatomic) NSString *ownerUserId;
@property (nonatomic) long long userCount;
@property (nonatomic) long long linkmicLayout;
@property (readonly, nonatomic) HTSLiveRoomExtra *extra;
@property (readonly, nonatomic) BOOL hasExtra;
@property (copy, nonatomic) NSString *dynamicCoverUri;
@property (retain, nonatomic) GPBInt64ObjectDictionary *dynamicCoverDict;
@property (readonly, nonatomic) unsigned long long dynamicCoverDict_Count;
@property (nonatomic) BOOL withLinkmic;
@property (nonatomic) BOOL enableRoomPerspective;
@property (retain, nonatomic) HTSLiveImage *cover;
@property (readonly, nonatomic) BOOL hasCover;
@property (retain, nonatomic) HTSLiveImage *dynamicCover;
@property (readonly, nonatomic) BOOL hasDynamicCover;
@property (retain, nonatomic) HTSLiveImage *dynamicCoverLow;
@property (readonly, nonatomic) BOOL hasDynamicCoverLow;
@property (copy, nonatomic) NSString *shareURL;
@property (copy, nonatomic) NSString *anchorShareText;
@property (copy, nonatomic) NSString *userShareText;
@property (nonatomic) long long mosaicStatus;
@property (copy, nonatomic) NSString *mosaicTip;
@property (nonatomic) long long cellStyle;
@property (retain, nonatomic) HTSLiveLinkMic *linkMic;
@property (readonly, nonatomic) BOOL hasLinkMic;
@property (nonatomic) long long luckymoneyNum;
@property (retain, nonatomic) NSMutableArray *decoListArray;
@property (readonly, nonatomic) unsigned long long decoListArray_Count;
@property (retain, nonatomic) NSMutableArray *topFansArray;
@property (readonly, nonatomic) unsigned long long topFansArray_Count;
@property (readonly, nonatomic) HTSLiveRoomStats *stats;
@property (readonly, nonatomic) BOOL hasStats;
@property (copy, nonatomic) NSString *sunDailyIconContent;
@property (copy, nonatomic) NSString *distance;
@property (copy, nonatomic) NSString *distanceCity;
@property (copy, nonatomic) NSString *location;
@property (copy, nonatomic) NSString *realDistance;
@property (retain, nonatomic) HTSLiveImage *feedRoomLabel;
@property (readonly, nonatomic) BOOL hasFeedRoomLabel;
@property (copy, nonatomic) NSString *commonLabelList;
@property (retain, nonatomic) HTSLiveRoomUserAttr *livingRoomAttrs;
@property (readonly, nonatomic) BOOL hasLivingRoomAttrs;
@property (retain, nonatomic) NSMutableArray *adminUserIdsArray;
@property (readonly, nonatomic) unsigned long long adminUserIdsArray_Count;
@property (readonly, nonatomic) BOOL hasOwner;
@property (copy, nonatomic) NSString *privateInfo;
@property (nonatomic) BOOL hasCommerceGoods;
@property (nonatomic) long long category;
@property (retain, nonatomic) GPBInt64Array *tagsArray;
@property (readonly, nonatomic) unsigned long long tagsArray_Count;
@property (nonatomic) long long startTime;
@property (nonatomic) long long popularity;
@property (copy, nonatomic) NSString *popularityStr;
@property (nonatomic) long long fcdnAppid;
@property (nonatomic) BOOL sellGoods;
@property (nonatomic) long long webCount;
@property (copy, nonatomic) NSString *verticalCoverUri;
@property (nonatomic) long long baseCategory;
@property (readonly, nonatomic) HTSLiveRoomAuthStatus *roomAuth;
@property (readonly, nonatomic) BOOL hasRoomAuth;
@property (retain, nonatomic) NSMutableArray *fansGroupAdminUserIdsArray;
@property (readonly, nonatomic) unsigned long long fansGroupAdminUserIdsArray_Count;
@property (readonly, nonatomic) NSMutableArray *roomTabsArray;
@property (readonly, nonatomic) unsigned long long roomTabsArray_Count;
@property (copy, nonatomic) NSString *introduction;
@property (retain, nonatomic) HTSLiveBurstInfo *burst;
@property (nonatomic) BOOL hasBurst;
@property (retain, nonatomic) HTSLiveRoomHealthScoreInfo *healthScore;
@property (readonly, nonatomic) BOOL hasHealthScore;
@property (nonatomic) BOOL isReplay;
@property (copy, nonatomic) NSString *vid;
@property (nonatomic) long long lotteryFinishTime;
@property (retain, nonatomic) HTSLiveRoomActivityTag *activityTag;
@property (readonly, nonatomic) BOOL hasActivityTag;
@property (retain, nonatomic) HTSLiveImage *portraitCover;
@property (nonatomic) BOOL hasPortraitCover;
@property (retain, nonatomic) HTSLiveImage *background;
@property (nonatomic) BOOL hasBackground;
@property (copy, nonatomic) NSString *waitCopy;
@property (retain, nonatomic) HTSLiveImage *guideButton;
@property (readonly, nonatomic) BOOL hasGuideButton;
@property (copy, nonatomic) NSString *previewCopy;
@property (nonatomic) BOOL isShowInquiryBall;
@property (retain, nonatomic) HTSLiveMatchInfo *matchInfo;
@property (readonly, nonatomic) BOOL hasMatchInfo;
@property (retain, nonatomic) HTSLiveMatchRoomData *match;
@property (nonatomic) BOOL useFilter;
@property (nonatomic) long long giftMsgStyle;
@property (copy, nonatomic) NSString *distanceKm;
@property (copy, nonatomic) NSString *finishURL;
@property (retain, nonatomic) OfficialRoomInfo *officialRoomInfo;
@property (nonatomic) BOOL hasOfficialRoomInfo;
@property (nonatomic) BOOL isShowUserCardSwitch;
@property (copy, nonatomic) NSString *videoFeedTag;
@property (copy, nonatomic) NSString *forumExtraData;
@property (nonatomic) long long fansclubMsgStyle;
@property (nonatomic) long long followMsgStyle;
@property (nonatomic) long long shareMsgStyle;
@property (copy, nonatomic) NSString *shortTitle;
@property (readonly, nonatomic) HTSLiveRoomShortTouchAreaConfig *shortTouchAreaConfig;
@property (nonatomic) BOOL hasShortTouchAreaConfig;
@property (nonatomic) long long bookTime;
@property (nonatomic) long long bookEndTime;
@property (nonatomic) long long roomAuditStatus;
@property (retain, nonatomic) GPBInt64Array *liveDistributionArray;
@property (readonly, nonatomic) unsigned long long liveDistributionArray_Count;
@property (readonly, nonatomic) HTSLiveTVStation *tv;
@property (nonatomic) BOOL hasTv;
@property (nonatomic) BOOL replay;
@property (copy, nonatomic) NSString *challengeInfo;
@property (nonatomic) long long likeCount;
@property (nonatomic) long long searchId;
@property (copy, nonatomic) NSString *anchorScheduledTimeText;
@property (copy, nonatomic) NSString *hotSentenceInfo;
@property (nonatomic) long long replayLocation;
@property (nonatomic) long long streamCloseTime;
@property (copy, nonatomic) NSString *contentTag;
@property (retain, nonatomic) HTSLiveImage *contentLabel;
@property (readonly, nonatomic) BOOL hasContentLabel;
@property (retain, nonatomic) HTSLiveImage *operationLabel;
@property (readonly, nonatomic) BOOL hasOperationLabel;
@property (nonatomic) int anchorTabType;
@property (retain, nonatomic) HTSLiveGameExtra *gameExtra;
@property (readonly, nonatomic) BOOL hasGameExtra;
@property (retain, nonatomic) HTSLiveOfficialChannelInfo *officialChannel;
@property (readonly, nonatomic) BOOL hasOfficialChannel;
@property (copy, nonatomic) NSString *officialChannelUid;
@property (copy, nonatomic) NSString *livePlatformSource;
@property (copy, nonatomic) NSString *stamps;
@property (readonly, nonatomic) HTSLiveCommentBox *commentBox;
@property (readonly, nonatomic) BOOL hasCommentBox;
@property (nonatomic) int businessLive;
@property (nonatomic) BOOL withKtv;
@property (nonatomic) BOOL withDrawSomething;
@property (nonatomic) long long webcastCommentTcs;
@property (nonatomic) long long roomTag;
@property (retain, nonatomic) GPBStringInt64Dictionary *linkerMap;
@property (readonly, nonatomic) unsigned long long linkerMap_Count;
@property (retain, nonatomic) HTSLiveLinkerDetail *linkerDetail;
@property (nonatomic) BOOL hasLinkerDetail;
@property (nonatomic) int finishReason;
@property (retain, nonatomic) HTSLiveRoomCart *roomCart;
@property (readonly, nonatomic) BOOL hasRoomCart;
@property (retain, nonatomic) HTSLiveEcomData *ecomData;
@property (nonatomic) BOOL hasEcomData;
@property (retain, nonatomic) HTSLiveAppearance *appearance;
@property (nonatomic) BOOL hasAppearance;
@property (copy, nonatomic) NSString *scrollConfig;
@property (copy, nonatomic) NSString *relationTag;
@property (nonatomic) long long ownerDeviceId;
@property (nonatomic) long long autoCover;
@property (nonatomic) long long webcastSdkVersion;
@property (nonatomic) long long commentNameMode;
@property (copy, nonatomic) NSString *roomCreateAbParam;
@property (nonatomic) long long preEnterTime;
@property (nonatomic) long long ranklistAudienceType;
@property (nonatomic) long long previewFlowTag;
@property (retain, nonatomic) HTSLiveImage *previewTagURL;
@property (readonly, nonatomic) BOOL hasPreviewTagURL;
@property (retain, nonatomic) HTSLiveQuizExtra *quizExtra;
@property (readonly, nonatomic) BOOL hasQuizExtra;
@property (retain, nonatomic) NSMutableDictionary *anchorAbmap;
@property (readonly, nonatomic) unsigned long long anchorAbmap_Count;
@property (retain, nonatomic) HTSLiveLinkerUsers *linkerUsers;
@property (readonly, nonatomic) BOOL hasLinkerUsers;
@property (nonatomic) long long linkmicDisplayType;
@property (retain, nonatomic) HTSLiveAudioBGData *audioRoomBgimage;
@property (readonly, nonatomic) BOOL hasAudioRoomBgimage;
@property (retain, nonatomic) HTSLiveLinkerUsers *cityTopLinkerUsers;
@property (readonly, nonatomic) BOOL hasCityTopLinkerUsers;
@property (retain, nonatomic) HTSLiveBorderInfo *borderInfo;
@property (readonly, nonatomic) BOOL hasBorderInfo;
@property (retain, nonatomic) HTSLiveImage *cityTopBackground;
@property (readonly, nonatomic) BOOL hasCityTopBackground;
@property (copy, nonatomic) NSString *cityTopDistance;
@property (retain, nonatomic) HTSLiveBonus *bonus;
@property (readonly, nonatomic) BOOL hasBonus;
@property (nonatomic) BOOL highlight;
@property (retain, nonatomic) HTSLiveShortTouchAuth *shortTouchAuth;
@property (nonatomic) BOOL hasShortTouchAuth;
@property (retain, nonatomic) HTSLiveAnnouncementInfo *announcementInfo;
@property (nonatomic) BOOL hasAnnouncementInfo;
@property (nonatomic) long long acquaintanceStatus;
@property (retain, nonatomic) HTSLiveLabelInfo *assistLabel;
@property (retain, nonatomic) HTSLiveRoomReplayInfo *replayInfo;
@property (retain, nonatomic) HTSLiveInteractOpenExtra *interactOpenExtra;
@property (nonatomic) BOOL hasInteractOpenExtra;
@property (retain, nonatomic) HTSLiveVerticalTypeInfo *verticalTypeInfo;
@property (nonatomic) BOOL hasVerticalTypeInfo;
@property (retain, nonatomic) HTSLiveWelfareProjectInfo *welfareProjectInfo;
@property (nonatomic) BOOL hasWelfareProjectInfo;
@property (nonatomic) long long hasPromotionGames;
@property (retain, nonatomic) HTSLiveBeautifyInfo *beautifyInfo;
@property (retain, nonatomic) HTSLiveToolBarData *toolbarData;
@property (retain, nonatomic) HTSLiveRoomPlatformComponentsData *platformComponentsData;
@property (retain, nonatomic) HTSLiveLifeGrouponInfo *lifeGrouponInfo;
@property (nonatomic) BOOL hasLifeGrouponInfo;
@property (retain, nonatomic) HTSLiveDesireInfo *desireInfo;
@property (retain, nonatomic) HTSLiveHotRoomInfo *hotRoomInfo;
@property (nonatomic) BOOL hasHotRoomInfo;
@property (retain, nonatomic) HTSLiveCastScreenData *castScreenData;
@property (copy, nonatomic) NSString *screenCaptureSharingTitle;
@property (retain, nonatomic) NSMutableArray *sharingMusicIdListArray;
@property (retain, nonatomic) HTSLiveRoomChannelData *roomChannel;
@property (retain, nonatomic) HTSLiveOfficialChannelExtraInfo *officialChannelExtra;
@property (nonatomic) BOOL hasOfficialChannelExtra;
@property (retain, nonatomic) HTSLiveRoomViewStats *roomViewStats;
@property (nonatomic) BOOL hasRoomViewStats;
@property (retain, nonatomic) HTSLivePublicScreenBottomInfo *publicScreenBottomInfo;
@property (nonatomic) BOOL hasPublicScreenBottomInfo;
@property (retain, nonatomic) HTSLiveRoomOthersData *others;
@property (retain, nonatomic) HTSLiveRoomBasisData *basis;
@property (nonatomic) BOOL hasBasis;
@property (retain, nonatomic) HTSLiveRoomGameData *gameData;
@property (retain, nonatomic) HTSLiveRoomInteractData *interact;
@property (readonly, nonatomic) NSString *itemExplicitInfo;
@property (nonatomic) BOOL isOfficialChannelRoom;
@property (retain, nonatomic) HTSLiveActivityRoomSkinInfo *activityRoomSkinInfo;
@property (retain, nonatomic) HTSLiveCommentWallInfo *commentWallInfo;
@property (retain, nonatomic) HTSLiveCommentWallPosition *commentWallPosition;
@property (retain, nonatomic) HTSLiveRoomIMInfo *imInfo;
@property (retain, nonatomic) HTSLiveCornerMarkReach *cornerMarkReach;
@property (retain, nonatomic) HTSLivePaidLiveData *paidLiveData;
@property (nonatomic) BOOL hasPaidLiveData;
@property (retain, nonatomic) HTSLiveEasterEggData *easterEggData;
@property (nonatomic) BOOL hasEasterEggData;
@property (retain, nonatomic) NSMutableArray *upperRightWidgetDataListArray;
@property (readonly, nonatomic) unsigned long long upperRightWidgetDataListArray_Count;
@property (retain, nonatomic) HTSLiveIndustryServiceInfo *industryServiceInfo;
@property (retain, nonatomic) HTSLiveAnchorTabLabel *anchorTabLabel;
@property (nonatomic) BOOL hasAnchorTabLabel;
@property (retain, nonatomic) HTSLiveVipData *vipData;
@property (nonatomic) BOOL withAggregateColumn;
@property (retain, nonatomic) HTSLiveFeedbackCard *liveFeedbackCard;
@property (nonatomic) BOOL hasLiveFeedbackCard;
@property (readonly, nonatomic) IOSClientComponent *iosClientComponentData;
@property (retain, nonatomic) HTSLiveClientComponent *clientComponentData;
@property (readonly, nonatomic) HTSLiveUnionLiveInfo *unionLiveInfo;
@property (retain, nonatomic) HTSLiveCommentaryRoomInfo *commentaryRoomInfo;
@property (retain, nonatomic) HTSLiveEpisodeExtraInfo *episodeExtra;
@property (retain, nonatomic) HTSLiveRoomReqUserData *reqUser;
@property (nonatomic) BOOL hasReqUser;
@property (nonatomic) long long orientation;
@property (nonatomic) BOOL hasActivityRoomSkinInfo;
@property (nonatomic) BOOL hasReplayInfo;
@property (nonatomic) BOOL hasCommentWallInfo;
@property (nonatomic) BOOL hasCommentWallPosition;
@property (nonatomic) BOOL liveTypeVsLive;
@property (nonatomic) BOOL liveTypeVsPremiere;
@property (nonatomic) BOOL hasEpisodeExtra;
@property (retain, nonatomic) GPBEnumArray *vsRolesArray;
@property (readonly, nonatomic) unsigned long long vsRolesArray_Count;
@property (nonatomic) long long sofaLayout;
@property (nonatomic) BOOL isNeedCheckList;
@property (nonatomic) BOOL hasLiveStatusInfo;
@property (nonatomic) BOOL hasImInfo;
@property (nonatomic) BOOL hasAssistLabel;
@property (retain, nonatomic) NSMutableArray *filterWordsArray;
@property (readonly, nonatomic) unsigned long long filterWordsArray_Count;
@property (retain, nonatomic) HTSLiveLabelInfo *dynamicLabel;
@property (nonatomic) BOOL hasDynamicLabel;
@property (nonatomic) BOOL hasCornerMarkReach;
@property (retain, nonatomic) HTSLivePreviewExposeData *previewExpose;
@property (nonatomic) BOOL hasPreviewExpose;
@property (nonatomic) int gameRoomType;
@property (nonatomic) BOOL titleRecommend;
@property (nonatomic) long long danmakuDetail;
@property (retain, nonatomic) HTSLiveAvatarLiveInfo *avatarLiveInfo;
@property (nonatomic) BOOL hasAvatarLiveInfo;
@property (retain, nonatomic) IESLiveCircleInfo *circleInfo;
@property (nonatomic) BOOL hasCircleInfo;
@property (retain, nonatomic) HTSLiveImage *screenshotSover;
@property (nonatomic) BOOL hasScreenshotSover;
@property (nonatomic) BOOL hasIndustryServiceInfo;
@property (retain, nonatomic) HTSLiveRelevantRecommendation *relevantRecommendation;
@property (nonatomic) BOOL hasRelevantRecommendation;
@property (nonatomic) BOOL hasSceneTypeInfo;
@property (retain, nonatomic) HTSLiveGameCPData *gameCp;
@property (nonatomic) BOOL hasGameCp;
@property (retain, nonatomic) HTSLiveGamePlayData *gamePlay;
@property (nonatomic) BOOL hasGamePlay;
@property (nonatomic) BOOL hasUnionLiveInfo;
@property (nonatomic) BOOL hasBeautifyInfo;
@property (nonatomic) BOOL hasToolbarData;
@property (nonatomic) BOOL hasVipData;
@property (nonatomic) long long toutiaoCoverRecommendLevel;
@property (nonatomic) long long toutiaoTitleRecommendLevel;
@property (retain, nonatomic) NSMutableArray *assistLabelListArray;
@property (readonly, nonatomic) unsigned long long assistLabelListArray_Count;
@property (nonatomic) BOOL hasDesireInfo;
@property (nonatomic) BOOL hasCastScreenData;
@property (copy, nonatomic) NSString *authCity;
@property (retain, nonatomic) HTSLiveActivityLiveRecommendConfig *activityLiveRecommendConfig;
@property (nonatomic) BOOL hasActivityLiveRecommendConfig;
@property (nonatomic) BOOL hasRoomChannel;
@property (retain, nonatomic) HTSLivePackMetaInfo *packMeta;
@property (nonatomic) BOOL hasPackMeta;
@property (retain, nonatomic) HTSLiveActivityData *activityData;
@property (nonatomic) BOOL hasActivityData;
@property (retain, nonatomic) HTSLiveLikeDisplayConfig *likeDisplayConfig;
@property (nonatomic) BOOL hasLikeDisplayConfig;
@property (nonatomic) BOOL hasCommentaryRoomInfo;
@property (nonatomic) long long redpacketAudienceAuth;
@property (retain, nonatomic) HTSLiveMatchChatConfig *matchChatConfig;
@property (nonatomic) BOOL hasMatchChatConfig;
@property (nonatomic) long long vsMainReplayId;
@property (retain, nonatomic) HTSLiveShareResource *shareResource;
@property (nonatomic) BOOL hasShareResource;
@property (readonly, nonatomic) unsigned long long sharingMusicIdListArray_Count;
@property (retain, nonatomic) HTSLiveStreamUrl *pushStreamHkt;
@property (nonatomic) BOOL hasPushStreamHkt;
@property (retain, nonatomic) HTSLiveRoomRevenueData *revenue;
@property (nonatomic) BOOL hasRevenue;
@property (nonatomic) BOOL hasAnchorData;
@property (nonatomic) BOOL hasOthers;
@property (retain, nonatomic) HTSLivePicoInfo *picoInfo;
@property (nonatomic) BOOL hasPicoInfo;
@property (nonatomic) BOOL hasGameData;
@property (retain, nonatomic) HTSLiveRoomFeedData *feedData;
@property (nonatomic) BOOL hasFeedData;
@property (retain, nonatomic) HTSLiveOpenContentData *openContentData;
@property (nonatomic) BOOL hasOpenContentData;
@property (nonatomic) BOOL hasClientComponentData;
@property (nonatomic) BOOL hasPlatformComponentsData;
@property (nonatomic) BOOL hasIosClientComponentData;
@property (retain, nonatomic) HTSLiveImage *coverGauss;
@property (nonatomic) BOOL hasCoverGauss;
@property (nonatomic) BOOL hasMatch;
@property (nonatomic) BOOL hasInteract;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy, nonatomic) NSString *identifier;
@property (readonly, nonatomic) NSString *anchorIdentifier;
@property (readonly, nonatomic, getter=isTemplateRoom) BOOL templateRoom;
@property (nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } screenInsets;
@property (nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } containerEdgeInsets;
@property (retain, nonatomic, setter=setroomLiveReason:) NSString *roomLiveReason;
@property (retain, nonatomic, setter=setinsertTaskId:) NSString *insertTaskId;
@property (retain, nonatomic) NSNumber *onlineCountByIM;
@property (retain, nonatomic) NSString *recommendMethod;
@property (nonatomic) BOOL declineToSwitchToFullScreen;
@property (nonatomic) BOOL isEnterFromAppointment;
@property (nonatomic) BOOL isPseudoLiving;
@property (retain, nonatomic) HTSLiveUser *anchorChannelUser;
@property (nonatomic) BOOL isMediaPreview;
@property (nonatomic) BOOL recommendUsed;
@property (nonatomic) BOOL searchUsed;
@property (nonatomic) BOOL operationUsed;
@property (nonatomic) BOOL selfDefinedUsed;
@property (nonatomic) BOOL dbUsed;
@property (nonatomic) BOOL challengeUsed;
@property (retain, nonatomic) NSString *tagID;
@property (retain, nonatomic) NSString *tagSource;
@property (nonatomic) BOOL roomDidStop;
@property (copy, nonatomic) NSString *clickOrder;
@property (copy, nonatomic) NSString *drawOrder;
@property (retain, nonatomic) NSString *currentMainCameraMatchID;
@property (retain, nonatomic) GPBInt64Array *currentMainCameraEventIds;
@property (readonly, nonatomic) BOOL isUnionLiveRoom;
@property (nonatomic) BOOL vsHasAppointmentTag;
@property (nonatomic) BOOL vsIsInnerFromDrawer;
@property (readonly, nonatomic) NSNumber *currentGroupID;
@property (nonatomic) long long degradeLevel;
@property (nonatomic) BOOL enableSeek;
@property (nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } screenInsets;
@property (nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } containerEdgeInsets;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic, setter=setrequestId:) NSString *requestId;
@property (retain, nonatomic, setter=setlogpb:) NSString *logpb;
@property (nonatomic) BOOL isAd;
@property (copy, nonatomic) NSDictionary *rawAdParams;
@property (copy, nonatomic) NSString *enterFromAdType;
@property (retain, nonatomic, setter=setroomLiveReason:) NSString *roomLiveReason;
@property (retain, nonatomic, setter=setinsertTaskId:) NSString *insertTaskId;
@property (retain, nonatomic) NSNumber *onlineCountByIM;
@property (retain, nonatomic) NSString *recommendMethod;
@property (nonatomic) BOOL declineToSwitchToFullScreen;
@property (nonatomic) BOOL isEnterFromAppointment;
@property (nonatomic) BOOL isPseudoLiving;
@property (retain, nonatomic) HTSLiveUser *anchorChannelUser;
@property (nonatomic) BOOL isMediaPreview;
@property (nonatomic) BOOL recommendUsed;
@property (nonatomic) BOOL searchUsed;
@property (nonatomic) BOOL operationUsed;
@property (nonatomic) BOOL selfDefinedUsed;
@property (nonatomic) BOOL dbUsed;
@property (nonatomic) BOOL challengeUsed;
@property (retain, nonatomic) NSString *tagID;
@property (retain, nonatomic) NSString *tagSource;
@property (nonatomic) BOOL roomDidStop;
@property (copy, nonatomic) NSString *clickOrder;
@property (copy, nonatomic) NSString *drawOrder;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSNumber *roomID;
@property (retain, nonatomic) HTSLiveRoom *micRoom;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) long long id_p;
@property (copy, nonatomic) NSString *idStr;
@property (nonatomic) long long status;
@property (copy, nonatomic) NSString *ownerUserId;
@property (copy, nonatomic) NSString *title;
@property (nonatomic) long long userCount;
@property (nonatomic) long long createTime;
@property (nonatomic) long long linkmicLayout;
@property (nonatomic) long long finishTime;
@property (retain, nonatomic) HTSLiveRoomExtra *extra;
@property (nonatomic) BOOL hasExtra;
@property (copy, nonatomic) NSString *dynamicCoverUri;
@property (retain, nonatomic) GPBInt64ObjectDictionary *dynamicCoverDict;
@property (readonly, nonatomic) unsigned long long dynamicCoverDict_Count;
@property (nonatomic) long long lastPingTime;
@property (nonatomic) long long liveId;
@property (nonatomic) long long streamProvider;
@property (nonatomic) long long osType;
@property (nonatomic) long long clientVersion;
@property (nonatomic) BOOL withLinkmic;
@property (nonatomic) BOOL enableRoomPerspective;
@property (retain, nonatomic) HTSLiveImage *cover;
@property (nonatomic) BOOL hasCover;
@property (retain, nonatomic) HTSLiveImage *dynamicCover;
@property (nonatomic) BOOL hasDynamicCover;
@property (retain, nonatomic) HTSLiveImage *dynamicCoverLow;
@property (nonatomic) BOOL hasDynamicCoverLow;
@property (copy, nonatomic) NSString *shareURL;
@property (copy, nonatomic) NSString *anchorShareText;
@property (copy, nonatomic) NSString *userShareText;
@property (nonatomic) long long streamId;
@property (copy, nonatomic) NSString *streamIdStr;
@property (retain, nonatomic) HTSLiveStreamUrl *streamURL;
@property (nonatomic) BOOL hasStreamURL;
@property (nonatomic) long long mosaicStatus;
@property (copy, nonatomic) NSString *mosaicTip;
@property (nonatomic) long long cellStyle;
@property (retain, nonatomic) HTSLiveLinkMic *linkMic;
@property (nonatomic) BOOL hasLinkMic;
@property (nonatomic) long long luckymoneyNum;
@property (retain, nonatomic) NSMutableArray *decoListArray;
@property (readonly, nonatomic) unsigned long long decoListArray_Count;
@property (retain, nonatomic) NSMutableArray *topFansArray;
@property (readonly, nonatomic) unsigned long long topFansArray_Count;
@property (retain, nonatomic) HTSLiveRoomStats *stats;
@property (nonatomic) BOOL hasStats;
@property (copy, nonatomic) NSString *sunDailyIconContent;
@property (copy, nonatomic) NSString *distance;
@property (copy, nonatomic) NSString *distanceCity;
@property (copy, nonatomic) NSString *location;
@property (copy, nonatomic) NSString *realDistance;
@property (retain, nonatomic) HTSLiveImage *feedRoomLabel;
@property (nonatomic) BOOL hasFeedRoomLabel;
@property (copy, nonatomic) NSString *commonLabelList;
@property (retain, nonatomic) HTSLiveRoomUserAttr *livingRoomAttrs;
@property (nonatomic) BOOL hasLivingRoomAttrs;
@property (retain, nonatomic) NSMutableArray *adminUserIdsArray;
@property (readonly, nonatomic) unsigned long long adminUserIdsArray_Count;
@property (retain, nonatomic) HTSLiveUser *owner;
@property (nonatomic) BOOL hasOwner;
@property (copy, nonatomic) NSString *privateInfo;
@property (nonatomic) BOOL hasCommerceGoods;
@property (nonatomic) BOOL liveTypeNormal;
@property (nonatomic) BOOL liveTypeLinkmic;
@property (nonatomic) BOOL liveTypeAudio;
@property (nonatomic) BOOL liveTypeThirdParty;
@property (nonatomic) BOOL liveTypeScreenshot;
@property (nonatomic) BOOL liveTypeSandbox;
@property (nonatomic) BOOL liveTypeOfficial;
@property (nonatomic) long long groupId;
@property (nonatomic) long long orientation;
@property (nonatomic) long long category;
@property (retain, nonatomic) GPBInt64Array *tagsArray;
@property (readonly, nonatomic) unsigned long long tagsArray_Count;
@property (nonatomic) long long startTime;
@property (nonatomic) long long popularity;
@property (copy, nonatomic) NSString *popularityStr;
@property (nonatomic) long long fcdnAppid;
@property (nonatomic) BOOL sellGoods;
@property (nonatomic) long long webCount;
@property (copy, nonatomic) NSString *verticalCoverUri;
@property (nonatomic) long long baseCategory;
@property (retain, nonatomic) HTSLiveRoomAuthStatus *roomAuth;
@property (nonatomic) BOOL hasRoomAuth;
@property (retain, nonatomic) NSMutableArray *roomTabsArray;
@property (readonly, nonatomic) unsigned long long roomTabsArray_Count;
@property (copy, nonatomic) NSString *introduction;
@property (retain, nonatomic) HTSLiveBurstInfo *burst;
@property (nonatomic) BOOL hasBurst;
@property (retain, nonatomic) HTSLiveRoomHealthScoreInfo *healthScore;
@property (nonatomic) BOOL hasHealthScore;
@property (nonatomic) BOOL isReplay;
@property (copy, nonatomic) NSString *vid;
@property (nonatomic) long long groupSource;
@property (nonatomic) long long lotteryFinishTime;
@property (retain, nonatomic) HTSLiveRoomActivityTag *activityTag;
@property (nonatomic) BOOL hasActivityTag;
@property (retain, nonatomic) HTSLiveImage *portraitCover;
@property (nonatomic) BOOL hasPortraitCover;
@property (retain, nonatomic) HTSLiveImage *background;
@property (nonatomic) BOOL hasBackground;
@property (nonatomic) long long layout;
@property (copy, nonatomic) NSString *waitCopy;
@property (retain, nonatomic) HTSLiveImage *guideButton;
@property (nonatomic) BOOL hasGuideButton;
@property (copy, nonatomic) NSString *previewCopy;
@property (nonatomic) BOOL isShowInquiryBall;
@property (retain, nonatomic) HTSLiveMatchInfo *matchInfo;
@property (nonatomic) BOOL hasMatchInfo;
@property (nonatomic) BOOL useFilter;
@property (nonatomic) long long giftMsgStyle;
@property (copy, nonatomic) NSString *distanceKm;
@property (copy, nonatomic) NSString *finishURL;
@property (retain, nonatomic) OfficialRoomInfo *officialRoomInfo;
@property (nonatomic) BOOL hasOfficialRoomInfo;
@property (nonatomic) BOOL isShowUserCardSwitch;
@property (copy, nonatomic) NSString *videoFeedTag;
@property (copy, nonatomic) NSString *forumExtraData;
@property (nonatomic) long long fansclubMsgStyle;
@property (nonatomic) long long followMsgStyle;
@property (nonatomic) long long shareMsgStyle;
@property (nonatomic) long long roomLayout;
@property (copy, nonatomic) NSString *shortTitle;
@property (retain, nonatomic) HTSLiveRoomShortTouchAreaConfig *shortTouchAreaConfig;
@property (nonatomic) BOOL hasShortTouchAreaConfig;
@property (nonatomic) long long bookTime;
@property (nonatomic) long long bookEndTime;
@property (nonatomic) long long roomAuditStatus;
@property (retain, nonatomic) GPBInt64Array *liveDistributionArray;
@property (readonly, nonatomic) unsigned long long liveDistributionArray_Count;
@property (retain, nonatomic) HTSLiveTVStation *tv;
@property (nonatomic) BOOL hasTv;
@property (nonatomic) BOOL replay;
@property (copy, nonatomic) NSString *challengeInfo;
@property (nonatomic) long long likeCount;
@property (nonatomic) long long searchId;
@property (copy, nonatomic) NSString *anchorScheduledTimeText;
@property (copy, nonatomic) NSString *hotSentenceInfo;
@property (nonatomic) long long replayLocation;
@property (nonatomic) long long streamCloseTime;
@property (copy, nonatomic) NSString *contentTag;
@property (retain, nonatomic) HTSLiveImage *contentLabel;
@property (nonatomic) BOOL hasContentLabel;
@property (retain, nonatomic) HTSLiveImage *operationLabel;
@property (nonatomic) BOOL hasOperationLabel;
@property (nonatomic) int anchorTabType;
@property (retain, nonatomic) HTSLiveGameExtra *gameExtra;
@property (nonatomic) BOOL hasGameExtra;
@property (retain, nonatomic) HTSLiveOfficialChannelInfo *officialChannel;
@property (nonatomic) BOOL hasOfficialChannel;
@property (copy, nonatomic) NSString *stamps;
@property (retain, nonatomic) HTSLiveCommentBox *commentBox;
@property (nonatomic) BOOL hasCommentBox;
@property (nonatomic) int businessLive;
@property (nonatomic) BOOL withKtv;
@property (nonatomic) BOOL withDrawSomething;
@property (nonatomic) long long webcastCommentTcs;
@property (nonatomic) long long roomTag;
@property (retain, nonatomic) GPBStringInt64Dictionary *linkerMap;
@property (readonly, nonatomic) unsigned long long linkerMap_Count;
@property (nonatomic) int finishReason;
@property (retain, nonatomic) HTSLiveRoomCart *roomCart;
@property (nonatomic) BOOL hasRoomCart;
@property (copy, nonatomic) NSString *scrollConfig;
@property (copy, nonatomic) NSString *relationTag;
@property (nonatomic) long long ownerDeviceId;
@property (nonatomic) long long autoCover;
@property (nonatomic) long long appId;
@property (nonatomic) long long webcastSdkVersion;
@property (nonatomic) long long commentNameMode;
@property (copy, nonatomic) NSString *roomCreateAbParam;
@property (nonatomic) long long preEnterTime;
@property (nonatomic) long long ranklistAudienceType;
@property (nonatomic) long long previewFlowTag;
@property (retain, nonatomic) HTSLiveImage *previewTagURL;
@property (nonatomic) BOOL hasPreviewTagURL;
@property (retain, nonatomic) HTSLiveQuizExtra *quizExtra;
@property (nonatomic) BOOL hasQuizExtra;
@property (retain, nonatomic) NSMutableDictionary *anchorAbmap;
@property (readonly, nonatomic) unsigned long long anchorAbmap_Count;
@property (retain, nonatomic) HTSLiveLinkerUsers *linkerUsers;
@property (nonatomic) BOOL hasLinkerUsers;
@property (nonatomic) long long linkmicDisplayType;
@property (retain, nonatomic) HTSLiveAudioBGData *audioRoomBgimage;
@property (nonatomic) BOOL hasAudioRoomBgimage;
@property (retain, nonatomic) HTSLiveLinkerUsers *cityTopLinkerUsers;
@property (nonatomic) BOOL hasCityTopLinkerUsers;
@property (retain, nonatomic) HTSLiveBorderInfo *borderInfo;
@property (nonatomic) BOOL hasBorderInfo;
@property (retain, nonatomic) HTSLiveImage *cityTopBackground;
@property (nonatomic) BOOL hasCityTopBackground;
@property (copy, nonatomic) NSString *cityTopDistance;
@property (nonatomic) long long liveRoomMode;
@property (retain, nonatomic) HTSLiveBonus *bonus;
@property (nonatomic) BOOL hasBonus;
@property (nonatomic) BOOL highlight;
@property (nonatomic) BOOL isOfficialChannelRoom;
@property (retain, nonatomic) HTSLiveActivityRoomSkinInfo *activityRoomSkinInfo;
@property (nonatomic) BOOL hasActivityRoomSkinInfo;
@property (retain, nonatomic) NSMutableArray *fansGroupAdminUserIdsArray;
@property (readonly, nonatomic) unsigned long long fansGroupAdminUserIdsArray_Count;
@property (retain, nonatomic) HTSLiveRoomReplayInfo *replayInfo;
@property (nonatomic) BOOL hasReplayInfo;
@property (copy, nonatomic) NSString *officialChannelUid;
@property (copy, nonatomic) NSString *livePlatformSource;
@property (nonatomic) long long acquaintanceStatus;
@property (retain, nonatomic) HTSLiveCommentWallInfo *commentWallInfo;
@property (nonatomic) BOOL hasCommentWallInfo;
@property (retain, nonatomic) HTSLiveCommentWallPosition *commentWallPosition;
@property (nonatomic) BOOL hasCommentWallPosition;
@property (nonatomic) BOOL liveTypeVsLive;
@property (nonatomic) BOOL liveTypeVsPremiere;
@property (retain, nonatomic) HTSLiveEpisodeExtraInfo *episodeExtra;
@property (nonatomic) BOOL hasEpisodeExtra;
@property (retain, nonatomic) GPBEnumArray *vsRolesArray;
@property (readonly, nonatomic) unsigned long long vsRolesArray_Count;
@property (copy, nonatomic) NSString *itemExplicitInfo;
@property (retain, nonatomic) HTSLiveShortTouchAuth *shortTouchAuth;
@property (nonatomic) BOOL hasShortTouchAuth;
@property (nonatomic) long long sofaLayout;
@property (retain, nonatomic) HTSLiveAnnouncementInfo *announcementInfo;
@property (nonatomic) BOOL hasAnnouncementInfo;
@property (nonatomic) BOOL isNeedCheckList;
@property (retain, nonatomic) HTSLiveLiveStatusInfo *liveStatusInfo;
@property (nonatomic) BOOL hasLiveStatusInfo;
@property (retain, nonatomic) HTSLiveRoomIMInfo *imInfo;
@property (nonatomic) BOOL hasImInfo;
@property (retain, nonatomic) HTSLiveLabelInfo *assistLabel;
@property (nonatomic) BOOL hasAssistLabel;
@property (retain, nonatomic) HTSLiveInteractOpenExtra *interactOpenExtra;
@property (nonatomic) BOOL hasInteractOpenExtra;
@property (retain, nonatomic) HTSLiveVerticalTypeInfo *verticalTypeInfo;
@property (nonatomic) BOOL hasVerticalTypeInfo;
@property (retain, nonatomic) NSMutableArray *filterWordsArray;
@property (readonly, nonatomic) unsigned long long filterWordsArray_Count;
@property (retain, nonatomic) HTSLiveLabelInfo *dynamicLabel;
@property (nonatomic) BOOL hasDynamicLabel;
@property (retain, nonatomic) HTSLiveLinkerDetail *linkerDetail;
@property (nonatomic) BOOL hasLinkerDetail;
@property (nonatomic) int visibilityRange;
@property (retain, nonatomic) HTSLiveCornerMarkReach *cornerMarkReach;
@property (nonatomic) BOOL hasCornerMarkReach;
@property (retain, nonatomic) HTSLivePreviewExposeData *previewExpose;
@property (nonatomic) BOOL hasPreviewExpose;
@property (retain, nonatomic) HTSLiveWelfareProjectInfo *welfareProjectInfo;
@property (nonatomic) BOOL hasWelfareProjectInfo;
@property (nonatomic) int gameRoomType;
@property (retain, nonatomic) HTSLivePaidLiveData *paidLiveData;
@property (nonatomic) BOOL hasPaidLiveData;
@property (retain, nonatomic) HTSLiveEasterEggData *easterEggData;
@property (nonatomic) BOOL hasEasterEggData;
@property (nonatomic) BOOL titleRecommend;
@property (nonatomic) long long danmakuDetail;
@property (retain, nonatomic) HTSLiveAvatarLiveInfo *avatarLiveInfo;
@property (nonatomic) BOOL hasAvatarLiveInfo;
@property (retain, nonatomic) IESLiveCircleInfo *circleInfo;
@property (nonatomic) BOOL hasCircleInfo;
@property (nonatomic) long long hasPromotionGames;
@property (retain, nonatomic) HTSLiveImage *screenshotSover;
@property (nonatomic) BOOL hasScreenshotSover;
@property (retain, nonatomic) HTSLiveAppearance *appearance;
@property (nonatomic) BOOL hasAppearance;
@property (retain, nonatomic) HTSLiveEcomData *ecomData;
@property (nonatomic) BOOL hasEcomData;
@property (retain, nonatomic) HTSLiveIndustryServiceInfo *industryServiceInfo;
@property (nonatomic) BOOL hasIndustryServiceInfo;
@property (retain, nonatomic) HTSLiveRelevantRecommendation *relevantRecommendation;
@property (nonatomic) BOOL hasRelevantRecommendation;
@property (retain, nonatomic) HTSLiveRoomSpecificSceneTypeInfo *sceneTypeInfo;
@property (nonatomic) BOOL hasSceneTypeInfo;
@property (retain, nonatomic) HTSLiveGameCPData *gameCp;
@property (nonatomic) BOOL hasGameCp;
@property (retain, nonatomic) HTSLiveGamePlayData *gamePlay;
@property (nonatomic) BOOL hasGamePlay;
@property (retain, nonatomic) HTSLiveUnionLiveInfo *unionLiveInfo;
@property (nonatomic) BOOL hasUnionLiveInfo;
@property (retain, nonatomic) HTSLiveBeautifyInfo *beautifyInfo;
@property (nonatomic) BOOL hasBeautifyInfo;
@property (retain, nonatomic) HTSLiveToolBarData *toolbarData;
@property (nonatomic) BOOL hasToolbarData;
@property (retain, nonatomic) HTSLiveAnchorTabLabel *anchorTabLabel;
@property (nonatomic) BOOL hasAnchorTabLabel;
@property (retain, nonatomic) HTSLiveLifeGrouponInfo *lifeGrouponInfo;
@property (nonatomic) BOOL hasLifeGrouponInfo;
@property (retain, nonatomic) HTSLiveVipData *vipData;
@property (nonatomic) BOOL hasVipData;
@property (nonatomic) long long toutiaoCoverRecommendLevel;
@property (nonatomic) long long toutiaoTitleRecommendLevel;
@property (retain, nonatomic) NSMutableArray *upperRightWidgetDataListArray;
@property (readonly, nonatomic) unsigned long long upperRightWidgetDataListArray_Count;
@property (retain, nonatomic) HTSLiveFeedbackCard *liveFeedbackCard;
@property (nonatomic) BOOL hasLiveFeedbackCard;
@property (retain, nonatomic) NSMutableArray *assistLabelListArray;
@property (readonly, nonatomic) unsigned long long assistLabelListArray_Count;
@property (retain, nonatomic) HTSLiveDesireInfo *desireInfo;
@property (nonatomic) BOOL hasDesireInfo;
@property (retain, nonatomic) HTSLiveHotRoomInfo *hotRoomInfo;
@property (nonatomic) BOOL hasHotRoomInfo;
@property (nonatomic) BOOL withAggregateColumn;
@property (retain, nonatomic) HTSLiveCastScreenData *castScreenData;
@property (nonatomic) BOOL hasCastScreenData;
@property (retain, nonatomic) HTSLiveOfficialChannelExtraInfo *officialChannelExtra;
@property (nonatomic) BOOL hasOfficialChannelExtra;
@property (copy, nonatomic) NSString *authCity;
@property (retain, nonatomic) HTSLiveActivityLiveRecommendConfig *activityLiveRecommendConfig;
@property (nonatomic) BOOL hasActivityLiveRecommendConfig;
@property (retain, nonatomic) HTSLiveRoomChannelData *roomChannel;
@property (nonatomic) BOOL hasRoomChannel;
@property (retain, nonatomic) HTSLivePackMetaInfo *packMeta;
@property (nonatomic) BOOL hasPackMeta;
@property (retain, nonatomic) HTSLiveActivityData *activityData;
@property (nonatomic) BOOL hasActivityData;
@property (retain, nonatomic) HTSLiveLikeDisplayConfig *likeDisplayConfig;
@property (nonatomic) BOOL hasLikeDisplayConfig;
@property (retain, nonatomic) HTSLiveRoomViewStats *roomViewStats;
@property (nonatomic) BOOL hasRoomViewStats;
@property (retain, nonatomic) HTSLiveMatchRoomData *match;
@property (nonatomic) BOOL hasMatch;
@property (retain, nonatomic) HTSLiveCommentaryRoomInfo *commentaryRoomInfo;
@property (nonatomic) BOOL hasCommentaryRoomInfo;
@property (nonatomic) long long redpacketAudienceAuth;
@property (retain, nonatomic) HTSLiveMatchChatConfig *matchChatConfig;
@property (nonatomic) BOOL hasMatchChatConfig;
@property (nonatomic) long long vsMainReplayId;
@property (copy, nonatomic) NSString *screenCaptureSharingTitle;
@property (retain, nonatomic) HTSLiveShareResource *shareResource;
@property (nonatomic) BOOL hasShareResource;
@property (retain, nonatomic) NSMutableArray *sharingMusicIdListArray;
@property (readonly, nonatomic) unsigned long long sharingMusicIdListArray_Count;
@property (retain, nonatomic) HTSLivePublicScreenBottomInfo *publicScreenBottomInfo;
@property (nonatomic) BOOL hasPublicScreenBottomInfo;
@property (retain, nonatomic) HTSLiveStreamUrl *pushStreamHkt;
@property (nonatomic) BOOL hasPushStreamHkt;
@property (retain, nonatomic) HTSLiveRoomBasisData *basis;
@property (nonatomic) BOOL hasBasis;
@property (retain, nonatomic) HTSLiveRoomInteractData *interact;
@property (nonatomic) BOOL hasInteract;
@property (retain, nonatomic) HTSLiveRoomRevenueData *revenue;
@property (nonatomic) BOOL hasRevenue;
@property (retain, nonatomic) HTSLiveRoomReqUserData *reqUser;
@property (nonatomic) BOOL hasReqUser;
@property (retain, nonatomic) HTSLiveRoomAnchorData *anchorData;
@property (nonatomic) BOOL hasAnchorData;
@property (retain, nonatomic) HTSLiveRoomOthersData *others;
@property (nonatomic) BOOL hasOthers;
@property (retain, nonatomic) HTSLivePicoInfo *picoInfo;
@property (nonatomic) BOOL hasPicoInfo;
@property (retain, nonatomic) HTSLiveRoomGameData *gameData;
@property (nonatomic) BOOL hasGameData;
@property (retain, nonatomic) HTSLiveRoomFeedData *feedData;
@property (nonatomic) BOOL hasFeedData;
@property (retain, nonatomic) HTSLiveOpenContentData *openContentData;
@property (nonatomic) BOOL hasOpenContentData;
@property (retain, nonatomic) HTSLiveClientComponent *clientComponentData;
@property (nonatomic) BOOL hasClientComponentData;
@property (retain, nonatomic) HTSLiveRoomPlatformComponentsData *platformComponentsData;
@property (nonatomic) BOOL hasPlatformComponentsData;
@property (retain, nonatomic) IOSClientComponent *iosClientComponentData;
@property (nonatomic) BOOL hasIosClientComponentData;
@property (retain, nonatomic) HTSLiveImage *coverGauss;
@property (nonatomic) BOOL hasCoverGauss;

+ (void)install;
+ (id)liveroomMD5SignWithRoomID:(id)a0;
+ (void)load;
+ (void)setIeslive_fileds:(id)a0;
+ (id)ieslive_fileds;
+ (BOOL)isMethodCacheOptEnabled;
+ (void)load;
+ (void)load;
+ (BOOL)isEnterRoomOptEnabled;
+ (id)descriptor;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)mergeFrom:(id)a0;
- (id)valueForUndefinedKey:(id)a0;
- (void)setValue:(id)a0 forUndefinedKey:(id)a1;
- (void)preloadStreamInfoByScene:(id)a0 roomID:(id)a1 completion:(id /* block */)a2;
- (BOOL)isQualityKey:(id)a0 lessThanOrEqualToQualityKey:(id)a1;
- (BOOL)containQualityGreatThanQualityKey:(id)a0;
- (id)storedResolutionKeyProvider;
- (id)getCurrentRealKey:(id)a0;
- (void)preloadStopAll;
- (void)preloadRequestWithRoomParam:(id)a0;
- (void)preloadRequestInStage:(unsigned long long)a0;
- (void)preloadRequestWithConfig:(id)a0;
- (void)bindDIWithAttachingDIContext:(id)a0;
- (void)clearEnterPreviewHandler;
- (void)enterRequestPreviewWithRoomParam:(id)a0;
- (void)preloadRequestWithStage:(unsigned long long)a0;
- (void)setEnterPreviewHandler:(id)a0;
- (id)handler;
- (BOOL)isPKOnGoing;
- (BOOL)isVoteOnGoing;
- (BOOL)isBreakthroughOnGoing;
- (BOOL)isSurvivalOnGoing;
- (BOOL)isOhterLinking;
- (BOOL)isMultiPKOnGoing;
- (BOOL)isMultiVoteOnGoing;
- (BOOL)isMultiShellOnGoing;
- (void)ieslive_room_protect_merge_from:(id)a0;
- (long long)isLastedGoodsRoom;
- (long long)friendShareVideoFeatureType;
- (long long)friendShareVideoTabType;
- (long long)friendVolumeSettingType;
- (BOOL)friendSupportNoiseSuppressionEnabled;
- (BOOL)isGuestShareVideoEnabled;
- (BOOL)isAcquaintanceUserCardNewStyleEnabled;
- (BOOL)isAcqIntimate;
- (id)acqRoomPrivacyStatusText;
- (BOOL)isPaidStream;
- (id)vipPrivilegeInfo;
- (BOOL)hasVipPrivilegeInfo;
- (id)ticketType;
- (id)cameraVSPrivilegeInfo;
- (BOOL)isUnpaidForVSPrivilegeCamera;
- (BOOL)isVRCamera;
- (id)vsMediaPreStreamTopImage;
- (id)vsMediaPreStreamBottomImage;
- (id)vsMediaPreStreamTopInfo;
- (id)vsMediaPreStreamBottomInfo;
- (BOOL)vsMediaShouldTopAndBottomOffset;
- (id)vsMediaPriorityCameraTitle;
- (int)vsMediaPreStreamType;
- (BOOL)isEcomCart;
- (BOOL)enableShowChatChannelInMultiTab;
- (BOOL)isLifeRoom;
- (BOOL)isMSequenceRoom;
- (BOOL)hasVSPrivilege;
- (BOOL)hasVSPrivilegeCamera;
- (BOOL)isPaywallRoom;
- (BOOL)isUnPaiedUserInPayRoom;
- (BOOL)isPaiedUserInPayRoom;
- (BOOL)isWhiteListUserInPayRoom;
- (BOOL)deliveriedUserInPayRoom;
- (BOOL)unDeliveriedUserInPayRoom;
- (BOOL)needShowPromisePromptInPayRoom;
- (BOOL)containsPaidSubCamera;
- (BOOL)containsPaidScenes;
- (id)createMainCamera;
- (id)initWithRoomID:(id)a0;
- (id)initWithRoomID:(id)a0 ownerUserID:(id)a1;
- (BOOL)isAutoCover;
- (BOOL)isFixedComment;
- (id)ieslive_roomAuth;
- (id)roomData;
- (BOOL)canLongPress;
- (id)initWithRoomID:(id)a0;
- (id)defaultQuality;
- (id)initWithRoomID:(id)a0 ownerUserID:(id)a1;
- (BOOL)isDouyinMediaRoom;
- (BOOL)isVRRoom;
- (BOOL)isExplainRoom;
- (id)getExplainRoomPullData;
- (long long)vrType;
- (BOOL)isValidRoom;
- (id)qualitiesArray;
- (BOOL)shouldShowViceView;
- (id)viceViewTypeForTrack;
- (long long)viceViewLayoutType;
- (BOOL)isGroupLiveGame;
- (BOOL)isGroupLiveChorus;
- (BOOL)isGroupLivePlaymode;
- (id)rtmpPullURLParams;
- (id)livetypeFromScence;
- (BOOL)enableShowCityDistanceInFeedDrawer;
- (BOOL)isGameRoom;
- (BOOL)isEcomCart;
- (long long)gameRoomResult;
- (long long)getGameID;
- (id)getGameName;
- (BOOL)isGameRoomWithPublishPoint;
- (BOOL)isBarrageGame;
- (int)barrageGameAnchorType;
- (id)barrageGameAppid;
- (id)multiStreamPayLoad;
- (BOOL)isMultiCameraRoom;
- (long long)cacheScene;
- (void)iesliveroom_mergeFrom:(id)a0;
- (id)iesliveroom_copyWithZone:(struct _NSZone { } *)a0;
- (BOOL)cacheValid;
- (void)setCacheScene:(long long)a0;
- (void)setCacheValid:(BOOL)a0;
- (long long)scene;
- (id)streamData;
- (void)trackSetValue:(id)a0 forUndefinedKey:(id)a1;
- (id)trackValueForUndefinedKey:(id)a0;
- (BOOL)isCompleteModel;
- (BOOL)didSetPlaceHolderBg;
- (void)setDidSetPlaceHolderBg:(BOOL)a0;
- (id)didSetPlaceHolderBgKey;
- (void)setDidSetPlaceHolderBgKey:(id)a0;
- (void)setHasEntered:(BOOL)a0;
- (void)setNeedSendPreLoadingDuration:(BOOL)a0;
- (BOOL)hasLiveStreamInfo;
- (BOOL)isVSCompleteModel;
- (void)setHasComplete:(BOOL)a0;
- (id)mixAnchorAbmap;
- (BOOL)hasUsedTopic;
- (id)challengeTraceInfo;
- (BOOL)channelUserFollow;
- (long long)tempStateDurationWithShortTouchItemType:(long long)a0 strategy:(int)a1;
- (BOOL)isPKOnGoing;
- (BOOL)isOhterLinking;
- (BOOL)isMultiPKOnGoing;
- (BOOL)isScreencastLinking;
- (id)diffIdentifier;
- (BOOL)isEqualToDiffableObject:(id)a0;
- (BOOL)isPKOnGoing;
- (BOOL)isOhterLinking;
- (BOOL)isMultiPKOnGoing;
- (BOOL)isScreencastLinking;
- (id)awes_ieslive_toJson;
- (id)awes_ownerAvatarURLString;
- (id)awes_ownerDisplayID;
- (id)awes_ownerNickname;
- (id)awes_ownerSignature;

@end
