@class IESECMallCompContext, IESECMallViewModel, NSDictionary, IESECMallPitayaModel, IESECListCardShowTimeTracker, IESECMallPageCard, UIPanGestureRecognizer, IESECMallHomeView, NSCache, IESECMallBackgroundView, IESECMallFeedMonitor, IESECListKitItemDataModel, UIColor, IESECMarqueeView, IESECLynxCardBridgeEventSubscriber, IESECMallTabDataPrefetchManager, NSNumber, IESECMallNativeCardCell, IESECMallListKitBffDataModel, HMDMonitorCallbackObject, IESECMallLiveMiniWindowService, IESECButton, UIView, NSArray, IESECMallBridgesRegister, IESECMallPopupTaskManager, FBKVOController, NSMutableDictionary, IESECLynxCard, IESECMallModel, NSString, NSObject, IESECMallNativeRreloadMonitor, IESECMallLynxRenderMonitor, IESECMallPopupView, IESECMallDeviceAdapterInfo, NSTimer, IESECListKitCardPreloader, IESECMallWhiteBoard, IESECListKitBackgroundModel, IESECMallRefreshToastManager, NSDate;
@protocol IESECPdpPreloadHandler, IESECMallMainViewControllerDelegate, IESECMallAnchorFloatingProtocol, OS_dispatch_queue, IESECMallLoadingViewProtocol;

@interface IESECMallMainViewController : UIViewController <AWELiveRoomMessage, IESECXBridgeCallHandlerService, IESECMallLiveMiniWindowServiceDelegate, IESECMallBusinessContextProtocol, IESECGoodsDetailPreloadSubscriber, IESECMallFeedViewControllerDelegate, IESECMallPopupViewDelegate, IESECSKUServiceProtocol, IESECMallHomeViewDelegate, IESECMallLynxRenderMonitorDelegate, IESECMallPopupDelegate, IESECMallJSBridgeProvider, IESECMallPageCardDelegate, IESECMallXBridgeRegisterDelegate, IESECListKitLynxCardLifeCycle, IESECMallFeedMonitorDelegate, UIGestureRecognizerDelegate, IESECMallNativePopupManagerDelegate, IESECMallFeedRequestProcessDataProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL enterBackgroundInvisible;
@property (nonatomic) long long loadSkinRequestType;
@property (nonatomic) BOOL mallTrackerAddSessionID;
@property (nonatomic) BOOL pitayaRefreshGYLABOn;
@property (copy, nonatomic) NSDictionary *gylRefreshConfig;
@property (nonatomic) BOOL canRefreshGYL;
@property (nonatomic) double requestRefreshGYLTime;
@property (copy, nonatomic) NSString *enterMethod;
@property (nonatomic) double viewDidAppearTime;
@property (nonatomic) double viewDidDisAppearTime;
@property (nonatomic) double lastScrollTime;
@property (copy, nonatomic) NSDictionary *pitayaMessage;
@property (nonatomic) BOOL gylTimeout;
@property (nonatomic) BOOL isViewVisible;
@property (copy, nonatomic) IESECMarqueeView *marqueeViewController;
@property (copy, nonatomic) id /* block */ completeBlock;
@property (weak, nonatomic) IESECListKitItemDataModel *marqueeCellModel;
@property (nonatomic) BOOL disableUserInteractionIfAnimation;
@property (nonatomic) double scrollStartOffsetY;
@property (nonatomic) double reportScrollMaxOffset;
@property (retain, nonatomic) NSMutableDictionary *hasScrolledDistanceDict;
@property (copy, nonatomic) NSArray *reportScrollPageNameArray;
@property (retain, nonatomic) NSNumber *mallListEnableNested;
@property (nonatomic) BOOL isLGRefreshStrategyOptABOn;
@property (nonatomic) BOOL hasLGRefreshGYLFromPitaya;
@property (nonatomic) BOOL cancelRequestByAppear;
@property (retain, nonatomic) NSDate *backgroundTime;
@property (retain, nonatomic) NSString *timeWindowStart;
@property (nonatomic) BOOL showMarqueeAnimation;
@property (nonatomic) BOOL gulPassiveRefreshOpt;
@property (retain, nonatomic) NSDictionary *pitayaActions;
@property (nonatomic) BOOL skipResetParams;
@property (nonatomic) BOOL changeScrollToTop;
@property (retain, nonatomic) IESECListKitBackgroundModel *bffDataBackground;
@property (nonatomic) long long gylFirstScreenMinCount;
@property (nonatomic) BOOL fixHalfScreen;
@property (nonatomic) BOOL cellAutoPlayUnderHalfScreen;
@property (nonatomic) double viewDidLoadTime;
@property (nonatomic) unsigned long long skeletonRenderState;
@property (retain, nonatomic) id<IESECPdpPreloadHandler> pdpPreloadHandler;
@property (retain, nonatomic) IESECMallHomeView *homeView;
@property (retain, nonatomic) IESECMallPageCard *pageCard;
@property (retain, nonatomic) IESECMallBackgroundView *bgView;
@property (retain, nonatomic) IESECButton *goTopButton;
@property (retain, nonatomic) UIView<IESECMallLoadingViewProtocol> *loadingView;
@property (retain, nonatomic) IESECMallLiveMiniWindowService *liveMiniWinService;
@property (retain, nonatomic) IESECMallNativeCardCell *nativeCardCell;
@property (nonatomic) BOOL isNativeCellMute;
@property (nonatomic) long long lastTabId;
@property (copy, nonatomic) NSString *nativeCardSchema;
@property (retain, nonatomic) FBKVOController *kvoController;
@property (retain, nonatomic) IESECMallLynxRenderMonitor *lynxRenderMonitor;
@property (retain, nonatomic) IESECMallNativeRreloadMonitor *nativePreloadMonitor;
@property (retain, nonatomic) IESECMallBridgesRegister *bridgesRegister;
@property (retain, nonatomic) IESECMallFeedMonitor *feedMonitor;
@property (nonatomic) double containerInitTime;
@property (retain, nonatomic) IESECLynxCardBridgeEventSubscriber *subscriber;
@property (nonatomic) BOOL viewDidSetup;
@property (copy, nonatomic) NSString *enterFrom;
@property (nonatomic) BOOL delayShowLoading;
@property (copy, nonatomic) NSString *finishLoadTemplate;
@property (nonatomic) BOOL enableFeedMonitor;
@property (nonatomic) BOOL needHandleSearchPitaya;
@property (nonatomic) BOOL hasSearchPitayaSignal;
@property (nonatomic) unsigned long long enterTypeForPitaya;
@property (copy, nonatomic) NSArray *pageNameListForPitaya;
@property (retain, nonatomic) IESECMallViewModel *mallViewModel;
@property (nonatomic) BOOL scrollStart;
@property (copy, nonatomic) NSString *coinsPendantSchema;
@property (nonatomic) BOOL hasShowCoinPendant;
@property (nonatomic) BOOL hasReportSlide;
@property (retain, nonatomic) IESECListKitCardPreloader *preloader;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *reportQueue;
@property (retain, nonatomic) IESECListKitBackgroundModel *skinBackground;
@property (nonatomic) BOOL isLoadingMore;
@property (nonatomic) unsigned long long preReqStatus;
@property (retain, nonatomic) NSTimer *loadMoreTimer;
@property (nonatomic) BOOL globalGreyMode;
@property (nonatomic) BOOL needRevetColorful;
@property (nonatomic) BOOL firstScreenShowNotify;
@property (nonatomic) double feedOffsetY;
@property (nonatomic) double baseOffsetY;
@property (nonatomic) BOOL disableDarkmodeGradientSwitch;
@property (nonatomic) long long refreshSteps;
@property (retain, nonatomic) IESECMallPopupTaskManager *popupManager;
@property (retain, nonatomic) IESECMallPopupView *coinsView;
@property (copy, nonatomic) NSString *lastPageShowId;
@property (copy, nonatomic) NSString *curPageShowId;
@property (retain, nonatomic) UIView *loginView;
@property (retain, nonatomic) HMDMonitorCallbackObject *hmdFPSCallback;
@property (retain, nonatomic) IESECMallListKitBffDataModel *stashedPopupData;
@property (nonatomic) BOOL disableLoadmoreModify;
@property (nonatomic) BOOL checkPostBack;
@property (retain, nonatomic) NSCache *loadmorePageNumTSDict;
@property (nonatomic) BOOL firstAppear;
@property (nonatomic) double preAppearTS;
@property (retain, nonatomic) IESECMallPitayaModel *pitayaModel;
@property (retain, nonatomic) IESECMallModel *currentMallModel;
@property (nonatomic) BOOL enableSlideForMultiTab;
@property (nonatomic) BOOL hasInitMultiTabConfig;
@property (retain, nonatomic) UIPanGestureRecognizer *crossSlideGesture;
@property (retain, nonatomic) IESECListCardShowTimeTracker *cardShowTimeTracker;
@property (retain, nonatomic) IESECMallWhiteBoard *whiteBoard;
@property (retain, nonatomic) IESECMallTabDataPrefetchManager *tabDataPrefetcher;
@property (retain, nonatomic) IESECMallCompContext *mallCompContext;
@property (retain, nonatomic) IESECMallRefreshToastManager *refreshToastManager;
@property (copy, nonatomic) id /* block */ gylRefreshBlock;
@property (weak, nonatomic) id<IESECMallMainViewControllerDelegate> delegate;
@property (copy, nonatomic) NSDictionary *currentRouterParams;
@property (copy, nonatomic) NSString *openTime;
@property (copy, nonatomic) NSString *swipeTime;
@property (nonatomic) BOOL forbiddenBottomMargin;
@property (nonatomic) BOOL useCustomTopMargin;
@property (nonatomic) double customTopMargin;
@property (nonatomic) BOOL forbiddenShowLoadingView;
@property (nonatomic) BOOL useCustomBackgroundColor;
@property (retain, nonatomic) UIColor *customBackgroundColor;
@property (copy, nonatomic) NSArray *xBridgeList;
@property (nonatomic) BOOL transferMainListError;
@property (nonatomic) BOOL forbidFirstScreenStraightOut;
@property (nonatomic) BOOL delayFirstScreenStraightOut;
@property (nonatomic) BOOL enableSyncStraightOut;
@property (retain, nonatomic) UIView *preCreatedPageCard;
@property (copy, nonatomic) NSString *firstScreenStraightOutIdentity;
@property (nonatomic) BOOL firstScreenStraightOutIdentityIsTabs;
@property (nonatomic) double recommendViewFirstViewAppear;
@property (nonatomic) BOOL openSaveStraightOutData;
@property (nonatomic) BOOL didPreloadStraight;
@property (nonatomic) BOOL didPreloadRealData;
@property (retain, nonatomic) NSNumber *sendVisibilityEventNextRunLoop;
@property (nonatomic) long long nativeType;
@property (nonatomic) BOOL nativefullTabBigFontEnabled;
@property (nonatomic) BOOL isImmerseRealDataLockMode;
@property (nonatomic) BOOL isImmerseLiteLockMode;
@property (nonatomic) BOOL isImmerseLiteShowAllSection;
@property (nonatomic) BOOL hasStraightOutFullDeliveryPage;
@property (nonatomic) BOOL hasStraightOutHalfDeliveryPage;
@property (copy, nonatomic) NSDictionary *mallFeedImpressionConfig;
@property (copy, nonatomic) id /* block */ refreshCompletion;
@property (nonatomic) BOOL isRequestOnAir;
@property (copy, nonatomic) NSArray *needlessComponents;
@property (copy, nonatomic) NSDictionary *openPopupByNativeConfig;
@property (copy, nonatomic) NSDictionary *openPopupByNativeResult;
@property (nonatomic) double backTopBottomMargin;
@property (nonatomic) unsigned long long currentThemeStyle;
@property (copy, nonatomic) NSDictionary *btmParams;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *trackQueue;
@property (retain, nonatomic) IESECMallDeviceAdapterInfo *deviceAdapterInfo;
@property (nonatomic) BOOL loadmorePreloadABOn;
@property (nonatomic) BOOL listViewAutoWidth;
@property (copy, nonatomic) NSString *apiConfigKey;
@property (nonatomic) long long fixedTabID;
@property (nonatomic) BOOL useNAGoTopBtnForce;
@property (weak, nonatomic) IESECLynxCard *outerTopBarView;
@property (weak, nonatomic) UIView<IESECMallAnchorFloatingProtocol> *outerContainerView;
@property (retain, nonatomic) IESECMallPopupView *popupView;
@property (nonatomic) long long fixScrollToSection;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)removeStorageConfigV2;
+ (BOOL)enterForegroundMallVisibleStatusOptimizeEnabled;
+ (BOOL)removeStorageByConfigV2;

- (void)sendEvent:(id)a0 params:(id)a1;
- (void)dismissLoadingView;
- (BOOL)mallIsVisible;
- (void)mallGetCardPosition:(id)a0 completion:(id /* block */)a1;
- (id)mallPageName;
- (void)updateLocationIfNeed;
- (BOOL)needCheckLogin;
- (BOOL)isHomePageMallTopMall;
- (BOOL)isMallInXtab;
- (void)didReceiveMemoryWarningNotification;
- (void)audienceQuitAllRoomWithSlideVC:(id)a0 player:(id)a1 context:(id)a2;
- (id)hybridMonitorContext;
- (void)stopPreload;
- (id)playerManager;
- (void)requireLogin;
- (void)buildUI;
- (id)currentPlayingCell;
- (double)containerTopMargin;
- (double)currentMemory;
- (void)requestClientAiPrefetchApis:(double)a0 message:(id)a1 completion:(id /* block */)a2;
- (id)listCollectionView;
- (void)leaveMall:(long long)a0;
- (void)updateSkinData:(id)a0;
- (void)configWithRouterParams:(id)a0 enterForm:(id)a1;
- (void)requestFirstScreenApis;
- (id)globalPropsExtra;
- (void)reloadWith:(id)a0;
- (void)refreshImmerseFullScreenFirstScreenRealData;
- (void)updateContextPropsExtraData;
- (void)refreshGYLTimeout;
- (BOOL)isRequestingGYL;
- (id)visibleBubbleViews;
- (void)refreshFirstScreenRealDataCachedBySO;
- (void)requestRefreshApis;
- (void)getCardPosition:(id)a0 completion:(id /* block */)a1;
- (BOOL)canBeginRefresh;
- (id)catchMallModel;
- (void)updateThemeStyleImmediately:(unsigned long long)a0;
- (void)updateThemeStyle:(unsigned long long)a0 defaultBgUrl:(id)a1;
- (void)rebuildConstraintsWhileTopMarginChanged;
- (void)updatePagePopViewExtraData:(id)a0;
- (void)requestRefreshApisActively:(BOOL)a0;
- (unsigned long long)pageNum;
- (void)handleClickProductAndBackCeiling;
- (void)handleHotStartRefreshCeiling;
- (BOOL)setHostScrollViewWithOffsetY:(double)a0 animated:(BOOL)a1 delayTime:(long long)a2;
- (double)calculateBottomCoverAreaHeight;
- (void)rebuildConstraints:(double)a0;
- (void)closeHalfMall;
- (void)lynxCard:(id)a0 didLoadFail:(id)a1 resource:(id)a2 itemModel:(id)a3;
- (void)lynxCard:(id)a0 didFirstScreen:(id)a1 resource:(id)a2 itemModel:(id)a3 isPreloader:(BOOL)a4;
- (void)lynxCardMallReport:(id)a0;
- (void)mallLynxRenderReport:(id)a0;
- (void)openWithTransitionInfoIfNeed:(id)a0;
- (id)getListVCForTransition:(id)a0 item:(id)a1 index:(id)a2 elementName:(id)a3;
- (unsigned long long)mallResVersion;
- (void)configPreloadStraight;
- (void)mallReport:(id)a0 enterNewPage:(BOOL)a1;
- (void)mallReport:(id)a0;
- (void)setupAiPrefetchData:(id)a0;
- (id)rootGlobalPropsExtra;
- (void)resetMallHomeViewUIAfterRotation;
- (BOOL)isNativeMallVisibleSupport;
- (void)mediaCellDidDisplay;
- (void)tryShowDesktopGuide;
- (void)anchorPendantShow:(id)a0 completion:(id /* block */)a1;
- (void)anchorPendantDismissWithContainerId:(id)a0;
- (void)setHalfScreenOpen:(BOOL)a0;
- (void)updateSkinDataDefault;
- (void)buildSubscriber;
- (void)updateBackTopLayoutWithParams:(id)a0;
- (void)goTopButtonAction:(id)a0;
- (BOOL)couldLoadMoreByChunk;
- (void)mallWriteAlog:(id)a0 paramModel:(id)a1 result:(id)a2 context:(id)a3;
- (BOOL)loadingMoreFlag;
- (BOOL)shouldLoadmorePreload;
- (BOOL)mainRequestIsLoading;
- (BOOL)currentOutContainerIsVisible;
- (void)dismissPopupView:(id)a0;
- (void)dismissBubbleView:(id)a0;
- (void)bubbleView:(id)a0 resetVisibility:(BOOL)a1;
- (id)currentBridgesRegister;
- (id)globalXBridgesCallHandler;
- (id)currentListContextIdForPopup:(id)a0;
- (id)globalExtraForPopup:(id)a0;
- (id)rootGlobalExtraForPopup:(id)a0;
- (id)hybridMonitorContextForPopup:(id)a0;
- (id)pageNameForPopup:(id)a0;
- (id)hmBidForPopup:(id)a0;
- (BOOL)enableOptLynxViewLoadLogicForPopup:(id)a0;
- (void)popupViewMakeStartPerformance;
- (void)popupViewMakeEndPerformance;
- (id)responderView;
- (void)popupViewLayoutUpdated;
- (BOOL)currentListViewIsVisible;
- (void)unregisterSubscriber;
- (BOOL)enableWhiteBoard;
- (id)hmBid;
- (id)lynxCardMallGetReportInfo:(id)a0;
- (void)scrollToFirstFavoriteCellWithSectionID:(id)a0 animated:(BOOL)a1;
- (id)lynxCardFeedProductIds:(id)a0;
- (void)runFullVerify:(id)a0 scriptMethodName:(id)a1 params:(id)a2 contextProvider:(id)a3;
- (void)lynxCardMallReport:(id)a0 isCacheData:(BOOL)a1;
- (void)appendAction:(id)a0 isInstantORWindFirst:(BOOL)a1;
- (void)lynxCardMallFeedScrollToTop:(id)a0;
- (BOOL)scrollToFirstFavoriteCellWithSectionID:(id)a0 itemID:(id)a1 itemIndex:(long long)a2 offset:(long long)a3 animated:(BOOL)a4 onlyWhenHeaderCardVisible:(BOOL)a5;
- (BOOL)scrollToFirstFavoriteCellWithSectionID:(id)a0 itemID:(id)a1 itemIndex:(long long)a2 offset:(long long)a3 animated:(BOOL)a4 onlyWhenHeaderCardVisible:(BOOL)a5 moveOutside:(BOOL)a6 forceScroll:(BOOL)a7;
- (void)lynxCardBffDataUpdate:(id)a0;
- (void)lynxCardAdReport:(id)a0;
- (id)mallListSharedDataIMP;
- (id)mallDynamicRequestIMP;
- (id)lynxCardMallGetPageInfo;
- (id)isCurrentPageVisible;
- (id)popupGetPageVisible;
- (void)checkInnerTokenForEffect:(id)a0 methodName:(id)a1 schema:(id)a2;
- (void)callNegativeFeedback:(id)a0;
- (void)callGetFeedDataMethod:(id)a0 completion:(id /* block */)a1;
- (void)lottieMountMethod:(id)a0 completion:(id /* block */)a1;
- (void)anchorPendantVisibility:(id)a0 visible:(BOOL)a1;
- (id)popupSubmitTask:(id)a0;
- (void)popupDismissWithContainerId:(id)a0;
- (void)halfMallIsExpandWithCompletion:(id /* block */)a0;
- (void)removeCardAndUpdateModel:(id)a0;
- (id)ecMallCardVisible:(id)a0;
- (void)closeHalfMallWithCompletion:(id /* block */)a0;
- (void)appendCommonImpressionArray:(id)a0;
- (void)getRecommendParams:(id /* block */)a0;
- (void)updateFilters:(id)a0 completion:(id /* block */)a1;
- (void)instantORWindEnd:(id)a0 completion:(id /* block */)a1;
- (void)mediaPlay:(id)a0 completion:(id /* block */)a1;
- (void)setNeedRecordPageShowIdIfNeed:(BOOL)a0;
- (id)responderViewForBtm;
- (void)reportSchemaDiff:(id)a0 outSchema:(id)a1;
- (void)realRecommendInfoWith:(id)a0 callback:(id /* block */)a1 isCacheData:(BOOL)a2;
- (BOOL)isHalfPageOpen:(id)a0;
- (void)openMarketingWithParamModel:(id)a0 completion:(id /* block */)a1;
- (void)handleRequestShowResultWithParamModel:(id)a0 completion:(id /* block */)a1;
- (void)showToastWithParamModel:(id)a0 completion:(id /* block */)a1;
- (void)getRealRecommendInfoWithParamModel:(id)a0 completion:(id /* block */)a1;
- (void)requestRefreshApisTimeout;
- (void)showLoginViewIfNeed;
- (void)deliveryDidRendered;
- (BOOL)hasVisiblePopup;
- (void)attachLiveMiniWindowWithRoomId:(id)a0;
- (void)callToBridgeHandlerAnchorPendantShow:(id)a0 completion:(id /* block */)a1;
- (void)callToBridgeHandlerAnchorPendantDismissWithContainerId:(id)a0;
- (void)setCustomReMakerNoMoreView:(id)a0;
- (void)setupEnterMethod:(id)a0;
- (void)checkAndGetGeckoResource;
- (void)removeStorageKeysIfNeed;
- (void)loadConfigJsonBundle;
- (void)loadStraightOutData:(id)a0;
- (void)preDecodeIfNeed;
- (id)pageCardLynxSchema;
- (void)preloadPageCardWithPageName:(id)a0;
- (BOOL)shouldSendVisibilityEventNextRunLoop;
- (BOOL)enableOptLynxViewLoadLogic;
- (id)mallGrayFilter;
- (id)removeStorageKeys;
- (long long)pageCardDynamicParamTimeout;
- (BOOL)mallEnableCheckJsbToken;
- (long long)favoriteScrollToTopDelayTime;
- (BOOL)mallEnableFallbackCustomThemeInSection;
- (BOOL)shouldDismissPopupWhenLeaveMall;
- (BOOL)mallFetchByNativeDynamicParams;
- (BOOL)isMusicConfigSwitchOn;
- (BOOL)shouldResetAudioSessionWithContext:(id)a0;
- (void)registerMusicConfigHandler;
- (void)unRegisterMusicConfigHandler;
- (void)handlePitayaBroadcast:(id)a0;
- (void)setupPDPPreloadHandler;
- (id)getPdpSchema:(id)a0;
- (id)listVC;
- (void)startPreload;
- (void)mallFeedMonitorReport:(id)a0;
- (id)mallFavoriteFeedItems;
- (long long)mallTabId;
- (id)mallFeedVC;
- (id)xBridgesCallHandler;
- (void)lynxCard:(id)a0 didUpdateDataWithLynxViewFromType:(unsigned long long)a1 resource:(id)a2 itemModel:(id)a3 perfDict:(id)a4;
- (void)addPopupTaskContainer;
- (id)sharedLynxGroupID:(id)a0;
- (BOOL)enableAnimaXWith:(id)a0;
- (void)stopPrefetchVideoWithReason:(unsigned long long)a0;
- (void)confirmWithSKUInfo:(id)a0;
- (BOOL)enableTimerOptV0;
- (void)liveCardDidDisplay:(id)a0;
- (id)mallListInnerNativeMonitor;
- (void)skeletonMainPicComplete;
- (id)getScrollEventParams;
- (BOOL)feedViewControllerIsNativeCellCardMute:(id)a0;
- (void)feedViewController:(id)a0 itemCardSetVoiceMute:(BOOL)a1;
- (void)feedViewController:(id)a0 itemCardRouterSchema:(id)a1;
- (id)feedViewControllerGetRootGlobalExtra:(id)a0;
- (id)feedViewControllerGetGlobalExtra:(id)a0;
- (id)feedViewControllerGetGreyParams;
- (id)feedViewControllerChannelGlobalProps;
- (double)scaleForFeedList;
- (id)feedViewControllerGetCurrentRequestContext:(id)a0;
- (BOOL)feedViewControllerIsCacheData;
- (BOOL)feedViewControllerMallListEnableNested:(id)a0;
- (long long)loadmoreRangeSize;
- (void)feedViewController:(id)a0 scrollViewDidScroll:(id)a1;
- (void)feedViewController:(id)a0 scrollViewDidEndDecelerating:(id)a1;
- (void)feedViewController:(id)a0 scrollViewDidEndScrollingAnimation:(id)a1;
- (void)feedViewController:(id)a0 scrollViewDidEndDragging:(id)a1 willDecelerate:(BOOL)a2;
- (void)feedViewController:(id)a0 scrollViewWillBeginDragging:(id)a1;
- (void)feedViewControllerLoadMoreData:(id)a0 source:(unsigned long long)a1;
- (id)logExtraForFeedViewControllerReport:(id)a0;
- (void)feedViewController:(id)a0 cellWillDisplay:(id)a1 source:(unsigned long long)a2 section:(long long)a3 index:(long long)a4 isFirstShow:(BOOL)a5 cell:(id)a6;
- (void)skeletonCellWillDisplay;
- (BOOL)feedViewControllerDidFirstScreen:(id)a0;
- (BOOL)feedViewControllerDidFirstMainRequestFailAndStraightOutRenderEnd:(id)a0;
- (void)feedViewController:(id)a0 mallReport:(id)a1 isCacheData:(BOOL)a2;
- (void)processTrackDataWithModel:(id)a0 block:(id /* block */)a1;
- (void)feedViewController:(id)a0 cellWillEndDisplay:(id)a1 source:(unsigned long long)a2 section:(long long)a3 index:(long long)a4;
- (void)appendCachedFeedDataIfNeeded;
- (id)feedViewControllerDidEnvIdentifier:(id)a0;
- (id)feedViewControllerGlobalNotiIdentifier:(id)a0;
- (void)didCreateCellWith:(long long)a0 totalInterval:(double)a1 createCellInterval:(double)a2 configCellInterval:(double)a3;
- (void)cancelSetAudioSession;
- (id)mallHomeViewHybridMonitorContext;
- (id)mallHomeViewHmBid;
- (BOOL)mallHomeViewEnableOptLynxViewLoadLogic;
- (id)currentFeedEnvIdentifier:(id)a0;
- (void)mallHomeView:(id)a0 topBarSizeDidChanged:(struct CGSize { double x0; double x1; })a1;
- (void)refreshLGGYLFromPitaya:(id)a0;
- (void)mallLiveMiniWindowWillChangeActiveState:(BOOL)a0;
- (void)mallLiveMiniWindowWillChangeMuteState:(BOOL)a0;
- (void)lynxCard:(id)a0 onSetup:(id)a1 resource:(id)a2 itemModel:(id)a3 isPreloader:(BOOL)a4 isPreDecode:(BOOL)a5;
- (void)requestRefreshApisActively:(BOOL)a0 withClickToast:(BOOL)a1;
- (BOOL)scrollToFirstFavoriteCellWithSectionID:(id)a0 itemID:(id)a1 itemIndex:(long long)a2 offset:(long long)a3 animated:(BOOL)a4 onlyWhenHeaderCardVisible:(BOOL)a5 moveOutside:(BOOL)a6;
- (void)buildCommonDataWithParamModel:(id)a0 itemModel:(id)a1;
- (void)chunkForMallReport:(id)a0;
- (id)recommendInfoFor:(id)a0 isCacheData:(BOOL)a1;
- (id)findTabContainerView:(id)a0;
- (id)tryFindPendantSuperView:(id)a0;
- (void)tryAddPendantToList:(id)a0 with:(id)a1;
- (void)appendFilters:(id)a0;
- (void)deleteFilters:(id)a0;
- (void)removeFilters;
- (void)instantORWindEndWithFilters:(id)a0 lastAction:(id)a1;
- (id)homepagePageRootView;
- (void)readABKeys;
- (void)setupWhiteBoard;
- (void)buildBinding;
- (id)currentDeliverySessionID;
- (void)buildHeaderRefreshViewIfNeeded;
- (BOOL)isLoginWithCheckIfNeed;
- (void)subscribeFpsEvent;
- (void)trackerDidLoad;
- (void)registerPitayaFeature;
- (void)registerGYLRefreshPitayaService;
- (void)initBackLGGYLRefreshComponentIfNeeded;
- (void)initComponents;
- (void)refreshGYLWithType:(id)a0;
- (BOOL)isFeedRemainCountEnough;
- (BOOL)realLoadMoreByPageCardWithSource:(unsigned long long)a0;
- (void)reportGYLRefreshWithSwitchType:(id)a0 timing:(id)a1 trackDict:(id)a2;
- (void)updateLGPitayaGULPassiveRefreshInfo;
- (void)trackRefreshProductListEventByPitaya:(BOOL)a0 hotStart:(BOOL)a1;
- (id)getFeedVideoBehavior;
- (id)appendRefreshParamsWithType:(id)a0;
- (void)updateSelectedTabInfo:(id)a0 curSectionModel:(id)a1 contextParams:(id)a2 type:(id)a3 networkFinish:(id /* block */)a4;
- (void)trackMallSwitchTabPerformance:(id)a0 fromTabId:(long long)a1 isCache:(BOOL)a2 type:(id)a3 startTime:(double)a4;
- (void)realRequestByPageCard:(id)a0 apiKeys:(id)a1 withHandler:(id /* block */)a2 forbidEvent:(BOOL)a3 skipResetParams:(BOOL)a4;
- (BOOL)isEnableFeedMonitor;
- (void)subscribedLiveStatusChange;
- (void)updateRecommendToWhiteBoardInfoIfNeeded;
- (void)pageVisibilityChage:(BOOL)a0;
- (id)cellForPaymentSuccess;
- (void)setLiveMiniWindowTop;
- (void)showOrHideLiveMiniWindow;
- (void)prefetchNextTabData;
- (void)cancelPrefetchNextTab;
- (void)trackerFpsPerformance;
- (void)resetPitayaRefreshStatus;
- (void)invalidLoadMoreTime;
- (void)reportWindowFPS:(id)a0;
- (void)requestRefreshApisWithType:(unsigned long long)a0 withClickToast:(BOOL)a1;
- (void)removeLoginViewIfNeed;
- (void)realRefreshByPageCardActively:(unsigned long long)a0;
- (void)refreshSoloHybridChannelIfNeeded;
- (void)getPitayaUserBehaviorParamsAndReport;
- (id)pageNameForPageCard;
- (void)addPageCardWithPageName:(id)a0;
- (void)trackerFirstScreenTime;
- (void)setAudioSessionAfterRefreshComplete;
- (BOOL)enablePreloadListKitViewModel;
- (void)buildPageCard;
- (void)addBgView;
- (void)addCoinsView;
- (void)addPopupView;
- (id)eventDenyList;
- (void)addDebugTipsToPageCard:(id)a0;
- (void)rebuildConstraintsForHomeViewOnPad;
- (void)addGoTopButton;
- (struct CGSize { double x0; double x1; })goTopButtonSize;
- (void)reportSingleItem:(id)a0 section:(long long)a1 index:(long long)a2;
- (void)trackerGoToTopShow;
- (void)trackerMainRequestStatus;
- (void)homePageEndRefreshing;
- (void)trackerLoadmorePerformance;
- (void)trackerLoadmoreRequestStatus;
- (void)__resetLoadmorePerfProps;
- (void)finishRefreshMainList:(id)a0;
- (void)setGreyIfNeed:(id)a0;
- (void)initMultiTabConfig:(id)a0;
- (void)__updateLastPageCountWithFeed:(id)a0;
- (void)disableUserInteractionIfShowCardAnimationWithListModel:(id)a0;
- (void)handleCoinsPop:(id)a0;
- (void)__updateNextPageCountWithFeed:(id)a0;
- (void)handleFavoriteSectionIfEmpty:(id)a0;
- (void)setupTimingModelProps;
- (void)setFooterEndRefreshing;
- (void)setupLiveMiniWindow;
- (void)forceReportShowTrackIfNeed:(id)a0;
- (id)buildNativePopupManager:(id)a0;
- (void)handleMallTabSelectedEvent:(id)a0 type:(id)a1;
- (void)mallRefreshHomepageEvent:(id)a0;
- (void)sendMallReportTrackerNative:(id)a0;
- (void)topBarChangeNoVisible:(id)a0;
- (void)bottomBarChangeNoVisible:(id)a0;
- (void)handleFeedLoadingError:(id)a0;
- (void)openNativeSKU:(id)a0;
- (BOOL)hasScrollAfterRequestFeed;
- (void)__resetFeedRequestTempData;
- (void)handleSwitchTabPanelShow:(id)a0;
- (void)handleSwitchTabPanelHide:(id)a0;
- (void)handleTopSwitchTabPanelShow:(id)a0;
- (void)handleTopSwitchTabPanelHide:(id)a0;
- (id)getCurrentExposingFilter;
- (void)canShowNewLoadingForCDN;
- (id)currentBundleConfigUrl;
- (void)resetSearchPitaya;
- (BOOL)needCookingNotification:(id)a0;
- (void)stopCoinsViewCountDown;
- (void)trackerScrollToTop;
- (BOOL)shouldRequestSelectedSection:(id)a0;
- (void)realRequestByPageCard:(id)a0 apiKeys:(id)a1 withHandler:(id /* block */)a2 forbidEvent:(BOOL)a3;
- (void)scrollToVisible:(BOOL)a0 animation:(BOOL)a1;
- (void)updateSpecificSectionForFeed:(id)a0;
- (BOOL)hasScrollAfterRequestGYL;
- (void)requestFeedResetNoMoreData;
- (void)realHandleSwitchTabPanelShow:(id)a0;
- (void)realHandleSwitchTabPanelHide:(id)a0;
- (void)trackerSwitchPanel;
- (id)holdTaskConfig;
- (void)sendBlockMallPopupEvent:(BOOL)a0;
- (void)checkAndExecuteSkeletonRendered;
- (void)skeletonRendered;
- (void)loadMoreTimeOutHandler;
- (void)__appendListModel;
- (void)__removeTempData;
- (void)trackerRealLoadmoreRequestWithSource:(unsigned long long)a0;
- (void)realRequestByPageCardReport:(id)a0 isTimeout:(BOOL)a1 startTime:(double)a2 useWhiteBoard:(BOOL)a3;
- (void)updateBackgroundColorInNeeded:(double)a0;
- (void)resetListViewBgColor;
- (void)trackerScrollGYLWithScrollView:(id)a0;
- (void)showCardAnimationWithCellModel:(id)a0 cell:(id)a1 first:(BOOL)a2;
- (BOOL)marqueeViewRectEqualToRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (BOOL)isMallListEnableNested;
- (id)mallJsbDenylist;
- (id)mallPopupViewHmBid;
- (BOOL)mallPopupViewEnableOptLynxViewLoadLogic;
- (void)delayDismissLoadingViewForCDN:(id)a0;
- (void)lynxCardWillChangeAutoPlayState:(BOOL)a0;
- (void)addSlideGestureForMultiTab;
- (void)initTabDataPrefetcher;
- (void)handleSlideForMultiTab:(id)a0;
- (void)switchCategory:(id)a0 headerView:(id)a1;
- (id)slideNextCategoryTabInfo:(id)a0;
- (void)trackMallSwitchTabUserAction:(id)a0 type:(id)a1;
- (id)getOpenPopupByNativeConfig;
- (void)feedViewController:(id)a0 feedback:(id)a1;
- (id)currentEnvIdentifierForPopup:(id)a0;
- (id)mallPopupViewHybridMonitorContext;
- (id)currentEnvIdentifierForPageCard:(id)a0;
- (id)mallPageCardHybridMonitorContext;
- (id)mallPageCardHmBid;
- (id)whiteBoardForPageCard:(id)a0;
- (void)lynxCardDidFinishLoad:(id)a0 resource:(id)a1 itemModel:(id)a2;
- (void)lynxCardReceiveError:(id)a0 resource:(id)a1 itemModel:(id)a2;
- (void)compensateVisibilityChage:(BOOL)a0;
- (void)refreshImmerseFullScreenCompensationRealData;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })insertItem:(id)a0 inSection:(id)a1 atIndex:(unsigned long long)a2 animated:(BOOL)a3;
- (BOOL)enableStraightOutRender;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getSearchBarFrame;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getToolBarFrame;
- (void)setCustomLoadMoreView:(id)a0;
- (void)setCustomNoMoreView:(id)a0;
- (void)setupNeedlessComponents:(id)a0;
- (id)currentFilters;
- (void)trackGYLFetchByAction:(id)a0;
- (id)__sceneName;
- (void).cxx_destruct;
- (id)init;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (void)sendAction:(id)a0;
- (void)viewWillAppear:(BOOL)a0;
- (void)appDidEnterBackground:(id)a0;
- (void)appWillResignActive:(id)a0;
- (void)scrollToTopAnimated:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)appDidBecomeActive:(id)a0;
- (void)appWillEnterForeground:(id)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)showLoadingView;
- (void)addNotificationObserver;
- (id)envIdentifier;
- (id)pageName;
- (void)buildConstraints;

@end
