@class IESECYataSKUContext, IESECYataGeneralService, UICollectionView, IESECSKUEventsImpl, IESECSKUSkeletonView, IESECSKUMultiBuySkeletonView, IESECYataPopupContaienrView, IESECSKUErrorView, IESECSKUScrollToViewInstance, UIView, NSString, IESECSKUDataController, UIStackView, IESECBuyNowTextFieldController, IESECSKUErrorViewModel, IESECDurationHelper, IESECSKUSliceViewClickInstance;
@protocol YataInstanceInterface;

@interface IESECYataSKUView : UIView <YataDependencyProvider, IESECSKUErrorViewDelegate, IESECSKUSkeletonViewDelegate, IESECSKUEventsDelegate, IESECHalfPageFloatContainerDelegate, IESECSKUErrorViewContainer, YataPopupContainerDelegate, IESECSKUViewProtocol, YataScrollViewDelegate, YataCallbackInterface, YataTrackService>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) IESECYataSKUContext *context;
@property (retain, nonatomic) id<YataInstanceInterface> yataInstance;
@property (retain, nonatomic) IESECSKUDataController *dataController;
@property (retain, nonatomic) IESECDurationHelper *stay;
@property (retain, nonatomic) IESECSKUEventsImpl *eventImpl;
@property (retain, nonatomic) IESECYataGeneralService *generalService;
@property (retain, nonatomic) IESECBuyNowTextFieldController *textFieldController;
@property (retain, nonatomic) IESECYataPopupContaienrView *popupContainerView;
@property (retain, nonatomic) UIView *skuMaskView;
@property (retain, nonatomic) UIView *panelContainer;
@property (retain, nonatomic) UIStackView *yataTopBanner;
@property (retain, nonatomic) UIStackView *yataHeader;
@property (retain, nonatomic) UICollectionView *yataCollectionView;
@property (retain, nonatomic) UIStackView *yataFooter;
@property (retain, nonatomic) IESECSKUSkeletonView *skeletonView;
@property (retain, nonatomic) IESECSKUMultiBuySkeletonView *multiSkeletonView;
@property (retain, nonatomic) IESECSKUErrorView *errorView;
@property (retain, nonatomic) IESECSKUErrorViewModel *errorViewModel;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } wholeFrame;
@property (nonatomic) long long stashedQueryStatus;
@property (nonatomic) long long panelShowState;
@property (nonatomic) BOOL animationFinished;
@property (retain, nonatomic) IESECSKUScrollToViewInstance *anchorInstance;
@property (retain, nonatomic) IESECSKUSliceViewClickInstance *clickAfterUplinkInstance;
@property (nonatomic) BOOL disableReconnect;
@property (nonatomic) BOOL isInvalid;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)onFetchBegin:(id)a0;
- (BOOL)onFetchEndBizValidWithDataObject:(id)a0;
- (void)onProtocolDispatchEnd:(unsigned long long)a0;
- (void)onProtocolReloadEnd:(unsigned long long)a0 success:(BOOL)a1;
- (void)popupWillShow:(id)a0 popupCount:(long long)a1;
- (void)popupDidShow:(id)a0 popupCount:(long long)a1 containerDict:(id)a2;
- (void)popupWillDismiss:(id)a0 popupCount:(long long)a1 containerDict:(id)a2;
- (void)popupDidDismiss:(id)a0 popupCount:(long long)a1;
- (void)popupMaskClick:(id)a0 containerDict:(id)a1;
- (BOOL)shouldTriggerEventWithType:(id)a0 renderObject:(id)a1 triggerParams:(id)a2;
- (void)container:(id)a0 showResult:(BOOL)a1;
- (id)yata_sessionID;
- (id)yata_bizCode;
- (id)yata_body;
- (id)yata_scrollForwardDelegate;
- (id)yata_renderConfig;
- (id)yata_netBizConfigDelegate;
- (id)yata_callbackInterface;
- (id)yata_popupContainerConfigDelegate;
- (id)yata_extendFieldsNameArray;
- (id)yata_trackerService;
- (id)yata_toastService;
- (id)yata_routerService;
- (id)yata_eventImpl;
- (id)yataPopupContainerView;
- (void)trackWithEventName:(id)a0 params:(id)a1;
- (void)configBtmTrackerV2;
- (void)configBtmTracker;
- (void)showWithAnimation:(id /* block */)a0 completion:(id /* block */)a1;
- (void)addErrorView;
- (void)tapMaskView;
- (void)removeSkeletonView;
- (void)addSkeletonView;
- (id)skuView;
- (void)dismissWithAnimation:(id /* block */)a0 closeType:(long long)a1 completion:(id /* block */)a2;
- (void)updateSKUFromUpdatedSKUInfo:(id)a0;
- (id)yataInstanceObj;
- (void)scrollToViewWithInstance:(id)a0;
- (id)uplinkController;
- (void)updateCommonEventParams:(id)a0;
- (void)trackMediaWithEventName:(id)a0 params:(id)a1;
- (id)getRenderObjectWithRenderInfo:(id)a0;
- (void)setupBTM;
- (void)p_handleDuplicatedAnimation:(id /* block */)a0 completion:(id /* block */)a1;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })originPanelFrame;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })finalPanelFrame;
- (void)updateTopFloatBannerIfNeeded;
- (void)p_manageTopFloatViewToShow:(BOOL)a0;
- (void)renewMaskViewAlpha;
- (void)renewPanelContainerHeight;
- (id)yata_footer;
- (id)yata_header;
- (void)preloadSliceXTemplates;
- (void)setupYataInstance;
- (void)autoScrollIfNeeded;
- (void)updateViewConstraintsWithErrorType:(unsigned long long)a0;
- (id)provideErrorView;
- (double)viewSizeScale;
- (void)setupDataController;
- (id)yataBizCode;
- (void)requestQueryWithCompletion:(id /* block */)a0;
- (void)viewClickedAfterUplinkWithInstance:(id)a0;
- (BOOL)cancelStashedClickEvent;
- (void)updateAfterFirstQueryRequest:(BOOL)a0;
- (void)updateAfterFirstQueryRequestSuccess;
- (void)scrollToRenterObject;
- (void)updateResponseRelatedData;
- (void)p_updateTrackerCommonParams;
- (void)handleStashedClickEventIfNeeded;
- (void)dismissWithAnimation:(id /* block */)a0 completion:(id /* block */)a1;
- (void)reconnect;
- (void)close;
- (void).cxx_destruct;
- (id)initWithContext:(id)a0;
- (void)registerNotifications;
- (void)connect;
- (id)dataDelegate;
- (void)scrollViewDidScroll:(id)a0;
- (id)delegate;
- (void)dealloc;
- (void)didMoveToWindow;
- (void)removeNotifications;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)setupUI;
- (void)removeErrorView;
- (id)heightPercent;

@end
