@class IESECTabKitTabPerfInfo, NSString, UIView, IESECTabKitDIContext, NSMutableDictionary, NSDictionary, LynxView, IESECTabKitTabSetting, NSMutableArray, IESECTabKitTabModel, IESECServiceProxy, UIScrollView;
@protocol IESECTabKitPuzzleTabDelegate, IESECTabKitEventService, IESHYContainerProtocol, IESECTabKitEventSubscriber, IESECTabKitDataService, IESECTabKitAbilityService, IESECTabKitMonitorService, IESECTabKitTabElementDelegate, IESECTabKitMarketingService;

@interface IESECTabKitPuzzleTabElement : UIViewController <LynxViewLifecycle, IESHYHybridViewLifecycleProtocol, LynxScrollListener, IESECTabKitTabElementProtocol, IESECTabKitPuzzleTabElement> {
    UIView<IESHYContainerProtocol> *_hybridContainer;
    NSMutableArray *_bridges;
    BOOL _isScrollViewRendered;
    LynxView *_lynxView;
    NSString *_bizTag;
    BOOL _isFirstAppearance;
    NSString *_statusBarColor;
    BOOL _isReportMonitor;
}

@property (weak, nonatomic) IESECTabKitDIContext *context;
@property (retain, nonatomic) IESECTabKitTabPerfInfo *tabPerfInfo;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitMonitorService> *monitorService;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitEventService, IESECTabKitEventSubscriber> *eventService;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitDataService> *dataService;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitAbilityService> *abilityService;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitMarketingService> *marketingService;
@property (retain, nonatomic) NSMutableDictionary *perfFlag;
@property (readonly, nonatomic) BOOL bdx_statusBarHidden;
@property (readonly, nonatomic) long long bdx_statusBarStyle;
@property (nonatomic) BOOL readyToUpdate;
@property (retain, nonatomic) NSDictionary *syncUpdateData;
@property (nonatomic) BOOL didInjectData;
@property (retain, nonatomic) IESECTabKitTabSetting *tabSetting;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<IESECTabKitTabElementDelegate> delegate;
@property (readonly, nonatomic) UIScrollView *scrollView;
@property (readonly, nonatomic) long long statusBarStyle;
@property (readonly, nonatomic) IESECTabKitTabModel *tabModel;
@property (copy, nonatomic) NSDictionary *customBtmParams;
@property (weak, nonatomic) id<IESECTabKitPuzzleTabDelegate> puzzleDelegate;
@property (copy, nonatomic) NSString *url;
@property (copy, nonatomic) NSDictionary *initialData;
@property (copy, nonatomic) NSDictionary *routerParams;
@property (copy, nonatomic) NSDictionary *customGlobalProps;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } preferredFrame;
@property (nonatomic) unsigned long long containerType;

- (void)viewDidFinishLoadWithURL:(id)a0;
- (void)viewDidPageUpdate;
- (void)viewDidLoadFailedWithUrl:(id)a0 error:(id)a1;
- (void)sendEvent:(id)a0 params:(id)a1;
- (void)viewDidCreated:(id)a0;
- (id)hmdPageExtension;
- (void)lynxView:(id)a0 onUpdate:(id)a1 timing:(id)a2;
- (void)lynxViewDidConstructJSRuntime:(id)a0;
- (void)registerBridge:(id)a0;
- (unsigned long long)kernalType;
- (void)closeHybridWithCompletion:(id /* block */)a0;
- (BOOL)viewShouldAllowLoadWithResponse:(id)a0;
- (void)scrollerWillBeginDragging:(id)a0;
- (void)scrollerDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)scrollerDidEndDecelerating:(id)a0;
- (void)registerBridges;
- (void)cancelTimeoutCallback;
- (void)viewVisibilityChange:(BOOL)a0;
- (void)p_registerBridge:(id)a0;
- (void)loadHybridContainer;
- (void)reportMonitor;
- (void)observeScrollViewDidScroll;
- (void)preloadWithTabModel:(id)a0;
- (void)tabLoadTimeout;
- (void)triggerNativePrefetchIfNeeded;
- (id)createHybridContainer;
- (void)loadUIConfigs:(id)a0;
- (id)createPuzzleContext;
- (id)createPuzzleConfig;
- (BOOL)enableSyncUpdate;
- (id)_syncUpdateDataFromPrefetch:(id)a0;
- (void)_updateLynxData:(id)a0 updateFrom:(id)a1;
- (id)curPerfTimingMetric;
- (BOOL)hiddenStatusBar;
- (void)reloadWithTabModel:(id)a0;
- (void)updateQueryItems:(id)a0;
- (void)updateBundleUrlIfNeeded;
- (void)load;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (id)initWithContext:(id)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)loadIfNeeded;
- (void)viewWillDisappear:(BOOL)a0;

@end
