@class IESECLiveGoodsListDataStore, IESECLiveGoodsListCollectionService, IESECLiveListHeaderStyleControl, IESECLiveContext, NSDictionary, IESECLiveGoodsListClickContext, IESECLiveListSkinConfig, IESECLiveGoodsListPageModel, IESECLiveGoodsListHeaderService, IESECLiveListHeaderSearchBarInfo, IESECLiveGoodsListItemViewModel, IESECLiveGoodsViewModel, NSString, IESECLiveGoodsListServiceManager, IESECLiveGoodsListBannerInfoModel, NSArray;
@protocol HTSKVStore, IESECLiveListViewModelDelegateV2;

@interface IESECLiveGoodsListViewModelV2 : NSObject <IESECLiveGoodsListDataStoreDataSource, IESECLiveGoodsModelUpdaterDataSource, IESECLiveGoodsListViewModelProtocol>

@property (retain, nonatomic) IESECLiveContext *liveContext;
@property (retain, nonatomic) IESECLiveGoodsListPageModel *listModel;
@property (nonatomic) BOOL goodsListViewOnShow;
@property (retain, nonatomic) IESECLiveGoodsListServiceManager *serviceManager;
@property (retain, nonatomic) IESECLiveGoodsListCollectionService *collectionService;
@property (weak, nonatomic) IESECLiveGoodsListHeaderService *headerService;
@property (retain, nonatomic) NSString *lastPromotionIDShowedBgEnhanceView;
@property (retain, nonatomic) id<HTSKVStore> kvStore;
@property (weak, nonatomic) id<IESECLiveListViewModelDelegateV2> delegate;
@property (readonly, nonatomic) IESECLiveGoodsListClickContext *clickContext;
@property (retain, nonatomic) IESECLiveGoodsListDataStore *dataStore;
@property (nonatomic) BOOL fetchBeforeViewCreated;
@property (readonly, nonatomic) IESECLiveGoodsViewModel *introducingGoodsViewModel;
@property (weak, nonatomic) id uiPage;
@property (nonatomic) long long tabType;
@property (readonly, nonatomic) NSArray *tabModels;
@property (retain, nonatomic) IESECLiveListSkinConfig *skinConfig;
@property (readonly, nonatomic) NSDictionary *trackDic;
@property (retain, nonatomic) NSArray *itemViewModelsOnShow;
@property (readonly, nonatomic) NSArray *allGoodsViewModels;
@property (readonly, nonatomic) long long selectedTabIndex;
@property (readonly, copy, nonatomic) NSString *emptyText;
@property (readonly, nonatomic) BOOL isCouponGoodsList;
@property (nonatomic) BOOL isSecondary;
@property (readonly, nonatomic) IESECLiveGoodsListBannerInfoModel *commonBanner;
@property (retain, nonatomic) IESECLiveListHeaderSearchBarInfo *lastSearchBarInfo;
@property (nonatomic) BOOL hasFetchedData;
@property (nonatomic) BOOL hasPreloadedData;
@property (nonatomic) BOOL isPreloadCacheHit;
@property (nonatomic) BOOL listOpenRegionContentEverLoad;
@property (readonly, nonatomic) BOOL showAuthorConnect;
@property (readonly, nonatomic) BOOL showSliderAuthorConnect;
@property (nonatomic) long long cartEnhanceStyle;
@property (nonatomic) long long cartCount;
@property (readonly, nonatomic) BOOL useGoodsAddCartAnimation;
@property (readonly, nonatomic) BOOL useLargerAddCartAnimation;
@property (readonly, nonatomic) BOOL useRedCartIcon;
@property (readonly, nonatomic) BOOL useLargeCartIcon;
@property (readonly, nonatomic) BOOL useCartCountDot;
@property (readonly, nonatomic) BOOL vibeViewDisabled;
@property (nonatomic) BOOL forbidRefreshOnBack;
@property (nonatomic) BOOL waitForceRefresh;
@property (retain, nonatomic) IESECLiveListHeaderStyleControl *headerStyleControl;
@property (nonatomic) BOOL alreadyShowedData;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy, nonatomic) NSString *bottomText;
@property (readonly, nonatomic) IESECLiveGoodsListItemViewModel *guideItem;
@property (nonatomic) BOOL shouldShowBottomGuideView;
@property (readonly, nonatomic) double bottomGuideHeight;
@property (readonly, nonatomic) NSArray *services;

- (id)ecomEntranceForm;
- (id)searchSchema;
- (id)trackDictionary;
- (void)updateListModel:(id)a0;
- (id)basicTrackParams;
- (id)initWithLiveContext:(id)a0;
- (BOOL)enableLiveListAnchorAdapter;
- (void)changeStore:(id)a0 completion:(id /* block */)a1;
- (BOOL)isInstantStore;
- (id)p_recordKeyWithKey:(id)a0;
- (void)refreshListBanner;
- (id)goodsItemViewModelWithPromotionID:(id)a0;
- (id)goodsItemViewModelOnShowWithPromotionID:(id)a0;
- (void)liveGoodsListWillAppear;
- (void)liveGoodsListDidAppear;
- (void)liveGoodsListWillDisappear;
- (void)liveGoodsListDidDisappear;
- (void)liveGoodsListDidScroll:(id)a0;
- (void)liveGoodsListWillBeginDragging;
- (void)closeListView;
- (id)itemViewModelFromGoodsViewModel:(id)a0;
- (void)updateGoodsWithType:(long long)a0 atIndexPaths:(id)a1 extraInfo:(id)a2;
- (void)loadPreviousPageData;
- (id)promotionIDToShowBgEnhanceView;
- (id)goodsItemViewModelAtIndex:(long long)a0;
- (BOOL)isInstantStoreShortBuyButton;
- (long long)getAddCartAnimationStyle;
- (void)performListUpdateWithForceReload:(BOOL)a0;
- (BOOL)useInstantStoreCartIcon;
- (long long)getListBusinessType;
- (BOOL)hasListView;
- (BOOL)enableRefreshListMessage;
- (id)fetchParams;
- (id)goodsModelsWithProductID:(id)a0;
- (void)updateGoodsWithProductID:(id)a0;
- (id)p_listCacheFetchParams;
- (void)fetchGoodsListWithRefreshInfo:(id)a0;
- (void)updateReservationGoodsWithPromotionID:(id)a0;
- (void)updateGoodsListWithCartList:(id)a0;
- (void)updateGoodsWithProductID:(id)a0 cartNum:(id)a1;
- (unsigned long long)indexOfGoodsModelWithPromotionID:(id)a0;
- (void)disablePageDataWithUniqueKey:(id)a0;
- (void)clearPromotionBottomCacheAndNoticeJumpToOtherPage;
- (void)excuteCartCount;
- (BOOL)openFromEnterRoomSchema;
- (void)listShowToast:(id)a0;
- (id)indexPathsForProductIds:(id)a0;
- (id)indexPathsForPromotionIds:(id)a0;
- (void)dataStoreGoodsDidChange;
- (BOOL)checkGuideIfNeededWithKey:(id)a0;
- (id)getSingleGuideInfoWithKey:(id)a0;
- (void)updateGuideInfoWithDict:(id)a0 bizKey:(id)a1;
- (long long)searchButtonStyle;
- (BOOL)listExistEnableForceRefresh;
- (BOOL)listNotExistEnableForceRefresh;
- (id)allGoodsModelOnShow;
- (BOOL)enableForceRefresh;
- (void)p_delegateShowToastWithExtraInfo:(id)a0;
- (id)p_fetchParams;
- (id)fetchParamsOfGoodsModelUpdater:(id)a0;
- (id)goodsModelToBeUpdatedOfGoodsModelUpdater:(id)a0;
- (id)allGoodsViewModelsOfGoodsModelUpdater:(id)a0;
- (id)allExistGoodsModelsOfGoodsModelUpdater:(id)a0;
- (BOOL)goodsListIsShowing;
- (id)listABConfigInfo;
- (id)getGoodsItemViewModelWithPromotionID:(id)a0;
- (void)openListViewWithParams:(id)a0;
- (id)getLynxBasicInitialDataWithParams:(id)a0;
- (void)fetchGeckoInfoIfNeed;
- (void)prefetch;
- (void).cxx_destruct;
- (BOOL)hasNextPage;

@end
