@class UIView, IESECTracker, NSString, IESECDurationHelper, IESECHighlightButton, IESECSKUViewModel, IESECSKUFloatBannerView, IESECSKUDetailContext, IESECSKUContentView, IESECSKUErrorView;
@protocol IESECSKUBottomViewProtocol, IESECEmptyViewProtocol, IESECSKUViewDelegate, IESECSKUTopViewProtocol;

@interface IESECSKUView : UIView <IESECSKUBottomViewDelegate, IESECSKUContentViewDelegate, IESECSKUTopViewDelegate, IESECSKUFloatBannerViewDelegate, IESECHalfPageFloatContainerDelegate, IESECSKUErrorViewDelegate, IESECSKUViewProtocol>

@property (weak, nonatomic) id<IESECSKUViewDelegate> delegate;
@property (retain, nonatomic) IESECSKUDetailContext *detailContext;
@property (retain, nonatomic) IESECTracker *tracker;
@property (retain, nonatomic) IESECSKUViewModel *viewModel;
@property (retain, nonatomic) IESECSKUFloatBannerView *topFloatView;
@property (retain, nonatomic) UIView<IESECSKUTopViewProtocol> *topView;
@property (retain, nonatomic) UIView<IESECSKUBottomViewProtocol> *bottomView;
@property (retain, nonatomic) IESECSKUContentView *contentView;
@property (retain, nonatomic) IESECHighlightButton *closeButton;
@property (retain, nonatomic) id<IESECEmptyViewProtocol> errorView;
@property (retain, nonatomic) UIView *loadingView;
@property (retain, nonatomic) IESECSKUErrorView *retryView;
@property (retain, nonatomic) IESECDurationHelper *stay;
@property (nonatomic) long long panelShowState;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } wholeFrame;
@property (retain, nonatomic) UIView *skuMaskView;
@property (retain, nonatomic) UIView *panelContainer;
@property (retain, nonatomic) NSString *closeTimeStamp;
@property (nonatomic) BOOL showedAddCartGuide;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL disableReconnect;
@property (nonatomic) BOOL isInvalid;

- (void)container:(id)a0 showResult:(BOOL)a1;
- (BOOL)shouldClosePanelWithCloseType:(long long)a0;
- (void)configBtmTrackerV2;
- (void)configBtmTracker;
- (void)showWithAnimation:(id /* block */)a0 completion:(id /* block */)a1;
- (void)tapMaskView;
- (void)tapCloseButton;
- (void)dismissWithAnimation:(id /* block */)a0 closeType:(long long)a1 completion:(id /* block */)a2;
- (void)updateSKUFromUpdatedSKUInfo:(id)a0;
- (void)setupHybridEventSubscriber;
- (void)setupBTM;
- (void)p_handleDuplicatedAnimation:(id /* block */)a0 completion:(id /* block */)a1;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })originPanelFrame;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })finalPanelFrame;
- (void)updateTopFloatBannerIfNeeded;
- (void)p_manageTopFloatViewToShow:(BOOL)a0;
- (void)renewMaskViewAlpha;
- (void)renewPanelContainerHeight;
- (void)setupMasonry;
- (void)reloadSKUView;
- (void)skuSelectChanged:(id)a0;
- (void)openCouponPanel;
- (void)openPOIListWithURLString:(id)a0;
- (void)clickTradeInItem:(id)a0;
- (void)soldOutCountDownDidFinish;
- (id)initWithDetailContext:(id)a0;
- (void)floatBannerViewDidShow:(id)a0 withTrustTags:(id)a1;
- (void)floatBannerView:(id)a0 didShowedContents:(id)a1 isTrustTag:(BOOL)a2;
- (void)openURL:(id)a0 withBTMToken:(id)a1 buttonStatus:(long long)a2;
- (void)trackCoverImageTapped;
- (void)openDetail;
- (void)loadSKUView;
- (void)skuDouSelectChanged:(id)a0;
- (void)reloadSKUViewWithShowLoading:(BOOL)a0 onEnter:(BOOL)a1;
- (void)updateSKUWithUpdatedPOIInfo:(id)a0;
- (id)fixEntranceInfoWithBCM:(id)a0 entranceInfoKey:(id)a1;
- (id)p_monitorPageShowPerformance;
- (void)monitorOpenSkuEndWithDuration:(double)a0;
- (void)addSearchParamsToTrackParams:(id)a0;
- (void)addSaaSParamsToTrackParams:(id)a0;
- (BOOL)needShowAddCartGuide;
- (void)addCartGuidePopoverDialog;
- (BOOL)showAddCartGuidePreCondition;
- (void)closeSKUPannel:(id)a0 closeType:(long long)a1;
- (BOOL)showAddCartGuideFreqCondition;
- (void)p_addToCartWithBTMToken:(id)a0;
- (void)doBottomActionWithType:(long long)a0 completion:(id /* block */)a1;
- (BOOL)p_handleSubActionIfNeeded;
- (id)configPriceInfoTrackerParams;
- (id)p_doBottomActionUpdatedTrackParams;
- (void)p_selectAction;
- (void)p_buynowAction:(id)a0;
- (void)dismissWithAnimation:(id /* block */)a0 completion:(id /* block */)a1;
- (void)confirmTapped;
- (void)reconnect;
- (void)close;
- (void).cxx_destruct;
- (void)removeFromSuperview;
- (void)updateConstraints;
- (void)dealloc;
- (void)didMoveToWindow;
- (void)reloadViews;
- (id)heightPercent;

@end
