@class IESECTabKitRouterParameters, IESECTabKitContainerStatusVC, NSString, IESECTabKitContainerAPI, IESECTabKitDIContext, IESECTabKitBFFModel, UIColor, IESECTabKitBackgroundView, UIViewController, IESECTabKitTabModel, IESECTabKitBFFController, IESECServiceProxy;
@protocol IESECTabKitHybridService, IESECTabKitPreProcessService, IESECTabKitDataService, IESECTabKitContainerTrackService, UIGestureRecognizerDelegate, IESECTabKitAbilityService, IESECTabKitMonitorService, IESECTabKitMarketingService;

@interface IESECTabKitContainerVC : UIViewController <UIGestureRecognizerDelegate, IESECTabKitBFFControllerDelegate, IESECTaskBannerContainerProtocol> {
    IESECTabKitRouterParameters *_parameters;
    IESECTabKitTabModel *_currentTabItem;
    Class _pageDisplayCycle;
    BOOL _isFirstViewWillAppear;
    BOOL _isFirstViewDidAppear;
    IESECTabKitDIContext *_context;
    IESECTabKitBFFModel *_bffModel;
    UIColor *_containerBgColor;
    id<UIGestureRecognizerDelegate> _preInteractivePopGestureRecognizer;
}

@property (retain, nonatomic) IESECTabKitContainerAPI *api;
@property (retain, nonatomic) IESECTabKitBFFController *tabKitVC;
@property (retain, nonatomic) IESECTabKitContainerStatusVC *statusVC;
@property (retain, nonatomic) IESECTabKitBackgroundView *backgroundView;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitMonitorService> *monitorService;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitContainerTrackService> *trackService;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitHybridService> *hybridService;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitAbilityService> *abilityService;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitDataService> *dataService;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitPreProcessService> *preprocessService;
@property (retain, nonatomic) IESECServiceProxy<IESECTabKitMarketingService> *marketingService;
@property (weak, nonatomic) UIViewController *fromVC;
@property (readonly, nonatomic) IESECTabKitRouterParameters *parameters;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (BOOL)aweDisableFullscreenPopTransition;
- (void)hostInjectionViewWillDisappear;
- (void)hostInjectionDidOpenPage;
- (void)hostInjectionWillClosePage;
- (void)hostInjectionWillOpenNextPage;
- (void)hostInjectionPageWillAppearAgain;
- (long long)currentPageContentMode;
- (id)taskBannerContainerView;
- (void)triggerNativePrefetchIfNeeded;
- (void)loadFirstScreenTab:(id)a0;
- (void)triggerSSRIfNeeded;
- (void)configTabKitUI;
- (void)setupGrayModeIfNeeded;
- (BOOL)checkInitializeData;
- (void)hostInjectionDidPageSwitchMode;
- (id)navItemTrackExtraParams:(id)a0;
- (void)trackEvents:(id)a0 extraParams:(id)a1;
- (id)btmParamsWithTabItem:(id)a0;
- (void)trackEvents:(id)a0 extraParams:(id)a1 btmParams:(id)a2;
- (void)trackOnceEvents:(id)a0 withOnceKey:(id)a1;
- (id)tabItemTrackExtraParams:(id)a0;
- (id)tabItemTrackExtraParamsForClick:(id)a0;
- (void)hostInjectionFirstScreenPage;
- (void)hostInjectionDidPageScroll:(double)a0;
- (id)pageDisplayExtraDict;
- (id)dynamicTrackParams;
- (void)appendPrefetchRes:(id)a0;
- (void)tabKitController:(id)a0 tabItem:(id)a1 visibilityDidChange:(BOOL)a2;
- (void)tabKitController:(id)a0 tabItem:(id)a1 hybridViewDidScroll:(id)a2;
- (void)tabKitController:(id)a0 tabItem:(id)a1 hybridLifeCycle:(id)a2 timestamp:(double)a3 params:(id)a4;
- (void)tabKitController:(id)a0 didUpdateScreenState:(unsigned long long)a1;
- (void)tabKitControllerNeedsUpdateStatusBarStyle:(id)a0;
- (void)tabKitController:(id)a0 didDisplayNavItem:(id)a1;
- (void)tabKitController:(id)a0 didSelectNavItem:(id)a1;
- (void)tabKitController:(id)a0 willDisplayTopTabItem:(id)a1;
- (void)tabKitController:(id)a0 willDisplayBottomTabItem:(id)a1;
- (void)tabKitController:(id)a0 didTapAtTopTabItem:(id)a1;
- (void)tabKitController:(id)a0 didTapAtBottomTabItem:(id)a1;
- (void)tabKitController:(id)a0 didMoveToTabItem:(id)a1 moveType:(unsigned long long)a2;
- (void)tabKitController:(id)a0 willMoveToTabItem:(id)a1;
- (void)tabKitController:(id)a0 firstScreenLoaded:(id)a1;
- (void)clearWarmupProcess;
- (void)applicationWillResignActive:(id)a0;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (BOOL)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (BOOL)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillAppear:(BOOL)a0;
- (BOOL)gestureRecognizer:(id)a0 shouldBeRequiredToFailByGestureRecognizer:(id)a1;
- (id)initWithParameters:(id)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)requestData;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)addNotificationObserver;

@end
