@class IESECSlidingTabScrollView, UIView, NSArray, NSString, NSDictionary, NSMutableArray, CAGradientLayer, IESECSlidingTabButton, NSMutableSet, UIColor;
@protocol IESECSlidingTabbarDelegate, IESECSlidingTabbarLayoutDelegate, IESECSlidingTabContainerProtocol;

@interface IESECSlidingTabbarView : UIView <IESECSlidingTabButtonLayoutDelegate, IESECSlidingTabbarProtocol> {
    struct { unsigned char hasImplWidthForSegmentAtIndex : 1; unsigned char hasImplInsetForSegmentAtIndex : 1; unsigned char hasLayout : 1; unsigned char isAnimating : 1; unsigned char isTabClicked : 1; unsigned char needsReload : 1; } _mState;
    struct UIEdgeInsets { double top; double left; double bottom; double right; } _originSegmentEdgeInset;
    NSMutableSet *_selectedButtonIndexes;
}

@property (nonatomic) BOOL scrollEnabled;
@property (retain, nonatomic) UIView *indicatorView;
@property (retain, nonatomic) IESECSlidingTabScrollView *contentScrollView;
@property (retain, nonatomic) NSMutableArray *tabButtons;
@property (copy, nonatomic) NSArray *segmentWidthsArray;
@property (retain, nonatomic) NSMutableArray *innerAttributedTitles;
@property (retain, nonatomic) NSMutableArray *innerSelectedAttributedTitles;
@property (weak, nonatomic) id<IESECSlidingTabbarDelegate> delegate;
@property (readonly, nonatomic) long long tabsCount;
@property (nonatomic) BOOL enableForwardHitTest;
@property (nonatomic) BOOL shouldCenterSelectedButton;
@property (copy, nonatomic) NSArray *tabInfos;
@property (copy, nonatomic) NSDictionary *titleAttributes;
@property (copy, nonatomic) NSDictionary *selectedTitleAttributes;
@property (nonatomic) long long hLayoutAlignment;
@property (nonatomic) long long vLayoutAlignment;
@property (nonatomic) struct UIEdgeInsets { double top; double left; double bottom; double right; } contentInset;
@property (nonatomic) double contentFixedHeight;
@property (nonatomic) long long widthStyle;
@property (nonatomic) long long imagePostion;
@property (nonatomic) double segmentMinimumWidth;
@property (nonatomic) struct UIEdgeInsets { double top; double left; double bottom; double right; } segmentEdgeInset;
@property (nonatomic) BOOL enableSegmentEdgeInsetAdjustment;
@property (nonatomic) struct CGSize { double width; double height; } iconSize;
@property (nonatomic) struct CGSize { double width; double height; } selectedIconSize;
@property (nonatomic) BOOL enableAnimatedIcon;
@property (nonatomic) struct UIEdgeInsets { double top; double left; double bottom; double right; } scrollViewInset;
@property (nonatomic) double iconPadding;
@property (weak, nonatomic) id<IESECSlidingTabbarLayoutDelegate> layoutDelegate;
@property (copy, nonatomic) id /* block */ configTabBlock;
@property (nonatomic) long long indicatorStyle;
@property (nonatomic) struct UIEdgeInsets { double top; double left; double bottom; double right; } indicatorEdgeInsets;
@property (nonatomic) double indicatorFixedWidth;
@property (nonatomic) double indicatorMinimumWidth;
@property (nonatomic) double indicatorHeight;
@property (nonatomic) double indicatorCornerRadius;
@property (retain, nonatomic) UIColor *indicatorColor;
@property (retain, nonatomic) CAGradientLayer *indicatorGradientLayer;
@property (nonatomic, getter=isIndicatorTracked) BOOL indicatorTracked;
@property (nonatomic) BOOL enableSwitchAnimation;
@property (nonatomic) BOOL hiddenIndicator;
@property (nonatomic) long long selectedIndex;
@property (nonatomic) long long preButtonCount;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, weak, nonatomic) id<IESECSlidingTabContainerProtocol> slidingContainer;
@property (readonly, nonatomic) IESECSlidingTabButton *currentSelectedBtn;

- (void)tabButtonClicked:(id)a0;
- (struct CGPoint { double x0; double x1; })transformScaleWithButton:(id)a0;
- (BOOL)needScroll;
- (id)resizeImage:(id)a0 ToSize:(struct CGSize { double x0; double x1; })a1;
- (void)updateSegmentsRects;
- (void)updateInnerAttributedTitles;
- (void)markDelegateMethodImpl;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frameForIndicatorAtIndex:(long long)a0;
- (void)setSelectIndicatorGradientLayerFrame;
- (void)selectIndexInScrollView:(long long)a0 animated:(BOOL)a1;
- (void)updateSegmentEdgeInset;
- (void)doReloadData;
- (void)generateInnerAttributedTitle:(id)a0;
- (id)createAttributedStringWithTitle:(id)a0 image:(id)a1 imageSize:(struct CGSize { double x0; double x1; })a2 attributes:(id)a3 color:(id)a4;
- (void)slidingContainer:(id)a0 didScroll:(id)a1 animated:(BOOL)a2;
- (void)scrollRatioWithSlidingContainer:(id)a0 scrollView:(id)a1 animated:(BOOL)a2;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frameForIndicatorWithButton:(id)a0 state:(long long)a1;
- (void)enumerateTabButtonsUsingBlock:(id /* block */)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frameForIndicatorWithButton:(id)a0;
- (void)selectButtonInScrollView:(id)a0 animated:(BOOL)a1 shouldCenterSelectedButton:(BOOL)a2;
- (void)setSelectIndicatorFrameWithButton:(id)a0 animated:(BOOL)a1;
- (void)setSelectIndicatorFrameWithButton:(id)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })slidingTabButton:(id)a0 frameForBadge:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })slidingTabButton:(id)a0 frameForRedDot:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)slidingContainer:(id)a0 didScroll:(id)a1;
- (void)setCustomIndicatorView:(id)a0;
- (id)tabButtonAtIndex:(unsigned long long)a0;
- (void)scrollSelectedButtonToVisible:(BOOL)a0;
- (void)reloadData;
- (void).cxx_destruct;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)layoutSubviews;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (double)widthForSegmentAtIndex:(long long)a0;
- (void)setSelectedIndex:(long long)a0 animated:(BOOL)a1;

@end
