@class NSDictionary, IESECYataConfirmImpl, IESECYataGeneralService, IESECBuyNowStateView, IESECSkuBuyNowModel, IESECYataInstanceUtil, NSString, IESECBuyNowTextFieldController, IESECBuyNowPreprocessor, IESECBuyNowContext, IESECBuyNowDataController, IESECTracker, IESECLinearGradientLayer, IESECBuyNowUltimateCeilingController, UICollectionView, UIView, IESECYataCommonBusiness, IESECBuyNowSKUEventsImpl, UIStackView, IESECBuyNowExtendEventImpl, IESECHybridParamsVerifyHelper, IESECBuyNowGuideController, IESECBuyNowAsyncTwoStageTrackController, IESECBuyNowNavView, IESECBuyNowContainerView, IESECYataPopupContaienrView;
@protocol IESECBuyNowOrderInterface, YataInstanceInterface, IESECUILoadingViewProtocol, UIGestureRecognizerDelegate;

@interface IESECBuyNowViewController : UIViewController <YataDependencyProvider, IESECBuyNowEventsDelegate, IESECYataCommonAbilityProtocol, IESECSkuBuyNowDelegate, IESECBaseSKUEventsDelegate, IESECBuyNowNavDelegate, IESECBuyNowStateProtocol, UIGestureRecognizerDelegate, YataTrackService, YataScrollViewDelegate, YataCallbackInterface, YataPopupContainerDelegate, IESECBuyNowVCDelegate, IESECBuyNowUIAbilityDelegate, IESECBuyNowTrackAbilityDelegate, IESECBuyNowCategoryInterface> {
    id<UIGestureRecognizerDelegate> _preInteractivePopGestureRecognizerDelegate;
    NSDictionary *_uplinkResponse;
    BOOL _uplinkIsDiffCut;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) IESECBuyNowSKUEventsImpl *skuEventsImpl;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) IESECSkuBuyNowModel *skuBuyModel;
@property (retain, nonatomic) IESECBuyNowSKUEventsImpl *skuEventsImpl;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) IESECBuyNowContext *context;
@property (retain, nonatomic) id<IESECBuyNowOrderInterface> orderService;
@property (retain, nonatomic) IESECTracker *tracker;
@property (retain, nonatomic) id<YataInstanceInterface> yataInstance;
@property (retain, nonatomic) IESECBuyNowContainerView *containerView;
@property (retain, nonatomic) IESECBuyNowNavView *navView;
@property (retain, nonatomic) IESECBuyNowStateView *stateView;
@property (retain, nonatomic) UICollectionView *mainCollectionView;
@property (retain, nonatomic) UIView *loadingMaskView;
@property (retain, nonatomic) UIView<IESECUILoadingViewProtocol> *loadingView;
@property (retain, nonatomic) IESECYataPopupContaienrView *popupContainerView;
@property (retain, nonatomic) UIView *dialogContainView;
@property (retain, nonatomic) IESECBuyNowUltimateCeilingController *ultimateCeilingController;
@property (retain, nonatomic) IESECBuyNowTextFieldController *textFieldController;
@property (retain, nonatomic) IESECBuyNowGuideController *guideController;
@property (retain, nonatomic) IESECLinearGradientLayer *headerGradientLayer;
@property (retain, nonatomic) UIStackView *yataHeaderAddress;
@property (retain, nonatomic) UIStackView *yataHeaderCeiling;
@property (retain, nonatomic) UIStackView *yataCeilingContainer;
@property (retain, nonatomic) UIStackView *yataTopBanner;
@property (retain, nonatomic) UIStackView *yataGuide;
@property (retain, nonatomic) UIStackView *yataDialog;
@property (retain, nonatomic) UIStackView *yataMask;
@property (nonatomic) BOOL isLoading;
@property (nonatomic) BOOL hasRecordPageScrolled;
@property (retain, nonatomic) NSString *closeMethod;
@property (nonatomic) long long iPageHidden;
@property (retain, nonatomic) NSString *pageStartStatus;
@property (nonatomic) double pageStartTime;
@property (nonatomic) double uplinkStartTime;
@property (retain, nonatomic) IESECHybridParamsVerifyHelper *verifyHelper;
@property (nonatomic) BOOL needRender;
@property (nonatomic) BOOL isInCeiling;
@property (weak, nonatomic) id<UIGestureRecognizerDelegate> preInteractivePopGestureDelegate;
@property (retain, nonatomic) UIStackView *yataHeaderNormal;
@property (retain, nonatomic) UIStackView *yataFooter;
@property (retain, nonatomic) IESECBuyNowExtendEventImpl *eventImpl;
@property (retain, nonatomic) IESECYataGeneralService *generalService;
@property (retain, nonatomic) IESECYataConfirmImpl *confirmImpl;
@property (retain, nonatomic) IESECBuyNowPreprocessor *preprocessor;
@property (retain, nonatomic) IESECBuyNowDataController *dataController;
@property (retain, nonatomic) IESECYataCommonBusiness *commonBusiness;
@property (nonatomic) long long themeStatusBarStyle;
@property (retain, nonatomic) IESECYataInstanceUtil *yataUtil;
@property (retain, nonatomic) IESECBuyNowAsyncTwoStageTrackController *asyncTrackController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (unsigned long long)positionWithString:(id)a0;

- (BOOL)aweDisableFullscreenPopTransition;
- (void)updatePageStatus:(id)a0;
- (void)dismissLoading;
- (void)closeVC;
- (void)clickMask;
- (void)scrollViewDidScroll:(id)a0 popupRenderObject:(id)a1;
- (void)onFetchBegin:(id)a0;
- (BOOL)onFetchEndBizValidWithDataObject:(id)a0;
- (void)onProtocolDispatchEnd:(unsigned long long)a0;
- (void)onProtocolReloadEnd:(unsigned long long)a0 success:(BOOL)a1;
- (void)popupWillShow:(id)a0 popupCount:(long long)a1;
- (void)popupDidShow:(id)a0 popupCount:(long long)a1 containerDict:(id)a2;
- (void)popupWillDismiss:(id)a0 popupCount:(long long)a1 containerDict:(id)a2;
- (void)popupDidDismiss:(id)a0 popupCount:(long long)a1;
- (void)popupMaskClick:(id)a0 containerDict:(id)a1;
- (BOOL)shouldTriggerEventWithType:(id)a0 renderObject:(id)a1 triggerParams:(id)a2;
- (BOOL)trackerEventModifyPlugin:(id)a0;
- (id)yata_sessionID;
- (id)yata_bizCode;
- (BOOL)yata_shouldUseFrontier;
- (BOOL)yata_disableCompress;
- (id)yata_body;
- (id)yata_scrollForwardDelegate;
- (id)yata_renderConfig;
- (id)yata_netBizConfigDelegate;
- (id)yata_callbackInterface;
- (id)yata_popupContainerConfigDelegate;
- (id)yata_dataPreprocessor;
- (id)yata_extendFieldsNameArray;
- (id)yata_confirmConfigDelegate;
- (id)yata_trackerService;
- (id)yata_toastService;
- (id)yata_routerService;
- (id)yata_eventImpl;
- (id)yataPopupContainerView;
- (void)trackWithEventName:(id)a0 params:(id)a1;
- (void)trackWithEventName:(id)a0 once:(id)a1 params:(id)a2;
- (void)startRender;
- (void)reportSchema;
- (void)configBtmTrackerV2;
- (void)configBtmTracker;
- (id)topFloatView;
- (void)closeCurrentPage;
- (void)subscribeXBridgeEvent;
- (void)toggleLoading:(BOOL)a0;
- (void)showPresentAnimationWithCompletion:(id /* block */)a0;
- (BOOL)ttHideNavigationBar;
- (id)skuView;
- (id)yataInstanceObj;
- (void)scrollToViewWithInstance:(id)a0;
- (id)uplinkController;
- (void)queryAgain;
- (void)updateCommonEventParams:(id)a0;
- (void)trackMediaWithEventName:(id)a0 params:(id)a1;
- (BOOL)isUltimateBuy;
- (void)removeVCFromPathWithMethod:(id)a0;
- (void)closeVCWithMethod:(id)a0;
- (void)triggerSubmitbarEventAfterCheck;
- (BOOL)payAndCheckWithEventData:(id)a0;
- (BOOL)openSchemaWithEventData:(id)a0;
- (BOOL)submitWithEventData:(id)a0;
- (void)trackerEventErrorWithEventData:(id)a0 msg:(id)a1;
- (BOOL)trackAdLogWithParams:(id)a0;
- (BOOL)setContainerWithStatusFontMode:(id)a0;
- (id)getCurrentFirstResponder;
- (BOOL)validateWithEventData:(id)a0;
- (BOOL)toggleSubmitWithEventData:(id)a0;
- (void)trackWithEventName:(id)a0 params:(id)a1 btmParams:(id)a2;
- (id)getBuyNowVC;
- (void)openMaskLayer;
- (void)closeMaskLayer;
- (BOOL)crossTriggerWithEventData:(id)a0;
- (BOOL)saveRenderNodeWithEventData:(id)a0;
- (void)updateBuyNowCommonEventParams:(id)a0;
- (BOOL)quitPageWithEventData:(id)a0;
- (BOOL)scrollToBottomWithEventData:(id)a0;
- (BOOL)multiRegexCheckWithEventData:(id)a0;
- (BOOL)regexCheckWithEventData:(id)a0;
- (BOOL)loadingWithEventData:(id)a0;
- (BOOL)readFieldAndTriggerWithEventData:(id)a0;
- (void)openDialog;
- (void)closeDialog;
- (void)scrollComponentToPositionWithEventData:(id)a0;
- (id)transformLocationWithEventData:(id)a0;
- (id)getRenderObjectWithRenderInfo:(id)a0;
- (id)initWithBuyNowContext:(id)a0;
- (void)dealAfterRenderRequest;
- (id)initSkuBuyNowVCWithContext:(id)a0 skuView:(id)a1;
- (id)buyNowView;
- (id)skuDataController;
- (void)stateViewRefreshClick;
- (void)stateViewReturnClick;
- (id)getScrollViewWithViewCode:(id)a0;
- (id)getPageStatusValueForKey:(id)a0;
- (id)getBoundingRectWithTargetView:(id)a0;
- (id)yata_footer;
- (id)yata_header;
- (BOOL)regexCheckWithNode:(id)a0 rules:(id)a1 fields:(id)a2 curNode:(id)a3;
- (void)scrollToTargetSliceView:(id)a0 withAnimation:(BOOL)a1 withSubviewSliceKey:(id)a2 inCollectionView:(id)a3 andOffset:(struct CGPoint { double x0; double x1; })a4 position:(unsigned long long)a5 completion:(id /* block */)a6;
- (void)category_SKUSetUpContextWithSkuBuyContext:(id)a0;
- (void)category_SKUSetupSkuContainerView;
- (void)calculateCacheAbilityForContext:(id)a0;
- (void)updateQueryParamsForContext:(id)a0 dataController:(id)a1;
- (void)setUpWithBuyNowContext:(id)a0;
- (void)setUpBasic;
- (id)category_findSkuTrackParamsWithPassThroughData:(id)a0;
- (void)retryQueryThenShow;
- (id)category_getSkuTrackParamsWithSkuBuyContext:(id)a0;
- (void)preloadSliceXTemplates;
- (void)setupBtm;
- (void)trackMonitorWithParams:(id)a0;
- (void)setupYataInstance;
- (void)autoScrollIfNeeded;
- (void)trackerPageStateWithType:(id)a0 extraParams:(id)a1;
- (void)p_preLoadSliceView;
- (void)renderWithCacheIfNeededWithCompletion:(id /* block */)a0;
- (void)trackEventAsync;
- (void)refreshUIAfterRenderWithCompletion:(id /* block */)a0;
- (void)trackerRenderPerformance;
- (id)defaultErrorConfig;
- (void)updateViewConstraintsWithRenderSuccess:(BOOL)a0;
- (void)updateTrackerBaseParams:(id)a0;
- (void)verifySchemaParams;
- (BOOL)closeBuyNowSKU;
- (void)dismissFromParentVC;
- (void)saveCacheForUplink;
- (void)trackerUplinkPerformanceWithOperatorType:(id)a0;
- (void)dealCeilingWithScrollView:(id)a0;
- (void)loadingMaskClick;
- (void)setupContainerView;
- (void)close;
- (void).cxx_destruct;
- (long long)preferredStatusBarStyle;
- (void)registerNotifications;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (void)applicationDidBecomeActive:(id)a0;
- (id)dataDelegate;
- (void)applicationDidEnterBackground:(id)a0;
- (void)scrollViewDidScroll:(id)a0;
- (BOOL)gestureRecognizer:(id)a0 shouldBeRequiredToFailByGestureRecognizer:(id)a1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)removeNotifications;
- (void)viewDidDisappear:(BOOL)a0;
- (void)setupUI;
- (void)showLoading;

@end
