@class NSMutableDictionary, IESLiveUserCardConfig, NSDictionary, IESLiveUserProfileData, IESLiveUserCardMonitor, NSObject, IESLiveUserCardBasicAbility, NSMutableArray, UIView, IESLiveUserCardPopupItemModel, NSString, IESLiveComponentContext, HTSEventContext, IESLivePopupItem, IESLiveUserCardProfileSettingView;
@protocol OS_dispatch_group, IESLiveUserCardDidFinishedAction, IESLiveSubscription, IESLiveRoomService;

@interface IESLiveUserCardViewModel : NSObject <HTSLiveUserPreviewActions, HTSLiveUserPreviewRouter>

@property (retain, nonatomic) HTSEventContext *trackContext;
@property (retain, nonatomic) IESLiveComponentContext *componentContext;
@property (retain, nonatomic) id<IESLiveRoomService> room;
@property (retain, nonatomic) IESLiveUserCardBasicAbility *usercardBasicAbility;
@property (retain, nonatomic) NSObject<OS_dispatch_group> *fetchUserCardDataGroup;
@property (retain, nonatomic) IESLiveUserProfileData *dataPlaceHolder;
@property (retain, nonatomic) IESLiveUserProfileData *dataCurrent;
@property (nonatomic) BOOL userPrefetch;
@property (retain, nonatomic) NSDictionary *userRelationInfo;
@property (retain, nonatomic) IESLiveUserCardConfig *previousConfig;
@property (retain, nonatomic) UIView *usercardContainer;
@property (retain, nonatomic) IESLiveUserCardMonitor *usercardMonitor;
@property (nonatomic) BOOL isShowing;
@property (nonatomic) BOOL isShowingAnonymousReportAlert;
@property (nonatomic) long long showingToastOnlyID;
@property (retain, nonatomic) IESLiveUserCardProfileSettingView *profileSettingView;
@property (nonatomic) BOOL isFollowUserSuccess;
@property (nonatomic) BOOL hasPopup;
@property (retain, nonatomic) id<IESLiveSubscription> disposable;
@property (nonatomic) long long skipPrivacyLevel;
@property (retain, nonatomic) IESLiveUserCardPopupItemModel *popupItemModel;
@property (retain, nonatomic) IESLivePopupItem *popupItem;
@property (retain, nonatomic) id<IESLiveUserCardDidFinishedAction> finishedAction;
@property (nonatomic) BOOL myLiveEnabled;
@property (retain, nonatomic) NSMutableDictionary *dataCache;
@property (nonatomic) BOOL hasOpenAnchorProfile;
@property (retain, nonatomic) NSMutableArray *latestPrefetchUid;
@property (nonatomic) long long anchorCardOpenCount;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)didSetAttachingDIContext;
- (void)unfollowAnchorSuccess;
- (void)followUserSuccess;
- (id)getUserRelationInfoWithParams:(id)a0;
- (void)dismissUserCard;
- (void)processAdminOperationTypeResponse:(id)a0 userID:(id)a1 actionType:(long long)a2 backupAction:(id /* block */)a3 cancelAction:(id /* block */)a4 scene:(id)a5;
- (void)showReportView:(id)a0 reportContent:(id)a1 messageId:(id)a2 isChat:(BOOL)a3 source:(unsigned long long)a4;
- (void)showUserModel:(id)a0 withConfig:(id)a1;
- (id)initWithRoom:(id)a0 trackContext:(id)a1 componentContext:(id)a2;
- (void)screenOrientationTransitionBegin:(long long)a0;
- (void)showUser:(id)a0 secUserId:(id)a1 withConfig:(id)a2;
- (BOOL)hasOpenAnchorUserCard;
- (void)prefetchUserCardWithUserID:(id)a0 secUserId:(id)a1 source:(unsigned long long)a2;
- (void)showAdminSheet:(id)a0;
- (void)reportRoomWithUser:(id)a0 functionType:(id)a1;
- (void)trackeUserCardSettingViewShow;
- (BOOL)isAnchorOfCurrentRoom;
- (void)p_prefetchWithAnimationSceneWithUserID:(id)a0 secUserId:(id)a1 source:(unsigned long long)a2;
- (void)p_prefetchWithUserID:(id)a0 secUserId:(id)a1 source:(unsigned long long)a2;
- (unsigned long long)p_currentUserRole;
- (void)showUserCardWithUserID:(id)a0 secUserId:(id)a1 withConfig:(id)a2 closeBlock:(id /* block */)a3;
- (BOOL)canShowUser:(id)a0 secUserId:(id)a1 withConfig:(id)a2;
- (BOOL)checkUserCardDataWithUserID:(id)a0 userProfileData:(id)a1 error:(id)a2;
- (void)updateCacheDataWithUserID:(id)a0 config:(id)a1 data:(id)a2;
- (id)createUserCardStoreWithData:(id)a0 userProfileConfig:(id)a1;
- (void)tr_clickUserCardEventWithStore:(id)a0;
- (id)createPopupItemWithUserCardStore:(id)a0;
- (id)createViewWithUserCardStore:(id)a0;
- (id)createPopupItemWithPopupModel:(id)a0;
- (void)requestUserCardWithUserID:(id)a0 secUserId:(id)a1 config:(id)a2 closeBlock:(id /* block */)a3;
- (BOOL)shouldUseCacheWithUserID:(id)a0 data:(id)a1 config:(id)a2;
- (BOOL)shouldShowNormalUserCardWithData:(id)a0 config:(id)a1;
- (void)setupPopupItemModel:(id)a0 withUserCardStore:(id)a1;
- (void)setupPopupItem:(id)a0 withPopupModel:(id)a1;
- (void)requestUserCard:(id)a0 secUid:(id)a1 room:(id)a2 config:(id)a3 specialScene:(long long)a4 completion:(id /* block */)a5;
- (BOOL)shouldShowUser:(id)a0 secUserId:(id)a1 config:(id)a2 requestFrom:(long long)a3 myRole:(unsigned long long)a4;
- (BOOL)isLinkMicSource:(unsigned long long)a0;
- (void)showReportConfirmView:(id)a0 secUserId:(id)a1 withConfig:(id)a2 withRequestFrom:(long long)a3 withMyRole:(unsigned long long)a4;
- (unsigned long long)p_previewUserRoleWithUser:(id)a0 config:(id)a1 ownRoom:(id)a2;
- (long long)getFromRoleWithMyRole:(unsigned long long)a0;
- (long long)getToRoleWithItsRole:(unsigned long long)a0 user:(id)a1;
- (id)customAnimationWithDuration:(double)a0 rateCurve:(id)a1;
- (void)showUserCardWithConfig:(id)a0 dispatch_group_t:(id)a1 closeBlock:(id /* block */)a2;
- (id)getShopIds;
- (void)showReportViewForPrivacyMode:(id)a0 secUserId:(id)a1 withConfig:(id)a2 withRequestFrom:(long long)a3 withMyRole:(unsigned long long)a4;
- (BOOL)isOtherAnchor:(id)a0 userID:(id)a1;
- (long long)getToRoleWithItsRole:(unsigned long long)a0 user:(id)a1 profile:(id)a2;
- (id)previewTypeWithMyRole:(unsigned long long)a0 itsRole:(unsigned long long)a1 toUserID:(id)a2;
- (BOOL)isHostWithUID:(id)a0;
- (void)showReportViewForPrivacyMode:(id)a0 secUserId:(id)a1 withConfig:(id)a2 withRequestFrom:(long long)a3;
- (void).cxx_destruct;
- (void)clear;

@end
