@class IESLivePKGuestAudienceInstance, IESLiveCountTimer, IESLivePKGuestApplyListPopUpViewModel, IESLivePKGuestInteractiveRootPanel, IESLivePKGuestInteractSettingHandler, UIView, IESLivePKGuestAudienceBuilder, HTSInteractionStreamAppData, IESLiveInteractionGuestPreviewView, NSString, HTSEventContext, IESLivePKGuestTrackerContext, IESLivePKGuestInteractiveRootPanelViewModel, NSArray, IESLivePKGuestReceiveInvitationPanel, IESLivePKGuestPermissionChecker, IESLivePKGuestApplyListPopUpView, IESLivePKGuestTrackHandler;
@protocol IESLiveRevenueInteractLinkerProvider, IESLivePKGuestAudienceBuilderService, IESLiveRoomService;

@interface IESLivePKGuestAudiencePlugin : NSObject <IESLivePKChatGuestListViewDelegate, IESLivePKGuestOperatePanelViewModelDelegate, IESLiveSEIListener, HTSLiveMessageSubscriber, IESLivePKGuestApplyListPopUpViewDelegate, IESLivePKGuestInteractiveRootPanelDelegate, IESLivePKGuestPreApplyManagerDelegate, IESLiveRevenueInteractInnerAction, IESLivePKStateAction, IESLivePKInstanceProtocol, IESLivePKGuestProvider>

@property (retain, nonatomic) IESLivePKGuestAudienceBuilder *guestBuilder;
@property (retain, nonatomic) HTSEventContext *trackContext;
@property (weak, nonatomic) IESLivePKGuestReceiveInvitationPanel *anchorInvitePanel;
@property (nonatomic) BOOL hasRealNameVerified;
@property (nonatomic) BOOL isGoingToRealNameVerified;
@property (retain, nonatomic) IESLiveCountTimer *verifiedTimer;
@property (retain, nonatomic) HTSInteractionStreamAppData *appData;
@property (nonatomic) BOOL isWatcherConnect;
@property (nonatomic) BOOL enteredRoom;
@property (retain, nonatomic) id<IESLivePKGuestAudienceBuilderService> audBuilderService;
@property (retain, nonatomic) NSArray *readedApplications;
@property (weak, nonatomic) IESLivePKGuestInteractiveRootPanel *adminOperatePanel;
@property (retain, nonatomic) IESLivePKGuestInteractiveRootPanelViewModel *adminOperatePanelViewModel;
@property (retain, nonatomic) IESLivePKGuestAudienceInstance *guestInstance;
@property (nonatomic) BOOL isSwitchConnect;
@property (nonatomic) BOOL isSwitchingToMultiNormal;
@property (nonatomic) BOOL linkListLoaded;
@property (weak, nonatomic) IESLivePKGuestApplyListPopUpView *applyListPopupView;
@property (retain, nonatomic) IESLivePKGuestApplyListPopUpViewModel *applyListPopupViewModel;
@property (nonatomic) BOOL hasCancelWaiting;
@property (weak, nonatomic) UIView *beautyView;
@property (retain, nonatomic) IESLiveInteractionGuestPreviewView *cameraPreview;
@property (nonatomic) BOOL pkWithGuest;
@property (nonatomic) BOOL switchingFlag;
@property (nonatomic) BOOL pkingStateReceived;
@property (weak, nonatomic) id<IESLiveRevenueInteractLinkerProvider> linkerProvider;
@property (retain, nonatomic) id<IESLiveRoomService> roomModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) IESLivePKGuestTrackerContext *guestTrackerContext;
@property (retain, nonatomic) IESLivePKGuestTrackHandler *guestTrackerHandler;
@property (retain, nonatomic) IESLivePKGuestInteractSettingHandler *settingHandler;
@property (nonatomic) BOOL isBigPartyMode;
@property (retain, nonatomic) IESLivePKGuestPermissionChecker *permissionChecker;

- (void)didSetAttachingDIContext;
- (BOOL)couldUnmountComponent;
- (id)userService;
- (unsigned long long)supportSeiTypes;
- (void)onParseredWithSEIResult:(id)a0;
- (BOOL)adminModeEnable;
- (void)componentContainerFrameChanged;
- (void)overturnCamera;
- (void)turnOnCameraByOther:(BOOL)a0;
- (void)turnOnCameraBySelf:(BOOL)a0;
- (BOOL)isCameraOpen;
- (BOOL)shouldIgnoreCameraRemoteControl;
- (void)openBeautySettingPanelBeforeVideoInteractionWithStartBlock:(id /* block */)a0 cancelBlock:(id /* block */)a1;
- (void)switchApplyStateFromMultiNormalWithLinkMicID:(id)a0 interactiveMode:(long long)a1;
- (void)switchSceneFromBigPartyWithMediaService:(id)a0 cameraPreview:(id)a1;
- (void)switchApplyStateFromBigPartyWithLinkMicID:(id)a0 interactiveMode:(long long)a1;
- (void)switchPreApplyStateFromBigPartyWithDisplayText:(id)a0;
- (void)applyConnectionWithEventExtra:(id)a0 applySource:(unsigned long long)a1;
- (void)stopConnectionWithRequestSource:(id)a0;
- (id)emojiContainerForUserID:(id)a0 isInteractiveEmoji:(BOOL)a1;
- (BOOL)userInActiveOrWaitingList:(id)a0;
- (void)didChangePKStateFrom:(long long)a0 to:(long long)a1;
- (void)onBusinessPrepare;
- (void)onPKFinish;
- (BOOL)adminRightEnable;
- (void)askForStopConnectionAction:(id /* block */)a0;
- (void)bindStore:(id)a0;
- (void)askForLeave;
- (void)trackWatchDuration;
- (void)closeLinkMicWithAudienceByForce;
- (void)applyConnectionForAudioModeWithApplySource:(unsigned long long)a0 paidCount:(id)a1 limitedTime:(id)a2 reason:(id)a3 extraParams:(id)a4;
- (void)renderWaitingApplicationNumTip:(id)a0;
- (void)showAdminPanel;
- (void)showAdminOperationPanelForGuest:(id)a0;
- (void)stopAndHidePreView;
- (void)endLiveWithScource:(unsigned long long)a0;
- (id)appendKeyWithUserID:(id)a0;
- (void)unloadGuestInstance;
- (BOOL)linkMicConnected;
- (void)showAdminOperatePanel;
- (void)askForStopConnection;
- (void)applyForConnection;
- (void)handleGuestSeatDidTapped;
- (void)onPKCloseWithGuest;
- (id)initWithDiContext:(id)a0 trackContext:(id)a1;
- (void)handleInteractiveItemDidTapped;
- (void)pkGuestInteractiveRootPanel:(id)a0 inviteWithUserID:(id)a1 secUserID:(id)a2 sourcePage:(id)a3 params:(id)a4;
- (void)pkGuestInteractiveRootPanel:(id)a0 permitApplicationOfUser:(id)a1 extraInfo:(id)a2;
- (void)pkGuestInteractiveRootPanel:(id)a0 inviteWithUserID:(id)a1 secUserID:(id)a2 sourcePage:(id)a3;
- (void)pkGuestInteractiveRootPanelNeedToResetWaitingApplications:(id)a0;
- (void)pkGuestInteractiveRootPanelAdminApply:(id)a0;
- (void)applyListPopUpViewDidClickTopRightBtn:(id)a0;
- (unsigned long long)currentSceneForGuest;
- (void)renderToolBarApplyStatus:(unsigned long long)a0;
- (id)currentLayoutForGuest;
- (void)showGuestBeautyPopupViewWithType:(unsigned long long)a0 startBlock:(id /* block */)a1 cancelBlock:(id /* block */)a2;
- (void)updateAdminUnReadTipsView:(id)a0;
- (void)showToolBarInteractiveItemTip:(id)a0;
- (void)showToolBarInteractiveItemDot:(BOOL)a0;
- (BOOL)enableAudiencePreapply;
- (void)changeWatcherConnect:(BOOL)a0;
- (void)loadGuestInstance;
- (void)removeAdminUI;
- (void)showToastWhenInterationEndedOnisSelfDisconnect;
- (unsigned long long)pr_customViewStatusFromCurrentLinkMicStatus;
- (void)updateApplyListPopupViewOnLinkMicStatusUpdate;
- (void)showAnchorInvitationPanelWithNickName:(id)a0 imageURLs:(id)a1 isFromAdmin:(BOOL)a2 message:(id)a3;
- (void)onStatusConnecting;
- (void)onStatusConnectEnd;
- (void)loadLinkListIfNeeded;
- (void)handlePreApply;
- (void)showApplyListPopupView;
- (void)doApplyProcess;
- (void)permissionChecked;
- (void)showOnlyApplyModeSelecter;
- (void)applyForVideoModeConnection;
- (void)applyForAudioModeConnection;
- (void)applyForVideoModeConnectionWithApplySource:(unsigned long long)a0;
- (void)applyForAudioModeConnectionWithApplySource:(unsigned long long)a0;
- (void)hideAdminPanel;
- (void)showAdminOperationRootPanel;
- (void)updateToolBarInteractiveItemDot:(long long)a0;
- (id)generateFastMatchConfig;
- (void)preapplyManagerDidSucceedInPreapplying:(id)a0;
- (void)preapplyManagerDidSucceedInCancellingPreapply:(id)a0;
- (void)stopLoginUserConnect;
- (void)showToast:(id)a0;
- (long long)currentCameraPosition;
- (void).cxx_destruct;
- (void)messageReceived:(id)a0;

@end
