@class NSTimer, NSString, IESLivePEDecisionService, IESLiveIMWebSocketFetcher, IESLiveIMConfig, IESLiveIMMessageChannel, NSDictionary;
@protocol IESLiveIMMessageReciever, IESLiveMessageConfig;

@interface IESLiveIMMessageClient : NSObject <IESLiveIMMessageStrategyService, IESLivePEDecisionObserver, IESLiveIMChannelDelegate>

@property (retain, nonatomic) IESLivePEDecisionService *decisionService;
@property (copy, nonatomic) NSString *channelTags;
@property (nonatomic) double channelTagsCreateTimeS;
@property (nonatomic) BOOL needSendPushMessage;
@property (nonatomic) double asyncSendPushMsgTimes;
@property (nonatomic) long long totalReceiveCount;
@property (nonatomic) long long totalParseCount;
@property (copy, nonatomic) NSString *wrdsSubscribeRooms;
@property (retain, nonatomic) id<IESLiveMessageConfig> bizConfig;
@property (retain, nonatomic) id<IESLiveIMMessageReciever> receiver;
@property (retain, nonatomic) IESLiveIMConfig *imConfig;
@property (nonatomic) BOOL isStarted;
@property (retain, nonatomic) IESLiveIMMessageChannel *channel;
@property (retain, nonatomic) IESLiveIMWebSocketFetcher *webSocketFetcher;
@property (retain, nonatomic) NSString *cursor;
@property (nonatomic) BOOL noMoreHistoryMessage;
@property (retain, nonatomic) NSString *pushServer;
@property (retain, nonatomic) NSString *internalExt;
@property (retain, nonatomic) NSDictionary *routeParams;
@property (nonatomic) BOOL isFirstFetch;
@property (nonatomic) double firstWsTimeout;
@property (nonatomic) double initTime;
@property (nonatomic) double startTime;
@property (nonatomic) double firstBatchTime;
@property (retain, nonatomic) NSString *firstBatchType;
@property (nonatomic) long long lastMemberEnterFilterCount;
@property (nonatomic) long long lastMemberEnterDiscardCount;
@property (retain, nonatomic) NSTimer *strategyTimer;
@property (retain, nonatomic) NSString *PL;
@property (copy, nonatomic) id /* block */ httpFetchParamsCallback;
@property (copy, nonatomic) id /* block */ wsFetchParamsCallback;
@property (copy, nonatomic) id /* block */ heartbeatData;
@property (copy, nonatomic) id /* block */ firstFetchProcess;
@property (nonatomic) long long wrdsPreloadRangeN;
@property (copy, nonatomic) id /* block */ wrdsPreloadRoomIdArray;
@property (nonatomic) BOOL enableStartEarlier;
@property (copy, nonatomic) id /* block */ memberEnterFilter;
@property (copy, nonatomic) id /* block */ memberEnterDiscard;
@property (copy, nonatomic) id /* block */ messageFrequency;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)stopStrategyTimer;
- (void)decision:(id)a0 result:(id)a1;
- (void)onFeatureChange:(id)a0;
- (void)channel:(id)a0 closed:(id)a1;
- (void)channel:(id)a0 received:(id)a1;
- (id)initWithConfig:(id)a0 receiver:(id)a1 diContext:(id)a2;
- (void)setupDecisionService;
- (void)updateMessageDecodeQueueIfMediaRoom;
- (void)startStrategyTimerWith:(double)a0;
- (void)doStrategyTimerAction;
- (void)setupStrategyEnvWith:(id)a0;
- (void)cleanupStrategyEnv;
- (id)initWithConfig:(id)a0 receiver:(id)a1 decoder:(id)a2;
- (id)readLastHttpUrl;
- (id)wrdsPreloadSubscribeRooms;
- (id)readLastWebsocketUrl;
- (void)trackParseRate;
- (void)trackPersonalizedChannelSwitchWithStatus:(BOOL)a0 reason:(id)a1 result:(id)a2;
- (void)sendPushMessageTimeoutWithResult:(id)a0;
- (BOOL)asyncSendPersonalizedChannelPushMsgWithResult:(id)a0;
- (id)messageFetchPath;
- (void)trackEnterToFirstMessageArrive;
- (void)firstFetch:(id)a0;
- (void)reconnect;
- (void).cxx_destruct;
- (void)stop;
- (void)start;
- (void)dealloc;

@end
