@class NSString, IESLiveInteractPureRTCstreamConfig, RtcExtInfo;
@protocol IESLiveLinkmicMediaServiceSessions, IESLiveLinkmicMediaServiceSignal, IESLiveLinkmicMediaServiceCrossRoom, IESLiveLinkmicMediaServiceVideo, IESLiveLinkmicMediaServiceKTV, IESLiveLinkmicMediaServiceExtra, IESLiveLinkmicMediaServiceDelegate, IESLiveChatChannelLinkmicMonitor, IESLiveLinkmicMediaServiceConfig, IESLiveLinkmicMediaServiceAudio, IESLiveInteractPureRTCStreamClient, IESLiveLinkmicMediaServiceInfoUpdatable;

@interface IESLiveChatChannelLinkmicRTCService : NSObject <IESLiveLinkmicMediaServiceAudio, IESLiveInteractPureRTCStreamDelegate, HTSLiveStreamPlayerAction, IESLiveChatChannelLinkmicRTCServiceInterface, IESLiveLinkmicMediaServiceInterface>

@property (retain, nonatomic) RtcExtInfo *rtcExtInfo;
@property (nonatomic) long long state;
@property (retain, nonatomic) IESLiveInteractPureRTCstreamConfig *rtcConfig;
@property (retain, nonatomic) id<IESLiveLinkmicMediaServiceConfig> mediaConfig;
@property (retain, nonatomic) id<IESLiveInteractPureRTCStreamClient> rtcClient;
@property (nonatomic) BOOL isPublicStreamEnabled;
@property (copy, nonatomic) NSString *publicStreamId;
@property (nonatomic) BOOL isAudioMixEnable;
@property (nonatomic) BOOL isAudioDataFirstFrameReceived;
@property (nonatomic) int streamPlayerSampleRate;
@property (nonatomic) int streamPlayerChannels;
@property (nonatomic) BOOL isMute;
@property (retain, nonatomic) id<IESLiveChatChannelLinkmicMonitor> monitor;
@property (readonly, nonatomic) BOOL mute;
@property (nonatomic) BOOL enableVolumReport;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) BOOL isInLinkmic;
@property (weak, nonatomic) id<IESLiveLinkmicMediaServiceDelegate> delegate;
@property (readonly, nonatomic) id<IESLiveLinkmicMediaServiceInfoUpdatable> mediaInfo;
@property (readonly, nonatomic) id<IESLiveLinkmicMediaServiceAudio> audio;
@property (readonly, nonatomic) id<IESLiveLinkmicMediaServiceVideo> video;
@property (readonly, nonatomic) id<IESLiveLinkmicMediaServiceSessions> sessions;
@property (readonly, nonatomic) id<IESLiveLinkmicMediaServiceSignal> signal;
@property (readonly, nonatomic) id<IESLiveLinkmicMediaServiceCrossRoom> crossRoom;
@property (readonly, nonatomic) id<IESLiveLinkmicMediaServiceKTV> ktv;
@property (readonly, nonatomic) id<IESLiveLinkmicMediaServiceExtra> extra;

- (void)didSetAttachingDIContext;
- (void)setEnableNoiseSuppression:(BOOL)a0 param:(float)a1;
- (BOOL)isInteractRunning;
- (void)stopInteract;
- (void)startInteract;
- (void)muteAllRemoteAudioStreams:(BOOL)a0 reason:(id)a1;
- (void)enableLocalAudio:(BOOL)a0;
- (void)setEnableVolumeBalance:(BOOL)a0 balancedLoudnessValue:(double)a1;
- (void)setRemoteDefaultAudioPlaybackVolume:(int)a0;
- (void)muteAudioCapture:(BOOL)a0 reason:(id)a1;
- (void)enterLinkmic;
- (void)setupWithRTCExtInfo:(id)a0;
- (BOOL)isEnterLinkmic;
- (void)setPlayerAudioMixVolume:(long long)a0;
- (id)linkmicID;
- (void)enableAudioCapture:(BOOL)a0 reason:(id)a1;
- (void)enableStreamPlayerAudioMix:(BOOL)a0 completion:(id /* block */)a1;
- (void)cleanState;
- (void)joinChatChannelRTCRoom;
- (void)joinChatChannelRTCLinkmic;
- (void)leaveChatChannelRTCLinkmic;
- (void)leaveChatChannelRTCRoom;
- (id)rtcStreamer;
- (void)startReportAudioVolume;
- (void)startReportAudioVolumeWithDuration:(long long)a0;
- (BOOL)muteRemoteAudioStreamWithLinkmicID:(id)a0 mute:(BOOL)a1 reason:(id)a2 force:(BOOL)a3;
- (void)muteLocalAudio:(BOOL)a0 reason:(id)a1;
- (void)muteLocalAudioCapture:(BOOL)a0 reason:(id)a1;
- (void)setPlaybackVolumeOnly:(long long)a0;
- (void)setDownlinkAuidoSelectionParameters:(id)a0;
- (void)setRefTimeMode:(int)a0;
- (void)setEnablePullStreamAGC:(BOOL)a0 targetLoudness:(long long)a1;
- (void)rtcStreamClient:(id)a0 onError:(id)a1;
- (void)rtcStreamClient:(id)a0 onJoinRoomFinish:(id)a1;
- (void)rtcStreamClientOnLeaveRoomFinish:(id)a0;
- (void)rtcStreamClient:(id)a0 onUserJoined:(id)a1;
- (void)rtcStreamClient:(id)a0 onUserLeaved:(id)a1 reason:(unsigned long long)a2;
- (void)rtcStreamClient:(id)a0 onStreamPublishSuccess:(id)a1;
- (void)rtcStreamClient:(id)a0 onUserMuteAudio:(id)a1 isMute:(BOOL)a2;
- (void)rtcStreamClient:(id)a0 onUserAudioCaptureChanged:(id)a1 isCapturing:(BOOL)a2 error:(id)a3;
- (void)rtcStreamClient:(id)a0 onFirstRemoteAudioFrameOfUid:(id)a1 roomID:(id)a2;
- (void)rtcStreamClientOnFirstLocalAudioFrame:(id)a0;
- (void)rtcStreamClient:(id)a0 onUserAudioVolumeIndication:(id)a1 volume:(long long)a2 totalVolume:(long long)a3;
- (void)rtcStreamClient:(id)a0 onPlayPublicStreamResult:(id)a1;
- (void)rtcStreamClient:(id)a0 onPublicStreamSystemSEIReceived:(id)a1 error:(id)a2;
- (void)leaveChatChannelRTCRoomAndDestroy;
- (BOOL)isInLinkmic;
- (void)setupWithConfig:(id)a0 diContext:(id)a1;
- (void)enterLinkmicWithoutJoin;
- (void)setupRtcClient;
- (void)realJoinChannel;
- (void)exitLinkmic;
- (void)setRemoteAudioPlaybackVolume:(id)a0 volume:(int)a1;
- (void).cxx_destruct;
- (void)setPlaybackVolume:(long long)a0;
- (void)clean;

@end
