@class NSNumber, RACDisposable, NSArray, IESLiveRefactGiftPanelEventServiceImp, RACReplaySubject, NSString, NSDictionary, HTSLiveGiftStruct, IESLiveGiftPanelImageMonitorHelper, IESLiveGiftPanelDataSharing, IESLiveGiftPanelTipCenter;
@protocol IESLivePopularCardAPI, IESLiveGiftModuleRecipientRouter, HTSLiveSendGiftActions, IESLiveURLSchemaHandler, IESLivePerfSampler, IESLiveSubscription, IESLivePropBindingAlarmAPI, IESLiveInternalRouter, IESLiveLocationService;

@interface IESLiveGiftPanelViewModel : NSObject <IESLiveRefactGiftPanelEventAction, IESHYControllerDelegate, IESLiveGiftDynamicPanelClientAIDataService, IESLiveGiftPanelViewModelProtocol>

@property (retain, nonatomic) IESLiveGiftPanelDataSharing *giftPanelDataSharing;
@property (retain, nonatomic) IESLiveRefactGiftPanelEventServiceImp *eventService;
@property (retain, nonatomic) IESLiveGiftPanelTipCenter *tipCenter;
@property (nonatomic) double panelCollectionHeight;
@property (nonatomic) double panelWidth;
@property (nonatomic) BOOL isEnterPopCard;
@property (copy, nonatomic) NSArray *backgroundImageUrlList;
@property (retain, nonatomic) id<HTSLiveSendGiftActions> sendDispatcher;
@property (retain, nonatomic) id<IESLiveInternalRouter> internalRouter;
@property (retain, nonatomic) id<IESLiveURLSchemaHandler> schemaURLHandler;
@property (retain, nonatomic) id<IESLiveLocationService> locationService;
@property (nonatomic) BOOL hasMergeLatestGiftPanelData;
@property (retain, nonatomic) id<IESLivePropBindingAlarmAPI> propBindingAlarmApi;
@property (retain, nonatomic) id<IESLiveSubscription> giftExtraDisposable;
@property (retain, nonatomic) id<IESLiveSubscription> pageExtraDisposable;
@property (retain, nonatomic) id<IESLivePopularCardAPI> popularCardAPI;
@property (retain, nonatomic) id<IESLiveGiftModuleRecipientRouter> recipientRouter;
@property (retain, nonatomic) RACReplaySubject *currentSelectedGiftPublisher;
@property (retain, nonatomic) RACReplaySubject *currentSelectedInfoPublisher;
@property (retain, nonatomic) RACReplaySubject *currentSelectedPagePublisher;
@property (retain, nonatomic) RACReplaySubject *smallGiftComboPublisher;
@property (retain, nonatomic) RACReplaySubject *clientAIInfoPublisher;
@property (retain, nonatomic) RACReplaySubject *currentSelectStatusPublisher;
@property (retain, nonatomic) id<IESLiveSubscription> giftPageTypeDisposable;
@property (retain, nonatomic) id<IESLiveSubscription> groupModeSubscription;
@property (retain, nonatomic) RACDisposable *groupModeDisposable;
@property (nonatomic) double appearTime;
@property (weak, nonatomic) id<IESLivePerfSampler> perfSampler;
@property (nonatomic) BOOL hasOperatePanel;
@property (nonatomic) long long panelVMType;
@property (copy, nonatomic) NSDictionary *clientAIGifts;
@property (retain, nonatomic) HTSLiveGiftStruct *lastRequestExtraGift;
@property (nonatomic) BOOL liveGiftPanelNewArchitecture;
@property (nonatomic) BOOL enableDynamicPanel;
@property (nonatomic) BOOL enableMergeNewModelFlag;
@property (nonatomic) BOOL enableGiftPriceLimitOpt;
@property (nonatomic) long long giftLargePriceLimit;
@property (retain, nonatomic) IESLiveGiftPanelImageMonitorHelper *imageMonitorHelper;
@property (nonatomic) BOOL fixDefaultSelectGift;
@property (nonatomic) BOOL isRealPanelViewModel;
@property (nonatomic) BOOL disableUpdateCardIndex;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSNumber *preSelectGiftId;
@property (retain, nonatomic) NSString *propRefId;
@property (nonatomic) long long preSelectPageType;
@property (nonatomic) BOOL isDefaultSelect;
@property (nonatomic) BOOL isEmptyPage;
@property (nonatomic) BOOL shouldRequestExtra;
@property (nonatomic) BOOL shouldShowFaceTip;
@property (copy, nonatomic) NSString *faceGiftText;
@property (copy, nonatomic) id /* block */ showGiftBanner;
@property (copy, nonatomic) id /* block */ refreshGiftBannerHybrid;
@property (copy, nonatomic) id /* block */ removeGiftBanner;
@property (copy, nonatomic) id /* block */ updateGiftPanelTopTip;
@property (copy, nonatomic) id /* block */ searchGift;
@property (copy, nonatomic) id /* block */ updateDynamicBackgroundImage;
@property (copy, nonatomic) id /* block */ handleSendGiftError;
@property (copy, nonatomic) id /* block */ handleSelectGiftError;

+ (id)defaultGiftIdWithDataSharing:(id)a0 configurationPageType:(long long)a1;

- (void)didSetAttachingDIContext;
- (void)gpe_changeTabWithIndex:(unsigned long long)a0 active:(BOOL)a1;
- (void)gpe_giftListSortTypeDidChange:(long long)a0;
- (void)gpe_changeTabBackgroundImageUrlList:(id)a0;
- (void)gpe_changeTopicWithId:(long long)a0 pageType:(long long)a1 needScroll:(BOOL)a2;
- (void)gpe_showBigGiftCountDownView:(long long)a0 item:(id)a1 transaction:(id)a2 dynamicParams:(id)a3;
- (id)getClientAIGifts;
- (void)sendCurrentSelectedItem;
- (void)changeTabWithIndex:(unsigned long long)a0 active:(BOOL)a1;
- (void)initTabWithIndex:(unsigned long long)a0;
- (void)hidePanel:(BOOL)a0;
- (void)gpe_giftListScrollViewWillBeginDragging:(id)a0 tabIndex:(long long)a1 layoutDirection:(long long)a2;
- (void)gpe_sendCurrentSelectedItem;
- (void)gpe_initTabWithIndex:(unsigned long long)a0;
- (void)giftPanelDidShow;
- (void)selectGiftItemWithId:(id)a0 isPreSelect:(BOOL)a1 pageType:(long long)a2 forceUsePageType:(BOOL)a3 changePage:(BOOL)a4 allTopic:(BOOL)a5 callback:(id /* block */)a6;
- (void)performPreSelectGiftActionwithChangePage:(BOOL)a0 type:(long long)a1 callBack:(id /* block */)a2;
- (void)giftPanelWillShow;
- (void)giftPanelWillHide;
- (id)giftItemWithGiftID:(id)a0 pageType:(unsigned long long)a1 scanFromFirstPageTypeIfNotFound:(BOOL)a2 allTopic:(BOOL)a3;
- (void)selectGiftItemWithId:(id)a0 pageType:(long long)a1 completionBlock:(id /* block */)a2;
- (void)updateWithClientAIGift:(id)a0;
- (void)updateDefaultSelectItemWithGiftId:(id)a0;
- (id)requirePanelGiftList:(id)a0;
- (void)mergeLatestGiftPanelData:(id)a0 recipientChanged:(BOOL)a1 dataMergeCompletion:(id /* block */)a2 giftPreSelectCompletion:(id /* block */)a3;
- (void)appendGiftListWithGiftModels:(id)a0 forPageType:(id)a1 requestGiftIds:(id)a2;
- (void)appendGiftListEmptyWithPageType:(id)a0 requestGiftIds:(id)a1;
- (void)showGiftBannerIfNeeded;
- (id)selectedCollectionViewModel;
- (long long)pageItemListCountFromVMWithPageType:(unsigned long long)a0;
- (BOOL)isPageExistWithPageType:(unsigned long long)a0;
- (id)panelGiftStructWithGiftId:(id)a0;
- (id)observeSelectedGift;
- (id)observeSelectedPageWithExtraPbDefinition:(id)a0 extraFqName:(id)a1;
- (id)observeSmallGiftCombo;
- (id)observeClientAIInfoById:(long long)a0;
- (id)observeCurrentSelectStatus;
- (id)observeSelectedInfo:(id)a0 fqName:(id)a1;
- (void)updateFirstChargeBanner;
- (void)showBigGiftContinueViewWithTransaction:(id)a0 dynamicParams:(id)a1 baseCount:(long long)a2;
- (void)sendGift:(id)a0;
- (void)iesHYController:(id)a0 didFinishLoadWithError:(id)a1;
- (id)itemViewModelWithPageType:(long long)a0;
- (id)getComponentsWithURLString:(id)a0;
- (BOOL)p_shouldSkipDiamondCheck;
- (BOOL)hasPlentyDiamand:(unsigned long long)a0;
- (void)showLackOfBanlance:(long long)a0;
- (void)currentSelectedGiftChangedWith:(id)a0;
- (void)sendCurrentSelectStatus;
- (void)sendCurrentSelectedPage;
- (void)currentSelectedPageChangedWith:(id)a0;
- (void)sendCurrentSelectInfo;
- (void)sendClientClientAIInfoWithId:(long long)a0;
- (id)initWithGiftPanelDataSharing:(id)a0 panelVMType:(long long)a1 isReal:(BOOL)a2;
- (void)p_bindSignal;
- (id)preSelectedCollectionViewModel;
- (void)showGiftWebGuideIfNeeded;
- (void)updateGiftExtraInfoIfNeeded;
- (void)userOperatePanel;
- (void)onChangeTab:(BOOL)a0;
- (void)trackGiftTabClick:(BOOL)a0 didChange:(BOOL)a1 shouldShowRedDot:(BOOL)a2 beforePageType:(long long)a3;
- (BOOL)checkTargetItemWithEnumerateGitfItem:(id)a0 selectedGiftItemId:(id)a1;
- (void)sendCurrentSelectedItemFromSource:(id)a0;
- (BOOL)prepareForSend:(id)a0;
- (void)sendSelectedItem:(id)a0;
- (BOOL)showConfirmAlertWithGift:(id)a0 interceptTracker:(id)a1;
- (void)trackClickUnlockGiftWithGiftID:(id)a0 extraParams:(id)a1;
- (void)lackOfDiamand:(long long)a0 interceptTracker:(id)a1;
- (void)p_sendPopularityCardGiftWithItem:(id)a0;
- (BOOL)hasPlentyMissionCurrency:(unsigned long long)a0;
- (void)trackPropStatusWithAssetItem:(id)a0;
- (BOOL)propCouldSendWithAssetItem:(id)a0;
- (BOOL)openSchemaInfoForPropIfNeeded;
- (void)p_showMessageBoardGiftPanelWithItem:(id)a0;
- (BOOL)validateWillSendGiftPriceLimitAlertWithPanelViewSelectedItem:(id)a0 selectedItem:(id)a1 interceptTracker:(id)a2;
- (void)realSendGiftWithPanelViewSelectedItem:(id)a0 selectedItem:(id)a1 interceptTracker:(id)a2;
- (void)didSendItem:(id)a0 transaction:(id)a1 dynamicParams:(id)a2 baseCount:(long long)a3;
- (void)appendExtraParamsWithConfig:(id)a0 giftItem:(id)a1;
- (id)getfirstSendSuccFromGiftPanelTimeIntervalStr;
- (void)deselectSelectedItem;
- (long long)showRedeemAlertFromTypeFromOpenGiftFromType:(long long)a0;
- (id)targetCollectionVMWithPageType:(id)a0;
- (void)performPreSelectGiftActionWithRenderOptChangePage:(BOOL)a0 type:(long long)a1 callBack:(id /* block */)a2;
- (void)monitorGiftPreSelectWithGiftID:(id)a0 preSelectType:(long long)a1 error:(id)a2;
- (void)scrollToItemWithId:(id)a0 pageType:(long long)a1 callback:(id /* block */)a2;
- (void)scrollToSelectGiftItem;
- (void)p_enterPopularityCardViewWithItem:(id)a0 needShowLocationOption:(BOOL)a1 cityCode:(id)a2;
- (void)trackPopularityCardClickWithCount:(id)a0 continueTime:(id)a1;
- (id)naviPrompts;
- (void)notifyAllItemsWhenGiftPanelShow;
- (void)_trackTaskShow;
- (void)getCurrentRoomGiftPagesWithCompletion:(id /* block */)a0;
- (void).cxx_destruct;
- (void)dealloc;
- (unsigned long long)selectedIndex;

@end
