@class NSString, HTSMediaMixPlayer, HTSVideoData, VEEditorSession;
@protocol IESLVPlayerDelegate;

@interface IESLVPlayer : IESMMObject <IVEAmazingFeatureProtocol>

@property (nonatomic) long long status;
@property (nonatomic) struct { long long value; int timescale; unsigned int flags; long long epoch; } playerCMTime;
@property (copy, nonatomic) id /* block */ getCurrentImageBlock;
@property (nonatomic) BOOL useEditorSession;
@property (retain, nonatomic) VEEditorSession *editorSession;
@property (nonatomic) BOOL useAudioPlayer;
@property (weak, nonatomic) id<IESLVPlayerDelegate> delegate;
@property (retain, nonatomic) HTSVideoData *videoData;
@property (readonly, nonatomic) HTSMediaMixPlayer *mixPlayer;
@property (readonly, nonatomic) NSString *curFilterPath;
@property (nonatomic) double currentPlayerTime;
@property (copy, nonatomic) id /* block */ updateVideoDataCompleteBlock;
@property (copy, nonatomic) id /* block */ canvasObservableEvent;
@property (copy, nonatomic) id /* block */ keyFrameCallBack;
@property (copy, nonatomic) id /* block */ audioKeyFrameCallBack;
@property (copy, nonatomic) id /* block */ canvasFramUpdateCallback;
@property (nonatomic) BOOL autoPlayWhenAppBecomeActive;
@property (nonatomic) BOOL autoRepeatPlay;
@property (copy, nonatomic) id /* block */ IESMMPlayerActionBlock;
@property (readonly, nonatomic) BOOL converMode;
@property (copy, nonatomic) id /* block */ stickerAddBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)playerWithView:(id)a0 videoData:(id)a1 withBlock:(id /* block */)a2 needReverseVideo:(BOOL)a3 isPanorama:(BOOL)a4 openBuildChain:(BOOL)a5 useNewModule:(BOOL)a6;

- (int)setTextStickerTextParams:(long long)a0 textParams:(id)a1;
- (unsigned long long)addTemplateWithResourcePath:(id)a0 dependResourceParams:(id)a1;
- (int)setTemplateStickerTextParams:(long long)a0 textParams:(id)a1;
- (long long)addEmojiSticker:(id)a0;
- (long long)addInfoSticker:(id)a0 withEffectInfo:(id)a1 userInfo:(id)a2;
- (void)setSticker:(long long)a0 alpha:(double)a1;
- (void)setSticker:(long long)a0 startTime:(double)a1 duration:(double)a2;
- (void)setStickerLayer:(long long)a0 layer:(long long)a1;
- (void)setSticker:(long long)a0 flipX:(BOOL)a1 flipY:(BOOL)a2;
- (void)recoveryPinResult:(long long)a0 withPinData:(id)a1;
- (struct CGSize { double x0; double x1; })getstickerEditBoxSizeNormaliz:(long long)a0;
- (void)removeInfoSticker:(long long)a0;
- (struct CGPoint { double x0; double x1; })getStickerPosition:(long long)a0;
- (long long)addTextSticker;
- (id)getTemplateStickerTextParams:(long long)a0;
- (id)getInfoStickerTemplateParams:(id)a0;
- (int)setPinSelectedArea:(long long)a0 areaParams:(id)a1;
- (void)cancelPin:(long long)a0;
- (long long)getStickerPinStatus:(long long)a0;
- (id)getPinResult:(long long)a0;
- (int)setTextStickerAnim:(long long)a0 animType:(int)a1 animPath:(id)a2 duration:(double)a3;
- (int)setTextStickerPreviewMode:(long long)a0 previewMode:(int)a1;
- (void)updateVideoData:(id)a0;
- (void)addFeature:(id)a0 forAsset:(id)a1;
- (void)deleteFeature:(id)a0 forAsset:(id)a1;
- (void)updateFeature:(id)a0 forAsset:(id)a1;
- (void)replaceFeature:(id)a0 oldFeature:(id)a1 forAsset:(id)a2;
- (void)addFrameExtractDriver:(id)a0 forAsset:(id)a1;
- (void)refreshCanvasGroupsWithKey:(id)a0 config:(id)a1;
- (void)updateVideoTextureVertices:(id)a0 forKey:(id)a1;
- (void)updateAssetAnimateInfo:(id)a0 animateInfo:(id)a1;
- (void)updateAssetBlendMode:(id)a0 blendMode:(id)a1;
- (void)updateSubTrackAssetLayer:(id)a0 layer:(long long)a1;
- (id)getAllKeyFramesAtPts:(unsigned long long)a0;
- (id)initWithView:(id)a0 videoData:(id)a1 withBlock:(id /* block */)a2 needReverseVideo:(BOOL)a3 isPanorama:(BOOL)a4 openBuildChain:(BOOL)a5 useNewModule:(BOOL)a6 actionBlock:(id /* block */)a7 mvModel:(id)a8;
- (void)createEditorSession:(id)a0 videoData:(id)a1;
- (void)setenableLensHdr2Sdr:(BOOL)a0;
- (int)applyLensHdrWithPath:(id)a0;
- (void)applyStabFilter:(id)a0 videoAsset:(id)a1;
- (BOOL)applyEffectIntensity:(struct IESIndensityParam_t { float x0; float x1; float x2; float x3; float x4; float x5; float x6; float x7; float x8; float x9; float x10; float x11; float x12; float x13; float x14; float x15; float x16; float x17; float x18; float x19; float x20; float x21; float x22; float x23; float x24; float x25; float x26; float x27; float x28; float x29; float x30; float x31; float x32; })a0 type:(long long)a1 videoAsset:(id)a2;
- (id)applyEffectPath:(id)a0 withTime:(double)a1 duration:(double)a2;
- (void)updateEffectTimeRange:(id)a0 startTime:(double)a1 duration:(double)a2;
- (double)removeEffectWithRangeID:(id)a0;
- (void)updateAudioData:(id)a0;
- (double)getLastPlayFramRate;
- (id)getFirstRenderTime;
- (void)getCurrentPlayImage:(id /* block */)a0;
- (void)getCurrentPlayImageAsset:(id)a0 completeBlock:(id /* block */)a1;
- (void)getCurrentPlayImageWithColor:(id /* block */)a0;
- (void)getCurrentPlayImageAssetWithColor:(id)a0 completeBlock:(id /* block */)a1;
- (void)stopEditMode;
- (void)getPreviewImageWithConfig:(id)a0 Block:(id /* block */)a1;
- (void)rebuildCanvasGroups;
- (void)transformSource:(id)a0 source:(id)a1;
- (void)updateMovieAnimationType:(id)a0 filterInfo:(id)a1;
- (id)applyAudioFilterWithType:(int)a0 config:(id)a1 forVideoAsset:(id)a2;
- (BOOL)removeVideoSoundFilter:(id)a0;
- (id)applyAudioFilterWithType:(int)a0 config:(id)a1 forAudioAsset:(id)a2;
- (BOOL)removeAudioSoundFilter:(id)a0;
- (void)commitAllKeyFrame;
- (double)getaudioVolumeKeyFrameAtPts:(unsigned long long)a0 withAVAsset:(id)a1;
- (id)getCurrentFrameFromFirstPreview;
- (void)setFirstRenderBlk:(id /* block */)a0;
- (BOOL)startMattingDetectWithAVAsset:(id)a0 resourceFinder:(void /* function */ *)a1 detectResult:(id)a2 resultBlock:(id /* block */)a3;
- (void)pauseMattingDetectWithAVAsset:(id)a0;
- (void)cancelMattingDetectWithAVAsset:(id)a0;
- (void)refreshMattingEffect;
- (void)pauseStillRender;
- (void)resumeStillRender;
- (void)preparePin;
- (void)setAutoFillFrame:(id)a0 forAsset:(id)a1;
- (id)initAudioPlayerWithVideoData:(id)a0;
- (void)resetPlayerWithView:(id)a0;
- (void)audioSeekToTime:(double)a0;
- (void)seekToTimeAndRender:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0 seekMode:(unsigned long long)a1;
- (void)seekToTimeAndRender:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (void)seekToTimeAndRender:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0 seekMode:(unsigned long long)a1 completionHandler:(id /* block */)a2;
- (void)seekToTimeAndRender:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0 completionHandler:(id /* block */)a1;
- (BOOL)applyFilterPath:(id)a0 type:(long long)a1 videoAsset:(id)a2;
- (void)setStickerNormaliz:(long long)a0 offsetX:(double)a1 offsetY:(double)a2 angle:(double)a3 scale:(double)a4;
- (id)getInfosticker:(long long)a0;
- (void)checkAudioSessionAsync:(BOOL)a0;
- (void)startEditMode:(id)a0;
- (void)getPreviewImage:(id /* block */)a0;
- (void)getPreviewImageAtTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0 compeletion:(id /* block */)a1;
- (void)startPin:(long long)a0 pinStartTime:(float)a1 pinDuration:(float)a2 completion:(id /* block */)a3 progressBlock:(id /* block */)a4;
- (void).cxx_destruct;
- (void)play;
- (void)pause;
- (id)init;
- (void)stop;
- (void)dealloc;
- (void)setAudioVolume:(float)a0;
- (void)playFromTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (void)setPreviewModeType:(long long)a0;

@end
