@class HTSEventForwardingView, UIImage, UILabel, IESLiveInteractionGuestAFKOverlapView, IESLiveVoiceWave, MASConstraint, IESLiveMultiKTVSingerProfileTagView, UIView, NSString, IESLiveMultiKTVMidiTagView, IESLiveUniformTag, CAShapeLayer, IESLiveMultiKTVLyricModeHighScoreTagView, NSArray, IESLiveInteractionFanTicketView, IESLiveMultiKTVAudioStageViewUser, UIImageView;
@protocol IESLiveCompoundSubscription, IESLiveWebPPlayer;

@interface IESLiveMultiKTVSingerProfileView : HTSEventForwardingView

@property (retain, nonatomic) HTSEventForwardingView *avatarContainer;
@property (retain, nonatomic) HTSEventForwardingView *playerContainer;
@property (retain, nonatomic) UILabel *nicknameLabel;
@property (retain, nonatomic) IESLiveInteractionFanTicketView *fanTicketView;
@property (retain, nonatomic) UIImageView *avatarView;
@property (retain, nonatomic) UIImageView<IESLiveWebPPlayer> *animationView;
@property (retain, nonatomic) id<IESLiveCompoundSubscription> disposable;
@property (retain, nonatomic) UIView *playerView;
@property (retain, nonatomic) UIView *removingPlayerView;
@property (retain, nonatomic) CAShapeLayer *playerMaskLayer;
@property (copy, nonatomic) NSString *speakingImageName;
@property (retain, nonatomic) IESLiveInteractionGuestAFKOverlapView *afkView;
@property (retain, nonatomic) UIView *nicknameContainer;
@property (retain, nonatomic) UIView *silenceView;
@property (retain, nonatomic) IESLiveMultiKTVSingerProfileTagView *tagView;
@property (retain, nonatomic) IESLiveUniformTag *tagView_v2;
@property (retain, nonatomic) IESLiveMultiKTVMidiTagView *midiTagView;
@property (retain, nonatomic) IESLiveMultiKTVLyricModeHighScoreTagView *videoMidiTagView;
@property (nonatomic) BOOL isNicknameLoadInStageCenter;
@property (retain, nonatomic) MASConstraint *silenceViewWidthConstraint;
@property (retain, nonatomic) MASConstraint *nicknameLabelLeadingConstraint;
@property (retain, nonatomic) MASConstraint *nicknameLabelTrailingConstraint;
@property (nonatomic) double animationViewSideLength;
@property (nonatomic) BOOL inDynamicKTV;
@property (retain, nonatomic) IESLiveVoiceWave *limitVoiceWave;
@property (copy, nonatomic) NSArray *loopAnimationURLs;
@property (retain, nonatomic) UIImage *defaultBgWebpImage;
@property (copy, nonatomic) id /* block */ showPlayerAction;
@property (nonatomic) double scale;
@property (retain, nonatomic) IESLiveMultiKTVAudioStageViewUser *user;
@property (nonatomic) BOOL playing;
@property (nonatomic) BOOL forbidShowFantickView;
@property (nonatomic) BOOL originalHiddenStatus;
@property (copy, nonatomic) id /* block */ wholeAreaAction;
@property (copy, nonatomic) id /* block */ fanTicketAction;
@property (copy, nonatomic) id /* block */ avatarAction;
@property (copy, nonatomic) id /* block */ midiTagAction;
@property (nonatomic) long long layoutType;

- (double)avatarRadius;
- (void)showAvatar;
- (double)tagViewWidth;
- (void)hideAvatar;
- (id)defaultLoopWebpImage;
- (void)updateFanticketAreaHidden:(BOOL)a0;
- (BOOL)isLimitVoiceWaveValid:(id)a0;
- (void)hideTag;
- (id)initWithScale:(double)a0 diContext:(id)a1;
- (void)updateStageSingMode:(int)a0;
- (id)initWithScale:(double)a0 speakingImageName:(id)a1 diContext:(id)a2;
- (void)didTapWholeAreaActions:(id)a0;
- (double)playerRatio;
- (void)remakeTitleConstraints:(BOOL)a0 layoutType:(long long)a1;
- (void)remakeAvatarConstrainst:(BOOL)a0 layoutType:(long long)a1;
- (void)updateNickNameAreaLaout:(long long)a0;
- (BOOL)hasTagView;
- (void)updateAnimatedTagHiddenStatus;
- (void)updateAvatarLayout:(long long)a0;
- (void)updateFanticketAlphaWithLayoutTyle:(long long)a0;
- (void)updateSilenceViewHidden:(BOOL)a0;
- (void)updateAfkViewHidden:(BOOL)a0 isMuted:(BOOL)a1;
- (void)updateVoiceWaveWithMicDress:(id)a0;
- (void)removePlayerView;
- (void)hidePlayerViewWithLayoutType:(long long)a0 completion:(id /* block */)a1;
- (void)updateAfkViewHidden:(BOOL)a0;
- (void)excutePlayerAnimation:(double)a0 isShow:(BOOL)a1 completion:(id /* block */)a2;
- (void)showStageModeAnimatedTag:(id)a0 iconURLString:(id)a1 colorsARGBHexStr:(id)a2 completion:(id /* block */)a3;
- (void)showVideoModeAnimatedTag:(id)a0 completion:(id /* block */)a1;
- (void)didTapMidiTagViewActions;
- (void)didTapAvatarViewActions:(id)a0;
- (void)showWithAnimationWithDuration:(double)a0 delay:(double)a1;
- (void)updateUIWithLayoutType:(long long)a0;
- (void)addPlayerView:(id)a0 layoutType:(long long)a1;
- (void)updateSoundAnimationWithLoopURLs:(id)a0;
- (void)showPlayerViewWithLayoutType:(long long)a0;
- (void)showSingingListEntranceView:(id)a0;
- (void)showTag:(id)a0 tagColorStr:(id)a1 colorsARGBHexStr:(id)a2;
- (void)showTagWithInfo:(id)a0;
- (void)enterDynamicMultikTVMode;
- (void)exitDynamicMultikTVMode;
- (void)showAnimatedTag:(id)a0 iconURLString:(id)a1 colorsARGBHexStr:(id)a2 completion:(id /* block */)a3;
- (void)setupConstraints;
- (void).cxx_destruct;
- (double)avatarSize;
- (void)setupViews;
- (void)updateUser:(id)a0;

@end
