@class UIView, NSTimer, UIImage, NSString, CAShapeLayer, UIImageView, UIButton, IESLiveCropScrollView, UIBezierPath, UILabel;

@interface IESLiveImageCropViewController : UIViewController <UIScrollViewDelegate>

@property (copy, nonatomic) id /* block */ completion;
@property (retain, nonatomic) UIImage *image;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } cropRect;
@property (nonatomic) double cropRectCornerRadius;
@property (nonatomic) BOOL expandEnable;
@property (nonatomic) double criticalRatio;
@property (nonatomic) long long nowRatioType;
@property (nonatomic) long long imageCropType;
@property (retain, nonatomic) UIImageView *imageView;
@property (retain, nonatomic) UIView *cropView;
@property (retain, nonatomic) IESLiveCropScrollView *scrollView;
@property (retain, nonatomic) UIView *topBarView;
@property (retain, nonatomic) UIButton *cancelButton;
@property (retain, nonatomic) UIButton *confirmButton;
@property (retain, nonatomic) UIButton *resetButton;
@property (retain, nonatomic) UIButton *descriptionButton;
@property (retain, nonatomic) UIBezierPath *path;
@property (retain, nonatomic) CAShapeLayer *cropMask;
@property (retain, nonatomic) CAShapeLayer *borderLayer;
@property (retain, nonatomic) UIView *expandBottomView;
@property (retain, nonatomic) UIButton *fourToThreeRatioButton;
@property (retain, nonatomic) UIButton *threeToOneRatioButton;
@property (retain, nonatomic) UILabel *fourTothhreeRatioLable;
@property (retain, nonatomic) UILabel *threeToOneRatioLable;
@property (retain, nonatomic) UILabel *imageCropLable;
@property (retain, nonatomic) UIImageView *imageCropOval;
@property (retain, nonatomic) UIImageView *imageCropRectangle;
@property (nonatomic) BOOL editing;
@property (retain, nonatomic) NSTimer *resetTimer;
@property (copy, nonatomic) NSString *descriptionScheme;
@property (copy, nonatomic) NSString *requestPage;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)getSettings;
- (void)startResetTimer;
- (void)cancelResetTimer;
- (double)scrollViewHeight;
- (void)setDefaultRatio;
- (void)setupUserInterface;
- (void)calculateCropRect;
- (void)calculateImageView;
- (void)calculateScrollView;
- (void)drawCropViewMask;
- (void)drawBoard;
- (void)scrollViewContentReset;
- (void)setCropEditing:(BOOL)a0 animated:(BOOL)a1;
- (id)cropImageWithImageViewWidth:(double)a0 convertRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1 cornerRadius:(double)a2;
- (void)confirmButtonHandler;
- (void)resetButtonHandler;
- (id)initWithImage:(id)a0 imageCropType:(long long)a1 completion:(id /* block */)a2;
- (void)isCropEditing:(BOOL)a0 animated:(BOOL)a1;
- (void)descriptionButtonHandler;
- (void)fourToThreeHandler;
- (void)threeToOneHandler;
- (void)scrollViewWillBeginZooming:(id)a0 withView:(id)a1;
- (id)viewForZoomingInScrollView:(id)a0;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (void)scrollViewDidEndZooming:(id)a0 withView:(id)a1 atScale:(double)a2;
- (BOOL)prefersStatusBarHidden;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)setupScrollView;
- (void)cancelButtonHandler;
- (void)startEditing;
- (void)timerTriggered;
- (void)calculate;

@end
