@class IESLLTempoContext, NSString, NSArray, IESLLTempoAttrMap, IESLLTempoBaseWidget, NSDictionary, NSMutableArray;
@protocol IESLLTempoWidgetProtocol;

@interface IESLLTempoNode : NSObject <NSCopying, IESLLTempoNodeProtocol>

@property (retain, nonatomic) NSDictionary *effectMap;
@property (retain, nonatomic) id exprResult;
@property (copy, nonatomic) NSString *treeType;
@property (nonatomic) unsigned long long patchType;
@property (copy, nonatomic) NSArray *deletions;
@property (weak, nonatomic) IESLLTempoContext *context;
@property (weak, nonatomic) IESLLTempoNode *attachCustomComponent;
@property (nonatomic) unsigned long long type;
@property (copy, nonatomic) NSString *tagName;
@property (copy, nonatomic) NSDictionary *style;
@property (copy, nonatomic) IESLLTempoAttrMap *attrs;
@property (copy, nonatomic) NSDictionary *events;
@property (copy, nonatomic) NSString *nodeID;
@property (weak, nonatomic) IESLLTempoNode *parent;
@property (retain, nonatomic) NSMutableArray *children;
@property (copy, nonatomic) NSArray *childrenIDs;
@property (copy, nonatomic) NSDictionary *props;
@property (copy, nonatomic) NSDictionary *data;
@property (copy, nonatomic) NSDictionary *preProps;
@property (copy, nonatomic) NSDictionary *preData;
@property (copy, nonatomic) NSString *componentID;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } nodeFrame;
@property (copy, nonatomic) NSString *ifCondition;
@property (copy, nonatomic) NSString *consequentRootID;
@property (copy, nonatomic) NSString *alternateRootID;
@property (copy, nonatomic) NSString *forCondition;
@property (copy, nonatomic) NSString *bodyRootID;
@property (copy, nonatomic) NSString *itemKey;
@property (copy, nonatomic) NSString *indexKey;
@property (copy, nonatomic) NSDictionary *envData;
@property (copy, nonatomic) NSString *reuseKey;
@property (retain, nonatomic) IESLLTempoBaseWidget<IESLLTempoWidgetProtocol> *widget;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)rootComponentID;
+ (id)getAnimationContextWithWidget:(id)a0 animationName:(id)a1;
+ (BOOL)animationsStillExistedOnAnimationContext:(id)a0;

- (id)toJSONString;
- (void)addView;
- (void)onDestroy;
- (void)loadAnimation;
- (void)setRotateScaleAnchorPoint:(struct CGPoint { double x0; double x1; })a0 forView:(id)a1;
- (id)getRealChildren;
- (void)loadRenderView;
- (void)loadFrame;
- (void)loadCommonStyle;
- (void)loadCommonAttributeWithContext:(id)a0;
- (long long)getRealCurrentIndex;
- (id)getRealParent;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getCalculateFrame;
- (void)yoga_layoutAddChildNode:(id)a0;
- (void)loadNoShrink;
- (void)loadWidgetWithContext:(id)a0;
- (id)getOriginTree;
- (void)loadExposureAttributeWithContext:(id)a0;
- (void)loadAccessibilityEnable;
- (void)loadAccessibilityLabel;
- (void)loadAccessibilityTraits;
- (void)calculateLayoutWithWidthMode:(long long)a0 heightMode:(long long)a1 containerWidth:(double)a2 containerHeight:(double)a3 error:(id *)a4;
- (void)loadBorderStyle;
- (void)loadOpacityStyle;
- (void)loadBackgroundStyle;
- (void)loadVisibilityStyle;
- (void)loadOverflow;
- (void)loadTransform;
- (void)loadAnimationStyle;
- (void)addBorderForSide:(unsigned long long)a0 borderTopLeftRadius:(double)a1 borderTopRightRadius:(double)a2 borderBottomRightRadius:(double)a3 borderBottomLeftRadius:(double)a4 width:(double)a5 height:(double)a6 color:(id)a7 lineWidth:(double)a8;
- (void)setupElementTransformOrigin;
- (void)removeExistingBackgroundLayer;
- (void)cancelBackgroundColorStyle;
- (BOOL)isBackgroundImage:(id)a0;
- (void)loadBackgroundImageStyle:(id)a0;
- (void)loadBackgroundColorStyle:(id)a0;
- (BOOL)isImageURL:(id)a0;
- (void)setupImageBackgroundWithURL:(id)a0;
- (void)setupGradientBackgroundWithStyle:(id)a0;
- (void)setupRadialGradientBackgroundWithStyle:(id)a0;
- (id)extractContentBetweenBracketsWithPrefix:(id)a0 fromString:(id)a1;
- (id)splitContentByCommaWithBrackets:(id)a0;
- (void)configureGradientLayer:(id)a0 withComponents:(id)a1;
- (id)parseRadialGradientParameters:(id)a0;
- (void)configureRadialGradientLayer:(id)a0 withParameters:(id)a1;
- (void)configureGradientAngle:(id)a0 withDegreeString:(id)a1;
- (BOOL)isGradientDirectionKeyword:(id)a0;
- (void)configureGradientDirection:(id)a0 withDirectionString:(id)a1;
- (void)parseGradientComponents:(id)a0 startFromIndex:(long long)a1 colors:(id)a2 locations:(id)a3;
- (id)separateColorAndPosition:(id)a0;
- (id)splitRadialGradientMainParts:(id)a0;
- (void)parseRadialGradientShapeAndPosition:(id)a0 intoParams:(id)a1;
- (void)parseRadialGradientColors:(id)a0 colors:(id)a1 locations:(id)a2;
- (void)parseRadialGradientSize:(id)a0 intoParams:(id)a1;
- (void)parseRadialGradientPosition:(id)a0 intoParams:(id)a1;
- (double)parseRadialGradientValue:(id)a0;
- (double)parseRadialGradientPositionValue:(id)a0 isHorizontal:(BOOL)a1;
- (void)invokeUIWithMethodName:(id)a0 methodParams:(id)a1 callback:(id /* block */)a2;
- (void)parseWithNodeDict:(id)a0;
- (BOOL)containsLoadEffect;
- (void)insertChildNode:(id)a0 index:(long long)a1;
- (id)initWithNodeDict:(id)a0;
- (long long)getRealIndexInParent;
- (id)getRealLeftSiblingNode;
- (void).cxx_destruct;
- (id)toDictionary;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)removeView;
- (void)setParentNode:(id)a0;
- (void)addChildNode:(id)a0;
- (id)createBackgroundLayer;
- (void)onLoad;
- (void)onUpdate;
- (id)createGradientLayer;

@end
