@class NSMutableDictionary, IESLiveGiftTrayBaseImageABConfig, UILabel, IESLiveGCDTimer, NSDictionary, IESLiveGiftTraySlideRateABConfig, IESLiveAnimatedImageView, UIView, IESLiveGiftTrayPostEffectView, CAGradientLayer, CALayer, HTSLiveArtTextLabel, HTSLiveAvatarImageView, NSString, CAShapeLayer, NSArray, IESLiveGiftTrayAnimationModel, IESLiveRebornGiftAnimationNode, UIImageView;
@protocol IESLiveLanguageService, IESLiveGiftImageTemplateService;

@interface IESLiveRebornPortraitGiftView : IESLiveRebornGiftView {
    BOOL isAnimating;
    BOOL isComboView;
    BOOL isGroup;
    BOOL isFaked;
    NSString *giftKey;
    id /* block */ onAnimationEnd;
    id /* block */ onAvatarViewTap;
    id /* block */ onTouchViewTap;
    id /* block */ onFlyMicAnimationStarted;
    id /* block */ onTrayExpandingAnimationEnd;
    id /* block */ flipAngle;
}

@property (nonatomic) BOOL isBigScale;
@property (retain, nonatomic) IESLiveAnimatedImageView *preAnimatedImageView;
@property (retain, nonatomic) IESLiveGiftTrayPostEffectView *postAnimatedImageView;
@property (retain, nonatomic) IESLiveGiftTrayAnimationModel *animationModel;
@property (retain, nonatomic) UIView *trayContainerView;
@property (retain, nonatomic) CAShapeLayer *trayExpandingLayer;
@property (retain, nonatomic) NSMutableDictionary *trayRipplesImageDict;
@property (retain, nonatomic) NSDictionary *trayRippleConfig;
@property (retain, nonatomic) IESLiveAnimatedImageView *backgroundImageView;
@property (retain, nonatomic) UIView *gradientView;
@property (retain, nonatomic) CAGradientLayer *gradientViewLayer;
@property (retain, nonatomic) UIView *touchView;
@property (retain, nonatomic) HTSLiveAvatarImageView *avatarView;
@property (retain, nonatomic) UIView *avatarContainer;
@property (retain, nonatomic) HTSLiveAvatarImageView *topAvatar;
@property (retain, nonatomic) HTSLiveAvatarImageView *bottomAvatar;
@property (retain, nonatomic) UIView *needScaleView;
@property (retain, nonatomic) UILabel *nameLabel;
@property (retain, nonatomic) UILabel *descLabel;
@property (retain, nonatomic) UIImageView *giftView;
@property (retain, nonatomic) IESLiveAnimatedImageView *animatedGiftView;
@property (retain, nonatomic) HTSLiveArtTextLabel *groupCountLabel;
@property (retain, nonatomic) UIView *comboContainerView;
@property (retain, nonatomic) HTSLiveArtTextLabel *comboXLabel;
@property (retain, nonatomic) HTSLiveArtTextLabel *comboNumberLabel;
@property (retain, nonatomic) HTSLiveArtTextLabel *comboXRedLabel;
@property (retain, nonatomic) HTSLiveArtTextLabel *comboNumberRedLabel;
@property (retain, nonatomic) IESLiveAnimatedImageView *comboStarView;
@property (nonatomic) BOOL disableComboCount;
@property (copy, nonatomic) id /* block */ stopAnimationTask;
@property (copy, nonatomic) NSArray *groupColorArr;
@property (nonatomic) long long groupIndex;
@property (nonatomic) unsigned long long animationLevel;
@property (retain, nonatomic) IESLiveRebornGiftAnimationNode *currentNode;
@property (retain, nonatomic) CAGradientLayer *flashLayer;
@property (retain, nonatomic) UIView *outlineView;
@property (retain, nonatomic) CALayer *outlineMaskLayer;
@property (retain, nonatomic) CALayer *maskLayer;
@property (retain, nonatomic) IESLiveAnimatedImageView *trayTagImageView;
@property (nonatomic) long long currentFlyMicIndex;
@property (nonatomic) long long flyMicCount;
@property (retain, nonatomic) IESLiveGCDTimer *flyMicTimer;
@property (nonatomic) long long maxComboCountForLabel;
@property (retain, nonatomic) IESLiveGiftTrayBaseImageABConfig *trayBaseImageABConfig;
@property (retain, nonatomic) IESLiveGiftTraySlideRateABConfig *traySlideRateABCofig;
@property (retain, nonatomic) id<IESLiveLanguageService> languageService;
@property (nonatomic) BOOL trayGroupModeServerControl;
@property (nonatomic) BOOL enableAggregateBigGiftTray;
@property (retain, nonatomic) NSDictionary *portraitDescDegradeConfig;
@property (nonatomic) BOOL enableHeic;
@property (nonatomic) BOOL enableCache;
@property (weak, nonatomic) id<IESLiveGiftImageTemplateService> templateService;
@property (nonatomic) BOOL isTopGiftView;
@property (nonatomic) double scale;
@property (nonatomic) BOOL degradeGiftTray;

- (void)didSetAttachingDIContext;
- (void)stopAnimationWithCompletionHandler:(id /* block */)a0;
- (void)updateWithGiftAnimationNode:(id)a0;
- (void)startFlashAnimation;
- (void)prepareToReuse;
- (BOOL)isFaked;
- (void)setIsFaked:(BOOL)a0;
- (id /* block */)onAnimationEnd;
- (void)setOnAnimationEnd:(id /* block */)a0;
- (id /* block */)onTouchViewTap;
- (void)setOnTouchViewTap:(id /* block */)a0;
- (BOOL)isAudience;
- (void)touchViewDidTap;
- (void)setUpGroup;
- (void)p_updateColorIndexWithPrice:(unsigned long long)a0;
- (void)setIsComboView:(BOOL)a0;
- (BOOL)fromCurrentUser;
- (void)startAnimationWithCompletionHandler:(id /* block */)a0 messageListCallback:(id /* block */)a1;
- (void)startComboAnimation:(id)a0 groupCount:(id)a1 upperBound:(BOOL)a2 completionHandler:(id /* block */)a3 messageListCallback:(id /* block */)a4;
- (void)setGiftKey:(id)a0;
- (BOOL)isComboView;
- (id /* block */)onAvatarViewTap;
- (void)setOnAvatarViewTap:(id /* block */)a0;
- (id /* block */)onTrayExpandingAnimationEnd;
- (void)setOnTrayExpandingAnimationEnd:(id /* block */)a0;
- (id /* block */)onFlyMicAnimationStarted;
- (void)setOnFlyMicAnimationStarted:(id /* block */)a0;
- (id /* block */)flipAngle;
- (void)setFlipAngle:(id /* block */)a0;
- (void)avatarViewDidTap;
- (id)copyFromNode:(id)a0;
- (unsigned long long)giftPriceWithNode:(id)a0;
- (void)p_updateAnimationLevelWithGroupIndex:(long long)a0;
- (void)p_renderComboCount:(id)a0 upperBound:(BOOL)a1;
- (void)startAnimationWithCompletionHandler:(id /* block */)a0 shouldAutoStop:(BOOL)a1 messageListCallback:(id /* block */)a2;
- (void)startComboAnimation:(id)a0 groupCount:(id)a1 upperBound:(BOOL)a2 completionHandler:(id /* block */)a3 shouldAutoStop:(BOOL)a4 messageListCallback:(id /* block */)a5;
- (void)p_setStaticImageOnGiftTrayWithURL:(id)a0;
- (double)p_timeIntervalWithAnimationLevel:(unsigned long long)a0;
- (void)p_stopFlyMicTimer;
- (void)preAnimationDidTap;
- (void)postAnimationDidTap;
- (void)p_setAnimatedImageOnGiftTrayWithImage:(id)a0;
- (void)p_setStaticImageOnGiftTrayWithImage:(id)a0;
- (BOOL)enableTrayTag;
- (BOOL)enablePostAnimation;
- (void)p_resetAnimatedGiftView;
- (BOOL)enableCombo;
- (void)prepareToShowTrayViewWithCompletion:(id /* block */)a0;
- (BOOL)enablePreAnimation;
- (void)startTrayRippleImageAnimation;
- (void)startTrayExpandingAnimation;
- (void)applyTransformWithScale:(double)a0 animation:(BOOL)a1 completion:(id /* block */)a2;
- (void)p_AddComboStarInNeedWithCurrentCount:(id)a0;
- (void)p_updateFlyMic;
- (double)p_transformUseTraySlideRateWithTimeInterval:(double)a0;
- (BOOL)enableMultiInteractGift;
- (void)p_restartFlyMicAnimation;
- (struct CGPoint { double x0; double x1; })p_flymicStartPointWithAngle:(double)a0 forFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)p_rotateFlyMicImageWithAngle:(double)a0;
- (struct CGPoint { double x0; double x1; })p_rotateStartPoint:(struct CGPoint { double x0; double x1; })a0 withAngle:(double)a1 centerPoint:(struct CGPoint { double x0; double x1; })a2;
- (double)p_baseTimeIntervalWithAnimationLevel:(unsigned long long)a0;
- (double)p_traySlideRate;
- (double)p_calculateLargeGiftTimeInterval;
- (BOOL)disableTrayAnimationWithFilter:(id)a0 type:(long long)a1;
- (void)upgradeWithGiftAnimationNode:(id)a0;
- (void)startAnimation;
- (void).cxx_destruct;
- (BOOL)isAnimating;
- (void)setIsAnimating:(BOOL)a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (BOOL)isGroup;
- (void)setIsGroup:(BOOL)a0;
- (void)dealloc;
- (id)giftKey;
- (void)layoutUI;

@end
