@class UIStackView, IESLivePublicScreenViewModel, NSString, IESLivePublicScreenContainer, NSMutableDictionary, IESLivePSAttachmentManager, IESLivePublicScreenNotificationCenter, IESLivePublicScreenContext;
@protocol IESLivePublicScreenViewDelegate, IESLivePublicScreenHighValueMaskService;

@interface IESLivePublicScreenView : IESLiveMessageListView <IESLivePublicScreenService, IESLivePSComponentInteractQueueDelegate, IESLivePSComponentInteractAreaDelegate, IESLivePSAttachmentAction, IESLivePublicScreenLayoutSubscriber>

@property (retain, nonatomic) IESLivePublicScreenContext *publicScreenContext;
@property (retain, nonatomic) IESLivePublicScreenViewModel *viewModel;
@property (retain, nonatomic) IESLivePublicScreenNotificationCenter *notifyCenter;
@property (nonatomic) double publicScreenHeight;
@property (nonatomic) double publicScreenWidth;
@property (nonatomic) double publicScreenSetWidth;
@property (retain, nonatomic) id<IESLivePublicScreenHighValueMaskService> maskService;
@property (nonatomic) BOOL firstUpdated;
@property (weak, nonatomic) id<IESLivePublicScreenViewDelegate> componentDelegate;
@property (retain, nonatomic) UIStackView *stackContainer;
@property (retain, nonatomic) IESLivePublicScreenContainer *topContainer;
@property (retain, nonatomic) IESLivePublicScreenContainer *bottomContainer;
@property (retain, nonatomic) IESLivePublicScreenContainer *outsideBottomContainer;
@property (retain, nonatomic) NSMutableDictionary *interactQueueMap;
@property (retain, nonatomic) NSMutableDictionary *interactAreaMap;
@property (retain, nonatomic) NSMutableDictionary *insertDataSuccessCountDic;
@property (retain, nonatomic) NSMutableDictionary *insertDataSumCountDic;
@property (retain, nonatomic) NSMutableDictionary *insertQueueDataSuccessCountDic;
@property (retain, nonatomic) NSMutableDictionary *insertQueueDataSumCountDic;
@property (retain, nonatomic) IESLivePSAttachmentManager *attachmentManager;
@property (copy, nonatomic) id /* block */ updatePublicScreenContainerHeightBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)ieslive_topContainerConfig;
+ (id)ieslive_bottomContainerConfig;
+ (id)ieslive_outsideBottomContainerConfig;
+ (id)ieslive_componentConfig;
+ (id)publicScreenViewWithDescriptor:(id)a0;

- (id)initWithDIContext:(id)a0;
- (double)topContainerHeight;
- (void)componentWillUnmount;
- (void)publicScreenLayoutChanged:(id)a0 forType:(unsigned long long)a1;
- (id)queryViewByType:(id)a0;
- (void)adjustTopMaskHeight:(double)a0 bizScene:(id)a1;
- (void)enableUpdateDataSource:(BOOL)a0 withCaller:(id)a1;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })queryConvertedMessageListRect;
- (void)bindViewModel:(id)a0;
- (void)updateMessageList;
- (void)enableUpdateDataSource:(BOOL)a0;
- (void)addPublicScreenComponentWithConfigModel:(id)a0;
- (void)updatePublicScreenComponentWithConfigModel:(id)a0;
- (void)removePublicScreenComponentWithConfigModel:(id)a0;
- (void)refreshUnreadTipView;
- (void)didAddToContainer;
- (void)startRefreshWithCaller:(id)a0;
- (void)tapUnreadTipView;
- (void)setTopMaskHeight:(double)a0;
- (void)hideContainers:(BOOL)a0;
- (void)stopRefreshWithCaller:(id)a0;
- (void)didAttachAttachment:(id)a0;
- (void)componentShow:(id)a0;
- (void)componentRemove:(id)a0;
- (void)trackComponentAssembleWithConfigModel:(id)a0;
- (id)checkInteractAreaWithModel:(id)a0;
- (void)componentViewProduced:(id)a0;
- (void)removeComponentWithConfigModel:(id)a0;
- (void)addPSComponentView:(id)a0;
- (void)updateMessageListFromReverse:(BOOL)a0 toRow:(long long)a1 section:(long long)a2;
- (void)updateViewWithContext:(id)a0;
- (void)trackConfigComponentInsert;
- (void)addPublicScreenLayoutSubscriber;
- (void)layoutPublicScreenWithLayoutData:(id)a0;
- (void)changeSubscribForPublicScreenWidthWithlayoutData:(id)a0;
- (void)updateConstraintsForComponents;
- (id)queryViewFromContainer:(id)a0 withType:(id)a1;
- (BOOL)filterByBlocklistWithConfigModel:(id)a0;
- (void)trackConfigModelCountForTypeKey:(id)a0 withDataDic:(id)a1;
- (BOOL)securityCheck:(id)a0;
- (id)checkInteractQueueWithModel:(id)a0;
- (void)produceComponent:(id)a0;
- (void)updatePublicScreenContainerHeight:(long long)a0;
- (void)logForSecurityCheck:(id)a0;
- (void)p_removePublicScreenComponentWithConfigModel:(id)a0;
- (void)p_componentViewProduced:(id)a0;
- (void)addPSComponentView:(id)a0 withConfigModel:(id)a1;
- (void)immediateRefresh;
- (void).cxx_destruct;
- (void)removeFromSuperview;
- (void)orientationChanged:(long long)a0;
- (void)setHidden:(BOOL)a0;
- (void)layoutSubviews;
- (void)dealloc;
- (void)setup;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;

@end
