@class IESLiveInteractSeatElementLoader, IESLiveInteractVoiceWaveView, UIFont, IESliveAudioSeatPriorityChecker, HTSLiveLinkmicPositionItem, RACDisposable, UIColor, IESLiveMultiAudioAvatarViewConfig, NSString, NSAttributedString, IESLiveMicPosTagInfo, NSArray, IESLiveMicInfoItem, RACCompoundDisposable, IESLiveInteractEmptySeatElement, IESLiveInteractCompetitionGameGuestInfoViewModel;
@protocol IESLiveCompetitionGameRouter, IESLiveTeamFightRouter, IESLiveMultiAudioAudienceRouter, IESLiveInteractVoiceWaveRouter, IESLiveInteractGameAvatarRouter, IESLiveGuestBattleProvider, IESLiveRoomService, IESLiveInteractUserModel, IESLiveGuestBattleRouter, IESLiveInteractionBattleService, IESLiveSocialInteractiveRouter, IESLiveTeamFightProvider, IESLiveAudioSeatUpdateAction, IESLiveCompoundSubscription;

@interface IESLiveAudioSeatViewModel : NSObject <IESLiveAudioSeatViewModelInputForAll, IESLiveAudioSeatViewModelOutputForAll>

@property (retain, nonatomic) id<IESLiveCompoundSubscription> disposable;
@property (retain, nonatomic) RACCompoundDisposable *rac_disposable;
@property (weak, nonatomic) id<IESLiveRoomService> room;
@property (nonatomic) long long teamFightStatus;
@property (retain, nonatomic) UIColor *teamSignColor;
@property (nonatomic) BOOL hasBindUser;
@property (retain, nonatomic) id<IESLiveInteractUserModel> guest;
@property (nonatomic) long long index;
@property (retain, nonatomic) IESliveAudioSeatPriorityChecker *checkerForEmptyAvatar;
@property (nonatomic) BOOL afkViewShow;
@property (nonatomic) BOOL pauseViewShow;
@property (nonatomic) long long emptyAvatarType;
@property (copy, nonatomic) NSAttributedString *emptyAvartarText;
@property (copy, nonatomic) NSArray *joinIconUrsl;
@property (copy, nonatomic) NSArray *localJoinIconUrsl;
@property (nonatomic) long long bgColorType;
@property (nonatomic) long long userNameIconType;
@property (nonatomic) long long userNameType;
@property (copy, nonatomic) NSString *userNameText;
@property (nonatomic) double userLabelWidth;
@property (nonatomic) long long userLabelTextAlignment;
@property (nonatomic) long long maxNameLength;
@property (retain, nonatomic) UIFont *userLabelFont;
@property (copy, nonatomic) NSString *emptyUserNameText;
@property (copy, nonatomic) NSString *lastEmptyUserNameText;
@property (copy, nonatomic) NSString *acceptLinkText;
@property (retain, nonatomic) UIColor *acceptLinkTitleColr;
@property (retain, nonatomic) UIColor *acceptLinkBgColr;
@property (nonatomic) long long enlargeType;
@property (nonatomic) struct CGPoint { double x; double y; } enlargeAvatarEmojiOrigin;
@property (nonatomic) long long seatNameType;
@property (copy, nonatomic) NSString *normalSeatName;
@property (copy, nonatomic) NSString *paidLinkSeatName;
@property (retain, nonatomic) IESLiveMicPosTagInfo *tagInfo;
@property (retain, nonatomic) IESLiveMicInfoItem *micItemInfo;
@property (retain, nonatomic) IESliveAudioSeatPriorityChecker *checkerForSeatName;
@property (retain, nonatomic) HTSLiveLinkmicPositionItem *positionItem;
@property (retain, nonatomic) UIColor *seatBgColor;
@property (retain, nonatomic) RACDisposable *linkmicTimer;
@property (retain, nonatomic) RACDisposable *linkmicSeatNameReplaceTimer;
@property (retain, nonatomic) IESLiveInteractEmptySeatElement *emptyElement;
@property (weak, nonatomic) id<IESLiveInteractionBattleService> battleService;
@property (weak, nonatomic) id<IESLiveTeamFightRouter> teamFightService;
@property (weak, nonatomic) id<IESLiveTeamFightProvider> teamFightProvider;
@property (weak, nonatomic) id<IESLiveGuestBattleRouter> guestBattleRouter;
@property (weak, nonatomic) id<IESLiveCompetitionGameRouter> gameRouter;
@property (weak, nonatomic) id<IESLiveTeamFightRouter> teamFightRouter;
@property (weak, nonatomic) id<IESLiveMultiAudioAudienceRouter> audioAudienceRouter;
@property (weak, nonatomic) id<IESLiveGuestBattleProvider> battleProvider;
@property (weak, nonatomic) id<IESLiveGuestBattleRouter> battleRouter;
@property (weak, nonatomic) id<IESLiveSocialInteractiveRouter> interactiveRouter;
@property (weak, nonatomic) id<IESLiveInteractGameAvatarRouter> gameAvatarRouter;
@property (retain, nonatomic) IESLiveInteractCompetitionGameGuestInfoViewModel *competitionGameViewModel;
@property (weak, nonatomic) IESLiveInteractVoiceWaveView *voiceWaveView;
@property (weak, nonatomic) id<IESLiveAudioSeatUpdateAction> updateAction;
@property (weak, nonatomic) id<IESLiveInteractVoiceWaveRouter> voiceWaveRouter;
@property (nonatomic) BOOL isPreStream;
@property (nonatomic) BOOL isFullScreenPreStreamView;
@property (nonatomic) BOOL isEnlarge;
@property (nonatomic) BOOL isSquareLayout;
@property (nonatomic) int uilayout;
@property (nonatomic) long long subUILayout;
@property (nonatomic) BOOL seatLocked;
@property (nonatomic) BOOL isLayoutConfig;
@property (copy, nonatomic) id /* block */ onFanticketInfoViewClicked;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (copy, nonatomic) id /* block */ firstLoadAnchorAvatarBlock;
@property (nonatomic) BOOL audioThemeEnabled;
@property (nonatomic) long long avatarWidth;
@property (nonatomic) float avatarAnimationGenderRatio;
@property (nonatomic) long long emojiWidth;
@property (nonatomic) float seatElementRatio;
@property (nonatomic) BOOL isPcStreaming;
@property (copy, nonatomic) id /* block */ onGuestInfoViewTapAcceptLink;
@property (nonatomic) BOOL isUserOnline;
@property (copy, nonatomic) id /* block */ onUserViewClicked;
@property (nonatomic) BOOL needShowIncomePrompt;
@property (nonatomic) BOOL disableSilence;
@property (nonatomic) BOOL disableEmoji;
@property (retain, nonatomic) IESLiveInteractSeatElementLoader *elementLoader;
@property (retain, nonatomic) IESLiveMultiAudioAvatarViewConfig *avatarConfig;
@property (readonly, nonatomic) double userNameTopOffset;
@property (readonly, nonatomic) UIFont *emptySeatLabelFont;

- (void)didSetAttachingDIContext;
- (BOOL)isInTeamFight;
- (void)updateWithIndex:(long long)a0;
- (BOOL)isInCompetitionGame;
- (BOOL)isTeamFightFlexible;
- (void)updateWithGuest:(id)a0;
- (void)p_disposable;
- (void)updateFanticketAreaHidden:(BOOL)a0;
- (BOOL)isMultiAvatarMode;
- (void)onGuestBattleFinish;
- (void)prepareTeamFight;
- (void)startTeamFight;
- (void)punishTeamFight;
- (void)finishTeamFight;
- (void)interactionPlaymodeDidStart:(int)a0;
- (void)interactionPlaymodeDidEnd:(int)a0;
- (void)paidLinkmicOpenStatusChanged:(BOOL)a0;
- (BOOL)isAvatarGameOpening;
- (BOOL)enableUpdateBattlerRole;
- (void)updateAudioStageSpeakingAnimation:(BOOL)a0;
- (void)updateAvatarResourceIfNeed:(BOOL)a0;
- (void)updateAvatarWidth;
- (void)updateLinkButtonStateInPrelinkMode;
- (void)initEmptyAvatarModel;
- (void)initGuestAvatarModel;
- (void)initSeatNameModel;
- (void)initCompetitionGameModel;
- (void)destroyCurrentGoldenMicInfo;
- (void)stopPaidLinkmicCountDown;
- (void)p_updateAdminAndSilenceStatus;
- (void)updatePaidLinkmicProgress;
- (void)destroyUserInfo;
- (void)updateEnlargeStatus;
- (void)resetEnlargeType;
- (void)setupElementLoaderIfNeeded;
- (void)updateWithEmptyGuest;
- (void)updateWitCurrentGuest;
- (void)updateUserNamelabel;
- (void)refreshVoiceWaveHiddenFor2dAvatarOrVideo;
- (void)updateGuestBattleViewIfNeeded;
- (void)addObserverWithGuest:(id)a0;
- (void)updatePCStreamingStatus;
- (void)resetCheckerForEmptyGuest;
- (void)setOrderSingEnlargeHeadWidgetHidden:(BOOL)a0;
- (void)updateEmptyUserTextIfNeeded;
- (void)clearAvatar;
- (id)registerVoiceWaveWithModel:(id)a0;
- (id)observeUserTagInfoWithModel:(id)a0;
- (id)observeLinkTypeWithModel:(id)a0;
- (void)updateEmptyAvatarWithIndex;
- (void)updateEnlargeTypeWithType:(long long)a0;
- (BOOL)isInFixTeamFight;
- (BOOL)isLeft1V8;
- (double)scaleFont:(double)a0;
- (void)updateIndexLabelText:(id)a0 fontSize:(long long)a1;
- (void)updateJoinIconWithURLs:(id)a0 isLocal:(BOOL)a1;
- (struct CGSize { double x0; double x1; })anchorAvatarSize;
- (struct CGSize { double x0; double x1; })audienceAvatarSize;
- (void)updateLinkButtonUI;
- (id)strForNormal;
- (void)updateEmptyUserTextWithText:(id)a0;
- (id)nameStrInTeamFight;
- (id)strForCompetitionGame;
- (void)updateEnlargeAvatarEmojiContainerRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (id)anchorNameFont;
- (id)audienceNameFont;
- (double)anchorUserLabelWidth;
- (double)audienceUserLabelWidth;
- (long long)cutLength;
- (void)startPaidLinkmicCountDownWithGuest:(id)a0;
- (double)paidLinkmicDuration;
- (void)showPaidLinkmicCountDownIfNeededWithGuest:(id)a0;
- (void)replacePaidLinkmicCoundownAfter:(double)a0 animated:(BOOL)a1;
- (void)updateAvatarHiddenWithModel:(id)a0;
- (void)showSeatName:(id)a0;
- (void)resetSeatNameTagBgColor;
- (BOOL)isCompetitionGamePerformer;
- (void)updateTeamSignColor;
- (long long)teamSignWithPosition:(long long)a0;
- (void)updateTeamSignColorWithSign:(long long)a0;
- (void)updateEmptyAvatarWithTeamFightStatus:(BOOL)a0;
- (void)onGuestBattleStart;
- (void)onGuestBattleSettle;
- (BOOL)isUserOffLine;
- (void)updateAcceptTitle;
- (void)updateJoinIconWithURLs:(id)a0;
- (void)updateAnchorPause:(BOOL)a0;
- (void)updateSeatInfo:(id)a0;
- (void)preStreamOnGuestBattleStart;
- (void)updateTeamFightViewIfNeeded;
- (BOOL)isLinkmicGuest;
- (void).cxx_destruct;
- (BOOL)isAnchor;
- (void)dealloc;
- (void)forwardInvocation:(id)a0;
- (void)updateAccessibilityLabel;

@end
