@class UIView, IESLivePKGuestMuteStateManager, NSString, IESLiveCountTimer, IESLiveSmallAudienceRequestView, IESLivePKChatGuestListView, IESLivePKGuestOperatePanelView, IESLivePKGuestTrackerContext, IESLiveInteractiveMediaService, IESLivePKEventTransparentView;
@protocol IESLivePushStreamLifeCycle, IESLivePKGuestAudienceBuilderService, IESLiveRealStreamingProvider;

@interface IESLivePKGuestAudienceInstance : NSObject <IESLiveInteractiveMediaServiceDelegate, IESLivePKChatGuestListViewDelegate, IESLivePKGuestOperatePanelViewModelDelegate, IESLiveInteractiveUserServiceDelegate, IESLiveSocialInteractAction, IESLiveSmallAudienceRequestViewDelegate, IESLiveMediaPermissionManagerAction, IESLivePKGuestAction>

@property (retain, nonatomic) id<IESLivePushStreamLifeCycle> pushStreamLifeCycle;
@property (retain, nonatomic) id<IESLiveRealStreamingProvider> streamProvider;
@property (retain, nonatomic) IESLivePKGuestMuteStateManager *muteStateManager;
@property (retain, nonatomic) IESLivePKChatGuestListView *pkGuestListView;
@property (retain, nonatomic) IESLivePKEventTransparentView *anchorEmojiContainer;
@property (weak, nonatomic) IESLivePKGuestOperatePanelView *panelView;
@property (weak, nonatomic) UIView *beautyView;
@property (retain, nonatomic) id<IESLivePKGuestAudienceBuilderService> interactStore;
@property (retain, nonatomic) IESLivePKGuestTrackerContext *guestTrackerContext;
@property (copy, nonatomic) id /* block */ beautyStartBlock;
@property (copy, nonatomic) id /* block */ beautyCancelBlock;
@property (retain, nonatomic) IESLiveCountTimer *checkLinkerStatusTmer;
@property (nonatomic) BOOL hasMutedOnJoinChannel;
@property (nonatomic) BOOL onInteract;
@property (nonatomic) BOOL inBeautyProcess;
@property (retain, nonatomic) IESLiveInteractiveMediaService *mediaService;
@property (retain, nonatomic) IESLiveSmallAudienceRequestView *smallAudienceRequestView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)roomModel;
- (void)didSetAttachingDIContext;
- (id)userService;
- (id)initWithDiContext:(id)a0;
- (void)muteStateDidChange:(BOOL)a0 reason:(id)a1;
- (void)overturnCamera;
- (void)turnOnCameraByOther:(BOOL)a0;
- (void)turnOnCameraBySelf:(BOOL)a0;
- (BOOL)isCameraOpen;
- (void)openBeautySettingPanelBeforeVideoInteractionWithStartBlock:(id /* block */)a0 cancelBlock:(id /* block */)a1;
- (void)switchSceneFromBigPartyWithMediaService:(id)a0 cameraPreview:(id)a1;
- (id)emojiContainerForUserID:(id)a0 isInteractiveEmoji:(BOOL)a1;
- (void)onBusinessPrepare;
- (void)interactiveMediaServiceDidStart:(id)a0;
- (void)interactiveMediaServiceWillEnd:(id)a0;
- (void)interactiveMediaService:(id)a0 receivesError:(id)a1;
- (void)interactiveMediaService:(id)a0 firstRemoteVideoWithLinkmicUid:(id)a1;
- (void)interactiveMediaService:(id)a0 didUpdatedSessionsLocalLayout:(id)a1;
- (void)interactiveMediaService:(id)a0 firstFrameRenderCallback:(id)a1;
- (void)interactiveMediaService:(id)a0 didOfflineOfUid:(id)a1 sessions:(id)a2 reason:(unsigned long long)a3;
- (void)interactiveMediaService:(id)a0 didVideoMuted:(BOOL)a1 byUid:(id)a2;
- (void)interactiveMediaServiceAppResignActive;
- (void)interactiveMediaServiceAppDidActive;
- (void)muteSelf:(BOOL)a0;
- (void)stopInteractiveMode;
- (BOOL)isAudioModeOn;
- (void)didSwitchConnectModeOn;
- (void)switchConnectMode;
- (void)onGuestMute:(BOOL)a0;
- (void)loadMediaService;
- (void)onPKCloseWithGuest;
- (void)showGuestOperatePanel:(id)a0;
- (void)didUpdateOppositeRoomSilence;
- (void)updateSessionsLocalLayout:(id)a0;
- (BOOL)handleCrossRoomForwardStreamForLinkmicID:(id)a0;
- (void)clearGuestView;
- (void)onInteractionEnded;
- (void)didClickEmptyView:(long long)a0;
- (void)didClickItemView:(id)a0;
- (void)didOwnPreViewAddToList;
- (void)updateLayoutWithAppData:(id)a0;
- (void)showPanelWithConfig:(id)a0 requestPage:(id)a1;
- (void)openBeautySettingPanelDuringVideoInteraction:(BOOL)a0;
- (BOOL)muteStateForUser:(id)a0;
- (BOOL)isUserConnected:(id)a0;
- (void)muteOthers:(id)a0 mute:(BOOL)a1;
- (void)stopConnectedWithUserID:(id)a0;
- (void)p_stopCheckLinkerStatus;
- (void)mediaCaptureInterruptedWithStrategy:(unsigned long long)a0;
- (void)mediaCaptureResumeedWithStrategy:(unsigned long long)a0;
- (void)didUpdateServerLinkTypeSucceed:(int)a0 actively:(BOOL)a1;
- (void)setupSmallWindowViewWithAudio:(BOOL)a0 cameraPreview:(id)a1;
- (unsigned long long)currentSceneForGuest;
- (void)renderToolBarApplyStatus:(unsigned long long)a0;
- (id)currentLayoutForGuest;
- (void)p_removeGuestListView;
- (void)trackGuestConnectSuccess;
- (void)p_startCheckLinkerStatus;
- (BOOL)enableAudienceMediaCaptureOpt;
- (void)p_muteOnJoinChannelIfNeeded;
- (void)didConnectSuccess;
- (void)p_trackGuestConnectionOver:(BOOL)a0;
- (void)stopInteractiveConnection;
- (void)setupGuestListView:(BOOL)a0;
- (void)showGuestBeautyPopupViewDuringVideoInteraction;
- (void)setupGuestListView:(BOOL)a0 height:(double)a1;
- (void)showControlPanelForSelf;
- (void)showGuestBeautyPopupViewBeforeVideoInteraction;
- (void)showGuestBeautyPopupViewDuringVideo:(BOOL)a0;
- (void)showGuestBeautyPopupViewWithType:(unsigned long long)a0 startBlock:(id /* block */)a1 cancelBlock:(id /* block */)a2;
- (void)clearSmallRequestView;
- (void)p_startCheckLinkerStatusCountDownTimerWithTimeInterval:(double)a0;
- (void)startRTCInteract;
- (void)moveInteractiveConnection;
- (void)moveSmallRequestView;
- (void)updateGuestListViewPosition;
- (void)stopAndQuit;
- (void)showToast:(id)a0;
- (long long)currentCameraPosition;
- (void).cxx_destruct;
- (void)stopConnection;
- (void)dealloc;

@end
