@class NSMutableDictionary, UIImageView, IESLiveChorusMixStreamInfo, IESLiveKtvProfitJoinChorusResponse_ResponseData, NSDictionary, IESLiveGCDTimer, IESLiveKtvSongStruct, UILabel, NSMutableArray, NSString, IESLivePartyKTVChorusApi, IESLiveKTVComponentContext, HTSEventContext, NSTimer, HTSLiveKtvChorusPermissionMessage, NSArray, IESLiveKTVCommonStore;
@protocol IESLiveCompoundSubscription, IESLiveKTVAudioScoreInfo, IESLiveInteractPushStreaming, IESLiveInteractionLinkerService;

@interface IESLivePartyKTVChorusComponent : IESLiveInteractComponentBase <IESLiveDataSyncDelegate, IESLiveSocialInteractAction, IESLiveKTVActions, IESLivePartyKTVChorusRouter, HTSLiveMessageSubscriber, IESLiveInteractionLinkerServiceAction, IESLiveInteractionRTSMessageDispatcher>

@property (retain, nonatomic) HTSEventContext *trackContext;
@property (weak, nonatomic) IESLiveKTVComponentContext *ktvContext;
@property (weak, nonatomic) IESLiveKTVCommonStore *commonStore;
@property (retain, nonatomic) IESLivePartyKTVChorusApi *api;
@property (retain, nonatomic) NSString *currentLoginUserId;
@property (retain, nonatomic) IESLiveKtvSongStruct *currentChorusMusicModel;
@property (nonatomic) long long chorusId;
@property (nonatomic) long long lastReportChorusId;
@property (copy, nonatomic) NSString *subRtcExtInfo;
@property (copy, nonatomic) NSString *rtcExtInfo;
@property (copy, nonatomic) NSString *chorusConfig;
@property (copy, nonatomic) NSDictionary *chorusBussinessConfig;
@property (copy, nonatomic) NSDictionary *spatialAudioConfig;
@property (nonatomic) BOOL spatialLinkmicIdFromWRDS;
@property (nonatomic) long long originalMixType;
@property (copy, nonatomic) NSString *listenerAllignedUID;
@property (copy, nonatomic) NSString *CDNAllignedUID;
@property (nonatomic) BOOL lastVisibleState;
@property (nonatomic) BOOL lastPublishState;
@property (retain, nonatomic) NSDictionary *publishOptimizeDict;
@property (retain, nonatomic) NSTimer *delayPublishTimer;
@property (nonatomic) BOOL continuePushOnPause;
@property (retain, nonatomic) NSTimer *leaderSyncTimer;
@property (nonatomic) double bgmStreamSyncInterval;
@property (nonatomic) double updateChorusDelay;
@property (retain, nonatomic) NSTimer *receiveSyncInfoTimer;
@property (retain, nonatomic) IESLiveKtvProfitJoinChorusResponse_ResponseData *joinResponse;
@property (retain, nonatomic) HTSLiveKtvChorusPermissionMessage *permissionMessage;
@property (nonatomic) unsigned long long chorusState;
@property (nonatomic) long long segment;
@property (copy, nonatomic) id /* block */ joinNextSongBlock;
@property (nonatomic) BOOL canSubscribreAllUser;
@property (nonatomic) long long rttDetectCount;
@property (nonatomic) long long rttThreshold;
@property (nonatomic) long long rttOverThreSholdCount;
@property (nonatomic) long long rttDetectMinPeople;
@property (nonatomic) long long chorusUserCount;
@property (nonatomic) BOOL enableLeaderDetect;
@property (nonatomic) double playerSeekThreshold;
@property (nonatomic) double playerSeekIntervalThreshold;
@property (nonatomic) double playerSeekThresholdForCDN;
@property (nonatomic) double playerSeekIntervalThresholdForCDN;
@property (nonatomic) double playerSeekBackWardThresholdForCDN;
@property (nonatomic) double playerLastSeekTime;
@property (nonatomic) double playerSyncOffset;
@property (nonatomic) long long deviceLoopDelay;
@property (nonatomic) long long localRtt;
@property (nonatomic) int upLinkBandWidth;
@property (nonatomic) double playerPlayTime;
@property (nonatomic) double playerPlayTimeLastUpdateTime;
@property (nonatomic) double playerMusicDuration;
@property (nonatomic) double playerFirstSeekTime;
@property (nonatomic) double playerMusicStart;
@property (nonatomic) unsigned long long currentLoginUserRoleType;
@property (nonatomic) unsigned long long prevLoginUserRoleType;
@property (weak, nonatomic) id<IESLiveInteractPushStreaming> interactStreamer;
@property (nonatomic) int sentancesPerSegment;
@property (nonatomic) double segmentTotalMidiScore;
@property (nonatomic) int segmentActualLines;
@property (nonatomic) double midiScoreFactor;
@property (retain, nonatomic) id<IESLiveKTVAudioScoreInfo> lastScoreResult;
@property (nonatomic) float lastMidiAverageScore;
@property (nonatomic) BOOL isAssignedLeader;
@property (retain, nonatomic) IESLiveKtvSongStruct *assignedLeaderPlayingMusic;
@property (nonatomic) double chorusStartTime;
@property (nonatomic) int orderPermissionType;
@property (nonatomic) int joinPermissionType;
@property (nonatomic) int leadChorusSwitch;
@property (retain, nonatomic) IESLiveChorusMixStreamInfo *mixInfo;
@property (nonatomic) BOOL isAutoJoinChorus;
@property (retain, nonatomic) NSMutableDictionary *startChorusTimeDict;
@property (nonatomic) BOOL joinChorusOptimize;
@property (copy, nonatomic) NSDictionary *joinChorusOptimizeDict;
@property (copy, nonatomic) NSDictionary *lastSyncInfo;
@property (nonatomic) BOOL enableLeaveChorusOpt;
@property (nonatomic) BOOL enableQuitRTCRoomOpt;
@property (nonatomic) BOOL pausePlayerBeforeExit;
@property (nonatomic) BOOL enablePlayerEndOpt;
@property (retain, nonatomic) NSTimer *noSongLeaveTimer;
@property (retain, nonatomic) IESLiveGCDTimer *howlDetectionTimer;
@property (copy, nonatomic) NSDictionary *howlDetectionConfig;
@property (nonatomic) BOOL isHowling;
@property (retain, nonatomic) id<IESLiveCompoundSubscription> CDNDisposable;
@property (copy, nonatomic) NSArray *linkedUsersArray;
@property (copy, nonatomic) NSString *orderUserLinkID;
@property (nonatomic) BOOL enableSeekBackwardInCDN;
@property (nonatomic) BOOL checkMixTypeWhenOrderListChange;
@property (weak, nonatomic) id<IESLiveInteractionLinkerService> linkerService;
@property (nonatomic) BOOL needResumeMute;
@property (retain, nonatomic) NSString *preSongSessionID;
@property (retain, nonatomic) NSString *preSongSessionIDForExit;
@property (retain, nonatomic) UIImageView *imageView;
@property (nonatomic) double rtsSyncThreshold;
@property (nonatomic) double lastReceiveSyncInfoTime;
@property (retain, nonatomic) UILabel *debugRoleLabel;
@property (retain, nonatomic) UILabel *debugStreamLabel;
@property (retain, nonatomic) UILabel *debugChoiceLabel;
@property (retain, nonatomic) NSMutableArray *debugLabels;
@property (retain, nonatomic) NSMutableArray *lastNeedPushUid;
@property (retain, nonatomic) IESLiveGCDTimer *debugTimer;
@property (nonatomic) BOOL playerToSilenceFix;
@property (nonatomic) BOOL leaderOnlyPushAccompany;
@property (nonatomic) int leadChorusMode;
@property (nonatomic) float bigEventVoiceVolume;
@property (nonatomic) BOOL bigEventVoiceVolumeEnable;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)componentMount;
- (void)componentUnmount;
- (void)subscribedSyncDataWithValue:(id)a0 version:(long long)a1;
- (void)subscribedSyncDataUpdatedWithValue:(id)a0 oldVersion:(long long)a1 newVersion:(long long)a2;
- (void)didSetAttachingDIContext;
- (void)startNetworkDetection;
- (void)didJoinChannelWithLayout:(id)a0;
- (void)didLeaveChannelWithLayout:(id)a0;
- (void)enableChorusSpatialAudio:(long long)a0 spatialAudioDistanceParam:(int)a1;
- (void)disableChorusSpatialAudio;
- (void)updateSingerList:(id)a0;
- (void)handleSyncData:(id)a0;
- (void)linkmicLinker:(id)a0 onAudioDeviceWarning:(id)a1 deviceType:(long long)a2 deviceWarning:(long long)a3;
- (void)didReceiveRTSMessage:(id)a0 fromUID:(id)a1 isBroadcastMessage:(BOOL)a2;
- (void)interactionLinkerService:(id)a0 onMixEventStartSuccessWithMixType:(long long)a1;
- (void)interactionLinkerServiceSilentInteractDidStart:(id)a0;
- (void)interactionLinkerServiceInteractDidStart:(id)a0;
- (void)interactionLinkerService:(id)a0 onStreamSyncInfoReceived:(id)a1 streamType:(long long)a2 data:(id)a3;
- (void)interactionLinkerService:(id)a0 onNetworkDetectionResult:(unsigned long long)a1 quality:(unsigned long long)a2 rtt:(int)a3 lostRate:(double)a4 bitrate:(int)a5 jitter:(int)a6;
- (void)interactionLinkerService:(id)a0 onNetworkQuality:(id)a1 remoteQualities:(id)a2;
- (void)interactionLinkerService:(id)a0 onDeviceLoopDelayReceived:(long long)a1;
- (void)willStartPlayMusicWithMusicID:(id)a0 afterTime:(long long)a1;
- (void)willStopPlayMusicWithMusicID:(id)a0;
- (void)didKTVIMOrderListChanged;
- (void)didUpdateKTVStageState:(unsigned long long)a0;
- (BOOL)isCurrentLoginUserPlayer;
- (BOOL)isCurrentLoginUserLeader;
- (BOOL)isChorusResidentialGuest;
- (void)joinPartyKTVChorusDownloadProgress:(id /* block */)a0 completion:(id /* block */)a1;
- (void)leavePartyKTVChorusWithLeaveType:(unsigned long long)a0 source:(id)a1;
- (void)leavePartyKTVChorusWithLeaveType:(unsigned long long)a0 completion:(id /* block */)a1 source:(id)a2;
- (BOOL)isCurrentLoginUserJoined;
- (BOOL)isCurrentLoginUserJoinedChannel;
- (void)anchorSwitchMixTypeIfNeeded:(id)a0;
- (void)openPartyKTVSettingPage;
- (id)trackDictionayForPartyKTV;
- (void)updateVoiceWithValue:(float)a0;
- (id)remotePlayingMusic;
- (void)updateCurrentLoginUserRoleType:(unsigned long long)a0 source:(id)a1;
- (void)handleCurrentLoginUserRoleTypeChangedFrom:(unsigned long long)a0 to:(unsigned long long)a1;
- (void)handleCurrentLoginUserRoleTypeChangedFromNoneTo:(unsigned long long)a0;
- (void)handleCurrentLoginUserRoleTypeChangedFromLeaderTo:(unsigned long long)a0;
- (void)handleCurrentLoginUserRoleTypeChangedFromPlayerTo:(unsigned long long)a0;
- (void)handleCurrentLoginUserRoleTypeChangedFromListenerTo:(unsigned long long)a0;
- (void)didEnterPartyKTV;
- (void)initDebugView;
- (void)enablePartyKTVFeature:(BOOL)a0;
- (void)anchorResetMixTypeIfNeeded;
- (void)closeLeaderSyncTimer;
- (void)closeReceiveSyncInfoTimer;
- (void)closeNoSongLeaveTimer;
- (void)didExitPartyKTV;
- (id)livePartyKTVChorusRoleDesc:(unsigned long long)a0;
- (void)leaderSendStreamSyncInfoWithPlayTime:(id)a0 playState:(id)a1;
- (void)calculateAndReportChorusUserMidiInfoWithCurrentScoreForCDNUser:(id)a0;
- (void)calculateAndReportChorusUserMidiInfoWithCurrentScore:(id)a0 lastScore:(id)a1;
- (void)handleCDNPlayingTime:(double)a0;
- (void)playerPauseMusic;
- (void)playerResumeMusic;
- (void)playerPlayAndPauseMusicWithMusic:(id)a0;
- (void)handleSyncInfo:(id)a0;
- (void)playerMusicSeekToTime:(double)a0 localNtp:(double)a1 currentProgress:(double)a2 progressDiff:(double)a3 remoteNTP:(double)a4 remoteProgress:(double)a5;
- (void)successJoinChorusToTrack;
- (void)onNetworkQuality:(int)a0 txQuality:(unsigned long long)a1;
- (void)trackClickedSettingButton;
- (void)trackDidEnterPartyKTV;
- (void)fetchPartyKTVSettingsWithCompletion:(id /* block */)a0;
- (void)trackDidExitPartyKTV;
- (void)anchorStartCDNIfNeeded;
- (void)p_handleHowlDetection;
- (BOOL)p_isEnableHowlDetection;
- (void)updateSelfVisibleState:(BOOL)a0 source:(id)a1;
- (void)p_resetHowlDetection;
- (long long)p_getHowlDetectionStopStreamTime;
- (void)trackChorusExitSuccess;
- (void)trackChorusJoinSuccess;
- (void)cleanChorusInfo;
- (void)setPartyKTVLeaderSingerLinkmicIDWithUID:(id)a0;
- (void)orderListChangeWithNoSong;
- (void)orderListChangeWithMySong:(id)a0;
- (void)orderListChangeWithNotMySong:(id)a0;
- (BOOL)isCurrentLoginUserLocalSinger;
- (void)leavePartyKTVChorusWithLeaveType:(unsigned long long)a0 chorusId:(id)a1 source:(id)a2;
- (void)leaveChorusSuccessWithSource:(id)a0;
- (void)joinPartyKTVChorusWithErrorCompletion:(id /* block */)a0 musicModel:(id)a1 source:(id)a2;
- (BOOL)isCurrentLoginUserMicSinger;
- (void)updateAssignedLeaderPlayingMusicIfNeededWithSource:(id)a0 needUpdateRole:(BOOL)a1;
- (void)assignedLeaderAutoJoinChorusIfNeededWithState:(unsigned long long)a0;
- (BOOL)enableLocalNetworkDetect;
- (id)choiceStr;
- (void)joinChannelSuccessWithSource:(id)a0;
- (void)anchorStartSpatialAudioIfNeeded;
- (void)checkBlockTypeWithError:(id)a0;
- (void)joinPartyKTVChorusWithResponse:(id)a0 musicModel:(id)a1;
- (unsigned long long)livePartyKTVChorusRoleFromResponseRole:(int)a0 isMySong:(BOOL)a1;
- (void)leavePartyKTVChorusWithLeaveType:(unsigned long long)a0 chorusId:(id)a1 completion:(id /* block */)a2 source:(id)a3;
- (BOOL)isFallBackUser;
- (void)anchorUpdateChoursCNDBaseUIDIfNeeded;
- (void)setPartyKTVChorusRoleListenerIfNeeded;
- (id)roleTypeStr;
- (void)handleCurrentLoginUserRoleTypeChangedFromSilentViceSingerTo:(unsigned long long)a0;
- (void)handleCurrentLoginUserRoleTypeChangedFromCDNTo:(unsigned long long)a0;
- (void)startPartyKTVChorus;
- (void)startPartyKTVChorusAsRole:(unsigned long long)a0;
- (void)stopPartyKTVChorusAsRole:(unsigned long long)a0;
- (void)playerStopMusic;
- (void)updateVoiceVolumeIfNeeded;
- (void)updateVolumeWithSelfVisibleState:(BOOL)a0 source:(id)a1;
- (void)switchServerMixType;
- (void)resetMixType;
- (void)setPartyKTVChorusInfo:(id)a0;
- (void)setPartyKTVChorusRole:(unsigned long long)a0;
- (void)addLeaderSyncTimer;
- (unsigned long long)liveLinkPartyKTVChorusRoleFromRole:(unsigned long long)a0;
- (void)stopPartyKtvChorus;
- (id)permissionTypeStrWithPermissionType:(int)a0;
- (void)addObserverForCDNPlayer;
- (void)addReceiveSyncInfoTimer;
- (void)startPlayLocalMusicModel:(id)a0 createPlayerCompletion:(id /* block */)a1;
- (void)resetPlayerPlayTimes;
- (void)segmentMidiScoreDidUpdateWithSegment:(long long)a0 segmentAverage:(double)a1 songAverage:(double)a2 curSentenceIndex:(int)a3;
- (id)orderPermissionTypeStr;
- (id)joinPermissionTypeStr;
- (BOOL)isLeadChorusSwitchEnable;
- (id)getDebugLabel;
- (id)getMixTypeStr;
- (void)onStreamSyncInfoReceived:(id)a0 streamType:(long long)a1 data:(id)a2;
- (void)stopPartyKTVChorusWithSource:(id)a0;
- (BOOL)isCurrentLoginUserNoSilenceSinger;
- (void)stopNetworkDetection;
- (void).cxx_destruct;
- (BOOL)isAnchor;
- (void)messageReceived:(id)a0;
- (void)addObservers;
- (void)resetInfo;

@end
