@class UIView, NSString, BDXContext, LLCubeNativeModuleContext, LLCubeMonitor, NSMutableDictionary, LLCubeModel, NSDictionary, LynxView, NSNumber, BDXLynxKitParams;
@protocol AnnieXContainerBaseProtocol, AnnieXCardModelProtocol, BDXLynxViewProtocol, BDXMonitorProtocol, LLCubeViewDelegate;

@interface LLCubeView : UIView <BDXKitViewLifecycleProtocol, LLCubeMonitorDataSource, BDXContainerLifecycleProtocol, AnnieXDataProviderProtocol, LLCubeViewDataSource>

@property (retain, nonatomic) UIView<BDXLynxViewProtocol> *lynxContainer;
@property (retain, nonatomic) UIView<AnnieXContainerBaseProtocol> *neoLynxContainer;
@property (retain, nonatomic) id<AnnieXCardModelProtocol> cardModel;
@property (retain, nonatomic) NSNumber *geckoID;
@property (retain, nonatomic) BDXLynxKitParams *kitParams;
@property (retain, nonatomic) BDXContext *context;
@property (retain, nonatomic) id<BDXMonitorProtocol> monitor;
@property (nonatomic) BOOL isLoading;
@property (nonatomic) BOOL isLoadFailed;
@property (nonatomic) BOOL isLoadSuccess;
@property (nonatomic) double initTimeStamp;
@property (retain, nonatomic) NSMutableDictionary *hasLoadedDict;
@property (retain, nonatomic) LLCubeNativeModuleContext *nativeModuleContext;
@property (readonly, nonatomic) NSString *loadStatus;
@property (nonatomic) long long dataSize;
@property (retain, nonatomic) LLCubeMonitor *cubeMonitor;
@property (copy, nonatomic) NSString *bid;
@property (nonatomic) BOOL didUpdateData;
@property (nonatomic) BOOL forceUpdateInThisSession;
@property (nonatomic) BOOL disableGecko;
@property (nonatomic) BOOL enableMemoryCache;
@property (retain, nonatomic) LLCubeModel *waitCubeModel;
@property (retain, nonatomic) NSDictionary *waitExtraParams;
@property (nonatomic) BOOL enableUIOperationQueue;
@property (weak, nonatomic) id<LLCubeViewDelegate> delegate;
@property (readonly, nonatomic) LynxView *lynxView;
@property (readonly, nonatomic) NSString *containerID;
@property (retain, nonatomic) LLCubeModel *cubeModel;
@property (retain, nonatomic) NSDictionary *extraParams;
@property (copy, nonatomic) NSString *uniqueTag;
@property (nonatomic) BOOL isPreloadView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (unsigned long long)serviceScope;
+ (id)serviceBizID;
+ (id)cacheKeyWithLynxUrl:(id)a0;
+ (unsigned long long)serviceType;

- (void)viewDidStartLoading:(id)a0;
- (void)viewWillStartLoading:(id)a0;
- (void)viewDidFirstScreen:(id)a0;
- (void)viewDidUpdate:(id)a0;
- (void)viewDidPageUpdate:(id)a0;
- (void)container:(id)a0 didFinishLoadWithURL:(id)a1;
- (void)container:(id)a0 didLoadFailedWithUrl:(id)a1 error:(id)a2;
- (void)container:(id)a0 didChangeIntrinsicContentSize:(struct CGSize { double x0; double x1; })a1;
- (void)containerWillStartLoading:(id)a0;
- (void)containerDidStartLoading:(id)a0;
- (void)container:(id)a0 didStartFetchResourceWithURL:(id)a1;
- (void)container:(id)a0 didFetchedResource:(id)a1 error:(id)a2;
- (void)containerDidFirstScreen:(id)a0;
- (void)containerDidUpdate:(id)a0;
- (void)container:(id)a0 didRecieveError:(id)a1;
- (void)containerDidPageUpdate:(id)a0;
- (void)container:(id)a0 onSetupLynxInfo:(id)a1 bulletInfo:(id)a2;
- (void)container:(id)a0 onUpdateLynxInfo:(id)a1 bulletInfo:(id)a2;
- (void)sendEvent:(id)a0 params:(id)a1;
- (void)view:(id)a0 didFetchedResource:(id)a1 error:(id)a2;
- (void)view:(id)a0 didFinishLoadWithURL:(id)a1;
- (void)view:(id)a0 didLoadFailedWithUrl:(id)a1 error:(id)a2;
- (void)view:(id)a0 didChangeIntrinsicContentSize:(struct CGSize { double x0; double x1; })a1;
- (void)view:(id)a0 didStartFetchResourceWithURL:(id)a1;
- (void)view:(id)a0 didRecieveError:(id)a1;
- (void)view:(id)a0 onSetUp:(id)a1;
- (void)view:(id)a0 onUpdate:(id)a1;
- (void)registerBridgeHandle:(id /* block */)a0 forMethod:(id)a1;
- (Class)schemaClass;
- (void)provideDefaultCardDataWithCardModel:(id)a0;
- (void)provideInstanceDataWitCardModel:(id)a0 schemaClass:(Class)a1;
- (double)getDurationForStartTime:(id)a0 endTime:(id)a1;
- (id)containerInitTimeStamp;
- (id)lynxGlobalProps;
- (id)lynxInitialData;
- (void)lynxViewWillShow;
- (void)lynxViewWillHide;
- (void)trackEvent:(id)a0 metric:(id)a1 category:(id)a2;
- (BOOL)isPredecodeWithCubeMonitor:(id)a0;
- (BOOL)isCubeBaseOnAnniexCard;
- (void)triggerEventBus:(id)a0 withParams:(id)a1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 cubeModel:(id)a1 uniqueTag:(id)a2 extraParams:(id)a3 delegate:(id)a4;
- (void)bindCubeModel:(id)a0;
- (void)createCubeMonitor;
- (id)ditoLogCommonParams;
- (void)setupCubeConfig;
- (void)setupBizBeforeCreateLynxView;
- (void)setupLynxView:(id *)a0;
- (void)trackTimeLine;
- (void)appendParametersToCubeModel:(id)a0;
- (void)configMonitor;
- (void)_setupLynxViewWithUrl:(id)a0;
- (id)cubeSettings;
- (id)fetchInitialData;
- (void)configWithLynxViewBuilder:(id)a0;
- (id)generateParamWithContext:(id)a0 url:(id)a1;
- (id)customElements;
- (id)nativeModuleClasses;
- (long long)threadStrategyFromTemplateUrl:(id)a0;
- (BOOL)enableCubeParserUrlThreadStrategy;
- (long long)threadStrategyForBDX:(long long)a0;
- (BOOL)enableCustomLynxComponent;
- (id)defaultCubeUIElementsConfigs;
- (id)bizCustomUIElementsConfigs;
- (id)customLynxElementWithRegisterName:(id)a0 elementClass:(Class)a1;
- (BOOL)shouldUpdate:(id)a0 extraParams:(id)a1;
- (void)updateViewWithCubeModel:(id)a0 extraParams:(id)a1 needUpdateGlobalProps:(BOOL)a2;
- (void)updateViewWithCubeModel:(id)a0 extraParams:(id)a1 needUpdateGlobalProps:(BOOL)a2 needResetData:(BOOL)a3;
- (void)updateViewWithCubeModel:(id)a0 extraParams:(id)a1;
- (double)fontScaleForCubeWithModel:(id)a0;
- (void)invokeSchemaInterceptor:(BOOL)a0;
- (void)setupFetchResourceConfig;
- (id)createBDXRenderConfig;
- (id)findLastLynxUIIn:(id)a0 withResponseEvent:(id)a1;
- (void)sendCustomLynxEvent:(id)a0 lynxUI:(id)a1;
- (void)reloadViewWithCubeModel:(id)a0 extraParams:(id)a1;
- (void)resetViewWithCubeModel:(id)a0 extraParams:(id)a1;
- (void)updateViewWithCubeModel:(id)a0 extraParams:(id)a1 waitFinish:(BOOL)a2;
- (void)safeUpdateWithCubeModel:(id)a0 extraParams:(id)a1;
- (void)updateGlobalProsAndDataAtTheSameTimeWithCubeModel:(id)a0 extraParams:(id)a1;
- (void)forceUpdateViewWithCubeModel:(id)a0;
- (void)registerBDXLocalMethod:(id)a0;
- (double)calculatePreRenderHeight;
- (void)updateClipsToBounds:(BOOL)a0;
- (void)componentViewSendLynxCustomEvent:(id)a0 eventParams:(id)a1 viewID:(id)a2;
- (id)innerLynxView:(id)a0;
- (BOOL)isOnSaaSAPP;
- (void)initCubeBid;
- (void)resetLynxView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (id)initWithCoder:(id)a0;
- (void)dealloc;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)resetAnimation;
- (void)restartAnimation;

@end
