@class LLDitoAnchorPageScheduler, LLDitoLynxExtensionV2, LLDitoLogInfoManager, LLDitoComponentTrackExtension, LLDitoDataCacher, IESLLPOIDetailSkinConfig, NSDictionary, LLDitoPageView, UIViewController, NSMutableArray, UIView, LLDitoPerformanceChainRecorder, NSString, LLDitoPerformanceTaskManager, LLPageContext, LLDitoTempoExtension, LLDitoPageModel, LLDitoActionCenter, LLDitoNestedScrollExtension;
@protocol LLDitoMonitorProtocol, LLDitoLynxContainerBuilder, LLDitoStorageProtocol, LLDitoNetworkProtocol, LLDitoVirtualRefreshPageInterceptor, LLDitoPageContextPrivateDelegate, LLDitoTempoDataProviderProtocol, LLDitoExtensionContainerProtocol;

@interface LLDitoPageContext : NSObject

@property (nonatomic) BOOL reloadContainerOptimize;
@property (nonatomic) BOOL visibleComponentOptimize;
@property (nonatomic) BOOL scrollNodeAnimationOptimize;
@property (nonatomic) BOOL ditoDecorationEnable;
@property (nonatomic) BOOL fixingTradeHalfUIBugEnabled;
@property (nonatomic) BOOL ditoMoveFloatNodeEnable;
@property (nonatomic) BOOL forceShutDownSwitchLayoutEnable;
@property (nonatomic) BOOL nestedScrollDispatchEventOptimize;
@property (nonatomic) BOOL ditoPerformanceChainEnable;
@property (nonatomic) BOOL ditoNewFullContainerManager;
@property (nonatomic) BOOL nestedScrollV2Enable;
@property (nonatomic) BOOL viscousDragEnable;
@property (readonly, nonatomic) NSDictionary *aweDitoSettingsConfig;
@property (nonatomic) BOOL componentViewShowOptimize;
@property (readonly, nonatomic) NSDictionary *disasterImmediateRecoveryConfig;
@property (nonatomic) BOOL ditoRealHalfFixEnable;
@property (nonatomic) double FMPTimeThreshold;
@property (retain, nonatomic) id<LLDitoLynxContainerBuilder> lynxContainerBuilder;
@property (retain, nonatomic) LLDitoLynxExtensionV2 *p_lynxExtensionV2;
@property (nonatomic) double currentModalViewOffset;
@property (readonly, nonatomic) long long halfContainerState;
@property (copy, nonatomic) NSString *screenshot_enterFrom;
@property (retain, nonatomic) IESLLPOIDetailSkinConfig *skinConfig;
@property (weak, nonatomic) id<LLDitoVirtualRefreshPageInterceptor> virtualRefreshPageInterceptor;
@property (retain, nonatomic) LLDitoLogInfoManager *logManager;
@property (retain, nonatomic) LLDitoPerformanceTaskManager *performanceTaskManager;
@property (weak, nonatomic) UIView *p_stickyContainer;
@property (weak, nonatomic) LLDitoDataCacher *dataCacher;
@property (weak, nonatomic) id<LLDitoPageContextPrivateDelegate> privateDelegate;
@property (weak, nonatomic) id<LLDitoNetworkProtocol> networkImpl;
@property (weak, nonatomic) id<LLDitoMonitorProtocol> monitorImpl;
@property (weak, nonatomic) id<LLDitoStorageProtocol> storageImpl;
@property (readonly, nonatomic) LLDitoPerformanceChainRecorder *perfChainRecorder;
@property (weak, nonatomic) LLDitoNestedScrollExtension *private_nestedScrollExtension;
@property (readonly, nonatomic) BOOL private_nestedScrollV2Enable;
@property (readonly, nonatomic) BOOL private_viscousDragEnable;
@property (readonly, nonatomic) BOOL private_optimizeComponentViewShow;
@property (nonatomic) BOOL enableAutoPlay;
@property (weak, nonatomic) id<LLDitoTempoDataProviderProtocol> tempoDataProvider;
@property (retain, nonatomic) LLPageContext *context;
@property (weak, nonatomic) LLDitoDataCacher *dataCacher;
@property (copy, nonatomic) NSDictionary *loadMoreParams;
@property (nonatomic) BOOL hasMore;
@property (nonatomic) BOOL enableAutoPlay;
@property (nonatomic) long long ditoDisasterDegradeStrategy;
@property (nonatomic) BOOL needDisasterDegrade;
@property (copy, nonatomic) NSString *sessionID;
@property (weak, nonatomic) LLDitoTempoExtension *tempoExtension;
@property (weak, nonatomic) id<LLDitoTempoDataProviderProtocol> tempoDataProvider;
@property (weak, nonatomic) LLDitoComponentTrackExtension *trackExtension;
@property (weak, nonatomic) id<LLDitoNetworkProtocol> networkImpl;
@property (weak, nonatomic) id<LLDitoMonitorProtocol> monitorImpl;
@property (weak, nonatomic) id<LLDitoStorageProtocol> storageImpl;
@property (weak, nonatomic) id<LLDitoPageContextPrivateDelegate> privateDelegate;
@property (nonatomic) unsigned long long ditoHalfContainerType;
@property (nonatomic) double halfContainerInitialRatio;
@property (retain, nonatomic) LLDitoPerformanceChainRecorder *perfChainRecorder;
@property (copy, nonatomic) NSString *disasterRevoveryURL;
@property (retain, nonatomic) LLDitoAnchorPageScheduler *anchorPageScheduler;
@property (nonatomic) BOOL forceLightTheme;
@property (copy, nonatomic) NSString *bizCode;
@property (copy, nonatomic) NSString *screenshot_enterFrom;
@property (copy, nonatomic) NSString *DitoPageScene;
@property (weak, nonatomic) LLDitoPageModel *pageModel;
@property (retain, nonatomic) LLDitoActionCenter *actionCenter;
@property (copy, nonatomic) NSDictionary *routerParams;
@property (copy, nonatomic) NSDictionary *trackParams;
@property (weak, nonatomic) LLDitoPageView *pageView;
@property (weak, nonatomic) UIViewController *viewController;
@property (weak, nonatomic) id<LLDitoExtensionContainerProtocol> containerDelegate;
@property (copy, nonatomic) NSString *pageKeyFromFirstRequest;
@property (copy, nonatomic) NSString *dito_tt_log_id;
@property (retain, nonatomic) NSMutableArray *chunkSizeArr;
@property (nonatomic) BOOL firstScreenDidLoad;

- (void)clearCacheWithKey:(id)a0;
- (BOOL)transferToURLString:(id)a0;
- (void)transferToURLString:(id)a0 completion:(id /* block */)a1;
- (void)setWeakObject:(id)a0 forKey:(id)a1;
- (id)weakObjectForKey:(id)a0;
- (id)viewWithIdSelector:(id)a0;
- (void)lynxContainerView;
- (id)lynxManager;
- (void)networkWithURL:(id)a0 method:(unsigned long long)a1 params:(id)a2 completion:(id /* block */)a3;
- (void)lynxComponentView;
- (void)networkWithURL:(id)a0 params:(id)a1 completion:(id /* block */)a2;
- (void)postEvent:(id)a0 sender:(id)a1 extraParams:(id)a2 completion:(id /* block */)a3;
- (void)postEvent:(id)a0 sender:(id)a1 completion:(id /* block */)a2;
- (void)postEvent:(id)a0 withCompletion:(id /* block */)a1;
- (id)findEventFromNode:(id)a0 eventName:(id)a1;
- (id)containerViewByType:(id)a0;
- (void)reloadPageData;
- (id)logCommonParams;
- (void)innerLynxView:(id)a0;
- (id)nodeByTag:(id)a0;
- (void)setupTempoWithGlobalProps:(id)a0 extendData:(id)a1 configEngineBlock:(id /* block */)a2;
- (void)scrollNode:(id)a0 targetSubViewID:(id)a1 atScrollPosition:(unsigned long long)a2 offsetYWithPosition:(double)a3 animated:(BOOL)a4 speedMultiple:(double)a5 anchorToPageTop:(BOOL)a6 includeStickyContainer:(BOOL)a7 completion:(id /* block */)a8;
- (void)scrollNode:(id)a0 atScrollPosition:(unsigned long long)a1 offsetYWithPosition:(double)a2 animated:(BOOL)a3 completion:(id /* block */)a4;
- (void)updateHalfContainerIntialRatio:(double)a0;
- (id)viewWithUniqueTag:(id)a0;
- (void)setLynxClass:(Class)a0;
- (void)setLynxTrackParamsProvider:(id)a0;
- (Class)lynxClass;
- (id)ditoPerformanceMonitor;
- (id)superNode:(id)a0;
- (void)reloadContainerWithType:(id)a0;
- (id)lynxPreloadManager;
- (id)componentViewModelByTag:(id)a0;
- (id)getTagsContextItemForOptionKey:(id)a0;
- (id)getTagsContextItemForOptionKey:(id)a0;
- (BOOL)hasCacheWithKey:(id)a0;
- (void)setTagsContextItem:(id)a0 forOptionKey:(id)a1;
- (void)setTagsContextItem:(id)a0 forOptionKey:(id)a1;
- (void)removeTagsContextItemForOptionKey:(id)a0;
- (void)removeTagsContextItemForOptionKey:(id)a0;
- (id)lynxTrackParamsProvider;
- (id)lynxPreloadManagerV2;
- (void)iterateWithGroupTagName:(id)a0 pageModel:(id)a1 block:(id /* block */)a2;
- (id)cachePageModels;
- (void)removeTags:(id)a0 animationDuration:(double)a1;
- (void)foldGroup:(id)a0 startIndex:(long long)a1 endIndex:(long long)a2 animationDuration:(double)a3;
- (void)expandGroup:(id)a0 startIndex:(long long)a1 endIndex:(long long)a2 animationDuration:(double)a3;
- (double)currentModalViewRatio;
- (void)scrollNode:(id)a0 atScrollPosition:(unsigned long long)a1 animated:(BOOL)a2 completion:(id /* block */)a3;
- (void)scrollToOffset:(struct CGPoint { double x0; double x1; })a0 animated:(BOOL)a1 completion:(id /* block */)a2;
- (id)tempoExtension;
- (id)tempoContainerWithNodeTag:(id)a0;
- (void)cancelPresetHeight:(id)a0;
- (id)resourceInfoByNodeTag:(id)a0;
- (void)updateDitoBodyContainerFirstNodeTopMargin:(id)a0;
- (id)ditoBodyContainerFirstNodeTopMargin;
- (void)reloadBodyContainerLayout;
- (BOOL)fixSkipNestedScrollWhenElevator;
- (void)subscribeJSB:(id)a0 eventName:(id)a1 params:(id)a2 eventCallback:(id /* block */)a3;
- (id)lynxGeneralViewModelByNodeTag:(id)a0;
- (id)lynxContainerWithNodeTag:(id)a0;
- (BOOL)enableDitoNewArchitecture;
- (id)lynxExtensionV1;
- (double)renderCompleteHeightWithTag:(id)a0;
- (void)updateComponentNestedScrollItem:(id)a0 viewModel:(id)a1;
- (void)setupComponentNestedScrollEnabled:(id)a0 nestedScrollEnabled:(BOOL)a1;
- (void)setComponentErrorStageOfTag:(id)a0 stage:(long long)a1 message:(id)a2 errorType:(id)a3;
- (unsigned long long)numberOfLynxNodeDidStartLoad;
- (unsigned long long)numberOfLynxNodeDidEndLoad;
- (id)nodeTagListOfLynxNodeDidStartLoad;
- (id)nodeTagListOfLynxNodeDidEndLoad;
- (double)firstLynxNodeStartLoadDuration;
- (id)logCommonParamsWithPageModel:(id)a0;
- (id)nodesOfLynxLoadInFMP;
- (id)convertDitoLogToExceptionModel:(id)a0;
- (id)convertDitoLogToPerformanceModel:(id)a0;
- (id)nodeForView:(id)a0;
- (void)setSharkContainerSwitch:(BOOL)a0;
- (BOOL)sharkContainerSwitch;
- (void)setDestroyHeadlessLynxTimeoutKey:(BOOL)a0;
- (BOOL)destroyHeadlessLynxTimeoutKey;
- (void)setHeadlessLynxDisableUiFlushEnableKey:(BOOL)a0;
- (BOOL)headlessLynxDisableUiFlushEnableKey;
- (id)ditoGeneralContainerTagsContextKey:(id)a0;
- (void)virtualRefreshPageWithUrl:(id)a0 taskId:(id)a1 refreshPageWhenTimeOut:(BOOL)a2 timeOutDuration:(double)a3 showLoadingView:(BOOL)a4 extraParams:(id)a5 callback:(id /* block */)a6;
- (void)addNode:(id)a0 index:(long long)a1 animationDuration:(double)a2;
- (id)fetchGroupTrackParamsWithComponentTag:(id)a0;
- (BOOL)optNestedScrollSideBar;
- (void)didReceivePerformanceModel:(id)a0;
- (void)startComponentShowTimeTrack:(id)a0;
- (void)pauseComponentShowTimeTrack:(id)a0;
- (void)setComponentLongestStageOfTag:(id)a0 stage:(long long)a1;
- (id)siblingNodeList:(id)a0;
- (id)leftSiblingNode:(id)a0;
- (id)rightSiblingNode:(id)a0;
- (id)fetchCacheItemWithKey:(id)a0;
- (void)cacheNodeTreeWithTag:(id)a0 withCacheKey:(id)a1 extraParams:(id)a2;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })nodeFrameInContainer:(id)a0;
- (void)removeGroup:(id)a0 startIndex:(long long)a1 endIndex:(long long)a2 animationDuration:(double)a3;
- (id)componentTagListInNodeContainHidden:(id)a0;
- (id)componentTagListInNode:(id)a0;
- (BOOL)whetherToRender:(id)a0;
- (struct CGPoint { double x0; double x1; })bodyContentStartPointInPage;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })cardFrameTopWithTag:(id)a0 targetSubViewID:(id)a1;
- (BOOL)fixStickyAndNestedScroll;
- (double)cardMarginTopWithTag:(id)a0 targetSubViewID:(id)a1;
- (void)cancelRepeatAnchorPage;
- (void)updateDitoHalfContainerType:(unsigned long long)a0;
- (BOOL)fixScrollConflict;
- (BOOL)fixNestedScrollSkipOffsetToHalfContainer;
- (void)scrollBodyContainerToContentOffset:(struct CGPoint { double x0; double x1; })a0 shouldLimitContentOffset:(BOOL)a1;
- (double)stickyRemainContentHeight;
- (long long)nodeIndexInBodyContainerWithTag:(id)a0;
- (BOOL)optNestedScrollHalfScreenConflict;
- (double)stickyHeightAboveNode:(id)a0;
- (void)logDitoError:(id)a0 withDitoErrorType:(id)a1;
- (void)logCustomError:(id)a0 withDitoErrorType:(id)a1 reportType:(unsigned long long)a2 level:(unsigned long long)a3 extraParams:(id)a4 processor:(id /* block */)a5;
- (id)createExceptionModelWithExceptionType:(id)a0 infoLevel:(unsigned long long)a1 reportType:(unsigned long long)a2 errorObject:(id)a3 extraParams:(id)a4;
- (void)logDitoError:(id)a0 withDitoErrorType:(id)a1 extraParams:(id)a2 processor:(id /* block */)a3;
- (void)tryLogWithLogInfoLevel:(unsigned long long)a0 description:(id)a1 extraParams:(id)a2;
- (void)logCustomError:(id)a0 withDitoErrorType:(id)a1 level:(unsigned long long)a2;
- (BOOL)fixHalfScreenHorizontalBeginPos;
- (BOOL)fixStickyExtensionFirstConsume;
- (BOOL)enableDitoRenderBodyFirst;
- (id)trackExtension;
- (id)anchorPageScheduler;
- (double)calculateScrollTag:(id)a0 node:(id)a1 pageView:(id)a2 bodyView:(id)a3 atScrollPosition:(unsigned long long)a4 offsetYWithPosition:(double)a5 anchorToPageTop:(BOOL)a6 includeStickyContainer:(BOOL)a7;
- (void)scrollTo:(double)a0 halfContainer:(id)a1 speedMultiple:(double)a2 bodyView:(id)a3 animated:(BOOL)a4 resultBlock:(id /* block */)a5;
- (double)calculateNodeContentOffsetY:(id)a0 atScrollPosition:(unsigned long long)a1 offsetYWithPosition:(double)a2 anchorToPageTop:(BOOL)a3;
- (double)calculateMinContentSizeHeightWithStickyNodeFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (id)calculateStickyNodesContentOffsetY;
- (long long)findNearestStickyNodeIndex:(id)a0 curScrollContentOffsetY:(double)a1;
- (id)stickyManger;
- (double)getBodyPatchYOffset;
- (void)scrollBodyContainerToContentOffset:(struct CGPoint { double x0; double x1; })a0 shouldLimitContentOffset:(BOOL)a1 speedMultiple:(double)a2 animate:(BOOL)a3 completion:(id /* block */)a4;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })DitoNodeContentFrameConcernItsStyleWithTag:(id)a0;
- (void)scrollNode:(id)a0 atScrollPosition:(unsigned long long)a1 offsetYWithPosition:(double)a2 animated:(BOOL)a3 speedMultiple:(double)a4 completion:(id /* block */)a5;
- (unsigned long long)positonTransformation:(unsigned long long)a0;
- (id)fetchSuperNodeListWithTag:(id)a0;
- (id)getSuperNodeWithNode:(id)a0;
- (void)parseData:(id)a0 withCompletion:(id /* block */)a1;
- (id)mergePageModel:(id)a0;
- (void)updatePageModel:(id)a0 animationDuration:(double)a1;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bodyIntersectHeaderFrame;
- (BOOL)registerWidget:(id)a0 name:(id)a1;
- (id)IESLLPOICityDetailTagsContextKey:(id)a0;
- (float)floatForKey:(id)a0;
- (void)setDouble:(double)a0 forKey:(id)a1;
- (void)setSessionID:(id)a0;
- (void)setBool:(BOOL)a0 forKey:(id)a1;
- (void)setString:(id)a0 forKey:(id)a1;
- (void).cxx_destruct;
- (void)setInteger:(long long)a0 forKey:(id)a1;
- (void)setArray:(id)a0 forKey:(id)a1;
- (id)dictionaryForKey:(id)a0;
- (id)objectForKey:(id)a0;
- (void)setFloat:(float)a0 forKey:(id)a1;
- (id)init;
- (BOOL)boolForKey:(id)a0;
- (long long)integerForKey:(id)a0;
- (id)arrayForKey:(id)a0;
- (void)removeObjectForKey:(id)a0;
- (double)doubleForKey:(id)a0;
- (id)stringForKey:(id)a0;
- (void)dealloc;
- (void)setDictionary:(id)a0 forKey:(id)a1;
- (void)setObject:(id)a0 forKey:(id)a1;

@end
