@class RACSequence;

@interface RACSignal : RACStream

@property (readonly, nonatomic) RACSequence *sequence;

+ (id)if:(id)a0 then:(id)a1 else:(id)a2;
+ (id)defer:(id /* block */)a0;
+ (id)interval:(double)a0 onScheduler:(id)a1 withLeeway:(double)a2;
+ (id)try:(id /* block */)a0;
+ (id)combineLatest:(id)a0 reduce:(id /* block */)a1;
+ (id)interval:(double)a0 onScheduler:(id)a1;
+ (id)switch:(id)a0 cases:(id)a1 default:(id)a2;
+ (id)createSignal:(id /* block */)a0;
+ (id)startLazilyWithScheduler:(id)a0 block:(id /* block */)a1;
+ (id)never;
+ (id)startEagerlyWithScheduler:(id)a0 block:(id /* block */)a1;
+ (id)return:(id)a0;
+ (id)createSignalWithServiceRegister:(id)a0 serviceProtocol:(id)a1;
+ (id)empty;
+ (id)merge:(id)a0;
+ (id)error:(id)a0;
+ (id)combineLatest:(id)a0;

- (id)deliverOnMainThread;
- (id)subscribeNext:(id /* block */)a0;
- (id)or;
- (id)retry:(long long)a0;
- (id)subscribeNext:(id /* block */)a0 error:(id /* block */)a1;
- (id)and;
- (id)ignoreValues;
- (id)catchTo:(id)a0;
- (id)replayLast;
- (id)throttle:(double)a0 valuesPassingTest:(id /* block */)a1;
- (id)aggregateWithStartFactory:(id /* block */)a0 reduce:(id /* block */)a1;
- (id)combineLatestWith:(id)a0;
- (id)flatten:(unsigned long long)a0;
- (id)aggregateWithStart:(id)a0 reduce:(id /* block */)a1;
- (id)aggregateWithStart:(id)a0 reduceWithIndex:(id /* block */)a1;
- (id)switchToLatest;
- (id)firstOrDefault:(id)a0 success:(BOOL *)a1 error:(id *)a2;
- (id)groupBy:(id /* block */)a0 transform:(id /* block */)a1;
- (id)throttle:(double)a0;
- (id)try:(id /* block */)a0;
- (id)tryMap:(id /* block */)a0;
- (id)initially:(id /* block */)a0;
- (id)bufferWithTime:(double)a0 onScheduler:(id)a1;
- (id)concat;
- (id)setKeyPath:(id)a0 onObject:(id)a1;
- (id)takeUntilReplacement:(id)a0;
- (BOOL)waitUntilCompleted:(id *)a0;
- (id)replayLazily;
- (id)reduceApply;
- (id)subscribeNext:(id /* block */)a0 error:(id /* block */)a1 completed:(id /* block */)a2;
- (id)subscribeNext:(id /* block */)a0 completed:(id /* block */)a1;
- (id)subscribeError:(id /* block */)a0;
- (id)subscribeCompleted:(id /* block */)a0;
- (id)subscribeError:(id /* block */)a0 completed:(id /* block */)a1;
- (id)logNext;
- (id)logError;
- (id)logCompleted;
- (id)doError:(id /* block */)a0;
- (id)doCompleted:(id /* block */)a0;
- (id)logAll;
- (id)asynchronousFirstOrDefault:(id)a0 success:(BOOL *)a1 error:(id *)a2 timeout:(double)a3;
- (id)timeout:(double)a0 onScheduler:(id)a1;
- (id)deliverOn:(id)a0;
- (BOOL)asynchronouslyWaitUntilCompleted:(id *)a0 timeout:(double)a1;
- (id)asynchronousFirstOrDefault:(id)a0 success:(BOOL *)a1 error:(id *)a2;
- (BOOL)asynchronouslyWaitUntilCompleted:(id *)a0;
- (id)firstOrDefault:(id)a0;
- (id)zipWith:(id)a0;
- (id)setKeyPath:(id)a0 onObject:(id)a1 nilValue:(id)a2;
- (id)delay:(double)a0;
- (id)publish;
- (id)subscribe:(id)a0;
- (id)then:(id /* block */)a0;
- (id)all:(id /* block */)a0;
- (id)description;
- (id)concat:(id)a0;
- (id)first;
- (id)replay;
- (id)any:(id /* block */)a0;
- (id)catch:(id /* block */)a0;
- (id)merge:(id)a0;
- (id)not;
- (id)groupBy:(id /* block */)a0;
- (id)retry;
- (id)collect;
- (id)subscribeOn:(id)a0;
- (id)any;
- (id)dematerialize;
- (id)materialize;
- (id)sample:(id)a0;
- (id)takeLast:(unsigned long long)a0;
- (id)takeUntil:(id)a0;
- (id)toArray;
- (id)finally:(id /* block */)a0;
- (id)repeat;
- (id)multicast:(id)a0;
- (id)doNext:(id /* block */)a0;
- (id)bind:(id /* block */)a0;

@end
