@class SearchListContainerEdgePanView, NSString, NSArray, SearchListContainerBounceElement, SearchHorizontalPlayRule, NSMutableDictionary, NSDictionary, AWESearchAutoPlayHandler, NSMutableArray, LynxUIListContainer;
@protocol SearchDynamicElementStatusDelegate;

@interface SearchListContainerElement : LynxUI <SearchDynamicElementProtocol, AWESearchAutoPlayContainerProtocol, AWESearchAutoPlayCardProtocol, LynxUIListContainerDelegate, UIScrollViewDelegate>

@property (copy, nonatomic) NSString *sessionid;
@property (copy, nonatomic) NSDictionary *logExtra;
@property (copy, nonatomic) NSArray *cardList;
@property (nonatomic) BOOL bounce;
@property (nonatomic) BOOL banReturnLastPage;
@property (nonatomic) BOOL isTriggeringLeftBounce;
@property (nonatomic) BOOL isShowingLeftBounce;
@property (nonatomic) BOOL isTriggeringRightBounce;
@property (nonatomic) BOOL isShowingRightBounce;
@property (nonatomic) BOOL enableSearchListPagePanBackSwitch;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } activeRect;
@property (nonatomic) BOOL pauseByUser;
@property (retain, nonatomic) NSMutableDictionary *internalSessionIdDict;
@property (copy, nonatomic) NSString *contentSizeObserverIdentify;
@property (retain, nonatomic) SearchListContainerEdgePanView *edgePanView;
@property (nonatomic) BOOL isBecomeActiveCalled;
@property (retain, nonatomic) LynxUIListContainer *lynxListContainer;
@property (retain, nonatomic) SearchListContainerBounceElement *leftBounce;
@property (retain, nonatomic) SearchListContainerBounceElement *rightBounce;
@property (copy, nonatomic) NSString *scrollMonitorTag;
@property (retain, nonatomic) AWESearchAutoPlayHandler *horizontalAutoPlayHandler;
@property (retain, nonatomic) SearchHorizontalPlayRule *horizontalAutoPlayRule;
@property (retain, nonatomic) NSMutableArray *cardWrapperList;
@property (weak, nonatomic) id<SearchDynamicElementStatusDelegate> statusDelegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL isActive;
@property (weak, nonatomic) AWESearchAutoPlayHandler *autoPlayHandler;

+ (id)__lynx_prop_config__1552;
+ (id)__lynx_prop_config__1744;
+ (id)__lynx_prop_config__1471;
+ (id)__lynx_prop_config__2038;
+ (id)__lynx_prop_config__1967;
+ (id)__lynx_prop_config__1390;
+ (id)__lynx_prop_config__1603;
+ (id)__lynx_prop_config__1795;
+ (id)__lynx_prop_config__1876;
+ (id)__lynx_ui_method_config__2259;
+ (id)__lynx_ui_method_config__23310;
+ (id)__lynx_ui_method_config__23911;

- (void)logExtra:(id)a0 requestReset:(BOOL)a1;
- (void)setScrollMonitorTag:(id)a0 requestReset:(BOOL)a1;
- (id)getEngine;
- (BOOL)shouldNotActive;
- (unsigned long long)suitableRuleType;
- (id)feedScrollView;
- (id)scrollProxy;
- (void)didEndShowing;
- (void)didStartShowing;
- (BOOL)isMediaSourceCard;
- (void)sessionid:(id)a0 requestReset:(BOOL)a1;
- (void)viewWillDisAppear;
- (void)insertListComponent:(id)a0 wrapper:(id)a1;
- (void)removeListComponent:(id)a0;
- (id)lynxListContainerContextDict;
- (void)handleBounceViewElementFrame:(id)a0;
- (void)startContentSizeObserver;
- (void)updateHorizontalAutoPlayHandler;
- (void)elementDidFinishBind;
- (void)updateListInternalSessionIdDict;
- (void)scrollToIndex:(long long)a0 smooth:(BOOL)a1;
- (void)updatePauseByUser:(BOOL)a0;
- (id)createComponentWrapperAtIndex:(long long)a0 withComponentSessionId:(id)a1;
- (void)sendScrollToActiveEventToFEIfNeeded:(long long)a0;
- (void)sendScrollEventToFE:(struct CGPoint { double x0; double x1; })a0;
- (void)sendBounceViewStatusEventToFE:(id)a0 showing:(BOOL)a1;
- (void)sendScrollToBounceEventToFE:(id)a0;
- (void)customScrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)customScrollViewWillBeginDragging:(id)a0;
- (void)bounce:(BOOL)a0 requestReset:(BOOL)a1;
- (void)activearea:(id)a0 requestReset:(BOOL)a1;
- (void)setCardList:(id)a0 requestReset:(BOOL)a1;
- (void)enablePagePanBackGesture:(BOOL)a0 requestReset:(BOOL)a1;
- (void)enableSearchListPagePanBack:(BOOL)a0 requestReset:(BOOL)a1;
- (void)panBackGestureLeftEdge:(double)a0 requestReset:(BOOL)a1;
- (void)scrolltoindex:(id)a0 withResult:(id /* block */)a1;
- (void)becomeactive:(id)a0 withResult:(id /* block */)a1;
- (void)resignactive:(id)a0 withResult:(id /* block */)a1;
- (void)setAutoPlayDisenabled:(BOOL)a0;
- (void)searchListPanBack;
- (id)getLynxElementType;
- (BOOL)shouldResumeAutomaticAutoPlay;
- (void)viewDidAppear;
- (void)didBecomeActive;
- (id)visibleCells;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)scrollViewDidScroll:(id)a0;
- (BOOL)hasVideo;
- (void)didResignActive;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (id)activeView;
- (void)insertChild:(id)a0 atIndex:(long long)a1;
- (id)createView;

@end
