@class SearchDynamicContext, BDXContext, NSDictionary, NSString, UIView, SearchDynamicContainerView;
@protocol AnnieXContainerBaseProtocol, BDXViewContainerProtocol, SearchDynamicLifeCyleProtocol, AnnieXCardModelProtocol, SearchDynamicEngineRenderDelegate, SearchDynamicElementProtocol, SearchDynamicEngineDelegate;

@interface SearchDynamicEngine : NSObject <BDXContainerLifecycleProtocol, SearchDynamicElementStatusDelegate, SearchDynamicContainerProtocol>

@property (nonatomic) BOOL byReload;
@property (nonatomic) long long reuseMethod;
@property (retain, nonatomic) id<SearchDynamicLifeCyleProtocol> searchDynamicLifeCyle;
@property (retain, nonatomic) NSDictionary *initialData;
@property (nonatomic) double firstScreenTS;
@property (nonatomic) struct CGSize { double width; double height; } lastContainerSize;
@property (retain, nonatomic) BDXContext *bdxContext;
@property (retain, nonatomic) UIView<BDXViewContainerProtocol> *bdxView;
@property (nonatomic) BOOL isAnnieX;
@property (retain, nonatomic) id<AnnieXCardModelProtocol> anniexModel;
@property (retain, nonatomic) UIView<AnnieXContainerBaseProtocol> *annieXView;
@property (retain, nonatomic) SearchDynamicContext *sdContext;
@property (weak, nonatomic) id<SearchDynamicEngineRenderDelegate> renderDelegate;
@property (weak, nonatomic) id<SearchDynamicEngineDelegate> delegate;
@property (retain, nonatomic) SearchDynamicContainerView *containerView;
@property (retain, nonatomic) id<SearchDynamicElementProtocol> lynxElementView;
@property (nonatomic) BOOL hasShown;
@property (nonatomic) BOOL didMount;
@property (nonatomic) BOOL hasHydrated;
@property (nonatomic) BOOL showEventTriggered;
@property (nonatomic) BOOL shouldReuseLynxView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)container:(id)a0 didFinishLoadWithURL:(id)a1;
- (void)container:(id)a0 didLoadFailedWithUrl:(id)a1 error:(id)a2;
- (void)containerWillDestory:(id)a0;
- (void)containerDidPageReady:(id)a0 sourceParam:(id)a1;
- (void)containerOnShow:(id)a0 sourceParam:(id)a1;
- (void)containerOnHide:(id)a0 sourceParam:(id)a1;
- (BOOL)container:(id)a0 shouldStartLoadWithRequest:(id)a1 navigationType:(id)a2;
- (void)container:(id)a0 didChangeIntrinsicContentSize:(struct CGSize { double x0; double x1; })a1;
- (void)containerOnTasmFinishByNative:(id)a0;
- (void)containerWillStartLoading:(id)a0;
- (void)containerDidStartLoading:(id)a0;
- (void)container:(id)a0 didStartLoadingSuccessWithUrl:(id)a1;
- (void)container:(id)a0 didStartLoadingFailedWithUrl:(id)a1;
- (void)container:(id)a0 didStartFetchResourceWithURL:(id)a1;
- (void)container:(id)a0 didFetchedResource:(id)a1 error:(id)a2;
- (void)containerDidFirstScreen:(id)a0;
- (void)containerDidUpdate:(id)a0;
- (void)container:(id)a0 didRecieveError:(id)a1;
- (void)container:(id)a0 didReceivePerformance:(id)a1;
- (void)container:(id)a0 updateTitle:(id)a1;
- (void)containerDidClose:(id)a0;
- (void)container:(id)a0 didStartAnimationWithDuration:(double)a1 startFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a2 finalFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a3;
- (void)container:(id)a0 didEndAnimationWithDuration:(double)a1 startFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a2 finalFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a3;
- (void)containerDidPageUpdate:(id)a0;
- (void)containerDidConstructJSRuntime:(id)a0;
- (void)container:(id)a0 didReceivePerformanceFirstLoad:(id)a1 bulletPerfDict:(id)a2;
- (void)container:(id)a0 didFetchFromPool:(id)a1;
- (void)container:(id)a0 didReuseFromPool:(id)a1;
- (void)container:(id)a0 didRecycleIntoPool:(id)a1;
- (void)container:(id)a0 didFallBackWithURL:(id)a1;
- (void)container:(id)a0 onSetupLynxInfo:(id)a1 bulletInfo:(id)a2;
- (void)container:(id)a0 onUpdateLynxInfo:(id)a1 bulletInfo:(id)a2;
- (void)sendEvent:(id)a0 params:(id)a1;
- (void)registerXBridgeMethod:(id)a0;
- (void)updateData:(id)a0 processorName:(id)a1;
- (void)didEndShowing;
- (void)didStartShowing;
- (BOOL)isMediaSourceCard;
- (void)startScroll;
- (void)endScroll;
- (id)templateDataWithModel:(id)a0;
- (void)commonContextProcessWithContext:(id)a0;
- (void)renderUpdateDataWithView:(id)a0 context:(id)a1;
- (id)lifeCyleWithContext:(id)a0;
- (id)renderViewWithContext:(id)a0;
- (void)renderBindDataWithView:(id)a0 context:(id)a1;
- (id)renderAnnieXModel;
- (void)renderAnnieXViewUpdate:(id)a0 withModel:(id)a1;
- (id)renderAnnieXViewWithModel:(id)a0;
- (void)updateSearchDynamicLynxElement:(id)a0;
- (void)updateSearchDynamicLynxElement;
- (void)searchDynamicLynxElement;
- (void)searchElementDidFinishBind;
- (void)commonContextProcessWithModel:(id)a0;
- (void)renderSSRHydrateWithView:(id)a0 context:(id)a1;
- (BOOL)shouldTransitionWithPlayer;
- (BOOL)shouldTransitionWithPlayStatus;
- (void)ssrHydrate;
- (void)registerXBridgeMethodWithBDXBridge:(id)a0;
- (void)updateDataFromRotate:(id)a0 processorName:(id)a1;
- (void)didTotallyShow;
- (id)getLynxElementTagName;
- (void)viewDidAppear;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (id)init;
- (id)sessionID;
- (id)renderContext;
- (void)updateWithContext:(id)a0;
- (void)restartAnimation;
- (void)viewWillDisappear;

@end
