@class NSString;

@interface SubtitleItemV2 : GPBMessage

@property (nonatomic) long long id_p;
@property (nonatomic) BOOL hasId_p;
@property (nonatomic) long long complaintId;
@property (nonatomic) BOOL hasComplaintId;
@property (nonatomic) long long expire;
@property (nonatomic) BOOL hasExpire;
@property (copy, nonatomic) NSString *format;
@property (nonatomic) BOOL hasFormat;
@property (nonatomic) BOOL isAutoGenerated;
@property (nonatomic) BOOL hasIsAutoGenerated;
@property (copy, nonatomic) NSString *languageCode;
@property (nonatomic) BOOL hasLanguageCode;
@property (nonatomic) int languageId;
@property (nonatomic) BOOL hasLanguageId;
@property (copy, nonatomic) NSString *language;
@property (nonatomic) BOOL hasLanguage;
@property (nonatomic) long long subId;
@property (nonatomic) BOOL hasSubId;
@property (copy, nonatomic) NSString *translatorId;
@property (nonatomic) BOOL hasTranslatorId;
@property (copy, nonatomic) NSString *URL;
@property (nonatomic) BOOL hasURL;
@property (copy, nonatomic) NSString *subVersion;
@property (nonatomic) BOOL hasSubVersion;

+ (id)descriptor;

@end
