@class NSString, TIMXConversationChecker, TIMXSDKInstance, TIMXPBResponseLongConnectionCallback, TIMXBatchUpdateAggregater;
@protocol TIMXInstanceDispatchQueuePoolProtocol;

@interface TIMXConversationManagerV2 : NSObject <TIMXConversationListProtocol, TIMXConversationCreatorProtocol, TIMXConversationInfoUpdaterProtocol, TIMXConversationParticipantOperationProtocol, TIMXConversationCreatorProtocol, TIMXConversationInfoUpdaterProtocol, TIMXMessageStoreChangesObserver, TIMXConversationParticipantOperationProtocol, TIMXStartUpTaskProtocol, TIMXConversationListProtocol, TIMXBatchUpdateAggregaterDelegate, TIMXConversationModelUpdateEventProtocol, TIMXInstanceScopeSingleton> {
    TIMXSDKInstance *_r;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) TIMXPBResponseLongConnectionCallback *callback;
@property (retain, nonatomic) TIMXConversationChecker *conversationChecker;
@property (retain, nonatomic) id<TIMXInstanceDispatchQueuePoolProtocol> queuePool;
@property (retain, nonatomic) TIMXBatchUpdateAggregater *updateAggregater;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (long long)startUpOrder;
+ (void)startUpWithRootObject:(id)a0;

- (void)fetchConversationInfo:(long long)a0 conversationID:(id)a1 type:(int)a2 inInbox:(int)a3 completion:(id /* block */)a4;
- (void)userDidLogin:(id)a0;
- (void)updateConversation:(id)a0;
- (void)leaveConversation:(id)a0 completion:(id /* block */)a1;
- (void)fetchAllConversationsByLocalDBInInbox:(int)a0 beforeSortOrder:(long long)a1 conversationType:(int)a2 pageCount:(unsigned long long)a3 completion:(id /* block */)a4;
- (void)onConversationsCreated:(id)a0;
- (void)onUnknownParticipantAppearedInConversation:(id)a0;
- (void)createThreadWithRootMessageid:(id)a0 rootServerMessageId:(long long)a1 parentConversationShortId:(long long)a2 completion:(id /* block */)a3;
- (void)createConversationWithContext:(id)a0 completion:(id /* block */)a1;
- (void)createEcomConversationWithContext:(id)a0 completion:(id /* block */)a1;
- (void)createSubConversationWithParentConvShortID:(long long)a0 parentConvID:(id)a1 inInbox:(int)a2 participantsObjects:(id)a3 bizExtension:(id)a4 completion:(id /* block */)a5;
- (id)taskSourceForEnsureShortIDForSingleChat:(id)a0 shortID:(long long)a1 type:(int)a2 inInbox:(int)a3;
- (void)loadRemoteConversationsIfLocalNotExist:(id)a0 shortIdMap:(id)a1 typeMap:(id)a2 inbox:(int)a3 completion:(id /* block */)a4;
- (void)updateConversation:(id)a0 completion:(id /* block */)a1;
- (void)batchUpdateAggregater:(id)a0 needProcessBatch:(id)a1;
- (void)updateConversationsIfExist:(id)a0 completion:(id /* block */)a1;
- (void)ecomUpdateAndCheckMessageContinues:(id)a0 completion:(id /* block */)a1;
- (void)updateConversation:(id)a0 convInfoUpateType:(unsigned long long)a1 userIDs:(id)a2 completion:(id /* block */)a3;
- (void)upsertWithLocalObject:(id)a0 inInbox:(int)a1 forceSave:(BOOL)a2 completion:(id /* block */)a3;
- (void)updateConversationSettingsSyncedExtEntries:(id)a0 onConversation:(id)a1 completion:(id /* block */)a2;
- (void)updateConversationSettingsSyncedExtEntries:(id)a0 shouldRequest:(BOOL)a1 onConversation:(id)a2 completion:(id /* block */)a3;
- (void)upsertWithLocalConversationObject:(id)a0 inInbox:(int)a1 forbidNotify:(BOOL)a2 forceSave:(BOOL)a3 completion:(id /* block */)a4;
- (void)updateDBConvInfoWithPBConvInfo:(id)a0 updateType:(unsigned long long)a1 forbidNotify:(BOOL)a2 inbox:(int)a3 completion:(id /* block */)a4;
- (void)batchUpdateDBConvInfoWithPBConvInfo:(id)a0 forbidNotify:(BOOL)a1 inbox:(int)a2 completion:(id /* block */)a3;
- (void)batchUpdateConversationSettingsSyncedExtEntries:(id)a0 conversationIDs:(id)a1 retryCount:(unsigned long long)a2 completion:(id /* block */)a3;
- (void)batchUpdateConversationSettingsSyncedExtEntries:(id)a0 shouldRequest:(BOOL)a1 conversationIDs:(id)a2 retryCount:(unsigned long long)a3 completion:(id /* block */)a4;
- (void)updateConversationCoreInfoSyncedExtEntries:(id)a0 onConversation:(id)a1 completion:(id /* block */)a2;
- (void)updateConversationParticipant:(long long)a0 entries:(id)a1 onConversation:(id)a2 completion:(id /* block */)a3;
- (void)updateConversationBatchParticipants:(id)a0 entries:(id)a1 onConversation:(id)a2 bizExt:(id)a3 completion:(id /* block */)a4;
- (void)updateConversationSettingsEntries:(id)a0 onConversation:(id)a1 completion:(id /* block */)a2;
- (void)updateConversationCoreInfoEntries:(id)a0 ext:(id)a1 onConversation:(id)a2 completion:(id /* block */)a3;
- (void)setConversationSilent:(id)a0 silentStatus:(long long)a1 silentNormalOnly:(BOOL)a2 speakMode:(id)a3 completion:(id /* block */)a4;
- (void)setMemberSilent:(id)a0 silentStatus:(long long)a1 members:(id)a2 bizExtension:(id)a3 complection:(id /* block */)a4;
- (void)updateBadgeCount:(id)a0 pbBadgeCount:(int)a1;
- (void)updateThreadMessageCount:(int)a0 conv:(id)a1;
- (void)updateThreadBadgeCount:(int)a0 conv:(id)a1;
- (void)updateImportantThreadBadgeCount:(int)a0 conv:(id)a1;
- (void)updateThreadSubscribeStatus:(id)a0 subscribeStatus:(long long)a1 completion:(id /* block */)a2;
- (void)batchFetchConvInfosWithConvIds:(id)a0;
- (void)fetchAllFavoritedConversationsInInbox:(int)a0 completion:(id /* block */)a1;
- (void)fetchAllStickedOnTopConversationsInInbox:(int)a0 completion:(id /* block */)a1;
- (void)batchFetchConversationConversations:(id)a0 shortIDs:(id)a1 types:(id)a2 inbox:(int)a3 completion:(id /* block */)a4;
- (void)fetchConvForConversationShortID:(long long)a0 conversationID:(id)a1 type:(int)a2 inInbox:(int)a3 completion:(id /* block */)a4;
- (void)fetchAllConversationsInInbox:(int)a0 cursor:(long long)a1 conversationType:(int)a2 extEntries:(id)a3 pageCount:(unsigned long long)a4 completion:(id /* block */)a5;
- (void)clientMetric:(id)a0 inbox:(int)a1;
- (void)fetchAllFetchFailedConversations:(id /* block */)a0;
- (void)_fetchAllFavoritedConversationsInInbox:(int)a0 cursor:(long long)a1 resultArray:(id)a2 completion:(id /* block */)a3;
- (void)handleSuccessFetchConvInfo:(id)a0 inbox:(int)a1 completion:(id /* block */)a2;
- (void)_fetchAllStickOnTopConversationsInInbox:(int)a0 cursor:(long long)a1 resultArray:(id)a2 completion:(id /* block */)a3;
- (void)p_loadRemoteNotInDbConvs:(id)a0 pageConfig:(id)a1 inbox:(int)a2 completion:(id /* block */)a3;
- (void)p_handleSuccessFetchConvInfos:(id)a0 responseObject:(id)a1 inbox:(int)a2 completion:(id /* block */)a3;
- (void)createSingleConversationWithContext:(id)a0 allParticipants:(id)a1 completion:(id /* block */)a2;
- (void)createGroupConversationWithContext:(id)a0 allParticipants:(id)a1 completion:(id /* block */)a2;
- (void)_updateConversationsIfExist:(id)a0 completion:(id /* block */)a1;
- (void)p_endLogEventForConvInfoUpdate:(id)a0 logMarker:(id)a1 updatedKeyValues:(id)a2 conversationID:(id)a3 error:(id)a4;
- (void)p_updateConversationEntries:(id)a0 logEventName:(id)a1 onConversation:(id)a2 requestConfigBlock:(id /* block */)a3 responseHandler:(id /* block */)a4 completion:(id /* block */)a5;
- (void)updateDBConvInfoWithPBConvInfo:(id)a0 updateType:(unsigned long long)a1 shouldUpdateAllInfo:(BOOL)a2 forbidNotify:(BOOL)a3 inbox:(int)a4 completion:(id /* block */)a5;
- (void)updateWithLocalConversationSettingsObject:(id)a0 inInbox:(int)a1 completion:(id /* block */)a2;
- (void)updateWithLocalConversationCoreInfoObject:(id)a0 inInbox:(int)a1 completion:(id /* block */)a2;
- (void)upsertWithStrangerConversationObject:(id)a0 inInbox:(int)a1 completion:(id /* block */)a2;
- (id)p_validateParamsOfConversationID:(id)a0 shortID:(long long)a1 checkConvExist:(BOOL)a2;
- (int)sdkConversationTypeFromPBType:(int)a0;
- (void)updateConvParticipant:(id)a0 participantInfo:(id)a1 serverParticipantCount:(long long)a2;
- (BOOL)isStrangerWithConversationID:(id)a0 mode:(int)a1 currentAccountID:(long long)a2;
- (void)p_updateConsultConvBelongedAcquaintanceType:(id)a0 participants:(id)a1 currentAccountID:(long long)a2;
- (void)updateConvBadgeCountInfo:(id)a0 pbConvInfo:(id)a1 readBadgeCount:(id)a2;
- (void)fetchAllParticipantsIfNeeded:(id)a0;
- (void)overrideBotsForPbConv:(id)a0;
- (id)p_validateParamsOfPbConv:(id)a0;
- (void)ecomUpdateDBConvInfoWithPBConvInfo:(id)a0 updateType:(unsigned long long)a1 shouldUpdateAllInfo:(BOOL)a2 forbidNotify:(BOOL)a3 inbox:(int)a4 completion:(id /* block */)a5;
- (void)p_configLocalConvInfoORMWithPBConvInfo:(id)a0 convInfoUpdateDBModel:(id)a1 updateType:(unsigned long long)a2 isSettingsInfoChanged:(BOOL *)a3 shouldUpdateAllInfo:(BOOL)a4 shouldApplyNewGroupMember:(BOOL)a5 updateParticipants:(id)a6;
- (void)p_configLocalNotEixstConvInfoORMWithPBConvInfo:(id)a0 inbox:(int)a1 convInfoUpdateDBModel:(id)a2 isSettingsInfoChanged:(BOOL *)a3 shouldApplyNewGroupMember:(BOOL)a4;
- (void)p_finishUpdateLocalNotExistConvInfoWithPBConvInfo:(id)a0 shouldApplyNewGroupMember:(BOOL)a1 forbidNotify:(BOOL)a2;
- (void)p_processConvORM:(id)a0 withPbInfo:(id)a1;
- (void)_updateConversationsIfExist:(id)a0 inInboxType:(int)a1 completion:(id /* block */)a2;
- (void)__updateDBConvUnreadCountAndLogChangeInfoWithConv:(id)a0 readBadgeCount:(long long)a1 changedReason:(id)a2;
- (void)insertParticipantsPages:(id)a0 forConversation:(id)a1;
- (void)fetchAllParticipantsFromServerConv:(id)a0 page:(id)a1 resultArray:(id)a2;
- (id)p_transferLocalParticipantModelToPBModel:(id)a0;
- (void)addParticipants:(id)a0 toConversation:(id)a1 bizExtension:(id)a2 completion:(id /* block */)a3;
- (void)removeParticipants:(id)a0 fromConversation:(id)a1 bizExtension:(id)a2 completion:(id /* block */)a3;
- (void)addBots:(id)a0 toConversation:(id)a1 bizExtension:(id)a2 completion:(id /* block */)a3;
- (void)removeBots:(id)a0 fromConversation:(id)a1 bizExtension:(id)a2 completion:(id /* block */)a3;
- (void)updateBot:(long long)a0 fromConversation:(id)a1 bizExtension:(id)a2 completion:(id /* block */)a3;
- (void)dismissConversation:(id)a0 bizExtension:(id)a1 completion:(id /* block */)a2;
- (void)enterConversation:(id)a0 conversationType:(int)a1 shortID:(long long)a2 inbox:(int)a3 bizExtension:(id)a4 completion:(id /* block */)a5;
- (void)didUpdateConversationCoreInfo:(id)a0;
- (void)didUpdateConversationLocalExtDict:(id)a0;
- (BOOL)isBottomConversation:(id)a0;
- (void)setUp;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithRootObject:(id)a0;

@end
