@class NSString, NSDictionary, TIMXSDKInstance, NSDate;

@interface TIMXConversationCoreInfoORM : TIMXBaseORM <WCTTableCoding, IESIMSDKBaseConversationCoreInfoModel, TIMXConversationCoreInfoModelProtocol> {
    TIMXSDKInstance *_r;
}

@property (nonatomic) long long ownerID;
@property (nonatomic) long long creatorUid;
@property (retain, nonatomic) NSDictionary *extDictionary;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSString *belongingConversationIdentifier;
@property (nonatomic) long long infoVersion;
@property (retain, nonatomic) NSString *name;
@property (retain, nonatomic) NSString *desc;
@property (retain, nonatomic) NSString *icon;
@property (retain, nonatomic) NSString *notice;
@property (nonatomic) long long ownerID;
@property (nonatomic) int mode;
@property (retain, nonatomic) NSString *ext;
@property (nonatomic) long long creatorUid;
@property (retain, nonatomic) NSDate *createTime;
@property (retain, nonatomic) NSDictionary *extDictionary;
@property (retain, nonatomic) NSDictionary *dbExtDictionary;
@property (nonatomic) int blockSource;
@property (nonatomic) int blockStatus;
@property (nonatomic) long long leftBlockTime;
@property (nonatomic) int blockNormalOnly;
@property (nonatomic) long long rootMessageId;
@property (nonatomic) long long parentConvShortId;
@property (retain, nonatomic) NSString *rootClientMessageId;
@property (retain, nonatomic) NSDictionary *extDictionaryForECOM;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (const void *)blockStatus;
+ (const void *)creatorUid;
+ (const void *)rootMessageId;
+ (const void *)rootClientMessageId;
+ (const void *)blockSource;
+ (const void *)leftBlockTime;
+ (const void *)blockNormalOnly;
+ (const void *)belongingConversationIdentifier;
+ (id)__wcdbtyper;
+ (const void *)objectRelationalMappingForWCDB;
+ (const void *)AllProperties;
+ (const void *)AnyProperty;
+ (id /* block */)PropertyNamed;
+ (const void *)__wcdb_synthesize_3:(void *)a0;
+ (const void *)objectRelationalMapping;
+ (const void *)ss_name;
+ (id)allBridgeProperties;
+ (id)swift_ss_name;
+ (const void *)__wcdb_synthesize_1:(void *)a0;
+ (const void *)ss_ext;
+ (const void *)__wcdb_synthesize_5:(void *)a0;
+ (const void *)__wcdb_synthesize_7:(void *)a0;
+ (const void *)__wcdb_synthesize_9:(void *)a0;
+ (id)swift_ss_ext;
+ (const void *)__wcdb_synthesize_11:(void *)a0;
+ (const void *)__wcdb_synthesize_13:(void *)a0;
+ (const void *)__wcdb_synthesize_15:(void *)a0;
+ (const void *)__wcdb_synthesize_17:(void *)a0;
+ (const void *)__wcdb_synthesize_19:(void *)a0;
+ (const void *)__wcdb_synthesize_21:(void *)a0;
+ (const void *)__wcdb_synthesize_23:(void *)a0;
+ (void)__wcdb_column_constraint_37:(void *)a0;
+ (void)__wcdb_column_constraint_39:(void *)a0;
+ (const void *)ss_createTime;
+ (id)swift_ss_createTime;
+ (const void *)__wcdb_synthesize_25:(void *)a0;
+ (const void *)ss_blockStatus;
+ (const void *)__wcdb_synthesize_27:(void *)a0;
+ (const void *)__wcdb_synthesize_29:(void *)a0;
+ (const void *)__wcdb_synthesize_31:(void *)a0;
+ (const void *)__wcdb_synthesize_33:(void *)a0;
+ (const void *)__wcdb_synthesize_35:(void *)a0;
+ (id)swift_ss_blockStatus;
+ (const void *)ss_belongingConversationIdentifier;
+ (id)swift_ss_belongingConversationIdentifier;
+ (const void *)infoVersion;
+ (const void *)ss_infoVersion;
+ (const void *)ss_desc;
+ (const void *)ss_icon;
+ (const void *)ss_notice;
+ (const void *)ss_ownerID;
+ (const void *)ss_rootMessageId;
+ (const void *)ss_parentConvShortId;
+ (const void *)ss_rootClientMessageId;
+ (const void *)ss_mode;
+ (const void *)ss_creatorUid;
+ (const void *)ss_blockSource;
+ (const void *)ss_leftBlockTime;
+ (const void *)ss_blockNormalOnly;
+ (const void *)parentConvShortId;
+ (id)swift_ss_infoVersion;
+ (id)swift_ss_desc;
+ (id)swift_ss_icon;
+ (id)swift_ss_notice;
+ (id)swift_ss_ownerID;
+ (id)swift_ss_rootMessageId;
+ (id)swift_ss_parentConvShortId;
+ (id)swift_ss_rootClientMessageId;
+ (id)swift_ss_mode;
+ (id)swift_ss_creatorUid;
+ (id)swift_ss_blockSource;
+ (id)swift_ss_leftBlockTime;
+ (id)swift_ss_blockNormalOnly;
+ (const void *)desc;
+ (const void *)icon;
+ (const void *)createTime;
+ (const void *)name;
+ (const void *)allProperties;
+ (const void *)mode;
+ (const void *)notice;
+ (const void *)ownerID;
+ (const void *)ext;

- (BOOL)isEqualToAnotherOne:(id)a0;
- (void)setupPropertyWithPBModel:(id)a0;
- (void).cxx_destruct;
- (void)addObserver:(id)a0 forKeyPath:(id)a1 options:(unsigned long long)a2 context:(void *)a3;
- (void)removeObserver:(id)a0 forKeyPath:(id)a1 context:(void *)a2;
- (id)initWithRootObject:(id)a0;

@end
