@class NSMutableDictionary, NSString, NSArray, TTAccountCustomLoginConfiguration, NSObject;
@protocol OS_dispatch_queue, TTAccountSDKSetupProtocol, TTAccountMessageFirstResponder;

@interface TTAccountConfiguration : NSObject {
    NSObject<OS_dispatch_queue> *_readWriteQueue;
    struct _opaque_pthread_rwlock_t { long long __sig; char __opaque[192]; } _addtionalTokenDominsReadWriteLock;
    struct _opaque_pthread_rwlock_t { long long __sig; char __opaque[192]; } _needTokenDominsReadWriteLock;
}

@property (nonatomic) BOOL disableChainLogin;
@property (nonatomic) BOOL isProviderForChainLogin;
@property (nonatomic) BOOL shouldAutoHandleUserInfoForChainLogin;
@property (readonly, nonatomic) TTAccountCustomLoginConfiguration *wapLoginConf;
@property (retain, nonatomic) NSMutableDictionary *extraNetworkParams;
@property (retain, nonatomic) id<TTAccountSDKSetupProtocol> setupConfig;
@property (copy, nonatomic) id /* block */ networkParamsHandler;
@property (copy) id /* block */ appRequiredParamsHandler;
@property (copy, nonatomic) id /* block */ jsbNetworkParamsHandler;
@property (nonatomic) BOOL multiThreadSafeEnabled;
@property (copy, nonatomic) NSString *sharingKeyChainGroup;
@property (nonatomic) BOOL unbindAlertEnabled;
@property (nonatomic) BOOL byFindPasswordLoginEnabled;
@property (copy, nonatomic) NSString *domain;
@property (retain, nonatomic) NSObject<TTAccountMessageFirstResponder> *accountMessageFirstResponder;
@property (copy, nonatomic) id /* block */ visibleViewControllerHandler;
@property (nonatomic) BOOL isSupportMutilLogin;
@property (nonatomic) BOOL isBoe;
@property (copy, nonatomic) NSString *unbindThirdPartyURLPath;
@property (nonatomic) BOOL autoSynchronizeUserInfo;
@property (copy, nonatomic) NSString *userInfoURLPath;
@property (copy, nonatomic) NSArray *needTokenDomins;
@property (copy, nonatomic) NSArray *addtionalTokenDomins;
@property (nonatomic) BOOL isXTTTokenActive;
@property (nonatomic) BOOL shouldShareTokeInShareCookieHostList;
@property (nonatomic) BOOL shouldTrackNoTokenRequest;
@property (nonatomic) long long tokenPollingInterveral;
@property (nonatomic) BOOL openCacheLoginInfo;
@property (copy, nonatomic) NSString *mobileSeparator;
@property (nonatomic) BOOL enableNetNotParse;
@property (copy) NSArray *configLoginPaths;
@property (copy) NSArray *configLogoutPaths;
@property (nonatomic) BOOL shouldStrategyRecordNotClearWhenLogin;
@property (nonatomic) BOOL shouldCallbackWhenVerifyFail;
@property (nonatomic) BOOL disableBDTuringInterface;
@property (nonatomic) BOOL enableXTokenFilterSetup;
@property (nonatomic) BOOL enableErrorInterceptHandler;
@property (nonatomic) BOOL enableUserInfoLoadOptimize;
@property (nonatomic) BOOL enableAccessTokenGuard;
@property (nonatomic) BOOL showSessionExpiredAlert;
@property (nonatomic) long long customRequestCommonParams;
@property (readonly, nonatomic) BOOL enableHeaderSessionId;
@property (nonatomic) BOOL enableCheckDeviceTransfer;

+ (id)tta_defaultURLParameters;
+ (id)tta_appBundleID;

- (void)addExtraNetworkParams:(id)a0;
- (id)tta_commonNetworkParameters;
- (id)tta_sharingKeyChainGroup;
- (id)addExtraNetworkCommonParams:(id)a0;
- (void)trackSetExtraNetworkParams:(id)a0;
- (id /* block */)p_networkParamsHandler;
- (id)readExtraNetworkParams;
- (id /* block */)p_visibleViewControllerHandler;
- (id)tta_installID;
- (id)tta_currentViewController;
- (id)tta_ssAppID;
- (id)tta_ssMID;
- (id)tta_jsbNetworkParameters;
- (id)tta_deviceID;
- (id)tta_appRequiredParameters;
- (id)tta_platformAppDisplayNameForPlatformType:(long long)a0;
- (id)tta_platformAppInstallUrlForPlatformType:(long long)a0;
- (id)tta_platformAppIdForPlatformType:(long long)a0;
- (id)tta_platformAppNameForPlatformType:(long long)a0;
- (id)tta_platformConfigurationForType:(long long)a0;
- (id)tta_consumerKeyForPlatformType:(long long)a0;
- (id)tta_redirectURLForPlatformType:(long long)a0;
- (id)tta_permissionsForPlatformType:(long long)a0;
- (id)tta_additionalPermissionsForPlatformType:(long long)a0;
- (id)tta_universalLinkForPlatformType:(long long)a0;
- (void)addPlatformConfiguration:(id)a0;
- (void)addPlatformConfigurations:(id)a0;
- (BOOL)tta_tryCustomWAPLoginWhenSDKFailureForPlatformType:(long long)a0;
- (id)platformConfigurations;
- (void)setWapLoginConf:(id)a0;
- (id)__platformConfigurationForType:(long long)a0;
- (id)tta_consumerSecretForPlatformType:(long long)a0;
- (BOOL)tta_isShareUserInfoForPlatformType:(long long)a0;
- (id)tta_authSchemeCallbackURLForPlatformType:(long long)a0;
- (id)tta_scopeForPlatformType:(long long)a0;
- (void)tta_laziedRegisterPlatformAppIDForPlatformType:(long long)a0;
- (BOOL)tta_useDefaultWAPLoginForPlatformType:(long long)a0;
- (BOOL)tta_SNSBarHiddenForPlatformType:(long long)a0;
- (id)tta_SNSBarTextForPlatformType:(long long)a0;
- (id)tta_platformAppInstalledSchemesForPlatformType:(long long)a0;
- (id)tta_platformAppSupportedSchemesForPlatformType:(long long)a0;
- (id)tta_organizationIdForPlatformType:(long long)a0;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end
