@class NSString, NSArray, NSDictionary, NSNumber;

@interface TTAdSplashModel : NSObject <NSCoding, NSSecureCoding>

@property (class, readonly) BOOL supportsSecureCoding;

@property (nonatomic) unsigned long long adModelType;
@property (nonatomic) unsigned long long splashDisplayType;
@property (copy, nonatomic) NSString *splashAdId;
@property (nonatomic) double requestTimeInterval;
@property (copy, nonatomic) NSString *splashID;
@property (copy, nonatomic) NSString *logExtra;
@property (copy, nonatomic) NSString *adId;
@property (nonatomic) double serverAdStartTimeMs;
@property (copy, nonatomic) NSString *display_density;
@property (nonatomic) double displayTime;
@property (nonatomic) long long splashDisplayAfterSecond;
@property (nonatomic) long long splashExpireSeconds;
@property (copy, nonatomic) NSString *splashOpenURL;
@property (copy, nonatomic) NSString *splashActionType;
@property (copy, nonatomic) NSString *splashStyle;
@property (copy, nonatomic) NSString *splashSiteId;
@property (copy, nonatomic) NSString *splashDownloadURLStr;
@property (copy, nonatomic) NSString *splashAppName;
@property (copy, nonatomic) NSString *splashAppleID;
@property (copy, nonatomic) NSString *splashWebURLStr;
@property (copy, nonatomic) NSArray *splashWebUrlList;
@property (copy, nonatomic) NSString *splashWebTitle;
@property (nonatomic) unsigned long long mpPreloadPolicy;
@property (copy, nonatomic) NSString *splashMPURLStr;
@property (retain, nonatomic) NSArray *splashTrackURLStrings;
@property (retain, nonatomic) NSArray *splashClickTrackURLStrings;
@property (copy, nonatomic) NSString *weChatMPInfo;
@property (copy, nonatomic) NSDictionary *rawLiveInfo;
@property (copy, nonatomic) NSDictionary *imageInfo;
@property (retain, nonatomic) NSNumber *predownload;
@property (retain, nonatomic) NSNumber *splashBannerMode;
@property (retain, nonatomic) NSNumber *displaySkipButton;
@property (retain, nonatomic) NSNumber *skipButtonStyle;
@property (nonatomic) BOOL enableOpenType;
@property (copy, nonatomic) NSString *buttonText;
@property (nonatomic) long long buttonTextDisplayAfter;
@property (copy, nonatomic) NSString *appOpenURL;
@property (nonatomic) long long commerceType;
@property (nonatomic) long long showSoundTime;
@property (retain, nonatomic) NSArray *intervalCreatives;
@property (copy, nonatomic) NSArray *disableShowPeriods;
@property (nonatomic) long long launchType;
@property (nonatomic) BOOL repeats;
@property (retain, nonatomic) NSNumber *clickHeight;
@property (nonatomic) unsigned long long splashADType;
@property (nonatomic) BOOL isGif;
@property (copy, nonatomic) NSDictionary *videoInfo;
@property (copy, nonatomic) NSString *videoId;
@property (copy, nonatomic) NSString *videoGroupId;
@property (copy, nonatomic) NSArray *videoURLArray;
@property (copy, nonatomic) NSArray *videoPlayTrackURLArray;
@property (copy, nonatomic) NSArray *videoPlayOverTrackURLArray;
@property (copy, nonatomic) NSString *video_density;
@property (copy, nonatomic) NSString *videoSecretKey;
@property (copy, nonatomic) NSNumber *isH265;
@property (nonatomic) double loadTime;
@property (nonatomic) BOOL isRemoteVideo;
@property (copy, nonatomic) NSDictionary *fallbackInfo;
@property (nonatomic) BOOL useFallbackInfo;
@property (copy, nonatomic) NSDictionary *logoInfo;
@property (copy, nonatomic) NSDictionary *skipInfo;
@property (copy, nonatomic) NSDictionary *labelInfo;
@property (copy, nonatomic) NSString *predownloadText;
@property (copy, nonatomic) NSString *action;
@property (copy, nonatomic) NSDictionary *shakeStyleInfo;
@property (nonatomic) BOOL enablePreRenderWeb;
@property (copy, nonatomic) NSDictionary *clickArea;
@property (copy, nonatomic) NSDictionary *hotSplashFilterInfo;
@property (copy, nonatomic) NSDictionary *complianceArea;
@property (copy, nonatomic) NSDictionary *demotionArea;
@property (nonatomic) long long modelType;
@property (nonatomic) long long resourceLoadType;
@property (copy, nonatomic) NSString *splashExtra;
@property (copy, nonatomic) NSString *readingInfo;
@property (nonatomic) long long themeStyle;
@property (copy, nonatomic) NSDictionary *splashModuleInfo;
@property (copy, nonatomic) NSDictionary *splashBackgroundInfo;
@property (copy, nonatomic) NSDictionary *materialArea;
@property (copy, nonatomic) NSDictionary *bdsInfo;
@property (nonatomic) long long adPlatform;
@property (nonatomic) long long advanceType;
@property (nonatomic) BOOL useGoodsDetail;
@property (copy, nonatomic) NSString *brandPrizeInfo;
@property (nonatomic) long long forceRealtime;
@property (copy, nonatomic) NSArray *periodList;
@property (nonatomic) long long isRealtime;
@property (nonatomic) BOOL isMarket;
@property (copy, nonatomic) NSDictionary *floatLayerData;
@property (copy, nonatomic) NSString *shareTitle;
@property (copy, nonatomic) NSString *shareUrl;
@property (copy, nonatomic) NSString *shareCoverUrl;
@property (copy, nonatomic) NSString *shareDesc;
@property (copy, nonatomic) NSString *splashURLString;
@property (retain, nonatomic) NSNumber *splashHideIfExist;
@property (copy, nonatomic) NSString *adLandingPageStyle;
@property (retain, nonatomic) NSNumber *adInterceptFlag;
@property (retain, nonatomic) NSNumber *showExpected;
@property (copy, nonatomic) NSDictionary *promotionIcon;
@property (copy, nonatomic) NSDictionary *vastInfo;
@property (nonatomic) long long adStyle;
@property (copy, nonatomic) NSDictionary *adVerifications;
@property (nonatomic) long long liveStatus;
@property (copy, nonatomic) NSString *rawAdData;
@property (retain, nonatomic) NSString *realTimeLogExtra;
@property (nonatomic) BOOL useRealTime;
@property (nonatomic) long long errorCode;
@property (nonatomic) BOOL isRetrieval;
@property (nonatomic) long long preloadWeb;
@property (retain, nonatomic) NSNumber *repeatTimes;
@property (nonatomic) unsigned long long logoColor;
@property (copy, nonatomic) NSString *skanProductParams;
@property (nonatomic) BOOL isAutoRefresh;
@property (nonatomic) unsigned long long stopShowType;
@property (nonatomic) long long status;
@property (nonatomic) BOOL topviewTraceSplashChain;

+ (BOOL)propertyIsOptional:(id)a0;

- (id)getPreloadMPAppList;
- (id)adWebPrelodChannelId;
- (BOOL)isVideoRelatedAdType;
- (id)intervalCreativesWithData:(id)a0;
- (void)setDefaultValuesWithRequestTime:(double)a0;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)a0;
- (struct CGSize { double x0; double x1; })imageSize;
- (id)initWithCoder:(id)a0;
- (id)initWithDictionary:(id)a0;
- (struct CGSize { double x0; double x1; })videoSize;

@end
