@class NSString, NSMutableDictionary, NSDictionary, TTVideoEngineMDLTrackInfo;
@protocol TTVideoEngineEventLoggerDelegate;

@interface TTVideoEngineEventBase : NSObject

@property (weak, nonatomic) id<TTVideoEngineEventLoggerDelegate> delegate;
@property (retain, nonatomic) NSMutableDictionary *videoInfo;
@property (copy, nonatomic) NSString *session_id;
@property (copy, nonatomic) NSString *device_id;
@property (copy, nonatomic) NSString *sv;
@property (copy, nonatomic) NSString *pv;
@property (copy, nonatomic) NSString *pc;
@property (copy, nonatomic) NSString *sdk_version;
@property (copy, nonatomic) NSString *vid;
@property (copy, nonatomic) NSString *source_type;
@property (copy, nonatomic) NSString *tag;
@property (copy, nonatomic) NSString *subtag;
@property (copy, nonatomic) NSString *lastResolution;
@property (copy, nonatomic) NSString *currentResolution;
@property (nonatomic) long long beginSwitchResolutionCurPos;
@property (nonatomic) unsigned long long beginSwitchResolutionTime;
@property (copy, nonatomic) NSString *initialQualityDesc;
@property (copy, nonatomic) NSString *currentQualityDesc;
@property (copy, nonatomic) NSString *initial_ip;
@property (copy, nonatomic) NSString *initial_resolution;
@property (copy, nonatomic) NSString *curURL;
@property (copy, nonatomic) NSString *initialURL;
@property (copy, nonatomic) NSString *internal_ip;
@property (nonatomic) long long drm_type;
@property (copy, nonatomic) NSString *drm_token_url;
@property (nonatomic) long long play_type;
@property (nonatomic) long long audio_codec_nameId;
@property (nonatomic) long long video_codec_nameId;
@property (nonatomic) long long format_type;
@property (nonatomic) BOOL hw;
@property (nonatomic) BOOL hw_user;
@property (nonatomic) double playSpeed;
@property (nonatomic) long long reuse_socket;
@property (retain, nonatomic) NSDictionary *abr_info;
@property (nonatomic) BOOL isEnableABR;
@property (retain, nonatomic) NSString *vtype;
@property (nonatomic) long long video_stream_duration;
@property (nonatomic) long long audio_stream_duration;
@property (nonatomic) unsigned long long lastForebackSwitchTime;
@property (nonatomic) unsigned long long lastAVSwitchTime;
@property (nonatomic) unsigned long long lastResSwitchTime;
@property (nonatomic) unsigned long long lastHeadsetSwithTime;
@property (nonatomic) long long isInBackground;
@property (nonatomic) long long radioMode;
@property (nonatomic) long long curHeadset;
@property (nonatomic) long long blueTooth;
@property (copy, nonatomic) NSDictionary *r_stage_errcs;
@property (nonatomic) BOOL has_get_preload_traceid;
@property (nonatomic) BOOL hasAudioTrackInfo;
@property (nonatomic) long long mdl_cur_req_pos;
@property (nonatomic) long long mdl_cur_end_pos;
@property (nonatomic) long long mdl_cur_cache_pos;
@property (nonatomic) long long mdl_cache_type;
@property (copy, nonatomic) NSString *mdl_cur_ip;
@property (copy, nonatomic) NSString *mdl_cur_host;
@property (copy, nonatomic) NSString *mdl_cur_url;
@property (nonatomic) long long mdl_reply_size;
@property (nonatomic) long long mdl_down_pos;
@property (nonatomic) long long mdl_player_wait_time;
@property (nonatomic) long long mdl_player_wait_num;
@property (nonatomic) long long mdl_stage;
@property (nonatomic) long long mdl_error_code;
@property (nonatomic) long long mdl_sub_error_code;
@property (nonatomic) long long mdl_cur_task_num;
@property (nonatomic) int mdl_conc_count;
@property (nonatomic) long long mdl_speed;
@property (copy, nonatomic) NSString *mdl_file_key;
@property (nonatomic) long long mdl_is_socrf;
@property (nonatomic) long long mdl_req_num;
@property (nonatomic) long long mdl_url_index;
@property (copy, nonatomic) NSString *mdl_re_url;
@property (nonatomic) long long mdl_cur_soure;
@property (copy, nonatomic) NSString *mdl_extra_info;
@property (nonatomic) long long mdl_http_code;
@property (nonatomic) long long mdl_req_t;
@property (nonatomic) long long mdl_end_t;
@property (nonatomic) long long mdl_dns_t;
@property (nonatomic) long long mdl_tcp_start_t;
@property (nonatomic) long long mdl_tcp_end_t;
@property (nonatomic) long long mdl_ttfp;
@property (nonatomic) long long mdl_httpfb;
@property (nonatomic) long long mdl_http_open_end_t;
@property (nonatomic) long long mdl_fs;
@property (nonatomic) long long mdl_pcdn_full_speed;
@property (nonatomic) long long mdl_tbs;
@property (nonatomic) long long mdl_lbs;
@property (nonatomic) long long mdl_res_err;
@property (nonatomic) long long mdl_read_src;
@property (nonatomic) long long mdl_seek_num;
@property (copy, nonatomic) NSString *mdl_last_msg;
@property (copy, nonatomic) NSString *mdl_server_timing;
@property (nonatomic) long long mdl_v_lt;
@property (nonatomic) long long mdl_v_p2p_ier;
@property (copy, nonatomic) NSString *mdl_ip_list;
@property (copy, nonatomic) NSString *mdl_blocked_ips;
@property (copy, nonatomic) NSString *mdl_response_cinfo;
@property (copy, nonatomic) NSString *mdl_response_cache;
@property (copy, nonatomic) NSString *mdl_dns_type;
@property (nonatomic) long long mdl_p2p_loader;
@property (copy) NSDictionary *mdl_features;
@property (retain, nonatomic) TTVideoEngineMDLTrackInfo *mdlAudioInfo;
@property (retain, nonatomic) TTVideoEngineMDLTrackInfo *mdlVideoInfo;

+ (id)generateSessionID:(id)a0;

- (id)getNetworkType;
- (void)updateMDLInfo;
- (id)generateTraceID:(id)a0;
- (void)updateMdlFeatures:(id)a0;
- (void)initPlay:(id)a0 traceId:(id)a1;
- (void)beginToPlay:(id)a0;
- (void)updateVersionInfo;
- (void).cxx_destruct;
- (id)init;

@end
