@class AVCaptureVideoPreviewLayer, NSObject, AVCaptureStillImageOutput, NSMutableString, AVCaptureDevice, CameraScannerViewSwitchOpt, AVCaptureDeviceInput, NSString, CameraScannerViewBlackOpt, MMTimer, AVCaptureVideoDataOutput, NSRecursiveLock, AVCaptureSession;
@protocol OS_dispatch_queue, CameraScannerViewDelegate;

@interface CameraScannerView : MMUIView <AVCaptureVideoDataOutputSampleBufferDelegate> {
    BOOL _currentOpenAutoSwitchCamera;
    AVCaptureDeviceInput *_captureInput;
    AVCaptureVideoDataOutput *_captureOutput;
    AVCaptureDevice *_captureDevice;
    MMTimer *_lowLightCheckTimer;
    MMTimer *_firstCenterFocusTimer;
    MMTimer *_centerFocusTimer;
    BOOL _shouldCheckLowLight;
    BOOL _isLowLight;
    BOOL _isLightBoostOn;
    struct CGPoint { double x; double y; } _focusPoint;
    BOOL _observingFocus;
    BOOL _hasFocused;
    NSObject<OS_dispatch_queue> *_sessionQueue;
    float _compareBrightness;
    AVCaptureStillImageOutput *_imageOutput;
    BOOL _isTakingPic;
    BOOL _shouldStopScan;
    long long _initErrorType;
}

@property (nonatomic) BOOL stopTimerCheck;
@property (retain, nonatomic) CameraScannerViewSwitchOpt *switchOpt;
@property (nonatomic) BOOL useNewUI;
@property (nonatomic) long long cameraStatus;
@property (nonatomic) BOOL hasTimelineObserver;
@property (nonatomic) BOOL hasReportCameraStatus;
@property (retain, nonatomic) CameraScannerViewBlackOpt *blackOpt;
@property struct CGPoint { double x; double y; } lastestFocusPoint;
@property (nonatomic) BOOL isActiveFocus;
@property (nonatomic) BOOL hasReportCameraRebootStatus;
@property (readonly, nonatomic) AVCaptureSession *captureSession;
@property (readonly, nonatomic) AVCaptureVideoPreviewLayer *prevLayer;
@property (readonly, nonatomic) NSRecursiveLock *cameraLock;
@property (weak, nonatomic) id<CameraScannerViewDelegate> delegate;
@property (readonly, nonatomic) BOOL hasInit;
@property BOOL hasCaptureOutput;
@property (readonly, nonatomic) NSMutableString *zoomOplog;
@property (readonly, nonatomic) unsigned int lightMode;
@property (nonatomic) BOOL currentDeviceIsUltraWideAngleCamera;
@property (nonatomic) float cameraDefaultZoomFactor;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)sharedInstance;
+ (void)stopInstanceIfNeed;
+ (void)releaseInstance;

- (void)stopCaptureSessionRunning;
- (void)addAutoFocusObserverForCaptureDevice;
- (void)removeAutoFocusObserverForCaptureDevice;
- (id)init;
- (void)dealloc;
- (void)cleanupAVSession;
- (id)captureDevice;
- (void)layoutSubviews;
- (void)adjustToNewSize:(double)a0;
- (float)getRotateRadius:(long long)a0;
- (BOOL)isUsingFrontCamera;
- (long long)diagnoseCamera;
- (void)diagnoseReport:(long long)a0;
- (void)diagnoseReportReboot:(long long)a0;
- (id)getCaptureDeviceWithAutoSwitchCamera:(BOOL)a0;
- (id)defaultCaptureDevice;
- (void)initCaptureWithPreviewScale:(float)a0 isPortrait:(BOOL)a1;
- (void)initCaptureWithPreviewScale:(float)a0 isPortrait:(BOOL)a1 enableAutoSwitchCamera:(BOOL)a2;
- (void)initCaptureWithPreviewScale:(float)a0 enableAutoSwitchCamera:(BOOL)a1;
- (void)captureOutput:(id)a0 didOutputSampleBuffer:(struct opaqueCMSampleBuffer { } *)a1 fromConnection:(id)a2;
- (BOOL)isUsingUltraWideAngleCamera;
- (unsigned int)getLensType;
- (double)getLastLenPosition;
- (BOOL)isUsingLensCheck;
- (void)checkAutoSwitchCamera;
- (void)checkInitDefaultZoomFactor;
- (double)defaultZoomFactor;
- (double)maxZoomFactor;
- (BOOL)isCurrentOpenAutoSwitchCamera;
- (BOOL)enableScanAutoSwitchCameraWhenFocusing:(long long)a0;
- (double)autoSwitchingScanCameraLensPosition;
- (void)showTorchButtonWithSeconds:(unsigned int)a0;
- (long long)getDeviceOrientation:(long long)a0;
- (void)takePicturWithCompletion:(id /* block */)a0;
- (void)onCaptureTimeout;
- (void)setPreviewScale:(float)a0;
- (void)start;
- (void)stop;
- (void)startTimerCheckLowLight;
- (BOOL)enableFocusOpt;
- (BOOL)isFocusSimpleMode;
- (void)startTimerCenterFocus;
- (void)onCenterFocusInternalFirst;
- (void)onCenterFocusInternal;
- (void)updateFocusPoint:(struct CGPoint { double x0; double x1; })a0;
- (BOOL)hasActiveFocus;
- (void)onCenterFocus:(struct CGPoint { double x0; double x1; })a0;
- (void)stopTimerCenterFocus;
- (void)onTimerCheckLowLight;
- (void)stopTimerCheckLowLight;
- (void)tryRemoveFocusObserver;
- (void)addFocusObserver;
- (void)addCaptureSessionObserver;
- (void)removeCaptureSessionObserver;
- (void)captureSessionRuntimeError:(id)a0;
- (void)captureSessionDidStartRunning:(id)a0;
- (void)captureSessionDidStopRunning:(id)a0;
- (void)captureSessionWasInterrupted:(id)a0;
- (void)captureSessionInterruptionEnded:(id)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })convertToPortraitRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (struct CGPoint { double x0; double x1; })convertToPortraitPoint:(struct CGPoint { double x0; double x1; })a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })convertPortraitToCameraRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (struct CGPoint { double x0; double x1; })convertDevicePointToPortraitPoint:(struct CGPoint { double x0; double x1; })a0;
- (struct CGPoint { double x0; double x1; })pointToCaptureDevice:(struct CGPoint { double x0; double x1; })a0;
- (float)getRotateDegreeRelativeToCamera;
- (long long)getImageOrientationToCamera;
- (void)continuousFocusAtPoint:(struct CGPoint { double x0; double x1; })a0;
- (void)continuousExposureAtPoint:(struct CGPoint { double x0; double x1; })a0;
- (void)observeValueForKeyPath:(id)a0 ofObject:(id)a1 change:(id)a2 context:(void *)a3;
- (void)onTimerFocus;
- (void)setLightBoostOn:(BOOL)a0;
- (BOOL)innerSetLightBoostOn:(BOOL)a0;
- (double)getZoomFactor;
- (void)setDefaultZoomFactor;
- (void)setZoomFactor:(double)a0 animated:(BOOL)a1;
- (void)setZoomFactor:(double)a0 ignoreLimit:(BOOL)a1 animated:(BOOL)a2;
- (void)addZoomFactorLog:(double)a0 manually:(BOOL)a1;
- (void)clearLog;
- (void)setupReportTimerWhenStartScan;
- (void)cancelReportTimer;
- (void)reportOnNotRecieveBufferForShotTerm;
- (void)reportOnNotRecieveBufferForLongTerm;
- (void)addCameraTimelineObserver;
- (void)removeCameraTimelineObserver;
- (void)diagnoseNoBuffer;
- (void)addLifetimeObserver;
- (void)removeLifetimeObserver;
- (void)onEnterBackground:(id)a0;
- (void)onEnterForegound:(id)a0;
- (void)recover;
- (void)cleanupCaptureSession;
- (void)setupCaptureSession;
- (void).cxx_destruct;

@end
