@class UIView, UILabel, CameraScanBlurButtonWrapView, NSString, CameraScanCombineContentView, UIImageView, CameraScanCodesCenterDotView, CAAnimationGroup, NSMutableArray, CABasicAnimation, ImageFitWithBlurredBackgroundView, MMUIButton;
@protocol CameraScanCodesContentViewDelegate;

@interface CameraScanCodesContentView : CameraScanBaseContentView <CAAnimationDelegate, CameraScanCombineContentViewDelegate> {
    BOOL m_bShowMyQRCode;
    BOOL m_bInfoLabelNeedShowAgain;
}

@property (retain, nonatomic) UIImageView *scanCropImageView;
@property (retain, nonatomic) UIImageView *scanLineView;
@property (retain, nonatomic) NSMutableArray *markDotViewList;
@property (retain, nonatomic) CameraScanCodesCenterDotView *centerDotView;
@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UILabel *subtitleLabel;
@property (retain, nonatomic) ImageFitWithBlurredBackgroundView *snapshotImageView;
@property (retain, nonatomic) UIView *codeMaskView;
@property (retain, nonatomic) MMUIButton *cancelButton;
@property (retain, nonatomic) CAAnimationGroup *scanLineAnimation;
@property (nonatomic) BOOL isMaskViewShow;
@property (retain, nonatomic) CABasicAnimation *maskViewAnimation;
@property (nonatomic) BOOL isEnableCombineTab;
@property (nonatomic) BOOL isUseSmallCropArea;
@property (nonatomic) BOOL isMultiCodes;
@property (nonatomic) double scanLineTopCenterY;
@property (nonatomic) double scanLineBottomCenterY;
@property (nonatomic) BOOL isShowErrorView;
@property (nonatomic) BOOL isHandlingMultiCodes;
@property (nonatomic) BOOL isShowScanGoodsGuide;
@property (nonatomic) BOOL isShowTipsIKnow;
@property (retain, nonatomic) MMUIButton *tryScanGoodsButton;
@property (retain, nonatomic) MMUIButton *tipsIKnowButton;
@property (retain, nonatomic) CameraScanCombineContentView *goodCombineView;
@property (weak, nonatomic) id<CameraScanCodesContentViewDelegate> delegate;
@property (retain, nonatomic) CameraScanBlurButtonWrapView *myQRButtonWrapView;
@property (nonatomic) unsigned long long selectedIdx;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithIsUseSmallCropArea:(BOOL)a0 bShowMyQRCode:(BOOL)a1 bEnableCombineTab:(BOOL)a2;
- (void)setupSubViews;
- (id)centerTabTitle;
- (void)setCloseButtonBottom:(double)a0 infoLableTop:(double)a1;
- (void)setScanCropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)setupScanCropImageView;
- (void)setupScanLineView;
- (void)setupSnapshotImageView;
- (void)setupMaskView;
- (void)setupCenterDotView;
- (void)setupTitleLabel;
- (void)setupSubtitleLabel;
- (void)setupCancelButton;
- (void)setupMyQRButton;
- (void)setupTryScanGoodsButton;
- (void)setupTipsIKnowButton;
- (void)setupMaskViewAnimation;
- (void)layoutSubviews;
- (void)markDotViewsStartShowAnimation;
- (void)markDotViewsStartBreatheAnimation;
- (void)markDotViewsStopAllAnimations;
- (void)markDotViewsRemoveFromSuperview;
- (void)markDotViewsCleanUpNonSelectedItems;
- (void)maskViewsShowWithAnimation:(BOOL)a0;
- (void)maskViewsHidden;
- (void)animationDidStop:(id)a0 finished:(BOOL)a1;
- (void)updateMarkDotInfoList:(id)a0;
- (void)updateScanGoodsGuide:(id)a0;
- (id)currSelectedMarkDotView;
- (void)startScanLineAnimation;
- (void)stopScanLineAnimation;
- (void)startLoadingDotAnimation;
- (void)stopLoadingDotAnimation;
- (void)startHandleMultiCodes;
- (void)stopHandleMultiCodes;
- (void)resetMultiCodesModify:(BOOL)a0;
- (void)resetScanGoodsGuide;
- (void)resetTipsIKnow;
- (void)resetNetStatusModiy;
- (void)resetWhenStartScan;
- (void)showSnapshotImage:(id)a0;
- (void)hideSnapshotImage;
- (void)showNetDisconnectWithSubtitle:(BOOL)a0;
- (void)showNetTimeout;
- (void)showScanGoodsGuide:(id)a0;
- (void)showTipsIKnow;
- (BOOL)isCollisionWithAnyMarkDotView;
- (BOOL)tapInCancelButton:(id)a0;
- (void)setupGoodCombineAttachView;
- (id)goodCombineContentView;
- (double)getMyQRCodeButtonY;
- (void)onCombineContentViewStarMarkingAnimation;
- (void)onStartScanAlbumLoading;
- (void)onStopScanAlbumLoading;
- (void)onCancelBtnClicked:(id)a0;
- (void)onMyQRBtnClicked:(id)a0;
- (void)onTryScanGoodsBtnClicked:(id)a0;
- (void)onTipsIKnowBtnClicked:(id)a0;
- (double)getContentBottomMargin;
- (double)getWidthBetweenAlbumButtonAndMyQRCodeButton;
- (void)onAddItemFromDetectorsWithItemViewModel:(id)a0 index:(unsigned long long)a1;
- (void)onClikcItemCardWithItemViewModel:(id)a0 index:(unsigned long long)a1;
- (void)onExposeWithItem:(id)a0 hasTitle:(BOOL)a1;
- (double)getContentBottomMarginToTabView;
- (void)listViewWillFold:(BOOL)a0;
- (void)listViewDidFold:(BOOL)a0;
- (void)onListViewWillStartDragging;
- (void)onListViewWillEndDragging;
- (void)callSetupHoleMaskViewWithHoleFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void).cxx_destruct;

@end
