@class EmoticonLensInfo, EmoticonLensDesignerView, EditImageAnimatedEmoticonTool, StreamVoiceInputLogic, AVCaptureSession, NSString, EmoticonCameraResultView, AVCaptureDevice, MMUIButton, EmoticonCameraPreviewView, MMSightRecordHelperView, EditImageColor, XEffectEffectManager, NSObject, EmoticonEmptyEditView, UIView, MMCircularProgressView, EmoticonLensDynamicToolView, UIImageView, EmoticonCameraReportObject, EmoticonLensDynamicTipView, MMSightRecordView, EmoticonLensPackage, AVCaptureVideoDataOutput, EmoticonCameraToolBar, EditImageAnimatedTextTool;
@protocol OS_dispatch_queue, EmoticonCameraDelegate;

@interface EmoticonCameraViewController : MMUIViewController <AVCaptureVideoDataOutputSampleBufferDelegate, AVCaptureAudioDataOutputSampleBufferDelegate, MMSightRecordHelperViewDelegate, EmoticonCameraResultViewDelegate, EditImageAnimatedOperationDelegate, EditImageAnimatedDelegate, EmoticonEmptyEditViewGestureDelegate, IStreamVoiceInputExt, MonoServiceLogicExt, ISysCallCheckExt, EmoticonLensDynamicToolViewDelegate, EmoticonLensMoreViewDelegate, EmoticonLensMgrExt, EmoticonLensDesignerViewDelegate> {
    EmoticonCameraToolBar *m_toolBar;
    MMUIButton *m_hideBarBtn;
    MMUIButton *m_cameraSwitchBtn;
    MMUIButton *m_photoBtn;
    UIImageView *m_audioRecordView;
    MMSightRecordHelperView *m_recordHelperView;
    MMCircularProgressView *m_circleProgress;
    MMSightRecordView *m_recordButtonView;
    EmoticonCameraResultView *m_resultView;
    BOOL m_needFocusCenter;
    double m_lastScaleFactor;
    StreamVoiceInputLogic *m_inputLogic;
    unsigned long long m_currentInputId;
    NSString *m_lastVoiceInputResult;
    UIView *m_maskView;
    UIView *m_frontView;
    EmoticonEmptyEditView *m_editImageView;
    EditImageAnimatedEmoticonTool *m_editImageEmoticonView;
    EditImageAnimatedTextTool *m_editImageTextView;
    EmoticonLensDynamicToolView *m_emoticonLensDynamicToolBar;
    EmoticonLensInfo *m_currentSelectedEmoticonLens;
    EditImageColor *m_defaultCaptionColor;
}

@property (nonatomic) BOOL hasSetEffect;
@property (retain, nonatomic) XEffectEffectManager *effectManager;
@property (retain, nonatomic) EmoticonCameraPreviewView *previewView;
@property (retain, nonatomic) EmoticonLensDesignerView *designerView;
@property (retain, nonatomic) EmoticonLensDynamicTipView *lensActionTipView;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *captureQueue;
@property (retain, nonatomic) AVCaptureDevice *cameraDevice;
@property (retain, nonatomic) AVCaptureSession *captureSession;
@property (retain, nonatomic) AVCaptureVideoDataOutput *videoDataOutput;
@property (retain, nonatomic) NSString *caption;
@property (retain, nonatomic) EditImageColor *captionColor;
@property BOOL isGPUFrozen;
@property (nonatomic) BOOL enableNewYearPendant;
@property (retain, nonatomic) EmoticonLensPackage *currLensPackage;
@property (retain, nonatomic) EmoticonLensInfo *followLensInfo;
@property (weak, nonatomic) id<EmoticonCameraDelegate> delegate;
@property (retain, nonatomic) NSString *followMd5;
@property (retain, nonatomic) NSString *followCaption;
@property (retain, nonatomic) NSString *followCaptionColor;
@property (retain, nonatomic) NSString *followLensId;
@property (nonatomic) unsigned long long scene;
@property (retain, nonatomic) NSString *username;
@property (retain, nonatomic) EmoticonCameraReportObject *reportObject;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)dealloc;
- (void)viewDidLoad;
- (BOOL)useTransparentNavibar;
- (void)configGesture;
- (void)resetEffectManager;
- (void)configToolBar;
- (void)configEmoticonLensDynamicTool;
- (void)updateLensSelection;
- (void)configLensFollow;
- (void)configPreviewView;
- (void)configMaskView;
- (void)updateCameraAccessibility;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (float)sightCaptureMaxDuration;
- (void)showTips:(id)a0;
- (void)close;
- (void)cameraButtonPressed;
- (void)btnRelease;
- (void)openKitChen:(id)a0;
- (void)setZoomFactor:(double)a0;
- (void)focusAtPoint:(struct CGPoint { double x0; double x1; })a0;
- (void)focusCenter;
- (void)interruptRecord;
- (void)onEndInterruption;
- (void)handleFocusTap:(id)a0;
- (void)handleDoubleTap:(id)a0;
- (void)handlePinchGesture:(id)a0;
- (void)didEnterBackground;
- (void)didBecomeActive;
- (void)setupCameraDevice:(long long)a0;
- (id)privateCaption;
- (id)privateCaptionColor;
- (void)refreshEditImageTextView;
- (void)traitCollectionDidChange:(id)a0;
- (void)captureOutput:(id)a0 didOutputSampleBuffer:(struct opaqueCMSampleBuffer { } *)a1 fromConnection:(id)a2;
- (void)onRecordHelperViewTouchBegan:(id)a0;
- (void)onRecordHelperViewTouchMoved:(id)a0 point:(struct CGPoint { double x0; double x1; })a1;
- (void)onRecordHelperViewTouchEnded:(id)a0 shouldRecord:(BOOL)a1;
- (void)onRecordHelperViewStartRecord:(id)a0;
- (void)stopLoading;
- (void)onResultViewClickBack;
- (void)onResultViewClickDoneWithUploadInfo:(id)a0;
- (void)OnStartRecord:(unsigned int)a0;
- (void)OnEndRecord:(unsigned int)a0;
- (void)OnLevelMeter:(unsigned int)a0 Peak:(float)a1;
- (void)onGetResultText:(id)a0 andInputId:(unsigned int)a1;
- (void)OnError:(int)a0 andInputId:(unsigned int)a1;
- (void)OnVoiceTransEnd:(unsigned int)a0;
- (void)adjustEditImageAnimatedWidgetTool:(id)a0;
- (void)editImageViewDidStartDraw;
- (void)editImageViewdidEndDraw;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getAssetPreviewFrame;
- (void)didTapEmoticonEmptyEditView:(id)a0;
- (void)didPinchEmoticonEmptyEditView:(id)a0;
- (void)onMonoServiceVoipWillStart;
- (void)onMonoServiceMultitalkWillStart;
- (void)onMonoServiceWalkieTalkieWillStart;
- (void)onMonoServiceDidEnd;
- (void)BeginInterruption;
- (void)EndInterruption;
- (void)onEmoticonLensSelected:(id)a0;
- (void)onEmoticonLensShowAll;
- (void)doSelectedEmoticonLens:(id)a0;
- (void)onLensDidExposure:(id)a0;
- (void)moreLens:(id)a0 didSelectLens:(id)a1 isRecentUsed:(BOOL)a2;
- (void)moreLensViewWillClose:(id)a0;
- (void)moreLensViewDidShow:(id)a0;
- (void)moreLensViewDidExposure:(id)a0;
- (void)onEmoticonLensListRequestSuccess:(id)a0 isFirstPage:(BOOL)a1;
- (void)onEmoticonLensPkgDownloadSuccess:(id)a0;
- (void)onEmoticonLensRequestSuccess:(id)a0 forLensId:(id)a1;
- (void)onEmoticonLensInvalid:(id)a0 errType:(long long)a1;
- (void)onDesignerButtonSelected:(id)a0;
- (id)recordVideoPath;
- (id)getRecommendPassData;
- (void)reportLensExposureWithLensList:(id)a0 isFromRecommend:(BOOL)a1;
- (void).cxx_destruct;

@end
