@class ImageScrollView, NSDictionary, UIViewController, WXFullScreenGestureRecognizer, MMUILabel, ImageBrowseButton, UILabel, NSMutableArray, NSString, NSMutableSet, MMUIButton, MMLoadingIndicatorView, FileDetailLogicController, MiniRecTransitionController, UIButton, MMCircleProgressView, ShareDataToOpenSDKController, UIImageView, WKWebView, UIScrollView, NSURL, MMScrollActionSheet, UITapGestureRecognizer;
@protocol FileDetailViewControllerDelegate, FileDetailCustomizedPreviewController;

@interface FileDetailViewController : MMUIViewController <MMScrollActionSheetDelegate, RecentForwardScrollViewDelegate, FileDetailLogicDelegate, UIScrollViewDelegate, UIGestureRecognizerDelegate, WKNavigationDelegate, MMCircleProgressViewDelegate, MinimizationTransitionControllerDelegate, WAWxMaterialRefreshExt, FullScreenGestureDelegate> {
    FileDetailLogicController *m_logicController;
    BOOL m_bDownloading;
    BOOL m_bIsDelayingDownload;
    BOOL m_bFailDownload;
    UIScrollView *m_containerView;
    NSMutableArray *m_viewArray;
    NSMutableArray *m_defaultYArray;
    NSMutableSet *m_viewSet;
    UIButton *m_btnDownload;
    MMUILabel *m_labCannotOpen;
    UILabel *m_noSupportOpenLabel;
    UIButton *m_btnOpenByApp;
    UIButton *m_btnOpenRecentItemsSheet;
    UIButton *m_btnOpenByWeApp;
    UIImageView *m_fileTypeImage;
    MMUILabel *m_labelFileName;
    MMUILabel *m_sizeLabel;
    MMUILabel *m_infoLabel;
    MMUILabel *m_warningLabel;
    MMUILabel *m_stateLabel;
    UIButton *m_cancelBtn;
    UIImageView *m_downloadTriggerView;
    MMCircleProgressView *m_circleProgressView;
    BOOL m_bPreview;
    unsigned int m_uiPreviewType;
    BOOL m_vcDidAppear;
    ShareDataToOpenSDKController *m_shareOpenSDKController;
    WKWebView *m_webView;
    UIViewController<FileDetailCustomizedPreviewController> *m_customizedPreviewController;
    BOOL _bIsNaviBarHide;
    UITapGestureRecognizer *_singleTapRec;
    BOOL _bIsDisableTapRec;
    struct CGPoint { double x; double y; } m_lastContentOffset;
    UIButton *m_shareToFriendBtn;
    unsigned long long _startDownloadTime;
    unsigned long long _enterTime;
    unsigned long long _quitTime;
    unsigned long long _finishDownloadTime;
    NSURL *m_tmpLinkDestURL;
    WXFullScreenGestureRecognizer *m_gesture;
    ImageBrowseButton *_sessionSourceBtn;
    MMUIButton *_sessionContainerBtn;
}

@property (nonatomic) unsigned long long minimizeGenerateType;
@property (nonatomic) BOOL isPlayingAudio;
@property (nonatomic) BOOL viewDidScrollWhenTapping;
@property (nonatomic) double yOffsetAdjustFactor;
@property (retain, nonatomic) ImageScrollView *imgPreview;
@property (nonatomic) BOOL hasAddHistory;
@property (retain, nonatomic) MMLoadingIndicatorView *loadingIndicatorView;
@property (retain, nonatomic) MiniRecTransitionController *minimizationTransitionController;
@property (nonatomic) BOOL isMultiTaskMinimizeTransition;
@property (nonatomic) BOOL showNewUI;
@property (retain, nonatomic) MMScrollActionSheet *scrollActionSheet;
@property (nonatomic) BOOL m_bOpenMode;
@property (nonatomic) BOOL navigationBarVisibleInteractionEnabled;
@property (nonatomic) BOOL b_forceEnableJS;
@property (copy, nonatomic) id /* block */ downloadStartReportBlock;
@property (copy, nonatomic) id /* block */ downloadSuccessReportBlock;
@property (retain, nonatomic) FileDetailLogicController *logicController;
@property (weak, nonatomic) id<FileDetailViewControllerDelegate> delegate;
@property (retain, nonatomic) NSDictionary *userInfo;
@property (readonly, nonatomic) WKWebView *webView;
@property (readonly, nonatomic) UIViewController<FileDetailCustomizedPreviewController> *currentCustomizedPreviewController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)init;
- (void)pushSelfInNav:(id)a0 animated:(BOOL)a1;
- (BOOL)isAudioPlaying;
- (void)dealloc;
- (id)GetFileDisplayName;
- (void)SetProgressHide:(BOOL)a0;
- (void)SetDownloadHide:(BOOL)a0;
- (void)viewDidLoad;
- (id)commViewParams;
- (void)onEnterFilePreview:(BOOL)a0;
- (void)onEnterPredownload;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewDidBeDismissed:(BOOL)a0;
- (void)didBecomeActive;
- (void)updateNavBarItems;
- (void)initInfoLabel;
- (void)initWaringLabel;
- (void)updateWaringLabel:(id)a0;
- (void)initStateLable;
- (void)initCancelButton;
- (void)onCancelButtonClicked;
- (void)initSessionResourceButton;
- (void)onSessionSourceBtnClick;
- (id)generateExpiredText;
- (void)viewDidLayoutSubviews;
- (void)viewDidBePoped:(BOOL)a0;
- (void)viewDidBePushed:(BOOL)a0;
- (void)layoutMyViews;
- (void)recordView:(id)a0;
- (void)updateViewsInBottomTopEdge:(double)a0;
- (void)updateWebScrollViewInset;
- (void)InitPreview;
- (void)didInitPreview;
- (void)didLoadWebView;
- (void)refreshWAWxMaterialAppInfo:(id)a0;
- (void)updateOpenWeAppButton;
- (void)initOpenWeAppButton;
- (void)initNoSupportOpenLabel;
- (void)initSizeLabel;
- (void)initCannotOpenLabelIfNeeded;
- (void)InitCircleProgressView;
- (void)InitLoadingIndicatorView;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidTransitionToNewSize;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })a0 withTransitionCoordinator:(id)a1;
- (void)InitDownload;
- (void)InitDownload:(BOOL)a0;
- (BOOL)checkContinueDownloadForAppMsg;
- (void)OnOperate:(id)a0;
- (id)addActionSheetItem:(id)a0 icon:(id)a1 toArray:(id)a2;
- (void)OnReturn;
- (void)onRevokedReturn;
- (void)onSwitchScene:(id)a0;
- (BOOL)isExceptionFileName:(id)a0;
- (void)StartDownload:(id)a0;
- (void)StopDownload;
- (void)StopDownloadAndUpdateView;
- (void)ShowDownloadBtn;
- (void)ShowDownloadBtn:(id)a0;
- (void)ShowProgressView;
- (void)ShowIndicatorViewWithRealtimeUploading:(BOOL)a0;
- (void)showRealtimeUploadingStatus;
- (void)HiddenIndicatorView;
- (void)SetProgressPartLen:(unsigned long long)a0 TotalLen:(unsigned long long)a1;
- (id)minimizeKey;
- (BOOL)isOnMinimizeState;
- (BOOL)isMultiContentWindowState;
- (BOOL)isPreviewTypeAudio;
- (id)getRightBarButtonItem;
- (BOOL)isPreviewTypeVideo;
- (BOOL)isVideoCanPlay;
- (id)getFavoritesItemData;
- (unsigned int)currentPreviewType;
- (id)customizedPreviewControllerForPreviewType:(unsigned int)a0;
- (void)removeCustomizedPreviewControllerIfNeeded;
- (void)scrollActionSheet:(id)a0 didSelecteItem:(id)a1;
- (void)clickRFItemCallBack:(id)a0;
- (void)relayoutScrollSheet;
- (void)viewWillDisappear:(BOOL)a0;
- (BOOL)useTransparentNavibar;
- (BOOL)useBlackStatusbar;
- (void)setNaviBarHide:(BOOL)a0 animation:(BOOL)a1;
- (BOOL)hasPdfView;
- (void)resetPdfViewFrame;
- (void)restorePdfContentOffset;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)scrollViewDidScroll:(id)a0;
- (BOOL)gestureRecognizer:(id)a0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)a1;
- (BOOL)gestureRecognizer:(id)a0 shouldBeRequiredToFailByGestureRecognizer:(id)a1;
- (BOOL)gestureRecognizer:(id)a0 shouldReceiveTouch:(id)a1;
- (void)onSingleTap:(id)a0;
- (void)initShareToFriendBtn;
- (void)onDownloadFileFailWithHint:(id)a0;
- (void)setFileFailText:(id)a0;
- (void)updateStateLabel:(id)a0;
- (void)onDownloadFileSuccess;
- (void)onDownloadFilePartLen:(unsigned long long)a0 TotalLen:(unsigned long long)a1;
- (void)onRevoked;
- (void)prepareMultiContentMinimizeTransition;
- (void)onCanShareToFriendByButton;
- (id)getCurrentViewController;
- (void)setImageScrollView:(id)a0;
- (void)webView:(id)a0 decidePolicyForNavigationAction:(id)a1 decisionHandler:(id /* block */)a2;
- (void)webView:(id)a0 didCommitNavigation:(id)a1;
- (void)webView:(id)a0 didFinishNavigation:(id)a1;
- (void)webView:(id)a0 didFailNavigation:(id)a1 withError:(id)a2;
- (void)webViewWebContentProcessDidTerminate:(id)a0;
- (void)circleProgressViewDidTapped:(id)a0;
- (BOOL)tryAddToMinimize;
- (void)addToMinimize;
- (void)addToMultiContentMinimize;
- (void)updateToMinimize;
- (void)reloadWhenMaximize;
- (BOOL)isMinimizeEnable;
- (void)addToTaskHistory;
- (void)removeTaskHistory;
- (void)installMinimizationTransitionController;
- (id)mmNavigationController:(id)a0 animationControllerForOperation:(long long)a1 fromViewController:(id)a2 toViewController:(id)a3;
- (id)mmNavigationController:(id)a0 interactionControllerForAnimationController:(id)a1;
- (void)minimizationInteractivePopGestureRecognizerDidBegin;
- (void)minimizationInteractivePopToMinimizeTask:(BOOL)a0;
- (id)currentMinimizationTaskBizKey;
- (id)currentMinimizationTaskBizName;
- (id)currentMultiContentTaskBizName;
- (id)currentMultiContentTaskBizKey;
- (id)minimizationTaskData;
- (id)getMinimizeContentTaskData;
- (BOOL)minimizationInteractivePopGestureRecognizerShouldBegin;
- (id)minimizationInteractivePopGetPendingTaskContextWithGenerateType:(unsigned long long)a0;
- (BOOL)shouldBlockMinimizationEntryInInteractivePop;
- (void)onFullScreenSingleTap;
- (void)reloadPDFContent;
- (void)relayoutImageContent;
- (void)tryUpdateTaskSnapShot;
- (void)genCurrentContentSnapshot:(id /* block */)a0;
- (void)updateAppMsgState:(id)a0 andState:(unsigned int)a1;
- (void)didMoveToNewScene:(id)a0;
- (void).cxx_destruct;

@end
