@class FinderContact, FinderCommentMentionedUser, FinderNotification, FinderIdentityInfo, FinderMention_LikeContactInfo, FinderMentionContact, NSMutableArray, FinderHelpPromotionMentionInfo, FinderMentionExtInfo, NSString, FinderMentionAggregated, FinderJumpInfo, CommentContentInfo, FinderFollowReasonInfo, FinderPoiInteractionInfo, FinderMention_FinderMentionThankInfo, NewLifeMentionInfo;

@interface FinderMention : WXPBGeneratedMessage

@property (retain, nonatomic) NSString *headUrl;
@property (retain, nonatomic) NSString *nickname;
@property (nonatomic) unsigned int mentionType;
@property (retain, nonatomic) NSString *mentionContent;
@property (nonatomic) unsigned int createtime;
@property (retain, nonatomic) NSString *thumbUrl;
@property (nonatomic) unsigned long long mentionId;
@property (nonatomic) unsigned long long refObjectId;
@property (nonatomic) unsigned long long refCommentId;
@property (nonatomic) unsigned int flag;
@property (nonatomic) unsigned int extflag;
@property (retain, nonatomic) NSString *refContent;
@property (retain, nonatomic) FinderNotification *notification;
@property (nonatomic) unsigned int mediaType;
@property (retain, nonatomic) NSString *description;
@property (retain, nonatomic) NSString *replyNickname;
@property (retain, nonatomic) NSString *replyUsername;
@property (retain, nonatomic) NSString *refObjectNonceId;
@property (retain, nonatomic) NSString *username;
@property (retain, nonatomic) FinderMentionContact *contact;
@property (retain, nonatomic) FinderMentionContact *replyContact;
@property (retain, nonatomic) FinderMentionAggregated *aggregated;
@property (retain, nonatomic) NSMutableArray *aggregatedContactList;
@property (nonatomic) unsigned int aggregatedCount;
@property (nonatomic) unsigned int followExpireTime;
@property (retain, nonatomic) NSString *clientMsgId;
@property (nonatomic) unsigned long long followId;
@property (nonatomic) unsigned int refObjectType;
@property (nonatomic) unsigned long long refVideoObjectId;
@property (retain, nonatomic) NSString *refVideoObjectNonceId;
@property (retain, nonatomic) FinderMention_LikeContactInfo *likeInfo;
@property (retain, nonatomic) FinderContact *authorContact;
@property (retain, nonatomic) FinderCommentMentionedUser *commentMentionedUser;
@property (retain, nonatomic) FinderMentionExtInfo *extInfo;
@property (nonatomic) unsigned long long svrMentionId;
@property (nonatomic) unsigned int followFlag;
@property (nonatomic) unsigned long long refFavId;
@property (retain, nonatomic) FinderMention_FinderMentionThankInfo *thankInfo;
@property (nonatomic) unsigned int businessType;
@property (retain, nonatomic) FinderIdentityInfo *finderIdentity;
@property (retain, nonatomic) FinderFollowReasonInfo *followReason;
@property (retain, nonatomic) NSString *thumbUrlToken;
@property (nonatomic) unsigned int sourceType;
@property (nonatomic) unsigned long long rootCommentId;
@property (nonatomic) unsigned int mentionSubtype;
@property (nonatomic) unsigned int orderCount;
@property (nonatomic) unsigned int interactionCount;
@property (retain, nonatomic) NSString *memberProviderFinderusername;
@property (nonatomic) unsigned int forceUseContent;
@property (nonatomic) unsigned int forceUseRefContent;
@property (retain, nonatomic) NSString *svrReportInfo;
@property (nonatomic) unsigned long long refThumbupId;
@property (nonatomic) unsigned int thankIconType;
@property (retain, nonatomic) FinderPoiInteractionInfo *poiInteractionInfo;
@property (retain, nonatomic) FinderHelpPromotionMentionInfo *helpPromotionInfo;
@property (retain, nonatomic) NSMutableArray *interactionLabelList;
@property (retain, nonatomic) NewLifeMentionInfo *newlifeMentionInfo;
@property (nonatomic) unsigned int isSilentMention;
@property (retain, nonatomic) NSString *silentMentionEntityId;
@property (retain, nonatomic) NSString *aggregateTitle;
@property (nonatomic) unsigned int commentContentType;
@property (retain, nonatomic) CommentContentInfo *commentContentInfo;
@property (nonatomic) unsigned int jumpType;
@property (retain, nonatomic) FinderJumpInfo *jumpInfo;
@property (nonatomic) unsigned long long replyCommentId;
@property (retain, nonatomic) NSString *reportUdfKvJson;

+ (id)unarchiveWithWCTValue:(id)a0;
+ (unsigned long long)columnType;
+ (void)initialize;

- (void)setReportUdfKvJson:(id)a0;
- (id)reportUdfKvJson;
- (void)setReplyCommentId:(unsigned long long)a0;
- (unsigned long long)replyCommentId;
- (void)setJumpInfo:(id)a0;
- (id)jumpInfo;
- (void)setJumpType:(unsigned int)a0;
- (unsigned int)jumpType;
- (void)setCommentContentInfo:(id)a0;
- (id)commentContentInfo;
- (void)setCommentContentType:(unsigned int)a0;
- (unsigned int)commentContentType;
- (void)setAggregateTitle:(id)a0;
- (id)aggregateTitle;
- (void)setSilentMentionEntityId:(id)a0;
- (id)silentMentionEntityId;
- (void)setIsSilentMention:(unsigned int)a0;
- (unsigned int)isSilentMention;
- (void)setNewlifeMentionInfo:(id)a0;
- (id)newlifeMentionInfo;
- (void)setInteractionLabelList:(id)a0;
- (id)interactionLabelList;
- (void)setHelpPromotionInfo:(id)a0;
- (id)helpPromotionInfo;
- (void)setPoiInteractionInfo:(id)a0;
- (id)poiInteractionInfo;
- (void)setThankIconType:(unsigned int)a0;
- (unsigned int)thankIconType;
- (void)setRefThumbupId:(unsigned long long)a0;
- (unsigned long long)refThumbupId;
- (void)setSvrReportInfo:(id)a0;
- (id)svrReportInfo;
- (void)setForceUseRefContent:(unsigned int)a0;
- (unsigned int)forceUseRefContent;
- (void)setForceUseContent:(unsigned int)a0;
- (unsigned int)forceUseContent;
- (void)setMemberProviderFinderusername:(id)a0;
- (id)memberProviderFinderusername;
- (void)setInteractionCount:(unsigned int)a0;
- (unsigned int)interactionCount;
- (void)setOrderCount:(unsigned int)a0;
- (unsigned int)orderCount;
- (void)setMentionSubtype:(unsigned int)a0;
- (unsigned int)mentionSubtype;
- (void)setRootCommentId:(unsigned long long)a0;
- (unsigned long long)rootCommentId;
- (void)setSourceType:(unsigned int)a0;
- (unsigned int)sourceType;
- (void)setThumbUrlToken:(id)a0;
- (id)thumbUrlToken;
- (void)setFollowReason:(id)a0;
- (id)followReason;
- (void)setFinderIdentity:(id)a0;
- (id)finderIdentity;
- (void)setBusinessType:(unsigned int)a0;
- (unsigned int)businessType;
- (void)setThankInfo:(id)a0;
- (id)thankInfo;
- (void)setRefFavId:(unsigned long long)a0;
- (unsigned long long)refFavId;
- (void)setFollowFlag:(unsigned int)a0;
- (unsigned int)followFlag;
- (void)setSvrMentionId:(unsigned long long)a0;
- (unsigned long long)svrMentionId;
- (void)setExtInfo:(id)a0;
- (id)extInfo;
- (void)setCommentMentionedUser:(id)a0;
- (id)commentMentionedUser;
- (void)setAuthorContact:(id)a0;
- (id)authorContact;
- (void)setLikeInfo:(id)a0;
- (id)likeInfo;
- (void)setRefVideoObjectNonceId:(id)a0;
- (id)refVideoObjectNonceId;
- (void)setRefVideoObjectId:(unsigned long long)a0;
- (unsigned long long)refVideoObjectId;
- (void)setRefObjectType:(unsigned int)a0;
- (unsigned int)refObjectType;
- (void)setFollowId:(unsigned long long)a0;
- (unsigned long long)followId;
- (void)setClientMsgId:(id)a0;
- (id)clientMsgId;
- (void)setFollowExpireTime:(unsigned int)a0;
- (unsigned int)followExpireTime;
- (void)setAggregatedCount:(unsigned int)a0;
- (unsigned int)aggregatedCount;
- (void)setAggregatedContactList:(id)a0;
- (id)aggregatedContactList;
- (void)setAggregated:(id)a0;
- (id)aggregated;
- (void)setReplyContact:(id)a0;
- (id)replyContact;
- (void)setContact:(id)a0;
- (id)contact;
- (void)setUsername:(id)a0;
- (id)username;
- (void)setRefObjectNonceId:(id)a0;
- (id)refObjectNonceId;
- (void)setReplyUsername:(id)a0;
- (id)replyUsername;
- (void)setReplyNickname:(id)a0;
- (id)replyNickname;
- (void)setDescription:(id)a0;
- (id)description;
- (void)setMediaType:(unsigned int)a0;
- (unsigned int)mediaType;
- (void)setNotification:(id)a0;
- (id)notification;
- (void)setRefContent:(id)a0;
- (id)refContent;
- (void)setExtflag:(unsigned int)a0;
- (unsigned int)extflag;
- (void)setFlag:(unsigned int)a0;
- (unsigned int)flag;
- (void)setRefCommentId:(unsigned long long)a0;
- (unsigned long long)refCommentId;
- (void)setRefObjectId:(unsigned long long)a0;
- (unsigned long long)refObjectId;
- (void)setMentionId:(unsigned long long)a0;
- (unsigned long long)mentionId;
- (void)setThumbUrl:(id)a0;
- (id)thumbUrl;
- (void)setCreatetime:(unsigned int)a0;
- (unsigned int)createtime;
- (void)setMentionContent:(id)a0;
- (id)mentionContent;
- (void)setMentionType:(unsigned int)a0;
- (unsigned int)mentionType;
- (void)setNickname:(id)a0;
- (id)nickname;
- (void)setHeadUrl:(id)a0;
- (id)headUrl;
- (id)archivedWCTValue;

@end
