@class UIImageView, MMAssetSelectCheckButton, UILabel, LiteAppAssetInfo, WCLivePhotoButton, WCLivePhotoButtonModel, MMAssetICloudLoadingView, NSMutableArray, UIView, NSString, LiteAppAssetPickerControlCenter, MMUILabel, UIImage;
@protocol LiteAppAssetViewDelegate;

@interface LiteAppAssetView : MMUIView <LiteAppAssetPickerControllerExt> {
    BOOL m_isSelected;
    BOOL m_isPreviewStyle;
    UIView *m_disabledMaskView;
    UIView *m_tagBackgroundView;
    UILabel *m_lengthLabel;
    UILabel *m_gifLogoView;
    UIView *m_editImageView;
    MMAssetSelectCheckButton *m_selectCheckButton;
    double m_imgHeight;
}

@property (retain, nonatomic) UIImageView *m_assetImageView;
@property (retain, nonatomic) UIView *m_selectionBgView;
@property (retain, nonatomic) MMUILabel *m_nameLabel;
@property (retain, nonatomic) MMUILabel *m_sizeLabel;
@property (retain, nonatomic) UIView *limitTipsView;
@property (retain, nonatomic) UIView *highlightView;
@property (retain, nonatomic) UILabel *indexLabel;
@property (retain, nonatomic) MMAssetICloudLoadingView *icloudLoadingView;
@property (retain, nonatomic) UIImageView *mediaTypeIconView;
@property (nonatomic) BOOL isAutoPicking;
@property (nonatomic) BOOL isDragPicking;
@property (nonatomic) BOOL isDragPickingInterupt;
@property (nonatomic) BOOL isICloudLoading;
@property (retain, nonatomic) WCLivePhotoButton *livePhotoButton;
@property (retain, nonatomic) WCLivePhotoButtonModel *livePhotoButtonModel;
@property (retain, nonatomic) NSMutableArray *accessibleElements;
@property (retain, nonatomic) LiteAppAssetInfo *assetInfo;
@property (weak, nonatomic) id<LiteAppAssetViewDelegate> delegate;
@property (retain, nonatomic) LiteAppAssetPickerControlCenter *controlCenter;
@property (nonatomic) BOOL enabled;
@property (nonatomic) BOOL isInPreview;
@property (readonly, nonatomic) BOOL select;
@property (retain, nonatomic) UIImage *defaultImage;
@property (nonatomic) BOOL bDelayUpdateAssetInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 useLightStyle:(BOOL)a1;
- (void)layoutSubviews;
- (BOOL)tryShowFileSizeLimitTips;
- (void)showOriginSizeLimitAlert;
- (void)hiddeFileSizeLimitTips;
- (void)prepareForReuse;
- (void)updateAssetInfo;
- (void)updateAssetInfoWithAnimation;
- (BOOL)isShowLivePhotoBtn;
- (BOOL)isShowLivePhotoIcon;
- (void)updateAssetInfo:(BOOL)a0;
- (BOOL)shouldShowMultiSelect;
- (double)tagLogoLBMargin;
- (void)showTagBGView;
- (void)showVideoLogoViewWithTime:(id)a0;
- (void)showGifLogoView;
- (void)showEditedLogoView;
- (void)showAlertTips:(id)a0;
- (void)showAlertTips:(id)a0 scene:(unsigned long long)a1;
- (void)updateEnabledState;
- (BOOL)isCurrentAssetEnable;
- (void)updateAssetViewEnabledWithSelectedCount:(unsigned long long)a0;
- (BOOL)isAccessibilityElement;
- (long long)accessibilityElementCount;
- (id)accessibilityElementAtIndex:(long long)a0;
- (long long)indexOfAccessibilityElement:(id)a0;
- (BOOL)accessibilityPerformMagicTap;
- (id)accessibilityHint;
- (id)accessibilityValue;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityLabel;
- (struct CGPoint { double x0; double x1; })accessibilityActivationPoint;
- (void)showedSelectedMarkWithIndex:(long long)a0 animated:(BOOL)a1;
- (void)toggleLivePhotoIconVisibilityWithAnimate:(BOOL)a0;
- (BOOL)isShowLivePhotoGuide;
- (void)showLivePhotoGuideView;
- (void)onTapButton;
- (void)toggleSelection;
- (void)realToggleSelection;
- (void)removeSelected;
- (void)tryToSelectAsset;
- (void)tryToSelectVideoWithAvAsset:(id)a0 videoUrl:(id)a1 assetError:(long long)a2;
- (void)tryToSelectGifWithImage:(id)a0 imageData:(id)a1;
- (void)doSelectWithStateInfo:(id)a0;
- (void)doSelect;
- (void)doEdit;
- (void)onSelectAssetFinish;
- (void)tagAseetToPreview;
- (void)updateBgMaskView;
- (BOOL)checkThumbImage;
- (id)timeStringBySeconds:(double)a0;
- (void)onAssetPickerControllerChangeSelectInfo:(id)a0 index:(long long)a1;
- (void)onAssetPickerControllerChangeLivePhotoIconState:(id)a0;
- (void)onAssetPickerControllerFinishEditAssetInfo:(id)a0;
- (void)fadeOutHighlightView;
- (void)onAssetPickerControllerDidAddAssetId:(id)a0;
- (void)setupLivePhotoButton:(unsigned long long)a0;
- (void)initLivePhotoButton;
- (void)livePhotoButtonClicked:(id)a0;
- (void)configLivePhotoIconShadow;
- (BOOL)isSelectAssetExceedMaxCount;
- (void).cxx_destruct;

@end
