@class MJMovieComposingRecognitionGuideView, MJSegmentCropBoxView, MJMovieComposingBottomBar, MJAnalysisGuidanceManager, MJTimelineViewController, MJMovieComposingViewModel, NSMutableArray, MJGradientView, MJComposingBGMAdjustHalfScreenViewController, MJMovieComposingTitleGuideView, MJExportProgressMaskView, OMJHandleBoxBorderStyle, NSMapTable, MJSegmentCropGestureCaptureView, MMUILabel, MJPassthroughView, MJNarrationRecordingControlView, MJMovieTextSuggestionContext, MMUIButton, MMBGMSelectHalfScreenViewController, MJMusicCapsuleView, MJTimelineViewModel, UIView, MJSegmentViewModel, MJPassthroughButton, MJVideoSafeAreaTipsView, MJMovieTextEditInspector, MJMovieTextSuggestionProcessor, MJMovieTextSuggestionSnapshotGenerator, MJToolbarButton, NSString, MJMusicPickingViewModel, OMJPlaybackOverlayView, MMTimer, UIImageView, MJClippingPanel, MJMovieComposingSession, MJPlaybackViewModel, MJActionPanelViewController, MJPublisherPlaybackProgressSlider;
@protocol MJMovieComposingViewControllerDelegate;

@interface MJMovieComposingViewController : MMUIViewController <MJMovieComposingTitleGuideViewDelegate, MJMovieTextSuggestionContextDataSource, MJMovieTextSuggestionProcessorDelegate, MJMovieTextSuggestionSnapshotGeneratorDelegate, MJMovieTextEditInspectorDelegate, MJMovieTextTitleViewControllerDelegate, MJMovieTextContentDescViewControllerDelegate, MJMovieTextOSTRecognitionViewControllerDelegate, MJVoiceCloneViewControllerDelegate, MJStickerPickerViewControllerDelegate, MJEmotionViewControllerDelegate, MJMetaEditInspectorDelegate, MJMovieComposingRecognitionGuideViewDelegate, MMBGMSelectHalfScreenViewControllerDelegate, MJMusicCapsuleViewDelegate, MJStyleEditViewModelDataSource, MJStyleEditViewControllerDelegate, OMJPlaybackOverlayViewDelegate, MJSegmentCropGestureCaptureViewDelegate, MJTimelineCanvasEditViewDelegate, MJComposingBGMAdjustHalfScreenViewControllerDelegate, MJComposingPagePanelViewDelegate, MJClippingPanelDelegate, MJTimelineContentRangeEditViewDelegate, MJPlaybackViewModelDelegate, MJSegmentSpeedInspectorViewDelegate, MJTransitionInspectorViewDelegate, MJMovieComposingInspectorDelegate, MJExportProgressMaskViewDelegate, MJMovieComposingBottomBarReportDelegate, MMMenuControllerExt, QuickReplyMsgExt, MonoServiceLogicExt>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) MJPublisherPlaybackProgressSlider *playbackProgressSlider;
@property (nonatomic) BOOL isFirstAppear;
@property (nonatomic) struct { long long value; int timescale; unsigned int flags; long long epoch; } playbackResumeTime;
@property (readonly, nonatomic) MJTimelineViewModel *timelineVM;
@property (readonly, nonatomic) MJPlaybackViewModel *playbackVM;
@property (retain, nonatomic) UIView *backgroundGRView;
@property (readonly, nonatomic) UIView *renderView;
@property (readonly, nonatomic) UIView *renderViewContainer;
@property (nonatomic) BOOL isRenderViewShrinked;
@property (retain, nonatomic) OMJPlaybackOverlayView *overlayView;
@property (nonatomic) BOOL shouldAutoStartPlaying;
@property (retain, nonatomic) MJSegmentViewModel *previousFocusedSegmentVM;
@property (retain, nonatomic) MMUIButton *skipMovieTilteInputGuideButton;
@property (retain, nonatomic) MMUIButton *exitButton;
@property (retain, nonatomic) MJPassthroughButton *confirmButton;
@property (retain, nonatomic) MJToolbarButton *feedbackButton;
@property (retain, nonatomic) MMUIButton *debugShowTimeLineButton;
@property (retain, nonatomic) MMUIButton *playButton;
@property (retain, nonatomic) MMUIButton *backToStartButton;
@property (retain, nonatomic) MJMovieComposingBottomBar *bottomBar;
@property (retain, nonatomic) MJGradientView *bottomGradientView;
@property (retain, nonatomic) NSMutableArray *panelStack;
@property (retain, nonatomic) MJPassthroughView *panelContainer;
@property (retain, nonatomic) MJClippingPanel *clippingPanel;
@property (retain, nonatomic) MJTimelineViewController *clippingTimelineVC;
@property (retain, nonatomic) MJActionPanelViewController *actionPanelVC;
@property (retain, nonatomic) MJNarrationRecordingControlView *recordingControlView;
@property (nonatomic) struct { long long value; int timescale; unsigned int flags; long long epoch; } narrationStartTimeInTimeline;
@property (retain, nonatomic) NSMapTable *narrationSegmentIDsByIdentifier;
@property (retain, nonatomic) MJMovieComposingTitleGuideView *titleGuideView;
@property (nonatomic) BOOL isTitleGuideShrinked;
@property (retain, nonatomic) MJMovieComposingRecognitionGuideView *recognitionGuideView;
@property (retain, nonatomic) MJAnalysisGuidanceManager *analysisGuidanceManager;
@property (nonatomic) unsigned long long prevEditContentType;
@property (retain, nonatomic) MJMovieTextEditInspector *textInspector;
@property (nonatomic) BOOL shouldLeaveTextEditingWhenTextInspectorDidFinish;
@property (nonatomic) BOOL isShowingTitleInputGuideInProgress;
@property (nonatomic) unsigned long long stickerEditingOptions;
@property (retain, nonatomic) MJMusicCapsuleView *musicCapsuleView;
@property (retain, nonatomic) MMBGMSelectHalfScreenViewController *musicPickingVC;
@property (retain, nonatomic) MJMusicPickingViewModel *musicPickingVM;
@property (retain, nonatomic) MJComposingBGMAdjustHalfScreenViewController *bgmAdjustPanelVC;
@property (retain, nonatomic) MMTimer *musicDownloadDetectTimer;
@property (retain, nonatomic) MJExportProgressMaskView *progressView;
@property (readonly, nonatomic) NSMutableArray *toolbarSignalObservers;
@property (retain, nonatomic) MMUILabel *canvasUserInteractionTipLabel;
@property (retain, nonatomic) MJSegmentViewModel *handleBoxSegmentVM;
@property (nonatomic) unsigned long long handleBoxOptions;
@property (retain, nonatomic) OMJHandleBoxBorderStyle *handleBoxBorderStyle;
@property (retain, nonatomic) MJVideoSafeAreaTipsView *safeAreaTipsView;
@property (retain, nonatomic) MJSegmentCropBoxView *cropBoxView;
@property (retain, nonatomic) MJSegmentCropGestureCaptureView *cropGestureCaptureView;
@property (retain, nonatomic) MJMovieTextSuggestionProcessor *movieTextSuggestionProcessor;
@property (retain, nonatomic) MJMovieTextSuggestionContext *movieTextSuggestionContext;
@property (retain, nonatomic) MJMovieTextSuggestionSnapshotGenerator *movieTextSuggestionSnapshotGenerator;
@property (weak, nonatomic) id<MJMovieComposingViewControllerDelegate> delegate;
@property (retain, nonatomic) MJMovieComposingViewModel *viewModel;
@property (retain, nonatomic) MJMovieComposingSession *publisherMCSession;
@property (readonly, nonatomic) unsigned long long state;
@property (retain, nonatomic) UIImageView *initialContentImageView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)defaultHandleBoxTitlesWithSegmentVM:(id)a0 hasButton:(BOOL)a1;
+ (id)defaultHandleBoxTitleWithSegmentType:(unsigned long long)a0;
+ (id)defaultSpeechRoleTitleWithName:(id)a0 hasButton:(BOOL)a1;
+ (BOOL)shouldHandleExportError:(id)a0;

- (void)enterTrimmingWithCompletionHandler:(id /* block */)a0;
- (void)leaveTrimming;
- (void)setupTrimmingViews;
- (void)setupTitleGuideView;
- (void)layoutTitleGuideView;
- (void)movieComposingTitleGuideViewDidSelectCloseButton:(id)a0;
- (void)movieComposingTitleGuideViewDidTouchUpInside:(id)a0;
- (void)updateTitleGuideForState:(unsigned long long)a0;
- (void)hideTitleGuideIfNeeded;
- (void)showTitleGuideIfNeeded;
- (BOOL)isTitleGuideViewNeeded;
- (id)snapshotDataForMovieTextSuggestionContext:(id)a0;
- (id)feedLocationsForMovieTextSuggestionContext:(id)a0;
- (id)userLocationForMovieTextSuggestionContext:(id)a0;
- (id)musicIDForMovieTextSuggestionContext:(id)a0;
- (id)templateIDForMovieTextSuggestionContext:(id)a0;
- (void)movieTextSuggestionProcessor:(id)a0 didUpdateSuggestions:(id)a1;
- (void)movieTextSuggestionSnapshotGenerator:(id)a0 didGenerateSnapShot:(id)a1;
- (void)preloadTextEditingMaterials;
- (void)enterTextEditingWithOptions:(unsigned long long)a0 segmentVM:(id)a1 editContentType:(unsigned long long)a2 completionHandler:(id /* block */)a3;
- (void)addTextForFancyTextSegmentVM:(id)a0;
- (void)enterTextEditingStateWithPanel:(BOOL)a0 shouldShrinkRenderView:(BOOL)a1 hidePanelDuringAnimation:(BOOL)a2 segmentVM:(id)a3 editContentType:(unsigned long long)a4 completionHandler:(id /* block */)a5;
- (void)leaveTextEditing;
- (void)leaveTextEditingStateWithPanel:(BOOL)a0;
- (id)setupTextEditingViewsWithSegmentVM:(id)a0 editContentType:(unsigned long long)a1;
- (id)setupTextPagePanelViewModelWithSegmentVM:(id)a0 editContentType:(unsigned long long)a1;
- (BOOL)reloadTextPagePanelIfNeeded;
- (BOOL)resetPreviewForTextPagePanelIfNeeded;
- (BOOL)updateTextPagePanelOnSkimTimeDidChange:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (BOOL)updateTextPagePanelOnPlaybackTimeDidChange:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (BOOL)updateTextPagePanelOnIsPlayingDidChange:(BOOL)a0;
- (id)topTextViewController;
- (void)movieTitleVCNeedsUpdate:(id)a0 onSkimTimeDidChange:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)movieTitleVCNeedsUpdate:(id)a0 onPlaybackTimeDidChange:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)movieTitleVCNeedsUpdate:(id)a0 onIsPlayingDidChange:(BOOL)a1;
- (void)movieTitleVCNeedsReload:(id)a0;
- (void)movieTitleVCNeedsResetPreview:(id)a0;
- (void)skimToMovieTitleSegmentHeadTimeIfNeeded;
- (void)showHandleboxForMovieTitleSegment;
- (void)enterEditingStateForForMovieTitleSegment;
- (void)movieTitleVCDidSelectEditText:(id)a0;
- (void)movieTitleHandlePanelVCTextActionWithCompletionHandler:(id /* block */)a0;
- (void)movieTitleVCDidSelectEditStyle:(id)a0;
- (void)movieTitleVCDidSelectTrim:(id)a0;
- (void)movieTitleVCDidSelectDelete:(id)a0;
- (void)movieTitleVCDidSelectTTS:(id)a0;
- (id)movieTitleSegmentVM;
- (BOOL)checkIfMovieTitleSegmentExists:(id)a0;
- (void)contentDescVCNeedsUpdate:(id)a0 onSkimTimeDidChange:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)contentDescVCNeedsUpdate:(id)a0 onPlaybackTimeDidChange:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)contentDescVCNeedsUpdate:(id)a0 onIsPlayingDidChange:(BOOL)a1;
- (void)contentDescVCNeedsReload:(id)a0;
- (void)contentDescVCNeedsResetPreview:(id)a0;
- (void)showHandleboxForContentDescSegmentAtTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (void)contentDescVCDidSelectEditText:(id)a0;
- (void)contentDescVCDidSelectEditStyle:(id)a0;
- (void)contentDescVCDidSelectDelete:(id)a0;
- (id)contentDescSegmentVM;
- (BOOL)checkIfContentDescSegmentExists:(id)a0;
- (void)focusOnCurrentContentDescBelongingVM;
- (void)focusOnCurrentContentDescVM;
- (id)contentDescSegmentVMWitStorylineSegmentVM:(id)a0;
- (long long)contentDescVCRequestNumberOfStoryElementSegmentVMs:(id)a0;
- (id)contentDescVC:(id)a0 requestStoryElementSegmentVMAtIndexPath:(id)a1;
- (long long)contentDescVC:(id)a0 willScrollThumbnailToTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1 showHandleBox:(BOOL)a2;
- (void)contentDescVC:(id)a0 didTapOnSegmentAtIndexPath:(id)a1;
- (void)OSTRecognitionVCDidSelectEditCaptionText:(id)a0;
- (void)OSTRecognitionVCDidSelectEditCaptionStyle:(id)a0;
- (void)OSTRecognitionVC:(id)a0 didUpdateTimelineViewController:(id)a1;
- (void)stickerPickerNeedsResetPreview:(id)a0;
- (void)stickerPickerNeedsResetPreviewNeedsUpdate:(id)a0 onIsPlayingDidChange:(BOOL)a1;
- (void)textEditingHandlePopMenuActionWith:(id)a0 type:(unsigned long long)a1 completionHandler:(id /* block */)a2;
- (BOOL)isShowingTextInspector;
- (void)dismissTextInspector;
- (void)forceCleanupTextInspector;
- (void)enterInspectorWithEntranceType:(long long)a0 editType:(long long)a1 scene:(unsigned long long)a2 segment:(id)a3 completion:(id /* block */)a4;
- (void)textEditInspector:(id)a0 keyboardWillShow:(double)a1 inspectorHeight:(double)a2;
- (void)textEditInspector:(id)a0 keyboardWillHide:(BOOL)a1 inspectorHeight:(double)a2;
- (id)textEditInspector:(id)a0 anchorMovieTextWithMaterialID:(id)a1;
- (void)textEditInspector:(id)a0 segmentID:(id)a1 updateText:(id)a2;
- (void)textEditInspector:(id)a0 updateUnmarkedText:(id)a1 isUsingSuggestion:(BOOL)a2;
- (void)textEditInspector:(id)a0 segmentID:(id)a1 updateSubText:(id)a2;
- (void)textEditInspector:(id)a0 segmentID:(id)a1 updateMaterialID:(id)a2;
- (void)textEditInspector:(id)a0 segmentID:(id)a1 updateFont:(id)a2;
- (void)textEditInspector:(id)a0 segmentID:(id)a1 updateColor:(id)a2;
- (void)textEditInspector:(id)a0 segmentID:(id)a1 updateTextAnimPreset:(id)a2;
- (void)stopPlayingAndSkimToSegmentHeadTimeIfNeeded:(id)a0 shouldEnterEditingState:(BOOL)a1;
- (void)textEditInspector:(id)a0 didEndChangeMaterialWithDataType:(unsigned long long)a1;
- (void)textEditInspectorWillBeginEditing:(id)a0;
- (void)textEditInspectorDidFinish:(id)a0;
- (void)onTextEditInspectorDidFinish:(id)a0 updateHandleBoxWithSegmentVM:(id)a1;
- (void)onTextEditInspectorDidFinish:(id)a0 updateMaterialCacheWithSegmentVM:(id)a1;
- (void)showTTSTipsWithSegmentVM:(id)a0 cancelHandler:(id /* block */)a1 confirmHandler:(id /* block */)a2;
- (void)showVoiceChangeTipsWithNarrationSegmentVM:(id)a0 cancelHandler:(id /* block */)a1 confirmHandler:(id /* block */)a2;
- (void)textEditInspectorWillAppear:(id)a0;
- (void)textEditInspectorWillDisappear:(id)a0;
- (void)notifyTextEditingSegmentDidDelete;
- (BOOL)handleOverlayViewSingleTapActionForTextEdtingWithSegmentID:(id)a0;
- (BOOL)isShowingTTSInspector;
- (void)showTTSInspectorWithSegmentVM:(id)a0 shouldRequestVoiceChange:(BOOL)a1;
- (void)setupClippingPanelForTTS;
- (id)setupTTSInspectorWithSegmentVM:(id)a0 shouldRequestVoiceChange:(BOOL)a1;
- (void)showTTSInspectorInPreviewingState:(id)a0;
- (void)showTTSInspectorInEditingState:(id)a0;
- (void)dismissTTSInspector;
- (void)dismissTTSInspectorInPreviewingState;
- (void)dismissTTSInspectorInEditingState;
- (void)showVoiceCloneViewController;
- (void)voiceCloneViewControllerDidFinishCloning:(id)a0;
- (BOOL)reloadTTSInspectorContents;
- (void)enterStickerEditingWithCompletionHandler:(id /* block */)a0;
- (void)enterStickerEditingWithSegmentVM:(id)a0 options:(unsigned long long)a1 editType:(long long)a2 completionHandler:(id /* block */)a3;
- (void)leaveStickerEditing;
- (void)leaveStickerEditingWithCompletion:(id /* block */)a0;
- (BOOL)handleOverlayViewSingleTapActionForStickerEdtingWithSegmentID:(id)a0;
- (BOOL)isShowingWhenWhereEditInspector;
- (void)showWhenWhereEditInspectorAnimated:(BOOL)a0 editType:(long long)a1 completionHandler:(id /* block */)a2;
- (void)dismissWhenWhereEditInspectorWithCompletionHandler:(id /* block */)a0;
- (id)setupStickerEditingViewsWithSegmentVM:(id)a0;
- (id)setupStickerPagePanelViewModelWithSegmentVM:(id)a0;
- (void)notifyStickerEditingSegmentDidDelete;
- (void)stickerPicker:(id)a0 didChangeSelection:(id)a1 atIndex:(long long)a2;
- (void)updateStickerWithMaterialID:(id)a0 forSegmentWithID:(id)a1;
- (void)anchorStickerWithMaterialID:(id)a0 type:(unsigned long long)a1;
- (void)handleWhenWhereSegmentAfterAdded:(id)a0 completion:(id /* block */)a1;
- (void)requestLocationItemForClipSegment:(id)a0 wwSegment:(id)a1 completion:(id /* block */)a2;
- (void)didEndReplaceWithStickerPicker:(id)a0;
- (void)stickerPicker:(id)a0 didCancelReplace:(id)a1;
- (void)emoticonPickerWillStartLoading:(id)a0;
- (void)emoticonPickerDidFinishLoading:(id)a0;
- (void)emoticonPicker:(id)a0 selectedEmoticon:(id)a1;
- (void)updateEmoticonItem:(id)a0 forSegmentWithID:(id)a1;
- (void)anchorEmoticonWithEmoticonItem:(id)a0;
- (void)fetchAnchorTimeBlock:(id /* block */)a0;
- (void)metaEditInspector:(id)a0 segmentVM:(id)a1 replaceItem:(id)a2;
- (void)metaEditInspector:(id)a0 segmentVM:(id)a1 updateDate:(id)a2;
- (void)metaEditInspector:(id)a0 segmentVM:(id)a1 updateGeographic:(id)a2;
- (void)didEndEditWithMetaEditInspector:(id)a0;
- (void)metaEditInspector:(id)a0 segmentVM:(id)a1 didCancelEditWithBackupItem:(id)a2;
- (void)showRecognitionGuideIfNeeded;
- (void)recognitionGuideViewDidCancel:(id)a0;
- (void)dismissRecognitionGuideIfNeeded;
- (void)recognitionGuideViewDidConfirm:(id)a0;
- (void)setupPanels;
- (void)presentPanel:(id)a0 animated:(BOOL)a1 completionHandler:(id /* block */)a2;
- (void)presentPanels:(id)a0 animated:(BOOL)a1 completionHandler:(id /* block */)a2;
- (void)presentPanel:(id)a0 bottomOffset:(double)a1 animated:(BOOL)a2 completionHandler:(id /* block */)a3;
- (void)presentPanels:(id)a0 bottomOffset:(double)a1 animated:(BOOL)a2 completionHandler:(id /* block */)a3;
- (void)dismissPanel:(id)a0 animated:(BOOL)a1 completionHandler:(id /* block */)a2;
- (void)dismissPanelWithContentView:(id)a0 animated:(BOOL)a1 completionHandler:(id /* block */)a2;
- (BOOL)containsPanelWithType:(unsigned long long)a0;
- (id)panelWithType:(unsigned long long)a0;
- (BOOL)_validateForPresentPanel:(id)a0;
- (BOOL)_validateForDismissPanel:(id)a0;
- (void)_pushPanel:(id)a0;
- (void)_popPanel:(id)a0;
- (id)topPanel;
- (id)topPanelViewModel;
- (void)setupNarrationViews;
- (void)updateNarrationOnFocusedSegmentDidChange;
- (void)updateNarrationOnPlayheadTimeDidChange:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (void)updateNarrationOnPlayheadTimeDidChangeInNarrationSpeak:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (void)updateNarrationOnPlayheadTimeDidChangeInNarrationTextInput:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (void)_enableRecordingControl;
- (void)_disableRecordingControl;
- (BOOL)handleOverlayViewSingleTapActionForNarrationEdtingWithSegmentID:(id)a0;
- (void)requestSpeechRecognitionWithSegmentVM:(id)a0;
- (void)handleRecordFailureWithError:(id)a0;
- (void)narrationRecordingControlViewDidStartRecording:(id)a0;
- (void)narrationRecordingControlViewDidStopRecording:(id)a0;
- (void)narrationRecordingControlViewDidCancelRecording:(id)a0;
- (void)narrationRecordingControlViewDidTapOnTypeSwitchButton:(id)a0;
- (void)handleDidStartRecordingInNarrationSpeak;
- (void)handleDidStartRecordingInNarrationTextInput;
- (void)handleDidStopRecordingInNarrationSpeak;
- (void)handleDidStopRecordingInNarrationTextInput;
- (void)handleDidCancelRecordingInNarrationSpeak;
- (void)handleDidCancelRecordingInNarrationTextInput;
- (void)expandPlaybackDurationForRecording;
- (void)resetPlaybackDuration;
- (void)_showConfirmTipWithNarrationType:(unsigned long long)a0 exitHandler:(id /* block */)a1;
- (void)_updateRecordingViewWithNarrationType:(unsigned long long)a0 recordingControlView:(id)a1;
- (void)voiceInputManager:(id)a0 didUpdateAudioLevel:(float)a1 withIdentifier:(id)a2;
- (void)voiceInputManager:(id)a0 didStartRecordingWithIdentifier:(id)a1 error:(id)a2;
- (void)voiceInputManager:(id)a0 didStopRecordingWithIdentifier:(id)a1 isCancelled:(BOOL)a2 audioFilePath:(id)a3 captions:(id)a4 error:(id)a5;
- (void)voiceInputManager:(id)a0 didUpdateRecognitionResult:(id)a1 withIdentifier:(id)a2 error:(id)a3;
- (void)voiceInputManager:(id)a0 didFinishRecognitionWithResult:(id)a1 identifier:(id)a2 error:(id)a3;
- (void)voiceInputManager:(id)a0 didUpdateSentenceInfo:(unsigned int)a1 withIdentifier:(id)a2;
- (void)voiceInputManager:(id)a0 didUpdateDecibels:(const void *)a1 withIdentifier:(id)a2;
- (void)voiceInputManager:(id)a0 didUpdateRecognitionState:(unsigned long long)a1 withIdentifier:(id)a2;
- (void)voiceInputManager:(id)a0 didReachRecordingDurationLimitWithToastText:(id)a1 identifier:(id)a2;
- (BOOL)isRecordingAvailableAtTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (float)recordingDurationLimitAtTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (id)narrationSegmentVMWithIdentifier:(id)a0;
- (void)timelineViewControllerDidSelectAdjustVolume:(id)a0;
- (void)showTimelineVolumeInspector;
- (BOOL)dismissTimelineVolumeInspector;
- (BOOL)isShowingVoiceChangeInspector;
- (BOOL)reloadVoiceChangeInspectorContents;
- (void)setupMusicCapsuleView;
- (void)switchMusicEntryViewToMusicSelectedStateWithSongName:(id)a0;
- (void)switchMusicCapsuleViewToMusicUnSelectedState;
- (void)updateMusicEntranceViewWithResultMusic:(id)a0;
- (void)removeMusicIfNeeded;
- (void)updateMusicCapsuleTitle;
- (void)musicCapsuleViewDidClick:(id)a0;
- (void)disableMusicInCapsuleView:(id)a0;
- (void)enterMusicPickingWithChangeComposingState:(BOOL)a0 completionHandler:(id /* block */)a1;
- (void)leaveMusicPicking;
- (void)bgmSelectedViewController:(id)a0 didSelectedMusic:(id)a1 atTabIndex:(unsigned long long)a2 index:(unsigned long long)a3 isTriggerByTap:(BOOL)a4;
- (void)bgmSelectedViewController:(id)a0 didClickMusicOnBtn:(BOOL)a1;
- (void)bgmSelectedViewController:(id)a0 didClickLyricOnBtn:(BOOL)a1;
- (void)bgmSelectedViewController:(id)a0 didClickOSTOnBtn:(BOOL)a1;
- (void)bgmSelectedViewControllerWillClose:(id)a0;
- (void)bgmSelectedViewControllerDidClose:(id)a0;
- (void)bgmSelectedViewControllerWillStartPlayingVideo:(id)a0;
- (void)bgmSelectedViewControllerWillStopPlayingVideo:(id)a0;
- (unsigned long long)bgmSelectedViewControllerGetMaterialDuration:(id)a0;
- (void)bgmSelectedViewController:(id)a0 didEditMusic:(id)a1 atTabIndex:(unsigned long long)a2 index:(unsigned long long)a3;
- (void)_startMusicDownloadDetectTime;
- (void)_resetMusicDownloadDetectTime;
- (void)musicDownloadDetectTimerDidUpdate;
- (void)handleMusicSelectResult:(id)a0;
- (void)anchorMusicSegmentIfNeeded:(id)a0;
- (void)anchorMusicSegment:(id)a0;
- (void)anchorMusicSegmentInternal:(id)a0;
- (void)didFinishMusicPicking;
- (id)genMusicPanelReportDict;
- (void)enterLyricsEditingWithSegmentVM:(id)a0 completionHandler:(id /* block */)a1;
- (void)leaveLyricsEditing;
- (void)setupLyricEditingViews;
- (id)currentStyleEditingSegmentVM;
- (void)styleEditVC:(id)a0 didSelectedMaterial:(id)a1;
- (void)styleEditVC:(id)a0 didSelectedFont:(id)a1;
- (void)styleEditVC:(id)a0 didSelectedColor:(id)a1;
- (void)styleEditVC:(id)a0 didCancelWithBackupStyles:(id)a1 font:(id)a2 color:(id)a3 anim:(id)a4 needBackup:(BOOL)a5;
- (void)didDoneWithStyleEditVC:(id)a0;
- (void)bindHandleBox;
- (void)internalUpdateHandleBoxWithSettings:(id)a0;
- (void)handleSyncPositionWith:(id)a0;
- (void)updateHandleBoxOnFocusedSegmentDidChange;
- (void)updateHandleBoxOnTimelineDidMutate:(id)a0 options:(unsigned long long)a1;
- (void)updateHandleBoxOnSkimTimeDidChange;
- (void)overlayView:(id)a0 didTapCanvasAtPoint:(struct CGPoint { double x0; double x1; })a1;
- (void)handleOverlayViewSingleTapActionOnBackground;
- (void)handleOverlayViewSingleTapActionWithSegmentID:(id)a0;
- (void)overlayView:(id)a0 didDoubleTapOnHandleBox:(id)a1 atPoint:(struct CGPoint { double x0; double x1; })a2;
- (void)updateCurrentStoryElementSegmentHandleBoxWithStrokeColor:(id)a0;
- (void)overlayViewWillUpdatePosition:(id)a0;
- (void)overlayView:(id)a0 didUpdatePosition:(struct CGPoint { double x0; double x1; })a1;
- (void)overlayViewDidEndUpdatingPosition:(id)a0;
- (void)overlayViewWillUpdateRotation:(id)a0;
- (void)overlayView:(id)a0 didUpdateRotation:(double)a1;
- (void)overlayViewDidEndUpdatingRotation:(id)a0;
- (void)overlayViewWillUpdateScale:(id)a0;
- (void)overlayView:(id)a0 didUpdateScale:(double)a1;
- (void)overlayViewDidEndUpdatingScale:(id)a0;
- (void)syncSpatialInfoIfNeeded;
- (id)handleBoxItemsForSegmentVM:(id)a0 options:(unsigned long long)a1;
- (unsigned long long)handleBoxOptionsForSegmentVM:(id)a0 excludedOptions:(unsigned long long)a1;
- (void)showHandleBoxWithSegmentID:(id)a0;
- (void)showHandleBoxWithSegmentVM:(id)a0 options:(unsigned long long)a1;
- (void)showHandleBoxWithSegmentVM:(id)a0 options:(unsigned long long)a1 shouldStopPlaying:(BOOL)a2;
- (void)showHandleBoxWithSegmentID:(id)a0 borderStyle:(id)a1;
- (void)showHandleBoxWithSegmentVM:(id)a0 options:(unsigned long long)a1 borderStyle:(id)a2 shouldStopPlaying:(BOOL)a3;
- (void)removeHandleBox;
- (void)updateHandleBoxWithIsPlaying:(BOOL)a0;
- (void)addSafeAreaTipsView;
- (void)removeSafeAreaTipsView;
- (void)beginTrackingSafeArea;
- (void)endTrackingSafeArea;
- (void)handleBoxDeleteItemAction;
- (void)handleBoxEditItemContentAction;
- (void)handleBoxEditItemStyleAction;
- (void)handleBoxTrimItemAction;
- (void)handleBoxTTSItemAction;
- (void)handleBoxSyncPositionAction;
- (void)delayedTakingSnapshotAfterRotationOrScale;
- (void)internalTakeSnapshotAfterRotationOrScale;
- (void)enterTextEditingModeIfNeeded;
- (void)updateOverlayViewSpatialInfo;
- (void)handleMoreAction;
- (void)saveVideoToLocalAlbum;
- (void)exportAndPublish;
- (void)_exportAndPublishInnerV1;
- (void)_exportAndPublishInnerV2;
- (void)notifyComposingDidFinishWithVideoFileAtPath:(id)a0 userInfo:(id)a1;
- (void)notifyComposingDidFinishWithAsyncTask:(id)a0 userInfo:(id)a1;
- (void)notifyComposingDidFailWithError:(id)a0;
- (BOOL)shouldInterruptExportForFinderRedPackageEntry;
- (id)completeExportUserInfoIfNeeded:(id)a0;
- (BOOL)shouldShowVideoSaveTipVC;
- (void)showVideoSaveTipVC;
- (BOOL)isCurrentVideoComposingMatchToSave;
- (void)willShowCropInspector:(id)a0;
- (void)willDismissCropInspector:(id)a0 isFinished:(BOOL)a1;
- (void)beginClipSkimmingForEnterCropMode;
- (void)endClipSkimmingForExitCropMode;
- (void)transitionRenderView;
- (void)layoutCropForFixedHorizontalPaddingWithVideoAspectRatio:(double)a0;
- (void)layoutCropForFixedVerticalPaddingWithVideoAspectRatio:(double)a0;
- (void)dismissCropInspector:(id)a0 isFinished:(BOOL)a1;
- (void)bindCropInspector:(id)a0;
- (void)applyCroppedResultWithViewModel:(id)a0 resultRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)cropGestureCaptureView:(id)a0 handlePanGesture:(id)a1;
- (void)cropGestureCaptureView:(id)a0 handlePinchGesture:(id)a1;
- (void)showCropTipLabel;
- (void)removeCropTipLabel;
- (void)enterClipEditingWithNarration:(BOOL)a0 completionHandler:(id /* block */)a1;
- (void)enterClipEditingWithNarration:(BOOL)a0 popSubPanelType:(unsigned long long)a1 completionHandler:(id /* block */)a2;
- (id)createPanelViewWithInspectorView:(id)a0 panelHeight:(double)a1;
- (void)handleBackgroundTapActionForClipEditing;
- (void)setupClippingViewsWithNarration:(BOOL)a0;
- (void)addingButtonTouchUpInside:(id)a0;
- (void)insertPhotoVideoSegmentWithAssetInfos:(id)a0 completionHandler:(id /* block */)a1;
- (void)showCanvasPanel;
- (BOOL)dismissCanvasEditPanel;
- (void)canvasEditView:(id)a0 didChangeAspectRatio:(id)a1;
- (void)canvasEditView:(id)a0 didChangeContentScaleMode:(unsigned long long)a1;
- (void)updateWithOpDesc:(id)a0;
- (void)showReorderClipPanel;
- (BOOL)dismissReorderClipPanel;
- (void)showEditClipContentRangePanel;
- (BOOL)dismissEditClipContentRangePanel;
- (void)timelineViewControllerDidSelectAddMusic:(id)a0;
- (void)timelineViewControllerDidLongPress:(id)a0;
- (void)timelineViewController:(id)a0 didSelectTransition:(id)a1;
- (void)actionPanelViewController:(id)a0 showInspectorView:(id)a1;
- (void)willShowTransitionInspector:(id)a0;
- (void)willShowVoiceChangeInspector:(id)a0;
- (void)actionPanelViewController:(id)a0 dismissInspectorView:(id)a1 isFinished:(BOOL)a2;
- (void)willDismissTransitionInspector:(id)a0;
- (void)actionPanelViewControllerDidSelectRemove:(id)a0;
- (void)actionPanelViewControllerDidSelectCanvas:(id)a0;
- (void)actionPanelViewControllerDidSelectDigiZoom:(id)a0;
- (void)actionPanelViewControllerDidSelectReorder:(id)a0;
- (void)actionPanelViewControllerDidSelectContentRange:(id)a0;
- (void)actionPanelViewControllerDidSelectEditCaptionText:(id)a0;
- (void)actionPanelViewControllerDidSelectEditCaptionStyle:(id)a0;
- (void)actionPanelViewControllerDidSelectSpeechRecognition:(id)a0;
- (void)actionPanelViewControllerDidSelectSplit:(id)a0;
- (void)actionPanelViewControllerDidSelectRotate:(id)a0;
- (void)actionPanelViewControllerDidSelectBatchClipping:(id)a0 withType:(unsigned long long)a1 duration:(struct { long long x0; int x1; unsigned int x2; long long x3; })a2;
- (void)timelineReorderView:(id)a0 didSelectSegmentVM:(id)a1;
- (unsigned long long)nextAnticlockwiseContentRotationModeWithCurrentMode:(unsigned long long)a0;
- (void)MMImagePickerManagerDidCancel:(id)a0;
- (BOOL)shouldHandlePickingActionOutsideWithAssetInfos:(id)a0;
- (void)MMImagePickerManager:(id)a0 didFinishPickingWithAssetInfos:(id)a1 isUsingTemplate:(BOOL)a2;
- (id)assetPickerController:(id)a0 willFinishPickingAssets:(id)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 willSelectAsset:(id)a1 withCurrentState:(id)a2;
- (void)handleImagePickerDidFinishPickingMediaActionWithAssetInfos:(id)a0;
- (void)showBGMAdjustPanelVC;
- (void)bindBGMAdjustment;
- (void)syncBGMVolume:(float)a0;
- (void)syncOSTVolume:(float)a0;
- (void)didUpdateLyricShowingState:(BOOL)a0;
- (void)composingBGMAdjustPanelHalfScreenViewControllerWillClose:(BOOL)a0;
- (void)composingBGMAdjustPanelHalfScreenViewControllerDidClose:(BOOL)a0;
- (void)composingBGMAdjustPanelHalfScreenViewControllerDidChangeContentHeight:(double)a0;
- (struct CGSize { double x0; double x1; })renderSizeWithContainerSize:(struct CGSize { double x0; double x1; })a0;
- (struct CGSize { double x0; double x1; })maxRenderSizeShrinked;
- (struct CGSize { double x0; double x1; })maxRenderSizeExpanded;
- (double)composingPanelHeight;
- (double)backToStartTranslateWithPanelHeight:(double)a0 containsSlider:(BOOL)a1;
- (void)renderViewShrinkNoAnimationWithHeight:(double)a0;
- (void)animateRenderViewShrinkWithHeight:(double)a0 containsSlider:(BOOL)a1;
- (void)animateRenderViewExpandWithCompletion:(id /* block */)a0;
- (void)layoutRenderViewOnAspectRatioDidChange;
- (id)initWithViewModel:(id)a0;
- (void)_registerNotifications;
- (void)dealloc;
- (long long)preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)showKeyboardForMovieTitleIfNeeded;
- (void)viewWillDisappear:(BOOL)a0;
- (void)viewDidLayoutSubviews;
- (void)setupViews;
- (void)setupInitailContentTransitionViewIfNeeded;
- (void)removeInitailContentTransitionViewIfNeeded;
- (void)autoLayoutRenderView;
- (void)layoutViews;
- (void)bindViews;
- (void)setupGestures;
- (void)registerYReportSdk;
- (void)applicationDidEnterBackground:(id)a0;
- (void)applicationWillEnterForeground:(id)a0;
- (void)applicationWillResignActive:(id)a0;
- (void)applicationDidBecomeActive:(id)a0;
- (void)setState:(unsigned long long)a0;
- (void)willEnterState:(unsigned long long)a0;
- (void)willLeaveState:(unsigned long long)a0;
- (void)didEnterState:(unsigned long long)a0;
- (void)updatePlaybackButtonWithIsPlaying:(BOOL)a0;
- (void)updateHandleBoxWithMutationInfo:(id)a0;
- (void)leavePreviewing;
- (void)showExitConfirmTipWithExitHandler:(id /* block */)a0;
- (void)exitButtonTouchUpInside:(id)a0;
- (void)feedbackButtonTouchUpInside:(id)a0;
- (void)onClickShowTimelineButton:(id)a0;
- (void)skipMovieTilteInputGuideButtonTouchUpInside:(id)a0;
- (void)playButtonTouchUpInside:(id)a0;
- (void)backToStartAnimated:(BOOL)a0;
- (void)backToStartButtonTouchUpInside:(id)a0;
- (void)playbackControlViewValueChanged:(id)a0;
- (void)playbackControlViewTouchDown:(id)a0;
- (void)playbackControlViewTouchEnd:(id)a0;
- (void)handleBottomBarAction:(long long)a0;
- (void)bindToolbar;
- (void)toolbarPlayButtonTouchUpInside:(id)a0 withCompletionHandler:(id /* block */)a1;
- (void)toolbarUndoButtonTouchUpInside:(id)a0;
- (void)toolbarRedoButtonTouchUpInside:(id)a0;
- (void)reloadUndoRedoButtons;
- (id)mainPageViews;
- (void)hideMainPageViewsAnimated:(BOOL)a0 completion:(id /* block */)a1;
- (void)showMainPageViewsAnimated:(BOOL)a0 completion:(id /* block */)a1;
- (void)hideConfirmButtonAnimated:(BOOL)a0 completion:(id /* block */)a1;
- (void)showConfirmButtonAnimated:(BOOL)a0 completion:(id /* block */)a1;
- (void)updateConfirmButtonVisibilityAnimated:(BOOL)a0;
- (void)startPlayingUsingPlaybackConfigurationWithCompletionHandler:(id /* block */)a0;
- (void)setupPlayback;
- (void)teardownPlayback;
- (void)openAndResumePlayback:(BOOL)a0;
- (void)pauseAndClosePlayback;
- (void)playbackViewModelWillStartPlaying:(id)a0;
- (void)pagePanelView:(id)a0 didAppearPageAtIndex:(long long)a1;
- (void)pagePanelView:(id)a0 didDisappearPageAtIndex:(long long)a1;
- (void)clippingPanel:(id)a0 playButtonTouchUpInside:(id)a1;
- (void)clippingPanel:(id)a0 undoButtonTouchUpInside:(id)a1;
- (void)clippingPanel:(id)a0 redoButtonTouchUpInside:(id)a1;
- (void)clippingPanel:(id)a0 playbackProgressSliderValueDidChange:(id)a1;
- (void)clippingPanel:(id)a0 playbackProgressSliderTouchDown:(id)a1;
- (void)clippingPanel:(id)a0 playbackProgressSliderTouchEnd:(id)a1;
- (void)speedInspector:(id)a0 willSelectRawSpeedRatio:(long long)a1;
- (void)speedInspector:(id)a0 didSelectRawSpeedRatio:(long long)a1;
- (void)transitionInspectorDidSelectTransition:(id)a0;
- (void)timelineContentRangeEditView:(id)a0 didSelectSegmentVM:(id)a1;
- (void)timelineContentRangeEditView:(id)a0 didSkimToSegmentHeadAfterSelect:(id)a1;
- (void)timelineContentRangeEditView:(id)a0 selectedSegmentPlaybackTimeDidChange:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)timelineContentRangeEditView:(id)a0 selectedSegmentPlaybackDurationDidChange:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)bindExport;
- (void)exportProgressMaskViewDidCancel:(id)a0;
- (id)movieComposingBottomBarGetReportDict;
- (void)showTrimInspectorWithCancel:(id /* block */)a0 completion:(id /* block */)a1;
- (BOOL)isShowingTrimInspector;
- (BOOL)isShowingClipEditingInspector;
- (struct { long long x0; int x1; unsigned int x2; long long x3; })regulateTimecodeDurationWithPlaybackTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0 playbackTimeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })a1;
- (void)showInfiniteProgressToast;
- (void)showInfiniteProgressToastWithText:(id)a0;
- (void)showProgressToast;
- (void)showProgressToastWithText:(id)a0;
- (void)dismissProgressToast;
- (void)showSucceededToast;
- (void)showFailedToastWithText:(id)a0;
- (void)updateProgressToast:(double)a0 withText:(id)a1;
- (void)checkMemoryLeakOnExit;
- (BOOL)shouldAutorotate;
- (void)onBeginQuickReplyMsg;
- (void)onFinishQuickReplyMsg;
- (void)onShowQuickReplyAtSession:(id)a0 message:(id)a1;
- (void)dismissForVOIPEvents;
- (void)onMonoServiceMultitalkWillStart;
- (void)onMonoServiceVoipWillStart;
- (void)onMonoServiceWalkieTalkieWillStart;
- (void).cxx_destruct;

@end
