@class UIView, NSString, UIImpactFeedbackGenerator, MJShootComposingViewModel, MJToolbarButton, MMUIView, MJShootAIGCAsyncGenerationStateBar, WCActionSheet, MMUIButton, WCProgressMaskView;
@protocol MJShootPreviewViewControllerDelegate;

@interface MJShootPreviewViewController : MMUIViewController <MJShootComposingViewModelDelegate, MMWebViewDelegate, MJShootCropViewControllerDelegate, MJShootAIGCAsyncGenerationStateBarDelegate>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) UIView *renderView;
@property (retain, nonatomic) MMUIButton *exitButton;
@property (retain, nonatomic) MJToolbarButton *beautyButton;
@property (retain, nonatomic) MJToolbarButton *cropButton;
@property (retain, nonatomic) MMUIButton *moreButton;
@property (retain, nonatomic) MMUIButton *completeButton;
@property (retain, nonatomic) MMUIView *bottomBar;
@property (retain, nonatomic) MJShootAIGCAsyncGenerationStateBar *aigcAsyncGenerationStateBar;
@property (retain, nonatomic) WCActionSheet *aigcAsyncActionSheet;
@property (retain, nonatomic) WCProgressMaskView *progressMaskView;
@property (retain, nonatomic) UIImpactFeedbackGenerator *feedbackGenerator;
@property (nonatomic) BOOL isPresentingCropVC;
@property (nonatomic) BOOL isPresentingFeedbackVC;
@property (readonly, nonatomic) MJShootComposingViewModel *viewModel;
@property (weak, nonatomic) id<MJShootPreviewViewControllerDelegate> delegate;

- (void)setupViewModelDelegate;
- (void)shootComposingViewModel:(id)a0 recordingTimeDidChange:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1 maxRecordingDuration:(struct { long long x0; int x1; unsigned int x2; long long x3; })a2;
- (void)shootComposingViewModelOnAIGCProcessSucceed:(id)a0;
- (void)shootComposingViewModel:(id)a0 onAIGCProcessFailed:(id)a1;
- (void)_handleAIGCFinishActionInMaasSDKWithError:(id)a0;
- (id)_handleSDKAIGCError:(id)a0;
- (void)showAIGCFailedToast;
- (void)showAIGCRejectedToast;
- (void)showAIGCTimeoutToast;
- (void)showAIGCInsecurityToast;
- (void)presentFeedbackViewController;
- (void)webViewDidReturn:(id)a0;
- (void)exportAndPublish;
- (void)exportAndPresentMovieComposingVC;
- (void)exportAndSaveToPhotoLibrary;
- (void)saveExportAssetToPhotoLibraryWithFinishInfo:(id)a0 error:(id)a1 shouldShowSaveTip:(BOOL)a2;
- (void)showExportProgressView;
- (void)removeExportProgressView;
- (void)_startExportingVideoWithCompletion:(id /* block */)a0;
- (void)presentCropViewController;
- (void)cropViewController:(id)a0 didFinishCroppingWithSpatialDesc:(id)a1;
- (void)cropViewControllerDidMoveContent:(id)a0;
- (void)cropViewControllerDidScaleContent:(id)a0;
- (void)cropViewControllerDidTapOnRotate:(id)a0;
- (void)cropViewControllerDidTapOnFlip:(id)a0;
- (void)cropViewControllerDidTapOnReset:(id)a0;
- (void)registerAIGCSyncNotifications;
- (void)cancelAIGCSyncGenerationResultCheck;
- (void)didStartAIGCComposingInAssetGeneration:(id)a0;
- (void)didFinishAIGCComposingInAssetGeneration:(id)a0;
- (void)didFailedAIGCComposingInAssetGeneration:(id)a0;
- (void)checkAIGCContentIsGeneratedOrNot;
- (void)setupAndPrepareAIGCAsyncContentFromDraftWithCompletionHandler:(id /* block */)a0;
- (void)syncTaskCompletionStateFromServerWithCompletionHandler:(id /* block */)a0;
- (void)handleAIGCAsyncExitActionFromDraft;
- (void)registerAIGCAsyncNotifications;
- (void)unregisterAIGCAsyncNotifications;
- (void)_handleAIGCAsyncDidRecevieCreationResponseStart:(id)a0;
- (void)_handleAIGCAsyncDidRecevieCreationResponseNoti:(id)a0;
- (void)_handleAIGCAsyncDidRecevieQueryResponseNoti:(id)a0;
- (void)_handleAIGCAsyncDidSucceedInMaasSDKNoti:(id)a0;
- (void)_handleAIGCAsyncDidFailedInMaasSDKNoti:(id)a0;
- (void)cancelAIGCAsyncGenerating;
- (void)handleAIGCAsyncDraftExportActionWithFinishInfo:(id)a0;
- (void)handleAIGCAsyncDraftClipActionWithFinishInfo:(id)a0;
- (void)cleanUpCameraSessionWithCompletionHandler:(id /* block */)a0;
- (id)generateFinderVideoTemplateInfoWithRecordingFinishInfo:(id)a0;
- (void)showAIGCAsyncGenerationStateBar;
- (void)removeAIGCAsyncGenerationStateBar;
- (void)showAIGCAsyncGenerationCancelAlert;
- (void)_didCallOffCurrentAIGCAsyncGenerating;
- (void)aigcAsyncGenerationStateBarDidClickNotifyButton:(id)a0;
- (void)removeAIGCAsyncActionSheetIfNeeded;
- (void)_didLeaveShootComposingOnAIGCAsyncGenerating;
- (id)initWithViewModel:(id)a0;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)_registerNotifications;
- (void)_unregisterNotifications;
- (void)setupViews;
- (void)updateMainActionButtonsHiddenState:(BOOL)a0;
- (void)exitButtonTouchUpInside:(id)a0;
- (void)handleExitAction;
- (void)completeButtonTouchUpInside:(id)a0;
- (void)cropButtonTouchUpInside:(id)a0;
- (void)goToMovieComposing;
- (void)beautyButtonTouchUpInside:(id)a0;
- (void)goToFeedbackVC;
- (void)moreButtonTouchUpInside:(id)a0;
- (void)handleShootPreviewExportProgressNoti:(id)a0;
- (void)onApplicationWillResignActiveNotification:(id)a0;
- (void)onApplicationDidBecomeActiveNotification:(id)a0;
- (struct CGSize { double x0; double x1; })_calculateRenderViewSize;
- (void)disableMainFunctionButtonsExcludeExitButton;
- (void)enableMainFunctionButtonsExcludeExitButton;
- (void).cxx_destruct;

@end
