@class NSString, NSMutableArray, MMImagePickerManagerOptionObj;
@protocol MMImagePickerManagerDelegate;

@interface MMImagePickerManager : MMObject <MMImagePickerControllerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, ImageBrowseDelegate>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSMutableArray *tempImagePool;
@property (nonatomic) BOOL statusBarHidden;
@property (weak, nonatomic) id<MMImagePickerManagerDelegate> m_delegate;
@property (retain, nonatomic) MMImagePickerManagerOptionObj *optionObj;

+ (void)showWithOptionObj:(id)a0 inViewController:(id)a1;
+ (id)getImagePickerFromPhotoLibraryWithOptionObj:(id)a0 withManager:(id)a1;
+ (id)getImagePickerFromCameraWithOptionObj:(id)a0 withManager:(id)a1;
+ (id)getImagePickerControllerWithOptionObj:(id)a0;
+ (BOOL)isCaptureByImagePicker:(id)a0;

- (void)navigationController:(id)a0 didShowViewController:(id)a1 animated:(BOOL)a2;
- (void)navigationController:(id)a0 willShowViewController:(id)a1 animated:(BOOL)a2;
- (void)imagePickerController:(id)a0 didFinishPickingImage:(id)a1 editingInfo:(id)a2;
- (void)imagePickerController:(id)a0 didFinishPickingMediaWithInfo:(id)a1;
- (void)doActionsAfterTakenFromImagePicker:(id)a0;
- (void)imagePickerControllerDidCancel:(id)a0;
- (void)statusBarShowOniOS10;
- (void)MMImagePickerController:(id)a0 didFinishPickingMediaWithInfo:(id)a1;
- (void)MMImagePickerController:(id)a0 didFailToPickAssets:(id)a1;
- (void)MMImagePickerController:(id)a0 didFinishPickingImageWithEditImageAttr:(id)a1;
- (void)MMImagePickerManager:(id)a0 didFinishPickingAssetWithPostSession:(id)a1;
- (void)MMImagePickerControllerDidCancel:(id)a0;
- (void)MMImagePickerControllerDidSkip:(id)a0;
- (void)MMImagePickerControllerDidPopOrDismiss:(id)a0;
- (void)MMVideoPickerController:(id)a0 didFinishPickingMediaWithInfo:(id)a1;
- (void)MMVideoPickerController:(id)a0 didFinishPickingSightWithInfo:(id)a1;
- (void)MMVideoPickerController:(id)a0 didFinishPickingVideoWithAsset:(id)a1;
- (void)MMVideoPickerController:(id)a0 didFinishSelectingFinderDataItem:(id)a1;
- (void)MMImagePickerControllerDidCancelEditImage:(id)a0;
- (void)MMImagePickerControllerDidCancelEditImages:(id)a0 infos:(id)a1;
- (void)MMImagePickerControllerDidCancelEditVideo:(id)a0 infos:(id)a1;
- (void)MMImagePickerManagerDidWarning:(id)a0 warning:(id)a1 fromFinder:(BOOL)a2;
- (void)MMImagePickerManagerDidSendAssets:(id)a0 infos:(id)a1;
- (void)MMImagePickerManagerDidUnselected:(id)a0 infos:(id)a1;
- (void)MMImagePickerControllerDidCancelWithInfo:(id)a0 selectedAssets:(id)a1 finderData:(id)a2;
- (id)assetPickerController:(id)a0 willFinishPickingAssets:(id)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 willChangeUserActionCheckTo:(BOOL)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 didChangeUserActionCheckTo:(BOOL)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 willLoadPreviewForAsset:(id)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 didLoadPreviewForAsset:(id)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 willSelectAsset:(id)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 didSelectAsset:(id)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 willDeselectAsset:(id)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 didDeselectAsset:(id)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 willEditVideoAsset:(id)a1 withCurrentState:(id)a2;
- (id)assetPickerController:(id)a0 didEditVideoAsset:(id)a1 byEditAttr:(id)a2 withCurrentState:(id)a3;
- (id)onImagePreviewBrowserController:(id)a0 didCreateVideoCompositionActionFlow:(id)a1;
- (void)onImagePickerControllerClickFooterViewButton;
- (void)onImagePickerControllerOpenCamera;
- (void)onImagePickerControllerOpenFinderCamera:(id)a0;
- (void)onImagePickerControllerStartEditing;
- (void)onImagePickerControllerCancelEditing;
- (void)onImagePickerControllerStartPreview;
- (void)onImagePickerControllerCancelPreview;
- (void)onImagePickerControllerDidCancelSightCamera;
- (void)onImagePickerControllerDidTakeMedia;
- (void)onImagePickerControllerDidAppear;
- (void)onImagePickerControllerDidDisappear;
- (void)onImagePickerControllerStartExportingWithAssetId:(id)a0;
- (void)onImagePickerControllerEndExportingWithAssetId:(id)a0 error:(id)a1;
- (void)didSelectImage:(id)a0 fromImagePicker:(id)a1;
- (void)didSelectImage:(id)a0 Data:(id)a1 fromImagePicker:(id)a2;
- (void)didSelectImage:(id)a0 Data:(id)a1 imageInfo:(id)a2 fromImagePicker:(id)a3;
- (void)didSelectImage:(id)a0 Data:(id)a1 Finish:(BOOL)a2 fromImagePicker:(id)a3;
- (void)onNextStepWithPublishSelectAssetsDataItem:(id)a0;
- (void)onCancel;
- (void)onImagePickerControllerClickPostFinderLongVideoWithPostSession:(id)a0;
- (BOOL)shouldHandlePickingActionOutsideWithAssetInfos:(id)a0;
- (void)MMImagePickerController:(id)a0 didFinishPickingWithAssetInfos:(id)a1 isUsingTemplate:(BOOL)a2;
- (void)customBottomComposingButtonEnabledStateDidChange:(BOOL)a0;
- (id)customBottomComposingButtonForAssetPreviewing:(BOOL)a0;
- (void)showWithOptionObj:(id)a0 inViewController:(id)a1 delegate:(id)a2;
- (id)getImagePickerControllerWithOptionObj:(id)a0 delegate:(id)a1;
- (id)init;
- (void)addMonoServiceWithObj:(id)a0 inView:(id)a1;
- (void)OnShowWillFinished;
- (void)OnShowDidFinished;
- (void).cxx_destruct;

@end
