@class MMWebImageView, UILabel, MMMusicLocalFileDataInfo, SendAppMsgHandler, MMTipsViewController, CShakeChecker, MMMusicPageView, NSMutableArray, UIButton, NSString, MMMusicPlayerModeTipView, MMTimer, MMScrollView, MPVolumeView, MMMusicInfo, MMScrollActionSheet, MMMusicSliderControlView, UIImageView;

@interface MMMultipleMusicViewController : MMUIViewController <SendAppMsgHandleDelegate, UIScrollViewDelegate, MMScrollActionSheetDelegate, MMMusicPageViewDelegate, ShakeCheckerDelegate, IMusicPlayerExt, MMTipsViewControllerDelegate, FileDetailLogicDelegate> {
    MMScrollView *_musicPageScrollView;
    MMMusicPageView *_leftPageView;
    MMMusicPageView *_centerPageView;
    MMMusicPageView *_rightPageView;
    NSMutableArray *_musicInfoArray;
    MMMusicInfo *_curMusicInfo;
    int _numberOfPages;
    unsigned long long _currentPageIndex;
    SendAppMsgHandler *_sendAppMsgHandler;
    BOOL _isSingleLyricPage;
    float _offset;
    UIImageView *_bottomView;
    UIButton *_playMusicButton;
    MMTimer *_musicProgressTimer;
    MMMusicPlayerModeTipView *_transModeTipView;
    unsigned long long _pushedFromType;
    MMScrollActionSheet *_scrollActionSheet;
    CShakeChecker *_shakeChecker;
    BOOL _isOnShakeCheck;
    unsigned long long _beginShakeTime;
    unsigned long long _endShakeTime;
    unsigned long long _startEntranceTime;
    MMTipsViewController *_easterEggTipView;
    MMMusicPlayerModeTipView *_justOneSongTipView;
    MPVolumeView *m_viewAirPlay;
    UIButton *m_jumpOriginMusicView;
    MMWebImageView *m_sourceMusicIconImageView;
    UILabel *m_sourceMusicTitleLabel;
    UIImageView *m_arrowImageView;
    MMMusicSliderControlView *_sliderView;
    BOOL _bLayoutScrollView;
    BOOL _forceRestart;
}

@property (retain, nonatomic) MMMusicLocalFileDataInfo *fileLogicController;
@property (retain, nonatomic) MMScrollActionSheet *actionSheet;
@property (nonatomic) BOOL isFromShaking;
@property (nonatomic) long long playMode;
@property (retain, nonatomic) NSString *taskBizKey;
@property (nonatomic) unsigned long long enterMusicTime;
@property (nonatomic) BOOL bClickJumpButton;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithMusicInfo:(id)a0 withMusicListSource:(long long)a1 withOffset:(float)a2;
- (id)initWithMusicInfo:(id)a0 withMusicListSource:(long long)a1 withOffset:(float)a2 forceRestart:(BOOL)a3;
- (id)initFromBanner;
- (id)initFromLocalFileData:(id)a0;
- (void)initPageInfo;
- (unsigned long long)indexOfCurrentPage;
- (void)commonInit;
- (void)setPushedFromType:(long long)a0;
- (unsigned int)getSceneByPushFromType:(unsigned long long)a0;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)a0;
- (void)updateLogEntranceType;
- (void)viewWillBePushed:(BOOL)a0;
- (BOOL)shouldShowSearchPlayAllTip;
- (void)viewWillBePresented:(BOOL)a0;
- (void)viewDidBePoped:(BOOL)a0;
- (void)viewDidBeDismissed:(BOOL)a0;
- (void)viewDidDisappear:(BOOL)a0;
- (void)reportState;
- (void)beginPlayCurMusic;
- (void)viewWillDisappear:(BOOL)a0;
- (void)viewDidAppear:(BOOL)a0;
- (BOOL)useTransparentNavibar;
- (void)dealloc;
- (void)userDidTakeScreenshot:(id)a0;
- (void)initView;
- (void)updateButtomBtnColor:(id)a0;
- (void)initSelfView;
- (void)initNavigationItem;
- (void)initScrollView;
- (void)tileMusicPages;
- (void)setMusicPageDelegate;
- (void)initMusicPlayBtn;
- (void)initAirPlayBtn;
- (void)initSlider;
- (void)onClickJumpOriginMusicButton;
- (void)initJumpOriginMusicButton;
- (void)updateJumpOriginMusicView;
- (void)airPlayButtonTouchUpInside:(id)a0;
- (void)onRouteActiveChange:(id)a0;
- (void)onMinimizeMusicPlayer;
- (void)onPlayMusicBtnClicked;
- (id)getJumpToOriginMusicSheetItemWithMusicInfo:(id)a0;
- (id)getJumpToOriginMusicSheetItemWithMusicInfo:(id)a0 FromShowMore:(BOOL)a1;
- (void)onShowCommonMore:(id)a0;
- (void)showFileActionSheet:(id)a0;
- (void)addGestureRecognizers;
- (void)onSwipeScrollView;
- (void)scrollViewDidScroll:(id)a0;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)scrollViewWillEndDragging:(id)a0 withVelocity:(struct CGPoint { double x0; double x1; })a1 targetContentOffset:(inout struct CGPoint { double x0; double x1; } *)a2;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (void)updateMusicScrollView:(BOOL)a0;
- (void)updateMusicScrollViewByCurMusicInfo;
- (void)cancelSetShakePage;
- (void)OnGetSongAlbumUrl:(id)a0 AlbumUrl:(id)a1;
- (void)onLyricsChanged:(id)a0 Lyrics:(id)a1;
- (void)onMusicPlayStatusChanged;
- (void)onPlayMusic:(id)a0 fromScene:(long long)a1;
- (void)onPlayNextMusic;
- (void)onPlayPreviousMusic;
- (void)OnUpdateDuarationOnForeGround;
- (void)onDataBuffering:(double)a0;
- (void)onStopMusicListPlay;
- (id)getCoverImageData;
- (id)getUpLoadTask:(id)a0;
- (void)scrollActionSheet:(id)a0 didSelecteItem:(id)a1;
- (id)getMessageWrap:(id)a0;
- (void)setPlayMusicButtonImage:(BOOL)a0;
- (void)updatePlayBtn;
- (void)updateCurMusicInfo;
- (void)OnSendAppMsgOKToContacts:(id)a0;
- (void)onUpdateBottomBtnColor:(id)a0;
- (void)updateNavBarByColor:(id)a0;
- (void)updateNavBarTintColorByColor:(id)a0;
- (void)onFollowArrayUpToShowSecondPage;
- (void)onShowSecondPage;
- (void)onBack2FirstPage;
- (id)getPlayButton;
- (void)viewDidLayoutSubviews;
- (void)viewDidTransitionToNewSize;
- (void)layoutTipView;
- (void)layoutMusicPlayBtn;
- (void)layoutAirPlayBtn;
- (void)layoutScrollView;
- (void)layoutMusicPageView;
- (void)OnShake;
- (void)startShakeCheck;
- (void)transPlayMode;
- (void)showEasterEgg;
- (id)getEasterEggcontentTip;
- (void)playShakeSound;
- (void)playSoundByAQAudioPlayer:(id)a0 type:(id)a1;
- (void)onClickTipsBtn:(unsigned long long)a0;
- (id)getCurrentViewController;
- (id)getRightBarButtonItem;
- (void)onRevoked;
- (void)onRevokedReturn;
- (void).cxx_destruct;

@end
