@class MMOpenVoiceNetworkMgr, NSString, MMOpenVoiceAudioMgr, MMOpenVoiceVideoMgr, IConfSDKRegisterableCallbackHolder, MMOpenVoiceMemberMgr, VoIPConfSDKNativeCallbackMgr, MMOpenVoiceJoinRoomCGIImp, NSObject, MMConfSDKVideoHWenc, MMOpenVoiceRecorder, MMOpenVoiceSessionMgr;
@protocol OS_dispatch_queue;

@interface MMOpenVoiceService : MMUserService <ISysCallCheckExt, MonoServiceLogicExt, MMConfSDKVideoHWencDelegate, WCAudioModuleDelegate, MonoServiceMsgLogicDelegate, VoIPConfSDKNativeCallbackMgrDelegate, MMOpenVoiceAudioMgrDelegate, MMServiceProtocol> {
    NSObject<OS_dispatch_queue> *_workerQueue;
    MMOpenVoiceSessionMgr *_sessionMgr;
    MMOpenVoiceMemberMgr *_memberMgr;
    MMOpenVoiceAudioMgr *_audioMgr;
    MMOpenVoiceVideoMgr *_videoMgr;
    MMOpenVoiceNetworkMgr *_networkMgr;
    MMOpenVoiceJoinRoomCGIImp *_joinRoomImp;
    VoIPConfSDKNativeCallbackMgr *voipCallbackMgr;
    MMOpenVoiceRecorder *_recorder;
    IConfSDKRegisterableCallbackHolder *joinSucc;
    IConfSDKRegisterableCallbackHolder *joinFail;
    IConfSDKRegisterableCallbackHolder *talkSucc;
    IConfSDKRegisterableCallbackHolder *talkFail;
    IConfSDKRegisterableCallbackHolder *callBroken;
    IConfSDKRegisterableCallbackHolder *callExit;
    IConfSDKRegisterableCallbackHolder *sessionExpiredCallback;
    IConfSDKRegisterableCallbackHolder *memberChange;
    IConfSDKRegisterableCallbackHolder *videoMemberChange;
    IConfSDKRegisterableCallbackHolder *receiveCmdMsg;
    id /* block */ _currentInterruptedCallback;
    id /* block */ _currentMemberChangeCallback;
    id /* block */ _currentVideoMemberChangeCallback;
    id /* block */ _currentSpeakerChangedCallback;
    id /* block */ _currentReceiveCmdMsg;
    id /* block */ _currentEventCallback;
    int _currentStatus;
    BOOL _isQuitingRoom;
    NSString *_currentAppId;
    NSString *_busiAppId;
    NSString *_privateData;
    int _exitReason;
    BOOL _isJoiningRoom;
    BOOL _isInit;
    BOOL _isRequireExit;
    id /* block */ _pendingExitCallback;
    BOOL _isSyncJoinDone;
    BOOL _isCallbackJoinDone;
    BOOL _isCallbackTalkDone;
    BOOL _isCameraStarted;
    BOOL _isMicStarted;
    BOOL _isHandsFree;
    BOOL _isScreenStarted;
    BOOL _isForceCellularNetwork;
    long long _roomId;
    int _audioType;
    int _roomType;
    int _maxWidth;
    int _maxHeight;
    int _videoRatio;
    int _videoConfig;
    int _fixedVideoResolution;
    int _maxDecodeFPS;
    int _hwEncStatus;
    int _capW;
    int _capH;
    int _encStatusList[2];
    BOOL _isSWEncUsing;
    int _capStatus;
    MMConfSDKVideoHWenc *_hwEncoderList[2];
    struct __CVBuffer { } *_encodePixelBuffer;
    int _lastEncodePlaneWidth;
    int _lastEncodePlaneHeight;
    int _encodeWidth;
    int _encodeHeight;
    int _first5Frames;
    int _expectedRatio;
}

@property (nonatomic) BOOL enable720pCapture;
@property (nonatomic) BOOL enableDirectRendering;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)init;
- (void)dealloc;
- (void)OnSysCallState:(int)a0 andCallId:(id)a1;
- (void)onServiceTerminate;
- (void)setAudioActive:(BOOL)a0;
- (BOOL)isMonoServiceUIExist;
- (BOOL)isMonoServiceUIWorking;
- (BOOL)isMonoServiceCheckingServer;
- (void)onServiceInit;
- (void)onServiceEnterBackground;
- (void)onServiceEnterForeground;
- (void)onServiceClearData;
- (BOOL)resolveExternalConflicts;
- (void)joinConference:(id)a0 joinCallback:(id /* block */)a1 interruptedCallback:(id /* block */)a2 memberChangeCallback:(id /* block */)a3 videoMemberChangeCallback:(id /* block */)a4 speakerChangeCallback:(id /* block */)a5 receiveCmdMsgCallback:(id /* block */)a6 eventCallback:(id /* block */)a7;
- (void)joinConferenceSync:(id)a0 joinCallback:(id /* block */)a1 interruptedCallback:(id /* block */)a2 memberChangeCallback:(id /* block */)a3 videoMemberChangeCallback:(id /* block */)a4 speakerChangeCallback:(id /* block */)a5 receiveCmdMsgCallback:(id /* block */)a6 eventCallback:(id /* block */)a7;
- (void)join1v1Conference:(id)a0 joinCallback:(id /* block */)a1 interruptedCallback:(id /* block */)a2 memberChangeCallback:(id /* block */)a3 videoMemberChangeCallback:(id /* block */)a4 speakerChangeCallback:(id /* block */)a5 eventCallback:(id /* block */)a6;
- (void)join1v1ConferenceSync:(id)a0 joinCallback:(id /* block */)a1 interruptedCallback:(id /* block */)a2 memberChangeCallback:(id /* block */)a3 videoMemberChangeCallback:(id /* block */)a4 speakerChangeCallback:(id /* block */)a5 eventCallback:(id /* block */)a6;
- (id)minimizationHostForAppid:(id)a0;
- (void)joinRoomImp:(id)a0 groupId:(id)a1 nonceStr:(id)a2 timeStamp:(int)a3 joinRoomCallback:(id /* block */)a4 shouldMuteMicroPhone:(BOOL)a5;
- (void)furtherJoinCheck:(long long)a0 IOpenVoiceCallback:(id /* block */)a1 shouldMuteMicroPhone:(BOOL)a2;
- (void)setUpLongTermCallbackAfterJoin;
- (void)tryTriggerSucc:(id /* block */)a0 shouldMuteMicroPhone:(BOOL)a1;
- (void)callbackDeviceStartFailed:(id /* block */)a0 errCode:(int)a1;
- (void)suspendByExitRequest:(id /* block */)a0;
- (void)cleanUpJoinStatus;
- (void)startListenNetworkChange;
- (void)stopListenNetworkChange;
- (int)initWithSession:(id)a0;
- (void)callbackJoinConference:(id /* block */)a0 errType:(int)a1 errCode:(int)a2 errMsg:(id)a3;
- (BOOL)isVoIPWorking;
- (BOOL)isVideoVoIPWorking;
- (BOOL)isVoIPWorkingForAppId:(id)a0;
- (BOOL)isVoIPMuteMicroPhoneForAppId:(id)a0;
- (void)showConflictAlertForVoIP;
- (id)getConflictWording;
- (void)pauseCameraIfInVideoRoom;
- (void)resumeCameraIfInVideoRoom;
- (void)exitConference:(id /* block */)a0;
- (void)exitConference:(id /* block */)a0 reason:(int)a1;
- (int)convertReason:(int)a0;
- (int)exitConferenceSyncWithReason:(int)a0;
- (void)cleanUpLongTermCallbacks;
- (void)subscribe:(id)a0 callback:(id /* block */)a1;
- (void)updateConfig:(id)a0 callback:(id /* block */)a1;
- (void)mayRelease;
- (int)resetSync;
- (void)insertView:(id)a0 callback:(id /* block */)a1;
- (void)updateView:(id)a0 callback:(id /* block */)a1;
- (void)removeView:(id)a0 callback:(id /* block */)a1;
- (long long)getCurrentRoomId;
- (BOOL)getEnable720pCapture;
- (void)checkEnable720pCapture;
- (int)GetEncWidth:(int)a0 rmtDispW:(int)a1 rmtDispH:(int)a2 mode:(int)a3;
- (void)CloseCodec:(int)a0 codecFlag:(int)a1;
- (BOOL)doQosCtrl:(int)a0;
- (void)onVideoCapture:(struct __CVBuffer { } *)a0 orien:(int)a1;
- (void)onVideoFrame:(int)a0 data:(const char *)a1 dataLen:(int)a2 width:(int)a3 height:(int)a4 format:(int)a5;
- (void)onCameraSwitch:(BOOL)a0;
- (void)onMicSwitch:(BOOL)a0;
- (void)onAudioData:(char *)a0 length:(unsigned int)a1 timestamp:(double)a2;
- (int)gotEncodedData:(id)a0 isKeyFrame:(BOOL)a1 codecType:(int)a2 encIdx:(int)a3 isScreen:(BOOL)a4;
- (int)gotXpsData:(id)a0 codecType:(int)a1 encIdx:(int)a2 isScreen:(BOOL)a3;
- (int)gotEncodeErrCode:(int)a0 encIdx:(int)a1;
- (void)forceExitRoom:(int)a0;
- (void)notifyEventCallback:(int)a0 data:(id)a1;
- (int)sendCmdData:(id)a0 targetMemberId:(int)a1;
- (void)callIfNotNil:(id)a0 errCode:(int)a1 data:(id)a2 callbackData:(id)a3;
- (void)OnConfEvent:(int)a0 errCode:(int)a1 data:(id)a2 callbackData:(id)a3;
- (void)takeSnapshotWithOpenId:(id)a0 complete:(id /* block */)a1;
- (void)startRecordWithOpenId:(id)a0 complete:(id /* block */)a1;
- (void)stopRecordWithOpenId:(id)a0 complete:(id /* block */)a1;
- (void)setBackgroundEffectMode:(id)a0 mode:(int)a1 enable:(BOOL)a2 complete:(id /* block */)a3;
- (void)requestFullScreenWithOpenId:(id)a0 direction:(int)a1 complete:(id /* block */)a2;
- (void)exitFullScreenWithOpenId:(id)a0 complete:(id /* block */)a1;
- (void).cxx_destruct;

@end
