@class ContactsSelectionPreviewViewController, MultiSelectContactsSelectionOperation, NSDictionary, WCSearchBar, RecommendAlreadyHadGroupPageSheetView, UIBarButtonItem, NSIndexPath, NSMutableArray, NSString, RecommendAlreadyHadGroupListViewController, ChatRoomHistoryShareStat, MultiSelectContactsInChatRoomReport, NSMutableDictionary, ContactSelectToolView, NSArray, UIButton, UIView, MMPageSheetAdapter, ContactSelectView, SelectOpenIMContactsViewController, GroupSelectContactsViewController, WCColorProxy, ContactSelectDropDownHalfScreenView, ContactsSearchController, NewContactsSearchPanelView;
@protocol MultiSelectContactsViewControllerDelegate;

@interface MultiSelectContactsViewController : MMUILandscapeSheetViewController <RecommendAlreadyHadGroupPageSheetViewDelegate, MessagePageSheetAdapterDelegate, SameRecommendRoomMsgContentViewDelegate, SelectTagContactsViewControllerDelegate, ContactSelectViewDelegate, SelectOpenIMContactsViewControllerDelegate, ContactPickerViewDelegate, RoomContactSelectDelegate, IChatRoomHistoryUploadExt, WCSearchDelegate, WCDataSearchDelegate, WCMomentsContactTagListViewControllerDelegate, WCMomentsHistoryGroupSelectViewControllerDelegate, MultiSelectContactsViewControllerDelegate, ContactsSearchControllerDelegate, ContactsSelectionPreviewViewControllerDelegate, MMPageSheetAdapterDelegate, ContactSelectDropDownHalfScreenViewDelegate, MMDropDownHalfScreenViewDelegate, RecommendAlreadyHadGroupListViewControllerDelegate, WCActionSheetDelegate, NewContactsSearchPanelViewDelegate, GroupSelectContactsViewControllerDelegate> {
    NSIndexPath *m_indexPathToBeDeleted;
    NewContactsSearchPanelView *m_panelView;
    ContactSelectView *m_selectView;
    ContactSelectToolView *m_toolView;
    MultiSelectContactsInChatRoomReport *m_multiSelectContactsInChatRoomReport;
    UIView *_tableFooterView;
    NSString *nsCurrentSearchText;
    NSMutableDictionary *m_dicMultiOpenIMContactSelect;
    NSMutableDictionary *m_dicContactSelectFromGroup;
    NSMutableArray *m_wcTimeLineBlackMemListBlock;
    NSMutableArray *m_wcTimeLineBlackMemListHide;
    NSString *m_historyUploadTaskId;
    NSArray *m_selectedMsgList;
    ChatRoomHistoryShareStat *m_roomHistoryStat;
    double m_baseBottomBarHeight;
    double m_keyboardHeight;
    NSMutableArray *m_hadSeleteContactBeforSearch;
    NSMutableDictionary *m_dicMemberContactFromImportGroup;
    WCSearchBar *m_newSearchBar;
    BOOL m_updatingView;
    BOOL m_needToFixPanelViewLayout;
    BOOL m_hadFirstLoadView;
    ContactSelectDropDownHalfScreenView *m_contactSelectDropDownView;
    UIView *m_searchResultHeaderView;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL bOldHistoryMsgUploadSucc;
@property (nonatomic) BOOL bNewHistoryMsgUploadFinish;
@property (nonatomic) BOOL bShouldDelayUpdatePanelBtnAndToolViewSelectedContacts;
@property (retain, nonatomic) UIView *headerBarView;
@property (retain, nonatomic) UIView *mainContainerView;
@property (weak, nonatomic) SelectOpenIMContactsViewController *selectOpenIMContactsViewController;
@property (weak, nonatomic) GroupSelectContactsViewController *groupSelectContactsViewController;
@property (weak, nonatomic) WCSearchBar *searchBar;
@property (weak, nonatomic) ContactsSearchController *searchController;
@property (retain, nonatomic) NSMutableArray *searchControllerSelectedContacts;
@property (weak, nonatomic) ContactsSelectionPreviewViewController *selectionPreviewViewController;
@property (weak, nonatomic) MMPageSheetAdapter *pageSheetAdapter;
@property (retain, nonatomic) NSString *reportSessionId;
@property (nonatomic) long long bottomPanelOmitCount;
@property (nonatomic) BOOL ifExtendPanel;
@property (nonatomic) long long halfPanelOmitCnt;
@property (retain, nonatomic) NSMutableArray *selectionOperations;
@property (retain, nonatomic) MultiSelectContactsSelectionOperation *contactSelectViewSelectionOperation;
@property (retain, nonatomic) RecommendAlreadyHadGroupPageSheetView *alreadyHadGroupPageSheetView;
@property (retain, nonatomic) RecommendAlreadyHadGroupListViewController *alreadyHadGroupListViewController;
@property (nonatomic) unsigned int pushPageSheetMsgControllerAppearType;
@property (retain, nonatomic) NSString *pushPageSheetMsgControllerSelectGroupUserName;
@property (nonatomic) unsigned int pushPageSheetMsgControllerSelectGroupMemberCount;
@property (weak, nonatomic) id<MultiSelectContactsViewControllerDelegate> m_delegate;
@property (retain, nonatomic) NSDictionary *m_dicExistContact;
@property (retain, nonatomic) NSString *existContactSelectToast;
@property (retain, nonatomic) NSDictionary *m_dicIgnoreContact;
@property (retain, nonatomic) NSDictionary *m_dicDisabledContact;
@property (nonatomic) BOOL m_bShowHistoryGroup;
@property (nonatomic) BOOL m_bShowContactTag;
@property (nonatomic) BOOL m_bShowBlackListBlockFromTL;
@property (nonatomic) BOOL m_bShowBlackListHideFromTL;
@property (nonatomic) BOOL m_bShowRadarCreateRoom;
@property (nonatomic) BOOL m_bKeepCurViewAfterSelect;
@property (nonatomic) BOOL m_onlyChatRoom;
@property (nonatomic) BOOL m_bShowSelectFromGroup;
@property (nonatomic) unsigned int m_uiGroupScene;
@property (retain, nonatomic) NSMutableDictionary *m_dicMultiSelect;
@property (retain, nonatomic) UIButton *m_panelBtn;
@property (retain, nonatomic) UIBarButtonItem *m_panelBtnItem;
@property (nonatomic) unsigned long long m_memberCountLimit;
@property (nonatomic) unsigned long long m_commonSearchScene;
@property (nonatomic) unsigned long long m_scene;
@property (nonatomic) BOOL m_hideFavourContact;
@property (retain, nonatomic) NSString *customSubTitle;
@property (retain, nonatomic) NSString *overLimitToast;
@property (retain, nonatomic) NSString *overLimitAlert;
@property (nonatomic) BOOL hideSelfContact;
@property (nonatomic) BOOL m_onlyImportChatRoom;
@property (nonatomic) BOOL m_bSecondaryPage;
@property (nonatomic) BOOL m_isHiddenSearchShowAllTags;
@property (retain, nonatomic) NSString *m_presetsQuery;
@property (retain, nonatomic) WCColorProxy *colorProxy;
@property (nonatomic) BOOL m_bSearchSnsContact;
@property (retain, nonatomic) NSString *m_selectedUsername;
@property (retain, nonatomic) NSString *m_viewcontrllerTitle;
@property (retain, nonatomic) NSString *m_rightBarButtonTitle;
@property (nonatomic) long long m_rightBarButtonSelectedStyle;
@property (copy, nonatomic) NSString *headerBarText;
@property (retain, nonatomic) UIView *customContactListFooterView;
@property (retain, nonatomic) NSString *noResultTipText;
@property (nonatomic) BOOL useNewSearchControllerAndBottomBar;
@property (nonatomic) BOOL isInPageSheetMode;
@property (nonatomic) BOOL useNewSearchBarInChatRoom;
@property (nonatomic) unsigned int reportBizInChatRoomEnterType;
@property (nonatomic) unsigned long long reportBizType;
@property (nonatomic) BOOL isRemovingMember;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)setTitleInPageSheetModeIfNeeded:(id)a0;
- (void)setSubTitleInPageSheetModeIfNeeded:(id)a0;
- (void)initLeftBarItemInPageSheetModeIfNeeded:(BOOL)a0;
- (void)initRightBarItemInPageSheetModeIfNeeded;
- (void)updateMultiSelectRightBarItemInPageSheetModeIfNeeded;
- (void)updateRightBarItemEnabledInPageSheetModeIfNeeded:(BOOL)a0;
- (double)getContentViewYInPageSheetMode;
- (double)getVisibleHeight;
- (void)onCancelInPageSheetMode:(id)a0;
- (void)onDoneInPageSheetMode:(id)a0;
- (BOOL)checkAllSameRecommendAlreadyHadGroup;
- (BOOL)CheckIsNewGroupCreateGroupSelectGroupNewStype;
- (BOOL)CheckIsShowCreateChatSectionHeadViewInCreateGroup;
- (void)showCheckAllSameRecommendAlreadyHadGroupPageSheetView:(id)a0;
- (void)pushPageSheetMsgControllerForClickHadMMGroupList:(id)a0 tagetViewController:(id)a1;
- (void)pushPageSheetMsgController:(id)a0 tagetViewController:(id)a1 appearType:(unsigned int)a2;
- (id)getCurrentTopViewController;
- (void)hidePanelViewKeyboard;
- (unsigned int)getMsgPageSheetMoreOptionMask;
- (void)customPushOtherLogicController:(id)a0 fromViewController:(id)a1 animated:(BOOL)a2 complete:(id /* block */)a3;
- (void)pushPageSheetMsgControllerInRecommendAlreadyHadGroupCell:(id)a0 groupIndex:(unsigned int)a1 appearType:(unsigned int)a2 groupListNum:(unsigned int)a3;
- (void)onClickFullscreenSameRecommendChatRoom:(id)a0;
- (id)getViewController;
- (void)clickContinuCreateGroupInAlreadyHadGroupPageSheetView;
- (void)pushPageSheeteMsgControllerInRecommendAlreadyHadGroupPageSheet:(id)a0 tagetViewController:(id)a1 groupIndex:(unsigned int)a2;
- (void)pushPageSheetMsgControllerInRecommendAlreadyHadGroup:(id)a0 groupIndex:(unsigned int)a1;
- (void)startDataReportSession;
- (void)recordContactSelectionWithType:(unsigned long long)a0 selectionCount:(unsigned long long)a1 selectionFriCount:(unsigned long long)a2;
- (void)recordContactSelectViewSelection;
- (void)recordBottomPanelDeselectContact;
- (void)recordPreviewHalfScreenExposed;
- (void)recordPreviewHalfScreenDeselectContact;
- (void)endDataReportSessionWithDone:(BOOL)a0 originCount:(unsigned long long)a1 submitCount:(unsigned long long)a2;
- (void)reportSearchOperationWithDone:(BOOL)a0 objectType:(unsigned long long)a1 selectedCount:(unsigned long long)a2 querySplitCount:(unsigned long long)a3 multiSelectedFlag:(BOOL)a4;
- (void)doMultiSelectContactsInChatRoomReportWithExitScene:(unsigned int)a0;
- (void)recordContactSearchSelectionWithContact:(id)a0;
- (void)recordContactSelectionWithContact:(id)a0;
- (void)recordDeleteBackWordsInSearchCnt;
- (void)recordClkClearAllButtonCnt;
- (void)recordContactSelectionWithType:(unsigned int)a0 arrSelectionContact:(id)a1;
- (void)initReportCreateGroup;
- (void)reportCreatGroupSameRecommendReportExposure:(unsigned int)a0 groupListNum:(unsigned int)a1;
- (void)reportCreatGroupSameRecommendReporSameAddNewGroup:(unsigned int)a0;
- (void)reportCreatGroupSameRecommendReportClickHadMMGroupList:(id)a0;
- (void)reportCreatGroupSameRecommendReportClick:(unsigned int)a0 groupListNum:(unsigned int)a1 nsUserName:(id)a2 groupIndex:(unsigned int)a3;
- (void)reportCreatGroupSameRecommend:(id)a0;
- (id)init;
- (void)initData;
- (long long)overrideUserInterfaceStyle;
- (id)getSearchPanelOrSearchController;
- (BOOL)shouldShowSelectContactViewInBottomToolView;
- (void)UpdateForChatGroup:(id)a0;
- (void)onGroupSelectContactReturn:(id)a0;
- (void)onGroupMultiSelectContactReturn:(id)a0;
- (void)popGroupSelectContactsViewController:(id)a0 animated:(BOOL)a1;
- (BOOL)contactTagListViewController:(id)a0 shouldSelectContactTag:(id)a1;
- (void)contactTagListViewController:(id)a0 didSelectContactTag:(id)a1;
- (void)contactTagListViewControllerDidEndSearchWithDone:(BOOL)a0 selectedCount:(unsigned long long)a1 multiSelectedFlag:(BOOL)a2;
- (void)historyGroupSelectViewController:(id)a0 didSeletedContacts:(id)a1;
- (void)handleSelectedHistoryGroupContacts:(id)a0;
- (BOOL)isIgnore:(id)a0;
- (BOOL)isExisted:(id)a0;
- (void)updatePanelBtn;
- (unsigned int)getContactFromImportGroup:(id)a0;
- (void)updatePanelBtnAndToolViewSelectedContacts;
- (void)updatePanelView:(id)a0;
- (void)updateToolViewSelectedContacts;
- (void)updateMultiSelect:(id)a0;
- (void)updateMultiSelect:(id)a0 fromInputView:(BOOL)a1;
- (void)updateMultiSelect:(id)a0 fromRecommendSection:(BOOL)a1 fromInputView:(BOOL)a2 needReloadTableView:(BOOL)a3;
- (BOOL)checkIsShowRecommendAlreadyHadGroup;
- (void)updateSelectContactDataChange;
- (id)getCurrentGroupSelectContactsViewController;
- (void)onCancel:(id)a0;
- (void)actionCancel;
- (void)onDone:(id)a0;
- (void)actionDone;
- (void)initTitleArea;
- (void)initTitleAreaInPageSheetMode;
- (id)createInitRightBarItem;
- (id)createInitLeftBarItem:(BOOL)a0;
- (void)updateRightBarItemEnabled:(BOOL)a0;
- (BOOL)checkUseNewSearchBarInChatRoom;
- (void)initContactSelectDropDownView;
- (void)handleViewDidLayoutSubviewsInNewSearchBar;
- (void)didClickImageAtIndexInNewSearchBar;
- (id)getSearchResultHeaderView;
- (id)getSearchSectionHeaderMultiSelectContactButton;
- (void)onSearchSectionHeaderViewMultiSelectBtnChange;
- (BOOL)isMultiSelectInSearchSectionHeaderView;
- (void)updateMultiSelectPanelViewResultView;
- (void)resetSearchPanelViewAccessibilityInNewSearchBar;
- (void)onDropDownHalfScreenViewContactDidSelected:(id)a0;
- (void)onDropDownHalfScreenViewContactDidHide:(id)a0;
- (void)handleHalfScreenViewContactDidHideSearchMultiKey:(id)a0;
- (void)onDropDownHalfScreenViewHiddenExpandView;
- (void)initHeaderBar;
- (void)updateHeaderBar;
- (double)getHeaderBarViewHeight;
- (double)getVisibleHeightExcludeHeaderBar;
- (void)initBottomArea;
- (void)fireSmartGroupLogic;
- (void)fireSmartGroup;
- (void)onNavigationBarBackgroundColorChange;
- (BOOL)showNavigationBarSepLine;
- (void)initView;
- (void)alignPanelViewToNewSearchBarView;
- (void)onUpdateEmptyViewHidden:(BOOL)a0;
- (void)viewDidLoad;
- (void)updateSelectedHeadImgView;
- (void)removeSelectedHeadImgView:(id)a0;
- (void)viewWillBePushOrPresent:(BOOL)a0;
- (void)viewDidBePushOrPresent:(BOOL)a0;
- (void)viewDidBePopedOrDismissed:(BOOL)a0;
- (void)viewDidPopOrDismiss:(BOOL)a0;
- (void)viewDidLayoutSubviews;
- (void)willAnimateRotationToInterfaceOrientation:(long long)a0 duration:(double)a1;
- (void)viewWillDisappear:(BOOL)a0;
- (void)dealloc;
- (void)updateMultiSelectView;
- (id)getContactSelectView;
- (double)getContentViewY;
- (void)resetSelectContactViewAndHistoryButton;
- (void)updateToolViewAnimatedWithToolViewHeight:(double)a0 viewTop:(double)a1 subViewTop:(double)a2;
- (void)updateToolViewWithToolViewHeight:(double)a0 viewTop:(double)a1 subViewTop:(double)a2;
- (Class)getContactSelectViewClass;
- (void)modifySearchController:(id)a0;
- (id)getPageSheetAdapter;
- (double)getSearchPanelViewHeight;
- (double)getSearchPanelHeadImagesize;
- (double)getSearchPanelInputViewHeight;
- (double)getSearchPanelCellSize;
- (id)navigationBarBackgroundColor;
- (BOOL)navigationBarBlurEffect;
- (long long)preferredStatusBarStyle;
- (unsigned long long)getTotalSelectCount;
- (unsigned long long)getTotalSelectCountInSearchController;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)onContactSelectSearchSections:(id)a0 sectionTitles:(id)a1 sectionResults:(id)a2;
- (void)onContactUpdatePickDataSection:(long long)a0 added:(BOOL)a1 deleted:(BOOL)a2 sections:(id)a3 sectionTitles:(id)a4 sectionResults:(id)a5;
- (void)onSelectHistoryGroup;
- (void)openChatRoomlistHalfScreen;
- (void)onSelectContactTag;
- (void)onSelectWowBlackListHide;
- (void)selectWowBlackListHide;
- (void)onSelectWowBlackListBlock;
- (void)selectWowBlackListBlock;
- (void)importWCTimeLineBlackList:(id)a0 selectionType:(unsigned long long)a1;
- (void)onSelectOpenIMGroup;
- (void)openSelectOpenIMHalfScreenWithConfigBlock:(id /* block */)a0;
- (void)onSelectRadarCreateRoom;
- (void)onSelectContactFromGroup;
- (BOOL)onFilterContactCandidate:(id)a0;
- (BOOL)hideFavourContactCandidate;
- (BOOL)getUseMultiSelectContactsNewStyle;
- (void)resetTokenPickLogic;
- (BOOL)isSearchMultiKey;
- (double)tableView:(id)a0 heightForFooterInSection:(long long)a1 sesseionType:(unsigned int)a2;
- (id)tableView:(id)a0 viewForFooterInSection:(long long)a1 sesseionType:(unsigned int)a2;
- (void)onCheckContactAsynSearchAllSameGroupChanged:(id)a0;
- (id)makeFiterContactToTagSearchView:(id)a0;
- (id)cellForSearchViewTable:(id)a0 index:(id)a1;
- (double)cellSeparatorLeftInsetForSearchViewTable:(id)a0;
- (double)heightForSearchViewTable:(id)a0;
- (void)didSearchViewTableSelect:(id)a0;
- (void)didSearchPanelSelectContact:(id)a0 indexPath:(id)a1;
- (void)didSearchControllerSelectContact:(id)a0 indexPath:(id)a1;
- (void)onContactSearchControllerDidFinishMultiSelect;
- (void)onContactSearchControllerDidSwitchMultiSelectMode:(BOOL)a0;
- (void)onContactSearchControllerDidCancelItemClick;
- (double)heightForPanelResultFooterInSection:(long long)a0;
- (id)viewForPanelResultFooterInSection:(long long)a0;
- (void)showExistContactTip:(id)a0;
- (void)doTagSearch:(id)a0 arrContacts:(id)a1;
- (BOOL)onShouldSelectContact:(id)a0;
- (BOOL)onShouldSelectContact:(id)a0 originSelectCount:(unsigned long long)a1;
- (void)onSelectContact:(id)a0;
- (void)onViewContact:(id)a0;
- (void)onCancelSelectContact;
- (void)onSelectSearchSnsContact:(id)a0;
- (void)onSelectNormalContact:(id)a0;
- (void)onSelectRecommendGroup:(id)a0;
- (void)onSelectClickMoreRecommendAlreadyHadGroup:(id)a0 searchMatchTip:(id)a1 dicSearchMatchTip:(id)a2 appearType:(unsigned int)a3;
- (id)onGetSortedMultiSelectUsrs;
- (void)onExistContactDidSelected:(id)a0;
- (BOOL)isContactSelectPanelViewSearching;
- (void)onNotifyWillDoAsyncRecommend:(id)a0;
- (id)getSafeSearchViewController;
- (void)onNotifyPanelViewResignFirstReponder;
- (BOOL)onPanelViewIsExistContact:(id)a0;
- (void)onPanelViewExistContactDidSelected:(id)a0;
- (void)onPanelViewTableViewHidden:(BOOL)a0;
- (BOOL)isCanMultiSelectInDidSelectRow;
- (BOOL)isCanSupportOnTouchesEndedRemoveToken;
- (id)onGetMultiSelectUsrs;
- (void)onSearchControllerViewDidLoad;
- (BOOL)onShouldSelectContactInSearchController:(id)a0;
- (id)getSearchText;
- (id)cellForSelectionPreviewViewTable:(id)a0 contact:(id)a1;
- (double)heightForSelectionPreviewViewTable;
- (void)didSelectionPreviewViewTableSelectContact:(id)a0;
- (void)onSelectionPreviewDone;
- (void)onSelectionPreviewViewControllerDidSelectAll;
- (void)onSelectionPreviewViewControllerDidDeselectAll;
- (BOOL)isSelectionPreviewAllSelected;
- (void)pageSheetWillClose:(id)a0 isManualTrigger:(BOOL)a1;
- (void)didClickImageAtIndex:(unsigned int)a0 withKey:(id)a1;
- (void)didDeleteLastWithKey:(id)a0;
- (void)searchTextFieldDidBeginEditing;
- (void)searchTextFieldWillClearText;
- (void)doSearch:(id)a0 Pre:(BOOL)a1;
- (void)cancelSearch;
- (void)onPanelViewAsyncGetRecommends:(id)a0;
- (void)onShowSearchContactTagViews;
- (void)onSelectDoneWithContacts:(id)a0;
- (BOOL)onShouldSelectOpenIMContact:(id)a0;
- (void)onSelectOpenIMContactReturn:(id)a0;
- (void)onSelectOpenIMDidEndSearchWithDone:(BOOL)a0 selectedCount:(unsigned long long)a1 multiSelectedFlag:(BOOL)a2;
- (void)popSelectOpenIMContactsVC:(id)a0 animated:(BOOL)a1;
- (void)onMultiSelectContactReturnForSns:(id)a0;
- (void)onMultiSelectContactCancelForSns;
- (BOOL)shouldShowTextState;
- (void)openMessageContentView:(id)a0;
- (id)getRoomHistoryStat;
- (void)onCreateChatRoom:(id)a0;
- (void)onSelectCancel;
- (void)reportRecommendInfo:(int)a0;
- (long long)findUsr:(id)a0 inContactArray:(id)a1;
- (id)getSessionContact;
- (BOOL)canSelectMsgHistory;
- (BOOL)shouldUseBottomToolView;
- (void)viewSessionHistory;
- (void)uploadMsgList:(id)a0;
- (id)generateTaskIdForMsgList:(id)a0;
- (BOOL)preAsyncUploadHistory;
- (void)onFailToUploadHistory:(id)a0;
- (void)onHistoryUploadFinish:(id)a0 uploadInfo:(id)a1 errMsg:(id)a2;
- (void)onHistoryUploadProgressChanged:(id)a0 total:(unsigned long long)a1 remain:(unsigned long long)a2;
- (void)onNewHistoryUploadFinish:(id)a0 uploadInfo:(id)a1;
- (void)keyboardWillShow:(id)a0;
- (void)keyboardWillHide:(id)a0;
- (void)onKeyboardNotification:(id)a0;
- (void)registerYReportSdk;
- (id)getContactsFromGroupContact:(id)a0;
- (void)appendContact:(id)a0 intoSet:(id)a1;
- (id)genHadSelectContactSet;
- (BOOL)canSelectContactWithoutMemberCountLimit:(id)a0;
- (BOOL)canSelectContactTagWithoutMemberCountLimit:(id)a0 selectedTag:(id)a1;
- (BOOL)checkNewTokenPickSearch;
- (id)pageSheetAdapter;
- (void)setPageSheetAdapter:(id)a0;
- (void).cxx_destruct;

@end
