@class APAuth, NSString, PublicWifiCache, APPortal, MMUIViewController, APCheck, APAccess, MMWebViewController, NSMutableDictionary, APCheckPwd, CContact, NSArray;

@interface PublicWifiManager : MMUserService <APAuthDelegate, APCheckDelegate, APAccessDelegate, APProtalDelegate, INetworkStatusMgrExt, APCheckPwdDelegate, MMServiceProtocol, MMKernelExt, MMWebViewDelegate>

@property (copy, nonatomic) NSString *currSSID;
@property (copy, nonatomic) NSString *currMAC;
@property (nonatomic) BOOL isWifiChanged;
@property (nonatomic) BOOL hasDoWifiManager;
@property (nonatomic) BOOL isOnWifi;
@property (nonatomic) unsigned int annotationExpire;
@property (nonatomic) BOOL isWaitingUserConfirm;
@property (nonatomic) BOOL isOpenUrlProcessing;
@property (retain, nonatomic) PublicWifiCache *cache;
@property (retain, nonatomic) APAuth *apAuth;
@property (retain, nonatomic) APCheck *apCheck;
@property (retain, nonatomic) APAccess *apAccess;
@property (retain, nonatomic) APCheckPwd *apCheckPwd;
@property (retain, nonatomic) APPortal *apPortal;
@property (nonatomic) BOOL isWaitingBindPhone;
@property (nonatomic) BOOL isRegisterHotspotInterface;
@property (retain, nonatomic) APCheckPwd *successedPwd;
@property (retain, nonatomic) APPortal *successedPortal;
@property (retain, nonatomic) MMWebViewController *abroadApAuthWebViewController;
@property (retain, nonatomic) MMUIViewController *connectWebViewControler;
@property (retain, nonatomic) NSString *proto4ToConnectSSID;
@property (retain, nonatomic) NSString *proto4ToConnectPassword;
@property (retain, nonatomic) NSMutableDictionary *knownProtocol3HotspotsList;
@property (retain, nonatomic) CContact *currContact;
@property (nonatomic) unsigned int gAnnotationSwith;
@property (retain, nonatomic) NSArray *networkList;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)dealloc;
- (id)init;
- (void)onServiceInit;
- (void)onServiceClearData;
- (void)onServiceEnterForeground;
- (void)onServiceEnterBackground;
- (void)onAuthOK;
- (void)onNetworkStatusChange:(unsigned int)a0;
- (void)handleOffWifi;
- (BOOL)isUserStayOnConnectingView;
- (id)getAbroadApAuthUrlWithSSID:(id)a0;
- (void)resetWaitingFlagWhenFailed;
- (void)webViewReturn:(id)a0;
- (void)didStartApAuth:(id)a0;
- (void)didSuccessOfApAuth:(id)a0;
- (void)didFailOfApAuth:(id)a0 withErrCode:(int)a1;
- (void)didExpiredOfApAuth:(id)a0;
- (void)didReadyOfApPortal:(id)a0;
- (void)didStartApPortal:(id)a0;
- (void)didSuccessOfAPPortal:(id)a0;
- (void)didFailOfAPPortal:(id)a0 errMsg:(id)a1;
- (void)didSuccessOfApCheck:(id)a0;
- (void)didFailOfApCheck:(id)a0 withErrCode:(int)a1;
- (void)didReadyWithApCheckPwd:(id)a0 protolType:(unsigned int)a1;
- (void)didRunningOfApCheckPwd:(id)a0;
- (void)didSuccessOfApCheckPwd:(id)a0;
- (void)gotoApAuthWithApCheckPwd:(id)a0 protolType:(unsigned int)a1;
- (void)gotoApPortalWithApCheckPwd:(id)a0 tid:(id)a1 openId:(id)a2 appid:(id)a3;
- (void)gotoFrontPageWithApPortal:(id)a0;
- (void)didFailedWithApCheckPwd:(id)a0 errorMsg:(id)a1;
- (void)onPublicWifiApInfoViewContorllerWillGoBack;
- (void)userConfirm;
- (int)stateOfApAuth;
- (id)ssidOfApAuth;
- (BOOL)shouldOpenWebview;
- (id)showUrlOfCurrApAuth;
- (void)cleanCache;
- (void)logout;
- (void)showBindPhoneViewFromFrontPage;
- (BOOL)isBindAboardPhone;
- (void)refreshApAuthPageIfNeed;
- (void)showGuidePageAfterScanQrCodeOfApPortal;
- (void)showErrorViewControllerWithErrMsg:(id)a0 fromViewContorller:(id)a1;
- (void)sendCloseEventToObserver;
- (void)delayConfig;
- (void)registerHotspotHelper;
- (BOOL)isHotspotValidAndInList:(id)a0 macAddr:(id)a1;
- (id)forgroundAppTask;
- (void).cxx_destruct;

@end
