@class CBaseContact, NSString, WCColorProxy, NSIndexPath, UILabel, NSMutableDictionary, SearchHelpDataItem, NSMutableArray, NewContactsSearchPanelView, NSMutableSet, MMTableView, WCSearcher;
@protocol TemplateContactSelectDelegate;

@interface TemplateContactSelectViewController : MMUIViewController <WCSearchDelegate, MMTableViewDelegate, UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, NewContactsSearchPanelViewDelegate, ChatRoomMemberGridViewDelegate, MMTableViewInfoDelegate, NewChatRoomMemberItemViewDelegate, IContactMgrExt> {
    MMTableView *m_tableView;
    NSMutableArray *m_arrRoomMembers;
    NSMutableArray *m_arrKeys;
    NSMutableDictionary *m_dicRoomMembers;
    NSMutableArray *m_arrFilterdFriends;
    NSMutableSet *m_setFilteredFriends;
    NSMutableDictionary *m_dicMatchTips;
    unsigned long long m_commonSearchScene;
    NSIndexPath *m_oSelectIndexPath;
    SearchHelpDataItem *m_searchHelpDataItem;
    UILabel *m_groupTipLabel;
}

@property (retain, nonatomic) CBaseContact *m_roomContact;
@property (weak, nonatomic) id<TemplateContactSelectDelegate> m_delegate;
@property (nonatomic) BOOL m_bHideSearchBar;
@property (nonatomic) BOOL m_bSortByTime;
@property (nonatomic) BOOL m_bSortByNameWithoutIndex;
@property (nonatomic) BOOL m_bCustomMakeCell;
@property (nonatomic) BOOL m_bEnableEdit;
@property (nonatomic) BOOL useBarButtonStyleBack;
@property (nonatomic) struct CGPoint { double x; double y; } m_bContentOffset;
@property (retain, nonatomic) NewContactsSearchPanelView *m_panelView;
@property (retain, nonatomic) WCSearcher *searcher;
@property (retain, nonatomic) WCColorProxy *colorProxy;
@property (retain, nonatomic) NSString *beginSearchText;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)init;
- (void)makeWhiteCell:(id)a0 CellInfo:(id)a1;
- (void)openContactInfo:(id)a0;
- (void)onModifyContact:(id)a0;
- (id)GetCompareStrByContact:(id)a0;
- (id)addSectionKey:(id)a0;
- (void)addContact:(id)a0;
- (id)getContactWith:(id)a0;
- (void)initData;
- (void)reloadView;
- (void)reloadMemberListAndView;
- (id)getMemberList;
- (void)initTableView;
- (void)initSearchBar;
- (Class)getNewContactsSearchPanelViewClass;
- (void)initView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)viewDidLayoutSubviews;
- (id)getSearchMatchTip:(id)a0;
- (id)getCachedSearchHelpDataItem;
- (BOOL)hasNoSearchResult;
- (id)getTableView;
- (id)getArrKeys;
- (id)navigationBarBackgroundColor;
- (BOOL)navigationBarBlurEffect;
- (long long)preferredStatusBarStyle;
- (void)OnDataChange;
- (void)onCancel:(id)a0;
- (void)onDone;
- (long long)numberOfSectionsInTableView:(id)a0;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (double)tableView:(id)a0 heightForRowAtIndexPath:(id)a1;
- (void)makeCell:(id)a0 contact:(id)a1 tableView:(id)a2 indexPath:(id)a3;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (id)getViewController;
- (void)didSelectContact:(id)a0;
- (void)tableView:(id)a0 didSelectRowAtIndexPath:(id)a1;
- (void)tableView:(id)a0 willDisplayCell:(id)a1 forRowAtIndexPath:(id)a2;
- (long long)tableView:(id)a0 editingStyleForRowAtIndexPath:(id)a1;
- (void)tableView:(id)a0 commitEditingStyle:(long long)a1 forRowAtIndexPath:(id)a2;
- (double)tableView:(id)a0 heightForHeaderInSection:(long long)a1;
- (id)tableView:(id)a0 viewForHeaderInSection:(long long)a1;
- (id)tableView:(id)a0 titleForHeaderInSection:(long long)a1;
- (double)tableView:(id)a0 heightForFooterInSection:(long long)a1;
- (id)tableView:(id)a0 viewForFooterInSection:(long long)a1;
- (void)wcsWillPresentSearch:(id)a0;
- (void)wcsDidPresentSearch:(id)a0;
- (void)wcsDidDismissSearch:(id)a0;
- (void)doSearch:(id)a0;
- (void)sortResultContact:(id)a0 matchTips:(id)a1;
- (void)wcsSearchBarTextDidBeginEditing:(id)a0;
- (void)wcsSearchBar:(id)a0 textDidChange:(id)a1;
- (void)wcsSearchBarSearchButtonClicked:(id)a0;
- (void)wcsSearchBarCancelButtonClicked:(id)a0;
- (void)didClickImageAtIndex:(unsigned int)a0 withKey:(id)a1;
- (void)didDeleteLastWithKey:(id)a0;
- (void)doSearch:(id)a0 Pre:(BOOL)a1;
- (id)cellForSearchViewTable:(id)a0 index:(id)a1;
- (double)heightForSearchViewTable:(id)a0;
- (void)didSearchViewTableSelect:(id)a0;
- (double)heightForPanelResultFooterInSection:(long long)a0;
- (id)viewForPanelResultFooterInSection:(long long)a0;
- (void).cxx_destruct;

@end
