@class CMessageWrap, NSString, VoIPNotificationContentInfo, NSRecursiveLock, AVVideoDevice, VOIPVideoRender, NSMutableDictionary, XImageViewRenderer, NSMutableArray, XImageContext, CContact;
@protocol IlinkMultiTalkDelegate, IVOIPVideoDeviceDelegate;

@interface VoIPilinkMgr : MMUserService <MMKernelExt, VoipUIManagerExt, MultitalkApiDelegate, ilinkApiDelegate, MonoServiceMsgDelegate, VoIPConfSDKServiceExtension, IVoipCXMgrExt, MMServiceProtocol> {
    char *mCameraBuf;
    char *mHWYUVbuffer;
}

@property (retain, nonatomic) NSString *clientGroupId;
@property (retain, nonatomic) CContact *remoteContact;
@property (nonatomic) BOOL isCameraSetOn;
@property (nonatomic) BOOL isLocalCaptureSuspended;
@property (nonatomic) double lastLocalCaptureSuspendedTimestamp;
@property (nonatomic) unsigned int callType;
@property (nonatomic) BOOL isMicMute;
@property (nonatomic) BOOL isSpeakerOn;
@property (retain, nonatomic) NSMutableArray *observsers;
@property (nonatomic) unsigned long long lastLocalCaptureFrameIndex;
@property (nonatomic) BOOL isLocalCaptureCheckingActiveContinually;
@property (nonatomic) BOOL isInBackground;
@property (nonatomic) BOOL mIsInterruptByPhoneCall;
@property (nonatomic) BOOL mIsPausedByInterrupt;
@property (nonatomic) unsigned long long exceptionType;
@property (nonatomic) BOOL isAlreadyHangup;
@property (nonatomic) unsigned int receiveMsgTime;
@property (nonatomic) BOOL mEnableDirectRendering;
@property (nonatomic) BOOL isActived;
@property (nonatomic) BOOL joinToRoom;
@property (retain, nonatomic) NSMutableDictionary *lowVersionMembers;
@property (retain, nonatomic) CMessageWrap *changeToMultiTalkMsg;
@property (nonatomic) unsigned long long cancelRoomId;
@property (nonatomic) int mCntTryStartAudioDev;
@property (nonatomic) BOOL isRenderFirstFrameRemote;
@property (nonatomic) BOOL isRenderFirstFrameLocal;
@property (nonatomic) BOOL isInviteInitEngineFail;
@property (nonatomic) BOOL isInviteDeviceWaiting;
@property (nonatomic) BOOL enableVoIPMPAudioUnit;
@property (nonatomic) BOOL isCallKit;
@property (nonatomic) BOOL acceptNewCall;
@property (retain, nonatomic) VoIPNotificationContentInfo *notificationContentInfo;
@property (nonatomic) int notificationPushType;
@property (nonatomic) BOOL startedSecondPart;
@property (nonatomic) BOOL hangupByCall;
@property (nonatomic) BOOL isLocalRendered;
@property (nonatomic) BOOL isRemoteRendered;
@property (nonatomic) BOOL isJoinedRoom;
@property (nonatomic) BOOL isInAudioInterruption;
@property (nonatomic) unsigned long long localCaptureUnactiveCount;
@property (weak, nonatomic) id<IVOIPVideoDeviceDelegate> m_videoDeviceDelegate;
@property (nonatomic) BOOL supportIlinkCloudService;
@property (nonatomic) BOOL isThisTalkIlink;
@property (nonatomic) BOOL isAudio;
@property (nonatomic) BOOL isCaller;
@property (nonatomic) BOOL isConnected;
@property (weak, nonatomic) id<IlinkMultiTalkDelegate> multiTalkDelegate;
@property (nonatomic) BOOL mIsLocalVideoClosed;
@property (nonatomic) BOOL mIsRemoteVideoClosed;
@property (nonatomic) BOOL mIsInterrupted;
@property (nonatomic) unsigned long long modeActionStatus;
@property (nonatomic) unsigned long long mRoomId;
@property (retain, nonatomic) NSString *callID;
@property (retain, nonatomic) NSString *mRemoteUserName;
@property (nonatomic) unsigned int mInviteId;
@property (retain, nonatomic) VOIPVideoRender *inputVideoRender;
@property (retain, nonatomic) VOIPVideoRender *outputVideoRender;
@property (retain, nonatomic) VOIPVideoRender *smallInputVideoRender;
@property (retain, nonatomic) VOIPVideoRender *smallOutputVideoRender;
@property (retain, nonatomic) NSRecursiveLock *outputVideoRenderLock;
@property (retain, nonatomic) NSRecursiveLock *inputVideoRenderLock;
@property (nonatomic) BOOL mIsMinimizeView;
@property (retain, nonatomic) NSRecursiveLock *smallOutputVideoRenderLock;
@property (nonatomic) long long m_videoOrientation;
@property (nonatomic) unsigned int remoteWxVer;
@property (retain, nonatomic) NSString *remoteSourceDevice;
@property (nonatomic) unsigned long long mStartTalkingTime;
@property (nonatomic) unsigned long long mStartAcceptTime;
@property (nonatomic) int remoteRatio;
@property (nonatomic) unsigned long long remoteCaptureStatus;
@property (nonatomic) unsigned int changeToCelluarCount;
@property (nonatomic) int netSpeed;
@property (nonatomic) BOOL shouldCheckLocalCaptureIsActive;
@property (readonly, nonatomic) AVVideoDevice *videoDevice;
@property (nonatomic) BOOL isIlinkFailed;
@property (nonatomic) BOOL changeToMultiTalk;
@property (retain) XImageViewRenderer *localViewRenderer;
@property (retain) XImageViewRenderer *remoteViewRenderer;
@property (retain, nonatomic) XImageContext *remoteImageContext;
@property (nonatomic) BOOL startWithExternalDevice;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)isHavingIlinkCall;
+ (BOOL)shouldSupportIlinkCloudService;
+ (BOOL)shouldSupportAddMembers;
+ (BOOL)startVoipViewByVoipMonoMsg:(id)a0;

- (void)handleSubCallWithInviteInfo:(id)a0 inviteMsg:(id)a1 wragMsg:(id)a2;
- (void)acceptSubCallWithInviteInfo:(id)a0 inviteMsg:(id)a1 wragMsg:(id)a2;
- (void)onServiceEnterBackground;
- (void)onServiceEnterForeground;
- (void)onServiceInit;
- (void)onServiceClearData;
- (void)appendObserver:(id)a0;
- (void)removeObserver:(id)a0;
- (void)commonSetup;
- (void)reset;
- (BOOL)getIfThisTalkIlink;
- (BOOL)getIfThisTalkIlinkButNotMultiTalk;
- (void)changeFloatingWindowStatus:(int)a0;
- (void)receiveCancelFromSDK:(unsigned long long)a0 usrName:(id)a1;
- (void)makeMonoMsg:(unsigned long long)a0 usrName:(id)a1 msgType:(unsigned int)a2;
- (void)tryAddMembersForIlink:(id)a0;
- (void)onDidSelectNormalContact:(id)a0;
- (void)onIlinkChangeToMultiTalk:(id)a0;
- (void)onMultiTalkVCHangupWithGroup:(id)a0 isClickHangup:(BOOL)a1 isInviterQuitEarly:(BOOL)a2;
- (id)getLowVersionMembers;
- (id)getCallerName;
- (void)startRecord:(int)a0 channels:(int)a1 frameDuration:(int)a2;
- (void)startPlay:(int)a0 channels:(int)a1 frameDuration:(int)a2;
- (void)VoIPMPReleaseDevice;
- (unsigned long long)getCurrentRoomMembersCount;
- (void)voIPAudioServiceDidStartAudioUnitButFailed;
- (void)voIPAudioServiceInterruptionBegin;
- (void)voIPAudioServiceInterruptionEnd;
- (void)voIPAudioServiceQuitCompulsivelyFromInterruption;
- (void)BeginInterruption;
- (void)EndInterruption;
- (void)interruptVoipByNonPhoneCall;
- (void)restartAudioDevice;
- (void)OnSysCallState:(int)a0 andCallId:(id)a1;
- (void)interruptVoipByCall:(BOOL)a0;
- (int)ilinkOpenWindowWithContact:(id)a0 msgWrap:(id)a1 isCaller:(BOOL)a2 from:(unsigned long long)a3 startInApp:(BOOL)a4 isEarMode:(BOOL)a5 isAudioMode:(BOOL)a6;
- (void)RealCall:(id)a0 isAudioMode:(BOOL)a1 withCallType:(unsigned int)a2;
- (BOOL)isOutOfDate:(unsigned int)a0;
- (void)receiveVoIPMTMessageForIlink:(id)a0 username:(id)a1 receiveMsgTime:(unsigned int)a2 notifyFrom:(int)a3;
- (void)receiveVoIPMTMessageForIlink:(id)a0 username:(id)a1 MsgWrap:(id)a2 notifyFrom:(int)a3;
- (void)HandleVoIPNotifyForIlink:(id)a0 username:(id)a1 MsgWrap:(id)a2;
- (BOOL)handleNotificationContentInfo:(id)a0 pushType:(int)a1;
- (void)receiveVoIPMTCancelInviteForIlink:(id)a0 username:(id)a1 groupId:(id)a2 receiveMsgTime:(unsigned int)a3 roomID:(unsigned long long)a4 notifyFrom:(int)a5;
- (void)hangupWithVoIPCancelType:(int)a0;
- (void)hangupWithVoIPShutdownReason:(int)a0 ifIsConnect:(BOOL)a1;
- (void)hangup;
- (void)hangupWithRoomID:(unsigned long long)a0;
- (void)rejectWithRoomID:(unsigned long long)a0;
- (void)accept:(unsigned long long)a0;
- (void)joinRoomWithRoomID:(unsigned long long)a0 contact:(id)a1;
- (void)sendWxVersion;
- (void)sendRemoteSourceDevice;
- (void)sendIfCanSupportAddMembers:(BOOL)a0;
- (BOOL)checkHasChangedToCelluar;
- (void)InitAll;
- (void)UnInitAll;
- (void)StopSession;
- (void)StopTalk;
- (void)StartSession;
- (void)handleEnterBackground;
- (void)handleEnterForeground;
- (void)setVideoDeviceDelegate:(id)a0;
- (void)onVideoSessionStartComplete;
- (void)onVideoSessionRecvFirstFrame;
- (void)onVideoSessionStopComplete;
- (void)OngetVideoFrameWithOrientation:(long long)a0;
- (void)resetVoipRender;
- (void)HeadSetPlugin:(BOOL)a0;
- (void)StartSessionWithWorkModeSecondPart;
- (void)startAudioDevice:(id /* block */)a0;
- (void)notifyAudioDeviceChange:(BOOL)a0 isWirelessDevice:(BOOL)a1 isWiredDevice:(BOOL)a2;
- (BOOL)getIfCurrentSpeaker;
- (void)SetLocalVideoEnable:(BOOL)a0;
- (void)onLocalCaptureResume;
- (void)onLocalCatpureSuspend;
- (void)VideoStatusChange:(BOOL)a0 update:(BOOL)a1 notify:(BOOL)a2;
- (void)setVirtualBackground:(BOOL)a0 isFront:(BOOL)a1;
- (BOOL)isCameraFront;
- (void)FlipCamera;
- (void)StartLocalVideo;
- (BOOL)isLocalVideoClosed;
- (BOOL)isRemoteVideoClosed;
- (void)renderToLocalView:(id)a0;
- (void)renderYuvToLocalView:(struct __CVBuffer { } *)a0;
- (void)renderToRemoteView:(struct __CVBuffer { } *)a0;
- (void)renderLocalImage:(void *)a0 frameIndex:(unsigned long long)a1 width:(unsigned int)a2 height:(unsigned int)a3 rgbaTexture:(id)a4;
- (void)VideoDevPutDataFromMultiTalkToVoIP:(int)a0 frmData:(char *)a1 frmIndex:(unsigned long long)a2 imageWidth:(unsigned int)a3 imageHeight:(unsigned int)a4;
- (void)UIManagerDidClose;
- (void)UIManagerDidCloseCompletely;
- (void)updateSpeakerButtonStatus:(id)a0 hasExtenalOutput:(BOOL)a1;
- (void)onAuthOK;
- (void)onInviteMultiTalk:(id)a0;
- (void)onCreateMultiTalk:(id)a0;
- (void)onCancelCreateMultiTalk:(id)a0;
- (void)onEnterMultiTalk:(id)a0;
- (void)onInviteOrAcceptTimeout:(id)a0;
- (void)onReceiveMissMultiTalk:(id)a0;
- (void)onMemberChange:(id)a0;
- (void)onAcceptSubCallMultiTalk:(id)a0;
- (void)onMemberChange:(id)a0 withNewJoinedMembers:(id)a1;
- (void)onMultiTalkReady;
- (void)onMultiTalkDeviceLauchSuccess;
- (void)onMuteStateChange:(BOOL)a0;
- (void)OnVideoStateChange:(BOOL)a0 VideoOn:(BOOL)a1;
- (void)onCreateFailedDueToCallerRisk;
- (void)onCreateFailedDueToRequireVerification:(id)a0;
- (void)onJoinFailedDueToCallerRisk;
- (void)onCreateUnsafelyDueToCalleeRiskWithUserNames:(id)a0 isAll:(BOOL)a1;
- (void)onAddMultiTalkMemberFailedDueToCallerRisk;
- (void)onAddMultiTalkMemberFailedDueToRiskWithUserNames:(id)a0 groupInfo:(id)a1 isAll:(BOOL)a2;
- (void)onErr:(int)a0 groupUserName:(id)a1;
- (void)onVideoData:(unsigned int)a0 Bgra:(char *)a1 Width:(unsigned int)a2 Height:(unsigned int)a3 frontCamera:(BOOL)a4 screenData:(BOOL)a5 format:(int)a6;
- (void)onSpeakerStateChange:(BOOL)a0;
- (void)onAddMultiTalkMemberResult:(BOOL)a0 errorType:(int)a1 groupInfo:(id)a2;
- (void)OnSysCallNotifyInterrupt:(int)a0;
- (void)onReceiveVideoMemberChangeMsg:(id)a0 extArray:(id)a1;
- (void)onReceiveSubscribeMemberChangeMsg:(int)a0;
- (void)onMultiTalkRedirectOk;
- (void)onOtherDeviceHandleTalk:(id)a0;
- (void)onMultiTalkBannerChange:(id)a0;
- (void)onMultiTalkJoinLimit:(unsigned int)a0;
- (void)onMultiTalkCreateLimit:(unsigned int)a0;
- (void)onMultiTalkNotAllowCameraLimit:(unsigned int)a0;
- (void)onSetMultiTalkScreenSharingStatus:(int)a0 ScreenSharingStatus:(int)a1;
- (void)onDoScreenSharingSecurityCheck:(int)a0 checkStatus:(int)a1 fileMd5:(id)a2;
- (void)onRejectToCreateRoomForServerOverloadWithTimeInterval:(int)a0;
- (void)onRejectToOpenCameraForServerOverloadWithTimeInterval:(int)a0;
- (int)getVideoErrorCode;
- (void)onSetRoomID:(unsigned long long)a0;
- (void)onCall;
- (void)receiverOpenUIForRoomInfo:(id)a0 username:(id)a1 receiveMsgTime:(unsigned int)a2;
- (void)onRecvInviteBusy;
- (void)onRecvNotifyFail;
- (void)onRecvSimuCall;
- (void)onChangeOfjoinedMemberCnt:(int)a0 joiningMemberCnt:(int)a1;
- (void)onCallEndWithoutCheck:(unsigned long long)a0;
- (void)resetByNoVCCreate;
- (void)hangupByInterruptWithRoom:(unsigned long long)a0;
- (void)onCallEnd:(unsigned long long)a0 callResult:(unsigned int)a1;
- (BOOL)getIfIsConnected;
- (int)getRemoteVideoRatio;
- (void)remoteVideoStatusChange:(BOOL)a0;
- (void)ilinkInviteFailedToVoIPMgrWithUserName:(id)a0;
- (void)OnBeAccepted;
- (void)OnBeRejected;
- (void)OnCancel;
- (void)onSendCmdMsg;
- (void)onRecvCmdMsg:(id)a0;
- (void)simuCallFromCallerToReceiver:(id)a0;
- (void)onSimuCallerCloseVideo;
- (void)supplementLocalBubbleWithConfCallWordingInfo:(id)a0;
- (void)onReceiveConfCallWordingInfo:(id)a0;
- (void)confSDKOnRecvCmdMsg:(id)a0;
- (void)setNetworkStatus:(int)a0;
- (void)setGPUReslution:(int)a0;
- (BOOL)get720pCaptureStatus;
- (BOOL)getEnableDirectRendering;
- (void)changeToHighCapture:(int)a0;
- (void)onRecvAckFail:(unsigned long long)a0 username:(id)a1;
- (void)onStartRecvInvite:(id)a0;
- (void)onStartRecvInvite:(id)a0 inviteMsg:(id)a1;
- (id)currentRemoteSourceDevice;
- (id)getClientGroupId;
- (void)showAddMembersNotSupportToast:(id)a0;
- (void)readyJoinRoomForIlink:(unsigned int)a0 roomID:(unsigned long long)a1;
- (void)getIlinkAddMembersResult:(id)a0;
- (void)onInviteFailedBecauseOfRiskControlWithErrorCode:(int)a0 groupUserName:(id)a1 verificationUrlBase64:(id)a2;
- (unsigned long long)getRoomID;
- (void)receiveInviteNotFriendWithErrCode:(int)a0;
- (void)inviteInitEngineFail;
- (BOOL)shouldBluetoothStartEarlier;
- (void)startAudioDeviceSucc;
- (BOOL)getIfCallKitStatus;
- (int)getTryStartAudioDevCnt;
- (BOOL)getIfEnableVoIPMPAudioUnit;
- (void)setAudioParams:(id)a0;
- (void)releaseDevice;
- (BOOL)getIfCaller;
- (BOOL)getIfCallkitWithRoom:(unsigned long long)a0;
- (void)setMicroPhoneMute:(BOOL)a0;
- (void)setSpeakerPhone:(BOOL)a0;
- (void)notifyReceiverCanStart:(BOOL)a0;
- (void)receiverCanStartCamera;
- (void)ilinkVoIPMainWindowQuitAnimationDidEnd;
- (void)onMonoServiceMsgStartWithMsg:(id)a0;
- (BOOL)onMonoServiceMsgHandleWithMsg:(id)a0;
- (BOOL)onMonoServiceMsgRejectWithMsg:(id)a0;
- (BOOL)onMonoServiceMsgCancelWithMsg:(id)a0;
- (BOOL)onMonoServiceMsgHoldWithMsg:(id)a0;
- (BOOL)isMonoServiceUIWorking;
- (void)checkLocalCaptureActive;
- (void)onReceiveVoIPPushInfo:(id)a0;
- (void)voIPConfSDKServiceOnReceiveEvent:(int)a0 errCode:(int)a1 data:(id)a2 ret:(id)a3;
- (void)audioDeviceStartedFail:(id)a0;
- (void)audioDeviceDidReceiveCallbackFirstEachStartup;
- (void)audioDeviceDidReceivePlaybackCallbackFirstEachStartup:(id)a0;
- (void)audioDeviceDidReceiveRecordingCallbackFirstEachStartup:(id)a0;
- (void)OnVoipCXHungUp:(unsigned long long)a0;
- (void).cxx_destruct;

@end
