@class NSString, NSMutableDictionary, NSDictionary, WACustomKeyboard, WAJSEventHandler_BaseEvent, NSTimer, WANativeKeyboardAccessoryView;
@protocol WATextInputInterface, InputKeyboardDelegate;

@interface WAWebViewPlugin_InputKeyboard : WAWebViewPlugin_embedView <UIGestureRecognizerDelegate, UIScrollViewDelegate, TenpayMiniProgramKeyboardDelegate, WATextInputDelegate> {
    double _toolBarHeight;
    long long _orientation;
    NSMutableDictionary *_textInputs;
    BOOL _keyboardDidShow;
    BOOL _viewDisappear;
    BOOL _canShowKeyboard;
    BOOL _hidding;
}

@property (retain, nonatomic) id<WATextInputInterface> field;
@property (nonatomic) BOOL systemKeyboard;
@property (retain, nonatomic) WACustomKeyboard *customKeyboard;
@property (nonatomic) double keyboardHeight;
@property (retain, nonatomic) NSDictionary *delayParam;
@property (retain, nonatomic) WAJSEventHandler_BaseEvent *handler;
@property (nonatomic) BOOL customHiddingKeyboard;
@property (nonatomic) double offset;
@property (weak, nonatomic) id<WATextInputInterface> checkingField;
@property (retain, nonatomic) NSTimer *ignoreSafeAreaChangeTimer;
@property (nonatomic) BOOL isExptEnableInputRecover;
@property (retain, nonatomic) NSMutableDictionary *originalInputViews;
@property (weak, nonatomic) id<InputKeyboardDelegate> inputDelegate;
@property (nonatomic) BOOL modalMask;
@property (retain, nonatomic) WANativeKeyboardAccessoryView *nativeInputAccessoryView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)init;
- (void)showKeyBoard:(id)a0;
- (void)showKeyboardForExistInput:(id)a0;
- (void)showSystemKeyboard:(BOOL)a0;
- (void)showCustomKeyboard:(long long)a0 confirmButton:(BOOL)a1;
- (void)onKeyboardDidReady;
- (void)addNotifications;
- (long long)getTextFieldReturnKeyType:(id)a0;
- (long long)getTextViewReturnKeyType:(id)a0;
- (long long)getReturnKeyType:(id)a0 defaultType:(long long)a1;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)setInputValue:(id)a0 cursorPos:(long long)a1;
- (void)dealloc;
- (BOOL)handleEvent:(unsigned long long)a0 userInfo:(id)a1;
- (void)setSystemKeyboardMode:(BOOL)a0;
- (void)setEmptyInputViewIfAgentMode:(id)a0;
- (void)recoverInputView:(id)a0;
- (void)updateKeyboardAccessoryViewForInput:(id)a0;
- (void)onSystemKeyboardWillShow:(id)a0;
- (void)setWebviewInputFocusing:(BOOL)a0;
- (BOOL)isWebviewInputFocusing;
- (void)didResize;
- (void)enterBackground:(id)a0;
- (void)adjustViewPosition:(BOOL)a0;
- (void)onKeyboardDidShow:(id)a0;
- (void)onKeyboardWillHide:(id)a0;
- (void)sendOnKeyboardHeightChangeEventWithHeight:(double)a0 duration:(double)a1 inputId:(unsigned int)a2;
- (BOOL)keyboardVisible;
- (void)setDelayedHandler:(id)a0 withParam:(id)a1;
- (void)onKeyboardDidHide:(id)a0;
- (void)hideKeyBoard:(BOOL)a0;
- (void)onDone;
- (unsigned int)insertTextField:(id)a0;
- (void)parseSafePasswordParam:(id)a0 field:(id)a1;
- (BOOL)removeTextField:(unsigned int)a0;
- (BOOL)updateTextField:(id)a0;
- (BOOL)focusInput:(id)a0;
- (unsigned int)insertTextArea:(id)a0;
- (BOOL)removeTextArea:(unsigned int)a0;
- (BOOL)updateTextArea:(id)a0;
- (void)onFocus:(id)a0;
- (void)didValueChange:(id)a0 pos:(long long)a1 input:(id)a2 keyCode:(unsigned short)a3;
- (void)onCaretBreak;
- (void)didHeightChange:(double)a0 lineNum:(long long)a1 input:(id)a2;
- (BOOL)onReturn:(id)a0;
- (long long)getLineCount:(unsigned int)a0;
- (double)getContentHeight:(unsigned int)a0;
- (void)onDeleteDrop:(id)a0 input:(id)a1;
- (void)onSelectDrop:(id)a0 input:(id)a1;
- (void)onScrollViewWillBeginDragging:(id)a0;
- (void)onScrollViewDidEndScroll:(id)a0;
- (id)getInput;
- (void)setDrapDown:(id)a0 field:(id)a1;
- (void)showDropDown:(id)a0;
- (void)setCurrentViewOffset:(double)a0;
- (void)setKeyboardAppearance:(id)a0 WithStr:(id)a1;
- (void)miniProgramKeybaordTouchNumber:(id)a0;
- (void)miniProgramKeybaordTouchDelete:(id)a0;
- (void)miniProgramKeybaordFinish:(id)a0;
- (id)parseFontFamily:(id)a0;
- (void).cxx_destruct;

@end
