@class NSIndexPath, UILabel, WCBaseTextFieldItem, POIItem, NSMutableArray, UIButton, UIView, NSString, UITextView, WCBaseKeyboardToolBar, MMLocatingCoordinateLogic, WCBaseTextViewItem, MMPickLocationViewController, WCAddressMultiPickerItem;
@protocol WCAddressInfoViewControllerDelegate;

@interface WCAddressInfoViewController : WCAddressBaseViewController <MMPickLocationViewControllerDelegate, WCAddressHalfScreenDelegate, CountryCodePickerDelegate> {
    UIButton *m_footerButton;
    WCBaseTextFieldItem *m_textFieldNameItem;
    WCAddressMultiPickerItem *m_pickerDistrictItem;
    WCBaseTextViewItem *m_textViewStreetItem;
    WCBaseTextFieldItem *m_textFieldPostalCodeItem;
    WCBaseTextFieldItem *m_textFieldPhoneItem;
    WCBaseTextViewItem *m_textViewPasteBoardItem;
    WCBaseKeyboardToolBar *m_keyboardBar;
    NSMutableArray *m_arrayInfo;
    id<WCAddressInfoViewControllerDelegate> m_delegate;
    NSIndexPath *m_selectItemIndex;
    BOOL m_resolveConnection;
    NSString *m_pasteBoardString;
    double m_keyboardHeight;
    POIItem *m_selectPosition;
}

@property (nonatomic, copy) NSString *pasteBoardText;
@property (retain, nonatomic) MMPickLocationViewController *pickLocationViewController;
@property (retain, nonatomic) NSString *postCode;
@property (retain, nonatomic) UILabel *districtInfoLabel;
@property (retain, nonatomic) NSString *districtInfoLabelString;
@property (nonatomic) int infoStatus;
@property (nonatomic) unsigned long long cellHeightForDistrictInfo;
@property (retain, nonatomic) UITextView *pasteBoard;
@property (retain, nonatomic) UILabel *pasteBoardPlaceHoldText;
@property (retain, nonatomic) UIButton *resolveButton;
@property (retain, nonatomic) UIButton *doubleResolveButton;
@property (retain, nonatomic) UIButton *clearPasteButton;
@property (retain, nonatomic) MMLocatingCoordinateLogic *locatingLogic;
@property (retain, nonatomic) UIView *bottomMaskView;
@property (retain, nonatomic) UIButton *saveButton;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)addSwiftViewWithOriginAddress:(id)a0;
- (void)updateWithAddress:(id)a0;
- (void)setCountryCode:(id)a0;
- (void)setUserName:(id)a0;
- (void)setPhoneNumber:(id)a0;
- (void)setRegion:(id)a0;
- (void)setDetailAddress:(id)a0;
- (void)setShowPasteBoard:(BOOL)a0;
- (id)init;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)viewDidBePoped:(BOOL)a0;
- (id)navigationBarBackgroundColor;
- (void)refreshViewWithData:(id)a0;
- (void)initRegionPicker;
- (BOOL)isAddMode;
- (long long)bottomSavePanelHeight;
- (void)OnCancelClick;
- (void)onCancel;
- (void)showEnsureAlert:(id)a0 Title:(id)a1;
- (void)initNavigationBar;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)addBottomSavePanel;
- (void)keyboardWillShow:(id)a0;
- (void)keyboardWillHide:(id)a0;
- (BOOL)getData:(id)a0;
- (void)onNext;
- (void)reportSaveAction:(id)a0;
- (void)registerYReportSdk;
- (void)routeRegionPicker;
- (void)routeCountryCodePicker;
- (void)setDelegate:(id)a0;
- (void)resolvePasteBoardInfo;
- (void)onResolveAddressInfo:(id)a0;
- (void)clearPasteBoardInfo:(id)a0;
- (void)showResolvingIndictor;
- (void)textViewDidChange:(id)a0;
- (void)addressButtonDidClicked;
- (void)openPickLocationView;
- (void)onFinishSelectedLocation;
- (void)checkSaveEnabled;
- (id)onGetRightBarButton;
- (void)onCancelSeletctedLocation;
- (void)onFinishMultiPickerWithProvince:(id)a0 andCity:(id)a1 andDistrict:(id)a2 andStreet:(id)a3 andPostCode:(id)a4;
- (void)multiPickerWillDisappear;
- (void)onFailureCompletionWithText:(id)a0 andComponent:(int)a1;
- (void)setTextForStreetItem:(id)a0;
- (id)tipLabelForComponent:(int)a0;
- (void)onClickTipCellLink:(id)a0;
- (void)CountryCodePickerDidPickCountryCode:(id)a0;
- (void).cxx_destruct;

@end
