@class WCCanvasAbilitySliderInfo, WCCanvasComponentPureImageInfo, WCCanvasComponentRedEnvelopInfo, WCCanvsComponentScrollGroupListInfo, WCAdSphereCardInfo, NSMutableArray, WCCanvasComponentUltraWebViewInfo, WCCanvasComponentWebStoreInfo, WCCanvasComponentRandomPickCardTitleInfo, WCCanvasComponentFloatJumpInfo, WCCanvasRandomLayoutInfo, WCCanvasComponentSocialInfo, WCCanvasComponentBackgroundMusicInfo, WCCanvasComponentButtonInfo, WCCanvasComponentNewScrollInfo, WCCanvasComponentSidebarInfo, WCCanvsComponentPanoramaInfo, WCCanvasComponentTextAreaInfo, WCCanvasComponentFloatConversionBarInfo, WCCanvasComponentLocationInfo, WCCanvasComponentFloatActionButtonInfo, WCCanvasLinearLayoutInfo, WCCanvasComponentSeparatorInfo, WCCanvasComponentSightVideoInfo, WCCanvasComponentFullScreenImageInfo, WCCanvasFrameLayoutInfo, NSString, WCCanvasComponentHalfRandomCardInfo, WCCanvasComponentStreamVideoInfo, WCCanvasFloatLayoutInfo, WCCanvasRadarChartInfo, WCCanvasComponentGeneralVideoInfo, WCCanvasComponentMusicInfo, WCCanvasComponentBottomSwipeInfo, WCCanvasComponentShareInfo, WCCanvasComponentTelephoneInfo, WCCanvasComponentPreloadWebViewInfo, WCCanvasComponentRandomPickCardInfo;

@interface WCCanvasComponentItem : MMObject <NSCoding, WCCanvasIfAbility>

@property (retain, nonatomic) NSString *cid;
@property (nonatomic) int type;
@property (nonatomic) int subType;
@property (retain, nonatomic) NSString *bgColor;
@property (retain, nonatomic) WCCanvasComponentTextAreaInfo *textAreaInfo;
@property (retain, nonatomic) WCCanvasComponentButtonInfo *buttonInfo;
@property (retain, nonatomic) WCCanvasComponentPureImageInfo *pureImageInfo;
@property (retain, nonatomic) WCCanvasComponentSightVideoInfo *sightVideoInfo;
@property (retain, nonatomic) WCCanvasComponentStreamVideoInfo *streamVideoInfo;
@property (retain, nonatomic) WCCanvasComponentGeneralVideoInfo *generalVideoInfo;
@property (retain, nonatomic) WCCanvasComponentPreloadWebViewInfo *preloadWebViewInfo;
@property (retain, nonatomic) WCCanvsComponentPanoramaInfo *panoramaInfo;
@property (retain, nonatomic) WCCanvasComponentFullScreenImageInfo *fullScreenImageInfo;
@property (retain, nonatomic) WCCanvsComponentScrollGroupListInfo *scrollGroupListInfo;
@property (retain, nonatomic) WCCanvasComponentNewScrollInfo *oNewScrollInfo;
@property (retain, nonatomic) WCCanvasComponentLocationInfo *locationInfo;
@property (retain, nonatomic) WCCanvasComponentTelephoneInfo *telephoneInfo;
@property (retain, nonatomic) WCCanvasAbilitySliderInfo *abilitySliderInfo;
@property (retain, nonatomic) WCCanvasRadarChartInfo *radarChartInfo;
@property (retain, nonatomic) WCCanvasLinearLayoutInfo *linearLayoutInfo;
@property (retain, nonatomic) WCCanvasFrameLayoutInfo *frameLayoutInfo;
@property (retain, nonatomic) WCAdSphereCardInfo *sphereInfo;
@property (retain, nonatomic) WCCanvasComponentFloatActionButtonInfo *floatActionButtonInfo;
@property (retain, nonatomic) WCCanvasComponentBottomSwipeInfo *bottomSwipeInfo;
@property (retain, nonatomic) WCCanvasComponentUltraWebViewInfo *ultraWebViewInfo;
@property (retain, nonatomic) WCCanvasComponentWebStoreInfo *webStoreInfo;
@property (retain, nonatomic) WCCanvasFloatLayoutInfo *floatLayoutInfo;
@property (retain, nonatomic) WCCanvasComponentFloatJumpInfo *floatJumpInfo;
@property (retain, nonatomic) WCCanvasRandomLayoutInfo *randomLayoutInfo;
@property (retain, nonatomic) WCCanvasComponentShareInfo *shareInfo;
@property (retain, nonatomic) WCCanvasComponentFloatConversionBarInfo *floatConversionBarInfo;
@property (retain, nonatomic) WCCanvasComponentSocialInfo *socialInfo;
@property (retain, nonatomic) WCCanvasComponentRedEnvelopInfo *redEnvelopInfo;
@property (retain, nonatomic) WCCanvasComponentSidebarInfo *sidebarInfo;
@property (retain, nonatomic) WCCanvasComponentSeparatorInfo *separatorInfo;
@property (retain, nonatomic) WCCanvasComponentMusicInfo *musicInfo;
@property (retain, nonatomic) WCCanvasComponentBackgroundMusicInfo *backgroundMusicInfo;
@property (retain, nonatomic) WCCanvasComponentHalfRandomCardInfo *halfRandomCardInfo;
@property (retain, nonatomic) WCCanvasComponentRandomPickCardInfo *randomPickCardInfo;
@property (retain, nonatomic) WCCanvasComponentRandomPickCardTitleInfo *randomPickCardTitleInfo;
@property (nonatomic) double paddingTop;
@property (nonatomic) double paddingBottom;
@property (nonatomic) double paddingLeft;
@property (nonatomic) double paddingRight;
@property (nonatomic) double layoutWidth;
@property (nonatomic) double layoutHeight;
@property (nonatomic) int verticalAlignment;
@property (nonatomic) int horizontalAlignment;
@property (nonatomic) BOOL hasUpdateDynamicData;
@property (nonatomic) int noReport;
@property (nonatomic) double paddingBottomSupplemental;
@property (retain, nonatomic) NSString *jumpExtInfo;
@property (nonatomic) double floatStartTime;
@property (retain, nonatomic) NSString *floatComponentId;
@property (retain, nonatomic) NSString *qrExtInfo;
@property (retain, nonatomic) NSString *borderColor;
@property (retain, nonatomic) NSString *borderSize;
@property (retain, nonatomic) NSString *layoutBGColor;
@property (nonatomic) BOOL isTwistAnimView;
@property (nonatomic) BOOL isShakeAnimView;
@property (retain, nonatomic) NSString *randomCardId;
@property (nonatomic) BOOL isDefaultRandomCard;
@property (nonatomic) int canvasIf;
@property (nonatomic) int hasIf;
@property (retain, nonatomic) NSMutableArray *dynamicsInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)init;
- (void)encodeWithCoder:(id)a0;
- (id)initWithCoder:(id)a0;
- (BOOL)updateUsingDynamicInfo:(id)a0;
- (id)fetchLayoutItemsInLayoutComponent;
- (id)getInnerFirstVideoComponentItem;
- (void)allowAllVideoComponentsMakingVoice:(BOOL)a0;
- (void)resetAllComponentDynamicValues;
- (id)fetchRandomLayoutComponentItemItself;
- (id)fetchRandomLayoutChosenRandomCardId;
- (BOOL)updateRandomLayoutWithChosenCardId:(id)a0 cardDynamicInfo:(id)a1;
- (BOOL)resetRandomLayoutChosenCardId;
- (BOOL)updateRandomCardDynamicInfoWith:(id)a0;
- (BOOL)canShowTwistAnimation;
- (id)fetchTransitionImgInfoForTwistAnimation;
- (BOOL)canShowShakeAnimation;
- (id)fetchTransitionImgInfosForShakeAnimation;
- (double)fetchLayoutCornerRadius;
- (id)fetchDefaultComponentItemForTwistAnimation;
- (id)fetchTransitionAnimationInfoForShakeAnimation;
- (id)fetchRandomEncoreInfo;
- (id)fetchRandomEncorePickInfo;
- (id)fetchRandomPickComponentCardInfo;
- (BOOL)isSpecialFinderRedEnvelopeItem;
- (id)fetchFirstComponentWithAvailableImage;
- (id)fetchImageUrl;
- (long long)fetchImageContentMode;
- (id)fetchWebStoreUrlsWithInternalJump:(BOOL)a0;
- (BOOL)isNeedShowStreamVideoBtn;
- (double)jumpStreamVideoTextHeight;
- (void).cxx_destruct;

@end
