@class NSString, ShareMessageConfirmLogicHelper, WCCardConfigInfo, NSMutableArray;
@protocol WCCardDataControllerDelegate;

@interface WCCardDataController : NSObject <UITableViewDelegate, UITableViewDataSource, MMTableViewDelegate, WCActionSheetDelegate, WCNewCardDetailViewControllerDelegate, ShareMessageConfirmLogicHelperDelegate, SessionSelectControllerDelegate> {
    NSMutableArray *_expiringList;
    NSMutableArray *_memberCardList;
    NSMutableArray *_nearbyList;
    NSMutableArray *_recentList;
    NSMutableArray *_layoutList;
    NSMutableArray *_layoutDisplayList;
    NSMutableArray *_cardList;
    NSMutableArray *_displayCardList;
    NSMutableArray *_emptyList;
    NSMutableArray *_invoiceCardList;
    NSMutableArray *_generalCardList;
    NSMutableArray *_sectionArr;
    unsigned int _curMinUpdateTime;
    BOOL _isDeleteHandling;
    BOOL _isNeedScrollToShareCard;
    WCCardConfigInfo *_configInfo;
    ShareMessageConfirmLogicHelper *_SendAppMsgHelper;
}

@property (weak, nonatomic) id<WCCardDataControllerDelegate> delegate;
@property (nonatomic) BOOL hasMoreData;
@property (nonatomic) BOOL isReadyToLoad;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)init;
- (void)dealloc;
- (void)initData;
- (void)setDeleteHandling:(BOOL)a0;
- (unsigned long long)getDisplayListCount;
- (void)insertCardData:(id)a0 AtIndex:(id)a1;
- (id)getIndexPathWithCardData:(id)a0;
- (id)getCardDataByIndexPath:(id)a0;
- (void)removeAllNormalCard;
- (unsigned int)removeCard:(id)a0;
- (void)updateLayoutData;
- (void)updateDisplayList;
- (void)updateInvoiceAndGeneralData;
- (void)updateSectionArr;
- (void)genInvoiceCardList;
- (void)genGeneralCardList;
- (void)genLayoutDisplayList;
- (void)processMemberSortData;
- (void)processExpireSortData;
- (void)processNearBySortData;
- (void)sortLayoutInfo;
- (void)sortWCCardList:(id)a0;
- (unsigned int)safeAddCardList:(id)a0;
- (void)deleteCardDataWithIndexPath:(id)a0 needDeleteDB:(BOOL)a1;
- (void)scrollToShareCard;
- (id)tableView:(id)a0 viewForHeaderInSection:(long long)a1;
- (double)tableView:(id)a0 heightForHeaderInSection:(long long)a1;
- (long long)numberOfSectionsInTableView:(id)a0;
- (id)tableView:(id)a0 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)a1;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (double)tableView:(id)a0 heightForRowAtIndexPath:(id)a1;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (BOOL)tableView:(id)a0 canEditRowAtIndexPath:(id)a1;
- (void)tableView:(id)a0 commitEditingStyle:(long long)a1 forRowAtIndexPath:(id)a2;
- (long long)tableView:(id)a0 editingStyleForRowAtIndexPath:(id)a1;
- (void)tableView:(id)a0 didSelectRowAtIndexPath:(id)a1;
- (void)tableView:(id)a0 didHighlightRowAtIndexPath:(id)a1;
- (void)tableView:(id)a0 didUnhighlightRowAtIndexPath:(id)a1;
- (void)onDeleteCard:(id)a0;
- (void)onGiftCard:(id)a0 lastIndex:(id)a1;
- (void)onShareCard:(id)a0 lastIndex:(id)a1;
- (void)onUseCard:(id)a0 lastIndex:(id)a1 delayTime:(double)a2;
- (void)actionSheet:(id)a0 clickedButtonAtIndex:(long long)a1;
- (void)OnSelectSessionCancel:(id)a0;
- (void)OnSelectSession:(id)a0 SessionSelectController:(id)a1;
- (void)OnSendMessageOK:(id)a0;
- (void)unGiftCardDataWithIndexPath:(id)a0;
- (void)deleteCardDataWithIndexPath:(id)a0;
- (void)delayFadeOutCard:(id)a0;
- (void)loadInvoiceCardCellSubView:(id)a0 cardIndex:(id)a1;
- (void)loadCardCellSubView:(id)a0 cardIndex:(id)a1;
- (void)loadEmptyCellSubView:(id)a0 emptyIndex:(long long)a1;
- (void)onGiftToFriendWithIndexPath:(id)a0;
- (void)onOpenWebView;
- (id)getContollerTitle:(id)a0;
- (int)indexOfCardInNormalCardList:(id)a0;
- (int)indexOfCardInLayoutDisplayList:(id)a0;
- (void)scrollViewDidScroll:(id)a0;
- (id)getSvrRetEntryList;
- (BOOL)hasSvrRetEntry;
- (id)getCardPkgElementWithIndex:(long long)a0;
- (void)hanleCardPkgElementItemClickWithIndex:(long long)a0;
- (void)loadSvrRetEntryCellSubView:(id)a0 indexPath:(id)a1;
- (void).cxx_destruct;

@end
