@class WCAdQuicklyAddBrandLogic, WCAdFinderFollowLogic, WCAdAppointmentLogic, LocationRetriever, WCCanvasDynamicDataLoader, WCAdDetermineHalfScreenView, WCAdCombineFollowLogic, WCAdConfirmHalfScreenAdapter, WCCanvasComponentItem, WCAdFinderLiveNoticePolymericLogic, NSString;
@protocol WCCanvasClickEventManagerDelegate, WCCanvasComponentDelegate;

@interface WCCanvasClickEventManager : MMObject <WCCanvasImageLoaderObserver, WCCanvasDynamicDataLoaderDelegate, WCAdQuicklyAddBrandLogicDelegate, WCAdAppointmentLogicDelegate, WCAdFinderFollowLogicDelegate, WCAdFinderLiveNoticePolymericLogicDelegate, WCActionSheetDelegate, LocationRetrieveDelegate, WCAdDetermineHalfScreenViewDelegate, WCAdConfirmHalfScreenAdapterDelegate>

@property (retain, nonatomic) WCCanvasComponentItem *componentItem;
@property (weak, nonatomic) id<WCCanvasClickEventManagerDelegate> delegate;
@property (weak, nonatomic) id<WCCanvasComponentDelegate> canvasDelegate;
@property (retain, nonatomic) WCCanvasDynamicDataLoader *dataLoader;
@property (nonatomic) BOOL qrCodeProcessing;
@property (retain, nonatomic) LocationRetriever *locationRetriever;
@property (retain, nonatomic) WCAdDetermineHalfScreenView *determineHalfScreenView;
@property (nonatomic) unsigned long long clickSource;
@property (retain, nonatomic) WCAdQuicklyAddBrandLogic *addBrandLogic;
@property (retain, nonatomic) WCAdAppointmentLogic *appointmentLogic;
@property (retain, nonatomic) WCAdFinderFollowLogic *adFinderFollowLogic;
@property (retain, nonatomic) WCAdFinderLiveNoticePolymericLogic *finderLiveNoticeLogic;
@property (retain, nonatomic) WCAdCombineFollowLogic *combineFollowLogic;
@property (retain, nonatomic) WCAdConfirmHalfScreenAdapter *phoneNumAdapter;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithComponentItem:(id)a0 delegate:(id)a1 canvasDelegate:(id)a2;
- (void)dealloc;
- (void)onClickEventWithSource:(unsigned long long)a0;
- (void)onClickEvent;
- (id)fetchRelatedComponent;
- (BOOL)doGameCenterJump;
- (BOOL)doCanvasJump;
- (BOOL)doWeAppJump;
- (BOOL)doLocalJump;
- (BOOL)doWaBizJump;
- (BOOL)doProductActionJump;
- (BOOL)doSmartPhoneJump:(id)a0;
- (BOOL)doPhoneCallJump;
- (void)doQrCodeScan;
- (void)setQrCodeScanProcessing;
- (void)getLocationForQrCodeUpdate;
- (void)updateQrCodeUrlFromServer:(id)a0;
- (void)doScanGoodJump:(id)a0;
- (void)doQuicklyAddBrandJump:(id)a0 needJumpCompatiblePage:(BOOL)a1;
- (void)doJumpPersonalProfile:(id)a0;
- (void)setQrCodeProcessingAutoFinishAfter:(double)a0;
- (void)setQrCodeProcessFinished;
- (void)loadAndScanQrCodeImage;
- (void)doQrScanBegin:(id)a0;
- (void)onUxCanvasDynamicXMLReturn:(id)a0 error:(int)a1 forCanvasId:(id)a2;
- (void)onCanvasServerDataReturn:(id)a0 errorCode:(int)a1 forLoadParams:(id)a2;
- (void)onFavProductReturn:(unsigned int)a0 errMsg:(id)a1;
- (void)onGetSmartPhoneNumber:(id)a0;
- (void)onUpdateQrCode:(id)a0 componentId:(id)a1 snsId:(id)a2;
- (void)onUpdateProfileUsername:(id)a0;
- (void)onGetRedPacketCoverUrlResult:(id)a0 autoJump:(BOOL)a1;
- (void)ImageDidFail:(id)a0;
- (void)ImageDidLoadWithData:(id)a0 Url:(id)a1;
- (void)showLoading;
- (void)showLoadingAutoHideAfter:(double)a0;
- (void)hideLoading;
- (void)doAdChannelReport:(id)a0;
- (id)getAddBrandNavigationController;
- (void)doGetCoupon;
- (void)onGetCouponWithResult:(long long)a0 errMsg:(id)a1;
- (void)doOnGetCouponSuccess;
- (void)doFinderLiveNoticeReserve;
- (void)doJumpFinderProfileWithUsername:(id)a0;
- (BOOL)shouldOnlyShowBrandInfo;
- (void)tryToUpdateQuicklyAddBrandStatus;
- (void)tryToQueryRedPackCoverUrlWithAutoJump:(BOOL)a0;
- (void)doJumpFinderFeed;
- (id)getViewController;
- (id)getNavigationController;
- (id)getUxInfoWithShared:(BOOL)a0;
- (BOOL)isCanvasInHalfScreenMode;
- (void)doJumpEmotionStore;
- (void)doOpenCustomerService;
- (void)tryToQueryAppointmentStatus;
- (void)doAppointment;
- (void)onAppointmentSubmitForType:(int)a0 isSuccess:(BOOL)a1;
- (void)onAppointmentUpdatingStatus:(int)a0;
- (int)fetchDestAppointmentOpType;
- (void)showAppointmentPhoneNumberRequestView:(id)a0;
- (void)confirmAdapterClosedWithResult:(long long)a0 extInfo:(id)a1;
- (void)tryToQueryFinderFollowStatus;
- (void)doJumpFinderFollow;
- (void)doJumpFinderProfileByFollowing;
- (void)onFinderFollowingStateChanged:(BOOL)a0 byUser:(BOOL)a1;
- (void)tryToQueryFinderLiveNoticePolymericStatus;
- (void)doFinderLiveNoticePolymeric;
- (void)onFinderLiveNoticePolymericStatusUpdatedWith:(int)a0;
- (void)onFinderLiveNoticePolymericJumpToProfile:(id)a0;
- (void)tryToQueryCombineFollowStatus;
- (void)doCombineFollow;
- (void)doJumpStatePublish;
- (void)actionSheet:(id)a0 clickedButtonAtIndex:(long long)a1;
- (void)showLocationPermissionView;
- (void)onDetermineViewButtonClickedWithType:(long long)a0 determineInfo:(id)a1;
- (void)onDetermineViewDidClose:(BOOL)a0;
- (void)retrieveLocation;
- (void)reportLocationAuthResultWithName:(id)a0 status:(id)a1;
- (void)onRetrieveLocationError:(int)a0;
- (void)onRetrieveLocationTimeOut:(id)a0;
- (void)onRetrieveLocationCallbackTimeOut:(id)a0;
- (void)onRetrieveLocationOK:(id)a0;
- (void)doNextAction:(id)a0;
- (void).cxx_destruct;

@end
