@class UIViewController, WCFinderAnimationLoadingView, WCFinderPostMgr, WCFinderPlayRateSelectPanelView, WCFinderPullDownRefreshHeaderView, NSIndexPath, UILabel, NSString, WCFinderPlaybackSpeedView, UIImage, NSMutableSet, UITableViewCell, WCFinderFeedFriendsLikeListBaseViewController, NSMutableDictionary, EmoticonCustomCreateLogic, WCFinderTopPullStatusView, WCFinderFeedDragUpDislikeController, MMFinderHandOffItem, UIView, WCFinderFeedAudioHelper, UIImageView, UITableView, WCFinderRefreshTableFooterView, WCFinderScrollActionSheet, MMScrollViewProxy, MMTimer, WCFinderLandscapeReportInfo, NSNumber;
@protocol WCFinderFeedListViewDelegate, WCFinderFeedListViewDataSource, WCFinderFeedListViewReportDelegate, WCFinderCommentBaseViewProtocol;

@interface WCFinderFeedListView : UIView <WCFinderFeedListTransitionHelperBehavior, WCFinderMinimizeDelegate, WCFinderFeedListTransitionInnserScrollViewProvider, UITableViewDelegate, UITableViewDataSource, WCFinderRefreshTableFooterViewDelegate, MMScrollActionSheetDelegate, WCActionSheetDelegate, WCFinderFeedFriendsLikeListViewControllerDelegate, WCFinderPostingCommentExt, WCFinderContentTableViewCellDelegate, WCFinderFeedNPSCellDelegate, WCFinderDescTableViewCellDelegate, WCFinderFeedShopTableViewCellDelegate, WCFinderCommentDetailViewControllerDelegate, WCFinderFeedListDownLoadExt, WCGeneralMonitorDelegate, WCFinderFullMultiMediaTableViewCellDelegate, MMFinderMenuActionDelegate, WCFinderCardWebViewControllerDelegate, WCCanvasHalfScreenViewControllerDelegate, WCAdFinderDialogViewControllerDelegate, ForwardMessageLogicDelegate, WCFinderAppPushExt, MMLiveMorphDismissTarget, RingBackInfoDisplaySheetViewDelegate, RecentForwardScrollViewDelegate, WCFinderBulletCommentViewControllerDelegate, WCFinderHalfScreenProtocol, WCFinderPreloadStrategyExt, EGORefreshTableHeaderDelegate, WCFinderTopPullStatusViewDelegate, MMFinderLiveCastViewControllerExt, WCFinderPostMgrDelegate, WCFinderFansProfileViewControllerDelegate, WCFinderFeedDragUpDislikeControllerDelegate, SnapshotPrinterViewProtocol, WCFinderActionSheetDelegate, MMUIViewControllerDelegate, WCFinderLiteAppStoreKeyExt, WCFinderMinimizeListProtocol, MMScrollMetricsDelegate, MMScreenShotExt, WCFinderKeepHolderProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) UITableView *tableView;
@property (retain, nonatomic) WCFinderPlaybackSpeedView *playbackSpeedView;
@property (retain, nonatomic) UIView *originTitleView;
@property (retain, nonatomic) WCFinderPullDownRefreshHeaderView *refreshHeaderView;
@property (retain, nonatomic) WCFinderRefreshTableFooterView *footerView;
@property (retain, nonatomic) WCFinderTopPullStatusView *topPullStatusView;
@property (retain, nonatomic) WCFinderAnimationLoadingView *loadingView;
@property (retain, nonatomic) UIView *loadingViewContainer;
@property (retain, nonatomic) UILabel *stateTipsLabel;
@property (retain, nonatomic) UIImageView *retryImageView;
@property (retain, nonatomic) NSString *currentFocusTid;
@property (retain, nonatomic) NSIndexPath *currentFocusIndexPath;
@property (copy, nonatomic) NSString *lastFocusTid;
@property (copy, nonatomic) NSString *latestAutoplayVideoTid;
@property (copy, nonatomic) NSString *lastAutoplayTid;
@property (nonatomic) BOOL isSilencePlay;
@property (retain, nonatomic) NSMutableDictionary *exposureDict;
@property (retain, nonatomic) NSMutableSet *allExposeFeedIdSet;
@property (retain, nonatomic) UIViewController<WCFinderCommentBaseViewProtocol> *lastCommentVC;
@property (retain, nonatomic) MMScrollViewProxy *scrollProxy;
@property (copy, nonatomic) NSString *lastScrollReportFPSTid;
@property (nonatomic) unsigned long long lastScrollEndDraggingTimestamp;
@property (nonatomic) unsigned long long createTimestamp;
@property (nonatomic) BOOL needsResumeTimelineVideo;
@property (nonatomic) BOOL disableVideoAutoPlay;
@property (nonatomic) BOOL feedListViewIsAppear;
@property (nonatomic) unsigned long long enterTime;
@property (retain, nonatomic) MMTimer *playTimer;
@property (retain, nonatomic) WCFinderScrollActionSheet *actionSheet;
@property (retain, nonatomic) UIImage *minimizeCoverImage;
@property (retain, nonatomic) UIView *minimizeSnapshotView;
@property (copy, nonatomic) id /* block */ forwardActionDelayBlock;
@property (nonatomic) BOOL alreadyCheckLimitModeGuide;
@property (nonatomic) BOOL halfScreenIsShowState;
@property (retain, nonatomic) NSIndexPath *enterBackgroundIndexPath;
@property (retain, nonatomic) NSString *currentTidBeforeInsertAction;
@property (retain, nonatomic) UITableViewCell *currentCellBeforeInsertAction;
@property (nonatomic) double refreshHeaderViewLastAlpha;
@property (retain, nonatomic) NSNumber *originalInterfaceOrientation;
@property (copy, nonatomic) NSString *startFeedId;
@property (nonatomic) BOOL isBlockByLimitMode;
@property (retain, nonatomic) WCFinderPostMgr *timelinePostMgr;
@property (retain, nonatomic) WCFinderFeedAudioHelper *feedAudioHelper;
@property (retain, nonatomic) NSMutableDictionary *feedPostInfoDic;
@property (retain, nonatomic) WCFinderPlayRateSelectPanelView *operationViewV3;
@property (weak, nonatomic) WCFinderFeedFriendsLikeListBaseViewController *tmpLikeListVC;
@property (retain, nonatomic) WCFinderFeedDragUpDislikeController *notInterestedLogic;
@property (retain, nonatomic) EmoticonCustomCreateLogic *emoticonCustomCreateLogic;
@property (retain, nonatomic) MMFinderHandOffItem *finderHandoffItem;
@property (retain, nonatomic) WCFinderLandscapeReportInfo *landscapeReportInfo;
@property (nonatomic) BOOL cancelSpeedViewAnimateBlock;
@property (nonatomic) BOOL isPIPVideoPlaying;
@property (weak, nonatomic) id<WCFinderFeedListViewDataSource> dataSource;
@property (weak, nonatomic) id<WCFinderFeedListViewDelegate> delegate;
@property (weak, nonatomic) id<WCFinderFeedListViewReportDelegate> reportDelegate;
@property (copy, nonatomic) NSString *retryTipsTitle;
@property (copy, nonatomic) NSString *noDataTipsTitle;
@property (copy, nonatomic) NSString *footerNoMoreTips;
@property (nonatomic) long long preFetchNextPageIndex;
@property (nonatomic) long long topPreFetchAdvanceCount;
@property (nonatomic) long long topDraggingPreFetchAdvanceCount;
@property (readonly, nonatomic) struct CGPoint { double x0; double x1; } headerViewOrigin;
@property (readonly, nonatomic) struct CGPoint { double x0; double x1; } footerViewOrigin;
@property (readonly, nonatomic) WCFinderTopPullStatusView *topPullView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)configViewController:(id)a0;
+ (id)transitionDelegateMgr;

- (void)setupSpeedPlayViewIfNeeded;
- (void)changeNaviTitleWithCurrentPlayRate:(double)a0;
- (void)hidePlayRateView;
- (void)animatedShowPlayRateResultWithRate:(double)a0;
- (void)checkRedDotReadAction;
- (void)triggerSharedLeaveUnreadFinderSync;
- (void)onFeedShowPostEntranceByContentVM:(id)a0 enterScene:(unsigned long long)a1 postType:(unsigned long long)a2;
- (void)updateFeedPostInfoBy:(id)a0 onLoadingState:(BOOL)a1;
- (BOOL)feedPostIsOnLoadingStateBy:(id)a0;
- (void)updateFeedPostInfoBy:(id)a0 musicInfo:(id)a1;
- (id)feedPostMusicInfoBy:(id)a0;
- (id)onPostFollowMuiscFeedId:(id)a0;
- (id)postMgrGetRecommendedMusicInfoFromShoot:(BOOL)a0 postMgr:(id)a1;
- (id)postMgrGetVideoTemplateInfo:(id)a0;
- (id)postMgrPatMusicGetGroupId:(id)a0;
- (id)onPostMusicIds:(id)a0;
- (id)onPostFollowTemplateFeedId;
- (id)onPostFollowTopicFeedId:(id)a0;
- (id)postMgrGetMusicInfo;
- (id)postMgrSourceInfo:(id)a0;
- (id)postMgrAttachTextContent:(id)a0;
- (void)postMgrWillOpenAlbum:(id)a0;
- (void)triggerPostActionByCheckAudioTrack:(id)a0;
- (void)_tiggerPostActionByPostMgr:(id)a0 fromAudioExtract:(BOOL)a1;
- (void)extractAudioTrackFromFeedByPostMgr:(id)a0;
- (BOOL)postMgrEnableOpenAlbum:(id)a0;
- (BOOL)shouldStartEdgeSwipeGestureWithPoint:(struct CGPoint { double x0; double x1; })a0;
- (BOOL)shouldShowMinimizeQuickSwapeEntranceForVC:(id)a0 userInfo:(id)a1;
- (BOOL)shouldUseMinimizeAnimationFromVC:(id)a0 toVC:(id)a1 isClosure:(BOOL)a2;
- (BOOL)enableDragDownToCloseForVC:(id)a0;
- (BOOL)shouldDragDownCloseInvokeForVC:(id)a0;
- (id)transitionHelperFetchCurrentPlayTid;
- (BOOL)shouldGestureClosureAsCardForVC:(id)a0 userInfo:(id)a1;
- (BOOL)shouldDragDownAsCardForVC:(id)a0 userInfo:(id)a1;
- (BOOL)shouldTransitionProvider:(id)a0 requestFailedToOther:(id)a1;
- (BOOL)enablePushSwipeGestureForViewController:(id)a0;
- (id)pushSwipeGestureDestinationForViewController:(id)a0;
- (void)pushSwipeGestureTransitionWillBegin;
- (void)pushSwipeGestureTransitionEndWithComplete:(BOOL)a0;
- (BOOL)pushSwipeGestureShouldBeginWithLocation:(struct CGPoint { double x0; double x1; })a0;
- (void)_minimizeFinderFeedListWillAppear;
- (BOOL)_supportMinimize:(id *)a0;
- (BOOL)enableMinimize;
- (void)updateNavMinimizeItem;
- (BOOL)_isFeedListViewSupportMinimize:(id *)a0;
- (BOOL)isSupportMinimize;
- (id)minimizeDelegate;
- (id)_currentIndexPathContentVM;
- (id)_contentVMAtIndexPath:(id)a0;
- (int)_commentScene;
- (id)_currentViewController;
- (id)minimizePageBizKey;
- (BOOL)checkIsDisableMinimize;
- (BOOL)checkNeedInterruptMinimize;
- (id)requestMinimizeInfo:(BOOL)a0;
- (void)updateNewMinimizeInfo:(id)a0;
- (BOOL)dismissMinimizeWhenLimitMode;
- (id)minimizeConflictScrollViews;
- (void)onOpenMinimizedFromFloatingView:(id)a0;
- (void)onMinimizeResotreContentView:(id)a0 cleanPauseStatus:(BOOL)a1;
- (BOOL)shouldAutoMinimizeWhenPopOrDismiss;
- (id)minimizePlayInfo:(BOOL)a0;
- (void)updateFloatContentMinimizePlayInfo:(id)a0;
- (void)updateMsgButtonReportInfo;
- (void)updateMinimizePlayInfo;
- (void)onClickMinimizeButton;
- (id)fetchCurrentPlayDataItemThenPause:(double *)a0;
- (id)finderFetchTransitionInnerScrollView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 startFeedId:(id)a1;
- (void)configureTableView;
- (void)setUpHeaderView;
- (void)setUpFooterView;
- (void)setupTopLoading;
- (void)setupNotInterestedActionLogicIfNeeded;
- (void)setupTipsLabel;
- (void)resetStateTipsLabelWithRetry:(BOOL)a0;
- (void)stateRetryGestureAction:(id)a0;
- (void)startLoadingState;
- (void)resetLoadingStateWithAnimation:(BOOL)a0;
- (void)reloadData;
- (void)resetPullViewState;
- (void)showNoMoreData;
- (void)resetHeaderView;
- (void)resetHeaderPullView;
- (id)setupTopPullView:(BOOL)a0;
- (BOOL)_allowTopPull;
- (void)resetTopPullView;
- (void)prefetchTopFeed;
- (void)resetFooterView:(BOOL)a0;
- (void)processLastVideoHunger;
- (void)resetFooterViewNormal;
- (void)dealloc;
- (void)willMoveToWindow:(id)a0;
- (void)didMoveToWindow;
- (void)showErrorStatus;
- (void)handleVisibleCellExpose;
- (void)finderFeedListWillAppear;
- (void)checkFeedTeenageMode:(id)a0;
- (void)finderFeedListWillDisappear;
- (void)finderFeedListDidDisappear;
- (void)finderFeedListWillTransitionToSize:(struct CGSize { double x0; double x1; })a0 withTransitionCoordinator:(id)a1;
- (BOOL)shouldSkipRotation:(BOOL)a0;
- (void)adjustPortraitUIIfNeeded;
- (void)layoutSubviews;
- (BOOL)_didCurrentVCBePopedOrDismissed;
- (void)finderFeedListWillBePushed;
- (void)finderFeedListDidAppear;
- (void)tryUpdateNavigationBarHidden:(BOOL)a0;
- (void)tryShowLimitModeView;
- (void)appendContentVMFromSectionIndex:(long long)a0 toSectionIndex:(long long)a1;
- (void)modifyContentVMWithDiffResult:(id)a0;
- (void)modifyContentVMWithDeletes:(id)a0 inserts:(id)a1 updates:(id)a2;
- (BOOL)_shouldKeepLocationForRemoves:(id)a0 inserts:(id)a1 visitableIndexPath:(id)a2;
- (int)_tlFollowEnterType;
- (id)_tlFollowUdfKV;
- (void)performUpdateWithoutKeepLocation:(BOOL)a0 block:(id /* block */)a1 completion:(id /* block */)a2;
- (void)deleteContentVMWithContentVM:(id)a0 section:(long long)a1;
- (void)reloadToolBarUIWithContentVM:(id)a0 atSection:(long long)a1;
- (void)finderFeedListViewStopCurrentFeedPlay;
- (void)finderFeedListViewPauseCurrentFeedPlay;
- (void)finderFeedListViewPauseFeedPlayWithTid:(id)a0;
- (void)scrollToContentVM:(id)a0 animated:(BOOL)a1;
- (void)scrollToNextContentVM:(id)a0 animated:(BOOL)a1;
- (void)scrollToNextContentVM:(id)a0 animated:(BOOL)a1 limitMediaType:(unsigned long long)a2;
- (void)tryLoadMoreToNextContentVM;
- (void)finderReloadRowsAtIndexPaths:(id)a0 withRowAnimation:(long long)a1;
- (BOOL)shouldKeepPlayingDuringSwipePushTransition;
- (unsigned long long)supportedInterfaceOrientationsWithVCMask:(unsigned long long)a0;
- (void)addObserverForForegroundNotification;
- (void)removeObserverForForegroundNotification;
- (void)addScreenshotNotification;
- (void)removeScreenshotNotification;
- (void)setFeedListViewUserInteractionEnabled:(BOOL)a0;
- (void)onTimelineViewEnterForeground:(id)a0;
- (void)triggerCellEnterForegroundAction;
- (void)onTimelineViewEnterBackground:(id)a0;
- (void)ensureEnterBackground;
- (void)triggerCellEnterBackgroundAction;
- (void)onVideoPIPStart:(id)a0;
- (void)onVideoPIPStop:(id)a0;
- (void)onUserDidTakeScreenshot;
- (void)saveIndexPathBeforeEnterBackground;
- (void)setUsedTaskData:(id)a0;
- (void)addOrUpdateUsedTaskData;
- (void)stopCurrentMediaAndSnapCapture;
- (void)stopCurrentMedia;
- (void)pauseCurrentMediaWithShowPauseBtn:(BOOL)a0;
- (void)checkAndResetPlayHalfState;
- (void)resumeCurrentMedia;
- (void)stopCellMediaOfSection:(long long)a0;
- (void)pauseCellMediaOfSection:(long long)a0;
- (void)preloadVideoItems;
- (void)preloadVideoItemsWithCurrentIndexPath:(id)a0;
- (id)getNeedPreloadItemsWithCurrentIndexPath:(id)a0;
- (void)checkPreCreateVideoItems;
- (void)preloadNextPageDatasWithWillDisplayIndexPath:(id)a0;
- (void)onFeedCellHotAreaAndAutoPlay;
- (void)adjustHotAreaAndAutoPlay;
- (void)_adjustHotAreaAndAutoPlayWithTableViewContentOffset;
- (void)_adjustHotAreaAndAutoPlayWithTargetOffset:(struct CGPoint { double x0; double x1; })a0;
- (void)pourStateIntoPoolWithContentVM:(id)a0;
- (void)updateCurCellMetaModelExposeInfo:(id)a0;
- (void)autoPlayVideoWithTargetOffset:(struct CGPoint { double x0; double x1; })a0;
- (void)playVideoAtIndexPath:(id)a0;
- (void)checkShouldScrollToNextFeedWithDelay:(id)a0;
- (void)updateGlobalPlaybackInfo;
- (void)playCurrentIndexFeed;
- (void)checkCurrentFocusIndexPathWithTargetOffset:(struct CGPoint { double x0; double x1; })a0;
- (void)_onCurrentFocusIndexPathChangedTo:(id)a0 tid:(id)a1;
- (void)currentFocusIndexPathWillChanged;
- (void)reportCurrentTidStats;
- (BOOL)shouldScrollToNextVisibleCellAfterLoading:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)scrollToNextVisibleCellAfterLoadingWithVisiableTid:(id)a0;
- (void)scrollToPreVisibleCellAfterLoadingWithVisiableTid:(id)a0;
- (BOOL)_isCustomAtSection:(long long)a0;
- (id)_contentVMAtSection:(long long)a0;
- (id)_contentVMOfTid:(id)a0;
- (id)currentVC;
- (long long)sectionOfTid:(id)a0;
- (int)feedViewControllerScene;
- (int)fromViewControllerScene;
- (unsigned long long)commentAndLikeScene;
- (unsigned long long)refreshTime;
- (BOOL)isDisableVideoAutoPlay;
- (void)stopPreloadWithIndexPath:(id)a0;
- (void)_stopPreloadVideoItem:(id)a0;
- (void)_preloadVideoItemsWithContentVMArray:(id)a0 playedContentVMArray:(id)a1;
- (id)_tableViewParamModelWithContentVM:(id)a0;
- (BOOL)_shouldHandleJumpProfileUsername:(id)a0 vatarType:(unsigned long long)a1 contentVM:(id)a2;
- (BOOL)_isAuthorViewer;
- (void)willPresentHalfScreen;
- (void)resumeFromHalfScreen;
- (void)setTableViewScrollEnable;
- (BOOL)enableMixing;
- (void)onLandScapeBtnClick:(id)a0;
- (void)scrollViewDidScrollToTop:(id)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)scrollViewWillBeginDecelerating:(id)a0;
- (void)scrollViewWillEndDragging:(id)a0 withVelocity:(struct CGPoint { double x0; double x1; })a1 targetContentOffset:(inout struct CGPoint { double x0; double x1; } *)a2;
- (void)scrollViewDidScroll:(id)a0;
- (void)scrollViewDidEndScrollingAnimation:(id)a0;
- (void)setFeedCellDecorationViewsTranslucent:(BOOL)a0;
- (void)setFeedCellMoreActionButtonAlpha:(double)a0;
- (void)tableView:(id)a0 willDisplayCell:(id)a1 forRowAtIndexPath:(id)a2;
- (void)tableView:(id)a0 didEndDisplayingCell:(id)a1 forRowAtIndexPath:(id)a2;
- (void)exposureTime:(id)a0 index:(long long)a1;
- (long long)numberOfSectionsInTableView:(id)a0;
- (long long)numberOfContnetVMS;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (double)tableView:(id)a0 heightForRowAtIndexPath:(id)a1;
- (id)tableView:(id)a0 viewForFooterInSection:(long long)a1;
- (double)tableView:(id)a0 heightForHeaderInSection:(long long)a1;
- (double)tableView:(id)a0 heightForFooterInSection:(long long)a1;
- (BOOL)shouldTopPullViewTrigger:(id)a0;
- (void)onTopPullViewTriggePull:(id)a0;
- (BOOL)finderNotInterestedActionLogicCanShowPanel;
- (void)finderNotInterestedActionLogicSetDislikeWithContentVM:(id)a0;
- (id)finderNotInterestedActionLogicGetContentVMAtPanStart;
- (void)egoRefreshTableHeaderDidTriggerRefresh:(id)a0;
- (void)didClickFooterRefreshRetry:(id)a0;
- (void)finderFooterDidTriggerRefresh:(id)a0;
- (BOOL)isEnableTriggerRefreshAtScroll:(id)a0;
- (void)didClickFinderHandOff:(id)a0;
- (void)makeFinderHandoffItem:(id)a0;
- (void)onFriendsLikeListViewControllerDisappear;
- (void)onClickFriendWeChatProfile:(id)a0;
- (void)onClickFriendLikeListDetail:(id)a0;
- (void)onRefreshFriendUI:(id)a0;
- (BOOL)shouldShowFirstLikeLabel;
- (BOOL)canShowMore;
- (void)onClickLikedListClickMoreActionWith:(id)a0 ObjectId:(id)a1;
- (void)onClickLikedListContactWithWith:(id)a0 LikeInfo:(id)a1 ObjectID:(id)a2;
- (void)doBusinessWithCompletion:(id /* block */)a0;
- (void)fansProfileViewController:(id)a0 clickFinderActionWithWXUsername:(id)a1;
- (void)wx_fansProfileViewController:(id)a0 clickActionWithFinderContact:(id)a1;
- (void)onClickBottomBannerView:(id)a0 contentVM:(id)a1 triggerByUser:(BOOL)a2;
- (void)onCloseBottomBannerView:(id)a0 contentVM:(id)a1;
- (void)onShowGuideToFinderMoreRelatedView:(id)a0;
- (void)multiMediaCellBrowsePhotoLongTime:(id)a0;
- (void)multiMediaCell:(id)a0 shouldPauseVideoIfSupport:(BOOL)a1;
- (BOOL)multiMediaCell:(id)a0 shouldShowDislikeButton:(id)a1;
- (void)onLiveFeedDidTap:(id)a0 routeModel:(id)a1;
- (void)onLiveFeedStatusChanged:(id)a0;
- (void)onFeedCellDidClickAvatar:(id)a0 avatarType:(unsigned long long)a1 contentVM:(id)a2;
- (void)didFeedDoubleLikeAction:(id)a0;
- (void)doubleClickLikeFeedContentVMAction:(id)a0;
- (void)likeFeedContentVMAction:(id)a0 isPrivateLike:(BOOL)a1;
- (void)likeFeedContentVMAction:(id)a0 isPrivateLike:(BOOL)a1 touchPoint:(struct CGPoint { double x0; double x1; })a2;
- (void)showSpamTipsWithString:(id)a0;
- (void)photoContentPageTurning:(id)a0 currentPage:(unsigned long long)a1 lastPage:(unsigned long long)a2;
- (void)retryLoadingVideoResource:(BOOL)a0;
- (void)contentMediaDidStopPlay:(unsigned long long)a0 contentVM:(id)a1 finderPlayerReport:(id)a2;
- (void)contentMediaDidEndPlay:(unsigned long long)a0 contentVM:(id)a1 finderPlayerReport:(id)a2;
- (void)tryAutoPlayNextFeedAfterContentVM:(id)a0;
- (void)onFeedVideoStopPlay:(id)a0 tid:(id)a1;
- (id)createActionSheetWithContentVM:(id)a0;
- (BOOL)canShowAutoScrollItem;
- (id)_actionSheetItemConfigArrayWithContentVM:(id)a0;
- (unsigned long long)getScrollActionSheetOptions;
- (BOOL)haveDislikeEntryWithContentVM:(id)a0;
- (void)onLongPressMediaInCell:(id)a0;
- (id)getFinderSurveyContextInfoForCell:(id)a0;
- (void)onHeaderMoreClickAction:(id)a0 shareButton:(id)a1;
- (void)onHeaderFollowBtnClickAction:(id)a0 followButton:(id)a1;
- (BOOL)finderMulitMediaTableViewCellCanProgressGestureWithTid:(id)a0;
- (BOOL)onMultiMediaCellIsInHotSpots:(id)a0;
- (void)onMultiMediaCell:(id)a0 videoTemplateClickAction:(id)a1;
- (void)onImageMediaTableViewCellPlayPauseWillChange:(BOOL)a0;
- (void)onVideoPlayWithReport:(id)a0 mediaWrap:(id)a1 currentIndex:(unsigned long long)a2 forContentVM:(id)a3;
- (void)onVideoPlayDecoderError:(id)a0;
- (void)multiMediaCellInPicture:(id)a0;
- (void)multiMediaCellForceToProtrait:(id)a0;
- (BOOL)multiMediaCell:(id)a0 isTouchPlayRateOperationV3View:(id)a1;
- (void)multiMediaCellPlayRateView:(id)a0 playSpeedViewWillStartAnimatedChange:(long long)a1;
- (void)multiMediaCellPlayRateView:(id)a0 playSpeedViewAnimatedChangeComplete:(long long)a1;
- (void)multiMediaCell:(id)a0 handlePortoailLongPressGesture:(id)a1 stateModel:(id)a2;
- (void)multiMediaCellClickTemplateCommentSuspendViewConfirmViewWithDataItem:(id)a0 commentId:(unsigned long long)a1;
- (BOOL)multiMediaCellCanAutoOpenJumpInfo:(id)a0;
- (void)multiMediaCellShowPlayRate:(id)a0;
- (void)multiMediaCell:(id)a0 didChangePinchVideoState:(BOOL)a1;
- (BOOL)isNoMoreDataItemAfterContentVM:(id)a0;
- (BOOL)isLastDataItemAfterContentVM:(id)a0;
- (void)onWillClickToolbarLikeAction:(id)a0 isPrivateLike:(BOOL)a1;
- (void)onClickToolbarLikeAction:(id)a0 isPrivateLike:(BOOL)a1;
- (void)onClickRealNameAction;
- (void)onCellTriggerAntiAddictCheckLogic;
- (void)onClickViewAllCommentAction:(id)a0 isActiveInput:(BOOL)a1 forceCell:(id)a2;
- (void)onClickViewAllCommentAction:(id)a0 isActiveInput:(BOOL)a1 isFromCommentButton:(BOOL)a2;
- (BOOL)forceCloseCommentListView;
- (void)showCommentListWithContentVM:(id)a0 shouldEnterKeyBoard:(BOOL)a1 refCommentID:(unsigned long long)a2 commentAction:(unsigned long long)a3 showTitle:(BOOL)a4 enterType:(unsigned long long)a5 appendCommentModel:(id)a6;
- (void)onWillClickToolbarCollectionAction:(id)a0;
- (void)onClickToolbarCollectionAction:(id)a0 sourceType:(int)a1;
- (void)onClickToolbarCollectionAction:(id)a0 actionSheet:(id)a1 sourceType:(int)a2;
- (void)forbidTableViewScrollingWithDuration:(double)a0;
- (void)didFeedDoubleThumbLikeAction:(id)a0;
- (void)handleFavoriteActionWithContentVM:(id)a0 sourceType:(int)a1;
- (void)onClickToolbarFeedAllLikeAction:(id)a0;
- (void)onClickToolbarFeedAllFavAction:(id)a0;
- (void)onClickToolbarFeedAllViewedAction:(id)a0;
- (void)onClickToolbarRetryUploading:(id)a0;
- (void)onClickToolbarCancelUploading:(id)a0;
- (void)finderClickFinishedFeedNPSCell:(id)a0;
- (void)finderDescTableViewCell:(id)a0 clickActionType:(unsigned long long)a1;
- (void)feedShopCell:(id)a0 clickActionType:(unsigned long long)a1 contentVM:(id)a2 reportBuffer:(id)a3;
- (id)feedShopCellGetCurrentNavigationController;
- (void)_pushContentPOIVCAction:(id)a0 fromVC:(id)a1;
- (void)clickContentPOIAction:(id)a0 commentVC:(id)a1;
- (void)clickContentPOIAction:(id)a0;
- (void)_pushContentUsernameVCAction:(id)a0 fromVC:(id)a1;
- (void)onClickThankForShareButtonWithThank:(BOOL)a0;
- (void)onClickContentUsernameAction:(id)a0 commentVC:(id)a1;
- (void)onClickContentUsernameAction:(id)a0;
- (void)onClickBottomAreaTipsButton:(id)a0;
- (void)_pushEventEntry:(id)a0 fromVC:(id)a1;
- (void)onClickEventEntry:(id)a0 commentVC:(id)a1;
- (void)onClickEventEntry:(id)a0;
- (void)onFeedCellClickHotWord:(id)a0;
- (void)onMultiMediaCell:(id)a0 lastestLiveInfoClickAction:(id)a1;
- (void)onMultiMediaCell:(id)a0 beDisliked:(id)a1;
- (void)onFeedContentUserFollowStateChangedWithContentVM:(id)a0;
- (void)onFeedClickJumpInfo:(id)a0 style:(id)a1;
- (void)onAdFinderDialogFailedToJumpToAppDirectlyWithAppParams:(id)a0 jumpParams:(id)a1;
- (void)onFeedCellClickMemberShipPaymentGuideViewConfirmButtonWithContentVM:(id)a0;
- (void)onFeedCellClickSetRingToneGuideView:(id)a0;
- (void)onFeedCellClickHotComment:(id)a0 contentVM:(id)a1 enterType:(unsigned long long)a2;
- (void)onFeedCellTriggerBulletCommentWithReplyItem:(id)a0;
- (void)onReportBulletComment:(id)a0 contentVM:(id)a1;
- (void)onDeleteBulletComment:(id)a0 contentVM:(id)a1;
- (void)onMoreBulletComment:(id)a0 isInBlackList:(BOOL)a1 isAuthorScene:(BOOL)a2 contentVM:(id)a3;
- (void)onUnBlockBulletComment:(id)a0 contentVM:(id)a1;
- (void)onBlockBulletComment:(id)a0 contentVM:(id)a1;
- (void)modBlackListWithOpType:(int)a0 bulletItem:(id)a1 contentVM:(id)a2 successText:(id)a3 failText:(id)a4;
- (void)onBulletCommentOpenStateChanged:(id)a0;
- (void)onFeedCellClickPostComment:(id)a0 scene:(int)a1 contentVM:(id)a2;
- (void)onFeedCellClickGuideMakeEmotion:(id)a0;
- (void)onFeedCellClickMiaoJianMusic:(id)a0 musicId:(id)a1 tingListenId:(id)a2;
- (void)onFinderCardWebViewControllerJumpToOthers;
- (void)onFinderCardWebViewControllerWillResume;
- (void)onFinderCardWebViewControllerWillBeClosed;
- (void)onCanvasHalfScreenViewControllerJumpToOthers;
- (void)onCanvasHalfScreenViewControllerWillResume;
- (void)onCanvasHalfScreenViewControllerWillBeClosed;
- (void)onClickAdGuideFollowBtn:(id)a0;
- (void)onClickBigButton:(id)a0;
- (void)onRefreshContentCellUI:(id)a0;
- (void)onClickContentReadMoreAction:(id)a0 isExpand:(BOOL)a1;
- (void)onContentTableViewCell:(id)a0 longPressContentAction:(id)a1 rect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a2;
- (void)_pushContentExtReadingWithUrl:(id)a0 fromVC:(id)a1;
- (void)onClickContentExtReadingAction:(id)a0;
- (void)onClickContentExtReadingAction:(id)a0 commentVC:(id)a1;
- (void)_pushContentTopicVCWith:(id)a0 dataItem:(id)a1 fromVC:(id)a2;
- (void)onClickContentTopicAction:(id)a0 dataItem:(id)a1;
- (void)onClickContentTopicAction:(id)a0 dataItem:(id)a1 commentVC:(id)a2;
- (void)_pushContentMentionAction:(id)a0 nickname:(id)a1 dataItem:(id)a2 fromVC:(id)a3 sucBlock:(id /* block */)a4;
- (void)onClickContentMentionAction:(id)a0 nickname:(id)a1 dataItem:(id)a2;
- (void)onClickContentMentionAction:(id)a0 nickname:(id)a1 dataItem:(id)a2 commentVC:(id)a3 sucBlock:(id /* block */)a4;
- (void)scrollActionSheet:(id)a0 didSelecteItem:(id)a1;
- (void)didClickToolbarDeleteAction:(id)a0;
- (void)deleteFeedWithContentVM:(id)a0;
- (void)scrollActionSheetDidCancel:(id)a0;
- (void)scrollActionSheetDidTapTransparent:(id)a0;
- (void)reportForwordWith:(id)a0;
- (void)scrollActionSheetWillDismiss:(id)a0;
- (void)scrollActionSheetDidDismiss:(id)a0;
- (void)scrollActionSheetDidAppeared:(id)a0;
- (void)snapshotForMinimize;
- (id)currentMinimizationTaskBizKey;
- (id)currentMinimizationTaskBizName;
- (id)minimizeKey;
- (id)currentFeedMediaCell;
- (id)currentFeedContentVM;
- (id)snapshotImageForMedia;
- (id)viewForKeepHoldAnimation;
- (void)showPlayRatePanelTriggerByDragging:(BOOL)a0;
- (void)showLockSpeedPlayPanel;
- (void)_showV1OperationView;
- (void)inPicture;
- (void)bulletCommentOpenStateChanged:(BOOL)a0 itemFlag:(unsigned long long)a1 changedScene:(long long)a2;
- (void)bulletCommentOpenStateChanged:(BOOL)a0 itemFlag:(unsigned long long)a1 changedScene:(long long)a2 openType:(unsigned long long)a3;
- (id)finderFeedbackCustomQuery:(id)a0;
- (void)onFinderDataItemPostingCommentFailBySpecialError:(id)a0 errorCode:(int)a1 errorMsg:(id)a2;
- (void)onFinderVideoPlayerStartPlay;
- (void)needsUpdateCurrentVideo:(BOOL)a0;
- (void)resetCurrentVideoThumb;
- (void)updateCurrentVideoThumb;
- (void)onCommentDetailViewControllerDidDisappear;
- (void)clickCommentNickname:(id)a0 username:(id)a1 contact:(id)a2 isWeChatFriend:(BOOL)a3 dataItem:(id)a4;
- (void)clickAuthorCommentAvatarWhenInProfile:(id)a0;
- (void)monitorView:(id)a0 newExposedItems:(id)a1 lastExposedItems:(id)a2;
- (void)monitorView:(id)a0 unExposedCells:(id)a1;
- (void)monitorView:(id)a0 unExposedItems:(id)a1;
- (void)updateAdReportMeta:(id)a0;
- (id)getCurrentFocusTableViewCell;
- (BOOL)isLiveRoomFocused;
- (void)onContactClick:(id)a0 index:(unsigned long long)a1;
- (id)getCurrentViewController;
- (void)OnForwardMessageSend:(id)a0;
- (void)OnForwardMessageCancel:(id)a0;
- (void)onFinderAPNsPushBeClicked;
- (void)finderMediaVideoPreloadSuccessful:(id)a0 mediaWrap:(id)a1 isFirstFrameDowloadState:(BOOL)a2;
- (void)finderPreloadStrategyUpdate;
- (BOOL)canShowSwipEdu;
- (void)onVideoUpdatePosition:(double)a0 videoDuration:(double)a1 maxPlayVideoTime:(double)a2;
- (void)onCurrentBGMDidEndPlay:(id)a0;
- (void)onShowAutoScrollSheet:(id)a0;
- (BOOL)canShowAutoScrollSheetTips:(id)a0;
- (void)onFeedCellPreparedMediaContent:(id)a0;
- (void)onCurMultiMediaCellNPSFlutterShowing:(BOOL)a0 cell:(id)a1;
- (void)scrollToNextFeedWithContentVM:(id)a0;
- (BOOL)shouldLiveUseMorphDismissForCustomKey:(id)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })liveMorphDismissTargetFrameOnScreenForCustomKey:(id)a0 videoSize:(struct CGSize { double x0; double x1; })a1;
- (id)liveMorphDismissTargetExtraConfigForCustomKey:(id)a0;
- (void)onRingToneSheetDisappear;
- (void)onRingToneSheetSetRingtoneSuccess:(long long)a0 friendUsername:(id)a1;
- (void)clickRFItemCallBack:(id)a0;
- (void)relayoutScrollSheet;
- (void)onBulletCommentViewController:(id)a0 didCommentWithText:(id)a1 replyItem:(id)a2;
- (void)onBulletCommentViewControllerChangeBulletCommentOpenState:(BOOL)a0;
- (id)getCurrentMediaViewCell;
- (id)getCurrentLiveRoomCell;
- (void)onBulletCommentViewControllerClosed;
- (void)onBulletCommentViewControllerShowInputViewWithDisable;
- (id)getListenHalfAnimView;
- (unsigned long long)listenHalfScreenOption;
- (void)listenHalfScreenIsShow:(BOOL)a0 eventType:(unsigned long long)a1;
- (void)listenHalfScreenMoveProgress:(double)a0 heightRatio:(double)a1;
- (void)doShareAnimation;
- (void)restartBulletAnimationAftertransition;
- (BOOL)isAutoPlayNextFeedPageConditionOK:(BOOL)a0;
- (unsigned long long)getHeaderRefreshMode;
- (void)liveCastViewControllerDidDismiss:(id)a0;
- (void)gotoFinderAuidoMainFeed:(id)a0;
- (void)addToTingListenLater:(id)a0;
- (id)getViewController;
- (id)extInfoForSnapshotPrinter;
- (id)getNextMinimizeListPlayContentVMWithCurrentTid:(id)a0;
- (void)liteAppStoreShowCommentListWithContentVM:(id)a0;
- (void)liteAppStoreShowCommentHeatUpGuideWithContentVM:(id)a0;
- (void)onCreateScreenShotInfo:(id *)a0;
- (void)onMMScrollMetricsWillCollect:(id)a0;
- (void)onMMScrollMetricsDidCollected:(id)a0;
- (void).cxx_destruct;

@end
