@class WCFinderShareCustomTransition, WCFinderFollowTabDetailBaseViewModel, WCFinderFollowTabDetailVCReporter, NSString, WCFinderFeedListView, NSIndexPath;
@protocol WCFinderFollowTabDetailVCDelegate;

@interface WCFinderFollowTabDetailViewController : MMUIViewController <WCFinderFeedListViewDataSource, WCFinderFeedListViewDelegate, WCFinderFeedListViewMinimizeDelegate, WCFinderFeedBaseViewControllerProtocol, WCFinderFollowTabDetailVMDelegate, WCFinderShareCustomTransitionProtocol, WCFinderCustomTransitionProtocol, WCFinderShareAbstractCell>

@property (retain, nonatomic) WCFinderFeedListView *feedListView;
@property (retain, nonatomic) WCFinderFollowTabDetailBaseViewModel *viewModel;
@property (retain, nonatomic) WCFinderShareCustomTransition *animator;
@property (retain, nonatomic) WCFinderFollowTabDetailVCReporter *reporter;
@property (nonatomic) int commentScene;
@property (retain, nonatomic) NSIndexPath *currentMaxIndexPath;
@property (weak, nonatomic) id<WCFinderFollowTabDetailVCDelegate> delegate;
@property (copy, nonatomic) id /* block */ exitBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithFeedFollowVM:(id)a0 preVCData:(id)a1 postFeedInsertMachineTab:(BOOL)a2;
- (id)initWithFeedFollowVM:(id)a0 preVCData:(id)a1 reporter:(id)a2 postFeedInsertMachineTab:(BOOL)a3;
- (id)initWithFinderUsername:(id)a0 lastTid:(id)a1 nonceID:(id)a2;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(BOOL)a0;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)viewDidBePopedOrDismissed:(BOOL)a0;
- (void)dealloc;
- (BOOL)useTransparentNavibar;
- (unsigned long long)supportedInterfaceOrientations;
- (BOOL)prefersHomeIndicatorAutoHidden;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })a0 withTransitionCoordinator:(id)a1;
- (void)viewDidTransitionToNewSize;
- (void)configureFeedListView;
- (void)deleteContentVM:(id)a0;
- (id)finderFeedListView:(id)a0 contentVMAtSection:(long long)a1;
- (id)finderFeedListView:(id)a0 contentVMOfTid:(id)a1;
- (long long)numberOfContentVMsInTableView;
- (long long)finderFeedListView:(id)a0 sectionOfTid:(id)a1;
- (BOOL)finderFeedListViewCanPreFetchData:(id)a0;
- (BOOL)finderFeedListViewIsNoMoreData:(id)a0;
- (void)finderFeedListViewFetchMoreData:(id)a0;
- (void)finderFeedListViewRetryFetch:(id)a0;
- (id)finderFeedListViewCurrentViewController:(id)a0;
- (void)finderFeedListViewDidClickScreenRotateBtn:(id)a0;
- (BOOL)isInSubScene;
- (BOOL)finderFeedListViewShowsMoreButton:(id)a0;
- (BOOL)finderFeedListViewControllerSupportMinimize:(id)a0;
- (id)minimizePageBizKey;
- (BOOL)canShowAutoScrollItem;
- (id)finderFeedList:(id)a0 actionConfigureWithContentVM:(id)a1;
- (void)finderFeedListView:(id)a0 deleteContentVM:(id)a1;
- (void)finderFeedListView:(id)a0 dislikeContentVM:(id)a1;
- (void)finderFeedListView:(id)a0 changeCurrentFocusIndexPath:(id)a1 currentFocusTid:(id)a2;
- (void)onFollowTabDetailVMDataChange;
- (void)onFollowTabDetailVMDataEmpty;
- (void)onFollowTabDetailVMDataAppendFromIndex:(unsigned long long)a0 toIndex:(unsigned long long)a1;
- (void)onFollowTabDetailVMDataDeleteDataAtIndex:(long long)a0;
- (int)followDetailVMGetCommentScene;
- (int)feedViewControllerScene;
- (unsigned long long)feedViewerScene;
- (id)getCurMediaListObject;
- (id)mmNavigationController:(id)a0 animationControllerForOperation:(long long)a1 fromViewController:(id)a2 toViewController:(id)a3;
- (void)doShareAnimation;
- (id)getCustomTransitionAnimator:(BOOL)a0;
- (void)updateTransitionAnimator:(id)a0;
- (void)registerYReportSdk;
- (void).cxx_destruct;

@end
