@class UIView, NSString, WCFinderEmptyTipsView, WCFinderStreamFooterView, WCFinderFlowTopTipsView, NSMutableDictionary, WCFinderStreamLayout, UIImage, NSMutableArray, UICollectionView, NSIndexPath;
@protocol WCFinderFeedFlowViewDelegate, WCFinderFeedFlowViewMonitorDelegate, WCFinderFeedFlowViewDataSource, WCFinderFeedFlowViewLayoutDelegate;

@interface WCFinderFeedFlowView : UIView <WCFinderFlowLayoutDelegate, UICollectionViewDataSource, UICollectionViewDelegate, WCFinderStreamLayoutDelegate, WCFinderFeedStaticCoverCollectionViewCellDelegate, WCFinderFlowTopTipsViewDelegate, WCFinderStreamFooterViewActionDelegate, WCFinderEmptyTipsViewDelegate, WCGeneralMonitorDelegate, WCFinderFeedFlowLiveCellDelegate, WCFinderFeedStaticCoverCollectionViewCellDataSource>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) UICollectionView *collectionView;
@property (retain, nonatomic) WCFinderStreamLayout *streamLayout;
@property (nonatomic) long long layoutType;
@property (retain, nonatomic) WCFinderFlowTopTipsView *topTipsView;
@property (retain, nonatomic) WCFinderEmptyTipsView *emptyTipsView;
@property (retain, nonatomic) WCFinderStreamFooterView *footerView;
@property (nonatomic) unsigned long long topTipsViewLoadingState;
@property (nonatomic) unsigned long long emptyTipsViewLoadingState;
@property (nonatomic) unsigned long long footerViewLoadingState;
@property (retain, nonatomic) NSIndexPath *appendedIndexPath;
@property (nonatomic) unsigned long long state;
@property (retain, nonatomic) NSMutableDictionary *exposeTimeDict;
@property (retain, nonatomic) NSMutableDictionary *displayingCellPtrDict;
@property (retain, nonatomic) UIImage *topLoadingImage;
@property (retain, nonatomic) UIImage *centerLoadingImage;
@property (nonatomic) unsigned long long flowFeedViewPreloadIndex;
@property (nonatomic, getter=isViewCurrentAppear) BOOL viewCurrentAppear;
@property (retain, nonatomic) NSMutableArray *selectedContentVMs;
@property (nonatomic) BOOL forbidAutoPlayCell;
@property (weak, nonatomic) id<WCFinderFeedFlowViewDataSource> dataSource;
@property (weak, nonatomic) id<WCFinderFeedFlowViewDelegate> delegate;
@property (weak, nonatomic) id<WCFinderFeedFlowViewLayoutDelegate> layoutDelegate;
@property (weak, nonatomic) id<WCFinderFeedFlowViewMonitorDelegate> monitorDelegate;
@property (nonatomic) struct UIEdgeInsets { double top; double left; double bottom; double right; } contentInset;
@property (nonatomic) struct CGPoint { double x; double y; } contentOffset;
@property (nonatomic) struct CGSize { double x0; double x1; } minContentSize;
@property (nonatomic) unsigned long long consumerType;
@property (nonatomic) BOOL enableGradientEffect;
@property (retain, nonatomic) NSString *emptyTipsText;
@property (nonatomic) BOOL observeredByPageContainer;
@property (retain, nonatomic) UIView *topHeaderView;
@property (nonatomic) BOOL enableFooterJumpType;
@property (nonatomic) BOOL disableLiveAutoPlay;
@property (nonatomic) BOOL showCheckMark;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)flowLayoutFeedFlowView;
+ (id)flowLayoutFeedFlowView:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
+ (unsigned long long)defaultColumnCount;
+ (struct CGSize { double x0; double x1; })defaultCellSpace;

- (void)ls_interuptUserAction;
- (void)ls_recoverUserAction;
- (long long)collectionView:(id)a0 flowLayout:(id)a1 columnForSection:(long long)a2;
- (double)collectionView:(id)a0 flowLayout:(id)a1 heightForIndexPath:(id)a2 width:(double)a3;
- (double)collectionView:(id)a0 flowLayout:(id)a1 itemPaddingForSection:(long long)a2;
- (double)collectionView:(id)a0 headerHeight:(long long)a1;
- (double)collectionView:(id)a0 footerHeight:(long long)a1;
- (BOOL)collectionView:(id)a0 flowLayout:(id)a1 pinHeader:(long long)a2;
- (void)collectionView:(id)a0 insets:(out struct UIEdgeInsets { double x0; double x1; double x2; double x3; } *)a1 forSection:(long long)a2;
- (void)GetStreamAutoPlayFirstRowIndexPaths:(id *)a0 rightIndexPath:(id *)a1 filterBlock:(id /* block */)a2;
- (BOOL)isStreamCellFullExpose:(id)a0;
- (BOOL)isAutoPlayValid:(id)a0;
- (void)performFeedFlowCollectionView:(id)a0 beforeSelectedIndexPath:(id)a1 business:(id /* block */)a2;
- (id)indexPathForCurrentBrowserFeedTid:(id)a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 layoutType:(long long)a1;
- (void)layoutSubviews;
- (void)setContentOffset:(struct CGPoint { double x0; double x1; })a0 animated:(BOOL)a1;
- (void)setLoadingImage:(id)a0 withTipsType:(unsigned long long)a1;
- (void)finderFeedFlowViewWillAppear;
- (void)finderFeedFlowViewDidAppear;
- (void)finderFeedFlowViewWillDisappear;
- (void)finderFeedFlowViewDidDisappear;
- (void)updateState;
- (void)appendForOS12From:(long long)a0 toIndex:(long long)a1 feedFlowSection:(unsigned long long)a2;
- (void)appendContentVMFromSectionIndex:(long long)a0 toSectionIndex:(long long)a1;
- (void)appendContentVMFromSection:(unsigned long long)a0 fromIndex:(long long)a1 toIndex:(long long)a2;
- (void)batchReplaceAndInsertContentVMsFromSection:(unsigned long long)a0 replaceRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1 insertRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a2;
- (void)batchReplaceAndRemoveContentVMsFromSection:(unsigned long long)a0 replaceRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1 removeRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a2;
- (void)setTopTipsViewColor:(id)a0;
- (void)setEmptyTipsViewColor:(id)a0;
- (void)setEmptyTipsLoadingSize:(double)a0;
- (void)setFooterViewColor:(id)a0;
- (void)setTopTipsViewHidden:(BOOL)a0;
- (void)reset;
- (void)reloadData;
- (void)reloadItemsAtIndexPaths:(id)a0;
- (void)setTopTipsViewState:(unsigned long long)a0;
- (void)setEmptyTipsViewState:(unsigned long long)a0;
- (void)setFooterState:(unsigned long long)a0;
- (void)onFeedFlowViewEnterForeground;
- (void)onFeedFlowViewEnterBackground;
- (id)createStreamLayout;
- (id)createFlowLayout;
- (double)getCurFooterHeight;
- (long long)sectionNumber;
- (long long)feedFlowSection;
- (BOOL)isFeedsFlowSection:(long long)a0;
- (long long)itemNumberAtSection:(long long)a0;
- (id)getContentVMAtIndexPath:(id)a0;
- (BOOL)isCustomCellAtIndexPath:(id)a0;
- (id)getCustomCellAtIndexPath:(id)a0;
- (BOOL)isCustomSupplementaryViewOfKind:(id)a0 atSection:(long long)a1;
- (id)getCustomSupplementaryViewOfKind:(id)a0 atIndexPath:(id)a1;
- (id)tipsConfigWithType:(unsigned long long)a0 inState:(unsigned long long)a1;
- (void)hiddenTopTipsViewWithCompletion:(id /* block */)a0 animated:(BOOL)a1 delay:(double)a2;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })collectionViewContentInsetInTopLoadingState:(BOOL)a0;
- (BOOL)hasTopLoading;
- (void)forbidAutoPlay;
- (void)triggerCellAutoPlay;
- (void)_autoPlayCell;
- (void)preloadVideoFirstFrame;
- (BOOL)collectionView:(id)a0 layout:(id)a1 pinHeaderToVisibleBoundsAtSection:(unsigned long long)a2;
- (long long)numberOfSectionsInCollectionView:(id)a0;
- (long long)collectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (id)collectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (id)collectionView:(id)a0 viewForSupplementaryElementOfKind:(id)a1 atIndexPath:(id)a2;
- (void)collectionView:(id)a0 didSelectItemAtIndexPath:(id)a1;
- (void)checkUIDataDistinctWithIndexPath:(id)a0;
- (void)checkUIDataDistinctWithIndexPaths:(id)a0;
- (void)collectionView:(id)a0 willDisplayCell:(id)a1 forItemAtIndexPath:(id)a2;
- (void)collectionView:(id)a0 didEndDisplayingCell:(id)a1 forItemAtIndexPath:(id)a2;
- (void)collectionView:(id)a0 willDisplaySupplementaryView:(id)a1 forElementKind:(id)a2 atIndexPath:(id)a3;
- (void)collectionView:(id)a0 didEndDisplayingSupplementaryView:(id)a1 forElementOfKind:(id)a2 atIndexPath:(id)a3;
- (void)scrollViewDidScroll:(id)a0;
- (BOOL)scrollViewShouldScrollToTop:(id)a0;
- (void)scrollViewDidScrollToTop:(id)a0;
- (void)_refreshHeadOnScrolltoTop;
- (void)scrollViewWillEndDragging:(id)a0 withVelocity:(struct CGPoint { double x0; double x1; })a1 targetContentOffset:(inout struct CGPoint { double x0; double x1; } *)a2;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (void)scrollViewDidEndScrollingAnimation:(id)a0;
- (void)_endScrolling:(id)a0;
- (unsigned long long)collectionView:(id)a0 layout:(id)a1 columnCountAtSection:(unsigned long long)a2;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 cellSpaceAtSection:(unsigned long long)a2;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })collectionView:(id)a0 layout:(id)a1 cellEdgeInsetAtSection:(unsigned long long)a2;
- (double)collectionView:(id)a0 layout:(id)a1 cellHeightAtIndexPath:(id)a2 withWidth:(double)a3;
- (double)collectionView:(id)a0 layout:(id)a1 headerHeightAtSection:(unsigned long long)a2;
- (double)collectionView:(id)a0 layout:(id)a1 footerHeightAtSection:(unsigned long long)a2;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })collectionView:(id)a0 layout:(id)a1 headerEdgeInsetAtSection:(unsigned long long)a2;
- (double)collectionView:(id)a0 layout:(id)a1 decorationHeightAtSection:(unsigned long long)a2;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })collectionView:(id)a0 layout:(id)a1 decorationEdgeInsetAtSection:(unsigned long long)a2;
- (id)collectionView:(id)a0 layout:(id)a1 decorationLayoutAttributesAtSection:(unsigned long long)a2;
- (BOOL)isOnLoadingState;
- (int)feedViewControllerScene;
- (id)getCurrentVC;
- (void)onClickCoverContact:(id)a0 contentVM:(id)a1;
- (void)onClickFollowReccommendLabel:(id)a0;
- (void)onLongPress:(id)a0;
- (void)onClickRemoveAction:(id)a0;
- (void)onClickAnchorAction:(id)a0;
- (void)onClickMutiSelectedAction:(id)a0;
- (void)onClickForwardAction:(id)a0;
- (void)onClickEditTagAction:(id)a0;
- (void)onClickDeleteAction:(id)a0 contentVM:(id)a1;
- (void)onSelectItem:(id)a0 selected:(BOOL)a1;
- (id)getSelectedItems;
- (void)unSelecteAll;
- (void)cellNeedsUpdateHeight:(id)a0;
- (void)finderFlowTopTipsViewDidTriggerRefresh:(id)a0;
- (BOOL)finderFlowTopTipsViewDataSourceIsLoading:(id)a0;
- (void)clickNoMoreDataNavToRecBtn:(id)a0;
- (void)didClickStreamFooterRefresh:(id)a0;
- (void)finderEmptyTipsView:(id)a0 didClickOnState:(unsigned long long)a1;
- (void)finderEmptyTipsView:(id)a0 didClickLink:(id)a1;
- (void)resignCollectionViewCells;
- (void)setupCellExposureRateReportWithCell:(id)a0 indexPath:(id)a1;
- (void)reportFlowExposeForCell:(id)a0 atIndexPath:(id)a1 actionType:(long long)a2;
- (void)reportFeedStreamClickWithCollectionView:(id)a0 selectedIndexPath:(id)a1;
- (void)monitorView:(id)a0 newExposedItems:(id)a1 lastExposedItems:(id)a2;
- (id)onStaticCellLeftTopBadgeContent:(id)a0;
- (void)checkViewsLoadingState;
- (void)checkTopTipsViewLoadingState;
- (void)checkFooterViewLoadingState;
- (void)checkEmptyTipsViewLoadingState;
- (BOOL)isViewVisibleOnScreen:(id)a0;
- (void)addLongPressAction;
- (void).cxx_destruct;

@end
