@class WCFinderFullToolbarView, UIView, WCFinderPanelHotCommentView, WCFinderLandScapeCollectionDisplayView, WCFinderFeedContentVM, WCFinderLandScapePlayerParam, WCFinderLandScapeVideoDisplayViewInitParams, NSString, RichTextView, WCFinderFriendLikeToolbarView, WCFinderHeadInfoEasyView, WCFinderLandScapeVideoInteractivePlayerView;
@protocol WCFinderLandScapeVideoDisplayViewDelegate, WCFinderHeadInfoViewDelegate, WCFinderFullToolbarViewDelegate;

@interface WCFinderLandScapeVideoDisplayView : MMUIView <WCFinderHeadInfoViewDelegate, WCFinderFullToolbarViewDelegate, WCFinderLandScapeVideoInteractivePlayerViewDelegate, WCFinderFriendLikeToolbarViewDelegate, WCFinderPanelHotCommentViewDelegate, WCFinderLandScapeCollectionDisplayViewDelegate>

@property (retain, nonatomic) UIView *statusBarBackgroundView;
@property (retain, nonatomic) WCFinderLandScapeVideoInteractivePlayerView *interactivePlayerView;
@property (retain, nonatomic) RichTextView *descLabel;
@property (retain, nonatomic) RichTextView *feedTitleLabel;
@property (retain, nonatomic) WCFinderPanelHotCommentView *hotCommentView;
@property (retain, nonatomic) UIView *descInteractiveView;
@property (retain, nonatomic) UIView *containerView;
@property (retain, nonatomic) WCFinderHeadInfoEasyView *headInfoView;
@property (retain, nonatomic) WCFinderFullToolbarView *toolBarView;
@property (retain, nonatomic) WCFinderFriendLikeToolbarView *friendLikeToolBarView;
@property (retain, nonatomic) WCFinderLandScapeCollectionDisplayView *collectionView;
@property (retain, nonatomic) UIView *collectionTopSeperator;
@property (retain, nonatomic) UIView *collectionViewContainer;
@property (retain, nonatomic) WCFinderFeedContentVM *contentVM;
@property (retain, nonatomic) WCFinderLandScapePlayerParam *param;
@property (retain, nonatomic) WCFinderLandScapeVideoDisplayViewInitParams *setupParams;
@property (nonatomic) BOOL isPreOrientationLandScape;
@property (weak, nonatomic) id<WCFinderHeadInfoViewDelegate, WCFinderFullToolbarViewDelegate, WCFinderLandScapeVideoDisplayViewDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)shouldShowFriendLikeToolbarViewWithContentVM:(id)a0;
+ (double)heightWithContentVM:(id)a0 param:(id)a1 width:(double)a2;

- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 params:(id)a1;
- (void)reloadToolBar;
- (void)changeToolBarHiddenState;
- (void)changeToolBarHiddenState:(BOOL)a0;
- (BOOL)isFriendLikeToolBarHidden;
- (id)getInteractiveView;
- (void)restoreInteractiveView:(id)a0;
- (id)getPlayerViewAndClear;
- (void)restorePlayerView:(id)a0;
- (id)getFinderPlayerView:(BOOL)a0;
- (void)playVideo;
- (void)playVideoWithStartTime:(double)a0 isSilencePlay:(BOOL)a1;
- (void)stopVideo;
- (BOOL)isPlayingVideo;
- (id)getPlayerView;
- (void)pauseVideo;
- (void)resumeVideo;
- (void)setup;
- (void)setupViews;
- (void)setupViewLandScapeState;
- (void)landScapeStatWillChange:(BOOL)a0;
- (id)getPlayerViewSnapshot;
- (void)setPlayerInteractiveEnable:(BOOL)a0;
- (void)stopSpeedPlay;
- (double)foldMinBottom;
- (void)moveHeaderToolWithY:(double)a0;
- (void)_moveReleatedViewWithY:(double)a0;
- (BOOL)canMoveHeaderToolToTop;
- (void)moveHeaderToolToTop;
- (BOOL)canMoveHeaderToolToBottom;
- (void)moveHeaderToolToBottom;
- (BOOL)pointIsOnPlayerArea:(struct CGPoint { double x0; double x1; })a0;
- (void)updateWithContentVM:(id)a0 param:(id)a1;
- (void)updateHotCommentUIWithContentVM:(id)a0;
- (void)updateLikeToolStateWithContentVM:(id)a0;
- (void)updateBulletState;
- (void)adjustLayoutInLandScapeState;
- (void)adjustPlayerViewLayoutInPortialState;
- (void)adjustLayoutInPoratialState;
- (void)adjustLayoutInPoratialState:(BOOL)a0;
- (double)getCurrentPlayVideoTime;
- (double)getCurrentPlayVideoPercent;
- (void)onCollectionDisplayViewReadyToShowStateChanged:(BOOL)a0;
- (void)onCollectionDisplayViewDidSelectContentVM:(id)a0;
- (void)onFinderLandScapeInteractiveViewAntiAddictCheckLogic;
- (void)onFinderLandScapeInteractiveViewClickRotateBtn;
- (void)onFinderLandScapeInteractiveViewClickPauseBtn:(BOOL)a0;
- (void)onFinderLandScapeInteractiveViewClickReturnBtn;
- (void)onFinderLandScapeInteractiveViewClickBulletBtn;
- (void)onFinderLandScapeInteractiveViewClickBulletSwitchBtn:(BOOL)a0;
- (void)onFinderLandScapeInteractiveViewClickPlayRateBtnWithRate:(double)a0;
- (void)onFinderLandScapeInteractiveViewStartPan;
- (void)onFinderLandScapeInteractiveViewEndPan;
- (void)onFinderLandScapeInteractiveViewDidStartLongPressSpeedPlay:(double)a0;
- (void)onFinderLandScapeInteractiveViewDidEndLongPressSpeedPlay:(double)a0;
- (void)onFinderLandScapeInteractiveViewClickPlayNextVideoWithDataItem:(id)a0;
- (BOOL)shouldHiddenHeadInfoViewFollowBtn;
- (void)onFinderLandScapeInteractiveViewVideoUpdatePosition:(double)a0 videoDuration:(double)a1 maxPlayVideoTime:(double)a2;
- (void)onFinderLandScapeInteractiveViewContentMediaDidEndPlay;
- (void)onClickDescLabel;
- (void)onRefreshFriendUI:(id)a0;
- (void)onClickFriendLikeListDetail:(id)a0;
- (void)onClickPanelHotComment:(id)a0;
- (void).cxx_destruct;

@end
