@class NSString, NSArray;

@interface WCFinderLiveProductShareItem : NSObject <YYModel, NSCoding, NSCopying, PBCoding>

@property (copy, nonatomic) NSString *firstProductTagURL;
@property (nonatomic) double firstProductTagAspectRatio;
@property (copy, nonatomic) NSString *secondProductTagURL;
@property (nonatomic) double secondProductTagAspectRatio;
@property (nonatomic) int scene;
@property (copy, nonatomic) NSString *flashSalePrice;
@property (copy, nonatomic) NSString *flashSaleEndTime;
@property (copy, nonatomic) NSString *firstProductTagAspectRatioString;
@property (copy, nonatomic) NSString *secondProductTagAspectRatioString;
@property (copy, nonatomic) NSArray *showBoxItemStringList;
@property (copy, nonatomic) NSString *finderLiveID;
@property (copy, nonatomic) NSString *finderUsername;
@property (copy, nonatomic) NSString *finderObjectID;
@property (copy, nonatomic) NSString *finderNonceID;
@property (copy, nonatomic) NSString *liveStatus;
@property (nonatomic) unsigned long long finderLiveStatus;
@property (nonatomic) BOOL isLiveEndState;
@property (readonly, nonatomic) BOOL hasLimitDiscount;
@property (copy, nonatomic) NSString *appId;
@property (copy, nonatomic) NSString *pagePath;
@property (copy, nonatomic) NSString *productId;
@property (copy, nonatomic) NSString *coverUrl;
@property (copy, nonatomic) NSString *productTitle;
@property (copy, nonatomic) NSString *marketPrice;
@property (copy, nonatomic) NSString *sellingPrice;
@property (copy, nonatomic) NSString *discountWording;
@property (copy, nonatomic) NSString *sellingPriceWording;
@property (copy, nonatomic) NSString *platformHeadImg;
@property (copy, nonatomic) NSString *platformName;
@property (copy, nonatomic) NSString *shopWindowId;
@property (copy, nonatomic) NSString *platformIconURL;
@property (copy, nonatomic) NSString *promoterKey;
@property (nonatomic) unsigned long long cpsProductId;
@property (nonatomic) unsigned int valueOfFlashSalePrice;
@property (nonatomic) unsigned long long valueOfFlashSaleEndTime;
@property (copy, nonatomic) NSArray *productTags;
@property (retain, nonatomic) NSArray *showBoxItemList;
@property (retain, nonatomic) NSString *ecSource;
@property (copy, nonatomic) NSString *lastGMsgID;
@property (nonatomic) BOOL isPriceBeginShow;
@property (copy, nonatomic) NSString *priceSuffixDescription;
@property (copy, nonatomic) NSString *productCardKey;
@property (nonatomic) BOOL isWxShop;
@property (copy, nonatomic) NSString *brandIconUrl;
@property (copy, nonatomic) NSString *rIconUrl;
@property (copy, nonatomic) NSString *rIconUrlDarkmode;
@property (copy, nonatomic) NSString *topShopIconUrl;
@property (copy, nonatomic) NSString *topShopIconUrlDarkmode;
@property (copy, nonatomic) NSString *simplifyTopShopIconUrl;
@property (copy, nonatomic) NSString *simplifyTopShopIconUrlDarkmode;
@property (nonatomic) unsigned int topShopIconWidth;
@property (nonatomic) unsigned int topShopIconHeight;
@property (nonatomic) unsigned int simplifyTopShopIconWidth;
@property (nonatomic) unsigned int simplifyTopShopIconHeight;
@property (copy, nonatomic) NSString *maskPriceWording;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)PBArrayAdd_finderLiveID;
+ (void)PBArrayAdd_finderUsername;
+ (void)PBArrayAdd_finderObjectID;
+ (void)PBArrayAdd_finderNonceID;
+ (void)PBArrayAdd_appId;
+ (void)PBArrayAdd_pagePath;
+ (void)PBArrayAdd_productId;
+ (void)PBArrayAdd_coverUrl;
+ (void)PBArrayAdd_productTitle;
+ (void)PBArrayAdd_marketPrice;
+ (void)PBArrayAdd_sellingPrice;
+ (void)PBArrayAdd_platformHeadImg;
+ (void)PBArrayAdd_platformName;
+ (void)PBArrayAdd_shopWindowId;
+ (void)PBArrayAdd_liveStatus;
+ (void)PBArrayAdd_valueOfFlashSalePrice;
+ (void)PBArrayAdd_valueOfFlashSaleEndTime;
+ (void)PBArrayAdd_ecSource;
+ (void)PBArrayAdd_sellingPriceWording;
+ (void)PBArrayAdd_platformIconURL;
+ (void)PBArrayAdd_firstProductTagURL;
+ (void)PBArrayAdd_firstProductTagAspectRatio;
+ (void)PBArrayAdd_secondProductTagURL;
+ (void)PBArrayAdd_secondProductTagAspectRatio;
+ (void)PBArrayAdd_isPriceBeginShow;
+ (void)PBArrayAdd_lastGMsgID;
+ (void)PBArrayAdd_discountWording;
+ (void)PBArrayAdd_promoterKey;
+ (void)PBArrayAdd_showBoxItemList;
+ (void)PBArrayAdd_priceSuffixDescription;
+ (void)PBArrayAdd_productCardKey;
+ (void)PBArrayAdd_isWxShop;
+ (void)PBArrayAdd_brandIconUrl;
+ (void)PBArrayAdd_rIconUrl;
+ (void)PBArrayAdd_rIconUrlDarkmode;
+ (void)PBArrayAdd_topShopIconUrl;
+ (void)PBArrayAdd_topShopIconUrlDarkmode;
+ (void)PBArrayAdd_simplifyTopShopIconUrl;
+ (void)PBArrayAdd_simplifyTopShopIconUrlDarkmode;
+ (void)PBArrayAdd_topShopIconWidth;
+ (void)PBArrayAdd_topShopIconHeight;
+ (void)PBArrayAdd_simplifyTopShopIconWidth;
+ (void)PBArrayAdd_simplifyTopShopIconHeight;
+ (void)PBArrayAdd_maskPriceWording;
+ (void)initialize;
+ (id)modelPropertyBlacklistForConfigTag:(id)a0;

- (id)getPBPropertyTable;
- (id)initWithScene:(int)a0;
- (id)initWithCoder:(id)a0;
- (BOOL)fromXML:(struct XmlReaderNode_t { } *)a0;
- (id)toXML;
- (void)encodeWithCoder:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)genFinderDataItem;
- (void).cxx_destruct;

@end
