@class WCCreateNewGroupDemoViewController, NSString, NSArray, NSMutableSet, NSMutableDictionary, NSMutableArray, MMTableView;
@protocol WCGroupTagViewControllerDelegate;

@interface WCGroupTagDemoViewController : MMUIViewController <WCCreateNewGroupDemoViewControllerDelegate, WCFacadeExt, GroupSelectContactsViewControllerDelegate, IContactLabelMgrExt, MultiSelectContactsViewControllerDelegate, UITableViewDataSource, UITableViewDelegate> {
    long long m_originPrivacy;
    long long m_currentPrivacy;
    NSMutableArray *m_arrAllLabelName;
    NSMutableSet *m_currentLabelName;
    NSMutableSet *m_originLabelName;
    MMTableView *m_tableView;
    BOOL m_hasTryTransferLabel;
    NSMutableDictionary *m_dicGroupLabel;
    unsigned int m_transferEventId;
    long long m_transferPrivacy;
    double m_originContentOffset;
    BOOL m_bShowDetail;
    WCCreateNewGroupDemoViewController *newGroup;
    NSMutableSet *m_contactSetImportFromGroup;
    NSMutableSet *m_contactSetNotImportFromGroup;
}

@property (nonatomic) unsigned int createTagEventId;
@property (retain, nonatomic) NSString *createTagName;
@property (retain, nonatomic) NSArray *undeterminedTempContacts;
@property (retain, nonatomic) NSArray *originTmpSelectContacts;
@property (nonatomic) BOOL isImportTagFromGroupEnable;
@property (retain, nonatomic) NSArray *tmpSelectChatroomContacts;
@property (nonatomic) BOOL isMultiSelectOpenForChatroom;
@property (weak, nonatomic) id<WCGroupTagViewControllerDelegate> m_delegate;
@property (nonatomic) BOOL m_privacyGroupHidden;
@property (nonatomic) BOOL m_privacyGroupAndVisibleHidden;
@property (retain, nonatomic) NSString *m_title;
@property (retain, nonatomic) NSArray *tmpSelectContact;
@property (nonatomic) unsigned long long sourceScene;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)init;
- (id)initWithOriginPrivacy:(long long)a0 originContact:(id)a1 originLabel:(id)a2;
- (void)viewDidLoad;
- (void)viewDidBePushOrPresent:(BOOL)a0;
- (void)viewDidBePopedOrDismissed:(BOOL)a0;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)didReceiveMemoryWarning;
- (void)initData;
- (void)initView;
- (id)getAllTmpSelectArray;
- (void)reloadAllTableView;
- (void)onWCGroupUpdated;
- (void)willShow;
- (id)loadAllTagNameList;
- (long long)numberOfSectionsInTableView:(id)a0;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (double)tableView:(id)a0 heightForRowAtIndexPath:(id)a1;
- (id)tableView:(id)a0 viewForHeaderInSection:(long long)a1;
- (double)tableView:(id)a0 heightForHeaderInSection:(long long)a1;
- (int)getCellType:(id)a0;
- (BOOL)isSelected:(int)a0 postPrivacy:(long long)a1 indexPath:(id)a2;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (void)showTransferTip;
- (void)onShowTransferTipConfirm;
- (void)tableView:(id)a0 didSelectRowAtIndexPath:(id)a1;
- (BOOL)canSelectPrivacySetting:(long long)a0;
- (void)onDataChange;
- (BOOL)hasChangePrivacy;
- (void)onReturn;
- (void)onDone;
- (void)openAddFromChatroom;
- (void)editContactLabels;
- (void)onAllTagNameUpdate;
- (void)selectContacts;
- (void)createNewLabel:(id)a0;
- (void)onMultiSelectContactReturn:(id)a0 selectContactFromGroup:(id)a1;
- (void)onMultiSelectContactReturn:(id)a0;
- (void)onMultiSelectContactReturnForSns:(id)a0;
- (void)onSaveAsNewGroup;
- (void)onMultiSelectContactCancelForSns;
- (void)onTagNameEditViewControllerRetWithTagName:(id)a0;
- (void)onAddContactLabel:(id)a0 withRetCode:(int)a1 andEventId:(unsigned int)a2;
- (void)sortAndSaveSnsGroupLabel;
- (void)setContactLabel:(id)a0 withRetCode:(int)a1 andEventId:(unsigned int)a2;
- (void)deleteOldSnsGroup;
- (void)handleCreateContactLabel:(id)a0 withRetCode:(int)a1 andEventId:(unsigned int)a2;
- (id)contactNamesComponentsJoinedByComma:(id)a0;
- (void)handleCreateToSetContactLabel:(id)a0 withRetCode:(int)a1 andEventId:(unsigned int)a2;
- (void)reportSaveNewGroupAlertAction:(unsigned long long)a0 count:(unsigned long long)a1;
- (void).cxx_destruct;

@end
