@class UIView, UILabel, NSString, UIImageView, UIButton, WCPayCss, RichTextView, EXTPKG_mmpayapplynfccardbo_CardTypeInfo, WCPayWebImageView, MMUIButton;
@protocol WCPayNFCCardApplyViewControllerDelegate;

@interface WCPayNFCCardApplyViewController : WCPayBaseViewController <ILinkEventExt, WCPayNFCCardDepositViewDelegate>

@property (weak, nonatomic) id<WCPayNFCCardApplyViewControllerDelegate> m_delegate;
@property (retain, nonatomic) UIView *contentView;
@property (retain, nonatomic) WCPayWebImageView *nfcCardImageView;
@property (retain, nonatomic) WCPayCss *css;
@property (retain, nonatomic) UIView *cardInfoView;
@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UIView *tagsView;
@property (retain, nonatomic) UIView *seperatorView;
@property (retain, nonatomic) EXTPKG_mmpayapplynfccardbo_CardTypeInfo *m_viewData;
@property (retain, nonatomic) UILabel *preChargeLabel;
@property (retain, nonatomic) UIView *preChargeAmountContentView;
@property (retain, nonatomic) UILabel *depositTitleView;
@property (retain, nonatomic) UIView *depositContentView;
@property (retain, nonatomic) UIView *cardAboutContentView;
@property (retain, nonatomic) UIView *bottomContentView;
@property (retain, nonatomic) UIView *bottomViewUpperLine;
@property (retain, nonatomic) UIView *bottomViewLowerLine;
@property (retain, nonatomic) UIView *protocolView;
@property (retain, nonatomic) UIView *chargeConfirmView;
@property (retain, nonatomic) MMUIButton *checkBoxButton;
@property (nonatomic) BOOL isChecked;
@property (retain, nonatomic) RichTextView *protocolTextView;
@property (retain, nonatomic) UILabel *cardAboutTitleView;
@property (retain, nonatomic) UIView *cardApplyFeeView;
@property (retain, nonatomic) UILabel *cardApplyFeeTitleView;
@property (retain, nonatomic) UILabel *cardApplyFeeKeyLaxbel;
@property (retain, nonatomic) UILabel *cardApplyFeeValueLabel;
@property (retain, nonatomic) UIView *cardAboutInfoContentView;
@property (retain, nonatomic) UILabel *amountLabelPrefix;
@property (retain, nonatomic) UILabel *amountLabel;
@property (retain, nonatomic) UILabel *cardApplyAmountNameLabel;
@property (retain, nonatomic) UIView *amountContentView;
@property (retain, nonatomic) UIButton *confirmButton;
@property (nonatomic) long long selectedDepositAmount;
@property (retain, nonatomic) UILabel *cardChargeFeeTipsLabel;
@property (retain, nonatomic) UIImageView *maskView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)onWCPayNFCCardDepositViewTap:(long long)a0;
- (void)updateDepositContentViewState;
- (void)viewDidLoad;
- (void)setDelegate:(id)a0;
- (void)viewDidLayoutSubviews;
- (void)viewDidBePoped:(BOOL)a0;
- (void)onBack;
- (void)initNavigationBar;
- (void)refreshViewWithData:(id)a0;
- (void)updateView;
- (void)updateTailView;
- (void)updateNFCCardImageView;
- (void)updateCardInfoView;
- (void)updateApplyCardFeeView;
- (void)updateBottomContent;
- (void)updateMaskView;
- (id)navigationBarBackgroundColor;
- (void)updateChargeConfirmView;
- (void)onClickConfirmButton:(id)a0;
- (double)totalAmount;
- (void)onTapCheckBox;
- (void)updateProtocolView;
- (void)updateTitleLabel;
- (void)updateTags;
- (void)updateSeperator;
- (void)updateDepositView;
- (void)updateDepositTipsView;
- (void)updateDepositContentView;
- (void)updateCardAbountInfoView;
- (double)maxTitleLength;
- (void)onLinkClicked:(id)a0 withRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void).cxx_destruct;

@end
