@class NSDictionary, WCRedEnvelopesReportCgi, NSMutableArray, WCPayJumpRemindControlLogic, WCRedEnvelopesGreetingControlLogic, WCRedEnvelopesConfirmShowResourcesCgi, NSString, GetDefaultRedpacketResponse, WCPayControlData, HbEnvelopSource, MemoryMappedKV, WCRedEnvelopesMadeHBSuccessView, WCRedEnvelopesDeleteResourceCgi, WCPayPayMoneyLogic, ContactsCreateChatRoomLogic;
@protocol WCRedEnvelopesSendControlLogicDelegate;

@interface WCRedEnvelopesSendControlLogic : WCRedEnvelopesControlLogic <MMWebViewDelegate, MMTipsViewControllerDelegate, WCRedEnvelopesSelectSkinViewControllerDelegate, WCRedEnvelopesExpiredSkinViewControllerDelegate, WCRedEnvelopesGetShowResourcesCgiDelegate, WCRedEnvelopesConfirmShowResourcesCgiDelegate, WCPayPayMoneyLogicDelegate, WCRedEnvelopesReportCgiDelegate, WCRedEnvelopesDeleteResourceCgiDelegate, WCRedEnvelopesCheckAndUseTimeLimitPromoCgiDelegate, MMUseCaseCallback, WCPaySelectChatroomMemberViewControllerDelegate, WCPaySingleDownloadLogicExt, GetCoverSetRedDotInfoCgiDelegate, WCRedEnvelopesGetFullCoverInfoCgiDelegate, GetDefaultRedPacketSkinCgiDelegate, GetWishinigRecommandSkinCgiDelegate, WCBaseControlLogicDeleagte, WCBaseControlMgrExt, WCRedEnvelopesWelcomePageViewControllerDelegate, WCRedEnvelopesMakeRedEnvelopesViewControllerDelegate, WCRedEnvelopesMultiSelectContactsViewControllerDelegate, WCRedEnvelopesSessionSelectViewControllerDelegate, WCActionSheetDelegate, IWCPayControlLogicExt, WCRedEnvelopesMadeHBSuccessViewDelegate, ContactsCreateChatRoomLogicDelegate> {
    WCPayPayMoneyLogic *m_payMoneyLogic;
    WCPayControlData *oPayData;
    int m_scene;
    unsigned long long m_enMadeRedEnvelopesType;
    WCRedEnvelopesMadeHBSuccessView *m_oWCRedEnvelopesMadeHBSuccessView;
    ContactsCreateChatRoomLogic *createChatRoomLogic;
}

@property (retain, nonatomic) NSString *curAlertRightUrl;
@property (retain, nonatomic) WCRedEnvelopesConfirmShowResourcesCgi *confirmShowResourcesCgi;
@property (retain, nonatomic) WCRedEnvelopesDeleteResourceCgi *deleteShowResourceCgi;
@property (retain, nonatomic) WCRedEnvelopesReportCgi *reportWxhbCgi;
@property (retain, nonatomic) HbEnvelopSource *selectedConfirmHbResource;
@property (retain, nonatomic) NSMutableArray *downloadHbSourceQueue;
@property (retain, nonatomic) NSDictionary *lastReqKeyStruck;
@property (retain, nonatomic) WCPayJumpRemindControlLogic *jumpRemindLogic;
@property (nonatomic) BOOL isUserConfirmJump;
@property (nonatomic) long long lastUnpayReason;
@property (retain, nonatomic) NSString *uniqueId;
@property (nonatomic) BOOL isNeedReturnToSession;
@property (retain, nonatomic) WCRedEnvelopesGreetingControlLogic *m_sendGreetingHBLogic;
@property (nonatomic) BOOL isRetryOperationWhenPrepay;
@property (retain) NSString *reportSessionId;
@property (retain, nonatomic) NSString *baiNianEntryName;
@property (nonatomic) BOOL bIsFromLoadingMoreInvalidData;
@property (nonatomic) BOOL bIsFromWebScene;
@property (retain, nonatomic) GetDefaultRedpacketResponse *defaultRedpacketCacheResponse;
@property (retain, nonatomic) MemoryMappedKV *skinNewLogicMMKV;
@property (retain, nonatomic) NSString *openSkinPlazaLiteAppQuery;
@property (nonatomic) int currentClickedCoverType;
@property (nonatomic) unsigned long long getRecommendedCoverRequestId;
@property (retain, nonatomic) NSString *currentWishing;
@property (weak, nonatomic) id<WCRedEnvelopesSendControlLogicDelegate> m_delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)getData;
- (id)initWithData:(id)a0;
- (id)initWithData:(id)a0 Scene:(int)a1 RedEnvelopesType:(unsigned long long)a2;
- (id)userInfoCachePath;
- (BOOL)shouldRequestGetDefaultSkinCgi;
- (int)requestGetDefaultSkinScene;
- (void)QueryRedEnvelopesUserInfo:(id)a0;
- (void)QueryRedEnvelopesUserInfoNoCache:(id)a0;
- (void)GenRedEnvelopesPayRequest:(id)a0;
- (unsigned long long)getRoomContactMemCount;
- (void)startLogic;
- (void)startGetDefualtRedPacketSkinCgi:(BOOL)a0 scene:(int)a1;
- (void)startGetDefualtRedPacketSkinCgi:(BOOL)a0;
- (BOOL)checkLocalCacheIsExipredAndRefresh;
- (void)onGetDefaultRedPacketSkinCgiResponse:(id)a0 isUseCache:(BOOL)a1;
- (void)onGetDefaultRedPacketSkinCgiError:(id)a0 errorCode:(unsigned int)a1;
- (id)getQueryRedEnvelopesRequestDict;
- (BOOL)isRedskinUseNewLogic;
- (id)getRedSkinNewLogicMMKV;
- (void)saveRedskinIsUseNewLogic:(BOOL)a0;
- (void)refreshViewController;
- (id)convertHbEnvelopSourceNewIntoHbEnvelopSource:(id)a0;
- (id)getCurrentMakeRedViewController;
- (void)internalStartLogicWithSimpleSessionScene;
- (void)internalStartLoigcWithGroupSessionScene:(id)a0;
- (void)toGroupRedEnvelopes;
- (BOOL)shouldShowWeiShiEntry:(id)a0;
- (BOOL)shouldShowLiveStreamEntry:(id)a0;
- (id)weiShiConfig;
- (id)weiShiWordingConfig;
- (id)titleForWeiShi;
- (id)descForWeiShi;
- (id)schemeForWeishi;
- (BOOL)disableShareForWeishiUrl;
- (id)urlForWeishi;
- (id)appstoreForWeishi;
- (long long)maxCountForWeishiUrl;
- (id)maxCountStoreKeyForWeishiUrl;
- (BOOL)shouldShowHongBaoAbtestEntry;
- (void)stopLogic;
- (BOOL)hasChoseNonDefaultRedSkin;
- (void)OnWCRedEnvelopesWelcomePageViewControllerBack;
- (void)OnWCRedEnvelopesWelcomePageViewControllerMyRedEnvelopesList;
- (void)actionSheet:(id)a0 clickedButtonAtIndex:(long long)a1;
- (void)checkAndGoWeishi;
- (void)OnWCRedEnvelopesWelcomePageViewControllerSelectRadmonRedEnvelopes;
- (void)OnWCRedEnvelopesWelcomePageViewControllerSelectNormalRedEnvelopes;
- (void)OnWCRedEnvelopesMakeRedEnvelopesViewControllerBack;
- (void)OnMakeWCRedEnvelopesButtonClick:(id)a0;
- (void)GenLiveStreamRedEnvelopesPayRequest:(id)a0;
- (void)OnClickNotReceivedButton;
- (void)OnClickViewHBHistory;
- (BOOL)canShowExclusiveHbModeEntry;
- (void)onClickSelectMemberView;
- (void)gotoSelectSessionViewController;
- (void)onPayMoneyLogicDidStop;
- (void)onWCBaseLogicDidStop:(unsigned int)a0;
- (void)OnGotoRootViewController;
- (void)showSetPwdTipsView;
- (void)onClickTipsBtn:(id)a0 Index:(long long)a1 withText:(id)a2 withTipsVC:(id)a3;
- (void)onMultiSelectContactReturn:(id)a0;
- (void)OnConfirmSendMessageSelectSessionViewController;
- (void)OnConfirmCreateChatRoomAndSendMessageSelectSessionViewController;
- (void)OnSelectSession:(id)a0 SessionSelectController:(id)a1;
- (void)OnSelectSessionReturn:(id)a0;
- (void)OnSelectSessionCancel:(id)a0;
- (void)GotoNotReceivedListLogic;
- (void)OnSelectMutilContactsButton;
- (void)OnCreateRoom:(id)a0;
- (void)OnWCRedEnvelopesSendSuccessViewAnimationDidStop;
- (void)WCRedEnvelopesMadeHBSuccessViewBack;
- (void)WCRedEnvelopesMadeHBSuccessViewSendHB;
- (BOOL)gotoViewController:(id)a0;
- (void)OnQueryRedEnvelopesUserInfo:(id)a0 isCahceInfo:(BOOL)a1 Error:(id)a2;
- (void)startGetSkinCoverRedDotInfoCgi;
- (void)onGetCoverSetRedDotInfoCgiResponse:(id)a0;
- (void)handleCoverReddotInfo:(id)a0;
- (void)saveLocalRedDotInfoAndRefreshPage:(id)a0;
- (void)preDownloadHbShowResourceFromCoverInfoDetail:(id)a0;
- (void)preDownloadHbShowResource:(id)a0;
- (void)startDownloadDynmiacPagWithUrl:(id)a0 info:(id)a1;
- (void)onDownloadTaskCompletion:(long long)a0 taskUrl:(id)a1 extraInfo:(id)a2 filePath:(id)a3 totalLength:(unsigned long long)a4;
- (void)OnGenRedEnvelopesPayRequest:(id)a0 Error:(id)a1;
- (void)onErrorAlertViewDismiss:(id)a0;
- (void)handleShouldRelpaceCoverInfoDetail;
- (void)startGetFullCoverInfoDetail:(id)a0;
- (void)onGetFullCoverInfoCgiResp:(id)a0 messageWrap:(id)a1;
- (void)onGetFullCoverInfo:(id)a0 messageWrap:(id)a1;
- (void)OnContinueGenRedEnvelopesPayRequest:(id)a0 Error:(id)a1;
- (void)OnGenH5RedEnvelopesPayRequest:(id)a0 Error:(id)a1;
- (void)onGetH5PayNativeCashierResult:(BOOL)a0;
- (void)OnSendShareRedEnvelopesoRequest:(id)a0 Error:(id)a1;
- (void)OnJumpedToReceiveList;
- (void)setScene:(int)a0;
- (void)onWebViewWillClose:(id)a0;
- (void)webViewReturn:(id)a0;
- (void)prepayAlertViewConfirmClick;
- (void)liteappQueryAppendReddotInfo;
- (void)appendLiteAppInfoQuery;
- (void)openSkinPlazaLiteApp;
- (void)liteAppCreateStore:(id)a0;
- (void)onSkinPlazaLiteAppClickLeftButton;
- (void)OnClickSelectSkin;
- (void)startGetShowResourcesCgi;
- (void)onWCRedEnvelopesGetShowResourcesCgiResponseOK:(id)a0 type:(unsigned int)a1;
- (void)handleSourceListTypeInvalidResponse:(id)a0;
- (void)appendShowSourceResp:(id)a0;
- (void)onWCRedEnvelopesGetShowResourcesCgiError:(id)a0 errorCode:(unsigned int)a1;
- (void)OnWCRedEnvelopesSelectSkinViewControllerCheckAndUseDone;
- (void)onWCRedEnvelopesConfirmShowResourcesCgiResponseOK:(id)a0;
- (void)onWCRedEnvelopesConfirmShowResourcesCgiError:(id)a0 errorCode:(unsigned int)a1;
- (void)OnWCRedEnvelopesSelectSkinViewControllerConfirm:(id)a0;
- (void)onWCRedEnvelopesCheckAndUseTimeLimitPromoCgiResponseOK:(id)a0;
- (void)oWCRedEnvelopesCheckAndUseTimeLimitPromoCgiError:(id)a0 errorCode:(unsigned int)a1;
- (void)OnWCRedEnvelopesSelectSkinViewControllerBack;
- (void)OnWCRedEnvelopesSelectSkinViewControllerDelete:(id)a0;
- (void)OnWCRedEnvelopesExpiredSkinViewControllerDelete:(id)a0;
- (void)onWCRedEnvelopesDeleteResourceCgiResponseOK:(id)a0;
- (void)onWCRedEnvelopesDeleteResourceCgiError:(id)a0 errorCode:(unsigned int)a1;
- (void)call:(id)a0;
- (void)callReportWxhbCgi:(int)a0;
- (void)OnWCRedEnvelopesSelectSkinViewControllerNeedRefresh;
- (void)reportWithAction:(unsigned long long)a0;
- (void)reportWithAction:(unsigned long long)a0 sessionId:(id)a1;
- (id)getViewControllerTitle;
- (void)onSelectMemberViewControllerBack;
- (id)getChatroomContact;
- (id)getSameNicknameTips;
- (void)onSelectedContact:(id)a0;
- (void)OnWCRedEnvelopesSelectSkinViewControllerClickExpiredEntry;
- (void)OnWCRedEnvelopesExpireSkinGetNextPage:(id)a0;
- (void)OnWCRedEnvelopesExpiredSkinViewControllerBack;
- (void)onRefreshMakeVC:(BOOL)a0;
- (void)onRequestRecommendCgi:(id)a0;
- (void)onGetWishinigRecommandSkinCgiSuccess:(id)a0 withWishingText:(id)a1 requestTimestamp:(unsigned long long)a2;
- (id)getClickedCoverID;
- (void)onGetWishinigRecommandSkinCgiFailed:(unsigned int)a0 errMsg:(id)a1;
- (void)onWCRedEnvelopesWishingRecommendSkinViewClickLeftArea:(id)a0;
- (void)appendLiteappInfoQuery:(id)a0 value:(id)a1;
- (void)onWCRedEnvelopesWishingRecommendSkinViewClickRightArea:(id)a0;
- (id)getLiteappJumpInfo;
- (void).cxx_destruct;

@end
