@class WCDataSearcher, UILabel, CLLocation, WCTimeLineFooterView, LbsLife, WCUIAlertView, MMAutoSearchLogic, NSMutableArray, UIView, UIColor, NSString, LocationRetriever, MMTableView, MMLocationAccuracyAuthorizationTipView, NSIndexPath;
@protocol WCTimelinePOIPickerViewControllerDelegate;

@interface WCTimelinePOIPickerViewController : MMUILandscapeSheetViewController <UITableViewDelegate, MMTableViewDelegate, UITableViewDataSource, MMRefreshTableFooterDelegate, WCSearchDelegate, WCDataSearchDelegate, ILBSLifeMgrExt, LocationRetrieveDelegate, ILocationMgrExt, POICreateDelegate, IPOILocationDisplayExt, MMAutoSearchLogicDelegate> {
    NSString *_searchKeyword;
    MMTableView *_tableView;
    WCDataSearcher *_searcher;
    UIView *_logoFooterView;
    LocationRetriever *_locationRetriever;
    CLLocation *_lastUpdateLocation;
    WCTimeLineFooterView *_getListTableFooterView;
    WCTimeLineFooterView *_searchTableFooterView;
    unsigned int _scene;
    NSMutableArray *_lifeList;
    NSMutableArray *_searchResultList;
    unsigned long long _geoTag;
    UILabel *_searchErrorTips;
    NSString *_address;
    NSString *_addressAdCode;
    LbsLife *_selectedItem;
    int _poiCreateForbiden;
    BOOL _showCreatePOI;
    long long _startGetListTime;
    long long _firstGetListTime;
    long long _endGetListTime;
    unsigned int _getListPageCount;
    long long _startSearchTime;
    long long _firstSearchTime;
    long long _endSearchTime;
    unsigned int _searchPageCount;
    unsigned int _entryTime;
    NSString *_lastSelectLog;
    NSString *_currentSearchID;
    unsigned int _statImageCount;
    unsigned int _statLocationImageCount;
    BOOL _statHadSearch;
    NSString *_requestId;
    MMAutoSearchLogic *_autoSearchLogic;
    NSIndexPath *_currentIndexPath;
    NSIndexPath *_tempSelectedIndexPath;
    UIView *_authorizationTipContainerView;
    MMLocationAccuracyAuthorizationTipView *_accuracyAuthorizationTipView;
    WCUIAlertView *_currAlertView;
    BOOL _canAlert;
    BOOL _enterBackground;
    BOOL _isSearching;
}

@property (nonatomic) BOOL showAccuracyAuthorizationTip;
@property (nonatomic) int currentAuthLogType;
@property (weak, nonatomic) id<WCTimelinePOIPickerViewControllerDelegate> delegate;
@property (nonatomic) BOOL bSightScene;
@property (nonatomic) int lbsLifeScene;
@property (nonatomic) BOOL ignoreCityInfo;
@property (nonatomic) BOOL ignoreNotCheckInItem;
@property (retain, nonatomic) UIColor *selectTintColor;
@property (nonatomic) int forbidCreatePOI;
@property (nonatomic) unsigned long long locationAuthScene;
@property (nonatomic) BOOL isUseDrakMode;
@property (nonatomic) BOOL isShowDistance;
@property (nonatomic) BOOL forceAdjustTableViewInsetInLayout;
@property (nonatomic) BOOL enableFullRangeSearch;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)reportOnCommitWithString:(id)a0;

- (id)init;
- (void)dealloc;
- (void)initNotifications;
- (void)updateLocation:(id)a0 imageCount:(unsigned int)a1 locaionImageCount:(unsigned int)a2;
- (void)reset;
- (void)viewWillBePushed:(BOOL)a0;
- (void)viewWillBePresented:(BOOL)a0;
- (void)viewDidBePoped:(BOOL)a0;
- (void)viewDidBeDismissed:(BOOL)a0;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewDidLayoutSubviews;
- (double)getTableViewMarginTop;
- (void)checkLocationAuthorization;
- (void)initView;
- (BOOL)showNavigationBarSepLine;
- (void)initAccuracyAuthorizationTipView;
- (void)initSearchBar;
- (void)updateSearchBarTips;
- (void)hideSearchBarTips;
- (void)initTableView;
- (void)addNotCheckInItem;
- (void)addSelectedItem;
- (void)setSelectedItemByLocationInfo:(id)a0;
- (void)adjustSubviewRects;
- (void)showSearchTableLoadMore;
- (void)showDataProviderInfo:(id)a0;
- (void)onCancel;
- (void)onDone;
- (id)getPOIReportStr4Commit;
- (unsigned int)getTrue11135ReportTypeFor:(unsigned int)a0;
- (void)startUpdateLocation;
- (void)stopUpdateLocation;
- (void)onRetrieveLocationOK:(id)a0;
- (void)onRetrieveLocationTimeOut:(id)a0;
- (void)onRetrieveLocationError:(int)a0;
- (void)addCityItem:(id)a0;
- (void)getAddressByLocation:(struct CLLocationCoordinate2D { double x0; double x1; })a0;
- (void)stopGeocoder;
- (void)onDidFindAddress:(id)a0 forTag:(unsigned long long)a1;
- (void)getLBSLife:(BOOL)a0;
- (void)searchLBSLife:(id)a0 StartFromFirst:(BOOL)a1;
- (void)OnGetLBSLife:(id)a0 Error:(int)a1;
- (void)OnAutoSearchLBSLife:(id)a0 Keyword:(id)a1 NextQueryInterval:(double)a2 Error:(int)a3 IsStartFromFirst:(BOOL)a4;
- (void)filterSearchResultList;
- (void)OnSearchLBSLife:(id)a0 Keyword:(id)a1 Error:(int)a2 IsStartFromFirst:(BOOL)a3;
- (void)addLBSLifeListItem:(id)a0;
- (void)addSearchResultItem:(id)a0;
- (void)addCreatePOIItem;
- (void)removeCreatePOIItem;
- (id)poiCityFromLbsLife:(id)a0;
- (id)evolvePoiAddressFromLbsLife:(id)a0;
- (void)selectLBSLife:(id)a0 poiSourceType:(long long)a1;
- (long long)numberOfSectionsInTableView:(id)a0;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (double)tableView:(id)a0 heightForRowAtIndexPath:(id)a1;
- (id)makeCell:(id)a0 forLBSLifeItem:(id)a1;
- (id)descLabelTextWithLBSLifeItem:(id)a0;
- (id)makeCellForCreatePOIItem:(id)a0;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (void)tableView:(id)a0 didSelectRowAtIndexPath:(id)a1;
- (void)scrollViewDidScroll:(id)a0;
- (void)didScrollViewScroll:(id)a0;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)a0;
- (id)cellForSearchViewTable:(id)a0 index:(id)a1;
- (double)heightForSearchViewTable:(id)a0;
- (void)setSearchBar:(id)a0 CancelButtonText:(id)a1;
- (void)wcsSearchBarTextDidEndEditing:(id)a0;
- (void)didSearchViewTableSelect:(id)a0;
- (void)wcsSearchBar:(id)a0 textDidChange:(id)a1;
- (void)wcsSearchBarSearchButtonClicked:(id)a0;
- (void)wcsWillPresentSearch:(id)a0;
- (void)wcsWillDismissSearch:(id)a0;
- (void)setSearchTableResultText:(id)a0;
- (void)autoSearchShouldBeginWithKey:(id)a0 StartFromFirst:(BOOL)a1;
- (void)onPOICreated:(id)a0 poiDistrict:(id)a1 poiStreet:(id)a2 PoiID:(id)a3;
- (void)onGetPOIDisplayName:(id)a0 ForLocation:(id)a1 Scene:(int)a2 SrcDisplayName:(id)a3 extraInfo:(id)a4 Error:(int)a5;
- (void)updateAccuracyAuthorizationTipHidden;
- (void)adjustTableViewFrame;
- (void)showAlertForLocationAuthorization;
- (void)goToSettingLocationAuthorization;
- (void)onLocationAuthorizationStatusUpdatedWithAccuracyAuthorization:(long long)a0;
- (void)applicationDidEnterBackground;
- (void)applicationWillEnterForeground;
- (BOOL)wcsSearchBarShouldBeginEditing:(id)a0;
- (id)navigationBarBackgroundColor;
- (long long)overrideUserInterfaceStyle;
- (void).cxx_destruct;

@end
