@class MemoryMappedKV, WCSession, NSDictionary, NSString, NSDate, NSObject, NSMutableArray;
@protocol OS_dispatch_queue;

@interface WCWatchNativeMgr : MMUserService <WCSessionDelegate, PBMessageObserverDelegate, MMKernelExt, INetworkStatusMgrExt, IContactMgrExt, IMsgExt, IMMNewSessionMgrExt, IChatBoxMgrExt, IExptServiceExt, MMServiceProtocol> {
    BOOL _isRefreshingSessionKey;
    BOOL _needRefreshSessionKey;
    BOOL _didHandledOpenURLSinceEnterForeground;
}

@property (retain, nonatomic) WCSession *session;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *watchSessionQueue;
@property (retain, nonatomic) NSDate *lastReachableDate;
@property (retain, nonatomic) NSMutableArray *pendingSignalMessages;
@property (retain, nonatomic) NSDictionary *latestContact;
@property (retain, nonatomic) NSDictionary *recentContactDic;
@property (retain, nonatomic) NSDate *setupDate;
@property (nonatomic) BOOL requestSessionKeyWaitForAuthOk;
@property (retain, nonatomic) NSString *requestSessionKeyId;
@property (nonatomic) unsigned int watchXLabSwitch;
@property (nonatomic) unsigned int globalXLabSwitch;
@property (retain, nonatomic) NSString *userXLabConfiguration;
@property (retain, nonatomic) MemoryMappedKV *mappedKV;
@property (readonly, nonatomic) BOOL isPairedWatch;
@property (readonly, nonatomic) BOOL reachable;
@property (readonly, nonatomic) BOOL isWatchRunning;
@property (readonly, nonatomic) BOOL isWatchAppInstalled;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)transferUserInfo:(id)a0;
- (id)transferFile:(id)a0 metadata:(id)a1;
- (void)transferCachedImage:(id)a0 forURLString:(id)a1;
- (void)transferCachedImage:(id)a0 forURLString:(id)a1 progress:(float)a2;
- (void)transferInitDataForWatch;
- (void)logStatsWCSessionFile:(id)a0;
- (void)logReportsWCSessionFile:(id)a0;
- (void)statCodePayData:(unsigned int)a0 byFile:(id)a1;
- (void)statActiveData:(unsigned int)a0 systemVersion:(id)a1 byFile:(id)a2;
- (void)statDurationData:(unsigned int)a0 systemVersion:(id)a1 byFile:(id)a2;
- (void)reportActiveData:(unsigned int)a0 byFile:(id)a1;
- (id)init;
- (void)dealloc;
- (void)onServiceInit;
- (void)onServiceEnterBackground;
- (void)onServiceEnterForeground;
- (void)onServiceTerminate;
- (void)onServiceClearData;
- (void)willHandleOpenURL:(id)a0;
- (void)setupSession;
- (void)sendPairedInfoToServer;
- (id)dictionaryFromContact:(id)a0 sessionLastTime:(unsigned int)a1;
- (id)dictionaryFromDBMsg:(id)a0 chatName:(id)a1;
- (id)getRecentContactsInfosForWatch;
- (void)handleUpdateQuickReplies:(id)a0;
- (void)_handleDeviceIdFromWatch:(id)a0;
- (void)enterBackground:(id)a0;
- (BOOL)handleUserActivty:(id)a0 restorationHandler:(id /* block */)a1;
- (void)session:(id)a0 activationDidCompleteWithState:(long long)a1 error:(id)a2;
- (void)sessionWatchStateDidChange:(id)a0;
- (void)sessionReachabilityDidChange:(id)a0;
- (void)session:(id)a0 didReceiveMessage:(id)a1;
- (void)session:(id)a0 didReceiveMessage:(id)a1 replyHandler:(id /* block */)a2;
- (void)session:(id)a0 didReceiveApplicationContext:(id)a1;
- (void)session:(id)a0 didReceiveUserInfo:(id)a1;
- (void)session:(id)a0 didFinishUserInfoTransfer:(id)a1 error:(id)a2;
- (void)session:(id)a0 didFinishFileTransfer:(id)a1 error:(id)a2;
- (void)session:(id)a0 didReceiveFile:(id)a1;
- (void)requestUploadLogWithTimeSpan:(id)a0;
- (void)_handleSessionUserInfo:(id)a0;
- (void)callbackSessionKeyRequest:(BOOL)a0;
- (void)_handleSessionMessage:(id)a0 replyHandler:(id /* block */)a1;
- (void)MessageReturn:(id)a0 Event:(unsigned int)a1;
- (BOOL)isSessionKeyCached;
- (void)checkAndRefreshSessionKeyIfNeed;
- (BOOL)getExtensionKeyForceRefresh:(BOOL)a0;
- (void)handleGetIosExtensionKeyResp:(id)a0 Event:(unsigned int)a1;
- (void)onManulLoginOK;
- (void)onNewRegOK;
- (void)logoutWatch;
- (void)onKickQuit;
- (void)onPreQuit;
- (void)onPostQuit;
- (void)onAuthOK;
- (void)onAuthOKWithPlistVesionChangeFrom:(unsigned int)a0 to:(unsigned int)a1;
- (void)onNetworkStatusChange:(unsigned int)a0;
- (void)OnMsgNotAddDBNotify:(id)a0 MsgWrap:(id)a1;
- (void)OnDelMsg:(id)a0 MsgWrap:(id)a1;
- (void)OnDelMsg:(id)a0 DelAll:(BOOL)a1;
- (void)onDeleteContact:(id)a0;
- (void)OnChangeNotifyStatus:(id)a0 withStatus:(BOOL)a1;
- (void)displaySignalMessageWithDelay:(id)a0;
- (void)displayAllPendingSignalMessages;
- (unsigned int)replyYoTo:(id)a0 observer:(id)a1;
- (id)hookConfDic;
- (void)updateApplicationContextIfCould:(unsigned long long)a0;
- (id)settingDicWithCurCSetting:(id)a0;
- (unsigned int)watchXLabSwitchValue;
- (unsigned int)globalXLabSwitchValue;
- (id)GetUserXLabConfiguration;
- (BOOL)isNotificationActionFromWatch:(id)a0;
- (BOOL)isWatchRecentReachable;
- (void)debugLog:(id)a0;
- (BOOL)isValidContactForWatch:(id)a0;
- (BOOL)dnsHostForWatch;
- (void)checkAndRefreshHostIfNeeded;
- (void)onSessionTopStatusChanged:(id)a0 bTop:(BOOL)a1;
- (void)onSessionChatBoxTypeChange:(id)a0 inChatBox:(BOOL)a1;
- (void)onExptItemListChange;
- (void)mockRequestNewSession;
- (void).cxx_destruct;

@end
