@class NSString, NSRecursiveLock, WePkgCleanMgr, NSMutableDictionary, WePkgOperateUpdateMgr, MMLockMutableDictionary, WePkgDownloadMgr, NSMutableSet, WePkgCheckUpdateMgr, NSMapTable, WePkgConfigMgr;

@interface WePkgFacade : MMUserService <IWePkgCheckUpdateMgrExt, IWePkgDownloadMgrExt, MMServiceProtocol> {
    NSRecursiveLock *_createPackageLock;
    id _clearWePkgAllDataNotificationToken;
    id _receiveMemoryWarningNotificationToken;
}

@property (retain, nonatomic) MMLockMutableDictionary *dicPkgId2Package;
@property (retain, nonatomic) NSMapTable *dicUrl2UsingWebview;
@property (retain) NSMutableDictionary *dicOriginalUrl2A8KeyData;
@property (retain) NSMutableDictionary *dicOriginalUrl2NeedReloadWebVC;
@property (retain, nonatomic) NSMutableDictionary *reportSyncReloadOBjs;
@property (retain, nonatomic) NSMutableSet *webViewDidCommitSet;
@property (retain, nonatomic) NSMutableDictionary *webViewEvaluateJsDic;
@property (retain, nonatomic) WePkgConfigMgr *configMgr;
@property (retain, nonatomic) WePkgCheckUpdateMgr *checkMgr;
@property (retain, nonatomic) WePkgDownloadMgr *downloadMgr;
@property (retain, nonatomic) WePkgOperateUpdateMgr *operateMgr;
@property (retain, nonatomic) WePkgCleanMgr *cleanMgr;
@property (retain, nonatomic) NSString *jsCommonLibPkgId;
@property (retain, nonatomic) NSString *injectJsScript;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)dealloc;
- (void)onServiceInit;
- (void)onServiceClearData;
- (void)onServiceEnterForeground;
- (void)onServiceEnterBackground;
- (void)checkUpdateForJsCommonLib;
- (id)dataFromCachedItem:(id)a0 resourceUrl:(id)a1;
- (BOOL)needInjectJsRunTimeStatistics:(id)a0;
- (id)fileNameFromRid:(id)a0;
- (id)getCachedJsScript:(id)a0;
- (id)getCacheDataForResouceUrl:(id)a0 mainDocUrl:(id)a1;
- (id)getJscorePublicLib;
- (void)reportResourceHookResult:(id)a0 Version:(id)a1 ResourceUrl:(id)a2 Hook:(BOOL)a3;
- (id)getCacheDataForResouceUrlInternal:(id)a0 mainDocUrl:(id)a1 PkgId:(id *)a2 Version:(id *)a3;
- (void)updateUsingCommlibWebView:(id)a0;
- (BOOL)isCommonLibNeedForceUpdate;
- (void)setupMgr;
- (BOOL)isWePkgAllEntryEnabled;
- (void)observerWebViewNotification;
- (void)observerMemoryWarning;
- (id)loadPackage:(id)a0 createIfNeed:(BOOL)a1;
- (id)getNeedDownloadFileListOnCurrentNetwork:(id)a0;
- (id)getNeedDownloadSingleFileListOnCurrentNetwork:(id)a0 PkgId:(id)a1 Version:(id)a2 IsAtomicPart:(BOOL)a3;
- (void)tryOperateUpdateForPkgId:(id)a0 AtomicPart:(BOOL)a1 NonAtomicPart:(BOOL)a2;
- (void)downloadTmpConfigInDB;
- (unsigned int)getLastDownloadTmpConfigInDBTime;
- (void)setLastDownloadTmpConfigInDBTime:(unsigned int)a0;
- (BOOL)updateWePkgUsingWebview:(id)a0 WebView:(id)a1;
- (BOOL)updateWePkg:(id)a0 UsingWebview:(id)a1;
- (BOOL)tryLoadPkgForJsCommonLibWithPkg:(id)a0;
- (BOOL)loadPkgForJsCommonLib;
- (int)tryLoadPkgForUrl:(id)a0 Version:(id *)a1;
- (int)tryLoadPkgForUrl:(id)a0 preloadMain:(BOOL)a1;
- (int)tryLoadPkgForUrl:(id)a0 Version:(id *)a1 preloadMain:(BOOL)a2;
- (int)loadPkgForPkgId:(id)a0 Domain:(id)a1 Package:(id *)a2 Version:(id *)a3;
- (void)cleanWepkg:(id)a0;
- (BOOL)isPkgNeedForceUpdate:(id)a0;
- (void)traceEventForWepkgEnterWebWithPkgId:(id)a0 Url:(id)a1 Version:(id)a2 Result:(int)a3;
- (void)checkUpdateIfNeed:(id)a0;
- (void)checkUpdate:(id)a0 CheckInterval:(unsigned int)a1;
- (void)checkUpdateForExistPkgs:(id)a0 andForcePkgs:(id)a1;
- (BOOL)checkUpdateFrequenceIsOK:(id)a0 CheckInterval:(unsigned int)a1;
- (void)releaseDataForUrl:(id)a0 alsoReleasePreload:(BOOL)a1;
- (BOOL)existPkgForUrl:(id)a0;
- (void)notifyWebViewDidExit:(id)a0;
- (void)notifyWebViewDidCommit:(id)a0;
- (void)handleOperateEndForPkgId:(id)a0;
- (void)clearWkWebviewCache;
- (void)checkUpdateMgr:(id)a0 didSuccessForPkgId:(id)a1;
- (void)downloadMgr:(id)a0 didSuccessForDownloadInfo:(id)a1;
- (void)downloadMgr:(id)a0 didSuccessForDownloadInfoAtomicPart:(id)a1;
- (void)downloadMgr:(id)a0 didSuccessForDownloadInfoNonAtomicPart:(id)a1;
- (void)downloadMgr:(id)a0 didFailForDownloadInfo:(id)a1 errCode:(int)a2 NoAutoRetry:(BOOL)a3;
- (void)downloadMgr:(id)a0 didFailForDownloadInfoAtomicPart:(id)a1 NoAutoRetry:(BOOL)a2;
- (void)downloadMgr:(id)a0 didFailForDownloadInfoNonAtomicPart:(id)a1 NoAutoRetry:(BOOL)a2;
- (void)refreshWebViewWhenSyncReload:(id)a0 errCode:(int)a1;
- (BOOL)wePkgGlobalConfigDisabled;
- (void)reloadCurrentWebviewWaitWePkg:(id)a0 serverVersion:(id)a1 blockWait:(BOOL)a2;
- (void)reloadCurrentWebviewWithoutWePkg:(id)a0 serverVersion:(id)a1;
- (void)reloadCurrentWebviewWaitWePkg:(id)a0 serverVersion:(id)a1;
- (void)clearPageCacheState:(id)a0;
- (void)startReloadWebviews:(id)a0 withPackage:(id)a1;
- (void)startReloadWithOnlineModeAfterDownloadFailed:(id)a0 errorCode:(int)a1;
- (void)reloadCurrentWebview:(id)a0 WithoutWePkg:(id)a1;
- (void)notifyGetA8KeyReturn:(id)a0 OriginalUrl:(id)a1 FullUrl:(id)a2 ExtraInfo:(id)a3;
- (void)synchronizeCookies:(id)a0 originUrl:(id)a1 fullUrl:(id)a2 cookiesInfo:(id)a3;
- (void)handleGetA8KeyReturn:(id)a0 OriginalUrl:(id)a1 FullUrl:(id)a2;
- (void)tryStopLoadingViewAndReloadA8KeyFullUrl:(id)a0 OriginalUrl:(id)a1 ReloadUrl:(id)a2;
- (void)reloadWithoutCommonLibForWebView:(id)a0;
- (void)reportSyncReloadBegin:(id)a0 url:(id)a1 pkg:(id)a2 version:(id)a3;
- (void)reportSyncReloadEnd:(id)a0 result:(int)a1;
- (id)getWebViewKey:(id)a0;
- (BOOL)isGamePkgZipFile:(id)a0;
- (id)contentNameFromFileName:(id)a0 targetSuffix:(id)a1;
- (id)pkgNameFromPkgFile:(id)a0;
- (BOOL)isGamePkgPartFile:(id)a0;
- (BOOL)isGamePkgFileName:(id)a0;
- (void)applyFileToDebugPath:(id)a0 title:(id)a1;
- (void)showSuccessToastForPkgId:(id)a0 rid:(id)a1;
- (void)showMsg:(id)a0;
- (id)moveUnzipDirToDebugPath:(id)a0 pkgName:(id)a1;
- (BOOL)unzipFromPath:(id)a0 targetPath:(id)a1;
- (BOOL)isGameHarFile:(id)a0;
- (id)gameCustomizeActionTitleArray:(id)a0;
- (void)handleGameCustomActionWithPath:(id)a0 title:(id)a1 actionTitle:(id)a2;
- (void)airGameWkRecordDir;
- (id)getGamePreInjectJsForRidName:(id)a0;
- (BOOL)appendScript:(id)a0 preInjectJsRidName:(id)a1 enableExpt:(id)a2 enableDebugName:(id)a3;
- (void).cxx_destruct;

@end
