@class EAGLContext, MMGPUSpatiotemporalDenosing, NSMutableArray, WeVisGLYUV2RGBA, WeVisGLRGBA2YUVTwoPassFS, WeVisByPassFS, NSString, WCLoopMetricsCollector, WeVisGLTexture, WeVisGLFrameBuffer, NSRecursiveLock, SpatiotemporalDenosingPreProcess, WeVisPixelBuffer, MMGPUClarityFilter, MMGPUClarityPreProcess, NSArray;
@protocol WeVisVoipEffectDelegate;

@interface WeVisVoipEffectMgr : NSObject {
    int _rotation;
    struct unique_ptr<WeEffect::X3DEffect, std::default_delete<WeEffect::X3DEffect>> { struct __compressed_pair<WeEffect::X3DEffect *, std::default_delete<WeEffect::X3DEffect>> { struct X3DEffect *__value_; } __ptr_; } _spWeEffect;
    unsigned int _trackFaceRotation;
    BOOL _remoteIsNotPhone;
    BOOL _needMirror;
    BOOL _enableSTFilter;
    BOOL _enableSkipBeauty;
    BOOL _enableClarity;
    int _clarityMode;
    BOOL _useMultiTemporalFilter;
    BOOL _enableRciEffect;
    long long lutFilterId;
    long long lutRosyLutId;
    long long sharpenFilterId;
    long long teethBrightId;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct __compressed_pair<std::basic_string<char>::__rep, std::allocator<char>> { struct __rep { union { struct __short { char __data_[23]; unsigned char __padding_[0]; unsigned char __size_ : 7; unsigned char __is_long_ : 1; } __s; struct __long { char *__data_; unsigned long long __size_; unsigned long __cap_ : 63; unsigned char __is_long_ : 1; } __l; struct __raw { unsigned long long __words[3]; } __r; } ; } __value_; } __r_; } filterStrPath;
    long long filterID;
    WeVisPixelBuffer *sdkSrcPixelBuffer;
    WeVisGLTexture *texSdkSrcRGBA;
    WeVisGLTexture *texSdkDstRGBA;
    WeVisGLTexture *texSrcY;
    WeVisGLTexture *texSrcUV;
    WeVisGLTexture *texSrcRGBA;
    WeVisGLTexture *texDstY;
    WeVisGLTexture *texDstUV;
    WeVisGLFrameBuffer *fboSdkSrcRGBA;
    WeVisGLFrameBuffer *fboDstY;
    WeVisGLFrameBuffer *fboDstUV;
    WeVisGLFrameBuffer *fboSrcRGBA;
    int widthSrcY;
    int heightSrcY;
    int widthSrcUV;
    int heightSrcUV;
    int widthScaled;
    int heightScaled;
    int widthSdk;
    int heightSdk;
    int widthDstY;
    int heightDstY;
    int widthDstUV;
    int heightDstUV;
    int requiredWidthDstY;
    int requiredHeightDstY;
    WeVisGLYUV2RGBA *yuv2rgba;
    WeVisGLRGBA2YUVTwoPassFS *rgba2yuvTwoPass;
    WeVisByPassFS *scalePass;
    MMGPUSpatiotemporalDenosing *stDenosingFilter;
    SpatiotemporalDenosingPreProcess *denosingPreProcess;
    MMGPUClarityFilter *clarityFilter;
    MMGPUClarityPreProcess *clarityPreProcess;
    WeVisPixelBuffer *dstPixelBuffer;
    struct vector<unsigned char, std::allocator<unsigned char>> { char *__begin_; char *__end_; struct __compressed_pair<unsigned char *, std::allocator<unsigned char>> { char *__value_; } __end_cap_; } sdkSrcRGBData;
    struct __CVOpenGLESTextureCache { } *cvTextureCache;
    BOOL enableTranspose;
    BOOL usingBackCamera;
    int oldRotation;
    int oldInputWidth;
    int oldInputHeight;
    int oldOutputWidth;
    int oldOutputHeight;
    struct vector<unsigned char, std::allocator<unsigned char>> { char *__begin_; char *__end_; struct __compressed_pair<unsigned char *, std::allocator<unsigned char>> { char *__value_; } __end_cap_; } faceTrackInputRGB;
    struct __CVPixelBufferPool { } *mOutPool;
    long long sceneType;
    float blurRate;
    float eyePouchRate;
    float smileFoldsRate;
    float teethBrightRate;
    float contourRate;
    long long faceAutoSlimerId;
    long long girlFaceAutoSlimerId;
    long long boyFaceAutoSlimerId;
    long long smallHeadId;
    long long cheekboneId;
    long long lowerJawboneId;
    long long wingOfNoseId;
    long long shortChinId;
    long long longChinId;
    long long lowHairLineId;
    long long highHairLineId;
    long long eyeBiggerV2Id;
    long long zhaiLianId;
    long long contourId;
    struct __CVBuffer { } *texY;
    struct __CVBuffer { } *texUV;
    struct WeVisDataReport22049 { BOOL mIsInited; struct vector<WeVisDataReport22049Field, std::allocator<WeVisDataReport22049Field>> { struct WeVisDataReport22049Field *__begin_; struct WeVisDataReport22049Field *__end_; struct __compressed_pair<WeVisDataReport22049Field *, std::allocator<WeVisDataReport22049Field>> { struct WeVisDataReport22049Field *__value_; } __end_cap_; } mFieldVect; struct unordered_map<std::string, unsigned long, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<const std::string, unsigned long>>> { struct __hash_table<std::__hash_value_type<std::string, unsigned long>, std::__unordered_map_hasher<std::string, std::__hash_value_type<std::string, unsigned long>, std::hash<std::string>, std::equal_to<std::string>>, std::__unordered_map_equal<std::string, std::__hash_value_type<std::string, unsigned long>, std::equal_to<std::string>, std::hash<std::string>>, std::allocator<std::__hash_value_type<std::string, unsigned long>>> { struct unique_ptr<std::__hash_node_base<std::__hash_node<std::__hash_value_type<std::string, unsigned long>, void *> *> *[], std::__bucket_list_deallocator<std::allocator<std::__hash_node_base<std::__hash_node<std::__hash_value_type<std::string, unsigned long>, void *> *> *>>> { struct __compressed_pair<std::__hash_node_base<std::__hash_node<std::__hash_value_type<std::string, unsigned long>, void *> *> **, std::__bucket_list_deallocator<std::allocator<std::__hash_node_base<std::__hash_node<std::__hash_value_type<std::string, unsigned long>, void *> *> *>>> { void **__value_; struct __bucket_list_deallocator<std::allocator<std::__hash_node_base<std::__hash_node<std::__hash_value_type<std::string, unsigned long>, void *> *> *>> { struct __compressed_pair<unsigned long, std::allocator<std::__hash_node_base<std::__hash_node<std::__hash_value_type<std::string, unsigned long>, void *> *> *>> { unsigned long long __value_; } __data_; } __value_; } __ptr_; } __bucket_list_; struct __compressed_pair<std::__hash_node_base<std::__hash_node<std::__hash_value_type<std::string, unsigned long>, void *> *>, std::allocator<std::__hash_node<std::__hash_value_type<std::string, unsigned long>, void *>>> { struct __hash_node_base<std::__hash_node<std::__hash_value_type<std::string, unsigned long>, void *> *> { void *__next_; } __value_; } __p1_; struct __compressed_pair<unsigned long, std::__unordered_map_hasher<std::string, std::__hash_value_type<std::string, unsigned long>, std::hash<std::string>, std::equal_to<std::string>>> { unsigned long long __value_; } __p2_; struct __compressed_pair<float, std::__unordered_map_equal<std::string, std::__hash_value_type<std::string, unsigned long>, std::equal_to<std::string>, std::hash<std::string>>> { float __value_; } __p3_; } __table_; } mfind; } dataReport22049;
    NSArray *_modelKeyArray;
    struct mutex { struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } __m_; } mCacheMutex;
    struct priority_queue<cacheElement, std::vector<cacheElement>, cacheCmp> { struct vector<cacheElement, std::allocator<cacheElement>> { struct cacheElement *__begin_; struct cacheElement *__end_; struct __compressed_pair<cacheElement *, std::allocator<cacheElement>> { struct cacheElement *__value_; } __end_cap_; } c; struct cacheCmp { } comp; } mRenderTargetCache;
    int mLastFrameId;
    int mFrameCount;
    int mLastWidth;
    int mLastHeight;
    unsigned int mLastRenderTarget;
    BOOL isSTFilterBuildinPipeline;
    BOOL isUseSpatilFilterForPipeline;
    BOOL isSizeChanged;
    unsigned long long _deviceType;
    BOOL _isAllowFp16;
}

@property (retain, nonatomic) NSMutableArray *face2DStickers;
@property (retain, nonatomic) NSMutableArray *face3DStickers;
@property (retain, nonatomic) NSMutableArray *eyeBrows;
@property (retain, nonatomic) NSMutableArray *eyeShadows;
@property (retain, nonatomic) NSMutableArray *lipSticker;
@property (retain, nonatomic) NSMutableArray *faceContours;
@property (retain, nonatomic) NSMutableArray *blusher;
@property (retain, nonatomic) NSMutableArray *segments;
@property (retain, nonatomic) NSMutableArray *frontStickers;
@property (retain, nonatomic) NSMutableArray *effectMaterials;
@property (retain, nonatomic) NSMutableArray *pendingOpBlocks;
@property (retain, nonatomic) EAGLContext *glContext;
@property (retain, nonatomic) NSRecursiveLock *lock;
@property (nonatomic) long long trackConfig;
@property (nonatomic) long long actionConfig;
@property (retain, nonatomic) WCLoopMetricsCollector *liveCaptureMetricsCollector;
@property (copy, nonatomic) NSString *dataUniqueID;
@property (weak, nonatomic) id<WeVisVoipEffectDelegate> resultDelegate;
@property (copy, nonatomic) id /* block */ dataReportCallback;
@property (nonatomic) BOOL isBackground;
@property (nonatomic) BOOL shouldUseIPadRotationWhenProcessingVideoSampleBuffer;

- (void)setEffect:(id)a0;
- (id)init;
- (id)initWithGlContext:(id)a0 sceneType:(long long)a1;
- (id)initWithGlContext:(id)a0 sceneType:(long long)a1 modelKeyArray:(id)a2;
- (id)initWithGlContext:(id)a0 sceneType:(long long)a1 modelKeyArray:(id)a2 runDeviceType:(unsigned long long)a3 isAllowFp16:(BOOL)a4 isClientRciEnabled:(BOOL)a5;
- (id)initWithGlContext:(id)a0 sceneType:(long long)a1 modelKeyArray:(id)a2 SDKMode:(int)a3;
- (id)initWithGlContext:(id)a0 sceneType:(long long)a1 modelKeyArray:(id)a2 SDKMode:(int)a3 runDeviceType:(unsigned long long)a4 isAllowFp16:(BOOL)a5 isClientRciEnabled:(BOOL)a6;
- (void)dealloc;
- (void)enableTranspose:(BOOL)a0;
- (void)setRotation:(int)a0;
- (void)setUsingBackCamera:(BOOL)a0;
- (void)setRemoteIsNotPhone:(BOOL)a0;
- (void)setRotationForTrackFace:(int)a0;
- (BOOL)needFaceTrack;
- (long long)faceConfig;
- (BOOL)enableFaceOccuSeg;
- (void)performPendingOpBlocks;
- (void)loadingSettings;
- (void)flushDataReport:(id)a0;
- (BOOL)needWeEffectInstance:(int)a0 device:(unsigned long long)a1;
- (float)limitValue:(float)a0 ToMin:(float)a1 ToMax:(float)a2;
- (void)setBackgroundEffectRate:(float)a0 segmentMode:(int)a1;
- (void)setLutFilter:(float)a0;
- (void)setRosy:(float)a0;
- (unsigned int)getAppScenario;
- (void)setSkinSmooth:(float)a0;
- (void)setSkinBright:(float)a0;
- (void)setEyeBigger:(float)a0;
- (void)setEyeBright:(float)a0;
- (void)setFaceThin:(float)a0;
- (void)setFaceAutoSlimer:(float)a0;
- (void)setGirlFaceAutoSlimerTemplate;
- (void)setGirlFaceAutoSlimer:(float)a0;
- (void)setBoyFaceAutoSlimerTemplate;
- (void)setBoyFaceAutoSlimer:(float)a0;
- (void)setBrowEnhance:(float)a0;
- (void)setRemoveEyePouch:(float)a0 smileFolds:(float)a1;
- (void)setSharpenFilter:(float)a0;
- (void)setTeethBright:(float)a0;
- (void)setSmallHeadTemplate;
- (void)setSmallHead:(float)a0;
- (void)setCheekboneTemplate;
- (void)setCheekbone:(float)a0;
- (void)setLowerJawboneTemplate;
- (void)setLowerJawbone:(float)a0;
- (void)setWingOfNoseTemplate;
- (void)setWingOfNose:(float)a0;
- (void)setShortChinTemplate;
- (void)setLongChinTemplate;
- (void)setShortLongChin:(float)a0;
- (void)setLowHairLineTemplate;
- (void)setHighHairLineTemplate;
- (void)setLowHighHairLine:(float)a0;
- (void)setMouthMorph:(float)a0;
- (void)setEyeBiggerV2Template;
- (void)setEyeBiggerV2:(float)a0;
- (void)setZhaiLianTemplate;
- (void)setZhaiLian:(float)a0;
- (void)applyFilter:(id)a0 alpha:(double)a1;
- (void)applyFilterWithConfig:(id)a0 alpha:(double)a1;
- (void)SetNaturalFilter:(float)a0;
- (void)apply2DSticker:(id)a0;
- (void)applyEffectMaterial:(id)a0;
- (void)removeEffectMaterial:(long long)a0;
- (void)applyBackSticker:(id)a0;
- (void)applyFrontSticker:(id)a0;
- (void)applyEyeBrow:(id)a0;
- (void)applyEyeShadow:(id)a0;
- (void)applyLipStick:(id)a0;
- (void)applyContours:(id)a0;
- (void)applyBlusher:(id)a0;
- (void)applyContour;
- (void)setContourRate:(float)a0;
- (void)applyEffectMaterialsFolder:(id)a0;
- (void)setMakeupGlobalAlpha:(float)a0;
- (void)clearEffectMaterialsFolder;
- (void)updateActionsForAssetPath:(id)a0;
- (void)updateActionConfig:(id)a0;
- (void)requireVideoOutputWidth:(int)a0 outputHeight:(int)a1;
- (BOOL)updateOutCVPixelbufferFromPool;
- (void)updateVideoInputWidth:(int)a0 inputHeight:(int)a1 outputWidth:(int)a2 outputHeight:(int)a3;
- (void)genVideoInputSources:(int)a0 inputHeight:(int)a1 outputWidth:(int)a2 outputHeight:(int)a3;
- (void)genYUVSourceWithWidth:(int)a0 Height:(int)a1;
- (BOOL)callFaceTrackForPixelBuffer:(struct __CVBuffer { } *)a0;
- (BOOL)getSrcTexYUVFromPixelBuffer:(struct __CVBuffer { } *)a0;
- (id)processVideoSampleBuffer:(struct opaqueCMSampleBuffer { } *)a0 outputTexture:(int *)a1 pixelBufferFlipX:(BOOL)a2 shouldIgnoreBackground:(BOOL)a3;
- (id)processVideoSampleBuffer:(struct opaqueCMSampleBuffer { } *)a0 outputTexture:(int *)a1 shouldIgnoreBackground:(BOOL)a2;
- (id)processVideoSampleBuffer:(struct opaqueCMSampleBuffer { } *)a0 shouldIgnoreBackground:(BOOL)a1;
- (unsigned int)getIPadRotation;
- (id)processVideoSampleBuffer:(struct opaqueCMSampleBuffer { } *)a0 pixelBufferFlipX:(BOOL)a1 shouldIgnoreBackground:(BOOL)a2;
- (id)processVideoSampleBufferWithPipeLine:(struct opaqueCMSampleBuffer { } *)a0 pixelBufferFlipX:(BOOL)a1 shouldIgnoreBackground:(BOOL)a2;
- (void)collectPerformanceData;
- (void)notifyEventsIfNeeded;
- (void)clean;
- (void)clearAllEffects;
- (void)clearStickers;
- (void)clearMakeUp;
- (void)clearFilters;
- (void)enableSTDenoiseFilter:(BOOL)a0 useSpatioFilter:(BOOL)a1 useMultiTemporalFilter:(BOOL)a2;
- (void)enableClarityFilter:(BOOL)a0 withMode:(int)a1;
- (void)enableSkipBeauty:(BOOL)a0;
- (void)waitForPipeLineEnd;
- (id)getFaceRect;
- (void)registerBackgroundNotification;
- (void)appWillResignActive:(id)a0;
- (void)appDidBecomeActive:(id)a0;
- (void)setSceneType:(long long)a0;
- (void).cxx_destruct;
- (id).cxx_construct;

@end
