@class NSString, NSMutableArray;
@protocol BizTlPersonalCenterMgrRegisterExt;

@interface BizTlPersonalCenterMgr : MMUserService <WCPayLogicMgrExt, MMServiceProtocol>

@property (retain, nonatomic) NSMutableArray *groupCellList;
@property (nonatomic) int sessionId;
@property (nonatomic) unsigned int chatNotifyReddotCleanTime;
@property (nonatomic) BOOL interactiveIdentityEnable;
@property (nonatomic) BOOL meTabEntranceEnable;
@property (nonatomic) BOOL meTabEntranceWithoutAcctEnable;
@property (copy, nonatomic) NSString *personalCenterBiz;
@property (nonatomic) BOOL usingBizAsInteractiveIdentity;
@property (copy, nonatomic) NSString *bizUsername;
@property (copy, nonatomic) NSString *bizNickname;
@property (copy, nonatomic) NSString *bizHeadImgUrl;
@property (nonatomic) BOOL initFlag;
@property (nonatomic) unsigned int banType;
@property (nonatomic) unsigned int fansNum;
@property (copy, nonatomic) NSString *banUrl;
@property (nonatomic) unsigned int verifyFlag;
@property (nonatomic) unsigned int notifyUpdateTimestamp;
@property (nonatomic) long long notifyCount;
@property (nonatomic) BOOL shouldShowNotifyReddotOnChat;
@property (weak, nonatomic) id<BizTlPersonalCenterMgrRegisterExt> registerExt;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)onServiceInit;
- (void)onServiceEnterForeground;
- (void)onServiceClearData;
- (void)updateSessionId;
- (void)resetSessionId;
- (id)getPersonalCenterTabInfo;
- (void)selectGroupIndex:(long long)a0 cellIndex:(long long)a1 viewController:(id)a2;
- (void)jumpToMyBizList:(id)a0;
- (void)jumpToRecentReading;
- (void)jumpToNotify;
- (void)jumpToSetting;
- (void)jumpToWeb:(id)a0;
- (void)jumpToWxa:(id)a0;
- (id)convertToPersonalCenterTabInfo;
- (BOOL)triggerRedline:(id)a0;
- (id)getNewDynamicList;
- (void)filterDataSource:(id)a0;
- (BOOL)checkCellInfoAvaliable:(id)a0;
- (void)report27213:(unsigned int)a0 scene:(unsigned int)a1;
- (void)report27213:(unsigned int)a0 scene:(unsigned int)a1 redPointNum:(unsigned int)a2 biz:(id)a3 hasSmallPoint:(BOOL)a4;
- (id)getExtraParamInfoWithInfoList:(id)a0 picFromScene:(long long)a1 appId:(id)a2 wxaData:(id)a3;
- (id)processImageIfNeeded:(id)a0;
- (id)getImageItemInfoForItem:(id)a0 appId:(id)a1;
- (id)getImageItemLivePhotoExtraInfoForItem:(id)a0 appId:(id)a1;
- (void)selectPhotoAndJumpToPluginAppJumpInfo:(id)a0 viewController:(id)a1 limit:(long long)a2;
- (void)openPersonalCenterMiniAppPageJumpInfo:(id)a0 handlerWrapper:(id)a1;
- (void)onPersonalCenterLogin:(id)a0;
- (void)updateBizIdentityInfo;
- (id)covertBizSelectImgInfoToPersonalCenterPhotoInfo:(id)a0;
- (void)onPersonalCenterLogout:(id)a0;
- (void)getWeAppContactWithAppid:(id)a0;
- (id)getPersonalCenterBiz;
- (void)getRemotePersonalCenterBiz:(id /* block */)a0;
- (void)updatePersonalCenterReddotInfo:(id)a0;
- (BOOL)canShowBizCreatorCenter;
- (long long)getPersonalCenterNotifyCount;
- (unsigned int)getPersonalCenterReddotUpdateTimestamp;
- (void)cleanChatNotifyReddot;
- (void)writeDraftData:(long long)a0 draftData:(id)a1 sceneMd5:(id)a2;
- (void)readDraftData:(long long)a0 sceneMd5:(id)a1 completion:(id /* block */)a2;
- (void)clearDraftData:(long long)a0 sceneMd5:(id)a1;
- (BOOL)draftExist:(long long)a0;
- (BOOL)draftExist:(long long)a0 sceneMd5:(id)a1;
- (BOOL)checkUseDraft:(long long)a0 sceneMd5:(id)a1;
- (id)pathOfDraft:(long long)a0 sceneMd5:(id)a1;
- (BOOL)isBizValid;
- (void)checkHasFinishRegisterAndLogin:(id)a0;
- (void)handleResp:(id)a0;
- (void)clearRegisterExtState;
- (void)openPublishImage:(id)a0 taskInfo:(id)a1 useDraft:(BOOL)a2 viewController:(id)a3 handlerWrapper:(id)a4;
- (void)openPersonalCenterMiniAppPage:(id)a0 taskInfo:(id)a1 handlerWrapper:(id)a2;
- (id)getImageRealPathFromDic:(id)a0;
- (void)OnGetBindQueryInfo:(id)a0 Error:(id)a1;
- (void)openRegister;
- (BOOL)shouldShowEntryAtMineTab;
- (void)refreshMeTabStrategy;
- (void)queryCtrlInfoAndFetchMeTabRedPoint;
- (void)onReceiveMeTabRedPointInfo:(struct optional<NSData *> { union { char x0; id x1; } x0; BOOL x1; })a0;
- (void)disposeMeTabRedPoint:(id)a0 scene:(unsigned long long)a1;
- (void).cxx_destruct;

@end
