@class BTLTopBarReportItem, NSMutableDictionary, BTLNotifyBarReportItem, BrandTLExptConfig, NSMutableSet, NSMutableArray, KvReportItem29480, BrandReportMainSessionInfo;
@protocol BrandTimelineReportLogicDelegate;

@interface BrandTimelineReportLogic : MMObject <PBMessageObserverDelegate> {
    unsigned int m_stayTimeStart;
    unsigned int m_listStayTimeStart;
    unsigned int m_listStayTime;
    NSMutableDictionary *m_dicExposeInfo;
    NSMutableDictionary *m_dicRealTimeInfo;
    unsigned int m_enterPos;
    unsigned int m_exitPos;
    unsigned long long m_source;
    NSMutableDictionary *m_dicOftenReadAndLiveBarExposeItem;
    NSMutableDictionary *m_dicOftenReadAndLiveBarClickItem;
    BTLTopBarReportItem *m_channelExposingItem;
    NSMutableArray *m_arrChannelExposedItem;
    NSMutableArray *m_arrChannelClickItem;
    BTLNotifyBarReportItem *m_notifyBarReportItem;
}

@property (retain, nonatomic) BrandReportMainSessionInfo *sessionInfo;
@property (nonatomic) BOOL pushInCache;
@property (retain, nonatomic) NSMutableDictionary *dicLiveMsgExposedItem;
@property (retain, nonatomic) NSMutableSet *setLiveClickMsgId;
@property (nonatomic) int exptType;
@property (nonatomic) long long exposedMsgMaxIndex;
@property (nonatomic) long long exposedMsgMinIndex;
@property (nonatomic) unsigned int msgCntReceiveInBox;
@property (nonatomic) unsigned int sepLineType;
@property (nonatomic) unsigned int sepLineFirstExposeIndex;
@property (nonatomic) BOOL didClickRecoFlowUnfold;
@property (nonatomic) unsigned int navNewMsgClickCnt;
@property (nonatomic) unsigned int msgExpandMoreCnt;
@property (retain, nonatomic) KvReportItem29480 *personalCenterEntranceExposedItem;
@property (retain, nonatomic) BrandTLExptConfig *exptConfig;
@property (weak, nonatomic) id<BrandTimelineReportLogicDelegate> delegate;
@property (nonatomic) BOOL jump2OldBizList;

+ (unsigned int)sessionId;
+ (void)__setSessionId:(unsigned int)a0;
+ (unsigned long long)enterTimestampMs;
+ (void)__setEnterTimestampMs:(unsigned long long)a0;
+ (unsigned long long)exposedSessionId;
+ (void)__setExposedSessionId:(unsigned long long)a0;
+ (void)reportEnterTimelineTimeCostIdKey:(unsigned int)a0;
+ (void)reportDeleteTooOldTLMsgIdKey;
+ (unsigned int)msgTypeForMsgWrap:(id)a0;
+ (id)generateReddotReportItem:(id)a0;
+ (id)getReddotReportInfoWithNotifyCount:(long long)a0 isMassSend:(BOOL)a1 isNotification:(BOOL)a2 toBNotifyCount:(long long)a3;
+ (void)reportRecCardIdKeyEvent:(unsigned long long)a0;
+ (void)reportRecCardReceiveXMLPush:(id)a0;
+ (void)reportRecCardOptype:(unsigned int)a0 bizUsrName:(id)a1 recId:(unsigned long long)a2 mid:(unsigned int)a3 idx:(unsigned int)a4 feedBackReasonArr:(id)a5;
+ (void)reportRecCardOptype:(unsigned int)a0 sectionData:(id)a1 viewModel:(id)a2 extInfo:(id)a3;
+ (void)reportRecCardInsertActionRet:(unsigned int)a0 recCardWrapper:(id)a1;
+ (void)report15721RecommendFinderCellOptype:(unsigned int)a0 sectionData:(id)a1 index:(long long)a2;
+ (unsigned int)genChannelExposeSeqId;
+ (void)reportRecFlowCardOptype:(unsigned int)a0 recoFlowSectionData:(id)a1 cellView:(id)a2 extInfo:(id)a3;
+ (void)reportRecoFlowExpandMoreCellActionType:(unsigned int)a0 position:(unsigned int)a1;
+ (void)reportRecoFlowHeaderCellRefreshActionType:(unsigned int)a0 position:(unsigned int)a1;
+ (void)report27268FinderCardRecycledWithRecCardWrapperArr:(id)a0;
+ (void)reportGeneralException:(long long)a0 data:(id)a1;

- (id)init;
- (void)dealloc;
- (void)onEnterTL:(unsigned long long)a0 sessionInfo:(id)a1 pushInCache:(BOOL)a2;
- (void)onExitTL;
- (void)onTLDidAppear;
- (void)reportEnterTLLog11404:(id)a0;
- (int)getCurExptType;
- (void)report28651ExptOnEnter;
- (void)updateExposeMinIndexOnAppear;
- (void)report28651ExptOnExit;
- (void)fill28651ReportItemCommField:(id)a0;
- (void)onAddMsgInTL;
- (void)onExpandMsg;
- (void)onClickNavMsgBtn;
- (void)onUnfoldRecoFlow;
- (void)onMsgSectionExposeForIndex:(long long)a0;
- (BOOL)hasSeqLineExposed;
- (void)onSeqLineTypeExpose:(unsigned int)a0 firstExposeIndex:(unsigned int)a1;
- (void)reportOptype:(unsigned int)a0 sectionData:(id)a1;
- (void)reportOptype:(unsigned int)a0 sectionData:(id)a1 msgIdx:(unsigned int)a2;
- (void)reportOptype:(unsigned int)a0 readerSectionData:(id)a1 msgIdx:(unsigned int)a2;
- (void)reportOptype:(unsigned int)a0 notifySectionData:(id)a1 msgIdx:(unsigned int)a2;
- (void)startRecordTimelineStayTime;
- (void)pauseRecordTimelineStayTime;
- (void)resumeRecordTimelineStayTime;
- (void)abortRecordTimelineStayTime;
- (void)endRecordTimelineStayTime;
- (void)reportEnterPosWithVisibleItemVewModelArr:(id)a0 newMsgSequenceId:(unsigned long long)a1;
- (void)reportExitPosWithVisibleItemVewModelArr:(id)a0;
- (id)getExposeInfoCache;
- (id)converInfoToReportInfo:(id)a0;
- (void)sendListExposeRealTimeInfoReportReqForClickWithKey:(id)a0;
- (void)sendListExposeRealTimeInfoReportReq:(BOOL)a0;
- (void)clearRealTimeReportCache;
- (id)generateReddotReportItem;
- (void)sendListExposeInfoReportReq;
- (void)recordOftenReadAndLiveBarBrandLiveExposed;
- (void)sendOftenReadReportReq;
- (void)reportExposeItemArr:(id)a0 newMsgSequenceId:(unsigned long long)a1;
- (void)reportExposeItem:(id)a0 newMsgSequenceId:(unsigned long long)a1;
- (BOOL)isItemValidExpose:(id)a0;
- (void)reportValidExposeItem:(id)a0 ratio:(unsigned int)a1 newMsgSequenceId:(unsigned long long)a2;
- (BOOL)isExposeWithKey:(id)a0 isValidExpose:(BOOL)a1;
- (void)reportClickItem:(id)a0 newMsgSequenceId:(unsigned long long)a1;
- (id)genExposeInfoWithItem:(id)a0 newMsgSequenceId:(unsigned long long)a1;
- (id)genRealTimeExposeInfoWithItem:(id)a0 newMsgSequenceId:(unsigned long long)a1;
- (void)reportExposeCanvasSection:(id)a0 newMsgSequenceId:(unsigned long long)a1;
- (void)reportExposeRecCanvasSection:(id)a0 newMsgSequenceId:(unsigned long long)a1;
- (BOOL)isRecCanvasSectioValidExposed:(id)a0;
- (void)reportValidExposeRecCanvasSection:(id)a0 ratio:(unsigned int)a1;
- (id)genExposeInfoWithRecCanvasSection:(id)a0;
- (id)genRealTimeExposeInfoWithRecCanvasSection:(id)a0;
- (id)genComExposeInfoForCanvasSection:(id)a0;
- (void)reportClickCanvasCardItem:(id)a0;
- (void)reportExposeAdCanvasSection:(id)a0 newMsgSequenceId:(unsigned long long)a1;
- (id)genExposeInfoWithAdCanvasSection:(id)a0;
- (id)genRealTimeExposeInfoWithAdCanvasSection:(id)a0;
- (BOOL)isAdCanvasSectioValidExposed:(id)a0;
- (void)reportValidExposeAdCanvasSection:(id)a0 ratio:(unsigned int)a1;
- (void)reportExposeRecCard:(id)a0;
- (void)reportExposeRecommendItemWithViewModel:(id)a0 newMsgSequenceId:(unsigned long long)a1 index:(long long)a2;
- (void)reportClickRecCard:(id)a0;
- (void)reportClickFinderFixedCard:(id)a0 index:(long long)a1;
- (void)reportClickFinderScrollableCard:(id)a0 index:(long long)a1;
- (void)reportClickMPInterestData:(id)a0 interestData:(id)a1 index:(long long)a2;
- (void)updateExposeRecCardRecReason:(id)a0;
- (BOOL)isRecommendCardValidExposed:(id)a0;
- (BOOL)isRecommendItemValidExposed:(id)a0 withIndex:(long long)a1;
- (void)reportRecommendCardValidExposeItem:(id)a0 withIndex:(long long)a1;
- (void)reportRecCardVideoItemCellAutoPlayStart:(id)a0;
- (void)reportRecCardVideoItemCellAutoPlayEnd:(id)a0;
- (void)reportVideoItemCellAutoPlayStart:(id)a0;
- (void)reportVideoItemCellAutoPlayEnd:(id)a0;
- (void)reportBaseVideoItemCellAutoPlayStartWithKey:(id)a0 logTag:(id)a1;
- (void)reportBaseVideoItemCellAutoPlayEndWithKey:(id)a0 itemViewModel:(id)a1 logTag:(id)a2;
- (void)reportExposeOftenReadItemViewArr:(id)a0;
- (void)reportOftenReadSectionDisappear;
- (void)reportClickOftenReadItemView:(id)a0;
- (id)getContactFromBrandBarItemView:(id)a0;
- (void)reportExposeNotifyItemWithSectionData:(id)a0;
- (void)reportClickNotifyItemWithSectionData:(id)a0;
- (void)reportNotifyItemOnExitTimeline;
- (BOOL)isRecoContentCellView:(id)a0;
- (id)recoFlowItemIdentifierForCell:(id)a0;
- (BOOL)isRecoFlowSectionValidExpose:(id)a0 cellView:(id)a1;
- (void)reportRecoFlowSectionData:(id)a0 cellView:(id)a1 optype:(unsigned int)a2;
- (void)reportClickCardTitleFinderLive:(id)a0;
- (void)reportClickLiveBarItemView:(id)a0;
- (void)reportExposedLiveBarItemView:(id)a0;
- (void)reportLiveMsgExposed:(id)a0 viewModel:(id)a1;
- (void)reportLiveMsgClicked:(id)a0;
- (void)reportLiveMsgWhenLeave;
- (void)MessageReturn:(id)a0 Event:(unsigned int)a1;
- (BOOL)checkCGIBaseRespSuccess:(id)a0;
- (void)reportExposePersonalCenterEntrance:(long long)a0;
- (id)reportKv29480:(int)a0 redDotCount:(long long)a1;
- (void).cxx_destruct;

@end
