@class MMUIButton, NSMutableDictionary, UILabel, CameraScanTipsView, UISwipeGestureRecognizer, UITapGestureRecognizer, CSCHoleMaskViewMgr, RecentPhotoBubbleView, CameraScanBlurButtonWrapView, UIView, BizScanTabBarInfo, MMUIViewController, CameraScannerViewWrapper, NSString, OCRTransReport, CameraScanTabView, CameraScanViewControllerOpenParams, UIImageView;
@protocol CameraScanUIDelegate;

@interface CameraScanViewController : MMUIViewController <MMImagePickerManagerDelegate, IVOIPUILogicMgrExt, CameraScannerStatusExt, MultiTalkMgrExt, WAUINavigationControllerDelegate, WCCameraModuleDelegate, MMUIViewControllerExt, CameraScanTabViewDelegate, CameraScanTipsViewDelegate, UIGestureRecognizerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, WCActionSheetDelegate, BaseScanLogicDelegate, CNetworkStatusExt> {
    long long _scanTabAction;
    NSMutableDictionary *_logicDict;
    unsigned int _beepSound;
    BOOL _isManualCameraZoom;
    OCRTransReport *_transReport;
}

@property (nonatomic) double vcInitTime;
@property (nonatomic) unsigned long long enterScene;
@property (nonatomic) BOOL enableCombineTab;
@property (retain, nonatomic) CameraScanBlurButtonWrapView *albumButtonWrapView;
@property (retain, nonatomic) UIImageView *bgImageView;
@property (nonatomic) BOOL isNetDisconnect;
@property (retain, nonatomic) UILabel *infoLabel;
@property (retain, nonatomic) CameraScanTabView *tabView;
@property (retain, nonatomic) UIView *tabMaskView;
@property (retain, nonatomic) MMUIButton *closeButton;
@property (retain, nonatomic) MMUIButton *torchButton;
@property (retain, nonatomic) UILabel *torchLabel;
@property (nonatomic) BOOL bTorchViewHidden;
@property (retain, nonatomic) UILabel *descLabel;
@property (retain, nonatomic) UIView *alertBgView;
@property (retain, nonatomic) UILabel *alertLabel;
@property (retain, nonatomic) UILabel *smallAlertLabel;
@property (retain, nonatomic) RecentPhotoBubbleView *recentPhotoBubbleView;
@property (nonatomic) BOOL hasInit;
@property (nonatomic) BOOL hasInvokedViewDidLoad;
@property (retain, nonatomic) UISwipeGestureRecognizer *leftSwipeGesture;
@property (retain, nonatomic) UISwipeGestureRecognizer *rightSwipeGesture;
@property (retain, nonatomic) UITapGestureRecognizer *doubleTapGesture;
@property (retain, nonatomic) CameraScannerViewWrapper *cameraScannerWrapper;
@property (retain, nonatomic) BizScanTabBarInfo *tabBarInfo;
@property (retain, nonatomic) CSCHoleMaskViewMgr *holeMaskMgr;
@property (weak, nonatomic) MMUIViewController *vcPushingAnotherVC;
@property (nonatomic) BOOL delayPopSelfTillTopVCDidPush;
@property (retain, nonatomic) CameraScanTipsView *cameraErrorTipsView;
@property (nonatomic) BOOL isShowCameraErrorTips;
@property (nonatomic) BOOL isPickingImageFromAlbum;
@property (nonatomic) BOOL isShowingAlertView;
@property (nonatomic) BOOL isLoading;
@property (nonatomic) unsigned int enterSessionID;
@property (nonatomic) unsigned long long enterTimestampInMS;
@property (nonatomic) unsigned long long enterTimestampIn1970MS;
@property (nonatomic) unsigned int tabSessionID;
@property (nonatomic) BOOL enableOperateReporter;
@property (nonatomic) long long cameraScanType;
@property (readonly, nonatomic) int cameraScanCodeType;
@property (nonatomic) BOOL hideBottomBar;
@property (retain, nonatomic) CameraScanViewControllerOpenParams *openParams;
@property (weak, nonatomic) id<CameraScanUIDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)setVcInitTime:(double)a0;
- (double)vcInitTime;
- (id)init;
- (id)initWithCameraScanType:(long long)a0 presentModal:(BOOL)a1 enterScene:(unsigned long long)a2 bottomBarConfig:(unsigned long long)a3 openParams:(id)a4;
- (id)initWithCameraScanType:(long long)a0 CodeType:(int)a1 presentModal:(BOOL)a2 enterScene:(unsigned long long)a3 bottomBarConfig:(unsigned long long)a4 openParams:(id)a5;
- (void)initBottomBarHidden:(unsigned long long)a0;
- (void)initMember;
- (void)dealloc;
- (void)initView;
- (void)onRecentPhotoButtonClicked;
- (void)tryHideRecentPhotoBubbleView;
- (void)setupBgImageView;
- (void)setupAlbumButtonWrapView;
- (void)setupCameraTipsView;
- (void)centerLabelShowStart;
- (void)centerLabelShowEnd;
- (void)hiddenCameraTips;
- (void)switchFrontCamera;
- (void)setupCloseButton;
- (void)setupCommonViews;
- (void)shouldHideInteracitvesBtns:(BOOL)a0;
- (void)initGesture;
- (BOOL)useTransparentNavibar;
- (void)viewDidLoad;
- (void)setupTabView;
- (BOOL)useBlackStatusbar;
- (BOOL)canShowMiniTaskStarFloatingView;
- (void)viewDidLayoutSubviews;
- (double)getCloseBtnCenterY;
- (void)realDidRotateFromInterfaceOrientation;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)UISplitViewWillChangeSplitMode;
- (void)viewDidTransitionToNewSize;
- (void)setScannerDelegate:(id)a0 cameraScanType:(long long)a1;
- (void)viewWillDisappear:(BOOL)a0;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillBePoped:(BOOL)a0;
- (void)viewWillBePushed:(BOOL)a0;
- (void)viewDidBePushed:(BOOL)a0;
- (void)viewDidBePoped:(BOOL)a0;
- (BOOL)shouldStopScanAndPopSelf;
- (void)stopScanAndPopSelf;
- (void)dismissSelfAndDoReset;
- (void)viewDidPush:(BOOL)a0;
- (void)viewDidPresent:(BOOL)a0;
- (void)enterBackground;
- (void)enterForeground;
- (void)startScan;
- (void)startActiveLogicScan;
- (void)stopScan;
- (void)restartScan;
- (void)cameraModuleInterruptionBegin:(id)a0;
- (void)cameraModuleInterruptionEnd:(id)a0;
- (long long)cameraModuleReportScene;
- (void)stopLoadingDark;
- (BOOL)hasScanLogicController:(long long)a0;
- (id)getActiveLogicController;
- (id)getScanLogicController:(long long)a0;
- (void)ensureHasInvokedViewDidLoad;
- (void)resetOldLogicController;
- (void)resetCameraZoomFactor;
- (void)switchToLogicController:(long long)a0 fromAction:(long long)a1;
- (void)openLogicController:(long long)a0 tabAction:(long long)a1;
- (void)initActiveLogicControllerFromSwitchTab:(BOOL)a0;
- (BOOL)shouldResetScanWhenViewWillAppear;
- (BOOL)shouldResetScanWhenViewDidAppear;
- (void)updateWording;
- (void)showAlertWording:(id)a0 Animated:(BOOL)a1;
- (void)hideAlertWording;
- (float)getPreviewScale:(long long)a0;
- (double)getTabViewHeight;
- (BOOL)isTorchViewHiddenNow;
- (float)getContentHeight;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getContentRect;
- (void)onQRCodeAction:(id)a0;
- (void)onOCRAlbumAction:(id)a0;
- (BOOL)preViewControllerIsKindOf:(Class)a0;
- (void)reportAfterExit;
- (void)reportAfterBePoped;
- (void)resetWhenAppear;
- (void)reportWhenDisappear:(unsigned int)a0;
- (void)updateTorchButtonFrame;
- (void)setupTorchViewsWithOutAddToSuperView;
- (void)showTorchButton;
- (void)tryHideTorchButton;
- (void)doHideTorchButton;
- (void)onTorchButtonClicked:(id)a0;
- (void)showAndStartLoadingView:(id)a0;
- (void)stopAndHideLoadingView;
- (void)setSwipeGestureEnable:(BOOL)a0;
- (void)callSetupHoleMaskViewWithHoleFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)callSetHoleMaskViewHidden:(BOOL)a0 animated:(BOOL)a1;
- (void)callDismissCamearaScanViewCotroller:(id /* block */)a0;
- (void)callSetTabMaskViewHidden:(BOOL)a0;
- (void)onIKnowItBtnClick;
- (void)showImagePicker;
- (void)MMImagePickerManager:(id)a0 didFinishPickingImageWithInfo:(id)a1;
- (void)scanPickedImage:(id)a0;
- (void)MMImagePickerManagerDidCancel:(id)a0;
- (void)tapAtPoint:(id)a0;
- (void)onDoubleTapGesture:(id)a0;
- (void)onPinchGesture:(id)a0;
- (void)onLeftSwipeGesture:(id)a0;
- (void)onRightSwipeGesture:(id)a0;
- (BOOL)isGestureInValidLocation:(id)a0;
- (BOOL)shouldIgnoreSwipeGestureEvent:(id)a0;
- (void)ReachabilityChange:(unsigned int)a0;
- (BOOL)canScanInCurrentReachability;
- (void)onLowLightStatusChanged:(BOOL)a0;
- (void)onBrightnessValueUpdate:(float)a0;
- (id)getNavigationController;
- (void)onPushViewContoller:(id)a0 animated:(BOOL)a1;
- (void)onPopViewControllerCount:(int)a0 animated:(BOOL)a1;
- (void)onPresentModalViewController:(id)a0 animated:(BOOL)a1;
- (void)onDismissModalViewControllerAnimated:(BOOL)a0;
- (void)onEdgePanGestureRecognizerChanged:(BOOL)a0;
- (void)onPopFromStack;
- (void)onStartLoading;
- (void)onStopLoading;
- (void)onDetectSuccess;
- (id)getMainViewController;
- (void)onUpdateWording;
- (void)setInfoLabelHidden:(BOOL)a0 bAnim:(BOOL)a1;
- (void)onShowAlertWording;
- (void)onScanInUnreachableNetworkStatus;
- (void)onScanRequestTimeout;
- (void)onSetCameraZoomFactor:(double)a0;
- (double)getZoomFactor;
- (void)voipWindowMinimized;
- (void)voipWindowMaximized;
- (BOOL)shouldHandleDetectResult:(id)a0;
- (BOOL)isGoodsLogicCtrlActiveAndHandlingResult;
- (BOOL)isScanCodeLogicCtrlActiveAndShowingError;
- (BOOL)isScanCodeLogicCtrlActiveAndHandlingMultiCodes;
- (BOOL)isScanCodeLogicCtrlActiveAndShowingScanGoodsGuide;
- (BOOL)isOCRTransLogicCtrActive;
- (void)onFetchedLastAssetOriginImage:(id)a0 ThumbImage:(id)a1;
- (BOOL)shouldViewControllerDisplayRecentPhotoBubble;
- (void)tabSwitchWithDiffValue:(long long)a0 tabAction:(long long)a1;
- (void)stopCurrLogicCtrlHandler;
- (void)startLogicCtrlHandler:(long long)a0 tabAction:(long long)a1;
- (unsigned int)getUISessionID;
- (long long)currentCameraTabTypeForReport;
- (void)reportSwitchToTab:(long long)a0 tabAction:(long long)a1;
- (void)onVideoVoipViewDidAppear:(id)a0;
- (void)onVideoVoipViewDisappear;
- (void)onVoipMinimized;
- (void)onVoipMaximized;
- (void)onInviteMultiTalk;
- (void)onMultiTalkMinimized;
- (void)onMultiTalkMaximized;
- (void)actionSheet:(id)a0 clickedButtonAtIndex:(long long)a1;
- (void)tabView:(id)a0 didSelectTag:(unsigned long long)a1 fromAction:(long long)a2;
- (BOOL)isForbidSwitchTabIndex;
- (BOOL)navigationController:(id)a0 shouldUsePresentWhenPushViewController:(id)a1 animated:(BOOL)a2 scene:(unsigned long long)a3;
- (BOOL)isNetworkDisconnect;
- (BOOL)isActiveLogicController:(id)a0;
- (void)onCloseButtonClicked;
- (void)onAlbumButtonClicked;
- (void)onMyQRButtonClicked;
- (void)onTakePhotoButtonClicked;
- (void)setCommonViewsOfLogicController:(id)a0;
- (void)resetCommonViewsLogicController:(id)a0;
- (id)getCodesLogicControllerIfCodesActive;
- (id)getGoodsLogicControllerIfCodesActive;
- (long long)businessTypeForEnterScene:(unsigned long long)a0;
- (long long)businessSubTypeForScanTabAction:(long long)a0;
- (BOOL)canShowTabBarItemScanGoods;
- (BOOL)canShowTabBarItemOCRTranslate;
- (BOOL)calScanGoodCombineSwicthState;
- (id)codeTabName;
- (void)didReceiveMemoryWarning;
- (void)onScanCodeFinish;
- (void)registerYReportSdk;
- (unsigned long long)authScene;
- (void)MMUIViewControllerWillPushOrPresent:(id)a0;
- (void)MMUIViewControllerDidPushOrPresent:(id)a0;
- (void).cxx_destruct;

@end
