@class NSString;

@interface CEmoticonPackageWrap : NSObject <WCTTableCoding>

@property (nonatomic) unsigned int ConIntRes2;
@property (nonatomic) unsigned int ConIntRes3;
@property (retain, nonatomic) NSString *ConStrRes3;
@property (retain, nonatomic) NSString *m_packageId;
@property (retain, nonatomic) NSString *m_packageName;
@property (retain, nonatomic) NSString *m_iconUrl;
@property (retain, nonatomic) NSString *m_panelUrl;
@property (nonatomic) unsigned int m_payStatus;
@property (nonatomic) unsigned int m_downloadStatus;
@property (nonatomic) unsigned int m_installTime;
@property (nonatomic) unsigned int m_removeTime;
@property (nonatomic) unsigned int m_count;
@property (retain, nonatomic) NSString *m_designerUin;
@property (retain, nonatomic) NSString *designerIPSetKey;
@property (nonatomic) unsigned long long sortAbsoluteIndex;
@property (nonatomic) long long lastInsertedRowID;
@property (nonatomic) BOOL isAutoIncrement;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (const void *)objectRelationalMapping;
+ (const void *)allProperties;
+ (id)allBridgeProperties;
+ (id)__wcdbtyper;
+ (const void *)m_packageId;
+ (const void *)__wcdb_synthesize_0:(void *)a0;
+ (id)swift_m_packageId;
+ (const void *)m_packageName;
+ (const void *)__wcdb_synthesize_1:(void *)a0;
+ (id)swift_m_packageName;
+ (const void *)m_iconUrl;
+ (const void *)__wcdb_synthesize_2:(void *)a0;
+ (id)swift_m_iconUrl;
+ (const void *)m_panelUrl;
+ (const void *)__wcdb_synthesize_3:(void *)a0;
+ (id)swift_m_panelUrl;
+ (const void *)m_payStatus;
+ (const void *)__wcdb_synthesize_4:(void *)a0;
+ (id)swift_m_payStatus;
+ (const void *)m_downloadStatus;
+ (const void *)__wcdb_synthesize_5:(void *)a0;
+ (id)swift_m_downloadStatus;
+ (const void *)m_installTime;
+ (const void *)__wcdb_synthesize_6:(void *)a0;
+ (id)swift_m_installTime;
+ (const void *)m_removeTime;
+ (const void *)__wcdb_synthesize_7:(void *)a0;
+ (id)swift_m_removeTime;
+ (const void *)m_count;
+ (const void *)__wcdb_synthesize_8:(void *)a0;
+ (id)swift_m_count;
+ (const void *)ConIntRes2;
+ (const void *)__wcdb_synthesize_9:(void *)a0;
+ (id)swift_ConIntRes2;
+ (const void *)ConIntRes3;
+ (const void *)__wcdb_synthesize_10:(void *)a0;
+ (id)swift_ConIntRes3;
+ (const void *)m_designerUin;
+ (const void *)__wcdb_synthesize_11:(void *)a0;
+ (id)swift_m_designerUin;
+ (const void *)designerIPSetKey;
+ (const void *)__wcdb_synthesize_12:(void *)a0;
+ (id)swift_designerIPSetKey;
+ (const void *)ConStrRes3;
+ (const void *)__wcdb_synthesize_13:(void *)a0;
+ (id)swift_ConStrRes3;
+ (void)__wcdb_column_constraint_14:(void *)a0;
+ (void)__wcdb_column_constraint_15:(void *)a0;
+ (void)__wcdb_column_constraint_16:(void *)a0;
+ (void)__wcdb_column_constraint_17:(void *)a0;
+ (void)__wcdb_column_constraint_18:(void *)a0;
+ (void)__wcdb_column_constraint_19:(void *)a0;
+ (void)__wcdb_column_constraint_20:(void *)a0;
+ (void)__wcdb_column_constraint_21:(void *)a0;
+ (void)__wcdb_index_22:(void *)a0;
+ (void)__wcdb_index_23:(void *)a0;
+ (void)additionalObjectRelationalMapping:(void *)a0;
+ (id)packageItemFromSummary:(id)a0;

- (BOOL)isTusiji;
- (id)init;
- (void).cxx_destruct;

@end
