@class LiteAppSharedItem, BrandMpVideoItem, GiftCardItem, WCFinderOrderShareItem, MMLiveAppMsgInnerItem, BSAffMsgExtraData, NSMutableDictionary, FavoritesItem, WCFinderShareItemContainer, TingShareListenItem, iWatchAppMsgItem, MPPageIdentityInfo, WAAppMsgItem, TingShareChatRoomItem, WCFinderClubSystemMessage, WXSecretMsgItem, ShareMsgObj, VoiceAppMsgItem, MMTemplateMsg3rdAppShowItem, EmoticonSharedItem, GameLifeItem, TingShareCategoryItem, OpenSDKAppBrandItem, MPScreenshotArticleInfo, WCFinderLiveShareItem, EcsKFMsgItem, VideoUploadStatInfo, WCPayInfoItem, ServiceNotifyMessageItem, WCPayPocketMoneyMsgItem, AppTVItem, WeChatIntroductionItem, ScanCodeHistoryItem, WCFinderContentColumnSharedItem, WCFinderLiveProductShareItem, WCCanvasPageItem, WASourceWeappInfo, EcsGiftMsgItem, AppProductItem, StrongNotificationItemPB, WCFinderShareToMomentsItem, EcsInfoItem, NotifyMsgItem, MMAsset, MMEasterEggMatch, MpShareTraceItem, MMReaderInfo, WebviewSharedItem, ImageInfo, PushMailWrap, NSString, MallProductItem, MMMusicShareItem, MMFinderLiveRedPacketMessage, EmotionPageSharedItem, NSMutableArray, WSVideoModel, GroupNoticeItem, AppMsgShareItem, EmoticonSecurityInfoList, TingShareLyricsItem, EmotionDesignerSharedItem, WCFinderCollectionShareItem, BrandResortDigestInfo, WCFinderMessageShareNameCard, PatMessageWrap, MessageExpItem, EmoticonAppMsgItem, WCPayExtensionInfo, NSArray, HistoryMsgsInfo, AppMMScheduleItem, WCMegaVideoShareItem, RevokeWrap, WCFinderMessageGuaranteeItem, BrandAffMsgExtraData, WCPayThirdInfo, WxGameCardItem, HardWareItem, CardTicketItem, MMReferPartialInfo, WCFinderMessageVerifyItem, WCFinderTopicShareItem, CContact, GameShareCardItem, NSData, WAScreenshotContextInfo, WCFinderLiveShopWindowShareItem, GameShareNameCard, SourceImgInfo, WCFinderThemeLiveStreamShareItem;
@protocol IMsgExtendOperation;

@interface CMessageWrap : MMObject <WCPlayerMediaExt, ISysNewXmlMsgExtendOperation, IAppMsgPathMgr, IMsgExtendOperation, NSCopying> {
    NSString *m_nsLastDisplayContent;
}

@property (retain, nonatomic) NSString *m_nsTitle;
@property (retain, nonatomic) NSString *m_nsDesc;
@property (retain, nonatomic) NSString *m_nsAppAction;
@property (retain, nonatomic) NSString *m_nsUsername;
@property (nonatomic) unsigned int m_uiShowType;
@property (retain, nonatomic) NSString *m_nsAppContent;
@property (retain, nonatomic) NSString *m_nsAppMediaUrl;
@property (retain, nonatomic) NSString *m_nsAppMediaLowUrl;
@property (retain, nonatomic) NSString *m_nsAppMediaDataUrl;
@property (retain, nonatomic) NSString *m_nsAppMediaLowBandDataUrl;
@property (nonatomic) unsigned int m_uiAppVersion;
@property (nonatomic) unsigned int m_uiAppExtShowType;
@property (retain, nonatomic) NSString *m_nsAppExtInfo;
@property (retain, nonatomic) NSString *m_nsSourceUsername;
@property (retain, nonatomic) NSString *m_nsSourceDisplayname;
@property (nonatomic) unsigned int m_uiRemindTime;
@property (nonatomic) unsigned int m_uiRemindId;
@property (retain, nonatomic) NSString *m_nsRemindAttachId;
@property (nonatomic) unsigned int m_uiRemindAttachTotalLen;
@property (nonatomic) unsigned int m_uiRemindFormat;
@property (nonatomic) unsigned int m_uiOriginFormat;
@property (nonatomic) unsigned int m_uiOriginMsgSvrId;
@property (retain, nonatomic) NSString *m_nsThumbUrl;
@property (retain, nonatomic) NSString *m_nsAppName;
@property (nonatomic) unsigned int m_uiEncryVer;
@property (retain, nonatomic) NSString *m_nsAppMediaTagName;
@property (nonatomic) unsigned int m_fullXmlLength;
@property (nonatomic) unsigned int m_realInnerType;
@property (retain, nonatomic) MallProductItem *m_oMallProductItem;
@property (retain, nonatomic) AppProductItem *m_oAppProductItem;
@property (retain, nonatomic) CardTicketItem *m_oCardTicketItem;
@property (retain, nonatomic) GiftCardItem *m_oGiftCardItem;
@property (retain, nonatomic) NSString *m_nsEmojiInfoBase64;
@property (retain, nonatomic) EmoticonSharedItem *m_oEmoticonSharedItem;
@property (retain, nonatomic) EmotionDesignerSharedItem *m_oEmotionDesignerSharedItem;
@property (retain, nonatomic) EmotionPageSharedItem *m_oEmotionPageSharedItem;
@property (retain, nonatomic) AppTVItem *m_oAppTVItem;
@property (retain, nonatomic) FavoritesItem *m_oRecordItem;
@property (retain, nonatomic) HardWareItem *m_oHardWareItem;
@property (retain, nonatomic) WCPayInfoItem *m_oWCPayInfoItem;
@property (retain, nonatomic) EmoticonAppMsgItem *m_oEmoticonAppMsgItem;
@property (retain, nonatomic) VoiceAppMsgItem *m_oVoiceAppMsgItem;
@property (retain, nonatomic) WebviewSharedItem *m_oWebviewSharedItem;
@property (retain, nonatomic) MpShareTraceItem *m_oMpShareTraceItem;
@property (retain, nonatomic) iWatchAppMsgItem *m_oiWatchMsgItem;
@property (retain, nonatomic) NSString *m_nsAppMessageExt;
@property (retain, nonatomic) NSString *m_nsAppMessageAction;
@property (nonatomic) BOOL m_bIsForceUpdate;
@property (retain, nonatomic) WCCanvasPageItem *m_oCanvasPageItem;
@property (retain, nonatomic) OpenSDKAppBrandItem *m_openSDKAppBrandItem;
@property (nonatomic) BOOL m_isDirectSend;
@property (retain, nonatomic) NSString *m_nsTemplateId;
@property (retain, nonatomic) NSString *m_nsTemplateUniqueId;
@property (nonatomic) unsigned int m_uiTemplateType;
@property (nonatomic) unsigned int m_uiTemplateSubType;
@property (retain, nonatomic) NSString *m_openWeAppNativeExtraData;
@property (nonatomic) unsigned int m_openWeAppBusinessScene;
@property (retain, nonatomic) MMTemplateMsg3rdAppShowItem *m_oTemplateMsg3rdAppShowItem;
@property (nonatomic) BOOL m_bForbidJumpProfileWhenClickAvatar;
@property (retain, nonatomic) NSString *m_clientAppDataId;
@property (retain, nonatomic) NSString *m_mediaId;
@property (nonatomic) BOOL m_isReaderForbidForward;
@property (nonatomic) BOOL m_isHideHead;
@property (retain, nonatomic) NSString *m_nsStreamVideoUrl;
@property (nonatomic) unsigned int m_uiStreamVideoTime;
@property (retain, nonatomic) NSString *m_nsStreamVideoTitle;
@property (retain, nonatomic) NSString *m_nsStreamVideoWording;
@property (retain, nonatomic) NSString *m_nsStreamVideoWebUrl;
@property (retain, nonatomic) NSString *m_nsStreamVideoThumbUrl;
@property (retain, nonatomic) NSString *m_nsStreamVideoPublishId;
@property (retain, nonatomic) NSString *m_nsStreamVideoAdUxInfo;
@property (retain, nonatomic) NSString *m_nsStatExtStr;
@property (nonatomic) unsigned int m_uiDownloadPercent;
@property (retain, nonatomic) WAAppMsgItem *m_oWAAppItem;
@property (nonatomic) unsigned int m_uiWeAppState;
@property (nonatomic) unsigned int m_uiWeAppVersion;
@property (nonatomic) unsigned int m_isAudioTemplate;
@property (retain, nonatomic) NSString *m_audioTemplateUrl;
@property (nonatomic) unsigned int m_isAcceptWithForcePush;
@property (retain, nonatomic) NSString *m_forcePushInfo;
@property (retain, nonatomic) WCPayExtensionInfo *m_payExtensionInfo;
@property (retain, nonatomic) WSVideoModel *m_videoFlowInfo;
@property (retain, nonatomic) AppMMScheduleItem *m_scheduleItem;
@property (retain, nonatomic) ScanCodeHistoryItem *m_scanHistoryItem;
@property (retain, nonatomic) WCPayThirdInfo *m_thirdC2CInfo;
@property (retain, nonatomic) NSString *m_nsAttachFileKey;
@property (nonatomic) unsigned int m_uiContinueUploadCount;
@property (retain, nonatomic) NSString *m_authkey;
@property (retain, nonatomic) AppMsgShareItem *m_nsShareItem;
@property (nonatomic) unsigned int m_subscrMsgScopeType;
@property (nonatomic) unsigned int m_templateMsgBusinessType;
@property (retain, nonatomic) BrandMpVideoItem *m_brandMpVideoItem;
@property (copy, nonatomic) NSString *m_nsSongAlbumUrl;
@property (copy, nonatomic) NSString *m_nsSongLyric;
@property (nonatomic) unsigned int m_uiDirectShare;
@property (retain, nonatomic) WCFinderMessageShareNameCard *m_finderShareNameCard;
@property (retain, nonatomic) WCFinderMessageVerifyItem *finderVerifyItem;
@property (retain, nonatomic) WCFinderShareToMomentsItem *finderShareItem;
@property (retain, nonatomic) WCFinderShareItemContainer *finderShareItemContainer;
@property (retain, nonatomic) WCMegaVideoShareItem *finderLongVideoShareItem;
@property (retain, nonatomic) WCFinderTopicShareItem *finderTopicShareItem;
@property (retain, nonatomic) WCFinderCollectionShareItem *finderCollectionShareItem;
@property (retain, nonatomic) WCFinderLiveShareItem *finderLiveShareItem;
@property (retain, nonatomic) WCFinderLiveProductShareItem *finderLiveProductShareItem;
@property (retain, nonatomic) WCFinderOrderShareItem *finderOrderShareItem;
@property (retain, nonatomic) WCFinderLiveShopWindowShareItem *finderShopWindowShare;
@property (retain, nonatomic) WCFinderContentColumnSharedItem *finderContentColumnSharedItem;
@property (retain, nonatomic) MMLiveAppMsgInnerItem *liveAppMsgInnerItem;
@property (retain, nonatomic) PatMessageWrap *patMessageWrap;
@property (retain, nonatomic) WCFinderMessageGuaranteeItem *finderGuarantee;
@property (retain, nonatomic) WCFinderThemeLiveStreamShareItem *finderThemeLiveShareItem;
@property (retain, nonatomic) NSString *m_nsSolitaireXml;
@property (retain, nonatomic) NSString *m_nsOriginTitle;
@property (retain, nonatomic) NSString *referMessageSenderUsrname;
@property (retain, nonatomic) NSString *referMessageSenderDisplayName;
@property (nonatomic) unsigned int m_referFromScene;
@property (nonatomic) BOOL roomToolsFlag;
@property (retain, nonatomic) GameShareNameCard *m_gameShareNameCard;
@property (retain, nonatomic) GameLifeItem *m_gameLifeItem;
@property (retain, nonatomic) LiteAppSharedItem *m_liteAppSharedItem;
@property (retain, nonatomic) MMMusicShareItem *m_musicShareItem;
@property (retain, nonatomic) WCPayPocketMoneyMsgItem *m_payPocketMoneyItem;
@property (retain, nonatomic) GameShareCardItem *m_gameShareCardItem;
@property (retain, nonatomic) WxGameCardItem *m_wxGameCardItem;
@property (retain, nonatomic) EcsGiftMsgItem *m_ecsGiftMsgItem;
@property (retain, nonatomic) EcsKFMsgItem *m_ecsKFMsgItem;
@property (retain, nonatomic) EcsInfoItem *m_ecsInfo;
@property (retain, nonatomic) TingShareListenItem *tingListenItem;
@property (retain, nonatomic) TingShareCategoryItem *tingCategoryItem;
@property (retain, nonatomic) TingShareChatRoomItem *tingChatRoomItem;
@property (retain, nonatomic) TingShareLyricsItem *tingLyricsItem;
@property (retain, nonatomic) NotifyMsgItem *m_notifyMsgItem;
@property (retain, nonatomic) ServiceNotifyMessageItem *m_serviceNotifyMsgItem;
@property (nonatomic) BOOL bAppMsgCompleteFlag;
@property (retain, nonatomic) NSString *m_nsMsgFileUploadToken;
@property (nonatomic) long long m_overwriteNewMsgId;
@property (copy, nonatomic) NSString *lanTransferInfo;
@property (copy, nonatomic) NSString *syncRecordCtx;
@property (nonatomic) unsigned int m_forwardFlag;
@property (retain, nonatomic) WXSecretMsgItem *m_secretMsgItem;
@property (retain, nonatomic) NSString *m_nsGuardianTicket;
@property (nonatomic) unsigned int guardianBindScene;
@property (retain, nonatomic) NSString *m_nsTempAccessBizKey;
@property (nonatomic) unsigned int m_uiTempAccessBizType;
@property (nonatomic) unsigned int m_uiTempAccessAgreenTime;
@property (copy, nonatomic) NSString *teenagerAuthorizationTitle;
@property (copy, nonatomic) NSString *teenagerAuthorizationContent;
@property (copy, nonatomic) NSString *teenagerAuthorizationAgreeDesc;
@property (retain, nonatomic) GroupNoticeItem *groupNoticeItem;
@property (retain, nonatomic) NSString *announcementId;
@property (retain, nonatomic) WeChatIntroductionItem *introductionItem;
@property (retain, nonatomic) NSString *m_thumbDataHash;
@property (retain, nonatomic) NSString *m_hdAlbumThumbFileHash;
@property (nonatomic) unsigned int m_opensdkShareIsModified;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) unsigned int m_uiEmoticonType;
@property (nonatomic) unsigned int m_uiGameType;
@property (nonatomic) unsigned int m_uiGameContent;
@property (copy, nonatomic) NSString *m_nsEmoticonBelongToProductID;
@property (retain, nonatomic) NSString *m_cdnUrlString;
@property (retain, nonatomic) NSString *m_encryptUrlString;
@property (retain, nonatomic) NSString *m_aesKey;
@property (retain, nonatomic) NSString *m_nsExternUrl;
@property (retain, nonatomic) NSString *m_nsExternMd5;
@property (retain, nonatomic) NSString *m_nsDesignerId;
@property (retain, nonatomic) NSString *m_nsActivityId;
@property (retain, nonatomic) NSString *m_nsLinkId;
@property (retain, nonatomic) NSString *m_nsThumbImgUrl;
@property (nonatomic) unsigned int m_uiEmoticonWidth;
@property (nonatomic) unsigned int m_uiEmoticonHeight;
@property (retain, nonatomic) NSString *m_tpUrlString;
@property (retain, nonatomic) NSString *m_authkey;
@property (retain, nonatomic) NSString *m_attachedText;
@property (retain, nonatomic) NSString *m_attachedTextColor;
@property (retain, nonatomic) NSString *m_lensId;
@property (retain, nonatomic) NSString *m_nsEmoticonSvrDescStr;
@property (nonatomic) BOOL disableRecordSend;
@property (nonatomic) unsigned int m_uiHDImgSize;
@property (nonatomic) unsigned int m_uiNormalImgSize;
@property (nonatomic) unsigned int m_uiHevcNormalImgSize;
@property (retain, nonatomic) NSData *m_dtImg;
@property (retain, nonatomic) ImageInfo *m_oImageInfo;
@property (retain, nonatomic) NSString *m_nsImgHDUrl;
@property (retain, nonatomic) NSString *m_nsImgMidUrl;
@property (retain, nonatomic) MMAsset *m_asset;
@property (retain, nonatomic) NSData *wxamData;
@property (nonatomic) BOOL m_isCanUpload;
@property (nonatomic) unsigned int m_uiScene;
@property (retain, nonatomic) NSData *m_dtSenderMidImg;
@property (retain, nonatomic) NSString *m_nsAttachFileKey;
@property (nonatomic) unsigned int m_uiContinueUploadCount;
@property (retain, nonatomic) NSString *m_authkey;
@property (retain, nonatomic) NSString *m_imgDataHash;
@property (retain, nonatomic) NSString *m_imgSourceUrl;
@property (nonatomic) BOOL m_forbidShowSource;
@property (retain, nonatomic) NSString *m_nsOriginSourceDataMd5;
@property (retain, nonatomic) NSString *m_phash;
@property (retain, nonatomic) NSString *m_pdqhash;
@property (readonly, nonatomic) NSString *secInfo;
@property (nonatomic) BOOL m_isSpatial;
@property (nonatomic) unsigned int m_LivePhotoDuration;
@property (nonatomic) unsigned int m_LivePhotoStillImageTimeMs;
@property (nonatomic) unsigned int m_LivePhotoHDSize;
@property (retain, nonatomic) NSString *m_nsLivePhotoHDMd5;
@property (retain, nonatomic) NSString *m_nsLivePhotoHDUrl;
@property (nonatomic) unsigned int m_LivePhotoSize;
@property (retain, nonatomic) NSString *m_nsLivePhotoMd5;
@property (retain, nonatomic) NSString *m_nsLivePhotoUrl;
@property (nonatomic) double m_latitude;
@property (nonatomic) double m_longitude;
@property (nonatomic) double m_mapScale;
@property (retain, nonatomic) NSString *m_locationLabel;
@property (retain, nonatomic) NSString *m_poiName;
@property (retain, nonatomic) NSString *m_mapType;
@property (retain, nonatomic) NSString *m_infoUrl;
@property (retain, nonatomic) NSString *m_cityName;
@property (nonatomic) unsigned int m_adCode;
@property (retain, nonatomic) NSString *m_poiId;
@property (retain, nonatomic) NSString *m_buildingId;
@property (retain, nonatomic) NSString *m_floorName;
@property (retain, nonatomic) NSString *m_poiCategoryTips;
@property (retain, nonatomic) NSString *m_poiBusinessHour;
@property (retain, nonatomic) NSString *m_poiPhone;
@property (retain, nonatomic) NSString *m_poiPriceTips;
@property (nonatomic) BOOL m_isFromPoiList;
@property (retain, nonatomic) NSString *toListMd5;
@property (retain, nonatomic) PushMailWrap *m_oPushMailWrap;
@property (retain, nonatomic) NSString *revokeBatchId;
@property (retain, nonatomic) NSString *m_showContent;
@property (retain, nonatomic) NSMutableArray *m_arrMembers;
@property (retain, nonatomic) NSString *m_qrCode;
@property (retain, nonatomic) NSString *m_url;
@property (retain, nonatomic) NSString *m_sessionShowContent;
@property (retain, nonatomic) NSString *m_newXmlType;
@property (nonatomic) long long m_msgInnerType;
@property (retain, nonatomic) NSString *m_inviterName;
@property (retain, nonatomic) NSString *m_reportExtraData;
@property (retain, nonatomic) NSMutableArray *m_arrInviteeMembers;
@property (retain, nonatomic) NSMutableDictionary *m_dicQuitRoomInfo;
@property (retain, nonatomic) NSString *m_nsInviteTickets;
@property (nonatomic) BOOL m_bNewInv;
@property (nonatomic) BOOL m_bNewApprove;
@property (nonatomic) BOOL m_bHasApprove;
@property (nonatomic) BOOL m_bNeedReloadSubView;
@property (retain, nonatomic) NSString *m_fromChatUserName;
@property (retain, nonatomic) NSString *m_nsInviteReason;
@property (retain, nonatomic) NSString *m_nsRevokeContent;
@property (nonatomic) unsigned long long m_revokedReferSvrid;
@property (retain, nonatomic) NSString *m_revokedAtUserList;
@property (nonatomic) unsigned int m_revokedMsgInnerType;
@property (nonatomic) BOOL m_bCanFold;
@property (nonatomic) BOOL m_bFolded;
@property (nonatomic) BOOL m_bIsUpdatableMsgSubscribeMsg;
@property (nonatomic) unsigned int m_updatableMsgType;
@property (retain, nonatomic) CContact *m_inviterContact;
@property (retain, nonatomic) CMessageWrap *m_historyRecordMsg;
@property (retain, nonatomic) HistoryMsgsInfo *m_historyMsgsInfo;
@property (nonatomic) BOOL m_bHadAddNewHistoryMsg;
@property (nonatomic) unsigned long long m_ui64MassMsgSvrID;
@property (retain, nonatomic) MMFinderLiveRedPacketMessage *m_liveRedPacketMessage;
@property (retain, nonatomic) WCFinderClubSystemMessage *m_finderClubMessage;
@property (retain, nonatomic) NSArray *m_mergeArrReaderWaps;
@property (retain, nonatomic) RevokeWrap *revokeWrap;
@property (nonatomic) unsigned int m_inviterJoinScene;
@property (retain, nonatomic) NSString *m_inviterQRCode;
@property (nonatomic) unsigned int m_inviterQRCodeExpiredTime;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) unsigned int m_uiVideoTime;
@property (nonatomic) unsigned int m_uiVideoLen;
@property (nonatomic) unsigned int m_uiCameraType;
@property (nonatomic) unsigned int m_uiVideoSource;
@property (nonatomic) unsigned int m_uiVideoOffset;
@property (retain, nonatomic) NSString *m_nsFileParam;
@property (retain, nonatomic) NSString *m_nsStreamVideoUrl;
@property (nonatomic) unsigned int m_uiStreamVideoTime;
@property (retain, nonatomic) NSString *m_nsStreamVideoTitle;
@property (retain, nonatomic) NSString *m_nsStreamVideoWording;
@property (retain, nonatomic) NSString *m_nsStreamVideoWebUrl;
@property (retain, nonatomic) NSString *m_nsStreamVideoThumbUrl;
@property (retain, nonatomic) NSString *m_nsStreamVideoPublishId;
@property (retain, nonatomic) NSString *m_nsStreamVideoAdUxInfo;
@property (retain, nonatomic) NSString *m_nsStatExtStr;
@property (retain, nonatomic) NSString *m_nsNewMd5;
@property (retain, nonatomic) MMAsset *m_asset;
@property (retain, nonatomic) NSString *m_assetIdForForward;
@property (retain, nonatomic) NSString *m_nsAssetId;
@property (nonatomic) unsigned int m_uiVideoFormat;
@property (nonatomic) unsigned int m_uiPreDownloadPercent;
@property (nonatomic) unsigned int m_uiPreDownloadNetType;
@property (retain, nonatomic) NSString *m_nsNoPreDownloadRange;
@property (retain, nonatomic) VideoUploadStatInfo *m_oVideoUploadStatInfo;
@property (retain, nonatomic) NSString *m_nsAttachFileKey;
@property (nonatomic) unsigned int m_uiContinueUploadCount;
@property (nonatomic) unsigned int m_uiRawContinueUploadCount;
@property (nonatomic) unsigned long long m_uiRawFileLength;
@property (retain, nonatomic) NSString *m_nsRawFileMd5;
@property (retain, nonatomic) NSString *m_nsRawDataUrl;
@property (retain, nonatomic) NSString *m_nsRawAeskey;
@property (nonatomic) unsigned long long m_uiRawVideoOffset;
@property (nonatomic) unsigned int m_uiRawVideoFormat;
@property (retain, nonatomic) NSString *m_nsOriginSourceDataMd5;
@property (nonatomic) unsigned int m_uOverWriteMsgSendTime;
@property (nonatomic) long long m_n64OverWriteMsgSvrID;
@property (retain, nonatomic) NSString *m_nsUploadToken;
@property (nonatomic) BOOL m_bIsPlaceHolder;
@property (nonatomic) BOOL m_bIsVideoMsgToOverWrite;
@property (retain, nonatomic) NSString *m_nsAppID;
@property (retain, nonatomic) NSString *m_nsAppName;
@property (nonatomic) unsigned int m_uiAppVersion;
@property (nonatomic) BOOL m_bIsForceUpdate;
@property (retain, nonatomic) NSString *m_nsAppMediaTagName;
@property (retain, nonatomic) NSString *m_nsAppMessageExt;
@property (retain, nonatomic) NSString *m_nsAppMessageAction;
@property (retain, nonatomic) NSString *m_nsEncodeJson;
@property (retain, nonatomic) NSString *m_authkey;
@property (nonatomic) BOOL m_isSpatial;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) unsigned int m_uiVoiceTime;
@property (nonatomic) unsigned int m_uiVoiceFormat;
@property (nonatomic) unsigned int m_uiVoiceEndFlag;
@property (nonatomic) unsigned int m_uiVoiceCancelFlag;
@property (nonatomic) unsigned int m_uiVoiceForwardFlag;
@property (retain, nonatomic) NSData *m_dtVoice;
@property (retain, nonatomic) NSString *voiceUrl;
@property (retain, nonatomic) NSString *aesKey;
@property (nonatomic) unsigned int m_uiVoipRecvTime;
@property (nonatomic) unsigned int m_uiVoipInviteType;
@property (nonatomic) unsigned long long m_iVoipRoomid;
@property (nonatomic) long long m_i64VoipKey;
@property (nonatomic) unsigned int m_wordingType;
@property (nonatomic) unsigned int m_duration;
@property (nonatomic) unsigned int m_uiMesLocalID;
@property (nonatomic) long long m_n64MesSvrID;
@property (retain, nonatomic) NSString *m_nsFromUsr;
@property (retain, nonatomic) NSString *m_nsToUsr;
@property (nonatomic) unsigned int m_uiMessageType;
@property (retain, nonatomic) NSString *m_nsContent;
@property (retain, nonatomic) NSString *m_nsBeforeDisplayContent;
@property (nonatomic) unsigned int m_uiStatus;
@property (nonatomic) unsigned int m_uiImgStatus;
@property (nonatomic) unsigned int m_uiMsgFlag;
@property (nonatomic) unsigned int m_uiCreateTime;
@property (nonatomic) unsigned int m_uiSvrCreateTime;
@property (retain, nonatomic) NSString *m_openImStrId;
@property (retain, nonatomic) NSString *m_bEncUserName;
@property (retain, nonatomic) NSString *m_nsPushContent;
@property (retain, nonatomic) NSString *m_nsPushTitle;
@property (retain, nonatomic) NSString *m_nsPushPrefix;
@property (retain, nonatomic) NSString *m_nsPushBody;
@property (nonatomic) long long m_pushStyle;
@property (retain, nonatomic) NSString *m_nsMsgSource;
@property (retain, nonatomic) NSString *m_nsRealChatUsr;
@property (retain, nonatomic) id<IMsgExtendOperation> m_extendInfoWithMsgTypeForBiz;
@property (retain, nonatomic) id<IMsgExtendOperation> m_extendInfoWithMsgType;
@property (retain, nonatomic) id<IMsgExtendOperation> m_extendInfoWithFromUsr;
@property (nonatomic) BOOL m_bForward;
@property (nonatomic) BOOL m_bCdnForward;
@property (retain, nonatomic) NSData *m_dtThumbnail;
@property (nonatomic) BOOL m_bNew;
@property (nonatomic) unsigned int m_uiSendTime;
@property (nonatomic) unsigned int m_uiEmojiStatFlag;
@property (retain, nonatomic) NSString *m_nsPattern;
@property (nonatomic) unsigned int m_uiPercent;
@property (nonatomic) unsigned int m_uiFinishedLength;
@property (nonatomic) unsigned int m_uiDownloadStatus;
@property (retain, nonatomic) NSString *m_nsKFWorkerOpenID;
@property (nonatomic) unsigned int m_uiKFType;
@property (nonatomic) unsigned int m_intellCmdType;
@property (retain, nonatomic) NSString *m_intellCmdData;
@property (retain, nonatomic) NSString *m_loginTaskId;
@property (nonatomic) unsigned int m_nsBizChatUserType;
@property (copy, nonatomic) NSString *m_nsBizCliMsgId;
@property (retain, nonatomic) NSString *m_nsBizChatId;
@property (nonatomic) unsigned int m_uiBizChatVer;
@property (nonatomic) BOOL m_isP8Msg;
@property (nonatomic) unsigned long long mediaExpireAt;
@property (retain, nonatomic) NSString *m_forcePushId;
@property (retain, nonatomic) StrongNotificationItemPB *m_forcePushItem;
@property (retain, nonatomic) NSString *m_nsProfileRecommendInfo;
@property (retain, nonatomic) NSString *m_nsBizClientMsgID;
@property (retain, nonatomic) NSString *m_nsAtUserList;
@property (nonatomic) BOOL m_nsAtAll;
@property (nonatomic) unsigned long long watchMsgSourceType;
@property (nonatomic) BOOL m_isTempSessionMsg;
@property (nonatomic) BOOL m_isEnterpriseMsg;
@property (nonatomic) unsigned int m_sequenceId;
@property (retain, nonatomic) NSString *m_firstSendMsgId;
@property (nonatomic) unsigned int m_firstSendTime;
@property (nonatomic) BOOL m_ignoreSoftBank;
@property (retain, nonatomic) NSString *riskFileMd5List;
@property (nonatomic) unsigned int riskFileFlag;
@property (retain, nonatomic) NSString *riskWarningUrl;
@property (nonatomic) unsigned int unreadMediaExpired;
@property (nonatomic) BOOL m_bForbidden;
@property (nonatomic) unsigned int m_bTextFold;
@property (retain, nonatomic) NSString *m_nsTipsUrl;
@property (retain, nonatomic) NSString *m_nsShareTipsUrl;
@property (nonatomic) unsigned int m_secCtrlFlag;
@property (nonatomic) unsigned int m_blockRange;
@property (nonatomic) unsigned int m_mediaToEmoji;
@property (nonatomic) unsigned int m_selectLength;
@property (nonatomic) unsigned int m_forbidLink;
@property (nonatomic) unsigned int m_previewType;
@property (nonatomic) unsigned int m_bubbleType;
@property (retain, nonatomic) NSString *m_uuid;
@property (retain, nonatomic) NSString *m_publisherId;
@property (retain, nonatomic) NSString *m_initPublisherId;
@property (retain, nonatomic) EmoticonSecurityInfoList *m_emojiSecurityInfoList;
@property (retain, nonatomic) NSString *m_nsAesKey;
@property (retain, nonatomic) NSString *m_nsMsgThumbUrl;
@property (retain, nonatomic) NSString *m_nsMsgThumbMd5;
@property (retain, nonatomic) NSString *m_nsMsgThumbAesKey;
@property (nonatomic) unsigned int m_uiMsgThumbSize;
@property (nonatomic) unsigned int m_uiMsgThumbWidth;
@property (nonatomic) unsigned int m_uiMsgThumbHeight;
@property (retain, nonatomic) NSString *m_nsAutoDownloadControl;
@property (retain, nonatomic) NSString *m_nsEmoticonMD5;
@property (retain, nonatomic) NSArray *m_arrReaderWaps;
@property (nonatomic) unsigned int m_mmreaderSubType;
@property (retain, nonatomic) NSString *m_nsImgSrc;
@property (nonatomic) unsigned int m_uiUploadStatus;
@property (retain, nonatomic) NSString *m_nsDisplayName;
@property (retain, nonatomic) MessageExpItem *m_oMsgExpItem;
@property (retain, nonatomic) NSString *m_platformSignature;
@property (nonatomic) BOOL forbidDisplayInSession;
@property (retain, nonatomic) MMEasterEggMatch *eggMatch;
@property (nonatomic) long long m_easterEggIncludedType;
@property (nonatomic) long long m_easterEggBlockType;
@property (nonatomic) unsigned int m_easterEggRandomSeed;
@property (nonatomic) unsigned int m_uiAppMsgInnerType;
@property (nonatomic) unsigned int m_uiVoipStatus;
@property (nonatomic) long long m_uiAppDataSize;
@property (retain, nonatomic) NSString *m_nsMsgDataUrl;
@property (retain, nonatomic) NSString *m_nsAppFileExt;
@property (retain, nonatomic) NSString *m_nsAppAttachID;
@property (retain, nonatomic) NSString *m_nsAppID;
@property (nonatomic) unsigned int m_uiApiSDKVersion;
@property (retain, nonatomic) NSString *m_nsMsgAttachUrl;
@property (retain, nonatomic) NSString *m_nsShareOriginUrl;
@property (retain, nonatomic) NSString *m_nsShareOpenUrl;
@property (retain, nonatomic) NSMutableDictionary *m_dicStatParas;
@property (nonatomic) unsigned int m_forwardType;
@property (nonatomic) BOOL m_bAppAttachExistInSvr;
@property (retain, nonatomic) NSString *m_nsMsgMd5;
@property (nonatomic) int m_nDownloadLimit;
@property (nonatomic) BOOL m_bIsFromBrandSession;
@property (retain, nonatomic) NSMutableDictionary *m_dicForwardParas;
@property (nonatomic) BOOL m_bIsBrandSendMass;
@property (retain, nonatomic) NSString *m_bizMsgMenuID;
@property (retain, nonatomic) NSString *m_openkfMsgMenuID;
@property (nonatomic) unsigned int m_bReceiveMessageSwitchStatus;
@property (retain, nonatomic) NSString *bypSessionId;
@property (nonatomic) BOOL m_bIsSubscribeMsg;
@property (nonatomic) BOOL m_bIsPreviewMsg;
@property (nonatomic) BOOL m_bIsAffBrandMsg;
@property (nonatomic) BOOL m_bIsAffBrandServiceMsg;
@property (nonatomic) unsigned int m_uiBizSceneType;
@property (nonatomic) BOOL m_bIsBrandServiceMsg;
@property (retain, nonatomic) WASourceWeappInfo *m_sourceWeappInfo;
@property (retain, nonatomic) WAScreenshotContextInfo *m_weappScreenshotContextInfo;
@property (retain, nonatomic) SourceImgInfo *m_sourceImgInfo;
@property (retain, nonatomic) NSString *m_weappSourceUsername;
@property (nonatomic) unsigned long long m_brandTLAffMsgId;
@property (retain, nonatomic) BrandAffMsgExtraData *m_brandTLAffMsgExtraData;
@property (retain, nonatomic) BSAffMsgExtraData *m_bsTLAffMsgExtraData;
@property (nonatomic) unsigned int m_brandTimelineMsgId;
@property (nonatomic) unsigned long long m_brandTimelineSequenceId;
@property (nonatomic) BOOL m_bIsExpand;
@property (nonatomic) unsigned int m_brandTimelineGroupId;
@property (nonatomic) int m_msgPredict;
@property (nonatomic) BOOL m_bIsTimelineBanned;
@property (nonatomic) BOOL m_bIsNotificationOnlyShowInSession;
@property (nonatomic) BOOL m_bIsExposed;
@property (nonatomic) BOOL m_brandIsValidExpose;
@property (nonatomic) BOOL m_bIsShowBigPic;
@property (nonatomic) long long m_bizFlag;
@property (nonatomic) long long m_bizMsgType;
@property (retain, nonatomic) NSData *m_byteBuffer;
@property (nonatomic) BOOL m_bBrandMainSessionMsgExposed;
@property (nonatomic) unsigned int m_brandMainSessionExposeCount;
@property (nonatomic) unsigned int m_brandMainSessionExposeTotalTime;
@property (nonatomic) unsigned int m_brandMainSessionExposeMinPos;
@property (copy, nonatomic) NSString *m_nsBrandRankSessionId;
@property (nonatomic) BOOL m_hasResorted;
@property (retain, nonatomic) NSString *m_nsResortBuffer;
@property (retain, nonatomic) MMReaderInfo *m_readerInfo;
@property (retain, nonatomic) NSString *m_nsRecCardId;
@property (retain, nonatomic) NSString *m_nsRecReason;
@property (nonatomic) unsigned int recRecycleCardType;
@property (nonatomic) unsigned int recCardMediaType;
@property (nonatomic) BOOL m_bShouldShowPriorityNotification;
@property (nonatomic) BOOL m_bIsClickPriorityNotificationInTL;
@property (nonatomic) unsigned int m_brandCanvasAdExpiredTimeSec;
@property (copy, nonatomic) NSString *m_nsBrandCanvasId;
@property (retain, nonatomic) BrandResortDigestInfo *m_brandDigestInfo;
@property (nonatomic) BOOL m_bIsShowFinderRedDot;
@property (nonatomic) unsigned int m_brandMassSendType;
@property (nonatomic) long long m_mergeCount;
@property (nonatomic) unsigned int m_uiMergeShowTime;
@property (nonatomic) unsigned int m_uiShareCardMessageStatus;
@property (nonatomic) long long m_notifyMsgBlockFlag;
@property (nonatomic) unsigned int m_silentFoldMsgReadStatus;
@property (nonatomic) unsigned long long m_uiPastedFromType;
@property (copy, nonatomic) NSString *m_inLenList;
@property (retain, nonatomic) NSString *m_nsSpecifiedChatName;
@property (nonatomic) unsigned int m_uiIsSenderStatus;
@property (retain, nonatomic) NSData *m_nsBypMsgExtInfo;
@property (weak, nonatomic) CMessageWrap *referHostMsg;
@property (retain, nonatomic) NSString *m_nsSignature;
@property (nonatomic) unsigned long long m_appMsgSourceType;
@property (retain, nonatomic) NSString *m_nsWatchUser;
@property (retain, nonatomic) ShareMsgObj *shareMsgObj;
@property (nonatomic) unsigned int m_showAIReply;
@property (copy, nonatomic) NSString *m_aiMsgWording;
@property (retain, nonatomic) MPPageIdentityInfo *m_mpPageIdentityInfo;
@property (nonatomic) unsigned int sendFailRetCode;
@property (retain, nonatomic) MPScreenshotArticleInfo *m_mpScreenshotArticleInfo;
@property (nonatomic) BOOL m_isAITalkingMsg;
@property (retain, nonatomic) NSString *systemMessageWording;
@property (retain, nonatomic) NSString *systemMessageActionWording;
@property (retain, nonatomic) CMessageWrap *referingMessageWrap;
@property (retain, nonatomic) MMReferPartialInfo *referPartialInfo;
@property (weak, nonatomic) CMessageWrap *m_refMessageWrap;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)getMessageListStatusImage:(unsigned int)a0;
+ (BOOL)IsVoiceUseCdnDownload;
+ (id)genFileAppMsgWithFileName:(id)a0 filePath:(id)a1 fileData:(id)a2;
+ (void)GetPathOfAppDir:(id)a0 retStrPath:(id *)a1;
+ (void)GetPathOfAppImgCacheDir:(id)a0 retStrPath:(id *)a1;
+ (void)GetPathOfAppData:(id)a0 LocalID:(unsigned int)a1 FileExt:(id)a2 retStrPath:(id *)a3;
+ (void)GetPathOfAppDataByUserName:(id)a0 andMessageWrap:(id)a1 andAttachId:(id)a2 andAttachFileExt:(id)a3 retStrPath:(id *)a4;
+ (void)GetPathOfAppDataByUserName:(id)a0 andMessageWrap:(id)a1 retStrPath:(id *)a2;
+ (void)GetPathOfAppDataTemp:(id)a0 LocalID:(unsigned int)a1 AttachId:(id)a2 retStrPath:(id *)a3;
+ (void)GetPathOfAppDataTemp:(id)a0 LocalID:(unsigned int)a1 retStrPath:(id *)a2;
+ (void)GetPathOfMaskedAppThumb:(id)a0 LocalID:(unsigned int)a1 retStrPath:(id *)a2;
+ (void)GetPathOfAppThumb:(id)a0 LocalID:(unsigned int)a1 retStrPath:(id *)a2;
+ (void)GetPathOfAppRemindAttach:(id)a0 retStrPath:(id *)a1;
+ (id)localBubbleMessageWrapToUsername:(id)a0 withWordingMsg:(id)a1 isVideo:(BOOL)a2 roomID:(unsigned long long)a3 roomKey:(unsigned long long)a4 inviteID:(unsigned int)a5 inviteID64:(unsigned long long)a6 duration:(unsigned int)a7 isCaller:(BOOL)a8 needRedDot:(BOOL)a9 isIlink:(BOOL)a10 callerMemberID:(int)a11 calleeMemberID:(int)a12;
+ (id)localBubbleMessageWrapToUsername:(id)a0 withWordingType:(int)a1 isVideo:(BOOL)a2 roomID:(unsigned long long)a3 roomKey:(unsigned long long)a4 inviteID:(unsigned int)a5 inviteID64:(unsigned long long)a6 duration:(unsigned int)a7 isCaller:(BOOL)a8 needRedDot:(BOOL)a9 isIlink:(BOOL)a10 callerMemberID:(unsigned int)a11 calleeMemberID:(unsigned int)a12;
+ (id)localBubbleMessageWrapToUsername:(id)a0 withWordingId:(int)a1 isVideo:(BOOL)a2 roomID:(unsigned long long)a3 roomKey:(unsigned long long)a4 inviteID:(unsigned int)a5 inviteID64:(unsigned long long)a6 duration:(unsigned int)a7 isCaller:(BOOL)a8 isIlink:(BOOL)a9 callerMemberID:(int)a10 calleeMemberID:(int)a11;
+ (void)initialize;
+ (BOOL)shouldUseWeappChatToolSubpackageMode:(id)a0 weappSourceUsername:(id)a1;
+ (BOOL)shouldUseWeappChatToolAllPageMode:(id)a0 weappSourceUsername:(id)a1;
+ (id)FormMessageWrapFromAddMsg:(id)a0;
+ (void)clearLocalImage:(id)a0;
+ (void)clearLocalMaskedThumbImage:(id)a0;
+ (BOOL)SaveMsgThumbWithMsgWrap:(id)a0;
+ (BOOL)SaveMesImg:(id)a0 MsgWrap:(id)a1;
+ (BOOL)IsRecordOrNoteMsg:(id)a0;
+ (BOOL)IsFinderFeedMsgEnable:(id)a0;
+ (BOOL)IsFinderLongVideoMsgEnable:(id)a0;
+ (BOOL)IsFinderTopicMsgEnable:(id)a0;
+ (BOOL)IsFinderCollectionMsgEnable:(id)a0;
+ (BOOL)IsFinderMsgEnable:(id)a0;
+ (BOOL)IsFinderLiveMsgEnable:(id)a0;
+ (BOOL)IsFinderLiveConnectInviteMsgEnable:(id)a0;
+ (BOOL)IsFinderNameCardEnable:(id)a0;
+ (BOOL)IsFinderColumnEnable:(id)a0;
+ (BOOL)isSenderFromMsgWrap:(id)a0;
+ (id)getUserNameFromMsgWrap:(id)a0;
+ (id)getJpgPathOfMsgHdOrMiddleImg:(id)a0;
+ (id)getPathOfMsgVcodec2Img:(id)a0;
+ (id)getPathOfMsgVcodec2HDImg:(id)a0;
+ (id)getPathOfRawMiddleImage:(id)a0;
+ (id)getMsgHDImg:(id)a0;
+ (BOOL)MsgHDImgExist:(id)a0;
+ (id)getJpgPathOfMsgHDImgV1:(id)a0;
+ (id)getJpgPathOfMsgHDImgV2:(id)a0;
+ (id)getJpgPathOfMsgHDImg:(id)a0;
+ (id)getPathOfMsgWxAmImgByChatName:(id)a0;
+ (id)getPathOfMsgWxAmImgByChatName:(id)a0 localId:(unsigned int)a1;
+ (id)getPathOfMsgWxAmImg:(id)a0;
+ (BOOL)MsgMiddleImgExist:(id)a0;
+ (BOOL)isVcodec2Img:(id)a0;
+ (id)getJpgPathOfMsgMiddleImg:(id)a0;
+ (id)getMsgHDImgData:(id)a0;
+ (id)GetPathOfMesHDImg:(id)a0 LocalID:(unsigned int)a1 DocPath:(id)a2;
+ (id)GetPathOfMesHDImgV2:(id)a0 LocalID:(unsigned int)a1 DocPath:(id)a2;
+ (id)GetPathOfImgeMsgLiveVideo:(id)a0 LocalID:(unsigned int)a1;
+ (id)GetPathOfImgeMsgHDLiveVideo:(id)a0 LocalID:(unsigned int)a1;
+ (id)GetPathOfImgeMsgHDLiveVideoV2:(id)a0 LocalID:(unsigned int)a1;
+ (id)internalGetPathOfMsgHdImg:(id)a0;
+ (id)getPathOfMsgImg:(id)a0;
+ (id)getPathOfAudio:(id)a0;
+ (id)getMsgHdOrMiddleImg:(id)a0;
+ (id)getMsgHdOrMiddleImgJpgData:(id)a0;
+ (id)getMsgHdOrMiddleImgData:(id)a0;
+ (id)getMsgHdOrMiddleImgData:(id)a0 canUseHeif:(BOOL)a1;
+ (id)getMsgMiddleImg:(id)a0;
+ (id)getMsgMiddleImgJpgData:(id)a0;
+ (id)getMsgMiddleImgData:(id)a0;
+ (id)getMsgMiddleImgData:(id)a0 canUseHeif:(BOOL)a1;
+ (id)getPathOfMsgImgThumb:(id)a0;
+ (id)getPathOfHdOrMiddleImgForSender:(id)a0;
+ (id)getPathOfMiddleImgForSender:(id)a0;
+ (id)getPathOfMessageImageCache;
+ (id)getPathOfMaskedMsgImgThumb:(id)a0;
+ (id)getPathOfMaskedVideoMsgImgThumb:(id)a0;
+ (id)GetPathOfSquareMesImgThumb:(id)a0;
+ (id)GetPathOfMaskedSquareMesImgThumbDir:(id)a0;
+ (id)GetPathOfMaskedSquareMesImgThumbDir;
+ (id)getPathOfVideoMsgImgThumb:(id)a0;
+ (id)getThumbnailInMessage:(id)a0;
+ (id)getMsgImgThumb:(id)a0;
+ (id)getMaskedMsgImgThumb:(id)a0;
+ (id)getMaskedVideoMsgImgThumb:(id)a0;
+ (id)GetPathOfMesVideoWithMessageWrap:(id)a0;
+ (id)GetPathOfRawOrCompressVideo:(id)a0;
+ (id)GetPathOfRawVideo:(id)a0 LocalID:(unsigned int)a1 DocPath:(id)a2;
+ (id)GetPathOfRawVideoV2:(id)a0 LocalID:(unsigned int)a1 DocPath:(id)a2;
+ (id)GetPathOfMsgRawVideoV1:(id)a0;
+ (id)GetPathOfMsgRawVideoV2:(id)a0;
+ (id)GetPathOfRawVideoWithMessageWrap:(id)a0;
+ (id)GetTempPathOfRawVideoWithMessageWrap:(id)a0;
+ (id)GetTempPathOfMesVideoWithMessageWrap:(id)a0;
+ (id)GetCdnDownloadPathOfMsgThumb:(id)a0;
+ (id)GetPathOfAppData:(id)a0;
+ (id)createMaskedThumbImageForMessageWrap:(id)a0;
+ (BOOL)isPreViewMsg;
+ (id)FTSMessageSupportTypes;

- (BOOL)isFinderTopicLikeShareType;
- (id)usedFinderTopicShareItem;
- (BOOL)isFinderPOIRelatedType;
- (id)finerSharePOIRelatedItem;
- (BOOL)isSetRedEnvelopeCoverMsg;
- (BOOL)isScheduleMessageMsg;
- (BOOL)msgCanBeRefered;
- (id)msgReferSummary;
- (id)msgReferSummaryAndReplace:(BOOL)a0;
- (id)genReferIconWithName:(id)a0 useCustomBkg:(BOOL)a1;
- (id)msgReferSenderDisplayName;
- (id)msgReferSenderDisplayName:(BOOL)a0;
- (BOOL)hideDisplayNameInRefer;
- (BOOL)isFakeReferHostMsg;
- (BOOL)isFakeReferMsg;
- (BOOL)hasRealReferingMessageWrap;
- (id)generateReplySummaryWithoutDisplayName;
- (id)generateReplySummary:(id)a0;
- (id)generateReplySummary:(id)a0 useContactDisplayName:(BOOL)a1;
- (id)generateReplySummaryAndReplace:(id)a0 useCustomBkg:(BOOL)a1;
- (id)generateReplySummaryAndReplace:(id)a0 useCustomBkg:(BOOL)a1 useContactDisplayName:(BOOL)a2;
- (long long)compareMessageLocalIDDescending:(id)a0;
- (long long)compareMessageAscending:(id)a0;
- (BOOL)isPriorToMsg:(id)a0;
- (unsigned long long)yoCount;
- (int)yoType;
- (id)voipBubbleMsg;
- (id)voipMessageHistory;
- (BOOL)canUseCdnDownload;
- (id)GetCdnDownloadPathOfVideo;
- (id)GetCdnDownloadThumbPathOfVideo;
- (BOOL)isAd;
- (BOOL)isRawVideo;
- (BOOL)isRawVideoPreviewing;
- (id)getRawMediaIdentifier;
- (BOOL)canPlayVideo:(id)a0;
- (void)ayncCompress3rdVideoWithProgress:(id /* block */)a0 completion:(id /* block */)a1;
- (void)compressVideoWithMMAsset:(id)a0 AVAsset:(id)a1 assetURL:(id)a2 progressCallback:(id /* block */)a3 completion:(id /* block */)a4;
- (void)asyncCompressVideoWithProgressCallback:(id /* block */)a0 completion:(id /* block */)a1;
- (id /* block */)getVideoExportCallbackBlockWithAsset:(id)a0 URL:(id)a1 noCompress:(BOOL)a2 completion:(id /* block */)a3;
- (unsigned long long)getPickerSceneFromOptionObj;
- (BOOL)isPreloadVideoTask;
- (BOOL)canBeginPreload;
- (BOOL)needCompressToH264;
- (void)compressToH264WithResPath:(id)a0 CompletionSuccess:(id /* block */)a1 Fail:(id /* block */)a2;
- (id)getMediaWrapIdentifier;
- (id)getMediaWrapUrl;
- (id)getTempVideoPath;
- (id)getFormatVideoPath;
- (id)getThumbImagePath;
- (id)getHDThumbImagePath;
- (id)getRawHDThumbImagePath;
- (id)getRawFormatPath;
- (id)getRawTempPath;
- (BOOL)isWithHistoryRecord;
- (BOOL)hasDownloadHistoryRecord;
- (BOOL)canRevokeHistoryRecord;
- (BOOL)hasRevokedHistoryRecord;
- (BOOL)doRevokeHistoryRecord;
- (BOOL)isNewInviteesMsg;
- (id)getNodeBtnList;
- (BOOL)isLiveImage;
- (id)getImgWxaInfo;
- (id)getImgSourceInfo;
- (id)getImgMpInfo;
- (id)GetLivePhotoVideoPath;
- (id)GetLivePhotoVideoTempPath;
- (id)GetLivePhotoHDVideoPath;
- (id)GetLivePhotoHDVideoTempPath;
- (id)GetAppAttachmentPath;
- (id)nativeUrl;
- (BOOL)bIsAppUrlTypeWithCanvas;
- (BOOL)bIsAppUrlTypeFromWSVideoFlow;
- (id)convertToFinderMessageWrap;
- (BOOL)bIsFinderFeedShareContent;
- (BOOL)bIsFinderLongVideoShareContent;
- (BOOL)bIsFinderTopicShareContent;
- (BOOL)bIsFinderCollectionShareContent;
- (BOOL)bIsFinderShareContent;
- (BOOL)bIsFInderLiveContent;
- (BOOL)bIsFinderProductShareContent;
- (BOOL)bIsFinderOrderShareContent;
- (BOOL)bIsFinderContentColumnContent;
- (BOOL)bIsFinderShopWindowShare;
- (BOOL)bIsLiteAppShare;
- (BOOL)withLiteAppSource;
- (int)getLiteAppSource;
- (id)getLiteAppSourceTitle;
- (BOOL)isAAMessageForSessionStick;
- (BOOL)isForbitJumpUrl;
- (BOOL)isExclusiveHongBaoMsg;
- (BOOL)isExclusiveHbMessageForMe;
- (BOOL)isGroupTransferMessageForMe;
- (BOOL)isBrandAttributedNotifyMsg;
- (BOOL)isBrandAttributedNotifyMsgInMsgContentBeforeChangeForDisplay;
- (BOOL)isBrandAttributedNotifyUIMsgType;
- (BOOL)isBrandAttributedNotifyFromUserEqualToBrandTemplateMsgHolderName;
- (BOOL)isCanGetNotifyMsgNodeFromMsgSourceUIMsgType;
- (BOOL)shouldShowAsSystemMessage;
- (id)getContentForShowAsSystemMessage;
- (id)wishingString;
- (BOOL)isReferMsgType;
- (void)updateForReferMsg:(id)a0 replyContent:(id)a1;
- (id)generateMsgReferXML;
- (id)changeForPlainTextMsg;
- (BOOL)IsTextFold;
- (BOOL)IsMsgBubbleForbidForward;
- (BOOL)IsMsgBubbleForbidCopy;
- (BOOL)IsMsgBubbleForbidAll;
- (long long)GetMsgPreviewOpType;
- (struct _NSRange { unsigned long long x0; unsigned long long x1; })getMsgSelectRange;
- (BOOL)canSelectAll;
- (id)getMsgTipUrl;
- (BOOL)UpdateArgsMsgSource:(id)a0;
- (long long)getTextMsgInterceptType;
- (BOOL)forbidDetailPage;
- (BOOL)forbidSubPageWithMd5:(id)a0;
- (BOOL)forbidContentDisplay;
- (BOOL)isPredownloadAndNotPreview:(id)a0;
- (id)init;
- (id)initWithMsgType:(long long)a0;
- (id)initWithMsgType:(long long)a0 nsFromUsr:(id)a1;
- (BOOL)shouldUseWeappChatToolSubpackageMode:(id)a0;
- (BOOL)shouldUseWeappChatToolAllPageMode:(id)a0;
- (void)updateEasterEggRandomSeedIfNeeded;
- (void)copyToMsg:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)methodSignatureForSelector:(SEL)a0;
- (void)forwardInvocation:(id)a0;
- (id)forwardingTargetForSelector:(SEL)a0;
- (void)ChangeForChatRoom;
- (void)ChangeForMsgSource;
- (void)changeForSecNode:(struct XmlReaderNode_t { int x0; char *x1; struct XmlReaderNode_t *x2; struct XmlReaderNode_t *x3; struct XmlReaderNode_t *x4; struct XmlReaderNode_t **x5; struct XmlReaderAttr_t *x6; struct XmlReaderAttr_t **x7; int x8; } *)a0;
- (void)ChangeForShareCardMessageFromForwardNode:(struct XmlReaderNode_t { int x0; char *x1; struct XmlReaderNode_t *x2; struct XmlReaderNode_t *x3; struct XmlReaderNode_t *x4; struct XmlReaderNode_t **x5; struct XmlReaderAttr_t *x6; struct XmlReaderAttr_t **x7; int x8; } *)a0;
- (void)ChangeForStrongNotificationNode:(struct XmlReaderNode_t { int x0; char *x1; struct XmlReaderNode_t *x2; struct XmlReaderNode_t *x3; struct XmlReaderNode_t *x4; struct XmlReaderNode_t **x5; struct XmlReaderAttr_t *x6; struct XmlReaderAttr_t **x7; int x8; } *)a0;
- (void)ChangeForPushContent;
- (void)fillMsgSourceFromContact:(id)a0 isFromTempSession:(BOOL)a1;
- (void)ChangeForSimpleMsgInfo;
- (void)UpdateContent:(id)a0;
- (void)ChangeForDisplay;
- (void)UpdateMsgSource;
- (id)getSecContent;
- (void)AddTagToMsgSource:(id)a0 value:(id)a1;
- (void)AddOrModifyTagInMsgSource:(id)a0 value:(id)a1;
- (void)AddOrModifyTagInMsgSource:(id)a0 value:(id)a1 removeOnEmpty:(BOOL)a2;
- (id)GetChatName;
- (BOOL)IsMassSendMessage;
- (BOOL)IsChatRoomMessage;
- (BOOL)IsBypassMessage;
- (BOOL)IsBypFinderPrivateMessage;
- (BOOL)IsBypW1wPersonalMessage;
- (BOOL)IsTextMsg;
- (BOOL)IsMsgNeedForbidUrlParse;
- (BOOL)IsAppearAsTextMsg;
- (BOOL)isAppMsgAppearAsTextMsg;
- (BOOL)IsImgMsg;
- (BOOL)IsVoiceMsg;
- (BOOL)IsSimpleVideoMsg;
- (BOOL)IsVideoMsg;
- (BOOL)IsPureVideoMsg;
- (BOOL)isWeiShiVideo;
- (BOOL)IsGameVideo;
- (BOOL)IsBrandMPVideo;
- (BOOL)IsGetOnNeeded;
- (BOOL)IsAppMessage;
- (BOOL)IsInviteShareMessage;
- (BOOL)isNativeHongBaoMsg;
- (BOOL)IsGroupNoticeMsg;
- (BOOL)IsFileMsg;
- (BOOL)IsFileUploadingMsg;
- (BOOL)isMerge;
- (BOOL)IsSendBySendMsg;
- (BOOL)IsUrlMessage;
- (BOOL)IsRecordMsg;
- (BOOL)IsSameMsg:(id)a0;
- (BOOL)IsSameMsgWithFullCheck:(id)a0;
- (BOOL)IsBrandShareCardMsg;
- (id)getNativeAppSourceName;
- (id)getNativeAppSourceIconUrl;
- (id)getCurToUsername;
- (id)combineChatNameWithLocalId;
- (id)GetMsgClientMsgID;
- (id)GetDisplayContent;
- (BOOL)genImageFromMMAssetAndNotify:(id)a0;
- (BOOL)genImageFromMMAssetAndNotify:(id)a0 threshold:(id)a1;
- (void)reportAssetExifWithImageSize:(struct CGSize { double x0; double x1; })a0 dataSize:(unsigned long long)a1;
- (void)genMiddleImg:(id)a0 originImgData:(id)a1 isSaveOK:(BOOL)a2 delegate:(id)a3;
- (unsigned int)getSessionTime;
- (BOOL)isTemplateBrandMsg;
- (BOOL)IsNeedChatExt;
- (id)parseMsgClusterType;
- (id)parseMsgForwardType;
- (BOOL)isTransferMessageForNewWCPayBizExt;
- (BOOL)isHongBaoMessageNeedDownloadShowResoruce;
- (BOOL)isHongBaoMessageNeedDownloadEmoticon;
- (BOOL)isHongBaoMessageNeedDownloadAudio;
- (BOOL)isHongBaoMessageForNewWCPayBizExt;
- (BOOL)isAAMessageForNewWCPayBizExt;
- (BOOL)isOverseaHBMessageForNewWCPayBizExt;
- (BOOL)isPocketMoneyForNewWCPayBizExt;
- (BOOL)isThirdC2CMessageForNewWCPayBizExt;
- (long long)getC2CTransactionType;
- (id)getC2CTransactionId;
- (BOOL)isNewWCPayBizExtMsg:(long long *)a0;
- (id)getWCPayMsgExtBizIdWithType:(unsigned int)a0;
- (BOOL)IsNeedAddWCPayMsgBizExt;
- (unsigned int)getWCPayMsgInvalidTime;
- (id)getWCPayMsgExtBizId;
- (void)parseWCPayInfoItemIfNeed;
- (void)parseWCPayExtensionInfoIfNeed;
- (id)keyDescription;
- (BOOL)isShowAppBottomButton;
- (BOOL)isShowAppMessageBlockButton;
- (BOOL)IsSupportAtMe;
- (BOOL)IsAtMe;
- (BOOL)IsAtAll;
- (BOOL)IsRoomAnnouncement;
- (BOOL)IsNewInvitation;
- (BOOL)IsUpdatableMsgSubscribeMsg;
- (BOOL)IsNewInvitationApprove;
- (BOOL)isSentOK;
- (BOOL)isSpecialAttentionMessage;
- (BOOL)isMsgCanFindByServerId;
- (BOOL)canUseContineUpload;
- (id)messageFTSTextForDisplay;
- (id)messageFTSText;
- (id)nonCategorymessageFTSText;
- (id)getMessageFTSText;
- (BOOL)canEnterBrandTimeline;
- (BOOL)canEnterBrandTimelineNotification;
- (BOOL)canReadWrapIntoBrandTimeline;
- (long long)getBizNotifyMsgBlockType;
- (BOOL)showBrandFusionSummary;
- (BOOL)canEnterBrandServiceTimeline;
- (BOOL)canEnterBrandServiceTimelineNotification;
- (BOOL)canEnterBrandServiceTemplateMsgPage;
- (BOOL)canEnterBrandServicePrivateNotiMsg;
- (BOOL)isBizRecommendMsg;
- (BOOL)isBizRecommendNativeMsg;
- (BOOL)isBizRecommendCanvasMsg;
- (BOOL)isBizAdCanvasMsg;
- (BOOL)isBizAffRecommendMsg;
- (BOOL)isBizSysMsg;
- (BOOL)isEmbedExcerptMsg;
- (id)getReplyMessage;
- (id)generateExtCommonInfoXML;
- (void)parseExtCommonInfoXMLNode:(struct XmlReaderNode_t { int x0; char *x1; struct XmlReaderNode_t *x2; struct XmlReaderNode_t *x3; struct XmlReaderNode_t *x4; struct XmlReaderNode_t **x5; struct XmlReaderAttr_t *x6; struct XmlReaderAttr_t **x7; int x8; } *)a0;
- (void).cxx_destruct;

@end
