@class WCColorProxy, UIView, ContactsViewTagListCollectionView, NSString, NSMutableDictionary, UIButton, NSMutableArray, UITextField, WCSTokenPickLogic, MMTableView;
@protocol ContactsSearchControllerDelegate;

@interface ContactsSearchController : WCSearchViewController <ContactsViewTagListCollectionViewDelegate, UITableViewDelegate, UITableViewDataSource, MMPageSheetAdapterDelegate, GeneralContactsSearchPanelSearchingResultProtocol, MMUIViewControllerOverrideOrientationMaskProtocol>

@property (retain, nonatomic) ContactsViewTagListCollectionView *tagView;
@property (retain, nonatomic) NSMutableArray *tagList;
@property (retain, nonatomic) MMTableView *tableView;
@property (retain, nonatomic) UIView *bottomBar;
@property (retain, nonatomic) UIButton *doneButton;
@property (retain, nonatomic) NSMutableArray *arrSectionKeys;
@property (retain, nonatomic) NSMutableDictionary *dicSectionTitles;
@property (retain, nonatomic) NSMutableDictionary *dicSectionResults;
@property (nonatomic) unsigned int expandBitSet;
@property (retain, nonatomic) NSMutableArray *arrFilteredObject;
@property (weak, nonatomic) id<ContactsSearchControllerDelegate> delegate;
@property (retain, nonatomic) WCColorProxy *colorProxy;
@property (nonatomic, setter=SetIsShowAllTags:) BOOL isShowAllTags;
@property (nonatomic) BOOL bShouldFilterSearchResults;
@property (nonatomic) BOOL bDisplaySectionResults;
@property (nonatomic) BOOL bForbidMultiSelectChange;
@property (nonatomic) BOOL bForceHiddenBottomBar;
@property (nonatomic) BOOL m_bMultiSelect;
@property (nonatomic) unsigned long long selectedCount;
@property (retain, nonatomic) UIButton *multiSelectButton;
@property (nonatomic) unsigned long long overrideOrientationMask;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) UITextField *m_SearchTextField;
@property (retain, nonatomic) WCSTokenPickLogic *tokenPickLogic;

- (void)viewDidLoad;
- (unsigned long long)supportedInterfaceOrientations;
- (double)getContentViewY;
- (void)viewDidLayoutSubviews;
- (void)viewDidBePopedOrDismissed:(BOOL)a0;
- (void)onNavigationCancelItemClick;
- (BOOL)DismissMyselfAnimated:(BOOL)a0 completion:(id /* block */)a1;
- (BOOL)shouldInteractivePop;
- (void)initData;
- (void)initView;
- (void)initTagView;
- (void)initTableView;
- (void)initBottomBar;
- (void)onTextFieldChanged:(id)a0;
- (void)cancelSearch;
- (void)doSearch;
- (void)updateTagView;
- (BOOL)isSearchMultiKey;
- (void)onSwitchMultiSelect;
- (void)onFinishMultiSelect;
- (void)updateBottomBar;
- (void)updateBottomDoneButton;
- (void)keyboardWillShow:(id)a0;
- (void)keyboardWillHide:(id)a0;
- (void)onKeyboardNotification:(id)a0;
- (long long)numberofRowsInSection:(long long)a0;
- (id)getObjectFor:(unsigned long long)a0;
- (id)getObjectForIndexPath:(id)a0;
- (unsigned int)getObjectRow:(id)a0;
- (void)setFilteredObjects:(id)a0;
- (unsigned long long)getObjectCount;
- (void)addFilteredObject:(id)a0;
- (void)clearFilteredObjects;
- (void)tryFilterSearchResult;
- (id)getFilteredObjects;
- (void)setFilterdSectionKeys:(id)a0;
- (void)setSectionTitleMaps:(id)a0;
- (void)setFilterdSectionResults:(id)a0;
- (void)prepareRefreshing;
- (void)prepareRefreshingAnimated:(BOOL)a0;
- (BOOL)isMoreCellAtIndexPath:(id)a0;
- (BOOL)isCollapseAtSection:(long long)a0;
- (id)getMoreCellDescriptionAtSection:(long long)a0;
- (id)getMoreCellImageAtSection:(long long)a0;
- (void)clickMoreCellAtIndexPath:(id)a0;
- (unsigned long long)getMoreCellStatusAtSection:(long long)a0;
- (id)getSectionKeyAtSection:(long long)a0;
- (void)setExpandStatus:(BOOL)a0 forSection:(long long)a1;
- (BOOL)isExpandingForSection:(long long)a0;
- (BOOL)isJumpable:(id)a0;
- (BOOL)shouldCollaseOrExpandSearchResultAtIndex:(long long)a0;
- (id)getSearchResultTable;
- (id)getSearchText;
- (void)setSearchText:(id)a0;
- (BOOL)isM_bMultiSelect;
- (long long)numberOfSectionsInTableView:(id)a0;
- (double)tableView:(id)a0 heightForHeaderInSection:(long long)a1;
- (id)tableView:(id)a0 viewForHeaderInSection:(long long)a1;
- (id)tableView:(id)a0 titleForHeaderInSection:(long long)a1;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (double)tableView:(id)a0 heightForRowAtIndexPath:(id)a1;
- (void)tableView:(id)a0 didSelectRowAtIndexPath:(id)a1;
- (void)startSearchFrom:(id)a0 searchBar:(id)a1;
- (id)getViewController;
- (void)didSelectedOrCancelTagButtonWithTagId:(unsigned int)a0 tagName:(id)a1 isSelected:(BOOL)a2;
- (void)pageSheetDidClose:(id)a0 closeType:(long long)a1;
- (void)handleResultTokenPick:(id)a0;
- (void)onSelectContact:(id)a0 forIndexPath:(id)a1;
- (BOOL)isMultiSelectContactSection:(long long)a0;
- (void)tryDeselectOtherContactForIndexPath:(id)a0;
- (void)onDeselectContact:(id)a0 forIndexPath:(id)a1;
- (void)pickDataSelected:(id)a0 indexPath:(id)a1;
- (void)pickDataDeSelected:(id)a0 indexPath:(id)a1;
- (void)asyncRecommend;
- (void)refreshPickDataRecommendSection:(long long)a0 added:(BOOL)a1 deleted:(BOOL)a2;
- (void)removeTokenSelectedContact:(id)a0;
- (void)removePickDataForUsername:(id)a0;
- (void)tryReorderContactAtSection:(long long)a0;
- (void).cxx_destruct;

@end
