@class MemoryMappedKV, NSString, NSMutableDictionary, NSData, MMAutoAuthWrap;

@interface CSetting : NSObject <NSCoding> {
    NSMutableDictionary *m_dicSetting;
    MemoryMappedKV *mmkv;
}

@property (retain, nonatomic) NSData *m_dtOldAutoAuthKey;
@property (nonatomic) unsigned int m_version;
@property (nonatomic) unsigned int m_uiBindQQUin;
@property (nonatomic) unsigned int m_uiStatus;
@property (nonatomic) BOOL m_bNewMsgSound;
@property (nonatomic) BOOL m_bNewMsgVibration;
@property (nonatomic) BOOL ringToneSoundOpen;
@property (nonatomic) unsigned int m_uiLastTimeOfNotifyOpenPush;
@property (nonatomic) unsigned int m_uiCryptUin;
@property (nonatomic) unsigned int m_uiLastInitVersion;
@property (retain, nonatomic) NSString *m_nsInitBuffer;
@property (nonatomic) unsigned int m_uiInitStatus;
@property (nonatomic) BOOL m_bAuthAnotherPlace;
@property (nonatomic) unsigned int m_uiPushMailSwitchStatus;
@property (retain, nonatomic) NSString *m_nsPushmailFolderUrl;
@property (retain, nonatomic) NSData *m_dtSyncBuffer;
@property (nonatomic) unsigned int m_uiSex;
@property (retain, nonatomic) NSString *m_nsCountry;
@property (retain, nonatomic) NSString *m_nsProvince;
@property (retain, nonatomic) NSString *m_nsCity;
@property (retain, nonatomic) NSString *m_nsHDHeadImgMD5;
@property (retain, nonatomic) NSString *m_nsHDImgStatus;
@property (nonatomic) unsigned int m_uiPluginInstallStatus;
@property (nonatomic) unsigned int m_uiSelfShowType;
@property (nonatomic) unsigned int m_uiFacebookFlag;
@property (retain, nonatomic) NSString *m_nsFacebookID;
@property (retain, nonatomic) NSString *m_nsFacebookName;
@property (retain, nonatomic) NSString *m_nsFacebookToken;
@property (nonatomic) unsigned int m_uiPluginSwitch;
@property (retain, nonatomic) NSString *m_nsAuthKey;
@property (retain, nonatomic) NSString *m_nsWCBGImgObjectID;
@property (nonatomic) int m_iWCFlag;
@property (nonatomic) int m_iWCFlagExt;
@property (nonatomic) unsigned int m_iWCRecentHours;
@property (retain, nonatomic) NSString *m_pcWCBGImgID;
@property (retain, nonatomic) NSData *m_dtA2Key;
@property (retain, nonatomic) NSData *m_dtA2KeyNew;
@property (retain, nonatomic) NSString *m_nsLastUUID;
@property (retain, nonatomic) NSData *m_dtNewInitTempBuffer;
@property (retain, nonatomic) NSData *m_dtNewInitTempMaxBuffer;
@property (nonatomic) BOOL m_useInitContact;
@property (retain, nonatomic) NSString *m_nsMsgPushSound;
@property (nonatomic) unsigned int m_patternVersion;
@property (nonatomic) unsigned int m_patternLockStatus;
@property (retain, nonatomic) NSData *m_patternInfoSign;
@property (nonatomic) unsigned int m_walletType;
@property (nonatomic) unsigned int m_walletRegion;
@property (nonatomic) BOOL m_remindMMDBRestore;
@property (retain, nonatomic) NSString *m_nsUsrName;
@property (retain, nonatomic) NSString *m_nsAliasName;
@property (retain, nonatomic) NSString *m_nsNickName;
@property (retain, nonatomic) NSString *m_nsSignature;
@property (retain, nonatomic) NSString *m_nsEmail;
@property (retain, nonatomic) NSString *m_nsMobile;
@property (nonatomic) BOOL m_bNeedClearMailPluginMsg;
@property (retain, nonatomic) NSString *m_nsBindXmail;
@property (nonatomic) unsigned int userExtInfoStatus;
@property (nonatomic) unsigned long long m_uiExtStatus;
@property (nonatomic) unsigned long long extStatus2;
@property (nonatomic) unsigned long long m_uiPaySettingStatus;
@property (nonatomic) int m_iDiffTime;
@property (nonatomic) unsigned int m_uLastSystemUptime;
@property (nonatomic) BOOL m_bHasCheckTimeChange;
@property (nonatomic) unsigned int lqtVersion;
@property (nonatomic) unsigned int m_uStartTime;
@property (nonatomic) unsigned long long lastSvrTime;
@property (nonatomic) unsigned int m_uSnsWeishiShowed;
@property (nonatomic) unsigned int m_uSendMsgActionFlag;
@property (retain, nonatomic) MMAutoAuthWrap *m_oAutoAuthWrap;
@property (readonly, nonatomic) NSData *m_dtAutoAuthKey;
@property (readonly, nonatomic) NSData *m_dtServerId;
@property (retain, nonatomic) NSString *m_patSuffix;
@property (nonatomic) unsigned int m_patSuffixVersion;
@property (nonatomic) unsigned long long m_xAgreementInfoFuncsSwitch;
@property (nonatomic) unsigned long long m_xAgreementInfoFuncsUserChoiceSwitch;
@property (nonatomic) unsigned int m_teenagerModeFinderSetting;
@property (nonatomic) unsigned int m_teenagerModeBizAcctSetting;
@property (nonatomic) unsigned int m_teenagerModeMiniProgramSetting;
@property (nonatomic) unsigned int m_teenagerModeEmotionSetting;
@property (nonatomic) unsigned long long m_finderSetting;
@property (nonatomic) unsigned long long discoveryPageCtrlFlag;
@property (retain, nonatomic) NSString *m_textStatusID;
@property (retain, nonatomic) NSString *m_textStatusExtInfo;
@property (retain, nonatomic) NSString *m_textStatusData;
@property (nonatomic) unsigned long long systemAuthLocation;
@property (nonatomic) unsigned long long systemAuthAddressBook;
@property (nonatomic) unsigned long long systemAuthPhoto;
@property (nonatomic) unsigned long long systemAuthCamera;
@property (nonatomic) unsigned long long systemAuthMicrophone;
@property (nonatomic) unsigned long long systemAuthBluetooth;
@property (nonatomic) unsigned long long systemAuthSports;
@property (nonatomic) unsigned long long systemAuthImageLocationData;
@property (nonatomic) unsigned long long systemAuthImageContentData;
@property (nonatomic) unsigned int ringType;
@property (nonatomic) unsigned long long ringObjectId;
@property (retain, nonatomic) NSString *ringNonceId;
@property (nonatomic) unsigned int ringMusicSid;
@property (nonatomic) double ringStartTime;
@property (nonatomic) double ringEndTime;
@property (retain, nonatomic) NSString *m_salt;
@property (nonatomic) unsigned int m_SMCryptoFlag;
@property (retain, nonatomic) NSString *savedHelloMsg;
@property (nonatomic) BOOL m_bIsRunningAsBakDevice;
@property (retain, nonatomic) NSString *translateLanguage;
@property (nonatomic) unsigned int notifyBannerDisplayContentSetting;
@property (nonatomic) unsigned int apnsBannerDisplayContentSetting;
@property (nonatomic) unsigned long long clientGrayFlag;
@property (retain, nonatomic) NSData *passkeyCredentialID;
@property (retain, nonatomic) NSData *serviceAgreementInfo;
@property (retain, nonatomic) NSString *savedHelloMsgImageUrl;
@property (retain, nonatomic) NSString *savedHelloMsgAesKey;
@property (nonatomic) unsigned long long hearingAidModeLocal;
@property (nonatomic) unsigned long long hearingAidModeOld;
@property (nonatomic) unsigned long long hearingAidModeRemote;

+ (BOOL)resolveInstanceMethod:(SEL)a0;
+ (id)mmkvPathWithUsername:(id)a0;

- (void)setClientGrayFlag:(unsigned long long)a0;
- (void)setApnsBannerDisplayContentSetting:(unsigned int)a0;
- (void)setNotifyBannerDisplayContentSetting:(unsigned int)a0;
- (void)setTranslateLanguage:(id)a0;
- (void)setSavedHelloMsgAesKey:(id)a0;
- (void)setSavedHelloMsgImageUrl:(id)a0;
- (void)setSavedHelloMsg:(id)a0;
- (void)setDiscoveryPageCtrlFlag:(unsigned long long)a0;
- (void)setRingEndTime:(double)a0;
- (void)setRingStartTime:(double)a0;
- (void)setRingNonceId:(id)a0;
- (void)setRingObjectId:(unsigned long long)a0;
- (void)setRingMusicSid:(unsigned int)a0;
- (void)setRingType:(unsigned int)a0;
- (void)setM_nsBindXmail:(id)a0;
- (void)setServiceAgreementInfo:(id)a0;
- (void)setPasskeyCredentialID:(id)a0;
- (void)setM_salt:(id)a0;
- (void)setM_textStatusData:(id)a0;
- (void)setM_textStatusExtInfo:(id)a0;
- (void)setM_textStatusID:(id)a0;
- (void)setM_finderSetting:(unsigned long long)a0;
- (void)setM_teenagerModeEmotionSetting:(unsigned int)a0;
- (void)setM_teenagerModeMiniProgramSetting:(unsigned int)a0;
- (void)setM_teenagerModeBizAcctSetting:(unsigned int)a0;
- (void)setM_teenagerModeFinderSetting:(unsigned int)a0;
- (void)setM_xAgreementInfoFuncsUserChoiceSwitch:(unsigned long long)a0;
- (void)setM_xAgreementInfoFuncsSwitch:(unsigned long long)a0;
- (void)setM_uiPaySettingStatus:(unsigned long long)a0;
- (void)setHearingAidModeRemote:(unsigned long long)a0;
- (void)setExtStatus2:(unsigned long long)a0;
- (void)setM_uiExtStatus:(unsigned long long)a0;
- (void)setM_SMCryptoFlag:(unsigned int)a0;
- (void)setLqtVersion:(unsigned int)a0;
- (void)setM_walletRegion:(unsigned int)a0;
- (void)setM_walletType:(unsigned int)a0;
- (void)setM_patternInfoSign:(id)a0;
- (void)setM_patternLockStatus:(unsigned int)a0;
- (void)setM_patternVersion:(unsigned int)a0;
- (void)setM_nsMsgPushSound:(id)a0;
- (void)setM_pcWCBGImgID:(id)a0;
- (void)setM_iWCRecentHours:(unsigned int)a0;
- (void)setM_iWCFlagExt:(int)a0;
- (void)setM_iWCFlag:(int)a0;
- (void)setM_nsWCBGImgObjectID:(id)a0;
- (void)setM_nsFacebookToken:(id)a0;
- (void)setM_nsFacebookName:(id)a0;
- (void)setM_nsFacebookID:(id)a0;
- (void)setM_uiFacebookFlag:(unsigned int)a0;
- (void)setM_uiPluginInstallStatus:(unsigned int)a0;
- (void)setM_uiSex:(unsigned int)a0;
- (void)setM_nsCity:(id)a0;
- (void)setM_nsProvince:(id)a0;
- (void)setM_nsCountry:(id)a0;
- (void)setM_uiStatus:(unsigned int)a0;
- (void)setM_nsMobile:(id)a0;
- (void)setM_nsEmail:(id)a0;
- (void)setM_uiBindQQUin:(unsigned int)a0;
- (void)setM_nsAliasName:(id)a0;
- (void)setM_bIsRunningAsBakDevice:(BOOL)a0;
- (void)setM_oAutoAuthWrap:(id)a0;
- (void)setM_nsLastUUID:(id)a0;
- (void)setM_bAuthAnotherPlace:(BOOL)a0;
- (void)setM_uiCryptUin:(unsigned int)a0;
- (void)setM_nsPushmailFolderUrl:(id)a0;
- (void)setM_nsUsrName:(id)a0;
- (void)setLastSvrTime:(unsigned long long)a0;
- (void)setM_uStartTime:(unsigned int)a0;
- (void)setM_iDiffTime:(int)a0;
- (void)setM_dtSyncBuffer:(id)a0;
- (void)setM_uLastSystemUptime:(unsigned int)a0;
- (void)setM_uiPluginSwitch:(unsigned int)a0;
- (void)encodeWithCoder:(id)a0;
- (id)initWithCoder:(id)a0;
- (void)copyFromSetting:(id)a0;
- (void)setM_dtOldAutoAuthKey:(id)a0;
- (id)m_dtOldAutoAuthKey;
- (unsigned int)m_uiBindQQUin;
- (void)setm_uiBindQQUin:(unsigned int)a0;
- (unsigned int)m_uiStatus;
- (void)setm_uiStatus:(unsigned int)a0;
- (BOOL)m_bNewMsgSound;
- (void)setm_bNewMsgSound:(BOOL)a0;
- (BOOL)m_bNewMsgVibration;
- (void)setm_bNewMsgVibration:(BOOL)a0;
- (unsigned int)m_uiLastTimeOfNotifyOpenPush;
- (void)setm_uiLastTimeOfNotifyOpenPush:(unsigned int)a0;
- (unsigned int)m_uiCryptUin;
- (void)setm_uiCryptUin:(unsigned int)a0;
- (unsigned int)m_uiLastInitVersion;
- (void)setm_uiLastInitVersion:(unsigned int)a0;
- (id)m_nsInitBuffer;
- (void)setm_nsInitBuffer:(id)a0;
- (unsigned int)m_uiInitStatus;
- (void)setm_uiInitStatus:(unsigned int)a0;
- (BOOL)m_bAuthAnotherPlace;
- (void)setm_bAuthAnotherPlace:(BOOL)a0;
- (unsigned int)m_uiPushMailSwitchStatus;
- (void)setm_uiPushMailSwitchStatus:(unsigned int)a0;
- (id)m_nsPushmailFolderUrl;
- (void)setm_nsPushmailFolderUrl:(id)a0;
- (id)m_dtSyncBuffer;
- (void)setm_dtSyncBuffer:(id)a0;
- (id)m_nsCountry;
- (void)setm_nsCountry:(id)a0;
- (id)m_nsProvince;
- (void)setm_nsProvince:(id)a0;
- (id)m_nsCity;
- (void)setm_nsCity:(id)a0;
- (unsigned int)m_uiSex;
- (void)setm_uiSex:(unsigned int)a0;
- (id)m_nsHDHeadImgMD5;
- (void)setm_nsHDHeadImgMD5:(id)a0;
- (id)m_nsHDImgStatus;
- (void)setm_nsHDImgStatus:(id)a0;
- (unsigned int)m_uiPluginInstallStatus;
- (void)setm_uiPluginInstallStatus:(unsigned int)a0;
- (unsigned int)m_uiSelfShowType;
- (void)setm_uiSelfShowType:(unsigned int)a0;
- (unsigned int)m_uiFacebookFlag;
- (void)setm_uiFacebookFlag:(unsigned int)a0;
- (id)m_nsFacebookID;
- (void)setm_nsFacebookID:(id)a0;
- (id)m_nsFacebookName;
- (void)setm_nsFacebookName:(id)a0;
- (id)m_nsFacebookToken;
- (void)setm_nsFacebookToken:(id)a0;
- (unsigned int)m_uiPluginSwitch;
- (void)setm_uiPluginSwitch:(unsigned int)a0;
- (id)m_nsAuthKey;
- (void)setm_nsAuthKey:(id)a0;
- (id)m_nsWCBGImgObjectID;
- (void)setm_nsWCBGImgObjectID:(id)a0;
- (int)m_iWCFlag;
- (void)setm_iWCFlag:(int)a0;
- (int)m_iWCFlagExt;
- (void)setm_iWCFlagExt:(int)a0;
- (unsigned int)m_iWCRecentHours;
- (void)setm_iWCRecentHours:(unsigned int)a0;
- (id)m_pcWCBGImgID;
- (void)setm_pcWCBGImgID:(id)a0;
- (id)m_dtA2Key;
- (void)setm_dtA2Key:(id)a0;
- (id)m_dtA2KeyNew;
- (void)setm_dtA2KeyNew:(id)a0;
- (id)m_nsLastUUID;
- (void)setm_nsLastUUID:(id)a0;
- (id)m_dtNewInitTempBuffer;
- (void)setm_dtNewInitTempBuffer:(id)a0;
- (id)m_dtNewInitTempMaxBuffer;
- (void)setm_dtNewInitTempMaxBuffer:(id)a0;
- (BOOL)m_useInitContact;
- (void)setm_useInitContact:(BOOL)a0;
- (id)m_nsMsgPushSound;
- (void)setm_nsMsgPushSound:(id)a0;
- (unsigned int)m_patternVersion;
- (void)setm_patternVersion:(unsigned int)a0;
- (unsigned int)m_patternLockStatus;
- (void)setm_patternLockStatus:(unsigned int)a0;
- (id)m_patternInfoSign;
- (void)setm_patternInfoSign:(id)a0;
- (unsigned int)m_walletType;
- (void)setm_walletType:(unsigned int)a0;
- (unsigned int)m_walletRegion;
- (void)setm_walletRegion:(unsigned int)a0;
- (BOOL)m_remindMMDBRestore;
- (void)setm_remindMMDBRestore:(BOOL)a0;
- (id)m_nsUsrName;
- (void)setm_nsUsrName:(id)a0;
- (id)m_nsAliasName;
- (void)setm_nsAliasName:(id)a0;
- (id)m_nsEmail;
- (void)setm_nsEmail:(id)a0;
- (id)m_nsMobile;
- (void)setm_nsMobile:(id)a0;
- (unsigned long long)m_uiExtStatus;
- (void)setm_uiExtStatus:(unsigned long long)a0;
- (unsigned long long)m_uiPaySettingStatus;
- (void)setm_uiPaySettingStatus:(unsigned long long)a0;
- (int)m_iDiffTime;
- (void)setm_iDiffTime:(int)a0;
- (unsigned int)m_uStartTime;
- (void)setm_uStartTime:(unsigned int)a0;
- (unsigned int)m_uSnsWeishiShowed;
- (void)setm_uSnsWeishiShowed:(unsigned int)a0;
- (unsigned int)m_version;
- (void)setm_version:(unsigned int)a0;
- (unsigned int)m_uSendMsgActionFlag;
- (void)setm_uSendMsgActionFlag:(unsigned int)a0;
- (id)m_oAutoAuthWrap;
- (void)setm_oAutoAuthWrap:(id)a0;
- (BOOL)m_bNeedClearMailPluginMsg;
- (void)setm_bNeedClearMailPluginMsg:(BOOL)a0;
- (id)m_nsBindXmail;
- (void)setm_nsBindXmail:(id)a0;
- (unsigned long long)m_xAgreementInfoFuncsSwitch;
- (void)setm_xAgreementInfoFuncsSwitch:(unsigned long long)a0;
- (unsigned long long)m_xAgreementInfoFuncsUserChoiceSwitch;
- (void)setm_xAgreementInfoFuncsUserChoiceSwitch:(unsigned long long)a0;
- (id)m_salt;
- (void)setm_salt:(id)a0;
- (id)m_textStatusID;
- (void)setm_textStatusID:(id)a0;
- (id)m_textStatusExtInfo;
- (void)setm_textStatusExtInfo:(id)a0;
- (unsigned long long)m_finderSetting;
- (void)setm_finderSetting:(unsigned long long)a0;
- (unsigned int)m_teenagerModeFinderSetting;
- (void)setm_teenagerModeFinderSetting:(unsigned int)a0;
- (unsigned int)m_teenagerModeBizAcctSetting;
- (void)setm_teenagerModeBizAcctSetting:(unsigned int)a0;
- (unsigned int)m_teenagerModeMiniProgramSetting;
- (void)setm_teenagerModeMiniProgramSetting:(unsigned int)a0;
- (unsigned int)m_teenagerModeEmotionSetting;
- (void)setm_teenagerModeEmotionSetting:(unsigned int)a0;
- (unsigned int)ringType;
- (void)setringType:(unsigned int)a0;
- (unsigned long long)ringObjectId;
- (void)setringObjectId:(unsigned long long)a0;
- (id)ringNonceId;
- (void)setringNonceId:(id)a0;
- (unsigned int)ringMusicSid;
- (void)setringMusicSid:(unsigned int)a0;
- (double)ringStartTime;
- (void)setringStartTime:(double)a0;
- (double)ringEndTime;
- (void)setringEndTime:(double)a0;
- (BOOL)ringToneSoundOpen;
- (void)setringToneSoundOpen:(BOOL)a0;
- (unsigned long long)discoveryPageCtrlFlag;
- (void)setdiscoveryPageCtrlFlag:(unsigned long long)a0;
- (unsigned int)m_SMCryptoFlag;
- (void)setm_SMCryptoFlag:(unsigned int)a0;
- (unsigned long long)extStatus2;
- (void)setextStatus2:(unsigned long long)a0;
- (unsigned long long)systemAuthSports;
- (void)setsystemAuthSports:(unsigned long long)a0;
- (unsigned long long)systemAuthBluetooth;
- (void)setsystemAuthBluetooth:(unsigned long long)a0;
- (unsigned long long)systemAuthMicrophone;
- (void)setsystemAuthMicrophone:(unsigned long long)a0;
- (unsigned long long)systemAuthCamera;
- (void)setsystemAuthCamera:(unsigned long long)a0;
- (unsigned long long)systemAuthPhoto;
- (void)setsystemAuthPhoto:(unsigned long long)a0;
- (unsigned long long)systemAuthAddressBook;
- (void)setsystemAuthAddressBook:(unsigned long long)a0;
- (unsigned long long)systemAuthLocation;
- (void)setsystemAuthLocation:(unsigned long long)a0;
- (id)savedHelloMsg;
- (void)setsavedHelloMsg:(id)a0;
- (BOOL)m_bIsRunningAsBakDevice;
- (void)setm_bIsRunningAsBakDevice:(BOOL)a0;
- (unsigned int)m_uLastSystemUptime;
- (void)setm_uLastSystemUptime:(unsigned int)a0;
- (BOOL)m_bHasCheckTimeChange;
- (void)setm_bHasCheckTimeChange:(BOOL)a0;
- (unsigned int)lqtVersion;
- (void)setlqtVersion:(unsigned int)a0;
- (unsigned long long)systemAuthImageLocationData;
- (void)setsystemAuthImageLocationData:(unsigned long long)a0;
- (id)translateLanguage;
- (void)settranslateLanguage:(id)a0;
- (unsigned int)notifyBannerDisplayContentSetting;
- (void)setnotifyBannerDisplayContentSetting:(unsigned int)a0;
- (unsigned long long)systemAuthImageContentData;
- (void)setsystemAuthImageContentData:(unsigned long long)a0;
- (unsigned long long)lastSvrTime;
- (void)setlastSvrTime:(unsigned long long)a0;
- (id)m_textStatusData;
- (void)setm_textStatusData:(id)a0;
- (id)passkeyCredentialID;
- (void)setpasskeyCredentialID:(id)a0;
- (id)serviceAgreementInfo;
- (void)setserviceAgreementInfo:(id)a0;
- (id)savedHelloMsgImageUrl;
- (void)setsavedHelloMsgImageUrl:(id)a0;
- (id)savedHelloMsgAesKey;
- (void)setsavedHelloMsgAesKey:(id)a0;
- (unsigned int)apnsBannerDisplayContentSetting;
- (void)setapnsBannerDisplayContentSetting:(unsigned int)a0;
- (unsigned long long)clientGrayFlag;
- (void)setclientGrayFlag:(unsigned long long)a0;
- (unsigned long long)hearingAidModeLocal;
- (void)sethearingAidModeLocal:(unsigned long long)a0;
- (unsigned long long)hearingAidModeOld;
- (void)sethearingAidModeOld:(unsigned long long)a0;
- (unsigned long long)hearingAidModeRemote;
- (void)sethearingAidModeRemote:(unsigned long long)a0;
- (void)cleanUnusedKeys;
- (void)keepValidKeyValuesFromRecover;
- (id)keyPaths;
- (id)description;
- (void)setM_nsNickName:(id)a0;
- (id)m_nsNickName;
- (void)setM_nsSignature:(id)a0;
- (id)m_nsSignature;
- (void)migrateDicSetting;
- (id)getDicSetting;
- (void)preInit;
- (void)continueInit;
- (id)initWithCurUserName:(id)a0 fromOldSetting:(id)a1;
- (BOOL)save;
- (void)setBool:(BOOL)a0 forKey:(id)a1;
- (BOOL)getBoolForKey:(id)a0;
- (void)setUInt32:(unsigned int)a0 forKey:(id)a1;
- (unsigned int)getUInt32ForKey:(id)a0;
- (void)setInt32:(int)a0 forKey:(id)a1;
- (int)getInt32ForKey:(id)a0;
- (id)getObjectOfClass:(Class)a0 forKey:(id)a1;
- (id)getArrayOfValueType:(Class)a0 forKey:(id)a1;
- (void)setObject:(id)a0 forKey:(id)a1;
- (void)removeObjectForKey:(id)a0;
- (void).cxx_destruct;

@end
