@class EditImageDeleteBarView, UITapGestureRecognizer, WCEditEraserCurserView, EditImageWidgetTool, NSMutableArray, NSString, UIImage, WCEditViewControllerUIConfig, NSArray, EditImagePOITool, WCEditImageOperationMgr, EditImageTextTool, UIView, WCEditImagePenTraceMgr, WCEditPanGestureFilter, UIPanGestureRecognizer, EditImageCropOverlayView, UIImageView, CALayer, UIColor, MMTimer, EditImageScrollView, EditImageMusicLyricsWidgetTool;
@protocol WCEditImageToolProtocol;

@interface EditImageView : UIImageView <EditImageTextToolDelegate, MosaicToolDelegate, EditImageWidgetToolDelegate> {
    struct CGPoint { double x; double y; } p2Location;
    struct CGPoint { double x; double y; } p1Location;
    struct CGPoint { double x; double y; } cLocation;
    UITapGestureRecognizer *_tapGesture;
    UIPanGestureRecognizer *_panGesture;
    UITapGestureRecognizer *_blankGesture;
    BOOL _canZoom;
    BOOL _canDraw;
    unsigned long long _mosaicStyle;
    MMTimer *_timer;
    MMTimer *_finishDrawingTimer;
    MMTimer *_checkEventTimer;
    BOOL _hasOriginalImage;
    double _originalWaitingTime;
    double colorPointMapWidth;
    double colorPointMapHeight;
    char *colorPointMap;
    id /* block */ _completion;
    BOOL isCropped;
    unsigned int undoCount;
    unsigned int editEntrance;
    BOOL isRotated;
    UIImageView *imageView;
    NSArray *_viewSeq;
    double _checkEventTimerLimit;
    unsigned long long _startEditTimeInMs;
    double _storyMainTextTop;
}

@property (retain, nonatomic) EditImageMusicLyricsWidgetTool *musicLyricsWidget;
@property (retain, nonatomic) EditImagePOITool *poiWidget;
@property (retain, nonatomic) EditImageTextTool *textWidget;
@property (retain, nonatomic) WCEditPanGestureFilter *panFilter;
@property (nonatomic) BOOL isInEraserMode;
@property (retain, nonatomic) WCEditImageOperationMgr *operationMgr;
@property (retain, nonatomic) WCEditImagePenTraceMgr *penTraceMgr;
@property (retain, nonatomic) WCEditImagePenTraceMgr *mosaicTraceMgr;
@property (retain, nonatomic) WCEditEraserCurserView *eraserCurserView;
@property (nonatomic) BOOL isFinishEdited;
@property (nonatomic) unsigned long long editImageUIStyle;
@property (nonatomic) unsigned int fromEntrance;
@property (weak, nonatomic) EditImageScrollView *_delegate;
@property (nonatomic) BOOL animatable;
@property (nonatomic) struct CGPoint { double x; double y; } firstTouchPoint;
@property (nonatomic) struct CGPath { } *_drawPath;
@property (nonatomic) double _lineWidth;
@property (retain, nonatomic) UIColor *_lineColor;
@property (retain, nonatomic) NSMutableArray *_drawLayerArray;
@property (retain, nonatomic) NSMutableArray *_drawLayerBufferArray;
@property (retain, nonatomic) CALayer *_drawLayer;
@property (retain, nonatomic) NSMutableArray *_drawViewWidgetArray;
@property (retain, nonatomic) NSMutableArray *_drawViewPenArray;
@property (retain, nonatomic) NSMutableArray *_drawViewMosaicArray;
@property (retain, nonatomic) NSMutableArray *_drawViewCropArray;
@property (retain, nonatomic) UIImageView *_penView;
@property (retain, nonatomic) UIImageView *_mosaicView;
@property (retain, nonatomic) UIView *_tempMosaicView;
@property (retain, nonatomic) UIView *_tempPenView;
@property (retain, nonatomic) NSMutableArray *_undoViewPenArray;
@property (retain, nonatomic) NSMutableArray *_undoViewMosaicArray;
@property (retain, nonatomic) NSMutableArray *drawViewPenColorArray;
@property (retain, nonatomic) NSMutableArray *drawViewGlassMosaicArray;
@property (retain, nonatomic) NSMutableArray *drawViewPaintingMosaicArray;
@property (retain, nonatomic) NSMutableArray *_drawHierarchyViewArray;
@property (retain, nonatomic) NSMutableArray *_drawRevertArray;
@property (retain, nonatomic) NSMutableArray *_textViewArray;
@property (retain, nonatomic) UIImage *_foregroundImage;
@property (retain, nonatomic) UIImage *_backupImage;
@property (retain, nonatomic) id _mosaicImage;
@property (nonatomic) BOOL _willSetImageLayer;
@property (nonatomic) BOOL _didSetImageLayer;
@property (nonatomic) BOOL _isBeforeMosaicTool;
@property (nonatomic) BOOL _isNeedRedrawMosaicImage;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _startImageFrame;
@property (retain, nonatomic) UIImageView *_imgColorView;
@property (retain, nonatomic) EditImageCropOverlayView *_overlayView;
@property (retain, nonatomic) id<WCEditImageToolProtocol> _currentTool;
@property (nonatomic) int _toolType;
@property (retain, nonatomic) EditImageDeleteBarView *_deleteBar;
@property (retain, nonatomic) EditImageWidgetTool *_highlightWidgetTool;
@property (weak, nonatomic) UIView *_superView;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } editViewFrame;
@property (nonatomic) BOOL hasTapForDraw;
@property (nonatomic) double horizontalEditSafeAreaOffset;
@property (nonatomic) double verticalEditSafeAreaOffset;
@property (nonatomic) BOOL hasShowedDeleteBar;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } cancelBtnFrame;
@property (nonatomic) BOOL notCheckOriginalImgWhiteClickDone;
@property (retain, nonatomic) WCEditViewControllerUIConfig *uiConfig;
@property (nonatomic) unsigned long long editImageContentType;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithEditViewFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)initDeleteBar;
- (void)reloadDeleteBar;
- (void)dealloc;
- (void)initDrawViewArrayAndHierarchyArray:(id)a0;
- (void)genCacheImage;
- (void)handleTapGesture:(id)a0;
- (void)handlePanGesture:(id)a0;
- (void)handlePinchGesture:(id)a0;
- (void)handleRotateGesture:(id)a0;
- (void)handleLongPressGesture:(id)a0;
- (void)_tryAddAnGestureOperation;
- (void)_tryAddPenEraserOperationWithHiddenPenTraceIndex:(id)a0;
- (void)_tryAddMosaicEraserOperationWithHiddenPenTraceIndex:(id)a0;
- (BOOL)findGestureWidget:(id)a0;
- (void)startTimer;
- (void)cancelTimer;
- (void)triggerTimer;
- (void)startGesture;
- (void)endGesture:(id)a0;
- (void)bringWidgetviewToFront:(id)a0;
- (void)bringWidgetviewBack:(id)a0;
- (void)updateViewIndex;
- (void)widgetToolBecomeFirstResponder:(id)a0;
- (void)reloadAllWidgetFrame;
- (double)scrollViewZoomScale;
- (void)removeSubview:(id)a0;
- (void)addNewWidget:(id)a0;
- (void)dragaAndDropWidget;
- (void)deleteBarSelected;
- (void)deleteBarDeselected;
- (void)reloadViews:(BOOL)a0;
- (void)reloadImage:(BOOL)a0;
- (void)loadImage:(id)a0 withDrawLayerArray:(id)a1 withEditEntrance:(unsigned int)a2;
- (void)loadOriginalImage:(id)a0 withImageData:(id)a1;
- (void)reportEditImageLoadOriginalImageWithImageSize:(unsigned int)a0 withFitSize:(unsigned int)a1 withImageHeight:(unsigned int)a2 withImageWidth:(unsigned int)a3 withFitScale:(float)a4;
- (BOOL)canZoom;
- (void)setFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)scrollViewDidScroll;
- (void)scrollViewDidZoom;
- (void)scrollViewDidEndZoom;
- (BOOL)canPenUndo;
- (BOOL)canMosaicUndo;
- (BOOL)canRedo;
- (BOOL)hasAddPenTrace;
- (void)undoPen;
- (void)undoMosaic;
- (void)redo;
- (void)setEraserModeActive:(BOOL)a0;
- (int)checkToolType;
- (void)useImageTool:(int)a0;
- (double)getTextViewTop;
- (void)didSelectEmoticonWithWrap:(id)a0 decodedImage:(id)a1;
- (void)changeLineColor:(id)a0;
- (void)changeLineWidth:(double)a0;
- (void)changeMosaicStyle:(unsigned long long)a0;
- (void)setDeleteBarHidden:(BOOL)a0;
- (BOOL)alreadyHasSubviews;
- (void)addNewSubview:(id)a0;
- (void)startDrawing;
- (void)finishDrawing;
- (void)resetFinishDrawingTimer;
- (void)finishDrawingTriggerEvent;
- (void)checkWidgetOutside:(id)a0 withCompletion:(id /* block */)a1;
- (void)genLastEditView;
- (BOOL)isInPenOrMosaicToolType;
- (id)genEditedImageWithOriginalSize;
- (id)generateWidgetStateList;
- (BOOL)isTextToolType:(int)a0;
- (void)onClickDoneBtn:(id /* block */)a0;
- (void)timerTrigger:(id)a0;
- (void)trueClickDoneBtn;
- (void)onClickCancelBtn;
- (void)revertViewToBegining;
- (BOOL)checkWhetherEdited;
- (void)setMusicLyricIsOn:(BOOL)a0;
- (void)updateMusicLyrics:(id)a0 totalTime:(double)a1;
- (void)updateMusicLyricsCropTime:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })a0;
- (void)updateFixedPositionWidgetWithTipsButton:(id)a0 lineView:(id)a1;
- (id)transToMosaicImage:(id)a0 blockLevel:(unsigned long long)a1;
- (void)setColorPointMap:(id)a0;
- (id)colorOfPoint:(struct CGPoint { double x0; double x1; })a0;
- (id)getEditImagePOITool:(id)a0;
- (BOOL)canGlobalUndo;
- (BOOL)canGlobalRedo;
- (void)globalUndo;
- (void)globalRedo;
- (void)recordAnOperation:(id)a0;
- (void)undoAddNewSubview:(id)a0;
- (void)editImageTextTool:(id)a0 needConfirmEditText:(id)a1 withColor:(id)a2 style:(unsigned long long)a3 backgroundColor:(id)a4;
- (void)setToolType:(int)a0;
- (id)getCurrentTool;
- (id)mosaicImage;
- (double)initWidgetYPostionFactor;
- (BOOL)shouldShowVerticalEditSafeArea;
- (BOOL)shouldShowHorizontalEditSafeArea;
- (id)getEditImageAttr;
- (void).cxx_destruct;

@end
