@class NSString;

@interface EnterpriseMsgDBItem : MMObject <WCTTableCoding>

@property (nonatomic) unsigned long long m_ui64MesSvrId;
@property (nonatomic) unsigned int m_uiMesLocalId;
@property (nonatomic) unsigned int m_uiCreateTime;
@property (nonatomic) unsigned int m_uiDesc;
@property (nonatomic) unsigned int m_uiStatus;
@property (nonatomic) unsigned int m_uiImgStatus;
@property (nonatomic) unsigned int m_uiType;
@property (retain, nonatomic) NSString *m_nsMessage;
@property (retain, nonatomic) NSString *m_nsMsgSource;
@property (retain, nonatomic) NSString *m_nsFromUsr;
@property (retain, nonatomic) NSString *m_nsToUsr;
@property (retain, nonatomic) NSString *m_nsBizChatId;
@property (retain, nonatomic) NSString *m_nsRealChatUsr;
@property (retain, nonatomic) NSString *m_nsPattern;
@property (copy, nonatomic) NSString *m_nsBizCliMsgId;
@property (nonatomic) long long lastInsertedRowID;
@property (nonatomic) BOOL isAutoIncrement;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (const void *)objectRelationalMapping;
+ (const void *)allProperties;
+ (id)allBridgeProperties;
+ (id)__wcdbtyper;
+ (const void *)m_ui64MesSvrId;
+ (const void *)__wcdb_synthesize_0:(void *)a0;
+ (id)swift_m_ui64MesSvrId;
+ (const void *)m_uiMesLocalId;
+ (const void *)__wcdb_synthesize_1:(void *)a0;
+ (id)swift_m_uiMesLocalId;
+ (const void *)m_uiCreateTime;
+ (const void *)__wcdb_synthesize_2:(void *)a0;
+ (id)swift_m_uiCreateTime;
+ (const void *)m_uiDesc;
+ (const void *)__wcdb_synthesize_3:(void *)a0;
+ (id)swift_m_uiDesc;
+ (const void *)m_uiStatus;
+ (const void *)__wcdb_synthesize_4:(void *)a0;
+ (id)swift_m_uiStatus;
+ (const void *)m_uiImgStatus;
+ (const void *)__wcdb_synthesize_5:(void *)a0;
+ (id)swift_m_uiImgStatus;
+ (const void *)m_nsMessage;
+ (const void *)__wcdb_synthesize_6:(void *)a0;
+ (id)swift_m_nsMessage;
+ (const void *)m_uiType;
+ (const void *)__wcdb_synthesize_7:(void *)a0;
+ (id)swift_m_uiType;
+ (const void *)m_nsMsgSource;
+ (const void *)__wcdb_synthesize_8:(void *)a0;
+ (id)swift_m_nsMsgSource;
+ (const void *)m_nsFromUsr;
+ (const void *)__wcdb_synthesize_9:(void *)a0;
+ (id)swift_m_nsFromUsr;
+ (const void *)m_nsToUsr;
+ (const void *)__wcdb_synthesize_10:(void *)a0;
+ (id)swift_m_nsToUsr;
+ (const void *)m_nsBizChatId;
+ (const void *)__wcdb_synthesize_11:(void *)a0;
+ (id)swift_m_nsBizChatId;
+ (const void *)m_nsRealChatUsr;
+ (const void *)__wcdb_synthesize_12:(void *)a0;
+ (id)swift_m_nsRealChatUsr;
+ (const void *)m_nsPattern;
+ (const void *)__wcdb_synthesize_13:(void *)a0;
+ (id)swift_m_nsPattern;
+ (const void *)m_nsBizCliMsgId;
+ (const void *)__wcdb_synthesize_14:(void *)a0;
+ (id)swift_m_nsBizCliMsgId;
+ (void)__wcdb_column_constraint_15:(void *)a0;
+ (void)__wcdb_index_16:(void *)a0;
+ (void)__wcdb_index_17:(void *)a0;
+ (void)__wcdb_index_18:(void *)a0;
+ (void)__wcdb_index_19:(void *)a0;
+ (void)__wcdb_index_20:(void *)a0;
+ (void)__wcdb_index_21:(void *)a0;
+ (void)__wcdb_index_22:(void *)a0;
+ (void)__wcdb_index_23:(void *)a0;

- (long long)compareMessageAscending:(id)a0;
- (void).cxx_destruct;

@end
