@class MMUIViewController, NSString, FaceRecogUploadLogic, LocationRetriever, FaceRecogReporter, FaceRecogBaseViewController, FaceRecogConfigLogic, UIColor;
@protocol FaceRecogHandlerDelegate, FaceRecogBaseHandlerDelegate;

@interface FaceRecogBaseHandler : MMObject <ILocationMgrExt, LocationRetrieveDelegate, IRecordPermissionCheckExt, FaceRecogUploadLogicDelegate, FaceRecogConfigLogicDelegate, FaceRecogBaseHandlerDelegate, FaceRecogBaseViewDelegate>

@property (nonatomic) long long errorCode;
@property (retain, nonatomic) NSString *errorMsg;
@property (retain, nonatomic) NSString *verifyResult;
@property (nonatomic) BOOL userCancel;
@property (retain, nonatomic) LocationRetriever *locationRetriver;
@property (weak, nonatomic) id<FaceRecogBaseHandlerDelegate> faceDelegate;
@property (weak, nonatomic) id<FaceRecogHandlerDelegate> delegate;
@property (nonatomic) BOOL needGuide;
@property (retain, nonatomic) NSString *appId;
@property (nonatomic) BOOL needUploadVideo;
@property (nonatomic) BOOL uploadVideoForPay;
@property (nonatomic) float brightnessValue;
@property (nonatomic) unsigned int scene;
@property (nonatomic) BOOL isRSA;
@property (retain, nonatomic) NSString *userTicket;
@property (nonatomic) unsigned int finishDelayTime;
@property (nonatomic) BOOL hasShowVC;
@property (nonatomic) BOOL hasShowAlert;
@property (retain, nonatomic) NSString *feedbackUrl;
@property (retain, nonatomic) NSString *businessTip;
@property (retain, nonatomic) UIColor *businessTipColor;
@property (nonatomic) double faceFrameRatio;
@property (nonatomic) long long identifyType;
@property (nonatomic) BOOL isRunning;
@property (weak, nonatomic) MMUIViewController *currentViewController;
@property (retain, nonatomic) FaceRecogBaseViewController *faceVc;
@property (retain, nonatomic) FaceRecogConfigLogic *configFetcher;
@property (retain, nonatomic) FaceRecogUploadLogic *uploader;
@property (retain, nonatomic) FaceRecogReporter *reporter;
@property (nonatomic) BOOL useHttp;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithScene:(unsigned int)a0;
- (void)initConfigLogic;
- (void)initUploadLogic;
- (void)dealloc;
- (void)startFaceRecog;
- (void)requestAccessVideo;
- (void)requestAccessAudio;
- (void)requestAccessLocation;
- (void)finishedWithAuthorizationError:(id)a0;
- (void)onRequestAccessVideoDone:(BOOL)a0 isOccupy:(BOOL)a1;
- (void)onRequestAccessAudioDone:(BOOL)a0;
- (void)requestRetry;
- (void)requestCancel;
- (void)requestStop;
- (void)report:(int)a0 errorType:(int)a1 errorCode:(int)a2;
- (void)disMissAll:(BOOL)a0 complete:(id /* block */)a1;
- (unsigned long long)getAuthScene:(unsigned int)a0;
- (void)OnRecordPermissioned;
- (void)OnRecordDenied;
- (void)OnRecordDeniedByWeChat;
- (void)didInterruptedWithRetry:(BOOL)a0;
- (void)onGetBioConfig:(id)a0 succeedForScene:(unsigned int)a1 succeedForBioId:(unsigned long long)a2;
- (void)onGetBioConfig:(id)a0 failedCauseOf:(int)a1 forScene:(unsigned int)a2 errMsg:(id)a3;
- (void)onUploadFaceResultFinish:(id)a0;
- (void)onGetFaceVideoFinish:(id)a0 inWorkMode:(long long)a1;
- (id)faceRecogVerifyGetFeedbackUrl;
- (void)reportUserCancel;
- (void)faceRecogDidCancel;
- (void)faceRecogDidClose;
- (void)faceRecogDidSuccess;
- (void)faceRecogDidRetry;
- (void)onRealFinish;
- (int)resultCode;
- (id)resultMsg;
- (id)result;
- (void)handlerDidFinishWithCode:(long long)a0 reportCode:(int)a1 msg:(id)a2 errorTips:(id)a3 verifyResult:(id)a4 canRetry:(BOOL)a5;
- (void)handlerDidFinishWithCode:(long long)a0 reportCode:(int)a1 msg:(id)a2 verifyResult:(id)a3 canRetry:(BOOL)a4;
- (void)handlerDidFinishWithCode:(long long)a0 msg:(id)a1 verifyResult:(id)a2 canRetry:(BOOL)a3;
- (void)didFinishedWithCode:(int)a0 msg:(id)a1 retry:(BOOL)a2;
- (void)handlerDidFinishWithCode:(long long)a0 msg:(id)a1 errorTips:(id)a2 verifyResult:(id)a3 canRetry:(BOOL)a4;
- (void)didUploadFaceData:(id)a0;
- (void)didAccessVideo;
- (void)didAccessAudio;
- (void)didAccessConfig;
- (void)didAccessLocation:(double)a0 longitude:(double)a1;
- (void)handleUploadFaceFlashVideoForPayWithFlag:(BOOL)a0;
- (void)onRetrieveLocationOK:(id)a0;
- (void)onRetrieveLocationTimeOut:(id)a0;
- (void)onRetrieveLocationError:(int)a0;
- (void)onLocationAuthorizationStatusUpdatedWithAccuracyAuthorization:(long long)a0;
- (void)initView;
- (void)showView;
- (void).cxx_destruct;

@end
