@class NSData, NSString, FinderJumpInfo_Html5Info, FinderJumpInfoRedDot, FinderJumpInfo_LiteApp, FinderJumpInfo_SchemaInfo, FinderJumpInfo_MiniAppInfo, FinderJumpInfo_FlutterInfo, NSMutableArray, FinderJumpInfo_NativeInfo, FinderJumpInfo_OnlineHelp;

@interface FinderJumpInfo : WXPBGeneratedMessage

@property (nonatomic) unsigned int jumpinfoType;
@property (nonatomic) unsigned int businessType;
@property (retain, nonatomic) NSString *iconUrl;
@property (retain, nonatomic) NSString *wording;
@property (retain, nonatomic) NSString *recommendReason;
@property (retain, nonatomic) NSString *extInfo;
@property (retain, nonatomic) NSString *reportInfo;
@property (retain, nonatomic) FinderJumpInfo_MiniAppInfo *miniAppInfo;
@property (retain, nonatomic) FinderJumpInfo_Html5Info *html5Info;
@property (retain, nonatomic) FinderJumpInfo_NativeInfo *nativeInfo;
@property (retain, nonatomic) FinderJumpInfo_SchemaInfo *schemaInfo;
@property (nonatomic) unsigned int source;
@property (nonatomic) unsigned int expiredTs;
@property (nonatomic) unsigned int dislike;
@property (retain, nonatomic) NSString *iconUrlDark;
@property (retain, nonatomic) NSString *iconUrlBg;
@property (retain, nonatomic) NSData *extBuff;
@property (retain, nonatomic) FinderJumpInfoRedDot *redDot;
@property (retain, nonatomic) NSString *jumpId;
@property (nonatomic) unsigned int bannerType;
@property (nonatomic) unsigned int position;
@property (retain, nonatomic) NSString *iconName;
@property (nonatomic) unsigned int supportShare;
@property (nonatomic) BOOL needPreload;
@property (retain, nonatomic) FinderJumpInfo_LiteApp *liteAppInfo;
@property (retain, nonatomic) NSMutableArray *style;
@property (nonatomic) unsigned int extType;
@property (nonatomic) unsigned int effectiveDuration;
@property (nonatomic) unsigned int delayPreloadTime;
@property (nonatomic) unsigned int redPacketType;
@property (retain, nonatomic) NSString *groupKey;
@property (retain, nonatomic) NSMutableArray *supportDeviceList;
@property (nonatomic) unsigned int iconType;
@property (retain, nonatomic) NSString *pagIconUrl;
@property (nonatomic) BOOL needAutoShow;
@property (retain, nonatomic) NSString *clickButtonName;
@property (retain, nonatomic) NSString *uiFingerprint;
@property (retain, nonatomic) FinderJumpInfo_OnlineHelp *onlineHelpInfo;
@property (retain, nonatomic) NSString *openPopupWording;
@property (retain, nonatomic) NSString *openPopupTitle;
@property (retain, nonatomic) FinderJumpInfo_FlutterInfo *flutterInfo;
@property (nonatomic) unsigned int groupStyleType;
@property (retain, nonatomic) NSString *jumpPageId;
@property (retain, nonatomic) NSData *ecsJumpInfo;
@property (nonatomic) unsigned int singleSceneEffect;
@property (nonatomic) BOOL isNativeAdComponent;
@property (nonatomic) unsigned int businessCategory;
@property (nonatomic) BOOL ignoreObjectOcrFrameInfo;

+ (id)filterUserClosedBanner:(id)a0;
+ (id)filterCarouselBannerList:(id)a0;
+ (void)addUserCloseBanner:(id)a0;
+ (BOOL)isUserCloseBanner:(id)a0;
+ (void)initialize;

- (void)setIgnoreObjectOcrFrameInfo:(BOOL)a0;
- (BOOL)ignoreObjectOcrFrameInfo;
- (void)setBusinessCategory:(unsigned int)a0;
- (unsigned int)businessCategory;
- (void)setIsNativeAdComponent:(BOOL)a0;
- (BOOL)isNativeAdComponent;
- (void)setSingleSceneEffect:(unsigned int)a0;
- (unsigned int)singleSceneEffect;
- (void)setEcsJumpInfo:(id)a0;
- (id)ecsJumpInfo;
- (void)setJumpPageId:(id)a0;
- (id)jumpPageId;
- (void)setGroupStyleType:(unsigned int)a0;
- (unsigned int)groupStyleType;
- (void)setFlutterInfo:(id)a0;
- (id)flutterInfo;
- (void)setOpenPopupTitle:(id)a0;
- (id)openPopupTitle;
- (void)setOpenPopupWording:(id)a0;
- (id)openPopupWording;
- (void)setOnlineHelpInfo:(id)a0;
- (id)onlineHelpInfo;
- (void)setUiFingerprint:(id)a0;
- (id)uiFingerprint;
- (void)setClickButtonName:(id)a0;
- (id)clickButtonName;
- (void)setNeedAutoShow:(BOOL)a0;
- (BOOL)needAutoShow;
- (void)setPagIconUrl:(id)a0;
- (id)pagIconUrl;
- (void)setIconType:(unsigned int)a0;
- (unsigned int)iconType;
- (void)setSupportDeviceList:(id)a0;
- (id)supportDeviceList;
- (void)setGroupKey:(id)a0;
- (id)groupKey;
- (void)setRedPacketType:(unsigned int)a0;
- (unsigned int)redPacketType;
- (void)setDelayPreloadTime:(unsigned int)a0;
- (unsigned int)delayPreloadTime;
- (void)setEffectiveDuration:(unsigned int)a0;
- (unsigned int)effectiveDuration;
- (void)setExtType:(unsigned int)a0;
- (unsigned int)extType;
- (void)setStyle:(id)a0;
- (id)style;
- (void)setLiteAppInfo:(id)a0;
- (id)liteAppInfo;
- (void)setNeedPreload:(BOOL)a0;
- (BOOL)needPreload;
- (void)setSupportShare:(unsigned int)a0;
- (unsigned int)supportShare;
- (void)setIconName:(id)a0;
- (id)iconName;
- (void)setPosition:(unsigned int)a0;
- (unsigned int)position;
- (void)setBannerType:(unsigned int)a0;
- (unsigned int)bannerType;
- (void)setJumpId:(id)a0;
- (id)jumpId;
- (void)setRedDot:(id)a0;
- (id)redDot;
- (void)setExtBuff:(id)a0;
- (id)extBuff;
- (void)setIconUrlBg:(id)a0;
- (id)iconUrlBg;
- (void)setIconUrlDark:(id)a0;
- (id)iconUrlDark;
- (void)setDislike:(unsigned int)a0;
- (unsigned int)dislike;
- (void)setExpiredTs:(unsigned int)a0;
- (unsigned int)expiredTs;
- (void)setSource:(unsigned int)a0;
- (unsigned int)source;
- (void)setSchemaInfo:(id)a0;
- (id)schemaInfo;
- (void)setNativeInfo:(id)a0;
- (id)nativeInfo;
- (void)setHtml5Info:(id)a0;
- (id)html5Info;
- (void)setMiniAppInfo:(id)a0;
- (id)miniAppInfo;
- (void)setReportInfo:(id)a0;
- (id)reportInfo;
- (void)setExtInfo:(id)a0;
- (id)extInfo;
- (void)setRecommendReason:(id)a0;
- (id)recommendReason;
- (void)setWording:(id)a0;
- (id)wording;
- (void)setIconUrl:(id)a0;
- (id)iconUrl;
- (void)setBusinessType:(unsigned int)a0;
- (unsigned int)businessType;
- (void)setJumpinfoType:(unsigned int)a0;
- (unsigned int)jumpinfoType;
- (BOOL)isVideoTemplateJumpInfo;
- (id)genVideoTemplateData;
- (BOOL)canShowTemplateEntry;
- (id)extInfoModel;
- (BOOL)isMinifyRoomControlBanner;
- (BOOL)isCarouselBanner;
- (BOOL)isMoreLiveBanner;
- (id)lastBufferString;

@end
