@class MMLiveEnterRoomActionModel, WCFinderFeedLiveCellRouterModel, SharePreConfirmSheetView, WCFinderFullShareListTemplatePlugin, NSMutableArray, MMFinderRefSessionBufferKey, NSString, WCFinderDataItem, MMFinderLiveNotifyBannerReportInfo, SessionForwardRecordLogic, FinderLiveGuideFollowAdInfo, WCFinderShareEntranceMessageInfo, NSArray, FinderLiveAppMsgLiveRewardInfo, ForwardMessageLogicController, FinderObjectAdvertisementInfo, WCFinderContact;

@interface MMFinderLiveContentVM : NSObject <WCCommitViewResultDelegate, ForwardMessageLogicDelegate, TextStatePublishViewControllerDelegate, SharePreConfirmSheetViewDelegate>

@property (retain, nonatomic) ForwardMessageLogicController *forwardLogic;
@property (retain, nonatomic) SharePreConfirmSheetView *sharePreConfirmSheetView;
@property (retain, nonatomic) SessionForwardRecordLogic *forwardRecordLogic;
@property (nonatomic) BOOL isCertificateType;
@property (nonatomic) unsigned long long temporaryObjectId;
@property (retain, nonatomic) NSString *temporaryNonceId;
@property (retain, nonatomic) NSMutableArray *guideAdInfos;
@property (retain, nonatomic) WCFinderDataItem *dataItem;
@property (retain, nonatomic) WCFinderContact *contact;
@property (retain, nonatomic) NSString *sessionExtraKey;
@property (nonatomic) BOOL isRead;
@property (retain, nonatomic) NSString *customTransitionKey;
@property (nonatomic) unsigned long long refObjectID;
@property (retain, nonatomic) MMFinderRefSessionBufferKey *refSessionBufferKey;
@property (retain, nonatomic) NSString *finderForwardSource;
@property (retain, nonatomic) NSString *tmpEntryScene;
@property (retain, nonatomic) NSString *srcUrl;
@property (retain, nonatomic) NSString *sourceLiteAppId;
@property (retain, nonatomic) WCFinderFullShareListTemplatePlugin *jsapiPlugin;
@property (retain, nonatomic) id userInfo;
@property (readonly, nonatomic) unsigned long long objectID;
@property (readonly, nonatomic) NSString *tid;
@property (readonly, nonatomic) NSString *nonceId;
@property (readonly, nonatomic) BOOL needPlayOpenScreenAd;
@property (nonatomic) BOOL canNotRouteReplayView;
@property (retain, nonatomic) MMLiveEnterRoomActionModel *enterActionModel;
@property (nonatomic) BOOL joinTeamStatusChanged;
@property (nonatomic) BOOL assumeReplayAndGoToStopgap;
@property (retain, nonatomic) FinderLiveAppMsgLiveRewardInfo *rewardInfo;
@property (retain, nonatomic) NSString *liveReplayEntryType;
@property (nonatomic) BOOL isConnectMicEnter;
@property (retain, nonatomic) MMFinderLiveNotifyBannerReportInfo *notifyBannerReportInfo;
@property (nonatomic) unsigned int selectiveGoQrScenario;
@property (copy, nonatomic) NSString *entranceQRCodeURL;
@property (nonatomic) unsigned long long adFlag;
@property (retain, nonatomic) FinderObjectAdvertisementInfo *adInfo;
@property (nonatomic) unsigned long long shoppingProductId;
@property (nonatomic) unsigned long long fromSource;
@property (retain, nonatomic) FinderLiveGuideFollowAdInfo *followGuideInfo;
@property (retain, nonatomic) NSString *notifyReportExtInfo;
@property (retain, nonatomic) WCFinderShareEntranceMessageInfo *entranceMessageInfo;
@property (nonatomic) unsigned long long enterSessionId;
@property (retain, nonatomic) WCFinderFeedLiveCellRouterModel *feedModel;
@property (copy, nonatomic) NSString *instantDiscountActivityKey;
@property (nonatomic) BOOL useABRCfg;
@property (nonatomic) BOOL disableInteractiveToMinimizeWindow;
@property (retain, nonatomic) NSArray *backupFeeds;
@property (nonatomic) BOOL rotateEnabled;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)contentVMWithDataItem:(id)a0;

- (id)initWithDataItem:(id)a0 sessionExtraKey:(id)a1;
- (id)initWithContact:(id)a0;
- (id)initWithContact:(id)a0 objectId:(unsigned long long)a1 nonceId:(id)a2;
- (void)dealloc;
- (void)clearJSApiInfo;
- (BOOL)isAnchor;
- (BOOL)isAnchorSecondaryDevice;
- (BOOL)disableForwardByPrivateAccount;
- (BOOL)isSelfPrivate;
- (BOOL)isOpenLiveQuickShare;
- (unsigned int)currentContentInnerAppMsgType;
- (void)copyExtraInfoFrom:(id)a0;
- (void)updateRotateEnabled:(BOOL)a0;
- (void)shareToFriendWithParams:(id)a0;
- (void)liveShareToMomentFromVC:(id)a0 shareScene:(long long)a1;
- (void)shareToMoment;
- (void)shareToMomentFromVC:(id)a0;
- (void)shareToTextStateFromVC:(id)a0 verifyInfo:(id)a1;
- (void)shareToTextStateFromVC:(id)a0 verifyInfo:(id)a1 textStatusIconId:(id)a2;
- (void)shareToTextStateFromVC:(id)a0 verifyInfo:(id)a1 textStatusIconId:(id)a2 liveBanner:(BOOL)a3;
- (void)shareToFriend:(id)a0 fromVC:(id)a1 withShareScene:(long long)a2;
- (id)getFinderShareToFriendMessageWrapWithExtra:(id)a0 shareScene:(long long)a1;
- (void)shareLiveAndGoodsToFriends:(id)a0;
- (id)makeShareImageMsgSourceUrl;
- (void)onCancelForwardForForwardView:(id)a0;
- (void)onDoneForwardForForwardView:(id)a0;
- (void)forwardViewControllerDidCancel:(id)a0;
- (void)forwardViewController:(id)a0 didFinishForwardingWithDataItem:(id)a1;
- (id)getCurrentViewController;
- (void)OnForwardMessageSend:(id)a0;
- (void)OnForwardMessageCancel:(id)a0;
- (void)OnForwardMessageException:(id)a0;
- (void)onTextStatePublished;
- (void)onTextStatePublishCancelled;
- (void)OnSharePreConfirmSheetViewSend:(id)a0;
- (void)OnSharePreConfirmSheetViewCancel:(id)a0;
- (void)OnSharePreConfirmSheetViewClose:(id)a0;
- (void).cxx_destruct;

@end
