@class NSString, NSMutableArray, MMLocatingCoordinateLogic;

@interface MMIPlatformUtilImpl : NSObject <IMMLanguageMgrExt, MMIPlatformUtil>

@property (retain, nonatomic) NSMutableArray *lanageCallbacks;
@property (retain, nonatomic) MMLocatingCoordinateLogic *logic;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)getRedDotKey:(id)a0;
+ (id)getRedDotTipsId:(id)a0;

- (void)openTinyApp:(id)a0;
- (id)init;
- (int)androidAPILevel;
- (long long)androidDpiLevel;
- (id)currentLanguageCode;
- (void)setLanguageChangeCallbackImpl:(id)a0;
- (long long)currentPlatform;
- (long long)iOSDevice;
- (int)iOSScreenScale;
- (float)getPx:(float)a0;
- (id)iOSVersion;
- (float)getLoigcalResolutionWidth;
- (float)getLoigcalResolutionHeight;
- (float)getStatusBarHeight;
- (float)getNavigationBarHeight;
- (float)getBottomSafeAreaHeight;
- (BOOL)getIsAccessibilityServiceRunning;
- (BOOL)getExptBoolValue:(id)a0;
- (id)getPlatformString:(id)a0;
- (BOOL)isPad;
- (BOOL)isNetworkConnected;
- (id)md5:(id)a0;
- (id)sha256:(id)a0 uppercase:(BOOL)a1;
- (id)genUUID;
- (id)base64Decode:(id)a0;
- (id)base64Encode:(id)a0;
- (id)base64DecodeString:(id)a0;
- (int)getRedDotStatus:(id)a0;
- (id)getRedDotWording:(id)a0;
- (void)setRedDotStatus:(id)a0 value:(BOOL)a1;
- (void)setStatusBarHidden:(BOOL)a0 animated:(BOOL)a1;
- (float)getPadSplitWidth;
- (float)getPadSplitHeight;
- (void)playVibration;
- (float)getScreenBrightness;
- (void)setScreenBrightness:(float)a0;
- (void)makesureLonglink;
- (void)setIdleTimerDisable:(BOOL)a0;
- (id)getMemoryKVString:(id)a0;
- (float)getIphoneSafeAreaBottomHeight;
- (void)accessibilityFocus:(id)a0;
- (void)accessibilityAnnounce:(id)a0 key:(id)a1;
- (float)dynamicSize:(float)a0;
- (float)dynamicFontSize:(float)a0;
- (float)dynamicSizeByFontLevel:(float)a0 level:(int)a1;
- (int)getFontLevel;
- (float)getScaleByFontLevel:(int)a0;
- (float)getViewScale;
- (BOOL)isCareModeOn;
- (void)onLanguageChange;
- (void)beginIgnoringInteractionEvents;
- (void)endIgnoringInteractionEvents;
- (BOOL)shouldReportWifiSsid;
- (BOOL)shouldReportCellInfo;
- (BOOL)shouldReportLocation;
- (void)setReportLocationState:(BOOL)a0 cellInfoState:(BOOL)a1;
- (id)resolveLanguageStringForGlobal:(id)a0;
- (id)resolveURLStringForGlobal:(id)a0;
- (BOOL)supportSecurityStore;
- (BOOL)saveSecurityStore:(id)a0 data:(id)a1;
- (id)loadSecurityStore:(id)a0;
- (BOOL)delSecurityStore:(id)a0;
- (BOOL)isScreenCaptured;
- (id)getAndroidRepairConfig:(id)a0;
- (id)getCachedLocationInfo;
- (id)getCachedLocationInfoForCashier;
- (BOOL)isForAndroidTest;
- (void)getUserLocationImpl:(id)a0;
- (BOOL)isLocationAuthorized;
- (int)getLQTVersion;
- (void)launchFlutter:(BOOL)a0;
- (float)getScreenDensity;
- (BOOL)isFlutterOnTop;
- (void)reportDidTakeScreenshot:(id)a0;
- (id)getAccessibilityServiceList;
- (int)getAccessibilityIsTouchExplorationEnabled;
- (BOOL)isAccessibilityServiceSafe;
- (BOOL)isDarkModeOn;
- (void)setPaySafeAccessibilityServiceListCache:(id)a0 serviceListName:(id)a1;
- (void)reportScreenshotKeyPage:(id)a0 data:(id)a1;
- (void)publishPayLiteAppGlobalEvent:(id)a0;
- (void)preloadLiteApp:(id)a0 path:(id)a1;
- (void)releasePreloadLiteApp:(id)a0 path:(id)a1;
- (id)faceDataDecrypt:(id)a0 key:(id)a1;
- (id)faceDataEncrypt:(id)a0 key:(id)a1;
- (id)md5Data:(id)a0;
- (id)insertZeroWidthJoiner:(id)a0;
- (id)getExptStringValue:(id)a0;
- (int)getClientVersion;
- (id)getDeviceInfoForYuanBaoAd;
- (void)handleAdFeedbackCloseWithAid:(id)a0;
- (void)handleAdOpenWithAid:(id)a0;
- (void)reportAdWithAidAndType:(id)a0;
- (void)saveAdInfoWithPosId:(int)a0 pbDataString:(id)a1;
- (BOOL)getYuanBaoInstalledState;
- (BOOL)getYuanBaoIsForOldUser;
- (void)triggerPrefetchMallIndexWeApp:(id)a0;
- (void).cxx_destruct;

@end
