@interface MMLivePathUtil : NSObject

+ (id)localUsrDirPath;
+ (id)localUsrDirExtendedTempPath;
+ (id)localUsrDirTempPath;
+ (id)localUsrDirBriefTempPath;
+ (id)localUsrLibrary;
+ (id)GetLiveDBPath;
+ (id)GetPathOfLiveSetting;
+ (id)GetBasePathOfLiveSession;
+ (id)GetLiveRewardGiftsDBPath;
+ (id)GetLiveGiftBasePath;
+ (id)GetLiveGiftDownloadTmpPath;
+ (id)GetLiveGiftPath:(id)a0;
+ (id)GetLiveGiftDownLoadPath:(id)a0;
+ (id)GetLiveGiftMagicResBasePath;
+ (id)GetLiveGiftMagicResPath:(id)a0;
+ (id)GetLiveGiftThumbnailFilePath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftThumbnailFileDownLoadPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftPreviewPagFilePath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftPreviewPagFileDownLoadPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftAnimationPagFilePath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftLandscapeAnimationPagFilePath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftForegroundAnimationPagFilePath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftAnchorCustomizeImageFilePath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveMultiGiftAnimationPagFilePath:(id)a0 fileMD5:(id)a1 anmationId:(id)a2;
+ (id)GetLiveMultiGiftLandscapeAnimationPagFilePath:(id)a0 fileMD5:(id)a1 anmationId:(id)a2;
+ (id)GetLiveGiftTextCustomizationPreviewFilePath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftNewCustomizationComponentValueThumbnailFilePath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftAnimationPagFileDownLoadPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftLandscapeAnimationPagFileDownLoadPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftForegroundAnimationPagFileDownLoadPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftAnchorCustomizeImageFileDownLoadPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftTextCustomizationPreviewFileDownLoadPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftNewCustomizationComponentValueThumbnailFileDownLoadPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftInteractionEffectZipDownLoadPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftInteractionEffectFileUnzipPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveGiftInteractionEffectFileCachePath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveMultiGiftLandscapeAnimationPagFileDownLoadPath:(id)a0 fileMD5:(id)a1 anmationId:(id)a2;
+ (id)GetLiveMultiGiftAnimationPagFileDownLoadPath:(id)a0 fileMD5:(id)a1 anmationId:(id)a2;
+ (id)GetLiveAttackGiftWeEffectFileCachePath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveAttackGiftWeEffectFileUnzipPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveAttackGiftWeEffectZipDownLoadPath:(id)a0 fileMD5:(id)a1;
+ (id)GetLiveLotteryBasePath;
+ (id)GetLiveLotteryPath:(long long)a0;
+ (id)GetLiveLotteryPagFilePath:(long long)a0;
+ (id)GetLotteryFilePathNameFrom:(long long)a0;
+ (id)GetLiveMicBasePath;
+ (id)GetLiveMicPkResultWinFilePath;
+ (id)GetLiveMicPkResultDrawFilePath;
+ (id)GetLiveMicPkResultWinningStreakFilePath;
+ (id)GetLiveRandomMicAvatarFilePathWithIndex:(int)a0;
+ (id)GetFinderLiveDBPath;
+ (id)GetMoreLiveDirPath;
+ (id)GetMoreLiveTabsCachePath:(unsigned long long)a0;
+ (id)GetLiveDebugBasePath;
+ (id)GetLiveDebugMockVideoPath;
+ (id)liveAnniversaryDayBasePath;
+ (id)liveAnniversaryDayDownloadPath;
+ (id)localGroupLiveChatUsrDirPath;
+ (id)groupLiveChatBasePath;
+ (id)groupLiveChatSavePath:(id)a0 roomId:(id)a1;
+ (id)groupLiveChatRoomIndexPath:(id)a0;
+ (id)GetLiveActivityResBundleBasePath;
+ (id)liveLegacyActivityResBasePath;
+ (id)liveStaticResourcesTempPathWithType:(unsigned int)a0 subType:(unsigned int)a1 version:(unsigned int)a2;
+ (id)liveStaticResourcesPathWithType:(unsigned int)a0 subType:(unsigned int)a1 version:(unsigned int)a2;
+ (id)GetLiveAdvertisementBaseDir;
+ (id)getAdvertisementTempVideoPath:(id)a0;
+ (id)getAdvertisementFormatVideoPath:(id)a0;
+ (id)GetLiveReplayPreviewVideoBaseDir;
+ (id)getLiveReplayPreviewTempVideoPath:(id)a0;
+ (id)getLiveReplayPreviewFormatVideoPath:(id)a0;
+ (id)liveAudioModeBackgroundLegacyBasePath;
+ (id)liveAudioModeBackgroundBasePath;
+ (id)liveAudioModeAnimatedBackgroundVideoPath;
+ (id)liveReplayStopgapBasePath;
+ (id)liveReplayStopgapDownloadTemporaryPath:(id)a0;
+ (id)liveReplayStopgapDownloadedCachePath:(id)a0;
+ (id)liveResourceDownloaderDefaultBasePath;
+ (id)liveResourceDownloaderDefaultDownloadPath;
+ (id)liveGestureBasePath;
+ (id)liveGestureTempBasePath;
+ (id)liveAnchorDecorationTmpBasePath;
+ (id)liveAnchorDecorationBasePath;
+ (id)liveAnchorVisionEffectsTmpBasePath;
+ (id)liveAnchorVisionEffectsBasePath;
+ (id)liveStickersTempBasePath;
+ (id)liveStickersEphermalBasePath;
+ (id)liveImageUploadingTempBasePath;
+ (id)liveWevisionWidgetsTempBasePath;
+ (id)liveWevisionFaceDetectTempBasePath;
+ (id)liveBottomButtonResDirPath;
+ (id)liveGiftAdHocResourceDownloadWorkingPath;
+ (id)liveGiftAdHocResourceDownloadCachePath;
+ (id)liveGenericResourceFetcherBaseWorkingPath;
+ (id)liveGenericResourceFetcherDownloadWorkingPath;
+ (id)liveFansGroupCustomizableGiftsPreviewPath;
+ (id)liveAnchorCustomizeRewardModifyPagCachePath;
+ (id)liveConcertFluorescencePath;
+ (id)liveFloatMsgResourcePath;
+ (id)liveBatchRewardWevisionTempBasePath;
+ (id)liveGiftAttackWevisionTempBasePath;
+ (id)liveCustomPIPTempleteBasePath;
+ (id)liveGiftInteractionWevisionTempBasePath;
+ (id)liveKTVSongSrcTempBasePath:(id)a0;
+ (id)liveBeautyResourceDownloadPathRoot;
+ (id)liveBeautyResourceDownloadPathWithId:(id)a0;
+ (id)liveBeautyResourceMasterPathRoot;
+ (id)liveBeautyResourceMasterPathWithId:(id)a0;
+ (id)liveBeautyResourceInstancePathWithId:(id)a0;
+ (id)liveBeautyResourceLegacyInstancePath;
+ (id)GetKtvBasePath;
+ (id)GetKtvDownloadTmpPath;
+ (id)GetKtvSongDownloadTmpPath:(id)a0;
+ (id)liveKtvThemeResourcesPathWithUri:(id)a0;
+ (id)liveWeffectBasePath;
+ (id)liveWeffectBodyPosePath;
+ (id)liveWeffectPortraitSegmentPath;
+ (id)liveMiscellaneousTemporaryDirectoryPath;
+ (id)liveLocalMixBackgroundImagePath;

@end
