@class NSMutableDictionary, MMFinderLiveTask, CIContext, NSMutableArray, UIView, MMWeEffectManager, MMLiveTaskId, WCLoopMetricsCollector, NSString, MMWeEffectFrame, NSMutableSet, MMLiveRemoteTrtcCustomRenderComposeV2MetricsMonitor, MMLivePixelBuffer, NSLock, CADisplayLink;

@interface MMLiveRemoteTrtcCustomRenderComposeManagerV2 : NSObject <WeEffectEnergyController, WeEffectManagerResultDelegate>

@property unsigned long long invokeMode;
@property (retain, nonatomic) MMLiveTaskId *liveTaskId;
@property (readonly, nonatomic) MMFinderLiveTask *finderLiveTask;
@property (nonatomic) BOOL enableRCI;
@property (retain, nonatomic) UIView *videoRenderView;
@property (retain, nonatomic) MMWeEffectManager *weeffectManager;
@property (nonatomic) BOOL isAllowFp16;
@property (nonatomic) long long weffectScene;
@property BOOL isWeVisMgrCreated;
@property BOOL isCustomRenderStart;
@property BOOL isFirstFrameRendered;
@property BOOL isStopCustomRender;
@property (retain, nonatomic) NSMutableSet *remoteTrtcCustomRenderSceneSet;
@property (retain, nonatomic) NSMutableDictionary *remoteTrtcCustomRenderContextDict;
@property unsigned int cameraFrameRate;
@property (nonatomic) unsigned int effectFrameRate;
@property (nonatomic) unsigned int effectAccumulator;
@property double localMixVideoVideoWidth;
@property (retain, nonatomic) CADisplayLink *autoInvokeDisplayLink;
@property int autoInvokeRemainFrame;
@property unsigned long long renderFrameCnt;
@property BOOL isRenderPrepareWaitOverTime;
@property (retain, nonatomic) CIContext *tranferContext;
@property (nonatomic) BOOL isLiveCaptureRunning;
@property BOOL isAppResignActive;
@property (retain, nonatomic) CIContext *ciContext;
@property (nonatomic) struct __CVPixelBufferPool { } *pixelBufferPool;
@property (nonatomic) struct CGSize { double width; double height; } pixelBufferPoolSize;
@property (retain, nonatomic) NSLock *contextLock;
@property (retain, nonatomic) NSLock *pixelBufferLock;
@property (retain, nonatomic) MMWeEffectFrame *curMixBackgroundEffectFrame;
@property (nonatomic) unsigned long long curMixBackgroundType;
@property (nonatomic) unsigned long long nextMixBackgroundType;
@property (nonatomic) unsigned int requestBackgroundImageCount;
@property (retain, nonatomic) MMLivePixelBuffer *blackStreamPixelBuffer;
@property (retain, nonatomic) MMLiveRemoteTrtcCustomRenderComposeV2MetricsMonitor *metricsMonitor;
@property (retain, nonatomic) WCLoopMetricsCollector *metricsCollector;
@property (retain, nonatomic) NSMutableArray *composeEndCallbacks;
@property (retain, nonatomic) NSLock *composeEndCallbacksLock;
@property (readonly, nonatomic) UIView *renderView;
@property (readonly, nonatomic) BOOL hasCustomRenderStarted;
@property (nonatomic) double preferScaleRatio;
@property (copy, nonatomic) id /* block */ startCallback;
@property (copy, nonatomic) id /* block */ firstFrameRenderedCallback;
@property (copy, nonatomic) id /* block */ trtcUserFirstFrameRenderedCallback;
@property (copy, nonatomic) id /* block */ willStopCallback;
@property (copy, nonatomic) id /* block */ stopCallback;
@property (copy, nonatomic) id /* block */ weeffectMsgReceiveCallback;
@property (copy, nonatomic) id /* block */ trtcUserRenderStopCallback;
@property (copy, nonatomic) id /* block */ trtcUserRenderReqRenderSizeCallback;
@property (copy, nonatomic) id /* block */ destroyCallback;
@property (copy, nonatomic) id /* block */ requestDisplayImagesCallback;
@property (copy, nonatomic) id /* block */ requestUserListCallback;
@property (copy, nonatomic) id /* block */ checkIsCurrTopPerfLevelCallback;
@property (copy, nonatomic) id /* block */ increasePerfLevelCallback;
@property (copy, nonatomic) id /* block */ decreasePerfLevelCallback;
@property (copy, nonatomic) id /* block */ checkTimeRangeIsFullLoadCallback;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithTaskId:(id)a0 initParam:(id)a1;
- (void)dealloc;
- (void)initDefaultData;
- (void)addComposeEndCallback:(id /* block */)a0;
- (void)removeComposeEndCallback:(id /* block */)a0;
- (unsigned long long)updateTrtcCustomRenderUserList:(id)a0;
- (unsigned long long)addTrtcUserListToCustomRender:(id)a0;
- (BOOL)addTrtcUserToCustomRender:(id)a0;
- (void)removeCustomRenderTrtcUser:(id)a0;
- (void)removeAllCustomRenderTrtcUsers;
- (BOOL)isTrtcUserCustomRender:(id)a0;
- (BOOL)isTrtcUserCustomRenderWithUsrName:(id)a0;
- (unsigned long long)getCustomRenderSrcFormatForTrtcUser:(id)a0;
- (BOOL)hasTrtcCustomRenderUser;
- (BOOL)isTrtcUserFirstFrameRendered:(id)a0;
- (BOOL)isTrtcUserFirstFrameFromCapture:(id)a0;
- (BOOL)hasTrtcUserFirstFrameFromCapture;
- (id)getCustomRenderTrtcUser:(id)a0;
- (id)getTrtcCustomRenderUserIdList;
- (id)getTrtcCustomRenderContextList;
- (void)startCustomRenderWithScene:(unsigned long long)a0;
- (void)stopCustomRenderWithScene:(unsigned long long)a0;
- (void)invokeRender;
- (void)onRefreshPixelBuffer:(struct __CVBuffer { } *)a0 userId:(id)a1;
- (void)onLiveCaptureChanged:(BOOL)a0;
- (void)updateoLcalMixVideoVideoSize:(double)a0;
- (void)updateCameraFrameRate:(unsigned int)a0;
- (void)updateMixBackgroundWithType:(unsigned long long)a0;
- (void)startAutoInvokeRender;
- (void)stopAutoInvokeRender;
- (void)startAutoInvokeDisplayLink;
- (void)stopAutoInvokeDisplayLink;
- (void)autoInvokeWithDisplayLink:(id)a0;
- (void)updateInvokeMode;
- (void)initWeEffectData;
- (void)createWeEffectMananger;
- (void)createVideoRenderView;
- (void)startCustomRender;
- (BOOL)stopCustomRenderWithDelay:(BOOL)a0;
- (void)onCustomRenderStopFinished;
- (void)cancelCustomRenderStop;
- (void)clearData;
- (void)tagFrameRendered:(id)a0;
- (void)notifyFirstFrameRendered;
- (void)notifyTrtcUsersFirstFrameRendered:(id)a0;
- (void)notifyTrtcUsersRenderStop:(id)a0;
- (BOOL)checkAllRenderContextPrepareCompleteIfNeed;
- (void)checkRenderPrepareCompleteWaitOverTime;
- (void)createPixelBufferFromDisplaySurfaceForUnValidRenderContext;
- (void)requestDisplayImagesForUserIdList:(id)a0 completion:(id /* block */)a1;
- (id)createRenderContextForUser:(id)a0;
- (id)getCurrRenderWeeffectFrames;
- (BOOL)addRenderContext:(id)a0 renderFrameList:(id)a1;
- (id)getCurrRenderWeeffectFramesWithSort;
- (BOOL)isCurrentInvokeModeSupportRenderContext:(id)a0;
- (void)onWeeffectFramesProcessCompleted:(id)a0;
- (BOOL)shouldRenderEffect;
- (double)getScaleRatio;
- (void)_render;
- (void)renderFrame:(id)a0 contextList:(id)a1;
- (void)increaseRenderFrame;
- (id)transferImageToPixelbuffer:(id)a0;
- (void)createTransferContextIfNeed;
- (id)getCustomComposeRenderContextWrapper;
- (struct CGSize { double x0; double x1; })getLocalMixOutputSize;
- (struct CGSize { double x0; double x1; })getEffectOutputSize;
- (struct CGSize { double x0; double x1; })updateRenderList:(id)a0 composeOutputSize:(struct CGSize { double x0; double x1; })a1;
- (void)effectMgr:(id)a0 configSettings:(void *)a1;
- (void)effectMgr:(id)a0 adjustSettings:(void *)a1;
- (void)effectMgr:(id)a0 deviceRunPreferByCPU:(BOOL *)a1;
- (void)onWeEffectLuaScriptJsonMessageReceived:(id)a0 fromSourceId:(int)a1;
- (void)onResult:(int)a0;
- (void)onResourceID:(long long)a0;
- (void)onResourceIDVector:(id)a0 scene:(unsigned long long)a1;
- (void)onWeVisEffectMgrCreateCompleted;
- (void)registerNotification;
- (void)unregisterNotification;
- (void)onAppResignActive:(id)a0;
- (void)onAppBecomeActive:(id)a0;
- (id)createCIContext;
- (void)updatePixelBufferPoolWithOutputSize:(struct CGSize { double x0; double x1; })a0;
- (void)clearPixelBufferPool;
- (id)coreImageComposeVedio:(id)a0 outputSize:(struct CGSize { double x0; double x1; })a1;
- (id)cropForImage:(id)a0 targetSize:(struct CGSize { double x0; double x1; })a1;
- (void)updateBackgroundImageIfNeed;
- (void)initMixBackgroundEffectFrame;
- (void)destroyMixBackgroundEffectFrame;
- (void)createBlackStream;
- (void)refreshSelfPixelBufferWithBlackStream;
- (void)initMetricsReportData;
- (void)onRenderBegin;
- (void)onRenderEnd;
- (BOOL)isBeginRenderEffect;
- (BOOL)isBeginRenderLocalMixVideo;
- (BOOL)isBeginRenderGiftAttack;
- (unsigned long long)prepareWaitMaxFrames;
- (double)getWeVisMgrCreateTime;
- (void).cxx_destruct;

@end
