@class LivePAGStatistics, MMLiveReplaySetting, MMLiveStateDataInfoSession, NSMutableDictionary, MMLiveRewardGiftNewCustomizationMagicRewardMemoryManager, MMLiveCDNPlayerItem, MMLiveRemoteTrtcCustomRenderManager, OrderedDictionary, NSError, LiveSdkChannelParams, WCFinderLiveStarterLiveModeSubItem, MMLiveCameraCastingAdapter, MMLiveCaptureAdapter, MMLiveEnergyController, WCLiveBlurBtnPowerModeMonitorLogic, NSMutableArray, MMLiveView, MMLiveMetricsBusinessMonitorLogic, UIView, UINavigationController, MMLiveCdnStreamInfo, MMLivePrepareAdapter, MMLiveBeautyLogic, MMLiveRemoteTrtcCustomRenderComposeManagerV2, MMLiveRemoteTrtcCustomRenderGiftAttackManager, MMLiveMetricsMonitor, MicSetting_PurchaseMicSetting, MMFinderLiveBatchRewardAnimationWeVisionRenderer, MMFinderLiveGiftAttackRenderLogic, TRTCParams, MMLiveFaceDetectLogic, NSData, LiveSdkAudioParams, LiveInfo, MMLiveFaceLogic, MMLiveInteractionGiftRenderLogic, MMLiveRemoteTrtcCustomRenderComposeManager, MMLiveDisplayMonitor, MMFinderLiveCustomPIPHandler, MMLiveWevisionWidgetManageLogic, MMLiveRewardGiftNewCustomizationMagicEngineEnergyManager, NSArray, MMLiveTRTCPushAdapter, MMLiveCdnStreamErrorReportInfo, MMLiveMultiAngleChannelInfo, MMLiveTrtcRenderingNotificationContext, NSString, MMLiveRewardMagicEnginePerformanceStatisticManager, CdnRenderViewBase, MMLiveFaceDecodeLogic, WAApptaskPublicResLogic, MMWeEffectManager, MMLiveFaceTracker, MMLiveUIPerfMonitorLogic, TRTCCloud, MMLiveFaceDetectStatisticLogic, NSDictionary, NSMutableSet, MMFinderLiveModeItem, LiveSdkVideoParams, MMLiveFaceTrackOutputData, MMTimer, MMFinderLiveTask, MMXp2pWrapper, GameTeamUpSpecialGiftSettingDetail, FLVNetworkInfo;
@protocol MMLiveTaskDelegate;

@interface MMLiveTask : MMLiveBaseTask <TRTCCloudDelegate, TRTCVideoRenderDelegate, MMLiveAnchorSEISynchronizeExt, MMLiveMangerPusherDelegate, CNetworkStatusExt, MMXp2pWrapperDelegate, TXPIPManagerExt, CameraScanViewControllerExtention, WeEffectManagerResultDelegate, WeEffectEnergyController, MMLiveTRTCPushAdapterDelegate, MMLiveCaptureAdapterDelegate, MMLivePushAdapterDelegate, MMLiveMetricsMonitorDelegate, MMLiveViewDelegate, MMLiveConflictHandling, MMLiveAnchorSEISynchronizeDelegate>

@property (readonly, nonatomic) MMFinderLiveTask *finderOrNil;
@property (retain, nonatomic) LiveInfo *liveInfo;
@property (retain, nonatomic) TRTCParams *trtcParams;
@property (retain, nonatomic) LiveSdkVideoParams *trtcVideoParams;
@property (retain, nonatomic) LiveSdkAudioParams *trtcAudioParams;
@property (retain, nonatomic) LiveSdkChannelParams *trtcChannelParams;
@property (nonatomic) long long trtcRoleType;
@property (nonatomic) long long nextRoleType;
@property (retain, nonatomic) MMLiveView *liveView;
@property (nonatomic) BOOL isInRoom;
@property (retain, nonatomic) MMTimer *checkExpireTimer;
@property (retain, nonatomic) NSString *sessionId;
@property (nonatomic) unsigned int lastTransEventTime;
@property (nonatomic) unsigned int livePushMode;
@property (nonatomic) BOOL hasCreatedAudioEffectMgrBeforeEnterRoom;
@property (nonatomic) BOOL isDefaultCDNPlay;
@property (retain, nonatomic) NSMutableDictionary *remoteUserVideoInfoDict;
@property (nonatomic) int mMicAbility;
@property (nonatomic) BOOL isVideoParamSetOK;
@property (nonatomic) BOOL isAudioParamSetOK;
@property (nonatomic) BOOL isLocalAudioStarted;
@property (nonatomic) unsigned long long audienceConnectMicStreamMode;
@property (nonatomic) BOOL isAudioConnectedMic;
@property (nonatomic) BOOL isVideoConnectedMic;
@property (nonatomic) BOOL isUsingCamera;
@property (nonatomic) BOOL isCurrentUsingCamera;
@property (nonatomic) unsigned int maxOnlineUserCount;
@property (nonatomic) unsigned long long mCloudAppid;
@property (nonatomic) unsigned long long mCloudBizid;
@property (retain, nonatomic) MMXp2pWrapper *p2pManagerInstance;
@property (nonatomic) unsigned long long frontCameraMirrorMode;
@property (retain, nonatomic) NSMutableArray *lagHistoryQueue;
@property (nonatomic) unsigned int mCDNSwitchCnt;
@property (nonatomic) long long mCDNSwitchMode;
@property (nonatomic) unsigned int enterRoomTime;
@property (nonatomic) unsigned int cdnStartPlayTime;
@property (retain, nonatomic) UIView *connectMicUserVideoView;
@property (nonatomic) BOOL isFrontCamera;
@property (nonatomic) BOOL isFrontCameraMirrored;
@property (nonatomic) BOOL isLiveAfterAbnormalExit;
@property (nonatomic) BOOL isLocalAudioMuted;
@property (nonatomic) BOOL isMicMuted;
@property (retain, nonatomic) MMLiveBeautyLogic *beautyLogic;
@property (nonatomic) unsigned int lastQualityChangeTime;
@property (nonatomic) unsigned long long anchorSEISeq;
@property (nonatomic) BOOL isLiveQosReportEnabled;
@property (nonatomic) BOOL isLiveQosControlEnabled;
@property (nonatomic) BOOL isLivePlayInfoReportEnabled;
@property (nonatomic) BOOL isLivePlayInfoControlEnabled;
@property (nonatomic) BOOL isPlayerReportExtended;
@property (nonatomic) unsigned long long lastSEIReportTime;
@property (nonatomic) unsigned int mSEIMode;
@property (nonatomic) unsigned int mSEIReportInterval;
@property (nonatomic) unsigned int mReTryBackupUrlCnt;
@property (retain, nonatomic) NSArray *seiMicTalkingUsersList;
@property (retain, nonatomic) NSMutableDictionary *lastRecordLiveAudioSessionParams;
@property (nonatomic) int anchorUserTalkingCount;
@property (nonatomic) BOOL hasStartedSyncAnchorSEIUserStatus;
@property (nonatomic) BOOL hasSetPureAudioModeForAudience;
@property (nonatomic) unsigned long long videoEncoderParamMode;
@property (nonatomic) BOOL isAudienceInSwitchRoleProcess;
@property (nonatomic) BOOL isAspectRatio21_10;
@property (nonatomic) long long mCaptureResEnum;
@property (nonatomic) BOOL enableSwitchStream;
@property (nonatomic) BOOL forceHEVCMixing;
@property (nonatomic) BOOL isAllowFp16;
@property (nonatomic) double lastSEILogTime;
@property (nonatomic) BOOL canUsePublishMediaStream;
@property (nonatomic) unsigned long long beginEnterLiveTimestamp;
@property (nonatomic) unsigned long long startCdnPlayTimestamp;
@property (nonatomic) unsigned long long cdnPlayerConnectTimestamp;
@property (nonatomic) unsigned long long realCdnPlayOkTimestamp;
@property (nonatomic) unsigned long long firstShowCdnPlayerViewTimestamp;
@property (nonatomic) unsigned long long firstJoinLiveResponseTimestamp;
@property (nonatomic) BOOL useCachedPlayingDataItemWhenEnterLive;
@property (nonatomic) unsigned int audienceDelayTime;
@property (nonatomic) BOOL cdnPlayerItemHasEverStartedPlay;
@property (nonatomic) BOOL shouldHideLoadingForUsingCachedCdnPlayerItem;
@property (retain, nonatomic) NSString *lastServerIP;
@property (retain, nonatomic) OrderedDictionary *multiAngleChannelInfoDict;
@property (nonatomic) double lastMultiAnglePanGestureTranslationX;
@property (nonatomic) double lastMultiAnglePanGestureMovedDistanceX;
@property (nonatomic) struct CGPoint { double x; double y; } multiAnglePanGestureBeganLocation;
@property (nonatomic) BOOL shouldUpdateChannelInfoDictAfterSwitchChannel;
@property (nonatomic) BOOL shouldStartPlayForResume;
@property (nonatomic) BOOL isAllLiveAngleSupportRotate;
@property (retain, nonatomic) MMLiveMetricsMonitor *metricsMonitor;
@property (retain, nonatomic) MMLiveEnergyController *energyController;
@property (retain, nonatomic) MMLiveDisplayMonitor *displayMonitor;
@property (retain, nonatomic) NSDictionary *anchoTimeJsonContent;
@property (retain, nonatomic) MMTimer *anchorTTimer;
@property (nonatomic) BOOL isLiveAnchorPausedForOuter;
@property (retain, nonatomic) WCLiveBlurBtnPowerModeMonitorLogic *blurBtnPownerModeMonitorLogic;
@property (nonatomic) long long currentResourceObjectId;
@property (retain, nonatomic) MMLiveWevisionWidgetManageLogic *wevisionWidgetManageLogic;
@property (nonatomic) BOOL previewLocalCameraOn;
@property (retain, nonatomic) MMLiveRewardGiftNewCustomizationMagicRewardMemoryManager *magicRewardMemoryManager;
@property (retain, nonatomic) MMLiveRewardGiftNewCustomizationMagicEngineEnergyManager *magicEngineEnergyManager;
@property (nonatomic) long long cdnAudienceWeEffectScene;
@property (retain, nonatomic) MMLiveRemoteTrtcCustomRenderManager *remoteTrtcCustomRenderManager;
@property (retain, nonatomic) MMLiveRemoteTrtcCustomRenderComposeManager *remoteTrtcCustomComposeManager;
@property (retain, nonatomic) MMLiveFaceDetectLogic *faceDetectLogic;
@property (retain, nonatomic) MMLiveFaceDecodeLogic *faceDecodeLogic;
@property (retain, nonatomic) MMLiveRewardMagicEnginePerformanceStatisticManager *magicEnginePerformanceStatisticManager;
@property (retain, nonatomic) NSMutableDictionary *remoteTrtcCustomRenderWrapperDict;
@property (retain, nonatomic) MMLiveFaceLogic *faceLogic;
@property (nonatomic) long long currAudioRoute;
@property (nonatomic) BOOL isAudioRouteSetted;
@property (retain, nonatomic) MMLiveMetricsBusinessMonitorLogic *metricsBusinessMonitorLogic;
@property (nonatomic) BOOL isCdnProcessByWeeffect;
@property (retain, nonatomic) LivePAGStatistics *livePAGStatistics;
@property (retain, nonatomic) MMLiveFaceDetectStatisticLogic *faceDetectStatisticLogic;
@property (nonatomic) long long currExitState;
@property (nonatomic) BOOL isLiveAudioAuthorityUnActive;
@property (retain, nonatomic) MMLiveFaceTracker *faceTracker;
@property (retain, nonatomic) MMLiveRemoteTrtcCustomRenderComposeManagerV2 *remoteTrtcCustomComposeManagerV2;
@property (retain, nonatomic) MMLiveRemoteTrtcCustomRenderGiftAttackManager *remoteTrtcCustomRenderGiftAttackManager;
@property (nonatomic) unsigned int lastCdnQuality;
@property (nonatomic) BOOL enableBackgroundDecoding;
@property (weak, nonatomic) CdnRenderViewBase *barrageMaskRenderView;
@property (readonly, nonatomic) MMLiveCaptureAdapter *liveCaptureInstance;
@property (retain, nonatomic) MMLivePrepareAdapter *prepareAdapter;
@property (retain, nonatomic) MMLiveCameraCastingAdapter *cameraCastingAdapter;
@property (retain, nonatomic) MMLiveTRTCPushAdapter *pushAdapter;
@property (retain, nonatomic) MMLiveMultiAngleChannelInfo *currentChannelInfo;
@property (retain, nonatomic) MMLiveMultiAngleChannelInfo *nextChannelInfo;
@property (nonatomic) BOOL hasEverShownMultiAngle;
@property (retain, nonatomic) MMLiveCdnStreamInfo *audioModeCdnStreamInfo;
@property (retain, nonatomic) MMLiveCdnStreamInfo *lastCdnStreamInfo;
@property (retain, nonatomic) NSMutableDictionary *cdnStreamInfoDict;
@property (retain, nonatomic) NSMutableArray *displayedCdnStreamQualityTagList;
@property (retain, nonatomic) NSMutableArray *allCdnStreamQualityTagList;
@property (retain, nonatomic) NSData *qualityTagCacheBuf;
@property (retain, nonatomic) MMLiveCdnStreamErrorReportInfo *cdnStreamErrorReportInfo;
@property (nonatomic) unsigned int streamAbnormalFlag;
@property (retain, nonatomic) NSMutableArray *seiReportInfoList;
@property (nonatomic) BOOL hasShownVideoZoomGuideView;
@property (readonly, nonatomic) BOOL needStopRenderBufferInLiveRoom;
@property (nonatomic) unsigned long long audienceLiveState;
@property (nonatomic) BOOL notifyLiveClosed;
@property (nonatomic) BOOL notifyExitLive;
@property (nonatomic) unsigned long long anchorMainPreLiveOrientationMask;
@property (nonatomic) unsigned long long anchorMainOrientationMask;
@property (nonatomic) long long anchorMainDisplayMode;
@property (nonatomic) unsigned int ktvVolumeStrategyFlag;
@property (nonatomic) int mCaptureFps;
@property (readonly, nonatomic) WCFinderLiveStarterLiveModeSubItem *selectSubItem;
@property (readonly, nonatomic) MMFinderLiveModeItem *selectedModeItem;
@property (nonatomic) struct CGSize { double width; double height; } remoteVideoFrameSize;
@property (nonatomic) struct CGSize { double width; double height; } localVideoFrameSize;
@property (nonatomic) unsigned int videoFPS;
@property (nonatomic) unsigned int renderFPS;
@property (nonatomic) unsigned long long currentLiveState;
@property (nonatomic) BOOL secondaryDeviceCloseLiveSwitch;
@property (weak, nonatomic) id<MMLiveTaskDelegate> delegate;
@property (readonly, nonatomic) TRTCCloud *trtcInstance;
@property (readonly, nonatomic) MMLiveCDNPlayerItem *currentCdnPlayerItem;
@property (readonly, nonatomic) MMLiveCDNPlayerItem *nextCdnPlayerItem;
@property (readonly, copy, nonatomic) NSString *anchorIdentityId;
@property (readonly, nonatomic) BOOL hasEverEnteredRoom;
@property (readonly, nonatomic) BOOL isAudienceWithoutMic;
@property (readonly, nonatomic) BOOL isWaGameLive;
@property (readonly, nonatomic) unsigned int liveStartTime;
@property (readonly, nonatomic) BOOL useP2P;
@property (readonly, nonatomic) BOOL enableP2P;
@property (nonatomic) BOOL cdnPlayerItemP2PSwitchDidChanged;
@property (nonatomic) BOOL isFaceVerifying;
@property (nonatomic) BOOL isTakingLivePhoto;
@property (nonatomic) BOOL isUsedAfterLiveExited;
@property (nonatomic) BOOL willExit;
@property (nonatomic) BOOL isExit;
@property (nonatomic) BOOL isExitLiveByMorphTransition;
@property (nonatomic) BOOL shouldLiveKeepAudioEnabledAfterMorphDismiss;
@property (readonly, nonatomic) BOOL isLivePause;
@property (nonatomic) BOOL isLivePaused;
@property (nonatomic) BOOL isLiveUnablePlay;
@property (nonatomic) BOOL isLivePausedByPIP;
@property (nonatomic) BOOL isLivePausedForClosePIP;
@property (nonatomic) BOOL isLivePausedForEnterBackground;
@property (nonatomic) BOOL isLivePausedForPaidLiveTrialTimeup;
@property (nonatomic) BOOL isLivePausedForPaidLiveScreenCapturing;
@property (nonatomic) BOOL isLivePausedByMinimizeWindow;
@property (nonatomic) BOOL isLivePausedForOuter;
@property (nonatomic) BOOL isLivePausedForSysIntterupt;
@property (nonatomic) BOOL isLivePausedByHomepagePlayer;
@property (readonly, nonatomic) BOOL isLiveMute;
@property (nonatomic) BOOL isLiveMuteForIntterupt;
@property (nonatomic) BOOL isLiveMuteForSysIntterupt;
@property (nonatomic) BOOL isLiveMuteForOuter;
@property (nonatomic) BOOL isLiveMuteForAdVideo;
@property (nonatomic) BOOL isLiveMuteForLeaveToAppGame;
@property (nonatomic) BOOL isLiveMuteForErrorPage;
@property (nonatomic) BOOL isReleaseMonoService;
@property (nonatomic) long long livePlayStatusForAudience;
@property (nonatomic) long long livePauseStatus;
@property (nonatomic) unsigned long long livePauseTime;
@property (nonatomic) unsigned long long liveStartPlayTimeMs;
@property (nonatomic) unsigned long long liveRecvIframeTimeMs;
@property (nonatomic) BOOL isAnchorOpenAfterCrash;
@property (readonly, nonatomic) BOOL isOnlineStateButtonDisabled;
@property (nonatomic) BOOL isAllowLiveReward;
@property (nonatomic) BOOL isAllowFreeTalk;
@property (nonatomic) BOOL isAllowConnectMic;
@property (nonatomic) BOOL isAllowPaidConnectMic;
@property (nonatomic) BOOL isFocusOnInNormalConnectMicPrelive;
@property (retain, nonatomic) MicSetting_PurchaseMicSetting *purchaseMicSettingBeforeLive;
@property (nonatomic) BOOL isPreBanComment;
@property (nonatomic) BOOL isPreBanBigEmoticonComment;
@property (nonatomic) BOOL isPreBanLike;
@property (nonatomic) BOOL isPreOpenGloryList;
@property (nonatomic) BOOL isBanLikeStatusChanged;
@property (nonatomic) BOOL isPreHiddenAudienceName;
@property (nonatomic) BOOL isEnableLiveSongs;
@property (nonatomic) BOOL isPreOpenSkinSeg;
@property (nonatomic) BOOL isAllowSettingBGMusic;
@property (nonatomic) BOOL isPreEnableGiftWall;
@property (nonatomic) BOOL isPreEnableAnchorRealtimeDataPanel;
@property (retain, nonatomic) GameTeamUpSpecialGiftSettingDetail *specialGiftSetting;
@property unsigned int curJoinTeamMode;
@property (nonatomic) BOOL isPreEnableAiAssistant;
@property (retain, nonatomic) MMLiveReplaySetting *liveReplaySettingBeforeLive;
@property (nonatomic) BOOL isPreAllowProductQuestion;
@property (readonly, nonatomic) BOOL isEnableGiftWall;
@property (readonly, nonatomic) BOOL isTryViewLive;
@property (readonly, nonatomic) BOOL isAudienceConnectingMic;
@property (readonly, nonatomic) BOOL isAudienceWaitingConnectMicResult;
@property (readonly, nonatomic) BOOL isVideoEnabled;
@property (readonly, nonatomic) BOOL isAudioEnabled;
@property (readonly, nonatomic) BOOL isPushAdapterExisted;
@property (readonly, nonatomic) BOOL isInVideoZoomDisplayMode;
@property (readonly, nonatomic) float currentVideoDisplayScale;
@property (nonatomic) BOOL isApplyOrConnectingMicWithOtherAnchor;
@property (nonatomic) unsigned int onlineUserCount;
@property (nonatomic) unsigned int liveNewFansCount;
@property (nonatomic) BOOL isRulePoped;
@property (nonatomic) unsigned int applyConnectMicCount;
@property (nonatomic) unsigned int connectMicSuccCount;
@property (retain, nonatomic) NSMutableDictionary *operationReportInfo;
@property (retain, nonatomic) NSError *liveError;
@property (nonatomic) long long currTransitionState;
@property (retain, nonatomic) NSString *currentWeAppId;
@property (retain, nonatomic) NSMutableSet *currentPrehotWeAppIds;
@property (readonly, nonatomic) NSString *conflictWording;
@property (retain, nonatomic) UINavigationController *navigationController;
@property (readonly, nonatomic) unsigned int liveStartPlayTime;
@property (readonly, nonatomic) unsigned int livePlayTime;
@property (nonatomic) unsigned long long userTapOpenLiveTimestamp;
@property (nonatomic) unsigned int mCdnH265BackCfg;
@property (nonatomic) unsigned int cdnQualitySvrcfg;
@property (nonatomic) BOOL useABRCfg;
@property (nonatomic) unsigned int lastVideoStreamCdnQuality;
@property (nonatomic) unsigned int lastCdnQualitySwitchTime;
@property (nonatomic) long long cdnQualitySwitchCount;
@property (nonatomic) long long cdnQualityReduceCount;
@property (nonatomic) unsigned int isEnterroomFisrtTime;
@property (nonatomic) unsigned int supportHEVCDec;
@property (nonatomic) BOOL isInBackgroundFlag;
@property (nonatomic) BOOL hasSwitchedStreamByQosControl;
@property (readonly, nonatomic) BOOL isUsingUltraWideCamera;
@property (readonly, nonatomic) BOOL isHDRLiveRoom;
@property (nonatomic) BOOL isHEVCEncEnable;
@property (nonatomic) BOOL isHEVCEncUsing;
@property (retain, nonatomic) NSString *enterLiveLoadingText;
@property (readonly, nonatomic) BOOL isCaptureRes1920x1440Enable;
@property (readonly, nonatomic) BOOL isCaptureRes2560x1440Enable;
@property (readonly, nonatomic) BOOL isCaptureRes2560x1440EnableTag;
@property (readonly, nonatomic) BOOL isInConnectedMicUI;
@property (readonly, nonatomic) BOOL canUseVideoRatio10To21;
@property (readonly, nonatomic) BOOL canUseExtVideoRes;
@property (readonly, nonatomic) BOOL canUse2KResBitrate;
@property (readonly, nonatomic) BOOL isEnableHQByDevice;
@property (readonly, nonatomic) BOOL isEnable2KByDevice;
@property (nonatomic) BOOL useCustomVideoEncodeResolution;
@property (nonatomic) struct CGSize { double width; double height; } customVideoEncodeResolution;
@property (retain, nonatomic) NSData *lastSeiMsg;
@property (retain, nonatomic) NSData *anchorSeiMsgData;
@property (nonatomic) BOOL isAntiAddictPause;
@property (readonly, nonatomic) unsigned long long displayedCdnStreamCount;
@property (copy, nonatomic) NSMutableArray *channelParamsDesc;
@property (readonly, nonatomic) unsigned long long allMultiAngleChannelInfoCount;
@property (readonly, nonatomic) unsigned long long currentChannelIndex;
@property (nonatomic) BOOL ignoreCacheClarity;
@property (nonatomic) BOOL localSwitchCdnOrTrtc;
@property (nonatomic) unsigned int stopLocalConnectMicTime;
@property (readonly, nonatomic) BOOL isCurrentAnchorPushingVideo;
@property (retain, nonatomic) NSString *pendingWeAppId;
@property (retain, nonatomic) NSString *recentWeAppId;
@property (retain, nonatomic) NSString *liveDescription;
@property (nonatomic) unsigned int liveVrType;
@property (nonatomic) unsigned int lastQosReportTime;
@property (nonatomic) unsigned int mQosReportInterval;
@property (readonly, nonatomic) BOOL isLiveAndPushViaTrtc;
@property (readonly, nonatomic) BOOL hasAudienceBackgroundMusic;
@property (readonly, nonatomic) BOOL isSupportMultiAngleView;
@property (readonly, nonatomic) BOOL isSupportAndShowingMultiAngleView;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } nextAngleVideoSize;
@property (retain, nonatomic) WAApptaskPublicResLogic *weappResLogic;
@property (retain, nonatomic) MMWeEffectManager *weeffectManager;
@property (weak, nonatomic) MMFinderLiveGiftAttackRenderLogic *giftAttackRenderLogic;
@property (weak, nonatomic) MMFinderLiveBatchRewardAnimationWeVisionRenderer *batchRewardAnimationWeVisionRenderer;
@property (retain, nonatomic) MMWeEffectManager *cdnAudienceWeEffectManager;
@property (retain, nonatomic) MMLiveTrtcRenderingNotificationContext *trtcRenderingNotificationContext;
@property (nonatomic) unsigned long long currentResourceID;
@property (retain, nonatomic) NSMutableDictionary *currentResourceIdDict;
@property (readonly, nonatomic) NSString *anchorNickname;
@property (weak, nonatomic) MMLiveInteractionGiftRenderLogic *interactionGiftRenderLogic;
@property (readonly, nonatomic) MMLiveUIPerfMonitorLogic *uiPerfMonitorLogic;
@property (nonatomic) int enableHostDenoise;
@property (nonatomic) int enableHostClarity;
@property (retain, nonatomic) FLVNetworkInfo *flvNetWorkInfo;
@property (retain, nonatomic) MMLiveStateDataInfoSession *stateInfoSession;
@property long long cacheCdnPixelBufferOptions;
@property (readonly, nonatomic) BOOL isPcCameraCasting;
@property (nonatomic) BOOL joinLiveProcessInDispatchMode;
@property (nonatomic) double last3rdOrSysCallbackInterruptTime;
@property (nonatomic) double lastPauseLiveByPIPTime;
@property (nonatomic) BOOL debug_enableLikeAnimation;
@property (nonatomic) BOOL debug_enableCommentNotifyAnimation;
@property (nonatomic) BOOL debug_enableGiftNotificationAnimation;
@property (nonatomic) BOOL debug_enableGiftPagAnimation;
@property (nonatomic) BOOL debug_enableBannerAnimation;
@property (nonatomic) BOOL isRecordLive;
@property (readonly, nonatomic) BOOL useCustomPIP;
@property (readonly, nonatomic) BOOL isLiveAudioAuthorityActive;
@property (weak, nonatomic) MMFinderLiveCustomPIPHandler *customPIPHandler;
@property (retain, nonatomic) MMLiveFaceTrackOutputData *faceTrackOutputData;
@property (readonly, nonatomic) unsigned long long currAnchorMainOrientationMask;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)updateCrashAttachInfoWithLiveId:(unsigned long long)a0 userType:(long long)a1 tab:(id)a2;
+ (void)updateMetricsReportInfoWithLiveId:(unsigned long long)a0 userType:(long long)a1 liveTask:(id)a2;
+ (void)updateLastTaskInfo:(id)a0;
+ (BOOL)isLiveVideoLocalHorizontalWithDisplayScene:(unsigned long long)a0;

- (BOOL)isEnableLocalMixVideo;
- (void)updateLocalMixVideoCameraFrameRate:(unsigned int)a0;
- (void)initBackgroundImageResourceManager;
- (id)getCurrTrtcCustomRenderUserListV2;
- (void)configCallbacksForCustomComposeManagerV2:(id)a0;
- (void)createComposeManagerV2;
- (void)createGiftAttackManager;
- (void)updateILinkHasWaitConnectMicAudience:(BOOL)a0;
- (void)showAlert:(id)a0;
- (void)showAlert:(id)a0 actionBlock:(id /* block */)a1;
- (void)showToast:(id)a0;
- (void)showConfirm:(id)a0 message:(id)a1 confirmTitle:(id)a2 confirmBlock:(id /* block */)a3;
- (void)showConfirm:(id)a0 confirmTitle:(id)a1 confirmBlock:(id /* block */)a2;
- (void)showAlertInLive:(id)a0;
- (void)showAlertInLive:(id)a0 actionBlock:(id /* block */)a1;
- (void)showToastInLive:(id)a0;
- (void)showConfirmInLive:(id)a0 message:(id)a1 confirmTitle:(id)a2 confirmBlock:(id /* block */)a3;
- (void)showConfirmInLive:(id)a0 confirmTitle:(id)a1 confirmBlock:(id /* block */)a2;
- (void)setExtraReportMMInfo:(id)a0;
- (id)extraReportMMInfo;
- (id)initWithRoleType:(long long)a0 liveId:(unsigned long long)a1 andAnchorId:(id)a2;
- (id)initPrimitiveLiveWithRoleType:(long long)a0 liveId:(unsigned long long)a1 andAnchorId:(id)a2;
- (void)initFrontCameraMirrorMode;
- (void)dealloc;
- (void)clearSharedInstance;
- (void)clearForExit;
- (void)updateTrtcRoleType;
- (BOOL)isLiveClosed;
- (id)anchorIdentityId;
- (BOOL)isSameToTask:(id)a0;
- (BOOL)resolveConflictsWithLiveTask:(id)a0 navigationController:(id)a1 maximizeLiveBlock:(id /* block */)a2 switchLiveBlock:(id /* block */)a3;
- (BOOL)resolveExternalConflicts;
- (BOOL)handleConflictWithNewLive:(id)a0 navigationController:(id)a1;
- (BOOL)handleConflictWithNewFinderLiveContentVMs:(id)a0 exportIds:(id)a1 selectedIndex:(id)a2 navigationController:(id)a3 tabType:(long long)a4 commentScene:(int)a5 replayEntryType:(id)a6 useVerticalFullscreenMinimization:(BOOL)a7 routeParam:(id)a8;
- (BOOL)handleConflictForShowMinimizeWindowWithNewFinderDataItems:(id)a0 exportIds:(id)a1 selectedIndex:(id)a2 navigationController:(id)a3 tabType:(long long)a4 commentScene:(int)a5 replayEntryType:(id)a6 useVerticalFullscreenMinimization:(BOOL)a7 routeParam:(id)a8;
- (BOOL)handleConflictForCollapseMinimizeWindowWithNewFinderDataItems:(id)a0 exportIds:(id)a1 selectedIndex:(id)a2 navigationController:(id)a3 tabType:(long long)a4 commentScene:(int)a5 replayEntryType:(id)a6 useVerticalFullscreenMinimization:(BOOL)a7 routeParam:(id)a8;
- (void)showConflictAlertForLiving;
- (id)getConflictWording;
- (long long)trtcRoleTypeFromMMLiveRoleType:(long long)a0;
- (void)initWeeffectManager;
- (void)initCdnAudienceWeEffectManagerWithScene:(long long)a0;
- (void)destroyCdnAudienceWeEffectManager;
- (void)switchCamera;
- (void)switchCameraWithCompletionHandler:(id /* block */)a0;
- (void)updateDefaultIsFrontCamera:(BOOL)a0;
- (void)updateIsFrontCameraAndCachedValue:(BOOL)a0;
- (void)switchMirrorMode;
- (void)updateMirrorMode;
- (void)initBeautyLogicWithBeautyPackage:(id)a0;
- (void)initFaceDetectLogic;
- (id)lastCameraModeCachedKey;
- (void)initAbnormalState;
- (void)updateCameraModeCachedValue;
- (void)checkCachedValueAndSwitchCamera;
- (void)checkCachedValueAndUpdateFrontCameraMirrored;
- (void)updateFrontCameraMirroredCachedValue;
- (void)updateMicMutedCachedValue;
- (void)checkMicMutedCachedValue;
- (void)updatePauseStatusCachedValue;
- (void)checkPauseStatusCachedValue;
- (BOOL)sdkUserIsAnchor:(id)a0;
- (id)anchorSdkUserId;
- (void)startLocalVideo;
- (void)startLocalVideoWithView:(id)a0;
- (void)startPreviewLocalVideoForConnectMicAudienceWithView:(id)a0;
- (void)stopPreviewLocalVideoForConnectMicAudience;
- (void)startPreviewLocalVideoWithView:(id)a0;
- (void)stopPreviewLocalVideo;
- (void)updateCameraConfigs;
- (void)stopLocalVideo;
- (void)updateLocalVideoWithOpen:(BOOL)a0;
- (void)startRemoteViewWithUserId:(id)a0;
- (void)stopRemoteViewWithUserId:(id)a0;
- (void)switchRoleType:(long long)a0;
- (BOOL)isVideoPusher;
- (void)updateSEIMode:(unsigned int)a0;
- (void)updateLiveInfo:(id)a0;
- (void)updateAnchorStatus:(id)a0;
- (BOOL)checkIsConnectMicAudioAllowed;
- (BOOL)checkIsConnectMicVideoAllowed;
- (BOOL)useNewCloudMixtureStrategy;
- (void)updateCanUsePublishMediaStream:(BOOL)a0;
- (BOOL)updateLiveSdkInfo:(id)a0 liveInfo:(id)a1 partialUpdate:(BOOL)a2;
- (BOOL)updateLiveSdkInfo:(id)a0 liveInfo:(id)a1 partialUpdate:(BOOL)a2 forceUseCdnPlay:(BOOL)a3 updateVideoFrameAnimated:(BOOL)a4;
- (void)handleLiveSdkInfoAllValueUpdated:(id)a0;
- (BOOL)updateLivePushMode:(unsigned int)a0;
- (void)checkAndUpdateMultiAngleChannelInfoDict;
- (BOOL)updateLiveSdkInfo:(id)a0 partialUpdate:(BOOL)a1;
- (void)setTRTCHevcEncode:(BOOL)a0;
- (BOOL)isHEVCEncSupportedLocal;
- (void)updateLiveSDKAVParams:(id)a0 audioParams:(id)a1;
- (void)updatePushAudioVolumeType;
- (void)configPushAudioVolumeType;
- (long long)getCurrAudioVolumeType;
- (void)updateVideoEncoderParamWithSdkVideoParams:(id)a0 checkKitchen:(BOOL)a1;
- (void)limitCaptureRenderFpsAndResolutionWithEncParam:(id)a0;
- (struct CGSize { double x0; double x1; })getRequireVideoRenderSizeWithEncParam:(id)a0;
- (void)cancelLimitCaptureRenderFpsAndResolution;
- (void)set2kResolutionScale;
- (void)checkVideoEncoderParamModeAndUpdateVideoEncConfig:(id)a0 withSdkVideoParams:(id)a1;
- (void)updateVideoEncoderResMode;
- (void)updateTrtcPrivateMapKey:(id)a0;
- (BOOL)clearLiveSdkInfo;
- (id)getCurrentDisplayedCdnStreamList;
- (id)getCurrentCdnStreamInfo;
- (id)getCdnStreamInfoWithQualityTag:(unsigned int)a0;
- (id)getCdnStreamInfoWithVideoQualityLevel:(int)a0;
- (id)getCurrentCdnStreamInfoDict;
- (unsigned int)getCdnPlayLevelWithQualityTag:(unsigned int)a0;
- (void)updateMutilAnglePushLiveSdkInfo:(id)a0;
- (void)deleteMutilAngleWithStreamInfo:(id)a0;
- (void)updateCdnStreamAndClarityWithLiveSdkParams:(id)a0;
- (void)updateTRTCCloudMixtureParams;
- (void)setVideoEnabled:(BOOL)a0;
- (void)setVideoEnabledWithoutDestroyRender:(BOOL)a0;
- (void)setVideoMuted:(BOOL)a0;
- (void)checkAndUpdateVideoMuteImageForAudioMode;
- (void)setVideoMuteImage:(id)a0 fps:(long long)a1;
- (void)setAudioEnabled:(BOOL)a0;
- (void)setAudioMuted:(BOOL)a0;
- (void)setMicMuted:(BOOL)a0;
- (int)getCurrVoiceVolume;
- (void)updateCurrVoiceVolume;
- (void)setVoiceVolume:(long long)a0;
- (id)micMutedCachedKey;
- (void)setTrtcUser:(id)a0 isVideoEnabled:(BOOL)a1;
- (void)setTrtcUser:(id)a0 isAudioEnabled:(BOOL)a1;
- (void)setTrtcUser:(id)a0 isVideoMuted:(BOOL)a1;
- (void)setTrtcUser:(id)a0 isAudioMuted:(BOOL)a1;
- (id)getRemoteUserConfig:(id)a0;
- (void)addOrUpdateRemoteUser:(id)a0 withRoomId:(id)a1;
- (void)removeRemoteTrtcUser:(id)a0;
- (BOOL)isRemoteUserInTrtcRoom:(id)a0;
- (id)getMutableRemoteUsersDict;
- (void)enterLiveRoom;
- (BOOL)canEnableLocalCapture;
- (void)exitLiveRoom;
- (void)checkAndUpdateVideoConfigForConnectMicAudience;
- (void)localConnectMicWithStreamMode:(unsigned long long)a0 liveSdkInfo:(id)a1 nextVideoEncoderParamMode:(unsigned long long)a2;
- (BOOL)changeConnectMicStreamMode:(unsigned long long)a0 withMicUserUIType:(unsigned long long)a1;
- (unsigned long long)getVideoEncoderParamModeByMicUserUIType:(unsigned long long)a0;
- (void)stopLocalConnectMic;
- (void)startLocalVideoForConnectMic;
- (void)startSendVideoForConnectMic;
- (void)stopVideoForConnectMic;
- (void)updateConnectMicUserVideoView:(id)a0;
- (void)localConnectRoom:(id)a0 withUserId:(id)a1 sdkNewPkSign:(id)a2 andPkSign:(id)a3;
- (void)stopLocalConnectRoom:(id)a0;
- (void)stopAudioForConnectMic;
- (BOOL)startLocalAudioForConnectMic;
- (BOOL)startSendAudioForConnectMic;
- (void)checkAndStartSyncConnectMicSEIForAnchor;
- (void)setDefalutPlayMode:(BOOL)a0;
- (void)stopCdnPlayer;
- (void)releaseCdnPlayer;
- (void)releaseCdnPlayerForExitLive:(BOOL)a0;
- (void)releaseWeEffectCapture;
- (void)tryReleaseFlutterEngineGroup;
- (void)removeCdnPlayerItemForExitLive:(BOOL)a0;
- (void)pauseCdnPlayer;
- (void)resumeCdnPlayer;
- (BOOL)muteCdnPlayer;
- (BOOL)unmuteCdnPlayer;
- (BOOL)updateAllRemoteUsersAudioMuted:(BOOL)a0;
- (BOOL)updateAllRemoteUsersVideoMuted:(BOOL)a0;
- (BOOL)setCdnPlayerVolume:(long long)a0 business:(long long)a1;
- (BOOL)unSetCdnPlayerVolume:(long long)a0;
- (void)enableBackgroundDecoding:(BOOL)a0;
- (void)enableTrtcBackgroundDecoding:(BOOL)a0;
- (void)enableCDNBackgroundDecoding:(BOOL)a0;
- (void)requestARGBColorAtNormalizedCoordinateList:(id)a0 fromRectWithSize:(struct CGSize { double x0; double x1; })a1 callback:(id /* block */)a2;
- (void)requestCdnARGBColorAtNormalizedCoordinateList:(id)a0 fromRectWithSize:(struct CGSize { double x0; double x1; })a1 callback:(id /* block */)a2;
- (void)requestYUVColorAtNormalizedCoordinateList:(id)a0 fromRectWithSize:(struct CGSize { double x0; double x1; })a1 callback:(id /* block */)a2;
- (void)requestCdnYUVColorAtNormalizedCoordinateList:(id)a0 fromRectWithSize:(struct CGSize { double x0; double x1; })a1 callback:(id /* block */)a2;
- (void)disableCdnRenderPixelBuffer;
- (void)enableCdnRenderPixelBuffer;
- (BOOL)isCurrentEnableCdnRenderPixelBuffer;
- (struct __CVBuffer { } *)getCurrentCdnPixelBufferRef;
- (void)updateNeedCacheRecentCdnPixelBuffer;
- (void)updateBarrageMaskRenderView:(id)a0;
- (id)getCdnRenderContext;
- (BOOL)configCdnWeEffectManagerWithScene:(long long)a0;
- (BOOL)updateCdnRenderNeedProcessByWeffect:(BOOL)a0 scene:(long long)a1;
- (void)updateCurrCdnProcessByWeeffect:(BOOL)a0;
- (void)handleCdnRenderWeffectProcessForPlayerItemChange:(id)a0 newPlayerItem:(id)a1;
- (BOOL)needCdnProcessByWeffect;
- (BOOL)isCdnPlayerEnableRci;
- (id)getSelfSdkUserId;
- (id)directGetSelfSdkUserId;
- (BOOL)enableRci;
- (void)setIdleTimeDisableIfNeed;
- (void)setExitStateFlag:(unsigned long long)a0;
- (void)clearExitStateFlag:(unsigned long long)a0;
- (void)onExitStateChanged;
- (void)checkLiveAudioAuthorityActiveState;
- (void)updateLiveAudioAuthorityActive:(BOOL)a0;
- (BOOL)onBaseAdapterAudioSessionCategoryCheckCanSet:(id)a0;
- (void)onBaseAdapterAudioSessionCategoryWillSet:(id)a0;
- (void)onBaseAdapterAudioSessionCategoryDidSet:(id)a0;
- (BOOL)isOpenA2dpBluetoothMode;
- (void)updateKTVVolumeStrategyFlag;
- (long long)getTrtcVolumeTypeStrategy;
- (long long)transferStrategyFlagToStrategy:(long long)a0;
- (BOOL)isCurrentInMic;
- (void)setTrtcCapturedAudioFrameDelegateFormat:(id)a0;
- (BOOL)updateRemoteTrtc:(id)a0 renderByCustom:(BOOL)a1 scene:(long long)a2;
- (void)stopCustomRenderForAllRemoteTrtcUsers;
- (id)getRemoteTrtcCustomRenderWrapper:(id)a0 scene:(long long)a1 autoCreateIfNotExist:(BOOL)a2;
- (id)getRemoteTrtcCustomRenderManagerAutoCreateIfNotExist:(BOOL)a0;
- (void)configCallbacksForCustomRenderWrapper:(id)a0;
- (id)getRemoteTrtcCustomRenderWeefectManager:(id)a0 scene:(long long)a1;
- (BOOL)updateTrtcCustomComposeIfOverMaxSupportCnt;
- (void)makeAllGiftAttackRenderSupportByTrtcCustomCompose;
- (void)makeFaceRectVisibleAboveSheetView:(id)a0;
- (void)setIsMakeFaceRectVisibleMode:(BOOL)a0 offsetY:(double)a1;
- (BOOL)checkAllGiftAttackRenderSupportByTrtcCustomCompose;
- (id)getCurrTrtcCustomRenderUserList;
- (void)onMicUserViewInfoDicUpdated;
- (BOOL)updateRemoteTrtcComposeByCustom:(BOOL)a0 scene:(long long)a1;
- (void)cancelRemoteTrtcCustomComposeWithUser:(id)a0;
- (void)destroyCustomComposeRender;
- (id)getRemoteTrtcCustomComposeManagerWithScene:(long long)a0 autoCreateIfNotExist:(BOOL)a1;
- (void)configCallbacksForCustomComposeManager:(id)a0;
- (id)getRemoteTrtcCustomComposeWeefectManager:(long long)a0;
- (BOOL)checkIsCurrTopPerformanceLevel;
- (BOOL)increasePerformanceLevel;
- (BOOL)decreasePerfLevelCallback;
- (BOOL)checkTimeRangeIsFullLoadWithBeginTime:(double)a0 endTime:(double)a1;
- (void)refreshLiveCaptureSrcForTrtcCustomComposeIfNeed:(id)a0;
- (void)refreshLiveTransmitSrcForTrtcCustomComposeIfNeed:(struct __CVBuffer { } *)a0;
- (void)startCdnPlayOrEnterLiveRoom;
- (BOOL)canChangeAudioQuality;
- (void)reportPlayerEvent:(id)a0 evtId:(int)a1 evtMsg:(id)a2;
- (BOOL)isFinderLive;
- (void)startReportTimer;
- (void)stopReportTimer;
- (void)clearReportTimer;
- (void)didFirstCdnPlayOk;
- (void)didFirstJoinLiveOk;
- (void)checkAndUpdateFirstShowCdnPlayerViewTimestamp;
- (void)registerExtension;
- (void)registerExtensionForP2P;
- (void)updateIsPureAudioMode:(BOOL)a0 showTip:(BOOL)a1;
- (void)updateIsPureAudioMode:(BOOL)a0 showTip:(BOOL)a1 updateLocalVideo:(BOOL)a2;
- (void)updateIsPureAudioMode:(BOOL)a0 showTip:(BOOL)a1 forceTipsWhenUnchanged:(BOOL)a2;
- (void)updateIsPureAudioMode:(BOOL)a0 showTip:(BOOL)a1 forceTipsWhenUnchanged:(BOOL)a2 updateLocalVideo:(BOOL)a3;
- (void)updateAudienceLocalAudioModeState:(unsigned long long)a0;
- (void)handleIsAudienceLocalAudioModeChangedTo:(BOOL)a0;
- (void)updateAudioRoomScene:(unsigned long long)a0;
- (void)updateAudioRoomScene:(unsigned long long)a0 fromSEI:(BOOL)a1;
- (void)onAudioRoomModeChanged;
- (void)onKTVModeChanged;
- (void)addKTVTransitionIfNeed;
- (void)enableCustomVideoCapture:(BOOL)a0;
- (void)setExperimentConfig:(id)a0 params:(id)a1;
- (void)sendCustomVideoData:(struct __CVBuffer { } *)a0 pixelFormat:(long long)a1 rotation:(long long)a2 timestampMs:(unsigned long long)a3;
- (void)enableExternalH264EncodedVideo:(BOOL)a0;
- (void)sendH264EncodedVideoData:(id)a0 width:(double)a1 height:(double)a2 frameType:(long long)a3;
- (BOOL)setVideoEncoderRotation:(long long)a0;
- (void)sendCustomVideoData:(id)a0 pixelFormat:(long long)a1 rotation:(long long)a2 timestampMs:(unsigned long long)a3 width:(double)a4 height:(double)a5;
- (void)enableCustomAudioCapture:(BOOL)a0;
- (void)sendCustomAudioData:(id)a0 sampleRate:(long long)a1 channels:(int)a2 timestampMs:(unsigned long long)a3;
- (void)enableMixExternalAudio:(BOOL)a0 playout:(BOOL)a1;
- (void)mixExternalAudioData:(id)a0 sampleRate:(long long)a1 channels:(int)a2 timestampMs:(unsigned long long)a3;
- (void)mixExternalAudioVolume:(long long)a0 playoutVolume:(long long)a1;
- (void)setVideoEncoderParamWithWidth:(double)a0 height:(double)a1;
- (void)enableAudioVolumeEvaluation:(unsigned long long)a0;
- (void)enableVadDetectionWhenVolumeEvaluate:(BOOL)a0;
- (void)refreshCoverImageVisible;
- (BOOL)isCurrentTrtcHasVideoSource;
- (void)stopRenderBufferForTrtc;
- (void)reStartRenderBufferForTrtcIfNeeded;
- (id)getMagicRewardMemoryManagerAutoCreateIfNotExist:(BOOL)a0;
- (id)getMagicEngineEnergyManagerAutoCreateIfNotExist:(BOOL)a0;
- (id)getMagicEnginePerformanceStatisticManagerAutoCreateIfNotExist:(BOOL)a0;
- (id)getLivePAGStatisticsAutoCreateIfNotExist:(BOOL)a0;
- (id)getFaceDetectStatisticLogicAutoCreateIfNotExist:(BOOL)a0;
- (void)initPrepareAdapter;
- (void)initCameraCastingAdapter;
- (void)initPushAdapter:(BOOL)a0;
- (void)liveCaptureAdapter:(id)a0 didFinishCollectingCaptureMetrics:(id)a1;
- (void)liveCaptureAdapter:(id)a0 didOutputSampleBufferForRender:(struct opaqueCMSampleBuffer { } *)a1 localRenderFlipX:(BOOL)a2;
- (void)liveCaptureAdapter:(id)a0 didOutputRenderFrame:(id)a1;
- (void)liveCaptureAdapter:(id)a0 didOutputSampleBufferForTransmit:(struct opaqueCMSampleBuffer { } *)a1 localRenderFlipX:(BOOL)a2;
- (void)liveCaptureAdapter:(id)a0 didCapturingChanged:(BOOL)a1;
- (void)liveCaptureAdapter:(id)a0 didRenderRotateTransitingChanged:(BOOL)a1;
- (void)liveCaptureAdapter:(id)a0 didOutputInitialSampleBuffer:(struct opaqueCMSampleBuffer { } *)a1;
- (void)liveCaptureAdapter:(id)a0 didOutputEncodeVideoData:(id)a1;
- (BOOL)pauseLive;
- (BOOL)pauseLive:(long long)a0;
- (BOOL)prepareResumeLive;
- (BOOL)resumeLive;
- (void)updateLivePauseStatus:(long long)a0;
- (void)refreshPauseLiveForAudience;
- (id)getLivePauseSceneDescription;
- (id)getLiveMuteSceneDescription;
- (BOOL)innerPauseLiveForAudience;
- (BOOL)innerResumeLiveForAudience;
- (void)handleConnectMicAfterPauseLiveForAudience;
- (void)handleRemoteUsersStateAfterPauseLiveForAnchor;
- (void)handleRemoteUsersStateAfterPauseLiveForAudience;
- (void)updateAllRemoteUsersVideoAndAudioMuted:(BOOL)a0;
- (id)pauseStatusCachedKey;
- (id)pauseTimeCachedKey;
- (void)unableLivePlayingForAudience;
- (void)enableLivePlayingForAudience;
- (void)pauseLiveByPIP;
- (void)autoResumeLiveByPIPIfNeed;
- (void)resumeLiveByPIP;
- (void)pauseLiveForClosePIP;
- (void)resumeLiveForClosePIP;
- (void)pauseLiveForEnterBackground;
- (void)resumeLiveForEnterForeground;
- (void)pauseLiveForPaidLiveScreenCapturing;
- (void)resumeLiveForPaidLiveScreenCapturing;
- (void)pauseLiveAnchorPausedForOuter;
- (void)resumeLiveAnchorPausedForOuter;
- (void)pauseLiveByMinimizeWindow;
- (void)resumeLiveByMinimizeWindow;
- (void)pauseLiveByHomepagePlayer;
- (void)resumeLiveByHomepagePlayer;
- (void)pauseLiveForOuter;
- (void)resumeLiveForOuter;
- (void)pauseLiveForSysIntterupt;
- (void)resumeLiveForSysIntterupt;
- (void)updateLiveCloseStatus:(BOOL)a0;
- (void)onExitLive;
- (BOOL)muteLiveRemoteAudio;
- (BOOL)unMuteLiveRemoteAudio;
- (void)startRemoteVideo:(id)a0 withView:(id)a1;
- (void)stopRemoteVideo:(id)a0;
- (void)updateRemoteUser:(id)a0 fillMode:(long long)a1;
- (void)updateRemoteUser:(id)a0 volume:(long long)a1 business:(long long)a2;
- (void)unSetRemoteUserVolume:(id)a0 business:(long long)a1;
- (void)updateAllRemoteUsersVolume:(long long)a0 business:(long long)a1;
- (void)unSetAllRemoteUsersVolume:(long long)a0;
- (id)getAudioEffectManager;
- (id)getAudioEffectManagerCreateIfNotExist;
- (void)playMusic:(id)a0 publish:(BOOL)a1 startBlock:(id /* block */)a2 progressBlock:(id /* block */)a3 completionBlock:(id /* block */)a4;
- (void)pausePlayMusic:(id)a0;
- (void)resumePlayMusic:(id)a0;
- (void)stopPlayMusic:(id)a0;
- (void)updateIsViewCapturingForAudience:(BOOL)a0;
- (void)startViewCaptureWithView:(id)a0;
- (void)stopViewCapture;
- (void)pauseViewCapture;
- (void)resumeViewCapture;
- (void)refreshViewCaptureConfigurations;
- (id)getLiveCaptureVideoFrameWidgetManageLogic;
- (id)getWevisionWidgetManageLogic;
- (void)checkPaidLiveTrialCountLimitReached;
- (void)sendSEIMessageData:(id)a0;
- (long long)getBeautySceneType;
- (void)initFaceBeautyParam;
- (void)setEffectSkinBright:(float)a0 skinSmooth:(float)a1 lutRosy:(float)a2 lutColor:(float)a3 faceThin:(float)a4 eyeBigger:(float)a5 eyeBright:(float)a6;
- (void)onResult:(int)a0;
- (void)OnResourceID:(long long)a0;
- (void)onResourceIDVector:(id)a0 scene:(unsigned long long)a1;
- (void)onWeEffectLuaScriptJsonMessageReceived:(id)a0 fromSourceId:(int)a1;
- (void)onWeVisEffectMgrCreateCompleted;
- (void)onWeEffect:(id)a0 processCostTimeUpdate:(double)a1 scene:(long long)a2;
- (void)onWeEffectProcessBegin:(id)a0 scene:(long long)a1;
- (void)onWeEffectProcessEnd:(id)a0 scene:(long long)a1;
- (void)onWeEffect:(id)a0 processFpsUpdate:(int)a1;
- (void)removeResourceID:(long long)a0 scene:(unsigned long long)a1;
- (void)addResourceIDVector:(id)a0 scene:(unsigned long long)a1;
- (id)getCurResourceIdVector:(unsigned long long)a0;
- (void)switchCdnOrTrtcPlay:(BOOL)a0;
- (void)handleQualityChangeInfoFromServer:(id)a0 liveSdkInfo:(id)a1;
- (void)handleStreamChangedFromServerWithLiveSdkInfo:(id)a0;
- (void)handleStreamChangedFromServerWithQualityTagInfo:(id)a0 recommendedQualityTag:(unsigned int)a1;
- (void)checkAndUpdateDecryptionParamsWithCdnPlayerItem:(id)a0 url:(id)a1 checkStop:(BOOL)a2;
- (void)clearDataForAudienceSwitchCdnOrTrtcMode;
- (void)checkAndUpdateCdnPlayerEventParams;
- (void)generateMainCdnPlayerItem;
- (void)prepareCdnPlayerItem:(id)a0;
- (void)generateMainCdnPlayerItemAndUpdateView:(BOOL)a0;
- (void)updateAllCdnPlayerItemRenderMode:(long long)a0;
- (BOOL)cdnPlayerItemHasPlayedOK;
- (void)checkAndChangeCategory;
- (void)changeToCategoryPlayback;
- (void)recordCurrentLiveAudioParams;
- (void)checkAndRestoreLiveAudioParams;
- (void)reTryPlayBackupUrl;
- (void)onSwitchRoleCallBack:(int)a0 errMsg:(id)a1;
- (void)handlePanGestureForMultiAngleView:(id)a0;
- (BOOL)animateToSwitchMultiAngleChannelToIndex:(unsigned long long)a0;
- (BOOL)animateToSwitchMultiAngleChannelToIndex:(unsigned long long)a0 forceSwitch:(BOOL)a1;
- (BOOL)prepareForNextMultiAngleChannelInfoWithGestureTranslationX:(double)a0;
- (BOOL)prepareForNextMultiAngleChannelInfoWithIndex:(unsigned long long)a0 fromTheLeftSide:(BOOL)a1 muteNext:(BOOL)a2;
- (BOOL)prepareForNextMultiAngleChannelInfoWithIndex:(unsigned long long)a0 fromTheLeftSide:(BOOL)a1 muteNext:(BOOL)a2 withAnimation:(BOOL)a3;
- (void)notifyMultiAngleChannelInfoCountUpdated;
- (void)handlePinchGestureForZoom:(id)a0;
- (void)handleTapGestureForZoom:(id)a0;
- (void)handlePanGestureForZoom:(id)a0;
- (void)enterVideoZoomDisplayMode;
- (void)exitVideoZoomDisplayModeAnimated:(BOOL)a0;
- (void)markHasShownVideoZoomGuideView;
- (void)stopKeyUpdateTimer;
- (void)startKeyUpdateTimer:(unsigned long long)a0;
- (void)notifyLiveSdkInfoWillExpire;
- (void)updateP2pSwitches:(id)a0;
- (void)onConnectionLost;
- (void)onConnectionRecovery;
- (void)onError:(int)a0 errMsg:(id)a1 extInfo:(id)a2;
- (void)onWarning:(int)a0 warningMsg:(id)a1 extInfo:(id)a2;
- (void)onEnterRoom:(long long)a0;
- (void)onExitRoom:(long long)a0;
- (void)onSwitchRole:(int)a0 errMsg:(id)a1;
- (void)onConnectOtherRoom:(id)a0 errCode:(int)a1 errMsg:(id)a2;
- (void)onDisconnectOtherRoom:(int)a0 errMsg:(id)a1;
- (void)onRemoteUserEnterRoom:(id)a0;
- (void)onRemoteUserLeaveRoom:(id)a0 reason:(long long)a1;
- (void)testOnUserVideoAvailableYES:(id)a0;
- (void)testOnUserVideoAvailableNO:(id)a0;
- (void)handleRemoteSdkUserLeaveRoom;
- (void)onUserAudioAvailable:(id)a0 available:(BOOL)a1;
- (void)onUserVideoAvailable:(id)a0 available:(BOOL)a1;
- (void)handleRemoteSdkUserMediaDataAvailableChanged;
- (void)onUserSubStreamAvailable:(id)a0 available:(BOOL)a1;
- (void)onFirstVideoFrame:(id)a0 streamType:(long long)a1 width:(int)a2 height:(int)a3;
- (void)onUserVideoSizeChanged:(id)a0 streamType:(long long)a1 newWidth:(int)a2 newHeight:(int)a3;
- (void)onNetworkQuality:(id)a0 remoteQuality:(id)a1;
- (void)onStatistics:(id)a0;
- (void)onAudioRouteChanged:(long long)a0 fromRoute:(long long)a1;
- (void)handleAudioRouteChanged:(long long)a0 fromRoute:(long long)a1;
- (void)onUserVoiceVolume:(id)a0 totalVolume:(long long)a1;
- (void)onRecvCustomCmdMsgUserId:(id)a0 cmdID:(long long)a1 seq:(unsigned int)a2 message:(id)a3;
- (void)onRecvSEIMsg:(id)a0 message:(id)a1;
- (BOOL)tryProcessSeiMsgToJson:(id)a0 fromUserId:(id)a1;
- (BOOL)tryProcessSeiMsgToPB:(id)a0 fromUserId:(id)a1;
- (void)onSetMixTranscodingConfig:(int)a0 errMsg:(id)a1;
- (void)onSendFirstLocalAudioFrame;
- (void)onMicDidReady;
- (void)onAudioEffectFinished:(int)a0 code:(int)a1;
- (void)onStartPublishMediaStream:(id)a0 code:(int)a1 message:(id)a2 extraInfo:(id)a3;
- (void)onUpdatePublishMediaStream:(id)a0 code:(int)a1 message:(id)a2 extraInfo:(id)a3;
- (void)onStopPublishMediaStream:(id)a0 code:(int)a1 message:(id)a2 extraInfo:(id)a3;
- (void)onRenderVideoFrame:(id)a0 userId:(id)a1 streamType:(long long)a2;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getNormalizedFrameForUserId:(id)a0;
- (void)onMMLiveViewSwitchCamera;
- (void)onMMLiveViewStartLocalVideo;
- (BOOL)onMMLiveViewIsAudience;
- (id)onMMLiveViewGetAnchorIdentityId;
- (void)onMMLiveViewStartRemoteViewWithSdkUserId:(id)a0 andView:(id)a1;
- (void)onMMLiveViewStopRemoteViewWithSdkUserId:(id)a0;
- (void)onMMLiveViewConnectMicStateChanged;
- (void)onMMLiveViewAnchorAudioModeBackgroundPlayerVMChanged;
- (void)onMMLiveViewSwitchCdnPlayerViewFinishedWithStreamId:(id)a0 isSwitchToNext:(BOOL)a1;
- (void)onMMLiveViewNextCdnPlayerViewMovedWithStreamId:(id)a0 andProgress:(double)a1;
- (void)onMMLiveViewSwitchCdnPlayerViewWillStartAnimationWithStreamId:(id)a0 animationDuration:(double)a1 currentProgress:(double)a2 switchToNext:(BOOL)a3;
- (void)sendGameSEIReport:(id)a0 evtID:(int)a1;
- (void)sendOneWayDelayReport:(unsigned long long)a0;
- (id)getCurrentFinderName;
- (id)getCurrentFinderUsername;
- (void)checkSvrIPOrPlayHttps:(id)a0;
- (id)checkAndGenerateTestReplacePlayerEventObjectWithEventId:(int)a0;
- (void)onLiveCDNPlayerItem:(id)a0 playEvent:(int)a1 withParam:(id)a2;
- (void)onLiveCDNPlayerItem:(id)a0 switchStreamResult:(BOOL)a1 withStreamWrap:(id)a2;
- (void)updateCdnStreamErrorReportInfoWithQualityTag:(unsigned int)a0 hasChangedToBackStream:(BOOL)a1 playerEventId:(int)a2 sdkErrCode:(int)a3 qualityTagCacheBuf:(id)a4;
- (BOOL)tryProcessSeiMsgToJson:(id)a0 curTime:(unsigned int)a1;
- (BOOL)tryProcessSeiMsgToPB:(id)a0 curTime:(unsigned int)a1;
- (void)logForSEIData:(id)a0;
- (void)onNetStatus:(id)a0 p2pStatus:(id)a1;
- (void)notifySubTitleJsonInfo:(id)a0;
- (void)notifyLiveStreamServerTimeWithJsonDict:(id)a0;
- (void)notifyAdvertismentTimestamp;
- (BOOL)checkAndNotifySEIConnectMicMsg:(id)a0;
- (void)clearSeiMicMsgInfo;
- (void)checkAndNotifySEIMicTalkingUsersList:(id)a0;
- (void)clearSeiFreeMicUsersList;
- (id)seiConnectMicUserInfoList;
- (void)clearSeiConnectMicUserInfoList;
- (void)notifyAudioRoomSEIConnectMicMsgUpdated:(BOOL)a0;
- (void)checkAndUpdateFinderLiveStreamTypeInfoWithMicSEIMsg:(id)a0 andIsAudioMode:(BOOL)a1;
- (void)switchToNewQuality:(int)a0;
- (void)updateLastCdnQuality:(unsigned int)a0;
- (id)getCdnStreamInfoForQuality:(unsigned int)a0;
- (void)checkIsHdrCdnLive;
- (BOOL)isHdrCdnLive;
- (id)remoteUserVideoInfoForUserId:(id)a0;
- (id)remoteUserVideoInfoForUserId:(id)a0 autoCreate:(BOOL)a1;
- (void)updateMainRemoteViewFillMode;
- (void)updateVideoSize:(struct CGSize { double x0; double x1; })a0 cdn:(BOOL)a1;
- (void)updateLocalVideoFrameSize:(struct CGSize { double x0; double x1; })a0;
- (void)updateVideoFPS:(unsigned int)a0;
- (void)onVideoFpsChanged;
- (void)livePushAdapterWillStartLocalAudio:(id)a0;
- (void)livePushAdapterDidStartLocalVideo:(id)a0;
- (void)livePushAdapterDidStopLocalVideo:(id)a0;
- (void)livePushAdapter:(id)a0 didPushNetStatus:(id)a1;
- (void)livePushAdapterRemoteUsersVideoSettingChanged:(id)a0;
- (BOOL)livePushAdapter:(id)a0 isUserIdAddNeedIgnore:(id)a1;
- (BOOL)livePushAdapterContainUsersShouldIngore:(id)a0;
- (void)checkCurrentTrtcHasVideoSource;
- (BOOL)isCurrentHasRemoteVideoSource;
- (id)getFaceDecodeLogicAutoCreateIfNotExist:(BOOL)a0;
- (id)getFaceTrackerAutoCreateIfNotExist:(BOOL)a0;
- (id)createKTVBox;
- (void)startRemoteAudienceVideoInAudioModeWithSdkUserId:(id)a0;
- (BOOL)audioRouteSetted;
- (long long)getAudioRoute;
- (void)requestTrtcAudioRoute:(id /* block */)a0;
- (void)updateTrtcAudioRouteSetted:(BOOL)a0;
- (void)delayCheckTrtcAudioRoute;
- (void)updateAnchorLiveRoomCoverImage;
- (void)updateAudienceLiveRoomCoverImage;
- (void)setDelegate:(id)a0;
- (void)onDelegateUpdated;
- (id)createLiveViewWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 andTaskId:(id)a1 andDelegate:(id)a2;
- (void)setIsLivePlayingViaCdn:(BOOL)a0;
- (BOOL)isOnlyPausedInState:(unsigned long long)a0;
- (void)setIsInLive:(BOOL)a0;
- (BOOL)isKitchenOpenLivePerformAnalysisEntrance;
- (id)mm2LiveTabName;
- (unsigned long long)currentLiveVideoDisplayScene;
- (unsigned long long)nextLiveVideoDisplayScene;
- (BOOL)isLiveVideoRemoteValid;
- (BOOL)isLiveVideoLocalHorizontal;
- (unsigned long long)currentLiveLocalVideoDisplayScene;
- (BOOL)isLiveLocalVideoRemoteValid;
- (BOOL)isLiveLocalVideoLocalHorizontal;
- (double)getLocalVideoRemoteDisplayWHPercent;
- (BOOL)isAnchorMainDisplayAdjustCameraOrientation;
- (void)checkAndStartSyncAnchorSEI;
- (BOOL)isReplay;
- (void)setRoleType:(long long)a0;
- (void)checkAudienceConnectingMicStatusWithOldValue:(BOOL)a0;
- (void)setMainCdnPlayerItem:(id)a0;
- (BOOL)isInMainChannel;
- (void)checkAndUpdateAllowRotateStateInIphone;
- (void)onCurrCdnPlayerItem:(id)a0 changeTo:(id)a1;
- (void)onLiveAnchorSEISynchronizeRegistered:(id)a0;
- (void)onSynchronizedSEIAnchoInfo:(id)a0 taskId:(id)a1;
- (void)onStartCustomPixelTransferChange;
- (void)onRequestSynchronzizeInfoForSEIAnchorInfo:(id)a0;
- (id)generateSEILiveModeInfoString;
- (id)checkAndGenerateSEIKTVStateInfoString;
- (void)updateMicInfoInSEIAnchorInfo:(id)a0;
- (void)updateMicTalkingUsersInfoInSEIAnchorInfo:(id)a0;
- (void)updateAudioRoomModeMicInfoInSEIAnchorInfo:(id)a0;
- (void)updateRecordScreenInfoInSEIAnchorInfo:(id)a0;
- (void)processReceivedGestureSeiMessage:(id)a0;
- (BOOL)liveRoomPlayStream:(id)a0;
- (unsigned long long)liveRoomSwitchStream:(id)a0;
- (unsigned long long)liveRoomSwitchStream:(id)a0 switchByUser:(BOOL)a1 checkNetworkStatus:(BOOL)a2;
- (void)checkAndMarkHasManuallySwitchedStream;
- (id)getRecentClarityChooseFromCache;
- (void)clearRecentClarityChooseFromCache;
- (void)onSynchronizedSEIAnchorStatus:(unsigned long long)a0;
- (BOOL)shouldForceLandscapeResMode;
- (BOOL)isLiveCaptureRenderRotateTransiting;
- (void)onLiveTrtcRemoteUserAudioFrame:(id)a0 userId:(id)a1;
- (void)onLiveTrtcCapturedAudioFrame:(id)a0;
- (void)onLiveTrtcLocalProcessedAudioFrame:(id)a0;
- (void)onLiveTrtcVoiceEarMonitorAudioFrame:(id)a0;
- (void)onLiveTrtcWillStartPublishMediaStream;
- (id)asynSaveCurrentFrameToPath:(id)a0;
- (void)applicationWillEnterForeground:(id)a0;
- (void)ReachabilityChange:(unsigned int)a0;
- (void)reportCurrentP2pStat:(id)a0 initTime:(unsigned long long)a1;
- (void)onReportP2pStat:(id)a0 initTime:(unsigned long long)a1;
- (void)onResetP2pStat;
- (void)onReportLag:(unsigned int)a0;
- (void)fillReporterExtInfoIntoPushAdapter;
- (void)updatePlayLiveType:(unsigned int)a0;
- (void)restartAudioDevice:(BOOL)a0;
- (void)liveMetricsMonitor:(id)a0 didCollectMetricsInfo:(id)a1;
- (void)effectMgr:(id)a0 configSettings:(void *)a1;
- (void)effectMgr:(id)a0 adjustSettings:(void *)a1;
- (void)effectMgr:(id)a0 deviceRunPreferByCPU:(BOOL *)a1;
- (void)energyController:(id)a0 didChangeEnergyMode:(long long)a1;
- (void)updateLiveParamsForEnergyModeChanged:(long long)a0;
- (void)updateWeEffectParamsForEnergyModeChanged:(long long)a0;
- (void)updateBlurPowerModeAdjustParamLevelForEnergyModeChanged:(long long)a0;
- (BOOL)isLivePictureInPictureEnabled;
- (void)CameraScanViewControllerDealloc;
- (void)updateOrientationMaskForAnchorPreLive:(unsigned long long)a0;
- (void)fixOrientationMaskForAnchorPush;
- (void)forceChangeSupportedOrientationMaskForAnchor:(unsigned long long)a0;
- (void)setCameraPreviewOrientation;
- (long long)getCameraPreviewOrientation;
- (BOOL)shouldForbidLandScapeForIphone;
- (void)updateMainRemoteViewForOrientationChanged;
- (void)updateMainLocalViewFrame;
- (BOOL)shouldSupportRotateOrientation;
- (BOOL)shouldSupportRotateOrientationIgnoreMinimizeMode:(BOOL)a0;
- (double)getLiveCaptureResolutionPercentInOrientation:(long long)a0;
- (long long)tryGetRotateOrientationForAnchorMainOrientationMask;
- (void)updateLiveModeSelectSubItem:(id)a0;
- (void)updateLiveSelectedModeItem:(id)a0;
- (void)stopCameraCastLocalVideo;
- (void).cxx_destruct;

@end
