@class UILabel, UIImageView, VoipDescriptionButton, UIView, MMUIButton, MultiPathCellularTipsView;
@protocol MultiTalkBottomOperatePanelDelegate;

@interface MultiTalkBottomOperatePanel : UIView <WeChat.CarPlayVoIPTalkDelegate>

@property (retain, nonatomic) UIView *contentsView;
@property (retain, nonatomic) VoipDescriptionButton *videoButton;
@property (retain, nonatomic) VoipDescriptionButton *microphoneButton;
@property (retain, nonatomic) VoipDescriptionButton *speakerButton;
@property (retain, nonatomic) VoipDescriptionButton *hangupButton;
@property (retain, nonatomic) MMUIButton *arrowButtonUp;
@property (retain, nonatomic) MMUIButton *arrowButtonDown;
@property (retain, nonatomic) UIView *backgroundView;
@property (nonatomic) BOOL isPanGesturing;
@property (nonatomic) double panMovement;
@property (nonatomic) unsigned long long panStatus;
@property (nonatomic) BOOL videoButtonOn;
@property (nonatomic) BOOL microphoneButtonOn;
@property (nonatomic) BOOL speakerButtonOn;
@property (nonatomic) int layoutType;
@property (retain, nonatomic) MultiPathCellularTipsView *multiPathCellularTipsView;
@property (retain, nonatomic) UILabel *multiPathCellularTipsLabel;
@property (retain, nonatomic) UIImageView *multiPathCellularArrowView;
@property (nonatomic) BOOL isVideoButtonEnable;
@property (nonatomic) unsigned int deviceStatus;
@property (weak, nonatomic) id<MultiTalkBottomOperatePanelDelegate> delegate;
@property (nonatomic) long long multiPathCellularTips;
@property (nonatomic) BOOL isInScreenSharingAudienceMode;
@property (nonatomic) BOOL isSpeakerReady;
@property (nonatomic) BOOL isAudioInterruption;

+ (BOOL)isiPhoneWithNotch;
+ (id)normalVoipDescriptButtonBackImage;
+ (id)voipHangupButtonBackImage;
+ (id)voipSelectHangupAndAcceptButtonBackImage;
+ (id)selectedVoipDescriptButtonBackImage;
+ (id)disabledVoipDescriptButtonBackImage;
+ (id)createBasicVoipDescriptionButton;
+ (double)preferredHeight;
+ (double)preferredHeightForLayoutType:(int)a0 isInScreenSharingAudienceMode:(BOOL)a1;
+ (double)preferredHeightForLayoutType:(int)a0;

- (BOOL)pointInside:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (unsigned int)getDeviceStatus;
- (double)topForLayoutType:(int)a0;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })voIPDescriptionButtonImageEdgeInsetsWithLayoutType:(int)a0 isInScreenSharingAudienceMode:(BOOL)a1;
- (id)createArrowButton;
- (double)panGestureTotalOffset;
- (double)currentPanGestureOffsetPercent;
- (double)currentButtonTitleAlpha;
- (double)currentButtonSideLength;
- (double)foldedButtonLeftRightMargin;
- (double)currentButtonLeftRightMargin;
- (void)updateMultiPathCellularTipsView;
- (void)layoutContentsView;
- (void)layoutBackgroundView;
- (void)layoutVideoButton;
- (void)layoutMicrophoneButton;
- (void)layoutSpeakerButton;
- (void)layoutHangupButton;
- (void)layoutArrowButton;
- (void)animateToChangeLayout;
- (void)updateSpeakerButtonStatus:(id)a0 hasExtenalOutput:(BOOL)a1;
- (void)showAirplayLoadingState:(BOOL)a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 andLayoutType:(int)a1;
- (void)layoutSubviews;
- (BOOL)checkUseManualHitTest;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)reportOperationArrowBtnExposeOrClick:(BOOL)a0 Expand:(BOOL)a1;
- (void)reportOperationArrowBtnExposeWithRoomKey:(unsigned long long)a0 roomId:(unsigned long long)a1;
- (void)updateSpeakerButtonSelected:(BOOL)a0;
- (void)updateVideoButtonSelected:(BOOL)a0;
- (void)updateMicrophoneButtonSelected:(BOOL)a0;
- (void)updateSpeakerButtonEnabled:(BOOL)a0;
- (void)updateVideoButtonEnabled:(BOOL)a0;
- (BOOL)isSpeakerButtonEnable;
- (BOOL)isSpeakerButtonSelected;
- (BOOL)isMicrophoneButtonSelected;
- (BOOL)isVideoButtonSelected;
- (int)getCurrentLayoutType;
- (void)changeToPanelFoldedLayout;
- (void)changeToPanelLayoutFromFolded;
- (void)handleOperationPanelPanGesture:(id)a0;
- (void)onTapMultiPathCellularTipsView;
- (void)onVideoButtonClick;
- (void)onMicrophoneButtonClick;
- (void)onSpeakerButtonClick;
- (void)updateSpeakerButtonByPort:(id)a0 hasChanged:(BOOL)a1;
- (void)changeAudioToPort:(id)a0 hasChanged:(BOOL)a1;
- (void)onHangupButtonClick;
- (void)onFlipCameraButtonClick;
- (void)onArrowButtonClick;
- (void)onCarPlayVoIPTalkTemplateClickHangup;
- (void)onCarPlayVoIPTalkTemplateClickMute;
- (BOOL)isMicrOpen;
- (void).cxx_destruct;

@end
