@class NSMutableDictionary, SessionSelectSectionFoldView, NSDictionary, FTSTopHitMgr, NSMutableArray, UIView, UIColor, NSString, MMTableView, OrderedDictionary, MMUILabel, RecentForwardScrollView, WCSearchBar, WCDataSearcher;
@protocol SessionSelectViewDelegate;

@interface SessionSelectView : UIView <IFTSContactMgrExt, RecentForwardScrollViewDelegate, SessionSelectSectionFoldViewDelegate, UITableViewDelegate, UITableViewDataSource, WCSearchDelegate, WCDataSearchDelegate, ContactsDataLogicDelegate> {
    long long m_iSessionType;
    id<SessionSelectViewDelegate> m_delegate;
    NSMutableArray *m_arrContacts;
    NSMutableDictionary *m_contactSelectionRecords;
    FTSTopHitMgr *_ftsTopHitMgr;
    NSString *_taskKey;
    NSString *nsCurrentSearchText;
    NSMutableArray *arrSearchResultOfContacts;
    NSMutableArray *arrSearchResultOfGroup;
    NSMutableArray *arrSearchResultOfTopHit;
    NSMutableDictionary *dicSearchResult;
    NSMutableArray *arrSectionKey;
    NSMutableArray *m_specialCellList;
    unsigned int _expandBitSet;
    BOOL _chatRoomOnly;
    BOOL _bStartWithActiveSearch;
    NSString *_startActiveSearchText;
}

@property (retain, nonatomic) NSMutableArray *sectionTypes;
@property (retain, nonatomic) NSMutableArray *recentForwardContacts;
@property (retain, nonatomic) NSMutableDictionary *multiSelectContactSectionDict;
@property (nonatomic) long long topSessionCount;
@property (nonatomic) long long selectedChatBoxSessionCount;
@property (retain, nonatomic) RecentForwardScrollView *recentForwardScrollView;
@property (retain, nonatomic) UIView *recentChatHeaderView;
@property (retain, nonatomic) UIView *bizChatHeaderView;
@property (retain, nonatomic) UIView *noRecentChatHeaderView;
@property (retain, nonatomic) UIView *fakeRecentChatHeaderView;
@property (retain, nonatomic) MMUILabel *noRecentChatLabel;
@property (nonatomic) BOOL isFoldTopSession;
@property (nonatomic) BOOL canFoldTopSession;
@property (retain, nonatomic) SessionSelectSectionFoldView *sessionFoldView;
@property (retain, nonatomic) UIView *footerBottomView;
@property (nonatomic) double foldViewFloatingOffset;
@property (nonatomic) double bizChatHeaderFloatingOffset;
@property (nonatomic) double recentChatHeaderFloatingOffset;
@property (nonatomic) long long selectedTopSessionCount;
@property (nonatomic) BOOL hasModifiedSelectedContacts;
@property (nonatomic) BOOL m_bShowEnterpriseChat;
@property (nonatomic) BOOL m_bShowNewSession;
@property (nonatomic) BOOL bShowForwardToEnterpriseChat;
@property (nonatomic) BOOL disableForwardToLocalWeWork;
@property (nonatomic) BOOL m_bShowSelectFromContactList;
@property (nonatomic) BOOL m_alignsFilterRulesInSearchResult;
@property (nonatomic) BOOL m_bFilterMyContact;
@property (nonatomic) BOOL m_bMultiSelect;
@property (nonatomic) BOOL m_bIgnoreOpenIM;
@property (nonatomic) BOOL m_bIgnoreChatRoom;
@property (nonatomic) BOOL m_ignoresChatBox;
@property (nonatomic) BOOL m_ignoresFileTransfer;
@property (nonatomic) BOOL m_ignoresChatBotTransfer;
@property (nonatomic) BOOL m_recentForwardHidden;
@property (retain, nonatomic) WCDataSearcher *searcher;
@property (retain, nonatomic) OrderedDictionary *m_dicMultiSelect;
@property (retain, nonatomic) NSDictionary *m_dicRequiredContact;
@property (readonly, nonatomic) NSMutableDictionary *m_contactSelectionRecords;
@property (copy, nonatomic) NSDictionary *m_disabledContacts;
@property (copy, nonatomic) NSDictionary *m_ignoredContacts;
@property (retain, nonatomic) MMTableView *m_tableView;
@property (nonatomic) unsigned long long m_commonSearchScene;
@property (nonatomic) BOOL m_onlySelectSingleWeixChat;
@property (nonatomic) BOOL m_showsChatroomMembers;
@property (nonatomic) BOOL m_searchPanelHidden;
@property (nonatomic) BOOL m_disableSearchBar;
@property (nonatomic) unsigned long long m_specificLogicScene;
@property (retain, nonatomic) UIColor *brandColor;
@property (nonatomic) BOOL useNewSearchBar;
@property (retain, nonatomic) WCSearchBar *searchBarNew;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)setFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)dealloc;
- (void)cleartSearchQueryTest;
- (id)getMatchTipForUsername:(id)a0;
- (void)multiSelectWithSearchResult:(id)a0;
- (long long)indexForContact:(id)a0 atSection:(long long)a1;
- (long long)sectionTypeForSelectedContact:(id)a0;
- (long long)getTopSessionCount;
- (unsigned long long)getRecentForwardOneLineCount;
- (id)getRecentForwardDeleteList;
- (void)initData;
- (BOOL)filterContact:(id)a0;
- (void)onContactsDataChange;
- (BOOL)onFilterContactCandidate:(id)a0;
- (void)initSearchBar;
- (void)initRecentForwardView;
- (void)initView;
- (void)setupNoRecentChatView;
- (void)setupFakeRecentChatView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 delegate:(id)a1;
- (void)layoutSubviews;
- (BOOL)shouldDisplayChatRoomEntry;
- (id)parseSeperatedKeyword:(id)a0;
- (void)chatRoomEntryConvertionKVReport:(BOOL)a0;
- (void)idkeyWithResultClick:(BOOL)a0 withCollapse:(BOOL)a1;
- (BOOL)shouldShowChatroomMembers:(id)a0;
- (void)initSectionTypes;
- (long long)sectionTypeFor:(long long)a0;
- (long long)numberOfSectionsInTableView:(id)a0;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (BOOL)isSelected:(id)a0;
- (BOOL)hasSecondPage:(id)a0;
- (void)makeCell:(id)a0 contact:(id)a1 HightlightedTop:(BOOL)a2;
- (void)makeCell:(id)a0 contact:(id)a1 HightlightedTop:(BOOL)a2 showMatchTip:(BOOL)a3;
- (void)makeCell:(id)a0 contact:(id)a1 HightlightedTop:(BOOL)a2 showMatchTip:(BOOL)a3 descTip:(id)a4;
- (void)makeCell:(id)a0 contact:(id)a1 HightlightedTop:(BOOL)a2 showMatchTip:(BOOL)a3 descTip:(id)a4 multiSelect:(BOOL)a5;
- (void)makeCell:(id)a0 contact:(id)a1;
- (void)makeMoreCell:(id)a0 description:(id)a1 image:(id)a2;
- (void)makeChatRoomEntryCell:(id)a0;
- (void)updateMultiSelectView;
- (void)makeCell:(id)a0 ForRowAtIndexPath:(id)a1;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (double)tableView:(id)a0 heightForRowAtIndexPath:(id)a1;
- (double)tableView:(id)a0 heightForHeaderInSection:(long long)a1;
- (double)tableView:(id)a0 heightForFooterInSection:(long long)a1;
- (BOOL)tableView:(id)a0 shouldHighlightRowAtIndexPath:(id)a1;
- (id)tableView:(id)a0 viewForHeaderInSection:(long long)a1;
- (id)tableView:(id)a0 viewForFooterInSection:(long long)a1;
- (void)makeBizChatSectionHeaderView:(id)a0;
- (double)getRecentChatSectionHeaderHeight;
- (void)makeRecentChatSectionHeaderView:(id)a0;
- (id)sectionIndexTitlesForTableView:(id)a0;
- (long long)tableView:(id)a0 sectionForSectionIndexTitle:(id)a1 atIndex:(long long)a2;
- (void)tableView:(id)a0 willDisplayCell:(id)a1 forRowAtIndexPath:(id)a2;
- (BOOL)updateMultiSelect:(id)a0 source:(long long)a1;
- (void)switchSelect:(id)a0 atIndexPath:(id)a1 source:(long long)a2;
- (void)handleSelectEnterpriseChat:(id)a0;
- (void)handleSelectNewSession;
- (void)handleSelectFromContact;
- (void)handleForwardToEnterpriseChat;
- (void)onSelect:(id)a0;
- (id)getGroupDispName:(id)a0;
- (BOOL)isSelectEnabledForContact:(id)a0;
- (void)handleSelectIndexPath:(id)a0 tableView:(id)a1;
- (void)tableView:(id)a0 didSelectRowAtIndexPath:(id)a1;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)updateLineViewOfSectionHeaderView;
- (void)scrollViewDidScroll:(id)a0;
- (void)tableView:(id)a0 willDisplayHeaderView:(id)a1 forSection:(long long)a2;
- (void)wcsDidPresentSearch:(id)a0;
- (id)cellForIndex:(id)a0 ForSearchViewTable:(id)a1;
- (double)heightForSearchViewTable:(id)a0;
- (void)didSearchViewTableSelect:(id)a0;
- (long long)numberOfSectionsForSearchViewTable:(id)a0;
- (long long)numberOfRowsInSection:(long long)a0 ForSearchViewTable:(id)a1;
- (double)heightForHeaderInSection:(long long)a0 ForSearchViewTable:(id)a1;
- (id)viewForHeaderInSection:(long long)a0 ForSearchViewTable:(id)a1;
- (id)titleForHeaderInSection:(long long)a0 ForSearchViewTable:(id)a1;
- (double)heightForFooterInSection:(long long)a0 ForSearchViewTable:(id)a1;
- (id)viewForFooterInSection:(long long)a0 ForSearchViewTable:(id)a1;
- (void)SearchBarBecomeActive;
- (void)startByActiveSearch:(id)a0;
- (void)doSearch:(id)a0 Pre:(BOOL)a1;
- (void)delaySearchImp:(id)a0;
- (void)delaySearch:(id)a0 slowMode:(BOOL)a1;
- (void)cancelSearch;
- (BOOL)shouldCollaseOrExpandSearchResultAtIndex:(long long)a0;
- (BOOL)isMoreCellAtIndexPath:(id)a0;
- (BOOL)isChatRoomEntryCellAtSection:(long long)a0;
- (BOOL)isTopHitSection:(long long)a0;
- (void)wcsSearchBar:(id)a0 textDidChange:(id)a1;
- (void)wcsDidDismissSearch:(id)a0;
- (void)onFTSContactSearchFinish:(id)a0;
- (void)FilterSearchResultOfNormalContacts:(id)a0;
- (BOOL)hasBizChatSession;
- (id)sectionTitleForCurrentSessionView;
- (id)getTitleForBizChatSession;
- (long long)countOfRowForBizChatSession;
- (id)getContactInBizChatSessionAtRow:(unsigned long long)a0;
- (BOOL)isSpecialSection:(unsigned long long)a0;
- (BOOL)isBizChatSection:(unsigned long long)a0;
- (BOOL)isRecentChatSections:(unsigned long long)a0;
- (BOOL)isRecentChatTopSessionSection:(unsigned long long)a0;
- (BOOL)isRecentChatNonTopSessionSection:(unsigned long long)a0;
- (BOOL)isRecentForwardChatSection:(unsigned long long)a0;
- (unsigned long long)indexOfRecentChatTopSessionSection;
- (long long)contactIndexForRecentChatRowAtIndexPath:(id)a0;
- (id)contactForRecentChatRowAtIndexPath:(id)a0;
- (BOOL)hasRecentForwardSessions;
- (id)titleForRecentForwardSection;
- (BOOL)canMultiSelectContact:(id)a0;
- (void)clickRFItemCallBack:(id)a0;
- (void)relayoutScrollSheet;
- (void)onSelectAtSectionFoldView;
- (BOOL)shouldShowFoldSectionTopSep;
- (void)updateSessionFoldView;
- (void)updateFoldViewFloatingOffset;
- (void).cxx_destruct;

@end
