@class TextStateIconLogic, UIImage, TextStateTopicLogic, NSMutableDictionary, TextStatePublishLogic, TextStateLikeLogic, TextStateNewXMLLogic, TextStateReadLogic, NSString, NSSet, NSMutableArray, _TtC6WeChat18DoNotDisturbManger, TextStatePublishIconRecentUseCache, MemoryMappedKV, TextStateRedDotLogic, TextStateDataLogic;

@interface TextStateMgr : MMUserService <TextStatePublishLogicDelegate, TextStateDataLogicDelegate, TextStateNewXMLLogicDelegate, TextStateTopicLogicDelegate, TextStateLikeLogicDelegate, TextStateRedDotLogicDelegate, TextStateReadLogicDelegate, MMConfigMgrExt, WCTextStateDBExt, IMsgExt, IContactMgrExt, IUpdateProfileMgrExt, IExptServiceExt, IMMLanguageMgrExt, MMServiceProtocol>

@property (retain, nonatomic) TextStatePublishLogic *publishLogic;
@property (retain, nonatomic) TextStateDataLogic *dataLogic;
@property (retain, nonatomic) TextStateNewXMLLogic *systemNewXMLLogic;
@property (retain, nonatomic) TextStateTopicLogic *topicLogic;
@property (retain, nonatomic) TextStateLikeLogic *doLikeLogic;
@property (retain, nonatomic) TextStateIconLogic *iconLogic;
@property (retain, nonatomic) TextStateReadLogic *readLogic;
@property (retain, nonatomic) TextStateRedDotLogic *redDotLogic;
@property (retain, nonatomic) _TtC6WeChat18DoNotDisturbManger *doNotDisturbManager;
@property (retain, nonatomic) TextStatePublishIconRecentUseCache *recentUseIconCache;
@property (retain, nonatomic) NSString *clusterPresentType;
@property (nonatomic) BOOL bShowTextState;
@property (nonatomic) BOOL bShowTextStateIconInTimelineCommentsAndLike;
@property (nonatomic) BOOL bSortTopicWithFriendScore;
@property (nonatomic) unsigned int maxTextStateCount;
@property (nonatomic) unsigned int tempTextStateValidDuration;
@property (nonatomic) BOOL usePublishNewStyle;
@property (nonatomic) BOOL showRecentUseInPublish;
@property (nonatomic) BOOL forbid3rdBuffer;
@property (nonatomic) unsigned int messageChannel;
@property (nonatomic) unsigned int nearbyExperiment;
@property (nonatomic) BOOL updateNearbyEnteringForeground;
@property (retain, nonatomic) NSString *showRedEnvelopeButtonIconIds;
@property (retain, nonatomic) NSSet *showRedEnvelopeButtonIconIdSet;
@property (retain, nonatomic) NSMutableArray *cachedLikeItems;
@property (retain, nonatomic) NSMutableArray *cachedCommentItems;
@property (retain, nonatomic) NSString *currentBackgroundId;
@property (retain, nonatomic) UIImage *defaultImage;
@property (nonatomic) unsigned long long recentFetchWeAppTime;
@property (retain, nonatomic) MemoryMappedKV *autoExpiredKV;
@property (retain, nonatomic) MemoryMappedKV *defaultKV;
@property (copy, nonatomic) id /* block */ publishCallback;
@property (nonatomic) BOOL bSupportBrowseMultiStatus;
@property (nonatomic) BOOL bSupportPublishMultiStatus;
@property (nonatomic) BOOL isCustomBlurEffectSwitchOpen;
@property (retain, nonatomic) NSMutableDictionary *commentDrafts;
@property (retain, nonatomic) NSMutableDictionary *sessionIdDict;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)getSessionIDWithTextStateID:(id)a0 scene:(unsigned int)a1;
- (id)genNewSessionIDWithTextStateID:(id)a0 scene:(unsigned int)a1;
- (void)reportTextStateOperateWithSessionID:(id)a0 actionCode:(unsigned int)a1 actionResult:(id)a2;
- (void)reportWhenReceiveLikeNotify:(id)a0;
- (void)reportWhenSelectedMeTab;
- (void)reportWhenShowMsgNotifyView;
- (void)reportWhenClickMsgNotifyView;
- (void)reportWhenClickShowMoreNotifyMsg;
- (void)reportWithActionType:(unsigned int)a0;
- (void)reportWithActionType:(unsigned int)a0 textStateId:(id)a1;
- (void)reportWithActionType:(unsigned int)a0 actionResult:(id)a1;
- (void)reportWithActionType:(unsigned int)a0 actionResult:(id)a1 btnStyle:(long long)a2;
- (void)reportWithActionType:(unsigned int)a0 actionResult:(id)a1 btnStyle:(long long)a2 textStateId:(id)a3;
- (void)reportMixButtonActionType:(unsigned int)a0 interactionCount:(unsigned int)a1 notifyCount:(unsigned int)a2 isShowReddot:(BOOL)a3;
- (void)reportWithActionType:(unsigned int)a0 actionResult:(id)a1 btnStyle:(long long)a2 textStateId:(id)a3 sceneSessionId:(id)a4 cardListId:(id)a5;
- (unsigned long long)friendTextStateCount;
- (void)reportFriendStateExposeWithBtnStyle:(long long)a0 firstHeadImageUsername:(id)a1;
- (void)reportFriendStateClickWithBtnStyle:(long long)a0;
- (void)reportWhenLeftSlideInteractiveMessage:(id)a0;
- (void)reportWhenDeleteInteractiveMessage:(id)a0;
- (void)reportWhenClearInteractiveMessages;
- (void)reportWhenClickShowMoreInteractiveMessages;
- (void)reportMeTabPublishButtonExpose:(id)a0;
- (void)reportMeTabPublishButtonTap:(id)a0;
- (void)reportCardListFooterPublishButtonExposeWithSceneSessionId:(id)a0 cardListId:(id)a1;
- (void)reportCardListFooterPublishButtonTapWithSceneSessionId:(id)a0 cardListId:(id)a1;
- (id)getCurrentTextStateId;
- (void)onServiceInit;
- (void)onServiceClearData;
- (BOOL)shouldShowTextState;
- (BOOL)shouldShowTextStateIconInContactsList;
- (BOOL)shouldShowTextStateIconInGroupChat;
- (BOOL)shouldShowTextStateIconInTimelineFeed;
- (BOOL)shouldShowTextStateIconInTimelineCommentsAndLike;
- (BOOL)shouldShowTextStateIconInTimelineNotifications;
- (BOOL)shouldSortTopicWithFriendScore;
- (unsigned long long)emoticonSwitch;
- (BOOL)enableLikeVersionAndFetchBlackList;
- (void)initMainExperiment;
- (BOOL)enableDoNotDisturbMode;
- (BOOL)shouldUseCustomBlurEffect;
- (void)initOtherExperiment;
- (void)initOtherConfiguration;
- (BOOL)hasShownTextStatePublish;
- (void)onShowTextStatePublish;
- (BOOL)shouldShowRedDot:(unsigned int)a0;
- (void)disposeRedDot:(unsigned int)a0;
- (BOOL)shouldShowRedPointOnMeTab;
- (unsigned int)getRedPointCount;
- (void)disposeRedPointOnMeTab;
- (unsigned int)getTotalUnreadMessageCount;
- (id)createOrGetBackgroundId;
- (void)clearBackgroundId;
- (BOOL)isDataLoaded;
- (id)mostRecentTextStateForUsername:(id)a0;
- (id)textStateListForUsername:(id)a0;
- (id)textStateListMultipleForUsername:(id)a0;
- (id)textStateForId:(id)a0;
- (void)updateTextStateByBackLocgic:(id)a0;
- (void)initIconResource;
- (id)iconWrapForId:(id)a0;
- (id)publishIconList;
- (id)customIconBoardIconList;
- (id)recentUseIconList;
- (BOOL)removeRecentUseIcon:(id)a0;
- (id)activePassthroughIcon;
- (void)expirePassthroughIcon;
- (void)forceUpdateIconWithFlags:(unsigned int)a0;
- (BOOL)shouldShowRedEnvelopeButtonForIconId:(id)a0;
- (id)getExperimentForKey:(id)a0 defaultValue:(id)a1;
- (void)showDNDModeEducatePageIfNeed:(id)a0;
- (unsigned long long)topicUsernameCount;
- (id)topUnreadTopicUsernameList;
- (id)topicForId:(id)a0;
- (id)friendTopicList;
- (BOOL)isPositionAuthorized;
- (BOOL)checkShouldAuthorizePositionOnceAndSetShown;
- (void)clearPositionAuthorizationOnce;
- (BOOL)isAvailableAfterPublish;
- (BOOL)isTextStateSameTopicAsCurrentUser:(id)a0;
- (void)clearKeyValueFromOldExperiment:(unsigned int)a0 toNewExperiment:(unsigned int)a1;
- (void)updateNearbyExperimentFromValue:(id)a0;
- (void)updateNearbyIfNeeded;
- (id)newTextStateSquarePagePath;
- (BOOL)prefetchNewTextStateSquareWeApp;
- (void)openNewTextStateSquareWeApp;
- (void)postDataLoadedEventToNewSquare;
- (void)postPublishedEventToNewSquareWithTextState:(id)a0;
- (void)postNotifyChangeEventToNewSquare;
- (void)postTextStateLikeEventToNewSquareWithLike:(BOOL)a0 textStateId:(id)a1;
- (void)publishTextState:(id)a0 withCallback:(id /* block */)a1;
- (void)publishTextState:(id)a0 associateMediaItem:(id)a1;
- (void)publishTextState:(id)a0 associateMediaItem:(id)a1 parameter:(id)a2;
- (BOOL)canPublishNewTextState;
- (id)nonNetworkErrorPublishingTextState;
- (void)deleteTextStateForId:(id)a0;
- (void)deletePublishedTextState:(id)a0 completion:(id /* block */)a1;
- (void)deletePublishedTextStateWithId:(id)a0 completion:(id /* block */)a1;
- (id)tempMostRecentTextState;
- (BOOL)isLikeForTextStateWithId:(id)a0;
- (void)setLike:(BOOL)a0 forTextState:(id)a1;
- (void)setLike:(BOOL)a0 source:(unsigned int)a1 forTextState:(id)a2;
- (void)handleLikeDataItem:(id)a0;
- (void)handleCommentDataItem:(id)a0;
- (id)getCacheSelfLikeData;
- (BOOL)affStatusMainDBTransferFinish;
- (BOOL)useAffDB;
- (void)setUsername:(id)a0 withFriendScore:(double)a1;
- (double)friendScoreForUser:(id)a0;
- (BOOL)isTextStateReadWithUsername:(id)a0;
- (BOOL)isReadForTextStateId:(id)a0;
- (void)setReadForTextState:(id)a0;
- (BOOL)hasUnreadTextStateContact;
- (void)onTextStateTopicUpdate;
- (void)onTextStateTopicConstruct;
- (void)onRedDotDisposed:(unsigned int)a0;
- (void)onLike:(BOOL)a0 success:(BOOL)a1 textStateId:(id)a2;
- (void)onTextStateSubmitToPublish:(id)a0;
- (void)onTextState:(id)a0 publishSuccess:(BOOL)a1;
- (void)onTextStateDeleteFromPublishingQueue:(id)a0;
- (BOOL)shouldModifySelfContact;
- (void)onTextStateDataLoaded;
- (void)onTextStateUpdateForUsername:(id)a0;
- (unsigned int)activeMessageChannel;
- (void)onGetModTextStatusDataItem:(id)a0 checkSeqence:(BOOL)a1;
- (void)onGetTextStatusLikeDataItem:(id)a0;
- (void)onGetTextStatusCommentDataItem:(id)a0;
- (void)onShouldRefreshIconConfig;
- (void)onGetStatusDeleteDataItem:(id)a0;
- (void)onParseAffModTextStatueFinish:(id)a0;
- (id)getUsernameToMostRecentTextState;
- (id)getMostRecentTextStateForUsername:(id)a0;
- (void)willEnterForeground;
- (void)OnGetNewXmlMsg:(id)a0 Type:(id)a1 MsgWrap:(id)a2;
- (void)onContactListUpdate:(unsigned int)a0;
- (void)onNewContact:(id)a0;
- (void)onModifyContact:(id)a0;
- (void)onDeleteContact:(id)a0;
- (void)onRemoveContactFromAddressBook:(id)a0;
- (void)onProfileChange;
- (void)onLanguageChange;
- (void)onExptItemListChange;
- (void)onMMDynamicConfigUpdated;
- (void)onReceiveInteractionCount:(unsigned int)a0 withTextStateId:(id)a1;
- (BOOL)isSupportBrowseMultiStatus;
- (BOOL)isSupportPublishMultiStatus;
- (BOOL)isMultiStatusNumReachCeiling;
- (void).cxx_destruct;

@end
