@interface WAFileStorage : NSObject

+ (void)saveImageWithAppID:(id)a0 images:(id)a1 completeHandler:(id /* block */)a2;
+ (void)saveImageWithAppID:(id)a0 images:(id)a1 fileType:(long long)a2 completeHandler:(id /* block */)a3;
+ (void)syncSaveImageWithAppID:(id)a0 images:(id)a1 fileType:(long long)a2 completeHandler:(id /* block */)a3;
+ (id)generateImagesLocalIds:(id)a0 fileType:(long long)a1 appID:(id)a2;
+ (void)saveOriginalImageWithAppID:(id)a0 asset:(id)a1 completeHandler:(id /* block */)a2;
+ (id)getFileTypeWithData:(id)a0;
+ (id)saveLivePhotoVideoForAppID:(id)a0 videoPath:(id)a1;
+ (id)fileSchema;
+ (id)bufferSchema;
+ (id)getBufferIdentity:(id)a0;
+ (BOOL)generateTempLocalID:(id *)a0 path:(id *)a1 withAppID:(id)a2 fileType:(id)a3;
+ (BOOL)generateStoreLocalID:(id *)a0 path:(id *)a1 withAppID:(id)a2 fileType:(id)a3;
+ (id)cacheSandboxRootDir;
+ (id)tempDirName;
+ (id)tempFileDirWithAppID:(id)a0;
+ (id)storeFileDirWithAppID:(id)a0;
+ (id)storeLocalIDWithMD5:(id)a0 fileType:(id)a1;
+ (id)filePathWithAppID:(id)a0 localID:(id)a1;
+ (BOOL)ak_isSymlink:(id)a0;
+ (id)usrFilePathWithAppID:(id)a0 subPath:(id)a1 localName:(id)a2;
+ (BOOL)isMD5StringValid:(id)a0;
+ (BOOL)isHomePath:(id)a0;
+ (id)tempLocalIDPrefix;
+ (id)storeLocalIDPrefix;
+ (id)usrLocalIDPrefix;
+ (id)singlePageModeLocalIDPrefix;
+ (id)localIDPrefixWithName:(id)a0;
+ (BOOL)isTempLocalID:(id)a0;
+ (BOOL)isStoreLocalID:(id)a0;
+ (BOOL)isUsrLocalID:(id)a0 byName:(id)a1;
+ (BOOL)isUsrLocalID:(id)a0;
+ (BOOL)isWeAppLocalID:(id)a0;
+ (id)fileExtensionFromMIMEType:(id)a0;
+ (id)mimeTypeFromFileExtension:(id)a0;
+ (BOOL)isValidMIMEType:(id)a0;
+ (id)mimeTypeFromFilePath:(id)a0;
+ (id)mimeTypeFromData:(id)a0;
+ (BOOL)generatLocalID:(id *)a0 path:(id *)a1 withAppID:(id)a2 fileType:(id)a3 fileDir:(id)a4 localIDPrefix:(id)a5;
+ (id)localIDWithLocalIDPrefix:(id)a0 md5:(id)a1 fileType:(id)a2;
+ (unsigned long long)localIDGeneratorIncreaseID;
+ (id)usrFilePathWithAppID:(id)a0 localID:(id)a1;
+ (id)tmpOrStorefilePathWithAppID:(id)a0 localID:(id)a1;
+ (void)createFileStorageDirWithAppID:(id)a0;
+ (BOOL)haveFreeSpace:(id)a0 writeSize:(unsigned long long)a1 usrPath:(id)a2;
+ (BOOL)illegalTransferLocalID:(id)a0 toLocalID:(id)a1;
+ (BOOL)CreateFileWithLimitChecking:(id)a0 ForApp:(id)a1 WithFileSize:(unsigned long long)a2;
+ (BOOL)RenameFileWithLimitChecking:(id)a0 To:(id)a1 ForApp:(id)a2;
+ (BOOL)CopyFileWithLimitChecking:(id)a0 To:(id)a1 ForApp:(id)a2;
+ (BOOL)isTempPath:(id)a0 appID:(id)a1;
+ (BOOL)haveFreeTmpSpace:(id)a0 writeSize:(unsigned long long)a1;
+ (BOOL)haveFreeTmpSpace:(id)a0;
+ (void)saveOriginalImageWithAppID:(id)a0 imageArr:(id)a1 completeHandler:(id /* block */)a2;
+ (void)saveOriginalImageWithAppID:(id)a0 imageArr:(id)a1 savefileTypes:(id)a2 completeHandler:(id /* block */)a3;
+ (id)saveTempFileWithAppId:(id)a0 fileType:(id)a1 data:(id)a2;
+ (BOOL)isUsrSpaceOverStandardWithAppId:(id)a0;
+ (BOOL)isUsrSpaceOverStandard:(id)a0;
+ (void)saveOriginalVideoWithAppID:(id)a0 asset:(id)a1 completeHandler:(id /* block */)a2;
+ (struct __CFString { } *)imageFileType2UTType:(id)a0;
+ (id)copyFileFromAppId:(id)a0 toAppId:(id)a1 fromLocalId:(id)a2;
+ (id)copyFilesFromAppId:(id)a0 toAppId:(id)a1 fromLocalIds:(id)a2;

@end
