@class NSString, NSMutableDictionary, WAPreGetLaunchLogic, WAPrefetchInvalidateResourceLogic, WAPrefetchGetCodeLogic, NSMutableArray, WAPrefetchRegisterationMark;

@interface WAPrefetchMgr : MMUserService <WAContactMgrExtension, MMServiceProtocol>

@property (retain, nonatomic) NSMutableDictionary *queue;
@property (retain, nonatomic) WAPrefetchGetCodeLogic *getCodeLogic;
@property (retain, nonatomic) WAPreGetLaunchLogic *preGetLaunchLogic;
@property (retain, nonatomic) WAPrefetchInvalidateResourceLogic *invalidateResourceLogic;
@property (retain, nonatomic) NSMutableArray *arrFetching;
@property (retain, nonatomic) NSMutableArray *arrWaiting;
@property (retain, nonatomic) NSMutableArray *arrWalletFetching;
@property (retain, nonatomic) NSMutableDictionary *prefetchFirstOpenMarks;
@property (retain, nonatomic) NSMutableDictionary *prefetchOpenMarks;
@property (retain, nonatomic) WAPrefetchRegisterationMark *registerationMark;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)dealloc;
- (void)onServiceInit;
- (void)onServiceClearData;
- (void)onServiceEnterForeground;
- (void)onServiceEnterBackground;
- (void)heartBeatCheckWeappVersion;
- (void)realHeartBeatCheckWeappVersion;
- (void)cancelHeartBeatCheck;
- (void)cancelPreDownLoadAppPkgForScene:(unsigned int)a0;
- (void)cancelPreDownLoadAppPkgForUserName:(id)a0 appid:(id)a1 path:(id)a2 moduleName:(id)a3 inScene:(unsigned int)a4;
- (id)getAppPackagePreDownloadingSpeedForScene:(unsigned int)a0;
- (id)getAppPackagePreDownloadingSpeedForUserName:(id)a0 appid:(id)a1 path:(id)a2 moduleName:(id)a3 inScene:(unsigned int)a4;
- (void)tryDoPrefetchForUserName:(id)a0;
- (void)tryDoPrefetchForUserName:(id)a0 appid:(id)a1;
- (void)tryDoPrefetchForUserName:(id)a0 appid:(id)a1 enableDownloadResumption:(BOOL)a2;
- (void)tryDoPrefetchForUserName:(id)a0 path:(id)a1 inScene:(unsigned int)a2;
- (void)tryDoPrefetchForUserName:(id)a0 appid:(id)a1 path:(id)a2 inScene:(unsigned int)a3;
- (void)tryDoPrefetchForUserName:(id)a0 appid:(id)a1 path:(id)a2 moduleName:(id)a3 inScene:(unsigned int)a4;
- (void)tryDoPrefetchForUserName:(id)a0 appid:(id)a1 path:(id)a2 moduleName:(id)a3 enableDownloadResumption:(BOOL)a4 inScene:(unsigned int)a5;
- (void)wallet_tryUpdateContactAndDoPrefetchForUsernameList:(id)a0 pathDic:(id)a1 inScene:(unsigned int)a2;
- (void)wallet_cancelPrefetchContactUpdate;
- (BOOL)isContactInvalidateWithAppid:(id)a0 updateTime:(unsigned int)a1;
- (BOOL)isCodePkgInvalidateWithAppid:(id)a0 updateTime:(unsigned int)a1;
- (unsigned int)reportIdForInvalidateContact:(id)a0;
- (unsigned int)reportIdForInvalidateCode:(id)a0;
- (id)allInvalidateCodeAppid;
- (id)allInvalidateContactAppid;
- (void)clearInvalidateContactWithAppid:(id)a0;
- (void)clearInvalidateCodeWithAppid:(id)a0;
- (void)onModifyWeAppContact:(id)a0;
- (BOOL)isUsernameInPreDownloadBlackList:(id)a0;
- (void)syncVersion;
- (void)checkWaitingQueue;
- (BOOL)requestVersionSyncForUsernameList:(id)a0;
- (id)fetchNeedSyncUsageInfoAndClearOutdatedUsageInfo;
- (id)fetchNeedSyncPredonwloadInfo;
- (id)fetchNeedForceSyncUsernameList;
- (id)getAppIDFromForceSyncUsername:(id)a0;
- (void)onCgiResponse:(id)a0 forEvent:(unsigned int)a1;
- (void)handleBatchSyncVersion:(id)a0;
- (void)handlePreDownloadCGI:(id)a0;
- (void)handlePushWxACmdMsg:(id)a0;
- (void)handleBatchSyncVersionRespList:(id)a0 preDownloadRequestkey:(id)a1;
- (void)handleBatchSyncVersionRespList:(id)a0 preDownloadRequestkey:(id)a1 scene:(unsigned int)a2;
- (void)tryCallbackPrefetchNoNeedGetCodeWithRequestKey:(id)a0;
- (id)genUniqueKeyWithUsername:(id)a0 packageKey:(id)a1;
- (void)preCheckAndEliminateGetCodeCmd:(id)a0;
- (BOOL)checkRespInfoIsValid:(id)a0;
- (void)preProcessGetContactCmd:(id)a0;
- (void)preProcessUpdateVersionCmd:(id)a0;
- (void)preProcessGetCodeCmd:(id)a0 preDownloadRequestkey:(id)a1 scene:(unsigned int)a2;
- (void)preProcessIssueContactCmd:(id)a0;
- (void)preProcessIssueLaunchCmd:(id)a0;
- (void)preProcessIssueDecryptCmd:(id)a0;
- (void)preProcessBlockCgiRequestCmd:(id)a0;
- (void)preProcessPreLaunchCmd:(id)a0;
- (void)preProcessInvalidateCodeCmd:(id)a0;
- (void)preProcessInvalidateContactCmd:(id)a0;
- (void)preProcessPullGlobalConfigCmd:(id)a0;
- (void)preProcessGetExptInfoCmd:(id)a0;
- (void)preProcessGetJsApiControlBytesCmd:(id)a0;
- (unsigned long long)preCheckSequenceForCmd:(id)a0;
- (void)pushCmd:(id)a0;
- (void)executeCmdsWithPreDownloadRequestkey:(id)a0;
- (id)popCmd;
- (void)executeGetContactCmd:(id)a0;
- (void)executeUpdateVersionCmd:(id)a0;
- (BOOL)executeGetCodeCmd:(id)a0;
- (void)executeIssueContactCmd:(id)a0;
- (void)executeIssueLaunchCmd:(id)a0;
- (void)executeIssueDecryptCmd:(id)a0;
- (void)executeBlockCgiRequestCmd:(id)a0;
- (void)executePreGetLaunchCmd:(id)a0;
- (void)executeInvalidateCodeCmd:(id)a0;
- (void)executeInvalidateContactCmd:(id)a0;
- (void)executePullGlobalConfigCmd:(id)a0;
- (void)executeGetExptInfoCmd:(id)a0;
- (void)executeGetJsApiControlBytesCmd:(id)a0;
- (void)markPkgDownloadFromPrefetchWithInfoData:(id)a0 reportKey:(unsigned int)a1;
- (void)markPrefetchPkgDidOpenWithInfoData:(id)a0 instanceId:(id)a1;
- (BOOL)isPrefetchMarkedWithInfoData:(id)a0 inMarkDic:(id)a1;
- (void)deletePrefetchMarkForInfoData:(id)a0 inMarkQueue:(id)a1;
- (void)deletePrefetchMarkForInfoData:(id)a0;
- (void)deletePrefetchMarkForUsername:(id)a0 inMarkQueue:(id)a1;
- (void)deletePrefetchMarkForUsername:(id)a0;
- (void)saveLocalMarkData;
- (id)resumeLocalFirstOpenMarkData;
- (id)resumeLocalOpenMarkData;
- (BOOL)isPrefetchSceneRegisteredGetCodeSequenceCheck:(unsigned long long)a0;
- (void)registerPrefetchGetCodeSequenceCheckForScene:(unsigned long long)a0;
- (void)saveLocalPrefetchRegisterationMarkData;
- (id)resumeLocalPrefetchRegisterationMarkData;
- (void).cxx_destruct;

@end
