@class MMUIButton, UIImage, MPLandingPageCgiHandler, WCC2CVideoThumbImageView, CMessageWrap, MMScrollViewZoomReporter, CAGradientLayer, WCDownloadArgsWrap, MPLandingPageReportLogic, MMUILabel, NSString, MMBrandHeadImageView, WCPlayerPlayArgs, WCC2CVideoPlayerReporter, WXFullScreenGestureRecognizer, WCPlayerView, WCC2CPlayerControlView;
@protocol WCC2CVideoPlayerViewTouchDelegate, WCC2CVideoPlayerViewDelegate;

@interface WCC2CVideoPlayerView : UIView <IVideoExt, FullScreenGestureDelegate, WCC2CPlayerControlViewDelegate, WCPlayerViewUIDelegate, WCC2CVideoThumbImageViewDelegate, IRoamBackupPackageServiceExt, CNetworkStatusExt> {
    double m_initialTime;
    UIImage *m_thumbImage;
}

@property (retain, nonatomic) WCPlayerView *playerView;
@property (retain, nonatomic) WCPlayerPlayArgs *playerInfo;
@property (retain, nonatomic) WCC2CPlayerControlView *controlView;
@property (retain, nonatomic) WCPlayerPlayArgs *rawPlayerInfo;
@property (retain, nonatomic) WCPlayerView *rawPlayerView;
@property (retain, nonatomic) WCC2CVideoThumbImageView *thumbImageView;
@property (nonatomic) BOOL bShouldResumeInterrupt;
@property (nonatomic) BOOL isRawVideoMode;
@property (nonatomic) BOOL isPreloadSvrRecall;
@property (retain, nonatomic) WXFullScreenGestureRecognizer *fullScreenGestureRecognizer;
@property (nonatomic) BOOL bFirstPlay;
@property (nonatomic) BOOL bPlayToEnd;
@property (nonatomic) BOOL bHasRequestedVideoState;
@property (nonatomic) BOOL bRequaringVideoState;
@property (nonatomic) BOOL bInMuteMode;
@property (nonatomic) BOOL isDisplayingPlaceHolderMsg;
@property (nonatomic) BOOL isWaitingPlayWhenReceiveFinishMsg;
@property (nonatomic) BOOL isShowRawPlaySucc;
@property (nonatomic) BOOL enableLTR;
@property (nonatomic) unsigned long long rawBtnClickTime;
@property (nonatomic) unsigned long long rawPlayStartTime;
@property (nonatomic) int action;
@property (copy, nonatomic) id /* block */ customBottomLeftActioin;
@property (copy, nonatomic) id /* block */ customBottomLeftString;
@property (retain, nonatomic) WCDownloadArgsWrap *videoSaveDownloadArgsWrap;
@property (retain, nonatomic) MMUIButton *brandContentView;
@property (retain, nonatomic) CAGradientLayer *brandMaskLayer;
@property (retain, nonatomic) MMUILabel *brandTitleView;
@property (retain, nonatomic) MMBrandHeadImageView *brandHeadView;
@property (retain, nonatomic) MMUIButton *brandNickNameView;
@property (retain, nonatomic) MMUIButton *brandOpenMpPageBtn;
@property (retain, nonatomic) MPLandingPageCgiHandler *brandCgiHandler;
@property (nonatomic) BOOL bRequestingVideoStateCgi;
@property (retain, nonatomic) MPLandingPageReportLogic *brandReportLogic;
@property (nonatomic) unsigned int brandEnterIdForReport;
@property (nonatomic) BOOL hasAddToRecentUsed;
@property (nonatomic) BOOL hasRemovedFromRecentUsed;
@property (nonatomic) BOOL bVideoIsBlocked;
@property (nonatomic) BOOL bVideoIsExpired;
@property (nonatomic) BOOL isAnimating;
@property (nonatomic) BOOL soundable;
@property (nonatomic) BOOL bForbidDragDownToClose;
@property (retain, nonatomic) CMessageWrap *msgWrap;
@property (weak, nonatomic) id<WCC2CVideoPlayerViewDelegate> delegate;
@property (weak, nonatomic) id<WCC2CVideoPlayerViewTouchDelegate> touchDelegate;
@property (retain, nonatomic) MMScrollViewZoomReporter *zoomReporter;
@property (retain, nonatomic) MMScrollViewZoomReporter *thumbZoomReporter;
@property (retain, nonatomic) WCC2CVideoPlayerReporter *reporter;
@property (nonatomic) BOOL hideCloseButton;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)notifyBrandMpVideoDealloc;
- (void)initBrandViews;
- (void)initBrandContentView;
- (void)initBrandTitleView;
- (void)initBrandHeadView;
- (void)initBrandNickNameView;
- (void)initBrandOpenMpPageBtn;
- (void)addShadowToView:(id)a0;
- (void)layoutBrandViews;
- (void)setBrandViewsHidden:(BOOL)a0;
- (void)onOpenProfile;
- (void)onOpenMpPage;
- (void)requestVideoStateByVid:(id /* block */)a0;
- (void)reportBrandMpVideoCommonEvent:(unsigned long long)a0;
- (void)reportVideoPlayCgi17537:(unsigned long long)a0;
- (void)reportBrandMpVideoPlayFail:(int)a0 localizedErrorDes:(id)a1;
- (void)reportVideoShareSuccessEvent;
- (void)initReportLogicIfNeed;
- (unsigned int)getScene;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 MsgWrap:(id)a1 Soundable:(BOOL)a2 AutoPlay:(BOOL)a3 delegate:(id)a4;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 MsgWrap:(id)a1 Soundable:(BOOL)a2 AutoPlay:(BOOL)a3 delegate:(id)a4 customBottomLeftAction:(id /* block */)a5 customBottomLeftString:(id /* block */)a6;
- (void)dealloc;
- (void)initView;
- (void)configPlayerView;
- (void)layoutSubviews;
- (void)setThumbImage:(id)a0;
- (void)setInitialTime:(double)a0;
- (id)tryGetImgFromVideoPath:(id)a0 thumbImagePath:(id)a1;
- (void)createNewMaskedImageWithImage:(id)a0;
- (void)initFullScreenGestureOnView:(id)a0;
- (void)setEnableLeftToRightClose:(BOOL)a0;
- (void)didMoveToSuperview;
- (void)setImageExpireReporter:(id)a0;
- (id)generatePlayerView;
- (id)generateRawPlayerView;
- (id)generatePlayerView:(id)a0;
- (id)generatePlayerInfo;
- (id)generateRawPlayerInfo;
- (void)onPlayPlaceHolderMsg;
- (void)onStartPlay;
- (void)reportOnRawVideoPlayEnd:(BOOL)a0;
- (void)reportOnVideoPlayEnd;
- (void)changeMsgToDownloadStatus:(unsigned int)a0;
- (BOOL)tryRequestVideoInfo;
- (BOOL)startPlay;
- (void)realPlay;
- (void)seekTo:(double)a0;
- (void)destoryWhenVideoIsBlocked:(id)a0;
- (void)stopPlay;
- (void)stopPlayerDownload:(BOOL)a0;
- (void)stopPlay:(id)a0;
- (void)interruptVideo;
- (void)resumeVideoFromInterrupt;
- (void)pause;
- (unsigned long long)totalTime;
- (double)getCurrPlayedTimeInSec;
- (double)getTotalPlaybackTimeInSec;
- (id)getAnimateView;
- (void)preparePlayerView;
- (BOOL)checkFinishMsg:(id)a0;
- (BOOL)isNeedPlayFromEveryDisplay;
- (void)blockPlayerSyncDownload:(BOOL)a0;
- (BOOL)isVideoPlaying;
- (BOOL)isVideoReadyToPlay;
- (BOOL)isPreventHiddenTool;
- (void)onClickPreviewRawVideoButton;
- (void)updateToolbar;
- (void)ReachabilityChange:(unsigned int)a0;
- (void)showToolView;
- (void)hideToolView;
- (void)setToolViewsHidden:(BOOL)a0;
- (void)setViewsHiddenOnScroll:(BOOL)a0;
- (void)setViewsHiddenOnScroll:(BOOL)a0 hideIconOnFirstPlay:(BOOL)a1;
- (void)setViewsAlphaOnMultiPageScroll:(double)a0;
- (void)handleDownloadFail;
- (void)handleDownloadExpired;
- (void)onFullScreenClose;
- (void)exitVideoPlay:(int)a0;
- (void)onFullScreenDragToRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)onFullScreenLongPressEnd;
- (void)onFullScreenBackgroundColorAlphaChange:(double)a0;
- (void)onFullScreenSingleTap;
- (void)onFullScreenDragBegin;
- (void)onFullScreenDragCancel;
- (void)onFullScreenDragEnd;
- (BOOL)shouldPreventDragDownCloseGesture;
- (double)updateBottomLeftSpace;
- (double)getBottomRightMargin;
- (void)onVideoPrepareToPlay;
- (void)onVideoPlayFail:(unsigned long long)a0 errorCode:(int)a1 LocalizedErrorDes:(id)a2;
- (BOOL)tryDownloadFromCloudBackup;
- (void)reportWhenStartPlay;
- (void)onVideoPlay;
- (void)onVideoPause;
- (void)onPlayToEnd;
- (void)onStartPlayIconClick;
- (void)onCloseVideoPlay;
- (void)onClickDetailButton;
- (void)onClickPlayButton;
- (void)onClickPlayAttachVideoBtn;
- (void)onSightProgressBarHidden;
- (void)onProgressBarBeginSeek;
- (void)onProgressBarEndSeek:(double)a0;
- (void)onSliderPlayVideo;
- (void)onSliderPauseVideo;
- (void)onClickToPlayRawVideo;
- (void)onClickToCancelPlayRawVideo;
- (BOOL)canShowShareButton;
- (BOOL)canShowDownloadButton;
- (BOOL)canShowImgFastBrowseButton;
- (BOOL)canShowMoreButton;
- (void)onClickShareButton:(id)a0;
- (void)onClickDownloadButton:(id)a0;
- (void)onClickToCancelSaveVideo;
- (void)onClickImgFastBrowseButton:(id)a0;
- (void)onClickMoreButton:(id)a0;
- (void)OnMsgDownloadVideoCommonFail:(id)a0 MsgWrap:(id)a1;
- (void)onVideoDataDownloadSuccess:(id)a0;
- (void)onVideoDataDownloadFail:(id)a0;
- (void)configPlayerViewWhenReceiveFinishMsg;
- (void)OnModMsg:(id)a0 MsgWrap:(id)a1;
- (void)playerViewWillBeginZoom:(id)a0;
- (void)playerViewDidZoom:(id)a0;
- (void)playerViewDidEndZoom:(id)a0;
- (void)playerView:(id)a0 doubleTap:(id)a1;
- (void)thumbImageViewWillBeginZoom:(id)a0;
- (void)thumbImageViewDidZoom:(id)a0;
- (void)thumbImageViewDidEndZoom:(id)a0;
- (void)thumbImageView:(id)a0 doubleTap:(id)a1;
- (void)onRoamBackupPackageServiceLoadMediaProgress:(id)a0 dataID:(id)a1 finished:(unsigned long long)a2 total:(unsigned long long)a3;
- (void)onRoamBackupPackageServiceLoadMediaResult:(id)a0 errorCode:(unsigned int)a1 dataID:(id)a2;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })adjustShowAreaForDisplayFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void).cxx_destruct;

@end
