@class NSMutableDictionary, WCFinderFeedLayoutContentVM, FinderRelatedRecommendTips, NSMutableArray, FinderStreamOftenReadBar, WCFinderAbstractTask, FinderStreamLayoutInfo, NSString, WCFinderRedDotCtrlInfo, NSMutableSet, NSArray, NSData, NSIndexPath;
@protocol WCFinderFeedFollowVMDelegate;

@interface WCFinderFeedFollowVM : WCFinderFullFeedCommonViewModel <WCFinderDataItemExt, WCFinderPostingCommentExt, WCFinderRedDotNotifyExt, WCFinderPostDataItemExt, WCFinderFeedContentVMExt, WCFinderLiveExt, WCFinderContactExt, WCFinderContactCommonExt, WCFinderStreamPrefetchExt>

@property (nonatomic) unsigned long long maxTid;
@property (nonatomic) unsigned long long commentFailTidCount;
@property (nonatomic) unsigned long long unReadMSGCount;
@property (retain, nonatomic) NSMutableArray *serverFetchTasks;
@property (retain, nonatomic) WCFinderAbstractTask *currentServerFetchTask;
@property (nonatomic) BOOL shouldFetchHistory;
@property (copy, nonatomic) NSString *historyLabelText;
@property (nonatomic) BOOL pullEnterIsEmpty;
@property (copy, nonatomic) NSArray *streamDataArray;
@property (nonatomic) BOOL hasProcessLocalData;
@property (nonatomic) BOOL needCleanData;
@property (nonatomic) BOOL hasAddHistoryTips;
@property (nonatomic) BOOL hasFetchEnterData;
@property (nonatomic) unsigned long long historyType;
@property (nonatomic) BOOL shouldRecordEnterIndexPath;
@property (retain, nonatomic) NSIndexPath *enterIndexPath;
@property (nonatomic) BOOL isFetchingLocalFeed;
@property (nonatomic) BOOL showPrivateMSGTips;
@property (retain, nonatomic) NSMutableDictionary *loadingReportDict;
@property (retain, nonatomic) NSMutableSet *unfollowUseranemSet;
@property (retain, nonatomic) WCFinderFeedLayoutContentVM *livingLayout;
@property (retain, nonatomic) FinderStreamOftenReadBar *oftenReadBar;
@property (retain, nonatomic) FinderStreamLayoutInfo *streamLayoutInfo;
@property (nonatomic) BOOL isFetchLivingStream;
@property (retain, nonatomic) NSMutableArray *preloadArray;
@property (retain, nonatomic) NSData *cardBuffer;
@property (nonatomic) unsigned long long flowViewState;
@property (retain, nonatomic) WCFinderRedDotCtrlInfo *appendRedDotCtrlInfo;
@property (nonatomic) BOOL enterFeedByAppend;
@property (retain, nonatomic) FinderRelatedRecommendTips *relatedRecommendTips;
@property (weak, nonatomic) id<WCFinderFeedFollowVMDelegate> delegate;
@property (weak, nonatomic) id<WCFinderFeedFollowVMDelegate> followTabDetailDelegate;
@property (retain, nonatomic) NSArray *commentFailTidArray;
@property (copy, nonatomic) NSString *enterDataReportID;
@property (readonly, nonatomic) NSString *partialExposedObjectId;
@property (readonly, nonatomic) BOOL noMoreData;
@property (nonatomic) unsigned long long guideBarObjectId;
@property (retain, nonatomic) NSMutableArray *topObjects;
@property (nonatomic) BOOL isByFindPage;
@property (nonatomic) BOOL postFeedInsertMachineTab;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (long long)followTabFlowStyleCacheCount;

- (id)init;
- (void)dealloc;
- (void)markShouldRecordEnterIndexPath;
- (void)recordEnterIndexPathIfNeeded;
- (void)updateFailPostComment;
- (unsigned long long)sectionNums;
- (void)onFinderContentVMDelete:(id)a0;
- (id)filterDataItemArray:(id)a0;
- (id)processServerData:(id)a0;
- (void)clearDataByServerRequestWithHasNewFeed:(BOOL)a0;
- (id)getUnreadDataItems;
- (id)getLocalCacheContentVMs;
- (void)loadingLocalData;
- (void)checkCacheDataIsValid:(id)a0;
- (void)loadingFirstPageData;
- (void)loadingNextPagePageData;
- (BOOL)shouldStopFetchNextPageByFooter;
- (id)getHotTabLastBuff;
- (BOOL)hotTabNeedTopRefresh;
- (void)loadingNextSreamFeedPage;
- (id)firstPrefetchDataItem;
- (id)fetchTopFetchStreamCGIParamsAsReadOnly:(BOOL)a0;
- (void)pullToRefreshWithPullType:(unsigned long long)a0;
- (BOOL)preserveLocalContentVMs:(unsigned long long)a0;
- (void)bindFeedWidgetInfoWithStreamLayoutInfo:(id)a0 dataItemArray:(id)a1;
- (void)resetFirstItemSilentToNo:(unsigned long long)a0;
- (void)preformNextServerFetchTasks;
- (void)checkServerFetchTasks;
- (void)_fetchHistoryWithPullType:(unsigned long long)a0 successBlock:(id /* block */)a1 failBlock:(id /* block */)a2;
- (void)fetchHistoryWithPullType:(unsigned long long)a0;
- (void)refreshLatestDataByEnter:(BOOL)a0;
- (void)fetchFirstPageData;
- (BOOL)shouldShowMoreHotContentCell;
- (long long)firstFeedNum;
- (int)tabType;
- (unsigned long long)rowNumsWithSection:(unsigned long long)a0;
- (unsigned long long)limitModeRowNumsWithSection:(unsigned long long)a0;
- (id)vaildTopIndexPath;
- (id)contentVMAtDataIndex:(unsigned long long)a0;
- (long long)dataIndexOfContentVM:(id)a0;
- (long long)dataIndexOfTid:(id)a0;
- (id)contentVMWithLocalTid:(id)a0;
- (void)clearAllContentVMLayoutCache;
- (void)changeFirstItemToMuteBeforeRefresh;
- (id)oftenReadItems;
- (void)appendEnterContentVM:(id)a0 dataItems:(id)a1 cardBuffer:(id)a2 appendRedDotCtrlInfo:(id)a3;
- (void)appendFinderContentVM:(id)a0;
- (id)transformFinderItemToContentVM:(id)a0;
- (id)transformHistoryFinderItemToContentVM:(id)a0;
- (BOOL)checkRegardfulLayout:(id)a0;
- (void)addDividerWithStreamLayoutInfo:(id)a0 contentVMArray:(id)a1;
- (BOOL)checkLivingStreamLayoutInfo:(id)a0;
- (void)contentUnlikeFeedback:(id)a0 subType:(long long)a1;
- (void)startPreloadVideoItemsWithContentVMArray:(id)a0 playedContentVMArray:(id)a1;
- (void)stopPreloadVideoItem:(id)a0;
- (void)stopAllPreloadVideoItems;
- (id)streamLoadingInfoByExitVC;
- (void)addFavRelateActionWithContentVM:(id)a0 relateActionType:(unsigned long long)a1;
- (void)fetchMoreLivingList;
- (void)updateTimelineCachePageWithTid:(id)a0;
- (unsigned long long)getTLFirstPageCacheCount;
- (void)reloadNoMoreDataWithPullType:(unsigned long long)a0;
- (void)reloadErrorPageWithPullType:(unsigned long long)a0;
- (void)finishFetchDataSuccessful:(BOOL)a0;
- (long long)convertToFluencyStartScene:(unsigned long long)a0;
- (void)onFinderDataItemDelete:(id)a0;
- (void)onFinderDataItemDeleteFromScene:(int)a0 tid:(id)a1 toastWording:(id)a2;
- (void)onFinderDataItemDeleteByUserPageMergeWithTidList:(id)a0;
- (void)onFinderDataItemCleanBySecurityUpgrade;
- (void)onFinderDataCacheHasBeCleaned;
- (void)onFinderPostSessionUpLoadSuccessful:(id)a0;
- (void)onFinderPostSessionUpLoadFailWithTid:(id)a0 errorType:(long long)a1;
- (BOOL)shouldShowUploadDataItem:(id)a0;
- (BOOL)_enableShowPostStateFeed;
- (void)onFinderPostSessionStartUpload:(id)a0;
- (void)onFinderNotifyWechatUnreadMentionCountNeedReload;
- (void)onFinderNotifyPrivateMsgTipsChange;
- (void)onFinderDataItemPostingCommentCountUpdate;
- (int)feedViewControllerScene;
- (void)updateExposureStatusOfContentVM:(id)a0;
- (void)finderStreamPrefetchFinishedWithTabType:(int)a0;
- (void)onFeedContentFoldInfoChange:(id)a0 scene:(int)a1;
- (void)onFinderLiveCloseWithTid:(id)a0;
- (void)onFinderContactFollowListHasChange:(id)a0;
- (void)filterOutDataItemsByContact:(id)a0;
- (BOOL)shouldShowGuideNextBubbleCurProgress:(double)a0;
- (id)getRecommendTips;
- (void)resetRecommendTips;
- (void)clearUnreadCacheContentVMs;
- (void)deleteAllFeedAfterTid:(id)a0;
- (void).cxx_destruct;

@end
