@class NSString, WCFinderMention, NSArray, WCFinderAuthInfo, WCFinderContact;
@protocol WCFinderWechatMentionCellViewModelDelegate;

@interface WCFinderWechatMentionCellViewModel : NSObject <WCFinderMentionInteractionExt, WCFinderDataItemExt>

@property (copy, nonatomic) NSString *showTitleString;
@property (retain, nonatomic) WCFinderMention *mention;
@property (copy, nonatomic) NSString *replyNickname;
@property (copy, nonatomic) NSString *accessibilityString;
@property (nonatomic) BOOL showFollowButton;
@property (nonatomic) struct CGSize { double width; double height; } cellSize;
@property (readonly, copy, nonatomic) NSString *headURL;
@property (readonly, copy, nonatomic) NSString *thumbURL;
@property (readonly, copy, nonatomic) NSString *title;
@property (readonly, copy, nonatomic) NSString *content;
@property (readonly, copy, nonatomic) NSString *timeString;
@property (readonly, nonatomic) unsigned long long type;
@property (readonly, copy, nonatomic) NSString *objectTid;
@property (readonly, nonatomic) BOOL isAuthor;
@property (readonly, nonatomic) BOOL isFinder;
@property (readonly, copy, nonatomic) NSString *refContent;
@property (readonly, copy, nonatomic) NSString *descriptionText;
@property (readonly, nonatomic) unsigned long long mentionID;
@property (readonly, nonatomic) unsigned long long refCommentID;
@property (readonly, nonatomic) BOOL isCommentRelated;
@property (readonly, nonatomic) BOOL isPureText;
@property (readonly, copy, nonatomic) NSString *feedText;
@property (readonly, copy, nonatomic) NSString *nonceID;
@property (readonly, copy, nonatomic) NSString *username;
@property (readonly, nonatomic) WCFinderContact *contact;
@property (readonly, nonatomic) BOOL isAggregated;
@property (readonly, copy, nonatomic) NSArray *aggregatedHeadURLArray;
@property (readonly, copy, nonatomic) NSString *suffixTitle;
@property (retain, nonatomic) WCFinderAuthInfo *authInfo;
@property (nonatomic) long long uniType;
@property (nonatomic) unsigned int followMyFirstLikeFlag;
@property (nonatomic) BOOL magicPlayed;
@property (weak, nonatomic) id<WCFinderWechatMentionCellViewModelDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithMention:(id)a0 cacheContainerWidth:(double)a1;
- (void)dealloc;
- (double)cellHeightWithWidth:(double)a0;
- (id)displayContentForMention:(id)a0 originContent:(id)a1 isCommentRelated:(BOOL)a2;
- (BOOL)supportShowThankSharingTips;
- (BOOL)canShowMagicAnimation;
- (unsigned long long)magicAnimationStyle;
- (id)magicAnimationIconPath;
- (id)titleModel;
- (id)getMentionedContentWithMention:(id)a0;
- (id)getMentionTitleWithMention:(id)a0 authInfo:(out id *)a1;
- (id)ensureAuthInfo:(id)a0;
- (id)getDisplayNameWithUsername:(id)a0 nickName:(id)a1;
- (id)getDisplayNameWithContact:(id)a0;
- (id)displayContentString;
- (id)calDisplayNameWithCommentDidsplayName:(id)a0;
- (id)mentionAccessibilityLabel;
- (unsigned long long)thankTypeForReport;
- (unsigned long long)thankStyleForReport;
- (void)modCommentLikeStatus:(BOOL)a0;
- (void)replyMentionCommentWithComment:(id)a0;
- (BOOL)followButtonShouldShow;
- (BOOL)ignoreIconShouldShow;
- (unsigned long long)userTagType;
- (BOOL)isInvalidCommentMention;
- (BOOL)isValidCommentMention;
- (BOOL)isValidBulletCommentMention;
- (unsigned long long)commentLikeIconTypeForReport;
- (BOOL)shouldShowCommentInteraction;
- (id)commentReplyIconName;
- (void)updateMentionCommentLikeStatus:(BOOL)a0;
- (void)setCommentInvalid;
- (void)onFinderMention:(id)a0 commentLikeStatusChanged:(BOOL)a1;
- (void)onFinderMentionReplyCommentSuccess:(id)a0;
- (void)onFinderMention:(id)a0 replyCommentFailWithErrorMsg:(id)a1;
- (void)onFinderMention:(id)a0 silentStateChangedTo:(BOOL)a1;
- (void)onFinderDataItemCommentLikeStatusChangeWithTid:(id)a0 commentID:(unsigned long long)a1 rootCommentID:(unsigned long long)a2 likeStatus:(BOOL)a3;
- (void)onFinderDataItemDeleteComment:(id)a0 rootCommentID:(unsigned long long)a1 tid:(id)a2;
- (void).cxx_destruct;

@end
