@class MMWebImageView, ForwardMessageLogicController, NSMutableArray, WCFinderEmptyTipsView, WCFinderLiveTopicTemplateHeaderView, NSString, FinderThemeLiveStreamResponse, NSMutableSet, FinderThemeLiveStreamShareInfo, WCFinderLiveTopicTemplateTabContainerView, NSMutableDictionary, MMFinderLiveFeedExtraInfoFetcher, MMLiveColorfulLabel, FinderThemeLiveStreamAppearance, UIView, NSData, PAGFile, WCFinderLiveStreamContainerModel, FinderLiveEcGetLiveConfigResponse_ShowAnimation_HotSellingOptions, WCFinderLivePageStayReporter, CAGradientLayer, MMTimer, WCFinderLiveTopicTemplateTabPageView, MMScrollActionSheet;

@interface WCFinderLiveTopicTemplateViewController : MMUIViewController <WCFinderTabPageViewDataSource, WCFinderTabPageViewDelegate, WCFinderLiveTopicTemplatePageManagerDelegate, WCFinderTabPageViewBasicViewDelegate, MMFinderLiveFeedExtraInfoFetcherDelegate, MMScrollActionSheetDelegate, RecentForwardScrollViewDelegate, ForwardMessageLogicDelegate, WCCommitViewResultDelegate>

@property (retain, nonatomic) WCFinderLiveTopicTemplateTabPageView *tabPageView;
@property (retain, nonatomic) UIView *navBarView;
@property (retain, nonatomic) MMLiveColorfulLabel *navLabel;
@property (nonatomic) BOOL navWasHidden;
@property (retain, nonatomic) WCFinderLiveTopicTemplateHeaderView *headerView;
@property (retain, nonatomic) WCFinderLiveTopicTemplateTabContainerView *tabContainer;
@property (retain, nonatomic) MMWebImageView *bgImgView;
@property (retain, nonatomic) WCFinderLiveStreamContainerModel *tagContainerModel;
@property (retain, nonatomic) NSMutableArray *containerModels;
@property (retain, nonatomic) NSMutableSet *exposedDataItemTids;
@property (retain, nonatomic) NSMutableDictionary *pageMgrMap;
@property (retain, nonatomic) NSString *themeId;
@property (nonatomic) BOOL isVisible;
@property (nonatomic) unsigned long long lastVisibleIndex;
@property (retain, nonatomic) WCFinderEmptyTipsView *firstScreenLoadingView;
@property (nonatomic) unsigned long long reqContainerId;
@property (retain, nonatomic) FinderThemeLiveStreamResponse *latestResp;
@property (retain, nonatomic) MMFinderLiveFeedExtraInfoFetcher *extraInfoFetcher;
@property (retain, nonatomic) MMTimer *extraInfoFetchTimer;
@property (retain, nonatomic) PAGFile *hotSalePAGFile;
@property (retain, nonatomic) FinderLiveEcGetLiveConfigResponse_ShowAnimation_HotSellingOptions *hotSellingOptions;
@property (retain, nonatomic) FinderThemeLiveStreamAppearance *currentAppearance;
@property (retain, nonatomic) FinderThemeLiveStreamShareInfo *shareInfo;
@property (retain, nonatomic) CAGradientLayer *bgGradientLayer;
@property (retain, nonatomic) WCFinderLivePageStayReporter *stayReporter;
@property (nonatomic) BOOL hasReportAppear;
@property (nonatomic) BOOL tilingSwitch;
@property (retain, nonatomic) MMScrollActionSheet *shareActionSheet;
@property (retain, nonatomic) ForwardMessageLogicController *forwardLogic;
@property (retain, nonatomic) NSData *entryBuffer;
@property (nonatomic) unsigned long long enterScene;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithThemeId:(id)a0 defaultAppearance:(id)a1 fromSceneIsTilingSwitch:(BOOL)a2;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)initBgImageView;
- (void)initNavBarView;
- (void)initMoreButton;
- (BOOL)shouldInteractivePop;
- (id)navigationBarBackgroundColor;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)onEnterForeground;
- (void)onEnterBackground;
- (void)onMoreButtonClicked;
- (BOOL)pageManagerCanAutoPlayLive:(id)a0;
- (id)getViewControllerForPageManager:(id)a0;
- (void)fetchDataForPageManager:(id)a0 fromTop:(BOOL)a1 completion:(id /* block */)a2;
- (void)pageManager:(id)a0 onDataItemExposed:(id)a1;
- (id)getHotSalePAGFileForPageManager:(id)a0;
- (id)styleInfoForPageManager:(id)a0;
- (void)feedFlowViewDidScrollInPageManager:(id)a0;
- (id)getNavLastBufferForPageManager:(id)a0;
- (id)finderTabPageView:(id)a0 pageViewAtIndex:(unsigned long long)a1;
- (void)finderTabPageView:(id)a0 switchFromIndex:(unsigned long long)a1 toIndex:(unsigned long long)a2;
- (void)finderTabPageView:(id)a0 targetAlphaOfTabContainerChanged:(double)a1;
- (double)topInsetOfFinderTabPageView:(id)a0;
- (long long)numberOfTabPageInFinderTabPageView:(id)a0;
- (double)finderTabPageView:(id)a0 heightForTabViewAtIndex:(unsigned long long)a1;
- (id)finderTabPageView:(id)a0 tabViewAtIndex:(unsigned long long)a1;
- (id)tabViewContainerInFinderTabPageView:(id)a0;
- (id)customTabContainerBackgroundColorForFinderTabPageView:(id)a0;
- (double)heightForTabViewContainerInFinderTabPageView:(id)a0;
- (void)finderTabPageView:(id)a0 didSelectIndex:(unsigned long long)a1 isTriggerByUser:(BOOL)a2;
- (double)heightForHeaderViewChangeAlphaInFinderTabPageView:(id)a0;
- (id)headerViewInFinderTabPageView:(id)a0;
- (double)heightForHeaderViewInFinderTabPageView:(id)a0;
- (BOOL)hasTabContainer;
- (int)getCommentSceneWithContainerType:(unsigned int)a0;
- (void)autoPlayCurrentLive;
- (void)stopPlayingCurrentLive;
- (void)setupNavWithAppearance:(id)a0;
- (void)layoutNavLabel;
- (void)onAppearanceUpdated;
- (void)handleWillSwitchToPage:(unsigned long long)a0 switchType:(unsigned long long)a1;
- (void)setupBackgroundColor;
- (void)startExtraInfoFetchingTimer;
- (BOOL)enabledTimedRefresh;
- (void)initFetcherIfNeeded;
- (void)scheduleExtraInfoCheckTimer;
- (void)onTimedFetchExtraInfo;
- (void)fetchExtraInfoForVisibleLiveIfNeeded;
- (void)onFeedHighlightTagUpdate:(unsigned long long)a0 tag:(id)a1;
- (void)onFeedAggregationCardUpdate:(id)a0 card:(id)a1;
- (void)onFeedProductCardUpdate:(unsigned long long)a0 card:(id)a1;
- (void)initializeShareActionSheet;
- (void)shareToChat:(id)a0;
- (void)shareToMoment;
- (id)genShareItem;
- (void)scrollActionSheet:(id)a0 didSelecteItem:(id)a1;
- (void)clickRFItemCallBack:(id)a0;
- (void)relayoutScrollSheet;
- (id)getCurrentViewController;
- (void)OnForwardMessageSend:(id)a0;
- (void)OnForwardMessageCancel:(id)a0;
- (void)onCancelForwardForForwardView:(id)a0;
- (void)onDoneForwardForForwardView:(id)a0;
- (void)forwardViewControllerDidCancel:(id)a0;
- (void)forwardViewController:(id)a0 didFinishForwardingWithDataItem:(id)a1;
- (void)requestECConfig;
- (void)loadData;
- (void)fetchDataWithIndex:(unsigned long long)a0 fromTop:(BOOL)a1 completion:(id /* block */)a2;
- (id)getUnreadDataItemList;
- (id)getContainerContextForContainer:(id)a0;
- (void)syncHotSellingOptionsToPageManagers;
- (id)getDefaultSessionExtraKey;
- (void)saveDataItemAndExtraInfosWithContainerModels:(id)a0 commentScene:(int)a1 extraKey:(id)a2;
- (id)genSessionModelWithDataItem:(id)a0 scene:(int)a1 extraKey:(id)a2;
- (id)getCommentSceneStrWithPageIndex:(unsigned long long)a0;
- (id)getReportPageUdfKVWithPageIndex:(unsigned long long)a0;
- (void)reportPageAppearWithIndex:(unsigned long long)a0;
- (void)reportPageDisappearWithIndex:(unsigned long long)a0;
- (void).cxx_destruct;

@end
