@class MMWebImageView, WCFinderAnimationLoadingView, WCFinderBulletGroupView, WCPlayerView, UILabel, MMUIButton, NSString, MMTextView, WCFinderMegaVideoViewModel, WCFinderFeedMediaWrap, WCFinderFeedImageCDNView, UIButton, NSObject, WCFinderFeedContentVM, UIView, UIPanGestureRecognizer, WCFinderPlayBar, UIStackView, UIImageView, WCFinderMediaInfo, UIScrollView, WCFinderFeedContentTextView, UITapGestureRecognizer;
@protocol WCFinderFeedLongPlayTableViewCellDelegate;

@interface WCFinderFeedLongPlayTableViewCell : UITableViewCell <WCFinderPlayBarDelegate, WCFinderMegaVideoPropertyExt, WCFinderFeedContentTextClickActionDelegate, WCAudioSessionExt, UITextViewDelegate>

@property (retain, nonatomic) WCFinderPlayBar *playBar;
@property (retain, nonatomic) MMTextView *postTextView;
@property (retain, nonatomic) UIView *postContainerView;
@property (retain, nonatomic) UILabel *postLengthLabel;
@property (retain, nonatomic) UIView *bottomView;
@property (retain, nonatomic) WCPlayerView *player;
@property (retain, nonatomic) UIButton *fullScreenBtn;
@property (retain, nonatomic) MMWebImageView *headImageView;
@property (retain, nonatomic) UILabel *userNameLabel;
@property (retain, nonatomic) UIView *topView;
@property (retain, nonatomic) MMUIButton *likeButton;
@property (retain, nonatomic) UIButton *favButton;
@property (retain, nonatomic) UIButton *shareButton;
@property (retain, nonatomic) UIButton *bulletButton;
@property (retain, nonatomic) WCFinderFeedContentTextView *descTextView;
@property (retain, nonatomic) WCFinderFeedImageCDNView *coverImageView;
@property (retain, nonatomic) UIImageView *captureImageView;
@property (retain, nonatomic) UIView *bulletActionView;
@property (retain, nonatomic) UIView *bottomFunctionView;
@property (retain, nonatomic) UIView *dangerousView;
@property (retain, nonatomic) UILabel *dangerousLabel;
@property (retain, nonatomic) UIButton *moreButton;
@property (retain, nonatomic) UIImageView *lockImageView;
@property (retain, nonatomic) UIView *rightTopView;
@property (retain, nonatomic) UIScrollView *titleScrollView;
@property (retain, nonatomic) UIStackView *titleView;
@property (retain, nonatomic) WCFinderBulletGroupView *bulletView;
@property (retain, nonatomic) WCFinderAnimationLoadingView *loadingView;
@property (retain, nonatomic) MMUIButton *playRateButton;
@property (retain, nonatomic) UIView *playRatePanel;
@property (retain, nonatomic) WCFinderFeedContentVM *contentVM;
@property (weak, nonatomic) WCFinderMegaVideoViewModel *viewModel;
@property (retain, nonatomic) NSString *url;
@property (retain, nonatomic) NSObject *dispose;
@property (nonatomic) double nextBulletRequestTime;
@property (retain, nonatomic) WCFinderFeedMediaWrap *mediaWrap;
@property (retain, nonatomic) WCFinderMediaInfo *mediaInfo;
@property (retain, nonatomic) UIPanGestureRecognizer *playerPostionPanGesture;
@property (retain, nonatomic) UITapGestureRecognizer *playerTapGesture;
@property (nonatomic) long long orientation;
@property (weak, nonatomic) id<WCFinderFeedLongPlayTableViewCellDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithStyle:(long long)a0 reuseIdentifier:(id)a1;
- (void)awakeFromNib;
- (void)onPanProgress:(id)a0;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)onKeyboardFrameChange:(id)a0;
- (void)onDismiss;
- (void)onLandscape;
- (void)onProtrait;
- (void)onEditingEnd:(id)a0;
- (void)onAvatar;
- (void)onlike;
- (void)onMiniMize;
- (void)onInPicture;
- (void)onMore;
- (void)onFav;
- (void)onShare;
- (void)hideFunctionsToggle;
- (void)onBulletToggel;
- (void)onReport;
- (void)onDeleteBullet;
- (void)onReportBullet:(id)a0;
- (void)titleExpandToggle;
- (void)onDoubleLike:(id)a0;
- (void)onPlayRate:(id)a0;
- (void)updateStatus;
- (BOOL)textView:(id)a0 shouldChangeTextInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1 replacementText:(id)a2;
- (void)textViewDidChange:(id)a0;
- (void)textViewDidBeginEditing:(id)a0;
- (void)updateFullScreenBtn;
- (double)playerHeightFitInHeight:(double)a0;
- (void)updateLayoutWithItem:(id)a0 viewModel:(id)a1 orientation:(long long)a2;
- (BOOL)createPlayerIfNeed;
- (void)setupProtraitUI;
- (void)setupBottom;
- (void)setupLandScapedBottom;
- (void)setupTop;
- (id)authorIcon;
- (void)resetFunctionState;
- (void)addGestures;
- (void)play;
- (void)stop;
- (void)stopAll;
- (void)stashPlayer;
- (void)reportPlayerInfo;
- (BOOL)canRecognizeTouch:(id)a0;
- (void)playPositionMoveBegin;
- (void)playPositionMoveChange:(double)a0;
- (void)playPositionMoveEnd;
- (BOOL)isBottomViewHidden;
- (void)inPicture;
- (void)closeInPicture;
- (BOOL)setPlayerMute:(BOOL)a0;
- (BOOL)isEditing;
- (void)setPlayRate:(double)a0;
- (void)showPlayRatePanel;
- (id)playerReporter;
- (BOOL)isAuthorView;
- (id)megaVideo;
- (void)showCapture:(id)a0;
- (void)showDoubleLikeAnimation:(struct CGPoint { double x0; double x1; })a0;
- (id)playRateTitleForRate:(double)a0;
- (void)resetBulletConfig;
- (void)updateBullet;
- (void)fetchNextPageBulletInPosition:(double)a0;
- (void)updateVideoCurrentTime:(double)a0;
- (void)onVideoStart;
- (void)onVideoEnd;
- (void)onVideoPause;
- (void)onVideoStartDrag;
- (void)onVideoLoading;
- (void)onVideoStopLoading;
- (void)onComment;
- (void)onFeedContentTextView:(id)a0 clickReadMore:(BOOL)a1 isTouchExpand:(BOOL)a2;
- (void)onFinderMegaVideoFavChanged:(id)a0 videoId:(id)a1;
- (void)onFinderMegaVideoLikeChanged:(id)a0 videoId:(id)a1;
- (void)onFinderMegaVideoBulletOpenChanged:(id)a0 videoId:(id)a1;
- (void)onFinderMegaVideoPrivateChanged:(id)a0 videoId:(id)a1;
- (void)onFinderMegaVideoUpdate:(id)a0;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (void)onWCAudioSessionOldDeviceUnavailable;
- (void).cxx_destruct;

@end
