@class UIView, NSString, UIImage, ImageBrowseButton, UIImageView, CAGradientLayer, WCActionSheet, OCRTransReport;
@protocol WCImageTranslateDelegate;

@interface WCImageTranslateLogic : NSObject

@property (retain, nonatomic) UIView *scanImageCoverView;
@property (retain, nonatomic) UIImageView *scanImageView;
@property (retain, nonatomic) ImageBrowseButton *scanCancelButton;
@property (retain, nonatomic) UIImage *translateImg;
@property (retain, nonatomic) CAGradientLayer *bottomMaskLayer;
@property (retain, nonatomic) NSString *nsBiz;
@property (retain, nonatomic) id processingItem;
@property (retain, nonatomic) NSString *currentFileId;
@property (retain, nonatomic) NSString *currentAesKey;
@property (weak, nonatomic) id<WCImageTranslateDelegate> delegate;
@property (readonly, nonatomic) BOOL preDetectWordFinish;
@property (readonly, nonatomic) BOOL isDetectResultOK;
@property (readonly, nonatomic) unsigned int detectResult;
@property (readonly, nonatomic) BOOL isImgTranslating;
@property (readonly, nonatomic) unsigned int targetRate;
@property (readonly, nonatomic) OCRTransReport *transReport;
@property (readonly, nonatomic) int source;
@property (retain, nonatomic) id currentItem;
@property (retain, nonatomic) NSString *tmpIdentifier;
@property (weak, nonatomic) UIView *weakViewToDisableInteractWhenTranslateAnimating;
@property (weak, nonatomic) WCActionSheet *weakActionSheet;
@property (nonatomic) int translateActionSheetIndex;
@property (nonatomic) BOOL isShowingTranslatedImage;
@property (nonatomic) unsigned int businessType;

- (id)init;
- (id)initWithSource:(int)a0;
- (void)updateSource:(int)a0;
- (void)dealloc;
- (BOOL)shouldDoPreDetectWord:(id)a0;
- (BOOL)shouldShowTranslateEntry:(id)a0;
- (BOOL)shouldShowTranslateEntry:(id)a0 specifiedSource:(int)a1;
- (BOOL)isDisableAlwaysShowImageTranslateEntry;
- (long long)getWordRateThresholdForImageTranslateEntry;
- (BOOL)shouldShowOCREntry:(id)a0;
- (BOOL)hasTranslateResultFile:(id)a0;
- (BOOL)hasOCRResultFile:(id)a0;
- (BOOL)hasDetectWordResultCache:(id)a0;
- (id)pathForTranslateImage:(id)a0;
- (id)getTranslateImgIdentifier:(id)a0;
- (id)getTranslateImagePath:(id)a0;
- (id)getTranslateResultImage:(id)a0;
- (void)reportTranslateImgInfo;
- (BOOL)asyncPreDetectWord:(id)a0;
- (void)commonHandlePreDetectWordSuccess:(id)a0;
- (BOOL)translateImage:(id)a0 aboveView:(id)a1 andBackView:(id)a2;
- (void)commonHandleStartAnimateTranslateImage:(id)a0;
- (void)commonHandleFinishAnimateTranslateImage:(id)a0;
- (void)showTranslateImg:(id)a0;
- (void)prepareViewForTranslateOnView:(id)a0 andBackView:(id)a1;
- (void)startOCRScanningAnimationOnView:(id)a0 selfView:(id)a1;
- (void)stopOCRScanningAnimation;
- (void)showAlertViewForNetDisconnected;
- (void)onCancelTranslate:(id)a0;
- (void)cancelTranslate;
- (void)removeTranslateViews;
- (void)forceCancelImageTranslate;
- (void)showVCForTranslateImg:(id)a0 sourceVC:(id)a1 originSnapShotView:(id)a2 originRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a3;
- (void)showVCForTranslateImg:(id)a0 sourceVC:(id)a1 originSnapShotView:(id)a2 originRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a3 disableAutoResumeNavigationBar:(BOOL)a4;
- (BOOL)saveTranslateImage:(id)a0 key:(id)a1;
- (void)clearTranslateImageWithIdentifier:(id)a0;
- (void)removeTranslateImage:(id)a0;
- (void)resetDetectStatus;
- (void)setTranslateImageLang:(unsigned long long)a0 forKey:(id)a1;
- (unsigned long long)getResultLangForItem:(id)a0;
- (void)removeTranslateImageLangStateForItem:(id)a0;
- (void)setImageDetectResult:(unsigned int)a0 forKey:(id)a1;
- (unsigned int)getDetectResultForItem:(id)a0;
- (void)removeImageDetectResultForItem:(id)a0;
- (void)reportShowActionSheet;
- (void)reportDoTranslate;
- (void)reportShowTranslateEntry;
- (void)reportShowTranslateFastEntry;
- (void)reportSaveTranslateImage;
- (void)idkeyReportTranslate;
- (void)idkeyReportCgiTranslate;
- (void)updateFileIdAndAesKey;
- (void).cxx_destruct;

@end
