@class UIView, NSString, UIColor, WCLiveBlurButtonBackView, MMLiveViewController, UIImageView, UIImage, CAGradientLayer, WCLiveBlurButtonAnimationHandler, UILabel, MMUIButton;

@interface WCLiveBlurButton : MMUIView <WCLiveBlurButtonPowerModeExt>

@property (nonatomic) BOOL isRoundCorner;
@property (retain, nonatomic) WCLiveBlurButtonBackView *backView;
@property (retain, nonatomic) WCLiveBlurButtonAnimationHandler *animationHandler;
@property (retain, nonatomic) UILabel *badgeLabel;
@property (retain, nonatomic) NSString *badgeValue;
@property (retain, nonatomic) UIView *customBackgroundView;
@property (retain, nonatomic) UIView *redDotView;
@property (readonly, nonatomic) BOOL isCurrentSupportLowPowerMode;
@property (nonatomic) BOOL lowPowerModeSwitch;
@property (nonatomic) BOOL enableStartLowPowerMode;
@property (nonatomic) BOOL isStartLowPowerMode;
@property (retain, nonatomic) UIImageView *customBgImageView;
@property (nonatomic) BOOL hasBlurEffect;
@property (nonatomic) BOOL isBtnVisible;
@property (nonatomic) BOOL hiddenValue;
@property (readonly, nonatomic) MMLiveViewController *rootLiveVC;
@property (retain, nonatomic) UIImageView *blurBackView;
@property (retain, nonatomic) CAGradientLayer *customBackgroundViewLayer;
@property (readonly, nonatomic) MMUIButton *topButton;
@property (retain, nonatomic) NSString *buttonId;
@property (retain, nonatomic) UIColor *blurEffectColor;
@property (nonatomic) BOOL removeBlurBacked;
@property (nonatomic) BOOL isExposed;
@property (nonatomic) BOOL isEnabledInTrialLive;
@property (copy, nonatomic) id /* block */ btnFrameChangeCallback;
@property (retain, nonatomic) UIImage *customBackgroundImage;
@property (retain, nonatomic) UIColor *customBackgroundColor;
@property (nonatomic) BOOL hideBySpacingControl;
@property (nonatomic) BOOL useForButtonFolder;
@property (nonatomic) BOOL disableShowAtBottomOutside;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 roundCorner:(BOOL)a1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 blurEffectColor:(id)a1 roundCorner:(BOOL)a2;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 blurEffectColor:(id)a1;
- (void)dealloc;
- (void)registerExtensions;
- (void)unRegisterExtensions;
- (void)setFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)onBlurEffectAdd;
- (void)onBlurEffectRemove;
- (void)updateHasBlurEffect:(BOOL)a0;
- (void)onBlurBtnHasBlurEffect:(BOOL)a0;
- (void)startEnlargeReduceAnimation;
- (void)startEnlargeReduceAnimation:(unsigned int)a0;
- (void)updateBgViewMasksToBounds:(BOOL)a0;
- (void)setAccessibilityLabel:(id)a0;
- (void)createCustomBackgroundImageViewIfNeeded;
- (void)layoutSubviews;
- (void)layoutUI;
- (void)layoutCustomBackgroundImageView;
- (void)layoutCustomBackgroundView;
- (id)getCustomBackgroundView;
- (void)layoutBackView;
- (id)getBlurButtonBackView;
- (void)updateBlurEffect;
- (BOOL)pointInside:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)updateBadgeValue:(id)a0;
- (void)updateBadgeNum:(unsigned long long)a0;
- (void)updateBadgeValue:(id)a0 isNum:(BOOL)a1;
- (void)updateBadgePosition;
- (void)updateRedDotAppearance:(BOOL)a0;
- (void)updateRedDotPosition;
- (void)updateLowPowerModeAbility:(BOOL)a0;
- (void)setAlpha:(double)a0;
- (void)setHidden:(BOOL)a0;
- (void)didMoveToWindow;
- (void)addBlurEffect;
- (void)addBlurEffectSnapShot:(id)a0;
- (void)recoverBlurEffectIfNeeded;
- (void)clearAllBlurEffect;
- (BOOL)canHaveBackgroundBlur;
- (void)checkBtnVisible;
- (void)onBlurBtnVisible:(BOOL)a0;
- (void)checkNeedUpdateLowPowerMode;
- (void)startLowPowerModeBlurIfNeeded;
- (void)stopLowPowerModeBlurIfNeeded;
- (void)onWCLiveBlurButtonPowerModeSwitchChange:(BOOL)a0;
- (void).cxx_destruct;

@end
