@class UIImageView, MMUIButton, UILabel, AVCaptureVideoPreviewLayer, NSDictionary, IntelligentOCRPassport, NSMutableArray, UIView, CornerView, MMUILabel, NSString, MobileOCRImage, AVCaptureSession, UIImage;
@protocol WCPayScanPassportViewControllerDelegate;

@interface WCPayScanPassportViewController : MMUIViewController <AVCaptureVideoDataOutputSampleBufferDelegate, CAAnimationDelegate>

@property (retain, nonatomic) IntelligentOCRPassport *ocr;
@property (nonatomic) unsigned long long scene;
@property (retain, nonatomic) AVCaptureSession *captureSession;
@property (retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer;
@property (nonatomic) BOOL didHandledRotate;
@property (nonatomic) BOOL didSetupUI;
@property (retain, nonatomic) MMUIButton *closeButton;
@property (retain, nonatomic) UIView *containerView;
@property (retain, nonatomic) UIView *scanStatusView;
@property (retain, nonatomic) UIImageView *scanStatusIcon;
@property (retain, nonatomic) UILabel *scanStatusLabel;
@property (nonatomic) long long edgeFailedCount;
@property (nonatomic) long long stableFailedCount;
@property (nonatomic) unsigned long long startTime;
@property (nonatomic) unsigned int frameCount;
@property (retain, nonatomic) MMUILabel *tipsLabel;
@property (retain, nonatomic) NSMutableArray *resultRects;
@property (retain, nonatomic) UIImageView *scanLineView;
@property (nonatomic) double scanLineTopCenterY;
@property (nonatomic) double scanLineBottomCenterY;
@property (retain, nonatomic) CornerView *leftTopView;
@property (retain, nonatomic) CornerView *rightTopView;
@property (retain, nonatomic) CornerView *rightBottomView;
@property (retain, nonatomic) CornerView *leftBottomView;
@property (nonatomic) int captureWidth;
@property (nonatomic) int captureHeight;
@property (nonatomic) int viewWidth;
@property (nonatomic) int viewHeight;
@property (nonatomic) int statusResetCount;
@property (nonatomic) int frameResetCount;
@property (retain, nonatomic) MobileOCRImage *reuseImage;
@property (nonatomic) BOOL didPlayingScanAnimation;
@property (nonatomic) BOOL didInNormalScanProcess;
@property (retain, nonatomic) UIImage *onlyReflectionPhoto;
@property (nonatomic) long long minWeightingReflectionPixels;
@property (nonatomic) BOOL shouldEnterLeanFrontScan;
@property (nonatomic) BOOL didInLeanFrontScanProcess;
@property (retain, nonatomic) UIImage *leanFrontOnlyReflectionPhoto;
@property (nonatomic) long long leanFrontMinWeightingReflectionPixels;
@property (nonatomic) BOOL didRecognizeLeanFront;
@property (nonatomic) BOOL shouldEnterLeanBackScan;
@property (nonatomic) BOOL didInLeanBackScanProcess;
@property (retain, nonatomic) UIImage *leanBackOnlyReflectionPhoto;
@property (nonatomic) long long leanBackMinWeightingReflectionPixels;
@property (nonatomic) BOOL didRecognizeLeanBack;
@property (retain, nonatomic) UILabel *leanTipsLabel;
@property (retain, nonatomic) UIView *fixedScanFrameView;
@property (retain, nonatomic) UIImageView *leftTopCorner;
@property (retain, nonatomic) UIImageView *rightTopCorner;
@property (retain, nonatomic) UIImageView *rightBottomCorner;
@property (retain, nonatomic) UIImageView *leftBottomCorner;
@property (retain, nonatomic) UIImageView *vectorImageView;
@property (nonatomic) BOOL shouldPlayLeanAnimation;
@property (nonatomic) long long leanDirection;
@property (retain, nonatomic) UILabel *leanAnimateLabel;
@property (nonatomic) long long pitchDetectTotalWindow;
@property (nonatomic) long long pitchDetectLeanFrontWindow;
@property (nonatomic) long long pitchDetectLeanBackWindow;
@property (weak, nonatomic) id<WCPayScanPassportViewControllerDelegate> delegate;
@property (nonatomic) BOOL use4KMode;
@property (nonatomic) BOOL testMissingModel;
@property (nonatomic) BOOL testEngineError;
@property (nonatomic) BOOL testOutputError;
@property (retain, nonatomic) NSDictionary *scanDetailMsgMap;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (unsigned long long)getSession;
- (void)setSession:(unsigned long long)a0;
- (id)init;
- (void)continueFocus;
- (void)dealloc;
- (void)viewDidLoad;
- (void)setupCornerView;
- (void)viewWillDisappear:(BOOL)a0;
- (void)UISplitViewWillChangeSplitMode;
- (void)setupScanLineView;
- (void)setupCloseButton;
- (double)getCloseBtnCenterY;
- (void)onCloseButtonClicked;
- (void)updateContainerView;
- (void)updateScanStatusView;
- (void)updateScanStatusIcon;
- (void)updateScanStatusLabel;
- (void)hideScanStatus;
- (void)viewDidAppear:(BOOL)a0;
- (void)timeOutTips;
- (void)leanFrontTimeOutTips;
- (void)leanBackTimeOutTips;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewDidTransitionToNewSize;
- (BOOL)useTransparentNavibar;
- (void)setupUI;
- (void)setupEngine;
- (void)setupInput;
- (void)setupScanSize;
- (BOOL)setupIDCardEngine;
- (void)setupImageBuffer;
- (void)setupVideoDataOutput;
- (void)onCloseButtonCallback;
- (void)onReturn;
- (void)onFail;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })viewBounds;
- (float)getRotateRadius:(long long)a0;
- (void)handleVisible:(BOOL)a0 forView:(id)a1;
- (void)setBarViewToInvisible:(id)a0;
- (void)stopEngine;
- (void)continuousAutoFocus:(struct CGPoint { double x0; double x1; })a0;
- (BOOL)useHighResolution;
- (void)startCapture;
- (void)stopCapture;
- (BOOL)addOutput:(id)a0;
- (void)updateFrameStatus:(const void *)a0;
- (void)captureOutput:(id)a0 didOutputSampleBuffer:(struct opaqueCMSampleBuffer { } *)a1 fromConnection:(id)a2;
- (id)getPassportScanImageRectWithPassport:(const void *)a0;
- (void)animateScanStatusWithTips:(id)a0;
- (void)startLeanAnimation;
- (void)hideFixedScanFrame;
- (void)setupFixedScanFrameView;
- (void)updateLeanAnimationLabel;
- (id)handleOCRImageToUIImage:(id)a0 withPassport:(const void *)a1;
- (void)startScanLineAnimation;
- (void)stopScanLineAnimation;
- (void)reportDetail:(unsigned long long)a0;
- (void)reportTips:(id)a0;
- (BOOL)shouldEnableMultiAnglesProcess;
- (unsigned long long)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)isVerticalScreen;
- (unsigned long long)providedInterfaceOrientationMaskInIphone;
- (void).cxx_destruct;

@end
