@class NSDictionary, WCPayOfflineBlockTipsView, MMUIView, MMUILabel, UIDynamicAnimator, NSString, WCPayOfflinePayAddNewCardTipsView, WCPayOfflinePayCreateOfflinePayTipsView, WCPayOfflineDisableBlockTipsView, WCPayOfflinePayInvalidCheckTipsView, WCPayOfflinePayCodeView, WCPayOfflinePayPageJumpInfo, UIButton, WCPayOfflinePayBottomButton, WCPayOfflinePayNoCodeTipsView, WCPayOfflinePaymentTipsBarView, NSObject, WCUIAlertView, WCPayOfflineEnablePageTipsView, WCPayOfflinePayGuideBarView, WCPayOfflinePaySelectPayCardView, RichTextView, WCPayBindCardInfo, WCPayPickerView, WCPayWebImageView, UIAttachmentBehavior;
@protocol WCPayOfflinePayViewControllerDelegate, OS_dispatch_queue;

@interface WCPayOfflinePayViewController : WCPayBaseViewController <MMTipsViewControllerDelegate, WCPayOfflinePayCodeViewDelegate, UIGestureRecognizerDelegate, MMKernelExt, IdleTimerUtilExt, WCPayNoticeBannerDelegate, WCPayOfflinePayInvalidCheckTipsViewDelegate, WCPayOfflinePaySelectPayCardViewDelegate, WCPayOfflineAddNewCardTipsViewDelegate, WCPayOfflinePayCreateOffinePayTipsViewDelegate, WCPayOfflinePayNoCodeTipsViewDelegate, WCPayWalletLockVerifyLogicDelegate, WCPayWalletLockSettingLogicDelegate, WCPayOfflinePayGuideBarViewDelegate, WCPayOfflinePayBlockTipsViewDelegate, WCPayOfflineDisableBlockTipsViewDelegate, WCPayOfflineEnablePageTipsViewDelegate, WCActionSheetDelegate, ILinkEventExt, WCPayPickerViewDelegate, WCPayLogicMgrExt> {
    id<WCPayOfflinePayViewControllerDelegate> m_delegate;
    BOOL m_bFreezeAlertShowed;
    BOOL m_bReadAgreement;
    UIButton *footerButton;
    RichTextView *m_cardInfoLabel;
    WCPayOfflinePayCodeView *m_PayOfflinePayCodeView;
    int m_enCurrentOfflinePayCodeDisplayScene;
    double _oldBrightness;
    WCPayPickerView *m_pickerView;
    WCPayWebImageView *_bankIcon;
    WCPayOfflinePayBottomButton *_changeCardBtn;
    NSString *_cacheCode;
    NSObject<OS_dispatch_queue> *_cacheQueue;
    BOOL _isRefreshing;
    BOOL _triggeredGetToken;
    UIAttachmentBehavior *_attachment;
    MMUIView *_cardInfoView;
    NSDictionary *m_dicBanners;
    double bannerHeight;
}

@property (retain, nonatomic) UIDynamicAnimator *animator;
@property (nonatomic) unsigned int patternLockLogicTag;
@property (nonatomic) BOOL isPatternLockShowing;
@property (retain, nonatomic) WCUIAlertView *snapshotAlertView;
@property (nonatomic) BOOL bHasCheckFirstTips;
@property (retain, nonatomic) WCPayOfflinePayInvalidCheckTipsView *invalidTipsView;
@property (retain, nonatomic) WCPayOfflinePaySelectPayCardView *selectCardView;
@property (nonatomic) BOOL bIsAllCardNotSupportOfflinePay;
@property (retain, nonatomic) WCPayOfflinePayAddNewCardTipsView *addNewCardTipsView;
@property (nonatomic) BOOL bIsShowingAddNewCardTipsView;
@property (retain, nonatomic) WCPayOfflinePayCreateOfflinePayTipsView *createOfflinePayTipsView;
@property (retain, nonatomic) WCPayOfflinePayNoCodeTipsView *noCodeTipsView;
@property (nonatomic) BOOL bNeedShowNoCodeTipsView;
@property (nonatomic) BOOL bIsNavigateToReceiveLogic;
@property (nonatomic) BOOL bNeedShowReCreateOfflinePayTipsView;
@property (retain, nonatomic) MMUIView *actionBarView;
@property (nonatomic) BOOL bIsFirstRefresh;
@property (retain, nonatomic) MMUILabel *bankNameLabel;
@property (retain, nonatomic) MMUILabel *bankDescLabel;
@property (retain, nonatomic) MMUILabel *bankForbidWordLabel;
@property (retain, nonatomic) MMUIView *headerContentView;
@property (nonatomic) BOOL needRefreshCardList;
@property (nonatomic) BOOL needShowPayCardListAfterRefresh;
@property (retain, nonatomic) WCPayBindCardInfo *selectedCardNotSave;
@property (retain, nonatomic) WCPayOfflinePayGuideBarView *guideBarView;
@property (retain, nonatomic) WCPayOfflinePaymentTipsBarView *tipsBarView;
@property (nonatomic) BOOL bHasReportGuideBarShow;
@property (retain, nonatomic) WCPayOfflineBlockTipsView *blockTipsView;
@property (nonatomic) BOOL needRefreshData;
@property (retain, nonatomic) NSDictionary *refreshExtraInfo;
@property (retain, nonatomic) WCPayOfflineDisableBlockTipsView *disableBlockTipsView;
@property (nonatomic) BOOL bHasManualChangeCard;
@property (nonatomic) BOOL openProtocolClickFlag;
@property (retain, nonatomic) WCPayOfflinePayPageJumpInfo *pageJumpInfo;
@property (retain, nonatomic) WCPayOfflinePayBottomButton *pageJumpEntryView;
@property (nonatomic) BOOL bIsManualCloseTipsView;
@property (nonatomic) BOOL bIsCaptureWhenViewDisappear;
@property (retain, nonatomic) WCPayOfflineEnablePageTipsView *enableTipsView;
@property (nonatomic) BOOL bIsUpdateCodeAfterSetPayment;
@property (nonatomic) long long entryScene;
@property (nonatomic) BOOL isViewDidAppear;
@property (nonatomic) BOOL bNeedUpdateCodeView;
@property (nonatomic) BOOL bRefreshFromCreateOfflinePay;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)dealloc;
- (id)init;
- (id)navigationBarBackgroundColor;
- (void)onClickLeftBarButton;
- (long long)overrideUserInterfaceStyle;
- (void)viewDidLoad;
- (void)viewDidBePoped:(BOOL)a0;
- (void)adjustSubviewRects;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)doBackForTimeout;
- (void)viewWillDisappear:(BOOL)a0;
- (void)willAppear;
- (void)willDisappear;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewDidTransitionToNewSize;
- (void)OnOfflinePayCancelPosNotification:(id)a0;
- (void)setupHeaderContentView;
- (id)getActionBarView;
- (void)setupJumpInfoEntry;
- (void)jumpInfoEntryViewClick;
- (void)setupBottomButtonView;
- (id)genBottomButtonWithTitle:(id)a0 actionSelector:(SEL)a1 logoImg:(id)a2 buttonSize:(struct CGSize { double x0; double x1; })a3 bIsFirstBtn:(BOOL)a4 bIsLastBtn:(BOOL)a5 bNeedShowRedDot:(BOOL)a6 reddotshowWording:(id)a7 bNeedShowSmallReddot:(BOOL)a8;
- (id)createPayCodeView;
- (void)setupChangeCardView;
- (void)refreshViewWithData:(id)a0;
- (void)handleCodeViewRefreshFlag;
- (void)reloadTableView;
- (void)UpdateBarCodeImage;
- (void)UpdateQRCodeImage;
- (void)updateCodeImage;
- (void)updateCodeInNewWay;
- (BOOL)checkIfNeedSetPaymentBeforeUpdateCode:(id)a0;
- (void)updateCodeInNewWayWithTips:(BOOL)a0;
- (void)changeCodeScene;
- (void)onMoreAction:(id)a0;
- (void)onReadAgreement:(id)a0;
- (BOOL)preViewControllerIsKindOf:(Class)a0;
- (void)actionSheet:(id)a0 clickedButtonAtIndex:(long long)a1;
- (void)setDelegate:(id)a0;
- (void)onClickedReadSupportBanks;
- (void)exitFullScreenIfNeedAnimation:(BOOL)a0;
- (void)updateCodeImageAndStartAutomaticUpdate;
- (void)receiveMoneyBtnPress:(id)a0;
- (void)grouppayBtnPress:(id)a0;
- (void)f2fHongBaoBtnPress:(id)a0;
- (void)qrcoderewardBtnPress:(id)a0;
- (void)transferToMix:(id)a0;
- (void)transferToBankCardBtnPress:(id)a0;
- (void)removeButtonRedDot:(id)a0;
- (void)scrollContentToBottom;
- (void)showSelectedCardView;
- (void)cleanViewControllerBeforeShowPaidSucc;
- (void)preLoadTokensIfNeed;
- (BOOL)checkIfAllCardCannotUseForOfflinePay;
- (id)getOfflinePayHelpUrl;
- (BOOL)needShowBottomBusinessEntry;
- (BOOL)needShowPreferCardChangeTips;
- (void)onLinkClicked:(id)a0 withRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)OnShouldChangeCard:(id)a0;
- (void)WCPayPickerViewDidChooseRow:(long long)a0 atSession:(long long)a1;
- (void)WCPayPickerViewDidChooseRowTitle:(id)a0 atSessionTitle:(id)a1;
- (id)currentCardInfoShouldUse;
- (id)bankLogoUrlStrFromType:(id)a0;
- (void)increaseBrightnessIfNeed;
- (void)clearOfflinePayAndPopWithoutAlert;
- (void)onCloseOfflinePay;
- (void)onChooseCardIndex:(long long)a0;
- (void)onUserChooseCardForOfflinePay:(id)a0;
- (void)OnGetBarCodeFromQRCodeResponse:(id)a0 Error:(id)a1;
- (void)OnQueryOfflinePayLimit:(id)a0 fromCache:(BOOL)a1 Error:(id)a2;
- (void)onOffPayPauseAlertViewBtnClick;
- (void)OnShouldChangePayCardError:(id)a0 ErrorType:(unsigned int)a1;
- (void)OnOfflinePayTokenInfoUpdated:(BOOL)a0;
- (void)OnOfflinePayTokenGetEnablePageData;
- (void)OnGetReceiveOrPayReddotData;
- (void)onKickQuit;
- (void)wcPayOfflinePayCodeViewExitFullScreenAnimationFinished:(id)a0;
- (void)wcPayOfflinePayCodeViewBeginToShowFullScreen;
- (void)wcPayOfflinePayCodeViewAutoRefreshCountingFinished:(id)a0;
- (void)wcPayOfflinePayCodeViewClickViewBarCodeBtn;
- (void)motionEnded:(long long)a0 withEvent:(id)a1;
- (void)onApplicationWillEnterForeground:(id)a0;
- (void)walletLockVerifySuccess:(id)a0;
- (BOOL)walletLockVerifyLogicNeedBlock:(id)a0;
- (void)walletLockDidClose:(id)a0;
- (void)touchLockDidSetup:(id)a0;
- (void)patternLockDidSetup:(id)a0;
- (void)onIdleTimerUtilVoipQuit;
- (float)topMarginOfTipView;
- (float)cardInfoContentHeight;
- (float)guideBarHeight;
- (float)tipsViewContentHeight;
- (void)banner:(id)a0 clickWithUrl:(id)a1;
- (id)getNoticeBanner;
- (void)userDidTakeScreenshot:(id)a0;
- (void)didChangeScreenCapture:(id)a0;
- (void)handleScreenDuringCapture;
- (void)checkAndShowFirstTips;
- (void)paycodeviewAccessibilityHide;
- (void)paycodeViewAccessibilityShow;
- (void)showInvalidTipsView;
- (void)hideInvalidTipsView;
- (void)initInvalidTipsView;
- (void)wcPayOfflinePayInvalidCheckViewClickConfirmBtn:(BOOL)a0;
- (void)wcPayOfflinePayInvalidCheckViewClickViewDetailLink;
- (void)onSelectPayCardViewCancel;
- (void)onSelectPayCardViewReturnWithNewSelectCardBindSerial:(id)a0;
- (void)onSelectPayCardViewClickForbidUrl:(id)a0 isFQF:(BOOL)a1;
- (void)onSelectPayCardViewClickForbidTinyAppUsername:(id)a0 appPath:(id)a1 isFQF:(BOOL)a2;
- (void)showAddNewCardTipsView;
- (void)hideAddNewCardTipsView;
- (id)wcPayOfflineAddNewCardTipsViewGetTipsTitleContent;
- (void)wcPayOfflineAddNewCardTipsViewClickAddCardBtn;
- (void)wcPayOfflineAddNewCardTipsViewClickViewPayCardBtn;
- (void)showCreateOfflinePayTipsView;
- (void)showReCreateOfflinePayTipsView;
- (void)wcPayOfflinePayCreateOffinePayViewClickConfirmBtn;
- (void)wcPayOfflinePayCreateOffinePayViewClickSafeTips;
- (void)wcPayOfflinePayCreateOffinePayViewClickProtocolUrl:(id)a0;
- (BOOL)getProtocolClickFlag;
- (void)updateProtocolClickFlag:(BOOL)a0;
- (void)showNoCodeTipsView;
- (void)showNoCodeTipsView:(id)a0;
- (void)hideNoCodeTipsView;
- (void)wcPayOfflinePayNoCodeTipsViewClickRefreshBtn;
- (void)OnGetT2BCEntryMsg;
- (BOOL)needShowEnableTipsView;
- (void)showEnableOfflinePayTipsView;
- (void)onOfflinePayEnableTipsViewClickVerifyBtn;
- (void)viewCotnrollerDidBecomeActive:(id)a0;
- (void)onClickTipsBtn:(id)a0 Index:(long long)a1;
- (id)getCurrentSelectedCardInfo;
- (void)saveCurrentSelectedCardWithCardInfo:(id)a0;
- (void)refreshDefaultCardInfoAfterV2AuthCodeSetPayment:(id)a0;
- (BOOL)refreshDefaultCardInfoWithBindSerail:(id)a0;
- (void)showBlockTipsView;
- (void)hideBlockTipsView;
- (void)offlinePayBlockTipsViewClickConfirmBtn;
- (void)offlinePayBlockTipsViewClickOpenTinyAppWithExtraInfo:(id)a0;
- (void)showDisableBlockTipsView;
- (void)hideDisableBlockTipsView;
- (void)offlinePayDiableBlockTipsViewClickConfirmBtn;
- (void)openH5WithUrlString:(id)a0 needRefreshData:(BOOL)a1;
- (void)openTinyAppWithUsername:(id)a0 path:(id)a1 needRefresh:(BOOL)a2;
- (BOOL)shouldShowGuideBar:(id)a0;
- (BOOL)shouldAutoHideGuideBar:(id)a0;
- (void)onGuideBarClick;
- (void)handleClickCardSwitchTypeGuideBar;
- (void)handleClickOperateTypeGuideBar;
- (void)registerYReportSdk;
- (void).cxx_destruct;

@end
