@class UIScrollView, UIView, WCPayTransferMoneyAntiCheatUIView, NSString, WCPayTextField, UIButton, WCPayRemarkPageSheet, RichTextView, WCPayDecimalKeyboardView, WCPayWebImageView, UILabel;
@protocol WCPayTransferToBankCardViewControllerDelegate;

@interface WCPayTransferToBankCardViewController : WCPayBaseViewController <WCPayCurrencyInputViewDelegate, ILinkEventExt, WCPayDecimalKeyboardViewDelegate, WCPayTransferMoneyAntiCheatButtonDelegate, WCPayRemarkPageSheetDelegate>

@property (retain, nonatomic) UIScrollView *m_backgroundView;
@property (weak, nonatomic) id<WCPayTransferToBankCardViewControllerDelegate> m_delegate;
@property (retain, nonatomic) UIView *m_headerView;
@property (retain, nonatomic) UIView *m_footerView;
@property (retain, nonatomic) UIView *m_panelView;
@property (retain, nonatomic) UIView *m_lineView;
@property (retain, nonatomic) UIView *m_bottomDetailView;
@property (retain, nonatomic) UIView *m_chargeFeeLabelView;
@property (retain, nonatomic) UIView *m_totalAmountLabelView;
@property (retain, nonatomic) UIView *m_commentTextLabelView;
@property (retain, nonatomic) UIButton *m_confirmButton;
@property (retain, nonatomic) WCPayWebImageView *m_bankIconView;
@property (retain, nonatomic) UILabel *m_bankInfoLabel;
@property (retain, nonatomic) UILabel *m_receiverNameLabel;
@property (retain, nonatomic) UILabel *m_inputTitleLabel;
@property (retain, nonatomic) UILabel *m_chargeFeeLabel;
@property (retain, nonatomic) UILabel *m_totalAmountLabel;
@property (retain, nonatomic) WCPayTextField *m_currencyInputView;
@property (retain, nonatomic) RichTextView *m_commentTextView;
@property (retain, nonatomic) UILabel *unitLabel;
@property (retain, nonatomic) UIView *inputContainer;
@property (retain, nonatomic) WCPayDecimalKeyboardView *keyboard;
@property (nonatomic) double bottomDetailViewLeftMaxWidth;
@property (retain, nonatomic) WCPayTransferMoneyAntiCheatUIView *noticeBanner;
@property (retain, nonatomic) WCPayRemarkPageSheet *remarkPageSheet;
@property (retain, nonatomic) NSString *remarkContent;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (BOOL)useBlackStatusbar;
- (BOOL)useTransparentNavibar;
- (void)setDelegate:(id)a0;
- (void)viewDidLoad;
- (void)onBack;
- (void)onRightBarButtonClick;
- (void)initView;
- (void)viewDidLayoutSubviews;
- (void)viewDidBePoped:(BOOL)a0;
- (void)refreshViewWithData:(id)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)updateViewData;
- (void)updateBackgroundView;
- (void)scrollViewDidScroll:(id)a0;
- (void)updateNavigationbarItem;
- (void)updateHeaderView;
- (void)updateBankIconView;
- (void)updateDescriptionView;
- (void)updateFooterView;
- (void)updatePanelView;
- (void)updateNoticeItemView;
- (void)updateRoundCorner;
- (void)updateBottomDetailView;
- (void)updateBottomDetailViewRightView;
- (void)updateFeeChargeLabel;
- (void)updateTotalAmountLabel;
- (void)updateComentTextLabel;
- (void)updateCommentTextView;
- (void)updateConfirmButton;
- (double)getRealtimeChargeFee:(double)a0;
- (void)updateInputTitleLabel;
- (void)updateInputContainer;
- (void)updateUnitLabel;
- (void)textFieldDidChange;
- (void)showKeyboard;
- (void)updateCurrencyInputView;
- (void)updateLineView;
- (void)onInputTextChangeToString:(id)a0;
- (void)updateConfirmButtonStatus;
- (void)onLinkClicked:(id)a0 withRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)showRemarkPageSheet;
- (void)pageSheetCancel;
- (void)pageSheetConfirmWithRemark:(id)a0;
- (void)updateViewAfterPageSheetDismiss;
- (void)onButtonConfirm;
- (id)keyboardHostViewController;
- (void)keyboardViewConfirmBtnClick:(id)a0;
- (void)closeAllKeyboards;
- (void)viewDidBePushed:(BOOL)a0;
- (void)delayShowKeyboard;
- (void)onWCPayAntiCheatButtonClickWithH5:(id)a0;
- (void).cxx_destruct;

@end
