@class WCRedEnvelopesStoryViewController, ContactUpdateHelper, MMUILabel, CEmoticonWrap, UILabel, MMEmoticonView, NSString, WCUITextField, EmoticonCustomAddLogicController, WCRedEnvelopesStoryDargUtil, AVAudioPlayer, CMessageWrap, UIButton, UIView, WCActionSheet, SharePreConfirmSheetView, WCRedEnvelopesCommentInputToolView, UIImageView, RichTextView, EmoticonBoardView, MMTableView;
@protocol WCRedEnvelopesRedEnvelopesDetailViewControllerDelegate;

@interface WCRedEnvelopesRedEnvelopesDetailViewController : WCRedEnvelopesBaseViewController <WebAddContactDelegate, EmoticonBoardViewDelegate, BaseEmoticonViewDelegate, EmoticonCustomAddLogicControllerDelegate, WCActionSheetDelegate, SharePreConfirmSheetViewDelegate, WCActionSheetDelegate, WCRedEnvelopesStoryViewControllerDelegate, WCPlayerConfigDelegate, EmoticonSearchViewControllerDelegate, WCPlayerDownloaderExt, WCPlayerConfigDelegate, UITableViewDelegate, UITableViewDataSource, WCRedEnvelopesCommentInputToolViewDelegate> {
    id<WCRedEnvelopesRedEnvelopesDetailViewControllerDelegate> m_delegate;
    BOOL m_loadingMoreOrderList;
    MMTableView *m_tableView;
    BOOL m_bDidBack;
    WCUITextField *m_oWishingTextField;
    UIView *m_oHeaderView;
    WCRedEnvelopesCommentInputToolView *oWCRedEnvelopesCommentInputToolView;
    UIView *oMsgAnimationView;
    UIView *oMoneyAnimationView;
    UIView *oTableAnimationView;
    UIView *oTopHeaderView;
    UIView *oNavigationBarView;
    UIImageView *commentImageView;
    UIButton *commentButton;
    AVAudioPlayer *luckyPlayer;
    AVAudioPlayer *whistlePlayer;
    UIButton *tailBtn;
    UIView *oBottomView;
    BOOL hasChangeBackgroundY;
}

@property (retain, nonatomic) ContactUpdateHelper *m_helperForSenderNickName;
@property (retain, nonatomic) ContactUpdateHelper *m_helperForSenderNickNameAnimation;
@property (retain, nonatomic) UIView *m_pinImageViewAnimation;
@property (retain, nonatomic) UIView *m_pinImageView;
@property (retain, nonatomic) MMEmoticonView *emoticonView;
@property (retain, nonatomic) UIButton *thxEmoticonBtn;
@property (retain, nonatomic) UIButton *thxEmoticonTipsBtn;
@property (retain, nonatomic) MMEmoticonView *thxEmoticonView;
@property (retain, nonatomic) RichTextView *thxEmoticonTextView;
@property (retain, nonatomic) UIView *thxEmoticonBkgView;
@property (retain, nonatomic) UIButton *sendThxEmoticonBtn;
@property (retain, nonatomic) CEmoticonWrap *thxEmoticonWrap;
@property (retain, nonatomic) NSString *thxEmoticonText;
@property (retain, nonatomic) UIImageView *changeIconImgView;
@property (retain, nonatomic) UIImageView *loadingImgView;
@property (retain, nonatomic) MMUILabel *loadingLabel;
@property (retain, nonatomic) UILabel *m_receivedInfoLable;
@property (nonatomic) BOOL bIsEmoticonBoardViewShow;
@property (retain, nonatomic) EmoticonBoardView *emoticonBoardView;
@property (retain, nonatomic) EmoticonCustomAddLogicController *emoticonCustomAddLogic;
@property (nonatomic) double maskViewBottom;
@property (retain, nonatomic) UIView *emoticonBoardViewTopMaskView;
@property (retain, nonatomic) SharePreConfirmSheetView *sharePreConfirmSheetView;
@property (retain, nonatomic) CMessageWrap *thxEmoticonMsgWrap;
@property (retain, nonatomic) UIButton *bottomTailBtn;
@property (retain, nonatomic) UIImageView *topCoverImgView;
@property (retain, nonatomic) UIButton *detailLinkBtn;
@property (retain, nonatomic) UILabel *nickNameLabel;
@property (retain, nonatomic) UILabel *descLabel;
@property (retain, nonatomic) UILabel *personalWaterMarkLabel;
@property (retain, nonatomic) UIView *headImageView;
@property (retain, nonatomic) UIView *fightingIcon;
@property (retain, nonatomic) UIView *senderEmoticonView;
@property (retain, nonatomic) UILabel *moneyLabel;
@property (retain, nonatomic) UILabel *feeTypeLabel;
@property (retain, nonatomic) UIButton *jumpBalanceBtn;
@property (retain, nonatomic) UIImageView *topSkinBottomImageView;
@property (retain, nonatomic) UIImageView *m_headerRedSkinMaskCurveView;
@property (retain, nonatomic) UIImageView *m_globalRedSkinMaskCurveView;
@property (retain, nonatomic) WCRedEnvelopesStoryViewController *m_redSkinStoryVC;
@property (retain, nonatomic) WCRedEnvelopesStoryDargUtil *m_storyDragAnimationUtil;
@property (nonatomic) double currentTableViewOffSetY;
@property (nonatomic) BOOL hasShowGuideAnimate;
@property (nonatomic) BOOL isDisappearFromStory;
@property (nonatomic) BOOL isRefreshInAnimation;
@property (retain, nonatomic) UIImageView *storyMaskLoadingView;
@property (retain, nonatomic) UIImageView *m_globalStoryGuideHandImageView;
@property (retain, nonatomic) UILabel *m_globalStoryGuideLabel;
@property (nonatomic) BOOL m_isStoryShowing;
@property (nonatomic) unsigned int enterTimeStamp;
@property (nonatomic) unsigned int exitTimeStamp;
@property (retain, nonatomic) UIButton *exposeBtn;
@property (nonatomic) BOOL bHasReportExposeBtnShow;
@property (retain, nonatomic) UIView *emoticonBoardMask;
@property (retain, nonatomic) UIView *emoticonBoardBackground;
@property (retain, nonatomic) UILabel *finderDesignHBWarningLabel;
@property (retain) WCActionSheet *m_actionSheet;
@property (retain, nonatomic) UIImageView *bottomMaskImageView;
@property (nonatomic) int enWCRedEnvelopesRedEnvelopesDetailViewControllerScene;
@property (nonatomic) BOOL m_bEnterpriseRedEnvelopes;
@property (nonatomic) unsigned int m_uiStatFromScene;
@property (nonatomic) BOOL hasReportNormalExposure;
@property (nonatomic) BOOL isPreviewMode;
@property (nonatomic) BOOL isAnimationMode;
@property (nonatomic) BOOL isPanBegin;
@property (retain, nonatomic) UIView *m_globalStoryTitleView;
@property (retain, nonatomic) UIImageView *globalStoryCoverView;
@property (retain, nonatomic) UIView *jumpInfoView;
@property (retain, nonatomic) UIView *m_globalSwipeUpView;
@property (retain, nonatomic) UIButton *m_showStoryBigBtn;
@property (nonatomic) BOOL hasReportSelfMadeRedPakcetEntry;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)init;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)a0;
- (BOOL)showSmallShareButton;
- (void)initNavigationBar;
- (void)onClickSplitRedSkinEntryBtn:(id)a0;
- (id)splitRedPakcetRightBarButtonCustomView;
- (void)onTouchCancelSplitRedSkinEntryBtn:(id)a0;
- (void)onTouchDownSplitRedSkinEntryBtn:(id)a0;
- (id)navigationBarBackgroundColor;
- (BOOL)shouldInteractivePop;
- (void)OnLeftBarButtonDone;
- (void)OnLeftBarButtonDoneLogic;
- (void)reportWhenDetailViewControllerBePop;
- (void)OnRealnameVerfitySuccess:(id)a0;
- (void)viewDidBePoped:(BOOL)a0;
- (void)loadMoreOrderList;
- (void)viewDidTransitionToNewSize;
- (void)viewDidLoad;
- (void)checkShowAtmospherePagView;
- (void)showNavigationBar;
- (void)autoPlayStoryIfNeed;
- (void)statExpourseOperation;
- (void)reportPersonalMakeRedPakcetEntry;
- (void)reportNormalExposure:(BOOL)a0;
- (id)getBottomView;
- (id)getNoMoreBottomView;
- (id)getTailButton;
- (id)getExposeButton;
- (BOOL)hasRedSkin;
- (BOOL)isPersonalMakeRedSkin;
- (BOOL)hasPersonalMakeRedSkinEntry;
- (BOOL)hasStoryInfo;
- (void)initTableView;
- (void)bfs:(id)a0;
- (id)createPlayerConfig;
- (BOOL)isCanShowBufferingView;
- (id)getSameCoverTailView;
- (id)getActionJumpView;
- (id)getAnimationView:(id)a0;
- (id)GetNavigationBarViewHeader:(id)a0;
- (id)getHeaderImageViewWithImgSize:(double)a0;
- (id)GetViewHeader:(id)a0;
- (id)cropImage:(id)a0 toRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (id)creatImageWithMaskImage:(id)a0 andBackimage:(id)a1;
- (id)generateMaskImage:(id)a0;
- (BOOL)isNotchScreen;
- (void)onClickDetailJumpInfoBtn:(id)a0;
- (id)GetHeaderView:(id)a0;
- (void)reportChangeLinkClick:(unsigned int)a0 Url:(id)a1;
- (void)onForeignAmountDescInfoBtnClick:(id)a0;
- (void)refreshViewWithData:(id)a0;
- (id)getTabview;
- (void)showStoryInfoGuideAnimation;
- (void)commentRedEnvelopes;
- (void)gotoBalanceDetail;
- (void)gotoUrl;
- (void)handleRedEnvelopesOperation:(id)a0;
- (void)handleTailOperation;
- (void)handleExposeBtnClick;
- (void)watchMyRedEnvelopesList;
- (void)setDelegate:(id)a0;
- (void)handleAmountInfoBtnClick;
- (id)tableView:(id)a0 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)a1;
- (long long)numberOfSectionsInTableView:(id)a0;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (void)makeCell:(id)a0 cell:(id)a1 row:(unsigned long long)a2;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (double)tableView:(id)a0 heightForRowAtIndexPath:(id)a1;
- (void)tableView:(id)a0 didSelectRowAtIndexPath:(id)a1;
- (long long)tableView:(id)a0 editingStyleForRowAtIndexPath:(id)a1;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)scrollViewDidScroll:(id)a0;
- (void)SendTextMessageToolView:(id)a0;
- (void)OnToolViewDissmiss;
- (void)startOpenAnimation;
- (void)animationForLabel;
- (void)setLeftCloseBarButton;
- (void)showLuckyAnimationWithLuckyData:(id)a0 needWhistle:(BOOL)a1 withWhistleData:(id)a2;
- (id)generateEmitterLayer:(BOOL)a0 withColors:(id)a1;
- (void)OnWebAddContact:(int)a0 Msg:(id)a1 CallBack:(id)a2;
- (void)OnWebAddContactReturn;
- (id)currentViewController;
- (id)addBorderViewBottomAtView:(id)a0;
- (BOOL)hasEmoticon;
- (id)lastThxEmoticonMd5;
- (unsigned int)lastThxEmoticonType;
- (id)lastThxEmoticonText;
- (void)saveSendThxEmoticonWrap;
- (void)sendThxEmoticonBtnClick;
- (void)showSharePreConfirmView;
- (void)OnSharePreConfirmSheetViewSend:(id)a0;
- (void)dismissDetailViewController;
- (void)OnSharePreConfirmSheetViewCancel:(id)a0;
- (BOOL)enableAnswerBySelfie;
- (void)selectThxEmoticonTopBtnClick;
- (void)selectThxEmoticonBtnClick;
- (void)actionSheet:(id)a0 clickedButtonAtIndex:(long long)a1;
- (void)handleThxEmoticonTap;
- (BOOL)isDetailFromMessageScene;
- (void)emotionViewClick;
- (void)emoticonViewLongPress:(id)a0;
- (void)saveEmoticon;
- (void)forwardEmoticon;
- (id)getLastSelectEmoticonPid;
- (void)saveLastSelectEmoticonPid:(id)a0;
- (void)handleEmoticonBoardViewMaskViewTap;
- (void)setEmoticonBoardHidden:(BOOL)a0;
- (void)makeSelfieEmoitcon;
- (void)handleGetEmoticonWrap;
- (void)deleteSelctedEmoticon;
- (id)tryGettingEmojiInfoByMd5:(id)a0 completionIfDownloaded:(id /* block */)a1;
- (void)onSendButtonClicked;
- (BOOL)handleAddCameraEmoji;
- (void)didSelectorSelfDefinedEmotcion:(id)a0;
- (void)didSelectorEmoticon:(id)a0;
- (id)GetCurrentViewController;
- (void)onEmoticonBoardHeightChanged;
- (void)onEmoticonSearchIconClicked;
- (void)onSearchEmoticonViewControllerSendEmoticon:(id)a0;
- (void)onTakePhotoCancelled;
- (void)onAddEmoticonFinishedWithWrap:(id)a0 isSucceeded:(BOOL)a1;
- (void)panFronViewGestureRecognize:(id)a0;
- (void)onWCRedEnvelopesStoryViewControllerClickCloseBtn;
- (void)onDragDownImageClick:(id)a0;
- (void)onDragDownImageSwipe:(id)a0;
- (void)reportMakeSameCoverBtnExpose;
- (void)onTableViewSwipeUp:(id)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)viewDidDisappear:(BOOL)a0;
- (void)resetAllStatus;
- (void)onWCRedEnvelopesStoryViewControlleClickWxAppInfo:(id)a0;
- (void)onWCRedEnvelopesStoryViewControlleClickJumpAction:(id)a0 sameReceiveLink:(id)a1;
- (void)panGestureRecognize:(id)a0;
- (void)onWCRedEnvelopesStoryViewControlleMaskViewDownloadOK;
- (void)onWCRedEnvelopesStoryViewControlleMaskViewDownloadFail;
- (BOOL)isNeedShowStoryGuideAnimation;
- (void)scrollViewWillEndDragging:(id)a0 withVelocity:(struct CGPoint { double x0; double x1; })a1 targetContentOffset:(inout struct CGPoint { double x0; double x1; } *)a2;
- (void)scrollViewDidEndScroll:(struct CGPoint { double x0; double x1; } *)a0;
- (id)getHeaderNickNameAttributedStringWithSuffix:(id)a0;
- (id)getRecordNickNameAttributedStringWithSuffix:(id)a0 suffix:(id)a1;
- (BOOL)isFinderDesignHB;
- (void)rightBarButtonPress;
- (void)onClickJumpInfo:(id)a0;
- (void)viewWillBePoped:(BOOL)a0;
- (void)userDidTakeScreenshot:(id)a0;
- (void).cxx_destruct;

@end
