@class NSString, WCTPPlayer, WCPlayerAudioEnhance, TPVideoFrameBuffer;

@interface WCThumbPlayer : WCCorePlayer <WCTPPlayerDelegate>

@property (retain, nonatomic) WCTPPlayer *player;
@property (nonatomic) unsigned long long seekStartTime;
@property (nonatomic) BOOL isNoCallbackSeek;
@property (retain, nonatomic) TPVideoFrameBuffer *currentVideoFrameBuffer;
@property (nonatomic) struct _opaque_pthread_rwlock_t { long long __sig; char __opaque[192]; } pixelBufferLock;
@property (nonatomic) BOOL isLocalServerReinit;
@property (nonatomic) BOOL isPauseBuffering;
@property (nonatomic) BOOL isOpenWaveAudioHAidProcess;
@property (retain, nonatomic) WCPlayerAudioEnhance *audioEnhance;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithPlayerArgs:(id)a0 playbackInfo:(id)a1 downloadArgsWrap:(id)a2 resourceloader:(id)a3;
- (double)currentTime;
- (double)playablePos;
- (double)duration;
- (float)playbackRate;
- (float)audioBitrate;
- (float)videoBitrate;
- (void)setVolume:(double)a0;
- (double)getVolume;
- (long long)videoDecodeFrmCnt;
- (long long)videoRenderFrmCnt;
- (long long)videoFrameRate;
- (struct CGSize { double x0; double x1; })presentationSize;
- (struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })preferredTransform;
- (void)setPlaybackRate:(float)a0;
- (void)setPlayerToMuted:(BOOL)a0;
- (BOOL)muted;
- (void)setPlayerLoop:(BOOL)a0;
- (void)setAllowsExternalPlayback:(BOOL)a0;
- (void)setCallbackVideoFrameEnable:(BOOL)a0;
- (BOOL)isEnableCallbackVideoFrame;
- (struct __CVBuffer { } *)getCurrentPixelBuffer;
- (id)getPlayerItemVideoOutput;
- (void)setVideoRenderInBackgroundEnable:(BOOL)a0;
- (void)prepareAsync;
- (void)start;
- (void)stop;
- (void)pause;
- (void)releasePlayer;
- (void)pauseBuffering;
- (void)resumeBuffering;
- (void)seekNoCallbackToTime:(double)a0;
- (void)seekToTime:(double)a0 isAccurate:(BOOL)a1;
- (void)seekToTime:(double)a0 isAccurate:(BOOL)a1 isNoCallbackSeek:(BOOL)a2;
- (id)syncCaptureVideo;
- (void)captureVideoWithFinishBlock:(id /* block */)a0;
- (void)switchResourceloaderDelegate:(id)a0 resourceUrl:(id)a1 resourceType:(long long)a2 swithMode:(long long)a3;
- (long long)getAudioSpeedProcessorType;
- (void)initPlayer;
- (id)getProxyAssetUrl:(long long)a0;
- (void)setPlayerContentMode:(long long)a0;
- (void)setPlayerStartPos:(float)a0;
- (void)addPeriodicTimeObserver;
- (void)removeTimeObserver;
- (void)onPlayerReinitWithReason:(long long)a0;
- (void)onPlayerFirstAudioDecoderStart;
- (void)onPlayerFirstVideoDecoderStart;
- (void)onPlayerGetVideoDecoderType:(long long)a0;
- (void)onPlayerGetAudioDecoderType:(long long)a0;
- (void)onFirstAudioFrameRendered;
- (void)onFirstVideoFrameRendered;
- (void)onFirstVideoPacketRead;
- (void)onPlayerStateReady;
- (void)onPlayerDidPlayToEndTime;
- (void)onPlayerBufferingStart;
- (void)onPlayerBufferingEnd;
- (void)onPlayerPauseContinueBufferingCompleted;
- (void)onPlayerCurrentLoopEnd;
- (void)onPlayerCurrentLoopStart;
- (void)onPlayerErrorWithType:(long long)a0 errorCode:(long long)a1;
- (unsigned long long)onPlayerErrorHappend:(long long)a0 errorCode:(long long)a1;
- (void)onPlayerVideoFrameOut:(id)a0;
- (void)onPlayerAudioFrameOut:(id)a0;
- (id)onPlayerAudioProcessFrameOut:(id)a0;
- (void)onSwitchDataSourceCompeleted;
- (void)onVideoSizeChange:(struct CGSize { double x0; double x1; })a0;
- (void)onPlayerGetSeiInfo:(id)a0;
- (void)onPlayerSeekComplete;
- (void)onVideoDecoderPacketNoReceiveFrameWithDesc:(id)a0;
- (void).cxx_destruct;

@end
