@class GameSkStoreController, NSString, EmoticonBoardView, NSMutableDictionary, UIControl, NSDictionary, GCSelfUnTouchableView, GCInputAtModel, GameChatRoomViewController, GCWebInputToolView;

@interface WebviewJSEventHandler_gameCenterFacade : WebviewJSEventHandlerBase <MMLiteAppShowStatusChangeExt, GameChatInputToolViewDelegate, IWebviewResourceManagerExt, WCActionSheetDelegate, GameNoticeHalfScreenViewDelegate>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSDictionary *inputToolConfigDict;
@property (retain, nonatomic) NSString *inputIdentifierName;
@property (retain, nonatomic) GCWebInputToolView *inputToolView;
@property (retain, nonatomic) UIControl *inputBgView;
@property (retain, nonatomic) GCSelfUnTouchableView *inputLayerView;
@property (retain, nonatomic) EmoticonBoardView *emoticonBoardView;
@property (retain, nonatomic) GCInputAtModel *inputAtModel;
@property (retain, nonatomic) GameSkStoreController *skStoreController;
@property (retain, nonatomic) NSMutableDictionary *webDurationReportDict;
@property (retain, nonatomic) NSString *converationUpdateEventName;
@property (nonatomic) double collapseChildHeight;
@property (nonatomic) double expandChildHeight;
@property (retain, nonatomic) GameChatRoomViewController *childChatRoomVC;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)onLiteAppShowStatusChange:(id)a0 page:(id)a1 appUuid:(unsigned long long)a2 pageId:(unsigned int)a3 show:(unsigned char)a4;
- (void)handleWebTransfer:(id)a0 gameJsEvent:(id)a1;
- (void)asymcCompleteWithMessage:(id)a0 success:(BOOL)a1 dict:(id)a2 eventInfo:(id)a3;
- (void)asyncCompleteWithEventInfo:(id)a0 result:(id)a1;
- (void)handleExtTransfer:(id)a0 gameJsEvent:(id)a1;
- (void)addSignInfoIfNeedWithRequestParams:(id)a0;
- (void)getLocalMiniGameVideo:(id)a0 params:(id)a1;
- (id)dictionaryForVideoLocalInfo:(id)a0;
- (void)delMiniGameVideo:(id)a0 params:(id)a1;
- (void)uploadMiniGameVideoToShare:(id)a0 params:(id)a1;
- (void)saveMiniGameVideoToAlbum:(id)a0 params:(id)a1;
- (void)showInputToolWithParamDict:(id)a0 identifierName:(id)a1;
- (void)handleAtPannel;
- (void)initInputToolViewIfNeed;
- (void)setEmoticonBoardViewTypeStr:(id)a0;
- (void)showInputBgView:(BOOL)a0;
- (void)onInputBgTouched;
- (void)hideInputView;
- (void)textDidChanged:(id)a0 selectedRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1;
- (void)didCommitText:(id)a0;
- (void)onInputViewFrameChange;
- (id)imgParamDictFromEmoticon:(id)a0 pickMmImage:(id)a1;
- (id)emojiInfoDictForEmojiWrap:(id)a0;
- (void)didSelectWithEmotcion:(id)a0;
- (double)getVisibleHeight;
- (void)notifyInputStateChange;
- (void)onInputViewShowChange:(BOOL)a0;
- (id)emojiInfoFromBase64Str:(id)a0;
- (id)browseEmoticonViewWithParams:(id)a0;
- (void)showGameShareWindow:(id)a0 params:(id)a1;
- (id)__arrCustomMenuItemsFromParams:(id)a0 forKey:(id)a1;
- (int)getShareType:(id)a0;
- (void)openGameLifeChatroom:(id)a0 params:(id)a1;
- (void)quitGameLifeChatroom:(id)a0 params:(id)a1;
- (void)preloadChildGameChatroom:(id)a0 params:(id)a1;
- (void)changeChildGameChatroomState:(id)a0 params:(id)a1;
- (void)destoryChildGameChatroom:(id)a0 params:(id)a1;
- (id)findChatRoomViewController;
- (void)searchChatRoomMemberByName:(id)a0 params:(id)a1;
- (void)deleteChatRoomMemberByUserName:(id)a0 params:(id)a1;
- (void)chatRoomAtMember:(id)a0;
- (id)customEventParamFromEventInfo:(id)a0;
- (void)dealloc;
- (void)handleJSEvent:(id)a0 HandlerFacade:(id)a1 ExtraData:(id)a2;
- (void)handleWithEventInfo:(id)a0;
- (void)fetchGameCenterEntranceInfo:(id)a0 params:(id)a1;
- (void)showToast:(id)a0 params:(id)a1;
- (id)getParentMMUIViewController;
- (void)showGameNoticeInfoView:(id)a0 params:(id)a1;
- (void)cancelPreloadVideo:(id)a0 params:(id)a1;
- (void)preloadVideoList:(id)a0 params:(id)a1;
- (void)downloadGameVideo:(id)a0;
- (void)showInputToolView:(id)a0;
- (void)browseEmoticonView:(id)a0;
- (void)gameExtTransfer:(id)a0;
- (void)gameWebTransfer:(id)a0;
- (void)notifyAccountState:(id)a0 params:(id)a1;
- (void)switchToGameTab:(id)a0 params:(id)a1;
- (void)updateGameBanner:(id)a0 params:(id)a1;
- (void)changeGameBannerState:(id)a0 params:(id)a1;
- (void)getGameBannerState:(id)a0 params:(id)a1;
- (void)saveBannerWebCache:(id)a0 params:(id)a1;
- (void)showActionSheet:(id)a0 params:(id)a1;
- (void)createInteractWebView:(id)a0 params:(id)a1;
- (void)postMessageToInteractWeb:(id)a0 params:(id)a1;
- (void)getGameWeakNetInfo:(id)a0 params:(id)a1;
- (void)setNavigationBarStatus:(id)a0;
- (BOOL)beChildOfViewController:(id)a0 parentViewController:(id)a1;
- (void)addWebViewReportExtInfo:(id)a0;
- (void)updateClientReport:(id)a0;
- (id)gameCenterPlugin;
- (void)preloadAppStoreVc:(id)a0;
- (void)showAppStoreVc:(id)a0;
- (void)openGameChatVc:(id)a0;
- (void)getGameChatRedInfo:(id)a0;
- (id)keyForCurrentLiteAppPageWithAppId:(id)a0 appUuid:(unsigned int)a1 pageId:(unsigned int)a2;
- (void)initGameLiteApp:(id)a0;
- (void)handleGameTabNavigationEvent:(id)a0;
- (void)getWebViewSnapShot:(id)a0;
- (void)saveImageToPhotosAlbum:(id)a0;
- (void)handleSaveImage:(id)a0 imageData:(id)a1 eventInfo:(id)a2;
- (void)reportLaunchAppStoreEvent:(id)a0;
- (void)actionSheet:(id)a0 clickedButtonAtIndex:(long long)a1;
- (void)gameNoticeViewDidConfirmWithCheck:(BOOL)a0;
- (void)gameNoticeViewDidClickAdditionBtn;
- (void)gameNoticeViewDidDismiss;
- (void)publishLiteAppOverlayEvent:(id)a0 show:(BOOL)a1;
- (void).cxx_destruct;

@end
