@class WNAttachmentBaseView, UIBarButtonItem, NSString, WNContentSearchBar, FavoritesItemDataField, WNRTEToolView, WeNoteDataController, UIImage, WNSelectionView, MMWebTransHelpButton, MiniRecTransitionController, UIButton, UIView, WNTableview, StreamVoiceInputViewController, RTEAttributeNode, CADisplayLink, WNSaveImageLogic, MMTimer, WNTranslateLogic, WNSearchLogic, MMScrollActionSheet, RTEAttachmentViewProvider, WNTranslateTopView;

@interface WeNoteViewController : MMUIViewController <WNRTEToolViewDelegate, WNTextViewOperationDelegate, WNContentSearchBarDelegate, WNSearchLogicDelegate, FavForwardLogicDelegate, MMScrollActionSheetDelegate, FavTagViewDelegate, WCActionSheetDelegate, RecentForwardScrollViewDelegate, MMTipsViewControllerDelegate, IVOIPUILogicMgrExt, RTEAttachmentViewProviderDelegate, WNAttachmentBaseViewDelegate, WNSelectionViewDelegate, MinimizationTransitionControllerDelegate, WNTranslateDelegate, WNTranslateTopViewDelegate, WebTransHelpButtonDelegate, WeNoteDataControllerDelegate, WNAlertViewHelperDelegate, StreamVoiceInputViewControllerDelegate, WeNoteAddFavListViewControllerDelegate> {
    WeNoteDataController *m_dataController;
    MMScrollActionSheet *m_scrollActionSheet;
    BOOL m_bDeletePopView;
    WNRTEToolView *m_toolView;
    WNTableview *m_tableView;
    UIView *m_headerView;
    UIView *m_footerView;
    UIView *m_topMaskView;
    double m_keyboardHeight;
    double m_keyboardAnimationTime;
    long long m_keyboardAnimationCurve;
    BOOL m_forbidUpdateToolView;
    BOOL m_holdOnAudio;
    BOOL m_forceLoadImage;
    unsigned int m_oriVersion;
    UIImage *m_snapshotImage;
    StreamVoiceInputViewController *m_voiceInputViewController;
    NSString *m_voiceStreamTitle;
    UIView *m_topBarView;
    BOOL m_isOnSearch;
    WNContentSearchBar *m_contentSearchBar;
    WNSearchLogic *m_searchLogic;
    BOOL m_enableOrderListMenu;
    RTEAttributeNode *m_hightliteOrderListNode;
    long long m_curOrientation;
    long long m_lastOrientation;
    unsigned long long m_curReadlocation;
    id /* block */ m_handlerAfterChangeOri;
    BOOL m_forcePortrait;
    WNTranslateLogic *m_translateLogic;
    long long m_canTranslateContent;
    MMTimer *m_saveTimer;
    BOOL m_forceHideTimeHeader;
    UIButton *m_exposeButton;
    UIBarButtonItem *m_moreBarItem;
    UIBarButtonItem *m_undoBarItem;
    UIBarButtonItem *m_redoBarItem;
    RTEAttachmentViewProvider *m_attachmentViewProvider;
    RTEAttachmentViewProvider *m_attachmentViewProviderForLongImageUtilForLightMode;
    RTEAttachmentViewProvider *m_attachmentViewProviderForLongImageUtilForDarkMode;
    RTEAttachmentViewProvider *m_attachmentViewProviderForLongImageUtilForTransparentMode;
    RTEAttachmentViewProvider *m_attachmentViewProviderForSquareImageUtilForLightMode;
    RTEAttachmentViewProvider *m_attachmentViewProviderForSquareImageUtilForDarkMode;
    RTEAttachmentViewProvider *m_attachmentViewProviderForSquareImageUtilForTransparentMode;
    WNSelectionView *m_selectionView;
    MiniRecTransitionController *m_minimizationTransitionController;
    UIView *m_movingAttachmentView;
    WNAttachmentBaseView *m_movingInnerView;
    WNAttachmentBaseView *m_sourceAttachmentView;
    struct _NSRange { unsigned long long location; unsigned long long length; } m_sourceAttachmentViewRange;
    struct CGPoint { double x; double y; } m_longPressStartPosition;
    CADisplayLink *m_scrollDisplayLink;
    unsigned long long m_scrollMode;
    BOOL m_onScrollingLongImage;
    BOOL m_canMovingAttachmentView;
    MMWebTransHelpButton *m_translateHelpBtn;
    WNTranslateTopView *m_translateTopView;
    UIView *m_oTitleView;
    BOOL m_hasErrorDataType;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) FavoritesItemDataField *scrollToData;
@property (retain, nonatomic) WNSaveImageLogic *saveImageLogic;
@property (nonatomic) BOOL bEditable;
@property (nonatomic) BOOL bShowMoreMenu;
@property (nonatomic) BOOL bPresentedByMiniTask;
@property (nonatomic) unsigned long long scene;
@property (retain, nonatomic) NSString *placeHolder;
@property (nonatomic) unsigned long long maxFileSize;
@property (nonatomic) unsigned int maxObjectCount;
@property (nonatomic) BOOL bShowLocateToMsg;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)initToolView;
- (void)keyboardDidShow:(id)a0;
- (void)keyboardDidHide:(id)a0;
- (void)keyboardWillShow:(id)a0;
- (void)keyboardWillHide:(id)a0;
- (void)hideKeyboard;
- (void)onTopBarFrameChanged;
- (void)forceHideToolView;
- (void)updateToolBarHeight;
- (void)onBecomeFirstResponder:(id)a0;
- (void)onResignFirstResponder:(id)a0;
- (void)hideToolView;
- (void)onTapWeAppMPShortLink:(id)a0;
- (BOOL)isOnContentSearching;
- (BOOL)enableOrderListMenu;
- (void)onEditOrderList;
- (unsigned int)objectCount;
- (unsigned long long)getMaxFileSize;
- (void)holdOnAudio;
- (BOOL)ifNonTextParaInfoNumExceedLimit:(long long)a0;
- (void)insertAttributes:(id)a0;
- (BOOL)canBold;
- (BOOL)canHighlight;
- (BOOL)isOlLiParagraph;
- (BOOL)isTodoParagraph;
- (BOOL)isUlLiParagraph;
- (BOOL)checkListContent:(unsigned long long)a0;
- (void)onParagraphSetOl;
- (void)onParagraphSetTodo;
- (void)onAddCurrentTime;
- (void)onParagraphSetUl;
- (void)onBold;
- (void)onHighlight;
- (void)onShowBasicToolView;
- (void)onShowFullToolView;
- (id)getCurrentNoteItem;
- (BOOL)isUsingVoiceInput;
- (void)onShowVoiceInputView;
- (double)getInputToolViewHeight;
- (void)onSendTextMsg:(id)a0;
- (void)streamVoiceInputBoardDidHide;
- (void)showStreamVoiceInputMaskView:(BOOL)a0;
- (void)streamVoiceInputFullScreenEnter;
- (void)streamVoiceInputFullScreenExit;
- (void)editStreamVoiceTxtReturn;
- (void)initContentSearchBarView;
- (void)beginSearchContent;
- (void)checkContentSearchBarWidth;
- (void)updateSearchViewHeight;
- (void)onCancelSearch;
- (void)cancelContentSearch;
- (void)onSearchContentWith:(id)a0;
- (void)willVisibleTextViewAt:(id)a0;
- (void)scrollSelectedLocationVisible;
- (void)attachmentDidAddToSuperview:(id)a0;
- (void)forwardNote;
- (void)forwardNoteToUser:(id)a0;
- (void)realForwardNoteToUser:(id)a0;
- (id)tryRemoveChatVoiceBeforeForward:(id)a0;
- (void)forwardNote2WC;
- (void)realForwardNote2WC;
- (id)AddNewActionSheetCell2Array:(id)a0 WithText:(id)a1 WithImage:(id)a2;
- (id)AddNewActionSheetCell2Array:(id)a0 WithText:(id)a1 WithImage:(id)a2 WithAccessibilityLabel:(id)a3;
- (void)onMenuAction:(id)a0;
- (void)onSwitchScene:(id)a0;
- (void)clickRFItemCallBack:(id)a0;
- (void)relayoutScrollSheet;
- (void)scrollActionSheet:(id)a0 didSelecteItem:(id)a1;
- (void)reportSetOnTop:(BOOL)a0;
- (void)saveNoteAsImage;
- (void)realSaveNoteAsImage;
- (void)getNoteImage:(id /* block */)a0;
- (void)getTableViewimage:(id /* block */)a0;
- (id)getFooterViewImage;
- (void)actionSheet:(id)a0 clickedButtonAtIndex:(long long)a1;
- (id)getFavForawrdViewController;
- (void)onFavTagEditBegin:(int)a0;
- (void)onNoteSecurityCheckOK;
- (void)onNoteSecurityCheckFail;
- (void)onNoteDownloadResourceSuccess;
- (void)onNoteDownloadResourceFail;
- (void)onNoteDownloadResourceNone;
- (void)handleSuccessState;
- (void)handleFailState;
- (void)continueSaveNoteAsImage;
- (void)refuseSaveNoteAsImage;
- (id)init;
- (void)applicationWillResignActive;
- (void)applicationWillBecomeActive;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })a0 withTransitionCoordinator:(id)a1;
- (void)dealloc;
- (void)viewDidBePoped:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)a0;
- (void)fixOrientation;
- (void)viewDidAppear:(BOOL)a0;
- (void)viewDidBePushed:(BOOL)a0;
- (void)viewDidBePushOrPresent:(BOOL)a0;
- (void)viewDidBePopedOrDismissed:(BOOL)a0;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(BOOL)a0;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewDidBeDismissed:(BOOL)a0;
- (void)didMoveToNewScene:(id)a0;
- (unsigned long long)supportedInterfaceOrientations;
- (void)initUI;
- (void)initContent;
- (void)initHeaderAndFooterView;
- (void)onExpose;
- (void)initTableView;
- (void)initSelectView;
- (BOOL)disMissSelf;
- (BOOL)useBlackStatusbar;
- (BOOL)useTransparentNavibar;
- (BOOL)shouldInteractivePop;
- (void)viewDidTransitionToNewSize;
- (long long)getCurrentOrientation;
- (void)didChangeOrientation;
- (void)recoverReadingLocation;
- (void)recordReadingLocation;
- (void)setM_uiVcType:(unsigned int)a0;
- (void)configWithMsg:(id)a0;
- (void)configWithFavItem:(id)a0;
- (void)configWithWCDataItem:(id)a0;
- (void)configWithMsg:(id)a0 andData:(id)a1;
- (void)configWithDataWrap:(id)a0;
- (void)configWithGroupNoticeItem:(id)a0;
- (BOOL)isEmpty;
- (void)setDataEdited:(BOOL)a0;
- (void)saveNote;
- (void)setConversionOntop:(BOOL)a0;
- (void)menuWillHide;
- (void)reportLandscape;
- (void)configNavbar;
- (id)redoBarItem;
- (id)undoBarItem;
- (void)setForbidUpdateToolViewEnable:(BOOL)a0;
- (void)updateRightBarBtnStatus;
- (void)didGenerationFinished;
- (void)showLoading;
- (void)stopLoading;
- (void)showKeyboard;
- (void)reloadAll;
- (void)reloadSectionAtIndex:(unsigned long long)a0;
- (void)updateSelection;
- (void)updateToolViewStatus;
- (void)resetToolViewType;
- (void)scrollSelectionToVisible;
- (void)scrollElementToVisible:(id)a0;
- (void)realScrollSelectionToVisible;
- (void)scrollRectToVisible:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 fromView:(id)a1;
- (void)scrollRectToVisible:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 fromView:(id)a1 isFast:(BOOL)a2;
- (void)chectNeedFlashData;
- (void)updateAllOrderedListView;
- (BOOL)isSelectionViewShowing;
- (void)tryShowSelectionViewWithMenue:(BOOL)a0;
- (void)hideMenu;
- (void)tryUpdateSelectionViewOnScroll;
- (void)cancelSelect;
- (id)getAttachmentViewProvider;
- (id)getAttachmentViewProviderForLongImageUtilWithLightMode;
- (id)getAttachmentViewProviderForLongImageUtilWithDarkMode;
- (id)getAttachmentViewProviderForLongImageUtilWithTransparentMode;
- (id)getAttachmentViewProviderForSquareImageUtilWithLightMode;
- (id)getAttachmentViewProviderForSquareImageUtilWithDarkMode;
- (id)getAttachmentViewProviderForSquareImageUtilWithTransparentMode;
- (id)realGetAttachmentViewProviderWithColorType:(unsigned long long)a0;
- (struct CGSize { double x0; double x1; })getViewSize;
- (void)onCellHeightChange;
- (void)onTableSectionChange:(id)a0;
- (void)checkFooterView;
- (void)noteScrollViewDidScroll:(id)a0 extendHeight:(double)a1;
- (void)showToastOnToolView:(id)a0;
- (void)didContentViewScrollEnd;
- (void)onOpenTopicWithUrl:(id)a0;
- (void)contentViewWillBeginDragging;
- (long long)currentOrientation;
- (void)reloadTableView;
- (id)getCurrentViewController;
- (id)getScollToData;
- (id)getPlaceHolder;
- (id)favItem;
- (id)messageWrap;
- (id)getAllAttachmentImgInfo;
- (id)getOriginAttachmentViewWith:(id)a0;
- (BOOL)canEditNote;
- (BOOL)isForceLoadImage;
- (void)onAttachmentAttributeStartEdit:(id)a0;
- (void)onAttachmentAttributeEndEdit:(id)a0;
- (void)onAttachmentAttributeNeedReload:(id)a0;
- (BOOL)canOpenAttachmentAttribute:(id)a0;
- (void)tryToDownloadLargeFileWith:(id)a0;
- (BOOL)isVideoNeedLazyDownload:(id)a0;
- (void)onOpenAttachmentWith:(id)a0;
- (void)onUnknownAttachmentViewAppearWith:(id)a0;
- (unsigned int)enterNoteScene;
- (void)showMenuOnOrderListAttachmentView:(id)a0;
- (void)showMenuForOrderListAttributeNode:(id)a0;
- (id)getHighliteOrderListNode;
- (id)getTranslatedAttachmentInfoWith:(id)a0;
- (BOOL)hasRotated;
- (void)onCreatAttachmentView:(id)a0;
- (void)startAutoSaveTimer;
- (void)stopAutoSaveTimer;
- (void)onTimeSave;
- (void)onClickTipsBtn:(id)a0 Index:(long long)a1 tipTag:(long long)a2;
- (void)onVideoVoipViewDidAppear:(id)a0;
- (void)onVideoVoipViewDisappear;
- (void)onVoipMinimized;
- (void)onVoipMaximized;
- (id)getAlertTitleForType:(unsigned long long)a0;
- (BOOL)needHideKeyboardToShowAlert;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getSelectionMenuTargetRectOnFirstResponder;
- (void)setPopGestureEnable:(BOOL)a0;
- (double)getToolBarY;
- (void)tryUpdateToMinimize;
- (BOOL)tryAddToMinimize:(id)a0;
- (void)addToMinimizeWithGenerateType:(unsigned long long)a0;
- (void)updateToMinimize;
- (BOOL)tryAddToMultiContent;
- (void)installMinimizationTransitionController;
- (id)minimizationTransitionController;
- (id)mmNavigationController:(id)a0 animationControllerForOperation:(long long)a1 fromViewController:(id)a2 toViewController:(id)a3;
- (id)mmNavigationController:(id)a0 interactionControllerForAnimationController:(id)a1;
- (void)addToTaskHistory;
- (void)removeTaskHistory;
- (BOOL)checkNeedReloadData:(unsigned int)a0;
- (void)minimizationInteractivePopGestureRecognizerDidBegin;
- (void)minimizationInteractivePopToMinimizeTask:(BOOL)a0;
- (id)minimizationTaskData;
- (id)multiContentTaskData;
- (BOOL)minimizationInteractivePopGestureRecognizerShouldBegin;
- (id)minimizationInteractivePopGetPendingTaskContextWithGenerateType:(unsigned long long)a0;
- (id)currentMinimizationTaskBizKey;
- (id)currentMinimizationTaskBizName;
- (id)currentMultiContentTaskBizName;
- (id)currentMultiContentTaskBizKey;
- (BOOL)isStarMinimizePage;
- (BOOL)isMultiContentPage;
- (void)fixMinimizationIssueWhenPopedOrDismiss;
- (void)onLongPress:(id)a0;
- (unsigned long long)getLongPressMediaType;
- (id)getPressingAttachmentViewFor:(id)a0;
- (id)getTextViewFor:(id)a0;
- (void)addShadowToView:(id)a0;
- (void)removeShadowToView:(id)a0;
- (void)onStartLongPress:(id)a0 fromGesture:(id)a1;
- (void)forceToHideKeyBoard;
- (void)scaleMovingViewWith:(id)a0;
- (void)onStartMoveAttachmentFromGesture:(id)a0;
- (void)startScroll;
- (void)stopScroll;
- (void)scrollForConstantSpeed;
- (void)onMoveAttachmentFromGesture:(id)a0;
- (void)tryToScrollViewWith:(struct CGPoint { double x0; double x1; })a0;
- (void)onMoveAttachmentCancel;
- (void)onMoveAttachmentEnd;
- (void)tryToShowMenuWithoutSelectionView;
- (void)clearMoveStatus;
- (BOOL)isMovingAttachment;
- (BOOL)isOnLongPress;
- (BOOL)gestureRecognizer:(id)a0 shouldReceiveTouch:(id)a1;
- (void)checkCanTranslateContent;
- (void)initTranslateTitleBtn;
- (BOOL)isInTranslation;
- (void)translateContent:(id)a0;
- (void)cancelTranslate;
- (void)onTranslateFinishWith:(BOOL)a0 errMsg:(id)a1;
- (void)insertContentStroage:(id)a0;
- (id)generateContentStorageWithAttributes:(id)a0;
- (id)getMenuItemsWithResponder:(id)a0;
- (void)onCloseTranslateTopView;
- (void)onChangeTranslateLanguage;
- (void)clickHelperTransButton;
- (void)clickHelperRevertButton;
- (BOOL)canShowLocateToMsg;
- (void)locateToMsg;
- (void).cxx_destruct;

@end
