@class WSTabInfoList, NSMutableDictionary, WSRecommendSetting, NSDictionary, _TtC6WeChat26WeSeePageRecoverController, WSRecommendColikeStorage, WSTabRedDotInfoCollector, NSMutableArray, NSString, WSRecommendColikeTempModel, NSRecursiveLock, NSArray, UIImage;

@interface WSRecommendMgr : WSTemplateBaseMgr <IFunctionMsgExt, PBMessageObserverDelegate, NewLifeManagerExt, IMMLanguageMgrExt, IMinimizeTaskDelegateInterface>

@property (retain, nonatomic) NSMutableDictionary *dicWrdCache;
@property (nonatomic) BOOL isAuthOK;
@property (nonatomic) BOOL isRequestingOpenIdForOpenProfile;
@property (retain, nonatomic) NSMutableArray *colikeHideList;
@property (retain, nonatomic) NSMutableArray *colikeBlockList;
@property (retain, nonatomic) NSMutableArray *colikeRequestList;
@property (retain, nonatomic) NSMutableArray *colikeSucList;
@property (retain, nonatomic) NSMutableArray *colikeFailList;
@property (retain, nonatomic) NSMutableDictionary *tempSaveDic;
@property (retain, nonatomic) NSMutableDictionary *tempVideoCacheTimeDic;
@property (retain, nonatomic) WSRecommendColikeStorage *colikeLocalStorage;
@property (retain, nonatomic) WSRecommendColikeTempModel *colikeHideTempModel;
@property (retain, nonatomic) WSRecommendColikeTempModel *colikeBlockTempModel;
@property (nonatomic) BOOL hasRetryGetColikeBlockList;
@property (nonatomic) BOOL hasRetryGetColikeHideList;
@property (nonatomic) BOOL isRequestingGetColikeBlockList;
@property (nonatomic) BOOL isRequestingGetColikeHideList;
@property (retain, nonatomic) NSRecursiveLock *lock;
@property (retain, nonatomic) UIImage *mVideoFlowIcon;
@property (retain, nonatomic) NSDictionary *from3rdAppShareParams;
@property (retain, nonatomic) NSDictionary *tabsInfo;
@property (retain, nonatomic) WSTabInfoList *tabsInfoModel;
@property (retain, nonatomic) WSTabRedDotInfoCollector *tabRedDotInfoCollector;
@property (readonly, nonatomic) WSRecommendSetting *setting;
@property (readonly, nonatomic) NSString *tabParamsText;
@property (readonly, nonatomic) NSArray *tabListInfo;
@property (retain, nonatomic) _TtC6WeChat26WeSeePageRecoverController *pageRecoverController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)IsSupportTopStoryPlugin;

- (void)onServiceInit;
- (void)onServiceMemoryWarning;
- (id)defaultTemplateZipPath;
- (unsigned int)defaultTemplateZipVersion;
- (id)templateResouceRootPath;
- (unsigned int)packageResouceType;
- (unsigned long long)localJSBizType;
- (void)reloadPackageConfig:(unsigned long long)a0;
- (id)fileDir;
- (id)settingPath;
- (id)filePath;
- (void)loadCache;
- (BOOL)saveCache;
- (void)loadColikeCache;
- (BOOL)saveSetting;
- (void)outsideSetString:(id)a0 forKey:(id)a1;
- (id)outsideGetStringforKey:(id)a0;
- (void)outsideSetVideoCacheTime:(unsigned int)a0 forKey:(id)a1;
- (unsigned int)outsideGetVideoCacheTimeFor:(id)a0;
- (void)outsideSetFrom3rdAppShareParams:(id)a0;
- (id)outsideGetFrom3rdAppShareParams;
- (void)updateTabsInfo;
- (id)generateBaseSharedPage:(unsigned long long)a0;
- (id)generatePushingSharedPage:(unsigned long long)a0 reddotId:(id)a1 useLocalCache:(BOOL *)a2 useParallel:(BOOL *)a3;
- (void)preloadSharedPageWebViewIfNeeded:(id)a0;
- (id)generatePluginMsgRequestBuffer:(id)a0;
- (void)onFunctionMsgRequest:(id)a0 bussinessId:(unsigned long long)a1 functionMsgId:(id)a2;
- (void)logCacheInfo;
- (BOOL)isFFWebRecommendOpen;
- (BOOL)isFFWebRecommendOpenForGlobalSearch;
- (BOOL)confirmFullDragTips;
- (BOOL)confirmVideoGoodLookEducateAlertFlag;
- (BOOL)resetVideoGoodLookEducateAlertFlag;
- (BOOL)confirmVideoGoodLookTipEducateToastFlag;
- (BOOL)resetVideoGoodLookTipEducateToastFlag;
- (BOOL)updateContainWowContent:(BOOL)a0 timestamp:(unsigned int)a1;
- (void)asyncPostCommentWithContent:(id)a0 toDoc:(id)a1 withReplyId:(id)a2 subReplyId:(id)a3 docUrl:(id)a4 requestId:(id)a5 title:(id)a6 searchId:(id)a7 scene:(unsigned int)a8 subScene:(unsigned int)a9 byPass:(id)a10 source:(unsigned int)a11;
- (void)asyncSetCommentWithDocId:(id)a0 commentId:(id)a1 opType:(unsigned int)a2 requestId:(id)a3 content:(id)a4 scene:(unsigned int)a5 subScene:(unsigned int)a6 searchId:(id)a7 vid:(id)a8 byPass:(id)a9 source:(unsigned int)a10;
- (void)asyncGetWowHideList;
- (void)asyncGetWowBlockList;
- (void)asyncGetWowBlackFriendListWith:(int)a0;
- (void)onGetColikeListDataReturn:(BOOL)a0 type:(unsigned int)a1 list:(id)a2;
- (void)asyncStepGetWowBlackFriendListWith:(int)a0 offset:(unsigned int)a1 version:(unsigned long long)a2;
- (void)asyncColikeWithActionItems:(id)a0;
- (id)devideAsyncColikeWithActionItems:(id)a0;
- (void)asyncRequestPostColikeToWow:(id)a0 objectBuffer:(id)a1 appInfo:(id)a2;
- (void)MessageReturn:(id)a0 Event:(unsigned int)a1;
- (void)handleGetColikeListCGI:(id)a0;
- (void)handleGetColikeBlockListResp:(id)a0 oriRequest:(id)a1;
- (void)handleGetColikeHideListResp:(id)a0 oriRequest:(id)a1;
- (void)mergeBlockList;
- (void)mergeHideList;
- (void)handleColikeBlockCGI:(id)a0;
- (id)outsideGetWowHideList;
- (id)outsideGetWowBlockList;
- (BOOL)isFirstTimeGetColikeListWithType:(unsigned int)a0;
- (BOOL)isInK1kFlow;
- (void)preloadContactAuthorityData;
- (void)outsideModLocalColikeDataWithType:(unsigned int)a0 list:(id)a1;
- (void)handlePostCommentCGI:(id)a0;
- (void)handleSetCommentCGI:(id)a0;
- (void)handleColikePostCGI:(id)a0;
- (void)onNewLifeMainSwtichValueChanged;
- (void)onSearchConfigDataUpdated;
- (long long)categoryIdForTab:(unsigned long long)a0;
- (long long)topStoriesCategoryIdForTab:(unsigned long long)a0;
- (BOOL)hasTwoRecommendTab;
- (BOOL)hasThreeRecommendTab;
- (void).cxx_destruct;

@end
