@class NSURL, MMWebViewUniversalLinkMinitorLogic, NSMutableDictionary, MMURLHandler, WCDeepLinkHandler, UIButton, WebViewA8KeyLogicImpl, NSString, NSURLRequest, WebViewJSLogicImpl, MMJSApiVerifyMgr, UILongPressGestureRecognizer, WKWebView;
@protocol WXCustomWebViewControllerDelegate, YYWebViewInterface;

@interface WXBaseWebViewController : MMUIViewController <UIGestureRecognizerDelegate, WebViewA8KeyLogicDelegate, WebViewJSLogicDelegate, UIScrollViewDelegate, MMJSApiVerifyMgrDelegate, YYWebViewDelegate, WXCustomWebViewControllerProtocol> {
    MMURLHandler *m_urlHandler;
    UIButton *m_loadFailView;
    NSMutableDictionary *m_jsInitInfo;
    WCDeepLinkHandler *m_deepLinkHandler;
    MMJSApiVerifyMgr *m_apiVerifyMgr;
    id /* block */ _OnInitReadyNotifyBlock;
    BOOL m_bShowOnNewMainFrameBanner;
    NSMutableDictionary *_dicJsapiGetA8keyHadnleBlocks;
    long long m_loadingCount;
    UILongPressGestureRecognizer *m_longPressGestureRecognizer;
    BOOL _bLongPressingWebContentImage;
    unsigned long long _longPressingWebContentImageEndTimeStamp;
    NSString *m_jump;
    BOOL m_viewDidAppear;
    BOOL m_isPageLoadFail;
    BOOL m_bIFrame;
    BOOL _bIsDraggingScroll;
    BOOL _bIsBackForwardNavigationType;
    NSString *_lastURL;
    BOOL m_isFinishLoaded;
    BOOL m_enableAutoPlay;
}

@property (retain, nonatomic) NSString *m_lastCheckCpKey;
@property (retain, nonatomic) NSURL *wkLastCommitingNavigationUrl;
@property (retain, nonatomic) NSURL *onceRewindNavigationUrl;
@property (retain, nonatomic) MMWebViewUniversalLinkMinitorLogic *ulMonitorLogic;
@property (nonatomic) BOOL enableCommitCurrentUrl;
@property (readonly, nonatomic) WebViewJSLogicImpl *m_jsLogicImpl;
@property (readonly, nonatomic) NSString *m_initUrl;
@property (retain, nonatomic) NSMutableDictionary *m_extraInfo;
@property (readonly, nonatomic) WebViewA8KeyLogicImpl *m_a8KeyLogicImpl;
@property (readonly, nonatomic) BOOL m_bOfflinePage;
@property (retain, nonatomic) WKWebView<YYWebViewInterface> *webView;
@property (copy, nonatomic) id /* block */ m_blockOnWebViewDidTerminate;
@property (nonatomic) BOOL m_bIsJsapiUploadVideoUploading;
@property (weak, nonatomic) id<WXCustomWebViewControllerDelegate> m_delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSURLRequest *request;

- (id)initWithURL:(id)a0 extraInfo:(id)a1;
- (void)setEnableAutoPlay:(BOOL)a0;
- (id)webviewForInitialization;
- (void)internalInitWithUrl:(id)a0 extraInfo:(id)a1;
- (BOOL)IsBitsetSet:(unsigned int)a0 forUrl:(id)a1;
- (unsigned int)GetGeneralBitSetForUrl:(id)a0;
- (BOOL)hasUrlPermission:(id)a0;
- (id)getUrlPermission:(id)a0;
- (void)sendGetA8KeyEvent;
- (unsigned char)getPermissionWithName:(id)a0;
- (id)getShareUrl;
- (void)tryStartOutlinkDetect;
- (void)startLoadWeb;
- (void)notifyToJSBridgeVisibilityChanged:(BOOL)a0;
- (void)markNeedCheckUrlAndRemoveLastCheckedUrl:(id)a0;
- (void)setCurrentUrl:(id)a0;
- (id)getRequestingOrCurrentUrl;
- (void)clearScrollBackgroundColor;
- (void)goToURL:(id)a0;
- (id)getCurrentUrl;
- (id)getCurrentAppId;
- (id)getInitUrl;
- (id)extraInfo;
- (unsigned int)getCurrentScene;
- (BOOL)allowScanQRCodeByImage;
- (BOOL)allowShareByImage;
- (BOOL)allowFayByImage;
- (void)setDisableWebAlertView:(BOOL)a0;
- (void)doJsApiInitEvent;
- (void)forceShowCloseButton;
- (void)sendEventToJSBridge:(id)a0 Param:(id)a1;
- (void)startupPreVerifyJSAPI:(id)a0 failHandleBlock:(id /* block */)a1;
- (void)logUseWebviewSchemeToJumpWithUrl:(id)a0;
- (BOOL)isBackForwardNavigationType;
- (BOOL)webView:(id)a0 shouldStartLoadWithRequest:(id)a1 navigationType:(long long)a2 isMainFrame:(BOOL)a3 navigationAction:(id)a4;
- (BOOL)allowsAutoMediaPlay;
- (id)getWXHookScriptStr;
- (void)webViewDidCommitLoad:(id)a0 navigation:(id)a1;
- (void)webViewDidStartLoad:(id)a0 navigation:(id)a1;
- (void)webViewDidReceiveServerRedirect:(id)a0 navigation:(id)a1;
- (void)webViewDidFinishLoad:(id)a0 navigation:(id)a1;
- (void)webviewDidReceiveScriptMessage:(id)a0 handler:(id)a1 rawMessage:(id)a2;
- (void)webViewDidReceiveNavigationResponse:(id)a0 andGetIsCancelNavigation:(BOOL *)a1;
- (void)webView:(id)a0 didFailLoadWithError:(id)a1 navigation:(id)a2;
- (void)webViewContentProcessDidTerminate:(id)a0;
- (BOOL)webViewController:(id)a0 shouldStartLoadWithRequest:(id)a1 navigationType:(long long)a2 isMainFrame:(BOOL)a3 navigationAction:(id)a4;
- (void)webViewControllerDidStartLoad:(id)a0;
- (void)webViewControllerDidRecieveSvrRedirect:(id)a0;
- (void)webViewControllerDidReceiveResponse:(id)a0 isMainFrame:(BOOL)a1 andGetIsCancelNavigation:(BOOL *)a2;
- (void)webViewControllerDidCommitLoad:(id)a0;
- (void)webViewControllerDidFinishLoad:(id)a0;
- (void)webviewControllerDidReceiveScriptMessage:(id)a0 handler:(id)a1;
- (void)webViewController:(id)a0 didFailLoadWithError:(id)a1;
- (void)webViewControllerContentProcessDidTerminate:(id)a0;
- (void)webViewControllerTitleDidChange:(id)a0;
- (id)webViewControllerPreInjectScriptStr;
- (void)webViewControllerDidStartSyncA8Key:(id)a0;
- (void)webViewControllerForceSyncA8KeyError;
- (id)webViewControllerBackgroundColor;
- (void)webViewControllerJSApiRespForEvent:(id)a0 result:(id)a1;
- (void)webViewControllerCanGoBackChanged:(BOOL)a0;
- (void)cleanJSAPIDelegate;
- (void)handleWebViewVCDismiss;
- (id)getPreInjectScriptStr;
- (void)delayHandleUrl:(id)a0;
- (void)handleJumpProfileUrl:(id)a0 profileRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1;
- (BOOL)shouldRewindWebNavigation:(id)a0;
- (void)onGetA8Key:(BOOL)a0 ReqUrl:(id)a1 Reason:(int)a2;
- (void)onUpdatedPermisson;
- (void)onJumpToSafariWithUrl:(id)a0;
- (void)onJumpToViewController:(id)a0;
- (void)onJumpToEmoticonDetailViewController:(id)a0;
- (void)saveJSAPIAuthInfo:(id)a0;
- (void)saveJSAPIPermissions:(id)a0 url:(id)a1;
- (void)saveJSAPIPermissionsInOfflineCache:(id)a0 url:(id)a1;
- (void)onStartGetA8Key:(id)a0;
- (id)getCurrentWebviewViewController;
- (void)onFinishedHandleJSApi:(id)a0 result:(id)a1;
- (BOOL)isBridgedInNewMode;
- (BOOL)isUseAllOneWXJS;
- (BOOL)isGetingA8Key;
- (unsigned char)getJSApiPermission:(id)a0;
- (void)processJSAPICall:(id)a0 funcDef:(id)a1 funcBlock:(id /* block */)a2 failHandleBlock:(id /* block */)a3 apiPermission:(unsigned char)a4;
- (id)getAuthorizedMonitorEvents:(id)a0;
- (BOOL)isDisableRecordHistory;
- (void)onDomReady;
- (void)onPageStateChange:(id)a0;
- (id)currentPermissionKeyUrlString;
- (id)currentWebviewEnvInfo;
- (id)getJSFunctionDef:(id)a0;
- (unsigned int)getA8KeyRequestId;
- (void)kvReportJSCall:(id)a0 withParam:(id)a1;
- (BOOL)getJSApiFrequncyCheckResult:(id)a0;
- (BOOL)getJSApiEnvCompatibility:(id)a0;
- (void)onCopy:(id)a0;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)a0;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)a0 ofObject:(id)a1 change:(id)a2 context:(void *)a3;
- (void)initWebViewObservers;
- (void)removeWebViewObservers;
- (void)initNotificationObservers;
- (void)removeNotificationObservers;
- (void)keyboardDidShow:(id)a0;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)scrollViewDidScroll:(id)a0;
- (void)enableLongPressDetect;
- (void)enableWebContentImageLongPressingTag;
- (BOOL)allowImagePreview;
- (void)onLongPressOnWebview:(id)a0;
- (BOOL)gestureRecognizer:(id)a0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)a1;
- (BOOL)gestureRecognizer:(id)a0 shouldBeRequiredToFailByGestureRecognizer:(id)a1;
- (BOOL)gestureRecognizer:(id)a0 shouldRequireFailureOfGestureRecognizer:(id)a1;
- (void)delaySetFontsWithSize:(id)a0;
- (unsigned int)webviewCurrentFontLevel;
- (unsigned int)webviewCurrentFontScale;
- (BOOL)checkURLInDomainList:(id)a0;
- (void).cxx_destruct;

@end
