@class ACCAETextStickerViewEditorImpl, ACCTextStickerViewModel, ACCStickerGeometryModel, NSValue, AWEStoryTextImageModel, ACCAETextStickerInputView, ACCAETextStickerTrackerImpl, ACCTemplateTextStickerView, UIView, ACCSocialStickerEditToolbar, NSString, ACCTextStickerInputController, ACCTextStickerEditorSlider, NSNumber, ACCAETextStickerServiceImpl, ACCTextStickerTTSViewModel;
@protocol ACCAdvanceEditStickerServiceProtocol, AEKNewTextStickerEditor, AEKTextStickerEditor, AEKPreviewEditor, AEKAudioStashes, ACCStudioPerfUtilServiceProtocol, DVETimelineViewServiceProtocol, ACCAEViewContainerProtocol, ACCAEMenuRouteProtocol, ACCTextLoadingViewProtcol, ACCAEDraftService, AEKRuntimeStickerEditor, DVEComponentViewManagerProtocol, DVEEditingRuntimeProtocol;

@interface ACCAETextStickerComponent : ACCAdvanceEditComponent <ACCAETextStickerInputViewDelegate, AEKDiffChangeSubscriber, AEKMegaEditorRenderHandler, ACCAdvanceEditDataRepositorySubscriber, ACCAETextStickerActionService, ACCTextStickerInputControllerDelegate, ACCTextStickerConfigProvider, ACCTextStickerTTSViewModelDelegate>

@property (weak, nonatomic) id<ACCAdvanceEditStickerServiceProtocol> stickerService;
@property (weak, nonatomic) id<ACCAEViewContainerProtocol> viewControllerService;
@property (weak, nonatomic) id<DVEComponentViewManagerProtocol> bottomBarManager;
@property (weak, nonatomic) id<DVEEditingRuntimeProtocol> editingContext;
@property (weak, nonatomic) id<DVETimelineViewServiceProtocol> timelineViewService;
@property (weak, nonatomic) id<ACCAEMenuRouteProtocol> menuRouteService;
@property (weak, nonatomic) id<ACCAEDraftService> draftService;
@property (weak, nonatomic) id<ACCStudioPerfUtilServiceProtocol> perfService;
@property (retain, nonatomic) ACCAETextStickerServiceImpl *textStickerService;
@property (retain, nonatomic) ACCAETextStickerTrackerImpl *tracker;
@property (retain, nonatomic) ACCAETextStickerInputView *inputView;
@property (retain, nonatomic) ACCAETextStickerViewEditorImpl *stickerViewEditor;
@property (retain, nonatomic) ACCTextStickerViewModel *viewModel;
@property (retain, nonatomic) ACCTextStickerTTSViewModel *ttsViewModel;
@property (retain, nonatomic) NSNumber *pinchValue;
@property (retain, nonatomic) NSNumber *hasRotateValue;
@property (retain, nonatomic) ACCSocialStickerEditToolbar *socialToolbar;
@property (retain, nonatomic) ACCTextStickerInputController *stickerInputController;
@property (copy, nonatomic) NSString *placeholderStickerId;
@property (copy, nonatomic) NSString *stickerIdForSelect;
@property (weak, nonatomic) ACCTemplateTextStickerView *editingStickerView;
@property (retain, nonatomic) ACCTextStickerEditorSlider *fontSizeSlider;
@property (nonatomic) BOOL nextDeselectNotExitEditing;
@property (nonatomic) BOOL nextSelectUpdateInputView;
@property (nonatomic) BOOL isFinishingEditing;
@property (retain, nonatomic) AWEStoryTextImageModel *textModelForText;
@property (retain, nonatomic) ACCStickerGeometryModel *lastGeoModel;
@property (nonatomic) unsigned long long lastTextTemplateCategoryIndex;
@property (retain, nonatomic) NSValue *lastTextTemplateContentOffsetValue;
@property (retain, nonatomic) NSValue *singleWordSizeValue;
@property (retain, nonatomic) NSString *stickerIdForTTSUpdate;
@property (retain, nonatomic) id<AEKAudioStashes> ttsStashes;
@property (weak, nonatomic) id<AEKTextStickerEditor> textStickerEditor;
@property (weak, nonatomic) id<AEKNewTextStickerEditor> textNewStickerEditor;
@property (weak, nonatomic) id<AEKRuntimeStickerEditor> runtimeSticker;
@property (weak, nonatomic) id<AEKPreviewEditor> preview;
@property (retain, nonatomic) NSNumber *lastInvalidWillShowTime;
@property (retain, nonatomic) NSNumber *lastInvalidKeyboardHeight;
@property (retain, nonatomic) UIView *keyboardBackgroundView;
@property (readonly, nonatomic) ACCAETextStickerServiceImpl *textSickerService;
@property (retain, nonatomic) UIView<ACCTextLoadingViewProtcol> *loadingView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)componentDidAppear;
- (void)diffResults:(id)a0 fromSource:(unsigned long long)a1;
- (void)textStickerInputController:(id)a0 didUpdateSearchStatus:(BOOL)a1 Keyword:(id)a2 searchType:(unsigned long long)a3;
- (void)textStickerInputController:(id)a0 onExtraInfoDidChanged:(id)a1;
- (void)textStickerInputController:(id)a0 textView:(id)a1 onReplaceText:(id)a2 withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a3;
- (id)videoClipForTTSCanChangeTime;
- (void)componentDidMount;
- (id)serviceBindingArray;
- (id)locationModelWithData:(id)a0;
- (unsigned long long)defaultIndexWithSticker:(id)a0;
- (id)draftRootPath;
- (void)syncDataOnWillTransitionIn;
- (void)syncDataOnSaveWithPublishModel:(id)a0;
- (void)syncDataForLiveDraftWithPublishModel:(id)a0;
- (void)componentFirstFrameDidRender;
- (void)selectedSegmentDidChangeWithNew:(id)a0 old:(id)a1;
- (void)registerMenuActions;
- (void)menuActionCopy:(id)a0;
- (void)menuActionDelete:(id)a0;
- (void)menuActionApplyToCurrent:(id)a0;
- (void)menuActionApplyToAll:(id)a0;
- (id)selectedStickerTrack;
- (void)nleDoneWithActionName:(id)a0;
- (void)editTextStickerWithId:(id)a0;
- (void)recoverTextTemplateSticker:(id)a0;
- (void)recoverNewTextTemplateSticker:(id)a0;
- (id)wrapperViewWithNewSticker:(id)a0;
- (id)defaultContentWithFilePath:(id)a0;
- (id)wrapperViewWithSticker:(id)a0;
- (void)syncDataFromMegaEditor:(id)a0 toPublishModel:(id)a1;
- (void)updateTTSInfoWithStickerId:(id)a0 dataType:(long long)a1 megaEditor:(id)a2 publishModel:(id)a3;
- (void)saveTextSticker:(id)a0 withMegaEditor:(id)a1 useNewEffectProtocol:(BOOL)a2;
- (void)restoreTextStickerFromInfoStickerData:(id)a0;
- (void)updateEdgeInsetsWithView:(id)a0;
- (BOOL)isTextStickerWithStickerId:(id)a0;
- (BOOL)isNewStickerWithStickerId:(id)a0;
- (void)updateEditingStickerViewWithStickerId:(id)a0;
- (void)updateStickerInputControllerWithTextModel:(id)a0;
- (id)baseTextStickerWithId:(id)a0;
- (void)stickerViewSelectClipAtIndex:(long long)a0 stickerId:(id)a1 updateContent:(BOOL)a2;
- (void)updateSocialBarShow:(BOOL)a0;
- (BOOL)isStickerEditing:(id)a0;
- (BOOL)isTextTemplateSticker:(id)a0;
- (void)finishStickerEditing:(id)a0 needEndEditing:(BOOL)a1;
- (void)menuActionAdd:(id)a0;
- (void)menuActionEditContent:(id)a0;
- (void)menuActionTTS:(id)a0;
- (id)menuStatusTTS:(id)a0;
- (void)menuActionVoiceEffect:(id)a0;
- (id)menuStatusVoiceEffect:(id)a0;
- (void)menuActionEditTextStyle:(id)a0;
- (void)addNewSticker;
- (void)editStickerWithId:(id)a0;
- (void)editStickerTTS:(id)a0;
- (BOOL)hasTTSWithId:(id)a0;
- (void)editStickerStyleWithId:(id)a0;
- (void)copyStickerWithId:(id)a0;
- (void)deletePlaceholderStickerWithNeedEndEditing:(BOOL)a0;
- (void)deleteStickerWithId:(id)a0 needEndEditing:(BOOL)a1;
- (id)defaultLocationModel;
- (id)defaultTextModel;
- (BOOL)prepareEditingSticker:(id)a0;
- (void)setupInputViewWithSticker:(id)a0;
- (void)endStickerEditing;
- (id)validText:(id)a0;
- (void)deleteStickerAndResetEditingInfoWithId:(id)a0 needEndEditing:(BOOL)a1;
- (void)saveExtraTextInfoWithSticker:(id)a0;
- (void)refreshTextThirdMenuIfNeeded;
- (void)resetEditingStickerView;
- (void)preSaveStickImageWithStickerId:(id)a0;
- (void)copyWithSticker:(id)a0;
- (void)didSelectStickerView:(id)a0;
- (void)didDeselectStickerView:(id)a0;
- (BOOL)optimizeNewTextStickerToolsPreview;
- (void)setupFontSizeSlider:(double)a0;
- (void)updateFontSizeSlider;
- (void)removeFontSizeSlider;
- (void)resetInputView;
- (BOOL)isTextTemplateView;
- (void)activeBorderIfNeededWithSticker:(id)a0 clipIndex:(unsigned long long)a1;
- (void)changeTTSFromSticker:(id)a0 toSticker:(id)a1;
- (void)diffTextResult:(id)a0 fromSource:(unsigned long long)a1;
- (void)diffNewTextResult:(id)a0 fromSource:(unsigned long long)a1;
- (void)inputViewTextDidChange:(id)a0;
- (double)socialToolbarHeight;
- (void)saveEditingSocialContentWithSticker:(id)a0;
- (void)setupSocialToolbar;
- (struct CGSize { double x0; double x1; })generateSingleWordSize:(id)a0;
- (void)fontSizeSliderValueDidChanged:(id)a0;
- (BOOL)inputView:(id)a0 shouldChangeTextInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1 replacementText:(id)a2;
- (void)inputViewTextDidChangeSelection:(id)a0;
- (void)inputViewDidEndEditing:(id)a0;
- (void)inputView:(id)a0 didPickTextStyle:(unsigned long long)a1 indexPath:(id)a2;
- (void)inputView:(id)a0 didPickAlignment:(long long)a1 indexPath:(id)a2;
- (void)inputView:(id)a0 didPickColor:(id)a1 indexPath:(id)a2;
- (void)inputView:(id)a0 didPickFont:(id)a1 indexPath:(id)a2;
- (void)inputView:(id)a0 didSelectEffect:(id)a1 extraParams:(id)a2 indexPath:(id)a3 contentOffset:(struct CGPoint { double x0; double x1; })a4 categoryIdentifier:(id)a5;
- (void)trackClearSticker:(id)a0 extraParams:(id)a1;
- (void)inputView:(id)a0 didDeselectEffect:(id)a1 indexPath:(id)a2;
- (void)configActionsOfStickerId:(id)a0 dataType:(long long)a1;
- (id)configWithSticker:(id)a0;
- (id)defaultTextModelWithCache;
- (void)doneWithActionName:(id)a0 needRefreshCurrentBar:(BOOL)a1;
- (void).cxx_destruct;
- (void)keyboardWillShow:(id)a0;
- (void)keyboardWillHide:(id)a0;
- (void)render:(id)a0;

@end
