@class DUXAlertDialog, UILabel, NSObject, ACCAIGCUnifyLoadingViewConfig, ACCAIGCUnifyHeadingView, ACCAnimatedButton, ACCEditAIFakeProgressView, UIView, ACCAIGCScrollingTextLabel, NSString, DUXActionSheet, NSTimer, ACCTransAsyncButton, ACCAIGCUnifyLoadingViewSubTitleTaskManager, UIImageView;
@protocol ACCDUXLoadingInstance, ACCAIGCUnifyLoadingViewDelegate, ACCMultiStyleAlertProtocol;

@interface ACCAIGCUnifyLoadingView : UIView <DUXActionSheetDelegate, ACCAIGCUnifyLoadingViewProtocol>

@property (retain, nonatomic) ACCAnimatedButton *backButton;
@property (retain, nonatomic) UIView *bgMaskView;
@property (retain, nonatomic) UIImageView *showImageView;
@property (retain, nonatomic) UIImageView *avatarImageView;
@property (retain, nonatomic) UILabel *descriptionLabel;
@property (weak, nonatomic) id<ACCDUXLoadingInstance> duxLoading;
@property (retain, nonatomic) ACCEditAIFakeProgressView *progressView;
@property (retain, nonatomic) ACCAIGCUnifyHeadingView *headingView;
@property (retain, nonatomic) ACCAIGCScrollingTextLabel *scrollSubtitle;
@property (retain, nonatomic) ACCTransAsyncButton *bottomButton;
@property (retain, nonatomic) UILabel *bottomLabel;
@property (retain, nonatomic) UILabel *draftBottomLabel;
@property (retain, nonatomic) UILabel *errorHeadingLabel;
@property (retain, nonatomic) ACCAnimatedButton *retryButton;
@property (copy, nonatomic) id /* block */ backAlertConfig;
@property (retain, nonatomic) NSObject<ACCMultiStyleAlertProtocol> *backAlert;
@property (retain, nonatomic) NSTimer *delayTimer;
@property (retain, nonatomic) NSTimer *consumeMediumTimer;
@property (nonatomic) double consumeMediumCountdownTime;
@property (retain, nonatomic) ACCAnimatedButton *moreButton;
@property (retain, nonatomic) DUXActionSheet *moreActionSheet;
@property (retain, nonatomic) DUXAlertDialog *detainAlertDialog;
@property (nonatomic) BOOL shouldShowDetainAlert;
@property (nonatomic) long long estimateWaitTimeSeconds;
@property (retain, nonatomic) ACCAIGCUnifyLoadingViewConfig *config;
@property (nonatomic) BOOL isReceiveTaskId;
@property (nonatomic) BOOL didSetFakeReceiveTaskId;
@property (nonatomic) BOOL isTimerCreated;
@property (nonatomic) long long currentLoadingViewType;
@property (nonatomic) long long currentPageLoadingViewType;
@property (copy, nonatomic) NSString *waitTimeTip;
@property (nonatomic) long long lastWaitingSeconds;
@property (nonatomic) double estimateConsumingTime;
@property (nonatomic) BOOL doubleTapOpt;
@property (nonatomic) BOOL isBacking;
@property (nonatomic) unsigned long long lastSubtitleType;
@property (retain, nonatomic) ACCAIGCUnifyLoadingViewSubTitleTaskManager *subTitleTaskManager;
@property (weak, nonatomic) id<ACCAIGCUnifyLoadingViewDelegate> delegate;
@property (nonatomic) long long statusCode;
@property (nonatomic) BOOL shouldHiddenRetryButton;
@property (copy, nonatomic) NSString *taskError;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)actionSheet:(id)a0 didClickButtonAtIndex:(long long)a1;
- (void)backClicked;
- (void)updateLoadingViewSceneType:(long long)a0;
- (void)updateShowImage:(id)a0 exceptFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)updateLoadingViewWithAIGCProcessResultModel:(id)a0 querySceneType:(long long)a1;
- (BOOL)isErrorType;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 withConfig:(id)a1;
- (void)updateLoadingViewType:(long long)a0 errMsg:(id)a1;
- (void)updateLoadingViewShowOrHide:(BOOL)a0;
- (void)updateLoadingViewSubtitleWith:(long long)a0 type:(unsigned long long)a1;
- (void)resetUnifyLoadingViewState;
- (void)updateUnifyConfigTimeConsuming:(long long)a0;
- (void)removeLoading;
- (void)p_initData;
- (void)resetCurrentPageLoadingViewType;
- (void)updateLoadingViewWithNewErrorTypeFromToastDetail:(id)a0;
- (void)forceShowBottomTransAsyncButtonWith:(id)a0;
- (void)updateSubTitleWith:(id)a0 withScene:(long long)a1;
- (void)handleBackDismiss;
- (void)handleFinishTask;
- (void)endProgressWithDuration:(double)a0 completion:(id /* block */)a1;
- (long long)getloadingViewType;
- (void)updateShowImage:(id)a0;
- (void)startFakeProgress;
- (void)resetProgressView;
- (void)trackCancelAICreateShow;
- (id)waitTipWithType:(unsigned long long)a0 waitSeconds:(long long)a1 needDraftAppend:(BOOL)a2;
- (id)initialWaitTimeTip;
- (id)formatLongWaitTimeTipWithWaitSeconds:(long long)a0 originWaitTip:(id)a1;
- (BOOL)shouldUpdateWaitTipForViewTypeLongWithNewWaitSeconds:(long long)a0 lastWaitSeconds:(long long)a1;
- (void)p_setupTimeConsumingAndLoadingViewType;
- (void)setupRealTimeLoadingViewType;
- (void)closeAIGCLoadingForWidget;
- (void)setupRealTimeInitStyleWithWaitSeconds:(long long)a0 waitTip:(id)a1 querySceneType:(long long)a2;
- (void)updateRightInfoWithText:(id)a0;
- (void)setUpRightInfoLabel;
- (void)showTopTaskInfo:(id)a0;
- (void)updateDataWithResultModel:(id)a0;
- (void)enableMoreButtonIfNeeded;
- (void)updateLoadingViewSubtitle:(id)a0 needTimeInterval:(long long)a1 needSave:(BOOL)a2 type:(unsigned long long)a3;
- (void)updateRealTimeUpdateLoading:(long long)a0 waitTip:(id)a1 querySceneType:(long long)a2;
- (BOOL)isAuditNotPassAndSetTaskError:(id)a0;
- (id)defaultErrorText;
- (void)p_stopTask;
- (void)showBottomButtonIfNeeded:(long long)a0;
- (void)consumeMediumCountdown;
- (void)updateLoadingViewSubtitle:(id)a0 needTimeInterval:(long long)a1 needSave:(BOOL)a2 type:(unsigned long long)a3 completion:(id /* block */)a4;
- (BOOL)isInProgressLoadingViewType;
- (void)p_retryAction;
- (BOOL)isInFailedDismissDirectlyLoadingViewType;
- (void)p_cancelTaskAndDismiss;
- (void)bottomButtonClickWithType:(id)a0;
- (void)markBacking;
- (id /* block */)p_cancelActionConfig;
- (id /* block */)p_imNoticeActionConfig;
- (id /* block */)p_saveDraftActionConfig;
- (id /* block */)p_combineBackAlertConfigsWithBusinessConfigs:(id)a0 isCancelAlert:(BOOL)a1;
- (void)p_transferToIMAsyncTaskAndDismiss:(id)a0;
- (void)p_transferAsyncTaskAndDismiss:(id)a0;
- (void)p_postAsyncTaskNotification;
- (void)p_cancelTaskAndDismissWithClickType:(id)a0;
- (id /* block */)p_alertConfigWithoutActionWithIsCancelAlert:(BOOL)a0;
- (void)showDetainAlertAndCancelTaskWithCancelType:(id)a0;
- (void)showDetainAlertDialogWithCancelType:(id)a0;
- (void)cancelTaskActionWithCancelType:(id)a0;
- (void)moreButtonDidClicked:(id)a0;
- (void)bottomButtonClick;
- (void)configBottomButtonHidden:(BOOL)a0;
- (void)updateBottomTip:(id)a0;
- (id)getCurrentSubTitle;
- (BOOL)isTapedInRetryButton:(struct CGPoint { double x0; double x1; })a0;
- (void)performTapActionWithGesture:(id)a0;
- (void)cancelTaskAndDismissWithClickType:(id)a0;
- (id /* block */)p_backActionConfig;
- (id /* block */)p_cancelMakeActionConfig;
- (void)p_setupUI;
- (void).cxx_destruct;
- (void)dealloc;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)showLoading;

@end
