@class NSString, NSMutableDictionary, ACCEditBeautyEffectComposerCacheKeys, NSNumber;

@interface ACCEditBeautyEffectComposerCacheViewModel : NSObject

@property (retain, nonatomic) NSMutableDictionary *candidateCache;
@property (nonatomic) long long currentGender;
@property (nonatomic) long long cameraPosition;
@property (copy, nonatomic) NSString *businessName;
@property (retain, nonatomic) ACCEditBeautyEffectComposerCacheKeys *cacheKeysObj;
@property (retain, nonatomic) NSNumber *beautyDefaultSwitch;

- (id)initWithBusinessName:(id)a0;
- (id)cachedSelectedCategory;
- (void)setRatio:(float)a0 forEffect:(id)a1;
- (void)updateEffectWithCachedStrength:(id)a0;
- (id)effectNumberForTag:(id)a0;
- (id)appliedEffectsFromCacheForGender:(long long)a0;
- (id)isSwitchOnWithCategoryId:(id)a0;
- (id)cacheKeyForEffectItem:(id)a0 gender:(long long)a1;
- (id)cacheKeyForEffect:(id)a0 gender:(long long)a1;
- (id)cacheKeyForCategory:(id)a0 gender:(long long)a1;
- (id)cacheKeyForAppliedEffects;
- (id)appliedEffectsFromCacheForKey:(id)a0;
- (id)cachedKeyForAppliedEffectsOfGender:(long long)a0;
- (id)cacheIDSeparator;
- (void)cacheAppliedEffectsResourceIds:(id)a0 forGender:(long long)a1;
- (id)p_cacheKeyForChildCategoryIdOfCategory:(id)a0;
- (id)p_cacheKeyForCurrentTab;
- (void)updateCategoryFromCache:(id)a0 multiSlider:(BOOL)a1 gender:(long long)a2;
- (void)updateEffectWithCachedStrength:(id)a0 multiSlider:(BOOL)a1 gender:(long long)a2;
- (id)cachedSelectedCategoryIdForParentCategory:(id)a0;
- (void)updateAppliedEffectForCategory:(id)a0 gender:(long long)a1;
- (id)cacheKeyForCategory:(id)a0;
- (float)ratioForEffect:(id)a0 gender:(long long)a1;
- (float)ratioForEffectItem:(id)a0 gender:(long long)a1;
- (float)ratioForEffect:(id)a0 tag:(id)a1 gender:(long long)a2;
- (float)convertToRatioForEffectValue:(float)a0 withEffectItem:(id)a1;
- (void)setRatio:(float)a0 forEffect:(id)a1 gender:(long long)a2;
- (float)convertToValueForRatio:(float)a0 withEffectItem:(id)a1;
- (void)setEffectValue:(float)a0 forTag:(id)a1;
- (void)setRatio:(float)a0 forEffect:(id)a1 tag:(id)a2 gender:(long long)a3;
- (void)updateDefaultRatioForEffectWrapper:(id)a0 multiSlider:(BOOL)a1 gender:(long long)a2;
- (float)ratioForEffectItem:(id)a0;
- (void)updateAppliedChildEffectForEffect:(id)a0 forGender:(long long)a1;
- (id)cacheKeyForEffect:(id)a0;
- (id)appliedChildResourceIdForEffect:(id)a0 gender:(long long)a1;
- (id)keyForCacheSelectedTimestamp:(id)a0;
- (void)setRatio:(float)a0 forEffectItem:(id)a1 gender:(long long)a2;
- (void)cacheSelectedFilter:(id)a0 withCameraPosition:(long long)a1;
- (id)cacheKeyForFilterWithCameraPosition:(long long)a0;
- (id)cacheKeyForFilter;
- (BOOL)shouldAlwaysRecognizeAsFemale;
- (void)updateCurrentGender:(long long)a0 cameraPosition:(long long)a1;
- (float)effectValueForTag:(id)a0;
- (id)cacheKeyForEffectItem:(id)a0;
- (void)setCategory:(id)a0 switchOn:(BOOL)a1;
- (BOOL)isCategorySwitchOn:(id)a0;
- (void)configBeautyDefaultSwitchState:(id)a0;
- (void)updateCandidateChildEffect:(id)a0 forParentItemID:(id)a1;
- (id)cachedCandidateChildEffectIDForParentItemID:(id)a0;
- (id)appliedEffectsFromCache;
- (void)clearCachedAppliedEffects;
- (void)cacheAppliedEffects:(id)a0;
- (id)p_cacheKeyForSelectedNoneOfCategory:(id)a0;
- (void)cacheSelectedChildCategoryId:(id)a0 forParentCategory:(id)a1;
- (void)cacheSelectedCategory:(id)a0;
- (void)updateCategoryFromCache:(id)a0;
- (void)updateCategoryFromCache:(id)a0 multiSlider:(BOOL)a1;
- (void)updateAppliedEffectForCategory:(id)a0;
- (void)clearAppliedEffectForCategory:(id)a0;
- (float)ratioForEffect:(id)a0;
- (float)ratioForEffect:(id)a0 tag:(id)a1;
- (void)setRatio:(float)a0 forEffect:(id)a1 tag:(id)a2;
- (void)updateEffectWithCachedStrength:(id)a0 multiSlider:(BOOL)a1;
- (void)updateDefaultRatioForEffectWrapper:(id)a0 multiSlider:(BOOL)a1;
- (void)updateAppliedChildEffectForEffect:(id)a0;
- (void)clearAppliedChildEffectForEffect:(id)a0;
- (id)appliedChildResourceIdForEffect:(id)a0;
- (double)lastSelectedTimestamp:(id)a0;
- (void)cacheSelectedTimestampForEffect:(id)a0;
- (void)cacheSelectedTimestamp:(double)a0 forEffect:(id)a1;
- (void)setRatio:(float)a0 forEffectItem:(id)a1;
- (void)cacheSelectedFilter:(id)a0;
- (id)cachedFilterID;
- (void)updateRecognizedGender:(long long)a0;
- (void).cxx_destruct;
- (void)dealloc;

@end
