@class NSString, NSMutableDictionary, NSMutableSet, ACCRepositoryWorkspace, NSDictionary;
@protocol ACCRepoPrepareComposerData, ACCRepoDuetData, ACCRepoPublishConfigData;

@interface ACCRepositoryProject : NSObject <AEKMegaEditorDelegate, ACCPublishRepositoryFunctions, ACCPublishRepository, ACCCreationContext, NSCopying>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) id<ACCRepoPrepareComposerData> repoComposerData;
@property (readonly, nonatomic) id<ACCRepoDuetData> repoDuetData;
@property (readonly, nonatomic) id<ACCRepoPublishConfigData> repoPublishConfigData;
@property (readonly, weak, nonatomic) ACCRepositoryWorkspace *workspace;
@property (retain, nonatomic) NSMutableSet *virtualNodes;
@property (retain, nonatomic) NSMutableDictionary *extensionModels;
@property (retain, nonatomic) NSMutableDictionary *registerNodeInfoHash;
@property (weak, nonatomic) ACCRepositoryProject *relatedProject;
@property (readonly, nonatomic) NSDictionary *registerNodeInfo;
@property (retain, nonatomic) NSString *UUID;
@property (copy, nonatomic) id /* block */ registerInfoTest;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)makeNewProjectFromWorkspace:(id)a0;
+ (void)_aweLazyRegisterLoad_AEKEngine;
+ (void)_aweLazyRegisterLoad_CreationSession;
+ (void)_aweLazyRegisterLoad_Studio;
+ (id)recoveryNewProjectWithExtensionModels:(id)a0 forWorkspace:(id)a1;
+ (Class)projectClass;

- (void)setExtensionModelByClass:(id)a0;
- (id)extensionModelOfClass:(Class)a0;
- (unsigned long long)projectsCount;
- (id)allPublishViewModels;
- (id)repoDataOfProtocol:(id)a0;
- (id)useCaseOfProtocol:(id)a0;
- (BOOL)multiProjects;
- (id)megaEditor;
- (void)configWithDraftModel:(id)a0;
- (void)storeToDraftModel:(id)a0;
- (void)markWorkspaceDraftShadow:(id)a0;
- (void)resetCreationData;
- (id)extensionModelOfProtocol:(id)a0;
- (id)readerForProtocol:(id)a0 findInSession:(BOOL)a1;
- (id)mutableDataForProtocol:(id)a0 findInSession:(BOOL)a1;
- (void)syncCreationSessionTo:(id)a0;
- (void)aek_megaNodeWillDone:(id)a0;
- (id)aek_diffPropertyNames;
- (id)aek_megaNodeUndoRedoFrom:(id)a0 to:(id)a1;
- (id)aek_megaNodeResetFrom:(id)a0 to:(id)a1;
- (id)aek_allDiffableRepoModels:(BOOL)a0;
- (void)setAek_PreProject:(id)a0;
- (void)setAek_diffPropertyNames:(id)a0;
- (id)aek_preProject;
- (id)aek_diffRepoModels:(id)a0 fromRepoModels:(id)a1;
- (void)aek_persistDiffResults:(id)a0 editor:(id)a1 cache:(id)a2;
- (id)dtoModelFor:(id)a0 cache:(id)a1;
- (void)enumerateExtensionModels:(BOOL)a0 requireProtocol:(id)a1 requireSelector:(SEL)a2 block:(id /* block */)a3;
- (void)nodeWillChange:(id)a0 type:(unsigned long long)a1;
- (id)nodeDidChangeFrom:(id)a0 to:(id)a1 type:(unsigned long long)a2;
- (id)megaData;
- (BOOL)hasWorkspace;
- (void)removeExtensionModel:(Class)a0;
- (id)deepCopyExtensionModels;
- (id)instanceRepoDatasOfProtocol:(id)a0;
- (void)aek_generateMegaEditorWithNLE:(id)a0;
- (id)acc_projectDraftFolder;
- (id)instanceRepoModelsOfClass:(Class)a0;
- (void)setCreationScope:(long long)a0;
- (void)initializeRepoIfNeededWithClass:(Class)a0;
- (id)parentRepository;
- (id)copyWithZone_aek_project:(struct _NSZone { } *)a0;
- (void)aek_generateMegaEditorWithNLE:(id)a0 subscriberProvider:(id)a1;
- (void)aek_generateMegaEditorWithData:(id)a0 subscriberProvider:(id)a1;
- (void)aek_clearMegaEditor;
- (id)copyWithZone_creationSessionHook:(struct _NSZone { } *)a0;
- (void)syncCreationSessionToNewProject:(id)a0;
- (id)readerForProtocol:(id)a0;
- (id)readerForProtocol:(id)a0 searchInSession:(BOOL)a1;
- (id)mutableDataForProtocol:(id)a0;
- (id)mutableDataForProtocol:(id)a0 searchInSession:(BOOL)a1;
- (void)setupRegisteredRepositoryElements;
- (id)childRepositoryList;
- (void)updatePrepareScopeWithContainer:(id)a0;
- (id)createContainerWithReuseScopes:(id)a0;
- (void)removeObserver:(id)a0 forProtocol:(id)a1;
- (id)acc_copyWithZone:(struct _NSZone { } *)a0;
- (void)recoverFromExtensionModels:(id)a0;
- (void)updateRelatedProject:(id)a0 oldUUID:(id)a1;
- (id)registerInfoForModelClass:(Class)a0;
- (BOOL)addExtensionModel:(id)a0;
- (BOOL)hasRelatedProject;
- (void)insertRegisterInfo:(id)a0;
- (long long)currentScope;
- (id)allScopes;
- (id)project_repoModelOfClass:(Class)a0;
- (void).cxx_destruct;
- (id)init;
- (void)setWorkspace:(id)a0;
- (void)setup;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)addObserver:(id)a0 forProtocol:(id)a1;

@end
