@class UIView, NSString, TTVideoEngine, UISlider, ACCRecordTemplateVideoPreviewServiceImpl, UIImageView, UIButton, DUXPopover, UILabel, UIGestureRecognizer;
@protocol ACCRecordSwitchModeService, ACCRecordPropService, ACCRecordFrameRatioService, ACCRecorderViewContainer, ACCMusicModelProtocol, ACCRecordConfigService, ACCRecordSelectMusicService, ACCRecordTemplateVideoPreviewBarItemService, ACCRecordFlowService, ACCCameraService, ACCRecordCutMusicServiceProtocol;

@interface ACCRecordTemplateVideoPreviewComponent : ACCFeatureComponent <ACCRecordTemplateVideoPreviewServiceSubscriber, ACCRecordSwitchModeServiceSubscriber, ACCRecordFrameRatioServiceSubscriber, ACCRecordFlowServiceSubscriber, ACCRecordPropServiceSubscriber, ACCPanelViewDelegate, DUXToastDelegate, TTVideoEngineDelegate, ACCCameraLifeCircleEvent, ACCRecorderEvent>

@property (retain, nonatomic) ACCRecordTemplateVideoPreviewServiceImpl *templateVideoPreviewService;
@property (retain, nonatomic) UIView *templateVideoPreviewContainer;
@property (retain, nonatomic) UIView *templateVideoPreviewView;
@property (retain, nonatomic) UILabel *previewSpeedControlLabel;
@property (retain, nonatomic) UISlider *whiteSlider;
@property (retain, nonatomic) UIImageView *coverImageView;
@property (retain, nonatomic) UIView *loadingMaskView;
@property (retain, nonatomic) UIImageView *loadingIconView;
@property (retain, nonatomic) UIButton *closeButton;
@property (retain, nonatomic) id<ACCMusicModelProtocol> anchorMusic;
@property (retain, nonatomic) NSString *trendMusicID;
@property (nonatomic) double downloadStartTime;
@property (nonatomic) double veLoadPreviewStartTime;
@property (retain, nonatomic) DUXPopover *guidePopover;
@property (nonatomic) BOOL showVideoGuideOnResourceLoadFinished;
@property (nonatomic) BOOL disableShowGuide;
@property (nonatomic) BOOL hasTriedShowGuide;
@property (retain, nonatomic) TTVideoEngine *guideVideoPlayer;
@property (nonatomic) BOOL firstFrameDidRender;
@property (nonatomic) BOOL showGuideAfterFirstFrame;
@property (nonatomic) BOOL hasShownPreview;
@property (nonatomic) BOOL hasClickedBarItem;
@property (retain, nonatomic) UIGestureRecognizer *tapGesture;
@property (retain, nonatomic) UIGestureRecognizer *panGesture;
@property (retain, nonatomic) UIGestureRecognizer *pinchGesture;
@property (nonatomic) double currentScale;
@property (nonatomic) double scaleBeforePinch;
@property (retain, nonatomic) id<ACCCameraService> cameraService;
@property (retain, nonatomic) id<ACCRecorderViewContainer> viewContainer;
@property (retain, nonatomic) id<ACCRecordSwitchModeService> recordSwitchModeService;
@property (retain, nonatomic) id<ACCRecordConfigService> configService;
@property (retain, nonatomic) id<ACCRecordSelectMusicService> musicService;
@property (retain, nonatomic) id<ACCRecordFlowService> flowService;
@property (retain, nonatomic) id<ACCRecordCutMusicServiceProtocol> recordCutMusicService;
@property (retain, nonatomic) id<ACCRecordPropService> propService;
@property (retain, nonatomic) id<ACCRecordFrameRatioService> frameRatioService;
@property (weak, nonatomic) id<ACCRecordTemplateVideoPreviewBarItemService> previewBarItemService;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)videoEngineUserStopped:(id)a0;
- (void)videoEngineDidFinish:(id)a0 error:(id)a1;
- (void)videoEngineDidFinish:(id)a0 videoStatusException:(long long)a1;
- (void)videoEngineCloseAysncFinish:(id)a0;
- (void)videoEngineReadyToDisPlay:(id)a0;
- (void)componentDidAppear;
- (void)componentDidDisappear;
- (void)switchModeServiceDidChangeMode:(id)a0 oldMode:(id)a1;
- (void)onChangeMusicStartTimeS:(double)a0 clipDurationS:(double)a1;
- (void)onCameraFirstFrameDidRender:(id)a0;
- (void)flowServiceStateDidChanged:(unsigned long long)a0 preState:(unsigned long long)a1;
- (void)panelViewController:(id)a0 didShowPanelView:(id)a1;
- (void)flowServiceDidRemoveLastSegment:(BOOL)a0;
- (void)flowServiceDidRemoveAllSegment;
- (void)panelViewController:(id)a0 didDismissPanelView:(id)a1;
- (void)loadTemplateVideoIfNeeded;
- (void)loadComponentView;
- (void)componentDidMount;
- (void)componentDidUnmount;
- (id)serviceBinding;
- (void)setupCloseButton;
- (void)showGuideIfNeeded;
- (void)setupContent:(struct CGSize { double x0; double x1; })a0;
- (void)panAction:(id)a0;
- (void)recordFrameRatioDidSwitchTo:(long long)a0;
- (void)pinchAction:(id)a0;
- (void)cleanDuetProfileCache;
- (void)clickCloseBtn:(id)a0;
- (void)barItemClicked;
- (void)observeMusicSelect;
- (void)playAndShowTemplateVideoPreview;
- (void)replaceMusicAction;
- (void)cutMusicAction;
- (void)autoSwitchOnPreview;
- (void)alog_trackTemplateVideoLoadPreviewEvent;
- (void)setupBarItem;
- (void)setupSlider;
- (void)setupPreviewSpeedControl;
- (void)pauseAndHideTemplateVideoPreview:(BOOL)a0;
- (void)trackBarItemShow;
- (void)clearAllToolbarGuide;
- (void)trackBarItemClickWithIsSwitchOnBeforeClick:(BOOL)a0;
- (void)trackTemplateVideoPreviewCloseEvent;
- (void)updateTemplateVideoPreviewShowState;
- (void)showVideoGuidePopoverIfCan;
- (void)showSimpleGuidePopover;
- (id)guideTextFont;
- (void)showGuidePopover:(id)a0;
- (void)showVideoGuidePopover;
- (void)trackGuideClick;
- (void)trackGuideShow;
- (double)maxBottomForPreviewContainer;
- (id)speedControlAttributedText:(id)a0;
- (id)speedControlUnitAttributedText:(id)a0 fontSize:(double)a1;
- (void)trackTemplateVideoPreviewShowEvent;
- (void)tryShowTemplateVideoTips;
- (id)configTemplateVideoTipsWithTargetView:(id)a0;
- (void)pauseAndHideTemplateVideoPreview;
- (void)configLoadingView;
- (void)showLivePhotoRecordingImageView;
- (void)hideLivePhotoRecordingImageView;
- (id)templateVideoCommonTrackDic;
- (void)trackPreviewOperation:(id)a0 speed:(double)a1;
- (void)trackTemplateVideoPreviewLoadingTimeEvent;
- (void)alog_trackTemplateVideoResourceDownloadEvent:(BOOL)a0 error:(id)a1;
- (struct CGSize { double x0; double x1; })currentPreviewViewSize;
- (void)checkMusicRange;
- (BOOL)isCurrentMusicEqualToAnchorMusic;
- (void)showClosePreviewToastWithShowView:(id)a0 toastText:(id)a1 highlightedTextClickBlock:(id /* block */)a2;
- (BOOL)isCurrentMusicRangeLocationSatisfy;
- (void)trackPreviewOperation:(id)a0;
- (void)updatePreviewViewCenter:(id)a0 translation:(struct CGPoint { double x0; double x1; })a1;
- (void)swapAction:(id)a0;
- (void)loadTemplateVideoSuccess:(id)a0;
- (void)loadTemplateVideoFailed:(id)a0;
- (void)templateVideoPreviewViewSwapped;
- (void)applicationWillResignActive:(id)a0;
- (void).cxx_destruct;
- (BOOL)isRecording;
- (void)startLoading;
- (void)applicationDidBecomeActive:(id)a0;
- (void)stopLoading;
- (void)updateSlider:(double)a0;

@end
