@class ACCCameraSubscription, NSString;
@protocol AEKBGMPlayer;

@interface AEKAudioAbilityImpl : AEKEditAbility <AEKDiffChangeSubscriber, AEKAudioAbility>

@property (weak, nonatomic) id<AEKBGMPlayer> bgmPlayer;
@property (retain, nonatomic) ACCCameraSubscription *audioDiffSubscription;
@property (copy, nonatomic) id /* block */ slidesHasBGM;
@property (copy, nonatomic) id /* block */ isTemplate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)diffResults:(id)a0 fromSource:(unsigned long long)a1;
- (void)trimAudioClipDurationAfterMainVideoDurationChanged;
- (double)bgmVolume;
- (BOOL)configBGMFadeInOut:(float)a0 Keyframe:(id)a1 fadeInOut:(id)a2;
- (void)configAllMusicVolumes:(double)a0;
- (void)configAllVideoVolumesDiff:(id)a0;
- (double)getVoiceMaxVolume;
- (BOOL)configAllVideoVolumes:(double)a0;
- (BOOL)hasVideoAudioTrack;
- (BOOL)recoverVoiceChangeFlag:(id)a0;
- (BOOL)hasMusicAudioTrack;
- (void)removeBGM;
- (BOOL)hasBGM;
- (id)addAudioClip:(id)a0 name:(id)a1 audioId:(id)a2 audioType:(unsigned long long)a3 startTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a4 clipRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })a5;
- (id)addAudioClip:(id)a0 name:(id)a1 audioId:(id)a2 startTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a3 clipRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })a4 limitDuration:(struct { long long x0; int x1; unsigned int x2; long long x3; })a5 atAudio:(id)a6;
- (id)addAudioClip:(id)a0 name:(id)a1 audioId:(id)a2 startTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a3 clipRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })a4;
- (void)adjustAudioFeedInOutWithAudioClip:(id)a0;
- (BOOL)trimAudioClipByKeepSameAudioClipRangeStartTimeForAudioClip:(id)a0 targetTimeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })a1;
- (id)trimAudioClipDurationAfterVideoDurationChanged:(id)a0;
- (BOOL)isMusicTrack:(id)a0;
- (BOOL)isClipEdit:(id)a0 shootDuration:(double)a1;
- (BOOL)isVoiceTrack:(id)a0;
- (id)musicWithJsonString:(id)a0;
- (long long)getAudioClipCount:(BOOL)a0;
- (BOOL)isAudioEditWithData:(id)a0 shootDuration:(double)a1;
- (void)switchBGMPlayer:(id)a0;
- (void)addBGM:(id)a0 name:(id)a1 bgmId:(id)a2 startTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a3 duration:(struct { long long x0; int x1; unsigned int x2; long long x3; })a4 repeatCount:(long long)a5;
- (void)setBGMClipRange:(id)a0;
- (void)addAudioDiffSubscriber:(id)a0;
- (id)audioClipWithId:(id)a0;
- (void)removeAudioClip:(id)a0;
- (id)addAudioClip:(id)a0 name:(id)a1 audioId:(id)a2 startTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a3 clipRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })a4 atAudio:(id)a5;
- (id)splitAudioWithId:(id)a0 time:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (id)splitAudioByCreateNewAudioOperatorWithId:(id)a0 time:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (id)setAudioClipSpeedWithClipId:(id)a0 speed:(double)a1 keepTone:(BOOL)a2;
- (BOOL)trimAudioClipWithId:(id)a0 range:(id)a1;
- (BOOL)trimAudioClipWithId:(id)a0 targetStartTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (BOOL)trimAudioClipWithId:(id)a0 targetEndTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (BOOL)trimAudioClipByKeepSameAudioClipRangeStartTimeWithId:(id)a0 targetTimeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })a1;
- (id)trimAudioClipDurationAfterVideoDurationChangedByKeepClipRange:(id)a0;
- (id)moveAudioClipWithClipId:(id)a0 targetTimeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })a1 atAudio:(id)a2;
- (BOOL)updateAudioClipRangeEndAccordingToAudioTimeRangeWithClipID:(id)a0;
- (BOOL)updateAudioTimeRangeEndAccordingToAudioClipRangeWithClipID:(id)a0;
- (BOOL)isAudioEdit;
- (double)getClipMaxMusicVolume;
- (BOOL)isShowAudioChangeAlert;
- (BOOL)isShowVoiceChangeAlert;
- (id)getVoiceVolume;
- (BOOL)isBGMLoop;
- (BOOL)hasSpecialCopyrightAudio;
- (BOOL)hasVoiceAudio;
- (BOOL)hasExternalAudio;
- (void)configSlideAudioExit:(id /* block */)a0;
- (void)configHasTemplate:(id /* block */)a0;
- (void)updateBGMTrackWhenDelete;
- (id)jsonStringWithMusic:(id)a0 extraPlayURL:(id)a1;
- (id)bgmMusicWithStash:(id)a0;
- (void)restoreMusicTrackWhenDisableClipForScene:(unsigned long long)a0;
- (void)removeAudioClipWithLastPathComponent:(id)a0;
- (void)reset:(id /* block */)a0;
- (void).cxx_destruct;
- (void)done;
- (void)addObserver;
- (id)initWithServiceProvider:(id)a0;

@end
