@class AFDInsetsLabel, NSString, AWEPerformanceMeasureTask, UIView, AWEBindPhoneNumberTipView, UIButton, AWEAddressBookListManager, NSMutableArray, UITableView, DUXVacantView, UILabel, NSMutableDictionary;

@interface AWEAddressBookListViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIGestureRecognizerDelegate, AWEUserActionRevertMessage, AWEIMSwipeTableViewCellDelegate, AWEAddressBookListUserGeneralCellDelegate, AWERouterViewControllerProtocol>

@property (retain, nonatomic) UITableView *addressBookList;
@property (retain, nonatomic) AWEAddressBookListManager *addressBookListManager;
@property (retain, nonatomic) AWEBindPhoneNumberTipView *bindPhoneView;
@property (retain, nonatomic) NSMutableArray *eventArray;
@property (retain, nonatomic) AFDInsetsLabel *registerCountLabel;
@property (nonatomic) BOOL isEnterFromMain;
@property (nonatomic) BOOL isEnterFromFindFriends;
@property (nonatomic) BOOL isEnterFromFindContactFriends;
@property (copy, nonatomic) NSString *enterMethod;
@property (copy, nonatomic) NSString *enterFrom;
@property (retain, nonatomic) AWEPerformanceMeasureTask *refreshPerformanceTask;
@property (retain, nonatomic) AWEPerformanceMeasureTask *loadMorePerformanceTask;
@property (nonatomic) BOOL cancelPop;
@property (retain, nonatomic) UIView *thirdPartyPlatformFriendsGuideView;
@property (retain, nonatomic) UIView *limitedContactGuide;
@property (retain, nonatomic) UILabel *limitedContactGuideLabel;
@property (retain, nonatomic) UIButton *limitedContactGuideButton;
@property (retain, nonatomic) DUXVacantView *emptyViewWhenAuthorized;
@property (retain, nonatomic) DUXVacantView *emptyViewWhenLimited;
@property (nonatomic) BOOL showLimitContactTopGuide;
@property (nonatomic) BOOL hasTrackedShowLimitContactTopGuide;
@property (nonatomic) BOOL hasTrackedShowEmptyViewWhenLimited;
@property (retain, nonatomic) NSMutableDictionary *cellBusinessModels;
@property (copy, nonatomic) id /* block */ popBlock;
@property (nonatomic) BOOL isPresented;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (Class)aAWEUserProfileModuleServiceDOUYINLiteAdaperClass;

- (id)aweui_emptyPageConfigForState:(unsigned long long)a0;
- (void)aweui_emptyPagePrimaryButtonTapped:(id)a0;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })aweui_emptyPageEdgeInsets;
- (BOOL)configWithRouterParamDict:(id)a0;
- (BOOL)transition_enableCustomActionForSlideDirection:(unsigned long long)a0 gestureRecognizer:(id)a1;
- (void)backButtonClicked;
- (void)receiveUserRevertAction:(id)a0;
- (void)cellDidFinishFollow:(id)a0;
- (void)buildUI;
- (void)addressBookListRefresh:(BOOL)a0;
- (id)aAWEUserProfileModuleServiceDOUYINLiteAdaper;
- (void)p_reportDisplayForRowAtIndexPath:(id)a0;
- (void)showNotEmptyViewIfError:(BOOL)a0;
- (void)showEmptyView;
- (void)refreshRegisterCountLabel;
- (void)addThirdPartyPlatformFriendsGuideIfNeed;
- (void)removeThirdPartyPlatformFriendsGuideIfNeed;
- (long long)_sectionOfAddressBookList;
- (id)userModelForIndexPath:(id)a0;
- (id)configAndGetAddressBookTableViewCellWithTableView:(id)a0 indexPath:(id)a1 user:(id)a2 source:(id)a3;
- (void)removeCellWithSnackBar:(id)a0 userItem:(id)a1 indexPath:(id)a2;
- (id)p_previousPage;
- (BOOL)showBindPhoneView;
- (double)p_rowHeight;
- (void)addressBookListLoadMore;
- (id)weChatShareCell;
- (id)QQShareCell;
- (id)configAndGetUserListGeneralCellWithTableView:(id)a0 indexPath:(id)a1 user:(id)a2 source:(id)a3;
- (void)removeCell:(id)a0 indexPath:(id)a1;
- (void)p_showSocialSnackBar:(id)a0;
- (void)deleteDataSource:(id)a0;
- (void)deleteTableVIewCell:(id)a0;
- (void)removeUserModelAtIndexPath:(id)a0;
- (void)removeBindPhoneView:(id)a0;
- (void)enterBindPhonePage:(id)a0;
- (void)p_clickTopGuideButton;
- (void)p_gotoSystemSettings;
- (void)p_clickEmptyGuideButton;
- (id)tableView:(id)a0 editActionsForRowAtIndexPath:(id)a1 forOrientation:(long long)a2;
- (id)tableView:(id)a0 editActionsOptionsForRowAtIndexPath:(id)a1 forOrientation:(long long)a2;
- (void)p_trackRemoveFriendShow:(id)a0;
- (void).cxx_destruct;
- (id)tableView:(id)a0 viewForHeaderInSection:(long long)a1;
- (void)tableView:(id)a0 didSelectRowAtIndexPath:(id)a1;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (id)init;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (long long)numberOfSectionsInTableView:(id)a0;
- (void)endRefreshing;
- (void)tableView:(id)a0 willDisplayCell:(id)a1 forRowAtIndexPath:(id)a2;
- (double)tableView:(id)a0 heightForHeaderInSection:(long long)a1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)a0;
- (double)tableView:(id)a0 heightForFooterInSection:(long long)a1;

@end
