@class AWEBDALiteWebView, NSString, AWEAdWebViewController, AWEUILoadingView;
@protocol AWELiveStreamPlayer, AWELiveCustomMessageService;

@interface AWEBDASDKMediator : HTSService <BTDALSDKProtocol, BDASDKProtocol, BDASifProtocol, AWEWebViewLoadTaskMessage, BDARVSDKProtocol, AWEUserMessage, IESLivePlayerControllerDelegate, AWELiveCustomMessageSubscriber, AWEBDASDKMediator>

@property (retain, nonatomic) AWEAdWebViewController *adWebViewVC;
@property (copy, nonatomic) id /* block */ originalVideoInfoBlock;
@property (weak, nonatomic) AWEBDALiteWebView *liteWebview;
@property (retain, nonatomic) id<AWELiveStreamPlayer> livePlayer;
@property (retain, nonatomic) id<AWELiveCustomMessageService> customMessageManager;
@property (copy, nonatomic) id /* block */ sendMessageToFeBlock;
@property (copy, nonatomic) id /* block */ liveInnerWidgetAwardEvent;
@property (copy, nonatomic) id /* block */ liveInnerWidgetProgress;
@property (copy, nonatomic) id /* block */ liveShortCutEvent;
@property (copy, nonatomic) id /* block */ pendentInitInfo;
@property (retain, nonatomic) AWEUILoadingView *rewardLoadingView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)didFinishLogoutWithUid:(id)a0;
- (void)didFinishFollowUser:(id)a0 status:(long long)a1 error:(id)a2;
- (void)didFinishUnFollowUser:(id)a0 status:(long long)a1 error:(id)a2;
- (void)trackAdEvent:(id)a0 tag:(id)a1 extra:(id)a2 adExtra:(id)a3;
- (void)notifyLiveRewardedAdStatusFromShortTouchInfo:(id)a0;
- (void)notifyRewardAdLiveInnerWidgetInfo:(id)a0;
- (id)livePendantWatchInfoWithAwardEvent:(id /* block */)a0;
- (BOOL)isRewardVideo;
- (id)requestForBinaryWithResponse:(id)a0 params:(id)a1 method:(id)a2 needCommonParams:(BOOL)a3 headerField:(id)a4 priority:(long long)a5 requestSerializer:(Class)a6 responseSerializer:(Class)a7 callback:(id /* block */)a8;
- (id)requestForJSONWithResponse:(id)a0 params:(id)a1 method:(id)a2 needCommonParams:(BOOL)a3 headerField:(id)a4 priority:(long long)a5 requestSerializer:(Class)a6 responseSerializer:(Class)a7 callback:(id /* block */)a8;
- (void)performanceEventV3:(id)a0 params:(id)a1;
- (void)trackALog:(id)a0 tag:(id)a1 level:(long long)a2;
- (void)monitorService:(id)a0 value:(id)a1 category:(id)a2 extra:(id)a3;
- (void)eventData:(id)a0;
- (void)eventV3:(id)a0 params:(id)a1 isDoubleSending:(BOOL)a2;
- (void)monitorService:(id)a0 value:(id)a1 extra:(id)a2;
- (void)trackURLs:(id)a0 event:(id)a1;
- (void)openURL:(id)a0 options:(id)a1 completionHandler:(id /* block */)a2 customScene:(id)a3;
- (BOOL)openURL:(id)a0 customScene:(id)a1;
- (void)bdxPublishEventWithEventName:(id)a0 params:(id)a1;
- (id)getAppScheme;
- (id)liveModuleService;
- (void)adWebViewDidFinishLoadWithWebViewController:(id)a0;
- (void)adWebViewStartLoadWithWebViewController:(id)a0;
- (void)adWebViewDidFailLoadWithWebViewController:(id)a0 error:(id)a1;
- (void)trackRewardVideoPreloadWithLabel:(id)a0;
- (void)eventRewardData:(id)a0;
- (void)clickEventData:(id)a0 type:(id)a1;
- (id)preloadLiteWebViewWithModel:(id)a0;
- (BOOL)handleActionWithParams:(id)a0;
- (BOOL)openWebviewWithParams:(id)a0;
- (unsigned long long)clipboardAndPersistenceToken:(id)a0 params:(id)a1;
- (void)openFeedBackPageWithParams:(id)a0 adInfo:(id)a1 status:(id /* block */)a2;
- (void)openDetailWithParams:(id)a0;
- (void)preloadMPWithInfo:(id)a0;
- (void)preloadAppStoreWithInfo:(id)a0;
- (void)preloadLynxLandingWithInfo:(id)a0;
- (id)loadSpliceViewWithInfo:(id)a0;
- (void)loadLivePlayViewWithInfo:(id)a0;
- (id)createLivePlayViewWithInfo:(id)a0;
- (void)livePlayerStatus:(unsigned long long)a0;
- (id)requestHost;
- (void)originalVideoInfo:(id /* block */)a0;
- (void)openLive:(id)a0 lynxUI:(id)a1 completion:(id /* block */)a2;
- (BOOL)handleAppStoreActionModel:(id)a0;
- (long long)getOHRStatus;
- (void)inspireRequestExtraParams:(id /* block */)a0;
- (void)openAdShoppingWithURL:(id)a0 info:(id)a1;
- (void)connectLiveWithRoomID:(id)a0 scene:(id)a1 params:(id)a2;
- (void)addMessageSubscriberLiveWithMessage:(id)a0;
- (void)disconnectWithLive:(id)a0;
- (void)sendMessageToFeBlock:(id /* block */)a0;
- (id)getBridgesFromBtm;
- (void)bindLiveInnerPendantInitEvent:(id /* block */)a0;
- (void)bindLiveInnerWidgetProgressEvent:(id /* block */)a0;
- (void)bindLiveShortCutEvent:(id /* block */)a0;
- (void)notifyLiveReachBonusTimeWithInfo:(id)a0;
- (id)injectLoadingView;
- (void)showInjectLoading;
- (void)hideInjectLoading;
- (BOOL)routeOpenURL:(id)a0 userInfo:(id)a1;
- (unsigned long long)getAppTheme;
- (void)sendReqToWXWithUserName:(id)a0 path:(id)a1 customScene:(id)a2 callback:(id /* block */)a3;
- (void)pullSettings;
- (void)diggNotification:(id)a0;
- (void)registerATM;
- (void)registerMediator;
- (void)registerAdInnovation;
- (id)buildSchemeToRoom:(id)a0;
- (BOOL)largeFontAdaptationEnabled;
- (void).cxx_destruct;
- (long long)connectionType;
- (void)dealloc;
- (void)messageReceived:(id)a0;
- (id)getUserInfo;

@end
