@class NSValue, AWECloudAlbumAssetListDataController, UILabel, NSDictionary, NSObject, UITapGestureRecognizer, ACCAnimatedButton, AVPlayerLayer, AWECloudAlbumDetailTimeTracker, UIView, CAGradientLayer, NSString, EcAsset, UICollectionViewFlowLayout, AWECloudAlbumDownloadManager, AWECloudAlbumDetailDownloadHandler, AVPlayer, AWECloudAlbumPreviewCollectionView;
@protocol ACCTextLoadingViewProtcol, ACCMVTemplateManagerProtocol, AWECloudAlbumPreviewControllerDelegate, ACCMultiStyleAlertProtocol;

@interface AWECloudAlbumPreviewController : UIViewController <AWEZoomTransitionInnerContextProvider, AWETransitioningViewController, UICollectionViewDelegate, UICollectionViewDataSource, AWECloudAlbumDownloadManagerDelegate, AWECADDHandlerDelegate, AWECADDHandlerDataSource>

@property (readonly, nonatomic) NSDictionary *zoomTransitionContext;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSObject<ACCMultiStyleAlertProtocol> *moreAlert;
@property (weak, nonatomic) id<AWECloudAlbumPreviewControllerDelegate> delegate;
@property (retain, nonatomic) CAGradientLayer *gradientLayer;
@property (retain, nonatomic) ACCAnimatedButton *backButton;
@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) ACCAnimatedButton *editButton;
@property (retain, nonatomic) ACCAnimatedButton *moreButton;
@property (retain, nonatomic) UICollectionViewFlowLayout *layout;
@property (retain, nonatomic) AWECloudAlbumPreviewCollectionView *collectionView;
@property (retain, nonatomic) UITapGestureRecognizer *tapGesture;
@property (nonatomic) long long currentIndex;
@property (nonatomic) BOOL visibilityFlag;
@property (nonatomic) BOOL activeFlag;
@property (nonatomic) BOOL initialScrollDone;
@property (retain, nonatomic) AWECloudAlbumAssetListDataController *dataController;
@property (retain, nonatomic) UIView<ACCTextLoadingViewProtcol> *loadingView;
@property (retain, nonatomic) AWECloudAlbumDownloadManager *downloadManager;
@property (retain, nonatomic) UIView<ACCTextLoadingViewProtcol> *editLoadingView;
@property (nonatomic, getter=isCanceled) BOOL canceled;
@property (retain, nonatomic) AVPlayer *avPlayer;
@property (retain, nonatomic) AVPlayerLayer *avPlayerLayer;
@property (retain, nonatomic) NSValue *assetSize;
@property (nonatomic, getter=isTracking) BOOL tracking;
@property (retain, nonatomic) AWECloudAlbumDetailTimeTracker *timeTracker;
@property (retain, nonatomic) AWECloudAlbumDetailDownloadHandler *downloadHandler;
@property (retain, nonatomic) id<ACCMVTemplateManagerProtocol> mvTemplateManager;
@property (readonly, nonatomic) EcAsset *currentAssetModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)popViewControllerCancelled;
- (unsigned long long)zoomTransitionAllowedTriggerDirection;
- (id)zoomTransitionEndView;
- (long long)zoomTransitionItemOffset;
- (id)awe_preferredTransitionProviderClassNameForContext:(id)a0;
- (void)removePlayer;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })playerFrame;
- (void)loadMoreData;
- (void)handleAppBecomeActiveNotification;
- (void)handleAppResignActiveNotification;
- (void)runLoopTheMovie:(id)a0;
- (void)download_shouldExitSelectMode;
- (id)download_client;
- (id)download_taskKey;
- (id)download_containerView;
- (id)download_createAlertView;
- (id)initWithDataController:(id)a0 currentAssetModel:(id)a1 delegate:(id)a2;
- (void)downloadSucceedForItem:(id)a0;
- (void)downloadFailedForItem:(id)a0;
- (void)cancelSucceedForItem:(id)a0;
- (void)cancelFailedForItem:(id)a0;
- (long long)awe_zoomTransitionItemOffset;
- (BOOL)isFirstAsset;
- (BOOL)isLastAsset;
- (void)awe_popViewControllerCancelled;
- (void)preloadCoversWithIndex:(long long)a0;
- (void)playWhenFirstEnter:(id)a0;
- (void)setUpPlayer:(id)a0;
- (void)startPlayForIndex:(long long)a0;
- (void)playAfterCheck;
- (void)scrollToCurrentIndex;
- (void)tapScreen;
- (BOOL)localVideoIsPlaying;
- (void)moreButtonDidClick;
- (void)stopCurrentPlayingVideo;
- (void)playCellAtIndex:(long long)a0;
- (void)goToEditPage;
- (BOOL)isValidDataOfAsset:(id)a0;
- (void)shareLocalVideo:(id)a0;
- (void)shareImage:(id)a0;
- (void)shareCloudVideo:(id)a0;
- (void)shareCloudImage:(id)a0;
- (void)enterEditViewControllerWithAVAsset:(id)a0 completion:(id /* block */)a1;
- (void)enterEditPageViaCreaterWithImage:(id)a0;
- (id)createImagePublishModel;
- (id)createVideoPublishModel;
- (void)autoPlayOnFlagsChange;
- (void)stopPlayForIndex:(long long)a0;
- (void)configCell:(id)a0 withAsset:(id)a1;
- (void)autoPlayOnAnimationEnd:(id)a0 targetIndex:(long long)a1;
- (void)autoPlayOnAnimationEndForLocalAsset:(id)a0 targetIndex:(long long)a1;
- (void)autoPlayOnAnimationEndForCloudAsset:(id)a0 targetIndex:(long long)a1;
- (void)setCover;
- (BOOL)localVideoIsPaused;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (void)collectionView:(id)a0 didEndDisplayingCell:(id)a1 forItemAtIndexPath:(id)a2;
- (void)viewDidLayoutSubviews;
- (long long)preferredStatusBarStyle;
- (id)collectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (long long)collectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (void)collectionView:(id)a0 willDisplayCell:(id)a1 forItemAtIndexPath:(id)a2;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(BOOL)a0;
- (id)indexPathWithIndex:(long long)a0;
- (void)setupView;
- (id)currentCell;
- (void)setupFooter;
- (void)removeAsset;
- (void)showLoading;
- (void)back;

@end
