@class NSString;

@interface AWECodeGenSubtitleItemModel : AWEBaseDataModel

@property (nonatomic) long long modelID;
@property (nonatomic) long long complaintId;
@property (nonatomic) long long expire;
@property (copy, nonatomic) NSString *format;
@property (nonatomic) BOOL isAutoGenerated;
@property (copy, nonatomic) NSString *languageCode;
@property (nonatomic) int languageId;
@property (copy, nonatomic) NSString *language;
@property (nonatomic) long long subId;
@property (copy, nonatomic) NSString *translatorId;
@property (copy, nonatomic) NSString *url;
@property (copy, nonatomic) NSString *subVersion;

+ (id)JSONKeyPathsByPropertyKey;

- (void).cxx_destruct;

@end
