@class AWETabContainerSectionController, AWEChallengeDetailHeaderSectionController, AWEChallengeDetailBodySectionController, AWEBaseListSectionController, CAKModalTransitionDelegate, AWECommerceTapMaskView, AWEBaseWebViewController, NSString, AWEChallengeDetailFeedFactory, UIViewController, BDXPopupViewController, AWEChallengeDetailFilterSectionController;
@protocol AFDHorizontalSimilarChallengeSectionControllerProtocol, AWEStoryTransferToEditVCManagerProtocol, AWEChallengeDetailLiveWrapperSectionController, AWEAdChallengeLiveViewController, AWEChallengeDetailContainerViewControllerDelegate;

@interface AWEChallengeDetailContainerViewController : AWEBaseDetailContainerViewController <AWEUserMessage, AWERouterViewControllerProtocol, AWETabContainerSectionControllerDataSource, AWETabContainerSectionControllerDelegate, AWEChallengeDetailHeaderSectionControllerDelegate, AWEChallengeDetailFeedFactoryDelegate, AWEPageSheetPresentationObserving, AWEChallengeDetailFilterSectionControllerDelegate, CAKAlbumViewControllerDataSource, CAKAlbumViewControllerDelegate, AWEAdChallengeLiveDetailDelegate, BDXContainerLifecycleProtocol, AWEStickCollectionViewDelegate, BDChainLogNodeHostProtocol, AWEChallengeDetailContainerContextProtocol, AWEChallengeDetailContainerViewControllerProtocol, UIGestureRecognizerDelegate>

@property (retain, nonatomic) AWEChallengeDetailHeaderSectionController *headerSectionController;
@property (retain, nonatomic) AWEChallengeDetailBodySectionController *bodySectionController;
@property (retain, nonatomic) AWEChallengeDetailFilterSectionController *filterSectionController;
@property (retain, nonatomic) AWEBaseListSectionController<AWEChallengeDetailLiveWrapperSectionController> *liveSectionController;
@property (retain, nonatomic) AWEBaseListSectionController<AFDHorizontalSimilarChallengeSectionControllerProtocol> *horizontalSimilarSectionController;
@property (retain, nonatomic) AWETabContainerSectionController *tabSectionController;
@property (retain, nonatomic) AWEChallengeDetailFeedFactory *feedFactory;
@property (nonatomic) long long initialTabIndex;
@property (retain, nonatomic) UIViewController *selectedViewController;
@property (nonatomic) long long currentPreferredStyle;
@property (retain, nonatomic) CAKModalTransitionDelegate *transitionDelegate;
@property (nonatomic) BOOL shouldRefreshChallengeData;
@property (retain, nonatomic) id<AWEStoryTransferToEditVCManagerProtocol> transferToEditManager;
@property (nonatomic) BOOL isiCloudDownloading;
@property (nonatomic) double lastScrollViewContentOffsetY;
@property (nonatomic) BOOL isParticipateMission;
@property (retain, nonatomic) AWECommerceTapMaskView *tapMaskView;
@property (nonatomic) BOOL isTappedChallengePage;
@property (retain, nonatomic) AWEBaseWebViewController *lastCommerceWebViewController;
@property (retain, nonatomic) UIViewController<AWEAdChallengeLiveViewController> *adLiveViewController;
@property (nonatomic) double containerViewOriginFrame;
@property (nonatomic) BOOL isViewAppearing;
@property (retain, nonatomic) BDXPopupViewController *popupVC;
@property (nonatomic) long long liveSectionStartOrigin;
@property (weak, nonatomic) id<AWEChallengeDetailContainerViewControllerDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)startRecordComposerWithChallengeModel:(id)a0 extraInfo:(id)a1 commercialAnchorModel:(id)a2 logHost:(id)a3;
+ (void)p_transferValueWithKey:(id)a0 from:(id)a1 to:(id)a2;
+ (id)createComposeCameraComposerWithChallengeModel:(id)a0;
+ (id)createComposeInfiniEditorComposerWithChallengeModel:(id)a0;
+ (id)createComposeDataConfigWithChallengeModel:(id)a0;

- (void)container:(id)a0 didLoadFailedWithUrl:(id)a1 error:(id)a2;
- (BOOL)configWithRouterParamDict:(id)a0;
- (id)awe_naviBar;
- (void)awe_onReturnButtonClicked:(id)a0;
- (id)chainLogNodeParams;
- (BOOL)isChainLogGatewayNode;
- (id)awesst_enterFrom;
- (double)heightForSegmentedControl;
- (id)sectionControllerClassArray;
- (void)dataSourceDidCreateSectionController:(id)a0 forSectionViewModel:(id)a1;
- (BOOL)enableMemoryWarningHandling;
- (id)viewControllerForModel:(id)a0 index:(long long)a1;
- (double)heightForSectionController:(id)a0;
- (void)setupTabContentConfig:(id)a0;
- (id)segmentedControlForSectionController:(id)a0;
- (void)updateSegmentedControl:(id)a0 itemsArray:(id)a1;
- (void)tabContainerSectionController:(id)a0 didSelectItemAtIndex:(long long)a1 itemViewController:(id)a2 isByTap:(BOOL)a3;
- (void)shoot;
- (void)bindViewModel;
- (BOOL)shouldStickWithSubScrollView:(id)a0;
- (BOOL)enableStickCollectionView;
- (id)listViewConfigForAlbumViewController:(id)a0;
- (BOOL)albumViewControllerHiddenForFooter:(id)a0;
- (BOOL)albumViewControllerHiddenForSelectedAssetsView:(id)a0;
- (BOOL)albumViewControllerNeedFetchAlbumAssetsWhenClickNext:(id)a0;
- (BOOL)albumViewController:(id)a0 shouldSelectAlbumAsset:(id)a1;
- (void)albumViewController:(id)a0 didClickAlbumAssetCell:(id)a1;
- (id)albumViewControllerConfigForFooter:(id)a0;
- (void)albumViewController:(id)a0 didSelectAlbumAsset:(id)a1 sourceType:(long long)a2;
- (void)albumViewController:(id)a0 didClickNextButtonWithSourceType:(long long)a1 fetchedAlbumAssets:(id)a2;
- (void)albumViewController:(id)a0 updateBottomNextButtonWithButton:(id)a1 fromPreview:(BOOL)a2;
- (void)destroyLightMissionModel;
- (void)p_goToNextWithSelectedAssets:(id)a0;
- (void)onDiscoverButtonClicked:(id)a0;
- (void)emptyPagePrimaryButtonDidTap:(id)a0;
- (void)pageSheetPresentationWillBegin:(id)a0;
- (void)pageSheetDismissalDidEnd:(id)a0 completed:(BOOL)a1;
- (void)leaveFullScreenLiveRoomAndForceReloadHeaderSection:(BOOL)a0;
- (void)disableSlideSlip;
- (void)startTimingForTrack;
- (void)onActionButtonClicked:(id)a0;
- (void)handleBottomTipShowNotice;
- (void)handleBottomTipHideNotice;
- (void)_onShareButtonClicked_IMP:(id)a0;
- (void)onShareBtnClicked:(id)a0;
- (void)handleAppBecomeActive;
- (void)trackStaytime;
- (void)p_trackSearchBarShowEvent;
- (void)addCornerMaskView;
- (void)updateContainerOffset:(BOOL)a0;
- (void)closeChallengeDetailPage;
- (void)openSharePanelWithNotification:(id)a0;
- (void)setupPageTrackAttributes;
- (void)addCNYMaskViewForRetainWindow;
- (void)tryPopupSharePanel;
- (BOOL)openRetainWindow;
- (double)tabSectionOriginY;
- (void)topSectionHeightChanged;
- (double)stickOffsetY;
- (void)updateBackgroundColorView;
- (id)viewControllerForItem:(id)a0 info:(id)a1;
- (BOOL)shouldUseCommerceNewStyle;
- (id)getCommerceModeColor;
- (id)segmentedControlTitleWithModel:(id)a0 index:(long long)a1;
- (void)controllWebTabContainerVideo:(id)a0;
- (BOOL)isCurrentlyLightStyle;
- (void)changeNaviBarTheme:(long long)a0;
- (void)jumpOtherPageIfNeed;
- (void)animateNaviBarWhenScrollViewDidScroll:(id)a0;
- (void)adCoverLinkHandleDidEndDraggingEvent:(id)a0 willDecelerate:(BOOL)a1;
- (void)adCoverLinkHandleDidEndDeceleratingEvent:(id)a0;
- (void)tryEnterFullScreenAdLiveRoomWithScrollView:(id)a0;
- (void)notifyViewController:(id)a0 withInfo:(id)a1;
- (void)notifyViewController:(id)a0 event:(id)a1 reactID:(id)a2;
- (void)onFavoriteButtonClicked:(id)a0;
- (void)adLiveViewControllerHandlePan:(id)a0;
- (void)addGlobalPreviewWaterMarkViewIfNeed;
- (void)updateAdLiveControllerIfNeed:(id)a0;
- (void)updateTitleWithResponse:(id)a0;
- (void)initSubChallengeIfNeeded:(id)a0;
- (void)addShootActionToImageUponCamera;
- (void)updateCommerceChallengeBGColorIfNeeded;
- (void)updateCommerceLotteryGiftIfNeed:(id)a0;
- (void)updateTopImageViewAlpha:(double)a0;
- (void)animateNaviBarHalfScreenWhenScrollViewDidScroll:(id)a0;
- (void)animateNaviBarFullScreenWhenScrollViewDidScroll:(id)a0;
- (void)updateTopContentAlpha:(double)a0;
- (void)animateCommerceNaviBarFullScreenWhenScrollViewDidScroll:(id)a0;
- (BOOL)isCurrentlyDarkStyle;
- (void)animateNaviBarFullScreenVSWhenScrollViewDidScroll:(id)a0;
- (void)animateNaviBarFullScreenHasTopImageViewWhenScrollViewDidScroll:(id)a0;
- (void)animateNaviBarFullScreenNoTopImageViewWhenScrollViewDidScroll:(id)a0;
- (void)updateContentAlphaWithContentOffsetY:(double)a0;
- (void)animateSearchBarFullScreenHasTopImageViewWhenScrollViewDidScroll:(id)a0;
- (void)onSearchButtonClicked;
- (id)addFlowerParamsToSchema:(id)a0;
- (void)headerSectionController:(id)a0 didSelectVideoAtIndex:(long long)a1;
- (void)headerSectionControllerDidTapActionButton:(id)a0;
- (void)headerSectionControllerTopImageDidShow:(id)a0 image:(id)a1 gradientImage:(id)a2;
- (void)headerSectionControllerTopImageDidTapped;
- (void)feedViewControllerDidScrollUp;
- (void)feedViewControllerDidScrollDown;
- (void)filterSectionController:(id)a0 didChangeSortType:(unsigned long long)a1;
- (id)calculateZoomTransitionStartViewInHeaderWithIndex:(long long)a0;
- (id)createComposeModelWithModel:(id)a0 extra:(id)a1;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (void)viewDidLayoutSubviews;
- (long long)preferredStatusBarStyle;
- (id)init;
- (void)scrollViewWillBeginDragging:(id)a0;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (void)fetchData;
- (void)viewWillAppear:(BOOL)a0;
- (void)scrollViewDidScroll:(id)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)setupUI;
- (void)handleAppWillResignActive;
- (void)setupCollectionView:(id)a0;
- (void)setupNavigationBar;
- (void)closeButtonTapped;
- (id)challengeID;

@end
