@class AWEPOIContentItemModel, AWEDitoPOIFavoriteGrouponCellComponentView_New, AWEPOISpuModel, NSDictionary, UIColor, AWEDitoPOIFavoritePageContext, NSString, AWEPOILifeCollectTagModel, NSAttributedString, NSArray, AWEAwemeModel, NSNumber, UIImage;

@interface AWEDitoPOIFavoriteGrouponCellComponentViewModel_New : DitoComponentViewModel <AWEPOISyncFeedExtensionGetModelProtocol, AWEPOITagsViewDataSource>

@property (retain, nonatomic) AWEPOISpuModel *spuModel;
@property (copy, nonatomic) NSDictionary *spuInfoDict;
@property (nonatomic) double componentWidth;
@property (nonatomic) long long poiCount;
@property (nonatomic) BOOL isCommonExchangeCoupon;
@property (weak, nonatomic) AWEDitoPOIFavoritePageContext *context;
@property (retain, nonatomic) NSNumber *inTheSameCity;
@property (nonatomic) BOOL hasTrackShow;
@property (copy, nonatomic) NSDictionary *trackData;
@property (weak, nonatomic) AWEDitoPOIFavoriteGrouponCellComponentView_New *componentView;
@property (copy, nonatomic) NSArray *coverImageArray;
@property (copy, nonatomic) NSString *grouponName;
@property (retain, nonatomic) UIColor *titleColor;
@property (nonatomic) BOOL invalid;
@property (retain, nonatomic) AWEPOIContentItemModel *poiInfoModel;
@property (copy, nonatomic) NSString *poiNameText;
@property (copy, nonatomic) NSString *flashSaleCountDownTimeText;
@property (retain, nonatomic) UIColor *poiNameColor;
@property (retain, nonatomic) UIImage *houseIconImage;
@property (retain, nonatomic) UIColor *distanceColor;
@property (copy, nonatomic) NSString *pricePrefixText;
@property (copy, nonatomic) NSString *price;
@property (retain, nonatomic) NSString *priceSuffixText;
@property (copy, nonatomic) NSString *timesText;
@property (retain, nonatomic) NSAttributedString *originPriceAttr;
@property (copy, nonatomic) NSString *discountText;
@property (copy, nonatomic) NSString *soldCountText;
@property (copy, nonatomic) NSString *cornerText;
@property (copy, nonatomic) NSString *collectTimeText;
@property (nonatomic) BOOL isFrameHighlight;
@property (retain, nonatomic) AWEAwemeModel *aweme;
@property (copy, nonatomic) NSString *videoSource;
@property (nonatomic) BOOL isVideoCollect;
@property (nonatomic) BOOL hasBgAniCompleted;
@property (retain, nonatomic) AWEPOILifeCollectTagModel *priceReductionTagModel;
@property (retain, nonatomic) AWEPOILifeCollectTagModel *arrivedTagModel;
@property (retain, nonatomic) AWEPOILifeCollectTagModel *flashSaleTagModel;
@property (retain, nonatomic) NSString *btmString;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)getAwemeModel;
- (double)largeModeSizeWithFont:(double)a0;
- (id)componentReuseIdentifier;
- (struct CGSize { double x0; double x1; })componentSizeWithMaxWidth:(double)a0;
- (id)tagsView:(id)a0 tagViewForItemAtIndex:(long long)a1;
- (BOOL)shouldShowLargeMode;
- (double)largeModeWithMargin:(double)a0;
- (BOOL)shouldShowArrivedTag;
- (BOOL)shouldShowPriceReductionTag;
- (BOOL)shouldShowCollectTime;
- (id)trackParamsForAutoTrackWithEventName:(id)a0 params:(id)a1;
- (void)openFeed;
- (void)componentViewDidCompleteShow;
- (id)syncFeedManager;
- (void)trackClickWithAreaString:(id)a0;
- (id)priceString:(long long)a0;
- (BOOL)shouldShowHouseIcon;
- (BOOL)shouldShowPricePrefix;
- (BOOL)shouldShowTimes;
- (BOOL)shouldShowOriginPrice;
- (BOOL)shouldShowDiscountTag;
- (BOOL)shouldShowSoldCount;
- (BOOL)shouldShowFlashSaleTag;
- (void)handleTapContainerWithAreaString:(id)a0;
- (id)configView:(id)a0 withTagModel:(id)a1;
- (long long)numberOfItems;
- (void).cxx_destruct;
- (id)initWithNode:(id)a0;
- (void)trackEvent:(id)a0;
- (BOOL)shouldShowSubtitle;

@end
