@class NSTimer, NSString, NSArray, IESECMallDeviceAdapterInfo, NSMutableDictionary, NSDictionary, IESECMallMainViewController, IESECMallErrorPageView;
@protocol AWEECFullScreenMallDelegate;

@interface AWEECMallFullScreenViewController : UIViewController <IESECMallMainViewControllerDelegate>

@property (retain, nonatomic) IESECMallMainViewController *mallMainVC;
@property (retain, nonatomic) NSMutableDictionary *currentRouterParams;
@property (retain, nonatomic) IESECMallDeviceAdapterInfo *deviceAdapterInfo;
@property (copy, nonatomic) NSString *openTime;
@property (retain, nonatomic) NSTimer *stayTimer;
@property (nonatomic) BOOL isReportPageView;
@property (retain, nonatomic) NSMutableDictionary *btmCache;
@property (nonatomic) BOOL isSample;
@property (copy, nonatomic) NSDictionary *mallLynxConfig;
@property (nonatomic) double leaveTimeInterval;
@property (retain, nonatomic) NSArray *timeoutRefreshPageNameArray;
@property (nonatomic) double timeoutRefreshGYLTime;
@property (copy, nonatomic) NSString *pageTheme;
@property (nonatomic) BOOL isViewVisible;
@property (nonatomic) BOOL needRefreshDeviceLayout;
@property (retain, nonatomic) IESECMallErrorPageView *exceptionPageView;
@property (weak, nonatomic) id<AWEECFullScreenMallDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (Class)aAWEPadModuleAdapterClass;

- (id)enterFrom;
- (id)aAWEPadModuleAdapter;
- (id)routerParams;
- (BOOL)enableSample;
- (id)initWithRouterParamDict:(id)a0;
- (void)buildUI;
- (void)handleAppBecomeActive;
- (void)setBcmPageParams;
- (void)mallChannelInnerTheme:(id)a0;
- (void)configBtmTrackerV2;
- (void)reportPageView;
- (void)setStayDurationCountDownTimer;
- (id)globalPropsExtra;
- (void)mallDidFinishRender:(unsigned long long)a0;
- (void)reportPageRefresh;
- (void)needRefreshSkinInfo:(id)a0;
- (void)closeHalfMall;
- (double)mallContainerTopMargin;
- (BOOL)isHalfState;
- (id)mallBTMPageIdentifier;
- (void)dismissExceptionView;
- (void)showPageException:(long long)a0;
- (void)trackMallPreloadEnterWithParams:(id)a0;
- (BOOL)enableBtmCache;
- (void)mallReportSimple:(id)a0 withParams:(id)a1 isSample:(BOOL)a2;
- (void)mallReport:(id)a0 enterNewPage:(BOOL)a1;
- (void)mallReport:(id)a0 enterNewPage:(BOOL)a1 isSample:(BOOL)a2;
- (void)mallReport:(id)a0;
- (id)mallCustomHybridMonitorContext;
- (void)reportStayDuration:(long long)a0;
- (void)configBtmTracker;
- (BOOL)isUseNewThemeSetting;
- (void)setupDeviceAdapterInfo;
- (void)updateThemeStyle;
- (void)refreshDeviceLayoutIfNeeded;
- (void)stopStayDurationCountDownTimer;
- (long long)mallStayDuration;
- (void)handleStayDuration;
- (BOOL)isInNewThemeOptTestGroup;
- (id)rootGlobalPropsExtra;
- (void)mainViewConrtroller:(id)a0 mallReport:(id)a1 enterNewPage:(BOOL)a2;
- (void)mainViewConrtroller:(id)a0 finishRefreshMainList:(BOOL)a1 isCacheData:(BOOL)a2;
- (void)mainViewConrtroller:(id)a0 isShowingLoadingView:(BOOL)a1;
- (BOOL)mainViewControllerShouldShowHeaderView:(id)a0;
- (id)mainViewControllerUseCustomHeaderView:(id)a0;
- (id)globalPropsExtraForMainViewController:(id)a0;
- (id)rootGlobalPropsExtraForMainViewController:(id)a0;
- (id)currentRequestContextForMainViewController:(id)a0 withTabId:(id)a1;
- (BOOL)isADEventReportForbidPageChange;
- (id)hostBTMABStr;
- (id)mallReferString;
- (void)interfaceOrientationAdaptToIfNeed:(long long)a0;
- (void)requestMallClientAiPrefetchApis:(double)a0 message:(id)a1 completion:(id /* block */)a2;
- (BOOL)mallNeedRotateOnPad;
- (void).cxx_destruct;
- (BOOL)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })a0 withTransitionCoordinator:(id)a1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)handleAppWillResignActive;
- (id)pageName;

@end
