@class NSArray, NSMutableDictionary, NSString;
@protocol AWEFeedAdPitayaReRankController, AWEFeedDolphinAdapter, AWEFeedTrackControllerProtocol;

@interface AWEFeedCommerceModuleController : AWEBaseController <AWEFeedControllerProtocol, AWEDolphinSyncDataDelegate, AWEFeedTrackControllerListenerProtocol, AWEFeedPlayControlServiceListenerProtocol>

@property (retain, nonatomic) id<AWEFeedAdPitayaReRankController> adPitayaReRankController;
@property (nonatomic) long long latestShowFeedIndex;
@property (retain, nonatomic) NSMutableDictionary *bindings;
@property (nonatomic) struct CGPoint { double x; double y; } similarAdContentOffset;
@property (weak, nonatomic) id<AWEFeedTrackControllerProtocol> feedTrackController;
@property (retain, nonatomic) NSMutableDictionary *marketGapInfo;
@property (copy, nonatomic) NSArray *marketTypeArr;
@property (retain, nonatomic) id<AWEFeedDolphinAdapter> dolphinAdapter;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)cellViewControllerDidRenderFirstFrame:(id)a0;
- (long long)currentAwemeIndex;
- (void)refreshCompletion:(id)a0 error:(id)a1 needAnimation:(BOOL)a2;
- (void)beginLoadMore;
- (void)beginRefresh;
- (void)onAwemeDeleted:(id)a0 isLiveFinish:(BOOL)a1 isDislike:(BOOL)a2 index:(unsigned long long)a3 isLiveEnded:(BOOL)a4;
- (void)viewDidLoadAfterTableviewSetup;
- (void)tableView:(id)a0 didEndDisplayingCellBeforeReset:(id)a1 forRowAtIndexPath:(id)a2;
- (void)willConfigureCell:(id)a0 withModel:(id)a1 atIndexPath:(id)a2;
- (void)scrollViewDidScrollEndWithActive;
- (void)didPlayCell:(id)a0 indexPath:(id)a1 currentModel:(id)a2;
- (void)videoControllerWillStartNextLoop:(id)a0;
- (id)requestParamForCommercePitayaReRank;
- (void)trackPlaytimePredictWithState:(id)a0 params:(id)a1;
- (id)makeAwemeDataDict:(id)a0;
- (BOOL)validBeforeExecuteReRank;
- (id)reRankFeedStreamWithDeleteIndexes:(id)a0 insertIndexes:(id)a1 insertModels:(id)a2 trackerParams:(id)a3;
- (id)askForSatiParamsForPitayaCommerce;
- (void)asyncRequestAdWithParams:(id)a0 shouldRequest:(BOOL)a1 lastAsyncRequestTime:(double)a2 innerTrackParams:(id)a3 completion:(id /* block */)a4;
- (id)transferModeltoDataDict:(id)a0 floor:(long long)a1 dataType:(long long)a2;
- (id)paramsForTrackEventType:(unsigned long long)a0 initialContextParams:(id)a1;
- (void)didTrackEventWithTrackEventType:(unsigned long long)a0 initialContextParams:(id)a1 allTrackParams:(id)a2;
- (void)adDataFeedChecker:(id)a0;
- (id)makeAwemeActionDataDict:(id)a0;
- (id)reRankFeedStreamWithDeleteIndexes:(id)a0 insertIndexes:(id)a1 insertModels:(id)a2 invokeOptimize:(BOOL)a3 needFixFloor:(BOOL)a4 extraParams:(id)a5;
- (void)pitayaReRankResultDeDuplicateIfNeedeEeventName:(id)a0 extraParam:(id)a1;
- (void)pitayaReRankResultDeDuplicateLiveIfNeedeEeventName:(id)a0 extraParam:(id)a1;
- (void)runDolphinAIModelTask:(id)a0 model:(id)a1;
- (void)monitorDuplicateItemWithRemoveArr:(id)a0 insertArr:(id)a1;
- (void)trackGroupTraceParamsIfNeeded:(id)a0 curIndex:(long long)a1 beforeList:(id)a2 afterList:(id)a3 operateType:(long long)a4 triggerSource:(long long)a5 isDolphin:(BOOL)a6;
- (void)trackHolmesPitayaReRankInfoWithBeforeList:(id)a0 afterList:(id)a1 curIndex:(long long)a2 triggerSource:(long long)a3;
- (void)similarAdTwoAsyncRequestAdWithParams:(id)a0 shouldRequest:(BOOL)a1 lastAsyncRequestTime:(double)a2 innerTrackParams:(id)a3 completion:(id /* block */)a4;
- (void)normalFeedAsyncRequestAdWithParams:(id)a0 shouldRequest:(BOOL)a1 lastAsyncRequestTime:(double)a2 innerTrackParams:(id)a3 completion:(id /* block */)a4;
- (void)handelRequest:(id)a0 startRequestmodel:(id)a1 startRequestIdx:(long long)a2 insertAds:(id)a3 requestTime:(double)a4 asyncGetAdTs:(double)a5 getSameAdType:(long long)a6 innerTrackParams:(id)a7;
- (id)tryGetSimilarAdManager;
- (void)asyncRequestResultNotify:(BOOL)a0 response:(id)a1 originModel:(id)a2;
- (BOOL)enablePitayaReRankStrategy;
- (BOOL)enableFakePitayaReRankStrategy;
- (void)reportUnshowDataFromCloseApp;
- (void)didPreloadNextCell:(long long)a0;
- (void)setupPollenFeatureProvider;
- (void)setupAdPitayaReRankController;
- (void)addCommonParamsForROI2IfNeededWithAweme:(id)a0;
- (void)tryToRunClientAIModelPredictIfNeededWithIndexPath:(id)a0;
- (void)updateUnshowFeedCacheData:(long long)a0;
- (void)tryPreloadAdWebView;
- (void)trackMarketingGapInfoWithModel:(id)a0 curIndex:(long long)a1;
- (BOOL)unSetupAdPitayaReRankController;
- (id)fetchIdList:(id)a0;
- (BOOL)isSameArrWithArr1:(id)a0 arr2:(id)a1;
- (id)rangeListWithList:(id)a0 idx:(unsigned long long)a1;
- (BOOL)hasDuplicateStrings:(id)a0;
- (void)tryToRunAdComponentShowModelPredictIfNeededWithIndexPath:(id)a0;
- (void)tryToRunAdQuickSlideModelPredictIfNeededWithIndexPath:(id)a0;
- (void)tryToRunAdVolumeAdjustModelPredictIfNeededWithIndexPath:(id)a0;
- (void)tryToRunAdCTRModelPredictIfNeededWithIndexPath:(id)a0;
- (void)tryToRunAdLandingPageBrightnessPredictIfNeededWithIndexPath:(id)a0;
- (void)tryToRunAdMultiStrategyIfNeededWithIndexPath:(id)a0;
- (void)trackStrategyWithModel:(id)a0 strategyName:(id)a1 result:(long long)a2 strategyType:(unsigned long long)a3;
- (id)recentFiveListWithIndex:(long long)a0;
- (void)trackAdComponentPredictWithState:(id)a0 params:(id)a1;
- (void)trackStrategyWithModel:(id)a0 strategyName:(id)a1 result:(long long)a2 extra:(id)a3 strategyType:(unsigned long long)a4;
- (void)trackQuickSlidePredictWithState:(id)a0 params:(id)a1;
- (void)increaseFeedAdVideoCacheWhenSlowSlideWithModel:(id)a0 isForce:(BOOL)a1;
- (void)trackAdCTRModelWithState:(id)a0 params:(id)a1;
- (id)fetchAwemeTypeInfo:(id)a0;
- (void)updateMarketGapInfoBeforeTrack:(long long)a0;
- (long long)lastTypeAwemeGap:(id)a0 curIndex:(long long)a1;
- (long long)tagFromAweme:(id)a0;
- (id)paramsForEnterPersonalDetail;
- (id)paramsForSlideWithTrackEventType:(unsigned long long)a0 initialContextParams:(id)a1;
- (id)isToModelFromAd:(id)a0;
- (void)didTrackEnterPersonalDetail;
- (id)shouldPreventPlayCell:(id)a0 indexPath:(id)a1;
- (id)shouldPreventPlayIfActive;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (id)init;
- (void)tableView:(id)a0 willDisplayCell:(id)a1 forRowAtIndexPath:(id)a2;
- (void)viewWillAppear:(BOOL)a0;
- (void)scrollViewDidScroll:(id)a0;
- (id)currentDataSource;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)scrollViewDidEndScrollingAnimation:(id)a0;
- (void)viewWillDisappear:(BOOL)a0;

@end
