@class NSString, UIViewController;
@protocol AWEHPChannelControllerConfigProtocol, AWEFeedTabItemViewControllerProtocol, AWENewNearbyViewControllerProtocol;

@interface AWEFeedGrouponChannelController : NSObject <AWENearbyThemeStyleProtocol, AWENearbyBubbleAblityProtocol, AWENearbyTabDotAblityProtocol, AWENearbyChannelContextAblityProtocol, AWENearbyVcProtocol, AWENearbyChannelAbilityProtocol, AWENearbyTabForwardAblityProtocol, AWEHPChannelControllerProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<AWEHPChannelControllerConfigProtocol> config;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<AWEHPChannelControllerConfigProtocol> config;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) UIViewController<AWEFeedTabItemViewControllerProtocol, AWENewNearbyViewControllerProtocol> *contentVC;
@property (nonatomic) BOOL isChannelLoaded;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<AWEHPChannelControllerConfigProtocol> config;

- (void)cancelRefresh;
- (void)refreshWithType:(long long)a0 completion:(id /* block */)a1;
- (void)hideBubbleWithCompletion:(id /* block */)a0;
- (BOOL)verticalPanGestureRecognizerShouldBegin:(id)a0;
- (BOOL)channelRefreshWithModel:(id)a0 completion:(id /* block */)a1;
- (void)channelEnterWithModel:(id)a0;
- (void)channelLeaveWithModel:(id)a0;
- (void)channelTopTabContainerDidAppear;
- (void)channelTopTabContainerDidDisappear;
- (void)showBadgeWithModel:(id)a0 showCallBack:(id /* block */)a1 hideCallBack:(id /* block */)a2 downgradeCallBack:(id /* block */)a3;
- (id)getCustomTrackParamsWithTrackInfo:(id)a0;
- (id)getPrePluginControllers;
- (id)getNetworkQualityParams;
- (void)channelTopTabWillBeginDragging;
- (void)channelTopTabDidEndScroll;
- (void)channelDidLoadWithType:(unsigned long long)a0;
- (void)channelViewWillAppear;
- (void)channelViewDidDisappear;
- (void)channelTrackRefreshWithModel:(id)a0;
- (void)channelTopSegmentControllHidden:(BOOL)a0;
- (BOOL)channelReleaseContentViewController:(id)a0;
- (id)getContentViewController;
- (BOOL)isTopTabSelected;
- (void)generateContentVCIfNeed;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })topContainerFrame;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })tabSegmentViewRect;
- (void)tabShowPinTopComponentWithComponentID:(id)a0 componentText:(id)a1 extraTrackParams:(id)a2 completion:(id /* block */)a3;
- (void)tabShowPinTopComponentWithPinTopModel:(id)a0 extraTrackParams:(id)a1 showCompletion:(id /* block */)a2 pinTopCompletion:(id /* block */)a3;
- (void)tabGeneratePinTopTaskWithComponentID:(id)a0 extraTrackParams:(id)a1 completion:(id /* block */)a2;
- (void)checkCanPinTopTabWithCompletion:(id /* block */)a0;
- (void)cityHasChangedAndNeedRefresh:(BOOL)a0 animated:(BOOL)a1 nearbyTitle:(id)a2;
- (void)contentOffsetChangedWithNewOffset:(struct CGPoint { double x0; double x1; })a0 oldOffset:(struct CGPoint { double x0; double x1; })a1 isUserTriggered:(BOOL)a2;
- (void)showNearbyBubbleWithModel:(id)a0 completion:(id /* block */)a1 clickCallback:(id /* block */)a2 dismissCallback:(id /* block */)a3;
- (void)updateNearbyTopBarBadgeSceneStyle:(unsigned long long)a0;
- (void)updateNearbyTopBarThemeIsLight:(BOOL)a0;
- (BOOL)isTopTabLoaded;
- (void)scrollToTopTabSegmentWithChannelId:(id)a0 animated:(BOOL)a1;
- (BOOL)canShowTabDot;
- (double)topTabSegmentShowPercentWithChannelId:(id)a0;
- (void)showNearbyPinTopWithComponentID:(id)a0 extraTrackParams:(id)a1 completion:(id /* block */)a2;
- (void)removeNearbyDotWithCompletion:(id /* block */)a0;
- (void)updateNearbyBottomBarThemeIsLight:(BOOL)a0;
- (id)generateChannelBubbleWithNearbyModel:(id)a0;
- (void)showXtabNearbyBubbleWithModel:(id)a0 completion:(id /* block */)a1 clickCallback:(id /* block */)a2 dismissCallback:(id /* block */)a3;
- (void)hideXTabBubbleWithCompletion:(id /* block */)a0;
- (id)generaTopBarDotModelWithNearbyTabModel:(id)a0;
- (void)channelInitConfig;
- (void)hideRightEntrance;
- (void)showRightEntrance;
- (struct CGPoint { double x0; double x1; })bottomCenterOfTopTabSegmentWithChannelId:(id)a0;
- (void).cxx_destruct;
- (long long)tabIndex;
- (id)tabTitle;
- (id)initWithConfig:(id)a0;
- (void)addObservers;

@end
