@class AWEFeedMultiTabSegmentedViewUIConfig, UITapGestureRecognizer, MASConstraint, NSMutableArray, UIView, UIColor, NSString, AWEFeedMultiTabSegmentedMaskView, AWEFeedMultiTabSelectedContainerView, AWEMultiTabNavigationArrowView, DUXLoadingParticleView, NSArray, AWEHPTopTabItemView, AWEHPSegmentControlScrollView;
@protocol AWEFeedSegmentedControlDelegate;

@interface AWEFeedMultiTabSegmentedControl : UIView <AWEHPTopTabItemViewDelegate, UIScrollViewDelegate, UIGestureRecognizerDelegate, AWEFeedSegmentedControlProtocol>

@property (retain, nonatomic) AWEFeedMultiTabSelectedContainerView *selectedLineContainerView;
@property (nonatomic) BOOL isTapped;
@property (retain, nonatomic) NSArray *items;
@property (nonatomic) long long mainTabIndex;
@property (retain, nonatomic) AWEFeedMultiTabSegmentedViewUIConfig *config;
@property (nonatomic) double itemDistance;
@property (nonatomic) BOOL isLightTheme;
@property (retain, nonatomic) UIView *container;
@property (nonatomic) unsigned long long dotSceneStyle;
@property (retain, nonatomic) AWEHPSegmentControlScrollView *multiTabSegmentedControlScollWrapperView;
@property (retain, nonatomic) AWEFeedMultiTabSegmentedMaskView *maskContainerView;
@property (retain, nonatomic) NSMutableArray *tabIdentiferList;
@property (nonatomic) double rightNavigationArrowViewTargetAlpha;
@property (nonatomic) BOOL isScrollToRightTriggeredByClickArrowImage;
@property (nonatomic) BOOL canShowRightNavigationArrowView;
@property (retain, nonatomic) MASConstraint *iPadWrapperViewWidthEqual;
@property (retain, nonatomic) MASConstraint *iPadWrapperViewWidthLess;
@property (nonatomic) BOOL isAlreadyScrolled;
@property (retain, nonatomic) UIColor *selectedDarkColor;
@property (retain, nonatomic) UIColor *selectedLightColor;
@property (retain, nonatomic) UIColor *unSelectedDarkColor;
@property (retain, nonatomic) UIColor *unSelectedLightColor;
@property (retain, nonatomic) NSArray *redDotWhiteList;
@property (retain, nonatomic) DUXLoadingParticleView *refreshLoadingView;
@property (weak, nonatomic) AWEHPTopTabItemView *refreshItemView;
@property (nonatomic) BOOL isAbsorbScrolling;
@property (nonatomic) struct CGPoint { double x; double y; } lastBeginDragOffset;
@property (nonatomic) BOOL isViewOptEnable;
@property (retain, nonatomic) UITapGestureRecognizer *rightArrowGest;
@property (readonly, nonatomic) long long selectedIndex;
@property (nonatomic) long long previousSelectedIndex;
@property (copy, nonatomic) id /* block */ indexSingleClickBlock;
@property (copy, nonatomic) id /* block */ indexRepeatedClickBlock;
@property (readonly, nonatomic) NSMutableArray *itemViews;
@property (weak, nonatomic) UIView *liveView;
@property (retain, nonatomic) AWEMultiTabNavigationArrowView *rightNavigationArrowView;
@property (copy) id /* block */ tabItemTapGestureRecognizerShouldReceiveTouchBlock;
@property (copy) id /* block */ tabItemTapGestureRecognizerStateChangedBlock;
@property (copy, nonatomic) id /* block */ rightArrowTapGestureRecognizerShouldReceiveTouchBlock;
@property (copy, nonatomic) id /* block */ didRightArrowClicked;
@property (weak, nonatomic) id<AWEFeedSegmentedControlDelegate> delegate;
@property (nonatomic) BOOL launchLanding;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)scrollViewDidEndScroll:(id)a0;
- (id)generateLineView;
- (id)followRedDotTrackString;
- (long long)followRedDotCount;
- (void)buildUI;
- (void)replaceItem:(id)a0 atIndex:(long long)a1;
- (void)slidingControllerDidScroll:(id)a0 isFigureDragging:(BOOL)a1;
- (void)updateMaskLayer;
- (void)p_buildSegmentItemView;
- (double)bottomLineOffset;
- (void)tab:(id)a0 changeToSelected:(BOOL)a1 animated:(BOOL)a2 index:(long long)a3;
- (void)segmentedControlTapped:(long long)a0;
- (void)repeatTapIndex:(long long)a0;
- (void)configTextColor;
- (BOOL)isSlidable;
- (void)itemView:(id)a0 didSingleTapWithGestureRecognizer:(id)a1;
- (BOOL)itemView:(id)a0 singleTapGestureRecognizer:(id)a1 shouldReceiveTouch:(id)a2;
- (BOOL)isFixRedDotMisplace;
- (void)feedSegmentItemViewDifferentiationComplete:(id)a0;
- (void)changeTheme:(BOOL)a0 withLeftIndex:(long long)a1 rightIndex:(long long)a2 progress:(double)a3;
- (void)scrollMultiTabSegmentedControlToSelected;
- (void)showRefreshAnimationAtIndex:(long long)a0;
- (void)hideRefreshAnimation;
- (float)segmentItemViewShowPercentageAtIndex:(long long)a0;
- (void)removeAllBubbles;
- (BOOL)isRedDotExceedMaxWidthWithContent:(id)a0 tabIndex:(long long)a1;
- (void)updateTopTabItem:(id)a0 atIndex:(long long)a1 animeted:(BOOL)a2;
- (void)updateIndicatorIconAlphaWithIndex:(long long)a0;
- (void)updateIndicatorIconRotationWithIndex:(long long)a0;
- (void)updateBadgeSceneStyle:(unsigned long long)a0;
- (void)updateWithTooBrightOptConfig:(id)a0;
- (void)reloadTopTabItems:(id)a0 selectedIndex:(long long)a1;
- (void)scrollSegmentedControlItemViewToIndex:(unsigned long long)a0 animated:(BOOL)a1;
- (struct CGPoint { double x0; double x1; })segmentItemViewBottomCenterAtIndex:(long long)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })segmentItemViewRectAtIndex:(long long)a0;
- (id)getItemInfoAtIndex:(long long)a0;
- (BOOL)isRightBackArrowShowing;
- (long long)needDowngradeRedDotWithIndex:(long long)a0;
- (void)hideRedDotAtIndex:(long long)a0;
- (id)showRedDotAtIndex:(long long)a0 withCount:(long long)a1 withAnimationType:(unsigned long long)a2;
- (id)showRedDotAtIndex:(long long)a0 withText:(id)a1 withAnimationType:(unsigned long long)a2;
- (id)showRedDotAtIndex:(long long)a0 withAnimationType:(unsigned long long)a1;
- (id)segmentItemViewAtIndex:(long long)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getTopBarActuallyVisibleRect;
- (double)tabFloat:(double)a0;
- (id)redDotAtIndex:(long long)a0;
- (void)scrollMultiTabSegmentedControlToRight;
- (BOOL)redDotDidShow:(long long)a0;
- (void)setSegmentedControlDelegate:(id)a0;
- (void)hpUpdateSelectedIndex:(long long)a0 animated:(BOOL)a1 tapped:(BOOL)a2 isByUserTab:(BOOL)a3;
- (void)p_updateItems:(id)a0;
- (void)bindScrollWrapperView;
- (void)didChangeStatusBarOrientation:(id)a0;
- (void)buildScrollView;
- (void)setupMultiTabUI;
- (void)addRightNavigationArrowViewIfNeeded;
- (void)selectedLineShadowRadius:(double)a0 shadowOpacity:(double)a1 shadowOffsetX:(double)a2 shadowOffsetY:(double)a3 shadowAlpha:(double)a4;
- (void)didRightNavigationArrowClicked;
- (double)rightNavigationArrowSize;
- (void)singleTapIndex:(long long)a0;
- (BOOL)isChangePreviousIndexNegativeAnimated;
- (void)layoutSelectedLineViewWithIndex:(long long)a0;
- (BOOL)isTabVisibleInFirstPageWithIndex:(long long)a0;
- (void)scrollSegmentedControlItemViewToCenter:(unsigned long long)a0;
- (BOOL)isTabVisibleByDefineWithIndex:(long long)a0;
- (double)selectLineWidth;
- (void)updateSelectedContainerViewWithItem:(id)a0;
- (double)p_calculateOffsetWithIndex:(unsigned long long)a0;
- (void)updateSelectViewShadowPathWithProgress:(double)a0;
- (void)setUpSelectedLineViewColorWithItem:(id)a0;
- (void)new_updateSelectedLineWhenSlidingDidScroll:(id)a0 isFigureDragging:(BOOL)a1;
- (void)updateSelectedLineWhenSlidingDidScroll:(id)a0 isFigureDragging:(BOOL)a1;
- (BOOL)showDifferentiationLine;
- (BOOL)selectedLineViewIsDifferentiation:(id)a0;
- (void)updateSelectViewShadowPath:(BOOL)a0;
- (unsigned long long)getBadgeSceneStyleWithFCSceneStyle:(unsigned long long)a0;
- (id)p_getTextColorWithLeftIndex:(long long)a0 rightIndex:(long long)a1 progress:(double)a2;
- (void)updateItemRedDotWithIndex:(long long)a0;
- (void)updateMainTabWithItems:(id)a0;
- (id)p_getLabelShadowColor;
- (double)selectedLineHeight;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getRectInView:(id)a0 withItemView:(id)a1;
- (void)scrollWrapperViewScrollToOffset:(double)a0 animated:(BOOL)a1;
- (void)updateRightNavigationArrowWithAlpha:(double)a0;
- (double)p_getBackButtonOffset;
- (double)calculateRightNavigationArrowAlphaWithContentOffset:(double)a0;
- (void)dynamicUpdateMaskLayerFrameForNewLayout;
- (void)p_scrollSegmentedControlItemViewToIndex:(unsigned long long)a0 animated:(BOOL)a1;
- (double)p_calculateAdsorbOffsetWithIndex:(unsigned long long)a0;
- (void)p_tryAdsorbToRight;
- (void)updateRightNavigationArrowWithContentOffset:(double)a0;
- (double)tabVisibilityThreshold;
- (id)initWithItems:(id)a0 defaultSelectedIndex:(long long)a1 newConfig:(id)a2;
- (double)p_getLightThemeProgressWithFromIndex:(long long)a0 toIndex:(long long)a1 progress:(double)a2;
- (BOOL)enablePaddingOptimize;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (void)scrollViewWillBeginDecelerating:(id)a0;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)setHidden:(BOOL)a0;
- (void)setSelectedIndex:(long long)a0;
- (BOOL)gestureRecognizer:(id)a0 shouldReceiveTouch:(id)a1;
- (void)scrollViewDidScroll:(id)a0;
- (id)colorWithHexString:(id)a0;
- (void)layoutSubviews;
- (id)initWithConfig:(id)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)setTransform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })a0;
- (void)scrollViewDidEndScrollingAnimation:(id)a0;
- (void)setAlpha:(double)a0;
- (void)forceLayout;
- (void)setSelectedIndex:(long long)a0 animated:(BOOL)a1;

@end
