@class AWEFollowListUserListViewModel, NSString, AWEFollowListFooterViewModel, AWEEmptyPageSectionViewModel, AWEFollowListSearchBarViewModel, AWEFollowListPageContext, AWEFollowListSearchViewModel, AWEFollowListEntranceViewModel, AWEBaseListSectionViewModel, AWEFollowListRecommendCardViewModel;
@protocol AWEUserRecommendSectionViewModelProtocol;

@interface AWEFollowListViewModel : AWEBaseListViewModel

@property (retain, nonatomic) AWEFollowListUserListViewModel *userListViewModel;
@property (retain, nonatomic) AWEFollowListEntranceViewModel *entranceViewModel;
@property (retain, nonatomic) AWEFollowListSearchViewModel *searchViewModel;
@property (retain, nonatomic) AWEFollowListFooterViewModel *footerViewModel;
@property (retain, nonatomic) AWEFollowListSearchBarViewModel *searchBarViewModel;
@property (retain, nonatomic) AWEEmptyPageSectionViewModel *emptyVM;
@property (retain, nonatomic) AWEBaseListSectionViewModel<AWEUserRecommendSectionViewModelProtocol> *userRecommendSectionViewModel;
@property (retain, nonatomic) AWEFollowListUserListViewModel *cachedUserListViewModel;
@property (retain, nonatomic) AWEFollowListEntranceViewModel *cachedEntranceViewModel;
@property (retain, nonatomic) AWEFollowListRecommendCardViewModel *recommendCardViewModel;
@property (nonatomic) BOOL searching;
@property (nonatomic) BOOL scrollable;
@property (nonatomic) BOOL hideRefreshHeader;
@property (nonatomic) BOOL isShowingInviteFriends;
@property (nonatomic) BOOL showLoading;
@property (nonatomic) BOOL showLoadMoreError;
@property (nonatomic) BOOL handleVCDAlertOrBubble;
@property (nonatomic) BOOL initRefreshFinished;
@property (copy, nonatomic) NSString *vcd;
@property (nonatomic) unsigned long long cacheLoadStatus;
@property (nonatomic) BOOL cacheLoadSuccess;
@property (nonatomic) BOOL needFetchRecommendData;
@property (nonatomic) long long maximumLoadFollowCount;
@property (nonatomic) long long currentLoadPageNumber;
@property (nonatomic) long long maximumLoadPageNumber;
@property (nonatomic) long long topUserCount;
@property (retain, nonatomic) AWEFollowListPageContext *pageContext;
@property (readonly, nonatomic) BOOL hasMore;
@property (readonly, nonatomic) long long recommendDataState;
@property (nonatomic) BOOL hiddenMJFooter;
@property (nonatomic) BOOL isRefreshFromSortClick;

+ (Class)aAWERelationDOUYINHTSAdapterClass;
+ (Class)aAWEConcernRelationCommonAdapterClass;

- (void)setupViewModel;
- (BOOL)showVCDAuthorizedView;
- (id)aAWERelationDOUYINHTSAdapter;
- (BOOL)shouldShowHelpDeskEntrance;
- (BOOL)isOnlyEmptyPage;
- (id)emptyPageConfigForState:(unsigned long long)a0;
- (id)sectionComponents;
- (void)trackAccuracyCheckIfNeed;
- (void)fetchRecommendDataIfNeeded;
- (void)updateRecommendSectionIfNeeded;
- (BOOL)showEmpty;
- (BOOL)showVCDNotMine;
- (BOOL)commonRecommendCondition;
- (id)recommendManagerContext;
- (BOOL)emptyRecommend;
- (id)aAWEConcernRelationCommonAdapter;
- (void)fetchListData:(BOOL)a0;
- (BOOL)revertLibra;
- (long long)groupFilterType;
- (void)updateGroupFilterType:(long long)a0;
- (void)updateTopCount;
- (void)initFetchListData:(BOOL)a0;
- (void)initFetchGroupData;
- (void)fetchUserAndRefreshData;
- (void)followListDidAppear;
- (void)followListDidDisappear;
- (void)updateUserListDataControllerSourType:(long long)a0;
- (BOOL)needUserListRefresh;
- (void)fetchUserListWithGroupType:(long long)a0;
- (void)refreshUserListData;
- (void)followListSubscribeLive;
- (void)loadMoreSearchData;
- (void)loadMoreListData:(BOOL)a0 vcdAuthFirstTime:(BOOL)a1;
- (BOOL)showVCDAuthorizedBar;
- (id)sectionComponentsWithGroupType:(long long)a0;
- (void)refreshDataState;
- (BOOL)enableShowRecommendSection;
- (void)trackValidStay;
- (void)useCacheIfNeeded;
- (long long)userListViewModelDataProcess:(id)a0 groupFilterType:(long long)a1 error:(id)a2 isRefresh:(BOOL)a3;
- (BOOL)cellShowFullScreen;
- (void)addFooter;
- (BOOL)userListIsEmptyAfterRefresh;
- (BOOL)shouldShowVCDFooter;
- (BOOL)showHotsoonFooter;
- (BOOL)enableShowInviteFriend;
- (long long)userListCount;
- (long long)recListFollowMaxCount;
- (id)selfSectionComponentsWithGroupType:(long long)a0;
- (id)otherSectionComponents;
- (BOOL)insertedVCDVMAtLast;
- (long long)currentSortingSourceType;
- (long long)recommendCount;
- (void).cxx_destruct;
- (void)refreshSections;

@end
