@class AWEFeedDoubleColumnListDataController, NSString, AWEHPRecommendDoubleColumnChannelController, UIView, UIViewController;
@protocol AWEHPChannelControllerConfigProtocol, AWEDCFeedListViewControllerProtocol;

@interface AWEFeedNewDoubleColumnViewController : UIViewController <AWEDCFeedListViewControllerDelegate, AWEFeedContainerSearchExtraParamsProtocol, AWEDCFeedEventDispatcherProtocol, AWEDCFeedTopAreaSearchDelegate, AWEFeedDoubleColumnListDataProtocol, AWEFeedTabItemViewControllerProtocol, AWEHPContentVCChannelConfigProtocol>

@property (nonatomic) BOOL isFromPreload;
@property (retain, nonatomic) AWEFeedDoubleColumnListDataController *dataController;
@property (retain, nonatomic) AWEFeedDoubleColumnListDataController *innerDataController;
@property (nonatomic) BOOL placeholderDataLoaded;
@property (nonatomic) BOOL isDoubleColumnTabShowing;
@property (nonatomic) BOOL hasTriggerFakeRefresh;
@property (copy, nonatomic) id /* block */ feedRefreshCompletionBlock;
@property (retain, nonatomic) UIView *topTabBackgroundView;
@property (weak, nonatomic) id<AWEHPChannelControllerConfigProtocol> channelConfig;
@property (retain, nonatomic) UIView *statusBarBackgroundView;
@property (nonatomic) BOOL isPreload;
@property (retain, nonatomic) UIViewController<AWEDCFeedListViewControllerProtocol> *contentVC;
@property (weak, nonatomic) AWEHPRecommendDoubleColumnChannelController *channelController;
@property (copy, nonatomic) NSString *enterHomepageTabEnterMethod;
@property (copy, nonatomic) NSString *enterHomepageTabProcessID;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) long long type;
@property (readonly, copy, nonatomic) NSString *referString;

+ (Class)aAWEFeedModuleServiceDOUYINLiteAdaperClass;
+ (Class)aAWEPadFullPageFeedAdapterClass;
+ (void)setupImagePerformConfig:(id)a0;
+ (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getDefaultCoverFrameInRootViewController:(id)a0;

- (void)pauseWithAnimation;
- (void)animatedRefreshWithCompletion:(id /* block */)a0;
- (BOOL)currentTabIsTop;
- (void)feedRefreshWithType:(long long)a0 completion:(id /* block */)a1;
- (id)getRecentClickAndShowItems;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })dcFeed:(id)a0 frameForCollectionView:(id)a1;
- (BOOL)dcFeed:(id)a0 handleRouterEventWithType:(unsigned long long)a1 awemeModel:(id)a2;
- (id)getCustomSearchExtraDict;
- (void)onLoadPlaceholderDataEndWithResult:(unsigned long long)a0 placeholderData:(id)a1;
- (id)searchBarClickParamsWithContext:(id)a0;
- (id)fetchGuessWordParamsWithOption:(unsigned long long)a0 extra:(id)a1;
- (void)channelTopTabDidSelect;
- (long long)fetchGuessWordIntervalWhenEnableTimer;
- (id)extraParamsWithEvent:(id)a0 currentParams:(id)a1;
- (void)containerCollectionView:(id)a0 didSelectItemAtIndexPath:(id)a1;
- (void)onFetchListDataStartWithReason:(unsigned long long)a0;
- (void)onFetchListDataEndWithReason:(unsigned long long)a0 response:(id)a1 error:(id)a2;
- (void)trackStayTime;
- (id)aAWEFeedModuleServiceDOUYINLiteAdaper;
- (id)aAWEPadFullPageFeedAdapter;
- (BOOL)enableTextIcon;
- (void)clearSwitchPreviewClientShowArray;
- (void)handleAppBecomeActive;
- (id)getFeedListConfig;
- (id)getSmallWindowVC;
- (void)trackClientShowAfterPreviewIfNeededWithExtra:(id)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getCoverFrameInRootViewController;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getPinchTargetViewStartFrame;
- (id)pinchBackgroundViewWithHiddenTabBar:(BOOL)a0;
- (id)getPinchTipsView;
- (id)getPinchTargetView;
- (id)clientExtraCommonParams;
- (id /* block */)enterAnimationStartBlock;
- (void)willEnterChannelWithParams:(id)a0;
- (void)triggerChannelAnimationRefresh;
- (void)handlePreviewAndDCFeedDiff;
- (void)setupTrackTransmission;
- (void)triggerChannelAnimationRefreshWithModel:(id)a0 completion:(id /* block */)a1;
- (void)hiddenDCFeedSwitchToSingleViewIfNeeded;
- (void)hideStatusBarBackground;
- (void)showStatusBarBackground;
- (BOOL)enableOptFirstLoad;
- (void)reloadWithReason:(unsigned long long)a0;
- (void)preloadContent;
- (id)initPreloadVC;
- (void)feedForceRefreshWithType:(long long)a0 config:(id)a1 completion:(id /* block */)a2;
- (void)beginFMPEventWithEnterMethod:(id)a0;
- (void)enterChannelContainerWithModel:(id)a0;
- (void)exitChannelContainerWithModel:(id)a0;
- (BOOL)canRefresh;
- (void).cxx_destruct;
- (void)setScrollEnabled:(BOOL)a0;
- (void)play;
- (void)pause;
- (void)enterBackground;
- (void)reload;
- (void)stop;
- (void)encodeWithCoder:(id)a0;
- (void)viewWillAppear:(BOOL)a0;
- (void)enterForeground;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)traitCollectionDidChange:(id)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)handleAppWillResignActive;

@end
