@class BDXBridgeEventSubscriber, AWEFeedQuickFlashFullPageView, UILabel, NSDictionary, NSObject, AWEQuickFlashListDataController, UIView, NSString, DUXLoadingParticleView, NSArray, AWEAwemeModel, AWEQuickFlashStickerModel, AWEFeedQuickFlashPanelStyleConfig, UIPanGestureRecognizer;
@protocol AFDPineappleRedPacketManagerProtocol, AWEPlayInteractionViewControllerProtocol, AWEFeedStickerDisplayDelegate;

@interface AWEFeedQuickFlashFullPageViewController : UIViewController <AWEFeedQuickFlashFullPageViewDelegate, UIGestureRecognizerDelegate, AWEPreviewable, AWEZoomTransitionOuterContextProvider, AWEQuickFlashListDataControllerDelegate, BDXContainerLifecycleProtocol, AWEFeedQuickFlashFullPageViewControllerProtocol>

@property (retain, nonatomic) NSObject<AFDPineappleRedPacketManagerProtocol> *redPacketManager;
@property (retain, nonatomic) AWEFeedQuickFlashFullPageView *quickFlashFullPageView;
@property (retain, nonatomic) DUXLoadingParticleView *loadingView;
@property (retain, nonatomic) NSArray *fullPageModelList;
@property (retain, nonatomic) NSArray *tagList;
@property (retain, nonatomic) NSArray *playList;
@property (retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer;
@property (retain, nonatomic) UILabel *hintText;
@property (retain, nonatomic) UIView *errorView;
@property (retain, nonatomic) AWEQuickFlashListDataController *quickFlashListDataController;
@property (retain, nonatomic) UIView *shadowView;
@property (nonatomic) BOOL canLoadMore;
@property (retain, nonatomic) NSString *schema;
@property (retain, nonatomic) BDXBridgeEventSubscriber *subscriber;
@property (nonatomic) BOOL isFavoriteRequestOnAir;
@property (nonatomic) BOOL alreadyDismiss;
@property (nonatomic) long long cursor;
@property (nonatomic) BOOL hasMore;
@property (nonatomic) BOOL hasInsertFeedVideo;
@property (nonatomic) double fullPageTime;
@property (nonatomic) double hasUploadedDuration;
@property (retain, nonatomic) NSString *jumpSchema;
@property (nonatomic) BOOL isFromJSBridge;
@property (retain, nonatomic) AWEQuickFlashStickerModel *quickFlashStickerModel;
@property (weak, nonatomic) id<AWEPlayInteractionViewControllerProtocol> interactionDelegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSDictionary *zoomTransitionContext;
@property (retain, nonatomic) AWEAwemeModel *awemeModel;
@property (retain, nonatomic) NSString *enterFrom;
@property (copy, nonatomic) NSDictionary *logExtraDict;
@property (retain, nonatomic) NSDictionary *activicyDic;
@property (copy, nonatomic) NSDictionary *trackContext;
@property (nonatomic) BOOL fromSticker;
@property (retain, nonatomic) AWEFeedQuickFlashPanelStyleConfig *styleConfig;
@property (copy, nonatomic) id /* block */ dismissBlock;
@property (weak, nonatomic) id<AWEFeedStickerDisplayDelegate> hideDelegate;
@property (copy, nonatomic) id /* block */ dragedBlock;

- (void)containerOnShow:(id)a0 sourceParam:(id)a1;
- (void)containerOnHide:(id)a0 sourceParam:(id)a1;
- (void)containerWillStartLoading:(id)a0;
- (void)containerDidFirstScreen:(id)a0;
- (void)containerDidClose:(id)a0;
- (id)zoomTransitionStartViewForOffset:(long long)a0;
- (double)panelViewHeight;
- (double)panelContentViewHeight;
- (void)showOnView:(id)a0 animated:(BOOL)a1;
- (void)addNotifications;
- (void)preloadWithSchema:(id)a0;
- (void)prefetchWithSchema:(id)a0;
- (void)onAwemeDeleteNotification:(id)a0;
- (long long)transferIndexFromPanelToInner:(long long)a0;
- (long long)transferIndexFromInnerToPanel:(long long)a0 withStartIndex:(long long)a1;
- (void)favoriteItemChanged:(id)a0;
- (id)previewingViewControllerForView:(id)a0 atPoint:(struct CGPoint { double x0; double x1; })a1;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })previewingSourceRectForView:(id)a0 atPoint:(struct CGPoint { double x0; double x1; })a1;
- (void)closeButtonDidClicked:(id)a0;
- (void)p_dismiss;
- (void)backButtonDidClicked:(id)a0;
- (void)bgTapAction:(id)a0;
- (void)favoriteButtonDidClicked:(id)a0;
- (void)trackWillJumpToRecorderWithModel:(id)a0;
- (void)jumpToVideoListWithDefaultVideoID:(long long)a0;
- (void)trackVideoInfoWithIndex:(long long)a0 event:(id)a1 repeat:(BOOL)a2;
- (void)didSelectRecommendTitleAtIndex:(long long)a0;
- (void)fetchFullPageModelList;
- (void)trackRecommandTagShowWithIndex:(long long)a0;
- (void)jumpToFlashback;
- (void)joinQuickFlashClickedisNewQuickFlash:(BOOL)a0;
- (void)trackSucaiBtnClick;
- (void)trackSucaiCardClick;
- (void)trackForClientShow;
- (id)playModelTrackDicWithPlayModel:(id)a0;
- (void)trackInfoWithEvent:(id)a0 Model:(id)a1 Track:(id)a2;
- (void)fetchFullPageModelList:(BOOL)a0;
- (void)panContentView:(id)a0;
- (void)setupRefreshHeaderAndFooter;
- (void)updateFullPageModelListWithAwemeList:(id)a0 wrapperList:(id)a1;
- (void)rankListButtonDidClicked:(id)a0;
- (id)basicTrackInfoFromTag:(BOOL)a0 isNew:(BOOL)a1;
- (id)handleSchemaForTrack:(id)a0 extraParam:(id)a1;
- (void)entureLoginWithFavoriteFlashMobWithCompletion:(id /* block */)a0;
- (void)fetchFullPageModelListForInpage:(id /* block */)a0;
- (void)showShadowView;
- (void).cxx_destruct;
- (BOOL)gestureRecognizer:(id)a0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)a1;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void *)identifier;
- (void)viewDidAppear:(BOOL)a0;
- (BOOL)gestureRecognizer:(id)a0 shouldRequireFailureOfGestureRecognizer:(id)a1;
- (void)dealloc;
- (void)removeNotifications;
- (void)viewWillDisappear:(BOOL)a0;
- (void)setupUI;
- (void)pauseVideo;

@end
