@class NSString;

@interface AWEHomepageABSettingsService : HTSService <AWEHomepageABSettingsService>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)pizzaVerifyAPIMigrateV1;
+ (Class)aAWEHPColdLaunchAdapterClass;

- (double)tabBarOverlapHeight;
- (BOOL)tabBarCustomHeightEnabled;
- (long long)homeBubbleConsumeInterval;
- (BOOL)homeBubbleConsumeChange;
- (BOOL)inBlackListWiithTrackEvent:(id)a0;
- (BOOL)isServerTimeZeroProtectEnabled;
- (BOOL)isActivityOfflineByEndTimeEnabled;
- (double)activityBubbleInterval;
- (BOOL)isAllowColdLaunchHotReload;
- (BOOL)isAllowAccountChangeHotReload;
- (BOOL)isAllowHotReloadWhenSplash;
- (long long)requestRenderTimeInterval;
- (BOOL)homePageContextOpt;
- (BOOL)supportPitayaWithTabID:(id)a0;
- (BOOL)supportVCPreloadWithTabID:(id)a0;
- (BOOL)supportVCDelayLoadWithTabID:(id)a0;
- (BOOL)isOptimizeBubbleHitAreaEnable;
- (id)getTopBubbleOptimizeHitAreaInset;
- (id)getBottomBubbleOptimizeHitAreaInset;
- (id)getOptimizeBubbleHitAreaTabsBlacklist;
- (BOOL)isPreloadHpBubbleImageEnable;
- (long long)getPreloadMRBubbleImageOpportunity;
- (id)getPreloadBubbleImageTabsBlacklist;
- (id)tabBadgeConfigV2;
- (id)pinTopConfigV2;
- (id)homepageUIConfig;
- (double)topEditPanelSortTriggerTime;
- (id)topBarMaskWhiteList;
- (id)bottomTwoTabEditConfigDict;
- (id)homepageBottomTabSingleRefreshExpDict;
- (id)homepageBottomTabRefreshGestureControlDict;
- (id)activityLottieEffectControlDict;
- (BOOL)sideBarIMPlusRefactor;
- (id)channelDynamicSchedulingConfig;
- (BOOL)enableChannelDynamicRelease:(id)a0;
- (BOOL)channelDynamicReleaseAccessPitaya;
- (BOOL)enableFollowResumeUseOldAweme;
- (BOOL)enableChannelQualityInfoCollection;
- (id)greyModelBlackClassList;
- (id)hpTopChannelShowInvisibleWaterMarkArray;
- (BOOL)invisibleWaterMarkViewCreateNeedCheckImage;
- (BOOL)remoteTipsEntryNeedCheckView;
- (BOOL)tabbarLogNotTriggerWindowDescription;
- (BOOL)disableFixIPad18OSAndXcode16ProfileSideBarAfterTransitionShowTabBar;
- (BOOL)fixFamiliarUpdateSkylightBottomGradientCrashAfterRelease;
- (BOOL)diableFixTabBarGeneralButtonContentTypeAnimationChangeError;
- (BOOL)homepageC2FeedAnimOpt;
- (id)perfMetricsMonitorConfig;
- (BOOL)hpTopChannelLazyInitContentVC;
- (BOOL)fixLandingMallThemeNotChange;
- (BOOL)coldLaunchTimeMethodOptEnable:(id)a0;
- (BOOL)coldLaunchTimeMethodOptEnableWithIndividualPlay:(id)a0;
- (BOOL)coldLaunchTimeMethodOptTopChannelObjectNotDelay:(id)a0;
- (BOOL)coldLaunchTimeMethodOptBottomChannelObjectNotDelay:(id)a0;
- (long long)coldLaunchTimeMethodOptInteger:(id)a0;
- (BOOL)sideBarLandingCheckNeedWaitFeedAppear;
- (BOOL)disableFeedSchemaUse;
- (BOOL)pageAddContentNeedRemoveOriginParent;
- (BOOL)firstSelectedBottomTabNonPreviousChannel;
- (BOOL)updateTabBarAppearanceByInstance;
- (BOOL)interceptTabBarButtonStatusNotCheckTheme;
- (BOOL)tabBarButtonMultiSelectedDisable;
- (BOOL)tabBarControllerDistinguishSelectionAndClickAfterSelectionLogic;
- (BOOL)landingUseDeterminedLinkNode;
- (BOOL)launchFirstFrameReadyUseTask;
- (BOOL)feedInnerViewUpdateImageAnimationDeduplication;
- (BOOL)sidebarWalletUseNewSubtitleLink;
- (double)channelPitayaPreloadTimeLimit:(id)a0;
- (long long)maxLandingRollBackVCStackCount;
- (BOOL)canShowFeedLeftSideBar;
- (long long)changeImageAnimateStyle;
- (BOOL)replacePlayerMaskEnable;
- (BOOL)topTabVisibleAbilityOpt;
- (BOOL)bottomTabVisibleAbilityOpt;
- (BOOL)rollBackConfigEnable;
- (BOOL)fixLandingCompletion;
- (BOOL)fixIMGesture;
- (BOOL)onetimePullRefreshOpt;
- (BOOL)onetimePullRefreshOptWithChannelID:(id)a0;
- (BOOL)recommendTabToContainer;
- (BOOL)topTabSwitchThemeOptimizeEnabled;
- (id)getSideBarBusinessRefreshSceneWhiteList;
- (BOOL)getHPCombinePassiveTriggerEnable;
- (BOOL)getHPFixEnterLifeCycleInLanding;
- (BOOL)isFixedSelectedLineBug;
- (id)getTrackQueueConfig;
- (id)coldLaunchLandingTabErrorMonitor;
- (id)coldLaunchFirstLandingTrackConfig;
- (BOOL)getCombineRequestMovableWithKey:(id)a0;
- (id)getRequestCombineConfig;
- (BOOL)isPrivacyTransferToSettingPageEnabled;
- (double)tabBarContentHeight;
- (double)customSafeAreaBottomOffset;
- (id)customTabBarHeightBlackSet;
- (id)customSafeAreaBottomOffsetBlackSet;
- (BOOL)leftSideBarUIStyleUseNewGridStyle;
- (id)homepageTabUIConfig;
- (BOOL)skinDisplayOptimizeEnabled;
- (double)refreshSkinThresholdAfterBackground;
- (BOOL)updateInterfaceOrientationWhenResetRootVCEnabled;
- (BOOL)leftSideRedDotMigrateEnable;
- (BOOL)interestRecommendAutoSwipeEnabled;
- (id)interestRecommendBubbleGuideText;
- (BOOL)recommendChannelForceLoadBottomTabPlugin;
- (id)getLottiePlayParamsWithChannelID:(id)a0;
- (id)hpDisablePullRefreshList;
- (id)hpDisableTopTabSingleClickList;
- (id)aAWEHPColdLaunchAdapter;
- (id)p_generateParamsWithConfig:(id)a0 key:(id)a1;
- (id)activityTabOptimizeSettingsDict;
- (id)hotReloadSettingsDict;
- (id)getOptimizeBubbleHitAreaConfig;
- (id)getPreloadHpBubbleImageConfig;
- (id)channelDynamicReleaseWhiteList;
- (id)coldLaunchTimeMethodOptDic;
- (BOOL)coldLaunchTimeMethodCanIndividualPlay;
- (BOOL)supportColdLaunchTimeMethodOpt;
- (id)channelPitayaPreloadTimeLimit;
- (id)onetimePullRefreshOptConfig;
- (id)tabBarCustomHeightConfig;

@end
