@interface AWEIMMessageUI : NSObject

+ (double)bubbleCornerRadius;
+ (double)preferredMaxBubbleWidth;
+ (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })bubbleContentPaddingInsets;
+ (double)textMessageMaxWidthWithContext:(id)a0;
+ (BOOL)supportMessageUIFromProjectXMessage:(id)a0;
+ (id)textMessageFont;
+ (id)textMessageColorWithMesasge:(id)a0;
+ (BOOL)shouldHighlightMentionStringWithMessage:(id)a0;
+ (id)hyperlinkColorWithMesasge:(id)a0;
+ (BOOL)isPureEmojiAndCountSmallerThan3:(id)a0;
+ (double)avatarW;
+ (id)bubbleColorWithMessage:(id)a0 extraInfo:(id)a1;
+ (double)horizontalOffsetWithMessage:(id)a0 inConversation:(id)a1;
+ (id)symmetricBubblePathWithSize:(struct CGSize { double x0; double x1; })a0 message:(id)a1 extraInfo:(id)a2;
+ (id)bubbleStrokeColorWithMessage:(id)a0 extraInfo:(id)a1;
+ (double)duxFontSizeOfMessageTabIfNecessary:(double)a0;
+ (double)duxFontSizeIfNecessary:(double)a0;
+ (BOOL)shouldDisplayNicknameOfMessage:(id)a0 inConversation:(id)a1;
+ (id)cardMessageTitleColorWithMesasge:(id)a0 extraInfo:(id)a1;
+ (id)cardMessageSubTitleColorWithMesasge:(id)a0 extraInfo:(id)a1;
+ (BOOL)isPureDouyinEmojiString:(id)a0 lessThanCount:(unsigned long long)a1;
+ (double)duxFontSizeOfChatVCIfNecessary:(double)a0;
+ (double)preferredTextMessageMaxWidth;
+ (id)quotedMessageTextColor:(id)a0;
+ (id)quoteReplyLineViewColor:(id)a0;
+ (double)duxFontSizeIfNecessary:(double)a0 scene:(unsigned long long)a1;
+ (BOOL)isPureEmojiString:(id)a0 lessThanCount:(unsigned long long)a1;
+ (double)scaledPreferredMaxBubbleWidth;
+ (id)companyMessageHyperlinkColorWithMesasge:(id)a0;
+ (double)bigAvatarMargin;
+ (id)textMessageColorWithMesasge:(id)a0 sendFromMe:(BOOL)a1;
+ (id)mixedDarkCompanyMenuBottomViewBGColor;
+ (double)quoteTitleMaxWidthShareAweme;
+ (double)quoteTitleMaxWidthDefault;
+ (double)commentImageCornerRadius;
+ (struct CGSize { double x0; double x1; })quoteImageSize;
+ (double)quoteTitleFontSize;
+ (id)cellBackgroundColorWithMessage:(id)a0 extraInfo:(id)a1;
+ (id)inputBackgroundColor;
+ (id)newGameInviteMessageDetailStringAttributesWithFontColor:(id)a0;
+ (id)editedHintStringInTheme:(id)a0;
+ (id)textMessageEmojiAdjustFont:(id)a0;
+ (double)preferredBubleTextMaxWidth;
+ (double)defaultAnchorHeight;
+ (id)quotedMessageContentAttributes:(id)a0;
+ (BOOL)shouldDisplayNicknameOfMessage:(id)a0 inConversation:(id)a1 componentContext:(id)a2;
+ (double)avatarTagW;
+ (double)preferredMinBubbleHeight;
+ (id)colorForKey:(id)a0 fromMe:(BOOL)a1;
+ (id)bubbleColorForFansGroupOwner;
+ (id)bubbleExperimentGroupColorWithMessage:(id)a0 extraInfo:(id)a1;
+ (id)bubbleColorForShareCard:(BOOL)a0;
+ (id)p_recallMessageColorWithMesasge:(id)a0;
+ (id)messageColorResource;
+ (id)hexColorStrForKey:(id)a0 fromMe:(BOOL)a1;
+ (id)getTextContentWithMessage:(id)a0;
+ (BOOL)isPureEmojiStringAndCountSmallerThan3:(id)a0;
+ (id)quoteMessageTextFont;
+ (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })quoteMessageInsetsNeedHasImage:(BOOL)a0;
+ (id)textMessageFontWithScene:(unsigned long long)a0;
+ (id)bubbleColorWhenHasChatBackgroundImgMsgType:(long long)a0;
+ (id)preferImageForAudioMessage:(id)a0 originalImage:(id)a1;
+ (id)addBaselineOffsetAttributeIfNeededWithAttriDict:(id)a0 lineHeight:(double)a1 font:(id)a2;
+ (id)separatorLineColorWithMessage:(id)a0 extraInfo:(id)a1;
+ (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })inputVCQuoteMessageInsets:(BOOL)a0;
+ (struct CGSize { double x0; double x1; })quoteCloseSize;
+ (double)getQuotedContanerViewLineWidth;
+ (id)getQuotedContanerViewStrokeColor;
+ (id)getQuotedContanerViewFillColor:(BOOL)a0 hasChatBg:(BOOL)a1;
+ (id)quotedInvalidMessageContentAttributes;
+ (double)quoteImageCornerRadius;
+ (double)quotedTextMessageWithImageMaxWidth;
+ (id)textQuoteFontWithMessage:(id)a0;
+ (id)unreadDotColor;

@end
