@class AWEShareContext, NSArray, AWEIMTranspondListViewController, NSString, NSMutableArray, UIViewController;
@protocol AWEIMShareAndForwardToChatProtocol, AWESharePanel, AWEIMShareMutiselectProtocol;

@interface AWEIMSharePanelExtension : NSObject <AWEIMTranspondListViewControllerDelegate, AWEIMShareMutiselectViewControllerDelegate, AWEShareMessage, AWESharePanelExtension, AWEIMSharePanelExtensionInterface>

@property (retain, nonatomic) AWEShareContext *context;
@property (weak, nonatomic) UIViewController<AWESharePanel> *sharePanel;
@property (retain, nonatomic) AWEIMTranspondListViewController *transpondVC;
@property (retain, nonatomic) UIViewController<AWEIMShareMutiselectProtocol> *mutiselectVC;
@property (copy, nonatomic) NSArray *shareModels;
@property (nonatomic, getter=isAuthorSharingNonpublicAweme) BOOL authorSharingNonpublicAweme;
@property (copy, nonatomic) NSArray *recentSharedShareModels;
@property (copy, nonatomic) NSArray *recentSharedInfoModels;
@property (copy, nonatomic) NSString *multiselectShareText;
@property (nonatomic, getter=isAnimatingMultiselectVC) BOOL animatingMultiselectVC;
@property (nonatomic) BOOL isFetchingIronManShareInfo;
@property (nonatomic) BOOL isFirstSelectedFinish;
@property (nonatomic) BOOL hasFinishGoldShare;
@property (nonatomic) BOOL hasShared;
@property (nonatomic) BOOL hasScrolled;
@property (nonatomic) BOOL shouldAlwaysKeepOldShareLogic;
@property (retain, nonatomic) id<AWEIMShareAndForwardToChatProtocol> shareImpl;
@property (retain, nonatomic) NSMutableArray *currentShareModels;
@property (nonatomic) double bannerContainerHeight;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (Class)aAWEPadModuleAdapterClass;
+ (Class)aAWELiteUGSocialModuleAdapterClass;
+ (Class)aAWEFeedShareObtainGoldDOUYINLiteAdapterClass;
+ (id)extensionWithContext:(id)a0;
+ (Class)aAWEUGKitModuleDOUYINAdapterClass;

- (id)aAWEPadModuleAdapter;
- (id)aAWELiteUGSocialModuleAdapter;
- (id)aAWEFeedShareObtainGoldDOUYINLiteAdapter;
- (void)trackClickSendShareText;
- (void)trackShowSendShareText;
- (void)transpondListView:(id)a0 didSelectedShareModel:(id)a1 andCompletion:(id /* block */)a2;
- (void)transpondListView:(id)a0 didSelectedShareModel:(id)a1 hasMore:(BOOL)a2;
- (void)transpondListViewShareFinished:(id)a0;
- (void)transpondListViewDataSourceDeleteModel:(id)a0;
- (void)transpondListViewRequestDismissal:(id)a0 completion:(id /* block */)a1;
- (void)transpondListViewDismiss:(id)a0;
- (void)transpondListViewDidSelectMore:(id)a0;
- (void)transpondListView:(id)a0 didTappedRecentSharedCell:(id)a1;
- (void)transpondListViewWillScroll:(id)a0;
- (void)transpondListViewUpdateRecentShareModels:(id)a0;
- (id)aAWEUGKitModuleDOUYINAdapter;
- (BOOL)checkIfSharedToSelf:(id)a0;
- (void)startFetchingTranspondModels;
- (id)p_insertRecentSharedIfNeedForShareModels:(id)a0;
- (void)showTranspondWithModels:(id)a0 hasMore:(BOOL)a1;
- (void)p_reloadRecentSharedCellIfNeed;
- (void)p_shareToUserWithShareModel:(id)a0 andCompletion:(id /* block */)a1;
- (void)p_didTappedRecentSharedCellWithRecentSharedList:(id)a0 willUpdateDatasourceBlock:(id /* block */)a1 didUpdateDatasourceBlock:(id /* block */)a2;
- (void)p_updateDataSourceWithShareList:(id)a0;
- (void)sharePanelWillAppear:(id)a0;
- (void)sharePanelWillDisappear:(id)a0;
- (void)sharePanelDidDisappear:(id)a0;
- (void)mutiselectVCIsHidden:(id)a0 hasSentMessage:(BOOL)a1 shareList:(id)a2;
- (void)multiselectVCRequestDismissal:(id)a0 completion:(id /* block */)a1;
- (void)mutiselectVC:(id)a0 didTappedRecentSharedCell:(id)a1;
- (void)mutiselectVCWillScroll:(id)a0;
- (void)mutiselectVCconfirmToBindPhone:(id)a0;
- (void)viewExtensionUpdateHeight:(double)a0 animated:(BOOL)a1 completion:(id /* block */)a2;
- (void)__showTranspondWithModels:(id)a0 hasMore:(BOOL)a1;
- (void)__fetchTranspondShareModelList:(id /* block */)a0 filterNotFriendUser:(BOOL)a1 filterGroupChat:(BOOL)a2 needAddressBookFriend:(BOOL)a3 shieldFansGroup:(BOOL)a4 insertStickOnTopChats:(BOOL)a5;
- (void)__fetchTranspondShareModelList:(id /* block */)a0 afterSortAndFilter:(id /* block */)a1 filterNotFriendUser:(BOOL)a2 filterGroupChat:(BOOL)a3 needAddressBookFriend:(BOOL)a4 shieldFansGroup:(BOOL)a5 insertStickOnTopChats:(BOOL)a6 filterRecentShares:(BOOL)a7;
- (id)getIMFechShareListConfigWithFilterGroupChat:(BOOL)a0 insertStickOnTopChats:(BOOL)a1 filterNotFriendUser:(BOOL)a2 shieldFansGroup:(BOOL)a3 needAddressBookFriend:(BOOL)a4;
- (BOOL)__shouldShowSeletedTranspond;
- (void)__showSeletedTranspondWithModels:(id)a0 hasMore:(BOOL)a1 shouldShowMultiSelectView:(BOOL)a2;
- (void)showMultiselectWithShareModels:(id)a0 transpondListView:(id)a1 hasMore:(BOOL)a2 completion:(id /* block */)a3;
- (id)p_adjustedDataListIfNeeded:(id)a0 aweModel:(id)a1;
- (void)p_transpondListView:(id)a0 didSelectedShareModel:(id)a1 hasMore:(BOOL)a2;
- (void)showMultiselectWithShareModel:(id)a0 transpondListView:(id)a1 hasMore:(BOOL)a2 completion:(id /* block */)a3;
- (id)__seletedTranspondDefaultShareText;
- (void)didSelectRecentSharedShareModels;
- (void)dismissWithMultiselectAnimated:(BOOL)a0 completion:(id /* block */)a1;
- (void)showMultiselectWithShareModel:(id)a0 transpondListView:(id)a1 hasMore:(BOOL)a2;
- (void)p_prepareShareToUserWithShareModel:(id)a0 andCompletion:(id /* block */)a1;
- (void)p_privacyShareToUserWithShareModel:(id)a0 andCompletion:(id /* block */)a1;
- (void)finishShareVideoForActivityWithShareModel:(id)a0;
- (void)p_afterPrivacyTestShareToShareList:(id)a0 andCompletion:(id /* block */)a1;
- (void)fetchTranspondShareModelList:(id /* block */)a0 afterSortAndFilter:(id /* block */)a1 filterNotFriendUser:(BOOL)a2 filterGroupChat:(BOOL)a3 needAddressBookFriend:(BOOL)a4 shieldFansGroup:(BOOL)a5 insertStickOnTopChats:(BOOL)a6 filterRecentShares:(BOOL)a7;
- (void).cxx_destruct;
- (void)dealloc;

@end
