@class AWEIMTranspondListViewControllerUIConfig, AWEIMTranspondListAlertViewController, UICollectionView, UILabel, AWEIMTranspondListDataTracker, UIButton, UIView, AWEShareContext, NSString, NSAttributedString, NSMutableSet, CAShapeLayer, NSArray, YYLabel, UIImageView;
@protocol AWELiteUGSocialShareContactListTitleViewProtocol, AWEIMShareAndForwardToChatProtocol, AWEIMTranspondListViewControllerDelegate;

@interface AWEIMTranspondListViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, AWEIMTranspondListMoreCellActionDelegate, AWEIMTranspondListCellActionDelegate, AWEIMTranspondListRecentSharedCellActionDelegate, AWEIMTranspondListViewControllerInterface>

@property (retain, nonatomic) AWEIMTranspondListViewControllerUIConfig *config;
@property (retain, nonatomic) CAShapeLayer *baseLayer;
@property (retain, nonatomic) YYLabel *titleLabel;
@property (retain, nonatomic) UILabel *subtitleLabel;
@property (nonatomic) BOOL isHotType;
@property (retain, nonatomic) id<AWEIMShareAndForwardToChatProtocol> shareImpl;
@property (retain, nonatomic) UIButton *closeButton;
@property (retain, nonatomic) UIButton *searchButton;
@property (nonatomic) BOOL didTrackReplyAuthor;
@property (retain, nonatomic) UIView *lineView;
@property (nonatomic) BOOL isTitleCenter;
@property (nonatomic) unsigned long long titleDisplayType;
@property (retain, nonatomic) NSAttributedString *finalTitle;
@property (nonatomic) BOOL shouldShowAlert;
@property (retain, nonatomic) UILabel *redPackSubtitle;
@property (retain, nonatomic) UILabel *redPackSubtitleHigh;
@property (retain, nonatomic) UILabel *redPackLandPageDec;
@property (retain, nonatomic) UIImageView *redPackLandPageArrow;
@property (nonatomic) unsigned long long searchBtnStyle;
@property (retain, nonatomic) UIView<AWELiteUGSocialShareContactListTitleViewProtocol> *goldShareToIMTitleView;
@property (retain, nonatomic) NSMutableSet *trackChatShowSet;
@property (retain, nonatomic) NSMutableSet *trackRecentlyChatShowSet;
@property (retain, nonatomic) AWEShareContext *shareContext;
@property (retain, nonatomic) NSArray *dataList;
@property (weak, nonatomic) id<AWEIMTranspondListViewControllerDelegate> delegate;
@property (copy, nonatomic) NSArray *recentSharedList;
@property (nonatomic) BOOL hasMore;
@property (nonatomic) long long recentSharedCount;
@property (retain, nonatomic) UICollectionView *collectionView;
@property (retain, nonatomic) UIView *bannerContainerView;
@property (retain, nonatomic) AWEIMTranspondListAlertViewController *alertViewController;
@property (nonatomic) BOOL isBGColorWhite;
@property (nonatomic) BOOL isAuthorShareNotPublicAweme;
@property (copy, nonatomic) NSAttributedString *titleAttributedText;
@property (retain, nonatomic) AWEIMTranspondListDataTracker *dataTracker;
@property (nonatomic) BOOL isFromSharePanel;
@property (nonatomic) BOOL shouldAlwaysKeepOldShareLogic;
@property (copy, nonatomic) NSAttributedString *newUIStyleDefaultTitleAttributedText;
@property (copy, nonatomic) NSAttributedString *defaultSeletedTitleAttributedText;
@property (copy, nonatomic) NSAttributedString *liteGoldShareToIMAttributedText;
@property (copy, nonatomic) NSAttributedString *liteGoldtitleAttributedText;
@property (copy, nonatomic) NSAttributedString *fcoinTitleAttributedText;
@property (retain, nonatomic) UIImageView *redPackView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (Class)aAWEPadModuleAdapterClass;
+ (Class)aAWELiteUGSocialModuleAdapterClass;
+ (Class)aAWEFeedShareObtainGoldDOUYINLiteAdapterClass;
+ (Class)aAWEUGKitModuleDOUYINAdapterClass;

- (id)aAWEPadModuleAdapter;
- (void)p_updateUI;
- (id)panelBackgroundColor;
- (void)p_scrollViewDidEndScroll:(id)a0;
- (id)aAWELiteUGSocialModuleAdapter;
- (id)aAWEFeedShareObtainGoldDOUYINLiteAdapter;
- (void)updateUIConfig:(id)a0;
- (id)initWithShareContext:(id)a0;
- (BOOL)transpondListCellDelegateDidTapAvatar:(id)a0 shareModel:(id)a1;
- (BOOL)transpondListCellDelegateDidLongpressAvatar:(id)a0 shareModel:(id)a1 gesRecognizer:(id)a2;
- (id)transpondListCollectionViewCellAuthorUserId:(id)a0;
- (void)moreCellTapped;
- (void)p_acquireUserActiveWithCompletion:(id /* block */)a0;
- (id)fetchFinalTitle;
- (void)p_uploadImageAndGetUrl:(id)a0 completion:(id /* block */)a1;
- (id)aAWEUGKitModuleDOUYINAdapter;
- (BOOL)isEcommerceRedPackShareIM;
- (struct CGSize { double x0; double x1; })friendVisibleTextSize:(id)a0;
- (void)clickRedPackView:(id)a0;
- (void)openMoreSharePanel;
- (void)recentSharedCellTapped:(id)a0;
- (double)viewNewStyleHeight;
- (void)p_handleDefaultSelected;
- (void)p_fetchCoverImageURLIfNeed;
- (void)p_trackActiveUserDataWithModel:(id)a0;
- (void)updateCollectionViewWithIndexPath:(id)a0 filterRecentShare:(BOOL)a1 gesShareModel:(id)a2;
- (void)transferToShareList;
- (void)showShareRiskWarningTitleIfNeeded;
- (id)__titleAttributes;
- (BOOL)p_textCanShowTranspondPageTipAlert:(id)a0;
- (BOOL)canShowTranspondPageTipAlert;
- (void)p_showActiveUserTipAlert;
- (id)p_filterSelfInDataListIfNeeded:(id)a0;
- (void)getViewModelActiveState;
- (void)getViewModelRedPackState;
- (void)p_setupUI;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 sizeForItemAtIndexPath:(id)a2;
- (id)collectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (long long)collectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (void)scrollViewWillBeginDragging:(id)a0;
- (long long)numberOfSectionsInCollectionView:(id)a0;
- (void)collectionView:(id)a0 willDisplayCell:(id)a1 forItemAtIndexPath:(id)a2;
- (void)viewWillAppear:(BOOL)a0;
- (void)scrollViewDidScroll:(id)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(BOOL)a0;
- (void)closeButtonTapped:(id)a0;

@end
