@class NSArray, NSTimer, AWELiveSkylightRequestCompleteParams, NSString;
@protocol AWEConcernSkylightElementProtocol;

@interface AWELiveSkylightViewModel : NSObject <AWEUserMessage, AWELiveSkylightViewModelProtocol>

@property (nonatomic) BOOL isDataRefreshing;
@property (nonatomic) BOOL isShowingSkylight;
@property (nonatomic) BOOL isShowingPinedUserPopover;
@property (nonatomic) unsigned long long requestStatus;
@property (nonatomic) unsigned long long dispayStatus;
@property (nonatomic) unsigned long long leftRefreshStatus;
@property (nonatomic) unsigned long long loadMoreStatus;
@property (nonatomic) BOOL shouldShowCapsuleView;
@property (nonatomic) BOOL hasMore;
@property (retain, nonatomic) AWELiveSkylightRequestCompleteParams *requestCompleteParams;
@property (nonatomic) BOOL hasLiveOfRefreshCapsuleParam;
@property (retain, nonatomic) NSArray<AWEConcernSkylightElementProtocol> *allSkylightElements;
@property (retain, nonatomic) NSArray<AWEConcernSkylightElementProtocol> *skylightElements;
@property (retain, nonatomic) NSArray *dataSource;
@property (retain, nonatomic) NSTimer *refreshTimer;
@property (nonatomic) double LastEnteredSkyLightViewTime;
@property (nonatomic) long long totalMixSortUnreadCount;
@property (nonatomic) unsigned long long progressViewStatus;
@property (nonatomic) unsigned long long recommendCardStatus;
@property (nonatomic) double recommendCardCapsuleViewAlpha;
@property (nonatomic) BOOL isEnterByLiveBubble;
@property (nonatomic) BOOL liveAnimationStopIfNeed;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)didFinishLogoutWithUid:(id)a0;
- (void)didFinishUnFollowUser:(id)a0 status:(long long)a1 error:(id)a2;
- (void)didFinishBlockUser:(id)a0 status:(long long)a1;
- (id)cellModelAtIndexPath:(id)a0;
- (void)updateElementWithType:(unsigned long long)a0 cellType:(unsigned long long)a1 needUpdateFoldState:(BOOL)a2;
- (void)handleSkylightDataWhenRequestCompleted;
- (int)getRefreshDuration;
- (void)containerViewWillDisappear;
- (void)containerViewDidAppear;
- (void)containerEnterFollowWithModel:(id)a0;
- (void)willShowSkylightWithAnimated:(BOOL)a0 actionMethod:(unsigned long long)a1;
- (void)willCloseSkylightWithAnimated:(BOOL)a0 actionMethod:(unsigned long long)a1;
- (void)didScrollToConcern:(BOOL)a0;
- (BOOL)getIsShowingPinedUserPopover;
- (long long)actualLiveCount;
- (id)unreadData;
- (void)refreshWithIsSlientRefresh:(BOOL)a0;
- (void)awe_elementsContainerViewDidLoad;
- (void)awe_elementsContainerViewWillDisappear;
- (void)awe_elementsContainerViewDidAppear;
- (void)awe_elementsWillAutoSilentRefreshSkylight;
- (void)awe_elementsWillManualRefreshSkylight;
- (void)awe_elementsWillCloseSkylightWithAnimated:(BOOL)a0 actionMethod:(unsigned long long)a1;
- (void)awe_elementsWillShowSkylightWithAnimated:(BOOL)a0 actionMethod:(unsigned long long)a1;
- (void)awe_elementsWillDisplayCellWithCellModel:(id)a0;
- (void)awe_elementsReloadElementsCompletion;
- (void)awe_elementsScrollViewDidEndDecelerating:(id)a0;
- (void)awe_elementsScrollViewWillBeginDragging:(id)a0;
- (void)awe_elementsScrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)awe_elementsScrollDidEnd:(id)a0;
- (void)awe_elementsDidScrollToConcern:(BOOL)a0;
- (void)awe_elementsEnterFollowWithModel:(id)a0;
- (void)refreshTimeInvalidate;
- (void)refreshWithTimer;
- (void)refreshSkylightIfNeeded;
- (void)refreshWithNeedHandleData:(BOOL)a0 isSlientRefresh:(BOOL)a1 completion:(id /* block */)a2;
- (void)refreshElementsWithNeedHandleData:(BOOL)a0 isSlientRefresh:(BOOL)a1 completion:(id /* block */)a2;
- (void)handleSkylightDisplayElements;
- (void)handleSkylightElementDataWhenRequestCompleted;
- (void)removeElementWithCellType:(unsigned long long)a0 needUpdateFoldState:(BOOL)a1;
- (void)addElementWithCellType:(unsigned long long)a0;
- (void)reloadElementWithCellType:(unsigned long long)a0;
- (long long)findSectionWithCellType:(unsigned long long)a0 dataSource:(id)a1;
- (id)skylightElementWithCellType:(unsigned long long)a0;
- (void)removeTipViewNeedUpdateFoldState:(BOOL)a0;
- (void)addTipView;
- (void)handleSkylightDisplayElementsForAllData;
- (void)constructDataSourceForMixSort;
- (void)assemblyDataSource:(id)a0 cellType:(unsigned long long)a1 cellModel:(id)a2;
- (BOOL)isElementHasMore:(id)a0;
- (void)clearSkylightElementDataSource;
- (void)insertUpdateModelsToDataSource:(id)a0;
- (id)calculateInsertIndex;
- (BOOL)isDuplicateWithUserID:(id)a0;
- (void)insertUpdateModel:(id)a0 toDataSource:(id)a1 atIndex:(long long)a2;
- (id)calculateConfigInsertIndex;
- (long long)lastCellIndexOnScreen;
- (id)skylightElementsResortStrategy:(id)a0 liveActivity:(unsigned long long)a1;
- (void)updataUIAfterResortSkylightElements:(BOOL)a0;
- (void)skylightElementsResortByCrowd;
- (id)skylightElementWithCellType:(unsigned long long)a0 inElements:(id)a1;
- (id)getResortElementWithOriginElements:(id)a0 elementKeySortArray:(id)a1;
- (id)createAndSortElementsWithClasses:(id)a0 container:(id)a1;
- (void)refreshSkyLight;
- (void)startLoadMoreWithElement:(id)a0;
- (long long)collectionViewItemCount;
- (Class)cellClassWithCellType:(unsigned long long)a0 inSkylightElements:(id)a1;
- (BOOL)hasOtherElementWithElements:(id)a0;
- (void)clearSkylightDataSource;
- (void)containerStartViewDidLoad;
- (void)didCloseSkylightWithAnimated:(BOOL)a0 actionMethod:(unsigned long long)a1;
- (void)didShowSkylightWithAnimated:(BOOL)a0 actionMethod:(unsigned long long)a1;
- (void)updateTipViewWithType:(unsigned long long)a0 needUpdateFoldState:(BOOL)a1;
- (void)lowActivityJudgeAndSkylightElementsResortByClick:(BOOL)a0 isRealDisplay:(BOOL)a1;
- (void)resortElements;
- (void)skylightElementsResortByHighActiveUser:(BOOL)a0;
- (void)skylightElementsResortByLowActiveUser:(BOOL)a0;
- (void)skylightElementsResortByUidSwitch:(BOOL)a0;
- (void)configSkylightElementsWtihContainer:(id)a0;
- (void)startLeftRefresh;
- (void)endLeftRefresh;
- (void)startLoadMore;
- (void)endLoadMore;
- (Class)cellClassWithCellType:(unsigned long long)a0;
- (id)skylightElementFromDataSource:(id)a0 section:(long long)a1 skylightElements:(id)a2;
- (BOOL)hasOtherElementExceptLiveElement;
- (BOOL)canShowEmptyView;
- (void)startRequestData;
- (void)requestCompletedWithLiveExsit:(BOOL)a0 liveError:(id)a1;
- (void).cxx_destruct;
- (id)init;
- (long long)totalCount;
- (void)dealloc;
- (void)containerViewDidLoad;
- (void)addObservers;

@end
