@class DUXBasicSheet, AWELongPressPanelViewModel, AWELPPToSpeedControlViewModel, AWELongPressPanelViewGroupModel, AWELongPressPanelDataManager, UIViewController, NSMutableArray, UIView, UILongPressGestureRecognizer, AWELPPToSpeedControlTipsView, NSString, NSMutableSet, AWELongPressPanelConfiguration, AWEAwemeModel, NSArray;
@protocol AWEPadMorePanelViewControllerProtocol, AWELongPressPanelViewControllerProtocol, AWELongPressPanelAdsActionFeedbackProtocol;

@interface AWELongPressPanelManager : NSObject <DUXSheetDelegate, AWEFeedTableViewControllerMessage, UIGestureRecognizerDelegate, AWELongPressPanelProtocol>

@property (nonatomic) unsigned long long falseTouchType;
@property (nonatomic) double falseTouchBeginTimestamp;
@property (retain, nonatomic) NSMutableArray *shareSuccessList;
@property (nonatomic) BOOL isSheetWillDismiss;
@property (retain, nonatomic) UIViewController<AWEPadMorePanelViewControllerProtocol> *padPopoverViewController;
@property (retain, nonatomic) AWELongPressPanelDataManager *dataManager;
@property (retain, nonatomic) AWELPPToSpeedControlViewModel *toSpeedControlViewModel;
@property (weak, nonatomic) AWELPPToSpeedControlTipsView *toSpeedControlTipsView;
@property (weak, nonatomic) UILongPressGestureRecognizer *toSpeedControlGesture;
@property (copy, nonatomic) id /* block */ preloadBlock;
@property (retain, nonatomic) AWEAwemeModel *currentModel;
@property (retain, nonatomic) AWELongPressPanelConfiguration *config;
@property (retain, nonatomic) DUXBasicSheet *sheet;
@property (nonatomic) double nomalHeight;
@property (nonatomic) BOOL show;
@property (nonatomic) BOOL panelShowing;
@property (retain, nonatomic) NSMutableSet *friendsOnlineSet;
@property (weak, nonatomic) AWELongPressPanelViewModel *viewModel;
@property (nonatomic) BOOL isLongPressType;
@property (nonatomic) long long shareChooseNumber;
@property (nonatomic) BOOL dontShowShareTextBar;
@property (copy, nonatomic) NSArray *actionItems;
@property (nonatomic) BOOL showShareVideoTaskTip;
@property (retain, nonatomic) NSMutableArray *shareList;
@property (retain, nonatomic) AWELongPressPanelViewGroupModel *interactiveGroupModel;
@property (weak, nonatomic) UIViewController<AWELongPressPanelViewControllerProtocol> *longPressPanelVC;
@property (nonatomic) double panelWidthForPad;
@property (copy, nonatomic) id /* block */ shareInputViewDismissHandler;
@property (retain, nonatomic) UIView<AWELongPressPanelAdsActionFeedbackProtocol> *dislikeView;
@property (retain, nonatomic) UIView<AWELongPressPanelAdsActionFeedbackProtocol> *likeView;
@property (nonatomic) BOOL showShareFriends;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (Class)aAWEPadBizUIAdapterClass;
+ (Class)aAWEPlayInteractionAdapterClass;
+ (Class)aAWEFeedDOUYINiPadModuleAdapterClass;
+ (id)shareInstance;

- (BOOL)sheetWillStayAfterClickMaskArea;
- (void)sheetWillDismiss:(id)a0;
- (void)sheetDidDismiss:(id)a0;
- (void)sheet:(id)a0 didChangeFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1 withUserInteraction:(BOOL)a2;
- (double)sheetShouldUpdateHeightWhenContentHeightChange:(id)a0;
- (void)updateSheetHeight:(double)a0 animated:(BOOL)a1 completion:(id /* block */)a2;
- (void)showLongPressPanelWithModel:(id)a0 configuration:(id)a1 hasMask:(BOOL)a2 completion:(id /* block */)a3;
- (BOOL)shouldShowTranspondIMShareWithAwemeModel:(id)a0;
- (void)showLongPressPanelWithModel:(id)a0 configuration:(id)a1 completion:(id /* block */)a2;
- (id)aAWEPadBizUIAdapter;
- (void)showAdsActionDislikeView;
- (void)showAdsActionLikeView;
- (BOOL)shouldShowPanelWhenUserDidLongPressWithModel:(id)a0 referString:(id)a1 scene:(id)a2;
- (void)showNewLongPressPanelForScene:(id)a0 model:(id)a1 referString:(id)a2 logExtra:(id)a3;
- (BOOL)authorIsPrivateAccount;
- (id)aAWEPlayInteractionAdapter;
- (void)viewControllerAppear:(id)a0;
- (id)getSelectedShareList;
- (void)configWithViewController:(id)a0;
- (void)insertRecommendModel:(id)a0 forRoom:(id)a1;
- (id)getLongPressPanelVC;
- (void)updateSheetPaddingWithHeight:(double)a0 offset:(double)a1 animated:(BOOL)a2 completion:(id /* block */)a3;
- (id)aAWEFeedDOUYINiPadModuleAdapter;
- (void)dismissAdsActionDislikeView;
- (void)dismissAdsActionLikeView;
- (BOOL)enableNewPressPanelInScene:(id)a0 model:(id)a1;
- (BOOL)canShowLongPressPanelWithModel:(id)a0 referString:(id)a1 scene:(id)a2;
- (void)trackLongPressShowWithSuccess:(BOOL)a0;
- (void)_onReceiveChallengeFavoriteChanged:(id)a0;
- (void)breakPointUpdate:(id)a0;
- (void)showLongPressPanelWithModel:(id)a0 configuration:(id)a1 hasMask:(BOOL)a2 fromViewController:(id)a3 completion:(id /* block */)a4;
- (void)longPressShowTrack;
- (void)showPopoverPanelForPadWithViewController:(id)a0;
- (void)showLongPressPanelForPadWithViewController:(id)a0 hasMask:(BOOL)a1 completion:(id /* block */)a2;
- (BOOL)shouldShowModernLongPressPanel;
- (void)showModernLongPressPanelWithViewController:(id)a0 model:(id)a1 hasMask:(BOOL)a2 completion:(id /* block */)a3;
- (void)setupToSpeedControlGesture;
- (void)updateSheetHeight:(double)a0 withMinimumSheetHeight:(double)a1 animated:(BOOL)a2 completion:(id /* block */)a3;
- (void)dismissWithSheetMeanwhile:(BOOL)a0 animation:(BOOL)a1 completion:(id /* block */)a2;
- (void)dismissPreloadBlockIfNeededWithSelector:(SEL)a0;
- (id)LongPressPanelLogExtraDictGet:(id)a0;
- (double)adsActionViewTopOffset;
- (BOOL)shouldShowAdFeedActionView;
- (BOOL)shouldShowAdSearchActionView;
- (double)adsActionViewPanelHeight;
- (void)updateSheetPaddingWithHeight:(double)a0 animated:(BOOL)a1 completion:(id /* block */)a2;
- (void)longPressPanelExitTrack;
- (void)updateSheetPaddingWithWidth:(double)a0 animated:(BOOL)a1 completion:(id /* block */)a2;
- (void)dealDismissBlock;
- (void)onToSpeedControlStateChanged;
- (void)showToSpeedControlTipsViewIfNeed;
- (void)dismissToSpeedControlTipsView;
- (void)onToSpeedControlGesture:(id)a0;
- (void)innerToSpeedControl;
- (id)currentFamiliarRecommendViewModel;
- (id)currentStoryViewModel;
- (id)currentDislikeViewModel;
- (BOOL)shouldShowPanelWhenUserDidLongPressWithModel:(id)a0 referString:(id)a1;
- (void)preLoadPanelConfigIfNeedWithAwemeModel:(id)a0 referString:(id)a1 subScene:(id)a2;
- (BOOL)enableLongPressModal;
- (void)configManagerForModalWithModel:(id)a0 configuration:(id)a1;
- (BOOL)shouldShowModalRecommend;
- (void)willAppearModalRecommend;
- (void)triggerModalRecommend;
- (BOOL)shouldShowModalStory;
- (void)triggerModalStory;
- (BOOL)shouldShowModalDislike;
- (void)triggerModalDislike;
- (void)addShareModelToShareList:(id)a0;
- (void)addShareSuccessModelToShareList:(id)a0;
- (void)showReplySucessNoticeBarWithModel;
- (BOOL)shouldDisplayAdAttitude;
- (void)trackFalseTouchIfNeeded:(unsigned long long)a0;
- (void)dismissWithAnimation:(BOOL)a0 completion:(id /* block */)a1;
- (void)setUp;
- (void).cxx_destruct;
- (void)reset;
- (BOOL)gestureRecognizer:(id)a0 shouldBeRequiredToFailByGestureRecognizer:(id)a1;
- (void)dealloc;
- (void)appWillResignActive;

@end
