@class NSString, NSDictionary, UIScrollView, UIViewController;

@interface AWEModernFeedCellConcreteContext : NSObject <AWEModernFeedCellContext>

@property (copy, nonatomic) id /* block */ updateAccesoryViewBlock;
@property (copy, nonatomic) id /* block */ updateHiddenStatusBlock;
@property (copy, nonatomic) id /* block */ focusCurrentCellBlock;
@property (copy, nonatomic) id /* block */ saveCurrentScrollingStateBlock;
@property (copy, nonatomic) id /* block */ restoreSavedScrollingStateBlock;
@property (copy, nonatomic) id /* block */ forceBecomeActiveBlock;
@property (copy, nonatomic) id /* block */ endForceBecomingActiveBlock;
@property (copy, nonatomic) id /* block */ reloadCurrentSectionBlock;
@property (copy, nonatomic) id /* block */ removeRecommendWordsCardBlock;
@property (copy, nonatomic) id /* block */ queryIsLoadingDataBlock;
@property (copy, nonatomic) id /* block */ singleTapEnterAwemeDetailBlock;
@property (copy, nonatomic) id /* block */ singleTapEnterAwemeDetailBlockWithPlayer;
@property (copy, nonatomic) id /* block */ singleTapEnterAwemeDetailWithExtraBlock;
@property (copy, nonatomic) id /* block */ combinateCardAwemeListBlock;
@property (copy, nonatomic) id /* block */ recalculateToAutoPlayBlock;
@property (copy, nonatomic) id /* block */ registAutoPlayDistributeBlock;
@property (copy, nonatomic) id /* block */ videoPlayerStartPlay;
@property (copy, nonatomic) id /* block */ videoPlayerDidEndBlock;
@property (copy, nonatomic) id /* block */ videoPlayerDidPlayErrorBlock;
@property (copy, nonatomic) id /* block */ willEnterFullScreenBlock;
@property (copy, nonatomic) id /* block */ scrollToOffsetY;
@property (copy, nonatomic) id /* block */ scrollToDisplayItemWithOffset;
@property (copy, nonatomic) id /* block */ immersivePlayBlock;
@property (copy, nonatomic) id /* block */ immersiveBannerBlock;
@property (copy, nonatomic) id /* block */ showPendantBlock;
@property (copy, nonatomic) id /* block */ immersiveTransToBottomBlock;
@property (copy, nonatomic) id /* block */ searchChangeBackgroundColorBlock;
@property (copy, nonatomic) id /* block */ searchOpenImmersiveVideoBlock;
@property (copy, nonatomic) id /* block */ lynxElementDidMountBlock;
@property (copy, nonatomic) id /* block */ getSearchCardLocationBlock;
@property (copy, nonatomic) id /* block */ getFeedOffset;
@property (nonatomic) struct CGSize { double width; double height; } viewControllerSize;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } viewControllerFrame;
@property (retain, nonatomic) UIScrollView *videoFeedScrollView;
@property (copy, nonatomic) NSDictionary *searchLogPassback;
@property (copy, nonatomic) NSString *searchType;
@property (retain, nonatomic) id bindedData;
@property (nonatomic) long long sectionIndex;
@property (weak, nonatomic) UIViewController *startFromViewController;
@property (copy, nonatomic) NSDictionary *logExtraDict;
@property (copy, nonatomic) id /* block */ videoSinglePlayedBlock;
@property (copy, nonatomic) id /* block */ setAttachmentDataBlock;
@property (copy, nonatomic) id /* block */ updateIndexAwemeListBlock;
@property (copy, nonatomic) id /* block */ switchToSubTabBlock;
@property (copy, nonatomic) id /* block */ showRecommendWords;
@property (copy, nonatomic) id /* block */ sendAIGCQuery;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (BOOL)isContentLoading;
- (void)reloadCurrentSection;
- (void)lynxElementDidMount;
- (void)singleTapEnterAwemeDetailWithExtra:(id)a0;
- (void)saveCurrentScrollingState;
- (void)forceBecomeActive;
- (void)focusCurrentCellAnimated:(BOOL)a0;
- (void)singleTapEnterAwemeDetail;
- (void)accessaryViewDidUpdateAnimated:(BOOL)a0;
- (void)videoPlayerWillPlay;
- (void)endForceBecomingActive;
- (void)reloadCurrentSectionAnimated:(BOOL)a0;
- (void)hiddenStatusDidUpdateAnimated:(BOOL)a0;
- (void)restoreSavedScrollingStateAnimated:(BOOL)a0;
- (void)scrollToOffsetY:(double)a0;
- (void)scrollToDisplayItemWithOffset:(double)a0 animated:(BOOL)a1;
- (double)getVideoFeedOffset;
- (void)recalculateToAutoPlay;
- (void)searchImmersiveBanner:(id)a0;
- (void)singleTapEnterAwemeDetailWithPlayer:(id)a0 extra:(id)a1;
- (void)setAttachmentData:(id)a0 animated:(BOOL)a1;
- (void)videoPlayerDidEnd;
- (void)videoPlayerDidPlayError;
- (id)getSearchCardLocation;
- (void)registAutoplayDistribute:(id)a0;
- (void)updateIndex:(long long)a0 withAwemeList:(id)a1;
- (void)searchImmersivePlay:(BOOL)a0;
- (void)searchShowPendant:(id)a0;
- (void)searchTransToBottom:(id)a0;
- (void)searchChangeBackgroundColor:(id)a0;
- (void)searchOpenImmersiveVideo:(id)a0;
- (void)switchToSubTab:(id)a0 changeTabView:(BOOL)a1 enterMethod:(id)a2;
- (void)showRecommendWordsIfNeeded:(id)a0 completion:(id /* block */)a1;
- (void)sendQuery:(id)a0 source:(id)a1 extra:(id)a2 animated:(BOOL)a3 insertCompletion:(id /* block */)a4;
- (id)combinateCardAwemeList;
- (void).cxx_destruct;
- (void)willEnterFullScreen;

@end
