@class IESCategoryEffectsModel, NSArray, NSMutableDictionary, NSString, IESEffectModel, AWEPhotoToVideoMonitorInfo, NSDictionary;
@protocol ACCMusicModelProtocol, AWEMVTemplateModelDelegate;

@interface AWEMVTemplateModel : NSObject

@property (readonly, nonatomic) id<ACCMusicModelProtocol> musicModel;
@property (retain, nonatomic) id<ACCMusicModelProtocol> presentedMusicModel;
@property (retain, nonatomic) NSMutableDictionary *mvChallengeArrayDict;
@property (copy, nonatomic, setter=setTemplateModels:) NSArray *templateModels;
@property (copy, nonatomic) NSArray *urlPrefix;
@property (retain, nonatomic) NSMutableDictionary *effectModelTemplateInfos;
@property (retain, nonatomic) NSMutableDictionary *downloadingProgress;
@property (copy, nonatomic) NSArray *categories;
@property (retain, nonatomic) IESCategoryEffectsModel *categoryEffects;
@property (nonatomic) long long loadCursor;
@property (nonatomic) long long sortingPosition;
@property (nonatomic) BOOL isLoadingData;
@property (nonatomic) BOOL didLoadedFirstPageData;
@property (retain, nonatomic) IESEffectModel *sameMVModel;
@property (retain, nonatomic) IESEffectModel *singlePhotoToVideoModel;
@property (retain, nonatomic) IESEffectModel *multiplePhotoToVideoModel;
@property (retain, nonatomic) IESEffectModel *multiplePhotoToVideoSaveModel;
@property (retain, nonatomic) IESEffectModel *textPhotoToVideoModel;
@property (retain, nonatomic) IESEffectModel *feedPhotoToVideoModel;
@property (retain, nonatomic) NSArray *musicList;
@property (retain, nonatomic) id<ACCMusicModelProtocol> musicModel;
@property (retain, nonatomic) id<ACCMusicModelProtocol> presentedMusicModel;
@property (retain, nonatomic) id<ACCMusicModelProtocol> lastMusicModel;
@property (retain, nonatomic) id<ACCMusicModelProtocol> feedMusicModel;
@property (copy, nonatomic) id /* block */ singlePhotoTemplateCompletion;
@property (copy, nonatomic) id /* block */ multiplePhotoTemplateCompletion;
@property (copy, nonatomic) id /* block */ multiplePhotoTemplateSaveCompletion;
@property (copy, nonatomic) id /* block */ textTemplateCompletion;
@property (nonatomic) BOOL isSinglePhotoTemplateDownloading;
@property (nonatomic) BOOL isMultiplePhotoTemplateDownloading;
@property (nonatomic) BOOL isTextPhotoTemplateDownloading;
@property (nonatomic) BOOL isMultiplePhotoTemplateSaveDownloading;
@property (nonatomic) BOOL isTemplateMusicDownloading;
@property (copy, nonatomic) NSString *feedPhotoTemplateDownloadingModelId;
@property (nonatomic) unsigned long long feedVideoPhotoCountType;
@property (retain, nonatomic) AWEPhotoToVideoMonitorInfo *photoToVideoMonitorInfo;
@property (weak, nonatomic) id<AWEMVTemplateModelDelegate> delegate;
@property (nonatomic) BOOL hasMore;
@property (copy, nonatomic) NSDictionary *trackExtraDic;

+ (void)addEffectModelToManagerIfNeeds:(id)a0;
+ (id)sharedManager;

- (void)p_reset;
- (void)preFetchPhotoToVideoMusicWithRetryBlock:(id /* block */)a0 isCommercialScene:(BOOL)a1 params:(id)a2 completionBlock:(id /* block */)a3;
- (void)fetchPhotoToVideoMusicInTimeWithRetryBlock:(id /* block */)a0 isCommercialScene:(BOOL)a1 params:(id)a2 completionBlock:(id /* block */)a3;
- (id)videoMusicModelWithType:(unsigned long long)a0;
- (id)templateModelWithEffectId:(id)a0;
- (void)updateTemplateModels:(id)a0;
- (void)reloadDataFromCache;
- (id)templateInfoForModel:(id)a0;
- (void)checkAndUpdatePhotoMovieTemplate;
- (void)p_updatePageInfo:(id)a0 isLoadMore:(BOOL)a1;
- (id)effectForPublishModel:(id)a0;
- (void)setUpPlaceholderData;
- (id)templateVideoCoverURLForModel:(id)a0;
- (id)templatePictureCoverURLForModel:(id)a0;
- (long long)templateMinMaterialForModel:(id)a0;
- (long long)templateMaxMaterialForModel:(id)a0;
- (long long)templatePicInputWidth:(id)a0;
- (long long)templatePicInputHeight:(id)a0;
- (id)templatePicFillMode:(id)a0;
- (long long)templateTypeForModel:(id)a0;
- (id)downloadProgressForModel:(id)a0;
- (void)downloadMaterialWithEffectId:(id)a0 completion:(id /* block */)a1;
- (void)downloadMaterialForModel:(id)a0;
- (void)p_makeMVModelFirst:(id)a0;
- (void)addMVChallengeArray:(id)a0 mvEffectId:(id)a1;
- (id)photoToVideoMonitorInfo;
- (void)prefetchMVTemplatesForPanel:(id)a0;
- (BOOL)support1080P;
- (void)finishCompletion;
- (id)chooseEffectModelFrom:(id)a0;
- (void)updatePhotoVideoModel:(id)a0 forPanel:(id)a1;
- (void)finishPhotoToVideoTemplateDownloadFor:(id)a0;
- (void)downloadMaterialWithEffect:(id)a0 completion:(id /* block */)a1;
- (BOOL)enableUseMusicWithMusic:(id)a0;
- (BOOL)finishCompletionForSameModel;
- (void)preFetchPhotoToVideoMusicListWithType:(unsigned long long)a0;
- (void)preFetchPhotoToVideoMusicListWithType:(unsigned long long)a0 params:(id)a1;
- (BOOL)enablePreFetchPhotoToVideoMusicListWithType:(unsigned long long)a0;
- (void)preFetchPhotoToVideoMusicList:(id)a0;
- (void)preFetchPhotoToVideoMusicWithRetryBlock:(id /* block */)a0;
- (void)preFetchPhotoToVideoMusicWithRetryBlock:(id /* block */)a0 completionBlock:(id /* block */)a1;
- (void)saveRequestDuration:(long long)a0 infoDuration:(long long)a1;
- (void)prefetchTextToVideoTemplates;
- (void)prefetchPhotoToVideoSaveTemplates;
- (id)photoToVideoTemplateWithIsSinglePhoto:(BOOL)a0;
- (void)prefetchPhotoToVideoTemplates;
- (id)photoToVideoMoniterInfoSucceeed:(BOOL)a0 isSinglePhoto:(BOOL)a1 isTextMode:(BOOL)a2 startTime:(double)a3;
- (id)timeDiffForStart:(double)a0 end:(double)a1;
- (void)cleanPhotoToVideoMusic;
- (id)defaultMusicForPhotoToVideoTemplate;
- (void)prefetchCachedPhotoToVideoTemplates;
- (void)prefetchMVTemplateForSlideShowMVId:(id)a0 photoCountType:(unsigned long long)a1;
- (void)preFetchPhotoToVideoFeedMusicWithMusicId:(id)a0;
- (id)feedVideoMusicModelForType:(unsigned long long)a0;
- (void)resetFeedPhotoCountType;
- (void)preFetchPhotoToVideoMusicList;
- (void)asyncFetchTextToVideoTemplateWithCompletion:(id /* block */)a0;
- (void)asyncFetchPhotoToVideoSaveTemplateWithCompletion:(id /* block */)a0;
- (void)asyncFetchPhotoToVideoTemplateWithIsSinglePhoto:(BOOL)a0 completion:(id /* block */)a1;
- (id)textToVideoMoniterInfoSucceeed:(BOOL)a0 startTime:(double)a1;
- (id)photoToVideoMoniterInfoSucceeed:(BOOL)a0 isSinglePhoto:(BOOL)a1 startTime:(double)a2;
- (void).cxx_destruct;
- (id)init;

@end
