@class UIView, NSString, NSArray, AWENearbyC2SearchGapConfig, AWENearbyPageContext, UIButton, UIImageView, AWENearbyGrouponCitySelectView, AWENearbyC2SwitchBtn, DUXPopover, AWENearbyResourceMarginConfig;
@protocol AWESearchNearbyEntranceViewProtocol;

@interface AWENearbyC2SearchContainer : UIView <DUXPopoverDelegate, AWESearchNearbyEntranceViewLifeCycleProtocol, AWENearbyContainerEventMessage, AWENearbyC2FeedEventMessage>

@property (retain, nonatomic) AWENearbyPageContext *pageContext;
@property (retain, nonatomic) AWENearbyC2SwitchBtn *switchBtn;
@property (retain, nonatomic) UIView<AWESearchNearbyEntranceViewProtocol> *searchView;
@property (retain, nonatomic) AWENearbyGrouponCitySelectView *citySelectView;
@property (nonatomic) BOOL enableToolArea;
@property (nonatomic) BOOL hasLeaveGrouponTabOnce;
@property (retain, nonatomic) NSArray *toolIconViews;
@property (nonatomic) long long toolIconCount;
@property (copy, nonatomic) NSString *currentImageMode;
@property (retain, nonatomic) UIButton *backBtn;
@property (retain, nonatomic) UIImageView *backBtnImageView;
@property (nonatomic) BOOL hasActivityEntrance;
@property (retain, nonatomic) UIView *activityEntranceView;
@property (retain, nonatomic) AWENearbyResourceMarginConfig *entranceMargin;
@property (nonatomic) struct CGSize { double width; double height; } entranceSize;
@property (retain, nonatomic) AWENearbyC2SearchGapConfig *searchGapConfig;
@property (weak, nonatomic) DUXPopover *popover;
@property (weak, nonatomic) DUXPopover *citySelectPopover;
@property (retain, nonatomic) UIView *content;
@property (copy, nonatomic) NSString *firstShowCityBarText;
@property (copy, nonatomic) id /* block */ bubbleBlk;
@property (copy, nonatomic) id /* block */ closeBlk;
@property (nonatomic) long long searchContainerReloadTimes;
@property (copy, nonatomic) id /* block */ clickBlk;
@property (copy, nonatomic) id /* block */ bubbleDidShow;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)popoverDidDisappear:(id)a0;
- (void)applicationEnterBackground;
- (void)showBubble;
- (void)viewWillTransition;
- (void)nearbyContainerWillDisappear;
- (void)dismissSwitchBtnGuideBubble;
- (void)nearbyC2FeedScrollViewWillBeginDraggingWithContext:(id)a0;
- (void)updateToolEntranceInfo:(id)a0;
- (id)findViewWithShowName:(id)a0;
- (void)updateCitySelectText:(id)a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 gapConfig:(id)a1 pageContext:(id)a2 closeBlk:(id /* block */)a3;
- (void)updateSearchBackgroudStyle:(unsigned long long)a0;
- (void)updatehasHeadAreaImage:(BOOL)a0;
- (void)showBubbleOnSearchContainer:(id)a0;
- (void)enterGrouponTab;
- (void)leaveGrouponTab;
- (void)showCitySelectBubble:(id)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })adjustBackBtnFrame;
- (BOOL)isCitySelectViewInnerStyle;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })adjustCitySelectViewFrame;
- (void)trackCityBubbtonClick;
- (void)createSearchView;
- (BOOL)isDouyinEcommerce;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })adjustSearchViewFrame;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })adjustToolIconViewFrameWithIndex:(long long)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })adjustEntranceViewFrame;
- (void)resetLatyout;
- (id)getIconViewWithShowName:(id)a0;
- (void)trackHeaderToolsFmpWithToolEntranceInfo:(id)a0;
- (void)cancelCitySelectBubbleView;
- (void)realSugWordDidShow;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })adjustSwitchBtnFrame;
- (void)configActivityEntranceView:(id)a0 margin:(id)a1 size:(struct CGSize { double x0; double x1; })a2;
- (void)startNormalGuideAnimate;
- (void)startBubbleGuideAnimateClickBubbleBlk:(id /* block */)a0;
- (void)retractGuideAnimate;
- (void)__creatNormalSearchView;
- (id)popoverViewWithText:(id)a0 contentWidth:(double)a1;
- (void)animateHideSwitchBtnToRight;
- (id)addQueryWithClickArea:(unsigned long long)a0;
- (void)clickSearch:(unsigned long long)a0 isRealSugWord:(BOOL)a1;
- (void)close;
- (void).cxx_destruct;
- (void)refresh;
- (void)setHidden:(BOOL)a0;
- (BOOL)pointInside:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)dealloc;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)setupUI;
- (void)tap;

@end
