@class AWEUserProfileEventCommonParamsHandler, AWEOriginalSoundTrackNewDataSource, AWEMusicPlayerQueue, AWEUserModel, NSMutableDictionary, AWEOriginalSoundTrackViewHolder, UITableView, AWEMusicModel, NSString;
@protocol AWEMusicStreamingPlayEventService, MusicService, AWEUserProfileTabVCDelegate;

@interface AWEOriginalSoundTrackNewViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, AWEPreviewable, AWEMusicServiceDelegate, AWEUserMessage, AWEMusicBottomPlayerViewDelegate, AWEMusicStreamingQueueDelegate, AWEMusicFeedPlayerDelegate, AWEMusicPerformanceListCellDelegate, AWEMusicSubPlayerOuterTransitionProvider, AWEOriginalSoundTrackViewHolderProtocol, AWEOriginalSoundTrackViewControllerProtocol>

@property (retain, nonatomic) AWEOriginalSoundTrackNewDataSource *dataSource;
@property (nonatomic) BOOL fromHomepage;
@property (nonatomic) BOOL musicFeedShowing;
@property (nonatomic) BOOL queueShowing;
@property (nonatomic) BOOL shootShowing;
@property (retain, nonatomic) AWEMusicModel *playingMusicModel;
@property (retain, nonatomic) AWEMusicPlayerQueue *queue;
@property (retain, nonatomic) NSMutableDictionary *luna_itemShowDict;
@property (retain, nonatomic) NSMutableDictionary *rankShowDic;
@property (retain, nonatomic) AWEUserModel *targetUser;
@property (retain, nonatomic) id<AWEMusicStreamingPlayEventService> eventService;
@property (nonatomic) BOOL isAppearing;
@property (retain, nonatomic) id<MusicService> luna_musicService;
@property (retain, nonatomic) AWEOriginalSoundTrackViewHolder *viewHolder;
@property (retain, nonatomic) id<MusicService> musicService;
@property (retain, nonatomic) UITableView *ostTableView;
@property (weak, nonatomic) id<AWEUserProfileTabVCDelegate> userDelegate;
@property (retain, nonatomic) AWEUserProfileEventCommonParamsHandler *eventCommonParamsHandler;
@property (copy, nonatomic) NSString *currentUserID;
@property (copy, nonatomic) NSString *secUserID;
@property (retain, nonatomic) NSString *referString;
@property (nonatomic) BOOL isProfileDidAppear;
@property (nonatomic) BOOL hideData;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (copy, nonatomic) id /* block */ showPrivateAccountInfoView;
@property (copy, nonatomic) id /* block */ footerBootomInset;

- (id)aweui_emptyPageConfigForState:(unsigned long long)a0;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })aweui_emptyPageEdgeInsets;
- (void)didFinishLoginWithUid:(id)a0;
- (void)musicService:(id)a0 playStatusChanged:(long long)a1;
- (void)musicServiceMusicChanged:(id)a0;
- (id)aweui_emptyPageBelowView;
- (void)playerViewDidTapCover:(id)a0;
- (void)playerViewDidTapInfo:(id)a0;
- (void)playerViewDidTapConfirmBtn:(id)a0;
- (BOOL)shouldShowConfirmButton;
- (double)contentOffsetY;
- (void)adjustContentOffset:(struct CGPoint { double x0; double x1; })a0 animated:(BOOL)a1;
- (double)contentSizeHeight;
- (BOOL)shouldHideNoMoreText;
- (id)previewingViewControllerForView:(id)a0 atPoint:(struct CGPoint { double x0; double x1; })a1;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })previewingSourceRectForView:(id)a0 atPoint:(struct CGPoint { double x0; double x1; })a1;
- (void)p_startTimingForTrack;
- (void)p_trackEventForStayTime;
- (BOOL)hasMoreOfScene:(id)a0;
- (void)loadMoreScene:(id)a0 responseBlock:(id /* block */)a1 completion:(id /* block */)a2;
- (BOOL)isCustomAddToQueueModel;
- (id)titleForPlayerOfQueueId:(id)a0;
- (void)feed:(id)a0 viewWillAppear:(BOOL)a1;
- (void)feed:(id)a0 didDismissAnimation:(BOOL)a1;
- (void)lunaLoadMoreAction;
- (void)loadingShow:(BOOL)a0;
- (BOOL)hiddenTabBarBeforeTransition;
- (void)didClickPerformance:(id)a0;
- (void)willShowPerformance:(id)a0;
- (void)willShowFindMore;
- (void)didTriggerFindMore;
- (id)initWithUserID:(id)a0 secUserID:(id)a1 targetUser:(id)a2 fromHomepage:(BOOL)a3;
- (void)refreshMusicList:(id)a0;
- (void)luna_addNotification;
- (BOOL)newMusicPlayer;
- (void)p_trackMusicianTabShow;
- (void)p_showMusicianCenterGuideBubble;
- (void)updateMusic:(id)a0 collectStat:(id)a1;
- (void)refreshViewControllerState;
- (void)showNetRequestError;
- (BOOL)p_showPrivateAccountInfoView;
- (BOOL)__isVsOfficialAccount;
- (id)playerModelWithMediaModel:(id)a0;
- (void)showPlayerViewIfNeeded:(BOOL)a0;
- (void)musicPlayTracker:(id)a0;
- (id)p_musicModelsWithCurrentMedia:(id)a0 shouldIgnoreNoPlayRight:(BOOL)a1;
- (BOOL)startShootWithMusicModel:(id)a0 enterMethod:(id)a1;
- (void)loadMoreType:(long long)a0 completion:(id /* block */)a1;
- (id)paramsFromSchema:(id)a0;
- (void)confirmBtnClickedWithMusicModel:(id)a0;
- (void)playMusicWithMediaModel:(id)a0 needPause:(BOOL)a1;
- (void)luna_playMusicWithMediaModel:(id)a0 needPause:(BOOL)a1;
- (BOOL)__isFirstSubMediaAtIndexPath:(id)a0;
- (BOOL)__isLastSubMediaAtIndexPath:(id)a0;
- (id)mediaCellWithTableView:(id)a0 mediaModel:(id)a1 atIndexPath:(id)a2 isMainMedia:(BOOL)a3;
- (void)collectionBtnClickedWithAudio:(id)a0;
- (void)rankChartClickedWithMusicModel:(id)a0;
- (id)getMusicCenterCardSchmea;
- (float)parseMusicCenterCardHeighByMusicCenterCardSchmea;
- (void)luna_musicPlayTracker:(id)a0;
- (id)p_currentPlayingMedia;
- (void)reloadData;
- (void).cxx_destruct;
- (void)pause;
- (id)contentView;
- (id)storage;
- (id)tableView:(id)a0 viewForHeaderInSection:(long long)a1;
- (void)tableView:(id)a0 didSelectRowAtIndexPath:(id)a1;
- (id)tableView:(id)a0 cellForRowAtIndexPath:(id)a1;
- (id)init;
- (void)stop;
- (long long)tableView:(id)a0 numberOfRowsInSection:(long long)a1;
- (void)scrollViewWillBeginDragging:(id)a0;
- (long long)numberOfSectionsInTableView:(id)a0;
- (void)applicationWillResignActive;
- (void)tableView:(id)a0 willDisplayCell:(id)a1 forRowAtIndexPath:(id)a2;
- (double)tableView:(id)a0 heightForRowAtIndexPath:(id)a1;
- (void)viewWillAppear:(BOOL)a0;
- (void)scrollViewDidScroll:(id)a0;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })a0 withTransitionCoordinator:(id)a1;
- (double)tableView:(id)a0 heightForHeaderInSection:(long long)a1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (double)tableView:(id)a0 heightForFooterInSection:(long long)a1;
- (id)tableView:(id)a0 viewForFooterInSection:(long long)a1;
- (BOOL)isCurrentUser;
- (double)footerBottomInset;
- (void)refreshData;

@end
