@class NSTimer, UIView, NSArray, NSString, AWEPadFeedDrawerDataController, UIButton, NSMutableArray, DUXPopover, UICollectionView, AWEPadFeedContentViewModel, NSIndexPath;

@interface AWEPadFeedDrawerContainerViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIGestureRecognizerDelegate, UIScrollViewDelegate, AWEMVPadAuthorRecommendFeedHeaderDelegate, AWEFeedTabItemViewControllerProtocol, AWEPadFeedDrawerContainerViewControllerProtocol>

@property (retain, nonatomic) UICollectionView *sideBarCollectionView;
@property (retain, nonatomic) UIButton *expendButton;
@property (retain, nonatomic) UIView *sideBarContainer;
@property (retain, nonatomic) UIView *touchMaskView;
@property (retain, nonatomic) NSArray *awemeModels;
@property (retain, nonatomic) NSArray *authorModels;
@property (retain, nonatomic) NSMutableArray *selectedArray;
@property (nonatomic) long long isClosing;
@property (nonatomic) BOOL isPanelShow;
@property (retain, nonatomic) NSTimer *timer;
@property (retain, nonatomic) DUXPopover *popOver;
@property (nonatomic) double panelShowTime;
@property (nonatomic) double panelCloseTime;
@property (retain, nonatomic) NSIndexPath *currentIndexPath;
@property (copy, nonatomic) NSString *listEnterMethod;
@property (nonatomic) struct CGPoint { double x; double y; } originScrollViewContentOffset;
@property (nonatomic) BOOL waitLoadMoreComplete;
@property (retain, nonatomic) NSMutableArray *hasTrackItems;
@property (nonatomic) BOOL isAppeared;
@property (retain, nonatomic) AWEPadFeedContentViewModel *contentViewModel;
@property (retain, nonatomic) AWEPadFeedDrawerDataController *dataController;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) long long type;
@property (readonly, copy, nonatomic) NSString *referString;

+ (id)idFromModel:(id)a0;
+ (id)dataTypeWithModel:(id)a0;

- (void)pauseWithAnimation;
- (void)duxGrid_viewDidChangeBreakPointFrom:(struct { long long x0; long long x1; })a0 toBreakPoint:(struct { long long x0; long long x1; })a1;
- (void)animatedRefreshWithCompletion:(id /* block */)a0;
- (BOOL)currentTabIsTop;
- (void)seekPlayTimeWithItemID:(id)a0;
- (void)onAwemeDeleted:(id)a0 isDislike:(BOOL)a1;
- (void)invalidateCloseTimer;
- (void)didEnterChannel;
- (void)didTapChangeButtonOnHeader;
- (void)fetchAuthorList;
- (void)addLoadMoreCallback;
- (void)fireCloseTimer;
- (void)trackAllCards;
- (void)tableViewCellDidEndDisplay:(id)a0;
- (void)feedTableViewDidEndScroll:(id)a0;
- (void)updateViewWhenNetworkCompleteWithError:(id)a0;
- (void)trackMediumClientWithModel:(id)a0 index:(long long)a1 event:(id)a2;
- (void)trackMediumShowWithModel:(id)a0 index:(long long)a1;
- (void)openDrager;
- (void)expandCollectionView;
- (void)closeDrager;
- (void)positionTranslateScal:(double)a0;
- (BOOL)canRefresh;
- (double)collectionView:(id)a0 layout:(id)a1 minimumInteritemSpacingForSectionAtIndex:(long long)a2;
- (double)collectionView:(id)a0 layout:(id)a1 minimumLineSpacingForSectionAtIndex:(long long)a2;
- (void)collectionView:(id)a0 didHighlightItemAtIndexPath:(id)a1;
- (void).cxx_destruct;
- (void)setScrollEnabled:(BOOL)a0;
- (void)play;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (void)pause;
- (void)collectionView:(id)a0 didUnhighlightItemAtIndexPath:(id)a1;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })collectionView:(id)a0 layout:(id)a1 insetForSectionAtIndex:(long long)a2;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 referenceSizeForHeaderInSection:(long long)a2;
- (id)collectionView:(id)a0 viewForSupplementaryElementOfKind:(id)a1 atIndexPath:(id)a2;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 sizeForItemAtIndexPath:(id)a2;
- (void)viewDidLayoutSubviews;
- (void)reload;
- (BOOL)collectionView:(id)a0 shouldHighlightItemAtIndexPath:(id)a1;
- (void)stop;
- (id)collectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (long long)collectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (void)scrollViewWillBeginDragging:(id)a0;
- (void)collectionView:(id)a0 didSelectItemAtIndexPath:(id)a1;
- (long long)numberOfSectionsInCollectionView:(id)a0;
- (void)collectionView:(id)a0 willDisplaySupplementaryView:(id)a1 forElementKind:(id)a2 atIndexPath:(id)a3;
- (void)collectionView:(id)a0 willDisplayCell:(id)a1 forItemAtIndexPath:(id)a2;
- (void)addObserver;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)a0;
- (id)currentInteractionController;
- (void)setupUI;
- (void)tapGesture:(id)a0;
- (void)panGesture:(id)a0;

@end
