@class AWEPOIFeedUgcItemModel, BDXBridgeEventSubscriber, UILabel, NSDictionary, AWEPOIDetailUGCPhotosPreviewRateView, AWEPOIDetailUGCVideoProgressTimeView, AWEPOIDetailSkinConfig, UIButton, UIView, AWEPOIUGCCommentModel, AWEPOIUGCCommentDataProvider, AWEPOIDetailUGCInteractionHelper, CAGradientLayer, AWEPOIDetailUGCSliderView, NSString, AWEPOIUGCCommentDataProviderConfiguration, NSMutableArray, UIImageView;
@protocol AWEPOIUGCPreviewViewControllerBounceDelegate, BDXViewContainerProtocol, AWEPOIUGCPreviewViewControllerLoadMoreDelegate, AWEPOIDetailUGCPhotosPreviewViewControllerDelegate;

@interface AWEPOIDetailUGCPhotosPreviewViewController : AWEPOIDetailPhotosPreviewBaseViewController <AWEPOIDetailUGCPhotosPreviewRateViewDelegate, BTMPageManagableProtocol, BDXContainerLifecycleProtocol, AWEZoomTransitionInnerContextProvider, AWEZoomTransitionOuterContextProvider>

@property (retain, nonatomic) UIButton *closeIcon;
@property (retain, nonatomic) UIButton *muteIcon;
@property (retain, nonatomic) UIView *pageNumberView;
@property (retain, nonatomic) UILabel *pageLabel;
@property (retain, nonatomic) UILabel *slashLabel;
@property (retain, nonatomic) UILabel *totalLabel;
@property (retain, nonatomic) AWEPOIDetailUGCSliderView *sliderView;
@property (retain, nonatomic) AWEPOIDetailUGCVideoProgressTimeView *videoProgressTimeView;
@property (retain, nonatomic) CAGradientLayer *bottomGradientLayer;
@property (retain, nonatomic) AWEPOIDetailUGCPhotosPreviewRateView *rateView;
@property (retain, nonatomic) UIView<BDXViewContainerProtocol> *lynxRateView;
@property (retain, nonatomic) BDXBridgeEventSubscriber *lynxRateViewShowSubscriber;
@property (retain, nonatomic) UIImageView *animationStartView;
@property (nonatomic) BOOL hasTrackedFeedbackViewShow;
@property (nonatomic) BOOL didShowDiggHint;
@property (retain, nonatomic) AWEPOIDetailUGCInteractionHelper *interactionHelper;
@property (nonatomic) BOOL isTransferring;
@property (retain, nonatomic) AWEPOIUGCCommentModel *currentCommentModel;
@property (nonatomic) long long currentCommentIndex;
@property (retain, nonatomic) AWEPOIUGCCommentDataProvider *dataProvider;
@property (nonatomic) BOOL isAppeared;
@property (weak, nonatomic) id<AWEPOIDetailUGCPhotosPreviewViewControllerDelegate> delegate;
@property (weak, nonatomic) id<AWEPOIUGCPreviewViewControllerLoadMoreDelegate> loadModeDelegate;
@property (weak, nonatomic) id<AWEPOIUGCPreviewViewControllerBounceDelegate> bounceDelegate;
@property (retain, nonatomic) AWEPOIFeedUgcItemModel *ugcModel;
@property (nonatomic) unsigned long long feedbackType;
@property (retain, nonatomic) AWEPOIDetailSkinConfig *skinConfig;
@property (nonatomic) BOOL adaptForCommentTab;
@property (copy, nonatomic) NSString *rateID;
@property (nonatomic) BOOL dynamicRateView;
@property (copy, nonatomic) NSString *rateViewLynxUrl;
@property (copy, nonatomic) NSString *rateViewRawData;
@property (nonatomic) BOOL enableVideoPreview;
@property (nonatomic) BOOL enableMultiComments;
@property (retain, nonatomic) AWEPOIUGCCommentDataProviderConfiguration *dataProviderConfiguration;
@property (retain, nonatomic) NSMutableArray *commentModels;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSDictionary *zoomTransitionContext;

+ (Class)aAWEPadModuleAdapterClass;

- (void)container:(id)a0 didChangeIntrinsicContentSize:(struct CGSize { double x0; double x1; })a1;
- (id)zoomTransitionStartViewForOffset:(long long)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })focusViewPlaceholderFrame;
- (unsigned long long)zoomTransitionAllowedTriggerDirection;
- (BOOL)zoomTransitionWantsRemoveSpringAnimation;
- (id)zoomTransitionEndView;
- (long long)zoomTransitionItemOffset;
- (BOOL)btm_autoManaged;
- (id)btm_pageIdentifier;
- (id)aAWEPadModuleAdapter;
- (void)setupBinding;
- (BOOL)hasDoRateDiggAction;
- (struct CGSize { double x0; double x1; })sizeForCell;
- (void)updateProgressWithPage:(long long)a0 total:(long long)a1 photo:(id)a2;
- (void)notifyDelegatePhotoExpose:(BOOL)a0;
- (Class)photoCellClass;
- (Class)videoCellClass;
- (void)layoutCollectionView:(id)a0;
- (void)didDisplayCell:(id)a0 index:(long long)a1;
- (id)rateTrackingParams;
- (id)rateDiggRequestParams;
- (id)rateDiggBDXPublishEventParams;
- (void)didDiggHintDismissWithType:(id)a0;
- (void)didClickContentExpand;
- (void)trackFeedbackViewShowIfNeeded;
- (void)showDiggHintViewAfterDelayIfNeeded;
- (void)showDiggHintInRateView;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bottomGradientLayerFrame;
- (void)setupCloseIcon;
- (void)setupMuteIcon;
- (void)setupTimeView;
- (void)setupRateView;
- (void)setupSliderView;
- (void)setupCommentDataSource;
- (void)subscribeLynxViewReady;
- (BOOL)shouldShowSliderView;
- (void)tryPreloadMaterials:(id)a0;
- (void)publishPhotosPreviewOperationEventWithType:(id)a0 rateID:(id)a1 materialType:(long long)a2;
- (void)triggerBounce:(id)a0;
- (void)trackPreviewVCShow:(id)a0 mediaType:(long long)a1;
- (void)didTapOnCloseIcon;
- (void)didTapOnRateView;
- (void)addMoreCommentModels:(id)a0 materials:(id)a1 toLast:(BOOL)a2;
- (void).cxx_destruct;
- (id)initWithConfiguration:(id)a0;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (long long)totalCount;
- (void)collectionView:(id)a0 willDisplayCell:(id)a1 forItemAtIndexPath:(id)a2;
- (double)animationDuration;
- (void)viewWillAppear:(BOOL)a0;
- (void)scrollViewDidScroll:(id)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)a0;

@end
