@class NSData, NSString, UIImage, NSArray, AWEVideoPublishSourceInfo, APCDTOAlbumConfig, NSDictionary, NSMutableDictionary, NSMutableArray, NSURL, NSNumber, AWEPostPageVideoCutShareIdInfo;
@protocol ACCWorkspaceReader, ACCPublishRepository, ACCRepoDataContext;

@interface AWERepoUploadInfomationModel : NSObject <AWERepositoryDraftProtocol, ACCRepositoryDraftContextDeprecated, ACCRepoRegister, ACCCreationDataAccess, NSCopying, ACCRepoUploadInfomationData, ACCRepositoryRequestParamsDeprecated, ACCRepositoryContextDeprecated, ACCRepositoryTrackContextDeprecated>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSDictionary *videoSourceInfo;
@property (nonatomic) BOOL hasBindObserveForUpdateSourceInfo;
@property (retain, nonatomic) APCDTOAlbumConfig *imageAlbumConfig;
@property (retain, nonatomic) NSMutableDictionary *extraDict;
@property (nonatomic) BOOL isSpeedChange;
@property (nonatomic) double exportTime;
@property (nonatomic) unsigned long long videoClipMode;
@property (retain, nonatomic) NSNumber *originUploadVideoClipCount;
@property (retain, nonatomic) NSNumber *originUploadPhotoCount;
@property (nonatomic) unsigned long long clipSourceType;
@property (nonatomic) BOOL isMultiVideoUpload;
@property (nonatomic) unsigned long long mediaSubType;
@property (nonatomic) BOOL isFaceuVideoFirst;
@property (retain, nonatomic) UIImage *toBeUploadedImage;
@property (retain, nonatomic) NSMutableArray *sourceInfos;
@property (retain, nonatomic) AWEVideoPublishSourceInfo *lastSourceInfo;
@property (retain, nonatomic) AWEPostPageVideoCutShareIdInfo *shareIdInfo;
@property (nonatomic) BOOL hasReplaceAssets;
@property (nonatomic) long long sourceInfosUpdateSignal;
@property (copy, nonatomic) NSArray *selectedUploadAssets;
@property (nonatomic) long long selectedUploadAssetsUpdateSignal;
@property (copy, nonatomic) NSString *uploadImagePath;
@property (copy, nonatomic) NSString *uploadImagePathRelative;
@property (retain, nonatomic) NSString *sourceInfoJson;
@property (retain, nonatomic) NSData *extraDictData;
@property (copy, nonatomic) NSString *reactID;
@property (copy, nonatomic) NSArray *uploadInfoIDsDraft;
@property (retain, nonatomic) NSMutableArray *uploadInfoIDs;
@property (retain, nonatomic) NSMutableDictionary *uploadInfoDict;
@property (retain, nonatomic) NSMutableDictionary *uploadPropDict;
@property (retain, nonatomic) NSMutableDictionary *uploadAutoCaptionTemplateIdDict;
@property (retain, nonatomic) NSMutableDictionary *uploadAutoCaptionTemplateNameDict;
@property (retain, nonatomic) NSMutableDictionary *uploadDuetOriginIdDict;
@property (retain, nonatomic) NSMutableDictionary *uploadDuetFromDict;
@property (retain, nonatomic) NSMutableDictionary *uploadMomentMetaDict;
@property (retain, nonatomic) NSMutableDictionary *uploadEditInfoDict;
@property (retain, nonatomic) NSMutableDictionary *uploadAIGCInfoDict;
@property (retain, nonatomic) NSMutableDictionary *uploadPropExtraInfoDict;
@property (retain, nonatomic) NSMutableDictionary *uploadTemplateInfoDict;
@property (nonatomic) long long hdPublishStrategy2;
@property (nonatomic) BOOL isSourceFromJianying;
@property (nonatomic) BOOL isSourceFromAweme;
@property (nonatomic) unsigned long long imageAlbumLivePhotoMode;
@property (retain, nonatomic) NSURL *livePhotoVideoSourceUrl;
@property (retain, nonatomic) NSURL *livePhotoImageSourceUrl;
@property (nonatomic) BOOL didHandleLivePhotoToImageAlbum;
@property (nonatomic) BOOL disableCacheLiveMode;
@property (nonatomic) BOOL isMultiLivePhoto;
@property (nonatomic) BOOL momentCameraIsShowingAlbumButton;
@property (nonatomic) BOOL disableGraphicsAnchor;
@property (nonatomic) BOOL disableUploadPropList;
@property (nonatomic) BOOL isDeleteGraphicsAnchor;
@property (nonatomic) BOOL isAnchorPermissionDenied;
@property (copy, nonatomic) NSString *videocutTransferTemplateId;
@property (copy, nonatomic) NSString *beautyMeLooksIDs;
@property (copy, nonatomic) NSString *beautyMeFilterIDs;
@property (copy, nonatomic) NSString *beautyMeAIHairID;
@property (copy, nonatomic) NSArray *originLocalIDsFromShare;
@property (retain, nonatomic) NSArray *beautyMeEffects;
@property (nonatomic) unsigned long long anchorDisableGraphicsReason;
@property (nonatomic) BOOL hasAlbumSearchSuggestionAsset;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<ACCRepoDataContext> dataContext;
@property (weak, nonatomic) id<ACCWorkspaceReader> workspaceReader;
@property (weak, nonatomic) id<ACCPublishRepository> repoDeprecated;

+ (id)repo_dataProtocol;
+ (BOOL)p_isValidDescriptionInfo:(id)a0;
+ (id)uploadTimeWithAsset:(id)a0;
+ (void)p_loadMetadataForAsset:(id)a0 completion:(id /* block */)a1;
+ (id)p_sourceInfoWithImageData:(id)a0;
+ (id)p_uploadOriginWithAsset:(id)a0 metadata:(id)a1;

- (id)acc_publishRequestParams:(id)a0;
- (id)initWithDraft:(id)a0;
- (void)saveWithDraft:(id)a0;
- (id)aigcInfoFromUploadMetadata;
- (id)aigcPropListFromMetadata;
- (id)duetOriginIdFromMetadata;
- (id)duetFromIdFromMetadata;
- (id)editInfoDicFramMetadata;
- (BOOL)isAIVideoClipMode;
- (id)getMusicIdFromFaceuMetaData;
- (struct _HTSAudioRange { double x0; double x1; })getAudioRangeFromMetaData;
- (BOOL)isValidWithMusicIdFromFaceu:(id)a0;
- (id)sourceInfoList;
- (id)readUploadFirstAssetTemplateInfo;
- (id)acc_referExtraParams;
- (BOOL)hasAppliedTemplate:(id)a0;
- (id)acc_publishTrackEventParams:(id)a0;
- (id)videoPublishViewModel;
- (id)propListFromMetadata;
- (id)aigcPropListFromMetadataOnlyForLora;
- (id)aigcInfoFromMetadata;
- (void)draftWillBeSavedWithID:(id)a0;
- (void)modelDidRetrievedFromDraftWithID:(id)a0;
- (void)p_uploadSourceInfo:(id)a0;
- (void)p_appendUploadInfo:(id)a0;
- (id)sourceInfosArray;
- (BOOL)p_isStudioPublishFlow;
- (void)updateInfosWithIsMixedSlides:(BOOL)a0;
- (void)updateSelectedUploadAssetsIfNeeded;
- (void)updateSourceInfoForMixedSlides:(BOOL)a0;
- (void)updateImageSourceInfo:(BOOL)a0;
- (void)updateVideoSourceInfo:(BOOL)a0;
- (void)updateUploadInfosIfNeeded;
- (void)updateMomentUploadInfoIfNeeded;
- (void)setUpWithPHAsset:(id)a0 assetID:(id)a1 index:(int)a2;
- (void)setUpWithOnlineResourceWithIndex:(int)a0;
- (void)saveMetaDataWithAssetID:(id)a0 mediaType:(long long)a1 metaDaata:(id)a2 index:(int)a3;
- (void)updateAssetsProductInfo;
- (void)trackAIGCMetaInfoWith:(id)a0;
- (void)abnormalRegainFromDraft;
- (id)aigcPropListFromMetadata:(BOOL)a0;
- (void)recoverUploadIdsIfNeed;
- (void)updateFromLastSourceInfoIfNeed;
- (BOOL)isShootEnterFromGroot;
- (id)uploadOriginsString;
- (id)autoCaptionTemplateIdsFromMetadata;
- (id)autoCaptionTemplateNamesFromMetadata;
- (void)saveToBeUploadedImage:(id)a0 needSync:(BOOL)a1;
- (id)firstValidOriginalResolution;
- (void)updateExtraDictResolution;
- (void).cxx_destruct;
- (id)init;
- (id)copyWithZone:(struct _NSZone { } *)a0;

@end
