@class AWEAwemeModel, _TtC23AWERelatedRecommendImpl31RelatedRecommendDCDataProcessor, UINavigationController, AWEPageContext, DUXPartialSheet, AWEListDataController, AWERelatedRecommendViewController, _TtC23AWERelatedRecommendImpl30VideoDeconstructGuessWordModel;
@protocol AWERelatedRecommendListBaseDataControllerProtocol, AWEPlayInteractionContextProtocol;

@interface AWERelatedRecommendPanelManager : NSObject <AWERelatedRecommendViewControllerDelegate, DUXPartialSheetDelegate, AWERelatedRecommendPanelManagerProtocol> {
    void /* unknown type, empty encoding */ $__lazy_storage_$_outerDataController;
    void /* unknown type, empty encoding */ $__lazy_storage_$_topView;
    void /* unknown type, empty encoding */ panelShowing;
    void /* unknown type, empty encoding */ panelHasFloded;
    void /* unknown type, empty encoding */ didLoadNoMoreData;
    void /* unknown type, empty encoding */ isVideoPause;
    void /* unknown type, empty encoding */ topViewShowing;
    void /* unknown type, empty encoding */ fullScreenTopPadding;
    void /* unknown type, empty encoding */ $__lazy_storage_$_deviceOrientation;
    void /* unknown type, empty encoding */ tabPanelViewController;
    void /* unknown type, empty encoding */ $__lazy_storage_$_sheetHeight;
    void /* unknown type, empty encoding */ $__lazy_storage_$_dataProcessor;
    void /* unknown type, empty encoding */ _videoIsPlayWhenEnterPage;
    void /* unknown type, empty encoding */ closeType;
    void /* unknown type, empty encoding */ hasSlideTracked;
    void /* unknown type, empty encoding */ isEnterInner;
    void /* unknown type, empty encoding */ fetchSuccess;
    void /* unknown type, empty encoding */ floatZero;
    void /* unknown type, empty encoding */ beginMoveDistance;
    void /* unknown type, empty encoding */ handleViewHeight;
    void /* unknown type, empty encoding */ $__lazy_storage_$_businessStrategy;
    void /* unknown type, empty encoding */ enableLimitDistance;
    void /* unknown type, empty encoding */ gestureDir;
    void /* unknown type, empty encoding */ padPanelHasTransitionSize;
    void /* unknown type, empty encoding */ padPanelHasDismiss;
}

@property (nonatomic) BOOL videoIsPlayWhenEnterPage;
@property (nonatomic, retain) AWEListDataController<AWERelatedRecommendListBaseDataControllerProtocol> *outerDataController;
@property (nonatomic) BOOL panelHasExpanded;
@property (nonatomic, readonly) AWEPageContext<AWEPlayInteractionContextProtocol> *context;
@property (nonatomic, weak) void /* function */ container;
@property (nonatomic, readonly) AWEAwemeModel *currentModel;
@property (nonatomic, weak) void /* function */ delegate;
@property (nonatomic, retain) DUXPartialSheet *sheet;
@property (nonatomic, retain) UINavigationController *navigationViewController;
@property (nonatomic, retain) AWERelatedRecommendViewController *panelViewController;
@property (nonatomic, retain) _TtC23AWERelatedRecommendImpl30VideoDeconstructGuessWordModel *videoDeconstructGuessWordModel;
@property (nonatomic, retain) _TtC23AWERelatedRecommendImpl31RelatedRecommendDCDataProcessor *dataProcessor;

+ (double)enterTimestamp;

- (id)referString;
- (long long)workingRangeSize;
- (id)enterMethod;
- (void)enterInner;
- (void)backToPanel;
- (void)updateCloseType:(long long)a0;
- (void)scrollViewScroll:(id)a0 isScrollViewDidScrollCallback:(BOOL)a1;
- (double)sheetOriginHeight;
- (void)updateFetchStateWithSuccess:(BOOL)a0;
- (BOOL)panelIsShowing;
- (BOOL)panedIsExpanded;
- (BOOL)isMentionDataPreloading;
- (id)recommendPageReferString;
- (BOOL)dcFeed:(id)a0 handleRouterEventWithEventType:(unsigned long long)a1 awemeModel:(id)a2;
- (Class)dcFeedCustomCellWithModel:(id)a0 context:(id)a1;
- (id)dcFeedCustomTrackParamsWithModel:(id)a0 eventName:(id)a1;
- (id)dcFeedClientShowTrackParamsWithModel:(id)a0;
- (id)dcFeedClientClickTrackParamsWithModel:(id)a0;
- (id)dcFeedCommonTrackParamsWithModel:(id)a0;
- (id)dcFeedAutoPlayConfig;
- (BOOL)dcFeedClientShouldShowDislikeVC;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })relatedRecommendCollectionViewFrameWithBounds:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (BOOL)topViewShow;
- (double)topViewHeight;
- (double)sheetMaximimContentHeight;
- (double)sheetMinimumContentHeight;
- (void)back;
- (void)searchAction;
- (void)appWillResignActiveNotification;
- (void)appDidBecomeActiveNotification;
- (void)returnAction;
- (void)orientationChanged;
- (void)partialSheetDidDismiss:(id)a0;
- (void)partialSheet:(id)a0 didChangeFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1 withUserInteraction:(BOOL)a2;
- (void)partialSheetWillFloded:(id)a0;
- (void)partialSheetDidExpanded:(id)a0;
- (void)partialSheetDidClickMaskArea:(id)a0;
- (void)partialSheetWillDismiss:(id)a0;
- (void)partialSheetDidDragToExpanded:(id)a0;
- (BOOL)partialSheet:(id)a0 gestureRecognizer:(id)a1 shouldBeRequiredToFailByGestureRecognizer:(id)a2;
- (BOOL)partialSheet:(id)a0 gestureRecognizerShouldBegin:(id)a1;
- (void)partialSheetDidClickHandleView:(id)a0;
- (void)partialSheetDragWithHandAnimationDir:(unsigned long long)a0 distance:(double)a1 isPanelEnd:(BOOL)a2;
- (void)partialSheet:(id)a0 willTransitionToSize:(struct CGSize { double x0; double x1; })a1 withCoordinator:(id)a2;
- (void)partialSheetShow;
- (BOOL)isPanelShowing;
- (void)padDismissPanelIfNeeded;
- (void)showRelatedRecommendPanel;
- (void)tryPreloadRelatedVideosWithPreloadType:(unsigned long long)a0;
- (double)originShrinkVideoHeight;
- (void)dismissPanelIfNeeded;
- (id)initWithContext:(id)a0 container:(id)a1 currentModel:(id)a2 delegate:(id)a3;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end
