@class UIView, AWEAwemeModel, AWEDoubleColumnSearchMerchandiseModel, NSString, AWEGradientView, UIImageView, UIButton, NSDictionary, AWESearchAdProductView, UIVisualEffectView, UILabel;
@protocol AWEAdEndorseLiveTipsView, AWEAdSearchVideoViewProtocol, AWESearchLiveViewProtocol, AWESearchECardTracker;

@interface AWESearchAdVideoCell : AWESearchCachalotECommerceBaseCell <AWESearchVideoViewPlayerDelegate, AWEAdSearchVideoViewToDetailProtocol, AWESearchAdProductViewDelegate, AWESearchLiveViewPlayerDelegate, AWEMSearchAutoPlayCard>

@property (retain, nonatomic) UIView<AWESearchLiveViewProtocol> *liveView;
@property (retain, nonatomic) UIView<AWEAdSearchVideoViewProtocol> *videoView;
@property (retain, nonatomic) UILabel *adTagLabel;
@property (retain, nonatomic) UIView<AWEAdEndorseLiveTipsView> *liveStatusInfoView;
@property (retain, nonatomic) UIImageView *liveTagView;
@property (retain, nonatomic) AWESearchAdProductView *productView;
@property (retain, nonatomic) UIVisualEffectView *productEffectView;
@property (retain, nonatomic) UIView *bottomProductInfoView;
@property (retain, nonatomic) UILabel *bottomProductInfoLabel;
@property (retain, nonatomic) UIButton *bottomProductInfoButton;
@property (retain, nonatomic) AWEGradientView *bottomGradientView;
@property (nonatomic) BOOL isActive;
@property (readonly, nonatomic) BOOL isShowVideoView;
@property (readonly, nonatomic) BOOL isShowLiveView;
@property (readonly, nonatomic) BOOL isShowEcommerceLiveView;
@property (retain, nonatomic) AWEDoubleColumnSearchMerchandiseModel *searchMerchandiseModel;
@property (readonly, nonatomic) AWEAwemeModel *aweme;
@property (copy, nonatomic) NSDictionary *searchParams;
@property (retain, nonatomic) id<AWESearchECardTracker> searchTracker;
@property (nonatomic) double livePlayDuration;
@property (nonatomic) BOOL isCachalotSearchView;
@property (readonly, nonatomic) id transitionContext;
@property (nonatomic) BOOL isFromECommerce;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) BOOL needPlayFinish;
@property (readonly, nonatomic) double playInterval;
@property (copy, nonatomic) id /* block */ playDidFinishBlock;

+ (double)heightForModel:(id)a0 containerWidth:(double)a1;
+ (struct CGSize { double x0; double x1; })sizeWithViewModel:(id)a0 width:(double)a1;
+ (id)identifier;

- (long long)currentThemeStyle;
- (void)didPlayError:(id)a0;
- (void)didStartStall;
- (void)configWithModel:(id)a0;
- (void)configUI;
- (void)p_stop;
- (void)p_play;
- (void)enterLiveRoom;
- (void)trackWithLabel:(id)a0 refer:(id)a1 adExtraData:(id)a2;
- (void)jumpToAwemeFeed;
- (void)trackAdShow;
- (id)livePlayerView;
- (void)configSearchTracker:(id)a0;
- (void)setSearchInfoDict:(id)a0;
- (void)recordDidEndDisplaying;
- (void)trackWithLabel:(id)a0;
- (void)p_configAdTagLabel;
- (void)addCornerRadiusWithView:(id)a0 corners:(unsigned long long)a1 cornerRadii:(struct CGSize { double x0; double x1; })a2;
- (id)trackEcommerceCommonParamsWithNeedLogExtra:(BOOL)a0;
- (void)trackEcommerceUserEvent:(id)a0;
- (id)trackEcommerceCommonParams;
- (void)p_configUIInfoModel;
- (void)openPageWithSearchShopInfo;
- (double)productViewHeightWithModel:(id)a0;
- (void)p_configProductView;
- (void)p_configBottomProducInfoView;
- (void)p_configVideoView;
- (void)p_configLiveView;
- (void)trackEcommerceUserEvent:(id)a0 refer:(id)a1 partType:(long long)a2;
- (void)enterRoomWithProductId:(id)a0;
- (void)trackWithLabel:(id)a0 refer:(id)a1;
- (void)liveViewTapGR:(id)a0;
- (void)bottomProductInfoTapGR:(id)a0;
- (void)didBecomeActive;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (void)didEnd;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)didResignActive;
- (id)componentView;
- (id)activeView;
- (void)didStart;
- (void)updateWithViewModel:(id)a0;
- (void)didSelectItemAtIndexPath:(id)a0;
- (void)resetPlayer;
- (void)didStop;
- (void)didPause;
- (id)livePlayer;

@end
