@class UIView, ACCPanelHandlebarView, AWEStickerPickerSugView, AWEStickerPickerHashtagView, NSString, AWEStickerPickerStickerBaseCell, AWEStickerPickerSearchBar, UICollectionView, UITextField, UILabel;
@protocol ACCLoadingViewProtocol, AWEStickerPickerUIConfigurationProtocol, ACCGenericEffectCategoryModel, ACCGenericEffectPanelSearchService;

@interface AWEStickerPickerSearchView : UIView <AWEStickerPickerSearchBarDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, AWEStickerPickerCollectionViewCellDelegate, AWEStickerPickerHashtagViewDelegate, AWEStickerPickerSugViewDelegate, AWEStickerPickerSearchViewProtocol>

@property (retain, nonatomic) UIView *backgroundView;
@property (retain, nonatomic) ACCPanelHandlebarView *handlebarView;
@property (retain, nonatomic) AWEStickerPickerSearchBar *searchBar;
@property (retain, nonatomic) UIView<ACCLoadingViewProtocol> *loadingView;
@property (retain, nonatomic) UIView *loadingContainerView;
@property (retain, nonatomic) UILabel *emptyLabel;
@property (retain, nonatomic) AWEStickerPickerHashtagView *hashtagsView;
@property (retain, nonatomic) AWEStickerPickerSugView *sugView;
@property (retain, nonatomic) UICollectionView *collectionView;
@property (retain, nonatomic) id<AWEStickerPickerUIConfigurationProtocol> UIConfig;
@property (retain, nonatomic) AWEStickerPickerStickerBaseCell *currentSelectedCell;
@property (nonatomic) BOOL isTab;
@property (nonatomic) BOOL isUseHot;
@property (nonatomic) BOOL isFirst;
@property (readonly, nonatomic) UITextField *textField;
@property (retain, nonatomic) id<ACCGenericEffectPanelSearchService> model;
@property (retain, nonatomic) id<ACCGenericEffectCategoryModel> categoryModel;
@property (nonatomic) unsigned long long source;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (double)panelHeight;
- (void)updateSearchSource:(unsigned long long)a0;
- (void)addNotifications;
- (void)refreshView;
- (void)showLoadingView:(BOOL)a0;
- (void)updateUIConfig:(id)a0;
- (void)showEmptyView:(BOOL)a0;
- (BOOL)supportSearchSuggestWords;
- (void)fetchSearchSugWithText:(id)a0;
- (void)searchWithText:(id)a0 source:(unsigned long long)a1;
- (void)updateCategoryModel:(id)a0 isUseHot:(BOOL)a1;
- (void)textFieldBecomeFirstResponder;
- (void)enableCollectionViewToScroll:(BOOL)a0;
- (void)trackRecommendedListDidShow;
- (void)scrollToItemAtSection:(unsigned long long)a0 index:(unsigned long long)a1 animated:(BOOL)a2;
- (void)p_configLoading:(BOOL)a0;
- (BOOL)stickerPickerCollectionViewCell:(id)a0 isStickerSelected:(id)a1;
- (void)stickerPickerCollectionViewCell:(id)a0 didSelectSticker:(id)a1 category:(id)a2 indexPath:(id)a3;
- (void)stickerPickerCollectionViewCell:(id)a0 willDisplaySticker:(id)a1 indexPath:(id)a2;
- (void)stickerPickerCollectionViewCell:(id)a0 scrollViewWillBeginDragging:(id)a1;
- (void)updateSelectedStickerForId:(id)a0;
- (id)initWithIsTab:(BOOL)a0;
- (void)scrollToItemAtSection:(unsigned long long)a0 index:(unsigned long long)a1 offset:(double)a2 animated:(BOOL)a3;
- (void)onClearBGClicked;
- (void)triggerKeyboardToHide;
- (void)updateSugList;
- (void)stickerPickerHashtagView:(id)a0 didSelectCellWithTitle:(id)a1 indexPath:(id)a2;
- (void)needsShowCollectionView;
- (void)showHashtagsView:(BOOL)a0;
- (void)showSugView:(BOOL)a0;
- (void)showCollectionView:(BOOL)a0;
- (double)firstResponderHeight;
- (void)keyboardFrameChange:(id)a0;
- (void)p_cancelSearch;
- (void)p_clearSearchText;
- (void)didTapSearchTabTextField:(id)a0;
- (void)stickerPickerSugView:(id)a0 didSelectCellWithTitle:(id)a1 indexPath:(id)a2;
- (void)showHandlebar;
- (void)p_hideIpadKeyboard;
- (void).cxx_destruct;
- (void)searchBar:(id)a0 textDidChange:(id)a1;
- (BOOL)textFieldShouldEndEditing:(id)a0;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 sizeForItemAtIndexPath:(id)a2;
- (void)keyboardWillShow:(id)a0;
- (BOOL)textFieldShouldReturn:(id)a0;
- (id)collectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (long long)collectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (void)keyboardWillHide:(id)a0;
- (void)updateSubviewsAlpha:(double)a0;
- (void)collectionView:(id)a0 willDisplayCell:(id)a1 forItemAtIndexPath:(id)a2;
- (BOOL)textFieldShouldClear:(id)a0;
- (void)textFieldDidBeginEditing:(id)a0;
- (void)layoutSubviews;
- (void)dealloc;
- (void)setupSubviews;
- (void)updateSearchText:(id)a0;
- (void)textFieldResignFirstResponder;

@end
