@class NSHashTable, NSString, UICollectionViewFlowLayout, AWETeenProfilePreloadHandler, AWETeenUserLikesDataManager, AWEUILoadingView, AWEUserModel, NSDictionary, UICollectionView, AWEFeedRefreshFooter, NSNumber, NSIndexPath;
@protocol AWEUserProfileTabVCDelegate;

@interface AWETeenLikeWorkViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, AWEPreviewable, AWEZoomTransitionOuterContextProvider, AWETeenSubscribeMessage, AWETeenBlockMessage, AWETeenCollectMessage, AWEUserProfileTabBaseMethod>

@property (nonatomic) BOOL initialLoadMoreEnabled;
@property (retain, nonatomic) AWETeenUserLikesDataManager *dataManager;
@property (retain, nonatomic) AWEUILoadingView *loadingView;
@property (nonatomic) struct CGPoint { double x; double y; } savedContentOffset;
@property (nonatomic) BOOL needReloadAfterUserDigg;
@property (nonatomic) BOOL isTabShowing;
@property (retain, nonatomic) NSString *likePermissionEmptyText;
@property (retain, nonatomic) NSHashTable *animatedCoverCells;
@property (nonatomic) BOOL isLikeUnaccessible;
@property (retain, nonatomic) AWEFeedRefreshFooter *footer;
@property (retain, nonatomic) UICollectionViewFlowLayout *layout;
@property (nonatomic) BOOL selecting;
@property (nonatomic) BOOL showCleanSuccessInEmptyPage;
@property (retain, nonatomic) AWETeenProfilePreloadHandler *preloadHandler;
@property (copy, nonatomic) NSIndexPath *currentSelectedIndexPath;
@property (retain, nonatomic) UICollectionView *collectionView;
@property (copy, nonatomic) NSString *userID;
@property (nonatomic) BOOL isCurrentUser;
@property (nonatomic) BOOL fromHome;
@property (copy, nonatomic) NSString *referString;
@property (copy, nonatomic) NSString *enterPosition;
@property (retain, nonatomic) NSNumber *likeCount;
@property (retain, nonatomic) NSNumber *allLikeCount;
@property (retain, nonatomic) AWEUserModel *user;
@property (weak, nonatomic) id<AWEUserProfileTabVCDelegate> delegate;
@property (copy, nonatomic) NSDictionary *logExtraDict;
@property (copy, nonatomic) NSString *enterMethod;
@property (copy, nonatomic) NSDictionary *searchLogPassback;
@property (nonatomic) BOOL isProfileDidAppear;
@property (copy, nonatomic) id /* block */ cleanInvalidItemsFinishedBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSDictionary *zoomTransitionContext;

- (id)aweui_emptyPageConfigForState:(unsigned long long)a0;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })aweui_emptyPageEdgeInsets;
- (id)zoomTransitionStartViewForOffset:(long long)a0;
- (double)contentOffsetY;
- (void)adjustContentOffset:(struct CGPoint { double x0; double x1; })a0 animated:(BOOL)a1;
- (double)contentSizeHeight;
- (void)backBtnClicked:(id)a0;
- (id)initWithUserID:(id)a0;
- (BOOL)shouldHideNoMoreText;
- (id)p_invalidItemTextWithCleanButton;
- (id)p_invalidItemCleanLabel;
- (id)previewingViewControllerForView:(id)a0 atPoint:(struct CGPoint { double x0; double x1; })a1;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })previewingSourceRectForView:(id)a0 atPoint:(struct CGPoint { double x0; double x1; })a1;
- (void)p_endRefreshingWithMore:(BOOL)a0 list:(id)a1 error:(id)a2;
- (void)p_updateViewControllerState:(unsigned long long)a0;
- (BOOL)p_shouldUseFooterPlaceholderForState:(unsigned long long)a0;
- (void)_startTimingForTrack;
- (void)_trackEventForStayTime;
- (id)currentSelectedPathWithOffset:(long long)a0;
- (void)didUpdateSubscribeStatus:(long long)a0 secUserID:(id)a1;
- (void)didUpdateBlockStatus:(long long)a0 secUserID:(id)a1;
- (void)didFinishCollectWithItemID:(id)a0 actionType:(unsigned long long)a1 collectCount:(id)a2;
- (void)handleVideoDiggedNotification:(id)a0;
- (void)scrollViewWillBeginDragging:(id)a0 referString:(id)a1;
- (void)refreshLikePermissionEmptyText;
- (void)checkLikePermissionEmptyText;
- (BOOL)p_hasHidingInvalidItem;
- (BOOL)p_canClearInvalidItem;
- (void)preloadVideosIfNeeded;
- (void)p_showDeleteAllInvalidItemAlert:(BOOL)a0;
- (BOOL)shouldfilterDeleteItems;
- (void)deleteLikeWorkWithAweme:(id)a0;
- (id)likeAwemeDetailTableVCWithModel:(id)a0 itemIndex:(long long)a1;
- (void)_loadMoreData;
- (void)_refreshData;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 referenceSizeForFooterInSection:(long long)a2;
- (void)reloadData;
- (void)scrollViewDidScrollToTop:(id)a0;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (id)contentView;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 referenceSizeForHeaderInSection:(long long)a2;
- (id)collectionView:(id)a0 viewForSupplementaryElementOfKind:(id)a1 atIndexPath:(id)a2;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 sizeForItemAtIndexPath:(id)a2;
- (void)removeAll;
- (void)viewDidLayoutSubviews;
- (id)collectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (long long)collectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (void)applicationWillResignActive;
- (void)collectionView:(id)a0 didSelectItemAtIndexPath:(id)a1;
- (void)collectionView:(id)a0 willDisplayCell:(id)a1 forItemAtIndexPath:(id)a2;
- (void)viewWillAppear:(BOOL)a0;
- (void)scrollViewDidScroll:(id)a0;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })a0 withTransitionCoordinator:(id)a1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(BOOL)a0;
- (void)scrollViewDidEndScrollingAnimation:(id)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)refreshData;
- (double)footerInset;
- (void)_setupUI;
- (id)tabName;

@end
