@class AWETeenAgeGuideManager, AWETeenCollectWorkViewController, AWESlidingTabbarView, AWETeenUserHomeMoreButton, AWETeenPrivateWorkViewController, MASConstraint, UIView, AWETeenUserProfileTabHelper, AWETeenLikeWorkViewController, NSString, AWETeenUserProfileSlidingViewController, AWETeenProfileHeaderViewController, AWETeenProfileSettingSliderViewController, AWEUserModel, AWETeenModeFastEntryButton;

@interface AWETeenUserHomeViewController : UIViewController <AWEUserMessage, AWETeenUserMessage, AWEUserProfileTabVCDelegate, AWESlidingViewControllerDelegate, AWETeenUserProfileSlidingScrollViewDelegate, UIGestureRecognizerDelegate, AWETeenProfileHeaderViewControllerDelegate, AWEHeaderViewActionDelegate, AWETeenCollectMessage, AWETeenAlbumCollectMessage, AWEPadUITrackerProtocol, AWERouterViewControllerProtocol>

@property (retain, nonatomic) AWESlidingTabbarView *tabView;
@property (retain, nonatomic) AWETeenUserProfileSlidingViewController *slidingVC;
@property (retain, nonatomic) AWETeenLikeWorkViewController *likeVC;
@property (retain, nonatomic) AWETeenCollectWorkViewController *collectionVC;
@property (retain, nonatomic) AWETeenPrivateWorkViewController *privateWorkVC;
@property (retain, nonatomic) AWETeenUserProfileTabHelper *tabHelper;
@property (retain, nonatomic) AWETeenProfileHeaderViewController *profileHeaderVC;
@property (retain, nonatomic) AWETeenUserHomeMoreButton *moreFuncButton;
@property (retain, nonatomic) UIView *moreFuncBackgroundView;
@property (retain, nonatomic) UIView *notationDotView;
@property (retain, nonatomic) MASConstraint *navRightViewToSearch;
@property (retain, nonatomic) MASConstraint *navRightViewToMore;
@property (retain, nonatomic) AWETeenModeFastEntryButton *fastEntryButton;
@property (retain, nonatomic) AWETeenAgeGuideManager *ageGuideManager;
@property (retain, nonatomic) AWETeenProfileSettingSliderViewController *profileSettingSliderVC;
@property (retain, nonatomic) UIView *settingSliderMenuView;
@property (retain, nonatomic) UIView *redDotView;
@property (readonly, nonatomic) AWEUserModel *user;
@property (nonatomic) BOOL firstLayoutHeader;
@property (nonatomic) BOOL shouldReloadDataAfterAppear;
@property (nonatomic) BOOL alreadyLocateDefaultTab;
@property (nonatomic) BOOL isFirstTimeViewDidLoad;
@property (nonatomic) unsigned long long lastSelectedSlidingTab;
@property (nonatomic) BOOL didRefreshDataAfterEnterHomePage;
@property (nonatomic) BOOL isViewDidAppear;
@property (nonatomic) BOOL showProfileCompletedAnimation;
@property (nonatomic) unsigned long long headerContentStyle;
@property (nonatomic) long long currentTabbarButtonType;
@property (nonatomic) long long currentSelectedIndex;
@property (copy, nonatomic) NSString *referString;
@property (nonatomic) BOOL shouldRefreshAfterDigg;
@property (nonatomic) BOOL enterOtherTab;
@property (nonatomic) BOOL shouldKeepSettingSliderMenuView;
@property (nonatomic) BOOL isSwipeGesture;
@property (nonatomic) BOOL isHorizontalGesture;
@property (nonatomic) BOOL isFirstTimeUpdateUser;
@property (nonatomic) BOOL hasTrackYellowDotEvent;
@property (nonatomic) long long preFavoritePermission;
@property (nonatomic) long long prevContentOffsetY;
@property (nonatomic) double prevGestrueLocationY;
@property (nonatomic) double prevGestrueLocationX;
@property (nonatomic) BOOL animatingForPanGesture;
@property (nonatomic) BOOL needShowBannedAlert;
@property (nonatomic) struct CGSize { double width; double height; } transitionToSize;
@property (nonatomic) BOOL isForcePrivateWorkTab;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy, nonatomic) NSString *awe_padUITrackerPageEnterFrom;
@property (nonatomic) BOOL awe_padUITrackerIgnoreStayTime;

+ (Class)aAWEPadModuleAdapterClass;
+ (Class)aAWEChildModeModuleServiceCommonAdapterClass;

- (void)didFinishLoginWithUid:(id)a0;
- (void)didFinishLogoutWithUid:(id)a0;
- (void)didFinishUpdateCurrentFullUserForReason:(unsigned long long)a0;
- (BOOL)configWithRouterParamDict:(id)a0;
- (BOOL)awe_shouldAutorotate;
- (unsigned long long)awe_supportedInterfaceOrientations;
- (long long)numberOfControllers:(id)a0;
- (id)slidingViewController:(id)a0 viewControllerAtIndex:(long long)a1;
- (void)slidingViewController:(id)a0 didSelectIndex:(long long)a1 transitionType:(long long)a2;
- (id)awesst_enterFrom;
- (void)awe_themeReload;
- (id)aAWEPadModuleAdapter;
- (id)currentScrollView;
- (void)userProfileTabVC:(id)a0 didScroll:(struct CGPoint { double x0; double x1; })a1;
- (struct CGPoint { double x0; double x1; })contentOffsetOfCurrentVC;
- (double)maxBannerHeight;
- (id)userForTabVC;
- (double)userProfileTabHeight;
- (void)userProfileTabViewControllerWillBeginDragging:(id)a0;
- (void)p_trackShow;
- (id)aAWEChildModeModuleServiceCommonAdapter;
- (void)tabBarDidChangeNotification:(id)a0;
- (void)addNavigationBar;
- (BOOL)isShowSliderMenuView;
- (void)handleHideSliderPanGesture:(id)a0;
- (void)_updateTabBarSnapshot;
- (double)headerViewVisibleHeight;
- (id)p_tabVCForType:(long long)a0;
- (void)didUpdateAlbumCollectStatus:(long long)a0 albumID:(id)a1;
- (void)p_tryToShowAlbumCollectRedDot;
- (void)didFinishCollectWithItemID:(id)a0 actionType:(unsigned long long)a1 collectCount:(id)a2;
- (void)changeSlidingTabWithLocation:(struct CGPoint { double x0; double x1; })a0;
- (void)didFinishUpdateMinorAwemeUser;
- (void)handleFixHeaderScrollPanGesture:(id)a0;
- (void)updateHeaderHeight;
- (void)willTerminateAPP:(id)a0;
- (void)p_refreshUserData;
- (void)removeSettingSliderMenu;
- (void)_refreshLikeWork;
- (void)showSliderMenu:(BOOL)a0 animation:(BOOL)a1 highlightItemType:(long long)a2;
- (void)p_decreaseMemory;
- (void)__updateViewForRotateToSize:(struct CGSize { double x0; double x1; })a0;
- (void)p_showUserBannedAlert:(id)a0;
- (void)p_updateCompletionPercent;
- (void)_refreshHeaderViewAfterFetchUser:(id)a0;
- (void)didDiggAweme:(id)a0;
- (void)shouldChangeLanguage:(id)a0;
- (void)didEnterProfileEditVC:(id)a0;
- (void)shouldRefreshDataAfterEnter:(id)a0;
- (void)sliderMenuButtonClicked:(id)a0;
- (void)didCompleteProfileInfo;
- (void)updateUserInfo;
- (void)didSelectTabViewButtonAgainAtIndex:(long long)a0;
- (void)_refreshHeaderViewAlpha;
- (void)updateHeaderViewFrameWithOffset:(struct CGPoint { double x0; double x1; })a0;
- (void)updateContentThemeWithOffset:(struct CGPoint { double x0; double x1; })a0;
- (void)refreshHeaderHeight:(BOOL)a0 animateChildVCs:(BOOL)a1;
- (void)p_addLocksToTab;
- (void)animateChildVCs;
- (void)refreshAlphaOfNavibar:(double)a0;
- (void)showSliderTrackerWithEnterMethod:(id)a0;
- (void)handlePanGestureIfSliderShow:(BOOL)a0 gestureRecognizer:(id)a1;
- (void)showProfileSettingSliderVC;
- (void)sliderMenuAnimationWithOriginX:(double)a0 duration:(double)a1 showSlider:(BOOL)a2 removeSliderVC:(BOOL)a3 needTracker:(BOOL)a4 highlightItemType:(long long)a5;
- (void)addProfileSettingSliderVC;
- (void)openTeenEntrancePage;
- (void)openEyeProtectionPage;
- (double)fixTabScrollViewContentOffsetIfNeeded;
- (void)fastEntryButtonTapped:(id)a0;
- (void)p_fixOtherVCOffset:(double)a0;
- (void)_removeObserversAfterMemoryWarning;
- (BOOL)_willShowLocationAlert;
- (BOOL)currentIsBright;
- (BOOL)currentIsDark;
- (void)_refreshData;
- (void)handleShowSliderPanGesture:(id)a0;
- (void)p_setupUI;
- (void)applicationWillResignActive:(id)a0;
- (void)applicationWillEnterForeground:(id)a0;
- (void)_addObservers;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)_removeObservers;
- (BOOL)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (id)user;
- (id)init;
- (double)headerHeight;
- (BOOL)gestureRecognizer:(id)a0 shouldReceiveTouch:(id)a1;
- (void)viewWillAppear:(BOOL)a0;
- (long long)preferredStatusBarUpdateAnimation;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })a0 withTransitionCoordinator:(id)a1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)refreshData;
- (void)doSettings;
- (void)_removeController:(id)a0;
- (void)_resetUI;

@end
