@class NSTimer, UIView, NSString, ACCTextReaderToastView, UIImageView, CAShapeLayer, AWESliderLeft, AWESliderRight, UILabel, UIImpactFeedbackGenerator;
@protocol AWEVideoRangeSliderDelegate;

@interface AWEVideoRangeSlider : UIView <UIGestureRecognizerDelegate>

@property (retain, nonatomic) UIView *topBorder;
@property (retain, nonatomic) UIView *bottomBorder;
@property (retain, nonatomic) UIImageView *cursor;
@property (retain, nonatomic) UIView *bgView;
@property (retain, nonatomic) ACCTextReaderToastView *textReaderHintView;
@property (nonatomic) BOOL hasFeedback;
@property (nonatomic) BOOL hasSelectMask;
@property (retain, nonatomic) UILabel *leftHandlerBottomLabel;
@property (retain, nonatomic) UILabel *rightHandlerBottomLabel;
@property (nonatomic) double lockWidth;
@property (nonatomic) BOOL thumbHandlerMoveTogetherWithGesture;
@property (retain, nonatomic) UIImpactFeedbackGenerator *feedBackGenertor;
@property (nonatomic) BOOL holdLeftToDragOn;
@property (nonatomic) BOOL holdRightToDragOn;
@property (nonatomic) BOOL dragRightControlInsideRange;
@property (nonatomic) BOOL rightThumbFlyToRight;
@property (nonatomic) BOOL leftThumbFlyToLeft;
@property (nonatomic) BOOL animationInFlight;
@property (nonatomic) BOOL rightHandleInPan;
@property (nonatomic) BOOL leftHandleInPan;
@property (retain, nonatomic) CAShapeLayer *cursorLayer;
@property (retain, nonatomic) NSTimer *holdDragOnSliderTimer;
@property (nonatomic) double rightPositionDuringGestureChanging;
@property (nonatomic) BOOL isInSnappingRange;
@property (weak, nonatomic) id<AWEVideoRangeSliderDelegate> delegate;
@property (nonatomic) double leftPosition;
@property (nonatomic) double rightPosition;
@property (nonatomic) double cursorPosition;
@property (nonatomic) double bodyWidth;
@property (nonatomic) double audioDuration;
@property (retain, nonatomic) UILabel *bubleText;
@property (retain, nonatomic) UILabel *draggingBubleText;
@property (retain, nonatomic) AWESliderLeft *leftThumb;
@property (retain, nonatomic) AWESliderRight *rightThumb;
@property (nonatomic) double maxGap;
@property (nonatomic) double minGap;
@property (nonatomic) BOOL cursorCanOverrunMaxGap;
@property (nonatomic) unsigned long long enterFromType;
@property (nonatomic) BOOL showSideHandlerInfo;
@property (nonatomic) BOOL fixedBodyWidthMode;
@property (nonatomic) BOOL isAdapitionOptimize;
@property (readonly, nonatomic) BOOL isActive;
@property (nonatomic) long long rangeChangeCount;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)handleLeftPan:(id)a0;
- (void)handleRightPan:(id)a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 slideWidth:(double)a1 cursorWidth:(double)a2 height:(double)a3 hasSelectMask:(BOOL)a4;
- (void)showVideoIndicator;
- (void)lockSliderWidth;
- (void)hideBorderViews;
- (void)updateVideoIndicatorByPositionV1:(double)a0;
- (void)updateVideoIndicatorByPosition:(double)a0;
- (void)setCursorWidth:(double)a0 height:(double)a1;
- (void)handleCursorPan:(id)a0;
- (void)p_invalidSliderTimer;
- (void)handleSlidePan:(id)a0 forThumbType:(unsigned long long)a1;
- (void)gestureDidBeginByType:(unsigned long long)a0;
- (void)expandRightThumbToRight;
- (void)setTimeLabelWithFeedbackCheck:(BOOL)a0 checkMax:(BOOL)a1;
- (double)validActualLeftPositionForPosition:(double)a0;
- (void)p_toggleToastHidden:(BOOL)a0;
- (void)p_vibrate;
- (void)setTimeLabelWithFeedbackCheck:(BOOL)a0;
- (void)videoRangeChangedByThumbType:(unsigned long long)a0;
- (void)restoreRightThumbBackToNormal;
- (void)gestureDidEndByType:(unsigned long long)a0;
- (void)expandLeftThumbToLeft;
- (double)validActualRightPositionForPosition:(double)a0;
- (void)restoreLeftThumbBackToNormal;
- (id)timeAdjustedStr;
- (id)trimDurationStr;
- (id)rangeSliderTextFormatForDelta:(double)a0;
- (id)formattedStrForDelta:(double)a0;
- (id)timeToStr:(double)a0;
- (void)bubleTextAnimationWithDragging:(BOOL)a0 thumbType:(unsigned long long)a1;
- (void)updateTimeLabelFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 forIPhoneXS:(BOOL)a1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 slideWidth:(double)a1;
- (id)trimIntervalStr;
- (void)hiddenVideoIndicator;
- (void)showSliderAreaShow:(BOOL)a0 animated:(BOOL)a1;
- (void)updateActualLeftPosition:(double)a0;
- (void)updateActualRightPosition:(double)a0;
- (double)getActualLeftPosition;
- (double)getActualRightPosition;
- (double)convertActualPositionWithTime:(double)a0;
- (void)updateSliderWithHeight:(double)a0 cursorHeight:(double)a1;
- (void)unlock;
- (void).cxx_destruct;
- (double)delta;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)dealloc;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)updateTimeLabel;

@end
