@class TTVideoEngine, NSString, NSHashTable, NSLock, UIView, UIImageView, NSDictionary, TTVideoEngineModel;
@protocol BDARLynxContext, TTVideoEngineNetClient;

@interface BDARVPlayer : UIView <BDARLynxPlayer, TTVideoEngineDelegate, TTVideoEngineDataSource, TTVideoEngineResolutionDelegate>

@property (retain, nonatomic) id<BDARLynxContext> lynxContext;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) TTVideoEngine *videoEngine;
@property (retain, nonatomic) TTVideoEngineModel *videoEngineModel;
@property (retain, nonatomic) UIImageView *logoImageView;
@property (copy, nonatomic) NSString *videoID;
@property (nonatomic) BOOL readyForDisplay;
@property (nonatomic) BOOL idleTimerDisabled;
@property (retain, nonatomic) NSHashTable *map;
@property (retain, nonatomic) NSLock *lock;
@property (copy, nonatomic) NSString *fetchUrl;
@property (nonatomic) BOOL isPlaying;
@property (nonatomic) BOOL hasPlayed;
@property (nonatomic) BOOL hasCallBack;
@property (nonatomic) BOOL playBackEnded;
@property (copy, nonatomic) NSDictionary *selectRateInfo;
@property (nonatomic) BOOL looping;
@property (nonatomic) BOOL cacheVideoInfoEnable;
@property (retain, nonatomic) id<TTVideoEngineNetClient> netClient;
@property (readonly, nonatomic) double currentPlaybackTime;
@property (readonly, nonatomic) double duration;
@property (readonly, nonatomic) double playableDuration;
@property (readonly, nonatomic) double durationWatched;
@property (readonly, nonatomic) unsigned long long state;
@property (readonly, nonatomic) long long playbackState;
@property (readonly, nonatomic) unsigned long long loadState;
@property (readonly, nonatomic) BOOL shouldPlay;
@property (readonly, nonatomic) unsigned long long currentResolution;
@property (readonly, nonatomic) UIView *debugInfoView;
@property (nonatomic) BOOL disableSessionDeactive;
@property (nonatomic) BOOL disableSessionBeactive;
@property (nonatomic) BOOL muted;
@property (nonatomic) double playbackSpeed;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)setLogDelegate:(id)a0;
+ (void)setLogFlag:(long long)a0;
+ (id)platform;

- (id)supportedResolutionTypes;
- (void)videoEngineUserStopped:(id)a0;
- (void)videoEngine:(id)a0 playbackStateDidChanged:(long long)a1;
- (void)videoEngine:(id)a0 loadStateDidChanged:(unsigned long long)a1;
- (void)videoEngineDidFinish:(id)a0 error:(id)a1;
- (void)videoEngineDidFinish:(id)a0 videoStatusException:(long long)a1;
- (void)videoEngineCloseAysncFinish:(id)a0;
- (void)videoEngineReadyToDisPlay:(id)a0;
- (void)videoEngine:(id)a0 fetchedVideoModel:(id)a1;
- (void)videoEngineReadyToPlay:(id)a0;
- (void)videoEngine:(id)a0 mdlKey:(id)a1 hitCacheSze:(long long)a2;
- (void)removeTimeObserver;
- (void)setVideoModel:(id)a0;
- (void)setOptionForKey:(long long)a0 value:(id)a1;
- (void)setCurrentPlaybackTime:(double)a0 complete:(id /* block */)a1 renderComplete:(id /* block */)a2;
- (void)setRenderEngine:(unsigned long long)a0;
- (void)configEngine;
- (void)addBackgroundObserver;
- (BOOL)isPlaybackEnded;
- (void)configResolution:(unsigned long long)a0 completion:(id /* block */)a1;
- (void)updatePlaybackTime;
- (void)setVideoID:(id)a0 categoryID:(id)a1 itemID:(id)a2 adID:(id)a3;
- (void)enableGearStrategy;
- (void)setVideoLargeImageUrl:(id)a0;
- (void)beginObservePlayTime;
- (id)urlInfoForResolution:(unsigned long long)a0 videoInfo:(id)a1;
- (id)apiForFetcher:(unsigned long long)a0;
- (void)vodStrategy:(id *)a0 onAfterSelect:(id *)a1 type:(long long)a2 param:(id)a3 userData:(id)a4;
- (void)deactive;
- (void)setHTTPDNSFirst:(BOOL)a0;
- (long long)playPercent;
- (void)setDisableNotificationObserver:(BOOL)a0;
- (void)beactive;
- (void)updatePlaybackTimeWithCurrentPlayBackTime:(double)a0;
- (void)didFinishedWithType:(unsigned long long)a0 error:(id)a1;
- (void)setImageScaleEnable:(BOOL)a0;
- (void)setImageEnhancementEnable:(BOOL)a0;
- (long long)playAPIVersion2;
- (double)deactivateDelay;
- (void)performSelectorAtDelegate:(SEL)a0;
- (void)removeBackgroundObserver;
- (void)registerDelegate:(id)a0;
- (void).cxx_destruct;
- (BOOL)play;
- (void)pause;
- (id)init;
- (void)stop;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)didBecomeActive:(id)a0;
- (void)setOptions:(id)a0;
- (void)unregisterDelegate:(id)a0;
- (void)willResignActive:(id)a0;
- (void)layoutSubviews;
- (void)dealloc;
- (void)prepareToPlay;
- (BOOL)isValidNumber:(double)a0;

@end
