@class NSString, NSDictionary, NSArray, BDPCDDynamicCardParserUtil, BDPCDDynamicCardParserConfig;

@interface BDPCDDynamicCardTemplateModel : NSObject

@property (retain, nonatomic) BDPCDDynamicCardParserUtil *parserUtil;
@property (copy, nonatomic) NSDictionary *nodeDict;
@property (copy, nonatomic) NSDictionary *rootDict;
@property (copy, nonatomic) NSDictionary *originExtDict;
@property (copy, nonatomic) NSDictionary *dynamicData;
@property (nonatomic) BOOL cardHeaderHasEnableQuery;
@property (copy, nonatomic) NSString *customReportParams;
@property (copy, nonatomic) NSString *extDefaultHint;
@property (nonatomic) BOOL needQueryTemplate;
@property (nonatomic) BOOL onlyDealData;
@property (nonatomic) double getModelTimeStart;
@property (copy, nonatomic) NSString *cardID;
@property (copy, nonatomic) NSString *templateType;
@property (copy, nonatomic) NSString *cardEntityType;
@property (copy, nonatomic) NSString *cardSourceScene;
@property (nonatomic) BOOL enableQuery;
@property (nonatomic) BOOL needLowVersionTemplate;
@property (copy, nonatomic) NSString *rawNeedLowVersionTemplate;
@property (copy, nonatomic) NSDictionary *templateModelDict;
@property (nonatomic) long long schemaVersion;
@property (copy, nonatomic) NSString *rawSchemaVersion;
@property (copy, nonatomic) NSString *cardVersion;
@property (copy, nonatomic) NSString *cardType;
@property (copy, nonatomic) NSString *appSDKVersion;
@property (copy, nonatomic) NSDictionary *staticData;
@property (copy, nonatomic) NSArray *containerUIModelArr;
@property (nonatomic) BOOL canParse;
@property (nonatomic) BOOL isSupport;
@property (copy, nonatomic) NSString *unSupportStr;
@property (copy, nonatomic) id /* block */ getLocalDynamicData;
@property (copy, nonatomic) id /* block */ getMergeData;
@property (readonly, copy, nonatomic) NSDictionary *mergeData;
@property (copy, nonatomic) NSString *btmCid;
@property (copy, nonatomic) NSString *unitBtmIdStr;
@property (nonatomic) long long cardState;
@property (copy, nonatomic) id /* block */ btnTapCallback;
@property (copy, nonatomic) id /* block */ asyncGetTemplateModelCallback;
@property (copy, nonatomic) id /* block */ transferSchemaWithBtmIDCallback;
@property (copy, nonatomic) id /* block */ trackerBcmChainsWithBtmIDCallback;
@property (copy, nonatomic) id /* block */ transferSchemaCallback;
@property (copy, nonatomic) id /* block */ inputActionCallback;
@property (copy, nonatomic) id /* block */ fetchDataAndUpdateCardViewCallback;
@property (copy, nonatomic) id /* block */ updateCardViewCallback;
@property (copy, nonatomic) id /* block */ fetchDataWithExtraAndUpdateCardViewCallback;
@property (copy, nonatomic) id /* block */ dealBtmCustomActionCallback;
@property (copy, nonatomic) id /* block */ dealNoBtmCidCallback;
@property (copy, nonatomic) id /* block */ dealOpenSkuSelectPanelActionCallBack;
@property (copy, nonatomic) id /* block */ dealMakeTrackerActionCallBack;
@property (copy, nonatomic) id /* block */ updateLocalDataActionCallback;
@property (copy, nonatomic) id /* block */ appendCustomActionListCallback;
@property (copy, nonatomic) id /* block */ dealCustomActionResultCallback;
@property (nonatomic) BOOL openWindowAndRefresh;
@property (retain, nonatomic) BDPCDDynamicCardParserConfig *config;
@property (copy, nonatomic) NSString *buttonNamesStr;
@property (copy, nonatomic) id /* block */ errorTrackCallback;
@property (nonatomic) long long templateModelFromType;

+ (BOOL)validateResponse:(id)a0;
+ (id)messageFromResponse:(id)a0;

- (void)dealCustomActionWithCustomActionList:(id)a0 contextDict:(id)a1;
- (void)fetchDynamicDataWithIdentifier:(id)a0 completion:(id /* block */)a1;
- (id)initWithExtDict:(id)a0 config:(id)a1;
- (BOOL)needExposureCallback;
- (void)dealDynamicCardExposureCallbackWithComplation:(id /* block */)a0;
- (void)checkMetaParamsAndTrackError;
- (void)dealCustomActionWithCustomActionList:(id)a0 contextDict:(id)a1 clickUUID:(id)a2;
- (void)rebindCardUIModelArr;
- (void)fetchDynamicDataWithIdentifier:(id)a0 extraBody:(id)a1 extraParams:(id)a2 extraHeader:(id)a3 completion:(id /* block */)a4;
- (id)initWithExtDict:(id)a0 config:(id)a1 onlyDealData:(BOOL)a2;
- (void)fetchCardInfoWithExtension:(id)a0 completion:(id /* block */)a1;
- (id)getTemplateModleFromGeckoWithDict:(id)a0 needQueryTemplate:(BOOL)a1;
- (void)trackGetCardTemplateWithIsSuccess:(BOOL)a0;
- (void)initTemplateDict:(id)a0;
- (void)trackGetTemlateErrorWithType:(long long)a0;
- (void)asyncGetTemplateModelFromCDNOrServerWithDict:(id)a0 completion:(id /* block */)a1;
- (void)trackErrorWithOtherParams:(id)a0;
- (id)decodeAbbreviationTemplate:(id)a0;
- (void)updateTemplate:(id)a0 shouldRebind:(BOOL)a1;
- (void)updateTemplateWithDynamicData:(id)a0;
- (id)getAllButtonName:(id)a0;
- (id)getButtonName:(id)a0;
- (void)fetchCardInfoWithExtension:(id)a0 extraBody:(id)a1 extraParams:(id)a2 extraHeader:(id)a3 completion:(id /* block */)a4;
- (void)fetchCardInfoV2WithExtension:(id)a0 extraBody:(id)a1 extraParams:(id)a2 extraHeader:(id)a3 completion:(id /* block */)a4;
- (void)postTemplateCardActionV2WithParams:(id)a0 completion:(id /* block */)a1;
- (id)templateCardActionData:(id)a0;
- (void)updateWithDynamicData:(id)a0 uniqueId:(id)a1;
- (void)dealCustomActionWithCustomActionList:(id)a0 contextDict:(id)a1 clickUUID:(id)a2 needCheckSupportOrNot:(BOOL)a3;
- (void)trackActionParamsErrorWithContextDict:(id)a0 errorActionType:(id)a1 errorProp:(id)a2;
- (void)postTemplateCardActionWithParams:(id)a0 completion:(id /* block */)a1;
- (id)cacheKeyModelWithDict:(id)a0;
- (void)getTemplateModelFromServerWithRequestModel:(id)a0 completion:(id /* block */)a1;
- (void)getTemplateModelFromCDNWithRequestModel:(id)a0 completion:(id /* block */)a1;
- (void)getTemplateModelFromCDNWithCDNTemplateMapping:(id)a0 requestModel:(id)a1 completion:(id /* block */)a2;
- (id)getTemplateModelPathWithRequestModel:(id)a0 templateMapping:(id)a1;
- (id)trackCommonParamsDict;
- (void)updateWithDynamicData:(id)a0;
- (void).cxx_destruct;

@end
