@class CJPayDefaultChannelShowConfig, CJPayVerifySMSHelpModel, UILabel, CJPayBaseVerifyManager, CJPayButton, CJPayChoosedPayMethodViewV3, NSMutableArray, CJPayLabel, CJPayDynamicLayoutView, NSString, CJPayVerifySMSViewModel, CJPayNaviBarTextAction, CJPayAssetPayMethodDetailView, CJPayRoundedBubbleView, NSArray, CJPayMarketingMsgView, CJPayTimer, UIView, CJPayNaviBarImageAction, CJPayVerifyCodeTimerLabel, NSMutableAttributedString, CJPayBDCreateOrderResponse, CJPayGuideWithConfirmView, CJPaySMSInputView, MASConstraint, CJPayStyleErrorLabel;
@protocol CJPayTrackerProtocol;

@interface CJPayHalfVerifySMSViewController : CJPayHalfPageBaseViewController <CJPaySMSInputViewDelegate, CJPayVerifySMSVCProtocol>

@property (retain, nonatomic) CJPayDynamicLayoutView *dynamicContentView;
@property (retain, nonatomic) NSMutableArray *dynamicViewList;
@property (retain, nonatomic) CJPayRoundedBubbleView *roundedView;
@property (retain, nonatomic) CJPayMarketingMsgView *marketingMsgView;
@property (retain, nonatomic) CJPayChoosedPayMethodViewV3 *choosedPayMethodView;
@property (retain, nonatomic) CJPayAssetPayMethodDetailView *payMethodDetailView;
@property (retain, nonatomic) UIView *hintAreaView;
@property (retain, nonatomic) CJPayLabel *titleLabel;
@property (retain, nonatomic) CJPayLabel *subTitleLabel;
@property (retain, nonatomic) CJPayStyleErrorLabel *errorLabel;
@property (retain, nonatomic) UIView *bottomButtonView;
@property (retain, nonatomic) CJPayLabel *protocolLabel;
@property (retain, nonatomic) NSMutableAttributedString *protocolString;
@property (retain, nonatomic) CJPayButton *helpBtn;
@property (retain, nonatomic) CJPayButton *otherVerifyButton;
@property (retain, nonatomic) CJPayNaviBarImageAction *helpBarAction;
@property (retain, nonatomic) CJPayNaviBarTextAction *otherVerifyBarAction;
@property (retain, nonatomic) CJPayGuideWithConfirmView *guideView;
@property (retain, nonatomic) UILabel *tradeNameLabel;
@property (nonatomic) double maxKeyboardHeight;
@property (nonatomic) double lastKeyboardHeight;
@property (retain, nonatomic) MASConstraint *contentBottomOffsetConstraint;
@property (retain, nonatomic) MASConstraint *contentHeightConstraint;
@property (retain, nonatomic) CJPayVerifySMSViewModel *smsViewModel;
@property (nonatomic) BOOL isBaseVerifyProcess;
@property (nonatomic) BOOL isSimpleSMSViewStyle;
@property (nonatomic) BOOL isSwitchToSMS;
@property (nonatomic) BOOL isFirstInputSMSCode;
@property (nonatomic) BOOL isAutoFillInputCode;
@property (nonatomic) double sendSMSCodeTimeInterval;
@property (nonatomic) BOOL needUnchangedHeight;
@property (nonatomic) int codeCount;
@property (nonatomic) unsigned long long bizType;
@property (nonatomic) unsigned long long trackerExecuteTimes;
@property (weak, nonatomic) CJPayBaseVerifyManager *verifyManager;
@property (nonatomic) long long otherVerifyType;
@property (copy, nonatomic) id /* block */ otherVerifyPayBlock;
@property (copy, nonatomic) id /* block */ completeBlock;
@property (copy, nonatomic) NSString *bankCardID;
@property (retain, nonatomic) CJPayVerifySMSHelpModel *helpModel;
@property (retain, nonatomic) CJPayBDCreateOrderResponse *orderResponse;
@property (retain, nonatomic) CJPayDefaultChannelShowConfig *defaultConfig;
@property (copy, nonatomic) NSArray *agreements;
@property (retain, nonatomic) CJPaySMSInputView *smsInputView;
@property (retain, nonatomic) CJPayVerifyCodeTimerLabel *timeView;
@property (weak, nonatomic) CJPayTimer *externTimer;
@property (nonatomic) BOOL textInputFinished;
@property (copy, nonatomic) NSString *signSource;
@property (copy, nonatomic) NSString *verifySource;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<CJPayTrackerProtocol> trackDelegate;
@property (nonatomic) BOOL needSendSMSWhenViewDidLoad;

- (BOOL)supportStdNaviBar;
- (id)cj_performanceMonitorName;
- (BOOL)cj_supportMultiTheme;
- (id)commonTrackParams;
- (void)closeWithAnimation:(BOOL)a0 comletion:(id /* block */)a1;
- (void)p_applicationDidEnterBackground;
- (void)p_applicationDidBecomeActive;
- (void)p_makeConstraints;
- (void)updateTips:(id)a0;
- (void)p_keyboardWillChangeFrame:(id)a0;
- (void)p_trackWithEventName:(id)a0 params:(id)a1;
- (void)p_recordSelectionOriginStatusWithConfig:(id)a0;
- (void)p_refreshPasswordViewWithNoti:(id)a0;
- (void)showKeyBoardView;
- (void)retractKeyBoardView;
- (void)updateErrorText:(id)a0;
- (void)p_changeSelectionItemStatusWithChecked:(BOOL)a0;
- (void)p_setupOtherVerifyType;
- (id)p_getStyleParams;
- (BOOL)p_assetSelectionVoucherStatus:(id)a0;
- (void)p_updateMarketingMsgViewWithShowConfig:(id)a0 voucherType:(id)a1 animated:(BOOL)a2;
- (void)p_refreshGuideView;
- (void)p_setDynamicComponentHiddenStatus;
- (id)p_createDynamicLayoutList;
- (void)p_updateDynamicComponentLayout;
- (id)p_buildGuideProtocolModel;
- (BOOL)unchangedHeightWhenUpdate;
- (unsigned long long)placeholderViewIndex;
- (void)setShouldShowSecondaryTradeName:(BOOL)a0;
- (void)showState:(long long)a0;
- (id)initWithAnimationType:(unsigned long long)a0 withBizType:(unsigned long long)a1;
- (void)gotoNextStep;
- (void)postSMSCode:(id /* block */)a0 failure:(id /* block */)a1;
- (void)p_updateContentWithConfig:(id)a0 extParams:(id)a1;
- (BOOL)p_shouldShowTradeName;
- (BOOL)p_needShowGuideView;
- (void)p_updateContentWithDefaultConfig;
- (void)goToHelpVC;
- (void)tapResendButton;
- (void)didAutoFillInputSMSCode:(id)a0;
- (void)didInputFirstSMSCode;
- (void)didFinishInputSMS:(id)a0;
- (void)didDeleteLastSMS;
- (id)p_defaultDisplayConfigs;
- (void)updateContentWithVoucherSwell:(id)a0;
- (void)p_startTimerWhenViewLoaded;
- (id)p_trackThisMethod;
- (void)p_trackWithBtmEvent:(id)a0 btm:(id)a1 params:(id)a2;
- (void)p_setTopRightButton;
- (void)p_dynamicLayout;
- (void)p_makeTopConstraints;
- (id)p_getTopRightBtnInfo;
- (void)p_makeDynamicConstraints;
- (void)p_createHintAreaView;
- (void)p_createBottomButtonView;
- (double)p_getTimeViewHeight;
- (void)p_postCardSignSMSCode:(id /* block */)a0 failure:(id /* block */)a1;
- (void)recordSendSMSCodeTimeInterval;
- (id)defineButtonInfoActions;
- (BOOL)p_needShowBtnOnGuideView;
- (void)executeCompletionBlock:(BOOL)a0 withContent:(id)a1;
- (id)p_guideViewBtnTextWithChecked:(BOOL)a0;
- (double)p_sideMargin;
- (void)tapProtocolLabel;
- (void)p_guideViewConfirmClick;
- (id)p_trackCampaignInfo:(id)a0;
- (id)initWithAnimationType:(unsigned long long)a0 withModel:(id)a1;
- (void)showHelpInfo:(BOOL)a0;
- (void)p_setupUI;
- (void)clearInput;
- (void)setProtocol:(id)a0;
- (void).cxx_destruct;
- (id)init;
- (void)startLoading;
- (void)viewWillAppear:(BOOL)a0;
- (void)reset;
- (void)stopLoading;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)a0;
- (double)containerHeight;
- (void)back;

@end
