@class UILabel, NSDictionary, CJPaySwitchAreaInfoModel, CJPayBDCreateOrderResponse, CJPayButton, CJPayVerifyPassVCConfigModel, CJPaySafeInputView, CJPayOutDisplayInfoModel, NSString, CJPayErrorInfoActionView, CJPayForgetPwdOptController, NSArray, CJPayVerifyItemRecogFaceOnBioPayment, CJPayDefaultChannelShowConfig, CJPayMarketingMsgView;
@protocol CJPayAssetContextStoreDelegate, CJPayTrackerProtocol;

@interface CJPayVerifyPasswordViewModel : NSObject <CJPaySafeInputViewDelegate>

@property (copy, nonatomic) id /* block */ forgetPasswordBtnBlock;
@property (copy, nonatomic) id /* block */ otherVerifyPayBlock;
@property (copy, nonatomic) id /* block */ inputChangeBlock;
@property (copy, nonatomic) id /* block */ inputCompleteBlock;
@property (copy, nonatomic) id /* block */ faceRecogPayBlock;
@property (weak, nonatomic) id<CJPayTrackerProtocol> trackDelegate;
@property (weak, nonatomic) id<CJPayAssetContextStoreDelegate> contextStoreDelegate;
@property (retain, nonatomic) CJPayBDCreateOrderResponse *response;
@property (retain, nonatomic) CJPayDefaultChannelShowConfig *defaultConfig;
@property (copy, nonatomic) NSArray *displayConfigs;
@property (nonatomic) BOOL hideChoosedPayMethodView;
@property (nonatomic) BOOL cancelRetainWindow;
@property (nonatomic) BOOL cancelDefaultRetainWindow;
@property (nonatomic) BOOL hideMerchantNameLabel;
@property (nonatomic) BOOL hideMarketingView;
@property (nonatomic) BOOL hidePasswordFixedTips;
@property (retain, nonatomic) CJPayVerifyPassVCConfigModel *configModel;
@property (retain, nonatomic) CJPayForgetPwdOptController *forgetPwdController;
@property (retain, nonatomic) CJPayOutDisplayInfoModel *outDisplayInfoModel;
@property (nonatomic) long long passwordInputCompleteTimes;
@property (nonatomic) long long confirmBtnClickTimes;
@property (nonatomic) BOOL isGuideSelected;
@property (nonatomic) BOOL isSwitchFromSMS;
@property (nonatomic) BOOL isSwitchFromPreValidationHub;
@property (nonatomic) BOOL isFromOpenBioPayVerify;
@property (nonatomic) BOOL isStillShowingTopRightBioVerifyButton;
@property (nonatomic) BOOL isBioVerifyFailDowngradePwd;
@property (nonatomic) BOOL isPaymentForOuterApp;
@property (retain, nonatomic) CJPayVerifyItemRecogFaceOnBioPayment *bioVerifyItem;
@property (nonatomic) double passwordViewHeight;
@property (copy, nonatomic) NSString *downgradePasswordTips;
@property (copy, nonatomic) NSString *downgradePasswordIcon;
@property (copy, nonatomic) NSString *bioOptType;
@property (copy, nonatomic) NSString *passwordFixedTips;
@property (copy, nonatomic) NSDictionary *bizParams;
@property (copy, nonatomic) NSDictionary *outerTrackData;
@property (nonatomic) BOOL isDynamicLayout;
@property (nonatomic) BOOL canChangeCombineStatus;
@property (nonatomic) BOOL useStandardKeyboard;
@property (nonatomic) BOOL nonFirstVerifyType;
@property (nonatomic) long long pwdProcessType;
@property (readonly, nonatomic) CJPaySwitchAreaInfoModel *topRightBtnInfo;
@property (retain, nonatomic) UILabel *tipsLabel;
@property (retain, nonatomic) CJPaySafeInputView *inputPasswordView;
@property (retain, nonatomic) CJPayErrorInfoActionView *errorInfoActionView;
@property (retain, nonatomic) CJPayButton *otherVerifyButton;
@property (retain, nonatomic) CJPayButton *forgetPasswordBtn;
@property (retain, nonatomic) CJPayMarketingMsgView *marketingMsgView;
@property (nonatomic) BOOL notShouldBioTips;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)trackWithEventName:(id)a0 params:(id)a1;
- (id)tipText;
- (BOOL)isNeedHideTopLeftBubbleView;
- (BOOL)isPwdResetProcess;
- (void)trackPageClickWithButtonName:(id)a0;
- (id)isFingerprintDefault;
- (id)getBioGuideType;
- (id)getBioGuideTypeStr;
- (void)trackBtmEvent:(id)a0 btm:(id)a1 params:(id)a2;
- (BOOL)isShowComfirmButton;
- (long long)passwordGuideStyle;
- (BOOL)isNeedHideChooseMethodView;
- (void)trackPageClickWithButtonName:(id)a0 params:(id)a1;
- (BOOL)shouldShowTradeName;
- (BOOL)isNeedHideMarketingMsgView;
- (BOOL)isNeedShowGuide;
- (BOOL)shouldShowMerchantName;
- (BOOL)isNeedHideForgetPasswordButton;
- (BOOL)isNeedHideCreditDescriptionRegion;
- (BOOL)isNeedDisableChooseMethod;
- (BOOL)isNeedHideAllForgetPwdBtn;
- (void)inputView:(id)a0 completeInputWithCurrentInput:(id)a1;
- (void)inputView:(id)a0 textDidChangeWithCurrentInput:(id)a1;
- (BOOL)isSuggestCardStyle;
- (BOOL)isHasSuggestCard;
- (id)getSuggestChannelByIndex:(int)a0;
- (void)setShowKeyBoardSafeGuard:(BOOL)a0;
- (void)gotoForgetPwdVCFromVC:(id)a0;
- (void)updateErrorText:(id)a0 withTypeString:(id)a1 currentVC:(id)a2;
- (BOOL)isCombinedPay;
- (void)pageFirstAppear;
- (id)trackActivityLabel;
- (BOOL)p_isShowMarketing;
- (BOOL)isNeedHideAmountAreaListView;
- (BOOL)isNeedHidePasswordFixedTips;
- (id)getSuggestChannelModelList;
- (void)gotoForgetPwdVCFromVC:(id)a0 completion:(id /* block */)a1;
- (BOOL)isBioVerifyAvailable;
- (BOOL)isNeedShowOpenBioGuide;
- (void)p_hideDiscountLabel;
- (id)getGuideChoose;
- (id)p_pwdViewModelTrackParams:(id)a0;
- (id)addObjectWithDeduct:(id)a0;
- (BOOL)isNeedShowFunctionGuide;
- (BOOL)isInvokeScene;
- (void)p_trackForForgetClick;
- (void)p_handleWebViewCloseCallBack:(id)a0 completion:(id /* block */)a1;
- (BOOL)isNeedResignCard;
- (BOOL)isNeedShowChooseMethodView;
- (BOOL)isNeedShowPasswordFixedTips;
- (BOOL)needAfterwardSetPwd;
- (BOOL)needAfterPaySetPwd;
- (void).cxx_destruct;
- (void)reset;

@end
