@interface FlowIMX.FlowIMConversationServiceImpl : NSObject <FlowIMX.FlowIMConversationService, FlowIMX.FlowIMBotConversationService> {
    void /* unknown type, empty encoding */ delegateArray;
    void /* unknown type, empty encoding */ totalUnreadTimer;
    void /* unknown type, empty encoding */ _totalUnreadCount;
    void /* unknown type, empty encoding */ _socialUnreadCount;
    void /* unknown type, empty encoding */ queue;
    void /* unknown type, empty encoding */ isFetchingMainConv;
    void /* unknown type, empty encoding */ recentConvChainFetcher;
}

- (void)asyncGetConversationWithConversationID:(id)a0 callback:(id /* block */)a1;
- (void)refreshConversationMetaInfoBy:(id)a0 extra:(id)a1 success:(id /* block */)a2 fail:(id /* block */)a3;
- (void)asyncGetConversationLastMessageIndexOf:(id)a0 callback:(id /* block */)a1;
- (void)createUserConversationWith:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)createGroupConversationFrom:(id)a0 with:(id)a1 template:(id)a2 localMessages:(id)a3 success:(id /* block */)a4 fail:(id /* block */)a5;
- (void)updateGroupConversationWithConversationID:(id)a0 template:(id)a1 joinedParticipants:(id)a2 deletedParticipants:(id)a3 success:(id /* block */)a4 fail:(id /* block */)a5;
- (void)deleteConversationWith:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)batchDeleteUserConversationWithConversationIds:(id)a0 conversationType:(long long)a1 success:(id /* block */)a2 fail:(id /* block */)a3;
- (void)deleteLocalConversationWith:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)pinWithConversationID:(id)a0 cellType:(long long)a1 success:(id /* block */)a2 fail:(id /* block */)a3;
- (void)unpinWithConversationID:(id)a0 cellType:(long long)a1 success:(id /* block */)a2 fail:(id /* block */)a3;
- (void)updateMuted:(BOOL)a0 for:(id)a1;
- (void)markReadWithConversationID:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)dissolveConversationWithConversationID:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)conversationAutoSpeak:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)clearContextWithConversationID:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)clearHistoryWithConversationID:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)exitWithConversationID:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)getConversationMetaInfoBy:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)getConversationMetaInfoBy:(id)a0 forceRemote:(BOOL)a1 success:(id /* block */)a2 fail:(id /* block */)a3;
- (void)getConversationMetaInfoByBot:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)getConversationMetaInfoByBot:(id)a0 forceRemote:(BOOL)a1 success:(id /* block */)a2 fail:(id /* block */)a3;
- (void)getConversationMetaInfoByBot:(id)a0 extra:(id)a1 forceRemote:(BOOL)a2 success:(id /* block */)a3 fail:(id /* block */)a4;
- (void)refreshConversationMetaInfoBy:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)updateConversationMetaInfoWithConversationID:(id)a0 name:(id)a1 success:(id /* block */)a2 fail:(id /* block */)a3;
- (void)updateConversationMetaInfoWithConversationID:(id)a0 createScene:(long long)a1 success:(id /* block */)a2 fail:(id /* block */)a3;
- (id)getConversationListWithCaller:(id)a0 file:(id)a1;
- (void)asyncGetConversationListWithCallback:(id /* block */)a0;
- (void)getConversationListBy:(id)a0 callback:(id /* block */)a1;
- (void)asyncGetConversationListWithCursor:(id)a0 callback:(id /* block */)a1;
- (void)getConversationBotIDsBy:(id)a0 callback:(id /* block */)a1;
- (id)getConversationWithConversationID:(id)a0 caller:(id)a1 file:(id)a2;
- (long long)getConversationLastMessageIndexOf:(id)a0 caller:(id)a1 file:(id)a2;
- (id)createLocalGroupConversationWithConversationID:(id)a0 name:(id)a1 icon:(id)a2 ext:(id)a3;
- (long long)getTotalUnreadCount;
- (long long)getSocialUnreadCount;
- (long long)getBotUnreadCount;
- (long long)getConversationVersion;
- (void)getAllConversationUnreadWithSuccess:(id /* block */)a0 fail:(id /* block */)a1;
- (void)updateConversationStatusOf:(id)a0 status:(long long)a1 completion:(id /* block */)a2;
- (void)updateForbidSendMsgOf:(id)a0 value:(id)a1;
- (id)createLocalMainBotSubConversationWithRequest:(id)a0;
- (void)requestRecentConvMessagesWithScene:(long long)a0;
- (void)addDelegate:(id)a0;
- (void)removeDelegate:(id)a0;
- (id)mainBotConversation;
- (void)cancelAllChunkServiceWithReq:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)markConversationInOutWithReq:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (id)createLocalBotConversationWithReq:(id)a0;
- (void)getConversationBotIDWithReq:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)autoGenConversationWithReq:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (id)getConversationListWithCursor:(id)a0 caller:(id)a1 file:(id)a2;
- (void)searchLocalDBConversationsWithReq:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)searchLocalDBMessagesWithReq:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)mainBotConversationWithSuccess:(id /* block */)a0 fail:(id /* block */)a1;
- (id)createMainBotSubConversationWithMessageID:(id)a0;
- (id)createMainBotSubConversationWithMessageID:(id)a0 ext:(id)a1 name:(id)a2;
- (void)createMainBotSubConversationWithReq:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2 callback:(id /* block */)a3;
- (void)createMainBotSubConversationWithLocalConversationID:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)createLocalMainBotSubConversationWithReq:(id)a0 callback:(id /* block */)a1;
- (id)createCollectSubConversationWithCollectionId:(id)a0;
- (void)createCollectSubConversationWithCollectionId:(id)a0 callback:(id /* block */)a1;
- (void)createCaseSubConversationWithCaseId:(long long)a0 name:(id)a1 callback:(id /* block */)a2;
- (id)createLocalAndRemoteBotConversationWithReq:(id)a0;
- (void)createLocalAndRemoteBotConversationWithReq:(id)a0 callback:(id /* block */)a1;
- (void)convertLocalConversationToRemoteWithReq:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (void)createBotConversationWithReq:(id)a0 success:(id /* block */)a1 fail:(id /* block */)a2;
- (id)createLocalBotConversationWithBotInfo:(id)a0;
- (void)createLocalBotConversationWithReq:(id)a0 callback:(id /* block */)a1;
- (id)createTempBotConversationWithConversationID:(id)a0 name:(id)a1;
- (id)createTempMainBotSubConversationWithConversationID:(id)a0 iconImage:(id)a1 name:(id)a2 ext:(id)a3;
- (id)getDBBotConversationWithBotID:(id)a0;
- (void)asyncGetDBBotConversationWithBotID:(id)a0 callback:(id /* block */)a1;
- (void)genFakeLocalOnboardingMessageWithConversationId:(id)a0 botId:(id)a1 onboarding:(id)a2 success:(id /* block */)a3 fail:(id /* block */)a4;
- (void)cancelChunkServiceBy:(id)a0;
- (void).cxx_destruct;
- (id)init;

@end
