@class NSData, NSFileHandle, NSString, NSURL, NSDictionary, NSObject, NSURLRequest, GTMSessionFetcher;
@protocol OS_dispatch_queue;

@interface GTMSessionUploadFetcher : GTMSessionFetcher {
    NSObject<OS_dispatch_queue> *_delegateCallbackQueue;
    long long _initialBodyLength;
    long long _initialBodySent;
    NSURL *_uploadLocationURL;
    NSData *_uploadData;
    NSFileHandle *_uploadFileHandle;
    id /* block */ _uploadDataProvider;
    NSURL *_uploadFileURL;
    long long _uploadFileLength;
    NSString *_uploadMIMEType;
    long long _chunkSize;
    BOOL _isPaused;
    BOOL _isRestartedUpload;
    BOOL _useBackgroundSessionOnChunkFetchers;
    NSDictionary *_recentChunkReponseHeaders;
    long long _recentChunkStatusCode;
    GTMSessionFetcher *_fetcherInFlight;
    BOOL _isSubdataGenerating;
    BOOL _isCancelInFlight;
    id /* block */ _cancellationHandler;
}

@property (retain) NSURLRequest *lastChunkRequest;
@property long long currentOffset;
@property (retain) GTMSessionFetcher *fetcherInFlight;
@property (getter=isSubdataGenerating) BOOL subdataGenerating;
@property BOOL shouldInitiateOffsetQuery;
@property long long uploadGranularity;
@property BOOL allowsCellularAccess;
@property (retain) NSURL *uploadLocationURL;
@property (retain) NSData *uploadData;
@property (retain) NSURL *uploadFileURL;
@property (retain) NSFileHandle *uploadFileHandle;
@property (readonly, copy) id /* block */ uploadDataProvider;
@property (copy) NSString *uploadMIMEType;
@property (readonly) long long chunkSize;
@property (retain) GTMSessionFetcher *chunkFetcher;
@property (readonly) GTMSessionFetcher *activeFetcher;
@property long long statusCode;
@property (copy) id /* block */ cancellationHandler;
@property (readonly) NSObject<OS_dispatch_queue> *delegateCallbackQueue;
@property (readonly) id /* block */ delegateCompletionHandler;

+ (void)reconnectFetchersForBackgroundSessionsOnAppLaunch:(id)a0;
+ (id)uploadFetchersForBackgroundSessions;
+ (id)uploadFetcherWithRequest:(id)a0 fetcherService:(id)a1;
+ (id)uploadFetcherWithLocation:(id)a0 uploadMIMEType:(id)a1 chunkSize:(long long)a2 allowsCellularAccess:(BOOL)a3 fetcherService:(id)a4;
+ (id)uploadFetcherPointerArrayForBackgroundSessions;
+ (id)uploadFetcherForSessionIdentifierMetadata:(id)a0;
+ (unsigned long long)uploadStatusFromResponseHeaders:(id)a0;
+ (void)removePointer:(void *)a0 fromPointerArray:(id)a1;
+ (id)uploadFetcherWithRequest:(id)a0 uploadMIMEType:(id)a1 chunkSize:(long long)a2 fetcherService:(id)a3;
+ (id)uploadFetcherWithLocation:(id)a0 uploadMIMEType:(id)a1 chunkSize:(long long)a2 fetcherService:(id)a3;
+ (id)uploadFetcherForSessionIdentifier:(id)a0;
+ (void)load;

- (BOOL)useBackgroundSession;
- (void)setUseBackgroundSession:(BOOL)a0;
- (void)setUploadFileLength:(long long)a0;
- (void)beginFetchWithCompletionHandler:(id /* block */)a0;
- (BOOL)canFetchWithBackgroundSession;
- (long long)statusCodeUnsynchronized;
- (void)stopFetchReleasingCallbacks:(BOOL)a0;
- (void)beginFetchForRetry;
- (BOOL)shouldReleaseCallbacksUponCompletion;
- (void)setLocationURL:(id)a0 uploadMIMEType:(id)a1 chunkSize:(long long)a2 allowsCellularAccess:(BOOL)a3;
- (void)attachSendProgressBlockToChunkFetcher:(id)a0;
- (void)chunkFetcher:(id)a0 finishedWithData:(id)a1 error:(id)a2;
- (void)setupRequestHeaders;
- (long long)fullUploadLength;
- (id)uploadChunkUnavailableErrorWithDescription:(id)a0;
- (void)generateChunkSubdataFromFileURL:(id)a0 offset:(long long)a1 length:(long long)a2 response:(id /* block */)a3;
- (void)generateChunkSubdataFromFileHandle:(id)a0 offset:(long long)a1 length:(long long)a2 response:(id /* block */)a3;
- (void)setInitialBodyLength:(long long)a0;
- (void)setFetcherInFlight:(id)a0;
- (BOOL)isRestartedUpload;
- (void)sendQueryForUploadOffsetWithFetcherProperties:(id)a0;
- (void)beginChunkFetches;
- (void)invokeFinalCallbackWithData:(id)a0 error:(id)a1 shouldInvalidateLocation:(BOOL)a2;
- (void)generateChunkSubdataWithOffset:(long long)a0 length:(long long)a1 response:(id /* block */)a2;
- (void)retrieveUploadChunkGranularityFromResponseHeaders:(id)a0;
- (id)prematureFailureErrorWithUserInfo:(id)a0;
- (long long)initialBodyLength;
- (void)setInitialBodySent:(long long)a0;
- (void)uploadNextChunkWithOffset:(long long)a0;
- (void)invokeDelegateWithDidSendBytes:(long long)a0 totalBytesSent:(long long)a1 totalBytesExpectedToSend:(long long)a2;
- (void)releaseUploadAndBaseCallbacks:(BOOL)a0;
- (id)fetcherInFlight;
- (void)uploadNextChunkWithOffset:(long long)a0 fetcherProperties:(id)a1;
- (id)uploadFetcherWithProperties:(id)a0 isQueryFetch:(BOOL)a1;
- (void)queryFetcher:(id)a0 finishedWithData:(id)a1 error:(id)a2;
- (BOOL)triggerCancellationHandlerForFetch:(id)a0 data:(id)a1 error:(id)a2;
- (long long)updateChunkFetcher:(id)a0 forChunkAtOffset:(long long)a1;
- (void)beginChunkFetcher:(id)a0 offset:(long long)a1;
- (id)uploadSessionIdentifierMetadata;
- (void)destroyChunkFetcher;
- (void)sendCancelUploadWithFetcherProperties:(id)a0;
- (void)setUploadDataLength:(long long)a0 provider:(id /* block */)a1;
- (long long)initialBodySent;
- (id)activeFetcher;
- (void)setStatusCode:(long long)a0;
- (void).cxx_destruct;
- (BOOL)isPaused;
- (id)delegateCallbackQueue;
- (void)setCompletionHandler:(id /* block */)a0;
- (void)URLSession:(id)a0 task:(id)a1 didSendBodyData:(long long)a2 totalBytesSent:(long long)a3 totalBytesExpectedToSend:(long long)a4;
- (id)responseHeaders;
- (BOOL)waitForCompletionWithTimeout:(double)a0;
- (BOOL)isFetching;
- (void)pauseFetching;
- (void)resumeFetching;
- (void)stopFetching;
- (void)setDelegateCallbackQueue:(id)a0;

@end
