@class NSMapTable, NSTimer, NSString, NSDate, NSNumber;
@protocol HTSLiveAudienceWatchTimeDelegate;

@interface HTSLiveAudienceWatchTime : NSObject <IESLiveRoomWatchTimeService>

@property (retain, nonatomic) NSMapTable *observers;
@property (retain, nonatomic) NSTimer *timer;
@property (retain, nonatomic) NSDate *initialTime;
@property (retain, nonatomic) NSDate *livePlayTime;
@property (retain, nonatomic) NSDate *curCameraPlayTime;
@property (retain, nonatomic) NSDate *curContentPlayTime;
@property (retain, nonatomic) NSDate *playBackTime;
@property (nonatomic) double playBackTotalDuration;
@property (retain, nonatomic) NSDate *lastOrientationChangedTime;
@property (retain, nonatomic) NSDate *curOrientationWatchTime;
@property (nonatomic) double CurOrientationStopDuration;
@property (retain, nonatomic) NSDate *startTime;
@property (retain, nonatomic) NSDate *lastPauseTime;
@property (retain, nonatomic) NSDate *lastContinueTime;
@property (nonatomic, getter=isLivePaused) BOOL livePaused;
@property (nonatomic) double totalPauseDuration;
@property (retain, nonatomic) NSDate *stopTime;
@property (nonatomic) double lastStopDuration;
@property (nonatomic) double stopDuration;
@property (nonatomic) unsigned long long minitTickTimes;
@property (retain, nonatomic) NSTimer *videoOverTimer;
@property (retain, nonatomic) NSDate *videoOverDate;
@property (retain, nonatomic) NSDate *enterBackgroundTime;
@property (nonatomic) BOOL isPaused;
@property (retain, nonatomic) NSNumber *firstStopWatchingReason;
@property (readonly, nonatomic) long long watchDuration;
@property (nonatomic) unsigned long long lastStopWatchingReason;
@property (nonatomic) BOOL liveDurationTracked;
@property (retain, nonatomic) NSDate *liveDurationTrackTime;
@property (nonatomic) double afterTrackStopDuration;
@property (retain, nonatomic) NSDate *liveLandscapeEnterTime;
@property (nonatomic) long long totalLandscapeDuration;
@property (weak, nonatomic) id<HTSLiveAudienceWatchTimeDelegate> delegate;
@property (nonatomic) BOOL invalid;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)startTracker;
- (double)liveroomStartWatchingTime;
- (long long)timeSinceInitial;
- (void)videoOverTrackStart;
- (void)videoOverPartForKey:(id)a0;
- (void)videoOverTrack:(double)a0 forKey:(id)a1;
- (void)vsResumeWatching;
- (void)p_trackLandscapeWatchDurationIfHas;
- (void)_trackVSOrientationDurationWithCloseLive:(BOOL)a0;
- (void)p_callCameraPlayTimeDelegate;
- (void)p_callCameraContentPlayTimeDelegate;
- (void)vsPauseWatching;
- (double)stayPageTracker;
- (void)stopWatchingFor:(unsigned long long)a0;
- (long long)liveDurationTrackDuration;
- (void)trackBackgroundTimeIfNeededWithEndReason:(unsigned long long)a0;
- (void)p_terminationWatching;
- (void)p_closeLiveWatchingReason:(unsigned long long)a0;
- (void)stopPlayBackTimer;
- (void)resetVideoOverTimer;
- (long long)liveLandscapeTrackDuration;
- (void)updateInitialTime:(id)a0;
- (void)videoOverDisAppear;
- (void)videoOverWillAppear;
- (void)orientationDidChangeToFullScreen:(BOOL)a0;
- (void)vsOrientationWillChange;
- (void)stopWatchingFor:(unsigned long long)a0 needTrackDuration:(BOOL)a1;
- (void)closeWatchingFor:(unsigned long long)a0;
- (void)recordWatchTime;
- (void)startLivePlay;
- (void)startPlayBackTimer;
- (void)changeCameraStream;
- (void)changeContentStream;
- (long long)liveLandscapeDurationTrackDuration;
- (BOOL)isLiveDurationTracked;
- (void).cxx_destruct;
- (void)pause;
- (void)addObserver:(id)a0;
- (id)init;
- (void)resume;
- (void)removeObserver:(id)a0;
- (void)startWatching;
- (void)dealloc;

@end
