@interface IESECShopABTestManager : NSObject

+ (long long)shopSearchResultHybridRefactor;
+ (id)shopSearchResultHybridConfig;
+ (id)imagePreloadConfig;
+ (BOOL)enableShopLiveRoomTabInnerFlow;
+ (BOOL)enableContainerControllerAutoUpdate;
+ (BOOL)createTabInfosCombineCallBack;
+ (BOOL)enableFollowPageOpt;
+ (BOOL)enableShopTaskBannerRequestTimingFix;
+ (long long)brandAdPopupType;
+ (BOOL)enableMallMultiTab;
+ (BOOL)addFilterItemOnShopClassifyProductList;
+ (BOOL)enableShopLoginCheckReport;
+ (id)awe_settingForKeyPath:(id)a0 defaultValue:(id)a1;
+ (id)shopSliceConfig;
+ (id)relationHostsPreconnectConfig;
+ (id)shopPreviewPerfConfig;
+ (long long)awe_integerSettingForKeyPath:(id)a0;
+ (id)defaultReplaceGetToPostURLArray;
+ (BOOL)enableShopSliceProductCard;
+ (id)shopSlicePreloadTemplateList;
+ (BOOL)shopStateThrottleEnabled;
+ (double)shopStateDispatchInterval;
+ (id)shopLynxResourcePreloadConfig;
+ (id)relationApiHostsPreconnectConfig;
+ (id)relationPicHostsPreconnectConfig;
+ (BOOL)enableShopFPSMonitor;
+ (id)ecomLiveTransParams;
+ (id)ecomLiveDelParams;
+ (long long)shopPreviewPerfMetricDuration;
+ (id)shopPreviewPerfWhiteList;
+ (long long)imagePreloadFirstScreenNum;
+ (long long)imagePreloadLoadMoreNum;
+ (id)userEventsFilter;
+ (id)filterRulesForEvent:(id)a0;
+ (BOOL)enhanceSearchPlaceholder;
+ (long long)hotSearchStyle;
+ (BOOL)enableSearchUIOpt;
+ (BOOL)enableSearchGlideOpt;
+ (BOOL)enableActivityRespTransactionFix;
+ (BOOL)enableShopFloatLynxFix;
+ (BOOL)enableShopPerfRouterOpt;
+ (BOOL)enableAdShopApiPreload;
+ (BOOL)enableAdShopResourcePreload;
+ (id)shopDecorationChannels;
+ (BOOL)enableProductLayoutOpt;
+ (BOOL)enableSearchCamera;
+ (BOOL)enableShopProductsInsertion;
+ (BOOL)enableShopProductSkuImagePreload;
+ (BOOL)enableShopProductConvertCache;
+ (BOOL)enableShopProductExposedTagEventParams;
+ (BOOL)enableShopTagLineWidthEqual;
+ (BOOL)enableShopTopCardSlidCeil;
+ (long long)shopSKUFrequency;
+ (BOOL)enableShopRerankClientAiOpt;
+ (BOOL)enableShopLiveDelayTransfer;
+ (BOOL)enableShopListKitFixInsertEmptyItem;
+ (BOOL)enableSplitContainerLayoutUpdate;
+ (BOOL)enableShopSliceBindDataThrottle;
+ (BOOL)enableShopSLIProfileInitialSetupOpt;
+ (BOOL)enableShopLayoutBrandDecorationAdjust;
+ (long long)enableShopLiveRoomTab;
+ (BOOL)enableShopEnterLiveStyle;
+ (BOOL)enableShopLiveStyleOpt;
+ (BOOL)enableShopMomentsFullDetail;
+ (id)shopProductsPitayaConfig;
+ (id)shopSlideHintConfig;
+ (long long)shopRecommendSellPointType;
+ (BOOL)enableShopLiveHeaderDowngrade;
+ (id)shopCollapseAnimationConfig;
+ (BOOL)enableLaunchTaskOpt;
+ (BOOL)preloadProductDetailImgs;
+ (BOOL)enableCrossShopTitleOpt;
+ (BOOL)enablePuzzleMigrateToAnnieX;
+ (BOOL)shopProductCardPackMigrate;
+ (long long)shopCouponExperienceOpt;
+ (BOOL)enableShopTopPush;
+ (long long)optTabFrameV2;
+ (long long)optTabFrameV4;
+ (BOOL)enableReplaceGetToPost;
+ (BOOL)enableTabBizExtraNoTransfer;
+ (id)replaceGetToPostURLArray;
+ (BOOL)enableShopProductBottomCardPack;
+ (BOOL)enableFixPagerViewUpdateIdleContentOffsetY;
+ (BOOL)enableShopSearchResultHybridRefactor;
+ (BOOL)addScrollToTopViewToFloatContainer;
+ (BOOL)enableBrandShopUIUpgrade;
+ (id)settingsMap;

@end
