@class UITapGestureRecognizer, UICollectionView, NSIndexPath, IESECGoodsFeedSheetPanelViewController, LOTAnimationView, NSMutableSet, NSMutableArray, UIPanGestureRecognizer, IESECQualityInfoV2, CALayer, IESECHybridParamsVerifyHelper, IESECVideoPurchaseAbilityAdapter, UIStackView, IESECGoodsInternalFeedCustomNavigationBar, IESECUserTrackerPageContext, IGListAdapter, UIViewController, IESECGoodsInternalFeedHeaderBannerView, IESECInternalFeedStyleModel, IESECGoodsBottomActionHelper, IESECOnceHelper, NSNumber, IESECGoodsInternalFeedViewControllerConfiguration, IESECGoodFeedMallCardStorage, IESECGoodsFeedGradientView, IESECGCDTimer, UIView, IESECFeedRecommendItemModel, IESECHighlightButton, IESECGoodsInternalFeedDataSource, NSMutableDictionary, NSString, IESECDurationHelper, IESECGoodsDetailTracker, UILabel, IESECGradientView, IESECGoodsInternalFeedCouponBannerView, IESECGoodsDetailParameters, IESECGoodsFeedLargeCardNewCollectionViewCell, IESECGoodsFeedRedPacketPromptView, IESECFeedSearchWordModel, IESECGoodsFeedContext, IESECXBridgeEventSubscriber;
@protocol IESECSKUViewControllerProtocol, IESECGoodsDetailPopoverContentProtocol;

@interface IESECGoodsInternalFeedViewController : UIViewController <AWEFeedPlayResultFromChildViewController, UIGestureRecognizerDelegate, IGListAdapterDataSource, IGListAdapterDelegate, IESECGoodsFeedLargeCardCellContentProtocol, IESECGoodsFeedLargeCardCellOperationProtocol, UIScrollViewDelegate, UICollectionViewDelegate, IESECGoodsFeedResourceCardDelegate, IESECGoodsReportMessage, IESECShareGoodsResponse, IESECommerceAddGoodsToCartMessage, CAAnimationDelegate, IESECGoodsFeedTagsCellDelegate, IESECMixedFeedLayoutDelegate, IESECGoodsFeedCollectionHeaderViewDelegate, IESECGoodsFeedItemCardCellDelegate, IESECGoodsFeedListDelegate, IESECGoodsFeedContainerProtocol, IESECVideoSKUActionDelegate, IESECGoodsFeedSearchCardCellDelegate, IESECGoodsDetailHostInjectable, IESECGoodsDetailContainerProtocol, IESECGoodsPanelHalfToDismissProtocol> {
    UIView *_fullScreenBackgroundView;
    BOOL _isReturnFromOtherPages;
    NSMutableArray *_productsHaveBeenDisplayed;
    NSMutableArray *_sameGoodsHaveBeenDisplayed;
    long long _lastSectionHasBeenDisplayed;
    long long _sectionForDeduplication;
    NSString *_curEcomSceneID;
    NSString *_curGuessULikeEcomSceneID;
    long long _goodsCardCount;
    long long _resourceCardBeyondRecommendCount;
    BOOL _isSelfDisplayedOnScreen;
    NSMutableArray *_subscribers;
    BOOL _viewWillDismiss;
    BOOL _shouldRestoreFeedPlayer;
    IESECHybridParamsVerifyHelper *_verifyHelper;
    BOOL _disableLoadingOpt;
    BOOL _showBubbleComponent;
    IESECXBridgeEventSubscriber *_memberSubscriber;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) IESECGoodsDetailParameters *goodsDetailParameter;
@property (nonatomic, getter=isFirstAppear) BOOL firstAppear;
@property (retain, nonatomic) NSMutableArray *vCells;
@property (retain, nonatomic) IGListAdapter *listAdapter;
@property (retain, nonatomic) UICollectionView *collectionView;
@property (retain, nonatomic) IESECHighlightButton *hoverCloseButton;
@property (retain, nonatomic) IESECGoodsFeedGradientView *hoverCloseButtonContainer;
@property (retain, nonatomic) IESECGoodsFeedGradientView *hoverImmersionCloseButtonContainer;
@property (retain, nonatomic) IESECGoodsFeedGradientView *hoverImmersionMallEntranceButtonContainer;
@property (retain, nonatomic) IESECGradientView *hoverTopGradientView;
@property (retain, nonatomic) IESECGoodsInternalFeedCustomNavigationBar *customNavigationBar;
@property (retain, nonatomic) UIView *instructionView;
@property (retain, nonatomic) NSIndexPath *previewIndexPath;
@property (retain, nonatomic) IESECGoodsFeedGradientView *gradientView;
@property (retain, nonatomic) UIStackView *entranceStackView;
@property (retain, nonatomic) UIView *backToTopView;
@property (retain, nonatomic) UIView *cartButtonView;
@property (retain, nonatomic) UIView *guideToMallView;
@property (nonatomic) long long cartNumber;
@property (retain, nonatomic) LOTAnimationView *shopCartAnimationView;
@property (retain, nonatomic) UILabel *cartNumberLabel;
@property (retain, nonatomic) IESECGoodsFeedLargeCardNewCollectionViewCell *cellForCalculatingNew;
@property (retain, nonatomic) IESECGoodsFeedRedPacketPromptView *redPacketPromptView;
@property (nonatomic) double messageDisplayAlpha;
@property (nonatomic) double recommendTagViewAlpha;
@property (retain, nonatomic) UIPanGestureRecognizer *panGesture;
@property (retain, nonatomic) UITapGestureRecognizer *tapGesture;
@property (retain, nonatomic) UIPanGestureRecognizer *horizontalDismissPanGesture;
@property (retain, nonatomic) IESECGoodsInternalFeedDataSource *dataSource;
@property (retain, nonatomic) IESECGoodsBottomActionHelper *actionHelper;
@property (retain, nonatomic) IESECVideoPurchaseAbilityAdapter *purchaseAbilityAdapter;
@property (nonatomic) BOOL isPresentingPopover;
@property (retain, nonatomic) UIViewController<IESECGoodsDetailPopoverContentProtocol> *popoverContent;
@property (retain, nonatomic) UIView *popoverBackground;
@property (retain, nonatomic) UIView *popoverContainer;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } contentFrameBefore;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } bottomContainerFrameBefore;
@property (nonatomic) BOOL isGoToOrderPage;
@property (nonatomic) BOOL isWhiteGradientView;
@property (nonatomic) BOOL headerCartDisplay;
@property (retain, nonatomic) UIView *cartView;
@property (retain, nonatomic) UIView *searchView;
@property (retain, nonatomic) UIView *couponView;
@property (weak, nonatomic) UIView *cartViewWrapper;
@property (retain, nonatomic) CALayer *animationRedPoint;
@property (nonatomic) struct CGPoint { double x; double y; } cartStartPoint;
@property (nonatomic) BOOL shouldShowMallEntrance;
@property (nonatomic) long long headerSearchEntranceStyle;
@property (nonatomic) long long commentViewStyle;
@property (retain, nonatomic) IESECGoodsDetailParameters *currentSharingGoods;
@property (retain, nonatomic) IESECGCDTimer *timer;
@property (retain, nonatomic) NSMutableSet *slideSet;
@property (nonatomic) BOOL isLoadingSameGoodsData;
@property (retain, nonatomic) NSMutableSet *activityIndexSet;
@property (retain, nonatomic) IESECUserTrackerPageContext *pageContext;
@property (nonatomic) BOOL hasSetupUIWithStyle;
@property (retain, nonatomic) IESECGoodsDetailTracker *tracker;
@property (retain, nonatomic) IESECDurationHelper *stay;
@property (copy, nonatomic) NSString *closeMethod;
@property (retain, nonatomic) UIView *couponInfoView;
@property (nonatomic) unsigned long long mallCardFrequencyMethod;
@property (nonatomic) BOOL isMallCardShowRecord;
@property (copy, nonatomic) IESECGoodFeedMallCardStorage *mallCardStorage;
@property (retain, nonatomic) NSMutableArray *searchProductIds;
@property (retain, nonatomic) NSMutableArray *searchCardShowIndexArray;
@property (nonatomic) long long searchCardFrequency;
@property (retain, nonatomic) NSMutableArray *compareDealsProductIds;
@property (retain, nonatomic) IESECFeedRecommendItemModel *compareDealsCardModel;
@property (retain, nonatomic) IESECFeedRecommendItemModel *searchCardModel;
@property (retain, nonatomic) NSNumber *viewdidloadTime;
@property (retain, nonatomic) IESECQualityInfoV2 *info;
@property (nonatomic) BOOL shouldPauseWithoutAnimationWhenCloseInner;
@property (nonatomic) BOOL isAnimating;
@property (retain, nonatomic) CALayer *addCartAnimationWithPic;
@property (retain, nonatomic) UIView *addCartAnimationWithPicView;
@property (nonatomic) struct CGPoint { double x; double y; } addCartStartPoint;
@property (copy, nonatomic) NSString *currentImageUrl;
@property (retain, nonatomic) IESECGoodsInternalFeedCouponBannerView *topCouponPromptBanner;
@property (retain, nonatomic) IESECGoodsInternalFeedCouponBannerView *bottomCouponPromptBanner;
@property (nonatomic) BOOL isGestureInstructionShowed;
@property (retain, nonatomic) IESECGoodsInternalFeedHeaderBannerView *headerBanner;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } headerBannerFrame;
@property (retain, nonatomic) IESECFeedSearchWordModel *searchWordModel;
@property (retain, nonatomic) NSMutableArray *enterDetailBackToGoodsFeedDataArray;
@property (nonatomic) long long enterDetailCurrentIndex;
@property (weak, nonatomic) IESECGoodsFeedSheetPanelViewController *feedBackVC;
@property (nonatomic) BOOL hasMaskView;
@property (nonatomic) BOOL callClose;
@property (nonatomic) BOOL viewWillDisappear;
@property (retain, nonatomic) IESECOnceHelper *onceHelper;
@property (retain, nonatomic) IESECGoodsFeedContext *context;
@property (nonatomic) long long statusBarStyle;
@property (copy, nonatomic) NSString *imageSearchClickPosition;
@property (retain, nonatomic) NSMutableDictionary *metricsSnapshot;
@property (retain, nonatomic) NSMutableDictionary *fullMetricsSnapshot;
@property (copy, nonatomic) id /* block */ animationDidEndCallback;
@property (copy, nonatomic) id /* block */ refreshLargeCardCallback;
@property (nonatomic, getter=isFullMode) BOOL fullMode;
@property (retain, nonatomic) IESECGoodsInternalFeedViewControllerConfiguration *configuration;
@property (retain, nonatomic) IESECInternalFeedStyleModel *style;
@property (nonatomic) long long pageInternalFlowStyle;
@property (weak, nonatomic) UIViewController *fromVC;
@property (nonatomic) BOOL isMemberShip;
@property (retain, nonatomic) IESECGoodsDetailParameters *preloadPromotionParams;
@property (nonatomic) BOOL showByPresent;
@property (retain, nonatomic) NSString *feedSessionId;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) UIViewController<IESECGoodsDetailPopoverContentProtocol, IESECSKUViewControllerProtocol> *skuVC;
@property (nonatomic) BOOL shouldDetachLiveFloatOnTopToNextPage;
@property (readonly, nonatomic) BOOL willShowAsChildVC;
@property (copy, nonatomic) id /* block */ willDismiss;
@property (copy, nonatomic) id /* block */ didAppear;
@property (nonatomic) BOOL unPlayWhenClose;
@property (readonly, copy, nonatomic) NSString *animationType;
@property (copy, nonatomic) id /* block */ willClosePage;
@property (copy, nonatomic) id /* block */ closeHalfPageProgress;

- (unsigned long long)iesec_overrideColorTheme;
- (void)close:(id)a0 completion:(id /* block */)a1;
- (long long)containerMode;
- (id)objectsForListAdapter:(id)a0;
- (id)listAdapter:(id)a0 sectionControllerForObject:(id)a1;
- (id)emptyViewForListAdapter:(id)a0;
- (void)listAdapter:(id)a0 willDisplayObject:(id)a1 atIndex:(long long)a2;
- (void)listAdapter:(id)a0 didEndDisplayingObject:(id)a1 atIndex:(long long)a2;
- (void)performUpdatesAnimated:(BOOL)a0 completion:(id /* block */)a1;
- (void)scrollToObject:(id)a0 supplementaryKinds:(id)a1 scrollDirection:(long long)a2 scrollPosition:(unsigned long long)a3 animated:(BOOL)a4;
- (void)reloadContainer:(id /* block */)a0;
- (BOOL)viewControllerBasedStatusBarAppearanceEnabled;
- (void)didReportGoodsWithPromotionID:(id)a0 productID:(id)a1;
- (void)registerMessages;
- (void)hostInjectionViewWillDisappear;
- (void)hostInjectionDidOpenPage;
- (void)hostInjectionWillClosePage;
- (void)hostInjectionWillOpenNextPage;
- (void)configBtmTrackerV2;
- (void)configBTMTracker;
- (BOOL)presentPopover:(id)a0;
- (BOOL)presentingPopover;
- (void)dismissCurrentPopover;
- (void)transitionToCommentViewController;
- (void)transitionToStoreCommentVC;
- (void)favoriteActionButtonDidTapWithCompletion:(id /* block */)a0;
- (void)addToShoppingCartActionWithSKUInfo:(id)a0;
- (void)isGoingToOrderPage:(BOOL)a0;
- (void)isGoingToAddrBook:(BOOL)a0;
- (void)openAddrBook;
- (id)liveBanner;
- (void)detachLiveFloatOnTopWhenBuyTouTiaoGoodsIfNeeded;
- (void)detachLiveFloatOnTop;
- (void)openReplayWithURLString:(id)a0;
- (void)markNeedsStatusBarAppearanceUpdate;
- (void)goToOrderPageWithCouponId:(id)a0 actionType:(long long)a1 withSKUInfo:(id)a2 onViewController:(id)a3 entranceInfoParamsForSKU:(id)a4 completion:(id /* block */)a5;
- (void)dismissCurrentPopoverWithCompletion:(id /* block */)a0;
- (void)goToNativeOrderPageWithCouponId:(id)a0 actionType:(long long)a1 withSKUInfo:(id)a2 onViewController:(id)a3 entranceInfoParamsForSKU:(id)a4 completion:(id /* block */)a5;
- (id)recommendTypeEventDescription;
- (id)composeEntranceInfoFormDict:(id)a0 scene:(id)a1;
- (void)hostInjectionPageWillAppearAgain;
- (void)unregisterMessages;
- (void)p_dismissCurrentPopoverWithCompletion:(id /* block */)a0;
- (void)p_presentPopover:(id)a0;
- (BOOL)isPopoverSKU;
- (void)tapToDismissPopover;
- (void)attachLiveFloatOnTop;
- (BOOL)shouldNotAutoPlay;
- (void)callWillDismiss;
- (void)shareDidDimissPanelForGoods:(id)a0;
- (void)addToCartAnimationStart;
- (void)showGestureInstruction;
- (void)closeButtonDidTap:(id)a0;
- (BOOL)loadingOpt;
- (void)configBcmPageParams;
- (void)tapToClose;
- (void)forbidContentInteraction;
- (void)resumeContentInteraction;
- (BOOL)ttHideNavigationBar;
- (id)parseScheme:(id)a0;
- (void)addInfiniteScroll;
- (id)currentCenterCell;
- (void)addCustomNoMoreView;
- (void)setupInteraction;
- (id)switchModeAction;
- (void)horizontalDismissPanGestureHandler:(id)a0;
- (void)closeByMethod:(id)a0;
- (void)acceptAddCartAnimationImageCoverURL:(id)a0 cartCount:(long long)a1;
- (void)acceptShoppingCartNumberChanged:(id)a0;
- (void)startCartAnimation;
- (void)hostInjectionDidPageSwitchTo:(long long)a0;
- (void)backToTopViewDidTap;
- (BOOL)isInternalFeedAD;
- (void)collectionHeaderViewStyleShouldChange:(id)a0;
- (id)initWithGoodsDetailParameters:(id)a0 configuration:(id)a1;
- (void)updateSearchBannerViewWithResponse:(id)a0 error:(id)a1;
- (void)updateRecommendDataWithResponse:(id)a0 error:(id)a1;
- (void)updateLargeCardData:(id)a0 error:(id)a1;
- (id)activityDetailForTrackingWithParams:(id)a0;
- (id)getLargeCardViewModel;
- (id)listStyleEventDescription;
- (void)updateTargetParametersListStyleEvent;
- (void)updateContainerMode;
- (void)updateShopCartWithCount:(long long)a0 withStyle:(long long)a1;
- (void)hostInjectionPageWillDisappearPage;
- (void)hostInjectionPageDidDisappearPage;
- (void)updateCornerForView:(id)a0 percentage:(double)a1;
- (void)addCart2HalfView;
- (double)fullScreenY;
- (void)hostInjectionPageWillSwitchTo:(long long)a0 animationTime:(double)a1;
- (void)hostInjectionPageDidPanToPercent:(double)a0;
- (void)closeInternalFeedOnly;
- (void)closeInner;
- (void)cartEntranceDidTap:(id)a0;
- (void)p_presentPopover:(id)a0 needCorner:(BOOL)a1;
- (long long)getPageContentMode;
- (id)commonExtra;
- (void)hostInjectionPageWillAppearPage;
- (void)itemCardCell:(id)a0 didSelectItemWithType:(unsigned long long)a1;
- (BOOL)getIsMemberShip;
- (void)collectionViewCell:(id)a0 didScrollImagesToIndex:(long long)a1;
- (void)collectionViewCellDidClickWindowEntryView:(id)a0;
- (void)collectionViewCellWindowEntryViewTracker:(id)a0 didClick:(BOOL)a1;
- (void)collectionViewCell:(id)a0 doActionOf:(long long)a1;
- (void)collectionViewCell:(id)a0 doAddCartWithButton:(id)a1;
- (void)collectionViewCell:(id)a0 doEnterMemberWithButton:(id)a1 doActionOf:(long long)a2;
- (void)collectionViewCell:(id)a0 didClickVideoCommentWithIndex:(long long)a1;
- (void)collectionViewCell:(id)a0 doWantWithCompletion:(id /* block */)a1;
- (void)collectionViewCell:(id)a0 didSelectTagView:(id)a1;
- (void)collectionViewCellDidClickSearchSameGoodsEntrance:(id)a0;
- (void)collectionViewCellBalanceExchangeCouponViewTracker:(id)a0 didClick:(BOOL)a1;
- (void)collectionViewCellDidClickBalanceExchangeCouponView:(id)a0;
- (void)collectionViewCell:(id)a0 trackEvent:(id)a1 additionParams:(id)a2;
- (void)collectionViewCell:(id)a0 didTapImageAtIndex:(long long)a1;
- (void)collectionViewCellTapEffectivePreviewArea:(id)a0;
- (void)collectionViewCellScrollToDetails:(id)a0;
- (void)collectionViewCell:(id)a0 trackEvent:(id)a1 params:(id)a2;
- (void)timerFire;
- (void)collectionViewCell:(id)a0 longTapImageWithModel:(id)a1 imageURL:(id)a2;
- (void)productCardDataLoaded;
- (void)productCardUpdated;
- (void)loadMoreRecommendGoods;
- (void)p_reportFullRenderCompleteWithParams:(id)a0;
- (void)loadMoreRecommendGoodsWithFilterString:(id)a0;
- (void)shouldUpdateWindVane;
- (void)recommendListAppended;
- (void)loadRecommendGoodsFailedTrack:(id)a0 statusCode:(id)a1;
- (void)loadCollectionCards;
- (void)handleMoreData;
- (void)loadRecommendGoodsSucceededTrack;
- (void)requestRecommendListCompareDealsCard:(id)a0;
- (void)loadMoreRecommendCompleted;
- (BOOL)shouldRequestSearchCardWithIndex:(long long)a0;
- (void)insertRecommendListCompareDealsCard:(id)a0;
- (void)firstCardCompareDealsCardAdded;
- (BOOL)shouldDelete:(id)a0;
- (void)trackClickResourceCard:(id)a0 btm:(id)a1;
- (void)updateClickFrequencyControlCacheWithResourceCard:(id)a0;
- (void)resourceCard:(id)a0 didClickCard:(id)a1;
- (void)resourceCarddidClickPanelNodeChangeProduct:(id)a0 completionBlock:(id /* block */)a1;
- (void)resourceCard:(id)a0 didClickProductCellWithProduct:(id)a1;
- (void)resourceCard:(id)a0 didClickCellBuyButtonWithProduct:(id)a1;
- (void)resourceCard:(id)a0 didClickCouponViewWithSchema:(id)a1 hasCoupon:(BOOL)a2;
- (void)resourceCard:(id)a0 didClickMoreProductWithSchema:(id)a1;
- (void)resourceCard:(id)a0 didSelectProductWithModel:(id)a1;
- (void)resourceCard:(id)a0 didClickWindowCardWithClickArea:(id)a1 schema:(id)a2;
- (void)resourceCard:(id)a0 didClickStoreEntranceWithSchema:(id)a1;
- (void)resourceCard:(id)a0 didClickButtonNodeWithSchema:(id)a1;
- (void)clickSearchCardKeyWordAtIndex:(long long)a0 withModel:(id)a1;
- (void)clickSearchCardImageAtIndex:(long long)a0 withModel:(id)a1;
- (void)tagsCell:(id)a0 didSelectTagAtIndex:(long long)a1 withTagModel:(id)a2;
- (void)tagsCell:(id)a0 tagDidDisplayAtIndex:(long long)a1 withTagModel:(id)a2;
- (void)updateContainer:(BOOL)a0 completion:(id /* block */)a1;
- (void)setInnerFlowStyleWithParams:(id)a0;
- (unsigned long long)currentListStyle;
- (void)updateListLayout;
- (void)initLoadmore;
- (void)updateCloseButtonWithPercent:(double)a0;
- (void)updateCouponPromptWithPercent:(double)a0;
- (id)lightBackGroundEndColor;
- (void)updateGradientViewWithPercentIfNeeded:(double)a0;
- (void)handleMoreData:(id)a0 error:(id)a1 statusCode:(id)a2 requestStart:(double)a3;
- (BOOL)checkGuideToMallViewShouldShow;
- (void)recordMallCardShowIfNeeded;
- (BOOL)useDelayUpdate;
- (void)setupSearchBannerIfNeeded;
- (void)updateInflowStyle;
- (void)trackSearchEntranceShow;
- (void)p_enterPageTrack;
- (void)setupCouponPromptBannerIfNeeded;
- (void)trackSearchBannerWithActionType:(long long)a0;
- (void)trackCouponPromptBannerWithIsShow:(BOOL)a0;
- (void)tryStartTimer;
- (void)setupRedPacketPromptView;
- (void)goodsActivityStateChanged:(id)a0;
- (void)goodsDetailContextUpdated:(id)a0;
- (void)handleFavouriteActionNotification:(id)a0;
- (void)setupUIWithStyle;
- (id)setupHoverImmersionCloseButtonContainer;
- (void)toastIfNeeded;
- (BOOL)insertResourceCardIfNeeded;
- (long long)p_indexOfFreshManCard;
- (void)trackSearchIconWithActionType:(long long)a0;
- (void)animateToDismissWithEndingVelocity:(double)a0 currentFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1 animateTimeBlock:(id /* block */)a2;
- (void)restoreToFullWithEndingVelocity:(double)a0 currentFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1 animateTimeBlock:(id /* block */)a2;
- (void)restoreToHalfWithEndingVelocity:(double)a0 currentFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1 animateTimeBlock:(id /* block */)a2;
- (id)lightBackGroundStartColor;
- (BOOL)showHalfViewCart;
- (void)animateFromFullToHalfWithEndingVelocity:(double)a0 currentFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1 animateTimeBlock:(id /* block */)a2;
- (void)animateFromHalfToFullWithEndingVelocity:(double)a0 currentFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1 animateTimeBlock:(id /* block */)a2;
- (void)headerBannerTapGestureHandlerWithSourceBtmToken:(id)a0;
- (void)searchButtonDidTap:(id)a0 enterFromSecond:(id)a1 sourceBtmToken:(id)a2;
- (id)fetchCouponSchema;
- (id)p_buildParamsForBottomActionHelperWithCellIndex:(unsigned long long)a0;
- (long long)p_indexWithPromotionID:(id)a0;
- (unsigned long long)serverListStyle;
- (id)listStyleEventDescriptionWithStyle:(unsigned long long)a0;
- (void)trackADIsEmptyOpenURL:(BOOL)a0 IsFirstCard:(BOOL)a1;
- (id)recommendItemSchemeExpandWithOriginScheme:(id)a0 atIndex:(long long)a1 byMethod:(id)a2;
- (void)verifyURLScheme:(id)a0 withScene:(id)a1 context:(id)a2;
- (void)trackForOpenProductWithProductModel:(id)a0 withRecommendItem:(id)a1 atIndex:(long long)a2 byMethod:(id)a3;
- (long long)getDisplayRankWithIndex:(long long)a0;
- (id)viewModelForSection:(long long)a0;
- (id)cardTypeTextWithItemModel:(id)a0;
- (id)priceTypeWithPromotion:(id)a0 atIndex:(long long)a1;
- (id)tagCodeListWithModel:(id)a0;
- (id)targetGoodsDetailAdSchemeExpandWithOriginScheme:(id)a0 atIndex:(long long)a1;
- (void)trackClickEventWithItemModel:(id)a0 withClickArea:(id)a1 atIndex:(unsigned long long)a2;
- (void)trackFirstCardADWithEvent:(id)a0;
- (void)openTargetGoodsDetailWith:(id)a0 byMethod:(id)a1 atIndex:(long long)a2;
- (void)trackRecommendListADWithModel:(id)a0 event:(id)a1;
- (void)openRecommendItem:(id)a0 rankIndex:(long long)a1 byMethod:(id)a2;
- (void)trackGuideToMallViewDidClick;
- (void)trackClickEventWithItemModel:(id)a0 withClickArea:(id)a1 atIndex:(unsigned long long)a2 btm:(id)a3;
- (void)trackWindowCardDidClickWithAuthorID:(id)a0 entranceLocation:(id)a1 clickArea:(id)a2 displayRank:(long long)a3 productID:(id)a4 isFollowed:(BOOL)a5;
- (void)enterProductDetailAtIndex:(long long)a0 byMethod:(id)a1;
- (BOOL)shouldShowShopCartGuide;
- (void)addNGroupParams:(id)a0 actionType:(long long)a1;
- (void)trackFeedBackPanelEvent:(id)a0 cellViewModel:(id)a1 imageURL:(id)a2 btm:(id)a3 extraParams:(id)a4;
- (void)trackFeedBackHeaderEvent:(id)a0 cellViewModel:(id)a1 btm:(id)a2;
- (id)createFeedBackCellListWithCellModel:(id)a0 imageURL:(id)a1 viewController:(id)a2;
- (void)trackAutoSlide:(id)a0 isAutoSlide:(BOOL)a1;
- (void)trackWindowCardDidShowWithAuthorID:(id)a0 entranceLocation:(id)a1 isFollowed:(BOOL)a2;
- (id)_trackParamsForTagEvents:(id)a0 atIndex:(long long)a1;
- (void)trackSearchSameGoodsEntranceClickWithLargeCardCell:(id)a0;
- (void)trackClickEventWithItemModel:(id)a0 withClickArea:(id)a1 atIndex:(unsigned long long)a2 product:(id)a3;
- (void)clickResourceCardProductAtCardIndex:(long long)a0 withProductModel:(id)a1;
- (void)trackForClickResourceCardWithCardModel:(id)a0;
- (id)expandResourceProductSchema:(id)a0 WithParams:(id)a1;
- (void)trackClickEventWithItemModel:(id)a0 withClickArea:(id)a1 atIndex:(unsigned long long)a2 productID:(id)a3;
- (void)loadResourceCardPromotions:(id /* block */)a0;
- (void)preloadNextCell;
- (id)internalFeedV2BackgroundColor;
- (void)p_reportRenderCompleteWithParams:(id)a0;
- (void)uploadMetricsWhenFulfillingKeys:(id)a0;
- (void)trackInflowNGroupProductShowIfNeeded:(id)a0;
- (void)showStyleChangeGuidingIfNeeded;
- (void)trackSearchSameGoodsShowWithViewModel:(id)a0 index:(long long)a1;
- (void)trackGuideToMallViewDidShow;
- (void)couponEntranceDidTap:(id)a0;
- (void)searchNavButtonDidTap:(id)a0;
- (void)mallEntranceDidTap:(id)a0;
- (id)p_wrapperBarButtonViewWithConfig:(id)a0;
- (id)p_rightHoverNavbarsConfigs;
- (BOOL)showHalfViewSearchIcon;
- (void)addSearch2HalfView;
- (void)addCoupon2HalfView;
- (void)toastIfNeeded:(id)a0;
- (void)guideToMallViewDidTap;
- (void)recordIfNeededWithCell:(id)a0;
- (void)trackSearchSameGoodsItemShowWithModel:(id)a0 atIndex:(long long)a1;
- (void)enterSearchResultPageAtIndex:(long long)a0 withModel:(id)a1;
- (void)trackSearchSameGoodsClickWithViewModel:(id)a0 index:(long long)a1;
- (void)collectionViewCellDidClickSameGoodsEntrance:(id)a0;
- (void)trackClickResourceCard:(id)a0;
- (void)imageSearchEnterProductDetail:(id)a0 position:(id)a1;
- (void)imageSearchBuyClickedWithType:(long long)a0 position:(id)a1;
- (void)setStatusStyle:(long long)a0;
- (void)innerListScrollBegin;
- (void)innerListScrollEnd;
- (void)handleAddToCartWithSKUInfo:(id)a0 BTMModel:(id)a1;
- (void)handleBuyNowWithSKUInfo:(id)a0;
- (void)rankingCardEnterProductDetailAtIndex:(long long)a0 withProductModel:(id)a1;
- (id)liveSchemeByAppendingEvent:(id)a0 atIndex:(unsigned long long)a1;
- (id)videoSchemeByAppendingEvent:(id)a0 atIndex:(unsigned long long)a1;
- (void)trackProductTagShow:(id)a0 index:(long long)a1;
- (BOOL)isClosing;
- (void)applicationWillEnterForeground:(id)a0;
- (id)header;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (BOOL)gestureRecognizer:(id)a0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)a1;
- (BOOL)scrollViewShouldScrollToTop:(id)a0;
- (void)animationDidStop:(id)a0 finished:(BOOL)a1;
- (long long)preferredInterfaceOrientationForPresentation;
- (void)collectionView:(id)a0 didEndDisplayingCell:(id)a1 forItemAtIndexPath:(id)a2;
- (void)close:(id)a0;
- (long long)preferredStatusBarStyle;
- (void)registerNotifications;
- (void)invalidateTimer;
- (BOOL)gestureRecognizerShouldBegin:(id)a0;
- (BOOL)shouldAutorotate;
- (void)collectionView:(id)a0 willDisplayCell:(id)a1 forItemAtIndexPath:(id)a2;
- (unsigned long long)supportedInterfaceOrientations;
- (BOOL)gestureRecognizer:(id)a0 shouldReceiveTouch:(id)a1;
- (void)viewWillAppear:(BOOL)a0;
- (void)applicationDidEnterBackground:(id)a0;
- (void)scrollViewDidScroll:(id)a0;
- (double)totalDuration;
- (BOOL)gestureRecognizer:(id)a0 shouldBeRequiredToFailByGestureRecognizer:(id)a1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)scrollViewDidEndScrollingAnimation:(id)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (BOOL)accessibilityScroll:(long long)a0;
- (id)bottomView;
- (void)panGestureHandler:(id)a0;
- (id)headerViewForSection:(long long)a0;
- (void)didEndScroll;
- (void)setupUI;
- (void)refreshCells;
- (BOOL)showingPreview;
- (void)tapGestureHandler:(id)a0;

@end
