@class IESECGoodsCommentsListBFFResponse, NSString, IESECCommentGroup, IESECGoodsCommentContext, NSArray, IESECMemoryCache, NSDictionary, IESECCommentSectionViewModel, NSMutableArray, NSNumber, IESECCommentDetailModel;
@protocol IESECCommentBFFDataControllerDelegate, IESECHTTPRequestTask;

@interface IESECCommentBFFDataController : IESECListDataController <IESECCommentBFFDataControllerProtocol>

@property (retain, nonatomic) NSNumber *totalCount;
@property (retain, nonatomic) NSNumber *meaninglessCount;
@property (nonatomic) long long currentPage;
@property (nonatomic) long long filterModuleItemCount;
@property (nonatomic) BOOL isRequestSimilarData;
@property (copy, nonatomic) NSString *originContextInfo;
@property (copy, nonatomic) NSString *similarContextInfo;
@property (nonatomic) long long originTotalCount;
@property (nonatomic) long long similarTotalCount;
@property (copy, nonatomic) NSString *npsInfo;
@property (weak, nonatomic) id<IESECHTTPRequestTask> lastRequestTask;
@property (nonatomic) BOOL lastIsImpressionTag;
@property (copy, nonatomic) NSString *lastGeneralID;
@property (retain, nonatomic) IESECMemoryCache *memoryCache;
@property (nonatomic) BOOL mediaMode;
@property (nonatomic) BOOL showMediaSwitchBtn;
@property (nonatomic) long long currentCursor;
@property (nonatomic) long long similarCurrentCursor;
@property (nonatomic) long long similarCurrentPage;
@property (copy, nonatomic) NSString *generalID;
@property (copy, nonatomic) NSString *tabName;
@property (copy, nonatomic) NSString *tagName;
@property (copy, nonatomic) NSString *tagID;
@property (retain, nonatomic) IESECCommentDetailModel *sliceTagModuleModel;
@property (nonatomic) long long needPage;
@property (nonatomic) BOOL isFirstScreenData;
@property (retain, nonatomic) IESECGoodsCommentsListBFFResponse *hasBasicInfoCommentListResponse;
@property (retain, nonatomic) IESECGoodsCommentsListBFFResponse *commentListResponse;
@property (copy, nonatomic) NSDictionary *incomingData;
@property (copy, nonatomic) NSDictionary *requestParams;
@property (retain, nonatomic) IESECCommentGroup *npsGroup;
@property (retain, nonatomic) NSMutableArray *commentListComponents;
@property (retain, nonatomic) NSMutableArray *multiPicComponents;
@property (copy, nonatomic) NSDictionary *leewayParams;
@property (readonly, nonatomic) IESECGoodsCommentContext *context;
@property (weak, nonatomic) id<IESECCommentBFFDataControllerDelegate> delegate;
@property (nonatomic) BOOL isImpressionTag;
@property (nonatomic) BOOL isSortByTime;
@property (copy, nonatomic) NSString *fromScene;
@property (copy, nonatomic) NSArray *skuFilters;
@property (nonatomic) BOOL needFilterComments;
@property (copy, nonatomic) id /* block */ dataSourceDidChanged;
@property (copy, nonatomic) NSArray *mediaComment;
@property (retain, nonatomic) NSMutableArray *originCommentModels;
@property (nonatomic) BOOL originCommentsHasMore;
@property (nonatomic) BOOL similarCommentsHasMore;
@property (nonatomic) BOOL isFirstFetch;
@property (retain, nonatomic) NSNumber *originCommentCount;
@property (nonatomic) double commentsApiReqDuration;
@property (nonatomic) double sameCommentsApiReqDuration;
@property (nonatomic) double commentsPageApiReqDuration;
@property (copy, nonatomic) NSString *previousPage;
@property (copy, nonatomic) NSDictionary *abParamsDic;
@property (retain, nonatomic) NSArray *skuModelArray;
@property (copy, nonatomic) NSString *productName;
@property (retain, nonatomic) IESECCommentSectionViewModel *bodySectionViewModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)loadMoreWithCompletion:(id /* block */)a0;
- (void)initFetchWithCompletion:(id /* block */)a0;
- (void)clearDuration;
- (void)requestNextPageWithCompletion:(id /* block */)a0;
- (void)clearDataSource;
- (BOOL)shouldInsertGroup:(id)a0;
- (id)indexPathsWithSliceID:(id)a0 handler:(id /* block */)a1;
- (id)fetchCommentParams;
- (void)fetchCommentActionFrom:(unsigned long long)a0 completion:(id /* block */)a1;
- (id)getExpandTrackParams;
- (id)getSelectTagTrackParams;
- (void)removeNps;
- (void)appendTopComponentsGroupsToDataSource;
- (BOOL)isSelectPicTag;
- (void)appendGroupsToDataSource:(id)a0;
- (void)callDelegateDataSourceDidChange;
- (id)prepareRequestParams;
- (void)dealMixCommentWithOriginComment;
- (void)fetchMixedGoodsListWithParameters:(id)a0 completion:(id /* block */)a1;
- (BOOL)shouldAppendTopCommentIds;
- (void)dealGlobalData:(id)a0;
- (long long)getFilterModuleItemCount;
- (void)preprocessNps;
- (id)getSliceByComponentType:(id)a0;
- (id)sentimentToPositive:(long long)a0;
- (void)initRequestParams;
- (void)resetDataSourceWithNeedTag:(BOOL)a0;
- (void)didBack;
- (void)transToMediaMode;
- (void)transToListMode;
- (BOOL)isSelectPicTagAndMediaMode;
- (void)loadFirstScreenWithPreloadData:(id)a0;
- (id)getTagSlice;
- (void).cxx_destruct;
- (void)refresh;
- (BOOL)isEmpty;
- (id)initWithContext:(id)a0;
- (void)restart;
- (void)clearCache;
- (void)reset;
- (void)updateStatus;
- (void)clearState;
- (void)setup;
- (void)refreshWithCompletion:(id /* block */)a0;
- (long long)pageSize;
- (void)resetDataSource;

@end
