@class NSString, IESECMallPrefetcher, IESECMallHeaderContainer, IESECMultiMallContext, NSDictionary, IESECMallPopupTaskManager, IESECMallSlidingViewController, IESECMallBackgroundView;
@protocol IESECMallContainerViewControllerDelegate;

@interface IESECMallContainerViewController : UIViewController <IESECXBridgeCallHandlerService, IESECMallSlidingViewControllerDelegate, IESECMallHeaderContainerDelegate, IESECMallTabFrameService, IESECMallChannelViewControllerProtocol, IESECMallMultiTabJsbService>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) IESECMultiMallContext *context;
@property (retain, nonatomic) IESECMallSlidingViewController *slidingVC;
@property (retain, nonatomic) IESECMallHeaderContainer *headerContainer;
@property (retain, nonatomic) IESECMallBackgroundView *bgView;
@property (retain, nonatomic) IESECMallPrefetcher *prefetcher;
@property (copy, nonatomic) NSString *tMallFrameTime;
@property (copy, nonatomic) NSString *pageTheme;
@property (copy, nonatomic) NSDictionary *transInfo;
@property (nonatomic) BOOL enterBySchema;
@property (copy, nonatomic) NSDictionary *mallLynxConfig;
@property (weak, nonatomic) id<IESECMallContainerViewControllerDelegate> delegate;
@property (nonatomic) double innerTopMargin;
@property (copy, nonatomic) NSString *openTime;
@property (retain, nonatomic) IESECMallPopupTaskManager *popupManager;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)didFinishLoginWithUid:(id)a0;
- (void)dragWithProgress:(double)a0;
- (void)dragCancellation;
- (long long)numberOfControllers:(id)a0;
- (id)slidingViewController:(id)a0 viewControllerAtIndex:(long long)a1;
- (void)slidingViewController:(id)a0 didFinishTransitionToIndex:(unsigned long long)a1;
- (void)slidingViewController:(id)a0 didFinishTransitionFromPreviousViewController:(id)a1 currentViewController:(id)a2;
- (void)slidingViewController:(id)a0 didFinishTransitionFromPreviousIndex:(long long)a1 currentIndex:(long long)a2 transitionType:(long long)a3;
- (void)slidingViewControllerDidScroll:(id)a0;
- (BOOL)currentTabIsTop;
- (void)didFinishLogin;
- (id)currentBridgeCallHanderForCards;
- (BOOL)mallIsVisible;
- (void)prepareContext;
- (void)clearMemory;
- (void)slidingViewControllerWillBeginDragging:(id)a0;
- (void)slidingViewController:(id)a0 willFinishTransitionFromPreviousIndex:(long long)a1 currentIndex:(long long)a2 transitionType:(long long)a3;
- (void)slidingViewControllerDidEndScroll:(id)a0;
- (id)currentContentScrollView;
- (void)requestClientAiPrefetchApis:(double)a0 message:(id)a1 completion:(id /* block */)a2;
- (void)configWithRouterParamsForAiPrefetch:(id)a0;
- (void)mallChannelInnerTheme:(id)a0;
- (void)mallChannelTransInfo:(id)a0;
- (void)enterMallWithParams:(id)a0;
- (id)globalPropsExtra;
- (void)updateThemeStyleImmediately:(unsigned long long)a0;
- (void)updateThemeStyle:(unsigned long long)a0 defaultBgUrl:(id)a1;
- (id)mallMultiTabCurrentHostForBtm;
- (void)lynxCardMallReport:(id)a0;
- (long long)mallResVersion;
- (id)rootGlobalPropsExtra;
- (BOOL)needParentRefreshAbility;
- (BOOL)canResponsPullRefresh;
- (void)setContentViewScrollEnabled:(BOOL)a0;
- (void)animatedRefreshType:(long long)a0 completion:(id /* block */)a1;
- (void)anchorPendantShow:(id)a0 completion:(id /* block */)a1;
- (void)anchorPendantDismissWithContainerId:(id)a0;
- (id)currentTabViewController;
- (void)forceScrollToShoppingTab;
- (id)currentTabInfo;
- (void)tabBottomSelected;
- (void)tabBottomUnselected;
- (void)dragBegin;
- (void)configRouterParams:(id)a0;
- (void)channelInnerPendantLayoutUpdated:(id)a0;
- (void)mallWriteAlog:(id)a0 paramModel:(id)a1 result:(id)a2 context:(id)a3;
- (void)dismissPopupView:(id)a0;
- (void)dismissBubbleView:(id)a0;
- (void)bubbleView:(id)a0 resetVisibility:(BOOL)a1;
- (id)currentListContextIdForPopup:(id)a0;
- (id)globalExtraForPopup:(id)a0;
- (id)rootGlobalExtraForPopup:(id)a0;
- (id)hybridMonitorContextForPopup:(id)a0;
- (id)pageNameForPopup:(id)a0;
- (id)hmBidForPopup:(id)a0;
- (BOOL)enableOptLynxViewLoadLogicForPopup:(id)a0;
- (BOOL)currentListViewIsVisible;
- (void)slidingViewController:(id)a0 willBeginDeceleratingToIndex:(unsigned long long)a1;
- (BOOL)enableWhiteBoard;
- (id)lynxCardMallGetReportInfo:(id)a0;
- (void)scrollToFirstFavoriteCellWithSectionID:(id)a0 animated:(BOOL)a1;
- (id)lynxCardFeedProductIds:(id)a0;
- (id)mallMultiTabTemplateUrl;
- (void)addNotify;
- (BOOL)channelIsLoadedWithTabId:(id)a0;
- (void)tabAnchorPendantShow:(id)a0 completion:(id /* block */)a1;
- (id)tabViewControllerWithTabId:(id)a0;
- (void)addPopupTaskContainer;
- (id)sharedLynxGroupID:(id)a0;
- (BOOL)enableAnimaXWith:(id)a0;
- (void)handleShoppingTabRealFirstScreen;
- (id)tabViewControllerOf:(long long)a0;
- (double)iesecMallCrossSlideThreshold;
- (id)mallHeaderContainerGetTabHeaderHybridMonitorContext;
- (void)mallHeaderContainer:(id)a0 didDidFirstScreen:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)mallHeaderContainer:(id)a0 tabDidChanged:(id)a1;
- (void)mallHeaderContainer:(id)a0 tabInfoUpdated:(id)a1;
- (id)mallHeaderContainerGetCurrentTabViewController;
- (id)currentEnvIdentifierForLynxCard;
- (void)mallHeaderContainerLynxdidLoadFail:(id)a0;
- (void)mallHeaderContainer:(id)a0 mallSkinInfo:(id)a1;
- (void)startRefreshWithType:(long long)a0 completion:(id /* block */)a1;
- (void).cxx_destruct;
- (id)initWithDelegate:(id)a0;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)setupUI;
- (id)envIdentifier;

@end
