@class NSString, NSMutableDictionary;

@interface IESIMFTSStoreModuleService : NSObject <IESIMFTSStoreServiceProtocol> {
    struct _opaque_pthread_rwlock_t { long long __sig; char __opaque[192]; } _participantRWLock;
}

@property BOOL hasClosed;
@property (copy, nonatomic) NSString *curUid;
@property BOOL appWillTerminate;
@property (nonatomic) BOOL traceError;
@property (retain, nonatomic) NSMutableDictionary *databases;
@property (nonatomic) BOOL ftsParticipantOptEnable;
@property (nonatomic) double participantTrackRateDiff;
@property (nonatomic) double participantTrackRateAll;
@property (copy, nonatomic) id /* block */ userSortOrderBlock;
@property (copy, nonatomic) id /* block */ conversationSortOrderBlock;
@property (copy, nonatomic) id /* block */ messageSortOrderBlock;
@property (copy, nonatomic) id /* block */ participantSortOrderBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)initWithSetUpConfig:(id)a0;
- (void)insertOrUpdateUserDatas:(id)a0;
- (void)deleteUserDatasWithUid:(id)a0;
- (void)deleteAllUserDatas;
- (void)recalculateAllUserDatasSortOrder;
- (id)queryUsersWithKeywords:(id)a0 contentTypes:(id)a1 beforeSortOrder:(long long)a2 limit:(unsigned long long)a3;
- (id)queryUsersWithConfig:(id)a0;
- (void)insertOrUpdateConversationDatas:(id)a0;
- (void)deleteConversationDatasWithConvIds:(id)a0;
- (id)queryConversationsWithKeywords:(id)a0 contentTypes:(id)a1 beforeSortOrder:(long long)a2 limit:(unsigned long long)a3;
- (void)insertOrUpdateMessageDatas:(id)a0;
- (void)deleteMessageDatasWithMsgIds:(id)a0;
- (void)deleteMessageDatasWithConvIds:(id)a0;
- (void)deleteMessageDatasWithMessageTypes:(id)a0;
- (id)queryMessagesWithConfig:(id)a0;
- (long long)getTotalMessageCount;
- (long long)getTotalDeletedMessageCount;
- (long long)getTotalUserCount;
- (long long)getTotalDeletedUserCount;
- (long long)getTotalConversationCount;
- (long long)getTotalDeletedConversationCount;
- (long long)getTotalParticipantCount;
- (long long)getTotalDeletedParticipantCount;
- (void)insertOrUpdateParticipantDatas:(id)a0 withConversationId:(id)a1;
- (void)updateParticipantDatasWithUid:(id)a0 newContentDict:(id)a1;
- (void)deleteParticipantDatasWithUids:(id)a0;
- (void)deleteParticipantDatasWithConvIds:(id)a0;
- (void)deleteAllParticipantDatas;
- (id)queryParticipantsWithKeywords:(id)a0 contentTypes:(id)a1 beforeSortOrder:(long long)a2 limit:(unsigned long long)a3;
- (void)handleParticipantChangeWithConversationID:(id)a0 updates:(id)a1 deletes:(id)a2 version:(long long)a3;
- (long long)ftsParticipantVersionWithConversationID:(id)a0;
- (void)executeCheckpointWithCompletion:(id /* block */)a0;
- (void)handleAppWillTerminateNotification:(id)a0;
- (void)setUpAllDBWithPath:(id)a0;
- (BOOL)canMakeDBOperation;
- (id)getUserDatasInTableWithDatas:(id)a0;
- (void)calculateSortOrderForUser:(id)a0;
- (void)p_trackLanchIO:(unsigned long long)a0;
- (void)batchRecalculateAllUserDatasSortOrder;
- (void)recalculateUserDatasSortOrder:(id)a0;
- (id)getConversationDatasInTableWithDatas:(id)a0;
- (void)calculateSortOrderForConversation:(id)a0;
- (id)getMessageDatasInTableWithDatas:(id)a0;
- (void)calculateSortOrderForMessage:(id)a0;
- (struct WCTExpr { struct basic_string<char, std::char_traits<char>, std::allocator<char>> { union __rep { struct __short { char x0[23]; unsigned char x1 : 7; unsigned char x2 : 1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long x2 : 63; unsigned char x3 : 1; } x1; } x0; } x0; Class x1; struct shared_ptr<WCTColumnBinding> { struct WCTColumnBinding *x0; struct __shared_weak_count *x1; } x2; Class x3; })getConditionWithConfig:(id)a0;
- (id)getParticipantDatasInTableWithConversationId:(id)a0;
- (void)calculateSortOrderForParticipant:(id)a0;
- (void)p_updateFTSParticipantVersionWithConversation:(id)a0 version:(long long)a1;
- (void)p_trackHandleParticipantChange:(BOOL)a0 startTime:(double)a1 updateCount:(long long)a2 conversationID:(id)a3;
- (id)getParticipantDatasInTableWithCondition:(struct WCTExpr { struct basic_string<char, std::char_traits<char>, std::allocator<char>> { union __rep { struct __short { char x0[23]; unsigned char x1 : 7; unsigned char x2 : 1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long x2 : 63; unsigned char x3 : 1; } x1; } x0; } x0; Class x1; struct shared_ptr<WCTColumnBinding> { struct WCTColumnBinding *x0; struct __shared_weak_count *x1; } x2; Class x3; })a0;
- (void)p_resetFTSParticipantVersionWithConversation:(id)a0;
- (id)p_getParticipantDatasInTableWithConversationId:(id)a0 userIDs:(id)a1;
- (BOOL)p_shouldSampleWithRate:(double)a0;
- (void)setUpDBWithPath:(id)a0 tableClass:(Class)a1 virtualTableClass:(Class)a2 dbTag:(int)a3;
- (id)queryMessagesWithKeywords:(id)a0 contentTypes:(id)a1 inConversation:(id)a2 beforeSortOrder:(long long)a3 limit:(unsigned long long)a4;
- (id)getTransactionWithTableName:(id)a0;
- (BOOL)insertNewUserDatas:(id)a0 inTransaction:(id)a1;
- (BOOL)updateUserDatas:(id)a0 skipVirtualTableWrite:(BOOL)a1 inTransaction:(id)a2;
- (BOOL)updateUserDataProperty:(const void *)a0 withValue:(id)a1 WithCondition:(struct WCTExpr { struct basic_string<char, std::char_traits<char>, std::allocator<char>> { union __rep { struct __short { char x0[23]; unsigned char x1 : 7; unsigned char x2 : 1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long x2 : 63; unsigned char x3 : 1; } x1; } x0; } x0; Class x1; struct shared_ptr<WCTColumnBinding> { struct WCTColumnBinding *x0; struct __shared_weak_count *x1; } x2; Class x3; })a2 inTransaction:(id)a3;
- (BOOL)deleteAllDatasWithTableName:(id)a0 virtualTableName:(id)a1 inTransaction:(id)a2;
- (id)convertRowsToFTSDatas:(id)a0 dataClass:(Class)a1 rowList:(struct WCTResultList { struct __list_node_base<WCTResult, void *> { void *x0; void *x1; } x0; unsigned long long x1; BOOL x2; })a2;
- (BOOL)insertNewConversationDatas:(id)a0 inTransaction:(id)a1;
- (BOOL)updateConversationDatas:(id)a0 skipVirtualTableWrite:(BOOL)a1 inTransaction:(id)a2;
- (BOOL)insertNewMessageDatas:(id)a0 inTransaction:(id)a1;
- (BOOL)updateMessageDatas:(id)a0 skipVirtualTableWrite:(BOOL)a1 inTransaction:(id)a2;
- (BOOL)deleteMessageWithCondition:(struct WCTExpr { struct basic_string<char, std::char_traits<char>, std::allocator<char>> { union __rep { struct __short { char x0[23]; unsigned char x1 : 7; unsigned char x2 : 1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long x2 : 63; unsigned char x3 : 1; } x1; } x0; } x0; Class x1; struct shared_ptr<WCTColumnBinding> { struct WCTColumnBinding *x0; struct __shared_weak_count *x1; } x2; Class x3; })a0 inTransaction:(id)a1;
- (BOOL)insertNewParticipantDatas:(id)a0 inTransaction:(id)a1;
- (BOOL)updateParticipantDatas:(id)a0 skipVirtualTableWrite:(BOOL)a1 inTransaction:(id)a2;
- (BOOL)deleteParticipantWithCondition:(struct WCTExpr { struct basic_string<char, std::char_traits<char>, std::allocator<char>> { union __rep { struct __short { char x0[23]; unsigned char x1 : 7; unsigned char x2 : 1; } x0; struct __long { char *x0; unsigned long long x1; unsigned long x2 : 63; unsigned char x3 : 1; } x1; } x0; } x0; Class x1; struct shared_ptr<WCTColumnBinding> { struct WCTColumnBinding *x0; struct __shared_weak_count *x1; } x2; Class x3; })a0 inTransaction:(id)a1;
- (void)traceWCDBError;
- (BOOL)setUpDBTables:(id)a0 withTableClass:(Class)a1 virtualTableClass:(Class)a2 error:(id *)a3;
- (void)setCheckPoint:(id)a0 withTableName:(id)a1;
- (BOOL)isCorruptedError:(id)a0;
- (void)executeCheckpointWithTableName:(id)a0 completion:(id /* block */)a1;
- (void)clearWithTableName:(id)a0;
- (void).cxx_destruct;
- (void)clear;
- (void)dealloc;

@end
