@class UIView, IESLiveCommentWidgetExpandEntryView, IESLiveCommentQuickReplyView, IESLiveCommentWidgetOperationView, IESLiveCommentPanelInnerConfiguration, NSMutableDictionary, IESLiveCommentPaidDanmakuSelectedView, IESLiveCommentWidgetInputView, IESLiveCommentPopupView, IESLiveCommentContext, NSString, IESLiveCommentStructurePanelConfig;
@protocol IESLivePrivilegeDanmakuSettingItemProtocol, IESLiveCommentPanelDelegate;

@interface IESLiveCommentPanelBaseImp : UIView <IESLiveCommentWidgetInputDelegate, IESLiveCommentWidgetExpandEntryViewDelegate, IESLiveCommentQuickReplyDelegate, IESLiveCommentPanelProtocol>

@property (nonatomic) BOOL inputViewDidClickReturn;
@property (nonatomic) BOOL disableMode;
@property (nonatomic) BOOL dismissAnimating;
@property (retain, nonatomic) UIView *backTapContainer;
@property (retain, nonatomic) UIView *topContainer;
@property (retain, nonatomic) IESLiveCommentQuickReplyView *quickReplyView;
@property (retain, nonatomic) UIView *mainInputAreaContainer;
@property (retain, nonatomic) UIView *inputContainer;
@property (retain, nonatomic) IESLiveCommentPaidDanmakuSelectedView *paidDanmakuSelectedView;
@property (retain, nonatomic) IESLiveCommentWidgetInputView *inputView;
@property (retain, nonatomic) UIView *expandContainer;
@property (retain, nonatomic) IESLiveCommentWidgetOperationView *expandOperationView;
@property (retain, nonatomic) IESLiveCommentWidgetExpandEntryView *expandEntryView;
@property (retain, nonatomic) NSMutableDictionary *detailViewDic;
@property (retain, nonatomic) UIView *expandDetailAreaContainer;
@property (retain, nonatomic) UIView *modalContainer;
@property (retain, nonatomic) UIView *lastExpandDetailView;
@property (retain, nonatomic) UIView *danmakuView;
@property (retain, nonatomic) IESLiveCommentPopupView *popupView;
@property (nonatomic) double currentPanelContentHeight;
@property (retain, nonatomic) IESLiveCommentPanelInnerConfiguration *conf;
@property (retain, nonatomic) IESLiveCommentStructurePanelConfig *config;
@property (retain, nonatomic) IESLiveCommentContext *commentContext;
@property (nonatomic) double panelShowTimeStamp;
@property (nonatomic) double pandlDismissTimeStamp;
@property (retain, nonatomic) id<IESLivePrivilegeDanmakuSettingItemProtocol> danmakuSettingItem;
@property (nonatomic) BOOL loadingDanmakuData;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<IESLiveCommentPanelDelegate> delegate;

- (void)didSetAttachingDIContext;
- (void)panelWillDismiss;
- (void)showPanel;
- (id)placeHolderText;
- (void)setupInputView;
- (void)dismissPanel;
- (void)setupContainers;
- (void)animateDismissPanelWithCompletion:(id /* block */)a0;
- (long long)commentStateFromEntryType:(unsigned long long)a0;
- (void)showCommentPopupViewWithContent:(id)a0 preferredHeight:(double)a1;
- (void)animateShowPanelWithCompletion:(id /* block */)a0;
- (id)realPlaceholderText;
- (BOOL)disableContainerViewsMoveWhenCommentPanelShow;
- (BOOL)useCommnetPanelShowTracker;
- (BOOL)shouldAddPaidDanmaku;
- (void)bindPaidDanmakuAction;
- (BOOL)paideDanmakuEnabled;
- (void)clickPaidDanmakuEntry;
- (void)setupPaidDanmakuView;
- (id)getDefaultPlaceHolder;
- (id)defaultComment;
- (double)getInputViewExtraLeftSpace;
- (id)pinCommentReplyHint;
- (id)placeholderTextFromServer;
- (unsigned long long)defaultEntryType;
- (void)p_logClickCommentSendWithActionTag:(id)a0;
- (void)paidDanmakuDidSelectTab:(id)a0;
- (void)danmakuCancelAction;
- (void)showModalContainer:(BOOL)a0;
- (void)paidDanmakuViewDidShow:(BOOL)a0;
- (void)removeKeyboardObservers;
- (void)trackPanelShowDuration;
- (void)addKeyboardObservers;
- (id)grayedOutDanmakuString;
- (void)interruptExpandEntryIfNeeded;
- (id)paidDanmakuPriceHint;
- (void)triggerSendAction;
- (void)heightChangeWithOffset:(double)a0;
- (unsigned long long)getEntryTypeForDetailViewWithItem:(id)a0;
- (void)detailAreaChange:(unsigned long long)a0 withDetailView:(id)a1;
- (BOOL)onlyChat;
- (BOOL)isThirdPartyKeyboard;
- (void)inputView:(id)a0 textDidChange:(id)a1;
- (BOOL)inputView:(id)a0 textShouldChange:(id)a1;
- (void)inputView:(id)a0 inputTextReachLimit:(long long)a1;
- (void)inputView:(id)a0 heightWillChangeTo:(double)a1 from:(double)a2;
- (void)inputViewDidClickReturnOnKeyboard:(id)a0;
- (void)inputView:(id)a0 activityEmojiReachLimit:(long long)a1;
- (void)expandEntryView:(id)a0 didSelectEntryItem:(id)a1;
- (void)expandEntryView:(id)a0 didDeselectEntryItem:(id)a1;
- (void)expandEntryView:(id)a0 willDisplayEntryItem:(id)a1;
- (void)expandEntryView:(id)a0 defaultEntryTypeUnavailable:(unsigned long long)a1;
- (BOOL)expandEntryView:(id)a0 shouldEntryItemDisplay:(id)a1;
- (void)quickReplyClickWithContentView:(id)a0;
- (id)initWithCommentPanelWithConf:(id)a0 commentContext:(id)a1;
- (id)initWithCommentPanelWithStructureConfig:(id)a0 commentContext:(id)a1;
- (void)setupQuickReplyContentView;
- (void)setupPaidDanmakuSwitch;
- (void)setupCommentExpandEntrysView;
- (void)setupCommentExpandOperationView;
- (double)getExpandDetailAreaContainerHeight;
- (BOOL)isFullScreen;
- (void).cxx_destruct;
- (void)keyboardWillShow:(id)a0;
- (void)keyboardWillHide:(id)a0;
- (BOOL)isAnchor;
- (void)setupWidgets;
- (id)hitTest:(struct CGPoint { double x0; double x1; })a0 withEvent:(id)a1;
- (void)setupViews;
- (BOOL)isAdmin;
- (void)setupConfig;

@end
