@class NSString, NSMutableDictionary, IESLivePublicScreenCollectionView, IESLivePublicScreenView;
@protocol IESLivePublicScreenAutoFixService, IESLiveMIFullLinkIndexMonitor;

@interface IESLiveMessageListMonitor : NSObject <IESLiveRoomWatchTimeDelegate, IESLiveMessageListMonitorService>

@property (nonatomic) double enterRoomRequestEndTimeStamp;
@property (nonatomic) double messageClientDispatchFirstMessageTimeStamp;
@property (nonatomic) double messageClientStartConnectTimeStamp;
@property (nonatomic) double firstFetchHistoryMessageTimeStamp;
@property (nonatomic) double firstMessageHandleTimeStamp;
@property (nonatomic) BOOL didHandleFirstMessage;
@property (nonatomic) double firstMessageNodeCreatedTimeStamp;
@property (nonatomic) double firstMessageCommitTimeStamp;
@property (nonatomic) BOOL isFirstBatchMessage;
@property (nonatomic) double firstMessageListUpdateTimeStamp;
@property (nonatomic) BOOL messageListFirstUpdate;
@property (nonatomic) double roomEnterDuration;
@property (nonatomic) BOOL messageClientStartEarlier;
@property (nonatomic) long long source;
@property (nonatomic) BOOL enableHistoryMessageBackend;
@property (nonatomic) double createTime;
@property (nonatomic) long long memberEnterCount;
@property (nonatomic) long long memberEnterFilterCount;
@property (nonatomic) long long memberEnterDiscardCount;
@property (retain, nonatomic) NSMutableDictionary *messageStageMap;
@property (nonatomic) unsigned long long currentDisplayStage;
@property (nonatomic) BOOL didCheckPublicScreenDisplay;
@property (nonatomic) BOOL didSwitchBackground;
@property (nonatomic) BOOL refreshState;
@property (nonatomic) BOOL consumeMsgState;
@property (nonatomic) BOOL consumeNodeState;
@property (nonatomic) BOOL refreshViewState;
@property (nonatomic) unsigned long long currentRefreshStage;
@property (nonatomic) long long startCheckRefreshErrorTime;
@property (nonatomic) unsigned long long refreshStageForCheckError;
@property (copy, nonatomic) NSString *lastHiddenReason;
@property (nonatomic) BOOL publicScreenIsHidden;
@property (retain, nonatomic) id<IESLiveMIFullLinkIndexMonitor> fullLinkIndexMonitor;
@property (retain, nonatomic) id<IESLivePublicScreenAutoFixService> autoFixService;
@property (nonatomic) BOOL roomMessageDisplay;
@property (nonatomic) BOOL memberMessageDisplay;
@property (nonatomic) BOOL chatMessageDisplay;
@property (nonatomic) long long timerDuration;
@property (nonatomic) BOOL enableNoMessageMonitor;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) IESLivePublicScreenView *publicScreen;
@property (weak, nonatomic) IESLivePublicScreenCollectionView *publicScreenCollectionView;
@property (nonatomic) BOOL messageStatisticSwitch;

+ (void)monitorPublicScreenWithEventName:(id)a0 preEvent:(id /* block */)a1 useTrace:(BOOL)a2 diContext:(id)a3;

- (void)didSetAttachingDIContext;
- (id)initWithDIContext:(id)a0;
- (void)liveRoomWatchMinitTick:(unsigned long long)a0;
- (void)recordMessage:(id)a0 withFlowStage:(unsigned long long)a1;
- (void)recordRefreshStage:(unsigned long long)a0;
- (void)recordPSDisplayStage:(unsigned long long)a0;
- (void)startShowPublicScreenCheck;
- (void)monitorDataOnComponentUnmount;
- (void)recordPublicScreenHidden:(BOOL)a0 withReason:(id)a1;
- (void)recordMessageReceived:(id)a0;
- (void)recordRefreshStateChanged:(BOOL)a0 withReason:(id)a1;
- (void)recordConsumeMsgStateChanged:(BOOL)a0 withReason:(id)a1;
- (void)recordConsumeNodeStateChanged:(BOOL)a0 withReason:(id)a1;
- (void)recordUpdateViewStateChanged:(BOOL)a0 withReason:(id)a1;
- (void)recordFirstPatchHistoryMessageFetch;
- (void)recordFirstMessageHandle:(id)a0;
- (void)recordFirstNodeCreated;
- (void)recordFirstCommit;
- (void)recordFirstMessageListUpdate;
- (void)countFullLinkSelfChatWithMessage:(id)a0;
- (void)checkPublicScreenDisplayWithTimeCheckReport:(id)a0;
- (void)monitorFirstOnScreen;
- (void)trackMemberMessageDiscardInfo;
- (void)logAllStageMsgIDs;
- (void)getMessageClientTimerStamp;
- (id)stringWithFlowStage:(unsigned long long)a0;
- (void)reportNoMessageRefresh;
- (id)checkNoMessageRefreshError;
- (BOOL)refreshAllStateIsValid;
- (void)handleStateChangeForRefreshCheckError;
- (void)reportRefreshStateChangedWithType:(id)a0 reason:(id)a1;
- (id)stringWithDisplayStage:(unsigned long long)a0;
- (id)checkPSDisplayStageError;
- (void)reportPublicScreenRefreshStage;
- (void)reportMessageShowStatsIfNeeded;
- (void)checkPublicScreenRefreshError;
- (void)didBecomeActive;
- (void).cxx_destruct;
- (void)didEnterBackground;
- (void)addObserver;

@end
