@class RACDisposable, NSArray, NSString, IESliveAudienceInteractPanelManager, IESLiveBigPartyAnchorStore, IESLivePrivacyPolicyToken, IESLiveAudienceInteractFinishPopupView, IESLiveBigPartyTransferRouterImpl, IESLiveInteractionConfirmPanel, IESLiveBigPartyMSequenceAnchorManager;
@protocol IESLiveBigPartyAnchorAction, IESLiveCompoundSubscription, IESLiveInteractionSettingsRouter, IESLiveShareServiceAdapter, IESLivePerfSampler, IESLiveInteractionLinkerService;

@interface IESLiveBigPartyAnchorFragment : IESLiveRoomComponent <IESLiveBigPartyAnchorRouter, IESLiveBigPartyAnchorReaction, IESLiveComponentLifeCycleNotifier, IESLiveAudienceInteractiveRootPanelDelegate, IESLiveBigPartyProvider, IESLiveBigPartyActions, IESLiveInteractiveBigEventActions, IESLiveAnchorPaidLinkMicAction, IESLiveKTVModeSwitchAction, IESLiveMultiKTVStageActions, IESLiveInteractionEmojiProvider, IESLiveInteractVideoCaptureAction, IESLiveBigPartyTransferRouterDataSource, IESLiveInteractionPlaymodeActions, IESLiveAnchorCameraPermissionHandler, IESLiveAnchorPrivacyPermissionProtocol, IESLiveInteractionLinkerServiceAction, IESLiveTeamFightAction, IESLiveSocialInteractAction, IESLiveAnchorRoomStatusChangeEvents, IESLiveAnchorPFBizListAction, IESLivePrivacyContextProvider>

@property (retain, nonatomic) IESLiveBigPartyAnchorStore *store;
@property (retain, nonatomic) id<IESLiveCompoundSubscription> disposable;
@property (weak, nonatomic) RACDisposable *videoCaptureLevelDisposable;
@property (weak, nonatomic) IESLiveAudienceInteractFinishPopupView *finishPopupView;
@property (retain, nonatomic) NSArray *readedApplications;
@property (nonatomic) BOOL didLayout;
@property (retain, nonatomic) id<IESLiveBigPartyAnchorAction> actionCreator;
@property (retain, nonatomic) id<IESLiveShareServiceAdapter> shareService;
@property (nonatomic) BOOL invitationGuideHasShown;
@property (nonatomic) BOOL hasStartedLive;
@property (nonatomic) BOOL needResumeChatroom;
@property (nonatomic) BOOL directStartChatRoom;
@property (nonatomic) BOOL previousChangeToFullInteractOnlySelf;
@property (retain, nonatomic) IESLiveInteractionConfirmPanel *confirmPanel;
@property (weak, nonatomic) id<IESLivePerfSampler> perfSampler;
@property (nonatomic) BOOL isClosingLiveRoom;
@property (copy, nonatomic) NSString *multiLinkGameId;
@property (nonatomic) BOOL isEnterBackground;
@property (nonatomic) BOOL manualCloseCamera;
@property (retain, nonatomic) IESLiveBigPartyTransferRouterImpl *bigPartyTransferRouter;
@property (retain, nonatomic) IESLiveBigPartyMSequenceAnchorManager *mSeqManager;
@property (retain, nonatomic) IESliveAudienceInteractPanelManager *panelManager;
@property (weak, nonatomic) id<IESLiveInteractionSettingsRouter> interactionSettings;
@property (retain, nonatomic) id<IESLiveInteractionLinkerService> linker;
@property (retain, nonatomic) IESLivePrivacyPolicyToken *privacyToken;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)isMixed;

- (void)componentBindService;
- (void)componentCreate;
- (void)componentMount;
- (void)componentDidAppear;
- (void)componentDidDisappear;
- (void)componentUnmount;
- (void)componentOrientationTransitioning:(long long)a0;
- (void)mountDidFinishForLevel:(long long)a0;
- (BOOL)couldUnmountComponent;
- (void)currentLayoutUIDidUpdateFrom:(id)a0 to:(id)a1;
- (id)linkmicHost;
- (void)showAdminInteractivePanel;
- (BOOL)isInAnonymousPaidLinkmicWithUserID:(id)a0;
- (BOOL)isInAudienceLinkmic;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })guestListViewFrame;
- (unsigned long long)previousScene;
- (void)resumeVideoCapture;
- (void)cleanDataSource;
- (BOOL)canHandleVideoCapture;
- (void)startLive;
- (void)prepareAnchorLive;
- (void)startAnchorLiveWithRoom:(id)a0;
- (void)pauseAnchorLiveWithType:(unsigned long long)a0;
- (void)willStopAnchorLive;
- (BOOL)needIgnoreProcessGeneralVideoCaptureByResumeType_old:(long long)a0;
- (id)allSeatProviderViews;
- (id)providePrivacyContextForKey:(id)a0;
- (BOOL)userInActiveList:(id)a0;
- (BOOL)bigPartyAdminModeEnable;
- (BOOL)hasDealWithFirstSEI;
- (id)bizView;
- (BOOL)didConnectToAnchor;
- (BOOL)isApplyingToJoinChannel;
- (id)emojiContainerForUserID:(id)a0 isInteractiveEmoji:(BOOL)a1;
- (BOOL)userInActiveOrWaitingList:(id)a0;
- (id)onlineUserWrapper:(id)a0;
- (BOOL)isPreApplyingToJoinChannel;
- (id)needIgnoreProcessGeneralVideoCaptureByResumeType:(long long)a0;
- (unsigned long long)tryToShowInvitePanelWithIsTask:(BOOL)a0 activityName:(id)a1;
- (unsigned long long)tryToStartApplyProcessingWithIsTask:(BOOL)a0 activityName:(id)a1 applyType:(id)a2 applySource:(id)a3;
- (void)popUpOperationRootPanelLandingAtTab:(long long)a0 source:(id)a1;
- (id)guestInfoList;
- (id)activedList;
- (id)interactUserList;
- (id)waitingList;
- (BOOL)isAudioCaptureThisTime;
- (void)muteSelf:(BOOL)a0;
- (void)muteSelfForKTVSing:(BOOL)a0;
- (void)userProfileWillAppear;
- (void)leave:(id)a0 directly:(BOOL)a1 completed:(id /* block */)a2;
- (void)applyConnectionWithParams:(id)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })playerFrameWithOriginFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (id)guestBattleUIAdaptor;
- (void)openPaidLimitLinkTimeSettingPanelWithGuest:(id)a0;
- (BOOL)isInPaidLinkmic;
- (void)pfBizListMicrophoneStatusViewDidTapped;
- (BOOL)isEnlargeGuestLayoutStyle;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })anchorContainerFrame;
- (int)uilayout;
- (void)handlePauseAction;
- (void)inviteWithUserID:(id)a0 secUserID:(id)a1 sourcePage:(id)a2;
- (id)allInteractUserList;
- (BOOL)bigPartyModeEnable;
- (BOOL)bigPartyAdminRightEnable;
- (BOOL)isInvitingUser:(id)a0;
- (double)offsetYOfAnchorInteractiveEmojiEndPointAnimationContainer;
- (BOOL)playerbeInInteractLayoutStyle;
- (double)giftOffsetHeight;
- (void)onClickInteractEntranceItem;
- (void)showBigPartyPanelWithSeatIndex:(id)a0;
- (void)showLinkPanel:(long long)a0 source:(id)a1;
- (void)showThemeCompetitionPanelWithSource:(id)a0;
- (void)showAnchorOperationPanelForGuest:(id)a0;
- (void)showAnchorOperationPanelForGuest:(id)a0 requestPage:(id)a1;
- (void)trackSeatClickedEventWithExtra:(id)a0 seatIndex:(long long)a1;
- (void)trackSeatHeadClickedWithUser:(id)a0;
- (void)acceptStrongReminderRequestWithUser:(id)a0 requestPage:(id)a1;
- (BOOL)enableCameraRemoteControl;
- (void)acceptConnnectionWithUserID:(id)a0 requestPage:(id)a1;
- (void)muteSelfDirectly:(BOOL)a0;
- (void)stopBigPartyInteract;
- (void)startAudienceLinkmic:(id)a0;
- (void)closeBigPartyWithSourceType:(long long)a0 confirmAction:(id /* block */)a1;
- (void)p_trackFeedbackViewShow;
- (void)showUserPreView:(id)a0 trackerLabel:(id)a1;
- (void)updateWithLiveCoreExtInfo:(id)a0 rtcExtInfo:(id)a1;
- (BOOL)enableAudienceLinkMic;
- (void)interactionPlaymodeDidStart:(int)a0;
- (void)interactionPlaymodeDidEnd:(int)a0;
- (void)interactionLinkerService:(id)a0 muteStateDidChange:(BOOL)a1 reason:(id)a2;
- (void)interactionLinkerServiceAppDidActive:(id)a0;
- (void)interactionLinkerServiceAppResignActive:(id)a0;
- (void)interactionLinkerService:(id)a0 onSwitchMixTypeResult:(long long)a1 isMixOnClient:(BOOL)a2;
- (void)interactionLinkerService:(id)a0 interactListDidChangeFrom:(id)a1 to:(id)a2;
- (void)interactionLinkerService:(id)a0 didCloseWithContext:(id)a1;
- (void)interactionLinkerServiceInteractPrepareWillReady:(id)a0;
- (void)interactionLinkerServiceInteractWillStart:(id)a0;
- (void)interactionLinkerServiceInteractDidStart:(id)a0;
- (void)interactionLinkerServiceInteractDidEnd:(id)a0 error:(id)a1;
- (void)interactionLinkerServiceUserAlreadyLinked:(id)a0;
- (void)interactionLinkerService:(id)a0 interactReceiveError:(id)a1;
- (void)interactionLinkerService:(id)a0 linkerOccurError:(id)a1;
- (id)topRightItem;
- (void)audienceInteractiveRootPanel:(id)a0 shareWithClickScene:(id)a1 shareScene:(id)a2;
- (void)audienceInteractiveRootPanelOnGuestAutoLinkMic:(id)a0 completion:(id /* block */)a1;
- (void)audienceInteractiveRootPanel:(id)a0 permitApplicationOfUser:(id)a1 extraInfo:(id)a2;
- (void)audienceInteractiveRootPanel:(id)a0 inviteWithUserID:(id)a1 secUserID:(id)a2 sourcePage:(id)a3 params:(id)a4;
- (void)audienceInteractiveRootPanel:(id)a0 inviteWithUserID:(id)a1 secUserID:(id)a2 sourcePage:(id)a3;
- (void)audienceInteractiveRootPanelNeedToResetWaitingApplications:(id)a0;
- (void)audienceInteractiveRootPanel:(id)a0 onTabShowWithType:(id)a1;
- (void)audienceInteractiveRootPanel:(id)a0 fetchInvitableFriendsListWithCount:(unsigned long long)a1 completion:(id /* block */)a2;
- (void)audienceInteractiveRootPanelEndInteract:(id)a0;
- (void)paidLinkmicOpenStatusChanged:(BOOL)a0;
- (void)paidLinkmicDidReceiveAddPriceMessage:(id)a0;
- (id)guestsListView;
- (id)rootPanelTopRightItemWithPosition:(long long)a0;
- (id)targetGuestListView;
- (void)onAnchorClickSelf:(id)a0;
- (void)directStartWithLayout:(id)a0;
- (void)directStopWithLayout:(id)a0;
- (void)directSwitchToLayout:(id)a0;
- (void)didStartKTVWithPlayMode:(int)a0;
- (void)didEndKTVWithPlayMode:(int)a0;
- (void)didCreateTreamFight:(id)a0;
- (void)willFinishedTeamFight:(long long)a0;
- (id)bigPartyPanel;
- (void)directStartIfNeeded;
- (BOOL)startByAutoOpen;
- (void)startInteractIfNeedWhileDirectStartOrResumeChatroom;
- (BOOL)shouldSendBackgroundSignalWhenComponentDidDisappear;
- (void)startGameIfNeeded;
- (void)bigPartyDidEnd;
- (unsigned long long)p_normalizeSocialScene:(unsigned long long)a0;
- (void)anchorDidReceiverError:(id)a0;
- (BOOL)shouldSendBackgroundSignalWhenAppActiveStateChange;
- (void)showBigPartyPanelWithSeatIndex:(id)a0 enterFrom:(id)a1;
- (void)showBigPartyPanelWithSeatIndex:(id)a0 enterFrom:(id)a1 customPanelConfig:(id /* block */)a2;
- (id)bigPartyPanelViewModel;
- (unsigned long long)correctCurrentScene;
- (void)p_triggerInvitationGuideIfNeeded;
- (void)p_showSettingGuidePanel;
- (void)p_resumeBigPartyLayout;
- (BOOL)isLiveViewVisiable;
- (BOOL)isMiniAppScreenCastRunning;
- (void)p_trackAnchorNewConnectionPanelShow;
- (void)p_showAnchorOperationActionSheetForOtherLinkerGuest:(id)a0;
- (id)convertActivedToGuest:(id)a0;
- (id)interactiveEmojiEndPointAnimationContainerForUserID:(id)a0;
- (id)ownEmojiContainerForUserID:(id)a0;
- (void)p_trackAdminLinkSettingChangeSuccess;
- (void)p_trackAdminLinkSettingChangeShow;
- (void)p_trackFeedbackUploaded;
- (void)p_trackFeedbackConfirmClick;
- (void)shareLiveRoomWithScene:(id)a0;
- (void)bigPartyLayoutDidStarted:(id)a0;
- (void)bigPartyLayoutDidChangeFrom:(id)a0 to:(id)a1;
- (id)pkAudienceLinkmicMediaService;
- (void)p_addLinkSettingToolBarItem;
- (void)didStartRoomBattle;
- (void)p_trackGuestConnectAction:(BOOL)a0;
- (BOOL)enableEditSeatName;
- (BOOL)isEnlargeGuestLayout;
- (BOOL)isEqualStyle;
- (BOOL)p_enabledPaidLinkmicAddPrice;
- (id)cameraPreview;
- (BOOL)isDynamic;
- (void).cxx_destruct;
- (unsigned long long)currentScene;
- (void)stopVideoCapture;
- (BOOL)isMute;

@end
