@class IESLLPOIShareModel, IESLLPOICardModel, IESLLPOIAnchorBehaviorModel, IESLLPOITradingModel, NSDictionary, IESLLAddressModel, IESLLIndirectPOIInfoModel, IESLLPOIScanActivityInfo, UIImage, IESLLCouponModel, NSString, IESLLPOIAnchorCommentInfo, IESLLifeURLModel, IESLLPOIProductSimpleModel, NSArray, NSNumber, IESLLPOIItemAnchorInfo, IESLLPOIAnchorLifeExtraModel, IESLLPOITypeModel;
@protocol IESLLFuseAddressModel;

@interface IESLLPOIInfoModel : IESLLifeBaseApiModel <IESLLFusePOIInfoModel>

@property (readonly, copy, nonatomic) NSString *f_poiID;
@property (readonly, copy, nonatomic) NSString *f_poiName;
@property (readonly, copy, nonatomic) NSString *f_typeCode;
@property (readonly, nonatomic) id<IESLLFuseAddressModel> f_addressInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSNumber *moduelUnique;
@property (retain, nonatomic) NSDictionary *extraLogInfo;
@property (copy, nonatomic) NSDictionary *panelExtraData;
@property (copy, nonatomic) NSString *distanceToSpace;
@property (copy, nonatomic) NSArray *headerImages;
@property (copy, nonatomic) NSString *subTypeForShare;
@property (copy, nonatomic) NSString *costStringForShare;
@property (nonatomic) BOOL modalScene;
@property (nonatomic) BOOL isFromPOITravel;
@property (copy, nonatomic) NSString *cpsInfo;
@property (copy, nonatomic) NSString *poiContentExtra;
@property (retain, nonatomic) IESLLPOIItemAnchorInfo *cacheAnchorInfo;
@property (retain, nonatomic) IESLLIndirectPOIInfoModel *cacheIndirectPOIInfo;
@property (retain, nonatomic) NSDictionary *cachePOIExtendItemDict;
@property (retain, nonatomic) IESLLPOIAnchorCommentInfo *cachePOICommentInfo;
@property (copy, nonatomic) NSString *serviceTypeBury;
@property (copy, nonatomic) NSString *productType;
@property (copy, nonatomic) NSString *productBizline;
@property (copy, nonatomic) NSString *distanceMetersBury;
@property (retain, nonatomic) NSDictionary *extendJsonDictionary;
@property (retain, nonatomic) IESLLPOIAnchorBehaviorModel *cacheAnchorBehavior;
@property (copy, nonatomic) NSString *poiID;
@property (copy, nonatomic) NSString *poiName;
@property (copy, nonatomic) NSString *typeCode;
@property (retain, nonatomic) IESLLPOITypeModel *poiBackendType;
@property (nonatomic) long long userCount;
@property (nonatomic) long long itemCount;
@property (copy, nonatomic) NSString *viewCount;
@property (copy, nonatomic) NSString *popularity;
@property (copy, nonatomic) NSString *collectedCount;
@property (retain, nonatomic) IESLLPOIShareModel *shareInfo;
@property (retain, nonatomic) IESLLifeURLModel *coverHD;
@property (retain, nonatomic) IESLLifeURLModel *coverLarge;
@property (retain, nonatomic) IESLLifeURLModel *coverMedium;
@property (retain, nonatomic) IESLLifeURLModel *coverThumb;
@property (retain, nonatomic) IESLLifeURLModel *coverItem;
@property (copy, nonatomic) NSString *poiTypeName;
@property (copy, nonatomic) NSString *poiAreaName;
@property (copy, nonatomic) NSString *distance;
@property (nonatomic) long long distanceMeter;
@property (retain, nonatomic) IESLLAddressModel *addressInfo;
@property (nonatomic) long long iconType;
@property (nonatomic) double latitude;
@property (retain, nonatomic) NSNumber *latitudeGCJ;
@property (nonatomic) double longitude;
@property (retain, nonatomic) NSNumber *longitudeGCJ;
@property (nonatomic) BOOL userFavorited;
@property (retain, nonatomic) IESLLifeURLModel *iconEntry;
@property (retain, nonatomic) IESLLifeURLModel *iconMap;
@property (retain, nonatomic) IESLLifeURLModel *iconLocation;
@property (retain, nonatomic) NSNumber *expandType;
@property (nonatomic) unsigned long long detailType;
@property (copy, nonatomic) NSString *voucherInfo;
@property (copy, nonatomic) NSString *poiSubtitle;
@property (nonatomic) unsigned long long subtitleType;
@property (retain, nonatomic) IESLLPOICardModel *poiCard;
@property (nonatomic) BOOL recommendFromMedia;
@property (copy, nonatomic) NSArray *voucherReleaseAreas;
@property (nonatomic) BOOL shouldShowHalfCard;
@property (nonatomic) BOOL isTopRecommend;
@property (nonatomic) BOOL isAdminArea;
@property (copy, nonatomic) NSArray *iconServiceTypeList;
@property (copy, nonatomic) NSString *itemTag;
@property (nonatomic) long long guessExpect;
@property (nonatomic) long long withRecommendTag;
@property (nonatomic) BOOL isUserWithinGeoFence;
@property (copy, nonatomic) NSString *extJSONString;
@property (retain, nonatomic) IESLLPOIProductSimpleModel *simpleProduct;
@property (copy, nonatomic) NSDictionary *shootReward;
@property (nonatomic) double cost;
@property (copy, nonatomic) NSArray *poiDetailTags;
@property (retain, nonatomic) IESLLPOITradingModel *poiTrading;
@property (nonatomic) long long spuCount;
@property (nonatomic) long long cpsSpuCount;
@property (nonatomic) BOOL isCommerceIntention;
@property (copy, nonatomic) NSString *videoSpuLynxUrl;
@property (nonatomic) BOOL isCps;
@property (retain, nonatomic) NSString *searchTagStr;
@property (retain, nonatomic) NSString *searchRightConfStr;
@property (copy, nonatomic) NSDictionary *anchorPostExt;
@property (retain, nonatomic) IESLLPOIAnchorLifeExtraModel *lifeExtra;
@property (retain, nonatomic) IESLLPOIScanActivityInfo *scanActivityInfo;
@property (copy, nonatomic) NSString *imShareHintText;
@property (retain, nonatomic) UIImage *poiDetailScreenShoot;
@property (retain, nonatomic) UIImage *mapThumbnail;
@property (copy, nonatomic) NSArray *recommendedAwemeCovers;
@property (retain, nonatomic) IESLLCouponModel *coupon;
@property (nonatomic) BOOL isFoodGroupBuy;
@property (nonatomic) BOOL isAtCallBackCollect;
@property (nonatomic) BOOL isFromCommentPublishNotice;
@property (copy, nonatomic) NSString *poi3ClassType;
@property (retain, nonatomic) NSArray *poiMapRankEntry;
@property (copy, nonatomic) NSString *feedTTLogID;
@property (readonly, nonatomic) NSString *anchorGuideTitle;
@property (readonly, nonatomic) NSString *exploreURL;
@property (readonly, nonatomic) unsigned long long entrySuffixType;
@property (readonly, copy, nonatomic) NSString *entrySuffixDesc;
@property (copy, nonatomic) NSString *cpsDetailLynxUrl;
@property (copy, nonatomic) NSArray *styleEffectIds;
@property (retain, nonatomic) NSString *spuCardLynxUrl;
@property (nonatomic) long long spuCardExtendTime;

+ (id)placeholderObjectForSchool;
+ (id)placeholderObjectForEmpty;
+ (id)poiDetailTagsJSONTransformer;
+ (id)poiMapRankEntryJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;

- (id)POIItemAnchorInfo;
- (id)anchorBehavior;
- (id)indirectPOIInfo;
- (id)backendType;
- (id)p_extendJsonDictionary;
- (id)searchTagDesc;
- (id)searchRightConfDesc;
- (BOOL)isRecommendForPublish;
- (id)poiCommentInfo;
- (id)f_backendType;
- (id)initWithDictionary:(id)a0 error:(id *)a1;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)a0;
- (void)_initialize;
- (id)subType;

@end
