@class IESLiveAnchorAdminPromptService, NSMutableSet, NSString, HTSLiveToolbarItem, IESLiveAdminSwitchCell, IESLiveAnchorAdminPromptViewHandle, IESLivePresentNavController, IESLiveAdminApi, UIViewController, ChatSettingGetResponse_ResponseData, IESLiveAudioChatSettingApi;
@protocol IESLiveAnchorRecordPreferenceService, IESLiveAdminManagerProtocol, IESLiveAnchorDynamicClarityPreferenceService, IESLiveAnchorPreferenceService, IESLiveAnchorCommentPreferenceService, IESLiveURLSchemaHandler, IESLiveAnchorBacktrackPreferenceService, IESLiveAnchorRankListPreferenceService, IESLiveAnchorSharePreferenceService, IESLiveAskExplainPreferenceService;

@interface IESLiveAnchorAdminFragment : IESLiveRoomComponent <HTSLiveMessageSubscriber, IESLiveAnchorAdminPromptViewHandleDelegate, IESLiveAdministerPrivilegeServiceRouter, IESLiveAdminstratorListNewCellDelegate, IESLiveAnchorRoomStatusChangeEvents, IESLiveGuideRecordReplayService>

@property (retain, nonatomic) IESLiveAdminApi *adminApi;
@property (retain, nonatomic) IESLivePresentNavController *managerNav;
@property (retain, nonatomic) UIViewController<IESLiveAdminManagerProtocol> *managerVc;
@property (retain, nonatomic) HTSLiveToolbarItem *managerVcSuperItem;
@property (retain, nonatomic) UIViewController<IESLiveAdminManagerProtocol> *settingVc;
@property (retain, nonatomic) IESLivePresentNavController *adminSettingNav;
@property (retain, nonatomic) id<IESLiveAnchorRecordPreferenceService> recordPreference;
@property (retain, nonatomic) id<IESLiveAskExplainPreferenceService> askExplainPreference;
@property (retain, nonatomic) id<IESLiveAnchorRankListPreferenceService> rankListPreference;
@property (retain, nonatomic) id<IESLiveAnchorDynamicClarityPreferenceService> clarityPreference;
@property (retain, nonatomic) id<IESLiveAnchorBacktrackPreferenceService> backtrackPreference;
@property (retain, nonatomic) id<IESLiveAnchorPreferenceService> anchorPreferce;
@property (retain, nonatomic) id<IESLiveAnchorCommentPreferenceService> commentPreference;
@property (retain, nonatomic) id<IESLiveAnchorSharePreferenceService> sharePreference;
@property (retain, nonatomic) id<IESLiveURLSchemaHandler> schemaHandler;
@property (retain, nonatomic) IESLiveAnchorAdminPromptViewHandle *promptViewHandle;
@property (retain, nonatomic) IESLiveAnchorAdminPromptService *adminPromptService;
@property (weak, nonatomic) IESLiveAdminSwitchCell *earMonitorCell;
@property (nonatomic) BOOL isUsingBlueToothHeadPhone;
@property (nonatomic) BOOL backgroundWithoutBlueTooth;
@property (retain, nonatomic) ChatSettingGetResponse_ResponseData *audioChatSettingModel;
@property (retain, nonatomic) ChatSettingGetResponse_ResponseData *audioChatSettingModelForShow;
@property (retain, nonatomic) IESLiveAudioChatSettingApi *audioChatSettingApi;
@property (nonatomic) BOOL isSetAdminDanmakuPrivilegeToAdminDuringLive;
@property (retain, nonatomic) NSMutableSet *hasBeenSetAdminDanmakuPrivilegeAdmins;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)componentBindService;
- (void)componentCreate;
- (void)componentMount;
- (void)startAnchorLiveWithRoom:(id)a0;
- (void)willStopAnchorLive;
- (BOOL)isAdminNewStyle;
- (BOOL)isHavePrivilegeWithUser:(id)a0 privilegeType:(int)a1;
- (BOOL)isHavePrivilegeWithPrivilegeType:(int)a0;
- (void)showAdministrateSettingWithUser:(id)a0;
- (id)getSetAdminAuthorityVCInWhiteStyle:(BOOL)a0 height:(double)a1 isBottomType:(BOOL)a2;
- (void)showAdministrateSheet;
- (void)cancelManagerWithIndex:(long long)a0 managerModel:(id)a1;
- (void)adminDanmakuPrivilegeSetToAdmin:(id)a0;
- (void)initPromptViewHandleIfNeeded;
- (BOOL)isRecordHighlightEnable;
- (void)updateRecordHighlightEnable:(BOOL)a0 completion:(id /* block */)a1;
- (void)addAdminToolbarItem;
- (void)addSettingToolbarItem;
- (BOOL)supportEarItem;
- (BOOL)isBluetoothHeadPhonePlugging;
- (void)showAdminBubbleGuide;
- (BOOL)p_needShowPrompt;
- (void)showSkyEyeAnchorPanelWithMsg:(id)a0;
- (id)getAdminIconImage;
- (id)getAdminIconName;
- (void)updateAdminEntranceRedDotFor:(id)a0;
- (void)showAdministrateSheet:(id)a0;
- (BOOL)p_needShowHighlightRedDot;
- (void)showSettingSheet;
- (BOOL)p_needShowPlayBack;
- (BOOL)p_needShowRealTimePlayBack;
- (BOOL)p_needShowSyncProduct;
- (BOOL)p_needShowAskExplain;
- (BOOL)p_needShowExitRanklist;
- (BOOL)p_needShowAllowAudienceReceiveGift;
- (BOOL)p_needShowManageAudienceReceiveGiftList;
- (BOOL)p_needShowSubtitleSwitch;
- (BOOL)needShowItemOf:(unsigned long long)a0;
- (BOOL)p_hasECommercePermission;
- (BOOL)p_needShowFansGroupChatRedDot;
- (BOOL)p_sensitiveViewNeedShowRedDot;
- (BOOL)p_prompterNeedShowRedDot;
- (BOOL)p_needShowPrivilegeDanmakuSettingRedDot;
- (BOOL)p_needShowPinPrivilegeSettingRedDot;
- (BOOL)p_needShowAdminEntranceRedDot;
- (BOOL)shouldShowMirrorInMore;
- (BOOL)shouldShowClarityInMore;
- (void)showToastAndCloseBlueTooth;
- (void)tr_trackEarMonitorOpen:(BOOL)a0;
- (BOOL)isEarMonitorOpen;
- (void)showRecordPreferencePanel;
- (void)dismissSettingEntranceRedDot;
- (void)tr_trackRecordShow:(BOOL)a0;
- (void)p_triggerPlaybackEnable:(BOOL)a0 recordItem:(id)a1 syncProductItem:(id)a2 completion:(id /* block */)a3;
- (id)giftEffectSettingsCellItem;
- (id)anchorRankListCellItem;
- (void)p_allowCommentItem:(id)a0;
- (void)p_allowShareItem:(id)a0;
- (id)allowAdienceReceiveGiftItem;
- (id)manageReceiveGiftAudienceListItem;
- (void)p_syncProductItem:(id)a0 playbackRecordItem:(id)a1 replayRecordItem:(id)a2;
- (void)tr_trackSyncProductShow:(BOOL)a0;
- (void)p_askExplainItem:(id)a0;
- (void)tr_trackEarMonitorEffectiveOpen:(BOOL)a0;
- (id)createSettingItems;
- (void)updateFansGroupChatRedDotFor:(id)a0 adminEntrance:(id)a1;
- (void)pushFansChatListPage;
- (void)p_recordToolbarItemTappedForPrompt;
- (void)pushAdministratorList;
- (void)pushAdminSetting;
- (void)tr_trackSettingPanelClose;
- (id)createAdministrateSheetItems:(id)a0;
- (void)track_managetListDidClick;
- (id)p_createUnflodListViewControllerWithtype:(long long)a0;
- (void)p_pushOperateContainer:(id)a0;
- (void)p_sendUserPreviewShowReuqest:(BOOL)a0 target:(id)a1;
- (void)tr_trackClickHideConfirmBtnEvent;
- (void)tr_trackSwitchToggleEventWithShow:(BOOL)a0;
- (void)p_switchPlaybackRecordTo:(BOOL)a0 target:(id)a1 secondTarget:(id)a2 completion:(id /* block */)a3;
- (void)p_switchSyncProductTo:(BOOL)a0 target:(id)a1;
- (void)tr_trackRecordStatus:(BOOL)a0;
- (void)tr_trackSyncProductOpen:(BOOL)a0;
- (void)p_switchAskExplainTo:(BOOL)a0 target:(id)a1;
- (void)p_switchAllowCommentTo:(BOOL)a0 target:(id)a1;
- (void)p_switchAllowShareTo:(BOOL)a0 target:(id)a1;
- (void)tr_trackBlueToothToastShow;
- (void)p_ChangeRankListStatusWithRankListsStatus:(id)a0 cell:(id)a1;
- (void)tr_trackAudienceReceiveGiftAuthWithTargetValue:(BOOL)a0 result:(BOOL)a1;
- (BOOL)isUsingBloothEarMonitorDH;
- (void)p_showRankListSwitchPanel:(id)a0;
- (void)p_updateAudienceReceiveGiftSwitchTo:(BOOL)a0 cell:(id)a1;
- (void)tr_trackManageAudienceGiftReceiverEntranceClick;
- (void)onPromptUserNameTapped:(id)a0;
- (void)onPromptMessageShowFinished:(id)a0 duration:(double)a1;
- (void)handleBanUserPreviewWithTarget:(id)a0;
- (void)tr_backTrackItemDidSwitch:(BOOL)a0;
- (void).cxx_destruct;
- (void)appDidEnterBackground:(id)a0;
- (void)dealloc;
- (void)appWillEnterForeground:(id)a0;
- (void)messageReceived:(id)a0;
- (void)audioRouteDidChange:(id)a0;

@end
