@class HTSEventContext, NSString, IESLiveKTVMusicManager, IESLivePartyKTVChorusJumpService, NSArray, NSMutableDictionary, IESLiveCombineSubject, IESLiveKTVCommonStore, HTSLiveUser, NSMutableArray, IESLiveKtvSongStruct;
@protocol IESLiveVideoChorusService, IESLiveTracker, IESLiveMixKTVRouter, IESLiveRoomService, IESLiveKTVFullLinkMonitor, IESLiveKTVOptimizeCellDelegate, IESLiveKTVMultiChorusRouter, IESLiveKTVDecorateService, IESLiveKTVSongListActions, IESLiveKTVApplySingListActions;

@interface IESLiveCommonKTVOrderPanelModel : NSObject <IESLiveKTVDecorateReaction, IESLiveKTVMultiChorusActions, IESLiveInteractionLinkerServiceAction, IESLiveKTVOrderPanelProtocol, IESLiveMixKTVApplySingCellDelegate, IESLiveKTVWillSingCellDelegate>

@property (retain, nonatomic) IESLiveKTVMusicManager *ktvMusicManager;
@property (nonatomic) long long requestMode;
@property (weak, nonatomic) id<IESLiveKTVSongListActions> songActionsCreator;
@property (retain, nonatomic) IESLiveKtvSongStruct *unitTestMusicModel;
@property (weak, nonatomic) id<IESLiveVideoChorusService> videoChorusService;
@property (nonatomic) BOOL isCPUOptimize;
@property (weak, nonatomic) HTSLiveUser *currentLoginUser;
@property (retain, nonatomic) IESLivePartyKTVChorusJumpService *partyKTVChorusJumpService;
@property (nonatomic) BOOL isMixKTV;
@property (nonatomic) BOOL isMultiKTV;
@property (nonatomic) BOOL isAnchor;
@property (nonatomic) unsigned long long waitingOffset;
@property (copy, nonatomic) NSString *waitingPrompts;
@property (copy, nonatomic) id /* block */ scrollOrderBlk;
@property (nonatomic) BOOL needToOrderTab;
@property (nonatomic) BOOL isAuto;
@property (weak, nonatomic) IESLiveKTVCommonStore *store;
@property (nonatomic) BOOL isMusicPlaying;
@property (nonatomic) long long multiChorusApplyCount;
@property (weak, nonatomic) id<IESLiveKTVApplySingListActions> applyActionsCreator;
@property (weak, nonatomic) id<IESLiveKTVMultiChorusRouter> multiChoursCreator;
@property (weak, nonatomic) id<IESLiveKTVDecorateService> decorateServiceImpl;
@property (weak, nonatomic) id<IESLiveMixKTVRouter> mixKTVRouter;
@property (nonatomic) long long audienceApplyCount;
@property (copy, nonatomic) NSString *highScoreCountStr;
@property (nonatomic) BOOL needDecorateUnRead;
@property (weak, nonatomic) id<IESLiveKTVOptimizeCellDelegate> optimizeCellDelegate;
@property (nonatomic) BOOL isVideoChorusStarted;
@property (retain, nonatomic) NSMutableArray *segTitles;
@property (retain, nonatomic) NSArray *segTypeArr;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (copy, nonatomic) NSString *fastStartTabName;
@property (nonatomic) long long fastStartFirstLevelIndex;
@property (nonatomic) BOOL isSearching;
@property (retain, nonatomic) HTSEventContext *trackContext;
@property (retain, nonatomic) id<IESLiveRoomService> room;
@property (nonatomic) BOOL isOrderPanlShow;
@property (retain, nonatomic) id<IESLiveTracker> tracker;
@property (retain, nonatomic) id<IESLiveKTVFullLinkMonitor> ktvMonitor;
@property (retain, nonatomic) NSMutableDictionary *singListCallBackBlkDict;
@property (copy, nonatomic) id /* block */ showFeedBackBlock;
@property (retain, nonatomic) IESLiveCombineSubject *orderPanelActionSignal;
@property (nonatomic) BOOL isLinked;
@property (nonatomic) BOOL enableRecommendChorusRoom;
@property (nonatomic) BOOL isSoloKTV;

- (void)didSetAttachingDIContext;
- (BOOL)isOpenApply;
- (void)refreshAudienceAlready:(id)a0;
- (id)canApplySingSignal;
- (id)canMultiChorusSingSignal;
- (long long)getDefaultIndex;
- (id)currentUserType;
- (void)trackSoloKTVEntranceShow;
- (void)trackSoloKTVEntranceClick;
- (BOOL)isKTVController;
- (id)topSongId;
- (void)interactionLinkerService:(id)a0 userStateDidChangedFrom:(long long)a1 to:(long long)a2;
- (BOOL)useOldIMOrderList;
- (long long)getTotalOrderCount;
- (BOOL)hasJoinChannel;
- (void)clearYellowDotIfNeed;
- (id)wantSingSongCountSignal;
- (BOOL)canApplySing;
- (void)didReceiveYellowDotFromRemote;
- (void)didClearYellowDot;
- (void)didJoinMultiChorusForMusicModel:(id)a0;
- (void)didLeaveMultiChorusForMusicModel:(id)a0;
- (BOOL)canMultiChorus;
- (void)fetchKTVCategoryWithRequestMode:(long long)a0 firstLevelTab:(int)a1 completion:(id /* block */)a2;
- (long long)p_getIndexWithFirstLevelTab:(int)a0;
- (void)fetchKTVMusicListWithRequestMode:(long long)a0 firstLevelTab:(int)a1 category:(id)a2 isLoadMore:(BOOL)a3 topSongId:(id)a4 collectionId:(id)a5 completion:(id /* block */)a6;
- (BOOL)shouldAddAudienceSingTab;
- (void)trackSongShowWithMusicModel:(id)a0 source:(id)a1 forIndexPath:(id)a2 category:(id)a3 mainTab:(id)a4;
- (void)trackCollectSongEventWithMusic:(id)a0 source:(id)a1;
- (void)trackClickedKSongButtonEventWithSource:(id)a0 musicModel:(id)a1 isPlayAll:(BOOL)a2 index:(long long)a3;
- (void)cell:(id)a0 songDidAddSuccessFor:(id)a1;
- (void)trackClickedKSongSuccessEventWithSource:(id)a0 musicModel:(id)a1 index:(long long)a2;
- (void)cell:(id)a0 refreshDownloadButtonUIWithMusicModel:(id)a1;
- (void)requestHighScoreSongsCountIfNeed;
- (void)postNotificationToWebcastForPersonalCardShow;
- (void)trackKsongChorusButtonClickWithMusicModel:(id)a0 hasJoined:(BOOL)a1 category:(id)a2;
- (void)showConfirmToRemoveAlertWithModel:(id)a0 isCutSong:(BOOL)a1 completion:(id /* block */)a2;
- (void)trackClickedEventWithType:(id)a0 model:(id)a1;
- (void)insertContentWithParams:(id)a0 musicModel:(id)a1;
- (id)tabTitleForCellType:(long long)a0;
- (long long)multiChorusUnReadCount;
- (long long)applyUnReadCount;
- (long long)listenUnReadCount;
- (id)soloKTVEntranceSource;
- (BOOL)enableSoloKTVEntranceShowInCurrentScene;
- (long long)audienceUnReadCount;
- (BOOL)liveKtvEnableOpenMultiChorus;
- (void)listView:(id)a0 configurationForCell:(id)a1;
- (void)listView:(id)a0 configurationFooter:(id)a1 forSection:(long long)a2;
- (void)listView:(id)a0 willDisplayCell:(id)a1 forIndexPath:(id)a2;
- (void)cell:(id)a0 didFavoriteItem:(id)a1;
- (void)cell:(id)a0 didClickMultiChorus:(BOOL)a1 forItem:(id)a2;
- (void)cell:(id)a0 didClickChorusRecommendInfo:(id)a1 forItem:(id)a2;
- (void)cell:(id)a0 clickedAddSongFor:(id)a1;
- (void)cell:(id)a0 clickedWantListenFor:(id)a1;
- (void)showMusicListFeedbackInHomePanelViewWithSongName:(id)a0 singerName:(id)a1;
- (id)combineMusicListArray:(id)a0 firstLevelTab:(int)a1 category:(id)a2;
- (BOOL)needRefreshWithName:(id)a0;
- (BOOL)needAddAllHeaderWithName:(id)a0;
- (BOOL)needShowCountWithName:(id)a0;
- (BOOL)needReloadDataWithName:(id)a0;
- (void)addSingListCallBackWithViewModel:(id)a0;
- (void)refreshTabSortStatusWithTabArray:(id)a0;
- (void)needLoadBannerData;
- (void)fetchKTVMusicListWithRequestMode:(long long)a0 firstLevelTab:(int)a1 category:(id)a2 completion:(id /* block */)a3;
- (void)trackContainerCellShow;
- (void)trackShowPageWithViewModel:(id)a0;
- (void)trackClickSearchEventWithSearchType:(long long)a0 requestPage:(id)a1;
- (void)trackSearchRequestEventWithContent:(id)a0 contentType:(id)a1 searchType:(long long)a2;
- (void)trackSearchResultEventWithContent:(id)a0 requestPage:(id)a1 contentType:(id)a2 searchType:(long long)a3;
- (void)trackCellShowWithList:(id)a0;
- (void)cell:(id)a0 agreeFor:(id)a1;
- (void)cell:(id)a0 clickCell:(id)a1;
- (void)cell:(id)a0 goTopFor:(id)a1;
- (void)cell:(id)a0 pauseFor:(id)a1;
- (void)cell:(id)a0 removeFor:(id)a1;
- (void)cell:(id)a0 linkFor:(id)a1;
- (void)cell:(id)a0 changeRoomFor:(id)a1;
- (void)fetchTabSelectedIndexWithRequestMode:(long long)a0 firstLevelTab:(int)a1 completion:(id /* block */)a2;
- (id)getPersonalCardURL;
- (void)addAllMusicModel:(id)a0 source:(id)a1;
- (void)loadSoloKTV;
- (BOOL)enableSoloKTVEntranceShow;
- (void)exitKTVWithCompletion:(id /* block */)a0;
- (id)listenUnReadCountSignal;
- (id)audienceUnReadCountSignal;
- (id)applyUnReadCountSignal;
- (id)multiChorusUnReadCountSignal;
- (id)canMultiChorusSignal;
- (long long)tabIndexWithCellType:(long long)a0;
- (void).cxx_destruct;
- (id)initWithStore:(id)a0;
- (void)addObserver;
- (id)currentUser;
- (id)collectionId;

@end
