@class IESLiveKTVResourceManager, NSString, HTSEventContext, IESLiveCombineSubject, IESLiveVideoPlayerController, NSMutableDictionary, IESLiveKTVRecommendItem, IESLiveKTVCommonApi, NSMutableArray;
@protocol IESLiveKTVFullLinkMonitor, IESLiveKTVMusicManagerProtocol, IESLiveRoomService, IESLiveTracker;

@interface IESLiveInteractGameMusicPanelModel : NSObject <IESLiveVideoPlayerControllerDelegate, IESLiveKTVOrderPanelProtocol>

@property (retain, nonatomic) IESLiveKTVCommonApi *api;
@property (nonatomic) long long requestMode;
@property (retain, nonatomic) IESLiveKTVResourceManager *resourceManager;
@property (retain, nonatomic) NSMutableArray *normalPageModels;
@property (retain, nonatomic) NSMutableDictionary *categoryQueryDict;
@property (retain, nonatomic) IESLiveVideoPlayerController *player;
@property (nonatomic) BOOL isDowning;
@property (retain, nonatomic) IESLiveKTVRecommendItem *currentTryListeningMusicItem;
@property (nonatomic) double startClimaxProgress;
@property (nonatomic) double endClimaxProgress;
@property (copy, nonatomic) NSString *requiredSongInfo;
@property (copy, nonatomic) id /* block */ startMusicCallback;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) id<IESLiveKTVMusicManagerProtocol> ktvMusicManager;
@property (copy, nonatomic) NSString *fastStartTabName;
@property (nonatomic) long long fastStartFirstLevelIndex;
@property (nonatomic) BOOL isSearching;
@property (retain, nonatomic) HTSEventContext *trackContext;
@property (retain, nonatomic) id<IESLiveRoomService> room;
@property (nonatomic) BOOL isOrderPanlShow;
@property (retain, nonatomic) id<IESLiveTracker> tracker;
@property (retain, nonatomic) id<IESLiveKTVFullLinkMonitor> ktvMonitor;
@property (retain, nonatomic) NSMutableDictionary *singListCallBackBlkDict;
@property (copy, nonatomic) id /* block */ showFeedBackBlock;
@property (retain, nonatomic) IESLiveCombineSubject *orderPanelActionSignal;
@property (nonatomic) BOOL isLinked;
@property (nonatomic) BOOL enableRecommendChorusRoom;
@property (nonatomic) BOOL isSoloKTV;

- (void)onStalledEnd:(id)a0;
- (id)initWithRoom:(id)a0 trackContext:(id)a1;
- (void)playerController:(id)a0 updateProgress:(double)a1 duration:(double)a2;
- (void)playerController:(id)a0 playbackStateDidChange:(unsigned long long)a1;
- (void)playerController:(id)a0 playerDidFinishError:(id)a1;
- (id)topSongId;
- (void)fetchKTVCategoryWithRequestMode:(long long)a0 firstLevelTab:(int)a1 completion:(id /* block */)a2;
- (void)fetchKTVMusicListWithRequestMode:(long long)a0 firstLevelTab:(int)a1 category:(id)a2 isLoadMore:(BOOL)a3 topSongId:(id)a4 collectionId:(id)a5 completion:(id /* block */)a6;
- (void)cell:(id)a0 refreshDownloadButtonUIWithMusicModel:(id)a1;
- (void)listView:(id)a0 configurationForCell:(id)a1;
- (void)listView:(id)a0 configurationFooter:(id)a1 forSection:(long long)a2;
- (void)listView:(id)a0 didSelectCell:(id)a1 forIndexPath:(id)a2;
- (void)cell:(id)a0 didFavoriteItem:(id)a1;
- (void)cell:(id)a0 clickedAddSongFor:(id)a1;
- (void)showMusicListFeedbackInHomePanelViewWithSongName:(id)a0 singerName:(id)a1;
- (id)combineMusicListArray:(id)a0 firstLevelTab:(int)a1 category:(id)a2;
- (BOOL)needRefreshWithName:(id)a0;
- (BOOL)needAddAllHeaderWithName:(id)a0;
- (BOOL)needShowCountWithName:(id)a0;
- (BOOL)needReloadDataWithName:(id)a0;
- (void)addSingListCallBackWithViewModel:(id)a0;
- (void)refreshTabSortStatusWithTabArray:(id)a0;
- (void)needLoadBannerData;
- (void)fetchKTVMusicListWithRequestMode:(long long)a0 firstLevelTab:(int)a1 category:(id)a2 completion:(id /* block */)a3;
- (void)trackContainerCellShow;
- (void)trackShowPageWithViewModel:(id)a0;
- (void)trackClickSearchEventWithSearchType:(long long)a0 requestPage:(id)a1;
- (void)trackSearchRequestEventWithContent:(id)a0 contentType:(id)a1 searchType:(long long)a2;
- (void)trackSearchResultEventWithContent:(id)a0 requestPage:(id)a1 contentType:(id)a2 searchType:(long long)a3;
- (void)trackCellShowWithList:(id)a0;
- (void)stopPlayTryListenMusic;
- (id)p_pageModelWithCategory:(id)a0;
- (void)p_downloadMusic:(id)a0 cell:(id)a1 completion:(id /* block */)a2;
- (void)trackMusicSelectUseClickWithSong:(id)a0;
- (void)downloadMusicWithModel:(id)a0 completionBlock:(id /* block */)a1;
- (void)startPlayTryListenMusic;
- (void)trackMusicSelectTrailClickWithSong:(id)a0 isNewSong:(BOOL)a1;
- (void)pauseOrResumePlayTryListenMusic;
- (void)p_logDownloadWithString:(id)a0 musicID:(long long)a1;
- (id)getOrderPanelViewModelWithSize:(struct CGSize { double x0; double x1; })a0;
- (void).cxx_destruct;
- (id)collectionId;

@end
