@class IESLivePublicScreenLayoutManagerForPad, NSMutableDictionary, NSString, IESLivePublicScreenInfoModel;
@protocol IESLiveMessageInteractionModuleUserEnterInterface, IESLiveRevenueInteractModule, IESLiveRoomService, IESLivePublicScreenLayoutCalculator, HTSLivePluginLayoutMachineProvider, HTSLiveStreamPlayerProvider, IESLiveMultiTabService, IESLiveCommunityInteractModuleAdapter, IESLiveInteractionModule;

@interface IESLivePublicScreenLayoutManager : NSObject <IESLiveMessageInteractionModuleCommentAction, IESLivePublicScreenLayoutProvider, HTSLiveStreamPlayerAction, IESLivePublicScreenLayoutChangeProvider, IESLivePublicScreenCollectionViewActions, IESLivePublicScreenLayoutCalculateDataProvider, IESLiveMessageListLayoutService>

@property (retain, nonatomic) IESLivePublicScreenLayoutManagerForPad *padLayoutManeger;
@property (retain, nonatomic) NSMutableDictionary *subscriberDic;
@property (weak, nonatomic) id<IESLiveRoomService> roomService;
@property (weak, nonatomic) id<HTSLiveStreamPlayerProvider> streamPlayerProvider;
@property (weak, nonatomic) id<HTSLivePluginLayoutMachineProvider> layoutMachineProvider;
@property (weak, nonatomic) id<IESLiveMessageInteractionModuleUserEnterInterface> userEnterProvider;
@property (weak, nonatomic) id<IESLiveMultiTabService> multiTabService;
@property (nonatomic) unsigned long long currentScene;
@property (nonatomic) unsigned long long horizontalLayoutType;
@property (nonatomic) BOOL isPad;
@property (nonatomic) BOOL keyboardShow;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } playerFrame;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } viceViewFrame;
@property (nonatomic) double totalKeyboardOffset;
@property (nonatomic) double suitableHeight;
@property (retain, nonatomic) IESLivePublicScreenInfoModel *currentPublicScreenInfoModel;
@property (retain, nonatomic) id<IESLivePublicScreenLayoutCalculator> normalCalculator;
@property (retain, nonatomic) id<IESLivePublicScreenLayoutCalculator> channelCalculator;
@property (retain, nonatomic) id<IESLiveInteractionModule> socialAdapter;
@property (retain, nonatomic) id<IESLiveRevenueInteractModule> revenueAdapter;
@property (retain, nonatomic) id<IESLiveCommunityInteractModuleAdapter> communityInteractAdapter;
@property (nonatomic) double viewErrorWidth;
@property (nonatomic) BOOL isUnmount;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)didSetAttachingDIContext;
- (id)initWithDIContext:(id)a0;
- (double)currentNormalPublicScreenTopContainerHeight;
- (double)messageListHeight;
- (double)messageListWidth;
- (double)roomContainerHeight;
- (BOOL)isUnderMessageListHeightGiftTrayAboveOptimization;
- (BOOL)isHorizontalSmallGiftMoveDownScene;
- (void)willUnmount;
- (void)enablePublicScreenCalculate:(BOOL)a0;
- (double)messageListHeightWithType:(unsigned long long)a0;
- (double)messageListWidthWithType:(unsigned long long)a0;
- (BOOL)isSideStyle;
- (double)sideScreenWidth;
- (BOOL)isTemplateSideStyle;
- (BOOL)isLiveIPadFakeFullScreen;
- (void)updatePublicScreenContainerHeight:(long long)a0 height:(double)a1 publicScreenType:(unsigned long long)a2;
- (void)enablePublicScreenCalculateForType:(unsigned long long)a0 enabled:(BOOL)a1;
- (void)addPublicScreenLayoutSubscriber:(id)a0 forPublicScreenType:(unsigned long long)a1;
- (double)userEnterViewHeight;
- (double)userEnterViewSpacing;
- (void)commentDidStartWithCommentPanelViewFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (BOOL)shouldHasViceView;
- (unsigned long long)currentPublicScreenLayoutScene;
- (void)cancelLayoutSceneIfIsCurrentScene:(unsigned long long)a0;
- (void)updatePublicScreenHeightWithScene:(unsigned long long)a0;
- (void)updatePublicScreenHeight;
- (void)updatePublicScreenHeightWithLevel:(unsigned long long)a0;
- (void)updateTopAvoidHeight:(double)a0 scene:(id)a1;
- (void)updatePublicScreenHeightDynamicallyType:(unsigned long long)a0;
- (void)updatePublicScreenWidth:(double)a0 withSource:(unsigned long long)a1;
- (void)removePublicScreenOutSetWidth;
- (void)updateNormalCalculator:(id)a0;
- (void)playerFrameDidChange:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)playerViceViewFrameDidChange:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)selectedToPublicScreenWithInfoModel:(id)a0;
- (void)selectedPublicScreenFromInfoModel:(id)a0 toInfoModel:(id)a1;
- (BOOL)isSmallGiftViewMoveDownScene;
- (double)caculateHeightForCommon;
- (double)anchorHorisontalUserEnterAvoidHeight;
- (unsigned long long)currentLayoutScene;
- (BOOL)isHorisontal;
- (double)defaultAllAvoidHeight;
- (void)setupCalculatorWithType:(unsigned long long)a0;
- (double)designatedMessageListWidthWithPublicScreenType:(unsigned long long)a0;
- (void)publicScreenLayoutChangedWithCalculator:(id)a0;
- (id)calculatorWithType:(unsigned long long)a0;
- (id)subscribersForPublicScreenType:(unsigned long long)a0;
- (void)sendMessageListHeightChangedAction:(id)a0 forType:(unsigned long long)a1;
- (void)sendPublicScreenLayoutChangedAction:(id)a0 forType:(unsigned long long)a1;
- (void)assignCurrentScene:(unsigned long long)a0;
- (void)monitorPublicScreenViewWidth:(double)a0 withSource:(unsigned long long)a1;
- (BOOL)needChangeHeightWhenKeyBoardShow;
- (void)log_messageListHeightChanged:(double)a0 type:(unsigned long long)a1;
- (id)layoutInfoDictWith:(id)a0;
- (void)log_publicScreenLayoutChanged:(id)a0 reason:(id)a1;
- (id)layoutInfoDictForType:(unsigned long long)a0;
- (double)getConstMessageListHeight;
- (double)messageListHeightForMultiTab;
- (BOOL)isCommonTemplateStyle;
- (BOOL)isGameWithViceView;
- (double)bottomPaddingForCaculate;
- (double)allAvoidHeight;
- (double)smallGiftViewHeight;
- (double)userEnterAvoidHeight;
- (double)smallGiftAvoidHeight;
- (double)messageListMinHeight;
- (double)pkOffset;
- (double)multiLinkOffset;
- (double)equalBigPartyOffset;
- (double)normalAudioOffset;
- (double)multiAudioOffset;
- (double)playerOffset;
- (double)gameStreamPlayerOffset;
- (double)screenTopToBannerBottomConstHeight;
- (double)multiLinkMediaOffset;
- (void)monitorPublicScreenLayoutErrorWithErrorType:(long long)a0 preEvent:(id /* block */)a1;
- (void)p_monitorPublicScreenViewWidthError;
- (void)p_monitorPublicScreenLayoutWithInfoModel:(id)a0;
- (id)log_commonParameters;
- (void)assignHorizontalLayoutType:(unsigned long long)a0;
- (double)smallGiftHeight;
- (double)messageListMaxHeight;
- (double)messageListSuitableHeight;
- (void)messageListHeightChanged:(double)a0 calculator:(id)a1;
- (void)monitorPublicScreenLayoutWithInfoModel:(id)a0;
- (double)toolBarContainerBottomOffset;
- (void)keyboardWillHide;
- (double)bottomPadding;
- (void).cxx_destruct;
- (double)topOffset;
- (BOOL)isAnchor;
- (void)dealloc;

@end
