@class NSString;

@interface IESLiveRecoderImp_multiDevice : NSObject <IESLiveRecoder>

@property (readonly, nonatomic) long long status;
@property (readonly, nonatomic) long long currentCameraPosition;
@property (nonatomic) long long cameraFlashMode;
@property (nonatomic) BOOL ignoreNotification;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } outputSize;
@property (readonly, nonatomic) NSString *currentSessionPreset;
@property (readonly, nonatomic) unsigned long long preferedFrameRate;
@property (readonly, nonatomic) NSString *deviceType;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)didSetAttachingDIContext;
- (BOOL)captureIsRunning;
- (void)runDirtyCameraDetectAlgorithmWithCompletion:(id /* block */)a0;
- (void)resetDirtyCameraDetectCount:(int)a0 back:(int)a1;
- (void)turnLensCombinedEnhanceAlgorithm:(BOOL)a0;
- (void)tapFocusAtPoint:(struct CGPoint { double x0; double x1; })a0;
- (void)resetFocusMode:(long long)a0 point:(struct CGPoint { double x0; double x1; })a1;
- (void)tapExposureAtPoint:(struct CGPoint { double x0; double x1; })a0;
- (void)setVideoProcessedBufferCallback:(id /* block */)a0;
- (id)supportedBaseFocalLengthArray;
- (void)setPureModeReturnWithLens:(BOOL)a0;
- (BOOL)isCameraCapabilitySupportedZoom;
- (void)startVideoCaptureWithPrivacyCert:(id)a0 source:(long long)a1 completion:(id /* block */)a2;
- (void)stopVideoCaptureWithPrivacyCert:(id)a0 source:(long long)a1;
- (void)stopAudioCaptureWithPrivacyCert:(id)a0 source:(long long)a1;
- (BOOL)cameraSetZoomFactor:(double)a0 source:(long long)a1;
- (void)switchCameraSourceWithTrigger:(long long)a0;
- (void)enableFrontCameraMirrored:(BOOL)a0 source:(long long)a1;
- (void)setTorchOn:(BOOL)a0 source:(long long)a1;
- (void)setPureCameraMode:(BOOL)a0 source:(long long)a1;
- (id)resetPreviewView:(id)a0 source:(long long)a1;
- (void)resetContextWithSource:(long long)a0;
- (void)setCameraParamWithConfig:(struct { struct CGSize { double x0; double x1; } x0; unsigned long long x1; })a0 source:(long long)a1;
- (struct { struct CGSize { double x0; double x1; } x0; unsigned long long x1; })getCameraParamConfig;
- (void)resetPreferredFrameRate:(unsigned long long)a0 source:(long long)a1;
- (void)resetOutputSize:(struct CGSize { double x0; double x1; })a0 source:(long long)a1;
- (void)setVideoBufferCallbackWithSource:(long long)a0 callback:(id /* block */)a1;
- (void)resetCapturePreset:(id)a0 source:(long long)a1 then:(id /* block */)a2;
- (void)setFishEyeRecoderConfigWithPreset:(id)a0 outputSize:(struct CGSize { double x0; double x1; })a1 source:(long long)a2;
- (void)setNormalLiveRecoderConfigWithPreset:(id)a0 outputSize:(struct CGSize { double x0; double x1; })a1 source:(long long)a2;
- (void)setCustomRecoderPreset:(id)a0 outputSize:(struct CGSize { double x0; double x1; })a1 source:(long long)a2;
- (void)setPreferredBackZoomFactor:(double)a0 source:(long long)a1;
- (void)configCameraWithSource:(long long)a0 configuration:(id)a1 completion:(id /* block */)a2;
- (void)cameraIsolateConfigWithCert:(id)a0 configuration:(id)a1 cameraComplete:(id /* block */)a2;
- (BOOL)checkConfig:(id)a0 source:(long long)a1;
- (void)setRecorderConfig:(id)a0 source:(long long)a1 cameraComplete:(id /* block */)a2;
- (BOOL)cameraTorchOn;
- (void)setExposureByFaceDetectOn:(BOOL)a0 source:(long long)a1;
- (void)setStablizationMode:(long long)a0 source:(long long)a1;
- (void)isCameraCapabilitySupportedAsync:(unsigned long long)a0 completion:(id /* block */)a1;
- (void)setMaxZoomFactor:(double)a0 Source:(long long)a1;
- (BOOL)cameraRampToZoomFactor:(double)a0 withRate:(double)a1 Source:(long long)a2;
- (void)clearCameraMemoryResource:(long long)a0;
- (void)dealFuncUnIMP;
- (id)cameraConfigForNormalOpenLive;
- (id)generateNewConfigWithOldConfig:(id)a0 configuration:(id)a1;
- (void)setRecorderConfig:(id)a0 source:(long long)a1 extra:(id)a2 cameraComplete:(id /* block */)a3;
- (void)addRecoderMonitorWithEvent:(id)a0 source:(id)a1 extra:(id)a2;
- (void)startVideoCaptureCompletion:(id /* block */)a0;
- (double)minExposureBias;
- (double)maxExposureBias;
- (void)changeExposureBias:(double)a0;
- (double)currentCameraZoomFactor;
- (long long)currentStabilizationMode;
- (double)maxCameraZoomFactor;
- (id)init;
- (void)startAudioCapture;
- (id)methodSignatureForSelector:(SEL)a0;
- (double)exposureBias;
- (void)stopAudioCapture;
- (void)forwardInvocation:(id)a0;
- (void)stopVideoCapture;
- (void)startAudioCaptureWithPrivacyCert:(id)a0 source:(long long)a1;

@end
