@class HTSEventForwardingView, NSDictionary, IESLiveBeautyHandlerWrapper, IESLiveBeautyTrackImp, UIView, HTSLiveApi, HTSLiveFeedbackCard, NSString, NSTimer, IESLiveGuideToolBarItem, IESLivePopupItem, NSArray, IESLiveBeautyCrowdTestModeSelectedView, IESLiveBeautyCrowdTestModeSwitchPanelView;
@protocol IESHYContainerProtocol;

@interface IESLiveGuideFaceBeautyFragment : IESLiveGuideComponent <IESLiveGuideOpenLiveAdditionalEvent, IESLiveVRSwitchRouter, IESLiveGuideActions, IESLiveBeautyHandlerDelegate, IESHYHybridViewLifecycleProtocol, IESLiveFeedbackAction, IESLiveGuideBeautyRouter, IESLiveBeautyCrowdTestPanelDelegate>

@property (retain, nonatomic) IESLiveGuideToolBarItem *beautyToolbarItem;
@property (retain, nonatomic) IESLiveBeautyHandlerWrapper *handlerWrapper;
@property (nonatomic) BOOL isVRLiveMode;
@property (retain, nonatomic) HTSEventForwardingView *fullscreenContainer;
@property (retain, nonatomic) IESLiveBeautyTrackImp *beautyTracker;
@property (nonatomic) BOOL hasCameraSet;
@property (retain, nonatomic) NSArray *normalHandlerArray;
@property (retain, nonatomic) NSArray *vrHandlerArray;
@property (nonatomic) long long appearanceLoadDuration;
@property (nonatomic) long long bodyLoadDuration;
@property (nonatomic) long long makeupLoadDuration;
@property (nonatomic) long long filterLoadDuration;
@property (nonatomic) BOOL alreadyRequested;
@property (retain, nonatomic) HTSLiveApi *api;
@property (retain, nonatomic) UIView<IESHYContainerProtocol> *hybridContainer;
@property (retain, nonatomic) HTSLiveFeedbackCard *feedbackCardData;
@property (retain, nonatomic) NSDictionary *feedbackData;
@property (nonatomic) BOOL alreadyShowed;
@property (retain, nonatomic) NSTimer *questionnaireShowTimer;
@property (nonatomic) double timestampShowBeautyPanel;
@property (nonatomic) BOOL beautyFeedbackEnable;
@property (nonatomic) double showConditionDuration;
@property (nonatomic) double hideConditionDuration;
@property (retain, nonatomic) NSString *feedbackURL;
@property (retain, nonatomic) NSArray *crowdTestModeArray;
@property (retain, nonatomic) NSString *lastCrowdTestModeEndToast;
@property (retain, nonatomic) IESLiveBeautyCrowdTestModeSelectedView *crowdTestModeSelectedView;
@property (retain, nonatomic) IESLiveBeautyCrowdTestModeSwitchPanelView *crowdTestModeSwitchView;
@property (nonatomic) unsigned long long currentSelectModeIndex;
@property (retain, nonatomic) IESLivePopupItem *currentBeautyPanelPopupItem;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)componentShouldActive:(id)a0;

- (void)componentBindService;
- (void)componentCreate;
- (void)componentMount;
- (void)componentUnmount;
- (void)showBeautyPanel;
- (void)onFeedbackStateChange:(long long)a0;
- (void)liveTypeDidChange:(unsigned long long)a0;
- (void)cameraDidSet;
- (void)appendCreateAnchorBusinessParams:(id)a0 completion:(id /* block */)a1;
- (void)loadHybridContainer;
- (void)switchVRLiveMode:(BOOL)a0;
- (id)changeAppearenceSwitch:(BOOL)a0;
- (id)changeBodySwitch:(BOOL)a0;
- (void)openBeautyPanel;
- (void)setupBeautyToolBarItem;
- (BOOL)isEffectEnvironmentReady;
- (id)specifiedAbGroupForPanel:(id)a0;
- (void)onBeautyEffectRenderFromFetch:(long long)a0 stage:(id)a1 time:(double)a2;
- (void)didSelectedModeIndex:(unsigned long long)a0;
- (BOOL)shouldShowBeautyBubble;
- (void)handleBottomPanelDisplay:(BOOL)a0;
- (void)setupWrapperIfNeed;
- (void)processECommodityNoFiler;
- (BOOL)isCrowdTest;
- (void)setupCrowdTest;
- (void)hideNoFilterBubble;
- (void)showCrowdTestSelectedViewWithContainerView:(id)a0;
- (void)beautyFeedbackRequestAndShow;
- (void)interruptCountDown;
- (void)removeCrowdTestSelectedView;
- (void)InitOnCameraDidSet;
- (void)dispatchEffectEnvironmentReady;
- (void)showNoFilterBubbleIfNeeded;
- (BOOL)shouldShowNoFilterBubble;
- (void)trackNoFilterBubbleShow;
- (void)p_requestFeedbackData;
- (void)showBeautyQuestionnaire;
- (void)changeCrowdTestSelectedViewHiddenState:(BOOL)a0;
- (void)removeBeautyQuestionnaire;
- (void)trackBeautyTypeLoadTime:(id)a0 duration:(long long)a1;
- (void)trackBeautyLoadTimeIfNeed;
- (void)setupCrowdTestModeArrayWith:(id)a0;
- (BOOL)checkLastModeIsDeleted:(id)a0;
- (void)showCrowdTestModeSwitchPanel;
- (void)hideCrowdTestModeSwitchPanel;
- (void).cxx_destruct;

@end
