@class NSString, NSMutableDictionary, NSDictionary, NSMutableArray;
@protocol IESMMEffectHelperProtocol, IESMMTrackerHelperProtocol;

@interface IESMMTrackerManager : IESMMObject

@property (nonatomic) double cameraStartTime;
@property (nonatomic) long long device_cameraWillStartTime;
@property (nonatomic) long long device_cameraWillStopTime;
@property (nonatomic) long long device_micWillStartTime;
@property (nonatomic) long long device_micWillStopTime;
@property (nonatomic) long long device_flashModeWillChangeTime;
@property (nonatomic) double previewFpsStartTime;
@property (nonatomic) double previewFpsStopTime;
@property (nonatomic) long long previewFrameCount;
@property (nonatomic) BOOL previewHaveStart;
@property (nonatomic) long long generateFrameCount;
@property (nonatomic) double recordFpsStartTime;
@property (nonatomic) double recordFpsStopTime;
@property (nonatomic) long long recordFrameCount;
@property (nonatomic) BOOL recordHaveStart;
@property (nonatomic) float processStartTime;
@property (nonatomic) float processStopTime;
@property (nonatomic) float processTotalTime;
@property (nonatomic) long long processFrameCount;
@property (nonatomic) BOOL processHasStart;
@property (nonatomic) struct IESMMRecorderCostStat { double avgRecorderProcessCost; double avgEffectProcessCost; double avgRecorderRenderScreenCost; double avgNextFrameArrivedInterval; double avgExposureTime; } recorderCostStat;
@property (nonatomic) double lastPointEndTime;
@property (nonatomic) unsigned long long recorderFrameCount;
@property (nonatomic) float initStartTimeValue;
@property (nonatomic) float initStopTimeValue;
@property (nonatomic) BOOL haveInit;
@property (nonatomic) float compositeStartSystemTime;
@property (nonatomic) float compositeSystemStopTime;
@property (nonatomic) BOOL haveStartCompositeTime;
@property (nonatomic) float compositePauseStartSystemTime;
@property (nonatomic) float compositePauseTotalTime;
@property (nonatomic) float importGenerateThumbnailStartSystemTime;
@property (nonatomic) float importGenerateThumbnailStopSystemTime;
@property (nonatomic) BOOL haveStartGenerateThumbnail;
@property (nonatomic) float importCropFileStartSystemTime;
@property (nonatomic) float importCropFileStopSystemTime;
@property (nonatomic) BOOL haveStartImportCropFile;
@property (nonatomic) double playerStartTime;
@property (retain, nonatomic) NSMutableDictionary *contextDic;
@property (retain, nonatomic) NSMutableDictionary *importVideoDic;
@property (retain, nonatomic) NSMutableDictionary *recordVideoDic;
@property (retain, nonatomic) NSMutableDictionary *preViewDic;
@property (retain, nonatomic) NSMutableDictionary *previewDict2;
@property (retain, nonatomic) NSMutableDictionary *recordVideoDic2;
@property (retain, nonatomic) NSMutableDictionary *editPlayerDict;
@property (retain, nonatomic) NSMutableDictionary *compostionDic;
@property (retain, nonatomic) NSMutableDictionary *compositionDic2;
@property (retain, nonatomic) NSMutableDictionary *pre_record_compostionDic;
@property (retain, nonatomic) NSMutableDictionary *cameraDic;
@property (nonatomic) BOOL useHMD;
@property (retain, nonatomic) NSString *bundleName;
@property (nonatomic) double recordFPS;
@property (nonatomic) double previewFPS;
@property (nonatomic) double recordFirstFrameTime;
@property (nonatomic) double previewFirstFrameTime;
@property (retain, nonatomic) NSDictionary *defaultPar;
@property (retain, nonatomic) id<IESMMEffectHelperProtocol> effectHelper;
@property (retain, nonatomic) id<IESMMTrackerHelperProtocol> trackerHelper;
@property (nonatomic) long long recordLagCount;
@property (nonatomic) long long recordLagMaxDuration;
@property (nonatomic) long long recordTotalLagDuration;
@property (nonatomic) BOOL isRecording;
@property (nonatomic) struct { long long value; int timescale; unsigned int flags; long long epoch; } lastRecordFrameTime;
@property (nonatomic) BOOL isRecordFirstFrame;
@property (nonatomic) long long recordSlightLagCount;
@property (nonatomic) long long recordNormalLagCount;
@property (nonatomic) long long recordSeriousLagCount;
@property (nonatomic) long long previewLagCount;
@property (nonatomic) long long previewSeriousLagCount;
@property (nonatomic) long long previewLagMaxDuration;
@property (nonatomic) long long previewTotalLagDuration;
@property (nonatomic) long long lastPreviewFrameTime;
@property (nonatomic) long long previewLagFrameCount;
@property (nonatomic) long long recordRenderFrameCount;
@property (nonatomic) long long last30PreviewRenderFrameTime;
@property (nonatomic) long long last30RecordRenderFrameTime;
@property (nonatomic) double last30PreviewRenderFPS;
@property (nonatomic) double last30RecordRenderFPS;
@property (nonatomic) long long previewStartTime;
@property (retain, nonatomic) NSMutableArray *previewAvgExposureDurationArray;
@property (nonatomic) double previewTotalNFrameInterval;
@property (nonatomic) double previewFirstTwoFrameInterval;
@property (nonatomic) double recordTotalNFrameInterval;
@property (nonatomic) double recordFirstTwoFrameInterval;
@property (nonatomic) long long recordPreviewFrameCount;
@property (nonatomic) float multiCamPreviewFpsStartTime;
@property (nonatomic) float multiCamPreviewFpsStopTime;
@property (nonatomic) long long multiCamFirstPreviewFrameCount;
@property (nonatomic) long long multiCamSecondPreviewFrameCount;
@property (nonatomic) BOOL multiCamPreviewHaveStarted;
@property (nonatomic) long long multiCamFirstPreviewDropFrameCount;
@property (nonatomic) long long multiCamSecondPreviewDropFrameCount;
@property (nonatomic) double multiCamFirstPreviewFPS;
@property (nonatomic) double multiCamSecondPreviewFPS;
@property (nonatomic) long long applyStickerLagCount;
@property (nonatomic) long long applyStickerLagTotalDuration;
@property (nonatomic) BOOL startApplySticker;
@property (nonatomic) float cameraFpsConfig;
@property (nonatomic) long long frameCount;
@property (nonatomic) long long lagCount;
@property (nonatomic) long long seriousLagCount;
@property (nonatomic) long long totalLagDuration;
@property (nonatomic) long long maxLagDuration;
@property (nonatomic) struct { long long value; int timescale; unsigned int flags; long long epoch; } firstFrameTime;
@property (nonatomic) struct { long long value; int timescale; unsigned int flags; long long epoch; } lastFrameTime;
@property (nonatomic) BOOL isCalLagFirstFrame;
@property (nonatomic) double editorStartTime;
@property (nonatomic) double editorStopTime;
@property (nonatomic) double editorPlayFPS;
@property (nonatomic) long long editorFrameCount;
@property (nonatomic) BOOL editorPlaying;
@property (nonatomic) double editorTotalNFrameInterval;
@property (nonatomic) double editorMaxFrameInterval;
@property (nonatomic) long long editorLagCount;
@property (nonatomic) long long editorSeriousLagCount;
@property (nonatomic) long long editorLagDuration;
@property (nonatomic) double lastEditorPreviewTime;
@property (nonatomic) double editorPreviewStartTime;
@property (nonatomic) long long editorPreviewFrameCount;
@property (nonatomic) double editorPreviewLogStartTime;
@property (copy, nonatomic) NSMutableDictionary *eventParams;
@property (retain, nonatomic) NSMutableDictionary *switchEffectTimeStamp;
@property (copy, nonatomic) id /* block */ IESMMTrackerBlock;
@property (copy, nonatomic) id /* block */ appLogTrackerBlock;
@property (copy, nonatomic) id /* block */ performanceTrackerBlock;
@property (copy, nonatomic) NSString *appId;
@property (nonatomic) float recordStartTime;
@property (nonatomic) float recordStopTime;
@property (nonatomic) long long firstNFrame;
@property (nonatomic) long long recordCount;
@property (copy, nonatomic) NSString *reportVid;
@property (nonatomic) long long mergeStatus;
@property (nonatomic) long long vtEncodeStatus;
@property (nonatomic) double firstRenderTime;
@property (nonatomic) double updateVideoTime;
@property (nonatomic) double firstDecodeTime;
@property (nonatomic) double initEditorTime;
@property (nonatomic) long long editorMode;
@property (nonatomic) double micXRunStartTime;
@property (nonatomic) double micXRunCurrentTime;
@property (nonatomic) long long micXRunCount;
@property (nonatomic) float micBufferDuration;
@property (nonatomic) float micChannelCount;
@property (nonatomic) float micSampleRate;
@property (nonatomic) double musicXRunStartTime;
@property (nonatomic) double musicXRunCurrentTime;
@property (nonatomic) long long musicXRunCount;
@property (nonatomic) float musicBufferDuration;
@property (nonatomic) float musicChannelCount;
@property (nonatomic) float musicSampleRate;

+ (void)configureMMTracker:(id)a0;
+ (id)effectSDKCommit;
+ (id)getEffectVersion;
+ (id)getEditorVersion;
+ (id)shareInstance;

- (void)localConfigureMMTracker:(id)a0;
- (void)postTracker:(id)a0 value:(id)a1 status:(long long)a2;
- (void)postServiceType:(long long)a0 key:(id)a1 value:(id)a2;
- (void)trackDeviceStateOnEvent:(id)a0 state:(int)a1;
- (void)postTracker:(id)a0 value:(id)a1;
- (void)setEffectHelperIntance:(id)a0;
- (void)resetRecorderCostStat;
- (void)recordPlayerFirstRender;
- (void)clearComposTracker;
- (void)trackRecordVideo;
- (void)trackImpportCropVideo;
- (void)trackPreViewDic;
- (void)trackCompostionDic;
- (void)postRecordFinishTracker;
- (void)postPreAndRecordAndCompostionTracker;
- (void)postComposFinishTracker;
- (void)iesAppLogOnEvent:(id)a0 params:(id)a1 eventType:(id)a2;
- (void)appLogOnEvent2IES:(id)a0 params:(id)a1 eventType:(id)a2;
- (void)iesAppLogOnEvent:(id)a0 params:(id)a1 eventType:(id)a2 toBusiness:(BOOL)a3;
- (void)appLogOnEvent2IES:(id)a0 params:(id)a1 eventType:(id)a2 toBusiness:(BOOL)a3;
- (void)updateRecordLagCount;
- (void)updateRecordLagTotalDuration:(long long)a0;
- (void)updateRecordSlightLagCount;
- (void)updateRecordNormalLagCount;
- (void)updateRecordSeriousLagCount;
- (long long)getRecordLagMaxDuration;
- (void)updateRecordLagMaxDuration:(long long)a0;
- (long long)getPreviewDuration;
- (void)resetEditorParameters;
- (float)getPlayFps;
- (float)getEditorPreviewCurFrameRate;
- (void)appLogOnEvent:(id)a0 params:(id)a1 eventType:(id)a2 toBusiness:(BOOL)a3;
- (void)appLogReportBussiness:(id)a0 params:(id)a1 eventType:(id)a2;
- (id)getRuntimeMemoryInfo;
- (void)postDelegateTracker:(id)a0 value:(id)a1;
- (void)previewResolution:(float)a0 height:(float)a1;
- (void)multiCamPreviewFpsReset;
- (void)multiCamFirstPreviewFrameArrive;
- (void)multiCamSecondPreviewFrameArrive;
- (void)multiCamFirstPreviewFrameDropped;
- (void)multiCamSecondPreviewFrameDropped;
- (void)multiCamPreviewFpsStop;
- (double)getMultiCamFirstPreviewFPS;
- (double)getMultiCamSecondPreviewFPS;
- (long long)getMultiCamFirstPreviewLagCount;
- (double)getMultiCamFirstPreviewFrameCount;
- (long long)getMultiCamSecondPreviewLagCount;
- (void)previewFpsStart;
- (void)previewFrameArrive;
- (void)previewFpsdStop;
- (void)frameGenerate;
- (void)recordFpsStart;
- (void)recordFrameArrive;
- (void)recordFpsdStop;
- (void)processFrameStartTime;
- (void)processFrameArrive;
- (void)processFrameStopTime;
- (void)clearPreviewExposureDuration;
- (long long)getAvgPreviewExposureDuration;
- (void)addExposureDurationForAvgPreview:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (void)receiveCaptureFrame;
- (void)beforeEffectProcess;
- (void)afterEffectProcess;
- (void)updateExposureTime:(double)a0;
- (struct IESMMRecorderCostStat { double x0; double x1; double x2; double x3; double x4; })getRecorderCostStat;
- (void)startInit;
- (void)firstFrameRender;
- (void)recordPlayerStart;
- (void)recordEditReverseTime:(double)a0 duration:(double)a1 useCache:(BOOL)a2;
- (void)recordEditReverseError:(id)a0;
- (void)recordEditAllocNum;
- (void)recordEditErrorCode:(int)a0;
- (void)recordComposEndWaterMark:(BOOL)a0;
- (void)recordComposEffect:(id)a0;
- (void)recordComposInfoSticker:(id)a0;
- (void)compositeFile:(id)a0;
- (void)compositeStartTime;
- (void)compositeStopTime;
- (void)compositePauseStartTime;
- (void)compositePauseStopTime;
- (double)getCompositePauseTotalTime;
- (void)postTracker;
- (void)postPreViewTracker;
- (void)postRecordTracker;
- (void)clearRecordTracker;
- (void)postCompostionTracker;
- (void)postTracker:(long long)a0;
- (double)getRecordFPS;
- (double)getPreviewFPS;
- (double)getRecordFirstFrameTime;
- (double)getPreviewFirstFrameTime;
- (void)addParams:(id)a0 forEvent:(id)a1;
- (void)setAppLogCallback:(id)a0 callback:(id /* block */)a1;
- (void)performanceOnEvent:(id)a0 params:(id)a1;
- (void)setPerformanceCallback:(id /* block */)a0;
- (double)getSlightLagRate;
- (double)getNormalLagRate;
- (double)getSeriousLageRate;
- (long long)getRecordLagCount;
- (long long)getRecordLagTotalDuration;
- (void)resetRecordLagParams;
- (void)calRecordLag:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (void)updatePreviewLagCount:(long long)a0;
- (void)updatePreviewLagMaxDuration:(long long)a0;
- (void)updatePreviewLagTotalDuration:(long long)a0;
- (long long)getPreviewLagCount;
- (long long)getPreviewSeriousLagCount;
- (long long)getPreviewLagMaxDuration;
- (long long)getPreviewLagTotalDuration;
- (void)calPreviewLag:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0 firstFrame:(BOOL)a1;
- (void)resetPreviewLagParams;
- (double)getPreviewFirstTwoFrameInterval;
- (double)getPreviewFirstNFrameAvgInterval;
- (double)getRecordFirstTwoFrameInterval;
- (double)getRecordFirstNFrameAvgInterval;
- (double)getPreviewPureFps;
- (long long)getPreviewLagFrameCount;
- (double)getLast30PreviewRenderFPS;
- (double)getLast30RecordRenderFPS;
- (long long)getApplyStickerLagCount;
- (long long)getApplyStickerLagTotalDuration;
- (void)startApplyStickerLag;
- (void)endApplyStickerLag;
- (void)updateCameraFpsConfig:(float)a0;
- (void)resetPreviewLagStatistics;
- (void)calRenderLag:(struct { long long x0; int x1; unsigned int x2; long long x3; })a0;
- (void)postPreviewLagTracker:(BOOL)a0;
- (void)updatePlayStartTime:(double)a0;
- (double)getPlayStartTime;
- (void)updatePlayStopTime:(double)a0;
- (double)getPlayStopTime;
- (void)updateEditorFrameCount;
- (void)resetEditorFrameCount;
- (void)updatePlayFps:(float)a0;
- (void)editorPreviewFrameArrive;
- (long long)getEditorLagCount;
- (long long)getEditorSeriousLagCount;
- (long long)getEditorLagDuration;
- (float)getEditorPreviewFrameRate;
- (double)getEditorMaxFrameInterval;
- (double)getEditorFirstNFrameAvgInterval;
- (void)reportEditorFirstFrameTime:(double)a0 mode:(long long)a1;
- (void)reportEditorPreloadTime:(double)a0 readerType:(long long)a1;
- (void)trackFlashStateOnEvent:(id)a0 state:(int)a1;
- (void)trackCameraInterruptionOnEvent:(id)a0 isRuning:(BOOL)a1;
- (void)trackCameraInfo:(id)a0 forEvent:(id)a1;
- (void)trackFaceAEModeOnEvent:(id)a0 device:(id)a1 sysVer:(id)a2 faceAE:(BOOL)a3 sysAutoFaceAE:(BOOL)a4;
- (void)micXRunArrive:(BOOL)a0;
- (void)clearMicXRun;
- (void)musicXRunArrive:(BOOL)a0;
- (void)clearMusicXRun;
- (id)getSwitchEffectTimeStamp;
- (void)setClientCallVESwitchEffectTimeStamp:(id)a0 timestamp:(unsigned long long)a1;
- (void)setVECallSwitchEffectTimeStamp:(id)a0 timestamp:(unsigned long long)a1;
- (void)appLogOnEvent:(id)a0 params:(id)a1 eventType:(id)a2;
- (void).cxx_destruct;
- (id)init;
- (void)setRecordingState:(BOOL)a0;
- (void)initData;

@end
