@class NSMutableDictionary, LiveStreamSingScore, LiveStreamCapture, LSLiveAudioUnitProcess, NSObject, NSDictionary, LSLiveAudioLoudness, LiveStreamMultiTimerManager, LiveCoreCamera, LiveCoreRunInfo, UIView, LiveStreamRenderSink, NSString, LiveStreamAudioCapture, AVAudioFile, AVAudioPlayer, NSNumber, LiveStreamSession, NSLock;
@protocol ILCRTCAudioSinkProtocol, ILiveCoreForInteractDelegate, LiveCoreCaptureDelegate, OS_dispatch_source, OS_dispatch_queue, ILCRTCVideoSinkProtocol;

@interface LiveCore : NSObject <LiveStreamSessionProtocol> {
    struct __CVBuffer { } *_darkFrameImageBuffer;
    LiveStreamMultiTimerManager *_pushDarkFrameTimer;
    BOOL _remoteSessionNeedRender;
    BOOL _needResetPerformanceProfile;
    short *_musicData;
    short *_originMusicData;
    struct mutex { struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } __m_; } _sei_mutex;
    unsigned long long _music_type;
    struct mutex { struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } __m_; } _user_layout_mutex;
    struct unique_ptr<avframework::VideoInfoStatisticManager, std::default_delete<avframework::VideoInfoStatisticManager>> { struct __compressed_pair<avframework::VideoInfoStatisticManager *, std::default_delete<avframework::VideoInfoStatisticManager>> { struct VideoInfoStatisticManager *__value_; } __ptr_; } statisticManager;
    LSLiveAudioLoudness *_audioLoudness;
    struct LSAudioBGMProcessor { void /* function */ **x0; long long x1; BOOL x2; id x3; id x4; unsigned long long x5; id x6; id x7; struct mutex { struct _opaque_pthread_mutex_t { long long x0; char x1[56]; } x0; } x8; BOOL x9; } *_audioBGMProcessor;
}

@property (class, nonatomic) BOOL interactDecouple;

@property (copy, nonatomic) id /* block */ lyricInfoDidReceiveCallback;
@property (nonatomic, getter=isReverberationEnabled) BOOL reverberationEnabled;
@property (copy, nonatomic) id /* block */ playAudioFrameCallback;
@property (retain, nonatomic) UIView *previewView;
@property (retain, nonatomic) LiveCoreCamera *camera;
@property (nonatomic) long long captureMode;
@property (copy, nonatomic) id /* block */ videoProcessingCallback;
@property (copy, nonatomic) id /* block */ didCapturedVideoFrame;
@property (weak, nonatomic) id<LiveCoreCaptureDelegate> captureDelegate;
@property (retain, nonatomic) LiveStreamSession *liveSession;
@property (retain, nonatomic) LiveStreamRenderSink *effectRenderSink;
@property (retain, nonatomic) LiveStreamRenderSink *aecRenderSink;
@property (retain, nonatomic) LiveStreamRenderSink *gameRenderSink;
@property (retain, nonatomic) NSMutableDictionary *user_layer_map;
@property (retain, nonatomic) NSLock *userLayerMap_lock;
@property (nonatomic) long long runState;
@property (nonatomic) long long captureMode;
@property (nonatomic) NSString *mode;
@property (nonatomic) NSString *category;
@property (nonatomic) unsigned long long options;
@property (retain, nonatomic) NSObject<OS_dispatch_source> *logTimer;
@property (nonatomic) long long firstVideoPts;
@property (nonatomic) long long lastVideoPts;
@property (nonatomic) BOOL mixOnClient;
@property (nonatomic) BOOL audioDidCapturedData;
@property (nonatomic) BOOL audioMute;
@property (nonatomic) BOOL enableExternalClientMix;
@property (retain, nonatomic) LiveStreamCapture *capture;
@property (nonatomic) int deviceLevel;
@property (retain, nonatomic) UIView *previewView;
@property (copy, nonatomic) NSString *effectLicense;
@property (nonatomic) BOOL externalPushDark;
@property (nonatomic) BOOL releaseAudioCaptureInCleanUp;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *timer_quque;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *filePlayQueue;
@property (retain, nonatomic) LiveStreamMultiTimerManager *timerManager;
@property (retain, nonatomic) NSMutableDictionary *propertyDict;
@property (nonatomic) BOOL audioMuteExceptBgm;
@property (nonatomic) BOOL muteLocalAudioStream;
@property (nonatomic) BOOL needCloseAEC;
@property (nonatomic) BOOL audioCaptureEnterBackGround;
@property (nonatomic) BOOL bMovieMode;
@property (nonatomic) BOOL didKTVCameraSetPipeline;
@property (nonatomic) BOOL useMVMode;
@property (nonatomic) BOOL useSingleDirChorusMode;
@property (nonatomic) BOOL forceCompositingLayout;
@property (retain, nonatomic) LiveStreamAudioCapture *audioCapture;
@property (retain, nonatomic) LiveCoreRunInfo *runInfo;
@property (retain, nonatomic) LiveStreamRenderSink *ktvRenderSink;
@property (retain, nonatomic) LiveStreamRenderSink *mvRenderSink;
@property (retain, nonatomic) LiveStreamRenderSink *karaokeRenderSink;
@property (retain, nonatomic) LiveStreamRenderSink *commonRenderSink;
@property (retain, nonatomic) LiveStreamRenderSink *chorusRenderSink;
@property (retain, nonatomic) LiveStreamRenderSink *audioFileRenderSink;
@property (retain, nonatomic) LiveStreamSingScore *singScore;
@property (weak, nonatomic) id<ILCRTCVideoSinkProtocol> rtcVideoSink;
@property (weak, nonatomic) id<ILCRTCAudioSinkProtocol> rtcAudioSink;
@property (weak, nonatomic) id<ILCRTCVideoSinkProtocol> rtcGameVideoSink;
@property (weak, nonatomic) id<ILCRTCAudioSinkProtocol> rtcGameAudioSink;
@property (weak, nonatomic) id<ILiveCoreForInteractDelegate> liveCoreForInteractDelegate;
@property (copy, nonatomic) NSString *interactCurrentUser;
@property (nonatomic) BOOL enableSkipMemsetMonitoringDataIfBgmPaused;
@property (nonatomic) BOOL didStartLogTimer;
@property (retain, nonatomic) LSLiveAudioUnitProcess *audioFileaudioUnit;
@property (retain, nonatomic) AVAudioPlayer *audioFilePlayer;
@property (retain, nonatomic) AVAudioFile *audioFileHandler;
@property (retain, nonatomic) LiveCoreCamera *camera;
@property (copy, nonatomic) id /* block */ didCapturedVideoFrame;
@property (copy, nonatomic) id /* block */ videoProcessingCallback;
@property (copy, nonatomic) id /* block */ interactVideoFrameCallback;
@property (nonatomic) BOOL didReceivedFirstRemoteAudio;
@property (nonatomic) long long pipelineMode;
@property (nonatomic) BOOL sendVideoToInteract;
@property (nonatomic) BOOL sendVideoToRTCGame;
@property (nonatomic) long long audioPlayerMode;
@property (nonatomic) long long busiScene;
@property (copy, nonatomic) id /* block */ shouldUpdateInteractLayout;
@property (copy, nonatomic) id /* block */ didOfflineCallback;
@property (nonatomic) BOOL needOpenAEC;
@property (nonatomic) BOOL enableSeiCurrentShiftDiffTime;
@property (nonatomic) long long seiCurrentShiftDiffTime;
@property (copy, nonatomic) id /* block */ audioFilePlayStoped;
@property (nonatomic) BOOL audioplayPlayIsCompleted;
@property (retain, nonatomic) NSLock *pushDarkLock;
@property (retain, nonatomic) NSLock *ktvAudioUnitLock;
@property (nonatomic) int dagnosisSwitchFreq;
@property (nonatomic) BOOL isEnableKtvAccurateProgress;
@property (nonatomic) BOOL enableKtvAccurateProgressFromVpaas;
@property (nonatomic) BOOL isEnablePulseGenerator;
@property (nonatomic) BOOL enablePulseGeneratorFromVpaas;
@property (nonatomic) int pulseGeneratorIndex;
@property (nonatomic) long long lastBGMPostion;
@property (nonatomic) BOOL isEnableAudioScoreWhenLocalPlay;
@property (nonatomic) double pullAudioCostTime;
@property (nonatomic) double pushAudioCostTime;
@property (nonatomic) double mixCostTime;
@property (copy, nonatomic) id /* block */ getAudioCallback;
@property (copy, nonatomic) id /* block */ getGameAudioCallback;
@property (copy, nonatomic) id /* block */ statusChangedBlock;
@property (copy, nonatomic) id /* block */ didCapturedAudioFrame;
@property (copy, nonatomic) id /* block */ didCapturedAudioFrameWithSampleRate;
@property (copy, nonatomic) id /* block */ didRecordAudioFrame;
@property (copy, nonatomic) id /* block */ pushStreamVideoFrameRateChangedBlock;
@property (nonatomic) long long reconnectCount;
@property (nonatomic) BOOL gotAppUploader;
@property (nonatomic) Class appLogClass;
@property (nonatomic) SEL appLogUploadMethod;
@property (nonatomic) unsigned long long logLevel;
@property (nonatomic) unsigned long long enabledModule;
@property (nonatomic) BOOL enableExternalAU;
@property (nonatomic) BOOL enableKeepDarkFrame;
@property (nonatomic) BOOL enablePipelineKTVCamera;
@property (nonatomic) BOOL enableMergeRtcExtraDataToLiveStream;
@property (nonatomic) BOOL willCloseLivingRoom;
@property (nonatomic) BOOL changeToFullInteractOnlySelf;
@property (nonatomic) BOOL interactIgnoreCaptureVideoBuffer;
@property (nonatomic) BOOL userForceFpsFallback;
@property (copy, nonatomic) id /* block */ queryIsNeedStreamingCallback;
@property (copy, nonatomic) NSDictionary *lensEnhancedAlgorithmParams;
@property (copy, nonatomic) id /* block */ shouldUpdateOptimumIPAddress;
@property (copy, nonatomic) id /* block */ excuteWithCommandAndUserInfo;
@property (nonatomic) unsigned char enableUpdateConfigCallAB;
@property (copy, nonatomic) id /* block */ streamLogCallback;
@property (copy, nonatomic) id /* block */ velivePusherLogCallback;
@property (copy, nonatomic) id /* block */ networkQualityCallback;
@property (copy, nonatomic) id /* block */ hostInfoProvider;
@property (nonatomic) BOOL enableCheckingCameraRunningStatus;
@property (copy, nonatomic) id /* block */ debugLogBlock;
@property (retain, nonatomic) NSNumber *performanceLevel;
@property (nonatomic) BOOL liveCoreLogEnabled;
@property (nonatomic) long long liveCoreLogFlag;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)setUpdateVersionCode:(id)a0;
+ (id)getEffectABInfoWithLicense:(id)a0;
+ (void)setEffectABInfo:(id)a0 withLicense:(id)a1;
+ (BOOL)ktvAllowed;
+ (id)getMidiDrawingDataFilePath:(id)a0;
+ (void)setisStreamingDisplayInfoEnable:(BOOL)a0;
+ (BOOL)isStreamingDisplayInfoEnable;
+ (id)showStreamingDisplayInfo;
+ (id)showInteractDisplayInfo;
+ (id)convertContourModelWithStruct:(struct contour_info_st { unsigned char x0; unsigned short x1; unsigned short x2; struct con_string_ { unsigned short x0; unsigned char x1[0]; } x3; struct contour_extra_ { unsigned char x0; unsigned short x1; unsigned char x2[0]; } x4; unsigned char x5; struct contour_item_ { unsigned short x0; struct point_ { unsigned short x0; unsigned short x1; } x1[0]; } x6[0]; } *)a0;
+ (id)getSdkVersion;
+ (void)sendStreamLogToB:(id)a0;
+ (void)aweprivacy_video_preload;
+ (void)load;
+ (void)setAppVersion:(id)a0;
+ (void)initialize;

- (double)musicDuration;
- (id)audioEffect;
- (void)setAudioEffect:(id)a0;
- (void)setMusicVolume:(float)a0;
- (id)liveConfig;
- (void)startVideoCapture:(id)a0;
- (double)currentPlayTime;
- (id)convertHexStrToData:(id)a0;
- (int)getAECType;
- (void)setEnableAgc:(BOOL)a0;
- (float)getMusicVolume;
- (void)setMusicPlayerVolume:(double)a0;
- (float)getMusicPlayerVolume;
- (void)setEnableAudioPitchShifter:(BOOL)a0;
- (BOOL)isEnableAudioPitchShifter;
- (void)didCaptureVideoSampleBuffer:(struct opaqueCMSampleBuffer { } *)a0;
- (void)exposureAtPoint:(struct CGPoint { double x0; double x1; })a0;
- (void)onLinkMicAudio:(void *)a0 size:(unsigned int)a1 numberOfFrames:(int)a2 numberOfchannels:(int)a3 sampleRate:(int)a4 pts:(long long)a5;
- (void)pushPlayerAudioData:(struct AudioBufferList { unsigned int x0; struct AudioBuffer { unsigned int x0; unsigned int x1; void *x2; } x1[1]; } *)a0 frames:(int)a1 bytesPerSample:(int)a2 channels:(int)a3 sampleRate:(int)a4;
- (void)pushPlayerAECAudioData:(struct AudioBufferList { unsigned int x0; struct AudioBuffer { unsigned int x0; unsigned int x1; void *x2; } x1[1]; } *)a0 frames:(int)a1 bytesPerSample:(int)a2 channels:(int)a3 sampleRate:(int)a4;
- (void)pullMicAudio:(void *)a0 size:(unsigned int)a1 sampleRate:(int)a2 timeStamp:(long long)a3 mNumberChannels:(unsigned int)a4 numberOfFrames:(int)a5 processedData:(void *)a6 earMonitorData:(void *)a7;
- (void)processEarMonitorData:(void *)a0 size:(unsigned int)a1 sampleRate:(int)a2 timeStamp:(long long)a3 mNumberChannels:(unsigned int)a4 numberOfFrames:(int)a5;
- (void)callbackAudioLog:(id)a0;
- (id)audioCoderSinkForNormal;
- (void *)audioCoderSinkForByteAudio;
- (void)onAudioCaptureEvent:(long long)a0;
- (void)onAudioDenoiseInfoChanged:(int)a0 audioCaptureRouter:(int)a1 denoiseBound:(int)a2 noiseEstimationMode:(int)a3 denoiseAedScene:(id)a4;
- (int)sizeForContourExtraStr:(id)a0;
- (int)sizeForContourExtraData:(id)a0;
- (struct con_string_ { unsigned short x0; unsigned char x1[0]; } *)contourExtraStr:(id)a0;
- (struct contour_extra_ { unsigned char x0; unsigned short x1; unsigned char x2[0]; } *)contourExtraData:(id)a0;
- (void)setContourInfoHelper:(id)a0;
- (id)contourInfoHelper;
- (void)setEffectABLicense:(id)a0;
- (void)fetchEffectDetectPhotoContentWithImage:(id)a0 algorithmType:(id)a1 isLastPhone:(BOOL)a2 callback:(id /* block */)a3;
- (void)setEffectRenderCacheTextureWithImage:(id)a0 algorithmType:(id)a1;
- (void)releaseEffectCapturedImage:(struct LSLiveEffectImage { char *x0; int x1; int x2; int x3; int x4; unsigned long long x5; void *x6; })a0;
- (id)byteAudioAuxRenderSink;
- (void)startSpeechRecognizing;
- (void)stopSpeechRecognizing;
- (BOOL)isSpeechRecognizing;
- (void)setEffectABInfo:(id)a0;
- (void)needAddMonitoringLinkMicAudioData;
- (void)needRemoveMonitoringLinkMicAudioData;
- (void)reportToServer:(id)a0;
- (void)stopPushKaraokeAudio;
- (void)setKaraokeVideoMixerDescription:(long long)a0 withPosition:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)pauseMV;
- (void)playMV;
- (void)setEnableKaraokeMovieAudioPitchShifter:(BOOL)a0;
- (BOOL)isEnableKaraokeMovieAudioPitchShifter;
- (void)setKaraokeMoviePitch:(double)a0;
- (void)setKaraokeVideoMixerDescription:(long long)a0 zOrder:(int)a1 withPosition:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a2;
- (void)resetMovieRenderView:(id)a0;
- (void)pushKaraokeMovieBuffer:(struct __CVBuffer { } *)a0 andCMTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)pushKaraokeMovieAudioBuffer:(float **)a0 samples:(int)a1;
- (void)prepareKaraokeMovieAudio:(int)a0 channels:(int)a1;
- (void)setKaraokeMixVolume:(float)a0 captureVolume:(float)a1;
- (void)setKaraokePlayVolume:(float)a0;
- (BOOL)original_ktv_installed;
- (BOOL)replace_ktv_installed;
- (void)original_ktv_init;
- (void)replace_ktv_init;
- (void)original_ktv_stop;
- (void)replace_ktv_stop;
- (id)original_ktv_requestExtraData;
- (id)replace_ktv_requestExtraData;
- (void)original_ktv_didReceiveRTCExtraData:(id)a0;
- (void)replace_ktv_didReceiveRTCExtraData:(id)a0;
- (void)original_ktv_processAudioBufferList:(void *)a0 inNumberFrames:(unsigned int)a1 processedData:(void *)a2 headphonesMonitoringData:(void *)a3 channels:(int)a4 dataSize:(unsigned int)a5 sampleRate:(int)a6 onlyLocalPlay:(BOOL)a7;
- (void)replace_ktv_processAudioBufferList:(void *)a0 inNumberFrames:(unsigned int)a1 processedData:(void *)a2 headphonesMonitoringData:(void *)a3 channels:(int)a4 dataSize:(unsigned int)a5 sampleRate:(int)a6 onlyLocalPlay:(BOOL)a7;
- (void)original_ktv_processEarMonitorData:(void *)a0 inNumberFrames:(unsigned int)a1 channels:(int)a2 dataSize:(unsigned int)a3 sampleRate:(int)a4 onlyLocalPlay:(BOOL)a5;
- (void)replace_ktv_processEarMonitorData:(void *)a0 inNumberFrames:(unsigned int)a1 channels:(int)a2 dataSize:(unsigned int)a3 sampleRate:(int)a4 onlyLocalPlay:(BOOL)a5;
- (void)p_stopBgMusic;
- (id)scoreEngine;
- (id)ktvEngine;
- (BOOL)isRouteToSpeaker;
- (BOOL)isHeadphonesMonitoringEnabled;
- (float)getAudioVolume;
- (id)musicLoudNormEngine;
- (BOOL)isEnableLoudNorm;
- (id)originRenderSink;
- (void)setOriginRenderSink:(id)a0;
- (void)renderAudioFile;
- (id)earMonitorKtvEngine;
- (id)lyricArray;
- (id)lyricStringArray;
- (id)bachContourInfoAndExtraDataUncompressWithData:(id)a0;
- (id /* block */)contourModelCallBack;
- (int)sendSEIMsgWithKey:(id)a0 value:(id)a1 repeatTimes:(long long)a2 keyFrameOnly:(BOOL)a3 allowsCovered:(BOOL)a4 timeGap:(int)a5;
- (long long)getTimestampWithNtpDiff;
- (id)bgmProcessorObserver;
- (void)setBgmProcessorObserver:(id)a0;
- (void)stopBgMusic;
- (void)setEnablePlayer:(BOOL)a0;
- (void)setEnablePipelineMode:(long long)a0;
- (void)playBgMusicWithConfig2:(id)a0 createPlayerCompletion:(id /* block */)a1 completionBlock:(id /* block */)a2;
- (void)setMusicLoudNormEngine:(id)a0;
- (void)playBgMusicWithConfig:(id)a0 createPlayerCompletion:(id /* block */)a1 completionBlock:(id /* block */)a2;
- (void)setEnablePulseGeneratorFilter:(BOOL)a0;
- (void)setPulseGeneratorFrequency:(long long)a0;
- (void)setDeviceLoopDelay:(long long)a0;
- (void)setLatestLyricInfo:(id)a0;
- (void)setLyricArray:(id)a0;
- (id)latestLyricInfo;
- (void)setLyricStringArray:(id)a0;
- (void)logWithALogSource:(long long)a0 logLevel:(int)a1 log:(id)a2;
- (void)setDisablePipelineMode:(long long)a0;
- (void)setMicVolume:(float)a0;
- (void)setEarMonitorVolume:(float)a0;
- (long long)setupSingScoring:(long long)a0 level:(long long)a1 lyricsFilepath:(id)a2 midiFilepath:(id)a3 refAcapellaFilepath:(id)a4;
- (long long)releaseSingScoring;
- (id)getMidiDrawingData;
- (id)getRealtimeInfo;
- (void)setEnableAudioLoudNorm:(BOOL)a0 param:(float)a1;
- (id)ktvReverb2Format;
- (id)ktvEqualizerFormat;
- (id)rockReverb2Format;
- (id)rockEqualizerFormat;
- (id)popularReverb2Format;
- (id)popularEqualizerFormat;
- (id)relaxedReverb2Format;
- (id)relaxedEqualizerFormat;
- (void)setScoreEngine:(id)a0;
- (void)setKtvEngine:(id)a0;
- (void)setEarMonitorKtvEngine:(id)a0;
- (BOOL)ktv_isInteractKTVAllowed;
- (void)playBgMusicWithURL:(id)a0 loop:(BOOL)a1 volume:(float)a2 createPlayerCompletion:(id /* block */)a3 completionBlock:(id /* block */)a4;
- (void)setEnableKTVAccurateProgress:(BOOL)a0;
- (void)setEnableAudioScoreWhenLocalPlay:(BOOL)a0;
- (void)sendLyricInfo:(id)a0 withKey:(id)a1;
- (void)sendLyricStringInfo:(id)a0 withKey:(id)a1;
- (void)pauseBgMusic;
- (void)resumeBgMusic;
- (BOOL)musicIsPlaying;
- (void)setMusicPushVolume:(double)a0;
- (float)getMusicPushVolume;
- (void)setAudioVolumeV2:(float)a0;
- (long long)startSingScoring;
- (long long)stopSingScoring;
- (long long)singScoreSeekToTime:(double)a0;
- (long long)setSingScoringPitch:(double)a0;
- (double)getSingScoringPitch;
- (void)muteLocalAudioStream:(BOOL)a0 exceptBgm:(BOOL)a1;
- (void)setEnableLoudNorm:(BOOL)a0;
- (void)setLoudNormParams:(id)a0;
- (void)forceMediaMode:(BOOL)a0;
- (void)applyReverb2Format:(id)a0;
- (void)setAudioScoreEngine:(id)a0;
- (void)setKtvEffectEngine:(id)a0;
- (void)setKtvEarMonitorEffectEngine:(id)a0;
- (void)playAudioFileInner:(id)a0 audioFileWillPlay:(id /* block */)a1 audioFileStoped:(id /* block */)a2 audioFilePlayError:(id /* block */)a3;
- (void)stopPlayAudioFileInner;
- (void)stopPlayAudioFile;
- (void)initAudioFilePlayStatus;
- (void)playAudioFile:(id)a0 audioFileWillPlay:(id /* block */)a1 audioFileStoped:(id /* block */)a2 audioFilePlayError:(id /* block */)a3;
- (void)releasePlayAudioFile;
- (double)getFileDuration;
- (int)karaokeMovieZOrder;
- (void)resetPreviewOn:(id)a0;
- (void)startVideoCapture:(id)a0 withStateDelegate:(id)a1;
- (void)setupVideoPath:(id)a0 withStateDelegate:(id)a1;
- (id)interactSeiNSData;
- (void)setInteractSeiNSData:(id)a0;
- (id)getAndCleanUpInteractSeiDic;
- (id)interactSeiDic;
- (void)__setupCaptureWithEffect:(BOOL)a0 withAsync:(BOOL)a1;
- (void)setupVideoCamera:(id)a0;
- (void)setPreviewMirror:(BOOL)a0;
- (void)enableSingleView:(BOOL)a0;
- (BOOL)fetchSingleViewStatus;
- (void)setSingleViewCropRegion:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)setLiveCapture:(id)a0;
- (void)setInteractSeiDic:(id)a0;
- (BOOL)startEffectBachAlgorithmWithConfig:(id)a0;
- (BOOL)startEffectBachAlgorithmWithConfig:(id)a0 seiFormat:(long long)a1;
- (BOOL)stopEffectBachAlgorithm;
- (struct contour_info_st { unsigned char x0; unsigned short x1; unsigned short x2; struct con_string_ { unsigned short x0; unsigned char x1[0]; } x3; struct contour_extra_ { unsigned char x0; unsigned short x1; unsigned char x2[0]; } x4; unsigned char x5; struct contour_item_ { unsigned short x0; struct point_ { unsigned short x0; unsigned short x1; } x1[0]; } x6[0]; } *)bachContourInfoUncompressWithData:(id)a0;
- (struct contour_info_st { unsigned char x0; unsigned short x1; unsigned short x2; struct con_string_ { unsigned short x0; unsigned char x1[0]; } x3; struct contour_extra_ { unsigned char x0; unsigned short x1; unsigned char x2[0]; } x4; unsigned char x5; struct contour_item_ { unsigned short x0; struct point_ { unsigned short x0; unsigned short x1; } x1[0]; } x6[0]; } *)bachContourInfoUncompressWithString:(id)a0;
- (void)enableAudioInterruptedObserver:(BOOL)a0;
- (void)setAudioInterruptMode:(long long)a0;
- (long long)setAudioCaptureSourceType:(long long)a0;
- (long long)pushExternalAudioFrame:(char *)a0 DataSize:(long long)a1 FormatType:(long long)a2 SampleRate:(long long)a3 ChannelNumber:(long long)a4 PTS:(long long)a5;
- (void)prepareCommonRenderSink;
- (void)stopAudioCaptureByScene:(id)a0;
- (void)startFakeAudioCapture;
- (void)stopFakeAudioCapture;
- (BOOL)isMicOccupiedSilenced;
- (void)audioPlayerInterrupted:(BOOL)a0;
- (void)pushAudioBuffer:(char *)a0 andDataLen:(unsigned long long)a1 sampelRate:(int)a2 channels:(int)a3 andBytesPerSample:(int)a4 timestamp:(long long)a5 trackId:(int)a6;
- (void)setEnableAudioCaptureInBackground:(BOOL)a0;
- (void)setEnableSpeaker:(BOOL)a0;
- (void)setEnableNoiseSuppression:(BOOL)a0 param:(float)a1;
- (void)setEnableNoiseSuppressionWithType:(unsigned long long)a0 enable:(BOOL)a1 param:(float)a2 resourceUrl:(id)a3;
- (void)setEnableExternalSoundCard:(BOOL)a0;
- (BOOL)isEnableExternalSoundCard;
- (void)setVideoRecordCallback:(id /* block */)a0;
- (void)setEnableAecOnHeadsetMode:(BOOL)a0;
- (BOOL)isEnableSoftAec;
- (void)setAECType:(int)a0;
- (void)setDiagnosisModelPath:(id)a0;
- (void)setEnableSoftAec:(BOOL)a0;
- (void)setEnableMediaVolOnSWAec:(BOOL)a0;
- (BOOL)isEnableAecOnHeadsetMode;
- (void)setSoftAECModelPath:(id)a0;
- (void)setHeadphonesMonitoringEnabled:(BOOL)a0;
- (void)setEnableAudioLowLatency:(BOOL)a0 ioBufferDuration:(float)a1;
- (void)setEnablePlayoutEcho:(BOOL)a0;
- (void)resetCheckAudioIOPipelineInterval:(double)a0;
- (void)setAudioInformationDelegate:(id)a0;
- (void)setAudioKitDiagnosisDelegate:(id)a0;
- (void)enableAudioVADReport:(long long)a0 percentage:(float)a1;
- (void)enableAudioAEDReport:(long long)a0 percentage:(float)a1;
- (void)enableAudioRhythmReport:(BOOL)a0 isSync:(BOOL)a1 rhythmType:(long long)a2 modlePath:(id)a3;
- (void)startAudioKitDiagnosis:(long long)a0 loopCallbackTime:(int)a1 diagnosisDuration:(int)a2;
- (void)stopAudioKitDiagnosis;
- (struct { double x0; double x1; })getAudioDeviceModuleStats;
- (BOOL)isMicRunning;
- (BOOL)isFakeAudioCaptureRunning;
- (BOOL)isEchoCancellationEnabled;
- (BOOL)isAudioCaptureInterrupted;
- (int)getAudioRmsInCaptureTime;
- (void)setInputFrameCallback:(id /* block */)a0;
- (void)setEffectFrameCallback:(id /* block */)a0;
- (BOOL)setCroppedInputFrameCallbackWithRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 originSize:(struct CGSize { double x0; double x1; })a1 callback:(id /* block */)a2;
- (BOOL)setCroppedEffectFrameCallbackWithRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 originSize:(struct CGSize { double x0; double x1; })a1 callback:(id /* block */)a2;
- (struct __CVBuffer { } *)getPixelBufferWithIsEffected:(BOOL)a0;
- (id)getJpegDataWithIsEffected:(BOOL)a0 compressionRatio:(double)a1;
- (void)configureAudioCatcher:(id)a0 durationMs:(long long)a1 format:(unsigned long long)a2 isPeriodCatch:(BOOL)a3 totalDurationMsOnPeriodCatch:(long long)a4 outSampleHz:(int)a5 outChannel:(int)a6;
- (void)stopAudioCatcher;
- (struct LSLiveEffectImage { char *x0; int x1; int x2; int x3; int x4; unsigned long long x5; void *x6; })getEffectCapturedImagewithKey:(id)a0;
- (void)enableAudioPushStream:(BOOL)a0;
- (void)setAudioCaptureDataMonitorWithResample:(id)a0 sampleRate:(int)a1 channels:(int)a2;
- (void)setContourDataCallBack:(id /* block */)a0;
- (void)setContourModelCallBack:(id /* block */)a0;
- (void)setEffectBachAlgorithmEnable:(BOOL)a0 threshold:(long long)a1;
- (id)bachContourInfoAndExtraDataUncompressWithString:(id)a0;
- (void)setupAudioCaptureWithConfig:(id)a0;
- (id)startAudioCaptureWithCert:(id)a0;
- (id)stopAudioCaptureWithCert:(id)a0;
- (id)audioCaptureInterrupted:(BOOL)a0 withCert:(id)a1;
- (void)setAudioRecordCallback:(id /* block */)a0;
- (id)setEchoCancellationEnabled:(BOOL)a0 withCert:(id)a1;
- (void)setAutoResumeVideoCaptureOnAppActive:(BOOL)a0;
- (void)setEnableAudioCaptureRespondToAppStatus:(BOOL)a0;
- (void)audioCatchOnData:(id)a0 startTimeMs:(long long)a1 durationTimeMs:(long long)a2 outSampleHz:(int)a3 outChannel:(int)a4 format:(unsigned long long)a5;
- (void)audioCatchOnError:(int)a0 message:(id)a1;
- (void)audioCatchOnComplete;
- (void)startAudioCatcher;
- (void)onCaptureEvent:(int)a0 code2:(int)a1 message:(id)a2;
- (void)onCaptureError:(int)a0 code2:(int)a1 message:(id)a2;
- (void)original_interact_init;
- (void)setBusinessScene:(long long)a0;
- (BOOL)replace_timor_game_installed;
- (void)original_timor_game_status_did_changed:(long long)a0;
- (void)original_interact_status_did_changed:(long long)a0;
- (void)startCameraCaptureIfNeeded;
- (void)startCameraChecking;
- (void)stopCameraChecking;
- (void)audioCaptureInterrupted:(BOOL)a0;
- (void)invalidateLogTimer;
- (void)removeAllTimerBlock;
- (void)releaseDarkImageBuf;
- (id)getEAGLContext;
- (void)onPowerStateChanged;
- (void)onThermalStateChanged;
- (void)parseLiveConfiguration:(id)a0;
- (long long)getLatestAudioPts;
- (void)parseReconnectConfig:(id)a0;
- (id)appendBasicLog;
- (id)appendVideoLog;
- (id)appendMessageLog;
- (void)reportAudioDiagnosisFinalResult;
- (void)checkSendStatus:(id)a0;
- (void)updateStreamingConfiguration:(id)a0;
- (void)checkDeviceLevel;
- (void)__updateStreamingBitrateRatio:(float)a0 from:(id)a1;
- (void)onPerformanceDegradeNotification:(id)a0;
- (int)sendSEIMsgWithKey:(id)a0 value:(id)a1 repeatTimes:(long long)a2;
- (void)setEnableAutoResumeAudioCaptureOnAppActive:(BOOL)a0;
- (void)setLiveConfigurationParamChangeCallback:(id)a0;
- (void)__updateStreamingOutputSize:(struct CGSize { double x0; double x1; })a0 from:(id)a1;
- (void)stopStreamingForPrivate;
- (void)startStreamingByScene:(id)a0;
- (id)liveCapture;
- (void)setEchoCancellationEnabled:(BOOL)a0;
- (void)setEnableCalculateAudioLoudness:(BOOL)a0;
- (void)generateNetworkStatusTimer;
- (void)setupCapturePipeline;
- (void)setStreamWillBeKickedOff:(BOOL)a0;
- (void)p_setupCaptureDarkFrameMode;
- (void)stopPushDarkFrame;
- (void)p_setupVideoProcessPipeLine;
- (void)p_setupCaptureVideoBypassPipeLine;
- (void)startPushDarkFrame;
- (void)p_pushVideoBufferToInteract:(struct __CVBuffer { } *)a0 timeInfo:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (BOOL)pushDarkFrameForAudioStreamIfNeeded;
- (void)setInputStreamRuntimeParams:(id)a0;
- (void)updateStreamingConfiguration:(id)a0 callback:(id /* block */)a1;
- (void)__updateStreamingBitrate:(long long)a0 minBit:(long long)a1 maxBit:(long long)a2 from:(id)a3;
- (void)__updateStreamingFrameRate:(int)a0 from:(id)a1;
- (void)checkDisableSitiForInteract:(BOOL)a0;
- (void)checkFpsFallback:(BOOL)a0;
- (void)checkDisableVQScoreForInteract:(BOOL)a0;
- (void)checkDisableColorHistForInteract:(BOOL)a0;
- (void)checkDisableVideoDenoiseForInteract:(BOOL)a0;
- (void)checkDisableBapLiveForInteract:(BOOL)a0;
- (void)checkDisableLensEnhancedBitrateRatioForInteract:(BOOL)a0;
- (void)checkSeiPayloadProcessorForInteract:(BOOL)a0;
- (void)checkUpdateRtcNetStats:(int)a0 rtt:(int)a1 jitter:(int)a2 lossRate:(float)a3 requestBpsMax:(int)a4;
- (void)checkRtcResolutionStats:(int)a0 height:(int)a1 fps:(int)a2 videoMaxBw:(int)a3 videoMinBw:(int)a4;
- (void)checkRtcPublishState:(int)a0;
- (void)checkRtcBusinessId:(id)a0;
- (void)updateBitrateRatioForLensEnhancedAlgorithm:(float)a0;
- (struct __CVBuffer { } *)darkFrameForAudioStream;
- (void)pushVideoBuffer:(struct __CVBuffer { } *)a0 andCMTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)stopStreamingByScene:(id)a0;
- (void)stopStreamingForPrivateByScene:(id)a0;
- (void)stopNetworkStatusTimer;
- (void)setAudioMute:(BOOL)a0 event_from:(id)a1;
- (float)getMicVolume;
- (int)sendSEIInfoInChorusWithKey:(id)a0 value:(id)a1;
- (void)updateInteractAuthInfo:(id)a0 value:(id)a1 Flag:(int)a2 FrameType:(long long)a3;
- (int)sendSEIMsgWithKey:(id)a0 value:(id)a1 repeatTimes:(long long)a2 keyFrameOnly:(BOOL)a3 allowsCovered:(BOOL)a4 timeGap:(int)a5 seiFlag:(int)a6;
- (int)sendSEIMsgWithKey:(id)a0 value:(id)a1 repeatTimes:(long long)a2 keyFrameOnly:(BOOL)a3 allowsCovered:(BOOL)a4 timeGap:(int)a5 seiFlag:(int)a6 pts:(struct { long long x0; int x1; unsigned int x2; long long x3; })a7;
- (void)addUserMetaData:(id)a0 value:(id)a1 flag:(int)a2;
- (id)getStreamInfoForKey:(id)a0;
- (long long)getTimestampForKey:(long long)a0;
- (id)getAudioBytesSent;
- (id)getVideoBytesSent;
- (void)setEnableAudioMonitor:(BOOL)a0 timefreq:(int)a1;
- (void)setAudioMonitorDelegate:(id)a0;
- (int)SetAudioBitrate:(int)a0 Profile:(id)a1 EnableChangeProfile:(BOOL)a2;
- (int)GetAudioBitrate;
- (void)pushAudioBuffer:(char *)a0 andDataLen:(unsigned long long)a1 andInNumberFrames:(int)a2 andCMTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a3;
- (void)original_timor_game_init;
- (void)original_timor_game_deinit;
- (void)reportLiveCoreLog:(id)a0 params:(id)a1;
- (void)refineAudioPlayerMode;
- (long long)p_getCurrentSysMillSeconds;
- (void)onLiveSdkParamsIssue:(id)a0;
- (void)p_execPushRestart:(id)a0;
- (void)p_execSwitchMixType:(id)a0;
- (id)getInteractExtraData;
- (void)audioProcessWithData:(void *)a0 size:(unsigned int)a1 sampleRate:(int)a2 timeStamp:(long long)a3 mNumberChannels:(unsigned int)a4 numberOfFrames:(unsigned int)a5 processedData:(void *)a6 earMonitorData:(void *)a7;
- (void)audioProcessEarMonitorData:(void *)a0 size:(unsigned int)a1 sampleRate:(int)a2 timeStamp:(long long)a3 mNumberChannels:(unsigned int)a4 numberOfFrames:(unsigned int)a5;
- (void)playerProcessWithData:(struct AudioBufferList { unsigned int x0; struct AudioBuffer { unsigned int x0; unsigned int x1; void *x2; } x1[1]; } *)a0 frames:(int)a1 bytesPerSample:(int)a2 channels:(int)a3 sampleRate:(int)a4;
- (void)executeTimerBLocks;
- (id)getAudioQosInfo;
- (void)streamSession:(id)a0 onStatusChanged:(long long)a1;
- (void)streamSession:(id)a0 errorType:(long long)a1 onError:(long long)a2 errorMessage:(id)a3;
- (void)updateLiveCoreModule:(unsigned long long)a0;
- (void)saveAVAudioSession;
- (void)restoreAVAudioSession;
- (void)setupLiveSessionWithConfig:(id)a0;
- (id)getStreamSession;
- (void)retryStreaming;
- (void)setEnableServerMix:(BOOL)a0;
- (void)updatePSNRStatisticsFrames:(long long)a0 periodSeconds:(long long)a1 enable:(BOOL)a2;
- (struct CGSize { double x0; double x1; })getCameraOutputSizeFromParams:(id)a0;
- (void)onInteractSatusChange:(BOOL)a0;
- (void)enableFpsFallBack:(BOOL)a0;
- (void)updateRtcNetStats:(int)a0 lossRate:(float)a1 bwe:(int)a2 jitter:(int)a3 backgroundLossRate:(float)a4 requestBpsMax:(int)a5;
- (void)updateRtcResolutionStats:(int)a0 height:(int)a1 fps:(int)a2 videoMaxBw:(int)a3 videoMinBw:(int)a4;
- (void)updateRtcPublishState:(int)a0;
- (void)updateRtcBusinessId:(id)a0;
- (int)sendSEIMsgWithKey:(id)a0 value:(id)a1 repeatTimes:(long long)a2 keyFrameOnly:(BOOL)a3 allowsCovered:(BOOL)a4;
- (long long)getBitrateStrategy;
- (void)setEnableAudioDeviceMonitor:(BOOL)a0 timefreq:(int)a1;
- (void)setADMonitorDelegate:(id)a0;
- (int)setAudioEncoderBiterate:(int)a0;
- (unsigned long long)getMetaAudioBitrate;
- (void)pushEffectedVideoBuffer:(struct __CVBuffer { } *)a0 texture:(int)a1 andCMTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a2;
- (void)pushEffectedVideoBufferAfterStarted:(struct __CVBuffer { } *)a0 texture:(int)a1 andCMTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })a2;
- (void)startPushEffectedFrame;
- (void)stopPushEffectedFrame;
- (void)pushVideoBuffer:(struct __CVBuffer { } *)a0 andTimestamp:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)p_setRunState:(long long)a0;
- (void)p_setMixOnClient:(BOOL)a0;
- (BOOL)p_mixOnClient;
- (void)p_enableExternalClientMix:(BOOL)a0;
- (BOOL)checkVendorClientMixPercentage:(id)a0 clientType:(int)a1 playMode:(id)a2;
- (BOOL)getInteractStreamBitrate:(long long *)a0 MinBitrate:(long long *)a1 MaxBitrate:(long long *)a2;
- (BOOL)getLivingStreamBitrate:(long long *)a0 MinBitrate:(long long *)a1 MaxBitrate:(long long *)a2;
- (void)pushRestart:(id)a0;
- (void)setAudioPlayerMixMode:(long long)a0;
- (void)audioProcessWithData:(void *)a0 size:(unsigned int)a1 timeStamp:(long long)a2 mNumberChannels:(unsigned int)a3 numberOfFrames:(unsigned int)a4 processedData:(void *)a5 earMonitorData:(void *)a6;
- (void)pullRecordAudio:(void *)a0 numberOfFrames:(int)a1 numberOfchannels:(int)a2 pts:(long long)a3;
- (void)generateLogTimer;
- (void)addTimerBlock:(id /* block */)a0;
- (void)removeTimerBlock:(id /* block */)a0;
- (id)appendAudioLog;
- (BOOL)original_interact_installed;
- (void)original_interact_cleanup;
- (void)original_interact_pushAudioDataToInteractSDK:(void *)a0 size:(unsigned int)a1 timeStamp:(long long)a2;
- (void)original_interact_pushVideoBuffer:(struct __CVBuffer { } *)a0 timeInfo:(struct { long long x0; int x1; unsigned int x2; long long x3; })a1;
- (void)original_interact_resumeMixedPushIfNeeded;
- (void)original_interact_updateStreamingWithParams:(id)a0;
- (void)original_interact_switchMixType:(BOOL)a0;
- (void)original_interact_leaveChannel;
- (BOOL)original_interact_isRunning;
- (void)original_interact_updateAuthinfo:(id)a0 value:(id)a1 Flag:(int)a2 FrameType:(long long)a3;
- (void)didCaptureAudioSampleBuffer:(struct opaqueCMSampleBuffer { } *)a0;
- (void)aweprivacy_video_startPushDarkFrame;
- (void)aweprivacy_video_stopPushDarkFrame;
- (id)initWithMode:(unsigned long long)a0;
- (void).cxx_destruct;
- (void)setPitch:(double)a0;
- (void)setAudioUnit:(id)a0;
- (void)debugLog:(id)a0;
- (id)init;
- (void)startAudioCapture;
- (BOOL)isStreaming;
- (id).cxx_construct;
- (void)addObserver;
- (void)cleanUp;
- (void)seekToTime:(double)a0;
- (void)dealloc;
- (void)setAudioVolume:(float)a0;
- (void)stopAudioCapture;
- (id)audioUnit;
- (void)removeObserver;
- (void)startVideoCapture;
- (void)stopVideoCapture;
- (void)setPreviewMode:(long long)a0;
- (void)setShouldAutoReconnect:(BOOL)a0;
- (struct AudioStreamBasicDescription { double x0; unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7; unsigned int x8; })audioStreamBasicDescription;
- (void)startStreaming;
- (void)stopStreaming;
- (id)commonLog;

@end
