@class NSTimer, NSString, NSArray, LSIMCurrentUser, LSIMTipModel, NSMutableDictionary, LSIMDebounce, LSIMRequestChatListMemberManager, NSMutableArray, LSIMChatListTracker, LSIMThrottle;

@interface LSIMChatListVM : LSListVM <LSIMServiceClientObserver, LSListCellVMDelegate>

@property (copy, nonatomic) NSString *enterFrom;
@property (copy, nonatomic) NSString *enterMethod;
@property (copy, nonatomic) NSString *noticeGroup;
@property (copy, nonatomic) NSString *originInbox;
@property (copy, nonatomic) NSArray *inboxes;
@property (nonatomic) BOOL isRequestOnAir;
@property (nonatomic) BOOL isFirstFetch;
@property (copy, nonatomic) NSArray *conversations;
@property (retain, nonatomic) NSMutableArray *dataSource;
@property (retain, nonatomic) NSMutableDictionary *dataSourceDict;
@property (retain, nonatomic) LSIMRequestChatListMemberManager *requestMemberManager;
@property (retain, nonatomic) LSIMThrottle *messageUpdateThrottle;
@property (copy, nonatomic) NSString *orderPageURL;
@property (retain, nonatomic) NSTimer *refreshTimer;
@property (copy, nonatomic) NSString *serviceProgressUrl;
@property (nonatomic) BOOL serviceProgressNeedUpdate;
@property (copy, nonatomic) NSArray *platformConversations;
@property (retain, nonatomic) NSMutableDictionary *platformInfo;
@property (nonatomic) BOOL isRequestingPlatform;
@property (retain, nonatomic) LSIMTipModel *tipModel;
@property (nonatomic) BOOL hasBeenReportUnread;
@property (nonatomic) BOOL hasBeenReportTopNotify;
@property (nonatomic) BOOL needSyncUnreadCount;
@property (nonatomic) BOOL needSyncStableUnreadCount;
@property (retain, nonatomic) LSIMDebounce *syncToIMDataDebounce;
@property BOOL syncingDataToIM;
@property BOOL hasSyncedDataToIM;
@property BOOL unreadCountIsNotStable;
@property (readonly, copy, nonatomic) NSString *title;
@property (readonly, nonatomic) BOOL isApplet;
@property (readonly, nonatomic) LSIMCurrentUser *currentUser;
@property (readonly, nonatomic) LSIMChatListTracker *tracker;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)configWithRouterParamDict:(id)a0;
- (id)initWithRouterParamDict:(id)a0;
- (unsigned long long)totalUnreadCountForDisplay;
- (void)syncDataToIMWithScene:(id)a0;
- (double)latestUnreadMsgCreateTime;
- (void)syncALLDataToIM;
- (void)unreadCountStateChange;
- (BOOL)enableBoxOpt;
- (void)markReadForMessageBox;
- (void)closeTip;
- (void)conversationDidUpdate:(id)a0;
- (void)handleListFetch;
- (Class)listFactory;
- (void)conversationsDidChangeWithNew:(id)a0;
- (void)conversationsDidDeleted:(id)a0;
- (void)messagesDidInsert:(id)a0 reason:(long long)a1 inConversations:(id)a2;
- (void)messageDidUpdateWithMessage:(id)a0;
- (void)didReceiveWsMessage:(id)a0 method:(long long)a1;
- (void)cellVM:(id)a0 action:(id)a1;
- (void)handleListLifeCycleChanged:(long long)a0;
- (void)refreshListTimestampShow;
- (void)requestTipInfoWithCompletion:(id /* block */)a0;
- (void)savePlatformConversationsToDisk;
- (void)requestCustomerServiceInfo;
- (void)requestServiceProgressInfoWithCompletion:(id /* block */)a0;
- (void)clickTipWithTemplateModel:(id)a0;
- (void)clearUnreadCountWithCompletion:(id /* block */)a0;
- (void)openPageWithURLString:(id)a0;
- (void)getOrderPageURLWithCompletion:(id /* block */)a0;
- (void)openServiceProgressPage;
- (void)removeModelAtIndexPath:(id)a0;
- (void)requestDataSource;
- (void)dataSourceReady;
- (id)sortDataSource:(id)a0;
- (void)clearCustomerServiceUnreadMessageWithCompletion:(id /* block */)a0;
- (void)addCustomerServiceConversationWithInfo:(id)a0;
- (void)deleteCellWithCellVM:(id)a0 sendToServer:(BOOL)a1;
- (void)messageDidUpdated;
- (void)recallMessageIfNeed:(id)a0;
- (void)deletePlatformConversationWithInfo:(id)a0;
- (void)clearPlatformConversationUnreadMessageWithConversationID:(id)a0;
- (void).cxx_destruct;
- (id)serviceClient;
- (void)dealloc;
- (void)setupDataSource;
- (void)initData;

@end
