@class LynxShadowNodeOwner, LynxEventHandler, NSDictionary, LynxUIOwner, LynxFontFaceContext, LynxContext, UIView, NSString, LynxEventEmitter, LynxRootUI, LynxScreenMetrics, LynxUIExposure, LynxScrollFluency, LynxGlobalObserver, LynxUIIntersectionObserverManager;
@protocol LynxResourceFetcher, ListNodeInfoFetcherProtocol, LynxMediaResourceFetcher, LUIErrorHandling, LUIBodyView, LynxTemplateResourceFetcher, LynxListLayoutProtocol, LynxScrollListener, LynxImageFetcher, LynxGenericResourceFetcher;

@interface LynxUIContext : NSObject {
    BOOL _isDev;
}

@property (weak, nonatomic) id<LynxImageFetcher> imageFetcher;
@property (weak, nonatomic) LynxEventHandler *eventHandler;
@property (weak, nonatomic) LynxEventEmitter *eventEmitter;
@property (readonly, weak, nonatomic) UIView *rootView;
@property (retain, nonatomic) NSDictionary *keyframesDict;
@property (nonatomic) BOOL imageMonitorEnabled;
@property (nonatomic) BOOL devtoolEnabled;
@property (nonatomic) BOOL fixNewImageDownSampling;
@property (retain, nonatomic) LynxScrollFluency *fluencyInnerListener;
@property (weak, nonatomic) LynxContext *lynxContext;
@property (weak, nonatomic) id<LynxImageFetcher> imageFetcher;
@property (weak, nonatomic) id<LynxResourceFetcher> resourceFetcher;
@property (retain, nonatomic) id<LynxResourceFetcher> resourceServiceFetcher;
@property (weak, nonatomic) id<LynxListLayoutProtocol> customizedListLayout;
@property (weak, nonatomic) id<LUIErrorHandling> errorHandler;
@property (weak, nonatomic) id<LynxScrollListener> scrollListener;
@property (readonly, weak, nonatomic) LynxEventHandler *eventHandler;
@property (readonly, weak, nonatomic) LynxEventEmitter *eventEmitter;
@property (readonly, weak, nonatomic) UIView<LUIBodyView> *rootView;
@property (weak, nonatomic) LynxRootUI *rootUI;
@property (weak, nonatomic) LynxFontFaceContext *fontFaceContext;
@property (weak, nonatomic) LynxShadowNodeOwner *nodeOwner;
@property (weak, nonatomic) LynxUIOwner *uiOwner;
@property (weak, nonatomic) id lynxModuleExtraData;
@property (nonatomic) long long shellPtr;
@property (retain, nonatomic) id<ListNodeInfoFetcherProtocol> fetcher;
@property (retain, nonatomic) LynxScreenMetrics *screenMetrics;
@property (readonly, nonatomic) LynxUIIntersectionObserverManager *intersectionManager;
@property (retain, nonatomic) LynxUIExposure *uiExposure;
@property (readonly, nonatomic) NSDictionary *keyframesDict;
@property (retain, nonatomic) NSDictionary *contextDict;
@property (retain, nonatomic) LynxGlobalObserver *observer;
@property (readonly, nonatomic) BOOL enableTextGradientOpt;
@property (retain, nonatomic) id<LynxGenericResourceFetcher> genericResourceFetcher;
@property (retain, nonatomic) id<LynxMediaResourceFetcher> mediaResourceFetcher;
@property (retain, nonatomic) id<LynxTemplateResourceFetcher> templateResourceFetcher;
@property (nonatomic) BOOL enableFetchUIImage;
@property (retain, nonatomic) NSString *imagePreviewHashMetadata;
@property (readonly, nonatomic) BOOL defaultOverflowVisible;
@property (readonly, nonatomic) BOOL defaultImplicitAnimation;
@property (readonly, nonatomic) BOOL enableTextRefactor;
@property (readonly, nonatomic) BOOL defaultAutoResumeAnimation;
@property (readonly, nonatomic) BOOL defaultEnableNewTransformOrigin;
@property (readonly, nonatomic) BOOL enableEventRefactor;
@property (readonly, nonatomic) BOOL enableA11yIDMutationObserver;
@property (readonly, nonatomic) BOOL enableTextOverflow;
@property (readonly, nonatomic) BOOL enableNewClipMode;
@property (readonly, nonatomic) BOOL enableEventThrough;
@property (readonly, nonatomic) BOOL enableBackgroundShapeLayer;
@property (readonly, nonatomic) BOOL enableFiberArch;
@property (readonly, nonatomic) BOOL enableExposureUIMargin;
@property (readonly, nonatomic) BOOL enableTextLayerRender;
@property (readonly, nonatomic) BOOL enableTextLanguageAlignment;
@property (readonly, nonatomic) BOOL enableXTextLayoutReused;
@property (readonly, nonatomic) BOOL enableNewGesture;
@property (readonly, nonatomic) BOOL cssAlignWithLegacyW3c;
@property (readonly, nonatomic) NSString *targetSdkVersion;
@property (readonly, nonatomic) BOOL enableTextNonContiguousLayout;
@property (readonly, nonatomic) BOOL enableImageDownsampling;
@property (readonly, nonatomic) BOOL enableNewImage;
@property (readonly, nonatomic) BOOL trailUseNewImage;
@property (readonly, nonatomic) long long logBoxImageSizeWarningThreshold;
@property (readonly, nonatomic) BOOL enableTextLayoutCache;
@property (readonly, nonatomic) BOOL enableExposureWhenReload;

- (void)setEnableEventThrough:(BOOL)a0;
- (BOOL)isDev;
- (void)onGestureRecognizedByUI:(id)a0;
- (void)setUIConfig:(id)a0;
- (void)setEnableTextRefactor:(BOOL)a0;
- (void)didReceiveResourceError:(id)a0 withSource:(id)a1 type:(id)a2;
- (void)setEnableTextNonContiguousLayout:(BOOL)a0;
- (void)setTargetSdkVersion:(id)a0;
- (void)reportLynxError:(id)a0;
- (id)getLynxRuntimeId;
- (void)onGestureRecognized;
- (void)resumeExposure;
- (void)didReceiveResourceError:(id)a0;
- (void)didReceiveException:(id)a0 withMessage:(id)a1 forUI:(id)a2;
- (void)stopExposure;
- (void)setEnableNewClipMode:(BOOL)a0;
- (void)setEnableTextLayoutCache:(BOOL)a0;
- (BOOL)isTouchMoving;
- (void)setEnableNewGesture:(BOOL)a0;
- (void)onPropsChangedByUI:(id)a0;
- (void)addUIToExposedMap:(id)a0;
- (void)removeUIFromExposedMap:(id)a0;
- (void)addUIToExposedMap:(id)a0 withUniqueIdentifier:(id)a1 extraData:(id)a2 useOptions:(id)a3;
- (void)removeUIFromExposedMap:(id)a0 withUniqueIdentifier:(id)a1;
- (void)setDefaultOverflowVisible:(BOOL)a0;
- (void)setEnableTextOverflow:(BOOL)a0;
- (void)setDefaultImplicitAnimation:(BOOL)a0;
- (void)setEnableEventRefactor:(BOOL)a0;
- (void)setEnableA11yIDMutationObserver:(BOOL)a0;
- (void)setEnableBackgroundShapeLayer:(BOOL)a0;
- (void)setEnableExposureUIMargin:(BOOL)a0;
- (void)setEnableTextLanguageAlignment:(BOOL)a0;
- (void)setEnableXTextLayoutReused:(BOOL)a0;
- (void)setEnableFiberArch:(BOOL)a0;
- (void)setCSSAlignWithLegacyW3c:(BOOL)a0;
- (void)setEnableTextLayerRender:(BOOL)a0;
- (void)setEnableImageDownsampling:(BOOL)a0;
- (void)setEnableNewImage:(BOOL)a0;
- (void)setTrailUseNewImage:(BOOL)a0;
- (void)setLogBoxImageSizeWarningThreshold:(long long)a0;
- (void)setEnableTextGradientOpt:(BOOL)a0;
- (void)setEnableExposureWhenReload:(BOOL)a0;
- (id)initWithScreenMetrics:(id)a0;
- (void)updateScreenSize:(struct CGSize { double x0; double x1; })a0;
- (id)getGenericResourceFetcher;
- (void)removeUIFromIntersectionManager:(id)a0;
- (void)findShadowNodeAndRunTask:(long long)a0 task:(id /* block */)a1;
- (void)mergeKeyframesWithLynxKeyframes:(id)a0 forKey:(id)a1;
- (void)removeKeyframeWithRemovedName:(id)a0;
- (void).cxx_destruct;
- (int)instanceId;
- (void)reportError:(id)a0;
- (void)setRootView:(id)a0;

@end
