@class LynxComponentScopeRegistry, UIView, LynxRootUI, LynxTextRenderManager, NSMutableDictionary, NSMutableSet, NSMutableArray, LynxUIContext, LynxFontFaceContext, LynxGestureArenaManager;
@protocol LynxBaseInspectorOwner, LUIBodyView;

@interface LynxUIOwner : NSObject {
    BOOL _enableDetailLog;
    long long _embeddedMode;
}

@property (retain, nonatomic) LynxRootUI *rootUI;
@property (nonatomic) struct CGSize { double width; double height; } oldRootSize;
@property (nonatomic) BOOL hasRootAttached;
@property (nonatomic) BOOL enableNewGesture;
@property (weak, nonatomic) UIView<LUIBodyView> *containerView;
@property (retain, nonatomic) NSMutableDictionary *nameLynxUIMap;
@property (retain, nonatomic) NSMutableDictionary *uiHolder;
@property (retain, nonatomic) NSMutableArray *a11yMutationList;
@property (retain, nonatomic) NSMutableArray *foregroundListeners;
@property (retain, nonatomic) NSMutableDictionary *componentIdToUiIdHolder;
@property (retain, nonatomic) NSMutableSet *uisThatHasNewLayout;
@property (retain, nonatomic) NSMutableSet *uisThatHasOperations;
@property (retain, nonatomic) LynxFontFaceContext *fontFaceContext;
@property (retain, nonatomic) LynxComponentScopeRegistry *componentRegistry;
@property (retain, nonatomic) NSMutableSet *componentSet;
@property (retain, nonatomic) NSMutableDictionary *a11yIDHolder;
@property (readonly, nonatomic) LynxUIContext *uiContext;
@property (readonly, nonatomic) id<LynxBaseInspectorOwner> baseInspectOwner;
@property (retain, nonatomic) LynxGestureArenaManager *gestureArenaManager;
@property (copy, nonatomic) id /* block */ attachLynxPageUICallback;
@property (readonly, nonatomic) LynxTextRenderManager *textRenderManager;

- (id)uiWithName:(id)a0;
- (id)uiWithIdSelector:(id)a0;
- (void)onEnterBackground;
- (void)onEnterForeground;
- (long long)getThreadStrategyForRender;
- (void)resumeRootLayoutAnimation;
- (void)pauseRootLayoutAnimation;
- (void)insertNode:(long long)a0 toParent:(long long)a1 atIndex:(long long)a2;
- (void)setA11yFilter:(id)a0;
- (void)attachContainerView:(id)a0;
- (id)getComponentRegistry;
- (id)findUIBySign:(long long)a0;
- (id)getMemoryUsage;
- (void)invokeUIMethodForSelectorQuery:(id)a0 params:(id)a1 callback:(id /* block */)a2 toNode:(int)a3;
- (id)viewsWithA11yID:(id)a0;
- (id)findUIByComponentId:(id)a0;
- (id)findUIByIdSelectorInParent:(id)a0 child:(id)a1;
- (id)findUIByIdSelector:(id)a0 withinUI:(id)a1;
- (void)invokeUIMethod:(id)a0 params:(id)a1 callback:(id /* block */)a2 fromRoot:(id)a3 toNodes:(id)a4;
- (id)a11yFilter;
- (void)lynxAccessibilityElementDidBecomeFocused:(id)a0;
- (BOOL)checkNestedAccessibilityElements:(id)a0;
- (void)addA11yMutation:(id)a0 sign:(id)a1 a11yID:(id)a2 toArray:(id)a3;
- (void)addA11yPropsMutation:(id)a0 sign:(id)a1 a11yID:(id)a2 toArray:(id)a3;
- (void)flushMutations:(id)a0 withBodyView:(id)a1;
- (void)listenAccessibilityFocused;
- (unsigned char)isLayoutInElementModeOn;
- (id)initWithContainerView:(id)a0 componentRegistry:(id)a1 screenMetrics:(id)a2 errorHandler:(id)a3 uiConfig:(id)a4 embeddedMode:(long long)a5;
- (id)uiWithA11yID:(id)a0;
- (id)findUIByRefId:(id)a0 withinUI:(id)a1;
- (id)createLynxUIWithTagName:(id)a0 props:(id)a1;
- (void)updateEventWithUI:(id)a0 eventSet:(id)a1 lepusEventSet:(id)a2 gestureDetectorSet:(id)a3;
- (void)componentStatistic:(id)a0;
- (void)updateComponentIdToUiIdMapIfNeedWithSign:(long long)a0 tagName:(id)a1 props:(id)a2;
- (void)updatePropsWithUI:(id)a0 props:(id)a1 isCreateUI:(BOOL)a2;
- (void)registerForegroundListener:(id)a0;
- (void)markHasUIOperationsBottomUp:(id)a0;
- (void)markHasUIOperations:(id)a0;
- (void)addLynxUIToNameLynxUIMap:(id)a0;
- (id)createAndAttachRootUI;
- (id)createUIWithClass:(Class)a0 supportedState:(long long)a1 onMainThread:(BOOL)a2;
- (id)createUIInnerWithSign:(long long)a0 tagName:(id)a1 clazz:(Class)a2 supportedState:(long long)a3 onMainThread:(BOOL)a4 eventSet:(id)a5 lepusEventSet:(id)a6 props:(id)a7 nodeIndex:(unsigned int)a8 gestureDetectorSet:(id)a9;
- (void)processUIOnMainThread:(id)a0 withSign:(long long)a1 tagName:(id)a2 props:(id)a3;
- (BOOL)observeA11yMutations;
- (void)recordNodeThatNeedLayoutBottomUp:(id)a0;
- (void)removeUIFromHolder:(id)a0;
- (void)removeUIFromHolderRecursively:(id)a0;
- (void)removeLynxUIFromNameLynxUIMap:(id)a0;
- (void)unRegisterForegroundListener:(id)a0;
- (void)updateUI:(long long)a0 layoutLeft:(double)a1 top:(double)a2 width:(double)a3 height:(double)a4 padding:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a5 border:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a6 margin:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a7 sticky:(id)a8;
- (void)onNodeRemovedRecursively:(id)a0;
- (void)resetGestureArenaInUIThread;
- (void)releaseUI;
- (void)recursivelyRebuildViewHierarchyAndApplyLayout:(id)a0;
- (void)reattachAllUIManagedLayers;
- (id)initWithContainerView:(id)a0 componentRegistry:(id)a1 screenMetrics:(id)a2 errorHandler:(id)a3 uiConfig:(id)a4;
- (id)initWithContainerView:(id)a0 componentRegistry:(id)a1 screenMetrics:(id)a2;
- (BOOL)isTransformProps:(id)a0;
- (void)createUIWithSign:(long long)a0 tagName:(id)a1 eventSet:(id)a2 lepusEventSet:(id)a3 props:(id)a4 nodeIndex:(unsigned int)a5 gestureDetectorSet:(id)a6;
- (void)createUISyncWithSign:(long long)a0 tagName:(id)a1 clazz:(Class)a2 supportedState:(long long)a3 eventSet:(id)a4 lepusEventSet:(id)a5 props:(id)a6 nodeIndex:(unsigned int)a7 gestureDetectorSet:(id)a8;
- (id)createUIAsyncWithSign:(long long)a0 tagName:(id)a1 clazz:(Class)a2 supportedState:(long long)a3 eventSet:(id)a4 lepusEventSet:(id)a5 props:(id)a6 nodeIndex:(unsigned int)a7 gestureDetectorSet:(id)a8;
- (Class)getTargetClass:(id)a0 props:(id)a1 supportedState:(long long *)a2;
- (BOOL)needCreateUIAsync:(id)a0;
- (BOOL)needProcessDirection:(id)a0;
- (void)updateUIWithSign:(long long)a0 props:(id)a1 eventSet:(id)a2 lepusEventSet:(id)a3 gestureDetectorSet:(id)a4;
- (void)recycleNode:(long long)a0;
- (void)updateUI:(long long)a0 layoutLeft:(double)a1 top:(double)a2 width:(double)a3 height:(double)a4 padding:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a5 border:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a6;
- (void)willContainerViewMoveToWindow:(id)a0;
- (void)onReceiveUIOperation:(id)a0 onUI:(long long)a1;
- (void)finishLayoutOperation:(long long)a0 componentID:(long long)a1;
- (void)layoutDidFinish;
- (void)onNodeReady:(long long)a0;
- (void)onNodeRemoved:(long long)a0;
- (void)onNodeReload:(long long)a0;
- (void)updateAnimationKeyframes:(id)a0;
- (void)updateFontFaceWithDictionary:(id)a0;
- (id)weakLynxUIWithName:(id)a0;
- (long long)getTagInfo:(id)a0;
- (void)updateScrollInfo:(long long)a0 estimatedOffset:(float)a1 smooth:(BOOL)a2 scrolling:(BOOL)a3;
- (void)insertListComponent:(long long)a0 componentSign:(long long)a1;
- (void)removeListComponent:(long long)a0 componentSign:(long long)a1;
- (void)updateContentOffsetForListContainer:(long long)a0 contentSize:(float)a1 deltaX:(float)a2 deltaY:(float)a3;
- (void)listWillReuseNode:(long long)a0 withItemKey:(id)a1;
- (void)listCellWillAppear:(long long)a0 withItemKey:(id)a1;
- (void)ListCellDisappear:(long long)a0 exist:(BOOL)a1 withItemKey:(id)a2;
- (void)initNewGestureInUIThread:(BOOL)a0;
- (long long)getRootSign;
- (void)setFrameAppBundle:(id)a0 withTag:(long long)a1;
- (void)detachAllUIViews;
- (void)rebuildAllUIViewsAndHierarchy;
- (void).cxx_destruct;
- (void)detachNode:(long long)a0;
- (void)didReceiveMemoryWarning;
- (void)resumeAnimation;
- (void)reset;
- (void)dealloc;
- (void)resetAnimation;
- (void)restartAnimation;
- (void)didMoveToWindow:(BOOL)a0;

@end
