@class UIView, NSString, NSTimer, POIMediaPlayerAlbumProgressContainerView, POIMediaPlayerAlbumCollectionView, POIMediaListPageContext, NSMutableDictionary, POIMediaPlayerModel;
@protocol AWEUILoadingViewProtocol, POIMediaAlbumPlayerDelegate, IESVideoPlayerProtocol, POIMediaPlayerViewDelegate;

@interface POIMediaPlayerView : UIView <IESVideoPlayerDelegate, POIMediaPlayerAlbumProgressContainerViewDelegate, UIGestureRecognizerDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, POIMediaAlbumControllerProtocol, POIMediaPlayerViewDelegate, POIMediaPlayerControllerProtocol>

@property (retain, nonatomic) UIView<AWEUILoadingViewProtocol> *loadingView;
@property (nonatomic) long long currentPlayState;
@property (retain, nonatomic) POIMediaPlayerModel *model;
@property (retain, nonatomic) POIMediaPlayerAlbumCollectionView *collectionView;
@property (retain, nonatomic) POIMediaPlayerAlbumProgressContainerView *progressView;
@property (retain, nonatomic) id<IESVideoPlayerProtocol> playerWrapper;
@property (retain, nonatomic) UIView *playerView;
@property (nonatomic) long long currentIndex;
@property (nonatomic) BOOL isScrolling;
@property (retain, nonatomic) NSTimer *scrollTimer;
@property (retain, nonatomic) NSTimer *progressTimer;
@property (nonatomic) double progressValue;
@property (nonatomic) BOOL isAlbumReadyForDisplay;
@property (readonly, nonatomic) unsigned long long mediaType;
@property (weak, nonatomic) id<POIMediaPlayerViewDelegate, POIMediaAlbumPlayerDelegate> delegate;
@property (nonatomic) BOOL mute;
@property (nonatomic) long long playbackAction;
@property (nonatomic) struct CGSize { double width; double height; } preferredPlayerSize;
@property (weak, nonatomic) POIMediaListPageContext *context;
@property (nonatomic) BOOL isDisturbPlay;
@property (copy, nonatomic) NSString *unique_tag;
@property (retain, nonatomic) NSMutableDictionary *trackParams;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)player:(id)a0 playbackFailedWithError:(id)a1;
- (void)playerDidReadyForDisplay:(id)a0;
- (void)player:(id)a0 didChangePlaybackStateWithAction:(long long)a1;
- (void)player:(id)a0 didChangeStallState:(long long)a1;
- (void)player:(id)a0 avOutsyncStateDidChangedWithType:(unsigned long long)a1 extraInfo:(id)a2;
- (void)player:(id)a0 playbackFailedForURL:(id)a1 error:(id)a2;
- (void)player:(id)a0 didChangeStallState:(long long)a1 actionType:(long long)a2 reason:(unsigned long long)a3;
- (void)player:(id)a0 didFinishVideoDataDownloadForURL:(id)a1;
- (void)player:(id)a0 noVideoDataToDownloadForURL:(id)a1;
- (void)player:(id)a0 didFetchVideoModel:(id)a1;
- (void)addPeriodicTimeObserver;
- (void)resetLoadingView;
- (id)createProgressView;
- (void)addVideoPlayer;
- (void)albumScrollToIndex:(unsigned long long)a0;
- (void)configWithModel:(id)a0 preferredSize:(struct CGSize { double x0; double x1; })a1;
- (void)didTapLeftEnd;
- (void)didTapRightEnd;
- (void)addMusicPlayer;
- (void)addPagerTimer;
- (void)addProgressTimer;
- (void)updateAlbumProgress;
- (id)createPlayerWrapper:(id)a0;
- (void)albumScrollToIndex:(unsigned long long)a0 isAuto:(BOOL)a1;
- (void)scrollToIndex:(long long)a0 animated:(BOOL)a1 isAuto:(BOOL)a2;
- (void)scrollToIndex:(unsigned long long)a0 isAuto:(BOOL)a1;
- (void)previousCell;
- (void)resetOffset;
- (BOOL)shouldAlbumPlayerHandlePanGesture:(id)a0;
- (void)playerWillLoopPlaying:(id)a0;
- (void).cxx_destruct;
- (BOOL)play;
- (BOOL)pause;
- (void)resetTimer;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 sizeForItemAtIndexPath:(id)a2;
- (void)prepareForReuse;
- (BOOL)stop;
- (id)collectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (long long)collectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (void)scrollViewWillEndDragging:(id)a0 withVelocity:(struct CGPoint { double x0; double x1; })a1 targetContentOffset:(inout struct CGPoint { double x0; double x1; } *)a2;
- (long long)numberOfSectionsInCollectionView:(id)a0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)layoutSubviews;
- (void)dealloc;
- (void)showLoadingView;
- (void)willDisplay;
- (void)seekToTime:(double)a0 completion:(id /* block */)a1;
- (void)nextCell;

@end
