@class RxPromise, RTVCompactStateMachine, RTVXRDegradeService, UIViewController, RTVEffectGameTracker, UIButton, UIView, RTVEffectGameContentLoadingView, NSString, RTVVoipToastHandler, UITextField, RTVXRBaseBusinessHandler, NSArray, RTVEffectGameDownloadTask;
@protocol RTVInteractionContentDelegate, RTVEffectGameContentBEFWrapper, RTVCustomPopoverSheetControllerInterface, RTVInteractionControlViewController, RTVEffectGameVolumeSettingControllerInterface, RTVEffectGameManager, RTVXRRoomSessionControllerInterface, RTVXRInteractionController, RxInjector, RTVAuthCheckerInterface, RTVTopViewControllerInterface, RTVXRCaptureController, RTVXRControllerInjector, RTVInteractionCastService, RTVUserProfileManagerInterface, RTVVoipResourceFetcherInterface, RTVInteractionConfigureManagerInterface, RTVXRAudioSessionCoordinator, RTVEffectGameContentCameraSheetViewController, RTVEffectGameMonitor, RTVReachabilityManagerInterface, RTVEffectGameSession, RTVEffectGameListController, RTVPipelineInterface;

@interface RTVEffectGameContentViewController : UIViewController <RTVEffectGameContentViewController, RTVInteractionControlViewControllerObserver, RTVEffectGameSessionObserver, RTVEffectGameContentBEFWrapperDelegate, RTVEffectGameListControllerDelegate, RTVEffectGameContentCameraSheetViewControllerDelegate, UITextFieldDelegate, RTVReachabilityManagerDelegate, RTVXRRoomSessionControllerObserver, RTVCompactStateMachineDelegate, RTVInteractionCastServiceContentDelegate, RTVInteractionControlViewControllerDelegate>

@property (readonly, weak, nonatomic) id<RxInjector> injector;
@property (weak, nonatomic) id<RTVPipelineInterface> pipeline;
@property (readonly, weak, nonatomic) id<RTVXRControllerInjector> controllerInjector;
@property (readonly, weak, nonatomic) id<RTVInteractionControlViewController> controlViewController;
@property (readonly, weak, nonatomic) RTVXRBaseBusinessHandler<RTVXRRoomSessionControllerInterface> *roomController;
@property (readonly, weak, nonatomic) id<RTVEffectGameVolumeSettingControllerInterface> volumeSettingController;
@property (readonly, weak, nonatomic) id<RTVXRInteractionController> xrinteractionController;
@property (readonly, nonatomic) id<RTVInteractionCastService> interactionCastService;
@property (readonly, nonatomic) id<RTVInteractionConfigureManagerInterface> interactionConfigureManager;
@property (readonly, nonatomic) id<RTVEffectGameSession> session;
@property (readonly, nonatomic) id<RTVEffectGameMonitor> monitor;
@property (readonly, nonatomic) RTVCompactStateMachine *stateMachine;
@property (readonly, nonatomic) id<RTVEffectGameManager> effectGameManager;
@property (readonly, nonatomic) id<RTVUserProfileManagerInterface> profileManager;
@property (readonly, nonatomic) id<RTVEffectGameListController> gameListController;
@property (readonly, nonatomic) id<RTVEffectGameContentCameraSheetViewController> cameraSheet;
@property (readonly, nonatomic) id<RTVReachabilityManagerInterface> reachabilityManager;
@property (readonly, nonatomic) id<RTVTopViewControllerInterface> topVCGetter;
@property (readonly, nonatomic) id<RTVAuthCheckerInterface> authChecker;
@property (readonly, nonatomic) RTVXRDegradeService *degradeService;
@property (readonly, nonatomic) UIView<RTVEffectGameContentBEFWrapper> *befWrapper;
@property (readonly, nonatomic) RTVEffectGameContentLoadingView *loadingView;
@property (readonly, nonatomic) RTVEffectGameDownloadTask *downloadTask;
@property (readonly, nonatomic) UIButton *resignButton;
@property (readonly, nonatomic) UITextField *inputField;
@property (readonly, nonatomic) RTVVoipToastHandler *toastHandler;
@property (readonly, nonatomic) RxPromise *hideLoadingViewPromise;
@property (readonly, nonatomic) UIViewController *topViewController;
@property (readonly, nonatomic) id<RTVXRAudioSessionCoordinator> audioSessionCoordinator;
@property (readonly, copy, nonatomic) NSString *currentProfileIMID;
@property (copy, nonatomic) NSArray *listViewConstraints;
@property (readonly, weak, nonatomic) id<RTVXRCaptureController> captureController;
@property (readonly, nonatomic) RTVEffectGameTracker *gameTracker;
@property (readonly, nonatomic) id<RTVInteractionConfigureManagerInterface> configureManager;
@property (readonly, nonatomic) id<RTVCustomPopoverSheetControllerInterface> popoverSheetController;
@property (readonly, nonatomic) id<RTVVoipResourceFetcherInterface> resourceFetcher;
@property (nonatomic) double gameStartTime;
@property (nonatomic) BOOL cameraSheetHasShown;
@property (nonatomic) BOOL active;
@property (nonatomic) BOOL hadShowMicOnToast;
@property (weak, nonatomic) id<RTVInteractionContentDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)rtv_awakeFromControllerInjector;
- (void)__createComponents;
- (void)__layoutComponents;
- (void)__showToast:(id)a0;
- (void)renderBusinessHandler:(id)a0 context:(id)a1;
- (void)__configComponents;
- (void)renderContext:(id)a0;
- (void)notifyChangeActive:(BOOL)a0;
- (void)notifyDidChangeActive:(BOOL)a0;
- (void)notifyChangeToNarrow:(BOOL)a0;
- (void)notifyDidChangeToNarrow:(BOOL)a0;
- (void)dismissContentController;
- (double)preferredBottomOffset;
- (void)effectGameListController:(id)a0 selectGame:(id)a1;
- (BOOL)shouldCastFeedType:(long long)a0;
- (void)interactionControlViewController:(id)a0 actionTypeTriggered:(unsigned long long)a1;
- (void)rtvSession:(id)a0 stateMachineDidChangeTo:(long long)a1 fromState:(long long)a2;
- (void)rtvSession:(id)a0 contextKeyPathChange:(id)a1 fromValue:(id)a2 toValue:(id)a3;
- (void)rtvSession:(id)a0 participatorsDidChange:(id)a1 oldParticipators:(id)a2;
- (void)__keyboardWillShow:(id)a0;
- (void)__keyboardWillHide:(id)a0;
- (void)reachabilityManager:(id)a0 reachableStatusChangeTo:(BOOL)a1;
- (void)stateMachine:(id)a0 didTransferFrom:(id)a1 to:(id)a2 transition:(id)a3;
- (void)stateMachine:(id)a0 didFireEvent:(id)a1 result:(BOOL)a2 transition:(id)a3;
- (void)befWrapper:(id)a0 gameStartModel:(id)a1;
- (void)befWrapperGameEnd:(id)a0;
- (void)befWrapperQuitGame:(id)a0;
- (void)befWrapperChangeGame:(id)a0;
- (void)befWrapper:(id)a0 showInput:(BOOL)a1;
- (void)gameContentCameraSheetOpenCamera:(id)a0;
- (void)__releaseBEFWrapper;
- (void)__showMicUnmutedToastIfNeeded;
- (void)__tryToAddGameList:(id)a0;
- (void)__addConfigAndLayoutGameListVC:(id)a0;
- (void)__createInteractionCastService;
- (void)__tapResignButton;
- (void)__setLoadingViewHidden:(BOOL)a0;
- (void)__showGameListWithAnimation:(BOOL)a0 showReason:(id)a1;
- (double)__currentTimeInterval;
- (void)__showNeedCameraAlertWithGameModelIfNeeded:(id)a0;
- (void)__updateLayoutWithKeybordHeight:(double)a0;
- (void)__prepareBEFWrapper;
- (id)__fireGameFinishEvent:(id)a0;
- (id)__loadGameWithFilePath:(id)a0;
- (BOOL)__needHideLoadingViewInstantly;
- (id)__joinGameWithLoadValue:(id)a0;
- (void)__refreshControlViewContents;
- (id)__reportGameWithJoinResult:(id)a0;
- (id)__waitGameStartWithReportValue:(id)a0;
- (void)__gameStartWithModel:(id)a0;
- (void)__removeGameList;
- (void)__downloadEventFired;
- (void)__gameLoadEventFired:(id)a0;
- (void)__gameWaitEventFired;
- (void)__gamePlayEventFired:(id)a0;
- (void)__dismissGameListWithReason:(id)a0;
- (void)__finishEffectGameWithReason:(unsigned long long)a0;
- (void)__closeBtnTappedV2WithControlViewController:(id)a0;
- (void)__closeBtnTappedV1;
- (void)__realFinishEffectGameWithReason:(unsigned long long)a0 reasonDetail:(id)a1;
- (void)__showBackDialogWithBackToVoip:(BOOL)a0;
- (void)__showExitPopConfirmWithContext:(id)a0;
- (void)__enterCoplayMiniWithEventType:(id)a0;
- (void)__backBtnTapped;
- (void)__closeBtnTappedWithControlViewController:(id)a0;
- (void)__showVolumeSettingController;
- (void)__exitInteractionWithReason:(long long)a0;
- (id)__onCallParticipators:(id)a0;
- (void)__reconnectGameIfNeeded;
- (void)__foldButtonTap;
- (void)effectGameSession:(id)a0 changeGame:(id)a1;
- (void)effectGameSession:(id)a0 willFinishWithReason:(unsigned long long)a1;
- (id)interactionControlViewControllerTopRightButton;
- (void).cxx_destruct;
- (long long)preferredStatusBarStyle;
- (BOOL)textFieldShouldReturn:(id)a0;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)a0;
- (long long)containerType;

@end
