@class RTVFeedCommand, NSString, RTVXRBaseBusinessHandler, RTVFeedScopeController, RTVFeedTracker;
@protocol RTVSettingsManager, RTVFeedManagerInterface, RTVFeedMonitorInterface, RTVInteractionConfigurator, RTVMultipleDelegateInterface, RTVXRRoomSessionControllerInterface, RTVStateRecorder, RTVXRCaptureController, RTVFeedQosMonitorInterface, RTVFeedNotifyDispatcherInterface, RTVXRInteractionController, RTVXRControllerInjector, RTVUserProfileManagerInterface, RTVFeedHotReminderControllerInterface, RTVXRRoomClockController, RTVVoipContextManagerInterface, RxInjector, RTVFeedObserver, RTVXRRoomMessageSender;

@interface RTVFeedController : NSObject <RTVFeedSessionObsever, RTVFeedNotifyHandlerProtocol, RTVXRRoomMessageSenderObserver, RTVXRRoomMessageSenderDelegate, RTVXRRoomSessionControllerObserver, RTVFeedControllerInterface>

@property (readonly, weak, nonatomic) id<RxInjector> injector;
@property (readonly, weak, nonatomic) id<RTVXRControllerInjector> controllerInjector;
@property (weak, nonatomic) RTVXRBaseBusinessHandler<RTVXRRoomSessionControllerInterface> *roomController;
@property (weak, nonatomic) id<RTVXRRoomMessageSender> engineMessageSender;
@property (weak, nonatomic) id<RTVXRRoomClockController> roomClockController;
@property (weak, nonatomic) id<RTVXRCaptureController> captureController;
@property (readonly, weak, nonatomic) id<RTVXRInteractionController> xrInteractionController;
@property (readonly, nonatomic) id<RTVVoipContextManagerInterface> voipContextManager;
@property (readonly, nonatomic) id<RTVUserProfileManagerInterface> profileManager;
@property (readonly, nonatomic) id<RTVSettingsManager> settingManager;
@property (retain, nonatomic) RTVFeedScopeController *feedScopeController;
@property (readonly, nonatomic) id<RTVMultipleDelegateInterface, RTVFeedObserver> observers;
@property (readonly, weak, nonatomic) id<RTVStateRecorder> stateRecorder;
@property (readonly, weak, nonatomic) id<RTVFeedManagerInterface> feedManager;
@property (readonly, weak, nonatomic) id<RTVFeedNotifyDispatcherInterface> feedNotifyDispatcher;
@property (readonly, nonatomic) id<RTVFeedQosMonitorInterface> feedQosMonitor;
@property (nonatomic) long long lastSyncCmdVersion;
@property (retain) RTVFeedCommand *lastFeedCommand;
@property (readonly, nonatomic) RTVFeedTracker *tracker;
@property (readonly, weak, nonatomic) id<RTVFeedMonitorInterface> monitor;
@property (nonatomic) BOOL previousNetworkConnected;
@property (readonly, weak, nonatomic) id<RTVFeedHotReminderControllerInterface> hotReminder;
@property (nonatomic) BOOL isFeedSharing;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) id<RTVInteractionConfigurator> interactionConfigurator;

- (void)rxAwakeFromPropertyInjection;
- (void)rtv_awakeFromControllerInjector;
- (void)__addObservers;
- (void)renderBusinessHandler:(id)a0 context:(id)a1;
- (BOOL)needPreResumeInteraction;
- (id)scopeInjector;
- (id)interactionSession;
- (id)interactiontTracker;
- (id)feedSession;
- (void)rtvSession:(id)a0 participatorsDidChange:(id)a1 oldParticipators:(id)a2;
- (void)feedSession:(id)a0 shareWillFinishWithReason:(long long)a1;
- (void)messageSender:(id)a0 didReceiveMessage:(id)a1;
- (void)__appDidBecomeActive;
- (BOOL)isFromInteractionTypeChange;
- (id)currentOwnerIdentifier;
- (void)configInterationViewController:(id)a0;
- (id)joinWithModel:(id)a0 context:(id)a1;
- (id)invokeWithModel:(id)a0 context:(id)a1;
- (BOOL)enterInteractionWithModel:(id)a0 context:(id)a1;
- (id)stopInteractionWithReason:(unsigned long long)a0;
- (id)createInterationViewController;
- (id)createNarrowInterationViewController;
- (void)feedSessionShareDidFinish:(id)a0 reason:(long long)a1;
- (void)feedSession:(id)a0 didSendCommand:(id)a1;
- (void)__connectionChanged;
- (long long)__localFeedShareRoomFeature;
- (void)__createSessionWithModel:(id)a0 context:(id)a1;
- (void)__handleShareModelChangeFrom:(id)a0 toModel:(id)a1;
- (id)__syncFeedShareFromServer;
- (void)__endFeedQosMonitorForShareFinish:(long long)a0;
- (id)__handleReceiveLargerVersion;
- (void)__didReceiveCommandFromFeedSignal:(id)a0;
- (void)__updateLocalFeedShareInfoWithModel:(id)a0 source:(unsigned long long)a1;
- (BOOL)__checkMessageIsCurrentFeedShare:(id)a0;
- (id)__pullFeedShareFromServer;
- (void)didReceiveMessage:(id)a0 ofMethod:(long long)a1;
- (void).cxx_destruct;
- (void)addObserver:(id)a0;
- (BOOL)isInteracting;
- (id)interactionType;
- (void)removeObserver:(id)a0;
- (void)dealloc;
- (id)currentTimestamp;
- (id)currentFeedSession;

@end
