@class TTAVPlayer, UIView, TTPlayerViewExtraViews, APOutputView;
@protocol TTPlayerViewDelegate, AVViewBackgroundProtocol;

@interface TTPlayerView : UIView {
    TTAVPlayer *_ttavplayer;
    struct RefPtr<com::ss::ttm::APWindow> { struct APWindow *mValue; } _window;
    UIView<AVViewBackgroundProtocol> *_view;
    APOutputView *_outputView;
    struct CGSize { double width; double height; } _previousValidVideoSize;
    struct CGSize { double width; double height; } _presetValidVideoSize;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _cropAreaFrame;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _normalizeCropArea;
    BOOL _preferSpdl4HDR;
    BOOL _playerViewHasSet;
    BOOL _useNormalizeCropArea;
    long long _normalizeCropType;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _normalizeCropAreaSixDoFLite;
    BOOL _dynMtTexSize;
    BOOL _shouldLogMore;
    BOOL _moveViewOpToMain;
    int _curVideoRotation;
    BOOL _newWindowManger;
    long long _specialFunType;
    TTPlayerViewExtraViews *_extraView;
    float _scale;
    BOOL _metalViewOpaque;
}

@property (retain, nonatomic) TTAVPlayer *player;
@property (nonatomic) long long alignMode;
@property (nonatomic) double alignRatio;
@property (nonatomic) long long scaleType;
@property (nonatomic) long long renderType;
@property (nonatomic) long long lastRenderType;
@property (nonatomic) long long rotateType;
@property (nonatomic) long long innerViewRotateType;
@property (nonatomic) BOOL memoryOptimizeEnabled;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } cropAreaFrame;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } normalizeCropArea;
@property (nonatomic) BOOL useNormalizeCropArea;
@property (nonatomic) long long normalizeCropType;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } normalizeCropAreaSixDoFLite;
@property (readonly, nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } videoAreaFrame;
@property (nonatomic, getter=isSupportPictureInPictureMode) BOOL supportPictureInPictureMode;
@property (weak, nonatomic) id<TTPlayerViewDelegate> playerViewDelegate;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } dualSecondViewclipCropArea;

+ (id)playerViewWithPlayer:(id)a0 type:(long long)a1;
+ (id)playerViewWithPlayer:(id)a0;
+ (id)playerViewWithPlayer:(id)a0 type:(long long)a1 specialFunctionType:(long long)a2;

- (struct __CVBuffer { } *)copyPixelBuffer;
- (void)setRenderRotation:(int)a0;
- (id)getExtraViewForViewType:(long long)a0;
- (void)setOptionForKey:(long long)a0 value:(id)a1;
- (void)setPlayerViewSpecialFunctionType:(long long)a0;
- (long long)getPlayerViewSpecialFunctionType;
- (void)setRenderPaused:(BOOL)a0;
- (BOOL)needRemoveView:(id)a0;
- (void)setVideoWindowInPresetView;
- (void)updateVideoFrame;
- (long long)getWantRenderTypeForHDR:(void *)a0;
- (void)createOSView:(long long)a0;
- (void)_updateVideoFrame;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })scaledRectFrom:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 ratio:(double)a1 scaleType:(long long)a2;
- (void)setPresetViewSize:(id)a0;
- (void)releaseContents;
- (BOOL)OpenGLActivityIsActive;
- (void)updateRenderType:(long long)a0;
- (long long)toPlayerViewRenderType:(int)a0;
- (void)resetWhenGivebackToPool;
- (void)refreshParamWhenReuseFromPool;
- (double)getOSViewWidth;
- (double)getOSViewHeight;
- (void)checkIsVPDirectScreen:(BOOL)a0;
- (BOOL)getOSViewisVaild;
- (void)releaseWindow;
- (void)createNewWindow:(long long)a0;
- (void)updateForAlignMode:(long long)a0;
- (void)checkPictureInPictureMode;
- (BOOL)internalPlayerShouldStillKeepRunningGPUWhenInBackground;
- (void)configInternalPlayerShouldStillKeepRunningGPUWhenInBackgroundWithValue:(BOOL)a0;
- (void)activateAVView;
- (int)getScaleType;
- (id)getOsView;
- (struct CGSize { double x0; double x1; })getDrawableSize;
- (BOOL)renderPausedInActive;
- (void)applicationWillResignActive:(id)a0;
- (void).cxx_destruct;
- (void)didMoveToSuperview;
- (void)applicationDidBecomeActive:(id)a0;
- (void)setOpaque:(BOOL)a0;
- (id).cxx_construct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)applicationDidEnterBackground:(id)a0;
- (void)layoutSubviews;
- (void)dealloc;
- (void)didMoveToWindow;
- (void)setPlayerView:(id)a0;
- (void)setColorPrimaries:(int)a0;

@end
