@class UIView, NSString, TVLPlayableURL, TVLRetryer, NSDictionary, TVLDNSParser, NSMutableArray, TVLPlayer, TVLPlayerItem;
@protocol TVLPlayerControllerDelegate;

@interface TVLController : NSObject <TVLDNSParserDelegate, TVLPlayerController> {
    long long _frameDroppingTerminatedDTS;
    NSDictionary *_ipMappingTable;
    NSDictionary *_hostIpList;
}

@property (retain, nonatomic) TVLDNSParser *parser;
@property (retain, nonatomic) NSString *currentPlayURL;
@property (retain, nonatomic) NSString *videoFormat;
@property (retain, nonatomic) NSString *level;
@property (copy, nonatomic) NSString *parsedHostname;
@property (retain, nonatomic) NSMutableArray *availableParsedIPAddresses;
@property (nonatomic, getter=isCacheHitted) BOOL cacheHitted;
@property (copy, nonatomic) NSString *hostnameWhenErrorOrStall;
@property (copy, nonatomic) NSString *lastUsedIPAddress;
@property (nonatomic) BOOL isPrepared;
@property (nonatomic) BOOL hasShowedFirstFrame;
@property (nonatomic) BOOL hasTriedOriginalURL;
@property (nonatomic) BOOL callPlay;
@property (nonatomic) BOOL callPrepare;
@property (nonatomic) BOOL hasCallStop;
@property (retain, nonatomic) TVLPlayableURL *playableURL;
@property (nonatomic) unsigned long long imageLayoutType;
@property (retain, nonatomic) NSDictionary *optimumNodeInfo;
@property (retain, nonatomic) TVLRetryer *retryer;
@property (nonatomic) long long frameDroppingTerminatedDTS;
@property (nonatomic) long long retryMaximumTimesInStall;
@property (nonatomic) double retryMaximumDuration;
@property (nonatomic) double retryTimeIntervalInStall;
@property (nonatomic) double retryTimeIntervalInError;
@property (nonatomic) BOOL shouldStopRetry;
@property (retain, nonatomic) TVLPlayerItem *currentItem;
@property (retain, nonatomic) TVLPlayer *player;
@property (readonly, nonatomic) UIView *playerView;
@property (weak, nonatomic) id<TVLPlayerControllerDelegate> delegate;
@property (readonly, nonatomic) BOOL isPlaying;
@property (nonatomic) BOOL shouldUseLiveDNS;
@property (copy, nonatomic) id /* block */ optimumNodeInfoRequest;
@property (nonatomic, getter=isPreferredToHTTPDNS) BOOL preferredToHTTPDNS;
@property (nonatomic) BOOL shouldTryAllResolvedIPAddresses;
@property (retain, nonatomic) NSDictionary *ipMappingTable;
@property (retain, nonatomic) NSDictionary *extraRequestHeaderByUser;
@property (retain, nonatomic) NSDictionary *hostIpList;
@property (nonatomic) long long playerDebugState;
@property (nonatomic) BOOL shouldTryCachedAddresses;
@property (nonatomic) BOOL shouldCacheUrlIPAddressAfterStartRender;
@property (nonatomic) BOOL isStalling;
@property (nonatomic) BOOL enableLivePrePrepare;
@property (nonatomic) BOOL stopRetryWhenAudioRender;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)hookCacheOfHostIsHitted;
+ (void)hookPlayerDidStopStalling;
+ (void)hookPlayerDidStartStallingWithReason;
+ (void)hookUpdateOptimumNodeInfo;
+ (void)hookPrepareToPlay;
+ (void)hookRetryWithResetPlayer;
+ (void)hookStartRender;
+ (void)hookHostReplacement;
+ (void)hookRetryAvailableParsedUrl;
+ (void)hookRetryOriginalUrl;
+ (void)load;

- (id)initWithOwnPlayer:(BOOL)a0;
- (void)recieveError:(id)a0;
- (void)onStreamDryup:(id)a0;
- (void)loadStateChanged:(id)a0;
- (long long)getIntValueForKey:(int)a0;
- (float)getFloatValueForKey:(int)a0;
- (void)updateOptimumNodeInfo;
- (BOOL)isLocalPlayURL:(id)a0;
- (void)tvl_prepareToPlayURL:(id)a0 withHost:(id)a1 withGivenIp:(id)a2;
- (void)didFinishParsingHostname:(id)a0 withParesedAddresses:(id)a1 error:(id)a2;
- (id)tvl_IPAddressesForOptimumNode:(id)a0;
- (id)getPreNodeSelection:(id)a0;
- (void)cacheOfHost:(id)a0 isHitted:(BOOL)a1;
- (void)resetControllerStates;
- (void)reportToApplication:(id)a0;
- (void)reportErrorToDebug:(id)a0;
- (id)tvl_replaceHostnameOfPlayURL:(id)a0 withParsedHostname:(id)a1 parsedIPAddress:(id)a2;
- (void)tvl_prepareToPlayURL:(id)a0 withOptions:(id)a1 withGivenIp:(id)a2;
- (void)initLutFilterWhenNeeded;
- (id)parameterizedPlayURLWithURLAbsoluteString:(id)a0;
- (void)updatePlayeyWithDecryptedKey;
- (id)generateRtsUrl:(id)a0;
- (id)prepareLiveIOPlayUrl:(id)a0 withOptions:(id)a1 withGivenIp:(id)a2;
- (BOOL)prepareLiveIODemuxer;
- (void)tryNextURLWithError:(id)a0;
- (void)retryWithResetPlayerWithReason:(long long)a0 timeInterval:(double)a1 maximumTimes:(long long)a2 maximumDuration:(double)a3;
- (BOOL)shouldRetryWithReason:(long long)a0 times:(long long)a1 duration:(double)a2;
- (void)retryWithResetPlayer;
- (void)notifyStopToLiveIo;
- (void)retryAvailableParsedUrl:(id)a0 withGivenIp:(id)a1;
- (void)retryOriginalUrl;
- (BOOL)isControllerOfPlayer:(id)a0;
- (id)tvl_evaluatorSymbolForOptimumNode:(id)a0;
- (id)tvl_IPAddressForOptimumNode:(id)a0;
- (void)refetchLiveInfo;
- (id)tvl_hook_tvl_replaceHostnameOfPlayURL:(id)a0 withParsedHostname:(id)a1 parsedIPAddress:(id)a2;
- (void)tvl_hook_startRender;
- (void)tvl_hook_retryWithResetPlayer;
- (void)tvl_hook_updateOptimumNodeInfo;
- (void)tvl_hook_cacheOfHost:(id)a0 isHitted:(BOOL)a1;
- (void)tvl_hook_player:(id)a0 didStartStallingWithReason:(long long)a1;
- (void)tvl_hook_playerDidStopStalling:(id)a0;
- (void)tvl_hook_tvl_prepareToPlayURL:(id)a0 withOptions:(id)a1 withGivenIp:(id)a2;
- (void)configAutoTestScript;
- (void)tvl_hook_retryAvailableParsedUrl:(id)a0 withGivenIp:(id)a1;
- (void)tvl_hook_retryOriginalUrl;
- (void)parser:(id)a0 didCancelParsingHostname:(id)a1;
- (void)parser:(id)a0 didFinishParsingHostname:(id)a1 withParesedAddresses:(id)a2 error:(id)a3;
- (id)getStringValueForKey:(int)a0;
- (void)player:(id)a0 videoSizeDidChange:(struct CGSize { double x0; double x1; })a1;
- (void)onReceiveSeiMessage:(id)a0;
- (void)handleRenderStall:(id)a0;
- (void)startAudioRender;
- (void)startVideoRender;
- (void)onReadyToPlay:(id)a0 videoCodecID:(int)a1 audioCodecID:(int)a2;
- (void)player:(id)a0 playerItemStatusDidChange:(long long)a1;
- (void)playerDidStopStalling:(id)a0;
- (void)player:(id)a0 didStartStallingWithReason:(long long)a1;
- (void)close;
- (void).cxx_destruct;
- (void)play;
- (void)pause;
- (void)setMuted:(BOOL)a0;
- (void)close:(BOOL)a0;
- (void)stop;
- (void)updateProgress;
- (void)handleError:(id)a0;
- (void)prepare;
- (void)reset;
- (void)setValue:(int)a0 forKey:(int)a1;
- (void)resume;
- (int)getCurrentTime;
- (BOOL)isMuted;
- (void)prepareToPlay:(id)a0;
- (void)resetPlayer;
- (id)initWithPlayerType:(unsigned long long)a0;
- (void)takeScreenShot:(id /* block */)a0;
- (id)getIPAddress;

@end
