@class NSDate, NSString, NSURL, NSLock, TVLNodeOptimizeInfo, NSDictionary, TVLSEIChecker, TVLAbnormalStreamChecker, NSMutableArray, NSMutableDictionary;

@interface TVLPlayerItemAccessLogPullStreamEvent : TVLPlayerItemLogEvent <TVLItemEventsCollectProtocol> {
    NSMutableArray *_retryEvents;
    NSMutableArray *_stallEvents;
    NSMutableArray *_renderStallEvents;
    NSMutableArray *_errorEvents;
    NSMutableArray *_videoBitrateSwitchEvents;
    NSString *_spsppsInfo;
    NSDate *_startPreviewDate;
    long long _totalPlayTimePreview;
    NSLock *_logLock;
}

@property (retain, nonatomic) NSString *resolutionType;
@property (retain, nonatomic) NSURL *playURL;
@property (retain, nonatomic) NSDate *pullStreamStartDate;
@property (retain, nonatomic) NSDate *SDKDNSFinishedDate;
@property (retain, nonatomic) NSDate *playerDNSFinishedDate;
@property (retain, nonatomic) NSDate *TCPConnectedDate;
@property (retain, nonatomic) NSDate *TCPFirstPacketArrivedDate;
@property (retain, nonatomic) NSDate *firstVideoPacketArrivedDate;
@property (retain, nonatomic) NSDate *firstAudioPacketArrivedDate;
@property (retain, nonatomic) NSDate *firstVideoFrameArrivedDate;
@property (retain, nonatomic) NSDate *firstAudioFrameArrivedDate;
@property (retain, nonatomic) NSDate *firstVideoFrameToDecodeDate;
@property (retain, nonatomic) NSDate *firstAudioFrameToDecodeDate;
@property (retain, nonatomic) NSDate *firstVideoFrameDecodedDate;
@property (retain, nonatomic) NSDate *firstAudioFrameDecodedDate;
@property (retain, nonatomic) NSDate *firstAudioFrameRenderDate;
@property (retain, nonatomic) NSDate *firstFrameRenderedDate;
@property (retain, nonatomic) NSDate *videoDeviceOpenStartDate;
@property (retain, nonatomic) NSDate *videoDeviceOpenEndDate;
@property (retain, nonatomic) NSDate *audioDeviceOpenStartDate;
@property (retain, nonatomic) NSDate *audioDeviceOpenEndDate;
@property (retain, nonatomic) NSDate *videoDeviceWaitStartDate;
@property (retain, nonatomic) NSDate *videoDeviceWaitEndDate;
@property (readonly, nonatomic) long long firstAudioPacketDTS;
@property (nonatomic) long long latestAudioPacketDTS;
@property (readonly, nonatomic) long long firstRenderingAudioFrameDTS;
@property (nonatomic) long long latestRenderingAudioFrameDTS;
@property (nonatomic, getter=isDNSCacheHitted) BOOL DNSCacheHitted;
@property (copy, nonatomic) NSString *serverAddress;
@property (nonatomic, getter=isServerAddressFromPlayerCore) BOOL serverAddressFromPlayerCore;
@property (retain, nonatomic) NSDictionary *contextInfo;
@property (nonatomic) long long waitedTimeAfterFirstFrame;
@property (retain, nonatomic) TVLNodeOptimizeInfo *nodeOptimizeInfo;
@property (retain, nonatomic) NSDictionary *preRedirectInfo;
@property (retain, nonatomic) NSString *missOptimizeInfo;
@property (retain, nonatomic) NSDictionary *responseHeaders;
@property (nonatomic) unsigned long long downloadedDataSizeInBytes;
@property (nonatomic) unsigned long long playSizeInBytes;
@property (nonatomic) long long liveioHttpFlowSizeInBytes;
@property (nonatomic) long long liveioP2pFlowSizeInBytes;
@property (nonatomic) long long liveioP2pMobileSizeInBytes;
@property (nonatomic) long long liveioRtmFlowSizeInBytes;
@property (nonatomic) long long liveioHttpIOPlayTimeMs;
@property (nonatomic) long long liveioP2pIOPlayTimeMs;
@property (nonatomic) long long liveioRtmIOPlayTimeMs;
@property (nonatomic) long long liveioHttpPatchDtsSize;
@property (nonatomic) long long liveioHttpSubstreamSize;
@property (nonatomic) long long segementPlayedSizeStartInBytes;
@property (nonatomic) long long segementDownloadSizeStartInBytes;
@property (retain, nonatomic) TVLAbnormalStreamChecker *abnormalStreamChecker;
@property (retain, nonatomic) TVLSEIChecker *SEIChecker;
@property (nonatomic) long long currentChloCount;
@property (nonatomic) long long firstFrameChloCount;
@property (readonly, nonatomic) BOOL isFirstFrameViewed;
@property (retain, nonatomic) NSDate *prepareStartDate;
@property (retain, nonatomic) NSDate *prepareEndDate;
@property (retain, nonatomic) NSDate *prepareStartTsDate;
@property (retain, nonatomic) NSDate *prepareEndTsDate;
@property (retain, nonatomic) NSDictionary *metaData;
@property (nonatomic) long long socketRecvBufferSize;
@property (nonatomic) long long playerOpenInputStartDate;
@property (nonatomic) long long httpOpenStartDate;
@property (nonatomic) long long transOpenStartDate;
@property (nonatomic) long long playerDnsAnalysisStartDate;
@property (nonatomic) long long socketCreateEndDate;
@property (nonatomic) long long redirectHappenTimeDate;
@property (nonatomic) long long httpReqFinishTimeDate;
@property (nonatomic) long long httpResFinishTimeDate;
@property (nonatomic) long long roomPlayTimeMs;
@property (nonatomic) long long streamInfoFindEndDate;
@property (retain, nonatomic) NSDate *roomPlayStartDate;
@property (nonatomic) long long videoCodecID;
@property (nonatomic) BOOL isPreCreate;
@property (copy, nonatomic) NSString *liveioP2PInfo;
@property (nonatomic) long long liveioSessionHttpPlayTime;
@property (nonatomic) long long liveioSessionP2PPlayTime;
@property (nonatomic) long long liveioSessionIoPlayTime;
@property (nonatomic) long long liveioSessionHttpFlowSize;
@property (nonatomic) long long liveioSessionP2PFlowSize;
@property (nonatomic) long long liveioSessionP2PMobileFlowSize;
@property (nonatomic) long long liveioSessionGroupId;
@property (nonatomic) long long liveioSessionGroupReason;
@property (nonatomic) long long liveioSessionGroupEnterReason;
@property (nonatomic) long long liveioSessionBufferNotSatifyP2PTimes;
@property (nonatomic) long long liveioSessionBufferNotSatifyP2PValue;
@property (nonatomic) long long liveioSessionFirstTimeH2pBuffer;
@property (nonatomic) long long liveioSessionP2POnlines;
@property (nonatomic) long long liveioExceptionCode;
@property (nonatomic) BOOL isUpdatefirstFrameRendered;
@property (retain, nonatomic) NSMutableArray *segementList;
@property (nonatomic) long long segementIndex;
@property (retain, nonatomic) NSDate *segementFrameRenderedDate;
@property (copy, nonatomic) NSString *segementRequestStr;
@property (nonatomic) int displayChanged;
@property (nonatomic) long long previewTime;
@property (nonatomic) long long previewPlaySize;
@property (nonatomic) long long previewDownloadSize;
@property (nonatomic) long long innerTime;
@property (nonatomic) long long innerPlaySize;
@property (nonatomic) long long innerDownloadSize;
@property (nonatomic) long long previewPreplayTime;
@property (nonatomic) long long previewPreplayPlaySize;
@property (nonatomic) long long previewPreplayDownloadSize;
@property (nonatomic) long long innerPreplayTime;
@property (nonatomic) long long innerPreplayPlaySize;
@property (nonatomic) long long innerPreplayDownloadSize;
@property (nonatomic) long long backgroundWatchingTime;
@property (nonatomic) long long backgroundWatchingPlaySize;
@property (nonatomic) long long backgroundWatchingDownloadSize;
@property (nonatomic) long long smallWindowTime;
@property (nonatomic) long long smallWindowPlaySize;
@property (nonatomic) long long smallWindowDownloadSize;
@property (nonatomic) long long initialTime;
@property (nonatomic) long long otherPlaySize;
@property (nonatomic) long long otherDownloadSize;
@property (retain, nonatomic) NSMutableDictionary *displayOtherModelMap;
@property (readonly, nonatomic) NSMutableArray *retryEvents;
@property (readonly, nonatomic) NSMutableArray *stallEvents;
@property (readonly, nonatomic) NSMutableArray *renderStallEvents;
@property (readonly, nonatomic) NSMutableArray *errorEvents;
@property (readonly, nonatomic) NSMutableArray *videoBitrateSwitchEvents;
@property (retain, nonatomic) NSDate *startPreviewDate;
@property (copy, nonatomic) NSString *spsppsInfo;
@property (readonly, nonatomic) NSMutableArray *demuxStallEvents;
@property (readonly, nonatomic) NSMutableArray *decodeStallEvents;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)pullStreamEventWithPlayerItem:(id)a0;

- (id)logInfo;
- (void)appendRetryEvent:(id)a0;
- (void)appendStallEvent:(id)a0;
- (void)appendRenderStallEvent:(id)a0;
- (void)appendErrorEvent:(id)a0;
- (void)appendBitrateSwitchEvent:(id)a0;
- (id)videoBitrateSwitchInfo;
- (unsigned long long)playDataSize;
- (unsigned long long)downloadedDataSizeDelta;
- (unsigned long long)playDataSizeDelta;
- (long long)liveioHttpFlowSize;
- (long long)liveioP2pFlowSize;
- (long long)liveioP2pMobileSize;
- (long long)liveioRtmFlowSize;
- (long long)liveioHttpIOPlayTime;
- (long long)liveioP2pIOPlayTime;
- (long long)liveioRtmIOPlayTime;
- (void)endPreview;
- (long long)getPlayTimePreview;
- (struct TVLItemStallInfomation { long long x0; long long x1; long long x2; long long x3; long long x4; long long x5; long long x6; long long x7; long long x8; long long x9; long long x10; long long x11; long long x12; long long x13; long long x14; long long x15; })stallBaseInfomation;
- (void)updateChlo;
- (long long)totalStallDuration;
- (id)latestStallEvent;
- (void).cxx_destruct;
- (id)endDate;
- (id)init;
- (id)startDate;
- (unsigned long long)downloadedDataSize;
- (long long)totalStallCount;

@end
