@class NSString, NSDictionary, NSArray, XPlayCloudPermissionModel, XPlayCloudFunctionModel;
@protocol XPlayHoverBallConfig, XPlayAgreementConfig, XPlayResolution, XPlayResolutionConfig, XPlayDataConfig;

@interface XPlayQueueConfiguration : XPlayConfiguration <XPlayConfigurationProtocol>

@property (nonatomic) unsigned long long remainingPlayTime;
@property (copy, nonatomic) NSString *queue;
@property (copy, nonatomic) NSString *queueType;
@property (nonatomic) int serviceId;
@property (nonatomic) int methodId;
@property (nonatomic) long long ranking;
@property (nonatomic) long long waitTime;
@property (nonatomic) long long actualWaitTime;
@property (nonatomic) long long rankTotal;
@property (nonatomic) long long expireTime;
@property (nonatomic) BOOL isVipQueue;
@property (nonatomic) int surpass;
@property (nonatomic) long long state;
@property (nonatomic) long long scene;
@property (copy, nonatomic) NSDictionary *openInfo;
@property (nonatomic) BOOL isAdShow;
@property (copy, nonatomic) NSString *adFrom;
@property (nonatomic) int adRit;
@property (nonatomic) int adCreatorId;
@property (nonatomic) int adCreatorType;
@property (copy, nonatomic) NSString *gameId;
@property (copy, nonatomic) NSString *xToken;
@property (copy, nonatomic) NSString *channel;
@property (copy, nonatomic) NSString *gameName;
@property (retain, nonatomic) NSArray *cloudPlayerNames;
@property (nonatomic) unsigned long long displayWidth;
@property (nonatomic) unsigned long long displayHeight;
@property (nonatomic) long long originX;
@property (nonatomic) long long originY;
@property (nonatomic) unsigned long long pcDisplayWidthRatio;
@property (nonatomic) unsigned long long pcDisplayHeightRatio;
@property (copy, nonatomic) NSString *expectCore;
@property (nonatomic) BOOL enableRTCMulti;
@property (nonatomic) BOOL muteAudioPlayback;
@property (nonatomic) BOOL enablePixelBuffer;
@property (nonatomic) BOOL enablePureDetect;
@property (nonatomic) BOOL enableAudioFrame;
@property (nonatomic) BOOL useDefaultShouldAutorotate;
@property (nonatomic) BOOL shouldAutorotate;
@property (nonatomic) BOOL enableExternalRenderer;
@property (nonatomic) BOOL enableFrameSEIData;
@property (copy, nonatomic) NSDictionary *extra;
@property (copy, nonatomic) NSDictionary *appExtra;
@property (copy, nonatomic) NSDictionary *innerExtra;
@property (nonatomic) BOOL useNativeKeyboardIfSupported;
@property (nonatomic) BOOL useGameOrientation;
@property (nonatomic) BOOL useNativeShockIfSupported;
@property (nonatomic) long long supportLiveType;
@property (nonatomic) long long trialTimeUpStatus;
@property (nonatomic) BOOL disableXPlayCountDown;
@property (nonatomic) BOOL enableGameSafeArea;
@property (copy, nonatomic) NSArray *videoSimulcast;
@property (retain, nonatomic) XPlayCloudPermissionModel *permissionModel;
@property (retain, nonatomic) XPlayCloudFunctionModel *cloudFunctionModel;
@property (nonatomic) unsigned long long guestType;
@property (nonatomic) BOOL useVirtualControlsIfSupported;
@property (readonly, copy, nonatomic) NSString *core;
@property (readonly, nonatomic) unsigned long long gameOrientation;
@property (readonly, nonatomic) unsigned short gameOrientationAngle;
@property (readonly, nonatomic) unsigned long long playTime;
@property (readonly, nonatomic) unsigned long long requestId;
@property (readonly, nonatomic) BOOL useNativeMotion;
@property (readonly, nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } frame;
@property (readonly, nonatomic) id<XPlayResolution> currentResolution;
@property (readonly, copy, nonatomic) NSArray *supportResolutions;
@property (readonly, copy, nonatomic) NSArray *availableResolutions;
@property (readonly, nonatomic) id<XPlayResolution> currentAvailableResolution;
@property (readonly, nonatomic) long long preload;
@property (readonly, nonatomic) long long podType;
@property (readonly, nonatomic) long long platformType;
@property (readonly, nonatomic) id<XPlayResolutionConfig> resolutionConfig;
@property (readonly, nonatomic) id<XPlayDataConfig> dataConfig;
@property (readonly, nonatomic) id<XPlayAgreementConfig> agreementConfig;
@property (readonly, copy, nonatomic) NSString *debugInfo;
@property (readonly, copy, nonatomic) NSString *itemId;
@property (readonly, copy, nonatomic) NSString *uniGameId;
@property (readonly, nonatomic) BOOL isArchivedGame;
@property (readonly, nonatomic) BOOL needAuthorized;
@property (readonly, nonatomic) BOOL needRealNameAuth;
@property (readonly, nonatomic) BOOL needClientLaunchAuth;
@property (readonly, nonatomic) BOOL hideHoverBall;
@property (readonly, nonatomic) id<XPlayHoverBallConfig> hoverBallConfig;
@property (readonly, nonatomic) NSDictionary *businessParams;
@property (readonly, nonatomic) unsigned long long supplierSDKType;
@property (readonly, copy, nonatomic) NSString *roomId;
@property (readonly, nonatomic) BOOL isPodReconnect;
@property (readonly, nonatomic) BOOL enableLocation;
@property (readonly, copy, nonatomic) NSString *podDc;
@property (readonly, copy, nonatomic) NSString *planId;
@property (readonly, copy, nonatomic) NSString *productId;
@property (readonly, copy, nonatomic) NSString *podDeviceModel;
@property (readonly, copy, nonatomic) NSString *podGPUInfo;
@property (readonly, copy, nonatomic) NSString *supplierPodID;
@property (readonly, copy, nonatomic) NSString *sessionId;
@property (readonly, nonatomic) BOOL isMultiInstance;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (BOOL)examineConfiguration;
- (id)xplayServiceRequestParams;
- (BOOL)configurationSetWithDictionary:(id)a0;
- (void).cxx_destruct;
- (id)init;

@end
