@class AWESearchWaterfallLayoutBackgroundView, AWESearchCachalotCardInjectManager, MASConstraint, AWEGeneralSearchHelpPublishManager, AWESearchCardShowPercentTrackerHandler, AWEGeneralFullpageFooterView, AWESearchUtility, AWEGeneralSearchPageContext, AWESearchSmartPreloadManager, NSMapTable, AWESearchGeneralSearchWaterfallTouchPlayRule, NSMutableDictionary, AWESearchLoadMoreFooter, AWESearchFloatingBackgroundView, UIViewController, AWESSCollegeSummaryEntranceManager, AWEGeneralSearchCommonCardTracker, UIImageView, AWESearchiPadModePlayRule, AWEVoiceSearchManager, DUXBottomNotification, AWESearchClientAIFeatureUploader, AWEBottomDoubleColumnBall, AWESearchGeneralSearchWaterfallPlayRule, AWESearchEasterEggManager, AWESearchFullPageLoadMoreFooter, AWESSCollegeSummaryEntranceView, AWESearchTabConfig, NSMutableArray, AWESearchCachalotGeneralLynxPipeline, AWESearchImmersiveContainerView, UIView, AWESearchHomePageOperateCardManager, AWESearchAIGCSSERequestBusinessManager, AWEGeneralSearchWaterfallRecommendWordsManager, AWESearchFullPageEmptyContainerView, NSTimer, AWESearchResultCachalotDataResponse, DUXContentSheet, NSObject, AWESearchClientTagsManager, NSHashTable, AWEGeneralSearchAITopHintView, AWESearchResultViewController, AWESearchCachalotResultContext, AWEGeneralCachalotRequestParams, AWESearchCachalotGeneralContext, AWETrackerContext, AWESearchTopLoadingView, TTHttpTask, AWESearchFullPageRefreshHeader, AWESearchHybirdHistoryModule, AWESearchCachalotDataController, AWESearchGeneralSearchDualColumnActiveLinePlayRule, AWESearchSchemaModel, AWESearchCachalotGeneralCardPipeline, AWESearchFoldTopTipsView, AWEBottomDoubleColumnButton, AWESearchClientAIFeatureCenter, AWESearchHomeNewStyleSearchBarQueryContext, NSArray, AWEGeneralCachalotDataController, AWEAwemeModel, AWEGeneralSearchBackgroundManager, AWESearchStateContext, AWESearchAIGCSummaryEntryView, AWEGeneralSearchModel, AWEGeneralSearchAIModeManager, AWESearchEasterEggView, AWESearchSessionConsumeRecorder, NSString, AWEHotSpotPublishHelper, AWESearchClientAIFeatureManager, AWESearchResultRefreshHeader, AWESearchCommonRerankManager, AWESeachFullPageLoadingView, NSDictionary, AWESearchCachalotGeneralWebPipeline, AWEGeneralSearchRecommendWordsManager, AWESearchCommonPreRenderManager, AWESearchSingleTapEnterDetailHandler, AWESearchCorrectView, AWESearchMuteView, AWESearchGeneralSearchDoubleColumnPlayRule, AWESearchFPSBlockUtil;
@protocol AWEFeedPreloadManagerProtocol, CachalotRenderPipelineComponentViewModel, AWESearchFeelGoodManagerProtocol, AWESearchBusinessImmersiveContainerViewProtocol, AWESearchLocationAuthGuideViewProtocol, AWESearchActionListenerProtocol, AWEHotSpotPublishHelperProtocol, AWESearchAdPopConfigManager, AWESearchAIGCServiceProtocol, AWESearchDecoratorDelegateProtocol, AWESearchChildViewControllerResultFilterProtocol, AWEGeneralSearchPublishEntranceManagerProtocol, SearchCachalotViewInterface, AWESearchAdImmersiveContainerViewProtocol, AWEFeedAdPitayaReRankController, AWEModernFeedCellControllerProtocol;

@interface AWEGeneralSearchCachalotViewController : AWESearchResultVerticalBaseViewController <AWESearchAwemePlayerStatusSyncProtocol, AWESearchGeneralPipelinePreRenderProvider, AWEGeneralHotSearchBusinessViewControllerProtocol, AWESearchMultiFeedFallThroughProtocol, AWEPlayletPaymentMessage, AWEShowMonetizeRefreshHandler, CachalotStructUpdateTransactionCommitDelegate, AWESearchSingleTapEnterDetailProtocol, AWEHotSpotPublishHelperDelegate, CachalotStructUpdateTransactionCommitDelegate, BDXContainerLifecycleProtocol, AWEAdImmersiveContainerDelegate, AWEBusinessImmersiveContainerDelegate, AWESearchImmersiveContainerViewDelegate, AFDMuteAwemeMessage, AWESearchCommonRerankManagerDelegate, AWEFeedPreloadManagerDelegate, DUXGridBreakPointResponder, CachalotStructUpdateTransactionCommitDelegate, AWESearchAutoPlayMonitorDelegate, AWESearchMonitorHelperDelegate, AWESearchHomePageOperateCardManagerDelegate, AWESearchFullpageGeneralLoadmoreCellDelegate, AWESearchAdPopConfigManagerDelegate, AWESSCollegeSummaryEntranceObserver, AWESSCollegeSummaryEntranceViewDelegate, AWEUGCTopicServiceProviderProtocol, AWELiveSearchOutterRoomTransitionContextProvider, AWESearchChildViewControllerDynamicTabProtocol, AWESearchPreRequestProtocol, AWESearchGeneralCachalotDataControllerDelegate, AWESearchDynamicTabPreRequestProtocol, AWESearchPopTaskProtocol, AWESearchDynamicPreLayoutProtocol, AWESearchAIGCServiceDelegate, AWEGeneralSearchCachalotViewControllerProtocol, AWESearchUGCTopicViewControllerProtocol>

@property (class, retain, nonatomic) NSString *searchPreNewSource;

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) NSMutableDictionary *chunkPreRenderCache;
@property (retain, nonatomic) NSMapTable *fingerprintAndModelTable;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL blockBGUpdateForTabSwitch;
@property (nonatomic) BOOL blockBGUpdateHeight;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL hasClickedCard;
@property (nonatomic) long long clickCardIndex;
@property (copy, nonatomic) NSString *fromGroupId;
@property (retain, nonatomic) AWEAwemeModel *clickCardAwemeModel;
@property (retain, nonatomic) AWEGeneralSearchModel *clickCardGeneralModel;
@property (retain, nonatomic) UIViewController<AWEModernFeedCellControllerProtocol> *clickCardComponent;
@property (copy, nonatomic) id /* block */ checkClickRecommendBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) AWESearchUtility *searchUtility;
@property (retain, nonatomic) AWESearchCorrectView *suggestView;
@property (retain, nonatomic) AWEGeneralCachalotDataController *searchDataController;
@property (copy, nonatomic) NSDictionary *attributes;
@property (copy, nonatomic) NSDictionary *transEventExtra;
@property (nonatomic) BOOL shouldAutoPlayVideo;
@property (nonatomic) BOOL refreshFirstScreenReady;
@property (nonatomic) BOOL pullRefreshEnable;
@property (nonatomic) long long loadMoreTriggerCount;
@property (nonatomic) long long preloadmoreLine;
@property (nonatomic) BOOL hasSetAnchorQueryID;
@property (retain, nonatomic) TTHttpTask *fetchRecommWordsTask;
@property (nonatomic) BOOL searchStrengthenToLight;
@property (copy, nonatomic) NSDictionary *logExtraDict;
@property (copy, nonatomic) NSDictionary *filteredToRaw;
@property (nonatomic) BOOL headerViewIsFloating;
@property (nonatomic) double lastContentOffsetY;
@property (nonatomic) BOOL lastDragDidTriggerHeaderTopChange;
@property (copy, nonatomic) id /* block */ gsAnimationComplete;
@property (nonatomic) BOOL preRenderExperiment;
@property (nonatomic) double lastMemoryWarningTS;
@property (nonatomic) long long latestShowFeedIndex;
@property (retain, nonatomic) AWESearchSingleTapEnterDetailHandler *tapEnterDetailHandler;
@property (retain, nonatomic) UIView *listHeaderView;
@property (nonatomic) unsigned long long themeStyle;
@property (retain, nonatomic) AWEGeneralSearchModel *objectToScroll;
@property (retain, nonatomic) AWESearchFPSBlockUtil *fpsBlockUtil;
@property (retain, nonatomic) AWEGeneralCachalotRequestParams *requestParams;
@property (retain, nonatomic) AWESearchCachalotGeneralContext *generalContext;
@property (retain, nonatomic) AWESearchCachalotGeneralLynxPipeline *lynxPipeline;
@property (retain, nonatomic) AWESearchCachalotGeneralCardPipeline *nativeCardPipeline;
@property (retain, nonatomic) AWESearchCachalotGeneralWebPipeline *webPipeline;
@property (retain, nonatomic) NSMutableDictionary *deleteItemCountMap;
@property (retain, nonatomic) AWEGeneralSearchCommonCardTracker *commonCardTracker;
@property (copy, nonatomic) id /* block */ foldToUnfoldBlock;
@property (nonatomic) BOOL isLoading;
@property (nonatomic) BOOL ssrWillDisplayHydrateEnable;
@property (nonatomic) double refreshBeginTimestamp;
@property (nonatomic) BOOL filterOnTab;
@property (copy, nonatomic) NSDictionary *currFilterText;
@property (nonatomic) long long dataProcessedIndex;
@property (nonatomic) long long currentContainerContextType;
@property (nonatomic) BOOL finishFirstTrack;
@property (nonatomic) double muteStatusInterval;
@property (retain, nonatomic) AWESearchMuteView *cancelMuteView;
@property (retain, nonatomic) DUXBottomNotification *cancelMuteTip;
@property (retain, nonatomic) AWEGeneralSearchBackgroundManager *backgroundManager;
@property (retain, nonatomic) AWESearchImmersiveContainerView *immersiveContainerView;
@property (retain, nonatomic) id<AWESearchAdPopConfigManager> popConfigManager;
@property (retain, nonatomic) UIView<AWESearchAdImmersiveContainerViewProtocol> *immersiveADView;
@property (retain, nonatomic) UIImageView *immersiveADEffectView;
@property (retain, nonatomic) UIView<AWESearchBusinessImmersiveContainerViewProtocol> *immersiveBusinessView;
@property (nonatomic) BOOL immersiveContainerViewHidden;
@property (nonatomic) BOOL searchImmersiveEnable;
@property (nonatomic) BOOL usedCSP2;
@property (retain, nonatomic) DUXContentSheet *sheet;
@property (nonatomic) double predictStarttime;
@property (nonatomic) BOOL isAppear;
@property (nonatomic) BOOL isAppearing;
@property (nonatomic) BOOL realAppear;
@property (copy, nonatomic) id /* block */ recaculateCellHeightBlock;
@property (retain, nonatomic) AWESearchEasterEggManager *easterEggManager;
@property (nonatomic) double fullScreenColorHeight;
@property (nonatomic) double lastScreenColorCardHeight;
@property (nonatomic) double insetTopHeight;
@property (nonatomic) double fixUIOffsetChangeTop;
@property (nonatomic) BOOL isNeedResetGs;
@property (nonatomic) BOOL isSearchFixUIOffsetChange;
@property (retain, nonatomic) id<AWEGeneralSearchPublishEntranceManagerProtocol> publishEntryManager;
@property (retain, nonatomic) AWEHotSpotPublishHelper *publishHelper;
@property (readonly, nonatomic) id<AWEHotSpotPublishHelperProtocol> currentPublishHelper;
@property (retain, nonatomic) AWEGeneralSearchHelpPublishManager *helpPublishManager;
@property (nonatomic) BOOL POITopBarIsShowing;
@property (nonatomic) BOOL filterViewIsShowing;
@property (retain, nonatomic) UIView<AWESearchLocationAuthGuideViewProtocol> *POITopBarView;
@property (retain, nonatomic) AWEGeneralSearchPageContext *pageContext;
@property (retain, nonatomic) NSMutableArray *searchModelArr;
@property (retain, nonatomic) NSMutableArray *viewModelArr;
@property (retain, nonatomic) AWESearchiPadModePlayRule *autoPlayHandlerRule;
@property (nonatomic) BOOL isPlayingMusic;
@property (retain, nonatomic) AWESearchCachalotCardInjectManager *injectManager;
@property (nonatomic) BOOL isSearchNeedWaterFallLayout;
@property (nonatomic) BOOL isIntentSingleColumn;
@property (nonatomic) BOOL isSingleColumnByUser;
@property (retain, nonatomic) AWESearchWaterfallLayoutBackgroundView *waterfallBackgroundView;
@property (nonatomic) double initialWaterfallBackgroundOffset;
@property (nonatomic) double previousContentOffset;
@property (retain, nonatomic) AWESearchGeneralSearchWaterfallPlayRule *waterfallAutoPlayRule;
@property (retain, nonatomic) AWESearchGeneralSearchWaterfallTouchPlayRule *waterfallTouchAutoPlayRule;
@property (retain, nonatomic) AWESearchGeneralSearchDoubleColumnPlayRule *doubleColumnAutoPlayRule;
@property (retain, nonatomic) AWESearchGeneralSearchDualColumnActiveLinePlayRule *dualColumnActiveLineAutoPlayRule;
@property (retain, nonatomic) AWEGeneralSearchWaterfallRecommendWordsManager *waterfallRecommendWordsManager;
@property (retain, nonatomic) AWEGeneralSearchRecommendWordsManager *recommendWordsManager;
@property (copy, nonatomic) NSString *strMaskedSearchUploadToken;
@property (retain, nonatomic) NSHashTable *optVisibleCellsCache;
@property (retain, nonatomic) AWESearchHomePageOperateCardManager *operateCardManager;
@property (nonatomic) BOOL isEcomRecommendWordMode;
@property (retain, nonatomic) NSDictionary *cacahlotRegisterCardDict;
@property (nonatomic) double startRemoveCacheTime;
@property (copy, nonatomic) NSString *previousKeyword;
@property (nonatomic) BOOL isAutoChangeOfContentOffset;
@property (retain, nonatomic) NSMutableDictionary *chunkPreRenderCache;
@property (nonatomic) BOOL canSetFloatingHeaderTheme;
@property (nonatomic) BOOL bottomBarHasExposure;
@property (retain, nonatomic) AWESearchCommonRerankManager *commonRerankManager;
@property (retain, nonatomic) AWESearchSessionConsumeRecorder *sessionConsumeRecorder;
@property (retain, nonatomic) AWESearchSmartPreloadManager *smartPreloadManager;
@property (retain, nonatomic) AWESearchClientAIFeatureManager *commonFeatureManager;
@property (retain, nonatomic) AWESearchClientAIFeatureCenter *featureCenter;
@property (retain, nonatomic) AWESearchCommonPreRenderManager *preRenderManager;
@property (retain, nonatomic) AWESearchClientAIFeatureUploader *featureUploader;
@property (retain, nonatomic) AWESearchClientTagsManager *clientTagsManager;
@property (nonatomic) BOOL fixBackgroundColorSearchBar;
@property (nonatomic) double lastFirstScreenWithWhiteSpaceTS;
@property (retain, nonatomic) id<AWEFeedPreloadManagerProtocol> preloadManager;
@property (copy, nonatomic) NSDictionary *firstScreenPreciseHeightInfo;
@property (retain, nonatomic) NSMutableArray *patchAwemeModels;
@property (nonatomic) long long layoutMode;
@property (nonatomic) double doubleColumnTimestamp;
@property (retain, nonatomic) AWEVoiceSearchManager *voiceManager;
@property (nonatomic) double anchorOffset;
@property (nonatomic) double beginDraggingOffset;
@property (nonatomic) BOOL isVoiceSearchSession;
@property (nonatomic) BOOL isSwipDown;
@property (weak, nonatomic) AWEBottomDoubleColumnBall *bottomDoubleColumnButton;
@property (retain, nonatomic) AWEBottomDoubleColumnButton *bottomDoubleColumnSwitch;
@property (retain, nonatomic) NSTimer *bottomDoubleColumnSwitchTimer;
@property (retain, nonatomic) MASConstraint *bottomDoubleColumnConstraint;
@property (retain, nonatomic) MASConstraint *bottomDoubleColumnRightConstraint;
@property (nonatomic) double doubleColumnBoundaryOffset;
@property (nonatomic) long long doubleColumnBoundaryIndex;
@property (retain, nonatomic) MASConstraint *backgroundViewLeftConstraint;
@property (retain, nonatomic) MASConstraint *backgroundViewRightConstraint;
@property (retain, nonatomic) AWESearchAIGCSSERequestBusinessManager *sseRequestBusinessManager;
@property (copy, nonatomic) NSString *lastSearchKeyword;
@property (copy, nonatomic) NSString *lastSearchOriginKeyword;
@property (retain, nonatomic) AWESearchAIGCSummaryEntryView *aigcSummaryEntryView;
@property (retain, nonatomic) NSTimer *aigcSummaryEntryTimer;
@property (nonatomic) double elapsedTime;
@property (nonatomic) double stayTime;
@property (nonatomic) BOOL isAIGCSummaryEntryTimerRunning;
@property (retain, nonatomic) AWEGeneralSearchAIModeManager *aiModeManager;
@property (nonatomic) BOOL hasShowHotSpotWidgetGuide;
@property (copy, nonatomic) NSString *waterfallFeelGoodShowSearchId;
@property (nonatomic) long long imageDetailIndex;
@property (nonatomic) long long questionnaireIndex;
@property (retain, nonatomic) AWESearchTopLoadingView *topLoadingView;
@property (retain, nonatomic) AWESearchTopLoadingView *fakeTopLoadingView;
@property (retain, nonatomic) UIView *topBackColorView;
@property (retain, nonatomic) AWESearchResultCachalotDataResponse *predictResponse;
@property (nonatomic) double maxOffsetY;
@property (nonatomic) BOOL isSuperAgentCard;
@property (copy, nonatomic) NSString *loadingCopywriting;
@property (nonatomic) BOOL isAiRelatedCard;
@property (retain, nonatomic) id<CachalotRenderPipelineComponentViewModel> beforeReleaseRoot;
@property (nonatomic) long long cachalotViewBeforeReleaseIndex;
@property (nonatomic) long long releaseState;
@property (retain, nonatomic) AWESearchHomeNewStyleSearchBarQueryContext *queryContext;
@property (weak, nonatomic) id<CachalotRenderPipelineComponentViewModel> clippingViewModel;
@property (nonatomic) double clippingHidingOffset;
@property (copy, nonatomic) NSDictionary *fullpageExtraParams;
@property (retain, nonatomic) NSMutableArray *maskedSearchKeys;
@property (retain, nonatomic) NSMapTable *foldableCardInfoTable;
@property (weak, nonatomic) id<CachalotRenderPipelineComponentViewModel> top1AIRootViewModel;
@property (weak, nonatomic) id<CachalotRenderPipelineComponentViewModel> foldBlankViewModel;
@property (retain, nonatomic) AWESearchFoldTopTipsView *foldTopTipView;
@property (weak, nonatomic) id<CachalotRenderPipelineComponentViewModel> willInsertViewModel;
@property (nonatomic) BOOL isAIRequestFailure;
@property (nonatomic) BOOL isAIRequestFinish;
@property (nonatomic) BOOL isAIQARoundFinish;
@property (nonatomic) BOOL isAIReload;
@property (nonatomic) long long hasExpand;
@property (nonatomic) BOOL insertAIRsCard;
@property (nonatomic) BOOL hasFinishShow;
@property (nonatomic) BOOL hasOuterInsertCard;
@property (nonatomic) BOOL isInsertingOutCard;
@property (nonatomic) BOOL hasInsertTips;
@property (retain, nonatomic) AWESearchFullPageLoadMoreFooter *fullpageFooterView;
@property (retain, nonatomic) AWESearchFullPageRefreshHeader *fullpageRefreshView;
@property (nonatomic) BOOL isFollowed;
@property (retain, nonatomic) AWESeachFullPageLoadingView *fullpageLoadingView;
@property (nonatomic) double fullpageLoadingViewInitialY;
@property (retain, nonatomic) AWESearchFullPageEmptyContainerView *fullpageEmptyContainerView;
@property (nonatomic) BOOL hasTrackedShowType;
@property (nonatomic) BOOL hasfoldedBefore;
@property (retain, nonatomic) AWESSCollegeSummaryEntranceManager *collegeSummaryEntranceManager;
@property (retain, nonatomic) AWESSCollegeSummaryEntranceView *collegeSummaryEntranceView;
@property (weak, nonatomic) id<CachalotRenderPipelineComponentViewModel> aiTypingAnchorVM;
@property (weak, nonatomic) id<CachalotRenderPipelineComponentViewModel> loadmoreCard;
@property (retain, nonatomic) AWEGeneralSearchAITopHintView *aiTopHintView;
@property (nonatomic) BOOL isAiRandering;
@property (nonatomic) BOOL hasLoadmoreCard;
@property (retain, nonatomic) AWEGeneralFullpageFooterView *loadmoreFooterView;
@property (nonatomic) BOOL tabBarHidden;
@property (nonatomic) double latestSearchStartTime;
@property (retain, nonatomic) AWESearchHybirdHistoryModule *ssHistoryModule;
@property (retain, nonatomic) NSString *refer;
@property (copy, nonatomic) NSArray *fallThroughFeeds;
@property (nonatomic) long long transitionIndex;
@property (nonatomic) long long transitionToIndex;
@property (nonatomic) long long transitionRealIndex;
@property (nonatomic) BOOL hasScrolledInInnerStream;
@property (nonatomic) BOOL clickAvatarNotScroll;
@property (nonatomic) BOOL isSearchHalfScreenMode;
@property (nonatomic) BOOL isSearchHalfScreenEnabled;
@property (nonatomic) BOOL isSearchHalfScreenLoadmore;
@property (retain, nonatomic) AWESearchEasterEggView *easterEggView;
@property (retain, nonatomic) AWESearchTabConfig *tabConfig;
@property (retain, nonatomic) id<AWESearchAIGCServiceProtocol> aigcService;
@property (weak, nonatomic) id<AWESearchActionListenerProtocol> listener;
@property (retain, nonatomic) NSMapTable *fingerprintAndModelTable;
@property (nonatomic) BOOL needPreFetch;
@property (retain, nonatomic) id<CachalotRenderPipelineComponentViewModel> predictRootModel;
@property (nonatomic) BOOL inCSP2PredictPhase;
@property (copy, nonatomic) NSString *feedPlayingTime;
@property (retain, nonatomic) id<AWEFeedAdPitayaReRankController> adPitayaReRankController;
@property (nonatomic) BOOL enterInnerStreamRerank;
@property (retain, nonatomic) AWESearchCardShowPercentTrackerHandler *showPercentTrackerHandler;
@property (retain, nonatomic) TTHttpTask *fetchRecommWordsTaskV2;
@property (weak, nonatomic) AWESearchStateContext *stateContext;
@property (retain, nonatomic) NSObject<AWESearchDecoratorDelegateProtocol> *searchDecoratorDelegate;
@property (nonatomic) BOOL manualSwitchColumn;
@property (nonatomic) BOOL isReSearch;
@property (nonatomic) BOOL needIsNewSession;
@property (retain, nonatomic) NSMutableDictionary *clarifiedQueryMap;
@property (retain, nonatomic) NSMutableDictionary *paymentAwemeAndModelTable;
@property (nonatomic) BOOL needRebuid;
@property (nonatomic) BOOL needFullPageHeader;
@property (retain, nonatomic) AWEAwemeModel *originModel;
@property (copy, nonatomic) NSString *enterFrom;
@property (nonatomic) BOOL isInSearchAdEndorseVideo;
@property (readonly, nonatomic) BOOL useCollectionView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) AWESearchSchemaModel *routerModel;
@property (retain, nonatomic) UIView *view;
@property (readonly, nonatomic) UIView<SearchCachalotViewInterface> *cachalotView;
@property (readonly, nonatomic) AWESearchCachalotDataController *dataController;
@property (weak, nonatomic) AWESearchResultViewController *searchResultViewController;
@property (readonly, nonatomic) AWESearchResultRefreshHeader *refreshHeaderView;
@property (readonly, nonatomic) AWESearchLoadMoreFooter *footerView;
@property (readonly, nonatomic) AWESearchCachalotResultContext *cachalotContext;
@property (nonatomic) BOOL isSearchLoading;
@property (weak, nonatomic) id<AWESearchChildViewControllerResultFilterProtocol> delegate;
@property (retain, nonatomic) AWETrackerContext *trackerContext;
@property (copy, nonatomic) id /* block */ searchTabsUpdateBlock;
@property (nonatomic) BOOL isFilterSearch;
@property (nonatomic) unsigned long long publishTime;
@property (nonatomic) unsigned long long sortType;
@property (nonatomic) unsigned long long refreshType;
@property (copy, nonatomic) NSString *enterMethod;
@property (nonatomic) BOOL dismissTabBottomLine;
@property (retain, nonatomic) AWESearchFloatingBackgroundView *floatingBackgroundView;
@property (nonatomic) long long searchTabFeedType;
@property (copy, nonatomic) NSString *personalSearchChannel;
@property (copy, nonatomic) NSString *personalTrackTabType;
@property (copy, nonatomic) NSString *userID;
@property (copy, nonatomic) NSString *tokenType;
@property (copy, nonatomic) NSString *clickMoreMethod;
@property (nonatomic) long long searchQueryInputTime;
@property (nonatomic) long long searchButtonPressDuration;
@property (nonatomic) long long searchButtonClickPositionX;
@property (nonatomic) long long searchButtonClickPositionY;
@property (copy, nonatomic) id /* block */ isShowingMiddlePageBlock;
@property (copy, nonatomic) id /* block */ sugSessionIDBlock;
@property (retain, nonatomic) NSObject<AWESearchFeelGoodManagerProtocol> *surveyManager;

+ (void)removeMemoryCacheForSearch;
+ (id)identifierForPreRequestWithRootTag:(id)a0;
+ (Class)aAWESearchModuleServiceDOUYINSSAdaperClass;
+ (Class)aAWESearchModuleServiceDOUYINSSAdaperClass;
+ (id)refreshParamsWithInitialParams:(id)a0 context:(id)a1;
+ (id)createRequestWithParams:(id)a0;
+ (BOOL)enablePreRequestWithInitialParams:(id)a0;
+ (unsigned long long)newPreRequestType:(id)a0;
+ (BOOL)enableNewPreRequestWithInitialParams:(id)a0;
+ (BOOL)enableUseNewPreRequestTagWithSearchSource:(id)a0;
+ (BOOL)enablePredictFetchRequestWithInitialParams:(id)a0;
+ (id)paramsProviders;
+ (void)removeMemoryCacheWithTime;
+ (long long)syncGetSearchAlbumStyle;
+ (BOOL)useParamsProvider;
+ (long long)syncGetSearchTop1FoldOptStyle;
+ (Class)paramsContextClass;
+ (BOOL)pullRefreshUseParamsProvider;
+ (BOOL)loadMoreUseParamsProvider;
+ (BOOL)switchParamsProvider;
+ (BOOL)pullRefreshSwitchParamsProvider;
+ (BOOL)loadMoreSwitchParamsProvider;
+ (double)fetchActiveRectTop;
+ (double)fetchActiveRectBottom;
+ (double)fetchShouldNotActiveHeight;
+ (BOOL)fetchShouldFilterStaticCard;
+ (void)preprocessModel:(id)a0;
+ (BOOL)isFullPageGeneralSearch;
+ (id)createNativeNodeWithContext:(id)a0 dataType:(unsigned long long)a1 viewType:(unsigned long long)a2 dataModel:(id)a3;
+ (id)identifierForDynamicTabPreRequestWithRootTag:(id)a0;
+ (id)preFetchParamsContextWithRouterModel:(id)a0 extraLogParams:(id)a1;
+ (BOOL)enableNewGeneralSmartPostFeature;
+ (id)dynamicTabParamsWithInitialParams:(id)a0 context:(id)a1;
+ (id)createDynamicTabRequestWithParams:(id)a0;
+ (BOOL)enableDynamicTabPreRequest;
+ (id)setupFeedFallThroughWithResponder:(id)a0 params:(id)a1 autoCalculateIndex:(BOOL)a2;
+ (id)setupFeedFallThroughWithResponder:(id)a0 params:(id)a1;
+ (id)setupFeedFallThroughWithResponder:(id)a0 autoCalculateIndexForParams:(id)a1;
+ (BOOL)top1CouldForceExpand;
+ (BOOL)top1AddThreshold;
+ (BOOL)enableAIGCService;
+ (BOOL)enablepreLoadmoreLineFollowSingle;
+ (BOOL)enableExtraFuncionAB;
+ (BOOL)shouldUseAIMultiBall;
+ (BOOL)enableFetchDataParamsFix;
+ (BOOL)enablePredictAutoPlayFixWhenRefresh;
+ (BOOL)enablePredictAutoPlayFixDownGrade;
+ (BOOL)enableAdjustGeneralLoadmoreOpportunity;
+ (BOOL)enableCustomePreLoadMoreRule;
+ (BOOL)generalNeedNativeCustomTransitionView;
+ (BOOL)enableCachalotPullRequestDetectOpt;
+ (BOOL)enableGeneralRefreshSwitch;
+ (BOOL)enableFlowResearchRecalculate;
+ (BOOL)fixClearSearchBackgroundColor;
+ (BOOL)fixAutoplayResignFromTag;
+ (id)fixAutoPlayWhenContentSheetOnTopConfig;
+ (BOOL)enablePredictAutoPlayFix;
+ (BOOL)enableAdjustGeneralCount;
+ (BOOL)enableRemoveListHeaderView;
+ (BOOL)enableAutoplayFlingOptimize;
+ (id)searchAdImagePreloadOptInfo;

- (id)referString;
- (void)container:(id)a0 didFinishLoadWithURL:(id)a1;
- (void)container:(id)a0 didLoadFailedWithUrl:(id)a1 error:(id)a2;
- (id)aweui_emptyPageConfigForState:(unsigned long long)a0;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })aweui_emptyPageEdgeInsets;
- (void)container:(id)a0 didRecieveError:(id)a1;
- (id)zoomTransitionStartViewForOffset:(long long)a0;
- (id)liveTransitionContext;
- (BOOL)loadMoreWithCompletion:(id /* block */)a0;
- (void)duxGrid_viewDidChangeBreakPointFrom:(struct { long long x0; long long x1; })a0 toBreakPoint:(struct { long long x0; long long x1; })a1;
- (BOOL)btm_autoManaged;
- (void)muteAwemeCanceled;
- (id)aweui_emptyPageBelowView;
- (void)custom_aweui_viewDidLayoutSubviews;
- (id)aweui_emptyPageBgContainerView;
- (long long)currentPlayingIndex;
- (id)searchKeyword;
- (void)modernTransitionUpdateOffset:(long long)a0 isScrolled:(BOOL)a1;
- (void)modernTransitionDidCompleteWithOffset:(long long)a0;
- (BOOL)shouldModernTransitionUpdatePlayerControllerWithToContext:(id)a0;
- (BOOL)shouldModernTransitionUpdatePlayerControllerWithFromContext:(id)a0;
- (BOOL)shouldUpdatePlayerWhenModelDifferent:(id)a0;
- (long long)preferScaleMode;
- (BOOL)updateScaleModeBeforeAnimation;
- (long long)modernUpdateOffsetDiffWithItem:(id)a0 initialIndex:(long long)a1 originOffset:(long long)a2;
- (BOOL)isDoubleColumnStaticCover;
- (BOOL)isDoubleColumn;
- (id)monetizeScene;
- (void)refreshMonetizeContent:(id)a0 reason:(unsigned long long)a1;
- (id)monetizeDataSource;
- (id)monetizeContentTrackParams;
- (id)monetizeContentReferString;
- (BOOL)needReceiveRefreshMonetizeContent;
- (id)fetchComponentViewModelAtIndex:(long long)a0;
- (void)feedDidScroll:(id)a0;
- (void)p_checkComponentShowingRatio;
- (id)getLayoutWithType:(unsigned long long)a0;
- (double)ignoredScrollViewContentInsetTop;
- (BOOL)enableMemoryOptimizeWithNunki;
- (void)didReceiveMemeoryDangerLevelTopNotification;
- (void)handleMemoryWarning;
- (void)handleKeyboardWillShowNotification:(id)a0;
- (id)searchEnterMethod;
- (void)updateSearchAdPopPendantViewStatus:(id)a0;
- (void)windowDidResignKeyNotification:(id)a0;
- (id)sectionBindedData;
- (void)scrollToDisplayItemAtIndex:(long long)a0 offset:(double)a1 animated:(BOOL)a2;
- (void)didEndShowing;
- (BOOL)isTrendingPage;
- (id)bottomBarConfig;
- (id)hotSpotAdditionalInfo;
- (void)customFeedRecieveRequestWithResponseParams:(id)a0 isLoadMore:(BOOL)a1;
- (void)customRefreshResponseCompletion:(id /* block */)a0 withParams:(id)a1;
- (void)customHandleNodeViewModelsReady:(id)a0 withResponseParams:(id)a1 isLoadmore:(BOOL)a2;
- (void)customComponentDidFinishRender:(id)a0 withViewModel:(id)a1;
- (void)handleRefreshResponseCompletion:(id /* block */)a0 withParams:(id)a1;
- (void)customComponentWillDisplay:(id)a0 withViewModel:(id)a1;
- (void)publishTaskDidFinish:(id)a0 Result:(BOOL)a1;
- (void)fetchDataWithCompletion:(id /* block */)a0;
- (void)saveSearchWord:(id)a0 wordType:(id)a1;
- (void)saveSearchWord:(id)a0 wordType:(id)a1 extraParams:(id)a2;
- (void)fetchDataWithKeyWord:(id)a0 enterFrom:(id)a1 extraLogParams:(id)a2 isSearchByUserClick:(BOOL)a3 animated:(BOOL)a4 completion:(id /* block */)a5;
- (void)searchMiddleViewControlleWillShow;
- (void)willRelease;
- (id)aAWESearchModuleServiceDOUYINSSAdaper;
- (id)aAWESearchModuleServiceDOUYINSSAdaper;
- (id)refreshParamsWithInitialParams:(id)a0 context:(id)a1;
- (BOOL)isFirstSearch;
- (BOOL)enableNewPreRequestWithInitialParams:(id)a0 context:(id)a1;
- (unsigned long long)newPreRequestType:(id)a0 context:(id)a1;
- (id)refreshNewPreRequestParams:(id)a0 context:(id)a1;
- (BOOL)enablePreRequestWithInitialParams:(id)a0 context:(id)a1;
- (BOOL)enablePredictFetchRequestWithInitialParams:(id)a0 context:(id)a1;
- (id)resultViewController;
- (id)customBtmPageIdentifier;
- (id)generateControllerContext;
- (double)searchStartTime;
- (void)autoPlayDidActiveCard:(id)a0;
- (void)autoPlayBecomeActiveIfNeed;
- (void)autoPlayForceBecomeActiveWith:(id)a0;
- (void)stopVoiceBroadcast;
- (void)updateViewForRotate;
- (void)searchADOperationToolViewWillDisplay:(id)a0 aweme:(id)a1;
- (void)searchADOperationToolViewDidEndDisplay:(id)a0;
- (void)handleUIThemeChangeNotification:(id)a0;
- (void)updateAddress;
- (void)updateSearchHeaderBackground:(id)a0 hidden:(BOOL)a1 theme:(unsigned long long)a2;
- (void)showBlankView;
- (void)changeSearchBarText:(id)a0;
- (void)hideBlankView;
- (void)updateSearchBackground:(id)a0;
- (void)userDidTakeScreenshot:(id)a0;
- (BOOL)enableSmartLoadMore;
- (id)preloadManagerGetDataSource:(id)a0;
- (void)updatePlayletPaymentInfoWithModels:(id)a0;
- (id)cellManager;
- (void)initCommercePitayaReRankController;
- (BOOL)enableSearchInnerRerankDeleteDuplicate;
- (void)cancelRemoveMemoryCache;
- (BOOL)syncGetSearchInnerFeedBackOptimizeV2;
- (BOOL)syncGetSearchInnerFeedBackOptimizeV2;
- (void)didChangedLanguage;
- (id)generateCellModelForLynxPipeLineWithViewModel:(id)a0;
- (id)generateModernFeedCellModelWithGeneralSearchModel:(id)a0 referString:(id)a1;
- (id)ugcTopicService;
- (id)bottomBarConfigModel;
- (BOOL)showErrorInDataController;
- (BOOL)isChallengePage;
- (BOOL)ugcChallengeScene;
- (id)logPassbackInDataController;
- (id)keywordInDataController;
- (id)clientServerExtraInDataController;
- (void)handleInsertSingleCardBeforeAnchorWithInsertModel:(id)a0 completion:(id /* block */)a1;
- (void)handleInsertDoubleCardBeforeAnchorWithInsertModel:(id)a0 completion:(id /* block */)a1;
- (void)autoPlayRecalculateToActiveNeedReset;
- (id)findFirstDoubleColumnCardViewModel;
- (id)findFirstSingleColumnCardViewModel;
- (void)commonRefreshAfterDataTrasaction;
- (id)getCurrentLiveViewWithOffset:(long long)a0;
- (void)onStartLeaveRoomAnimationWithOffset:(long long)a0;
- (void)seekPlayTime:(double)a0 withItemID:(id)a1 sessionId:(id)a2;
- (id)awemeModelAtIndex:(long long)a0;
- (id)preloadModels;
- (void)cancelVideoPrefetch;
- (BOOL)syncGetSearchOuterFeedBackOptimizeV2;
- (BOOL)syncGetSearchWaterFallEmpleShowTrackEnable;
- (long long)syncGetSearchMoveListHeaderView;
- (BOOL)syncGetSearchGeneralCardAddLimitHeightAbility;
- (BOOL)syncGetAWESearchSeedAsynCalculate;
- (BOOL)disableCatchRenderException;
- (BOOL)enableFilterUnrenderableIndexPaths;
- (BOOL)enableTransactionPrepareUntilExecute;
- (void)customLoadmoreResponseCompletion:(id /* block */)a0 withParams:(id)a1;
- (id)paramsContext;
- (void)paramsContextDidReady:(id)a0;
- (void)paramsDidCollected:(id)a0 params:(id)a1;
- (void)handleCachalotContext:(id)a0;
- (void)p_trackArrayTriggerRefreshEvent:(id)a0;
- (void)chunkHandleReplaceResponse:(id)a0 allowShow:(BOOL)a1 rootModel:(id)a2;
- (void)chunkHandleShowResponseContainer:(BOOL)a0;
- (void)chunkHandleClearResponse:(id /* block */)a0;
- (void)chunkHandleAppendResponse:(id)a0 rootModel:(id)a1;
- (id)customContainerConfig;
- (id)logTypeToCopyMonitorValueBeforeSendWithCurrentLogType:(id)a0;
- (BOOL)needServiceManager;
- (id)customPageScrollFpsSceneName;
- (id)customBusinesssId;
- (Class)customDataControllerClass;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })customContentInsets;
- (double)loadMoreMarigin;
- (void)customLayoutGenerator:(id)a0;
- (BOOL)customPageEnableAutoPlay;
- (BOOL)customAutoPlayWhenAppeard;
- (BOOL)customPageEnableAsyncProcess;
- (id)customInnerFlowEnterFrom;
- (BOOL)customInnerFlowShouldShowDataModel:(id)a0;
- (id)customOuterDataModels;
- (id)customCachalotContext;
- (id)customPageScrollFpsExtraData;
- (void)customFeedWillBeginDragging:(id)a0;
- (void)customFeedDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (void)customFeedDidEndDecelerating:(id)a0;
- (void)customFeedDidEndScrollingAnimation:(id)a0;
- (void)customComponentWillBeginRenderWithViewModel:(id)a0;
- (void)customComponentDidEndDisplay:(id)a0;
- (void)customFeedDidScroll:(struct CGPoint { double x0; double x1; })a0;
- (void)customFeedWillEndDragging:(id)a0 withVelocity:(struct CGPoint { double x0; double x1; })a1 targetContentOffset:(inout struct CGPoint { double x0; double x1; } *)a2;
- (void)customDataCompletionFromFlowData:(id)a0;
- (void)customHandleScrollDidStart;
- (void)customHandleScrollDidEnd;
- (BOOL)customConcurrentChunkMachineProcess;
- (BOOL)customSetScrollViewNotReturnToTopAfterRefresh;
- (BOOL)customSyncAtMainThread;
- (BOOL)customPartReloadFilterInvalidIndexPaths;
- (BOOL)customCleanComponentCacheWhenReSearch;
- (BOOL)customOptimizeComponentClearReuse;
- (BOOL)customAnalyserFixParentMissing;
- (BOOL)customCompletionUseLayoutIfNeed;
- (BOOL)customUseSerialOperationMode;
- (BOOL)customUseNewUpdateHeightTransaction;
- (id)customSerialOperationExpireDuration;
- (id)customCreateAutoPlayHandler;
- (BOOL)customEnableFullCasePreloadMore;
- (void)customHandlePreRenderUsage:(BOOL)a0 viewModel:(id)a1;
- (BOOL)customUseUniversalReusePool;
- (BOOL)enableMutipleColumnStyle;
- (BOOL)customDisablePadSideView;
- (BOOL)needDefaultSurveyManager;
- (BOOL)isPullRefreshing;
- (void)customAnylyseResponseDataModelsReadyBlock:(id)a0 withParams:(id)a1 isLoadMore:(BOOL)a2;
- (BOOL)customCleanReuseWhenRefreshSearch;
- (void)customBeforeReloadCahcalotWithData:(id)a0 params:(id)a1;
- (void)reloadCahcalotWithData:(id)a0 viewModelsReadyBlock:(id /* block */)a1 dataModelsReadyBlock:(id /* block */)a2 completion:(id /* block */)a3;
- (BOOL)p_useFlowData;
- (void)appendWithViewModel:(id)a0 viewModelsReadyBlock:(id /* block */)a1 dataModelsReadyBlock:(id /* block */)a2 completion:(id /* block */)a3;
- (void)p_fireRealFlowDataDisplay;
- (id)covertDictToString:(id)a0;
- (BOOL)allBlockExcuted;
- (BOOL)isEmptypListWithParams:(id)a0;
- (void)setUpCachalotViewHidden:(BOOL)a0;
- (void)p_checkContentRenderStatus;
- (void)p_cleanDisplayMetricBlocks;
- (void)calculateVisibleCardShowPercent:(id)a0;
- (void)singleTapEnterDetail:(long long)a0 withExtra:(id)a1 withPlayer:(id)a2;
- (long long)awemeIndexInDisplayItems:(long long)a0;
- (BOOL)customShouldTurnOnAutoPreloadMoreWhenEndRefreshingCompleted;
- (void)endReloadDataWithParams:(id)a0;
- (void)willExecutePullRefresh;
- (BOOL)customPullRefreshRequest;
- (void)pullRefreshComplectionWithResponse:(id)a0;
- (void)endPullRefresh;
- (void)singleTapEnterDetail:(long long)a0;
- (id)dictPreCreateCardGlobalConfig;
- (id)generalVideoCardClass;
- (id)generalVideoCardImageClass;
- (BOOL)doubleColumnExperienceOptimize;
- (void)findAndReplaceAwemeList:(id)a0;
- (BOOL)needReloadAutoPlayWithCellNewHeight:(double)a0 originHeight:(double)a1 withModel:(id)a2;
- (BOOL)shouldNotActivateItem;
- (id)awemeCellFrameModelAtIndex:(long long)a0;
- (long long)columnCountForLayout;
- (void)fetchDataWithParams:(id)a0;
- (void)resetAllStatus;
- (void)searchAutoPlayMonitorDidEnterBackground;
- (void)searchAutoPlayMonitorDidBecomeActive;
- (void)searchAutoPlayMonitorDidActiveAutoPlay;
- (void)searchAutoPlayMonitorDidActiveCard;
- (void)searchAutoPlayMonitorDidCalculateCardWithshouldActiveView:(id)a0 hasStarted:(BOOL)a1;
- (id)cachalotStructUpdateTransactionWithconfig:(id)a0;
- (void)fetchDataWithKeyWord:(id)a0 enterFrom:(id)a1 extraLogParams:(id)a2 isSearchByUserClick:(BOOL)a3 animated:(BOOL)a4 commentSearchData:(id)a5 completion:(id /* block */)a6;
- (void)fetchDataWithKeyWord:(id)a0 enterFrom:(id)a1 extraLogParams:(id)a2 isSearchByUserClick:(BOOL)a3 animated:(BOOL)a4 commentSearchData:(id)a5 andParamasToEngine:(id)a6 completion:(id /* block */)a7;
- (void)slidingViewDidTransitionToVCWith:(BOOL)a0;
- (void)slidingViewDidTransitionFromVCWith:(BOOL)a0;
- (void)refreshListViewLayout:(BOOL)a0 withPosition:(BOOL)a1;
- (BOOL)disableSwitchLayout;
- (void)slidingButtonDidSelectIndex:(long long)a0 currentIndex:(long long)a1;
- (void)didCancelExecutePopAnimation;
- (void)followSearchDidCompoletion;
- (void)verticalSearchViewControllerWillDisplaying;
- (void)verticalSearchViewControllerDidDisplaying;
- (void)verticalSearchViewControllerWillEndDisplaying;
- (void)verticalSearchViewControllerDidEndDisplaying;
- (void)configSearchBarQueryContext:(id)a0;
- (void)searchBarControllerStop;
- (void)searchBarControllerDelete;
- (void)willReBuild;
- (void)containerSizeChangedWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)insertPublishComment:(id)a0 completion:(id /* block */)a1;
- (void)scrollToMultiTabHeaderCard;
- (id)fetchDataControllerLogPassback;
- (id)registerCardDict;
- (void)replaceTopOneTips;
- (double)getContainerWidthWithViewModel:(id)a0;
- (id)aiPageEnterFrom;
- (id)aigcChatMonitorTrackParams;
- (id)adShowTypeWithViewModel:(id)a0;
- (void)searchAICardWillReAnswerWithViewModel:(id)a0;
- (void)searchTopLoadingViewWithTipString:(id)a0 searchID:(id)a1;
- (void)searchTopLoadingViewClickEnabledWithSchema:(id)a0 searchID:(id)a1;
- (void)searchAutoOpenDeepThink:(BOOL)a0 searchID:(id)a1;
- (void)notiInputControllerCostAniEvent:(BOOL)a0;
- (BOOL)fetchDeepThinkIsOpen;
- (void)aiStartRequestQuery:(id)a0;
- (void)aiReceiveFirstDataWithSearchID:(id)a0 searchKeyword:(id)a1;
- (void)aiReceiveFirstDataWithSearchID:(id)a0 searchKeyword:(id)a1 isReAnswer:(BOOL)a2 extra:(id)a3;
- (void)aiReceiveDataFinishWithSearchID:(id)a0;
- (void)aiCardRenderFirstWordWithSearchID:(id)a0;
- (void)aiRenderFinishWithSearchID:(id)a0;
- (void)aiRequestFailureWithSearchID:(id)a0;
- (void)aiBusinessVirtualCardSizeChange:(struct CGSize { double x0; double x1; })a0 oldSize:(struct CGSize { double x0; double x1; })a1;
- (void)aiSmartCanvasIsReadyWithSearchId:(id)a0;
- (void)aiChatOperationIsReadyWithSearchId:(id)a0;
- (void)aigcVoiceBroadcastStartWithParams:(id)a0;
- (id)getCurrentEnterFrom;
- (void)transactionWillCommit:(id)a0;
- (void)transactionDidCommit:(id)a0;
- (void)QARoundFinish;
- (void)aiChatMultiAwemeVideoNodeInserted;
- (BOOL)isFoldForTopOneNodeWithSearchID:(id)a0;
- (void)expandTopOneNodeWithSearchID:(id)a0;
- (id)aigcCustomComponentDataModelWithViewModel:(id)a0 originData:(id)a1 dataType:(long long)a2 renderType:(long long)a3;
- (void)hasReceivedOutFoldCards;
- (BOOL)generalSearchHandleBeforeInsert:(id)a0;
- (id /* block */)customHandleCardLayoutAfterMeasure:(id)a0;
- (void)p_substituteNodesInOperationConfig:(id)a0 inTree:(id)a1;
- (id)p_fetchSubstituteNodeFor:(id)a0 fromACopyTree:(id)a1;
- (id)p_fetchSubstituteNodesArrayFor:(id)a0 fromACopyTree:(id)a1;
- (void)handleCachalotContextAfterAck:(id)a0;
- (void)chunkHandleShowResponseContainer:(BOOL)a0 params:(id)a1;
- (void)chunkHandleRecieveCardsPatchDataCalculateDataSource;
- (void)chunkHandleRecieveCardsPatchData:(id)a0;
- (void)chunkHandleFirstResponse:(id)a0;
- (void)chunkHandleReplaceResponse:(id)a0 allowShow:(BOOL)a1 rootModel:(id)a2 useCSP2:(BOOL)a3 chunkIndex:(long long)a4;
- (void)chunkHandleReplaceResponse:(id)a0 allowShow:(BOOL)a1 rootModel:(id)a2 useCSP2:(BOOL)a3;
- (void)chunkHandlePredictAppendViewModel:(id)a0 chunkIndex:(long long)a1;
- (void)chunkHandlePredictAppendViewModel:(id)a0;
- (void)chunkHandlePredictDeleteCards:(id)a0;
- (void)chunkHandlePredictDeleteCards:(id)a0 chunkIndex:(long long)a1;
- (void)chunkHandlePredictReorderCards:(id)a0 patchModel:(id)a1 chunkIndex:(long long)a2;
- (void)chunkHandlePredictPatchCards:(id)a0;
- (void)switchSearchLayoutAccordingToResponse;
- (void)handleGlobalChunk:(id)a0;
- (id)fetchAllLeafGeneralSearchModel;
- (id)fetchAllLeafArrayWithModernFeedType;
- (BOOL)searchBarHasAiSwitchBtn;
- (void)ssrHydrate;
- (void)startGlobalVoiceBroadcastWithSearchID:(id)a0;
- (void)stopGlobalVoiceBroadcast;
- (void)startVoiceBroadcastWithSearchID:(id)a0;
- (void)tryToLocateAndRefreshAfterAuth;
- (id)fetchAllLeafModernFeedModel;
- (long long)findIndexOfModelInVC:(id)a0;
- (long long)getTransitionIndex;
- (void)customHandleRecoverFoldContent:(id)a0 completion:(id /* block */)a1;
- (void)customHandleAIGCUnFoldWithFoldIds:(id)a0 removeNode:(id)a1 searchId:(id)a2;
- (void)clearCacheSizeAndReloadWithViewModel:(id)a0 animated:(BOOL)a1;
- (void)cardFeedBackAction:(id)a0;
- (void)trackDoubleColimnEnterEvent;
- (void)handleCardFeedBackTrackEventWithExtraParams:(id)a0 errorType:(id)a1 deleteList:(id)a2;
- (void)refreshVisbleComponetIndex;
- (id)fetchValidResponse:(id)a0;
- (void)markFeedInitialData:(id)a0;
- (void)generateActuralCardArrayForResponseModel:(id)a0 isLoadMore:(BOOL)a1 fromExtraStruct:(BOOL)a2;
- (id)refreshPathOptimizeInfo;
- (BOOL)enableUploadErrorInfo;
- (void)checkAndRecordPaymentAweme:(id)a0 inCard:(id)a1;
- (void)resetWaterfallStatus;
- (id)dynamicTabParamsWithInitialParams:(id)a0 context:(id)a1;
- (id)currentVerticalKeyword;
- (long long)findIndexOfModel:(id)a0;
- (void)fetchDynamicTabsWithCompletion:(id /* block */)a0;
- (void)cancelDynamicTabTask;
- (BOOL)superAgentIsOpen;
- (void)reportTagsFromComponentToVCWithTags:(id)a0 searchID:(id)a1;
- (BOOL)openAutoPlayMonitor;
- (void)handleGlobalReuseComponent:(id)a0;
- (id)metaForCellModel:(id)a0;
- (void)preRenderComponent:(id)a0;
- (id)getFingerprintFromCell:(id)a0;
- (void)preRenderWithModel:(id)a0;
- (void)fixRankAndCurrentIndex;
- (id)fetchOffScreenLeafModels;
- (id)preRenderViewModel:(id)a0 isDeletedFingerprint:(id /* block */)a1;
- (void)preRenderTreeModel:(id)a0 dataPreHandleBlock:(id /* block */)a1 isDeletedFingerprint:(id /* block */)a2 completion:(id /* block */)a3;
- (void)updateFingerprintAndModelTableWithModel:(id)a0;
- (void)appendPreRenderTreeModel:(id)a0 dataHandler:(id /* block */)a1 isDeletedFingerprint:(id /* block */)a2 completion:(id /* block */)a3;
- (void)deleteSectionsWithFingerprints:(id)a0;
- (void)reorderSectionsWithFingerprints:(id)a0 patchModel:(id)a1;
- (void)patchPredictedSections:(id)a0;
- (void)calculateMetaForModels:(id)a0;
- (void)preRenderPredictedTreeModel:(id)a0 isDeletedFingerprint:(id /* block */)a1 completion:(id /* block */)a2;
- (void)willRenderPredictedSections;
- (void)cellModelUIInfoWith:(id)a0;
- (void)clearPredictedSections;
- (id)fetchPreRenderComponentWithViewModel:(id)a0;
- (id)findSelectTabCardComponentViewModel;
- (BOOL)p_isHotSpotFusionTabWithAnchorModel:(id)a0;
- (id)p_findHotSpotFusionAnchorWithTabModel:(id)a0;
- (id)p_firstViewModelAfterAnchor:(id)a0;
- (BOOL)p_isUGCTopicTabWithAnchorModel:(id)a0;
- (id)p_findUGCTopicAnchorWithTabModel:(id)a0;
- (void)handleInsertCardsOperateWithInsertModel:(id)a0 anchorModel:(id)a1 completion:(id /* block */)a2;
- (id)findCardsViewModelWithComponentRenderModelSelectionBlock:(id /* block */)a0;
- (void)handleVoteCardPublishCommentNotification:(id)a0;
- (id)findViewModelsArrayAfterSelectTabCard;
- (id)currBusinessConfigModel;
- (long long)initialIndexInSearchOutStream;
- (long long)enterFeedIndexWithAweme:(id)a0;
- (id)setupFeedFallThroughWithParams:(id)a0;
- (void)setInitialIndexInSearchOutStream:(long long)a0;
- (id)createDetailVCWithVideos:(id)a0 logExtra:(id)a1;
- (void)cardFeedBackDeleteAction:(id)a0;
- (void)addDoubleColumnStatusBlockWithFeed:(id)a0;
- (id)createDetailVCWithWithLogExtra:(id)a0;
- (BOOL)hasDuplicateItem:(id)a0;
- (BOOL)isCurrentItemIndoubleColumn:(id)a0;
- (long long)multiFeedIndexWithOffset:(long long)a0;
- (void)onLongVideoLockNotification:(id)a0;
- (void)onMixVideoTableViewControllerRefreshDataNotification:(id)a0;
- (void)onPlayletVideoTableViewControllerRefreshDataNotification:(id)a0;
- (void)refreshAllTargetPMTAwemeListByIdentify:(id)a0 type:(unsigned long long)a1;
- (void)addPaymentVideoObserver;
- (void)removePaymentVideoObserver;
- (void)showWaterfallClickRecomCardIfNeed;
- (void)showRecommendWords:(long long)a0 fromGroupId:(id)a1 trendingSource:(id)a2 generalSearchModel:(id)a3 realComponent:(id)a4;
- (void)showRecommendWordsWithAwemeModel:(id)a0 fromGroupId:(id)a1 currentIndex:(long long)a2 generalSearchModel:(id)a3 realComponent:(id)a4;
- (BOOL)enableSearchRecommendForAweme:(id)a0;
- (void)sendRecommendWordsParamsInCustomEnv:(id)a0 params:(id)a1;
- (void)fetchRecommWordsWithQuery:(id)a0 index:(long long)a1 businessId:(id)a2 fromGroupId:(id)a3 pd:(id)a4 categoryName:(id)a5 trendingSource:(id)a6 searchPosition:(id)a7 adId:(id)a8 penetrateParams:(id)a9 searchId:(id)a10 awemeModel:(id)a11 completion:(id /* block */)a12 extraCallBack:(id /* block */)a13;
- (BOOL)shouldAvoidInWaterfallCardWithFromGroupId:(id)a0 searchId:(id)a1 docType:(long long)a2 insertIndex:(long long)a3 extraParams:(id)a4;
- (BOOL)shouldAvoidInSingleCardWithFromGroupId:(id)a0 searchId:(id)a1 docType:(long long)a2 insertIndex:(long long)a3 lastSearchModel:(id)a4 nextSearchModel:(id)a5 extraParams:(id)a6;
- (id)buildRecommWordsModelWithJSONObject:(id)a0 complete:(id /* block */)a1;
- (void)insertWaterfallClickRecomCardWithModel:(id)a0 atIndex:(long long)a1 clickIndex:(long long)a2 extraParams:(id)a3;
- (void)insertRecommWordsModel:(id)a0 atIndex:(long long)a1;
- (BOOL)isCurrentCard:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 neighbourWithCard:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (double)xDistanceBetween:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 and:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (double)yDistanceBetween:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 and:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (BOOL)isYIntersectAnd50PercentAbove:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0 withTarget:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a1;
- (void)updateWaterfallClickRecomCardRealHeightWithModel:(id)a0 indexToInsert:(long long)a1 extraParams:(id)a2;
- (void)p_doFakeTransationWithClickRecomCardWithModel:(id)a0 atIndex:(long long)a1 clickIndex:(long long)a2 extraParams:(id)a3 completion:(id /* block */)a4;
- (BOOL)shouldAvoidWaterfallRelatedSearchCardWithInsertIndex:(long long)a0;
- (BOOL)shouldAvoidRecomCardOfVisibleCells;
- (BOOL)shouldAvoidInvisibleCard;
- (BOOL)shouldAvoidTheLastTwoCards;
- (void)onRecommendWordAction:(id)a0;
- (void)showRecommendWordsInCustomEnv:(long long)a0 params:(id)a1 displayItems:(id)a2 completion:(id /* block */)a3;
- (void)ugcTopic_handleInsertSingleCardBeforeAnchorWithInsertModel:(id)a0 completion:(id /* block */)a1;
- (void)ugcTopic_handleInsertDoubleCardBeforeAnchorWithInsertModel:(id)a0 completion:(id /* block */)a1;
- (id)ugcTopic_findFirstDoubleColumnCardViewModel;
- (id)ugcTopic_findFirstSingleColumnCardViewModel;
- (BOOL)enableFixTransactionParentMissing;
- (void)configLayoutViewInject;
- (void)handleGeneralSearchEnterCardDetailNotification:(id)a0;
- (void)showHouseAreaFilterSheet:(id)a0;
- (void)p_handleJumpToFusionPageNotification:(id)a0;
- (void)scrollQuestionnaireCardWithNotification:(id)a0;
- (void)p_handleProposePublishTaskFromCardNotification:(id)a0;
- (void)handleSearchRefreshMonitorStartNotification:(id)a0;
- (void)saveCurrentLayoutTypeInfo;
- (void)initialfoldToUnfoldBlock;
- (void)setPreRenderEnable:(BOOL)a0;
- (BOOL)enablePadSearchMultipleStyle;
- (void)configLoadMoreFooter;
- (void)doCommonInit;
- (void)configFloatingHeader;
- (void)configAutoPlayHandler;
- (void)setupGeneralSearchCommonRerankManager;
- (void)setupCommonFeatureManager;
- (BOOL)preRenderEnableSetting;
- (void)preRenderRegisterFeature;
- (void)recaculateFullScreenColorHeight;
- (void)calculateWaterfallBackgroundViewTopOffset;
- (id)preloadSceneID;
- (void)setupBottomDoubleColumnButton;
- (void)setupBottomDoubleColumnSwitch;
- (void)addGlobalComponentToReusePoolIfNeed;
- (void)addCollegeSummaryEntranceObserverIfNeed;
- (BOOL)enableGeneralSearchTabScrollHide;
- (void)handleScrollPanGesture:(id)a0;
- (void)cardFeedbackDeleteNotification:(id)a0;
- (void)handleClickTipsRefresh;
- (void)changeSearchBackground:(id)a0;
- (void)searchInnerFlowDetailControllerWillDisplayingCell:(id)a0;
- (void)exitDoubleColimnIfNeed:(id)a0;
- (void)resetAigcSummaryEntryTimer:(id)a0;
- (id)fetchSearchModelWithIndex:(long long)a0;
- (void)deleteItemsAtIndexes:(id)a0 onlyDeleteChild:(BOOL)a1 animated:(BOOL)a2 completion:(id /* block */)a3;
- (void)didStarShowing;
- (void)correctSearchMuteStatus;
- (void)removePOITopBarIfNeeded;
- (void)updateFilterToDataController;
- (void)immersiveContainerViewWillAppear:(BOOL)a0;
- (void)cancelMusicPlay;
- (void)updateCurrentScrollViewBgAlphaPercent;
- (void)searchMuteIconShow;
- (void)setupPadSingleListWith:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })a0;
- (void)setupPadMultipleListWith;
- (void)updateVerticalViewLayoutForPresentContainer;
- (BOOL)enableUpdateUIForViewChange;
- (BOOL)fixFullPageAutoPlayError;
- (void)p_setupWaterfallRecommendWordsManager;
- (void)immersiveContainerViewDidAppear:(BOOL)a0;
- (BOOL)hasDoubleColumnCard;
- (void)startAigcSummaryEntryTimer;
- (void)handleCouponPopTask;
- (void)immersiveContainerViewWillDisappear:(BOOL)a0;
- (void)cancelVoiceSearchIfNeeded;
- (void)pauseAigcSummaryEntryTimer;
- (void)immersiveContainerviewDidDisappear:(BOOL)a0;
- (void)clearWaterfallFeelGoodLynxViewAtIndex:(long long)a0;
- (void)dualLaoyoutViewInjectConfig;
- (void)singleLayoutViewInjectConfig;
- (BOOL)searchCardAddQuestionnaire;
- (double)getRecommendWordsHeightWithViewModel:(id)a0 cellModel:(id)a1;
- (id)convertToStringWithDict:(id)a0;
- (void)trackReRankIndexErrorInfo:(id)a0;
- (void)diffModelResult:(id)a0 withResults:(id)a1;
- (void)clearFoldableCardInfoTable;
- (void)resetCurrentLayoutTypeInfo;
- (void)resetRecordsInInnerFlowBackupMap;
- (BOOL)fixFullPageAutoPlay;
- (id)buildQueryCard;
- (void)startSearch:(id)a0;
- (void)realSearch:(id)a0;
- (void)addTitleCard:(id)a0 complete:(id /* block */)a1;
- (void)startSuperAgentQuery:(id)a0;
- (void)configFilterAnimation;
- (void)togglePullRefreshHeaderEnable:(BOOL)a0;
- (void)trackDoubleColimnExitEventWithKeyword:(id)a0;
- (void)removeCurrentVisibleRecommendWordsCard;
- (BOOL)shouldShowLayoutSwitchButton;
- (void)setFooterContentInset;
- (void)updateFloatingHeaderTop:(double)a0 animated:(BOOL)a1;
- (BOOL)enableRequestWithParamPreSearchID;
- (void)cancelVoiceSearchForBottomIfNeeded;
- (void)preloadSingleVideoCoverForScrollStart;
- (BOOL)fixTop1DefaultFoldError;
- (void)removeTopOneFoldCardDivideGradientView;
- (void)p_handleAfterDataControllerJustRefresh:(id)a0 error:(id)a1 passingCompletion:(id /* block */)a2 needBadNetworkView:(BOOL)a3 params:(id)a4;
- (void)p_networkMonitorRequestWithResponseParams:(id)a0 isLoadMore:(BOOL)a1;
- (void)adjustPendantsShowPriorityIfNeed;
- (long long)realColumnCount;
- (void)applyDynamicLoadmoreMargin:(double)a0;
- (double)loadMoreMariginWithIsDoubleColumn:(BOOL)a0;
- (void)refreshCachalotComplectionWithDataList:(id)a0;
- (void)updateCommerceResponseParams:(id)a0;
- (BOOL)searchImersiveEnable;
- (void)updateHelpPublishSearchParams;
- (id)p_generateGSHeightMetric;
- (void)p_sendExactCardHeightMetricsWithInfos:(id)a0;
- (void)excuteCommonPreRenderIsList:(BOOL)a0 renderList:(id)a1 upDocCnt:(long long)a2 downDocCnt:(long long)a3;
- (void)addPrelayoutTaskInMainIdle;
- (void)addPreCreateCardUITask;
- (void)executeSmartPreloadSubPages;
- (void)updateFilterToRefreshFooter;
- (void)tryCommerceRerankWithTriggerSource:(long long)a0 viewModels:(id)a1;
- (void)triggerCommonFeatureForLoadmoreWithResponse:(id)a0 models:(id)a1;
- (void)preloadSingleVideoCoverForLoadMoreWithModels:(id)a0;
- (void)prefetchImageForLoadMoreWithViewModels:(id)a0;
- (id)fetchAllLeafArrayWithGeneralSearchModelType;
- (id)fetchGeneralSearchModelLeafArr;
- (void)preloadSearchADImageIfNeededWithCurrentDisplayIndex:(unsigned long long)a0;
- (void)p_handleCustomComponentWillDisplay:(id)a0 withViewModel:(id)a1;
- (void)handleAttachmentCellControllerWillDisplaywithViewModel:(id)a0;
- (id)awemeCellFrameWithModel:(id)a0;
- (id)cellBackgroundModelForQualityWithCellModeModel:(id)a0;
- (BOOL)isFlowDataFinishRender;
- (void)fetchSearchFeatures;
- (void)checkDoubleColumnBoundaryWithViewModel:(id)a0 component:(id)a1;
- (BOOL)isSingleRangeAtNewGeneralLayoutWithViewModel:(id)a0;
- (void)cacheAwemeModelIfNeededForAdBrandAiWithModel:(id)a0;
- (void)appendSearchCommonRerankInfoWithModels:(id)a0 response:(id)a1;
- (id)sectionSearchType;
- (void)cardFeedBackDeleteAction:(id)a0 onlyDeleteChild:(BOOL)a1;
- (BOOL)enableLiveReuseErrorFix;
- (long long)backupInnerPositionFromOutPosition:(long long)a0;
- (id)liveCellModelAtIndex:(long long)a0;
- (void)p_trackFirstCardLogDatasWithSearchModel:(id)a0;
- (void)handleAttachmentCellControllerEndDisplaywithViewModel:(id)a0;
- (void)prefetchImageForRenderBeginWithViewModels:(id)a0 currentIndex:(long long)a1;
- (void)fetchRecommWordsWithKeyword:(id)a0 awemeModel:(id)a1 extraParams:(id)a2;
- (BOOL)judgeRecommTypeWithCurrentIndex:(long long)a0 indexSet:(id)a1;
- (BOOL)isIllegalIndex:(long long)a0 withDataArray:(id)a1 andPosition:(long long)a2;
- (void)resetSearchBackground;
- (BOOL)isGeneralSearchWaterfallLayout;
- (BOOL)isSingleCardAtNewGeneralLayoutWithIndex:(long long)a0;
- (id)loadmoreMarginConfig;
- (void)smartLoadMoreIfNeededWithSpeed:(double)a0;
- (void)p_handleFloatingHeaderTopChangeWithScrollView:(id)a0;
- (void)p_handleSuggestViewTopChangeWithScrollView:(id)a0;
- (void)updateBackgroundViewContentOffsetForScrollViewChanged:(id)a0;
- (void)updateFullpageTitleBarContentOffsetWith:(id)a0;
- (void)handleVerticalScroll:(id)a0;
- (void)p_handleVoiceSearchEntranceStateWithScrollView:(id)a0;
- (void)tryShowDoubleColumnButton;
- (void)aigcSummaryEntryViewSwitchToWeakStyleIfNeeded;
- (void)handleFoldTipsScroll:(id)a0;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })fullPageGeneralSearchContentInset;
- (BOOL)fixGeneralFoldTipsShowError;
- (void)findFoldAbleNodeWithCompletion:(id /* block */)a0;
- (unsigned long long)calculateViewHierarchyMemory:(id)a0;
- (BOOL)isNeedToShowVoiceSearch;
- (void)imersiveHandleScrollWithScrollView:(id)a0;
- (void)updateWaterfallBackgroundViewFrame:(struct CGPoint { double x0; double x1; })a0;
- (void)p_triggerAppearAnimForTopicButtonWithScrollView:(id)a0;
- (void)p_triggerAppearAnimForHotSearchBottomButtonWithOffset:(struct CGPoint { double x0; double x1; })a0;
- (void)p_triggerFoldAnimForTopicButtonFoldWithOffset:(struct CGPoint { double x0; double x1; })a0;
- (id)bottomButtonAb;
- (void)showBottomDoubleColumnSwitchIsScroll:(BOOL)a0;
- (void)cleanupRecommWordsItemsIfNeeded;
- (void)handleNewUserGuide;
- (void)closeCollegeSummaryEntranceViewIfNeed;
- (void)prefetchImageForEndDecelerateWithViewModels:(id)a0 currentIndex:(long long)a1;
- (void)adjustFullPageGeneralSearchContentInset;
- (void)fixDoubleColumnBoundaryOffsetWith:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })a0;
- (void)layoutTopLoadingViewFrame;
- (void)updateSuggestViewTop:(double)a0;
- (double)POIAuthTopBarHeight;
- (id)fetchAutoPlayComponent:(long long)a0;
- (BOOL)customHandleWaterFallFeedGoodIndex:(long long)a0;
- (id)fetchCellControllerWithIndex:(long long)a0;
- (id)buildRecommWordsModelWithJSONObject:(id)a0;
- (id)feedGid;
- (void)collegeSummaryEntranceTransitionToState:(unsigned long long)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })collegeSummaryEntranceViewFrameForState:(unsigned long long)a0;
- (void)destroyCollegeSummaryEntranceView;
- (void)setupCollegeSummaryEntranceViewIfNeed;
- (void)collegeSummaryEntranceDidShowForState:(unsigned long long)a0;
- (id)collegeSummaryEntranceCommonEventParams;
- (id)getAwemeModelForRecommendWordsWithDataModel:(id)a0;
- (id)buildRecomWordsLogCommonParamsWithLastModel:(id)a0 awemeModel:(id)a1 query:(id)a2 extraParams:(id)a3;
- (id)buildRecomWordsTrackerExtraParams:(id)a0;
- (void)reloadRecommendWordsWithIndex:(long long)a0 cardHeight:(double)a1 animated:(BOOL)a2 needRemove:(BOOL)a3;
- (BOOL)searchEngineForceLayoutAfterPerformBatchUpdates;
- (id)containerServices;
- (BOOL)generalCachalotSearchDisablePadSideView;
- (double)getCustomContentInsetTop;
- (void)processGuideSearch;
- (void)updateFixUIChangeOffset:(BOOL)a0;
- (void)adjustContentInset;
- (void)processVirtualGS;
- (id)generalSearchServiceManager;
- (id)p_buildUpdateHeightOperationConfigWithViewModel:(id)a0 preparedBlock:(id /* block */)a1;
- (void)updateTopOneFoldCardDivideGradientViewFrame;
- (void)clearCacheSizeAndReloadWithViewModels:(id)a0 animated:(BOOL)a1 extraOperationConfig:(id)a2;
- (void)p_doFakeTransationWithViewModel:(id)a0 completion:(id /* block */)a1;
- (void)customHandleReloadCurrentSectionWithIndex:(long long)a0 animated:(BOOL)a1;
- (void)clearCacheSizeAndReloadWithViewModels:(id)a0 animated:(BOOL)a1;
- (BOOL)activityTopOne;
- (void)reloadAutoPlayIfNeededWithViewModel:(id)a0 originHeight:(double)a1;
- (id)p_buildUpdateHeightTransactionConfigWithViewModels:(id)a0;
- (void)customHandleScrollToDisplayItemWithOffset:(double)a0 index:(long long)a1 animated:(BOOL)a2 completionBlock:(id /* block */)a3;
- (void)clearWaterfallRecommendwordsIfNeededAtIndex:(long long)a0;
- (void)showRecommendWordsForSectionIndex:(long long)a0 params:(id)a1 completion:(id /* block */)a2;
- (BOOL)searchFeedbackDelCardInnerBlankScreen;
- (BOOL)checkSearchFeedbackDelCardInnerBlankScreenRequired:(long long)a0;
- (void)startAutoPlayMonitorWithExtraDic:(id)a0;
- (void)willTransitionBackToVideoFeedWithSection:(long long)a0;
- (void)activeCardIndex:(long long)a0;
- (BOOL)syncTransitionUpdateOffset;
- (BOOL)fixGSCoverCard;
- (void)transitionBackToVideoFeedWithSection:(long long)a0;
- (BOOL)isDualColumnPlayHighlightEnableWithIndex:(long long)a0;
- (void)willTransitionBackFromLiveFeedWithSection:(long long)a0;
- (BOOL)isSingleRangeAtNewGeneralLayoutWithIndex:(long long)a0;
- (id)extendTransitionContext;
- (BOOL)enableModernFeedSafe;
- (void)uploadErrorInfo:(id)a0;
- (BOOL)enableStackSymbolsTrans;
- (id)transStackSymbols:(id)a0;
- (BOOL)useDefaultPullRefresh;
- (void)businessCustomPullRefresh;
- (unsigned long long)preferSearchTheme;
- (BOOL)isOnTopic;
- (void)p_registerCallbackFor:(id)a0;
- (void)p_registerCallbackForView:(id)a0;
- (void)reloadDataWithParams:(id)a0 rootModel:(id)a1 completion:(id /* block */)a2;
- (id)buildCachalotDataWithResponseParams:(id)a0;
- (id)fetchRealResponse:(id)a0;
- (void)checkAwemeChunkDataWithRawData:(id)a0;
- (void)processGuideSearchForFixUIChangeOffset:(BOOL)a0;
- (BOOL)syncScrollviewOffsetFixInCSP2;
- (BOOL)top1TriggerTipsCardEnable;
- (void)insertTriggerTipsToRoot:(id)a0;
- (void)p_updateVerticalBottomBarForChunk:(id)a0;
- (void)p_updateTopViewTipsWithParams:(id)a0;
- (BOOL)enableSearchTopicPublishOptimize;
- (BOOL)fixImmersiveBackground;
- (void)updateGlobalUIForRefresh:(BOOL)a0;
- (void)p_handleFirstScreenPreciseHeightProcess;
- (void)p_cleanChunkPreRenderCache;
- (void)cleanSearchBackgroundColor;
- (void)restSuggestView;
- (void)resetAllDisplayItemsContextAndClearData;
- (void)handleCardInfo:(id)a0 cardCreateKey:(id)a1 cardBindKey:(id)a2 cardCountKey:(id)a3;
- (void)prefetchImageForChunkPredictWithViewModels:(id)a0;
- (BOOL)fixFullPageLoadingJumpError;
- (void)removeSearchImmersive;
- (void)p_sendFirstScreenWithWhiteSpaceDuration;
- (void)prefetchImageForChunkAppendWithViewModels:(id)a0;
- (BOOL)clearReusePoolIfNeeded;
- (BOOL)fixUserbackBackgroundColor;
- (void)resetAllDisplayItems;
- (void)resetAllDisplayItemsAndContext;
- (void)p_chunkHandleShowResponseContainer:(BOOL)a0 params:(id)a1 completion:(id /* block */)a2;
- (void)configFilter;
- (void)handleChunkModel:(id)a0 byAwemeModel:(id)a1;
- (BOOL)enableVideoPreloadV2;
- (void)triggerUserDenyAction:(id)a0;
- (void)removePOIAuthTopBar;
- (BOOL)p_isUsingFlowData;
- (void)chunkHandleResponseError:(id)a0;
- (void)updateTabLine;
- (BOOL)p_enableFixLoadmoreCrash1740;
- (void)resetAllDisplayItemsAndClearData;
- (BOOL)didHitPredictACK;
- (void)setBadNetworkViewWithError:(id)a0 currentList:(id)a1;
- (id)buildTriggerViewModel;
- (id)buildTopOneViewModel;
- (void)insertFlodBlankCardWithViewModel:(id)a0 foldableData:(id)a1 subtractionHeight:(double)a2;
- (id)initializeFoldInfoAndHandleTruncationForAllNodes:(id)a0;
- (void)removeTaskWithContainer:(id)a0;
- (void)displayPOIAuthTopBar;
- (BOOL)triggerPoiCouponAction:(id)a0 popID:(id)a1;
- (void)updateSearchStrengthenColorToLight:(BOOL)a0;
- (BOOL)enableDynamicTabRequest;
- (void)configSearchCommonRerankInfoWithSearchTime:(double)a0 response:(id)a1;
- (void)triggerSearchCommonFeatureWithSearchTime:(double)a0 response:(id)a1;
- (void)p_handleDataRefreshCompletionWithList:(id)a0 currentTime:(double)a1;
- (BOOL)fixLoadmoreCardError;
- (void)insertLoadmoreCard;
- (void)p_handleDataRefreshCompletionWithList:(id)a0 currentTime:(double)a1 fromSubChannel:(id)a2 toSubChannel:(id)a3 enterMethod:(id)a4;
- (void)showAIGCSummaryEntryViewIfNeeded;
- (void)preloadSingleVideoCoverForChunkCompleteWithModels:(id)a0;
- (void)aigcEntryViewClick;
- (void)updateAigcSummaryEntryTimer;
- (void)showBlankViewWithHotSearch:(BOOL)a0;
- (void)addShowEggToDic:(id)a0;
- (void)handleSearchAfterRead;
- (void)handleSiriSuggestion;
- (void)trackMaskedRecommendWordsShowIfNeeded;
- (void)trackEcomMaskedRecommendWordsShowIfNeeded;
- (BOOL)checkHitLimit;
- (void)setCancelMuteViewFrame;
- (void)setBottomDoubleColumnButtonFrame;
- (void)handleSuggestView;
- (void)showVoiceSearchEntrance;
- (BOOL)isCellItemRenderingByDynamicController:(id)a0;
- (BOOL)isCellItemRenderingByLynxController:(id)a0;
- (void)updateSearchBackgroundOriginYWithOffset:(struct CGPoint { double x0; double x1; })a0;
- (BOOL)enablePresentContainerAnimationOpt;
- (void)checkHarmfulCategory;
- (void)removeNotShowDisplayItemFromDataSource;
- (Class)cellItemRenderingControllerClass:(id)a0;
- (BOOL)enableMaskTrackWithEnterMethod:(id)a0;
- (void)resetTimeLimitSelection;
- (BOOL)addDetailInfoToErrorPage;
- (void)updateFilterViewRedDot;
- (BOOL)checkFloatingHeaderType;
- (BOOL)isAppearingUnderContentSheet;
- (double)searchResultContentHeight;
- (BOOL)fixSearchBackgroundColorZeroHeight;
- (void)cleanHeaderBackground:(BOOL)a0;
- (void)updateImmerSiveHidden:(BOOL)a0;
- (double)fullScreenCellHeight;
- (BOOL)isInFloatingBgColor;
- (void)updateImmersiveFrameWithModel:(id)a0;
- (BOOL)fixImmersivePlayError;
- (void)setupSearchImmersiveWithModel:(id)a0;
- (void)updateSearchImmersiveWithModel:(id)a0;
- (void)trackGuidSearchTrendingShowWithEventName:(id)a0;
- (void)trackGuideSearchTrendingWordsShowMaskedWithModel:(id)a0 index:(long long)a1;
- (void)foldTopTipViewDidClick;
- (BOOL)fixMoodSettingColor;
- (void)clickBottomDoubleColumnSwitch;
- (void)didTappedMuteView;
- (void)searchMuteIconClick:(BOOL)a0;
- (void)reopenMuteView;
- (BOOL)needAvoidBottomFrame;
- (void)openEasterEgg;
- (BOOL)truellyShowEasterEggView:(id)a0 type:(long long)a1;
- (id)ugcTopicPublishHelper;
- (id)hotSearchPublishHelper;
- (id)hotSearchService;
- (id)hotSearchTrackParams;
- (void)_configurationAccessibilityElements;
- (void)adjustLayoutForPOITopBarView;
- (void)setFloatingHeaderAlpha:(BOOL)a0 top:(double)a1;
- (void)updateFoldTipsWithTop:(double)a0 animated:(BOOL)a1;
- (void)updateHelpPublishHeaderWithFloatHeaderTop:(double)a0;
- (void)updateCommonEasterEggWith:(id)a0;
- (void)updateHotSpotPublishEntranceView;
- (void)updateSearchAdPendantViewWith:(id)a0;
- (void)configAIModeManagerWith:(id)a0;
- (void)onVideoDownloadFinished:(id)a0;
- (void)prefetchVideo;
- (void)prefetchVideoForModel:(id)a0;
- (void)startVideoPrefetch;
- (id)getHistoryAttibuteText;
- (id)filterHintAttributeText;
- (void)showRecommWordsWithModel:(id)a0;
- (void)resetThemeStyleForDisplayItems;
- (void)updateSearchStrengthenColorWithAlpha:(double)a0;
- (void)syncThemeStatusForDisplayItems;
- (void)switchToSingleColumn;
- (void)doubleColumnSwitchWithSource:(id)a0;
- (void)p_getCurrentScreenCardInfoForRefreshMonitor:(id *)a0 andExactlyHeightCardInfoArray:(id *)a1;
- (id)p_getFirstScreenPreciseHeightInfoToSync:(id)a0;
- (id)p_exactCardHeightInfoWithViewModel:(id)a0;
- (BOOL)exactCardHeightInfoAddFPMD5;
- (id)p_getAllBusinessModels;
- (id)getCommonRerankFeatureModelWithResponse:(id)a0;
- (void)diffModelForRerankWithResult:(id)a0 withResults:(id)a1 withIsDummy:(BOOL)a2;
- (void)trySearchCommonRerankWithTriggerType:(unsigned long long)a0 viewModels:(id)a1;
- (BOOL)enableSearchCommonBaseFeatureClient;
- (id)p_getQueryInfoWithResponse:(id)a0;
- (void)deleteItemsAtIndexes:(id)a0 insertItems:(id)a1 atIndexes:(id)a2;
- (void)rerankItem:(id)a0 realRankItems:(id)a1 atIndexes:(id)a2 filteredToRaw:(id)a3;
- (id)convertDictKeyToString:(id)a0;
- (void)resetWaterfallBackgroundView;
- (BOOL)isWaterfallLayoutWithIndex:(long long)a0;
- (long long)dataModelIndexTolistViewIndex:(long long)a0;
- (long long)listViewIndexToDataModelIndex:(long long)a0;
- (void)refreshListViewLayoutBySearchResult:(BOOL)a0;
- (void)clearWaterfallBackgroundView;
- (void)switchDualLayout:(BOOL)a0 autoPlayAfterRefresh:(BOOL)a1;
- (void)resetFooterTextForFilterSelection;
- (void)resetDoubleColumnVariable;
- (BOOL)p_enableAutoplayFlingOptimize;
- (BOOL)generalCachalotSearchAutoplayFix_v3;
- (BOOL)generalCachalotSearchAutoplayFix_v4;
- (void)startAutoPlayMonitorWithSubScene:(id)a0;
- (void)registerFeatureWithBusinessName:(id)a0 featureName:(id)a1 registerBlock:(id /* block */)a2;
- (void)setupCommonPreRenderManager;
- (void)excuteCommonPreRenderWithRenderList:(id)a0;
- (void)removeFoldBlankCard;
- (void)callSuperAppendWithViewModel:(id)a0 viewModelsReadyBlock:(id /* block */)a1 dataModelsReadyBlock:(id /* block */)a2 completion:(id /* block */)a3;
- (void)p_doFakeTransaction:(id)a0 isOnScreen:(BOOL)a1 completion:(id /* block */)a2 didClickShowBlock:(id /* block */)a3;
- (void)p_triggerBanCardInsertForObservingNode:(id)a0;
- (id)findFoldableCardInfoModel:(id)a0;
- (void)trackClickFoldShowAllButton:(id)a0 withEvent:(id)a1;
- (void)aigcShowMoreButtonClickWithViewModel:(id)a0;
- (BOOL)fixTopOneGradientPosition;
- (void)addTopOneFoldCardDivideGradientView;
- (BOOL)p_nodeIsFromAI:(id)a0;
- (BOOL)p_nodeIsFromGeneral:(id)a0;
- (BOOL)enableTopOneFoldButtonOptimize;
- (BOOL)p_getTop1AutoExpandIfShownWithViewModel:(id)a0;
- (BOOL)p_fixTop1UseOffscreenTransactionToInsertBlankCard;
- (BOOL)userEnableAIStatus;
- (void)openCotPanelViewWithConfig:(id)a0;
- (void)p_handleTop1AdCardBeforeInsertWithSearchModel:(id)a0 vm:(id)a1;
- (void)updateFoldLoading:(BOOL)a0;
- (id)findFirstDualCard;
- (void)updateFoldableCardInfoModel:(id)a0 foldableCardInfo:(id)a1 forceUpdate:(BOOL)a2;
- (BOOL)checkIfParsedViewModel:(id)a0;
- (id)p_parseFoldableDataFromComponentData:(id)a0;
- (void)insertFlodBlankCardWithViewModel:(id)a0 foldableData:(id)a1;
- (void)addFoldEnableCardHeightObserbation:(id)a0;
- (void)buildInitialFoldabelInfoModel:(id)a0 didClickShowBlock:(id /* block */)a1;
- (void)addfoldGradientIconViewAndRejustFoldBlankView:(id)a0;
- (void)clearCacheAndRemoveFoldCardsFromFather:(id)a0 isOnScreen:(BOOL)a1 completion:(id /* block */)a2;
- (id)p_buildUpdateHeightOperationConfigWithViewModel:(id)a0;
- (BOOL)fixTwiceExpandView;
- (double)getFoldHeightWithFoldableInfoModel:(id)a0;
- (void)updateFoldableCardInfoModel:(id)a0 foldableCardInfo:(id)a1;
- (id)findFoldAbleNodeWithViewModel:(id)a0;
- (id)findObservingNodeWithTransactionConfig:(id)a0;
- (void)p_substituteNodesWithCardInfoModel:(id)a0 aimTree:(id)a1 offScreenNodes:(id)a2 useRepalce:(BOOL)a3 isUserRealReplace:(BOOL)a4;
- (id)clearCacheAndRemoveFoldCardsFromFather:(id)a0 isOnScreen:(BOOL)a1;
- (id)findAimNodeInOffScreenNodes:(id)a0 aimNode:(id)a1;
- (BOOL)disableAddFoldEnableCardHeightObservation;
- (BOOL)fixRebuildCacheError;
- (BOOL)isTopicScene;
- (id)fetchDataController;
- (id)sectionSearchLogPassback;
- (void)handleEnterDetailPerfWeaken;
- (void)handleWillShowFullScreenVideoFeed;
- (BOOL)syncOutsideFeedStreamReRankWithRemoveModelIndexSet:(id)a0 rankedModelIndexArr:(id)a1 insertCacheAwemeArr:(id)a2 insertCacheAwemeIndexArr:(id)a3 operateType:(long long)a4;
- (void)syncFeedData:(id)a0 feedIndex:(long long)a1;
- (id)fetchOutsideVCData;
- (id)fetchNavigationController;
- (void)innerDataControllerLoadmoreCallBackWithList:(id)a0;
- (void)didDeleteAwemeWithSyncData:(BOOL)a0 awemeID:(id)a1;
- (id)fetchAwemeModelWithIndex:(long long)a0;
- (id)fetchOutsideRequestParams;
- (id)containerView:(id)a0 creatImmersiveViewWithModel:(id)a1;
- (id)containerView:(id)a0 creatImmersiveCoverViewWithModel:(id)a1;
- (double)containerView:(id)a0 heightForImmersiveCoverViewWithModel:(id)a1;
- (BOOL)rerank_processSearchCommonRerankWithRemoveIndexSet:(id)a0 removeModelSet:(id)a1 insertIndexSet:(id)a2 insertModelSet:(id)a3 IsDummy:(BOOL)a4;
- (id)rerank_fetchModelWithDocId:(id)a0 index:(long long)a1;
- (id)rerank_getModelWithDocID:(id)a0 fromModels:(id)a1;
- (unsigned long long)rerank_getCurrentDisplayedIndex;
- (id)rerank_getAllBusinessModels;
- (BOOL)rerank_ableToReplaceWithError:(id *)a0;
- (void)rerank_reportTags:(id)a0 searchID:(id)a1;
- (void)rerank_reportDocIdListWithRawData:(id)a0;
- (void)searchAutoPlayMonitorDidScroll;
- (void)searchAutoPlayMonitorDidEndScroll;
- (void)clickLoadMore;
- (void)collegeSummaryEntranceDidUpdate:(id)a0;
- (void)summaryEntranceViewDidSelect:(id)a0;
- (void)summaryEntranceViewDidClose:(id)a0;
- (id)fetchTaskWithPopinfo:(id)a0;
- (void)fetchContentWithUGCTopicFilter;
- (id)pureInit;
- (void)cachalotClear;
- (double)getCustomizedPadContainerWidth;
- (BOOL)onlyClearNativeCard;
- (void)updateEngineData;
- (void)needAddCardComponentDataInfo:(id)a0 ToExtra:(id)a1;
- (BOOL)isAdEndorseVideo:(id)a0;
- (void)handleGSWordSelectedWithIndex:(long long)a0;
- (void)updateListViewInset;
- (BOOL)imageCardTransitionBackToOutflow;
- (long long)fetchDualCardSiteWithIndex:(long long)a0;
- (void)handleCollegeSummaryEntranceVisibilityIfNeed:(BOOL)a0;
- (id)currentSubtabName;
- (void)customHandleRegistAutoPlayDistribute:(id)a0;
- (id)findFoldNode;
- (void)customHandleReloadCurrentSectionWithViewModel:(id)a0 animated:(BOOL)a1;
- (void)updateFoldBlanckCardHeightWithSubtractionViewModel:(id)a0;
- (void)removeRecommendWordsCardWithViewModel:(id)a0 index:(long long)a1 animated:(BOOL)a2 cardHeight:(double)a3;
- (void)lynxElementDidMountWithIndex:(long long)a0;
- (void)customHandleUpdateIndex:(long long)a0 withAwemeList:(id)a1;
- (void)customHandleWillEnterFullScrrenWithIndex:(long long)a0;
- (id)customCombinateCardAwemeListWithIndex:(long long)a0;
- (void)customHandleScrollToDisplayItemWithOffset:(double)a0 index:(long long)a1 animated:(BOOL)a2;
- (BOOL)addCardTopCachalotOffset:(id)a0;
- (void)customHandleSetAttachmentData:(id)a0 index:(long long)a1 animated:(BOOL)a2;
- (long long)indexFromFilteredIndex:(long long)a0;
- (void)customHandleLoadMoreAwemeList:(id)a0 atIndex:(long long)a1;
- (void)reloadDataWithParams:(id)a0 rootModel:(id)a1;
- (void)triggerFetchData;
- (BOOL)enableNewMaskTypeWithSceneDic:(id)a0;
- (void)updateFilterSections;
- (void)checkAwemeChunkData;
- (void)shiftSearchPresentContainerView:(BOOL)a0;
- (void)tryRestoreRefreshHeaderAfterExistPresentContainerSeventhScreenMode;
- (void)resetWaterfallBackgroundConfig;
- (void)handleImmersivePlay:(BOOL)a0;
- (void)handleImmersiveBanner:(id)a0;
- (void)handleShowPendant:(id)a0;
- (void)handleImmersiveTransToBottom:(id)a0;
- (void)handleSearchChangeBackGroundColor:(id)a0;
- (void)handleSearchImmersiveOpenVideo:(id)a0;
- (void)customVideoPlayerStartPlay;
- (BOOL)enableSmartPaging;
- (void)updataEasterEggDataWithModel:(id)a0;
- (void)filterViewShowMenu:(BOOL)a0;
- (id)defaultFloatingHeader;
- (id)adInfoForAdEndorse:(id)a0;
- (void)handleUpdateIndex:(long long)a0 withAwemeList:(id)a1;
- (id)fetchCellComponentWithIndex:(long long)a0;
- (void)delayActive;
- (long long)visibleIndexOfFirstDoublerowBeforeRefreshLayout:(long long)a0;
- (long long)visibleCellIndexBeforeRefreshLayout;
- (void)positionToVisibleCellAtIndex:(long long)a0;
- (void)resetListViewLayoutConfig;
- (BOOL)useSeparateRenderIndividual;
- (void)customHandleVideoPlayerDidEndAtIndex:(long long)a0;
- (void)customHandleVideoPlayerDidPlayErrorAtIndex:(long long)a0;
- (void)customHandleTransitionBackFromInnerFeedAtIndex:(long long)a0;
- (BOOL)checkIfEnableFold:(id)a0;
- (void)searchAIGCSwitchFoldIdFromIDs:(id)a0 toIDs:(id)a1;
- (id)creatCache;
- (void)rebuidWithCache:(id)a0;
- (void)becomeActive;
- (id)visibleCells;
- (void).cxx_destruct;
- (id)gid;
- (void)viewDidLayoutSubviews;
- (void)setRefresh:(id)a0;
- (void)applicationDidEnterBackground;
- (id)init;
- (void)handleRefresh;
- (void)applicationWillResignActive;
- (id)displayItems;
- (void)fetchData;
- (void)updateBackgroundView;
- (void)applicationWillEnterForeground;
- (void)addObserver;
- (void)viewWillAppear:(BOOL)a0;
- (void)reset;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)clearAllData;
- (void)resetFilter;
- (BOOL)isActive;
- (void)deleteItemsAtIndexes:(id)a0 animated:(BOOL)a1;
- (void)viewWillDisappear:(BOOL)a0;
- (void)didEndScroll;
- (void)getAddress;
- (void)insertItemsAtIndexes:(id)a0;
- (void)updateScrollView;
- (void)pauseVideo;
- (long long)currentColumn;
- (double)containerWidth;

@end
