@class AWEVoiceSearchManager, AWESearchWebViewSecurityManager, UIViewController, AWEUITheme, UIView, UIButton, NSString, AWETrackerContext, AWESearchSugViewController, AWELifeSearchSchemaModel, AWELifeSearchBar, AWESearchSchemaModel, UIImage;
@protocol AWESearchTopBarControllerProtocol, AWESearchNewMiddleProtocol;

@interface AWELifeSearchViewController : AWESearchMultilayerViewController <AWERouterViewControllerProtocol, AWESearchMiddleProtocol, AWEBasicModeMessage, AWESearchTopBarControllerDelegate, UISearchBarDelegate>

@property (retain, nonatomic) UIButton *clearTextButton;
@property (retain, nonatomic) UIButton *returnButton;
@property (retain, nonatomic) AWELifeSearchBar *searchBar;
@property (retain, nonatomic) UIView *searchBarContainerView;
@property (retain, nonatomic) id<AWESearchTopBarControllerProtocol> topBarController;
@property (nonatomic) BOOL shouldUseNewTopBar;
@property (retain, nonatomic) AWESearchSugViewController *searchSugViewController;
@property (retain, nonatomic) UIViewController<AWESearchNewMiddleProtocol> *searchMiddleViewController;
@property (retain, nonatomic) AWESearchSchemaModel *routerModel;
@property (retain, nonatomic) AWELifeSearchSchemaModel *schemaModel;
@property (retain, nonatomic) AWETrackerContext *trackerContext;
@property (nonatomic) BOOL isVoiceSearchTracked;
@property (nonatomic) BOOL hideVoiceSearchEntrance;
@property (nonatomic) BOOL canUseVoiceSearch;
@property (retain, nonatomic) AWEVoiceSearchManager *voiceSearchManager;
@property (nonatomic) long long awemeType;
@property (copy, nonatomic) NSString *searchBarText;
@property (nonatomic) BOOL hasShow;
@property (nonatomic) BOOL isFirstSearchLaunch;
@property (retain, nonatomic) AWESearchWebViewSecurityManager *securityManager;
@property (nonatomic) BOOL keyboardIsFirstShow;
@property (retain, nonatomic) UIImage *searchIconLightImage;
@property (retain, nonatomic) UIImage *searchIconDarkImage;
@property (retain, nonatomic) UIImage *clearIconLightImage;
@property (retain, nonatomic) UIImage *clearIconDarkImage;
@property (retain, nonatomic) UIImage *returnIconLightImage;
@property (retain, nonatomic) UIImage *returnIconDarkImage;
@property (nonatomic) unsigned long long modernThemeStyle;
@property (nonatomic) long long uiThemeStyle;
@property (retain, nonatomic) AWEUITheme *globalTheme;
@property (nonatomic, getter=isViewAppeared) BOOL viewAppeared;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (copy, nonatomic) NSString *refer;

+ (Class)aAWEPadModuleAdapterClass;
+ (Class)aAWESearchViewControllerDOUYINLiteAdapterClass;
+ (Class)aAWESearchViewControllerDOUYINHTSAdapterClass;

- (BOOL)configWithRouterParamDict:(id)a0;
- (BOOL)awe_shouldAutorotate;
- (unsigned long long)awe_supportedInterfaceOrientations;
- (void)basicModeDidChange:(BOOL)a0;
- (id)aAWEPadModuleAdapter;
- (id)enterFromSecond;
- (double)searchBarHeight;
- (double)searchBarLeftMargin;
- (double)searchBarRightMargin;
- (void)privacyStateChanged:(id)a0;
- (void)refreshDefaultWord:(id)a0 searchWord:(id)a1 wordID:(id)a2 logid:(id)a3 extraLogParams:(id)a4;
- (void)hotSearchWordDidTapped:(id)a0 displayWord:(id)a1 extra:(id)a2;
- (void)resignKeyboard;
- (BOOL)isSugViewShowing;
- (BOOL)isMiddleViewShowing;
- (void)handleUIThemeChangeNotification:(id)a0;
- (void)updateWithParamDict:(id)a0;
- (void)configureSearch;
- (void)configNewSearchTheme:(unsigned long long)a0;
- (void)showSearchSugViewControllerWithKeyKeyword:(id)a0;
- (void)setupMiddleViewControllerIfNeeded;
- (void)suggestWordComplementDidTapped:(id)a0;
- (void)removeSearchSugViewControllerWithTriggeringLifeCycleMethod:(BOOL)a0;
- (void)updateMiddlePageKeyboardState;
- (id)getSugTextFieldParams;
- (long long)getCursorPosition;
- (void)updateSearchBarText:(id)a0;
- (BOOL)canShowVoiceSearchEntrance;
- (unsigned long long)searchMiddleVCInCurrentSearchTab:(id)a0;
- (id)middleRouterModel;
- (void)historyWordDidTapped:(id)a0 extraParams:(id)a1;
- (void)topBarTextDidBeginEditing:(id)a0;
- (void)topBarTextDidEndEditing:(id)a0;
- (void)topBarTextDidChange:(id)a0;
- (void)topBarReturnElementDidClicked;
- (void)topBarClearTextElementDidClicked;
- (void)topBarKeyboardSearchButtonClickedWithText:(id)a0;
- (void)prepareLynxCardResources;
- (void)suggestWordDidTapped:(id)a0 extraLogParams:(id)a1;
- (long long)obtainMiddlePageType;
- (id)aAWESearchViewControllerDOUYINLiteAdapter;
- (void)updateSearchTheme;
- (void)updateSearchBarStyle;
- (void)updateVoiceSearchEntranceVisible;
- (void)accessibilityElementFocusedChanged:(id)a0;
- (void)configureVoiceSearch;
- (id)aAWESearchViewControllerDOUYINHTSAdapter;
- (void)showKeyboardWithFirstEnter;
- (void)showSearchMiddleViewControllerWithKeyword:(id)a0;
- (void)updateSearchThemeForSystemChange;
- (void)configSearchTopBarTheme:(unsigned long long)a0;
- (void)searchTopBarTextDidChange:(id)a0;
- (void)layoutSearchBar;
- (double)clearTextButtonRightMargin;
- (void)setupNewMiddlePageViewControllerWithType:(long long)a0;
- (void)searchTopBarDidEndEditing:(id)a0;
- (void)searchTopBarDidBeginEditing:(id)a0;
- (void)setupNewTopBarController;
- (void)setupOldSearchBarUI;
- (void)voiceSearchEntranceInitFailureTrackWithReason:(long long)a0;
- (void)updateClearTextButtonHiddenStatus;
- (void)searchWithKeyword:(id)a0 wordID:(id)a1 wordSessionID:(id)a2 fromSource:(unsigned long long)a3;
- (void)searchTopBarkeyboardSearchButtonClickedWithText:(id)a0;
- (void)returnButtonDidTap;
- (void)clearTextButtonDidTap;
- (void)searchBarTextDidBeginEditing:(id)a0;
- (void)searchBarTextDidEndEditing:(id)a0;
- (void).cxx_destruct;
- (void)searchBar:(id)a0 textDidChange:(id)a1;
- (long long)preferredStatusBarStyle;
- (void)keyboardWillShow:(id)a0;
- (id)init;
- (void)keyboardWillHide:(id)a0;
- (void)goBack;
- (void)searchBarSearchButtonClicked:(id)a0;
- (BOOL)gestureRecognizer:(id)a0 shouldReceiveTouch:(id)a1;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;
- (void)showKeyboardIfNeeded;
- (BOOL)searchBar:(id)a0 shouldChangeTextInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a1 replacementText:(id)a2;
- (void)keyboardDidShow:(id)a0;
- (void)setupUI;

@end
