@class NSTimer, NSString, AWEDoubleColumnSearchMerchandiseQueryModel, NSDictionary, AWESearchPOICitySelectionManager, AWESearchPOIHotelMultipleSelectionFilterView, AWESearchAIGCSummaryEntryView, AWESearchCachalotLynxPipeline, NSMapTable, NSMutableArray;
@protocol CachalotRenderPipelineComponentViewModel;

@interface AWESearchGroupBuyViewController : AWESearchLifeServiceBaseViewController <AWESearchDynamicPreLayoutProtocol, AWESearchGroupBuyViewControllerProtocol> {
    double _currentInsetBottom;
}

@property (retain, nonatomic) AWESearchCachalotLynxPipeline *lynxPipeline;
@property (retain, nonatomic) AWEDoubleColumnSearchMerchandiseQueryModel *queryModel;
@property (copy, nonatomic) NSDictionary *transEventExtra;
@property (retain, nonatomic) NSMapTable *fingerprintAndModelTable;
@property (retain, nonatomic) AWESearchPOICitySelectionManager *citySelectionManager;
@property (nonatomic) BOOL shouldAvoidRemoveFilterViewWhenFetchData;
@property (retain, nonatomic) AWESearchPOIHotelMultipleSelectionFilterView *hotelMultipleSelectionFilterView;
@property (nonatomic) BOOL isFromLifeHotelChannelSearch;
@property (nonatomic) BOOL isExecuteEmptyQuerySearch;
@property (retain, nonatomic) NSDictionary *mobParamsExtra;
@property (retain, nonatomic) NSDictionary *clientServerPassForOnce;
@property (nonatomic, getter=isPresentingCitySelect) BOOL presentingCitySelect;
@property (nonatomic) BOOL shouldForceDisplayLightModeUI;
@property (nonatomic) double quickFilterContentOffSetX;
@property (retain, nonatomic) id<CachalotRenderPipelineComponentViewModel> filterViewModel;
@property (copy, nonatomic) NSDictionary *commonOnceParams;
@property (copy, nonatomic) NSDictionary *commonAllTimeParams;
@property (retain, nonatomic) AWESearchAIGCSummaryEntryView *aigcSummaryEntryView;
@property (retain, nonatomic) NSTimer *aigcSummaryEntryTimer;
@property (nonatomic) double elapsedTime;
@property (nonatomic) double stayTime;
@property (nonatomic) BOOL isAIGCSummaryEntryTimerRunning;
@property (retain, nonatomic) NSMutableArray *patchAwemeModels;
@property (nonatomic) double reloadListStartTS;
@property (nonatomic) double reloadListEndTS;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)identifierForPreRequestWithRootTag:(id)a0;
+ (BOOL)enablePreRequestWithInitialParams:(id)a0;
+ (unsigned long long)newPreRequestType:(id)a0;
+ (BOOL)enableNewPreRequestWithInitialParams:(id)a0;
+ (BOOL)enableUseNewPreRequestTagWithSearchSource:(id)a0;
+ (id)verticalPreRequestManager;
+ (id)paramsProviders;
+ (BOOL)useParamsProvider;
+ (Class)paramsContextClass;
+ (BOOL)pullRefreshUseParamsProvider;
+ (BOOL)loadMoreUseParamsProvider;
+ (BOOL)switchParamsProvider;
+ (BOOL)pullRefreshSwitchParamsProvider;
+ (BOOL)loadMoreSwitchParamsProvider;
+ (Class)customDataControllerClass;
+ (void)preprocessModel:(id)a0;
+ (id)preFetchParamsContextWithRouterModel:(id)a0 extraLogParams:(id)a1;
+ (BOOL)searchGroupBuyCardSeparatorEnabled;
+ (BOOL)isSearchPOIResultLynxConcurrentSizeMeasureOptimizationEnabled;
+ (BOOL)searchGroupbuyConfigAddServiceEnable;
+ (BOOL)isGroupBuySeparateRenderIndividualOpen;
+ (BOOL)p_shouldUpdatePOIFilterHeight;

- (void)feedDidScroll:(id)a0;
- (id)hmdPageExtension;
- (void)fetchDataWithKeyWord:(id)a0 enterFrom:(id)a1 extraLogParams:(id)a2 isSearchByUserClick:(BOOL)a3 isFilterSearch:(BOOL)a4 animated:(BOOL)a5 completion:(id /* block */)a6;
- (void)customFeedRecieveRequestWithResponseParams:(id)a0 isLoadMore:(BOOL)a1;
- (void)customRefreshResponseCompletion:(id /* block */)a0 withParams:(id)a1;
- (void)customHandleNodeViewModelsReady:(id)a0 withResponseParams:(id)a1 isLoadmore:(BOOL)a2;
- (void)customComponentDidFinishRender:(id)a0 withViewModel:(id)a1;
- (void)handleRefreshResponseCompletion:(id /* block */)a0 withParams:(id)a1;
- (void)customComponentWillDisplay:(id)a0 withViewModel:(id)a1;
- (BOOL)enableNewPreRequestWithInitialParams:(id)a0 context:(id)a1;
- (unsigned long long)newPreRequestType:(id)a0 context:(id)a1;
- (id)refreshNewPreRequestParams:(id)a0 context:(id)a1;
- (BOOL)enablePreRequestWithInitialParams:(id)a0 context:(id)a1;
- (id)customBtmPageIdentifier;
- (id)customAutoplayRules;
- (id)paramsContext;
- (void)paramsContextDidReady:(id)a0;
- (void)chunkHandleClearResponse:(id /* block */)a0;
- (id)customContainerConfig;
- (id)customPageScrollFpsSceneName;
- (Class)customDataControllerClass;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })customContentInsets;
- (BOOL)customPageEnableAutoPlay;
- (id)customCachalotContext;
- (id)customEmptyViewSubTitle;
- (BOOL)customConcurrentChunkMachineProcess;
- (BOOL)customSyncAtMainThread;
- (BOOL)customUseSerialOperationMode;
- (BOOL)customEnableFullCasePreloadMore;
- (Class)customLoadmoreFooterClass;
- (BOOL)isLifeServiceSearch;
- (BOOL)isLifeVerticalSearch;
- (void)setupLifeServiceLogData:(id)a0;
- (id)getLifeServiceExtraLynxParams;
- (id)getSearchBarCapsules;
- (id)getGroupBuySearchRequestParams;
- (void)chunkHandleRecieveCardsPatchData:(id)a0;
- (void)chunkHandleReciverCardsPatchResponse:(id)a0;
- (void)customAddExtraParamsToTrackSearchEventWithBuilder:(id)a0;
- (unsigned long long)customStayTimeStatisticsTabType;
- (BOOL)needUpdateSearchBackgroundWhenAppear;
- (BOOL)enableVerticalTabBarViewPressPrequest;
- (id)currentVerticalKeyword;
- (void)updateFingerprintAndModelTableWithModel:(id)a0;
- (void)configAutoPlayHandler;
- (void)resetAigcSummaryEntryTimer:(id)a0;
- (void)startAigcSummaryEntryTimer;
- (void)pauseAigcSummaryEntryTimer;
- (void)aigcSummaryEntryViewSwitchToWeakStyleIfNeeded;
- (void)checkAwemeChunkDataWithRawData:(id)a0;
- (void)handleChunkModel:(id)a0 byAwemeModel:(id)a1;
- (void)showAIGCSummaryEntryViewIfNeeded;
- (void)aigcEntryViewClick;
- (void)updateAigcSummaryEntryTimer;
- (id)customSearchBackgroundCornerRadius;
- (BOOL)customEnableVerticalNewCommonSearchBackground;
- (void)updateSelfViewBackgroundColor;
- (void)handleSearchExpandCardWithLoadmoreNotification:(id)a0;
- (id)groupBuyDataController;
- (id)p_getTabConfig;
- (void)setServiceManagerToContainerConfig:(id)a0;
- (BOOL)p_syncAtMainThread17Config;
- (BOOL)p_syncAtMainThread16p4Config;
- (BOOL)p_syncAtMainThread13t16Config;
- (BOOL)p_syncAtMainThreadBelow13Config;
- (id)p_getSyncAtMainThreadConfig;
- (void)handleSearchExpandWithSearchResultID:(id)a0 nextPage:(id)a1 hasMore:(BOOL)a2 completion:(id /* block */)a3;
- (id)pendingDeleteViewModelWithSearchResultID:(id)a0;
- (void)handleRefreshReponseParams:(id)a0;
- (void)customFeedRecieveRequestWithResponseParamsServiceOnly:(id)a0 isLoadMore:(BOOL)a1;
- (void)customRefreshResponseCompletionServiceOnly:(id /* block */)a0 withParams:(id)a1;
- (void)prepareRequestDataWithKeyWord:(id)a0 extraLogParams:(id)a1 isFilterSearch:(BOOL)a2;
- (void)updateRequestParamsWithIsFilterSearch:(BOOL)a0;
- (void)fetchDataWithKeyWordServiceOnly:(id)a0 enterFrom:(id)a1 extraLogParams:(id)a2 isSearchByUserClick:(BOOL)a3 isFilterSearch:(BOOL)a4 animated:(BOOL)a5 completion:(id /* block */)a6;
- (BOOL)isVerticalSearch;
- (id)getGroupBuySearchIdentifier;
- (void)notifyGroupBuyFMPHasDone;
- (void)prepareRequestDataWithKeyWordServiceOnly:(id)a0 extraLogParams:(id)a1 isFilterSearch:(BOOL)a2;
- (BOOL)useNewLynxPipeline;
- (BOOL)shouldRefreshAfterDeliveryAddressUpdated;
- (BOOL)shouldForbidPOIAuthPopup;
- (void)configFooterWithParams:(id)a0;
- (void)handleCommonPatchData:(id)a0;
- (id)visibleCells;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (void)applicationDidEnterBackground;
- (void)viewWillAppear:(BOOL)a0;
- (void)viewDidLoad;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)a0;
- (void)viewWillDisappear:(BOOL)a0;

@end
