@class NSMutableDictionary, AWESearchVideoFeedTransitionContextProvider, AWEGeneralSearchModel, NSDictionary, AWESearchTracker, NSString, NSHashTable, UICollectionViewFlowLayout, AWEGeneralSearchScrollTailView, AWESearchAccessibleCollectionView, NSArray, AWESearchHorizontalAutoPlayCellController, AWEOriginalAdModel;
@protocol AWESearchHorizontalAutoPlayViewControllerDelegate, AWESearchHorizontalAutoPlayViewControllerVideoControlDelegate;

@interface AWESearchHorizontalAutoPlayViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, UIScrollViewDelegate, UICollectionViewDelegateFlowLayout, AWESearchEcommerceLiveAutoPlayCellContollerDelegate, AWESearchHorizontalAutoPlayCellControllerDelegate>

@property (retain, nonatomic) AWEGeneralSearchScrollTailView *footerView;
@property (nonatomic) struct CGPoint { double x; double y; } lastOffset;
@property (nonatomic) BOOL isTransfering;
@property (retain, nonatomic) NSMutableDictionary *registeredIdentifier;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } searchHorizontalAutoPlayActiveRegion;
@property (nonatomic) BOOL shouldPreventResign;
@property (nonatomic) BOOL isSingleMode;
@property (retain, nonatomic) NSHashTable *allocatedCells;
@property (retain, nonatomic) AWESearchHorizontalAutoPlayCellController *forcePlayCellController;
@property (weak, nonatomic) id<AWESearchHorizontalAutoPlayViewControllerDelegate> delegate;
@property (weak, nonatomic) id<AWESearchHorizontalAutoPlayViewControllerVideoControlDelegate> videoControlDelegate;
@property (retain, nonatomic) AWESearchTracker *searchTracker;
@property (retain, nonatomic) AWEGeneralSearchModel *searchModel;
@property (nonatomic) BOOL shouldActive;
@property (copy, nonatomic) id /* block */ didClickItemWithIndex;
@property (copy, nonatomic) id /* block */ didClickItemWithIndexAndLogExtra;
@property (copy, nonatomic) id /* block */ didScrollToViewMore;
@property (nonatomic) long long cellControllerType;
@property (copy, nonatomic) NSDictionary *logExtraDict;
@property (copy, nonatomic) NSString *referString;
@property (nonatomic) BOOL hasMore;
@property (retain, nonatomic) AWEOriginalAdModel *adModel;
@property (retain, nonatomic) AWESearchVideoFeedTransitionContextProvider *transitionContextProvider;
@property (copy, nonatomic) id /* block */ trackAwemePlayTime;
@property (retain, nonatomic) UICollectionViewFlowLayout *collectionViewLayout;
@property (retain, nonatomic) NSArray *videoArray;
@property (retain, nonatomic) AWESearchAccessibleCollectionView *collectionView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (BOOL)p_isValidIndexPath:(id)a0;
- (double)stepSpace;
- (void)updateWithVideoArray:(id)a0;
- (void)didEndShowing;
- (void)onEcommerceViewClickedWithIndex:(long long)a0 productId:(id)a1;
- (void)pauseButtonDidTapInHorizontalAutoPlayCellController:(id)a0;
- (void)playButtonDidTapInHorizontalAutoPlayCellController:(id)a0;
- (id)getVisibleCellControllerWithIndexPath:(id)a0;
- (BOOL)checkIfIsLiveCardWithIndex:(long long)a0 cellType:(long long)a1;
- (void)sendBackToOutFlowAtIndexPath:(id)a0;
- (Class)_cellControllerClassForCellControllerType:(long long)a0 model:(id)a1;
- (void)registerCellClassWithReuseIdentifier:(id)a0;
- (void)enterDetailPage:(id)a0 logExtra:(id)a1;
- (id)cellControllerWithCell:(id)a0 cellControllerClass:(Class)a1 andIndex:(long long)a2;
- (id)p_getAwemeModelAtIndex:(long long)a0;
- (BOOL)shouldStartTrack;
- (BOOL)checkIfIsEcommerceLiveCardWithIndex:(long long)a0 cellType:(long long)a1;
- (void)enterDetailPageWithIndex:(long long)a0 productID:(id)a1;
- (void)playCellController:(id)a0;
- (id)calculateIndexPathInStrongHotSpotWithOffset:(long long)a0;
- (void)transitionScrollToIndexPath:(id)a0;
- (id)getFirstCellController;
- (void)enterOtherPageDetailWithIndexPath:(id)a0;
- (double)collectionView:(id)a0 layout:(id)a1 minimumInteritemSpacingForSectionAtIndex:(long long)a2;
- (void)didBecomeActive;
- (double)collectionView:(id)a0 layout:(id)a1 minimumLineSpacingForSectionAtIndex:(long long)a2;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 referenceSizeForFooterInSection:(long long)a2;
- (struct CGSize { double x0; double x1; })_itemSize;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)a0;
- (void)pause;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 referenceSizeForHeaderInSection:(long long)a2;
- (void)collectionView:(id)a0 didEndDisplayingCell:(id)a1 forItemAtIndexPath:(id)a2;
- (struct CGSize { double x0; double x1; })collectionView:(id)a0 layout:(id)a1 sizeForItemAtIndexPath:(id)a2;
- (id)init;
- (id)collectionView:(id)a0 cellForItemAtIndexPath:(id)a1;
- (long long)collectionView:(id)a0 numberOfItemsInSection:(long long)a1;
- (void)scrollViewWillEndDragging:(id)a0 withVelocity:(struct CGPoint { double x0; double x1; })a1 targetContentOffset:(inout struct CGPoint { double x0; double x1; } *)a2;
- (long long)numberOfSectionsInCollectionView:(id)a0;
- (void)scrollToIndexPath:(id)a0;
- (void)collectionView:(id)a0 willDisplayCell:(id)a1 forItemAtIndexPath:(id)a2;
- (void)scrollViewDidScroll:(id)a0;
- (void)didResignActive;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)a0;
- (void)scrollViewDidEndDragging:(id)a0 willDecelerate:(BOOL)a1;
- (double)_itemSpacing;
- (double)_rightMargin;
- (void)setNeedsCalculateLayout;
- (double)_leftMargin;
- (void)autoPlay;

@end
